### PR TITLE
Revert "Update cloud spanner library to 0.29.0"

### PR DESCRIPTION
**Pull request by jkff**
Reverts apache/beam#4139

It doesn't compile with Gradle, but compiles with Maven. I don't know why - reverting until investigation.

R: @mairbek @lukecwik

### CODE REVIEW

**Comment by akedin** [comment]
Looking at it a bit closer I only see updates in `pom.xml`, but not `build.gradle`. I can try upgrading spanner in gradle later tonight to see if it fixes it

**Comment by jkff** [comment]
Oh. I didn't realize we used different sources of versions for these. I guess that makes for an easy fix but I don't have time to do it myself right now - so the current revert PR should still be performed. Thank you!

**Comment by akedin** [comment]
Submitted https://github.com/apache/beam/pull/4636 : tried it locally, it fixed the failing test for me. Didn't test thoroughly yet.

**Comment by jkff** [comment]
The failed gradle tasks seem unrelated: that PR modifies only google-cloud-platform and it passed, and tests passed locally (`./gradlew :sdks:java:io:google-cloud-platform:test`). Merging.

**Pull request merged**
