### PR TITLE
Upgrade GCP-BOM to 26.49.0

### PR DESCRIPTION
**Pull request by Abacn**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Many zetasql nexmark tests fails with

```
com.google.zetasql.io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.zetasql.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at com.google.zetasql.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at com.google.zetasql.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.google.zetasql.ZetaSqlLocalServiceGrpc$ZetaSqlLocalServiceBlockingStub.getLanguageOptions(ZetaSqlLocalServiceGrpc.java:1562)
...
Caused by: java.lang.UnsupportedOperationException
	at com.google.zetasql.io.grpc.netty.AbstractHttp2Headers.iterator(AbstractHttp2Headers.java:500)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:423)
```

due to netty_version bumped from "4.1.100.Final" to "4.1.110.Final", not compatible with zetasql "2022.04.1" shaded netty version 

Similar to https://github.com/grpc/grpc-java/issues/10707

**Comment by Abacn** [comment]
as of the latest version of zetasql-client: https://mvnrepository.com/artifact/com.google.zetasql/zetasql-client/2024.08.2

it still shades grpc-1.56.0 and io.netty 4.1.87.Final (last updated: 2023.08.1)

**Comment by Abacn** [comment]
```
testCommit_handlesFailedCommits (org.apache.beam.runners.dataflow.worker.windmill.client.commits.StreamingEngineWorkCommitterTest) failed


expected to contain: CompleteCommit{computationId=computationId-10, shardedKey=0000000000000002, workId=WorkId{cacheToken=1, workToken=10}, status=ABORTED}
but was            : [CompleteCommit{computationId=computationId-6, shardedKey=0000000000000002, ...
```

not related to this change. Same test passed the first attempt run (where other irrelevant test failed)

**Comment by Abacn** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
Thanks!

**Pull request merged**
