### PR TITLE
[BEAM-1351] Upgrade google-auto-value to 1.3

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Please add a comment describing the diffs to`mvn dependency:tree`. This will take some effort to simplify by hand so we can understand the effect.

**Comment by dhalperi** [comment]
What JIRA is this under? What's the rationale for this change?

**Comment by kennknowles** [comment]
BTW I mean to say "un-LGTM, we need to see the dep tree to consider impact of this"

Fully agree with @dhalperi that this would benefit from being tagged with the JIRA of whatever endeavor of @peihe is helped by this upgrade.

Thought I'd add some additional flavor since I've perused [their changelog](https://github.com/google/auto/blob/master/value/CHANGES.md). When weighing stability (via dep freeze) versus commonsense keeping up (to get bugfixes and features that haven't bitten us _yet_), I think the Beam community particularly benefits from the following, especially considering our recommendation to use AutoValue in contributed transforms.

> - The classes in the autovalue jar are now shaded with a $ so they never appear in IDE autocompletion.
> - AutoValue now uses its own implementation of a subset of Apache Velocity, so there will no longer be problems with interference between the Velocity that was bundled with AutoValue and other versions that might be present.
> - Explicit check for nested @AutoValue classes being private, or not being static. Otherwise the compiler errors could be hard to understand, especially in IDEs.
> - An Eclipse bug that could occasionally lead to exceptions in the IDE has been fixed (GitHub issue #200)
> - Added logic to AutoValue to detect the confusing case where you think you are using JavaBeans conventions (like getFoo()) but you aren't because at least one method isn't.

So you could reasonably file a JIRA with the title "AutoValue 1.1 -> 1.3 adds bugfixes and features that help us" with those bullets (or more) in the description, just so anyone curious dropping in would find the most interesting details.

**Comment by peihe** [comment]
PTAL

Filed:  https://issues.apache.org/jira/browse/BEAM-1351


Diff of dependency:
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided
1726c1761
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided
2280c2315
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided
2461c2496
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided
2656c2691
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided
2886c2921
< [INFO] +- com.google.auto.value:auto-value:jar:1.1:provided
---
> [INFO] +- com.google.auto.value:auto-value:jar:1.3:provided

**Comment by dhalperi** [comment]
Thanks Kenn for providing a much more useful and informative comment than I did. Thanks Pei for filing JIRA and posting a (great-looking) dep tree.

Since Kenn already LGTM'ed, I'll go ahead and merge.

**Pull request closed without merging**
