### PR TITLE
[BEAM-6110] For SQL CoGBK-based join use EARLIEST output timestamp

### PR DESCRIPTION
**Pull request by kennknowles**
As an implementation detail of some SQL (equi-)joins, we perform a CoGBK. The element timestamps from this are not super important, since the next GROUP BY will have windowing that explicitly says which column to treat as a timestamp. In other words, there is no need for a "timestamp combiner" to decide what the output timestamp is since it is explicit. But we do need the watermark to be held in an appropriate way. If we let it jump to the end of the window and that happens to be the global window, then any downstream windowing will be immediately droppable.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @reuvenlax 

Hoping for some thoughts on pitfalls here. I know that it holds up downstream stuff. We could conceivably have many choices based on characteristics of the join and inputs. But I think with no other intelligence this is the only safe default choice for SQL.

**Comment by kennknowles** [comment]
ping!

**Comment by kennknowles** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by kennknowles** [comment]
run java postcommit

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
all green

**Pull request merged**
