### PR TITLE
[BEAM-59] Move IOChannelUtils.constructName to FileBasedSink

### PR DESCRIPTION
**Pull request by dhalperi**
R: @peihe OR @reuvenlax OR @kennknowles

### CODE REVIEW

**Comment by dhalperi** [comment]
PreCommit running: https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10072/

**Comment by dhalperi** [comment]
CC: @vikkyrk

**Comment by dhalperi** [comment]
PreCommit passed other than Dataflow, which was broken separately by #2685 and #2683

**Comment by reuvenlax** [comment]
looks good to me

**Comment by dhalperi** [comment]
rerunning: https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10077

**Pull request closed without merging**
