### PR TITLE
Fix Wiki links and move prerequisites subsection.

### PR DESCRIPTION
**Pull request by tweise**
**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by tweise** [comment]
We really need to get link checking working again!

**Comment by kennknowles** [comment]
I didn't realize it was turned off.

**Comment by kennknowles** [comment]
I suspect this was the wiki page names changing after the test ran. We also hit similar sometimes with SEO when we lack forwarding pointers. Not sure the best approach when it comes to Confluence.

**Comment by tweise** [comment]
Yes, to do it properly we would need a periodic job.

**Comment by kennknowles** [comment]
I think we have it, actually. What we need is a good dashboard.

https://builds.apache.org/view/A-D/view/Beam/job/beam_PreCommit_Website_Cron/ (every 6 hours)
https://builds.apache.org/view/A-D/view/Beam/job/beam_PreCommit_Website_Merge/ (on each merge?)

I'm unfamiliar with these, though.

**Comment by swegner** [comment]
I believe that problem is that confluence doesn't return an HTTP error code when a page doesn't exist.

**Comment by tweise** [comment]
@swegner the invalid link produces a 404 status code. Would it be possible to tweak the link checker?

https://cwiki.apache.org/confluence/display/BEAM/Development+Environment+FAQ
https://cwiki.apache.org/confluence/display/BEAM/Contributor+FAQ

**Comment by swegner** [comment]
Thanks for pushing on this. Upon further investigation, it turns out link checking was completely broken. Here's a fix: https://github.com/apache/beam/pull/6947

**Pull request merged**
