### PR TITLE
[BEAM-5946] Upgrade google-apitools to 0.5.24

### PR DESCRIPTION
**Pull request by markflyhigh**
Upgrade google-apitools to latest version 0.5.24. which contains a important support for Python 3 incompatibility issue.

This upgrade helps to solve problem in BEAM-5788

@tvalentyn 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Dataflow Python ValidatesRunner

**Comment by tvalentyn** [comment]
Thanks, please also update: https://github.com/apache/beam/blob/master/sdks/python/container/base_image_requirements.txt#L48

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python Dataflow ValidatesContainer

**Comment by markflyhigh** [comment]
Run Python Dataflow ValidatesRunner

**Comment by markflyhigh** [comment]
+R: @aaltay @tvalentyn

**Comment by aaltay** [comment]
Do you need to more the lower bound?

**Comment by markflyhigh** [comment]
Good catch. I think we should. The change that we need for Python 3 compatible starts at 0.5.23. (introduced in [this commit](https://github.com/google/apitools/commit/4857df34a130e25a8af2b5af8d1a158a51da0f79#diff-57ee635115775567cf13d76cdcbe94cfR245)). So I think we can move lower bound to 0.5.23

**Comment by aaltay** [comment]
Sounds good. Please remember to update dataflow container files as well.

**Comment by markflyhigh** [comment]
I ping google-apitools to 0.5.24 in `sdks/python/container/base_image_requirements.txt`. That's all I need to do, right?

**Comment by aaltay** [comment]
Please also file a JIRA and link to this PR, that way it will show up in 2.9.0 release notes. (And also add 2.9.0 as the fix version.)

**Comment by markflyhigh** [comment]
@aaltay 

Done. Filed https://issues.apache.org/jira/browse/BEAM-5946.

**Pull request merged**
