### PR TITLE
[SQL] Make field names case-sensitive

### PR DESCRIPTION
**Pull request by akedin**
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by akedin** [comment]
R: @apilloud @XuMingmin @xumingming @kennknowles @amaliujia

**Comment by amaliujia** [comment]
LGTM

**Comment by akedin** [comment]
run java postcommit

**Comment by apilloud** [comment]
LGTM

**Comment by robertwb** [comment]
Is there a JIRA/discussion about this?

**Comment by apilloud** [comment]
This is a follow-up to #5325. The original change was discussed on the list. I think this bit got dropped in a rebase with the complex ddl work.

**Comment by kennknowles** [comment]
Yea, just a bug fix.

**Pull request merged**
