### PR TITLE
[Website] Update additional case studies

### PR DESCRIPTION
**Pull request by bullet03**
NB!!! Merge this PR first before https://github.com/apache/beam/pull/23899
- add hugo to the additional cards layout, so they could be clickable and lead to certain webpages
- add link to the akvelon logo description
- add optional property `hasLink ` to md logos  in frontmatter. If you need your logo to be a link on hover, add this property to your case-study. If you need card description to be shown on hover, skip this property
------------------------
before:
before_case
after:
after_with_cards
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pabloem, @aijamalnk, could you, kindly, help with review of PR?

**Comment by pabloem** [comment]
taking a look...

**Comment by pabloem** [comment]
I don't see the links appearing here: http://apache-beam-website-pull-requests.storage.googleapis.com/23555/case-studies/index.html

maybe it's because we've not added links yet?

**Comment by AKosolapov** [comment]
correct, this is to add hasLink parameter, actual links for logos haven't been part of this PR

**Comment by pabloem** [comment]
lgtm

**Pull request merged**
