### PR TITLE
Temporarily Ignore 2 FhirIO Integration Tests

### LINKED ISSUE #28635: [Failing Test]: Java_GCP_IO_Direct on Github Actions is very flaky due to OOMs when running FhirIOSearchIT tests
### What happened?

Looks like both `testFhirIOSearchWithGenericParameters` and `testFhirIOSearch` are failing due to OOM errors. Seeing these errors very frequently when running `Java_GCP_IO_Direct` on Github Actions but not so much for the Jenkins jobs.
Example runs: https://github.com/apache/beam/actions/runs/6281472530/job/17059883679?pr=28634, https://github.com/apache/beam/actions/runs/6278950376/job/17053724245?pr=28631
Not to say it doesn't happen on Jenkins ([see this failing test](https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Cron/1782/testReport/)), just not seeing it as much

Stacktrace dump for testFhirIOSearch:

```
com.google.gson.JsonParseException: Failed parsing JSON source: JsonReader at line 1 column 518561 path $[121].resource.item[1].adjudication[1].category.coding[0].code to Json
	at com.google.gson.JsonParser.parseReader(JsonParser.java:106)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:70)
	at com.google.gson.JsonParser.parseString(JsonParser.java:51)
	at org.apache.beam.sdk.io.gcp.healthcare.JsonArrayCoder.decode(JsonArrayCoder.java:46)
	at org.apache.beam.sdk.io.gcp.healthcare.JsonArrayCoder.decode(JsonArrayCoder.java:28)
	at org.apache.beam.sdk.coders.Coder.decode(Coder.java:154)
	at org.apache.beam.sdk.coders.KvCoder.decode(KvCoder.java:84)
	at org.apache.beam.sdk.coders.KvCoder.decode(KvCoder.java:37)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:142)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:102)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:96)
	at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:168)
	at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.verifyUnmodifiedThrowingCheckedExceptions(MutationDetectors.java:139)
	at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.verifyUnmodified(MutationDetectors.java:128)
	at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.verifyUnmodified(ImmutabilityEnforcementFactory.java:146)
	at org.apache.beam.runners.direct.ImmutabilityEnforcementFactory$ImmutabilityCheckingEnforcement.afterElement(ImmutabilityEnforcementFactory.java:131)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:175)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1014)
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:798)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:783)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725)
	at com.google.gson.internal.Streams.parse(Streams.java:49)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:102)
```

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by svetakvsundhar**
Temporarily disabling due to  #28635, https://github.com/apache/beam/issues/28505. 

Will enable once Jenkins to GHA migration is complete.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by svetakvsundhar** [comment]
retest this please

**Comment by svetakvsundhar** [comment]
r: @bvolpato 

I think it's worth disabling these for now, and then seeing what we have to work with once the migration is complete.

**Review by bvolpato — APPROVED** [review]

**Comment by bvolpato** [comment]
Thanks! Missed an import

```
/runner/_work/beam/beam/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIOSearchIT.java:159: error: cannot find symbol
  @Ignore("https://github.com/apache/beam/issues/28505")
   ^
  symbol:   class Ignore
  location: class FhirIOSearchIT

```

**Comment by svetakvsundhar** [comment]
yes, sorry, pushing in next commit

**Comment by svetakvsundhar** [comment]
R: @ahmedabu98

**Comment by svetakvsundhar** [comment]
Run Java_GCP_IO_Direct PreCommit

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
