### PR TITLE
Revert "Updates Python ExternalTransform to use the transform service when needed (#27228)"

### PR DESCRIPTION
**Pull request by bvolpato**
This reverts commit d545243b30d1192b76379659b2345fd349ec456d (https://github.com/apache/beam/pull/27228)

It is currently failing tests with:

```
ValueError: Cannot start an expansion service since neither Java nor Docker executables are available in the system.
```

For environments that were working completely fine. This validation was added by https://github.com/apache/beam/pull/27228 

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bvolpato** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
I think the failure is very specific to the way the failing test is run internally at Google (so not a widespread issue). Testing a fix.

**Comment by chamikaramj** [comment]
Sent https://github.com/apache/beam/pull/27345

**Comment by bvolpato** [comment]
Thanks @chamikaramj, closing this for now.

**Pull request closed without merging**
