### PR TITLE
[BEAM-6487] Updating BQ API

### PR DESCRIPTION
**Pull request by pabloem**
The BQ API is not up to date now. Adding the changes.
r: @chamikaramj

### CODE REVIEW

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Ugh py3 lint is complaining for something that has not even been changed..

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by pabloem** [comment]
rebased. Hoping this'll fix the lint issue.

**Comment by pabloem** [comment]
added lint exclusion for generated internal proto sources cc:@tvalentyn

**Pull request merged**
