### PR TITLE
Enable drain operation for flink jobs with requiresStableInput annotation

### PR DESCRIPTION
**Pull request by kkdoon**
Currently, drain operation does not work for flink pipelines when RequiresStableInput annotation is used. This is caused due to buffered data not being processed before the final checkpoint operation that causes watermark hold related exception. This PR addresses this issue by processing the buffer before the final checkpoint completes. More context in #28554. 

----
Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by kkdoon** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by kkdoon** [comment]
R: @mxm @je-ik 

Could you kindly help me review this PR. Thanks!

**Comment by je-ik** [comment]
I don't think we can just skip the check. The fact that the check fails implies there are still buffered data that have  not been processed yet. We need to either:
 a) correctly flush and process the buffered data (which will clear the hold), or
 b) ensure that checkpoint is called before the final watermark
 
I have a suspicion that correct is only b), because otherwise, in case of failure and restore from checkpoint after we flushed the data, we might break the stable input contract.

**Comment by kkdoon** [comment]
> I don't think we can just skip the check. The fact that the check fails implies there are still buffered data that have not been processed yet. We need to either: a) correctly flush and process the buffered data (which will clear the hold), or b) ensure that checkpoint is called before the final watermark
> 
> I have a suspicion that correct is only b), because otherwise, in case of failure and restore from checkpoint after we flushed the data, we might break the stable input contract.

I agree that option B is the cleanest and makes logical sense. I think in implementation terms it works if somehow [flushData](https://github.com/apache/beam/blob/79d0a8d11095522a036a6b3007f5fed4f6f46b3b/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L608) is invoked after last checkpoint finishes (or some other approach). Option A violates the requiresStableInput contract and hence seems incorrect (i did experiment with this approach as well and it gave the expected output when checkpoint successfully completed). 

Having said that, the current approach also works correctly when `requiresStableInput` is set since all the buffered data is emitted after checkpoint completes and the output watermark finally becomes equal to MAX_WATERMARK (i have run multiple jobs to verify the behavior). I can defer the `currentOutputWatermark < Long.MAX_VALUE` check for requiresStableInput scenario and do this check inside [notifyCheckpointComplete](https://github.com/apache/beam/blob/79d0a8d11095522a036a6b3007f5fed4f6f46b3b/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1045), at the time of job completion, to verify that output watermark is correct.

**Comment by je-ik** [comment]
> Having said that, the current approach also works correctly when `requiresStableInput` is set since all the buffered data is emitted after checkpoint completes and the output watermark finally becomes equal to MAX_WATERMARK (i have run multiple jobs to verify the behavior).

This seems to be the source of troubles. See my comment [here][1].

 [1]: https://github.com/apache/beam/issues/28554#issuecomment-1730987899

**Comment by kkdoon** [comment]
@je-ik i have updated the PR based on our discussion. Could you kindly check again?

**Comment by je-ik** [comment]
LGTM, thanks! Can you please update the title of the PR to match the implementation? We can merge it afterwards.

**Comment by je-ik** [comment]
Could you also please squash the commits? Thanks!

**Comment by kkdoon** [comment]
closing this PR since i botched up squashing the commits and created #29102 instead

**Pull request closed without merging**
