### PR TITLE
[BEAM-2015] Remove shared profile in runners/pom.xml and fix Dataflow ValidatesRunner PostCommit

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Diff'd effective poms to compare changes and find all inherited properties in sub runner modules.

I was limited by the seed job failing to make some other minor changes in clean-up.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @davorbonaci @dhalperi 
CC: @iemejia @tweise @amitsela

**Comment by dhalperi** [comment]
Run Dataflow ValidatesRunner

**Comment by dhalperi** [comment]
Run Spark ValidatesRunner

**Comment by dhalperi** [comment]
Run Apex ValidatesRunner

**Comment by dhalperi** [comment]
Run Flink ValidatesRunner

**Comment by dhalperi** [comment]
Run Direct ValidatesRunner

**Comment by dhalperi** [comment]
LGTM, please self-merge once green.

**Comment by dhalperi** [comment]
And thanks!

**Pull request closed without merging**
