### PR TITLE
Update GcsIO initialization to support converting input parameters to PipelineOptions for authentication

### LINKED ISSUE #23764: [Bug]: [Python] Dataflow jobs fail if GcsIO initializes credentials
### What happened?

https://github.com/apache/beam/pull/23644 (and a partial fix in https://github.com/apache/beam/pull/23677) breaks certain pipelines if gcsio.py initializes credentials first.

gcsio.py currently passes around dictionaries in certain situations instead of PipelineOptions types causing authentication to give up due to the following error:
```
Unable to find default credentials to use: 'dict' object has no attribute 'view_as'
Connecting anonymously.
```

This causes pipelines to fail with auth errors:
```
apitools.base.py.exceptions.HttpUnauthorizedError: HttpError accessing <https://www.googleapis.com/resumable/upload/storage/v1/b/cloud-ml-benchmark-output-us-central/o?alt=json&name=df2-cloudml-benchmark-reddit-small-python-presubmit6%2F10200737556536%2Ftemp%2Fdf2-cloudml-benchmark-reddit-small-python-presubmit6-10200737556536.1666276719.656090%2Fdax-tmp-2022-10-20_07_38_49-7887649702781606893-S27-0-4db7a63035854b2a%2Ftmp-4db7a630358540d1-shard--try-25d98cd94bb07d82-endshard.avro&uploadType=resumable>: response: <{'x-guploader-uploadid': 'ADPycdtyRy7Hq7selxzaj8sF3d21Wdd-BACcWNvpgZ7-Pu7RN1-3G-3UkY2YDcLGQgVQCo7Z-5tZQ7bDORmkMyHSF-gY5ZxUiodV', 'date': 'Thu, 20 Oct 2022 14:47:54 GMT', 'vary': 'Origin, X-Origin', 'www-authenticate': 'Bearer realm="https://accounts.google.com/"', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'pragma': 'no-cache', 'content-length': '438', 'server': 'UploadServer', 'content-type': 'text/html; charset=UTF-8', 'status': '401'}>, content <{
  "error": {
    "code": 401,
    "message": "Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object.",
    "errors": [
      {
        "message": "Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object.",
        "domain": "global",
        "reason": "required",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
```

### Issue Priority

Priority: 0

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by lukecwik**
fixes #23764

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @Abacn

**Comment by Abacn** [comment]
Run Python Examples_Dataflow

**Comment by lukecwik** [comment]
Run Python Examples_Dataflow

**Comment by Abacn** [comment]
LGTM, thanks! PostCommit Dataflow Example test passed.

**Pull request merged**
