### PR TITLE
Fix erroneous use of .expand() in KafkaIO

### PR DESCRIPTION
**Pull request by jkff**
R: @rangadi

### CODE REVIEW

**Comment by dhalperi** [comment]
Oy. Thanks!

**Comment by rangadi** [comment]
What is incorrect about it? I didn't handle KafkaIO port to Beam's expand() API, but it looks like Reader.expand() decides weather it would be bounded source or unbounded.

**Comment by jkff** [comment]
.apply() calls .expand() under the hood. Manually calling .expand() is always a bug because it bypasses a lot of important transform application machinery in the runner. See https://issues.apache.org/jira/browse/BEAM-438

**Comment by rangadi** [comment]
Thanks. LGTM.

**Pull request closed without merging**
