### PR TITLE
[Website] Update copy icon styles

### LINKED ISSUE #23064: [Bug]: in pre tag copy icon overlaps content on mobile resolutions
### What happened?

Steps:

1. Open the website page https://beam.apache.org/documentation/runners/spark/
2. Find the section Running on Dataproc cluster (YARN backed)
3. Scroll to Create a Dataproc cluster with Docker
4. Change the screen size to 428px x 680px
5. Take a look on the pre tag

Actual result: copy icon overlaps the text content
Expected result: copy icon doesn't overlap the text content
bofore_copy

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #23064
- update copy icon styles, change from float to position absolute 
- fix styles, so links get correct position in pre tag
------------------------
before:
before_copy
after:
after_copy
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
@pcoetm could you, please, help with review of PR?

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Review by pcoet — APPROVED** [review]
These changes to the global anchor seem right to me. I'm not sure why we'd want to have this:

```
float: right
margin-left: 12px
```

But please do some sanity testing to make sure there are no side effects. Thanks!

**Comment by bullet03** [comment]
There is a bug with copy icon moving with horizontal scroll. It it not a regress due to current PR, such behaviour was present before. Should be fixed in separate PR.
bug_copy_icon

**Comment by bullet03** [comment]
@aromanenko-dev, could you kindly help with merging? PR was tested and approved.

**Comment by aromanenko-dev** [comment]
@bullet03 I don't see it was approved, was it?
CC: @pcoet

**Comment by bullet03** [comment]
> @bullet03 I don't see it was approved, was it? CC: @pcoet

**Review by aromanenko-dev — APPROVED** [review]
Ok, I missed that. LGTM

**Comment by bullet03** [comment]
> Ok, I missed that. LGTM

Thank you!

**Pull request merged**
