### PR TITLE
[BEAM-2257] Ensure Kafka sink serializers are set.

### PR DESCRIPTION
**Pull request by rangadi**
Ensure that Kafka serializers are set.
Please merge this after #3969 is merged.

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Pull request closed without merging**
