### PR TITLE
[BEAM-2749] update BeamSqlExample

### PR DESCRIPTION
**Pull request by XuMingmin**
R: @takidau

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: + @xumingming

**Comment by xumingming** [comment]
Just out of curiosity, what's the reason that Tyler's previous try failed?

**Comment by XuMingmin** [comment]
I don't find the cause, possibly some libraries are broken. It may happens as DSL_SQL uses the same version as master, however the two branches are quite different so far.

**Comment by XuMingmin** [comment]
Glad to know that it works in your env now, `mvn clean install` seems a one-size-fits-all solution.

**Comment by takidau** [comment]
Merged, feel free to close. Thank you!

**Comment by XuMingmin** [comment]
close #3706, thank you @takidau @xumingming

**Pull request closed without merging**
