### PR TITLE
Use vendored grpc 1.54.0

### LINKED ISSUE #25746: Upgrade vendored grpc to eliminate vulnerability from protobuf-java 3.21.1
Hi team,

The protobuf-java version that we are currently using in below mentioned gradle has [security vulnerabilities](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.21.1), is there any plan to update it to latest protobuf-java version which has no vulnerabilities
https://github.com/apache/beam/blob/db8db0b6ed0fe1e4891f207f0f7f811798e54db1/buildSrc/src/main/groovy/org/apache/beam/gradle/GrpcVendoring_1_48_1.groovy#L41

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #25746

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by Abacn** [comment]
Run Python_Integration PreCommit

**Comment by Abacn** [comment]
All tests passed except those re-triggered, likely flaky unrelated. Ready for review for now.

Test passed not update status and no "Details" link:

Java_Spark3_Versions: https://ci-beam.apache.org/job/beam_PreCommit_Java_Spark3_Versions_Commit/1403/
PythonDocker: PythonDocker PreCommit: https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Commit/16221/
Spotless : https://ci-beam.apache.org/job/beam_PreCommit_Spotless_Commit/26450/

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by Abacn** [comment]
Run Python_Integration PreCommit

**Review by damccorm — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
Both triggered tests passed. Merging for now.

**Pull request merged**
