### PR TITLE
fix : kotlin warnings

### PR DESCRIPTION
**Pull request by harshithdwivedi**
@pabloem this PR should eliminate the warnings that started showing up in builds due to the addition of kotlin snippets.

P.S. @alexvanboxel this ought to make you happy! 😄

### CODE REVIEW

**Comment by alexvanboxel** [comment]
I think you need to rebase it against master, to make it not fail.

**Comment by alexvanboxel** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Sorry about the missed time. @harshithdwivedi are you able to rebase?

**Comment by alexvanboxel** [comment]
@harshithdwivedi can you please rebase against master? And make sure that tests are green. We can't merge into master without all tests ok.

**Comment by harshithdwivedi** [comment]
Hey Folks, sorry for my lack of activity on this issue.
I got caught up with work and nearly forgot about this. I'll send a commit to fix the failing tests this weekend.

**Comment by alexvanboxel** [comment]
Great, I'll follow up if finished. I can now merge into master.

**Comment by harshithdwivedi** [comment]
Ok, probably not the best way to go about it.
I'll open a new PR.

**Pull request closed without merging**
