### PR TITLE
[BEAM-3597] Add optional function registration to Go SDK runtime

### PR DESCRIPTION
**Pull request by herohde**
This change allows init-time insertion of functions into the resolver cache, thereby avoiding slow lookups into the binary symbol table. Added registration of SDK provided functions.

### CODE REVIEW

**Comment by herohde** [comment]
R: @lostluck @wcn3

**Comment by herohde** [comment]
retest this please

**Comment by herohde** [comment]
Thanks!

R: @kennknowles (please merge)

**Comment by kennknowles** [comment]
Cool. By the way I think switching the version to 2.4.0 on your branch will fix the redness.

**Pull request merged**
