### PR TITLE
[BEAM-8352] Add "withMaxCapacityPerShard()" to KinesisIO.Read

### PR DESCRIPTION
**Pull request by aromanenko-dev**
Added new configuration option `withMaxCapacityPerShard()` to `KinesisIO.Read` to provide a possibility to control the size of `ShardReadersPool.recordsQueue` in case if default value (10K records per shard) can cause NPE for topics with big amount of shards or large messages that can't fit into memory.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lukecwik** [comment]
Can't we instead use some other limit such as sum of queued message sizes to limit memory pressure?

**Comment by aromanenko-dev** [comment]
@lukecwik I think we **can** do this by adding a consumed messages size counter and checking this before putting new messages into queue. If total size is exceeded then we can stop and block fetching and adding new messages until the queue will be dequeued and there will be a free space for new records. 
In the same time, it will be a more complicated implementation comparing to what we have now and I don't see too much profit from it. Do I miss something?

**Comment by lukecwik** [comment]
Your right that you can provided an immediate solution right now and this is an acceptable change that will solve a real problem.

What I wanted to highlight about "tuning" flags in general is that:
1) Users need to know to set it to some value but what value can we suggest to them?
2) It doesn't work dynamically over time so that users need to choose a value that is very conservative.

**Comment by aromanenko-dev** [comment]
@lukecwik Yes, I agree that we need to reduce the number of tuning knobs to as less as possible and try to configure transforms automatically and dynamically if it's feasible.  But here is a question how we can estimate a maximum size in bytes in this case...

**Comment by lukecwik** [comment]
You can use the size of the KinesisRecords data field or you can assume each is the maximum size of 1MiB (https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Record.html).

**Comment by aromanenko-dev** [comment]
@lukecwik Regarding your questions:

1. Default value was (and stays) 10K records per shard and it worked well for topics with not large amount of shards per worker (we've got this issue only after 2 years of KinesisIO utilisation by different users). So, in general, we can conclude that user doesn't need to configure it manually and this option has to be used only in corner cases.

2. Yes, this is a field for improvement. Though, it's not very clear under which conditions user would need to be able change this option in the runtime dynamically.
> you can assume each is the maximum size of 1MiB
I mean the maximum size of available memory that can be allocated for this queue. Actually, it goes to more complicated question how effectively implement backpressure to have effectively working pair of consumer/producer in terms of consumed memory and total performance.

**Comment by lukecwik** [comment]
Yeah, the process needs to have a memory budget and every "largeish" thing should be accounted for. I have been thinking about how to best do this for the Java portability container since it would allow for removing several knobs that already exist.

**Comment by aromanenko-dev** [comment]
I agree that limitation based on payload size would be better, though it's still unclear how we can manage it dynamically.
1. Should be initial value based on process heap size as default value or configured by user? 
2. How much of free space we should leave unused to prevent NPE because of new arrived records (we don't know their size in advance)? 
3. Do we need to adapt the maximum queue size in runtime? 
4. If yes, what are the causes for that?

Btw, do you already have a solution for Java portability container problem? Either maybe we have something similar implemented for other IO?

**Comment by kennknowles** [comment]
This is associated with a bug marked release-blocking. Is that accurate? Is it important enough that we should go with an early approach and make improvements later? Maybe mark experimental/deprecate immediately if you know it will not last... or if it is not urgent to make 2.17.0 perhaps adjust the Jira.

**Comment by aromanenko-dev** [comment]
@kennknowles This one is definitively not a release blocker since it's not a regression and this bug can occur only under some load conditions. We haven't come to final solution for the moment (I raised several questions in above discussion) and final fix may affect user API. So I'd not merge this (even as experimental) until we decide how to proceed further.  For now, I just removed `Fix Version/s` in associated Jira. Sorry for noice.

**Comment by aromanenko-dev** [comment]
@lukecwik If we are agree on current solution (limit internal message queue by number of records) then I'm fine to merge it.

**Pull request merged**
