### PR TITLE
[BEAM-2152] Remove gcloud auth as application default credentials manages it

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

R: @aaltay PTAL

### CODE REVIEW

**Comment by sb2nov** [comment]
Run Python PostCommit

**Comment by aaltay** [comment]
LGTM. (Will wait for tests to merge)

cc: @lukecwik

**Comment by sb2nov** [comment]
Run Python PostCommit

**Comment by lukecwik** [comment]
Yeah, this looks like it has the same logic as Java now.

**Pull request closed without merging**
