### PR TITLE
[BEAM-3034] Utilize some java 5 features

### PR DESCRIPTION
**Pull request by wtanaka**
Was having trouble getting Jenkins tests to pass before in https://github.com/apache/beam/pull/3960 -- after rebasing and re-runing the analyzer in IntelliJ, this is what turns up.

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by wtanaka** [comment]
@iemejia

**Comment by iemejia** [comment]
Run Java Gradle PreCommit

**Comment by iemejia** [comment]
@wtanaka are there any other pending issues of this kind in the code base?

**Comment by wtanaka** [comment]
@iemejia I had run the intellij analyzer to make sure my local clone was using the gradle build properly and this was all that was found.  There are other warnings related to Java7 which this PR hasn't touched.

**Pull request merged**
