### PR TITLE
BEAM-1361: update Python build instructions

### PR DESCRIPTION
**Pull request by wikier**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

As described at [BEAM-1361](https://issues.apache.org/jira/browse/BEAM-1361).

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Just waiting end of the checks to merge.

**Comment by jbonofre** [comment]
Thanks Sergio !

**Comment by wikier** [comment]
yaw, @jbonofre!

**Comment by jbonofre** [comment]
The Travis failure is not related. I'm merging. Thanks again !

**Comment by dhalperi** [comment]
Nit: @wikier, in future can you please update PR title to include `[]` around `[BEAM-xxx]`? That is what makes the JIRA actually log this PR's state changes

**Comment by wikier** [comment]
Sorry @dhalperi, in other project we use the syntax `PROJ-XXX: ...` instead of `[PROJ-XXX] ...`. 
But I think the jirabot would link it as soon as the jira key appears in the title.

**Comment by dhalperi** [comment]
Maybe so! I guess I've just been wrong all along.

Maybe it's proj-XXX (lower-case) that it does not catch.

On Tue, Jan 31, 2017 at 11:39 PM, Sergio Fernández <notifications@github.com

**Comment by wikier** [comment]
Well, I was also curious, and I think it should work with just the jira issue key, does not matter how: https://git1-us-west.apache.org/repos/infra?p=asfgit-admin.git;a=blob;f=cgi-bin/github.cgi;h=3cf1e65d16a7e61fd5ca8b67d49974de54bf3663;hb=HEAD#l309

**Comment by dhalperi** [comment]
+1. Looks like it only recognizes capital letters: `([A-Z][A-Z0-9]+-\d+)` which is what I had noticed not working in the past, and mis-remembered :). Thanks for clearing it up!

**Pull request closed without merging**
