### PR TITLE
Do not fail when gen_protos cannot be imported

### PR DESCRIPTION
**Pull request by aaltay**
R: @robertwb

### CODE REVIEW

**Comment by robertwb** [comment]
When would we expect this to happen?

**Comment by aaltay** [comment]
It happens, if the sdk is packaged without the egg_info. In that case pip install, triggers `python setup.py egg_info`. Even though this cmd does not requires protos, it fails because packaged SDK does not contain the gen_protos.py.

**Comment by robertwb** [comment]
How about in that case wrapping the commands with classes that raise an error? This way we never silently fail to generate the protos when we need them.

**Comment by robertwb** [comment]
Alternatively, move the import into the run method.

**Comment by aaltay** [comment]
Would not it be the same problem, if we move the import into the run method? Then it will fail when run is called.

**Comment by robertwb** [comment]
But in that case it would only fail for the commands that require the
generated protos. egg_info would be just fine.

**Comment by aaltay** [comment]
@robertwb Maybe I am missing something, but moving the import into the run method fails the same way. Because egg_info, triggers running of build_py. (That was the reason for original failure, egg_info did indeed caused a call to generate_protos_first and that returns a wrapped cmd.)

**Comment by robertwb** [comment]
Ah, I wasn't aware that egg_info called build_py. 

LGTM.

**Comment by aaltay** [comment]
Thank you, merging.

**Pull request closed without merging**
