### PR TITLE
[BEAM-6518] fix python metric-querying bug

### PR DESCRIPTION
**Pull request by ryan-williams**
Fixing a minor edge-case.

R: @mxm 
CC: @ajamato 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Could you please give a quick example of why this needs to be fixed?

**Comment by ajamato** [comment]
LGTM after mxm's comments.

**Comment by ryan-williams** [comment]
[This test I added](https://github.com/apache/beam/pull/7638/files#diff-520d5662bc2c53338f2f2b497e9b14e1R79) shows an example of a step-name where the old code would have a false negative (i.e. would omit a metric in response to a query that should have returned it); paraphrasing:

```
name = MetricName('ns1', 'name1')
key = MetricKey('Step10/Step1', name)
filter = MetricsFilter().with_step('Step1')
MetricResults.matches(filter, key)  # previously False, now True (which is correct/intended)
```

This previously would have failed because:
- the `Step1` in `Step10` would be found as a potential match for `Step1`
- it would be ruled out due to not being an exact match
- algorithm would incorrectly `return False`, missing the actual `Step1` which comes later

Most likely no one has ever hit this in production. However, to me it is a clear-cut bug-fix. `MetricResults._matches_sub_path` is not supposed to have this edge-case.

In fact, talking it through here, it was unnecessarily complicated as a result of being based on `str.find()` and then retroactively checking against `/`-delimiters. I've rewritten it to more directly do what it is supposed to: split on `/`s and see if the "filter" is a sub-list of the "actual" `MetricKey`'s "step".

I also removed some redundant lines (re-assigning the same values to the same vars) from the tests.

lmk what you think!

**Comment by mxm** [comment]
Makes sense. Thanks for clarifying!

**Pull request merged**
