### PR TITLE
[BEAM-1622] Port Java modules from RunnableOnService to ValidatesRunner

### PR DESCRIPTION
**Pull request by kennknowles**
Python is already using ValidatesRunner, as per dev list consensus.

A deprecated RunnableOnService is left in place as a superclass so anything
remaining that scrapes for it can be ported gradually.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
Run Flink RunnableOnService

**Comment by kennknowles** [comment]
R: @davorbonaci

This should wait until after the release, so that we don't do anything that could cause testing problems.

**Comment by davorbonaci** [comment]
@kennknowles, can you please rebase?

LGTM on the rename from RunnableOnService to ValidatesRunner, but can you perhaps go further and get rid of it completely:
* Update the rest, so the old annotation can be removed completely (not deprecated)
* Update website / documentation
AFAIK, it can be a simple `sed`, right?

**Comment by kennknowles** [comment]
I will attempt a complete removal right now as well. Since it doesn't slow anything down to checkpoint halfway through the process, I'll merge if I see green along the way if it does not create an inconsistent state.

**Comment by kennknowles** [comment]
OK, here is what I have done:

 - Rebased to resolve conflicts and fix some later-added `RunnableOnService` tests.
 - Removed `RunnableOnService`
 - Made the poms do the right scan for the category

I have not:

 - Renamed any of the profiles or test executions in the poms
 - Modified the Jenkins job names or invocations

These will require some seed job hackery and I think will be easier to do next.

**Comment by kennknowles** [comment]
Run Flink RunnableOnService

**Comment by kennknowles** [comment]
Separately I will follow up with the website.

**Comment by kennknowles** [comment]
Run Spark RunnableOnService

**Comment by kennknowles** [comment]
Run Apex RunnableOnService

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Both failures are known breakages prior to this PR.

**Comment by kennknowles** [comment]
Rebased, which should fix one, but planning on going ahead, since the desired tests are running.

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Run Apex RunnableOnService

**Comment by kennknowles** [comment]
Run Flink RunnableOnService

**Comment by kennknowles** [comment]
Run Spark RunnableOnService

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
Looks like there might be a problem pulling the repo onto a fresh Jenkins worker. Unrelated to this PR. At this point we've gotten a lot of good feedback on this PR.

**Pull request merged**
