### PR TITLE
[BEAM-2530] Fix compilation of modules with Java 9 that depend on jdk-tools

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @jbonofre

**Comment by iemejia** [comment]
For ref, after applying this patch I can build the full project by skipping some things with maven 3.5 and JDK 9+175.
```
mvn -Dcompiler.error.flag="" -Denforcer.skip=true clean compile test-compile
```

**Comment by iemejia** [comment]
The other issues with the enforcer plugin and autovalue need to addressed on upstream I think first.

**Comment by jbonofre** [comment]
Thanks, let me take a look.

**Pull request closed without merging**
