### PR TITLE
bump go version to 1.20.4

### PR DESCRIPTION
**Pull request by jamesfricker**
Go 1.20.2 contains vulnerabilities, update the version to the latest, 1.20.4.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
@jamesfricker As I said last time for your other PR, this doesn't do what you think it does. https://github.com/apache/beam/pull/26368#issuecomment-1518110203


The `go` directive in a go.mod specifies the minimum version of Go with which the code in the module can be built with. So it says that The Go beam SDK doesn't rely on language features or features of the standard library that were added after 1.19.

So unless there's a paired change to make use of features introduced in the 1.20 release, there's no real value in changing this.

It also doesn't prevent users from using newer versions of Go (including the patched security releases).

Further, the `go` directive only indicates Major.Minor and doesn't specify Patch. To-wit: As specified, this cases a build failure, caught by our build system (and would have been caught if it had been built locally too)

```
go: errors parsing go.mod:
/home/runner/work/beam/beam/sdks/go.mod:23: invalid go version '1.20.3': must match format 1.23
Error: Process completed with exit code 1.
```

The Go Module reference is quite readable, and explains the `go` directive in detail here: 
https://go.dev/ref/mod#go-mod-file-go

----

That said, to update the Beam's Infra to use the latest patch, that kind of PR looks like this https://github.com/apache/beam/pull/26054 though for a patch update, only the BeamModulePlugin.groovy and sdks/go/run_with_go_version.sh files would need changes to ensure the latest patch is used. This only affects releases, when they build the boot loader scripts.

**Comment by jrmccluskey** [comment]
Which vulnerabilities batched between 1.20.2 and 1.20.4 do you think are relevant to the bootloader code?

**Comment by lostluck** [comment]
Sorry for the hasty initial reply (since deleted). When I see repeated PRs from the same person without any other comments, I assume SPAM. Remember, open source is community over code, and that requires interaction on both sides.

This is much better! Thank you.

I'll note that as this only affects the container image bootloader, which has limited interactions, and dependencies the likely hood of any of the patched CVEs being a relevant attack surface are minimal.

https://go.dev/doc/devel/release#go1.20.minor

A more interesting fix than one-off manual upgrades though, would be looking into simply automating the patch version upgrades for these last two bits of manual configuration, so a PR isn't needed all the time for the patch revisions.

**Review by lostluck — APPROVED** [review]
Thank you for this second attempt!

**Pull request merged**
