### PR TITLE
[BEAM-1693] Detect supported Python & pip executables in Python-SDK

### PR DESCRIPTION
**Pull request by tibkiss**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tibkiss** [comment]
R: @aaltay

**Comment by tibkiss** [comment]
R: @jasonkuster for his maven expertise

**Comment by aaltay** [comment]
Thank you @tibkiss. I will defer to @jasonkuster for the review. 

I have some questions from usability perspective. Have you had a chance to run this over a matrix of OSes? Do you foresee any compatibility issues?

**Comment by tibkiss** [comment]
@aaltay : I did test the change on RHEL7, Debian 9 and OS X. Let me know if you would like to have greater OS coverage.

**Comment by tibkiss** [comment]
@jasonkuster : Thanks for the review, I moved the version to the top level pom as requested.

**Comment by tibkiss** [comment]
One thing I was wondering of: there are numerous build related files (run_*.sh, generate_pydoc.sh and most recently findSupportedPython.groovy) are located now in Python-SDK's root. Shall we consider moving those files to a designated (build_utils) directory?

**Comment by aaltay** [comment]
@tibkiss It is a good idea to move build specific things to a folder.

**Comment by tibkiss** [comment]
Thanks @aaltay, will create a separate jira to move the build tools into a dedicated dir.

**Comment by aaltay** [comment]
@tibkiss I missed the OS comment in between other comments. I think we should test it on Windows if possible.

**Comment by tibkiss** [comment]
I validated on a Windows Server 2012 machine, the maven modification and the groovy script is working: 
`[INFO] --- groovy-maven-plugin:2.0:execute (find-supported-python-for-compile) @ beam-sdks-python ---
[INFO] Using python interpreter binary 'python' with pip 'pip2'
[INFO] `

I need to mention though, that my results are somewhat strange: pip2 was found even though I have pip2.7 in my path. For some the execution of pip2.7 is unsuccessful:
`
c:\dev\beam\sdks\python>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
owsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft Windows
Performance Toolkit\;C:\Program Files (x86)\CMake\bin;c:\dev\apache-maven-3.3.9\
bin;c:\dev\protobuf-2.5.0\;c:\Progra~1\Git\usr\bin;C:\dev\apache-ant-1.7.1\bin;C
:\hdp\hadoop-dist\target\hadoop-2.7.1-SNAPSHOT\bin;C:\Python27\;C:\Python27\scri
pts

c:\dev\beam\sdks\python>pip2.7 --version
pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)

c:\dev\beam\sdks\python>\dev\groovy-2.4.10\bin\groovysh
Groovy Shell (2.4.10, JVM: 1.7.0_79)
Type ':help' or ':h' for help.
-------------------------------------------------------------------------------
groovy:000> def foo = "pip2.7 --version".execute()
ERROR java.io.IOException:
Cannot run program "pip2.7": CreateProcess error=2, The system cannot find the f
ile specified
groovy:000> def bar = "pip2 --version".execute()
===> java.lang.ProcessImpl@22fe404a
groovy:000>
`

As I do have the same problem with tox, I don't think it is related to the PR:
`
[INFO] --- exec-maven-plugin:1.5.0:exec (setuptools-test) @ beam-sdks-python ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "c:\dev\beam\sdks\python\target\python\bin\tox" (in directory "c:\dev\beam\sdks\python"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
`

**Comment by aaltay** [comment]
@tibkiss I do not fully understand the issue. Do you know what is causing it? `tox` should have any `java` errors in it, so I am a bit confused about that part as well.

**Comment by tibkiss** [comment]
@aaltay : Sorry for not being clear at the first place.

The problem / weirdness in my system is that java apps (including groovy scripts) are not always able to start executables present on the path. 
In particular: I have both pip2.7 and pip2 in my path, I can start both from a cmd.exe from any directory, but from groovy only pip2 is found.

Taking a second look on Tox's problem I realized that it is a different issue:
The build script tries to execute Tox from 'target\python\bin\tox', but in my system it is located under 'target\python\Scripts\tox'. Sorry about the confusion here.

I believe this problem is unrelated to the change I made in my PR as 'master' branch behaves exactly the same. 

Feel free to ping me in slack if you have further questions. Thanks!

**Comment by aaltay** [comment]
Thank you. Yes the `tox` problem you described is unrelated. As long as it manages to find a python 2 implementation, that is good.

LGTM. @jasonkuster do you have additional comments on this?

**Comment by tibkiss** [comment]
Figured out what is the problem with execution of 'pip2.7' under windows: For some reason the dot confuses windows and it will not start the binary. If I try to start 'pip2.7.exe' then it works. Eh.

If you agree I'll extend the groovy script by adding .exe suffix to the pip and python candidates in case of Windows builds.

**Comment by aaltay** [comment]
@tibkiss This is fine for me. Do you see any problems with this? Would this only be Windows specific?

@jasonkuster any concerns?

**Comment by tibkiss** [comment]
@aaltay : I don't see any problems other than being ugly to make exceptions for Windows. However I'm not a Windows person, that's why I'm asking for your guidance :)

**Comment by aaltay** [comment]
I am fine with ugly exceptions, as long as it only affects Windows, works correctly and has a comment explaining why :)

**Comment by jasonkuster** [comment]
Yeah, overall LGTM. Agreed with Ahmet about ugly expectations, fine as long as there's a comment. :) One thing to note though -- Maven has the ability to autodetect OS and we're doing that here -- it's possible we could only activate those options if we detect we're running on Windows. Thoughts? This has been in PR for a while and I think it'd be great to get in so if this is going to be a lot more work I'd bias towards just the comment and submit, but I figured it was worth mentioning.

**Comment by tibkiss** [comment]
Thanks for your comments. Sorry for not bringing this to completion yet (haven't felt good lately).

OS (or Windows) detection is not a big deal in Groovy, it can be done in one line:
`System.properties['os.name'].toLowerCase(Locale.ROOT).contains('windows')`

If there is no objection I'd put this into the groovy script to have everything centralized there.
Will deliver this improvement today for review.

Thanks!

**Comment by jasonkuster** [comment]
Awesome, sounds good!

**Comment by jasonkuster** [comment]
Also, please don't interpret my comment above as impatience -- I haven't been super snappy about reviewing, which has slowed the process down. :) Hope you feel better soon.

**Comment by tibkiss** [comment]
@jasonkuster : no offense was taken :) 
PTAL on the updated PR, it includes the windows specific part.

Tested successfully on Windows Server 2012, CentOS7 & OS X.

**Comment by tibkiss** [comment]
Oh, you are fast :)

**Pull request closed without merging**
