### PR TITLE
Manually specify streaming flag for SDF DirectRunner tests

### PR DESCRIPTION
**Pull request by charlesccychen**
R: @chamikaramj

### CODE REVIEW

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by charlesccychen** [comment]
Can you please merge?

CC: @robertwb (this blocks direct / fnapi runner migration)

**Comment by robertwb** [comment]
One should not have to specify streaming mode to use SDFs. We should instead inspect if there are any SDFs before using the Fn Api Runner (until SDFs are supported over the Fn Api Runner of course).

**Comment by charlesccychen** [comment]
I chatted with Robert--we should not hard-code `--is_streaming`, since we should support SDFs in batch mode as well.  Accordingly, I am closing this PR.

**Pull request closed without merging**
