### PR TITLE
Add MetricsContainer support to the Flink sources.

### LINKED ISSUE #25741: [Task]: Add MetricsContainer support in the FLIP-27 sources in Flink runner.
### What needs to happen?

As a part of #25525. The old MetricsContainer metrics for the Source are removed for Flink streaming jobs and replaced by the metrics specified in [FLIP-33](https://cwiki.apache.org/confluence/display/FLINK/FLIP-33%3A+Standardize+Connector+Metrics).

It is probably worth keeping the old metrics for backwards compatibility. This task should add the metrics that are currently emitted by the `UnboundedSourceWrapper` to the newly introduced `FlinkSource`.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by becketqin**
This patch is a follow-up patch for the Flink runner migration from DataSet API to DataStream API. It adds support for MetricsContainer which exposes the metrics defined in Beam metrics via the Flink metric framework.

fixes #25741 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by becketqin** [comment]
@xinyuiscool Would you help take a look? Thanks!

**Comment by tvalentyn** [comment]
@becketqin are you still interested in submitting this change? I'd recommend reaching out on @dev and ask folks who are familiar with FlinkRunner codebase to help take a look.

**Comment by jto** [comment]
Hey there! 
Can someone take at look at this PR and https://github.com/apache/beam/pull/25742 ? 
Looks like everything is in place for Beam use `DataStream` in place of the deprecated `DataSet` API.
Maybe @xinyuiscool since you reviewed and merged https://github.com/apache/beam/pull/25525 :)

**Comment by tvalentyn** [comment]
hey @jto, thanks for reaching out. unfortunately I haven't heard from the original author - if you or someone else can take over the PRs, it might be a path to get the change unblocked. In addition to an author, we will need a reviewer who is familiar with the codebase or is willing to dig in to take more ownership in the flink runner codebase. You could also be a reviewer, then, we will need a committer for the merge but I this point I think we are looking for review to complete. reaching out to dev@ may be an avenue to get help.

**Comment by jto** [comment]
Hey @tvalentyn ! Thanks for your reply. I think either one of my colleague or myself will take over those two PRs :)

**Comment by tvalentyn** [comment]
Thanks, @jto, let's continue in https://github.com/apache/beam/pull/28609

**Pull request closed without merging**
