### PR TITLE
[BEAM-10848] Initialize gauge to 0

### PR DESCRIPTION
**Pull request by mravi**
The PR addresses the encoding issue of Gauges by initializing them with 0.

### CODE REVIEW

**Review by robertwb — APPROVED** [review]

**Comment by mravi** [comment]
Run Python PreCommit

**Comment by mravi** [comment]
Run PythonFormatter PreCommit

**Comment by mravi** [comment]
Run Python PreCommit

**Comment by mravi** [comment]
@robertwb Thanks for applying the lint fix and approving the PR.  

Apparently, I see a the task failure from running [py37-cloud](https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2233/console) which seems to occur on other PR's also https://ci-beam.apache.org/job/beam_PreCommit_Python_Commit/15498/console.  Can you please suggest the next steps ?

**Review by mxm — APPROVED** [review]

**Comment by mxm** [comment]
It doesn't fail anymore and the failure in https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2233/ is unrelated.

Thank you @mravi!

**Comment by mxm** [comment]
@mravi Could you squash the commits?

**Comment by mxm** [comment]
Good to see that GitHub's squash feature now preserves authorship. This was not the case for a long time (the author of the resulting commit would be the merger and not the original author before squashing).

**Pull request merged**
