### PR TITLE
Fixed wrong isRelease() call in publish

### PR DESCRIPTION
**Pull request by boyuanzz**
isRelease() call should be isRelease(project)

r: @pabloem 
cc: @aaltay @lukecwik

### CODE REVIEW

**Comment by holdensmagicalunicorn** [comment]
@boyuanzz, thanks! I am a bot who has found some folks who might be able to help with the review:@kennknowles, @lukecwik and @garrettjonesgoogle

**Comment by pabloem** [comment]
This LGTM. Thanks Boyuan. This should be tested on the next release.

**Comment by pabloem** [comment]
Run Gradle Publish

**Comment by boyuanzz** [comment]
Jenkins failed because of 
* What went wrong:
Execution failed for task ':beam-sdks-java-nexmark:test'.

**Comment by pabloem** [comment]
Run Gradle Publish

**Comment by boyuanzz** [comment]
publish build failed because of timeout

**Comment by pabloem** [comment]
discussed offline. Merging now.

**Pull request merged**
