### PR TITLE
Cherry pick #8234 to release 2.12.0

### PR DESCRIPTION
**Pull request by iemejia**
This should stabilize the tests now.
Thanks a lot @echauchot for doing quickly this fix.

R: @apilloud @kennknowles 
CC: @echauchot @aromanenko-dev

### CODE REVIEW

**Comment by kennknowles** [comment]
run rat precommit
run javaportabilityapi precommit

**Comment by kennknowles** [comment]
run rat precommit

**Comment by kennknowles** [comment]
Run JavaPortabilityApi PreCommit

**Comment by apilloud** [comment]
LGTM.

**Pull request merged**
