### PR TITLE
[BEAM-5086] Update kudu-client to version 1.11.1

### PR DESCRIPTION
**Pull request by iemejia**
Catching up with kudu-client improvements
R: @timrobertson100 @aromanenko-dev

### CODE REVIEW

**Comment by iemejia** [comment]
@aromanenko-dev  can you take a look at this one too since Tim apparently is not available.

**Comment by lukecwik** [comment]
Verify upgrade compatibility using [linkage checker](https://github.com/apache/beam/blob/04498d56f9bc17528d807c6ef02434eed29decf1/build.gradle#L290)?

**Comment by lukecwik** [comment]
Linkage checker complained of a bunch of things but I filtered it down to the ones that seemed pertinent:
```
Class javax.servlet.ServletOutputStream is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class javax.servlet.http.HttpServlet is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class javax.servlet.ServletException is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class javax.servlet.ServletConfig is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class javax.servlet.http.HttpServletRequest is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class javax.servlet.http.HttpServletResponse is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.channel.socket.http.HttpTunnelingServlet (kudu-client-1.11.1.jar)
Class org.jboss.marshalling.ByteInput is not found;
  referenced by 4 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ChannelBufferByteInput (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.LimitingByteInput (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ChannelBufferByteInput (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.LimitingByteInput (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.jboss.marshalling.ByteOutput is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ChannelBufferByteOutput (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ChannelBufferByteOutput (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.jboss.marshalling.Unmarshaller is not found;
  referenced by 8 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.CompatibleMarshallingDecoder (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ContextBoundUnmarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.MarshallingDecoder (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ThreadLocalUnmarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.MarshallingDecoder (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.CompatibleMarshallingDecoder (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ThreadLocalUnmarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ContextBoundUnmarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.jboss.marshalling.Marshaller is not found;
  referenced by 6 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.CompatibleMarshallingEncoder (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.MarshallingEncoder (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ThreadLocalMarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.CompatibleMarshallingEncoder (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.MarshallingEncoder (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ThreadLocalMarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.jboss.marshalling.MarshallerFactory is not found;
  referenced by 8 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.DefaultMarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.DefaultUnmarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ThreadLocalMarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.codec.marshalling.ThreadLocalUnmarshallerProvider (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.DefaultUnmarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.DefaultMarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ThreadLocalMarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.codec.marshalling.ThreadLocalUnmarshallerProvider (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.eclipse.jetty.npn.NextProtoNego$ServerProvider is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.JettyNpnSslEngine (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.JettyNpnSslEngine (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.eclipse.jetty.npn.NextProtoNego$ClientProvider is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.JettyNpnSslEngine (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.JettyNpnSslEngine (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.eclipse.jetty.npn.NextProtoNego is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.JettyNpnSslEngine (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.JettyNpnSslEngine (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.apache.tomcat.jni.SSL is not found;
  referenced by 3 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSsl (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslEngine (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslServerContext (kudu-client-1.11.1.jar)
Class org.apache.tomcat.jni.Library is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSsl (kudu-client-1.11.1.jar)
Class org.apache.tomcat.jni.Buffer is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslEngine (kudu-client-1.11.1.jar)
Class org.apache.tomcat.jni.Pool is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslServerContext (kudu-client-1.11.1.jar)
Class org.apache.tomcat.jni.SSLContext is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslServerContext (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.OpenSslSessionStats (kudu-client-1.11.1.jar)
Class org.bouncycastle.asn1.x500.X500Name is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.bouncycastle.operator.jcajce.JcaContentSignerBuilder is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.bouncycastle.cert.X509v3CertificateBuilder is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.bouncycastle.cert.jcajce.JcaX509CertificateConverter is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.bouncycastle.jce.provider.BouncyCastleProvider is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.apache.kudu.shaded.org.apache.commons.logging.Log is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.logging.CommonsLogger (kudu-client-1.11.1.jar)
Class org.apache.kudu.shaded.org.apache.commons.logging.LogFactory is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.logging.CommonsLoggerFactory (kudu-client-1.11.1.jar)
Class org.jboss.logging.Logger is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.logging.JBossLogger (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.logging.JBossLoggerFactory (kudu-client-1.11.1.jar)
Class org.apache.log4j.Logger is not found;
  referenced by 3 class files
    org.apache.kudu.shaded.org.jboss.netty.logging.Log4JLogger (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.logging.Log4JLoggerFactory (kudu-client-1.11.1.jar)
    org.apache.beam.vendor.grpc.v1p21p0.io.netty.util.internal.logging.Log4JLoggerFactory (beam-vendor-grpc-1_21_0-0.1.jar)
Class org.osgi.service.log.LogService is not found;
  referenced by 2 class files
    org.apache.kudu.shaded.org.jboss.netty.logging.OsgiLogger (kudu-client-1.11.1.jar)
    org.apache.kudu.shaded.org.jboss.netty.logging.OsgiLoggerFactory (kudu-client-1.11.1.jar)
Class org.osgi.util.tracker.ServiceTracker is not found;
  referenced by 1 class file
    org.apache.kudu.shaded.org.jboss.netty.logging.OsgiLoggerFactory (kudu-client-1.11.1.jar)
```

Rerun with:
```
./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-kudu :checkJavaLinkage
```

**Comment by iemejia** [comment]
Yes I did, these results are pretty much equivalent to the previous version 1.9. So functionally this is not a regression. Filled https://issues.apache.org/jira/browse/KUDU-3041 so upstream Kudu takes care of it.

**Comment by aromanenko-dev** [comment]
So, if there are no regressions according to linkage checker, can we merge it "as it is"? Any objections, @lukecwik ?

**Comment by lukecwik** [comment]
If the linkage issues are with the client, it would be good to explicitly resolve them since upgrades may cause issues even if no new errors are being reported since the new version may use different code paths.

In the end its a judgement call always when errors are still being reported that can be done based upon the number of unit/integration/manual testing that has been performed vs how popular something is and how many people might be broken by the change.

**Comment by iemejia** [comment]
I agree with you in the sense that this is a question of judgment, but I don’t think we should assume any extreme position in particular for dependencies that ‘are working’. Of course it is clear that the goal is that Beam users have a experience with no issues and we should fix linkage issues that impede the use of such libraries on Beam for example if we cannot read Data from Kudu because some of those linkage errors.

Taking the responsibility of fixing every linkage issue that is not related to Beam is a considerable amount of work for in many cases not much in return. Linkage errors on bad shaded libraries provided by other projects happen commonly on unused execution paths, otherwise they would be  detected as errors in the dependency and fixed by the provider project.

The important deal is to have a clear frontier of which are client provider problems that we may be inclined to fix so they don’t break the usage of the library for our users, but even in that case it makes more sense to provide the solution in the dependent project first. To save Beam of the extra maintenance.

We should not be adding the extra work of dealing with this to Beam. I am afraid that this would be an endless task because I have seen the devil of doing this for Hadoop and friends or basically that nobody shades some deps well (yes I am looking at you netty) and we can be ‘fixing’ them for some IO just to discover that the new added (and unused paths) conflict with the version that a runner use. Also we may end up with leaking dependencies that we pinned in our side to fix linkage errors, but that the upstream project may fix in the future and it will be also hard to discover / track the extra dependencies removal in our side.

**Comment by lukecwik** [comment]
I agree with your sentiment @iemejia and in this case it makes sense to merge. I do believe the OSS community should strive to fix the garbage that is produced by bad shading and improper semantic versioning because spending the time making popular projects not break compatibility pays off immensely in downstream projects.

Also the linkage checker has another option where it will only report errors for reachable classes which might address the question as to whether the classes are relevant or not (`--report-only-reachable`) but obviously has the shortcomings where it doesn't deal with classes loaded reflectively (e.g. ServiceLoader, ...).

**Pull request merged**
