### PR TITLE
move nested windmill state classes to top level files and organize di…

### PR DESCRIPTION
**Pull request by m-trieu**
Move nested windmill state classes to their own files.

r: @kennknowles @dustin12 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by kennknowles** [comment]
How does this relate to the other PR where you are organizing the code?

**Comment by m-trieu** [comment]
> How does this relate to the other PR where you are organizing the code?

@kennknowles the other one is organizing the code in StreamingDataflowWorker.java.  The broken out files were all static classes declared within the same source file, so broke them out for readability.  

This PR breaks up the WindmillStateInternals.java source file.

**Comment by m-trieu** [comment]
r: @scwhittle

some clean up for WindmillInternalState files

**Comment by dustin12** [comment]
LGTM

**Comment by m-trieu** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by m-trieu** [comment]
@tvalentyn ready for merge thank you!
thanks for taking a look @dustin12 @kennknowles

**Pull request merged**
