### PR TITLE
[BEAM-6493] Add wordcount example in kotlin

### PR DESCRIPTION
**Pull request by the-dagger**
Signed-off-by: Harshit Dwivedi <harshithdwivedi@gmail.com>

Hi @kennknowles, as discussed in the [Jira ticket](https://issues.apache.org/jira/browse/BEAM-6493), I've added the Kotlin Sample for WordCount in the example folder.
Please have a look and let me know if the project structure looks good, if it does, I'll go ahead and refactor rest of the projects.

Here's what I had in mind for the structure : 

```
examples
    -java/src/main/org/apache/beam/examples
        -java (all the java samples go in this folder)
        -kotlin (all the kotlin samples go in this folder)

```

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`). @kennknowles 
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by the-dagger** [comment]
Hi @kennknowles the builds are failing with the following message
```
13:19:19 * What went wrong:
13:19:19 Execution failed for task ':rat'.
13:19:19 > Found 1 files with unapproved/unknown licenses. See file:/home/jenkins/jenkins-slave/workspace/beam_PreCommit_RAT_Commit/src/build/reports/rat/rat-report.xml
13:19:19 
```

Any ideas as to how I can work on fixing it?

**Comment by kennknowles** [comment]
run java precommit

**Comment by pabloem** [comment]
@the-dagger ping : )

**Comment by harshithdwivedi** [comment]
Please close this PR and review #8034 instead.
Thanks!

**Pull request closed without merging**
