### PR TITLE
Fix java sdk container dependency for Python PostCommit

### LINKED ISSUE #32896: [Failing Test]: Python PostCommit perma-red due to Flink Python xlang test failures: "apache/beam_java11_sdk:2.61.0.dev not found"
### What happened?

First failure: 

https://github.com/apache/beam/actions/runs/11445520520

https://github.com/apache/beam/runs/31848196342

```
      if self._runtime_exception:
>       raise self._runtime_exception
E       RuntimeError: Pipeline BeamApp-runner-1021175329-11c8c557_04f95baf-bc86-48dc-954b-16138b058df3 failed in state FAILED: java.io.IOException: Received exit code 125 for command 'docker run -d --network=host --env=DOCKER_MAC_CONTAINER=null apache/beam_java11_sdk:2.61.0.dev --id=1-2 --provision_endpoint=localhost:41031'. stderr: Unable to find image 'apache/beam_java11_sdk:2.61.0.dev' locallydocker: Error response from daemon: manifest for apache/beam_java11_sdk:2.61.0.dev not found: manifest unknown: manifest unknown.See 'docker run --help'.

apache_beam/runners/portability/portable_runner.py:568: RuntimeError
```

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #32896

after self hosted github action runner bumped to Java11

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @damccorm @jrmccluskey

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by damccorm** [comment]
Oh nice - I had https://github.com/apache/beam/pull/32897 but this is a bit more complete

**Comment by chamikaramj** [comment]
Thanks @Abacn. For my understanding, when/where was Java version bumped ?

**Comment by Abacn** [comment]
> Thanks @Abacn. For my understanding, when/where was Java version bumped ?

It is done manually following this doc: https://github.com/apache/beam/blob/master/.github/gh-actions-self-hosted-runners/arc/README.md

It was supposed to be done as part of #32220 but I wasn't aware that one needs to manually kick off a terraform there (so does previous changes made on. Later on I kicked off after Beam 2.60.0 release finalized. Yeah we should be able to improve the process.

**Pull request merged**
