### PR TITLE
Add properties to skip tests for particular modules

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

A discussion piece. Used pervasively, we might trim a lot of time and also improve usability.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @dhalperi your maven-fu might provide valuable insight.

If I read the output right, the ROS postcommits have at least 5 minutes of tests that are redundant. It is the majority of the Flink runner ROS and a nice chunk off Spark and Apex.

Given the build backlog, I think there's a good multiplier on little improvements like this.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by davorbonaci** [comment]
I'm not sure this is a scalable approach. Instead of introducing a 20+ flags on a per module basis, perhaps a better solution would be to install the modules without any tests first, and then running tests on the target module instead. Perhaps we should explore that direction before going down this path.

**Comment by kennknowles** [comment]
Your comment is about the use case of an individual in their development cycle, but this PR is about Jenkins postcommit `RunnableOnService` integration tests, which often create multi-hour Jenkins queues.

We can (and should) eliminate the queue by adding build workers, but we can do even better than that.

Perhaps you extrapolated that I was trying to generally engineer our configs to make it easy - or at least possible - to quickly and hermetically build just what is needed. I also want to do that, but I don't actually know how yet, or whether it is even possible.

**Comment by kennknowles** [comment]
As I mentioned, this is just for discussion. I don't like the approach, either, but I don't know of another way that plays nice with mvn and Jenkins plugin, etc. I was hoping to prompt thoughts like yours on other ways we might address the problems here 🎺. Any other ideas?

**Comment by davorbonaci** [comment]
No -- Jenkins could do the same. In fact, Travis is engineered to specifically separate build and test phases.

**Comment by kennknowles** [comment]
OK, sounds like a good idea. I'll close this assuming that will be the approach taken. Certainly still quite bad in terms of simplicity and hermeticity, but better than status quo.

**Pull request closed without merging**
