### PR TITLE
[BEAM-10492] Cherrypick the fix from #12263 to 2.23.0 release branch. 

### PR DESCRIPTION
**Pull request by tvalentyn**

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @chamikaramj @mwalenia

**Comment by mwalenia** [comment]
Run Java PreCommit

**Comment by mwalenia** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
LGTM

**Comment by mwalenia** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Prior error: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/2516/ (License check failed, now fixed by https://github.com/apache/beam/pull/12322)

**Pull request merged**
