### PR TITLE
Revert "Increase the timeout  for ValidatesContainer suite"

### PR DESCRIPTION
**Pull request by tvalentyn**
Reverts apache/beam#14151

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Dataflow Python ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Seed Job

**Comment by tvalentyn** [comment]
Run Seed Job

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
R: @y1chi

**Review by y1chi — APPROVED** [review]
LGTM

**Pull request merged**
