### PR TITLE
deps: update libraries bom version to 26.20.0

### PR DESCRIPTION
**Pull request by mutianf**
Update libraries bom version. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by mutianf** [comment]
Hi @bvolpato, didn't realize you were already updating it to 26.19.0.  Yes, we have a Bigtable fix in 26.20.0 that we wish to get in the beam 2.50.0.

**Comment by suztomo** [comment]
Run Java Postcommit

**Comment by suztomo** [comment]
It hit the Guava's recent Gradle metadata problem.  https://github.com/google/guava/releases/tag/v32.1.0 "_Still, read the release notes below if you use Gradle, since the fixed Gradle metadata in 32.1.1 may still require action on your part._"

https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/27802/console

```
12:03:19 Execution failed for task ':sdks:java:extensions:sql:shell:analyzeClassesDependencies'.
12:03:19 > Could not resolve all files for configuration ':sdks:java:extensions:sql:shell:permitUnusedDeclared'.
12:03:19    > Could not resolve com.google.guava:guava:32.1.1-jre.
12:03:19      Required by:
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:libraries-bom:26.20.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.api.grpc:proto-google-cloud-bigtable-v2:2.25.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:google-cloud-pubsublite:1.12.12
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.api.grpc:proto-google-cloud-pubsublite-v1:1.12.12
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api:gax-grpc:2.31.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api:gax:2.31.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api:gax-httpjson:2.31.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api:api-common:2.14.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-bigquerystorage:2.41.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-bigtable:2.25.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-core:2.21.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-core-grpc:2.21.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-firestore:3.13.7
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-pubsub:1.124.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud:google-cloud-spanner:6.44.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:grpc-google-cloud-pubsub-v1:1.106.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:grpc-google-cloud-pubsublite-v1:1.12.12
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:proto-google-cloud-bigquerystorage-v1:2.41.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:proto-google-cloud-firestore-v1:3.13.7
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:proto-google-cloud-pubsub-v1:1.106.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:6.44.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.api.grpc:proto-google-cloud-spanner-v1:6.44.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:libraries-bom:26.20.0 > com.google.api.grpc:grpc-google-cloud-storage-v2:2.25.0-alpha
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:libraries-bom:26.20.0 > com.google.cloud:proto-google-cloud-firestore-bundle-v1:3.13.7
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:libraries-bom:26.20.0 > com.google.api.grpc:proto-google-cloud-storage-v2:2.25.0-alpha
12:03:19       > Module 'com.google.guava:guava' has been rejected:
12:03:19            Cannot select module with conflict on capability 'com.google.guava:listenablefuture:1.0' also provided by [com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava(runtime)]
12:03:19    > Could not resolve com.google.guava:guava:32.0.1-jre.
12:03:19      Required by:
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform
12:03:19       > Module 'com.google.guava:guava' has been rejected:
12:03:19            Cannot select module with conflict on capability 'com.google.guava:listenablefuture:1.0' also provided by [com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava(runtime)]
12:03:19    > Could not resolve com.google.guava:guava:31.1-jre.
12:03:19      Required by:
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.protobuf:protobuf-java-util:3.23.2
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:extensions:google-cloud-platform-core > com.google.api-client:google-api-client:2.2.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > com.google.cloud.datastore:datastore-v1-proto-client:2.15.0
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:google-cloud-platform > io.grpc:grpc-alts:1.56.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:google-cloud-pubsublite:1.12.12 > io.grpc:grpc-googleapis:1.56.1
12:03:19          project :sdks:java:extensions:sql:shell > project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > com.google.cloud:google-cloud-pubsublite:1.12.12 > io.grpc:grpc-services:1.56.1
12:03:19       > Module 'com.google.guava:guava' has been rejected:
12:03:19            Cannot select module with conflict on capability 'com.google.guava:listenablefuture:1.0' also 
```

**Comment by bvolpato** [comment]
Yes, I am trying to handle this in the other PR https://github.com/apache/beam/pull/27725. Just submitted something to completely exclude `listenablefuture` and will see how it goes.

It's up to you -- I can either pivot to 26.20.0 (I was using 26.19.0 because it's still latest according to https://cloud.google.com/java/docs/bom), or you can address the Guava bump here as well.

**Comment by mutianf** [comment]
I believe 26.20.0 was cut yesterday so it hasn't showed up in maven central or public doc page yet. https://mvnrepository.com/artifact/com.google.cloud/libraries-bom. I also realized that I missed a few dependency updates in this PR. Can you pick up 26.20.0 in your PR? I'll close this one. Thank you! @bvolpato

**Pull request closed without merging**
