### PR TITLE
Include byte size of stateKey in estimated weight of WindmillBag, WindmillValue, and WindmillWatermarkHold

### PR DESCRIPTION
**Pull request by dmitryor**
Include byte size of stateKey in estimated weight of WindmillBag, WindmillValue, and WindmillWatermarkHold

The weight is used to track and limit the total StateCache memory size. For certain workloads stateKey consitutes major portion of total memory pinned by cache entries. Not including it into the weight results in severe underestimate of the real cache size, and may leads to GC thrashing and eventually to workers crashing OOM.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by dmitryor** [comment]
R: @arunpandianp

**Review by arunpandianp — APPROVED** [review]

**Comment by scwhittle** [comment]
From precommit logs it appears the tests need to be updated

```
org.apache.beam.runners.dataflow.worker.windmill.state.WindmillStateInternalsTest > testCachedCombining FAILED
    java.lang.AssertionError at WindmillStateInternalsTest.java:3188

> Task :runners:google-cloud-dataflow-java:worker:test

org.apache.beam.runners.dataflow.worker.windmill.state.WindmillStateInternalsTest > testCachedBag FAILED
    java.lang.AssertionError at WindmillStateInternalsTest.java:3086

org.apache.beam.runners.dataflow.worker.windmill.state.WindmillStateInternalsTest > testCachedWatermarkHold FAILED
    java.lang.AssertionError at WindmillStateInternalsTest.java:3148

org.apache.beam.runners.dataflow.worker.windmill.state.WindmillStateInternalsTest > testCachedValue FAILED
    java.lang.AssertionError at WindmillStateInternalsTest.java:3046
```

**Comment by dmitryor** [comment]
R: @scwhittle fixed the test, thank you for pointing to it, still learning workflows for Beam on GitHub.

The test is inherently fragile, but I'm not sure how to improve it without major rework.

**Comment by Abacn** [comment]
```
org.apache.beam.sdk.util.UnboundedScheduledExecutorServiceTest > testThreadsAreAddedOnlyAsNeededWithContention FAILED
    java.lang.AssertionError at UnboundedScheduledExecutorServiceTest.java:556
```

unrelated flaky test

**Review by Abacn — APPROVED** [review]

**Pull request merged**
