### PR TITLE
[BEAM-4126] Delete Maven build files.

### PR DESCRIPTION
**Pull request by lukecwik**
Note that I left the archetype related pom.xml as they are used in the gradle build process.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by lukecwik** [comment]
CC: @swegner We ready for this yet?

**Comment by swegner** [comment]
I believe there are just a couple remaining prerequisites before we officially stop supporting the Maven build:

1. We should first verify we can successfully release from Gradle. @jbonofre is currently working on the 2.5.0 release.
1. @reuvenlax [previously mentioned](https://lists.apache.org/thread.html/e45f09edb70f5ded73d20e9faef22e7497798ee46b5ee7e3afd203c6@%3Cdev.beam.apache.org%3E) that Google uses the Maven build for internal Dataflow builds. The internal build has yet to be migrated. Once other prerequisites are completed perhaps we can set a deadline for downstream consumers to migrate before we delete the pom's.

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
R: @markflyhigh

**Comment by lukecwik** [comment]
Google has migrated away from needing the pom.xml for the build.

**Comment by pabloem** [comment]
Q: How come it's okay to remove dependencies from the poms within `maven-archetypes`? Does mvn infer the dependencies when creating the archetypes?

Everything else LGTM. Thanks Luke : )

**Comment by lukecwik** [comment]
If your talking about beam-examples-java, beam-runners-direct-java, beam-sdks-java-core. Those `dependencies` were there because the archetype testing/generation needed to have an explicit hint that these modules needed to be built before you can generate the archetypes. Those dependencies have been moved to the equivalent build.gradle files (e.g. https://github.com/apache/beam/blob/8873d414b0b4f4cbae4f424af663d33bc92e7b6f/sdks/java/maven-archetypes/starter/build.gradle#L27) to ensure the appropriate ordering.

**Pull request merged**
