### PR TITLE
Increase streaming server timeout 

### PR DESCRIPTION
**Pull request by byronellis**
Increases the timeout for the streaming server to 60s which appears to allow sufficient time for the PVR Spark 2 tests to complete. In local testing this addresses #21473 

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by byronellis** [comment]
It worked! Okay, so it's really just that setting up and tearing down Spark can take awhile.

**Review by damccorm — APPROVED** [review]
This LGTM - it obviously doesn't get to the core of the race condition, but it is a strict improvement over the current permared status of this suite - https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark2_Streaming/

**Comment by byronellis** [comment]
I'm no longer sure it's a race. I think the tests may just take awhile to run and get killed by the timeout if they overrun.

**Comment by damccorm** [comment]
image

This is nice!

**Pull request merged**
