### PR TITLE
Auto-cancel old unit test Actions Runs

### LINKED ISSUE #23089: [Feature Request]: Auto-cancel old Actions Runs
### What would you like to happen?

Right now, our actions runs deal with long queues on a pretty much daily basis. Part of the reason for this is that if you make 5 commits in quick succession, 5 sets of workflow runs are queued and it takes a _long_ time to work through all of them.

We can work around this by auto-canceling outdated runs. We're already [doing this in Tour of Beam](https://github.com/apache/beam/pull/23032#discussion_r965927104) and it should be generalizable to the rest of the repo (or at least the workflows that are queued based on pull request pushes).

For reference, auto cancel docs: https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run

### Issue Priority

Priority: 2

### Issue Component

Component: build-system

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #23089

The concurrency condition works: https://github.com/Abacn/beam/actions/runs/3016483393

Get message like "Canceling since a higher priority waiting request for 'Java Tests @ Abacn:dumb' exists"

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @damccorm

**Review by damccorm — COMMENTED** [review]
This looks great! Could we add it to some other workflows as well? I'm thinking [local_env_tests](https://github.com/apache/beam/blob/master/.github/workflows/local_env_tests.yml), [build_wheels](https://github.com/apache/beam/blob/master/.github/workflows/build_wheels.yml), and the playground workflows would all benefit from this

**Comment by Abacn** [comment]
> This looks great! Could we add it to some other workflows as well? I'm thinking [local_env_tests](https://github.com/apache/beam/blob/master/.github/workflows/local_env_tests.yml), [build_wheels](https://github.com/apache/beam/blob/master/.github/workflows/build_wheels.yml), and the playground workflows would all benefit from this

Yeah thanks for pinning to the workflows. Specifically including build_wheels would be very helpful (they take long time)

**Review by damccorm — APPROVED** [review]
LGTM - thanks for the quick turnaround!

**Pull request merged**
