### PR TITLE
Revert "[BEAM-11934] Remove Dataflow override of streaming WriteFiles with runner determined sharding"

### PR DESCRIPTION
**Pull request by reuvenlax**
Reverts apache/beam#15178

### CODE REVIEW

**Comment by reuvenlax** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by reuvenlax** [comment]
I'm not convinced that the flakiness was caused by this PR, as it happens
even when this PR is rolled back.

I'm still confused about how WordCount ever succeeds after this PR was
submitted as it writes to files, it does not specify numShards, and it also
runs on windmill appliance.

**Comment by tvalentyn** [comment]
retest this please

**Comment by kileys** [comment]
There's an ongoing failure for org.apache.beam.examples.WordCountIT.testE2EWordCount unrelated to this change.

https://issues.apache.org/jira/browse/BEAM-12699

**Comment by tvalentyn** [comment]
closing in favor of https://github.com/apache/beam/pull/15287

**Pull request closed without merging**
