### PR TITLE
[BEAM-3391] Upgrade oauth2client and google-apitools dependencies

### PR DESCRIPTION
**Pull request by aaltay**
R: @udim 

cc: @znewman01

### CODE REVIEW

**Comment by aaltay** [comment]
run python postcommit

**Comment by udim** [comment]
Looks good. Please fix the typo in the title: "oauth2cleitn"

**Comment by aaltay** [comment]
Thank you for the quick review, fixed the typo. I will wait for tests before merging.

**Comment by aaltay** [comment]
Python pre-commit and post-commit tests are passing.

**Pull request merged**
