### PR TITLE
Update fastavro to 0.21.4

### PR DESCRIPTION
**Pull request by akedin**
Update fastavro to latest release

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by akedin** [comment]
R: @aaltay @chamikaramj @charlesccychen

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

**Comment by lgajowy** [comment]
It seems that both Python Performance Tests and some of the IOIT Java Performance Test Jobs started failing after this change (version conflict error): 
 - [Python performance tests logs](https://builds.apache.org/view/A-D/view/Beam/job/beam_PerformanceTests_Python/1378/console)
 - [example IOIT logs (see Jenkins for more)](https://builds.apache.org/view/A-D/view/Beam/job/beam_PerformanceTests_Compressed_TextIOIT/934/console)

I investigated the issue a little bit in https://github.com/apache/beam/pull/6330 and it seems that we were using fastavro version from system site packages (not from virtualenv). From the performance tests perspective, I don't see any reason to use system site packages so I removed it which fixed the non-python performance tests. 

There is still problem with python performance tests though - the job has trouble loading BeamTestPlugin due to the very same version mismatch. I gave it a shot and tried [installing nose in beam_env](https://github.com/apache/beam/pull/6330/commits/acdc1a4f78b85f7137c57e8f3f6f2703ad530f0f) but it didn't help. Does anyone have an idea what should be the proper fix in this case? Or maybe we need to use the --system-site-packages flag for some reason?

cc: 
@charlesccychen @akedin @pabloem @DariuszAniszewski @kkucharc

**Comment by markflyhigh** [comment]
Thanks for the investigation Lukasz. 

Remove `--system-site-packages` looks like the right thing to do, but to me the wired things are `nose` still looks for `fastavro` in system site package. Even `nose` may also come from system site package, if you look at this error log in [this build](https://builds.apache.org/job/beam_PerformanceTests_Python/1380/console):

/home/jenkins/.local/lib/python2.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin beam_test_plugin = test_config:BeamTestPlugin: (fastavro 0.19.7 (/home/jenkins/.local/lib/python2.7/site-packages), Requirement.parse('fastavro==0.21.4'))

Any Python expert can help?

**Comment by lgajowy** [comment]
I tried this solution once again but since merging [this pr](https://github.com/apache/beam/pull/6266) it doesn't seem to work (due to some other dependency). I will look for a solution but currently, I'm out of ideas. 

Adding @aaltay and @tvalentyn (I have a hunch that you may know the right solution. :) )

In short: it is weird that even when we get rid of `--system-side-packages` option from all the virtualenvs that we create, it still has conflicts with dependencies located in: `/home/jenkins/.local/lib/python2.7/site-packages`

example logs: https://builds.apache.org/job/beam_PerformanceTests_Compressed_TextIOIT/945/console

**Pull request merged**
