### PR TITLE
[BEAM-2272] Enforce dependency convergence

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This changes the global config. Opening a PR to see which modules include the enforcer plugin but have divergent deps.

### CODE REVIEW

**Comment by kennknowles** [comment]
retest this please

**Comment by reuvenlax** [comment]
@kennknowles any update?

**Comment by aaltay** [comment]
@kennknowles Do we still need this PR? (For my own education, what does this do?)

**Comment by kennknowles** [comment]
This would make it so that our dependencies have to all be explicitly resolved, not overwritten according to Maven's precedence rules.

For example, we currently have situations like this:

 * B -> proto version _x_
 * A -> proto version _y_ (let's say it is earlier)
 * A -> B

We end up with A -> proto version _y_ so now when B calls a proto version _x_ method it crashes. In this case, B needs to bundle proto or A needs to upgrade.

Dependency conversion forces one of these to be done explicitly. It will increase the number of explicit exclusions we have, but will prevent accidentally having two versions with precedence that depend on vagaries of the dep graph.

Specifically today, we have this situation between sdks/java/io/gcp and the Java dataflow runner, and users have been hit by having the wrong version of proto included.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
I need to make some progress on it before it is appropriate for a reviewer. I'll close it for now.

**Pull request closed without merging**
