### PR TITLE
Fix clean up resource workflow; fix XVR Flink

### PR DESCRIPTION
**Pull request by Abacn**
The test_data table got accidentally deleted when manually clean up test tables, because https://github.com/apache/beam/actions/workflows/beam_CancelStaleDataflowJobs.yml?page=2 shows there were tables cannot be cleaned by the cron cleaner job

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Clean up gcp resources: https://github.com/apache/beam/actions/runs/6826209994/job/18565628607

XVR Flink: https://github.com/apache/beam/actions/runs/6826215764/job/18565648261

both running.

**Comment by Abacn** [comment]
I am thinking about having a dedicate service account to execute clean up jobs. Currently it would fail when the temp BigQuery/spanner dataset are created by other service account so our GHA service account does not have permission to delete them

Or, if the migration is done there should no longer be this case happening

R: @volatilemolotov

**Comment by volatilemolotov** [comment]
> I am thinking about having a dedicate service account to execute clean up jobs. Currently it would fail when the temp BigQuery/spanner dataset are created by other service account so our GHA service account does not have permission to delete them
> 
> Or, if the migration is done there should no longer be this case happening

Not sure, the account used is either one that is specified within the job using auth step or the one used by GKE (beam-actions-wheel, this will probably change in the future).

**Comment by Abacn** [comment]
tests finished. XVR flink passed on highmem, merging for now

**Pull request merged**
