### PR TITLE
Explictly delcare globals defined elsewhere

### PR DESCRIPTION
**Pull request by cclauss**
Similar to #4562

DESCRIPTION HERE

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `./gradlew build` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by cclauss** [comment]
Please retest this.

**Comment by cclauss** [comment]
Jenkins: Please retest

**Comment by cclauss** [comment]
Jenkins: Please retest this

**Comment by cclauss** [comment]
@Jenkins Please retest this.

**Comment by cclauss** [comment]
Jenkins please retest

**Comment by cclauss** [comment]
Jenkins retest this please

**Comment by cclauss** [comment]
@Jenkins retest this please

**Comment by cclauss** [comment]
@aaltay Can you please help me to understand why the Java test is failing with this change?

**Comment by aaltay** [comment]
I think it is a flake in Java tests (DirectRunner ensureMetricsThreadDoesntLeak). Do you mind filing a JIRA issue for that?

I will merge this PR.

**Pull request merged**
