### PR TITLE
[BEAM-4410] added Broadcast Join translation

### PR DESCRIPTION
**Pull request by mareksimunek**
R: @jbonofre 

[BEAM-4410] 
Translation of Broadcast Join. Broadcast join can be very efficient for joins between a large dataset with small dataset that has to fit into memory.  It's implemented with Beam's `sideInput`.

[BEAM-4419]
Update Operator Testkit 
Testkit was moved into 'euphoria-beam' package. Testing instrumentation was simplified.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by mareksimunek** [comment]
run java precommit

**Comment by mareksimunek** [comment]
run java precommit

**Comment by VaclavPlajt** [comment]
run java precommit

**Comment by VaclavPlajt** [comment]
run java precommit

**Comment by mareksimunek** [comment]
R: @jbonofre

**Pull request merged**
