### PR TITLE
Expose BigQuery schema autodetect in Java SDK

### LINKED ISSUE #20515: Expose BigQuery schema autodetect in Java SDK
The Beam Java SDK's BigQueryIO transform currently doesn't expose the [schema autodetect job configuration](https://developers.google.com/resources/api-libraries/documentation/bigquery/v2/java/latest/com/google/api/services/bigquery/model/JobConfigurationLoad.html#setAutodetect-java.lang.Boolean-).  The feature is exposed by the current [Python SDK](https://github.com/apache/beam/blob/a99c6826a067f49ebb60e625c8652900c7d0e810/sdks/python/apache_beam/io/gcp/bigquery.py#L1593), but not the Java SDK.

Although Java is more strict about types and schemas, the BigQueryIO transform supports writing TableRows which don't inherently have a schema. This provides a convenient path for loading JSON data into BigQuery but is massively thwarted by the fact that a schema is required to make use of the SchemaUpdateOption values ALLOW_FIELD_ADDITION and ALLOW_FIELD_RELAXATION.

The BigQuery schema autodetection feature must be enabled at the JobConfigurationLoad level. The BigQueryIO creates the JobConfigurationLoad in only one place: [WriteTables.java](https://github.com/apache/beam/blob/752bdfd09bc4175dd9f51a096f81c9e5b0805913/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java#L370). Exposing the autodetection option would mean adding it here, then propagating the change upwards until it's exposed at the BigQueryIO.Write level.

A big of context on this issue:
 * Google cloud's blog [has an article](https://cloud.google.com/blog/products/gcp/how-to-handle-mutating-json-schemas-in-a-streaming-pipeline-with-square-enix) on handling mutating JSON schemas in Dataflow using a black-box "Validate and Mutate BQ Schema" step.
 * Suggested workarounds include creating a stateful DoFn to dynamically generate a schema, load it as a side input to create a PCollectionView, then passing it to BigQuerIO using withSchemaFromView: https://stackoverflow.com/a/58809875/477563
 * [Entire projects](https://github.com/the-dagger/dataflow-dynamic-schema) have been created to try and work around this issue.

All of the above would be rendered moot (and many headaches spared!) if only the schema autodetection were exposed in the Java SDK _like it already is_ in the Python SDK.

Imported from Jira [BEAM-10826](https://issues.apache.org/jira/browse/BEAM-10826). Original Jira may contain additional context.
Reported by: mtruscello.

### PR DESCRIPTION
**Pull request by dannikay**
Fixes #20515 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by dannikay** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by dannikay** [comment]
All checks passed. Please take a look! @robertwb @Abacn

**Review by Abacn — COMMENTED** [review]
Thanks for the contribution. I see this is a long standing issue and this sounds a useful change. Will look into the original JIRA ticket and Python implementation to get more contexts. CC: @reuvenlax @ahmedabu98 for BigQuery SchemaUpdate related changes.

For now I just have one comment. In accordance with the BigQuery [option](https://developers.google.com/resources/api-libraries/documentation/bigquery/v2/java/latest/com/google/api/services/bigquery/model/JobConfigurationLoad.html#setAutodetect-java.lang.Boolean-) and Python, maybe consider naming this option `schemaAutoDetect`, `BigQueryIO.Write.withSchemaAutoDetect`?

**Comment by reuvenlax** [comment]
I'm not sure I understand this PR. The schema is required if CREATE_IF_NEEDED is set, in which case the schema is needed to create the table. We don't currently require a schema for existing tables. How does autodetect schema work if the table doesn't exist yet?

**Comment by Abacn** [comment]
waiting on author

**Pull request closed without merging**
