### PR TITLE
Cherry pick #8178 and #8211 to release-2.12.0

### PR DESCRIPTION
**Pull request by iemejia**
This addresses https://issues.apache.org/jira/browse/BEAM-5723

A part of https://issues.apache.org/jira/browse/BEAM-6620

### CODE REVIEW

**Comment by iemejia** [comment]
R: @kennknowles 
CC: @apilloud

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Updted PR to cherry pick @echauchot fixes to `CassandraIOTest`

**Comment by kennknowles** [comment]
My worry as the unaddressed thread on https://issues.apache.org/jira/browse/BEAM-6974 where the Cassandra tests are very flaky (I think more than 50%). They seem to pass first try here.

**Comment by iemejia** [comment]
@kennknowles the flakiness of the tests was because of a port conflict, this should be solved now. Notice that's the reason why I included the cherry pick of the test fixes too here.

**Comment by echauchot** [comment]
> @kennknowles the flakiness of the tests was because of a port conflict, this should be solved now. Notice that's the reason why I included the cherry pick of the test fixes too here.

@iemejia you mix up 2 different flakiness issues: the flakiness I fixed that was due to port conflicts is related to [this](https://issues.apache.org/jira/browse/BEAM-6982) ticket but @kennknowles refers to [that other](https://issues.apache.org/jira/browse/BEAM-6974) ticket which is not related to port conflicts. I have no idea about this later ticket as there is no error message and there it was not reproduced locally.

**Comment by iemejia** [comment]
@echauchot  I was not mixing both, I was not even aware of BEAM-6974. I thought Kenn referred to the other issue.
Any chance to have a quick fix of that one? Remember that the fix has to be done in both `HIFIOWithEmbeddedCassandraTest` module and `HadoopFormatIOCassandraTest` module because the code of the tests is duplicated for the moment.

**Comment by echauchot** [comment]
@iemejia I have no time to do this. I already spent a lot of time on Cassandra related tickets. I'll try to to a quick fix but after that can you please take it ?
Seems bad to have duplicated code, what's the reason

**Comment by iemejia** [comment]
Oups sorry I forgot this was not about CassandraIO but about HadoopInputFormat and his clone, so not in your park effectively (I thought it was correlated to your PR).
It is a miracle that the 3 tests passed in the past. I can do the fix if you prefer.
The duplicated code is about `HadoopInputFormat` being superceded by `HadoopFormat` and will be removed soon.

**Comment by echauchot** [comment]
Just fixed it: https://github.com/apache/beam/pull/8234

**Pull request merged**
