### PR TITLE
[Spark runner] Support running (VR) tests with Java 17

### LINKED ISSUE #24400: [Task]: Support testing Spark runner with Java 17
### What needs to happen?

Goal of this ticket is to support running tests (including VR tests) using Java 17 as well.
In Beam this is shall be done using the properties `compileAndRunTestsWithJava17` and `java17Home`.

```
gradle :runners:spark:3:test -PcompileAndRunTestsWithJava17 -Pjava17Home=???
```

### Issue Priority

Priority: 2

### Issue Component

Component: runner-spark

### PR DESCRIPTION
**Pull request by mosche**
Support running (VR) tests with Java 17 (closes #24400)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @echauchot

**Comment by echauchot** [comment]
@mosche thanks, reviewing ...

**Comment by echauchot** [comment]
@mosche please rebase on master

**Comment by echauchot** [comment]
@mosche is there any CI job added to run compilation/tests/VRtests with java 17 (using -PcompileAndRunTestsWithJava17) ?

**Comment by mosche** [comment]
no, for now this is just fixing the build to support such runs

**Review by echauchot — APPROVED** [review]
Thanks Moritz ! LGTM. I guess that creating CI jobs for supported JDKs consumes computing resources and needs a broader discussion. As your changes to the build are backward compatible it is enough to test them locally for now until the community agrees on the CI jobs.

**Pull request merged**
