### PR TITLE
[BEAM-778] Fix the Compressed file seek tests on windows

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

R: @chamikaramj @tibkiss 

The seek tests were failing on windows due to two main reasons: (1) files not being closed before removing and (2) files not being opened as binary files.

### CODE REVIEW

**Comment by tibkiss** [comment]
Nice catch @sb2nov. It was clearly a mistake from my side not testing BEAM-778 on Windows.
Your fix looks reasonable to me from the content perspective (I don't have windows machine around to test it).

Two thoughts:
 * Is it possible to setup Windows Jenkins Slave/Travis for testing?
 * Currently the tests are using `with open('filename', mode)`. This could be further simplified to `with CompressedFile(open(..),..)`. That way we would also test the `__enter__` and `__exit__` methods of CompressedFile.

**Comment by chamikaramj** [comment]
LGTM.

Thanks for fixing this.

**Comment by sb2nov** [comment]
@chamikaramj Thanks for merging.

@tibkiss Makes sense. (1) I think Jason is looking into adding a windows slave. We could also try to investigate using something like https://docs.tea-ci.org/usage/overview/ as it is free for open source projects (2) I'll followup with that in a PR shortly.

**Comment by aaltay** [comment]
cc: @jasonkuster for the Windows testing question.

**Pull request closed without merging**
