### PR TITLE
[BEAM-8271] Properly encode/decode StateGetRequest/Response continuation token

### PR DESCRIPTION
**Pull request by chadrik**
This behavior is the same as Java, and corrects an inconsistency with bytes/str that might have caused problems in python3.

This is a followup to #9056.

Note that this issue has its own Jira. 

R: @robertwb 
R: @udim 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by chadrik** [comment]
> Actually, I think it's more correct to let continuation_token by bytes everywhere (possibly fixing the uses if need be).

Here's the ticket I made: https://issues.apache.org/jira/browse/BEAM-8271.  

It's been awhile, but my instinct was that this is an issue in the proto file:  all other id-like fields throughout these protos are strings.  Also, the token itself is created using string operations (`'token_%x' % len(self._continuations)`) so it certainly feels like this wants to be a string right up until it's encoded and stored in the proto message.   

IIRC, my first attempt to solve this was to preserve the `bytes` typing, but I think there are other calls that create the continuation token from strings, and it started getting pretty ugly (converting from bytes to str to do some string formatting, then back to bytes in multiple places, etc), so I looked at how this was solved in Java, and based my changes here on that.  It keeps the ugliness isolated and at a minimum.  

Again, it was awhile ago, so I may be misremembering something.  If I haven't convinced you yet, I can show you what an alternate solution looks like using bytes, but first please do have a look at other ids in the .proto files and at the Java equivalent for this.

**Comment by robertwb** [comment]
It's bytes because non-trivial runners may serialize arbitrary data into this field used to continue the iterable. (Ids are strings because they're just used to compare against, and also the type of proto map keys constrains us here.) There shouldn't be any manipulation of this token except for passing it back on the client side at least--just accepting it and passing it back. 

It looks like Java treats this as a BytesString. I still think we should do the same.

**Comment by chadrik** [comment]
Ok, I’ll have another look at it.

**Comment by chadrik** [comment]
@robertwb  Ok, the solution using `bytes` is actually much simpler.  I thought that `bytes` had all of its string formatting capabilities neutered in python3, but apparently it has not (my python3 experience is limited to a few side projects).    Thanks for pushing me in the right direction.

Note: I can't see the tests on this PR.  Are they running?

**Comment by chadrik** [comment]
> It's bytes because non-trivial runners may serialize arbitrary data into this field used to continue the iterable. (Ids are strings because they're just used to compare against, and also the type of proto map keys constrains us here.) 

Make sense.  Thanks for the explanation.

**Comment by chadrik** [comment]
@robertwb this is ready to go

**Pull request merged**
