### PR TITLE
Remove spaces in experiments

### LINKED ISSUE #22422: [Bug]: Python streaming LoadTests failing since July 8
### What happened?

https://ci-beam.apache.org/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/

```
06:01:37                      [--input_options INPUT_OPTIONS] [--timeout_ms TIMEOUT_MS]
06:01:37                      [--iterations ITERATIONS]
06:01:37                      [--number_of_counter_operations NUMBER_OF_COUNTER_OPERATIONS]
06:01:37                      [--number_of_counters=0 NUMBER_OF_COUNTERS=0]
06:01:37 pardo_test.py: error: argument --number_of_counters=0: expected one argument
```

### Issue Priority

Priority: 1

### Issue Component

Component: build-system

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Fixes #22422

See explanation in https://github.com/apache/beam/issues/22422#issuecomment-1193019507

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
Tested in https://ci-beam.apache.org/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/673, which successfully started the load test job.

**Comment by TheNeuralBit** [comment]
R: @tvalentyn

**Comment by TheNeuralBit** [comment]
We should consider changes to make this more robust, but this at least gets the jobs running again.

**Comment by tvalentyn** [comment]
Thank you!

**Pull request merged**
