### PR TITLE
[Website] add publishdate attribute to case studies frontmatter

### PR DESCRIPTION
**Pull request by bullet03**
NB!!! Merge this PR first, before merging https://github.com/apache/beam/pull/21891
- add publishdate attribute to case studies md files (study category: lyft, seznam, ricardo, paloalto, hop). It was done since file layouts\case-studies\list.html uses hugo and ranges throug all case-studies using `ByPublishDate `attribute like this `{{ $pages := .Pages.ByPublishDate.Reverse }}`, but ByPublishDate wasn't located in any case studies md files, so when you add a new case study it takes a place not an order you would expect (freshly added file was shown second, not first or last). To take control over this flow abovementioned case studies md files got publishdate attribute and by that a new added file gets a correct place.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
R: @nausharipov

**Comment by bullet03** [comment]
Future idea, not included in this PR: research if we can use lastModifiedDate as publishdate.

**Comment by AKosolapov** [comment]
Looks good to me

R: @pabloem could you please review

**Comment by aijamalnk** [comment]
> Future idea, not included in this PR: research if we can use lastModifiedDate as publishdate.

Better to have two indicators: Publish date and Last updated date if the post was modified. Similar to newspapers.

**Comment by pabloem** [comment]
ok lgtm

**Pull request merged**
