### PR TITLE
Script that trains and run the housing data.

### PR DESCRIPTION
**Pull request by nervoussidd**
This is the script that train the housing data and saves the trained models to GCS i don't have an GCS account so i have just put in the code that will save the model to GCS location ,commented out the code.This is not the exact code as i also need to build pipeline but it does reflect the operation what it will do.In the moment just want feedback on the code which will help me to fix the issue.
issue#24903 desc : https://github.com/apache/beam/issues/24903

### CODE REVIEW

**Comment by nervoussidd** [comment]
OK,lets do it

**Comment by nervoussidd** [comment]
So over here i have already commented out the GCS code , should i add the code that will take  the code that will take a folder from local storage and run it.

**Comment by jrmccluskey** [comment]
@AnandInguva are you going to handle PR review for these?

**Comment by AnandInguva** [comment]
> @AnandInguva are you going to handle PR review for these?

Yes, I will take this review.

**Comment by nervoussidd** [comment]
Now it will be able to save the trained models to local storage

**Comment by AnandInguva** [comment]
Hi, the end goal of this PR should be to 

Build a CI that follows: 

1. use https://gist.github.com/AnandInguva/1ce58c7df98ade4efe6bc95a157b82da script here to train the models using Japanese housing dataset.
2. Save the model to a remote repository.
3. Once the model is saved, we will launch a beam pipeline from https://github.com/apache/beam/blob/a4f55afa052b83237387698649b127570e1e5a63/sdks/python/apache_beam/examples/inference/sklearn_japanese_housing_regression.py#L4. This example would be using the models saved in the step 1.

Steps 1, 2, and 3 can be sequential and you can use a bash script to run steps 1, 2, 3.

**Pull request closed without merging**
