### PR TITLE
Update Dataflow Beam container version.

### PR DESCRIPTION
**Pull request by udim**
This should fix Python postcommit tests.

### CODE REVIEW

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
It failed: https://builds.apache.org/job/beam_PostCommit_Python_Verify/4396/
Investigating...

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
Woohoo! Passed: https://builds.apache.org/job/beam_PostCommit_Python_Verify/4400/

R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

R: @aaltay for merge.

**Pull request merged**
