### PR TITLE
[BEAM-1835] NPE in DirectRunner PubsubReader.ackBatch

### PR DESCRIPTION
**Pull request by ravwojdyla**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @tgroh -- I think that Thomas was looking into this.

**Comment by ravwojdyla** [comment]
One very simple solution to this problem is to just always reuse reader, not sure if that is best, but decided to create this PR cause it's the simplest one, but I'm open to any suggestions.

**Comment by tgroh** [comment]
My understanding is that the bug that caused the NPE should have been fixed in #2237 and https://github.com/apache/beam/pull/2323, which have both been merged into master. They're in the nightly builds as well, but not the most recent release. This occurs when you build from github HEAD?

**Comment by ravwojdyla** [comment]
@tgroh yep, i tested this on the master, let me double check again, just so I'm sure.

**Comment by ravwojdyla** [comment]
@tgroh yep - just double checked - i can reproduce this on the current master, and sorry for the delay, had to adjust code and create #2366 in the mean time. Also looking at the issues you listed, I don't think they address the issue described in the jira.

Also the travis error does not seems to be related to this change:

```
2017-03-30T00:52:21.323 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project beam-sdks-parent: Failed during checkstyle execution: Unable to find suppressions file at location: beam/suppressions.xml: Could not find resource 'beam/suppressions.xml'. -> [Help 1]
```

Is this known issue?

**Comment by ravwojdyla** [comment]
Also I would like to understand why direct runner even has `DEFAULT_READER_REUSE_CHANCE` (apart from the comment in the code), that would let me understand if this PR is even acceptable.

**Comment by tgroh** [comment]
The `DEFAULT_READER_REUSE_CHANCE` is there to ensure that authors of IO Connectors will exercise the resume-from-checkpoint behavior of their readers while running in the `DirectRunner`; I'd like to avoid removing it if possible.

I can reproduce the failure. This is actually a bug in `PubsubUnboundedSource` or `PubsubCheckpoint`. The `finalizeCheckpoint` documentation states that
"This finalize method may be called from any thread, concurrently with calls to {@link UnboundedReader} it was created from."
and
"It is not safe to assume the {@link UnboundedReader} from which this checkpoint was created still exists at the time this method is called."

The Runner is permitted to close the reader and finalize all outstanding checkpoints in whatever order, potentially interleaving the two operations, so the checkpoint mark must not assume that the client is still available, or that the client, if it is available and open when the call to `finalizeCheckpoint` begins, is still available and open at any future point.

I'm looking into fixes for the source proper.

**Comment by ravwojdyla** [comment]
@tgroh If we would like to avoid disabling `DEFAULT_READER_REUSE_CHANCE`, I'm happy to adjust this PR to keep it.

About the issue - agree - sounds pretty much like the description in the [jira ticket](https://issues.apache.org/jira/browse/BEAM-1835).

**Comment by tgroh** [comment]
Yeah. https://github.com/apache/beam/pull/2368 should fix your problem, but I'd like @dhalperi to weigh in there.

**Pull request closed without merging**
