### PR TITLE
Update Enrichment Handlers to PEP 585 typing

### PR DESCRIPTION
**Pull request by jrmccluskey**
Updates type hints to PEP 585 standards.

Part of #32969 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by damccorm — APPROVED** [review]
Nice!

**Comment by lianliangzhang** [comment]
@jrmccluskey , I meet a issue want to reference BigQueryEnrichementHandler to generate a SpannerEnrichemenetHandler.

Could you please help check how can batch list data can be received in     def __call__(self, request: Union[beam.Row, list[beam.Row]], *args, **kwargs):  method in SpannerEnrichemenetHandler()
I want to use EnrichemenetHandler to handle batch element instead of one by one beam. raw element, but when I put input data as below list, the data still comes to handler one by one.    requests = [
        beam.Row(sale_id=1, Consumer_Id='0b47c98f-58bf-4ae6-8577-9257f14ee7e6', product_id=1, quantity=1),
        beam.Row(sale_id=3, Consumer_Id='e687e75a-d4be-411b-9301-4777183b2611', product_id=2, quantity=3),
        beam.Row(sale_id=5, Consumer_Id='5c17e957-ceea-4ab9-a9d9-2d9f84c91380', product_id=4, quantity=2)
    ]

Create pipline as below approach

  spanner_handler = SpannerMultiLineEnrichmentHandler(
        project=project_id,
        instance_id=instance_id,
        database=database,
        row_restriction_template=row_key + " ='{}'",
        table_name=table_id,
        fields=fields,
        min_batch_size=3,
        max_batch_size=3)

    with beam.Pipeline() as p:
        _ = (
                p
                | "Create" >> beam.Create(requests)
                | "Enrich W/ Spanner" >> Enrichment(spanner_handler)
                | "Print" >> beam.Map(print))

**Comment by lianliangzhang** [comment]
I just want to get batch beam.raw list one time instead of one by one, please help on it, thanks.

**Comment by damccorm** [comment]
Hey @lianliangzhang in general it is probably better to create a GitHub issue to discuss questions like this - could you please open one [here](https://github.com/apache/beam/issues/new?assignees=octocat&labels=task%2Cawaiting+triage&projects=&template=task.yml&title=%5BTask%5D%3A+) and tag me, @jrmccluskey , and @claudevdm ? Please include the code you are currently using to define `SpannerMultiLineEnrichmentHandler`.

**Pull request merged**
