### PR TITLE
Remove duplicate SchemaIOProvider AutoService in Java core

### LINKED ISSUE #25601: [Failing Test]: Python PostCommit failing due to duplicate AvroSchemaIO autoservice
### What happened?

Python PostCommit jdbcio_xlang_it_test failing. Jenkins log does not show much message, but running locally the actual error shows:
```
ERROR:apache_beam.utils.subprocess_server:Starting job service with ['java', '-jar', '/Users/yathu/.apache_beam/cache/jars/composite-jars/9b6e2cb01bd723cbd87a5e71462f25664f165993697afc98e1c64c34bf814f98.jar', '50709', '--filesToStage=/Users/yathu/dev/virtualenv/py38beam/lib/sdks/java/extensions/schemaio-expansion-service/build/libs/beam-sdks-java-extensions-schemaio-expansion-service-2.47.0-SNAPSHOT.jar,/Users/yathu/.apache_beam/cache/jars/postgresql-42.2.16.jar']
ERROR:apache_beam.utils.subprocess_server:Error bringing up service
Traceback (most recent call last):
  File "/Users/yathu/dev/virtualenv/py38beam/lib/python3.8/site-packages/apache_beam/utils/subprocess_server.py", line 88, in start
    raise RuntimeError(
RuntimeError: Service failed to start up with error 1
Traceback (most recent call last):
```
This is because there are two `@AutoService AvroSchemaIOProvider` classes so the schemaio expansion service fails to start.

The fix could either be similar to the workaround here: https://github.com/apache/beam/blob/011296c14659f80c8ecbeefda79ecc3f1113bd95/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/io/Providers.java#L45

Or simply remove AvroSchemaIOProvider in core. 

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #25601

Considering two solutions mentioned in #25601 I think simply remove it is fine, because the deliverable of the expansion service is the shadowJar [beam-sdks-java-extensions-schemaio-expansion-service-$BEAM_VERSION.jar](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-extensions-schemaio-expansion-service). The removed class should never be used directly.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python 3.10 PostCommit

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
@Abacn Thanks for fixing this but I doubt that we can simply remove it for now. IINM, if user code depends only on `beam-sdks-java-core` module and not on `beam-sdks-java-extensions-avro` (which is rather default case for now since this extension is quite new) and it leverages `AvroSchemaIOProvider` then it will fail in runtime.
CC: @mosche

**Comment by Abacn** [comment]
> @Abacn Thanks for fixing this but I doubt that we can simply remove it for now. IINM, if user code depends only on `beam-sdks-java-core` module and not on `beam-sdks-java-extensions-avro` (which is rather default case for now since this extension is quite new) and it leverages `AvroSchemaIOProvider` then it will fail in runtime. That is why I preferred to keep two versions of this loader for a period of deprecation. CC: @mosche

Hi @aromanenko-dev thanks for the comment. Yes this is the case. For users only using released artifacts it does not have problem because the expansion service jar is a shadowJar:
https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-extensions-schemaio-expansion-service/2.45.0

**Comment by aromanenko-dev** [comment]
@Abacn Yes, this is correct about expansion service jar. Though, my point was mostly about "pure" Java SDK pipelines where `AvroSchemaIOProvider` is used (e.g., Beam SQL + Avro) and I can be very risky to remove any of Avro-related classes from `core` now.
 
Do I miss something?

**Comment by Abacn** [comment]
I see, understand, could you please assign yourself #25601 then, thanks!

**Pull request closed without merging**
