### PR TITLE
[flink] Fix watermark generation for empty UnboundedSource

### LINKED ISSUE #30050: [Bug]: FlinkRunner: KafkaIO emits MAX_WATEMARK
### What happened?

When reading data from Kafka with legacy Read, MAX_WATERMARK is emitted when the source is not completed.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by je-ik**
Closes #30050 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by je-ik** [comment]
R: @Abacn @JozoVilcek @dmvk

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by JozoVilcek** [comment]
lgtm

**Review by JozoVilcek — APPROVED** [review]

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by Abacn** [comment]
Hi, we have migrated to GitHub Action and the way to run PostCommit has changed due to some limitation of GHA. To run Flink ValidatesRunner PostCommit, add an empty file named `.github/trigger_files/beam_PostCommit_Java_ValidatesRunner_Flink.json` and attach to your PR, see https://github.com/apache/beam/tree/master/.github/workflows#comment-triggering-support

**Comment by je-ik** [comment]
Ah, thanks.

**Comment by Abacn** [comment]
though the Jenkins is still running a few job (with only a couple of workers)

For this PR, the result is in https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_PR/511/

**Comment by Abacn** [comment]
testTeardownCalledAfterExceptionInStartBundleStateful  is a known flaky test: #19814

**Review by Abacn — APPROVED** [review]
The newly added test passed: https://ge.apache.org/s/i3siknxbqnh5a/tests/task/:runners:flink:1.16:test/details/org.apache.beam.runners.flink.translation.wrappers.streaming.io.source.unbounded.FlinkUnboundedSourceReaderTest/testWatermarkOnEmptySource?top-execution=1

**Pull request merged**
