### PR TITLE
Do not relocate generated Model Classes

### PR DESCRIPTION
**Pull request by tgroh**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Doing so with this pattern breaks the clients, as the shade plugin will
rewrite the gRPC method name as well, which servers do not implement.
All calls will then be broken.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles @lukecwik (any)

**Comment by lukecwik** [comment]
It was actually protobuf that relies on the strings during converting text to proto.

**Comment by kennknowles** [comment]
That's a different thing entirely, but also an issue. Probably a good reason not to use the text format, since it doesn't benefit from proto's compatibility features, even when it would be easy to do so.

**Comment by tgroh** [comment]
run java precommit

**Comment by tgroh** [comment]
run java precommit

**Pull request closed without merging**
