### PR TITLE
Add support repeated template invocations for BQIO.Write

### PR DESCRIPTION
**Pull request by sammcveety**

### CODE REVIEW

**Comment by sammcveety** [comment]
retest this please

**Comment by sammcveety** [comment]
R: @dhalperi

**Comment by sammcveety** [comment]
Test failures appear unrelated.

**Comment by dhalperi** [comment]
R: @tgroh 

Thomas, can you take a look at this? Very similar to the sharding stuff you did for TextIO.Write, I think.

**Comment by tgroh** [comment]
Please resolve the merge conflicts, however.

**Comment by sammcveety** [comment]
Done

**Comment by sammcveety** [comment]
retest this please

**Pull request closed without merging**
