### PR TITLE
Fix error and warnings on KafkaIO javadoc generation

### PR DESCRIPTION
**Pull request by iemejia**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @aviemzur

**Comment by iemejia** [comment]
For some context the current master is broken because of javadoc generation referring to a method that does not exist in the current version of Kafka (0.10.x). Yesterday some changes to support Kafka 0.11.x were introduced. This is a quickfix for this.

**Comment by aviemzur** [comment]
It looks like the `@see` used instead of the `@link` that existed before doesn't seem to work in this context (inside a `@param`).
Since the problem is that the `@link` is broken when the client is not dependent on Kafka 0.11+ consider instead of the original code based `@link` to link instead to Kafka [GitHub](https://github.com/apache/kafka/blob/0.11.0.0/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L549-L567)/[Javadoc](https://kafka.apache.org/0110/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html#sendOffsetsToTransaction(java.util.Map,%20java.lang.String))

**Comment by iemejia** [comment]
Good point, Changed to a link to the external documentation.

**Comment by aviemzur** [comment]
SGTM
CC: @rangadi

**Comment by aviemzur** [comment]
Retest this please.

**Comment by iemejia** [comment]
@rangadi I suppose just moving the version up would have fixed it too but didn't want to do that until I was sure it was the intended idea. We probably need a way to ensure that KafkaIO passes the tests with all the different versions. Extra question why kafka-clients is not provided or if we just move to version 0.11 it would cover the backward compatibility, e.g if I want to connect with a 0.9 instance ?

**Comment by rangadi** [comment]
@iemejia, Kafka versions was supposed to be upgraded to 0.11.0.1 in BEAM-2720 that went in yesterday. But looks like root pom changes got dropped just before merging (I must have dropped it during rebase and conflict resolution). I will sending a fix for that now.

KafkaIO support all the versions from 0.9 (that's missing pom update didn't cause build failure). May be better to move it to provided scope. Right now, if a user is building Beam manually they can set kafka.client.version (e.g. `mvn -pl sdks/java/io/kafka test -Dkafka.clients.version=0.9.0.1`).

**Comment by rangadi** [comment]
Sent pr #4001 to update kafka-clients version and to fix the warning with `@param`. `mvn javadoc:javadoc -pl sdks/java/io/kafka` looks good. Thanks.

**Pull request closed without merging**
