### PR TITLE
[BEAM-6855] Side inputs are not supported when using the state API

### PR DESCRIPTION
**Pull request by mtalhajamil**
Added test cases for `StatefulDoFnRunner` implementation for `DoFnRunner `in `SimplePushbackSideInputDoFnRunner`.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mtalhajamil** [comment]
Run Portable_Python PreCommit

**Comment by mtalhajamil** [comment]
R: @kennknowles 
R: @reuvenlax

**Comment by kennknowles** [comment]
Seems like good tests that prove the different DoFnRunner classes can be composed properly. I will let @reuvenlax take a closer look. If he is happy w/ the code then I think merging this piece now is good, and then next move on to support in the DirectRunner with a `@ValidatesRunner` test.

**Comment by mtalhajamil** [comment]
@kennknowles thanks ken for review. Isn't this [link to code](https://github.com/apache/beam/pull/9140/files#diff-04f8f7fac926e889fa8063060a0506d5R348) the test you require? I have provided Direct runner in my tasks while executing this test. Let me know if you want something else.

**Comment by mtalhajamil** [comment]
@reuvenlax can you please look into this PR.

**Comment by tvalentyn** [comment]
FYI @kennknowles will be OOO until next week. @reuvenlax could you provide feedback here please?

**Comment by je-ik** [comment]
FYI, changing this in DirectRunner (i.e. `SimplePushbackSideInputDoFnRunner` will use `StatefulDoFnRunner`) will manifest nondeterminism of state garbage collect timer (defined in `StatefulDoFnRunner`) and user timers (or any other timers, for that matter). This PR adds only tests for the `SimplePushbackSideInputDoFnRunner`, so I think it is fine, but if I understand it correctly, the goal is to inject `StatefulDoFnRunner` to `SimplePushbackSideInputDoFnRunner` in `runners-core`. I think that [BEAM-7520] (PR #8815) would be a prerequisite for that.

**Comment by mtalhajamil** [comment]
@je-ik as per discussion with @kennknowles [Link to jira discussion](https://issues.apache.org/jira/browse/BEAM-6855?focusedCommentId=16889000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16889000) 

As per my understanding testing `StatefulDoFnRunner` with `SimplePushbackSideInputDoFnRunner` was the target of this jira.

**Comment by je-ik** [comment]
My reaction was on
```
Then you will want to test that the DirectRunner and other runners are creating these correctly.
```
In current master, DirectRunner uses only `SimplePushbackSideInputDoFnRunner`, it doesn't use `StatefulDoFnRunner`. But - when you change that (e.g. [like this](https://github.com/rezarokni/beam/pull/2/commits/be83b387cc2249ab66bed9862c393d0b0d4bb430#diff-a9ce0e5a837aa74d2a0cf5b308651e75R96)) - then various strange behavior appears. It is related to timers in DirectRunner not being correctly ordered. PR #9190 fixes that.

**Comment by mtalhajamil** [comment]
Thanks @je-ik 

So, after your PR #9190 is merged we should run our tests again to see if these tests are working fine?

**Comment by je-ik** [comment]
No, I don't think that this PR (#9140 to be clear :)) is anyhow affected by #9190. What is - is that I assume, that the next step would be to use the tested behavior (that SimplePushbakcSideInputDoFnRunner works with StatefulDoFnRunner). That should be done only after the issue [BEAM-7520] is resolved (either by merging #9190 or in some other way, that depends on the result of the merge process of #9190).

**Comment by reuvenlax** [comment]
Is this meant to fix the bug, or just a prerequisite PR to add a test?

**Comment by mtalhajamil** [comment]
@reuvenlax as in discussion with Ken https://issues.apache.org/jira/browse/BEAM-6855?focusedCommentId=16889000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16889000 on jira & above comments by committers looks like the task of this jira was to add these tests.

**Comment by reuvenlax** [comment]
I don't think so. This functionality didn't work (accessing side inputs in
a stateful DoFn) and the task of the JIRA was to make it work. Sounds like
Ken said that the first step was to write tests?

**Comment by reuvenlax** [comment]
I think part of the confusion here is that Dataflow appears to use a different .code path for this - StreamingSideInputDoFnRunner

**Comment by xubii** [comment]
Run Dataflow ValidatesRunner

**Comment by salmanVD** [comment]
Run Java PreCommit

**Comment by salmanVD** [comment]
Run JavaPortabilityApi PreCommit

**Comment by kennknowles** [comment]
Hrmm. Actually merging the test and disabling it in all runners would have been a good step.

**Pull request closed without merging**
