### PR TITLE
[BEAM-7788] Add git scm extension to wipe workspace before cloning project

### PR DESCRIPTION
**Pull request by zachbadgett**
This change will wipe the workspace instead of doing a git clean before each job. This is important to prevent issues caused by jobs that could potentially create readonly files which can corrupt the workspace and cause ALL subsequence jobs to fail due to `git clean` returning an error.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by zachbadgett** [comment]
@udim

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run rat precommit

**Comment by udim** [comment]
Verified change in rat precommit log:
```
11:38:06 Wiping out workspace first.
```
And no `git clean` commands.
https://builds.apache.org/job/beam_PreCommit_RAT_Phrase/36/console

**Comment by kennknowles** [comment]
This change is a problem. It kills dependency caching, making all jobs slower and more dependent on flakily and redundantly pulling deps from maven central.

**Comment by kennknowles** [comment]
I recognize that the original problem was valid. This just isn't a workable solution given our infrastructure.

**Comment by kennknowles** [comment]
Notably I think gradle still puts its cache in the actual homedir, not in the workspace, so it is not wiped out. Only our maven-based builds were affected. Our verification that snapshot releases work is perma-red due to inability to reliably pull all deps. Moving maven cache to outside the workspace could make this OK.

**Comment by udim** [comment]
To make sure we're on the same page: this change only wipes the `src/` subdirectory in the workspace.
There is also another later change that wipes the whole workspace after the job is done. (https://github.com/apache/beam/pull/12326)

In any case, you could disable this behavior for the snapshot jobs, but it makes the build less hermetic.

**Comment by kennknowles** [comment]
If that is true, then this change is fine. But `wipeOutWorkspace` in Jenkins context typically means the Jenkins workspace, which would include `src/..`.

Hermeticity is good. But note that our employer's favorite hermetic build system caches aggressively and that is the only way it actually works at all.

**Comment by kennknowles** [comment]
Turns out I was completely wrong. The flaky process sets `.m2` to a subdirectory of a wiped out temp dir. Once that is fixed, we'll still need an outside-the-workspace location for the cache to avoid it being wiped out. But we'll reduce our downloads by O(# runners) by just fixing the script.

**Pull request merged**
