### PR TITLE
Optimize counters by reducing allocations

### PR DESCRIPTION
**Pull request by scwhittle**
- use forEach instead of requiring  Iterator/UnmodifiableIterator overhead
- optimize shortId cache hasing by just using MetricName as stepName is fixed
- reduce MetricKey objects
- avoid MetricsUpdate construction in getMonitoringData by directly processing maps

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @reuvenlax 

Saw a 1% total decrease for SDK in metrics related CPU for a nexmark pipeline

**Comment by reuvenlax** [comment]
LGTM

**Comment by reuvenlax** [comment]
run dataflow postcommit

**Comment by reuvenlax** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by reuvenlax** [comment]
run dataflow java postcommit

**Comment by reuvenlax** [comment]
Run PostCommit_Java_Dataflow

**Comment by scwhittle** [comment]
Failing test is [org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT.testReadWithDataBoost](https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Phrase/129/testReport/org.apache.beam.sdk.io.gcp.spanner/SpannerReadIT/testReadWithDataBoost/)
and is failing with some unrelated project permissions issue for DataBoost.

**Pull request merged**
