### PR TITLE
[BEAM-1297] Update maven build plugins and various build performance improvements

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by iemejia** [comment]
Since there seem not to be new issues after last week PR (
https://github.com/apache/beam/pull/1816) , I send here the rest of the changes:

**Comment by iemejia** [comment]
R: @dhalperi (sorry to bother you again, this is the follow up of the performance improvements for maven)

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by iemejia** [comment]
Build failed for unexpected reason, re-executing.

**Comment by iemejia** [comment]
retest this please

**Comment by davorbonaci** [comment]
This looks good to me, but for posterity, can you comment here in the PR on the individual meaning of each flag being added?

**Comment by iemejia** [comment]
Thanks Davor, The extra optimizations are the following:

Maven args:
```
--threads 1C   Executes 1 thread per core (Enables parallelism).
```
JVM arguments:
```
-client                 The JVM on linux uses by default the server mode. This flag forces the JVM to execute in client mode, this is useful because it takes less time to startup and maven forks and restart the JVM many times
-XX:+TieredCompilation  Enables Tiered Compilation. This improves startup time.
-XX:TieredStopAtLevel=1 Uses full optimization but not profiling (so it is faster).
```
Finally some references on speeding Maven and Tiered compilation.
Refs.
https://zeroturnaround.com/rebellabs/your-maven-build-is-slow-speed-it-up/
http://blog2.vorburger.ch/2016/06/improve-maven-build-speed-with-q.html
https://www.slideshare.net/maddocig/tiered
https://docs.oracle.com/javase/7/docs/technotes/guides/vm/performance-enhancements-7.html

**Comment by davorbonaci** [comment]
Any comment on the diff, say old runtime vs. new runtime?

**Comment by iemejia** [comment]
Feel free to squash everything, I did really tiny commits to make clear each intention. And please tell me if you think something else is missing.

**Comment by iemejia** [comment]
Thanks.

**Pull request closed without merging**
