### PR TITLE
[BEAM-3527] Adding a comment for ZERO element of DistributionResult.

### PR DESCRIPTION
**Pull request by pabloem**
I've decided to not rename the ZERO, because I get the feeling that IDENTITY might be even less clear (though I'm open to having my mind changed:) ). I've only added a comment to clarify its purpose.
cc: @bjchambers 
cc: @ClaireMcGinty

### CODE REVIEW

**Comment by robertwb** [comment]
+1 to changing your mind. Another alternative would be EMPTY. I though ZERO was the distribution with nothing but zeros in it.

**Comment by ClaireMcGinty** [comment]
@robertwb `EMPTY` could be good as it matches what [GaugeResult](https://github.com/apache/beam/blob/a39960b131674e6c1d120a971b91b37226c88414/sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/GaugeResult.java#L39) has -- although, still not a perfect analogue as `EmptyGaugeResult` just returns a value of -1.

**Comment by pabloem** [comment]
hmm how about we go with IDENTITY_ELEMENT ?

**Comment by ClaireMcGinty** [comment]
Sounds good to me!

**Comment by pabloem** [comment]
r: @kennknowles 
getting another reviewer

**Comment by kennknowles** [comment]
SGTM LGTM

**Pull request merged**
