### PR TITLE
[BEAM-1281] Encode GlobalWindow in one byte when it is the whole stream

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

See JIRA and inline comment for explanation. TL;DR empty encodings are pretty fragile. Many coders are sensitive to one byte addition, but this will not affect anything in the main element collections, as they are within a `WindowedValueCoder`. The motivating case is actually quite mundane.

### CODE REVIEW

**Comment by lukecwik** [comment]
Can't empty encodings be solved at the protocol level?

**Comment by kennknowles** [comment]
See the ticket for motivating particulars. It is possible to solve these at the protocol level in many ways. But that is not as good, for (at least) the following reasons:

1. We don't - and shouldn't - control all protocols. It is a principle hallmark of good work that it can be used in ways you never thought of. If the original code was written to be context-unaware, we wouldn't be having this discussion because everything would just work. It is very easy to concoct protocols and formats that are slightly better but require nonempty data elements. If you want to come up with some, play with ideas like "how many elements do these zero bytes represent? where are the zero-byte encoded elements in this list that also has non-empty elements? did I just receive an empty element over the wire? how do I block until an empty element is transmitted?" These all have workarounds via framing or sentinels but they can be more efficient without such.
2. Using a dummy byte as you suggest means that no user encoding can use that byte, so all encodings must be prefixed with a "non-empty" byte or else must just be larger because they cannot use the dummy byte. So everyone is penalized and this is just one case of 3. For textual base64 this works OK because it already wastes bits and there are characters available, but that is context-aware programming and I'd rather not make excuses for hacks when I could improve them.
3. Tracking empty vs nonempty encodings usually requires space for every encoded element whether or not it is empty, either with sentinel values or framing information. This is currently the case for Dataflow, the motivation behind ticket. There is a 1 byte penalty on every namespace because we tried to avoid a 1 byte penalty for `GlobalWindow`. It was certainly net negative. Using a spare dummy byte would work and probably end up unnoticeable, though it is in many tight loops so we'd have to measure.

I obviously thought of the natural approach you suggest, but decided not to do it. I might do it someday, with careful benchmarking of the cost/benefit, but might not bother.

I've worked around this issue for now; this PR is now largely code health and best practices.

**Comment by lukecwik** [comment]
If your trying to model more than one of something, why is it not wrapped in an iterable/list/container coder?

For the questions that you ask:
How many elements do these zero bytes represent?
Exactly one element, otherwise its wrapped in an iterable/list/container coder that provides the count/framing information.

Where are the zero-byte encoded elements in this list that also has non-empty elements?
For a list of several types, you need a coder which encodes what type is being used (which will take at least one bit even if the value it encodes represents zero bytes). There is no way to have a mixed list of types without typing information preceding each element.

Did I just receive an empty element over the wire? How do I block until an empty element is transmitted?
The protocol needs to represent end of file some how in a generic stream irrespective of how much data is sent. Assuming that always one byte will be sent is a poor choice for protocols.

**Comment by kennknowles** [comment]
The point of the questions is not that I don't know [many] answers to them. It is that they cannot be answered without otherwise-unnecessary metadata that almost certainly outweighs any potential savings.

**Comment by lukecwik** [comment]
The point that I'm bringing across is that protocols already have to deal with the issue of an end of file marker and if they represent a stream of elements must encode element boundaries themselves somehow. Any protocol that doesn't follow the above is broken in some small but fundamental use case so it doesn't make sense to require objects to encode to non-zero number of bytes.

**Comment by kennknowles** [comment]
I'm going to close this. It is pointed out that when an encoding context says "outer" it actually means "tail"; it is quasi-accurately documented but just inaccurately named. So there are plenty of situations where the outer context is actually nested within a larger structure that includes adequate framing to get some savings. Given this demonstration of > 0 cases where there is a benefit, we shouldn't make this change.

**Pull request closed without merging**
