### PR TITLE
[BEAM-8947] Fix Jenkins jobs using Flink cluster

### PR DESCRIPTION
**Pull request by mwalenia**
After the change in 8b859ab8a52778d1bc14ca76f2eef7c9e70d528d, Docker image name for Flink job server changed. This PR changes Jenkins jobs using it to account for this.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mwalenia** [comment]
Run seed job

**Comment by mwalenia** [comment]
Run Load Tests Python GBK Flink Batch

**Comment by mwalenia** [comment]
R: @kamilwu 
The Flink job I started passed the stage with Flink Job Server publication, meaning the issue got fixed. Success or failure of the test suite itself is out of scope of this PR :)

**Comment by kamilwu** [comment]
LGTM as long as the tests suite passes. Could you trigger the test once again? We shouldn't merge PRs with unsuccessful checks, no matter what's the cause of the problem

**Comment by kamilwu** [comment]
Assigning R: @lgajowy, who can help with merging the PR

**Comment by mwalenia** [comment]
Sure, I'll tag a committer after the test passes. I'm juggling two PRs with seed job needs, this might take a while. Thanks!

**Comment by mwalenia** [comment]
Run seed job

**Comment by mwalenia** [comment]
Run Load Tests Python GBK Flink Batch

**Comment by mwalenia** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by mwalenia** [comment]
Run seed job

**Comment by mwalenia** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by mwalenia** [comment]
Run seed job

**Comment by mwalenia** [comment]
Run Load Tests Python GBK Flink Batch

**Comment by mwalenia** [comment]
@lgajowy Can we merge this? The GBK test timed out, but Combine passed and both created their Flink clusters correctly.

**Comment by lgajowy** [comment]
Run Load Tests Python GBK Flink Batch

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
I see that the problem described in JIRA is fixed but I'm concerned about the failing python GBK suite. Clearly the clusters were created correctly so I'm merging this PR. 

@mwalenia could you create an issue for the other problem that the GBK suite suffers (https://builds.apache.org/job/beam_LoadTests_Python_GBK_Flink_Batch_PR/53/console)?

**Comment by lgajowy** [comment]
Run Load Tests Python GBK Flink Batch

**Comment by mwalenia** [comment]
Sure, I created a JIRA for this [here](https://issues.apache.org/jira/browse/BEAM-8961)

**Pull request merged**
