### PR TITLE
Enable UsesStrictTimerOrdering ValidatesRunner tests on Spark Classic Runner

### PR DESCRIPTION
**Pull request by iemejia**
Seems we were excluding this set of tests even if they were passing for the Batch case.
R: @aromanenko-dev

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
