### PR TITLE
sync-up DSL_SQL from Master

### PR DESCRIPTION
**Pull request by XuMingmin**
pull latest code from `master` branch to `DSL_SQL` branch.

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @davorbonaci 
CC: @jbonofre  @xumingming

**Comment by XuMingmin** [comment]
@davorbonaci, could you merge this directly? I'll follow with another PR to solve the errors.

**Comment by davorbonaci** [comment]
Sure -- merged (since this is a feature branch). Please fix it up sooner rather than later.

**Comment by davorbonaci** [comment]
Merged; please close.

**Pull request merged**
