### PR TITLE
Remove trailing whitespace from blog to fix precommit

### PR DESCRIPTION
**Pull request by damccorm**
This fixes the breakages introduced by #24951 by removing trailing whitespace. It is an alternative to #25048 which removes the rule.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Whitespace PreCommit

**Review by Abacn — APPROVED** [review]
ah I see, the point is (two space) and (two new line) have the same effect.
would you like taking the chance to fix old release notes where new lines in List of Contributors not rendering (e.g. either add another new line as 2.44.0 release note, or add a comma separator or so)

**Comment by lukecwik** [comment]
I'm happy with this as well and I'm going to merge this to get a green signal. We can always revert and remove the whitespace check in the future if people like the alternative more.

**Comment by lukecwik** [comment]
The [website](https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/10348/) and [whitespace](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Commit/10449/) checks passed, just delayed update here.

**Comment by kennknowles** [comment]
This alters `<br />` to `<p />` does it not?

**Pull request merged**
