### PR TITLE
GA Migration Java PreCommit

### PR DESCRIPTION
**Pull request by MarcoRob**
As part of the migration of Pre-commit and Postcommit Jobs from Jenkins to GA in self-hosted runners, this PR contains:

- Migrated workflow [job-precommit-java](https://github.com/apache/beam/blob/096fb6900a747aff7ae21865d578dab8157ea379/.github/workflows/job-precommit-java.yml)

The migrated workflows were removed from [.test-infra/jenkins/README.md](https://github.com/apache/beam/blob/096fb6900a747aff7ae21865d578dab8157ea379/.test-infra/jenkins/README.md) and added to [CI.md](https://github.com/apache/beam/blob/096fb6900a747aff7ae21865d578dab8157ea379/CI.md)

`DO NOT MERGE` until the effort to use self-hosted runners is completed https://github.com/apache/beam/pull/22703
These workflows use base actions listed in https://github.com/apache/beam/pull/23109 (Dependency)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by MarcoRob** [comment]
Hi @damccorm 
I am reaching out to validate the current approach for the `Java Pre-commit Job`. Right now we are handling the tests of the workflow in a matrix (https://github.com/apache/beam/blob/096fb6900a747aff7ae21865d578dab8157ea379/.github/workflows/job-precommit-java.yml). This allows us to have one job per test and be able to run them individually in case they fail, but this also means that for each test inside the matrix one runner/pod will be generated.
So for example, the way we separated the JavaPrecommit workflow (tests listed inside a matrix), the total number of jobs/runners will be 40ish.
If we add just one job for all the tests, only one runner will be created, but we lose the option of executing only the test/job that failed. 
I would like to know your thoughts on this matter. Ty
cc: @fernando-wizeline @benWize @andoni-guzman

**Comment by MarcoRob** [comment]
@damccorm In another matter for the current workflow 
We got the following reports `Errorprone, Java and SpotBugs`. In the GA we don’t have a straightforward process (the plugins for errorprone, java & spotbugs) since we don’t have any plugins as in Jenkins for this.
As a proposal, we are thinking that we can leave the GA for java pre-commit and as well the Jenkins job meanwhile we continue working on adapting the job.

Do you have any thoughts as well on this matter? 
Ty

**Comment by damccorm** [comment]
> Hi @damccorm
I am reaching out to validate the current approach for the Java Pre-commit Job. Right now we are handling the tests of the workflow in a matrix (https://github.com/apache/beam/blob/096fb6900a747aff7ae21865d578dab8157ea379/.github/workflows/job-precommit-java.yml). This allows us to have one job per test and be able to run them individually in case they fail, but this also means that for each test inside the matrix one runner/pod will be generated.
So for example, the way we separated the JavaPrecommit workflow (tests listed inside a matrix), the total number of jobs/runners will be 40ish.
If we add just one job for all the tests, only one runner will be created, but we lose the option of executing only the test/job that failed.
I would like to know your thoughts on this matter. Ty
cc: @fernando-wizeline @benWize @andoni-guzman

I think my only concern here is that any build steps will have to be run for every single worker. Could we consider having 1 build job that runs common steps that build any artifacts and [persists them](https://levelup.gitconnected.com/github-actions-how-to-share-data-between-jobs-fc1547defc3e) so that later jobs just have to download the artifact and run?

> We got the following reports Errorprone, Java and SpotBugs. In the GA we don’t have a straightforward process (the plugins for errorprone, java & spotbugs) since we don’t have any plugins as in Jenkins for this.
As a proposal, we are thinking that we can leave the GA for java pre-commit and as well the Jenkins job meanwhile we continue working on adapting the job.

I think leaving those out initially should be ok, and we can keep running those in Jenkins until we figure out a GitHub Actions solution to the problem

**Comment by MarcoRob** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]

**Comment by damccorm** [comment]
LGTM, thanks!

**Pull request closed without merging**
