### PR TITLE
[BEAM-8474] A microbenchmark for Python FnApiRunner:

### PR DESCRIPTION
**Pull request by pabloem**
Overall runtime of this microbenchmark is about one minute.

This runs a series of N parallel pipelines with M parallel stages each. Each
stage does the following:

1) Put all the PCollection elements in state
2) Set a timer for the future
3) When the timer fires, change the key and output all the elements downstream

Results:
```
python -m apache_beam.tools.fn_api_runner_microbenchmark
     1 element  3.97874 sec
   101 elements 5.81925 sec
   201 elements 6.12566 sec
   301 elements 6.57774 sec
   401 elements 7.43154 sec
   501 elements 7.97614 sec
   601 elements 8.63536 sec
   701 elements 9.10238 sec
   801 elements 9.17786 sec
   901 elements 10.0178 sec

Fixed cost   4.765602442423502
Per-element  0.00017222933748583773
R^2          0.9607312619599335
```

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by pabloem** [comment]
r: @boyuanzz

**Comment by boyuanzz** [comment]
Thanks for starting to create microbenchmark for more components! Would you mind explaining more about what kind of regression this microbenchmark trying to catch? Regression of core SDK component? SDK harness? or just FnApiRunner?

**Comment by pabloem** [comment]
This is for the Fn API runner. I'm going to be making changes to it, and I want to make sure that performance will not worsen : )

**Comment by tvalentyn** [comment]
Consider reusing https://github.com/apache/beam/blob/51efa2efbd850838092d9b4f5db12da1eb54d6e6/sdks/python/apache_beam/tools/utils.py#L47, you can look at coders_microbenchmark for an example.

**Comment by pabloem** [comment]
Thanks for the tip Valentyn. I'll add that

**Comment by pabloem** [comment]
Hm I think `BenchmarkConfig` runs the benchmark multiple times on a fixed size. I think I prefer running the varying sizes to get a linear regression of runtime vs number of elements. That allows to extract the per-element overhead, and the fixed cost of running the NxM stages...

**Comment by tvalentyn** [comment]
> Hm I think `BenchmarkConfig` runs the benchmark multiple times on a fixed size. I think I prefer running the varying sizes to get a linear regression of runtime vs number of elements. That allows to extract the per-element overhead, and the fixed cost of running the NxM stages...

Linear regression sounds like something that can be reused in other benchmarks, so you can consider generalizing the launcher in utils.py to allow that.

**Comment by pabloem** [comment]
alright. It seems reasonable. I'll look into that monday.

**Comment by pabloem** [comment]
@tvalentyn I've added a BenchmarkConfig class that does linear regression. LMK what you think!

@boyuanzz lmk what you think about the benchmark itself : )

**Comment by pabloem** [comment]
Results:
```
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 1 of 10, per element time cost: 3.6778 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 2 of 10, per element time cost: 0.053498 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 3 of 10, per element time cost: 0.0299434 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 4 of 10, per element time cost: 0.0211154 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 5 of 10, per element time cost: 0.0170031 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 6 of 10, per element time cost: 0.0150809 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 7 of 10, per element time cost: 0.013218 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 8 of 10, per element time cost: 0.0119685 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 9 of 10, per element time cost: 0.0107382 sec
run_single_pipeline, 1 element(s) at start, 100 growth per run: run 10 of 10, per element time cost: 0.0103208 sec


Fixed cost   4.537164939085642
Per-element  0.005474923321695039
R^2          0.9518956932309706
```

**Comment by boyuanzz** [comment]
> Results:
> 
> ```
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 1 of 10, per element time cost: 3.6778 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 2 of 10, per element time cost: 0.053498 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 3 of 10, per element time cost: 0.0299434 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 4 of 10, per element time cost: 0.0211154 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 5 of 10, per element time cost: 0.0170031 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 6 of 10, per element time cost: 0.0150809 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 7 of 10, per element time cost: 0.013218 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 8 of 10, per element time cost: 0.0119685 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 9 of 10, per element time cost: 0.0107382 sec
> run_single_pipeline, 1 element(s) at start, 100 growth per run: run 10 of 10, per element time cost: 0.0103208 sec
> 
> 
> Fixed cost   4.537164939085642
> Per-element  0.005474923321695039
> R^2          0.9518956932309706
> ```

Changes look good to me. I would attach this perf result and suggested regression rate into fn_api_runner_microbenchmark.py. 
Would you mind explaining a little bit more on choosing `Create`, `GroupByKey` and `Pardo` with `Timer` to construct pipeline? Which particular piece of FnApiRunner that you want to benchmark?

**Comment by pabloem** [comment]
I've added documentation, but to answer your question Boyuan, what the docs say:

This microbenchmark attempts to measure the overhead of the main data paths
for the FnApiRunner. Specifically state, timers, and shuffling of data.

I am planning to make changes to how stages and bundled get scheduled for execution, and I want to make sure that I am not increasing the overhead of scheduling bundles / data exchange in the runner.

**Comment by pabloem** [comment]
Done and done. Merging. Thanks!

**Pull request merged**
