### PR TITLE
[BEAM-3164] Flush stderr on failures

### PR DESCRIPTION
**Pull request by holdenk**
Flush stderr on failures generating protos.

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by aaltay** [comment]
R: @robertwb

**Comment by robertwb** [comment]
Jenkins: retest this please

Were there logs missing without these flushes?

**Comment by holdenk** [comment]
@robertwb sometimes

**Comment by robertwb** [comment]
Odd. Well, this can't hurt. LGTM.

**Pull request merged**
