### PR TITLE
Add cron job to trigger Java JMH micro-benchmarks weekly 

### PR DESCRIPTION
**Pull request by mosche**
Add cron job to trigger Java JMH micro-benchmarks weekly on Sundays (addresses #22238).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
Run Java Jmh benchmarks

**Comment by mosche** [comment]
Run Java Jmh benchmarks

**Comment by mosche** [comment]
Run Java Jmh benchmarks

**Comment by mosche** [comment]
Run Java Jmh benchmarks

**Comment by apilloud** [comment]
Our default is to run jobs like this every 6 hours. What are the constraints that limit this to weekly?

(Also you need to run the seed job to get your Jenkins changes to load. I believe `Run Seed Job` worked in the past, but you might need to invoke it via the Jenkins UI.)

**Comment by mosche** [comment]
Run Seed Job

**Comment by mosche** [comment]
Run Java Jmh benchmarks

**Comment by mosche** [comment]
@apilloud Thanks a lot! The "problem" with JMH benchmarks is that they take a massive amount of time. They are running a large number of iterations including various forks and warmups to produce a more stable and accurate number. 

With the current (default) JMH settings these would run for ~ 14 hours:
```
~100 benchmarks * 5 forks * (5 warmup iterations + 5 measurement iterations) * 10 seconds
```

If using just 3 forks it's running for ~ 8.5 hours, which seems more reasonable.
Later, once we have some numbers, we might be able to reduce the number of iterations slightly and see how that impacts (stability of) results. 
cc @lukecwik

**Comment by mosche** [comment]
Run Seed Job

**Review by lukecwik — APPROVED** [review]

**Comment by lukecwik** [comment]
It would be great to run this daily or every 2 days. @mosche or @apilloud, do you know how busy or perf machine is already?

**Comment by apilloud** [comment]
Run length of over ~3 hours is going to be disruptive to existing tests regardless of run length. I think the behavior of Jenkins is to just run tests less frequently? Daily would be a good start. Our current tests run every 6 hours and it looks like we are busy ~25% of the time: https://ci-beam.apache.org/label/beam-perf/load-statistics?type=hour

**Comment by lukecwik** [comment]
We could easily split the job into two JMH runs since there are two JMH projects currently. We can also split it very finely if we utilize `-Pbenchmark=...` and run one suite at a time.

**Comment by mosche** [comment]
Sorry @lukecwik, I was off for a couple of days. Thanks for merging 👍 

> We could easily split the job into two JMH runs since there are two JMH projects currently. 

The benchmarks of core take ~ 7h, compared to ~ 1,5h for the fn harness. That won't be enough yet.

> We can also split it very finely if we utilize -Pbenchmark=... and run one suite at a time.

For parametrized benchmarks runtimes vary a lot, but it would certainly be possible to split the benchmarks into equal sized chunks this way. Though, I'm a bit worried that this isn't maintainable long term. Of course it doesn't have to be perfect, but every new benchmark has to be added manually and scheduled appropriately...

I'll think a bit further about it.

**Comment by lukecwik** [comment]
I agree that `-Pbenchmark=` isn't a great solution because of how much maintenance it would take.

**Comment by mosche** [comment]
Screenshot 2022-11-08 at 14 54 26

@lukecwik looking at the benchmark runtimes, we could split the benchmarks into 3 groups and run them 2/3 times weekly
 - ByteStringOutputStreamBenchmark: Tue, Sat
 - GetterBasedSchemaProviderBenchmark: Thu, Sun
 - Everything else: Mon, Wed, Fri
 
I was briefly looking at implementing this, but without a plugin to conditionally run steps (`conditionalStep`) this would have to be implemented as 3 jobs (or use a shell step to trigger gradle tasks, but loosing all the default switches). Thoughts?

**Comment by mosche** [comment]
Here's the respective dashboard
http://metrics.beam.apache.org/d/kllfR2vVk/java-jmh-benchmarks?orgId=1&from=now-34d&to=now

**Comment by lukecwik** [comment]
Do you think we can get it listed on the getting started page http://metrics.beam.apache.org/d/1/getting-started?orgId=1 ?

**Comment by mosche** [comment]
> Do you think we can get it listed on the getting started page http://metrics.beam.apache.org/d/1/getting-started?orgId=1 ?

Absolutely, wasn't aware of the the necessary tag 👍 See  https://github.com/apache/beam/pull/24335

**Pull request merged**
