### PR TITLE
[BEAM-6183] BigQuery insertAll API request rate is not properly controlled

### PR DESCRIPTION
**Pull request by ihji**
add a rate limiter that dynamically adjusts insertAll submission rate below a given rate limit quota.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by chamikaramj** [comment]
Can we implement shared backoff across threads as a solution to https://issues.apache.org/jira/browse/BEAM-6183 before this ?

I think that should fix the bulk of the problem (sending too many requests to BQ when quota errors are hit).

Looks like you are trying to implement client-side throttling for BQ in this PR which could result in unintended performance issues in some cases.

**Comment by ihji** [comment]
I ran a quick benchmark for 4 different implementations. The benchmark program is a simple streaming pipeline that generates random integer numbers and inserts them into BigQuery table. The number of workers was 4 and running time was 20 minutes on DataflowRunner.

## Current master
- writer wall time: 11 hr 0 min 56 sec
- bytes_written: 1,281,740,388 bytes

##  Dynamic throttling on top of current master
- writer wall time: 15 hr 50 min 35 sec
- bytes_writtern: 1,119,466,932 bytes

## Shared backoff on top of current master
- writer wall time: 8 hr 43 min 59 sec
- bytes_written: 536,049,960 bytes

## Backoff all IOExceptions PR #7189 
- writer wall time: 13 hr 34 min 5 sec
- bytes_written: 1,374,636,336 bytes

Some observations:
- #7189 shows better performance than current master since there's no total failure of worker which delays a task for a whole bundle for at least 10 seconds
- The best performance can be achieved by pushing the BigQuery backend to its limit (like the current implementation with no rate controlling). However, it generates lots of error messages every second and also creates unnecessary overheads on BigQuery backend
- Dynamic throttling underperforms no throttling by 20 percent but generates near-zero error messages about exceeded rate limit

**Comment by ihji** [comment]
IMHO, it's better to just stick to the current implementation and add dynamic throttling as an optional parameter so a user can choose the better performance or keeping them under the quota without verbose error messages.

**Comment by ihji** [comment]
Won't fix. Closing.

**Pull request closed without merging**
