### PR TITLE
PreCommit_Portable_Python fix: use double quotes when using embedded values

### PR DESCRIPTION
**Pull request by ahmedabu98**

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Portable_Python PreCommit

**Comment by ahmedabu98** [comment]
R: @AnandInguva

**Review by AnandInguva — APPROVED** [review]

**Comment by ahmedabu98** [comment]
R: @tvalentyn

**Comment by ahmedabu98** [comment]
@Abacn

**Comment by Abacn** [comment]
run seed job

**Pull request merged**
