### PR TITLE
Upgrade Avro dependency to version 1.8.2

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
Following the slack discussion on the Avro issue with common-compress I noticed we were not using the latest version of the 1.8.x branch.

R: @dhalperi

**Comment by iemejia** [comment]
Retest this please

**Comment by iemejia** [comment]
Retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
R: @jbonofre

**Pull request merged**
