### PR TITLE
[BEAM-8935] Fail fast if sdk harness startup failed.

### PR DESCRIPTION
**Pull request by sunjincheng121**
Currently the runner waits for the sdk harness to startup blockingly until the sdk harness is available or timeout occurs. The timeout is 1 or 2 minutes. If the sdk harness startup failed for some reason, the runner may be aware of it after 1 or 2 minutes. This is too long.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by sunjincheng121** [comment]
R: @tgroh

**Comment by sunjincheng121** [comment]
Run Java PreCommit

**Comment by sunjincheng121** [comment]
R: @lukecwik

**Comment by sunjincheng121** [comment]
Good catch! I have not found direct documentation for this question. However, I did find some useful information which maybe helpful.

According to the [doc](https://docs.docker.com/engine/api/v1.40/#operation/ContainerList), the status of a docker container could be one of `created, restarting, running, removing, paused, exited, dead`. So I think we only need to consider if the status of a container could be `created` in race conditions after executing `docker run`(for the other status, it's obvious that there is something wrong). According to [StackOverFlow](https://stackoverflow.com/questions/37744961/docker-run-vs-create), `docker run = docker create + docker start`. I guess that `docker create` will change the state of container to `created` and `docker start` will change the state of container to `running`. It is further explained in [StackOverFlow](https://stackoverflow.com/questions/43734412/what-does-created-container-mean-in-docker) in which case the status of docker container could be "created": `docker create` and `docker run`. For `docker run`, it says that `Docker container has been created using docker run but it hasn't been able to start successfully`. So we can infer that if the docker status become `created` after `docker run`, the docker container isn't started successfully.
So, I think current logic would be fine :) What do you think?

**Comment by boyuanzz** [comment]
Hey, I found this PR may break [beam_PostCommit_Py_ValCont](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/). The first failure shown up at: https://builds.apache.org/job/beam_PostCommit_Py_ValCont/5172/#showFailuresLink.

**Comment by boyuanzz** [comment]
Create JIRA issue here: https://issues.apache.org/jira/browse/BEAM-9137(this is a release blocker for 2.19.0)

**Comment by sunjincheng121** [comment]
Thanks for your info @boyuanzz , I would like to make a test for it. https://github.com/apache/beam/pull/10623

**Comment by sunjincheng121** [comment]
It seems that the test error is not caused by this commit. @boyuanzz

**Pull request merged**
