### PR TITLE
[BEAM-4264] Fixed test Cloud Spanner instance name.

### PR DESCRIPTION
**Pull request by mairbek**
R: @chamikaramj

### CODE REVIEW

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Looks like following test still failed but has a different error message. Is there another issue ?

https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/324/testReport/org.apache.beam.sdk.io.gcp.spanner/SpannerWriteIT/testFailFast/

**Comment by chamikaramj** [comment]
I don't think that change is new (I might be wrong). Exceptions that are caught by runner (and result in workitem failures) are wrapped in UserCodeException. If you catch this in a ParDo you'll get the original exception.

**Comment by mairbek** [comment]
Here is the exception I'm getting locally
```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Value must not be NULL in table users.

	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:349)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:319)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:210)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:66)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:346)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:328)
	at org.apache.beam.sdk.io.gcp.spanner.SpannerWriteIT.testFailFast(SpannerWriteIT.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:317)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by mairbek** [comment]
So the problem here is that I was running the test with `DirectRunner` and the test is using `DataflowRunner`. `DirectRunner` truncates the exception stack, I'm updating test matcher.

**Comment by chamikaramj** [comment]
LGTM

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
I've added some logging, let's see if that helps

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
Run Java PostCommit

**Comment by mairbek** [comment]
@chamikaramj Spanner tests passed, https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/349/testReport/org.apache.beam.sdk.io.gcp.spanner/

**Comment by mairbek** [comment]
rebased commits

**Comment by chamikaramj** [comment]
Retest this please

**Comment by jkff** [comment]
Merged because the only failure is in an unrelated test.

**Pull request merged**
