### PR TITLE
[BEAM-10781] Add PTransformOverride.get_replacement_transform_for_applied_ptransform()

### PR DESCRIPTION
**Pull request by yifanmai**
`PTransformOverride.get_replacement_transform_for_applied_ptransform()` is a new method that replaces `PTransformOverride.get_replacement_transform()`. This new method provides access to the `AppliedPTransform` when constructing the replacement transform, whereas the old method only provides access to the `PTransform`.

- Introduces `PTransformOverride.get_replacement_transform_for_applied_ptransform(self, applied_ptransform)`. The user can override this to provide a replacement `PTransform` using the input `AppliedPTransform`.
- Provides a default implementation of this method that calls `PTransformOverride.get_replacement_transform()` for backwards compatibility.
- Deprecates `PTransformOverride.get_replacement_transform()`.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
Build python source distribution and wheels
Python tests

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by yifanmai** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
Sorry about the delay. Will get to these by the end of the work.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by yifanmai** [comment]
I seem to be running into the same issues as in #12655 with failing tests; how should I resolve this?

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Are test failures unrelated ?

**Comment by chamikaramj** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Run PythonDocker PreCommit

**Comment by chamikaramj** [comment]
Run Python 3.5 PostCommit

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
Retest this please

**Comment by yifanmai** [comment]
Precommits (besides codecov) look good.

**Comment by yifanmai** [comment]
@chamikaramj Can this be merged?

**Comment by chamikaramj** [comment]
Run Python 3.5 PostCommit

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
Let's run post-commits as well.

**Comment by chamikaramj** [comment]
Seems like failure is related: https://ci-beam.apache.org/job/beam_PostCommit_Python35_PR/161/testReport/junit/apache_beam.examples.wordcount_it_test/WordCountIT/test_wordcount_fnapi_it/

**Comment by yifanmai** [comment]
Run Python PreCommit

**Comment by yifanmai** [comment]
Run Python 3.5 PostCommit

**Comment by yifanmai** [comment]
@chamikaramj could you re-run post submits? I fixed a typo that was causing the breakage.

**Comment by chamikaramj** [comment]
Run Python 3.5 PostCommit

**Comment by yifanmai** [comment]
3.5 PostCommit looks good

**Comment by chamikaramj** [comment]
Retest this please

**Comment by yifanmai** [comment]
The failures are on `DataChannelTest.test_time_based_flush_grpc_data_channel` which does not seem related to the PR. @chamikaramj is this ready for merge or is there more testing needed?

**Comment by chamikaramj** [comment]
PreCommit test suite passed and macos failure seems to be unrelated - https://issues.apache.org/jira/browse/BEAM-10866.

**Comment by yifanmai** [comment]
Awesome, thanks for your help!

**Pull request merged**
