### PR TITLE
[BEAM-13767] Remove eclipse plugin as it generates a lot of unused tasks

### PR DESCRIPTION
**Pull request by y1chi**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by y1chi** [comment]
Run Java PreCommit

**Comment by y1chi** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by y1chi** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by y1chi** [comment]
Run Python_PVR_Flink PreCommit

**Comment by y1chi** [comment]
Run Python_PVR_Flink PreCommit

**Comment by y1chi** [comment]
R: @kennknowles 

Ken, is it ok to remove this plugin? I think the recommended IDE is Intellij and newer eclipse version seem to have better gradle project support https://projects.eclipse.org/projects/tools.buildship?

**Comment by kennknowles** [comment]
I think ask on the dev list (if you haven't already).

**Comment by y1chi** [comment]
thread with dev list https://lists.apache.org/thread/djq0prysk3zpx1vvqo77b4f6y88oqyrd

IIUC removing this plugin is ok as long as developer can import beam into eclipse, which I have verified.

**Comment by aaltay** [comment]
What is the next step on this PR?

**Comment by kennknowles** [comment]
Nobody responded to say they cared, so I think it can be removed.

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
