### PR TITLE
Bump Python SDK harness container version to use with Beam HEAD

### PR DESCRIPTION
**Pull request by tvalentyn**
This should fix BEAM-3196.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by angoenka** [comment]
Run Python Performance Test

**Comment by tvalentyn** [comment]
Postcommit suite does not run against this PR - it runs against master. We can see in the job logs that we are still using old container. Verified locally that offending postcommit test passes.
cc: @angoenka 
R: @aaltay  - please merge this when you have a chance. Thank you.

**Comment by aaltay** [comment]
LGTM. Thank you. Please monitor tests after the merge.

**Comment by tvalentyn** [comment]
Postcommit suite still fails, and looking at the logs, the change has not been picked up  - we are still using old container name that is no longer in the code.

**Comment by tvalentyn** [comment]
Postcommit issue is tracked in https://issues.apache.org/jira/browse/BEAM-3120.

For the record, to verify the test manually, run in a virtual environment: 

python setup.py sdist
pip install -e .[gcp,test]

PROJECT="myorg:myproject";\
GCS_LOCATION="gs://mybucket";\
SDK_LOCATION=$(find dist/apache-beam-*.tar.gz);\
nosetests ./apache_beam/examples/wordcount_it_test.py:WordCountIT.test_wordcount_fnapi_it --test-pipeline-options=" \
    --runner=TestDataflowRunner \
    --project=$PROJECT \
    --staging_location=$GCS_LOCATION/staging-it \
    --temp_location=$GCS_LOCATION/temp-it \
    --output=$GCS_LOCATION/py-it-cloud/output \
    --sdk_location=$SDK_LOCATION \
    --num_workers=1 \
    --sleep_secs=20"

**Pull request closed without merging**
