### PR TITLE
Enable githubCommitNotifier for post commits

### PR DESCRIPTION
**Pull request by apilloud**
This should enable status for post commits run on master.

### CODE REVIEW

**Comment by apilloud** [comment]
@jasonkuster Can you take a look?

**Comment by jasonkuster** [comment]
LGTM

**Comment by apilloud** [comment]
This isn't working because credentials aren't plumbed through. I've opened a revert, will follow up with Apache Infra.

**Comment by lgajowy** [comment]
Ok, thanks!

**Pull request merged**
