### PR TITLE
Move Triggers from sdk-core to runners-core-construction

### PR DESCRIPTION
**Pull request by dhalperi**
Converting to/from Runner API is not the SDK API surface.

R: @tgroh @kennknowles 

I think this may break DataflowRunner, in which case I'll add back `@Deprecated Triggers`

### CODE REVIEW

**Comment by kennknowles** [comment]
I like this as an API reduction for now, but can an SDK really not own producing a Beam graph?

**Comment by dhalperi** [comment]
@kennknowles Yes, an SDK should be able to produce its graph but it might do so using a tool in the construction-core module or a third module that shades and bundles everything.

Certainly, protobuf cannot be on the public API surface of sdk-core at first stable release -- it interferes with the runtime environment too much.

**Comment by dhalperi** [comment]
retest this please

**Comment by dhalperi** [comment]
retest this please

**Pull request closed without merging**
