### PR TITLE
[BEAM-3582] Rename BeamRecord to BeamRow.

### PR DESCRIPTION
**Pull request by reuvenlax**
BeamRecord is a confusing name (as all elements are "records"). Row is a better term, that matches common terminology.

R: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
Definitely has my full support. What do you think, @xumingming @XuMingmin @takidau @akedin ?

**Comment by reuvenlax** [comment]
We could do Row. I just worried that so many other packages have Row
classes that it would create confusion.

**Comment by XuMingmin** [comment]
I like `BeamRow` vs `Row` as @reuvenlax mentioned.

**Comment by reuvenlax** [comment]
Given that we may often be converting from one Row to another, it seems
likely. Also guava has a Row class I believe.

**Comment by takidau** [comment]
Guava appears to have Table and Cell. I don't immediately see Row.

**Comment by kennknowles** [comment]
I also prefer `Row`. It isn't so bad to have to say `org.apache.beam.values.Row` or `some.other.package.Row` in those cases where you are using both in the same file (too bad about the useless `values` package making that name longer).

**Comment by kennknowles** [comment]
Either one makes me pretty happy.

**Comment by kennknowles** [comment]
Maybe we should take this to the `dev@` list for some real bikeshedding :-)

**Comment by robertwb** [comment]
Having dealt with this before (actually, I think it was literally a `Row` class) I can say that having to fully qualify names is painful in Java. One workaround is to put it in a nested class, such that it can be imported as just Row or used with a (shorter) qualification as needed. My preference would be to just keep the Beam prefix on the class itself. My $0.02, not held to strongly. 

As for `Record` -> `Row`, I was an instigator of the original name `Record` to try to denote that this wasn't bound to SQL alone (though my biggest concern was pulling it up to a top-level Beam value rather than keeping it in the SQL namespace). I think of a Record as an element with fields, which is what is being specified here. But again, if Row makes more sense to folks, that's fine by me.

**Comment by reuvenlax** [comment]
The problem with Record is that we already refer to all elements in the
Beam model as "records."

**Comment by reuvenlax** [comment]
Any conclusions here?

**Comment by robertwb** [comment]
I'm -0 on the move from Record to Row, -0.5 on dropping the Beam prefix,
and +1 on getting this in without a huge amount of bikeshedding.

**Comment by takidau** [comment]
The thing I like about Row vs Record (in addition to being easier to type :-) is that it carries with it an implication of there being columns somewhere. So as we add more columnar support directly into Beam (regardless of whether SQL is in play or not), the Row name would provide a little hint that there are columnar things lurking around as well.

For me, Row > Record > BeamRow > BeamRecord. But I don't feel super strongly, and will live with BeamRecord if we just stick with that. So big +1 to not bikeshedding to death.

**Comment by reuvenlax** [comment]
Ok, let's come to a conclusion here.

**Comment by XuMingmin** [comment]
+1 to keep the Beam prefix, I would take the *duplication* so users are clear that it's related with Beam, there're so many classes named as Row. 
either BeamRow or BeamRecord is good to me.

**Comment by kennknowles** [comment]
A pull request isn't really the right place for a vote, but here's the tally, if we accept half votes:

`BeamRow`: 2.5 @XuMingmin @reuvenlax  @robertwb (half)
`Row`: 2.5 @takidau @akedin @kennknowles (half)

So that is perfectly unhelpful :-)

**Comment by lukecwik** [comment]
+1 to Row

**Comment by kennknowles** [comment]
I just did a couple queries in the public GitHub data set and there's Hive and Cassandra and SparkSQL. Basically everyone who has a row calls it that. I think everyone does this because it is best for their users, even if implementing becomes uglier for a couple files. Changing to +1 full support for just `Row` actually.

**Comment by reuvenlax** [comment]
I'm convinced, and at this point most people seem to be leaning to Row. Ken
pointed out that most other systems (Hive, Cassandra, Spark, etc.) just use
Row. Since there was discussion, we should send a note to the dev list
about this.

For now I've changed the class name to be Row.

**Comment by reuvenlax** [comment]
Ok, rebased around conflicts.

**Comment by kennknowles** [comment]
Actually I think it would be sporting to wait for #4593 by @akedin because it is easier to re-do the automated refactor than to resolve the conflicts there.

**Comment by akedin** [comment]
I'm fine either way. Or I can rename everything myself as part of that PR

**Comment by akedin** [comment]
Renamed on top my refactoring PR: https://github.com/apache/beam/pull/4628

**Comment by reuvenlax** [comment]
Did you get the other classes as well (e.g. BeamRecordCoder BeamRecord
Asserts et.c)?

**Comment by akedin** [comment]
Yes BeamRecordCoder->RowCoder, BeamRecordAsserts -> RowAsserts. intellij
doesn't shows only one "BeamRecord" in javadoc that i missed

**Comment by XuMingmin** [comment]
@akedin  can you close this task as it's covered in #4628.

**Comment by kennknowles** [comment]
Closing this since it is done.

**Pull request closed without merging**
