### PR TITLE
Fix broken parsing of uuid

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by apilloud** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by apilloud** [comment]
There are some weird failures in the nexmark job:
```
14:13:25 Performance:
14:13:25   Conf  Runtime(sec)    (Baseline)  Events(/sec)    (Baseline)       Results    (Baseline)
14:13:25   0000          -1.0                        -1.0                          -1              
14:13:25         *** Job was unexpectedly updated ***
14:13:25   0001          61.2                    163345.3                     9200000              
14:13:25   0002          42.4                    235826.8                       83527              
14:13:25   0003          96.0                    104137.4                       59507              
14:13:25   0004          62.4                     16027.2                         140              
14:13:25   0005          80.8                    123783.8                        4567              
14:13:25   0006          68.5                     14594.3                        8902              
14:13:25   0007         110.3                     90685.7                         100              
14:13:25   0008          63.1                    158355.6                       92833              
14:13:25   0009          57.0                     17547.9                       32548              
14:13:25   0010          79.2                    126328.0                          -1              
14:13:25         *** Job was unexpectedly updated ***
14:13:25   0011          71.4                    140111.0                     1839657              
14:13:25   0012          51.9                    192778.5                      199929              
14:13:25 Exception in thread "main"   0013          61.6                    162469.5                     9200000              
14:13:25   0014         134.3                     74449.6                     9200000              
14:13:25 ==========================================================================================
14:13:25 
14:13:25 java.lang.RuntimeException: Execution was not successful
14:13:25 	at org.apache.beam.sdk.nexmark.Main.runAll(Main.java:170)
14:13:25 	at org.apache.beam.sdk.nexmark.Main.main(Main.java:415)
```

**Comment by reuvenlax** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by reuvenlax** [comment]
Dataflow Runner Nexmark Tests

**Comment by reuvenlax** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by reuvenlax** [comment]
@apilloud something is still failing even with this fix. At this point I suggest excluding the original PR that added this codepath from the release. If that's not easy to do we can roll it back to do the release and resubmit once the bug has been fixed.

**Comment by apilloud** [comment]
Can you send a rollback PR to the release branch?

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Python PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Pull request merged**
