### PR TITLE
[BEAM-14439] [BEAM-12673] Add extra details to PubSub matcher errors

### PR DESCRIPTION
**Pull request by yeandy**
Adding more details to the error message to `PubSubMessageMatcher` when the actual and expected messages don't match. This will aid in future debugging when test jobs fail.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by yeandy** [comment]
R: @tvalentyn

**Comment by tvalentyn** [comment]
Thanks. You can also mention something on relevant bugs that we are looking forward to seeing this error again next time it fails.

**Comment by lveraszto** [comment]
Hi,

thanks for the commit.

I found a little thing.
I had a custom matcher inherited from `PubSubMessageMatcher`. 
I used in my class the `_wait_for_messages` function to get the message and decode it for comparison.
But my converter throws an error because the messages are now a tuple not a single list.

My old code:
`// store the messages as a local variable in my custom class`
`self.messages = self._wait_for_messages(self.expected_msg_len, self.timeout)`

and

`// convert the messages for comparison`
`def __convert_message(self, messages):
        return list(map(lambda x: json.loads(x.decode("utf-8")), messages))`
        
The error: `AttributeError: 'list' object has no attribute 'decode'`

My fix:
`self.messages = self._wait_for_messages(self.expected_msg_len, self.timeout)[0]`

**Comment by yeandy** [comment]
Sorry that this broke your old code! Thanks for the update, and glad to know that you're able to make an adjustment to fix it.

**Pull request merged**
