### PR TITLE
[BEAM-6407] Revert "BEAM-5933: avoid memory allocation in hashCode call"

### PR DESCRIPTION
**Pull request by nielm**
Reverts apache/beam#6909, as this appears to cause an obscure error in FileIO.writeDynamic

### CODE REVIEW

**Comment by nielm** [comment]
@kennknowles

**Comment by kennknowles** [comment]
CC @janotav @iemejia

**Comment by kennknowles** [comment]
Can you add a regression test?

**Comment by kennknowles** [comment]
Note that these are certainly distinct hashes: https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-

I'm guessing that the check whether every view is set up right also uses Objects.hash. So there might be an easy roll-forward.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by janotav** [comment]
I will try to look into it over the week-end. If the release is sooner than that, rolling back is definitely the  appropriate solution. The allocations were frequent, but given their size they are unlikely to have material effect.

Sorry for the complications, my intentions were good, honestly :-)

**Comment by nielm** [comment]
note that the does not repro the problem on master branch... 
I plan to find out whether that is because the test is invalid, or because the problem is fixed on master...

**Comment by nielm** [comment]
Fixed test case - now fails reliably when the fix is not applied.

**Comment by nielm** [comment]
note that Spotless fails on TestPOJOs.java -- not on any of the files modified in this PR.

**Comment by kennknowles** [comment]
I am going to merge this and then look into the spotless issue. In this case, it is likely because the merge of turning off `paddedCell` was concurrent with the merge of adding `TestPOJOs.java`.

**Pull request merged**
