### PR TITLE
BEAM-934 Findbugs doesn't pass in Java8 Examples

### PR DESCRIPTION
**Pull request by eralmas7**
Maven Build result:

...
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ beam-examples-java8 ---
[INFO] Installing C:\workspace-apache\beam\examples\java8\target\beam-examples-java8-2.2.0-SNAPSHOT.jar to C:\Users\almass\.m2\repository\org\apache\beam\beam-examples-java8\2.2.0-SNAPSHOT\beam-examples-java8-2.2.0-SNAPSHOT.jar
[INFO] Installing C:\workspace-apache\beam\examples\java8\dependency-reduced-pom.xml to C:\Users\almass\.m2\repository\org\apache\beam\beam-examples-java8\2.2.0-SNAPSHOT\beam-examples-java8-2.2.0-SNAPSHOT.pom
[INFO] Installing C:\workspace-apache\beam\examples\java8\target\beam-examples-java8-2.2.0-SNAPSHOT-tests.jar to C:\Users\almass\.m2\repository\org\apache\beam\beam-examples-java8\2.2.0-SNAPSHOT\beam-examples-java8-2.2.0-SNAPSHOT-tests.jar
[INFO] Installing C:\workspace-apache\beam\examples\java8\target\beam-examples-java8-2.2.0-SNAPSHOT-tests.jar to C:\Users\almass\.m2\repository\org\apache\beam\beam-examples-java8\2.2.0-SNAPSHOT\beam-examples-java8-2.2.0-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:20 min
[INFO] Finished at: 2017-07-09T11:49:43+05:30
[INFO] Final Memory: 30M/109M
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Python SDK build failed. Let me take a look.

**Comment by eralmas7** [comment]
It's nothing to do with the module in which i the change has been released. It's in the python module which is unchanged.

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (setuptools-test) on project beam-sdks-python: Command execution failed.

**Comment by eralmas7** [comment]
Weird that latest build failed for no issue of code issue:

2017-07-10T16:57:01.907 [ERROR] Failed to execute goal on project beam-sdks-java-io-hadoop-jdk1.8-tests: Could not resolve dependencies for project org.apache.beam:beam-sdks-java-io-hadoop-jdk1.8-tests:jar:2.2.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.hive:hive-exec:jar:1.2.1, org.apache.calcite:calcite-core:jar:1.2.0-incubating: Could not transfer artifact org.apache.hive:hive-exec:jar:1.2.1 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/hive/hive-exec/1.2.1/hive-exec-1.2.1.jar from central failed: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project beam-sdks-java-io-hadoop-jdk1.8-tests: Could not resolve dependencies for project org.apache.beam:beam-sdks-java-io-hadoop-jdk1.8-tests:jar:2.2.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.hive:hive-exec:jar:1.2.1, org.apache.calcite:calcite-core:jar:1.2.0-incubating: Could not transfer artifact org.apache.hive:hive-exec:jar:1.2.1 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/hive/hive-exec/1.2.1/hive-exec-1.2.1.jar from central failed

**Comment by kennknowles** [comment]
Can you also edit the pom to re-enable findbugs?

**Comment by reuvenlax** [comment]
Anything more needed for this PR?

**Comment by eralmas7** [comment]
Nothing @reuvenlax . I'm waiting for a long time to get it merged!

**Pull request closed without merging**
