### PR TITLE
[BEAM-1871] Remove google api BackOff usage from sdks/core

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

- cheryy-pick of https://github.com/apache/beam/pull/2937

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @davorbonaci 
CC: @lukecwik

**Comment by vikkyrk** [comment]
There was the `Base64` encoding cherry-pick that I has missed, updated now.

**Comment by lukecwik** [comment]
d28ef6c is equivalent to https://github.com/apache/beam/commit/88e044fda0a7d0ea1372f075a4c7a4bd54af47da beyond the worker change

**Comment by lukecwik** [comment]
Merging

**Comment by lukecwik** [comment]
Merged, please close at your leisure

**Pull request closed without merging**
