### PR TITLE
[BEAM-3074] Serialize DoFns by portable id in Dataflow runner.

### PR DESCRIPTION
**Pull request by robertwb**
DESCRIPTION HERE

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by robertwb** [comment]
Gradle failure seems unrelated. 

Jenkins: run python postcommit

**Comment by robertwb** [comment]
Ping @kennknowles This should be quite the easy review. Any comments?

**Comment by kennknowles** [comment]
I believe it and LGTM. Is there a Python equivalent of `run Dataflow ValidatesRunner`? Or what coverage is there?

**Comment by robertwb** [comment]
I tested this by patching the change internally on the local runner. 

Jenkins: run PythonPostCimmt

**Comment by robertwb** [comment]
Run Python PostCommit

**Comment by kennknowles** [comment]
We should get some public coverage. Anyhow if any job at all, like an example E2E then I am satisfied. And TBH if it doesn't break the build again LGTM.

**Comment by robertwb** [comment]
Run Python PostCommit

**Comment by robertwb** [comment]
Run Python PostCommit

**Comment by robertwb** [comment]
Indeed Python SDK PostCommit found I was not guarding against not using the Fn API. Fixed, all passes now.

**Pull request merged**
