### PR TITLE
[BEAM-14072] Revert "[BEAM-13993] [BEAM-10039] Import beam plugins before starting SdkHarness"

### PR DESCRIPTION
**Pull request by chamikaramj**
Reverts apache/beam#16998

### CODE REVIEW

**Comment by chamikaramj** [comment]
Testing a revert to fund the culprit for following test suite breakages.
https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow/
https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow/

**Comment by chamikaramj** [comment]
Run XVR_PythonUsingJava_Dataflow PostCommit

**Comment by chamikaramj** [comment]
R: @rahuliyer95 @robertwb

**Comment by rahuliyer95** [comment]
Hi, Thanks for triaging this! Would it be possible for you to link the failed CI job run and Dataflow job logs from the failed run? I would like to see which plugin import is causing the failure and maybe we can make it work without having to revert the change completely.

**Comment by chamikaramj** [comment]
Seems like build jogs do not contain Dataflow job IDs unfortunately: https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJava_Dataflow/144/consoleText

Lemme try running a separate x-lang job from HEAD.

**Comment by chamikaramj** [comment]
I couldn't reproduce by running a single job but you should be able to reproduce by triggering the test suite.
https://issues.apache.org/jira/browse/BEAM-14072?focusedCommentId=17503837&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17503837

Could we proceed with the revert since this could result in other other critical bugs creeping into the repo ?

**Comment by chamikaramj** [comment]
R: @tvalentyn 

BTW one suspicion is that this might be broken for certain Python versions.
Both these test suites are run for multiple Python versions: https://github.com/apache/beam/blob/b07840e925b910fffee85d3bcdb67468965b7770/.test-infra/jenkins/PythonTestProperties.groovy#L37

**Comment by tvalentyn** [comment]
LGTM.

s.apache.org/beam-python-dev-wiki has some pointers on running individual intergration tests that may be helpful

**Comment by chamikaramj** [comment]
Thanks Valentyn. @rahuliyer95 I'll merge this to make the test suites green again but lemme know if you need help running x-lang tests. (also added some info to the Jira)

**Pull request merged**
