### PR TITLE
[Ignore, Test] spark-runner: upgrade to spark 2.1.0

### PR DESCRIPTION
**Pull request by peihe**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @amitsela

**Comment by reuvenlax** [comment]
R: @aviemzur

**Comment by aviemzur** [comment]
@peihe this will probably work, since the breaking changes in API in Spark 2.x are small.
However, our plan currently is to support both Spark 1.6.x and Spark 2.x in the runner.
This is covered by [BEAM-1920](https://issues.apache.org/jira/browse/BEAM-1920)
I believe this is currently being worked on by @jbonofre you two can sync your efforts on this.

**Comment by jbonofre** [comment]
I replied on the mailing list about that. Indeed, I have a branch with a new Spark 2 runner. @peihe can you please sync before pushing any PR ? Thanks !

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by amitsela** [comment]
I was also involved in this.
This is what I thought last I checked the Spark1.x/2.x difference:
  
1. We keep supporting only the RDD API, "Structured Streaming" does not provide a stateful operator that scans the entire state (last I checked..).
2. There was an idea to dynamically switch between the `Iterator`s and `Iterable`s since this was the only compile-time difference I noticed. If we can do this we can actually support both with minimal duplication.

**Comment by aviemzur** [comment]
Can this PR be closed?

**Comment by reuvenlax** [comment]
is this still needed?

**Comment by amitsela** [comment]
I don't think so, not since https://github.com/apache/beam/pull/4208 got merged.

**Comment by iemejia** [comment]
I am closing this one for the reasons Amit mentioned, this is already covered by the recent merge of the support for Spark 2.

**Pull request closed without merging**
