### PR TITLE
Revert "Add drop_example flag to the RunInference and Model Handler"

### PR DESCRIPTION
**Pull request by AnandInguva**
Reverts apache/beam#23266

### CODE REVIEW

**Comment by AnandInguva** [comment]
R: @damccorm

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by AnandInguva** [comment]
@damccorm can we revert this PR? I will tag in a new one, which follows the pattern that was discussed in the dev list 

https://docs.google.com/document/d/1vJgGArgNTCkKo9BDxhf5jJtzr6yLTo1CRMw5B9ljT9o/edit?resourcekey=0-5TTi0_4oFPl0DM_g_04JBA#

**Review by damccorm — APPROVED** [review]
SGTM

**Comment by kennknowles** [comment]
Can you edit the PR description to describe why it was reverted? (backwards-incompatible change, when you take typing into account)

Ideally put it in the commit history next time, as we cannot edit that after the fact.

**Pull request merged**
