### PR TITLE
[BEAM-1619] Write to the existing View in Dataflow Streaming Side Inputs

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This updates Streaming View Overrides to use the original view when they override a transform
by causing the override to only apply to the `View.CreatePCollectionView`, inserting a global combine
and view write prior to the primitive which creates the view.

There are also updates to how the Dataflow Runner signifies that a Map or Multimap view has a nondeterminstic key coder, as well as an additional test for CombineGloballyAsSingletonView.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles 
CC: @aaltay @reuvenlax @dpmills

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Actually, streaming doesn't have coverage :-(

**Comment by kennknowles** [comment]
LGTM. Spark test failures seem to be a common flake right now.

**Comment by kennknowles** [comment]
Confirmed via chat that streaming tests have been run manually since we don't have them connected to Jenkins.

**Pull request closed without merging**
