### PR TITLE
[BEAM-867] Add schema update options to BigQueryIO

### PR DESCRIPTION
**Pull request by johanhaleby**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This is a first attempt at solving [BEAM-876](https://issues.apache.org/jira/browse/). This should work for batch inserts but I haven't found a way to implement it for streaming inserts.

Note that I was not able to successfully run `mvn clean verify` even before I started working on this PR. 

Also I've not added any tests since I'm a bit uncertain on how to do this. Please advice.

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by johanhaleby** [comment]
Hmm I don't understand why the python stuff fails since to commit doesn't touch any python code.

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by aaltay** [comment]
R: @reuvenlax

**Comment by johanhaleby** [comment]
@reuvenlax Thanks for your comment. Where can I read up on the other attempt? I've also created a feature request at issuetracker.google.com to hopefully allow BigQuery to support schema updates on streaming inserts "natively".

**Comment by kennknowles** [comment]
@reuvenlax did the other in-progress approach land? Should this be rebased and worked out further?

**Comment by oskoi** [comment]
@aaltay @reuvenlax what's the status of this issue BEAM-876 (https://issues.apache.org/jira/browse/BEAM-876)? Does anyone do it?

**Comment by reuvenlax** [comment]
Has not been implemented. However there's a workaround - use
withFailedInsertRetryPolicy to detect when inserts fail due to invalid
schema, and update the schema in response to that.

**Pull request closed without merging**
