### PR TITLE
[Website] Add GraalSystems in case studies

### PR DESCRIPTION
**Pull request by Treydone**
Add GraalSystems in use cases

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by damccorm — COMMENTED** [review]
@pabloem could you take a look? Not sure what our normal process is for use cases

**Comment by apilloud** [comment]
R: @pabloem

**Comment by apilloud** [comment]
Looks like the new directions for approval are in #23958
```
If you have any questions about adding a case study, please send an email to dev@beam.apache.org with subject: [Beam Website] Add New Case Study.
```

**Comment by pabloem** [comment]
I am sooo sorry to miss this so long. Let's see...

**Comment by pabloem** [comment]
Run Website_Stage_GCS PreCommit

**Comment by pabloem** [comment]
thanks so much @Treydone ! Sorry about the delay : ) - let me know if you'd like to add anything else

**Pull request merged**
