### PR TITLE
[BEAM-3249, BEAM-3457] Make Apache Rat a dependency of the Java and Gradle precommits.

### PR DESCRIPTION
**Pull request by lukecwik**
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lukecwik** [comment]
CC: @kennknowles

**Comment by kennknowles** [comment]
From #4818:

me: "Why is the precommit looped out and using those targets? Shouldn't it just be straight line hardcoded list of targets like :sdks:java:core:check and :globalRAT or some such?"

**Comment by lukecwik** [comment]
The loop over the same set of projects that maven listed via `-pl` and the `-am` `-amd` flags have gradle equivalents `:buildNeeded` and `:buildDependents`. If your asking why a loop, then its to prevent people from missing specifying buildNeeded vs buildDependents or vice versa and to ease the maintenance when running both Maven and Gradle.

**Comment by kennknowles** [comment]
The use of three roots for the Maven `-am` and `-amd` was to compensate for the fact that it does not work correctly due to lack of dep-driven build. If a module was pulled in by `-amd` then its other deps would not get pulled in.

I think if Gradle works correctly it should be enough to specify `:sdks:java:core:buildDependents`.

It is fine to do `buildNeeded` but all that does is "run the tests" of the deps - building them is already built into the dependency-driven execution.

**Comment by kennknowles** [comment]
Confirmed that `:sdks:java:core:build :sdks:java:core:buildDependents` suffices to replace the loop.

**Comment by lukecwik** [comment]
Swapped to `:sdks:java:core:buildNeeded` and `:sdks:java:core:buildDependents` to prevent a regression if the SDK core ever depends on another project like the shaded guava module that had been discussed.

**Comment by kennknowles** [comment]
What do you expect to be run by `sdks:java:core:buildNeeded` if there is a pre-shaded Guava?

**Comment by lukecwik** [comment]
The pre-shaded guava isn't a great example because it wouldn't contain tests but other projects that contain utility/test libraries that the SDK and runners could depend on.

**Comment by kennknowles** [comment]
Filed https://issues.apache.org/jira/browse/BEAM-3823 about breaking out RAT.

**Pull request merged**
