### PR TITLE
[BEAM-8889] Upgrades gcsio to 2.1.2

### PR DESCRIPTION
**Pull request by veblush**
This is part of [BEAM-8889](https://issues.apache.org/jira/projects/BEAM/issues/BEAM-8889) to get new GCS connector 2.1.2 after #10769. This doesn't add any feature except the new API `setGrpcEnabled` that does no-op currently, but enables #10786 to get merged. Once this and #10786 are merged, developers (mostly us) can try the unstable gRPC/GCS feature by changing the gcsio dependency to 2.2.x of their Beam project.

After gcsio releases 2.2.x, the the first version supporting gRPC/GCS protocol, that version will be added to Beam SDK so that users can try the feature by using `use_grpc_for_gcs` experiment flag (#11183).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by veblush** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by veblush** [comment]
All failures other than `Java_Examples_Dataflow` don't seem related with the change. Can you run the test again?

```
# CommunityMetrics ("Run CommunityMetrics PreCommit") 
Task :beam-test-infra-metrics:composeUp FAILED
-> dockerpycreds.errors.InitializationError: docker-credential-gcloud not installed or not availabl

# Java ("Run Java PreCommit")
org.apache.beam.runners.fnexecution.control.DefaultJobBundleFactoryTest.loadBalancesBundles
-> Assert.assertTrue(System.currentTimeMillis() - tms >= 100 && closed.get());

# Java_Examples_Dataflow ("Run Java_Examples_Dataflow PreCommit")
org.apache.beam.examples.WordCountIT.testE2EWordCount
-> java.lang.RuntimeException: Failed to read from: gs://temp-storage-for-end-to-end-tests/WordCountIT-2020-04-07-22-11-56-654/output/results*-of-* with shard template '(?x) \S* (?<shardnum> \d+) -of- (?<numshards> \d+)'

# Python2_PVR_Flink ("Run Python2_PVR_Flink PreCommit") 
Execution failed for task ':sdks:python:test-suites:portable:py2:flinkCompatibilityMatrixBatchLOOPBACK'.
-> ERROR:apache_beam.runners.worker.data_plane:Failed to read inputs in the data plane.
```

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by chamikaramj** [comment]
Can you check if failure here is due to the library update:
https://builds.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Commit/7467/testReport/junit/org.apache.beam.examples/WordCountIT/testE2EWordCount/

**Comment by chamikaramj** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by chamikaramj** [comment]
Run CommunityMetrics PreCommit

**Comment by veblush** [comment]
Fortunately the failure in the example was gone now.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by veblush** [comment]
Both `CommunityMetrics PreCommit` and `Java PreCommit` seem to fail because of environmental flakiness since those are observed by other PRs, too.

**Comment by chamikaramj** [comment]
Don't think failure is related but test suite seems to be pretty flake. So will try re-run when it's more stable.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
'CommunityMetrics' failure is unrelated. Merging.

**Pull request merged**
