### PR TITLE
Gradle target and script for adding YAML reference manual to site.

### PR DESCRIPTION
**Pull request by robertwb**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Current release workflow actually uses this github action to generate documents: https://github.com/apache/beam/blob/2f8854a3e34f31c1cc034f95ad36f317abc906ff/.github/workflows/build_release_candidate.yml#L329-L345

would you mind add the same command to this action? and could test by running the workflow on your branch (need to be in apache/beam repo)

**Comment by robertwb** [comment]
Good to know. Updated the workflow.

**Review by Abacn — APPROVED** [review]
LGTM, thanks!

Tried to test the workflow but apparently it needs the (already released) RC tag did not have generate yml doc target. So need next release to exercise the workflow

also failed python tests looks unrelated

**Comment by robertwb** [comment]
I've run the command manually, but agree that the real test will be as part of the next RC (with the required tag and all). 

Yes, the failures are unrelated (and not present earlier).

**Pull request merged**
