### PR TITLE
LoadTestsBuilder: Disallow whitespace in option values

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Follow-up for #22422

Add an explicit check for pipeline option values that contain whitespace. This will prevent us from introducing another option that is incorrectly parsed in the future.

Verified by adding back a bad option value and running the seed job: https://ci-beam.apache.org/job/beam_SeedJob/10035/console

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Run seed job

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
R: @tvalentyn

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
