### PR TITLE
[BEAM-1875] Remove Spark runner custom Hadoop and Avro IOs.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @iemejia this is long overdue now, especially after the last improvements to "HadoopIO" in the SDK.

**Comment by amitsela** [comment]
Spark Run ValidatesRunner

**Comment by amitsela** [comment]
Run Spark ValidatesRunner

**Comment by amitsela** [comment]
@iemejia PTAL

**Comment by amitsela** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
LGTM

**Pull request closed without merging**
