### PR TITLE
Fix beam_PostCommit_Java_Sickbay build

### LINKED ISSUE #21826: [Bug]: beam_PostCommit_Java_Sickbay fails
### What happened?

beam_PostCommit_Java_Sickbay fails to run successfully

https://ci-beam.apache.org/job/beam_PostCommit_Java_Sickbay/

### Issue Priority

Priority: 2

### Issue Component

Component: build-system

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #21826

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Ran "successful" locally:

```
FAILURE: Build completed with 6 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:flink:1.14:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/flink/1.14/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:flink:1.13:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/flink/1.13/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:flink:1.12:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/flink/1.12/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:samza:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/samza/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:flink:1.15:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/flink/1.15/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':runners:direct-java:validatesRunnerSickbay'.
> There were failing tests. See the report at: file:///Users/***/beam/runners/direct-java/build/reports/tests/validatesRunnerSickbay/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

```

**Comment by pabloem** [comment]
Run Gradle Publish

**Comment by pabloem** [comment]
(disregard my command. I'm just taking advantage of your PR for this release : P)

**Comment by fernando-wizeline** [comment]
Thanks for this Yi @Abacn! I was working on the same issue in [PR21838](https://github.com/apache/beam/pull/21838/) but totally missed the flink tasks.

**Comment by fernando-wizeline** [comment]
Thanks for this Yi @Abacn! I was working on the same issue in [PR21838](https://github.com/apache/beam/pull/21838/) but totally missed the flink tasks.

**Comment by pabloem** [comment]
merging this but I'm also requesting changes in #21838

**Pull request merged**
