### PR TITLE
[BEAM-6190] Add processing stuck message to Pantheon.

### PR DESCRIPTION
**Pull request by dustin12**
This PR adds an indication visible on the Pantheon page of a streaming Dataflow job to indicate when processing on a worker has become stuck.  Currently exceptions in the workers are clearly visible on the Pantheon landing page but stuck worker messages are only viewable in the worker logs. 

@pabloem @lukecwik 
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by pabloem** [comment]
It seems that the change caused breakage in a test. Can you fix that? 
image
https://scans.gradle.com/s/llmzycuwfbkiq/console-log?task=:beam-runners-google-cloud-dataflow-java-legacy-worker:compileTestJava

**Comment by dustin12** [comment]
@pabloem Whoops sorry about that I was running the wrong tests locally so didn't see the problem.  Should be fixed now, thanks!

**Comment by pabloem** [comment]
Okay, this looks fine, but I have a couple things that give me pause:

- I agree that these lull messages need to be shown to the user more directly. Have you tested this on Dataflow? TBH I was not aware that such a path existed to surface individual worker messages on the job log.

- One more thing. A lull is not necessarily a failure. Do you know if there is a way of surfacing this, but as a Warning, or even Info?

**Comment by pabloem** [comment]
I don't know what's your LDAP. Mine is pabloem@ - talk to me in hangouts?

**Comment by pabloem** [comment]
Thank you Dustin!

**Pull request merged**
