### PR TITLE
[BEAM-9281] Update commons-csv to version 1.8

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev

### CODE REVIEW

**Comment by iemejia** [comment]
Run CommunityMetrics PreCommit

**Comment by iemejia** [comment]
Run SQL PostCommit

**Comment by aromanenko-dev** [comment]
Run PythonLint PreCommit

**Comment by aromanenko-dev** [comment]
Run PythonFormatter PreCommit

**Comment by aromanenko-dev** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by aromanenko-dev** [comment]
Run Python PreCommit

**Comment by aromanenko-dev** [comment]
Seems like this dependency is used only in `sdks/java/extensions/sql`. Can someone from Beam SQL developers take a look?

**Comment by iemejia** [comment]
The PR is passing in total 17 checks including both `Run SQL PreCommit` and `SQL Post Commit Tests`. If there is an error then we have bad test coverage, what about merging as it is?

**Pull request merged**
