### PR TITLE
[BEAM-6512] Run GrpcDataServiceTest clients on the main thread

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Run gRPC clients on the main thread in GrpcDataServiceTest. Prevents a possible race condition where clients did not add data to `clientInboundElements` until _after_ the assertion was already called.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
R: @robertwb
Let's try this again, I think I like this solution better. Running the gRPC clients on the main thread seems to resolve the flake - even if I put long `Thread.sleep` calls in the onNext callback, the test runs fine.

**Comment by TheNeuralBit** [comment]
Ran Java PreCommit

**Comment by TheNeuralBit** [comment]
Run Java PreCommit

**Comment by TheNeuralBit** [comment]
Run Java PreCommit

**Comment by TheNeuralBit** [comment]
Run Java PreCommit

**Comment by robertwb** [comment]
I'm not sure I understand the race condition--it looks like we explicitly wait on all futures that add elements to these lists before asserting on them.

It would be useful to understand the intent of this test--the way it's written makes me think it's explicitly trying to verify this works in the face of concurrency which is removed with these changes.

**Comment by TheNeuralBit** [comment]
I think the cause of the race condition is that the futures can return before the clients receive all the data. Nothing in the future is blocking until all the messages have been received. There's a build scan with some additional logging in [BEAM-6512](https://issues.apache.org/jira/browse/BEAM-6512) where you can see this happening.

As far as the intent of the test, my understanding is that we're trying to test [this](https://github.com/apache/beam/blob/b953645ed6db837d24284d7fe1fe091e7309f821/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/data/GrpcDataService.java#L98), which attempts to ensure only one of the created multiplexers is actually used.

**Comment by robertwb** [comment]
It's hard to make sense of the logging without seeing where it is in the code, but it looks like the withOnNext argument gets deferred as well? If so, we'd need to add a future that gets completed when this gets called. Given your statement about "only one of the created multiplexers is actually used" it seems that multi-threading is important to ensure it handles concurrency correctly.

**Comment by TheNeuralBit** [comment]
Ah sorry #7775 is the PR where I added the logging. Hopefully that helps you make sense of the detailed log.

You're right there are two things that get deferred:
1. The creation of the clients (threads are managed in `clientFutures`)
2. The calls to onNext (managed by gRPC)

I removed both of them in this PR, but #2 is really the root of the problem, and to your point, #1 is necessary to actually exercise the GrpcDataService's client creation in the face of concurrency.

What if I just remove #2, i.e. use the direct executor so the onNext calls are not deferred, but continue to create each client in it's own thread? I pushed up some commits that revert my previous changes and do that instead. It seems to fix the problem (tested by adding a Thread.sleep to the onNext function which makes the previous test fail consistently), and still ensures GrpcDataService correctly handles concurrency.

**Comment by TheNeuralBit** [comment]
Do you think this is ok @robertwb?

FYI I also wrote up #7784 which just moves the countdown latch synchronization into the onNext function. I was wary of that approach though since it requires that exactly three elements are received across all the clients, and I thought receiving n != 3 elements could be a failure mode we care about.

**Comment by robertwb** [comment]
This looks good, thanks.

**Pull request merged**
