### PR TITLE
Fix various lint errors in Python presubmit.

### PR DESCRIPTION
**Pull request by robertwb**
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for fixing this. Still seems to be failing.

```
11:23:39 Running isort for module apache_beam  gen_protos.py  setup.py  test_config.py:
11:23:45 ERROR: /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_it_test.py Imports are incorrectly sorted.
11:23:45 --- /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_it_test.py:before	2018-12-11 10:20:43.606281
11:23:45 +++ /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_it_test.py:after	2018-12-11 10:23:41.687212
11:23:45 @@ -23,9 +23,8 @@
11:23:45  import unittest
11:23:45  from collections import Counter
11:23:45  
11:23:45 +import pyarrow as pa
11:23:45  from nose.plugins.attrib import attr
11:23:45 -
11:23:45 -import pyarrow as pa
11:23:45  
11:23:45  from apache_beam import Create
11:23:45  from apache_beam import DoFn
11:23:45 ERROR: /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_test.py Imports are incorrectly sorted.
11:23:45 --- /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_test.py:before	2018-12-11 10:20:43.606281
11:23:45 +++ /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit@2/src/sdks/python/apache_beam/io/parquetio_test.py:after	2018-12-11 10:23:42.026171
11:23:45 @@ -25,13 +25,12 @@
11:23:45  import unittest
11:23:45  
11:23:45  import hamcrest as hc
11:23:45 -from parameterized import param
11:23:45 -from parameterized import parameterized
11:23:45 -
11:23:45  import pandas
11:23:45  import pyarrow as pa
11:23:45  import pyarrow.lib as pl
11:23:45  import pyarrow.parquet as pq
11:23:45 +from parameterized import param
11:23:45 +from parameterized import parameterized
11:23:45  
11:23:45  from apache_beam import Create
11:23:45  from apache_beam import Map
11:23:45 Command exited with non-zero status 1
```

**Comment by robertwb** [comment]
isort can't seem to make up its mind... I'll revert that change.

**Comment by robertwb** [comment]
ERROR: beam7 is offline; cannot locate JDK 1.8 (latest)

**Comment by robertwb** [comment]
Run RAT PreCommit

**Pull request merged**
