### PR TITLE
Revert "[BEAM-11648] BigQuery Storage API sink"

### PR DESCRIPTION
**Pull request by tvalentyn**
Reverts apache/beam#11767

### CODE REVIEW

**Comment by boyuanzz** [comment]
R: @chamikaramj

**Review by kennknowles — APPROVED** [review]
Yup, looks like a failure.

**Comment by chamikaramj** [comment]
Thanks. LGTM.

Please create a JIRA for the failure.

**Comment by kennknowles** [comment]
I realize that I had extra context here when I merged. This PR is missing a lot of information like which test was failing. I do not insist on a Jira but at least a meaningful description. Hence the PR template that says _please_ add a meaningful description.

**Pull request merged**
