### PR TITLE
[WIP] re-enable unbounded scheduled executor

### PR DESCRIPTION
**Pull request by johnjcasey**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
run java postcommit

**Comment by johnjcasey** [comment]
Run Java Precommit

**Comment by lukecwik** [comment]
I see that there was a change to the watchdog to not shutdown the executor (https://github.com/googleapis/gax-java/commit/6241a2118690d07dd28ffb9447423363f3f914e4) and has been released for a long time. 

I'm concerned that if we don't shutdown the watchdog then we will leak Watchdog futures. How did you come to this being the right fix?

**Comment by johnjcasey** [comment]
This is primarily proving that the issue @reuvenlax found was due to the watchdog trying to close the executor. The correct fix is likely fixing the BQ client library.

**Comment by johnjcasey** [comment]
I've raised an issue and a PR on the GAX side of things to try and address this https://github.com/googleapis/gax-java/pull/1859

**Comment by lukecwik** [comment]
Thanks, didn't expect the awaitTermination call to happen if the isShutdown/isTerminated would have returned true.

We can always incorporate a new WatchDog based upon https://github.com/googleapis/gax-java/pull/1859 into Beam until we migrate to a version of gax that includes the fix. If we do so, should we use a FixedWatchDogProvider that watches multiple streams or stick with the instantiating one?

**Comment by johnjcasey** [comment]
I'm not sure we can do that with the fixed provider, because Watchdog itself is a final class

**Comment by lukecwik** [comment]
Another alternative would be to use an instantiating executor provider that returns wrapped ScheduledExecutorService implementations that track whether they were closed, cancelling tasks and futures that are still running that are associated with it on shutdown and also rejecting tasks once closed.

**Comment by lukecwik** [comment]
waiting on author

**Comment by apilloud** [comment]
waiting on authorwaiting on author

**Comment by lukecwik** [comment]
waiting on author

**Comment by lukecwik** [comment]
superseded by https://github.com/apache/beam/pull/24950

**Pull request closed without merging**
