### PR TITLE
[BEAM-9285] specify overload for toArray

### PR DESCRIPTION
**Pull request by reuvenlax**
Fix for Java 11

R: @iemejia

### CODE REVIEW

**Comment by reuvenlax** [comment]
Run Flink ValidatesRunner Java 11

**Comment by iemejia** [comment]
It seems it is still breaking but now it says size 0 instead of 2. The `SplittableDoFn` tests are already in the process of being fixed by #11475
`org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalStateException: size = 0`

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Flink ValidatesRunner Java 11

**Comment by iemejia** [comment]
I am closing this one in favor of #11695

**Pull request closed without merging**
