### PR TITLE
[BEAM-13352] Add transient qualifier to StorageApi member variables 

### PR DESCRIPTION
**Pull request by Naireen**
Add transient qualifier to StorageApi member variables.

R: @reuvenlax

### CODE REVIEW

**Comment by Naireen** [comment]
R: @reuvenlax

**Comment by reuvenlax** [comment]
please run spotless

**Comment by Naireen** [comment]
Run Spotless PreCommit

**Comment by Naireen** [comment]
Run Spotless PreCommit

**Comment by reuvenlax** [comment]
Looks like fixing this is somewhat more complicated - take a look at
https://github.com/apache/beam/pull/16146

**Pull request closed without merging**
