### PR TITLE
[release-2.16.0][BEAM-8299] Upgrade Jackson to version 2.9.10

### PR DESCRIPTION
**Pull request by iemejia**
Cherry pick of #9636 (done in parallel)
R: @pabloem 
CC: @markflyhigh

### CODE REVIEW

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by pabloem** [comment]
LGTM. I've merged https://github.com/apache/beam/pull/9636 -  I'll let the release manager merge this.

**Comment by markflyhigh** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by markflyhigh** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by markflyhigh** [comment]
pydoc failure in Python Precommit will be fixed by cherry-pick https://github.com/apache/beam/pull/9654. We can ignore it since all test passed.

**Comment by markflyhigh** [comment]
Run Java_Examples_Dataflow PreCommit

**Pull request merged**
