### PR TITLE
[BEAM-1299] Removes Dataflow native text source and sink from Beam Python SDK.

### PR DESCRIPTION
**Pull request by chamikaramj**
Users should be using Beam text source and sink available in module 'textio.py' instead of this.

Also removes Dataflow native file source/sink that is only used by native text source/sink.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM. Thank you. Please watch the next post commit run after this is merged.

Also related to: https://issues.apache.org/jira/browse/BEAM-1218

**Comment by robertwb** [comment]
Nice! I'm going to wait until the next postcommit finishes (hopefully green) before merging.

**Comment by chamikaramj** [comment]
Failures here seem to be unrelated: https://builds.apache.org/job/beam_PostCommit_Python_Verify/1081/console

**Comment by aaltay** [comment]
Let's wait for https://builds.apache.org/job/beam_PostCommit_Python_Verify/1082/console

**Comment by aaltay** [comment]
Postcommit is passing, this could be merged now.

**Comment by chamikaramj** [comment]
Thanks.

**Pull request closed without merging**
