### PR TITLE
[BEAM-1256] SparkPipelineResult.StreamingMode should not return null …

### PR DESCRIPTION
**Pull request by amitsela**
…on awaitTermination()

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @staslev

**Comment by staslev** [comment]
I totally agree that returning `null` here is far from ideal.
See also the [mail thread](https://lists.apache.org/thread.html/79d78e8e114ac97e804f2c01570419404983d6fe40540471698c07c6@%3Cdev.beam.apache.org%3E) and thoughts on [BEAM-849](https://issues.apache.org/jira/browse/BEAM-849).

That said, at the moment this `null` is ["according to spec":](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/PipelineResult.java#L54)

```java
/**
   * @return The final state of the pipeline or null on timeout.
   * @throws UnsupportedOperationException if the runner does not support cancellation.
   */
  State waitUntilFinish(Duration duration);
```

I guess it boils down to whether we want to deviate from the SDK spec here.

**Comment by amitsela** [comment]
Well, I've hit this when playing around with streaming pipelines (tests) that assert on the result state and it will always return `null` even if all goes brilliantly well (you might expect `DONE`).

I think the final state of the pipeline should be `DONE` after returning from "awaitTermination..." because Spark either finished by then or throws an exception.. `null` is not in Spark's spec, and `SparkPipelineResult` will still return `null` in case of a `TimeoutException`. 

Eventually, the current state is effectively "hard-coded" to always return `null` - and this is wrong according to the Beam spec as well.

**Comment by staslev** [comment]
Come to think about it, can `javaStreamingContext.awaitTerminationOrTimeout(duration.getMillis())` ever return `true`?

**Comment by amitsela** [comment]
Well... if _something_ caused it to close the context before timeout.

**Comment by amitsela** [comment]
But that is not relevant. Even if this is a bug, branch-1.6 is not expected to be further developed and we shouldn't count on it.

**Comment by staslev** [comment]
I think I understand the motivation.
Though if `awaitTermination` always returns `DONE` in streaming mode we will no longer be able to tell whether the waiting was completed successfully or due to a time out. Is this something we care about?

**Comment by amitsela** [comment]
Won't a timeout throw a TimeoutException ?

**Comment by staslev** [comment]
I think that `StreamingContext#awaitTerminationOrTimeout()` will throw only if there were errors during execution, `true` if stopped before the given duration elapsed, and `false` otherwise.

Or as `Spark` puts it: "true if it's stopped; or throw the reported error during the execution; or false if the waiting time elapsed before returning from the method."

**Comment by amitsela** [comment]
Pretty sure the future you used there will throw `TimeoutException` if Spark, for some reason, has not returned - so you'd still end up with `null` state in that case (catch clause in SparkPipelineResult).

**Comment by staslev** [comment]
If memory serves, if it's a streaming pipeline the future is only responsible for starting the pipeline and will return right away (as opposed to the batch mode, where it actually blocks). Then, it's the `javaStreamingContext.awaitTerminationOrTimeout(duration.getMillis())` that's blocking in `SparkPipelineResult#awaitTermination()`.

Let's take a deeper look tomorrow to make sure.

**Comment by amitsela** [comment]
OK, I agree that something is off here.. the API needs a bit more clarification.
I'll close this for now and keep discussion in the dev-list.

**Comment by amitsela** [comment]
Better yet, in the designated ticket [`BEAM-849`](https://issues.apache.org/jira/browse/BEAM-849)

**Pull request closed without merging**
