### PR TITLE
Expose GroupIntoBatches parameters for WriteFiles auto-sharding transform

### LINKED ISSUE #30131: [Feature Request]:  Expose GroupIntoBatches Parameters for WriteFiles Autosharding transform
### What would you like to happen?

WriteFiles transform currently uses hard coded values to set the element and byte limits for flushing a bundle (currently set here: https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L151).  Make this tunable for end users. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Amar3tto**
Fixes #30131

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by Amar3tto** [comment]
Run Xlang_Generated_Transforms PreCommit 3.8

**Comment by Amar3tto** [comment]
R: @Abacn

**Review by Abacn — COMMENTED** [review]
Regarding the feature request, this exposes the configs in WriteFiles, however end user most likely use file-based IOs (not WriteFiles directly), e.g. TextIO and other IOs, this is still not exposed.

I suggest at least we implement this to TextIO, so this PR is useful for end user, and other file based IOs could be follow up.

**Comment by Amar3tto** [comment]
> Regarding the feature request, this exposes the configs in WriteFiles, however end user most likely use file-based IOs (not WriteFiles directly), e.g. TextIO and other IOs, this is still not exposed.
> 
> I suggest at least we implement this to TextIO, so this PR is useful for end user, and other file based IOs could be follow up.

Implemented for TextIO

**Comment by Amar3tto** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Review by Abacn — APPROVED** [review]

**Comment by Abacn** [comment]
The test added in this PR failing PostCommit Java ValidatesRunner Samza: #31725

**Pull request merged**
