### PR TITLE
[BEAM-9071] Ignore pytype before typing is fully developed.

### PR DESCRIPTION
**Pull request by boyuanzz**
R: @udim @aaltay 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aaltay** [comment]
LGTM.

1. Please wait for the tests to pass.
2. Please add a JIRA either on the same line or above to gradually remove these and add this support.

A question for @udim -- In the meantime do we need a system to ensure new files have this comment in place?

**Comment by boyuanzz** [comment]
Tests failed because encoding comments are required at the line1 and line2: https://www.python.org/dev/peps/pep-0263/.
Udi, will the skip type comment work after encoding comment?

**Comment by udim** [comment]
> LGTM.
> 
> 1. Please wait for the tests to pass.
> 2. Please add a JIRA either on the same line or above to gradually remove these and add this support.
> 
> A question for @udim -- In the meantime do we need a system to ensure new files have this comment in place?

There's a similar check you can adopt here:
https://github.com/apache/beam/blob/4b772254447d1fa5fc7f0c5857312c70552ad7ef/sdks/python/scripts/run_pylint.sh#L108-L122

**Comment by boyuanzz** [comment]
> > LGTM.
> > 
> > 1. Please wait for the tests to pass.
> > 2. Please add a JIRA either on the same line or above to gradually remove these and add this support.
> > 
> > A question for @udim -- In the meantime do we need a system to ensure new files have this comment in place?
> 
> There's a similar check you can adopt here:
> https://github.com/apache/beam/blob/4b772254447d1fa5fc7f0c5857312c70552ad7ef/sdks/python/scripts/run_pylint.sh#L108-L122

Hey Udi, could you please help add the check after this PR checked in?

**Comment by udim** [comment]
> Tests failed because encoding comments are required at the line1 and line2: https://www.python.org/dev/peps/pep-0263/.
> Udi, will the skip type comment work after encoding comment?

Yes it should. I was thinking of putting it before the first import statement in each file:
```
sed '0,/import/ s/.*import.*/# pytype: skip-file\n\n&/' apache_beam/pvalue.py | less
```
or for all files:
```
find apache_beam | grep \\.py$ | xargs -n 1 sed '0,/import/ s/.*import.*/# pytype: skip-file\n\n&/' | less
```
and when satisfied this will make changes to files:
```
find apache_beam | grep \\.py$ | xargs -n 1 sed -i '0,/import/ s/.*import.*/# pytype: skip-file\n\n&/'
```

https://stackoverflow.com/a/9453461/63302

**Comment by udim** [comment]
> > > LGTM.
> > > 
> > > 1. Please wait for the tests to pass.
> > > 2. Please add a JIRA either on the same line or above to gradually remove these and add this support.
> > > 
> > > A question for @udim -- In the meantime do we need a system to ensure new files have this comment in place?
> > 
> > 
> > There's a similar check you can adopt here:
> > https://github.com/apache/beam/blob/4b772254447d1fa5fc7f0c5857312c70552ad7ef/sdks/python/scripts/run_pylint.sh#L108-L122
> 
> Hey Udi, could you please help add the check after this PR checked in?

sure, np

**Comment by udim** [comment]
gradle died: https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/1844/console
retrying

**Comment by udim** [comment]
Run PythonLint PreCommit

**Comment by boyuanzz** [comment]
I did some manual check and changes. Waiting for test passing.

**Pull request merged**
