### PR TITLE
[BEAM-2690] Fix type parameter in AvroIO.Write

### PR DESCRIPTION
**Pull request by nevillelyh**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @reuvenlax

**Comment by nevillelyh** [comment]
@reuvenlax can you or anyone else take a look?

**Comment by reuvenlax** [comment]
Can you please file a JIRA, and change the title of this PR per the policy?

**Comment by nevillelyh** [comment]
Fixed. Thanks.
https://issues.apache.org/jira/browse/BEAM-2960

**Comment by nevillelyh** [comment]
Ping @reuvenlax

**Comment by reuvenlax** [comment]
retest this please.

**Pull request closed without merging**
