### PR TITLE
Add skip header lines in TextIO

### LINKED ISSUE #17990: Skip header row from csv
Add functionality to skip header rows when reading from a csv file.

http://stackoverflow.com/questions/28450554/skipping-header-rows-is-it-possible-with-cloud-dataflow

Imported from Jira [BEAM-123](https://issues.apache.org/jira/browse/BEAM-123). Original Jira may contain additional context.
Reported by: davin.pidoto.

### PR DESCRIPTION
**Pull request by gudfhr95**
Fixes #17990 

**Changes**
- Add `withSkipHeaderLines`
- Disable `isSplittable` of `TextSource` when `skipHeaderLines` is greater than 0

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by gudfhr95** [comment]
fixes #17990

**Comment by gudfhr95** [comment]
Run Java PreCommit

**Comment by gudfhr95** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_Amazon-Web-Services2_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_IOs_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java PreCommit

**Comment by gudfhr95** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by gudfhr95** [comment]
Run Java_Amazon-Web-Services_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java PreCommit

**Comment by gudfhr95** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by gudfhr95** [comment]
Run Java PreCommit

**Review by damondouglas — CHANGES_REQUESTED** [review]
Good day @gudfhr95, Thank you so much for your contribution! I would like to propose the following change to your PR.

Instead of making changes to TextIO, [FileIO.ReadableFile's readFullyAsUTF8String() method](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/FileIO.java#L438) would still provide #17990's feature request. I would like to propose that this PR add a new method such as: `public String readFullyAsUTF8String(int skipHeaderLines) throws IOException {}`

What do you think of this idea? Your contribution and opinion is important.

Thank you, again for your contribution!

**Comment by gudfhr95** [comment]
Hello, @damondouglas. I really appreciate for your review and your suggestion.
I have a question about your suggestion.

As far as I understand, even though I found every occurrences of `readFullyAsUTF8String()`, I think that there is no relationship between `readFullyAsUTF8String()` method and reading `TextSource` or `FileBasedSource`. Could you explain where can I find connection between them?

**Comment by damondouglas** [comment]
> Hello, @damondouglas. I really appreciate for your review and your suggestion. I have a question about your suggestion.
> 
> As far as I understand, even though I found every occurrences of `readFullyAsUTF8String()`, I think that there is no relationship between `readFullyAsUTF8String()` method and reading `TextSource` or `FileBasedSource`. Could you explain where can I find connection between them?

Hello @gudfhr95, It's nice to hear from you and thank you for your response. I just created this example gist that uses `FileIO.ReadableFile`'s [readFullyAsUTF8String](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/FileIO.ReadableFile.html#readFullyAsUTF8String--) method. In the gist, I performed the line skipping in a DoFn as copied from the gist below.

```
@ProcessElement
public void process(@Element ReadableFile element) {
        String rawData = element.readFullyAsUTF8String();
        Stream<String> lines = rawData.lines().skip(/* int */ skipLines);
        List<String> result = lines.collect(Collectors.toList());
}
```

https://gist.github.com/damondouglas/84c34469d4a6d7b7483468659482855c

However, I can see this code in a new `readFullyAsUTF8String` method that takes an `int skipLines` argument. So the above DoFn could look like this:

```
@ProcessElement
public void process(@Element ReadableFile element) {
        List<String> lines = element.readFullyAsUTF8String(/* int */ skipLines);
}
```

**Comment by gudfhr95** [comment]
Ah, I see. Thank you for your detailed examples.
Your suggestion is to add a utility methods in `ReadableFIles`.

Then, I think that I should revert my previous commits and create new PR only containing `readFullyAsUTF8String(int skipLines)`
I'll do it ASAP and request your review.

Again, thank you for your kind explanation @damondouglas!

**Comment by damondouglas** [comment]
@gudfhr95 Take your time. Again, we are very grateful for your contribution and thank you again for listening to my feedback. I look forward to talking with you soon.

**Pull request closed without merging**
