### PR TITLE
Add a ValidatesContainer integration test for use_sibling_sdk_workers

### PR DESCRIPTION
**Pull request by ryanthompson591**
Add a ValidatesContainer integration test that exercises --experiments=[no]use_sibling_sdk_workers

See https://github.com/apache/beam/issues/24092
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ryanthompson591** [comment]
R: @tvalentyn

I was trying to figure out if we should use the prebuild_sdk_container_engine flag in this test. WDYT?

**Comment by ryanthompson591** [comment]
Run Python Dataflow ValidatesContainer

**Comment by ryanthompson591** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
thanks.
verified sibling protocol is enabled in runner harness container:

```
    "args": [ "--endpoint=https://dataflow.googleapis.com/", "--log_file=/var/log/dataflow/boot-json.log", "--log_dir=/var/log/dataflow", "--logging_port=12370", "--control_port=12371", "--provision_endpoint=localhost:12373", "--sdk_harness_ids=sdk-0-0,gcr.io/cloud-dataflow/v1beta3/python37:beam-master-20221021", "--enable_sibling_sdk_workers", "--sdk_harness_to_env_ids=sdk-0-0,,,ref_Environment_default_environment_1", "--num_threads_per_worker=2" ],
      "image": "gcr.io/cloud-dataflow/v1beta3/unified-harness:20221026-14-rc00",
```

by running 

```
python -m pytest  -o log_cli=True -o log_level=Info apache_beam/examples/wordcount_it_test.py::WordCountIT::test_wordcount_it_with_use_sibling_sdk_workers  --test-pipeline-options='--runner=TestDataflowRunner --project=apache-beam-testing --temp_location=gs://valentyn-testing --sdk_location=dist/apache-beam-2.44.0.dev0.tar.gz --region=us-central1 --output=gs://valentyn-testing/out'
```

and checking the container manifest for the running job.

**Comment by tvalentyn** [comment]
cc: @robertwb fyi

**Pull request merged**
