### PR TITLE
[BEAM-13434] Upgrade to pubsublite 1.4.0.2 on the release branch.

### PR DESCRIPTION
**Pull request by tvalentyn**
Dependency bump to pick up: https://github.com/google/flogger/releases/tag/flogger-0.7.3

### CODE REVIEW

**Comment by tvalentyn** [comment]
@aaltay

**Review by aaltay — APPROVED** [review]

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Pull request merged**
