### PR TITLE
[BEAM-1225] Simplify ToString.element()

### PR DESCRIPTION
**Pull request by dhalperi**
R: @eljefe6a @bjchambers 

Will this be a good change, or will Java wildcard mumbo jumbo make this actually much worse?

### CODE REVIEW

**Comment by eljefe6a** [comment]
I think a wildcard is the only way to do this.

**Comment by eljefe6a** [comment]
@dhalperi @vikkyrk I think `element` isn't the right name. Some ideas:
`asString`, `simpleString`, `simple`, `stringValue`. I'm leaning towards `stringValue`.

**Comment by eljefe6a** [comment]
Perhaps `.of()` is the better name. I think that's the most API consistent name.

**Comment by dhalperi** [comment]
I think the goal of choosing `.element` was to support proposed future variants like `.kv`. I'll let @bjchambers ring in there, as I suspect it was his proposal.

A nice thing is that the name change is thankfully unrelated to removing the need for a type that I proposed here. The question I meant to ask originally:

Right now, we have an ignored template parameter `<T>` that makes the user's code more annoying. This PR proposes replacing it with `<?>`, which simplifies the user's code because they need not care about types. Could this change cause Java wildcard hell? (I think not, but looking for an authoritative answer ;).

**Comment by vikkyrk** [comment]
@eljefe6a The idea was to have , `ToString.element`, `ToString.kv`, `ToString.iterable` and so on, to distinguish what type of PCollection we are applying this to, while still keeping it future proof. 

@dhalperi Need to change https://github.com/apache/beam/blob/master/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ToStringTest.java#L47 as well.

+1, I like this better and do not see any wildcard issues here.

**Comment by eljefe6a** [comment]
I understand the need to have different methods and future proofing. Looking at [other classes](https://beam.apache.org/documentation/sdks/javadoc/0.3.0-incubating/org/apache/beam/sdk/transforms/Create.html), the "default" behavior method is `of()` and the other non-default behavior are different names.

**Comment by dhalperi** [comment]
@eljefe6a I'm looking forward to a PR from you to improve and add new functionality to the `ToString` transform.

Can you LGTM or otherwise review this specific change, swapping `ToString.element()` (possibly pending new name in a separate PR) to not require the user to specify a type?

**Comment by eljefe6a** [comment]
LGTM

**Pull request closed without merging**
