### PR TITLE
[BEAM-1266] Remove value only outputs in Dataflow job representation

### PR DESCRIPTION
**Pull request by lukecwik**
Always define outputs in terms of full windowed value representations

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Fired off some postcommits:

https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Dataflow/2012/
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1345/

**Comment by kennknowles** [comment]
Postcommit failures are all due to other things (now rolled back). LGTM.

**Comment by dhalperi** [comment]
@lukecwik -- The merge commit for this accidentally says `This closes #1266` (the issue #) instead of the PR# 1766. Mind closing manually?

**Comment by lukecwik** [comment]
Whoops

**Pull request closed without merging**
