### PR TITLE
[BEAM-5297] Add propdeps-idea plugin.

### PR DESCRIPTION
**Pull request by dmvk**
Intellij Idea (2018.2.1) does not pick up provided dependencies.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by ryan-williams** [comment]
Thanks for this!

Can you elaborate on "does not pick up provided dependencies"?

In IntelliJ 2018.1.6, I see `provided` `hadoop-common` being understood fine by IntelliJ in the `:beam-sdks-java-io-hadoop-file-system` module:



though maybe it's strange that it's listed as `Compile`-scoped?

I just want to make sure I understand the state of what works and doesn't in IJ.

I did a lot of digging recently because I saw IntelliJ not understanding the `provided` dependencies above, but the problem was apparently due to some strange interactions between IntelliJ and my local Maven repository (details on [my dev list post just now](https://lists.apache.org/thread.html/520f1d3b931581a4ff58c2c391bf56e547b3b15f0706c094ebfc0273@%3Cdev.beam.apache.org%3E)).

**Comment by dmvk** [comment]
Hello Ryan,

I also see files listed as `compile` scoped, but they don't get picked up as in your setup.

screen shot 2018-09-05 at 19 58 23

I don't really understand idea internals, but the plugin seems to be adding them PROVIDED scope.

https://github.com/spring-gradle-plugins/propdeps-plugin/blob/master/src/main/groovy/io/spring/gradle/propdeps/PropDepsIdeaPlugin.groovy

Also they list some relevant issues in the comment:
http://youtrack.jetbrains.com/issue/IDEA-107046
http://youtrack.jetbrains.com/issue/IDEA-117668

Applying the plugin solves the problem.

I hope this will helps.

D.

**Comment by swegner** [comment]
@ryan-williams are you still reviewing this? If not, could you help find another reviewer? For tips, see: https://s.apache.org/beam-owners

**Comment by ryan-williams** [comment]
sorry, I didn't mean to take any reviewer-locks here; I don't have the ability to approve this change, was just trying to understand it.

I don't know how to evaluate proposed changes to our IntelliJ integration when people seem to get different results locally for reasons no one has been able to characterize (afaik)

**Comment by swegner** [comment]
LGTM, thanks for the contribution

I see we have usages of `provided` dependencies in our build, and adding this plugin looks to be consistent with other usages (`propdeps`, `propdeps-maven`). I don't know if this will fix all of our IntelliJ woes, but I don't think it will hurt.

**Pull request merged**
