### PR TITLE
Reduce stdout spam from BeamModulePlugin

### PR DESCRIPTION
**Pull request by udim**
**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Spark
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by udim** [comment]
R: @kennknowles

**Comment by udim** [comment]
Cool, deleted!

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
run go precommit

**Comment by kennknowles** [comment]
run python precommit

**Comment by kennknowles** [comment]
Well, here's something useful to know: `buildSrc` is build, tested, compiled, before you can even run something like `spotlessApply`. So you have to do the hack of `./gradlew -p buildSrc spotlessApply -PdisableSpotlessCheck=true` which I just did. You can squash all the commits.

**Comment by kennknowles** [comment]
Both Jenkins jobs are hanging reporting their status. I'm going to merge but keep an eye on that.

**Comment by udim** [comment]
So what happened here? Did the spotlessApply task fail?

**Comment by udim** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Yea there was a spotless issue. So I just fixed it squashed, pushed to this PR, and merged with the green button.

**Pull request merged**
