### PR TITLE
[BEAM-14160] Parse filesToStage in Java expansion service

### PR DESCRIPTION
**Pull request by deepix**
### Summary

A filesToStage arg when starting expansion service will let us customize and/or control what files can be staged. This speeds up pipeline execution in environments where we can pre-stage jars in the Java harness SDK.

This is based on guidance by @chamikaramj in a [mailing list thread](https://lists.apache.org/thread/knkf6yn52z1fxzbcgkt22dv48o8055bh).

### Testing

Added two unit tests.

Also ran expansion service separately and a portable Python pipeline that uses Kafka I/O (hence Java expansion service). Pipeline ran successfully.

```
$ java -cp ./runners/flink/1.13/job-server/build/libs/beam-runners-flink-1.13-job-server-2.35.0-SNAPSHOT.jar org.apache.beam.sdk.expansion.service.ExpansionService 8096 --filesToStage="foo.jar"
...
Mar 22, 2022 7:04:30 PM org.apache.beam.sdk.expansion.service.ExpansionService$TransformProvider getDependencies
INFO: Staging to files from the classpath: 1, [foo.jar]
```

One can also prevent staging (useful when we have already pre-staged relevant jars in the Java harness SDK):

```
$ java -cp ./runners/flink/1.13/job-server/build/libs/beam-runners-flink-1.13-job-server-2.35.0-SNAPSHOT.jar org.apache.beam.sdk.expansion.service.ExpansionService 8096 --filesToStage=
...
Mar 22, 2022 7:03:59 PM org.apache.beam.sdk.expansion.service.ExpansionService$TransformProvider getDependencies
INFO: Staging to files from the classpath: 1, []

### CODE REVIEW

**Comment by deepix** [comment]
@chamikaramj Please take a look at this PR, thank you.

**Comment by deepix** [comment]
For the "Run Java PreCommit" failure, I see the failure even when I reset to HEAD, indicating that it's a pre-existing condition. Let me know if I'm mistaken.

**Comment by chamikaramj** [comment]
Thanks. Will take a look.

**Review by chamikaramj — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by deepix** [comment]
@chamikaramj Thanks, I cannot merge the PR because I don't have write access to the repo. What is our next step? Thanks again!

**Comment by chamikaramj** [comment]
Thanks. I was just waiting for the tests to pass.

**Comment by lukecwik** [comment]
This change broke the python xlang postcommit, filed https://issues.apache.org/jira/browse/BEAM-14191

**Comment by deepix** [comment]
@lukecwik Thanks, this needed a change in how Python SDK was treating non-local files, fixed by @chamikaramj in #17199.

**Pull request merged**
