### PR TITLE
[Tour of Beam] [Frontend] Minor improvements

### PR DESCRIPTION
**Pull request by nausharipov**
Minor UI improvements.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by nausharipov** [comment]
R: @alexeyinkin

**Review by alexeyinkin — APPROVED** [review]
LGTM (internal review).

**Comment by nausharipov** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
LGTM

**Comment by damccorm** [comment]
Actually, looks like https://github.com/apache/beam/actions/runs/5001733504/jobs/8965458156?pr=26735 is failing and this failure seems new/not occurring on master (https://github.com/apache/beam/actions/workflows/playground_frontend_test.yml?query=branch%3Amaster).

@nausharipov could you please take a look? Would be great if we could just generally get green on our CI failures

**Comment by nausharipov** [comment]
@damccorm as Alexey mentioned, [Playground frontend tests are being fixed](https://github.com/apache/beam/pull/26735#pullrequestreview-1430645482). Fixing Tour of Beam integration test is on Dmitry. 

This PR doesn't contain important and urgent changes. I'll add some more improvements and send it for review after the test fixes are merged.

**Review by damccorm — APPROVED** [review]
Thanks!

**Pull request merged**
