### PR TITLE
[BEAM-1283] Finish bundle should only emit windowed values

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

R: @aaltay @robertwb PTAL

### CODE REVIEW

**Comment by robertwb** [comment]
This is a serious usability regression; I've seen the bug but am unconvinced we should change the spec (specifically the justification that "The use cases for these methods are best addressed by state plus window expiry callback" doesn't cover *most* of the uses I've seen.)

**Comment by sb2nov** [comment]
@robertwb Thanks. Can you comment on the issue as that is marked for the first stable release. I'll holdoff on this PR till we reach some resolution.

**Comment by kennknowles** [comment]
@robertwb your comment sounds like we are removing a capability, but this seems to be implementing the compromise whereby users can still output here - they just need to track the windows, which they needed to do anyhow.

**Comment by kennknowles** [comment]
Have you read the spec? It is both nonsensical and not type safe.

**Comment by kennknowles** [comment]
The reason it is a stable release blocker is that we want to remove the incorrect behavior and always have the option to add supplementary functionality as we figure out how to do so correctly.

**Comment by robertwb** [comment]
I have read the spec; I helped come up with it. It was a compromise between
many options (including requiring explicit windowing in FinalizeOutputs,
which is actually much less typesafe as explicitly emitting to the
GlobalWindow when the ambient windowing function is something else will not
be caught eagerly and can result in undefined behavior (including possibly
silent data corruption)). The current spec will at least give a clear
error.

**Comment by kennknowles** [comment]
The current spec will almost always result in data corruption.

**Comment by kennknowles** [comment]
Well, at any rate, this discussion belongs to the JIRA not a PR.

**Comment by sb2nov** [comment]
Retest this please

**Comment by sb2nov** [comment]
@aaltay PTAL as this is already done in Java now.

**Comment by sb2nov** [comment]
Retest this please

**Comment by sb2nov** [comment]
@robertwb ping

**Comment by sb2nov** [comment]
Retest this please

**Comment by robertwb** [comment]
The discussion still being resolved on the list (http://mail-archives.apache.org/mod_mbox/beam-dev/201705.mbox/browser), we've decided to accept this for consistency with Java until a decision is made to the contrary. 

The code is good. The only failure is (unrelated) "Apache Beam :: Examples :: Java." LGTM.

**Pull request closed without merging**
