### PR TITLE
[BEAM-13818] [SnowflakeIO] Add support for unencrypted private keys

### PR DESCRIPTION
**Pull request by sfc-gh-kbregula**
I would like to adds support for unencrypted private keys and additionally improved the user experience by adding more friendly error messages.

Internal tracker: SNOW-539549

R: @pabloem 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
there's a failure in checkstyle: https://scans.gradle.com/s/r46cpqyvsewxi/console-log?task=:sdks:java:io:snowflake:checkstyleTest

Specifically, please avoid `.*` imports in the test file.

**Comment by pabloem** [comment]
other than that, this LGTM

**Comment by sfc-gh-kbregula** [comment]
@pabloem Thanks for pointing this out. I've already fixed it.

**Comment by pabloem** [comment]
LGTM. Thanks! I'll merge once the CI finishes running.

**Comment by sfc-gh-kbregula** [comment]
One job failed, but it looks flaky:
> Python tests / Python Unit Tests (ubuntu-latest, 3.9, py39) (pull_request) Failing after 13m — Python Unit Tests (ubuntu-latest, 3.9, py39)

**Comment by pabloem** [comment]
merging

**Pull request merged**
