### PR TITLE
[Go] Update Go version used by Beam repo to go1.23.1

### PR DESCRIPTION
**Pull request by lostluck**
* Update the Go version used for builds prior to the next release. 
* Update CHANGES.md accordingly.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @Abacn 

Should be reviewed and merged before the 2.60.0 cut.

**Review by Abacn — APPROVED** [review]
thanks!

looks like there is merge conflict (possibly changes.md)

**Comment by Abacn** [comment]
this breaks https://github.com/apache/beam/actions/workflows/go_tests.yml

Error message:

```
go: downloading golang.org/x/mod v0.12.0
panic: Cannot range over: func(yield func(K, V) bool)

goroutine 333 [running]:
honnef.co/go/tools/go/ir.(*builder).rangeStmt(0xc001619a60, 0xc00130d400, 0xc0004e7320, 0x0, {0xa4c4d8, 0xc0004e7320})
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2225 +0x894
honnef.co/go/tools/go/ir.(*builder).stmt(0xc001619a60, 0xc00130d400, {0xa4e900?, 0xc0004e7320?})
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2438 +0x20a
honnef.co/go/tools/go/ir.(*builder).stmtList(...)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:859
honnef.co/go/tools/go/ir.(*builder).stmt(0xc001619a60, 0xc00130d400, {0xa4e540?, 0xc0011d3560?})
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2396 +0x14[15](https://github.com/apache/beam/actions/runs/11113057812/job/30876518088#step:10:16)
honnef.co/go/tools/go/ir.(*builder).buildFunction(0xc00[16](https://github.com/apache/beam/actions/runs/11113057812/job/30876518088#step:10:17)19a60, 0xc00130d400)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2508 +0x4[17](https://github.com/apache/beam/actions/runs/11113057812/job/30876518088#step:10:18)
honnef.co/go/tools/go/ir.(*builder).buildFuncDecl(0xc001619a60, 0xc009282480, 0xc0011d3590)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2545 +0x[18](https://github.com/apache/beam/actions/runs/11113057812/job/30876518088#step:10:19)9
honnef.co/go/tools/go/ir.(*Package).build(0xc009282480)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2649 +0xb46
sync.(*Once).doSlow(0xc00084c7e0?, 0xc0094f9c20?)
	/opt/hostedtoolcache/go/1.23.1/x64/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.23.1/x64/src/sync/once.go:67
honnef.co/go/tools/go/ir.(*Package).Build(...)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/go/ir/builder.go:2567
honnef.co/go/tools/internal/passes/buildir.run(0xc0034981a0)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/internal/passes/buildir/buildir.go:86 +0x18b
honnef.co/go/tools/lintcmd/runner.(*analyzerRunner).do(0xc00968d3e0, {0xa50fd8?, 0xc001098f00})
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:992 +0x71b
honnef.co/go/tools/lintcmd/runner.genericHandle({0xa50fd8, 0xc001098f00}, {0xa50fd8?, 0xc001098e60?}, 0xc0010b8d[20](https://github.com/apache/beam/actions/runs/11113057812/job/30876518088#step:10:21), 0xc0004bd6b0, 0xc0004295f0)
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:817 +0x11f
created by honnef.co/go/tools/lintcmd/runner.(*subrunner).runAnalyzers in goroutine 397
	/home/runner/go/pkg/mod/honnef.co/go/tools@v0.4.7/lintcmd/runner/runner.go:1061 +0x6a6
```

**Comment by lostluck** [comment]
I think we'll need to update the version of staticcheck, it's older at this point.

**Pull request merged**
