### PR TITLE
[BEAM-12277] Update Flink 1.13 version to 1.13.1

### PR DESCRIPTION
**Pull request by iemejia**
They released a new version just after we merged the PR so probably worth to start with this one.
R: @dmvk @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Review by dmvk — APPROVED** [review]
LGTM 👍

**Pull request merged**
