### PR TITLE
[BEAM-1112] Improve Python E2E Test Framework

### PR DESCRIPTION
**Pull request by markflyhigh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

IT tests should not failed `python setup.py test`.
 - Skip IT(integration test) if `--test-pipeline-options` is not specified in command line arguments.

### CODE REVIEW

**Comment by markflyhigh** [comment]
+R: @aaltay

**Comment by markflyhigh** [comment]
@aaltay PTAL

**Comment by aaltay** [comment]
LGTM (please wait for tests to finish).

**Comment by markflyhigh** [comment]
@dhalperi please merge if looks good to you.

**Comment by dhalperi** [comment]
LGTM, merged, thanks.

**Pull request closed without merging**
