### PR TITLE
BigQuery Storage Write API extreme timestamp overflow fix

### PR DESCRIPTION
**Pull request by algirdas-k**
Fix for https://github.com/apache/beam/issues/23636

Writing extreme  ( <1677-09-21, >2262-04-12) timestamp values to BigQuery via Storage Write API now fails due to `long overflow` exception, because conversion of timestamp to `micros` is done in `nanos`, overflowing `long` (see detailed analysis in https://github.com/apache/beam/issues/23636), although BigQuery supports such dates ([TIMESTAMP range](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type)).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~[ ] Update `CHANGES.md` with noteworthy changes.~
 - ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by algirdas-k** [comment]
I think this is for @reuvenlax

**Comment by algirdas-k** [comment]
R: @reuvenlax

**Comment by algirdas-k** [comment]
PreCommit failures:
- `HadoopFormatIOElasticTest.classMethod` https://github.com/apache/beam/issues/24389
- `:runners:java-fn-execution:test` `ServerFactoryTest`
  - `urlFactoryWithPortSupplier FAILED`
  - `defaultServerWithPortSupplier FAILED`

**Comment by kennknowles** [comment]
Seems unrelated tests. I'm working on making sure they don't get pulled in on irrelevant PRs. For now I will rerun it.

**Comment by kennknowles** [comment]
run java precommit

**Comment by pabloem** [comment]
r: @vachan-shetty @kmjung

**Comment by kmjung** [comment]
Storage write API issues should go to @yirutang or someone she delegates.

**Comment by agrawal-siddharth** [comment]
It appears the fix for this issue was committed to the JDK with the following change:

https://github.com/openjdk/jdk/commit/81d2acee57188a4507c798b46b0bd129dc302fec

**Comment by agrawal-siddharth** [comment]
I verified the code no longer overflows with JDK 19 deployed.

**Comment by algirdas-k** [comment]
I see the same result (no overflow) on higher versions of JDK (18, 19) used by us.

Thank you @agrawal-siddharth 🙇

**Pull request closed without merging**
