### PR TITLE
Adding try_claim function to RestrictionTracker interface

### PR DESCRIPTION
**Pull request by pabloem**
@boyuanzz @lukecwik I think this was missing?

### CODE REVIEW

**Comment by lukecwik** [comment]
https://github.com/apache/beam/blob/37326d3988af4a78008e6d44d9647c190aaffe2e/sdks/python/apache_beam/io/iobase.py#L1232 ?

**Comment by lukecwik** [comment]
The method was missing till just a few days ago.

**Comment by pabloem** [comment]
ah well - nevermind then : )

**Comment by boyuanzz** [comment]
Added here: https://github.com/apache/beam/pull/8641/files#diff-5bdf3a832591550d5839cb5f76ea2f10R1232

**Pull request closed without merging**
