### PR TITLE
Add ability to configure ArtifactService gRPC Channel

### PR DESCRIPTION
**Pull request by snallapa**
The purpose of this PR is to support configurable gRPC channels for ArtifactService. We have use cases where we run the ExpansionService in different environments. One example environment is in Google Cloud Run. This requires authenticated gRPC calls with the google cloud token in the gRPC header and transport security enabled vs plaint text. With the current public methods, we can do this for the expand stub with no problem, but not for the artifact stub which would need the same channel configuration.  We ended up monkey patching this to get our use case to work. I am contributing the monkey patch back to beam. 

address #25840 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by chamikaramj — COMMENTED** [review]
Thanks. Looks good in general.

Can you add a unit test ?

**Comment by chamikaramj** [comment]
Also, please attach a Github issue.

**Comment by snallapa** [comment]
@chamikaramj sounds good ill add one later today

**Comment by snallapa** [comment]
@chamikaramj sorry for the late update, went on vacation. Here is the issue ill include it in the PR description as well. I will update this branch with testing now as well.

**Comment by chamikaramj** [comment]
BTW, how would you use this ?
I don't see a good way to override the DefaultExpansionServiceClientFactory in our API currently.

If there's a way to override this you could setup an integration test that provides required dependencies through a custom ArtifactService.

**Comment by snallapa** [comment]
@chamikaramj you would have to use the External.of constructor with a new implementation ExpansionServiceClientFactory (the one that is visible for testing but it is public)

I can try that, do you have an example?

**Comment by snallapa** [comment]
@chamikaramj thank you, I will update and try that soon!

**Comment by tvalentyn** [comment]
waiting on author

**Comment by snallapa** [comment]
no time for this sorry, if anyone else is interested they can pick it up 👍

**Pull request closed without merging**
