### PR TITLE
[BEAM-6489] Cherry-pick 10f4b1a5ef to 2.10.0 release branch

### PR DESCRIPTION
**Pull request by tvalentyn**
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @kennknowles

**Comment by mxm** [comment]
I've already put this in #7564, but makes sense to merge this separately here.

**Comment by mxm** [comment]
PreCommit fails, but might be flaky: https://builds.apache.org/job/beam_PreCommit_Python_Commit/3790/

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by swegner** [comment]
Precommit failed on Dataflow `test_wordcount_it`: https://builds.apache.org/job/beam_PreCommit_Python_Phrase/161/

**Comment by swegner** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
From job logs: "No such image: gcr.io/cloud-dataflow/v1beta3/python-fnapi:2.10.0" - that test will not pass until Dataflow maintainers prepare the 2.10.0 container image.

**Comment by kennknowles** [comment]
@tvalentyn did you see this via the DF UI? On #7564 I had to click over the StackDriver and scan for errors.

**Comment by tvalentyn** [comment]
@kennknowles I looked into StackDriver logs.

**Pull request merged**
