### PR TITLE
Reduce log spam of Py37PostCommit

### PR DESCRIPTION
**Pull request by Abacn**
Follow up of #23631

While Py38-Py310 postcommit logging has been reduced significantly, Py37 still have ~30 MB logging mostly from `:sdks:python:test-suites:portable:py37:xlangSpannerIOIT`. This test suite only runs on Py37.

~Also fix the priority of log suppress in gradle commands.~ (the setting of `"org.apache.flink.runtime.metrics.groups":"ERROR"}` does not take effect. Many warning level logs in this module sill emitted)

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python 3.7 PostCommit

**Comment by Abacn** [comment]
Run PythonDocs PreCommit

**Comment by Abacn** [comment]
Run Python 3.7 PostCommit

**Comment by Abacn** [comment]
Run Python PreCommit

**Comment by Abacn** [comment]
Now get 16 MB logs. Not idea, reduced by half after all

**Comment by Abacn** [comment]
R: @tvalentyn

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
Failures are known flakes: https://github.com/apache/beam/pull/23829 https://github.com/apache/beam/issues/22115

**Pull request merged**
