### PR TITLE
[BEAM-1542] Make AbstractSpannerFn public

### PR DESCRIPTION
**Pull request by mairbek**
Make AbstractSpannerFn public to support custom user defined functions that use Cloud Spanner.

R: @jkff

### CODE REVIEW

**Comment by jkff** [comment]
Can you elaborate what kind of functions you expect users to write based on this? Is an abstract DoFn base class the best API to enable those use cases?

**Comment by mairbek** [comment]
So, I'm building a pipeline that exports all the database records. For this I've build a function that reads system tables and builds the schema.

I don't want to rewrite the spanner client lifecycle management code.

**Comment by jkff** [comment]
It should be possible to do this via composition rather than inheritance: you can create a helper class `SpannerAccessor` with a constructor from `SpannerConfig` and getters `getSpanner()`, `getDatabaseClient()` and a `close()` method. Then your new DoFn will have 1-line `Setup` and `Teardown` methods which I think is acceptable. In return, you'll get:

- The ability to unit-test `SpannerAccessor` without a pipeline or a `DoFnTester`
- The ability to have multiple `SpannerAccessor`'s in a single `DoFn` (say, you want to do something like `DynamicDestinations` but for Spanner)
- The ability to use it in the context of something that is not a `DoFn`
- The ability to use a different base class for a `DoFn` that wants to use Spanner

**Comment by mairbek** [comment]
I've updated the code, please take a look.

**Comment by jkff** [comment]
retest this please

**Pull request closed without merging**
