### PR TITLE
[BEAM-2530] Automatically retrieving JDK 11 containers in Dataflow

### PR DESCRIPTION
**Pull request by pabloem**
r: @aaltay 
r: @mwalenia

### CODE REVIEW

**Comment by mwalenia** [comment]
@pabloem LGTM, thanks!

**Comment by pabloem** [comment]
@aaltay does this look fine to you?

**Comment by aaltay** [comment]
Question, raised from somewhere else:

Could dataflow just use a java11 based container to run both java8 and java11 pipelines? Would not java11 JVM will be compatible with java8 built files?

**Comment by pabloem** [comment]
TBH I dont know what the answer is to this. Maybe yes? I'd like to hear from someone with more java knowledge.

**Comment by aaltay** [comment]
@kennknowles Do you know if Java 11 JVM can backward compatibly run packages built with Java 8? Does Dataflow need a period of time where it offers Java 8 and Java 11 containers?

**Comment by kennknowles** [comment]
Yes, I believe JDK 11 can run JDK 8 compiled code. I'm not aware of any breaking change in this direction.

**Comment by kennknowles** [comment]
I would trust @lukecwik or @adude3141 opinion more than my own.

**Comment by adude3141** [comment]
Unfortunately I do not fully understand the changes here.

I assume we are talking about some container, a beam pipeline is run with? I.e. the container is running beam code and user code.

I further assume, the customer is allowed to provide her code compiled with java8. So will likely not test on java11 herself, but that containers java version would be kind of transparent to her.

Now given a business critical pipeline depending on some third-party library which can not easily be replaced nor upgraded. Which in turn depends for instance on some byte code enhancement lib or does such simple things as
`(URLClassLoader) getClass().getClassLoader()`
which, iirc does not work anymore on java11 (or some such I do not remember).

Wouldn't that mean, that this customer is suddenly locked out of the service? Always assuming that for whatever reason it is not feasible to upgrade those deps.

**Pull request merged**
