### PR TITLE
[YAML] - Normalize YAML PubSub format

### PR DESCRIPTION
**Pull request by ffernandez92**
addresses #31067

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by brucearctor — APPROVED** [review]
Lgtm.  will leave open a couple days for anyone to comment, though should be fine to merge

**Comment by brucearctor** [comment]
@ffernandez92 -- once you've confirmed docs/website/etc updated [ if necessary ], we can merge.

@robertwb -- should we also update syntax/style guide?  That seems outside scope of this PR, but perhaps worth specifying to further specify desired conventions.

**Comment by ffernandez92** [comment]
Run Python PreCommit 3.9

**Comment by ffernandez92** [comment]
Run Python_Coverage PreCommit

**Comment by ffernandez92** [comment]
@brucearctor, I've updated the docs, website, and tests [I didn't see specific `examples` to fix] to ensure they are consistent with the new uppercase scenario. They currently function regardless of whether it's upper or lower case. However, I'd like to be prepared for when we deprecate the lowercase option so that we don't need to modify the tests.
As you've said, we can leave the PR open for a couple of days in case there is more feedback

**Pull request merged**
