### PR TITLE
Tensorflow object detection example using RunInference

### PR DESCRIPTION
**Pull request by AnandInguva**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
stop reviewer notifications

**Comment by AnandInguva** [comment]
@damccorm Andy started this and this was used to provide benchmarks for NVIDIA and Dataflow blog. What should we do about this PR?

**Comment by yeandy** [comment]
Is there any harm in adding this example? Especially to showcase TF w/ GPUs? 

(Though we don't have to do it for the sake of adding more. I'll leave the decision up to y'all.)

**Comment by damccorm** [comment]
I don't mind adding it, but I'm not sure that it adds a ton of value given that we now have https://github.com/apache/beam/pull/23456; I think it would take at least a little additional work to get this ready (we'd at least need a test) and I'd probably vote we focus on other things. If either of you feels differently and wants to take it forward, I'm happy to review and don't have a problem adding it

**Comment by yeandy** [comment]
I agree that the incremental value-add (especially in the short-term) isn't that high. I don't know the details of your bandwidths, so if there are higher priorities, I think it's ok to table this. We can pick this up from the backlog (keep this draft PR or create an issue?) if there's more time in the future, or a new contributor wants to work on this.

**Comment by damccorm** [comment]
Keeping it in draft seems fine to me, its got all the context we'd need to pick it back up

**Pull request closed without merging**
