### PR TITLE
26756-Python-SDK-Harness-Failure-Log-Critical

### PR DESCRIPTION
**Pull request by cozos**
Issue: https://github.com/apache/beam/issues/26756

Make Python SDK Worker terminations log CRITICAL

Note that `log.exception` uses the `ERROR` level:

> exception(msg, *args, **kwargs)
> 
> Logs a message with level ERROR on this logger. The arguments are interpreted as for [debug()](https://docs.python.org/3/library/logging.html#logging.debug). Exception info is added to the logging message. This method should only be called from an exception handler.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by AnandInguva — APPROVED** [review]

**Comment by AnandInguva** [comment]
cc: @tvalentyn

**Comment by Abacn** [comment]
@AnandInguva  the base branch is release-2.47.0

**Comment by AnandInguva** [comment]
> @AnandInguva the base branch is release-2.47.0

Oh yeah. @cozos can you make this to master branch? I don't think it is a release blocker and also we don't merge on to the release-branch directly. We merge on to master branch and cherry pick the commit on to release branch.

**Comment by cozos** [comment]
As you might've seen, the other PR was merged to master

**Pull request closed without merging**
