### PR TITLE
Checkout repo for post step in website publish

### PR DESCRIPTION
**Pull request by damccorm**
This is currently permared because we check out a branch that doesn't have our setup action's post-step as part of publishing the website. This fixes the problem by checking out the original branch again

Example success - https://github.com/apache/beam/actions/runs/6669683640
History of failure - https://github.com/apache/beam/actions/workflows/beam_PostCommit_Website_Publish.yml

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @Abacn

**Comment by Abacn** [comment]
I've experienced Post Setup Environment step being flaky / slow, e.g. even in this  succeeded run: https://github.com/apache/beam/actions/runs/6669683640/job/18128013945

Post Setup Environment took 5min27s even longer than the test itself, looks like gradle cache upload is failing and retrying

In general upload cache could be useful but for this job shall we just disable the gradle cache?

**Comment by damccorm** [comment]
> I've experienced Post Setup Environment step being flaky / slow, e.g. even in this succeeded run: https://github.com/apache/beam/actions/runs/6669683640/job/18128013945
> 
> Post Setup Environment took 5min27s even longer than the test itself, looks like gradle cache upload is failing and retrying
> 
> In general upload cache could be useful but for this job shall we just skip Post Setup Environment?

Yeah, I just tried it again and it did the same thing - https://github.com/apache/beam/actions/runs/6670562474/job/18130702059

I just pushed a change to disable it, will test and comment back once we see it working

**Comment by damccorm** [comment]
https://github.com/apache/beam/actions/runs/6670718104/job/18131171884 is a working run with the cache set to read only

**Review by Abacn — APPROVED** [review]

**Pull request merged**
