### PR TITLE
[BEAM-13866] Add small unit tests to errorx, make boolean assignment clear

### PR DESCRIPTION
**Pull request by jrmccluskey**
Adds small clarifying parentheses to boolean assignment for guarded error check, also adds small unit tests. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
R: @damccorm @riteshghorse 

Not a lot going on here but I thought I'd put a quick PR together. The boolean assignment for the nil check was visually very jarring so I opted to make it a little clearer (although Go style tends to dislike parenthesis so it may not stick.)

**Review by damccorm — APPROVED** [review]
This LGTM. It is unfortunate that we're not really testing the core functionality of thread safety here though. I don't have a good workaround there (maybe others do), all I can think of are:
1. Grab the mutex ourselves in the test (bad because we're testing implementation not interface)
2. Start up a ton of threads and have them return results of running TrySetError with different values only one should succeed and they should all end up with the same value (bad because it is definitely overengineered **and** isn't deterministic).

All that to say, this is fine (and the right approach IMO), but it makes me a little sad.

**Comment by jrmccluskey** [comment]
There are a lot of things that just wind up being mutex-guarded wrappers around other types and not doing much else, which is fine so long as we trust that golang mutexes actually work correctly. It just also makes test cases around these things unnecessary or, in this case, extremely simple. Eventually I'd like to not have stuff like this kicking around but for the time being it's here

**Comment by jrmccluskey** [comment]
R: @lostluck @youngoli

**Review by lostluck — APPROVED** [review]
LGTM

**Comment by lostluck** [comment]
> There are a lot of things that just wind up being mutex-guarded wrappers around other types and not doing much else, which is fine so long as we trust that golang mutexes actually work correctly. It just also makes test cases around these things unnecessary or, in this case, extremely simple. Eventually I'd like to not have stuff like this kicking around but for the time being it's here

+1 This is a simple enough usage, we don't need to also test the mutex. If things were a few degrees removed, and we were wrangling multiple goroutines, we'd be testing scenarios like this wrapper intends to ensure. Eg - complicated situation, but we have multiple errors, ensure the first error which we know by construction is returned.

This package, like stringx is largely a bit of premature optimization, since it's very easy to implement in place. But we do actually use this one IIRC.

**Pull request merged**
