### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by y1chi**
You can run many tests automatically using release/src/main/scripts/mass_comment.py.

### CODE REVIEW

**Comment by y1chi** [comment]
Run CommunityMetrics PreCommit

**Comment by y1chi** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by y1chi** [comment]
Run Dataflow Runner V2 Java 11 Nexmark Tests

**Comment by y1chi** [comment]
Run Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by y1chi** [comment]
Run Dataflow Runner V2 Nexmark Tests

**Comment by y1chi** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by y1chi** [comment]
Run Dataflow ValidatesRunner Java 11

**Comment by y1chi** [comment]
Run Dataflow ValidatesRunner Java 17

**Comment by y1chi** [comment]
Run Dataflow ValidatesRunner

**Comment by y1chi** [comment]
Run Direct Runner Nexmark Tests

**Comment by y1chi** [comment]
Run Direct ValidatesRunner Java 11

**Comment by y1chi** [comment]
Run Direct ValidatesRunner Java 17

**Comment by y1chi** [comment]
Run Direct ValidatesRunner in Java 11

**Comment by y1chi** [comment]
Run Direct ValidatesRunner

**Comment by y1chi** [comment]
Run Flink Runner Nexmark Tests

**Comment by y1chi** [comment]
Run Flink ValidatesRunner Java 11

**Comment by y1chi** [comment]
Run Flink ValidatesRunner

**Comment by y1chi** [comment]
Run Go Flink ValidatesRunner

**Comment by y1chi** [comment]
Run Go PostCommit

**Comment by y1chi** [comment]
Run Go PreCommit

**Comment by y1chi** [comment]
Run Go Samza ValidatesRunner

**Comment by y1chi** [comment]
Run Go Spark ValidatesRunner

**Comment by y1chi** [comment]
Run Java 11 Examples on Dataflow Runner V2

**Comment by y1chi** [comment]
Run Java 17 Examples on Dataflow Runner V2

**Comment by y1chi** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by y1chi** [comment]
Run Java Dataflow V2 ValidatesRunner

**Comment by y1chi** [comment]
Run Java Examples on Dataflow Runner V2

**Comment by y1chi** [comment]
Run Java Examples_Direct

**Comment by y1chi** [comment]
Run Java Examples_Flink

**Comment by y1chi** [comment]
Run Java Examples_Spark

**Comment by y1chi** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by y1chi** [comment]
Run Java Portability examples on Dataflow with Java 11

**Comment by y1chi** [comment]
Run Java PostCommit

**Comment by y1chi** [comment]
Run Java PreCommit

**Comment by y1chi** [comment]
Run Java Samza PortableValidatesRunner

**Comment by y1chi** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by y1chi** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by y1chi** [comment]
Run Java Spark v3 PortableValidatesRunner Streaming

**Comment by y1chi** [comment]
Run Java examples on Dataflow Java 11

**Comment by y1chi** [comment]
Run Java examples on Dataflow Java 17

**Comment by y1chi** [comment]
Run Java examples on Dataflow with Java 11

**Comment by y1chi** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by y1chi** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by y1chi** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by y1chi** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by y1chi** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by y1chi** [comment]
Run Javadoc PostCommit

**Comment by y1chi** [comment]
Run Jpms Dataflow Java 11 PostCommit

**Comment by y1chi** [comment]
Run Jpms Dataflow Java 17 PostCommit

**Comment by y1chi** [comment]
Run Jpms Direct Java 11 PostCommit

**Comment by y1chi** [comment]
Run Jpms Direct Java 17 PostCommit

**Comment by y1chi** [comment]
Run Jpms Flink Java 11 PostCommit

**Comment by y1chi** [comment]
Run Jpms Spark Java 11 PostCommit

**Comment by y1chi** [comment]
Run PortableJar_Flink PostCommit

**Comment by y1chi** [comment]
Run PortableJar_Spark PostCommit

**Comment by y1chi** [comment]
Run Portable_Python PreCommit

**Comment by y1chi** [comment]
Run PostCommit_Java_Dataflow

**Comment by y1chi** [comment]
Run PostCommit_Java_DataflowV2

**Comment by y1chi** [comment]
Run PostCommit_Java_Hadoop_Versions

**Comment by y1chi** [comment]
Run Python 3.6 PostCommit

**Comment by y1chi** [comment]
Run Python 3.7 PostCommit

**Comment by y1chi** [comment]
Run Python 3.8 PostCommit

**Comment by y1chi** [comment]
Run Python 3.9 PostCommit

**Comment by y1chi** [comment]
Run Flink ValidatesRunner

**Comment by y1chi** [comment]
Run Java examples on Dataflow Java 11

**Comment by y1chi** [comment]
Run PortableJar_Flink PostCommit

**Comment by y1chi** [comment]
Run Direct Runner Nexmark Tests

**Comment by y1chi** [comment]
Run Python Dataflow V2 ValidatesRunner

**Comment by y1chi** [comment]
Run Python Dataflow ValidatesContainer

**Comment by y1chi** [comment]
Run Python Dataflow ValidatesRunner

**Comment by y1chi** [comment]
Run Python Examples_Dataflow

**Comment by y1chi** [comment]
Run Python Examples_Direct

**Comment by y1chi** [comment]
Run Python Examples_Flink

**Comment by y1chi** [comment]
Run Python Examples_Spark

**Comment by y1chi** [comment]
Run Python Flink ValidatesRunner

**Comment by y1chi** [comment]
Run Python PreCommit

**Comment by y1chi** [comment]
Run Python Samza ValidatesRunner

**Comment by y1chi** [comment]
Run Python Spark ValidatesRunner

**Comment by y1chi** [comment]
Run PythonDocker PreCommit

**Comment by y1chi** [comment]
Run PythonDocs PreCommit

**Comment by y1chi** [comment]
Run SQL PostCommit

**Comment by y1chi** [comment]
Run ULR Loopback ValidatesRunner

**Comment by y1chi** [comment]
Run XVR_Direct PostCommit

**Comment by y1chi** [comment]
Run XVR_Flink PostCommit

**Comment by y1chi** [comment]
Run XVR_JavaUsingPython_Dataflow PostCommit

**Comment by y1chi** [comment]
Run XVR_PythonUsingJava_Dataflow PostCommit

**Comment by y1chi** [comment]
Run XVR_Samza PostCommit

**Comment by y1chi** [comment]
Run XVR_Spark PostCommit

**Comment by y1chi** [comment]
Run XVR_Spark3 PostCommit

**Comment by y1chi** [comment]
Run Jpms Dataflow Java 11 PostCommit

**Comment by y1chi** [comment]
Run Typescript PreCommit

**Comment by y1chi** [comment]
Run Spotless PreCommit

**Comment by y1chi** [comment]
Run SQL PreCommit

**Comment by y1chi** [comment]
Run SQL_Java11 PreCommit

**Comment by y1chi** [comment]
Run SQL_Java17 PreCommit

**Comment by y1chi** [comment]
Run Release Gradle Build

**Comment by y1chi** [comment]
Run RAT PreCommit

**Comment by y1chi** [comment]
Run Java PreCommit

**Comment by y1chi** [comment]
Run Release Gradle Build

**Comment by y1chi** [comment]
Run Jpms Dataflow Java 11 PostCommit

**Comment by y1chi** [comment]
Run PostCommit_Java_Dataflow

**Comment by y1chi** [comment]
Triaging so far:
Ongoing flake: https://issues.apache.org/jira/browse/BEAM-14275 causes PostCommit_Java_Dataflow to fail sometimes but it is not a regression on release branch.
Java Samza PortableValidatesRunner Tests, Java Spark v2 PortableValidatesRunner Streaming Tests, Samza CrossLanguageValidatesRunner Tests  are flaky on main branch and not regression on release branch.
JPMS Java 11/17 Dataflow Post Commit needs java worker container version 2.39.0 to be built.

Dataflow Runner Nexmark Tests and Google Cloud Dataflow Portability Runner Examples Java 11 builds are successful.

**Comment by y1chi** [comment]
Run Release Gradle Build

**Comment by y1chi** [comment]
I tested that Release Gradle Build is successful when run locally

**Comment by aaltay** [comment]
Could this be closed now?

**Pull request closed without merging**
