### PR TITLE
[BEAM-5528] Re-add CREATE_VIEW in portable Flink translators

### PR DESCRIPTION
**Pull request by mxm**
Was running tests with the PortableRunner and found that it produces pipelines with the deprecated CREATE_VIEW transform. We should re-add support for it for as long it is not removed.

CC @tweise 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by tweise** [comment]
There was discussion about this on the slack channel. Essentially this is an issue with the Java SDK, it should not generate this URN (at least not for portable pipelines). Can you please check what it takes to fix the root cause?

**Comment by mxm** [comment]
@tweise I'll check if we can easily remove this in the Java SDK. In the meantime, should we merge this to fix the portable Java SDK?

**Comment by tweise** [comment]
Let's see what your check yields. I would prefer we fix this in the Java SDK as otherwise it will leak into every runner.

**Comment by mxm** [comment]
https://issues.apache.org/jira/browse/BEAM-5649

It might be easier to be removed from just the Runner API because it can continue to exist for non-portable pipelines. I'll take another look and would remove the NOOP alongside with CREATE_VIEW removal from the Runner API.

**Comment by mxm** [comment]
(Would still merge this PR in the meantime)

**Comment by mxm** [comment]
(What makes this hard is that the translation code of the old Runners is also tight to the URNs of the Runner API. So removing the transform from the Runner API means we also have to remove it from the legacy code).

**Comment by angoenka** [comment]
I was thinking of utilizing beam_fnapi flag to construct the graph differently for legacy and portable runner. 
However this adds its own complication over time and there is no real good way to other than removing createview from various transforms on per case basis.

**Comment by angoenka** [comment]
I agree that lets re-add it and unblock the java PVR tests. And do the actual fix as a separate item asap.

**Comment by tweise** [comment]
@mxm please update https://issues.apache.org/jira/browse/BEAM-5649 with your findings

**Pull request merged**
