### PR TITLE
[BEAM-6349] & [BEAM-6368] Build worker and use it when running loadtests on Dataflow

### PR DESCRIPTION
**Pull request by lgajowy**
This forces usage of the newest version of worker code preventing any code mismatches that can occur if the version is stale on Dataflow. 

Similar approach is used for Nexmark and IO performance tests.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by lgajowy** [comment]
Run GroupByKey Small Java Load Test Dataflow

**Comment by lgajowy** [comment]
@boyuanzz @swegner could you take a look?

**Comment by lgajowy** [comment]
Run GroupByKey Small Java Load Test Dataflow

**Comment by lgajowy** [comment]
I'm firing this Load test ("Java GroupByKey Small Load Test Dataflow") because it used to fail. Errors were visible in https://console.cloud.google.com in the job details. They should be gone now.

**Comment by swegner** [comment]
Changes look good to me, but is seems the tests are hanging and timing out: https://builds.apache.org/job/beam_Java_LoadTests_GroupByKey_Dataflow_Small_PR/6/

**Comment by lgajowy** [comment]
@swegner right, thank you for noticing this. The Dataflow job lasted 4 hours. We need to address this later. Nevertheless, the errors didn't appear in the Dataflow job and it succeeded so I think we can merge this.

**Comment by swegner** [comment]
Run GroupByKey Small Java Load Test Dataflow

**Comment by swegner** [comment]
Looking at the [previous build](https://builds.apache.org/job/beam_Java_LoadTests_GroupByKey_Dataflow_Small_PR/6/), I found the Dataflow job which timed out is [loadtestoptions-jenkins-0108152432-e92b5183](https://console.cloud.google.com/dataflow/jobsDetail/locations/us-central1/jobs/2019-01-08_07_24_35-12424371536798620857?project=apache-beam-testing&folder&organizationId=433637338589). From the job page, I see the job eventually succeeded, though it ran for 4h 11m.

This change LGTM, though we probably need some follow-up on why the job took so long (or if we need longer timeout)

**Pull request merged**
