### PR TITLE
[BEAM-3230] Fix beam_PerformanceTests_Python

### PR DESCRIPTION
**Pull request by angoenka**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Increasing the timeout to 20minutes.

This PR depends upon PR 4158 for the success of beam_PerformanceTests_Python

### CODE REVIEW

**Comment by aaltay** [comment]
Is this PR ready for review?

**Comment by aaltay** [comment]
Should we review or close this PR?

**Comment by angoenka** [comment]
The issue is still happening. But I am not sure if this PR will fix the issue.
One recent occurrence of timeout issue: https://builds.apache.org/view/A-D/view/Beam/job/beam_PerformanceTests_Python/645/console "2017-12-06 12:17:41,066 066079e2 Thread-4 ERROR    IssueCommand timed out after 600 seconds. Killing command "python setup.py nosetests ". I will rebase and retrigger the test.

**Comment by reuvenlax** [comment]
should we close this?

**Comment by chamikaramj** [comment]
Shall we close this ?

**Comment by angoenka** [comment]
We can close it as the PR is outdated.

**Comment by chamikaramj** [comment]
Thanks. Closing.

**Pull request closed without merging**
