### PR TITLE
Revert "Set setFailIfPoolExhausted in SessionPoolOptions for SpannerA…

### PR DESCRIPTION
**Pull request by manitgupta**
This reverts commit efee92bf02b55bee86848a9d0d291de58cb8412a.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by nielm — APPROVED** [review]

**Comment by Abacn** [comment]
did efee92b introduce a regression? If so is this fix needed a cherry-pick into upcoming 2.60.0 release?

**Comment by nielm** [comment]
> did [efee92b](https://github.com/apache/beam/commit/efee92bf02b55bee86848a9d0d291de58cb8412a) introduce a regression? If so is this fix needed a cherry-pick into upcoming 2.60.0 release?

In some situations, yes, so yes please. can you cherry-pick (want a regression bug?) 

Specific cause: 

Spanner has a max number of 400 sessions in a session pool, where a session is used for a read or a write operation. 

When using streaming pipelines on Dataflow with a high degree of parallelisation, where each work item can be reading from and writing to spanner, Dataflow will have up to 300 threads per worker, which potentially means 300 simultaneous read sessions, and 300 simultaneous downstream writes.

In some scenarios, this can lead to session pool exhaustion, followed by a worker failing due to this flag.

**Comment by Abacn** [comment]
thanks. could you please open a cherry-pick PR, that is checkout release-2.60.0 branch, run `git cherry-pick bcd785f`, and open a PR with release-2.60.0 as the base branch, similar to #32663

**Comment by nielm** [comment]
> thanks. could you please open a cherry-pick PR, that is checkout release-2.60.0 branch, run `git cherry-pick bcd785f`, and open a PR with release-2.60.0 as the base branch, similar to #32663

Done: #32702

**Pull request merged**
