### PR TITLE
Clean up stale code in BigtableService

### PR DESCRIPTION
**Pull request by mutianf**
The underlying issue with attempt timeout is fixed in the Bigtable client. We don't need to pass around operation and attempt timeout in the reader anymore. This PR cleans up the code that's not used anymore.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Are these "stale code" not used in Beam, i.e., there is currently no way to make this code in effect; or it's not needed? If it still can make some effect on Beam I would suggests defer the clean up until we see the issue no longer exist for a time period

**Comment by damondouglas** [comment]
@mutianf I'll have a look at it. Apologies for your wait.

**Review by damondouglas — APPROVED** [review]

**Comment by damondouglas** [comment]
@mutianf LGTM, would you like me to merge this?

**Review by igorbernstein2 — APPROVED** [review]

**Comment by Abacn** [comment]
This one has taken long. Going to merge it in 24 hrs if no other concern

**Pull request merged**
