### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by boyuanzz**
Please comment as instructions below:
  Run Go PostCommit
  Run Java PostCommit
  Run Java PortabilityApi PostCommit
  Run Java Flink PortableValidatesRunner Batch
  Run Java Flink PortableValidatesRunner Streaming'
  Run Apex ValidatesRunner
  Run Dataflow ValidatesRunner
  Run Flink ValidatesRunner
  Run Gearpump ValidatesRunner
  Run Dataflow PortabilityApi ValidatesRunner
  Run Samza ValidatesRunner
  Run Spark ValidatesRunner
  Run Python Dataflow ValidatesContainer
  Run Python Dataflow ValidatesRunner
  Run Python Flink ValidatesRunner
  Run Python PostCommit
  Run SQL PostCommit
  Run Go PreCommit
  Run Java PreCommit
  Run Java_Examples_Dataflow PreCommit
  Run JavaPortabilityApi PreCommit
  Run Portable_Python PreCommit
  Run Python PreCommit

### CODE REVIEW

**Comment by swegner** [comment]
It looks like only one check was run. Do you if there's a requirement to specify each trigger phrase separately?

**Comment by swegner** [comment]
Run Go PreCommit
Run Java PreCommit

**Comment by swegner** [comment]
Run Samza ValidatesRunner
Run Spark ValidatesRunner

**Comment by boyuanzz** [comment]
Run Go PostCommit

**Comment by boyuanzz** [comment]
So you need to copy the phrase per comment. I think I updated the description here: https://github.com/apache/beam/pull/7509/files#diff-d7850f2c9e5a82efefbc6ad24f3447d1R167

**Pull request closed without merging**
