### PR TITLE
Adding Autocomplete IT for Java once more

### PR DESCRIPTION
**Pull request by pabloem**
r: @jasonkuster 
This reverts commit e3ddecdda6587233b333da4aa8a0e0dba66c7337.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
The problem was that the pipeline is run via the `main` method, and it should be run as a JUnit test, via the `@Test`-marked methods.

**Comment by jasonkuster** [comment]
LGTM -- thanks!

**Comment by jasonkuster** [comment]
Is there a JIRA for this?

**Pull request merged**
