### PR TITLE
Fix error-prone warnings for google-cloud-platform IO

### PR DESCRIPTION
**Pull request by timrobertson100**
Really simple PR to fix error-prone warnings in google-cloud-platform IO

( CC @iemejia )

### CODE REVIEW

**Comment by iemejia** [comment]
R: @jkff by randomly assigning reviewers for the fixes on error-prone

**Comment by timrobertson100** [comment]
retest this please

**Comment by jkff** [comment]
LGTM thanks!

**Comment by timrobertson100** [comment]
Thanks @jkff

**Pull request merged**
