### PR TITLE
[BEAM-7603] Support for ValueProvider-given GCS Location for WriteToBigQuery w File Loads

### PR DESCRIPTION
**Pull request by pabloem**

### CODE REVIEW

**Comment by pabloem** [comment]
https://github.com/apache/beam/pull/8833

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
Run Python PreCommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
run python precommit

**Comment by akedin** [comment]
run python precommit

**Comment by pabloem** [comment]
The failures look suspicious to me. Maybe related to recreating some containers?

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
@tvalentyn any idea about the ':sdks:python:test-suites:tox:py37:testPython37'. failure on the release branch ? 
https://builds.apache.org/job/beam_PreCommit_Python_Phrase/550/consoleFull

Seems to be unrelated to this PR.

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
We investigate Py3 failures as any other failures, in this case it is a flake
```16:29:26 ERROR: test_approximate_unique_global_by_sample_size (apache_beam.transforms.stats_test.ApproximateUniqueTest)
```
@Hannah-Jiang is looking into this flake in https://issues.apache.org/jira/browse/BEAM-7548.

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by akedin** [comment]
Re-ran the python precommit manually, all seems green: https://scans.gradle.com/s/3s7bzzralmq6w , merging

**Comment by pabloem** [comment]
Thank you Anton!

**Pull request merged**
