### PR TITLE
[BEAM-1743] Use CreatePCollectionView explicitly in CombineGloballyAsSingletonView

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Implement View.asSingleton as a CombineGloballyAsSingletonView.

This stops any writing of a SingletonView that is not actually a
Singleton View. - i.e. the contents (which can never be read) cannot
be provided to the View.CreatePCollectionView transform, as they must
go through a combiner before they arrive.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by aaltay** [comment]
@kennknowles any progress on the review?

**Comment by tgroh** [comment]
This probably isn't actually suitable for review yet - the failures are real, and I haven't had time to actually investigate and fix them.

**Comment by tgroh** [comment]
This should be ready for review.

**Comment by tgroh** [comment]
Run Dataflow RunnableOnService

**Comment by tgroh** [comment]
Run Dataflow RunnableOnService

**Comment by tgroh** [comment]
This should now be ready to review.

@kennknowles

**Comment by kennknowles** [comment]
LGTM

**Pull request closed without merging**
