### PR TITLE
[BEAM-1311] Check that a Multi-Output map contains the Tag, not the TaggedValue

### PR DESCRIPTION
**Pull request by tgroh**
Fixes Flink Batch translation.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This broke Flink Batch execution for pipelines that contained a Multi-output ParDo.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi @aljoscha (ANY)

**Comment by dhalperi** [comment]
Kicked off postcommit test: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1434/

Thomas thinks this will work.

**Comment by tgroh** [comment]
Well, it should reduce the failing tests to only be in streaming. Looking
into those now.

**Comment by dhalperi** [comment]
9 fewer failures, change makes sense. LGTM.

**Comment by dhalperi** [comment]
(please file a JIRA for the breakage, and self-merge at your discretion.)

**Comment by tgroh** [comment]
Added fix for streaming

https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1436/

**Comment by aljoscha** [comment]
Ahh, that causes the failures. Saw this PR to late because I was drowning in mail after returning from vacation.

LGTM!

**Comment by dhalperi** [comment]
retest this please

**Comment by dhalperi** [comment]
Kicked off https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1440/ to see if it fixes the Flink postcommit.

Still LGTM to merge when green.

**Pull request closed without merging**
