### PR TITLE
[BEAM-1777] In certain circumstances PipelineEnforcement shades exceptions.

### PR DESCRIPTION
**Pull request by staslev**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by staslev** [comment]
Run Spark ValidatesRunner

**Comment by staslev** [comment]
R: @tgroh

**Comment by tgroh** [comment]
Is it possible to add a test that throws during the call to `run()` and also in the `afterPipelineExecution` and ensure that the message is from the call to `run()`?

**Comment by tgroh** [comment]
If not really feasible, LGTM. else, I'd like to take a look at the test.

**Comment by staslev** [comment]
After this change, `TestPipeline#run()` looks like so:

```java
public PipelineResult run() {
   ...
    try {
      ...
      pipelineResult = super.run();
    } catch (RuntimeException exc) {
      Throwable cause = exc.getCause();
      if (cause instanceof AssertionError) {
        throw (AssertionError) cause;
      } else {
        throw exc;
      }
    }

    enforcement.get().afterPipelineExecution();
    ...
  }
```

So in case of an exception in `super.run()`, I would not expect the flow to reach `afterPipelineExecution()`, which makes the kind of test you mention quite challenging.

**Comment by tgroh** [comment]
The way that I encountered this is with a `PTransformOverride` that throws an exception in the call to `apply`, but that seems overly complex. Certainly a comment with the `afterPipelineExecution` call would be worthwhile.

Otherwise, LGTM. Feel free to merge as appropriate.

**Pull request closed without merging**
