### PR TITLE
[CdapIO] Add integration tests for CdapIO (Batch)

### LINKED ISSUE #22315: [Cdap IO][Task]: Implement integration tests for CDAP IO batch interface
### Context 
There is [CDAP IO write/read interface](https://github.com/apache/beam/tree/master/sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap) for processing data from [CDAP plugins](https://github.com/data-integrations).

### Task
It's needed to implement a CDAP IO integration test for batch data processing. 

### Acceptance criteria
1. Implemented integration test in the `beam/sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOIT.java`
2. Described the Jenkins job for running the CdapIOIT and needed resources for testing in `beam/.test-infra/`
3. Documentation on how to run the CDAP integration tests

### Issue Component
Component: io-java-cdap

### PR DESCRIPTION
**Pull request by Amar3tto**
Resolves #22315 

- Added test CDAP `Plugin`s for reading/writing from/to PostgreSQL database and Input/Output `Format`s and `FormatProvider`s for these plugins.
- Added `CdapIOIT` class  on `HadoopFormatIOIT` with integration test that performs the following:
- - Writes `TestRowDBWritable`s to the PostgreSQL database using `DBBatchSink` CDAP plugin.
- - Reads test rows from the PostgreSQL database using `DBBatchSource` CDAP plugin.
- - Asserts expected and actual hashcodes for given `rowCount`.
- Added Jenkins job called **_job_PerformanceTests_CdapIO_** for running `CdapIOIT` tests.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Spotless PreCommit

**Comment by Amar3tto** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by Amar3tto** [comment]
Run Java CdapIO Performance Test

**Comment by Amar3tto** [comment]
Run seed job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Java CdapIO Performance Test

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by Lizzfox** [comment]
@chamikaramj Cham, PR is ready for review. Thanks!

**Comment by aromanenko-dev** [comment]
Run Java CdapIO Performance Test

**Review by chamikaramj — APPROVED** [review]
Please also make sure that the benchmark results are available in http://metrics.beam.apache.org/.

LGTM.

**Pull request merged**
