### PR TITLE
Keep stale action from closing issues

### PR DESCRIPTION
**Pull request by damccorm**
This config will keep stale bot from closing issues like it has recently started to do (https://github.com/actions/stale#days-before-issue-close for config option)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @aaltay @kennknowles @Abacn (https://github.com/apache/beam/issues/22011#issuecomment-1239652250 for context)

**Review by riteshghorse — APPROVED** [review]

**Comment by aaltay** [comment]
Thank you!

Do we know why did this starting happening recently?

**Comment by damccorm** [comment]
I'm not 100% sure, but I think there were 2 factors that kept it from happening until now:

1) The default for the action is 60 days before marking stale and another 7 days before closing.
2) The action batches its processing of issues and will only perform up to 30 actions (labeling or closing).

I think those combined with us not running the bot very often (its only run daily) kept the bot from closing lots of issues since its been ~90 days since the migration to issues.

FWIW, the core miss here was that this automation would automatically pick up issues without further action on our part.

**Comment by aaltay** [comment]
Got it. Thank you for the detailed explanation.

**Pull request merged**
