### PR TITLE
Rename from default-pool to pool-1

### PR DESCRIPTION
**Pull request by damccorm**
This pool recently got renamed, breaking https://ci-beam.apache.org/job/Rotate%20IO-Datastores%20Cluster%20Credentials/

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Thanks. There is another occurrence of default-pool: https://github.com/apache/beam/blob/4718cdff87fed4f92636e94dbf3a04c2315d6a95/.test-infra/jenkins/job_MetricsCredentialsRotation.groovy#L38

**Comment by damccorm** [comment]
That's on the metrics cluster, though, right? Did both change?

**Comment by Abacn** [comment]
> That's on the metrics cluster, though, right? Did both change?

Oops, no, that one did not change.

**Review by Abacn — APPROVED** [review]

**Comment by damccorm** [comment]
Run Seed Job

**Comment by damccorm** [comment]
Run Rotate IO-Datastores Cluster Credentials

**Comment by damccorm** [comment]
Oops, it looks like my seed job got overrun by another one.

**Comment by damccorm** [comment]
Run Seed Job

**Pull request merged**
