### PR TITLE
[BEAM-12672] Add plugin to retry flaky tests

### PR DESCRIPTION
**Pull request by benWize**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Hi @aaltay, I'm working on BEAM-12672, but after some testing I'm getting two cases for different configs, maybe you can give me some guidance.
 I added this test  to reproduce a flaky test. https://github.com/apache/beam/blob/46af36fea099e4255bf00f02593940839ce79ca6/sdks/java/core/src/test/java/org/apache/beam/sdk/DummyTest.java#L32.
In this JavaPrecommit this test is marked as `passed` https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4407/testReport/org.apache.beam.sdk/DummyTest/,  but in the console, it shows a failure before a success https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4407/console.
The first failure has not been recorded at test results in Jenkins.
Also, the failed test https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4407/testReport/org.apache.beam.sdk.fn.data/BeamFnDataInboundObserver2Test/ was rerun several times (https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4407/console) but just the last one was recorded.
This happens when the option `mergeReruns` (https://docs.gradle.org/current/userguide/java_testing.html) at https://github.com/apache/beam/blob/46af36fea099e4255bf00f02593940839ce79ca6/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L416 is set as `true`.
When the option `mergeReruns` is not set as true, Jenkins records the multiple reruns https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4392/testReport/org.apache.beam.sdk/DummyTest/ but the global status execution is marked as UNSTABLE (https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4392/), which shows a failure in Github Checks UI.
Also with the `mergeReruns` disabled, Gradle scans shows the tests as flaky https://scans.gradle.com/s/32e4qwltztojq/tests/:sdks:java:core:test/org.apache.beam.sdk.DummyTest/testFlakiness?top-execution=1.
At this time, I'm not sure which path accomplishes better the requirements by this task, so I want to ask you for your guidance on this.

**Comment by aaltay** [comment]
@benWize - I do not know much about the jenkins/gradle configs unfortunately. Could you ask on the dev@ list?

**Comment by aaltay** [comment]
> @benWize - I do not know much about the jenkins/gradle configs unfortunately. Could you ask on the dev@ list?

I think neither option is ideal really. The best outcome would be test marked as passing or unstable, github UI showing passing, all tests results being available. I do not know if that is possible.

**Comment by benWize** [comment]
> I think neither option is ideal really. The best outcome would be test marked as passing or unstable, github UI showing passing, all tests results being available. I do not know if that is possible.

Thanks, @aaltay, I tried with this plugin https://plugins.jenkins.io/flaky-test-handler/ in my local Jenkins setup, and with that plugin and this config https://github.com/apache/beam/blob/6d4af1cc8024e0f86d77fbcc66bf93030633f3d1/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L410 the flaky tests were marked as passing, with a label: "flaked with N failures". Also, all tests results are available, and the global status of the job is marked as a success, so the GitHub UI is expected to show the check as passing. I will ask in dev@ list for help installing that plugin and for further review on this.


Screen Shot 2021-12-22 at 17 44 36
Screen Shot 2021-12-22 at 17 43 33
Screen Shot 2021-12-22 at 17 44 07

**Comment by aaltay** [comment]
That actually looks like a great outcome.

I am not sure what is required to install that plugin. dev@ list could help, please also cc @kennknowles on the email.

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Python PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Python PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Java PreCommit

**Comment by benWize** [comment]
Run Python PreCommit

**Comment by benWize** [comment]
Verified that [Python Precommi](https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2874/testReport/apache_beam.coders.coders_test/)t and [Java Precommit](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4578/testReport/org.apache.beam.examples/) have flaky test info and failed tests are rerun.
Also, tests that were rerun have [info](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4578/testReport/org.apache.beam.sdk.transforms/GroupIntoBatchesTest/testBufferingTimerInFixedWindow/) of each run

**Comment by kileys** [comment]
Can we add this to all the precommit tests?

**Comment by aaltay** [comment]
> Can we add this to all the precommit tests?

Probably not a good idea. If we do that we will gradually move tests to become flaky.

/cc @kennknowles

**Comment by benWize** [comment]
> Can we add this to all the precommit tests?

Yes, we just need to add -PretryFlakyTest=true and configure the publisher as https://github.com/apache/beam/blob/841a355936a1d32d13bcfde4db3d3ed2da7eb193/.test-infra/jenkins/job_PreCommit_Java.groovy#L45

**Review by kileys — APPROVED** [review]

**Comment by aaltay** [comment]
This plugin was disabled due to (https://issues.apache.org/jira/browse/INFRA-22878). 

@kileys - Should we rollback this change?

**Comment by benWize** [comment]
> This plugin was disabled due to (https://issues.apache.org/jira/browse/INFRA-22878).
> 
> @kileys - Should we rollback this change?

I think we should, this config isn't going to work without the plugin

**Comment by benWize** [comment]
Opened #16930 to revert this

**Comment by kileys** [comment]
Thanks Benjamin

**Comment by aaltay** [comment]
Thank you @benWize.

**Pull request merged**
