### PR TITLE
Add dry run option to DataflowRunner in python SDK

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @robertwb

**Comment by robertwb** [comment]
Could we perhaps add this as a pipeline option so `p.run()` (including called implicitly by being a context) would still work rather than having to store the runner and call `runner.run(p)`?

**Comment by vikkyrk** [comment]
Yes I think would be better. Where would option be defined under, `TestOptions` maybe?

**Comment by robertwb** [comment]
+1 to TestOptions.

**Comment by vikkyrk** [comment]
Done

**Comment by vikkyrk** [comment]
Retest this please

**Comment by robertwb** [comment]
LGTM

**Pull request closed without merging**
