### PR TITLE
[Website] update Available contact channels table content

### LINKED ISSUE #22696: [Bug]: Contact us. The Action of the purpose "Contact users and contributors in real time through the ASF slack workspace" contains  the word "#general" without the link
### What happened?

Steps to reproduce: 

1. Open the website page [Community](https://beam.apache.org/community/)
2. Click on the button "Contact US" in the navbar or footer
3. Find the section "Available contact channels"
4. Look at the Action of the purpose "Contact users and contributors in real time through the ASF slack workspace"

Actual result: The action contains the word "#general" without the link
Expected result: The action contains the word "#general" with the link

ASF Slack - #general was renamed to #announcements. 

### Issue Priority

Priority: 0

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22696
- remove text from Available contact channels table 
________________________________________________________________________________________________________________________________
before:
before_channels

after:
after_channels

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
@pcoet, could you, please, help with review?

**Review by pcoet — APPROVED** [review]

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, help with merge?

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by bullet03** [comment]
> LGTM

Thank you!

**Pull request merged**
