### PR TITLE
[BEAM-4046, BEAM-7527] Fix benchmark with correct Gradle project

### PR DESCRIPTION
**Pull request by markflyhigh**
Beam benchmarks use Gradle to run integration tests. Since Gradle project name is changed in BEAM-4046, need to apply to benchmark framework as well.

Working in progress to change on Perfkit side.
**Do not merge only after Perfkit changes are merged** since Beam benchmark tests use master branch of [PerfkitBenchmarker](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker). These are incompatible changes and will make benchmarks fail if merge first.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lgajowy** [comment]
Note for the future work: you can use phrase triggering to trigger the IOITs, eg type `Run Java JdbcIO Performance Test` in comment. More info: https://beam.apache.org/documentation/io/testing/#running-integration-tests

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by markflyhigh** [comment]
Run Python27 WordCountIT Performance Test

**Comment by markflyhigh** [comment]
Run Seed Job

**Comment by markflyhigh** [comment]
Run Python27 WordCountIT Performance Test

**Comment by markflyhigh** [comment]
run seed job

**Comment by markflyhigh** [comment]
Run Java ParquetIO Performance Test

**Comment by markflyhigh** [comment]
Run Python27 WordCountIT Performance Test

**Comment by markflyhigh** [comment]
run seed job

**Comment by markflyhigh** [comment]
Realized that the changes on PerfkitBenchmarker (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1934) only pass Python tests but not Java. My quick fix (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1936) is out waiting for review.

In order to run Jenkins job based on Perfkit fix, I pointed PerfkitBenchmarker git repo to my fix branch in this PR and both Java ParquetIOPerformance and Python WordCountIT passed:
- https://builds.apache.org/job/beam_PerformanceTests_ParquetIOIT/1616/
- https://builds.apache.org/job/beam_PerformanceTests_WordCountIT_Py27/164/

Given that review on Perfkit may take a day or two, Java benchmarks will be blocked during this period, I would prefer to point PerfkitBenchmarker repo to my fix branch first and I'll switch back to master once it's merged. Would love to create a jira tracking this if make sense to you.

**Comment by lgajowy** [comment]
That's ok. Thank you for doing this. I don't think changing the fork is necessary - let's wait until the Perfkit change gets merged. We can intervene after some longer period of time in case the change is not merged but from what I see it shouldn't be the case (it was approved).

This situation (once again) shows that this is not good that Beam tests are dependent on Perfkit's master. Currently, any breaking change can turn lots of our tests red. Do you by any chance know if it is possible to keep all benchmark beam code from Perfkit (`beam_benchmark_helper.py`, `beam_integration_benchmark.py`) in beam repository and inject it to perfkit every time we use it? I think that would be the best solution in our case. We could do whatever we want in beam_benchmark code without the need to submit PRs everytime we want to change anything. 

Alternatively, maybe we could drop Perfkit (at least for IOITs this is doable right now).

**Comment by markflyhigh** [comment]
SGTM. Let's wait for https://github.com/apache/beam/pull/8919 merge.

As for dependent on Perfkit master, I would prefer remove Perfkit at all since there are few other issues that limit our benchmarks. For example:
1. Black box testing which hard to collect pipeline related metrics.
2. Measurement of runtime is inaccurate. 
3. Can't run in Python3 (depends on py2 only library like `functools32`)
4. `beam_integration_benchmark.py` inherit the complexity of Perfkit framework and require some knowledge to maintain.

**Comment by markflyhigh** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1936 is merged, I'll start testing this PR.

**Comment by markflyhigh** [comment]
run seed job

**Comment by markflyhigh** [comment]
Run Python27 WordCountIT Performance Test

**Comment by markflyhigh** [comment]
Run Java ParquetIO Performance Test

**Comment by markflyhigh** [comment]
run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
I agree with you. From the IOIT perspective, only the code that setups/tears down Kubernetes resources is useful but these parts can be easily implemented in jenkins/gradle code. Once this is done we can remove Perfkit in all IOITs. 

It sounds like the way to go but I will ping the devlist with this thread to see if there are any objections.

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by lgajowy** [comment]
Run Python27 WordCountIT Performance Test

**Comment by lgajowy** [comment]
All jobs worked. Merged. Thanks!

**Pull request merged**
