### PR TITLE
fix dataloss bug in batch Storage API sink.

### PR DESCRIPTION
**Pull request by reuvenlax**
Two issues fixed:
   1. Retry behavior was incorrect. We created a new stream abandoning the old, but then only retried the current append.
   2.  Offset was inadvertently reset to 0 the first time we called append, which meant that the second append would always fail with invalid offset. This triggered the data-loss bug in 1.

We fixed the offset bug and no longer create a new stream on failure. In cases where the stream is known to be unusable (e.g. it's been deleted), we raise an exception which forces retry of the entire work item.

### CODE REVIEW

**Comment by johnjcasey** [comment]
LGTM. This will break storage api writes for now, but we will no longer have false positive results

**Comment by johnjcasey** [comment]
LGTM

**Comment by johnjcasey** [comment]
fixes #26521 and #26520

**Comment by kennknowles** [comment]
Why isn't there a test for this?

**Comment by reuvenlax** [comment]
Good question - there should be a unit test, and I believe this would be
fairly easy to reproduce in a unit test.

**Comment by ahmedabu98** [comment]
We only have one test case that indirectly tests for multiple stream appends, and it uses streaming mode (while this error occurs in batch): https://github.com/apache/beam/blob/03ecb158f9a24a0e956d79c6d096d353d6b28a7b/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIOWriteTest.java#L1971-L1976

**Comment by kennknowles** [comment]
Yea let's add a batch test that reproduces the issue at the commit before the fix, and confirms it fixed. Keep the bug open until the test is in.

**Comment by ahmedabu98** [comment]
I'll write up the test and tag @reuvenlax to review

**Pull request merged**
