### PR TITLE
Populate PBegin input when decoding from Runner API

### PR DESCRIPTION
**Pull request by charlesccychen**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @robertwb

**Comment by charlesccychen** [comment]
As a side note, I find it very surprising that () | Flatten(...) is allowed in the model.  It makes the reasonable expectation that the pipeline DAG traces back to PBegin through all paths non-intuitive.  Should we consider changing this behavior?

**Comment by charlesccychen** [comment]
As a side note, I find it very surprising that () | Flatten(...) produces an AppliedPTransform with no inputs, and that it is allowed in the model.  It makes the reasonable expectation that the pipeline DAG traces back to PBegin through all paths false just for this special case, which is non-intuitive.  Should we consider changing this behavior?

**Comment by robertwb** [comment]
LGTM

PBegin is not part of the model; technically these are simply zero-input PTransforms. PBegin is simply an artifact of the SDK. Not being able to handle the degenerate flatten would be a regression.

**Comment by charlesccychen** [comment]
Thanks! Can you please merge?

**Pull request closed without merging**
