### PR TITLE
[BEAM-12579] Don't hold watermark for expiry timer

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Pull request merged**
