### PR TITLE
Improve tox installation for python sdk

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @aaltay 

While testing the vote for 0.6.0 I had issues because the tox installation was not working correctly in my system. These two changes solve it.
Some explanation:
The --user is not needed if you are already working in a virtualenv.
and since the first step install tox in the virtualenv it will be available for the whole virtualenv so no need to prefix the invocation of tox.

**Comment by aaltay** [comment]
This is going to fail in Jenkins and for all users who do not have `tox` installed globally. Installing `tox` as a user package is generally safe. How does it fail for you?

**Comment by iemejia** [comment]
I just saw how it broke, not nice, but I still think we can improve this (I hope).

I am super radical with python and I don't even have user packages via pip installed I go for everything through a virtualenv, and I think this should be the case for jenkins too.
If you start from a clean install and you create/activate a virtualenv the path of the virtualenv becomes part of your path, so when maven installs tox it does not install it globally or even as part of the user site-packages, it resides just in the path of the virtualenv (e.g. in my case ~/.virtualenvs/beam/bin).
Maybe we can configure maven to behave more like this, because it is the most 'jailed' possible case.

Snce I don't have tox installed at user level or root, when I run from the activated virtualenv I have this error:
```
[INFO] --- exec-maven-plugin:1.5.0:exec (setup-test-tox) @ beam-sdks-python ---
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by iemejia** [comment]
But if I apply the two changes I put in this PR is fixed.

**Comment by aaltay** [comment]
@iemejia I believe there are two issues. 1) `virtualenv` is not installed by default. This is not a jenkins specific problem, this is the for a basic python installation. 2) `tox` manages a virtualenv, running `tox` inside the virtualenv does not make such sense, but we can switch to it. I am not sure it works correctly or not though (i.e. virtualenv in virtualenv). Even if we address 2), because of 1) we will continue to install user packages.

If we take a step, the instructions for running the maven script does not require setting up a `virtualenv`. It will create one as part of the process and use it. If you think that user installed packages are an issue, we can remove them at the clean phase maybe.

**Comment by iemejia** [comment]
Yes @aaltay the leaking of the tox dependency on the user for me is an issue, this is for me the whole reason to use virtualenvs, to contain some how all the dependencies.
I am preparing a dockerfile that fully validates a release, so we can have a reproducible case, let's keep this PR open so we can discuss on this and eventually fix this if still an issue.

**Comment by aaltay** [comment]
@iemejia 

Thank you. I agree that it would be better if we can run `tox` inside `virtualenv`, if possible. We can also address the user pain first and uninstall `tox` as a stop gap measure.

Do you want to move this discussion to JIRA?

**Comment by iemejia** [comment]
Uninstalling the tox dependency afterwards is not a good idea because the user could have installed it before so we will change his work environment.
Great idea to continue the discussion/fix in JIRA, doing it right now.

**Pull request closed without merging**
