### PR TITLE
Trigger for Java SDK post submit tests

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @jasonkuster @davorbonaci

**Comment by vikkyrk** [comment]
Run Java PostCommit
(Testing if this works or needs to be submitted)

**Comment by jasonkuster** [comment]
Seed job needs to run, but this LGTM

**Comment by vikkyrk** [comment]
I was looking for a way to run Post Commit tests against my PR but could not find an easy way. So having a trigger for post submit java tests makes sense to me given that python SDK already has it ( https://github.com/apache/beam/blob/master/.test-infra/jenkins/job_beam_PostCommit_Python_Verify.groovy#L37)

**Comment by kennknowles** [comment]
I also needed this recently, LGTM and I'll merge.

**Pull request merged**
