### PR TITLE
[BEAM-7196] Add Display Data to FileIO Match/MatchAll

### PR DESCRIPTION
**Pull request by iemejia**
R: @chamikaramj

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
LGTM

**Comment by iemejia** [comment]
Thanks @chamikaramj I still have two more PRs related to FileIO and friends and then I won't bother you more for some time :)

**Comment by chamikaramj** [comment]
Hopefully I got everything. Lemme know if not :)

**Pull request merged**
