### PR TITLE
[BEAM-3156] Fix BigTableIO to use non-deprecated Futures.addCallback function

### PR DESCRIPTION
**Pull request by rniemo-g**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ x] Each commit in the pull request should have a meaningful subject line and body.
 - [ x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Jira issue: https://issues.apache.org/jira/browse/BEAM-3156
This PR changes which Futures.addCallback() overload we call. This is because the overload we're using is being deprecated.

---

### CODE REVIEW

**Comment by reuvenlax** [comment]
lgtm

**Comment by chamikaramj** [comment]
LGTM. I'll merge.

Thanks.

**Comment by chamikaramj** [comment]
Run Java PreCommit.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by rniemo-g** [comment]
Run Java PreCommit

**Comment by rniemo-g** [comment]
It looks like the failed test was a timeout -- mind taking a look at this again?

**Comment by chamikaramj** [comment]
Looks like Jenkins  is stable now. I'll wait for the current run.

**Pull request merged**
