### PR TITLE
[BEAM-3177][BEAM-5468] Add pipeline options to set default logging level

### PR DESCRIPTION
**Pull request by Abacn**
* Python counterpart of existing --defaultSdkHarnessLogLevel pipeline options
  in Java sdk

* Still need updates from worker side to make it working in DataflowRunner

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @tvalentyn
R: @robertwb

**Comment by Abacn** [comment]
Was doing [BEAM-14147](https://issues.apache.org/jira/browse/BEAM-14147) but apparently this is a blocker. Along with this change still need an update from dataflow worker side to call logger.initialize with the added log_level parameter.

**Comment by robertwb** [comment]
The failure at apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithGrpcAndMultiWorkers.test_pardo_large_inputlooks irrelevant.

**Comment by robertwb** [comment]
Run Python PreCommit

**Comment by johnjcasey** [comment]
LGTM

**Comment by Abacn** [comment]
rebased due to conflicts of TODO label changes on master

**Comment by Abacn** [comment]
Run Python PreCommit

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
