### PR TITLE
Rename COMBINE_TRANSFORM_URN to the more proper COMBINE_PER_KEY_TRANSFORM_URN

### PR DESCRIPTION
**Pull request by iemejia**
It also exposes COMBINE_GLOBALLY_TRANSFORM_URN
R: @tweise

### CODE REVIEW

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Run Samza ValidatesRunner

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Run Samza ValidatesRunner

**Comment by lukecwik** [comment]
CC: @youngoli

**Pull request merged**
