### PR TITLE
[BEAM-1642] Try PTransform-based coder inference before using fallback coder.

### PR DESCRIPTION
**Pull request by robertwb**
This is particularly important for fallback coders that claim
to provide a coder for Object (or equivalently an unconstrained
type parameter).  See BEAM-1642.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @tgroh

**Comment by tgroh** [comment]
Nice.

**Comment by kennknowles** [comment]
That order does seem sensible. It all comes from whether we consider the coder registry to be carefully curated by a user, in which case it should still have precedence.

**Comment by kennknowles** [comment]
I think the order of (1) use non-fallbacks in the registry then (2) use the transform's coder and then (3) use fallback. 1 and 3 are basically orthogonal.

**Comment by kennknowles** [comment]
But really if someone went to the trouble to implement `getDefaultOutputCoder` they probably know best. So this change also LGTM, it is just a change in the intent and I wanted to note that.

**Comment by robertwb** [comment]
Yes. Also, the registry is pipeline-level, getDefaultOutputCoder is
scoped (and overridden) at a transform level, and finally setCoder()
is per-instance. Note that many transforms (in particular those with
type parameters) still re-invoke the coder registry (but with more
context than we have here).

I'll ensure all tests pass (hopefully jenkins is back up and running
again soon, looks like it's not taking any more builds right now).

**Comment by robertwb** [comment]
I fixed the test, PTAL.

**Comment by kennknowles** [comment]
LGTM

**Pull request closed without merging**
