### PR TITLE
Cherry-pick pull request #2649 into release-2.0.0 branch

### PR DESCRIPTION
**Pull request by aviemzur**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by aviemzur** [comment]
R: @jbonofre

**Comment by dhalperi** [comment]
R: @davorbonaci too – for cherry-picks into release branch, release manager should see them all.

**Comment by aviemzur** [comment]
Any news for this one? @dhalperi @jbonofre @davorbonaci

**Comment by kennknowles** [comment]
(this PR has now been cherry-picked into the release branch)

**Pull request closed without merging**
