### PR TITLE
[BEAM-3826] Tweak Go integration test driver

### PR DESCRIPTION
**Pull request by herohde**
* Rename parameter as per design doc feedback

### CODE REVIEW

**Comment by herohde** [comment]
Run Go PostCommit

**Comment by herohde** [comment]
R: @jasonkuster

**Comment by jasonkuster** [comment]
@herohde I assume this PR is not actually referencing BEAM-386, Java Dataflow runner to support Read.Bounded in streaming mode. ;) Can you update PR title to correct JIRA? I will merge after that.

**Comment by herohde** [comment]
Done. Thanks @jasonkuster !

**Comment by herohde** [comment]
@jasonkuster Do you have a moment to merge?

**Pull request merged**
