### PR TITLE
[BEAM-11227] Moving from vendored gRPC 1.26 to 1.36

### PR DESCRIPTION
**Pull request by suztomo**
The vendored gRPC artifact is available in Maven Central: https://search.maven.org/artifact/org.apache.beam/beam-vendor-grpc-1_36_0/0.1/jar . This PR uses the artifact and deletes the reference to the old gRPC 1.26.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by suztomo** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by suztomo** [comment]
Run SQL Postcommit

**Comment by suztomo** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Dataflow ValidatesRunner

**Comment by suztomo** [comment]
Run Spark ValidatesRunner

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run SQL Postcommit

**Review by kennknowles — APPROVED** [review]
Excellent!

**Comment by kennknowles** [comment]
run flink validatesrunner

**Review by kennknowles — APPROVED** [review]
I'll merge when green. Give me a ping if I forget. (once I approve GitHub takes it off my list of "review requests")

**Review by kennknowles — APPROVED** [review]
I'll merge when green. Give me a ping if I forget. (once I approve GitHub takes it off my list of "review requests")

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
The Java precommit check succeeded after 6 failures.

Screen Shot 2021-03-23 at 10 26 13

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
The last one was not timeout

```
org.apache.beam.sdk.io.TextIOWriteTest.testWriteViaSink

java.lang.AssertionError: Read All/TextIO.ReadFiles/Read all via FileBasedSource/Read ranges/ParMultiDo(ReadFileRanges).output: 
Expected: iterable with items ["a", "b", "c", "d", "e", "f"] in any order
     but: not matched: "c"

```

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Unstable.

org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInFinishBundleStateful failed.

```
java.lang.AssertionError: Function should have been torn down after exception
Expected: is <TEARDOWN>
     but: was <START_BUNDLE>
```

https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/3246

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
🤔

Screen Shot 2021-03-23 at 14 51 59

**Comment by suztomo** [comment]
org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInFinishBundleStateful failed https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/3250/.

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
org.apache.beam.sdk.metrics.MetricsTest$AttemptedMetricTests.testAllAttemptedMetrics failed 

```
java.lang.AssertionError: 
Expected: a collection containing MetricResult{inNamespace="org.apache.beam.sdk.metrics.MetricsTest", name="bundle", step="MyStep1", attemptedMin=<10L>, attemptedMax=<40L>}
     but: mismatches were: [MetricResult{inKey: <MyStep1:org.apache.beam.sdk.metrics.MetricsTest:bundle> != <MyStep1/ParMultiDo(Anonymous):org.apache.beam.sdk.metrics.MetricsTest:input>attemptedMin: <10L> != <5L>attemptedMax: <40L> != <13L>}, MetricResult{inKey: <MyStep1:org.apache.beam.sdk.metrics.MetricsTest:bundle> != <MyStep2:org.apache.beam.sdk.metrics.MetricsTest:input>attemptedMin: <10L> != <5L>attemptedMax: <40L> != <13L>}, MetricResult{inKey: <MyStep1:org.apache.beam.sdk.metrics.MetricsTest:bundle> != <MyStep1/ParMultiDo(Anonymous):org.apache.beam.sdk.metrics.MetricsTest:bundle>attemptedMax: <40L> != <10L>}]
```

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
https://ci-beam.apache.org/job/beam_BiqQueryIO_Streaming_Performance_Test_Java/ looks generally unhealthy

**Comment by kennknowles** [comment]
run java postcommit

**Comment by suztomo** [comment]
@kennknowles "BigQueryIO Streaming Performance Test Java 10 GB" has been timed-out before this PR: https://ci-beam.apache.org/job/beam_BiqQueryIO_Streaming_Performance_Test_Java/

**Comment by suztomo** [comment]
Java Precommit is unstable with this PR. Sometimes it succeeds. This PR of upgrading gRPC might be introducing randomly failing tests (`ParDoLifecycleTest`, `MetricsTest$AttemptedMetricTests` above, yesterday it was timed-out).

Screen Shot 2021-03-23 at 17 02 37

(Compare this to an empty change with 5 consecutive success https://github.com/apache/beam/pull/14307#issuecomment-805255582)

@kennknowles  The failures are from different test classes. Have you observed such problematic PRs in past?

**Comment by kennknowles** [comment]
I can see in the log that there was already a failure in `org.apache.beam.sdk.io.gcp.healthcare.FhirIOLROIT > test_FhirIO_deidentify`. I don't know if this is meaningful without seeing some logs.

**Comment by kennknowles** [comment]
CC @amaliujia who is interested in watching the perf when this goes in

**Comment by kennknowles** [comment]
Hmm in the precommit those would be running on DirectRunner.

**Comment by suztomo** [comment]
Memo for myself: I tried this script to reproduce one of the failed tests, but no luck.

```
#!/bin/bash

set -e
for I in `seq 100`; do
  echo "Attempt: $I"
  ./gradlew --no-build-cache -p runners/direct-java cleanTest needsRunnerTests --tests org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInFinishBundleStateful
done
```

**Comment by kennknowles** [comment]
The merge commit associated with this PR may be at an unhealthy point in `master` branch. I believe that the merge commit is updated only when the PR is updated. So you may need to rebase to force healthy tests.

We can note the health status to avoid re-running too many tests:

 - The only failure to be concerned about is `Run Java PostCommit`
    - the failed targets are `:sdks:java:io:google-cloud-platform:integrationTest` and `:runners:google-cloud-dataflow-java:googleCloudPlatformRunnerV2IntegrationTest`
    - notably, V1 integration tests with GCP IOs passed and also V2 integration tests with examples passed

This points to issues we had on master recently.

**Comment by kennknowles** [comment]
I pushed up ##14321 to make it easier to re-run specific pieces of the very large `Run Java PostCommit`

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Thank you for the guide. I just rebased this branch onto origin/master.

**Comment by suztomo** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by suztomo** [comment]
With this (not specifying `testTeardownCalledAfterExceptionInFinishBundleStateful`), it failed in 5th attempt. 

```
#!/bin/bash

set -e
for I in `seq 100`; do
  echo "Attempt: $I"
  ./gradlew --no-build-cache -p runners/direct-java cleanTest needsRunnerTests --tests org.apache.beam.sdk.transforms.ParDoLifecycleTest
done
```

https://gist.github.com/suztomo/215a07666bcd014578bb5fcc3d491fcb

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
This one is a known issue. There are a number of reports: https://issues.apache.org/jira/issues/?jql=project%20%3D%20BEAM%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20%22Triage%20Needed%22)%20AND%20text%20~%20%22testTeardownCalledAfterExceptionInFinishBundleStateful%22

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by suztomo** [comment]
@kennknowles Thank you for the references to the issues.

**Comment by suztomo** [comment]
Post commit ([640](https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/640/)) failed with

```
Test Result (2 failures / ±0)
org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPubsubMessageId
org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPublicData


...

java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/result-subscription-5089407805962046781 in 300s

```

**Comment by suztomo** [comment]
The latest Java preocommit timed out. No constant failures but I see this PR is more likely have timeout and (flaky) test failures than a PR with an empty change (https://github.com/apache/beam/pull/14307). Screenshot for comparision

Screen Shot 2021-03-24 at 14 39 12


@amaliujia Do you happen to have some insight into this?

Memo for myself. Maybe I can do a binary search between gRPC 1.26 and 1.36. For each version, I create a pull request and run Java Precommit 3 times.

**Comment by amaliujia** [comment]
@suztomo 

I don't have a concrete idea what has happened on Java precommit after the gRPC upgrade. My current plan is to run this PR with some internal benchmarks to see whether there is any performance difference for batch workload. 

I will keep you updated when I find something interesting.

**Comment by kennknowles** [comment]
One thing that may be useful is to try to note which test cases take a long time due to issues and give them a timeout at the JUnit level

**Comment by kennknowles** [comment]
After some clicking it does seem like all the timeouts occur on `apache-beam-jenkins-11`

**Comment by kennknowles** [comment]
No I just didn't click far enough. Also on 5.

**Comment by suztomo** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by suztomo** [comment]
Run PostCommit_Java_Dataflow

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run PostCommit_Java_Hadoop_Versions

**Comment by amaliujia** [comment]
LGTM from batch perf portability perspective (tested by running a set of internal Nexmark benchmarks).

**Comment by suztomo** [comment]
Comparison of the time.

Bad one: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/16814/consoleFull
Good one: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/3287/consoleFull

Differences

# "FROM-CACHE"

Good one has 718 "FROM-CACHE" marked Gradle task, while bad one has only 19.

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Java Precommit succeeded on node 5 ([link](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/3290/))

**Comment by suztomo** [comment]
Run PostCommit_Java_Dataflow

**Comment by suztomo** [comment]
Run PostCommit_Java_Dataflow

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
I think the problem was the cache in the Jenkins server. The more I run the precommit, the more likely I get success from the build.

Screen Shot 2021-03-31 at 09 15 43

No timeout lately.

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
@kennknowles It's ready for merge.

**Comment by kennknowles** [comment]
Interesting. I guess we would need to reorganize things to have a timeout per target. Probably need a very long Jenkins job and do the timeout as part of Gradle.

**Pull request merged**
