### PR TITLE
Splits large TextIOTest into TextIOReadTest and TextIOWriteTest

### PR DESCRIPTION
**Pull request by jkff**
R: @reuvenlax

### CODE REVIEW

**Comment by jkff** [comment]
Reuven is OOO so alternatively R: @jbonofre

**Comment by jkff** [comment]
Ping.

**Comment by kennknowles** [comment]
It is idiomatic to have `XYZTest` be a test of of the class `XYZ`. One way to maintain this while splitting tests up is to use the JUnit `Suite` test runner. We have a few examples in our codebase. FWIW I think we should also do this with the `SplittableDoFnTest` and to break up various test classes. The sub-suites do not need to be suffixed with `Test`.

**Comment by kennknowles** [comment]
(note also that Beam differs from Google in that only a committer can issue a binding LGTM, so be sure to loop one in after initial review)

**Comment by jkff** [comment]
OK, I preserved TextIOTest but made it a `Suite` wrapper over TextIORead/WriteTest, because I still wanted to split the overgrown .java file. Also rebased against Reuven's dynamic sinks changes. PTAL.

**Comment by reuvenlax** [comment]
lgtm

**Comment by kennknowles** [comment]
LGTM. I did not come to adequate resolution on whether these are going to be executed twice (I wouldn't be surprised) or how that is managed. I would prefer to have the suffix be something that looks less like a standalone test suite, but since they technically _are_ also standalone, it is fine. Best of both worlds.

**Pull request merged**
