### PR TITLE
Uses _all to follow alias/datastreams when estimating index size

### LINKED ISSUE #24117: [Bug]: ElasticsearchIO connector does not properly estimate index size
In the process of investigating the issue reported here:
https://stackoverflow.com/questions/74390325/how-to-enable-elasticsearchio-parallel-reads-in-apache-beam

it appears that the method used by the ElasticsearchIO connector to get the estimated size of the data in the response is not accounting for the case where the configured index is an alias or a datastream or an index pattern which can point to multiple indexes.

The original issue was a query that returns over 100 million documents for processing in the pipeline was unable to scale and was only processing at a rate of 40 / second.

As discussed in the stackoverflow thread, the code here: https://github.com/apache/beam/blob/c7f2cab6ea30a63e04847dc45047a8193abc9552/sdks/java/io/elasticsearch/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L871

is not properly accounting for a number of scenarios where the index name returned by ElasticSearch is different than `connectionConfiguration.getIndex()`. 

ElasticSearch should be relied upon to return the proper indexes for a given stats query, and as such the `_all` object should be used instead of the `indicies` top level object.  If there are other cases where the `_all` object isn't appropriate, then the code should iterate through all of the indicies returned under the `indices` field and sum the total store size, and not simply try to match the configured index.

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-elasticsearch

### PR DESCRIPTION
**Pull request by egalpin**
Fixes #24117

Ensures that index size estimation accounts for index aliases, patterns, and datastreams by using `_all` stats for an aggregate value of `size_in_bytes`.

All credit to @JeffBolle for this patch.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by aromanenko-dev — APPROVED** [review]
Thanks @egalpin and @JeffBolle for fixing this. LGTM

Just a one question - is it possible to add a regression test for this issue?

**Comment by egalpin** [comment]
@aromanenko-dev yes great call 👍  It should be trivial to add, I've got a WIP for the regression test I'll add to this PR today

**Comment by egalpin** [comment]
Confirmed locally by first seeing all tests pass, then reverting [a014637](https://github.com/apache/beam/pull/24186/commits/a014637106970a0a0e9eb7944aa5caf79fa5fd37) (i.e. removing @JeffBolle's patch) and re-running the test suite.  When the patch is removed, I received the following expected error:

```
org.apache.beam.sdk.io.elasticsearch.ElasticsearchIOTest > testSizesWithAlias FAILED
    java.lang.AssertionError: Wrong estimated size
    Expected: a value greater than <1000L>
         but: <0L> was less than <1000L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.apache.beam.sdk.io.elasticsearch.ElasticsearchIOTestCommon.testSizes(ElasticsearchIOTestCommon.java:218)
        at org.apache.beam.sdk.io.elasticsearch.ElasticsearchIOTest.testSizesWithAlias(ElasticsearchIOTest.java:95)
```

**Comment by aromanenko-dev** [comment]
@egalpin Thanks!

**Pull request merged**
