### PR TITLE
[BEAM-2394] Support concurrent execution of SpannerWriteIT test 

### PR DESCRIPTION
**Pull request by mairbek**
Generate a random database name.

Run Java JDK Version Test

### CODE REVIEW

**Comment by markflyhigh** [comment]
Run Java JDK Version Test

**Comment by markflyhigh** [comment]
LGTM

**Comment by mairbek** [comment]
Run Java JDK Version Test

**Comment by markflyhigh** [comment]
I think the fix works for all three version of JDK in `Java JDK Version Test`. The failure happened in the downstream sub-project which is unrelated to `SpannerWriteIT` test.

**Pull request closed without merging**
