### PR TITLE
Ignore IntelliJ Gradle build outputs

### PR DESCRIPTION
**Pull request by kennknowles**
This ignores IntelliJ's default output directories when building a gradle-importing project when you _don't_ delegate actions to Gradle.

To avoid any conflicts with command-line gradle, IntelliJ writes to `out` folders instead of `build` folders. I don't have full context or a strong opinion. Lots of details at https://youtrack.jetbrains.com/issue/IDEA-175172

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by kennknowles** [comment]
It turns out that all of our idea plugin config is not effective when we do not delegate, because the hints are relative to Gradle's output directories, not IntelliJ's. The comments on the linked ticket indicate how to set things up for IntelliJ in a Java-specific way so perhaps we can try for the same in all areas. I am not sure.

CC @akedin @bsidhom

**Comment by kennknowles** [comment]
Looking at https://github.com/gradle/gradle/issues/2315 it seems we should recommend using `gradle idea`. However, I want the project files to be generated outside the source tree, to support `git clean` so that is a prerequisite.

Closing this as I _don't_ think we should just ignore these, until we have them configured properly within the gradle scripts.

**Comment by kennknowles** [comment]
OK I am going to add hints so these output dirs actually work.

**Comment by iemejia** [comment]
We should exclude this out/ thing also from assembly.xml and probably from build.gradle too. For ref this was the commit I reviewed from the PR mentioned yesterday.
https://gist.github.com/iemejia/c894d1da4ee9b6bea8eb5bdbadfb43d3

**Comment by lukecwik** [comment]
Please update/respond for @iemejia's comment

**Comment by kennknowles** [comment]
Indeed. Not abandoned, just back burner.

**Comment by kennknowles** [comment]
Added the additional ignores. Added a couple hints that get IntelliJ to use its own default directories when not delegating to gradle. Remaining problems with non-delegated build include - not running protoc - not running avro generation from avsc.

**Comment by kennknowles** [comment]
But this one should be g2g

**Comment by iemejia** [comment]
The changes I asked for are ok, up to @lukecwik for the final LGTM.

**Pull request merged**
