### PR TITLE
[BEAM-1964] Revert clean else-return lint changes.

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
This is just a quick revert of the no-else-return changes in https://github.com/apache/beam/pull/2539 that apply cleanly and whose intent was better expressed with an else.

R: @sb2nov

**Comment by sb2nov** [comment]
LGTM

**Comment by robertwb** [comment]
Thanks. Will merge as soon as the tests finish.

**Comment by robertwb** [comment]
Failure in Apache Beam :: Runners :: Direct Java. 

Jenkins: retest this please

**Pull request closed without merging**
