### PR TITLE
[BEAM-11992] Run CrossLanguage ValidatesRunner for Spark 3

### PR DESCRIPTION
**Pull request by iemejia**
R: @chamikaramj @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by chamikaramj** [comment]
Run XVR_Spark3 PostCommit

**Comment by chamikaramj** [comment]
Seems like the new test suite was not triggered for some reason. Trying again.

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run XVR_Spark3 PostCommit

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by chamikaramj** [comment]
LGTM. Thanks Ismaël.

**Pull request merged**
