### PR TITLE
[BEAM-3130] View.asMap() causes a ClassCastException in Apex runner

### PR DESCRIPTION
**Pull request by tweise**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
R: @jkff

### CODE REVIEW

**Comment by jkff** [comment]
Thanks! Is it possible to add some tests for this?

**Comment by tweise** [comment]
@jkff tests are added

**Comment by jkff** [comment]
Thank you! While trying to merge this, I noticed a much more serious issue that I believe should be resolved before this one: https://issues.apache.org/jira/browse/BEAM-3261 - could you take a look?

**Comment by tweise** [comment]
@jkff I'm aware of that issue as well. It is certainly important, but at the same time it's not new and I don't see why it needs to be resolved in order for this change to be merged.

**Comment by jkff** [comment]
Fair enough, the current PR is an improvement in any case. Simplified the test a little bit and merged.

**Pull request closed without merging**
