### PR TITLE
[BEAM-2375] Rebase SQL DSL branch with master

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`.
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @xumingming 
CC: @XuMingmin

**Comment by xumingming** [comment]
LGTM.

**Comment by xumingming** [comment]
@jbonofre do you mind share the methods, I was thinking that this rebase might need two steps, because it if I rebase from `master`, it will conflict with `DSL_SQL`(as there are some breaking api changes to resolve), if i rebase again from `DSL_SQL`, it will conflict with `master`. So separate into two steps by first let DSL_SQL adopt the new breaking apis, then rebase from master.

**Comment by aaltay** [comment]
cc: @davorbonaci 

Hey @jbonofre, does this require a vote before merging a feature branch into master?

**Comment by davorbonaci** [comment]
Not following this fully, but it seems like a merge from the SQL branch into master. I don't think we are ready for this just yet.

@xumingming's comment make sense to me. Let's merge master branch into the SQL branch, fix up there, and continue development as usual.

**Comment by XuMingmin** [comment]
+1 we're not ready to merge SQL branch into master, guess some miscommunication. 

I think what @xumingming wants is pulling the latest code from master branch into SQL branch.

**Comment by xumingming** [comment]
Yeah, my intention was to pull the latest code into DSL_SQL branch(sorry if there are miscommunication @jbonofre).

**Comment by jbonofre** [comment]
Dual rebase on `master` and `DSL_SQL` (to be up to date from both side).

**Comment by davorbonaci** [comment]
But we shouldn't be updating DSL_SQL branch -- that requires force push, and may lose data.

**Comment by jbonofre** [comment]
It's not a merge on master, it's a rebase of the DSL_SQL branch from master. So, we don't merge on master, we just update the DSL_SQL branch.

**Comment by jbonofre** [comment]
Let me fix the pull request (it should be base on DSL_SQL branch instead of master).

**Comment by xumingming** [comment]
hi guys, can we boost this a little bit? This PR kinda blocks other several PRs.

**Comment by jbonofre** [comment]
Yeah, let me clean it up. I'm on it.

**Comment by jbonofre** [comment]
Fixed by #3311

**Pull request closed without merging**
