### PR TITLE
Makes FileIO.match watermark advance even without new files

### PR DESCRIPTION
**Pull request by jkff**
R: @rangadi

### CODE REVIEW

**Comment by jkff** [comment]
Sadly I don't know how to unit-test this, because it only manifests in the situation where we never stop watching a filepattern, and direct runner doesn't have good support for unit-testing non-terminating pipelines. But I tested this manually, and saw some output not produced without the fix, and produced with the fix.

**Comment by rangadi** [comment]
LGTM.

Related PR: #5137

**Comment by jkff** [comment]
Thanks! Yeah the full scope of that other PR is too difficult, but the current PR at least gets rid of the egregious issue.

**Comment by rangadi** [comment]
Agreed. This is an important fix. Thanks.

**Pull request merged**
