### PR TITLE
[BEAM-3336] Fix thread safety issues of MqttIOTest

### PR DESCRIPTION
**Pull request by lukecwik**
Ran the tests on my desktop 50 times with zero flakes.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
Can you add some detail about the particular changes in the commit log? I had to deduce what it was you were actually fixing, and there seem to be a few unrelated improvements (which you could just leave in). Can you clarify which of these are the fix?

I see these three seemingly independent changes:

1. Using a concurrent `Set` implementation in `testWrite()`. But that test wasn't a problem AFAIK. The map isn't used concurrently, and the `join()` provides adequate memory barrier, I think... but certainly seems better style to use a concurrent structure across threads. (incidentally it is the deprecated style of thread launching)
2. Joining the publisher thread before disconnecting. This seems like a very real fix.
3. Using `QoS.EXACTLY_ONCE`. I didn't see errors that looked like duplication, but I agree that from the code it looks possible.

To be clear: all three seem like OK improvements but I'd love to know which are required and which are nice to have, etc.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4406#-:-L2h0w07nlxV22MVG9FP:b-umh8ww)*

**Comment by kennknowles** [comment]
:lgtm: though, because build breakage is more important than these clarifications. Maybe next time.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4406#-:-L2h49uWsqT0FhrW9ZYX:b-ll09q8)*

**Comment by lukecwik** [comment]
Joining the publisher thread before disconnecting and the test timeout configuration were the real fixes.

**Comment by lukecwik** [comment]
Run Java Gradle PreCommit

**Comment by lukecwik** [comment]
MqttIOTest test passed https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/org.apache.beam$beam-sdks-java-io-mqtt/16749/testReport/org.apache.beam.sdk.io.mqtt/MqttIOTest/ but Flink checkstyle broken by https://github.com/apache/beam/pull/4343

**Pull request merged**
