### PR TITLE
Enable writing JSON type to BQ for Python FILE_LOADS

### PR DESCRIPTION
**Pull request by ahmedabu98**
BigQuery's [JSON data type](https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data) is now available for batch loads (until recently it has only been allowed for CSV file format. It's now available for JSON and Avro formats). This PR enables writing JSON data types for the Python BigQueryIO connector.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by ahmedabu98** [comment]
retest this please

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by pwiecek** [comment]
Is there a chance to return to this topic? We would like to use json data type together with Avro as temp file format and BQ FILE_LOADS. @ahmedabu98 were there any reasons why this PR was not merged to the master?

**Pull request closed without merging**
