### PR TITLE
Add an OWNERS file for .test-infra/metrics

### PR DESCRIPTION
**Pull request by swegner**
This documentation has been moved to the wiki: https://cwiki.apache.org/confluence/display/BEAM/Community+Metrics

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by swegner** [comment]
R: @Ardagan

**Comment by Ardagan** [comment]
Pre-commit failed. Do we need retries?

**Comment by swegner** [comment]
`:beam-test-infra-metrics:composeUp` [failed](https://scans.gradle.com/s/kspgoro5ezv7g/console-log?task=:beam-test-infra-metrics:composeUp); it seems that the Grafana instance never came up:

```
Creating beamsyncjenkins ... done
Creating beamsyncjira    ... done
Creating beampostgresql  ... done
Creating beamgrafana     ... done
Will use 172.18.0.1 (network 985960be794b18395bad082fc631b260_beam-test-infra-metrics__default) as host of postgresql
Gateway cannot be read from container inspection - trying to read from network inspection (network '985960be794b18395bad082fc631b260_beam-test-infra-metrics__default')
Will use 172.18.0.1 (network 985960be794b18395bad082fc631b260_beam-test-infra-metrics__default) as host of syncjira
Gateway cannot be read from container inspection - trying to read from network inspection (network '985960be794b18395bad082fc631b260_beam-test-infra-metrics__default')
Will use 172.18.0.1 (network 985960be794b18395bad082fc631b260_beam-test-infra-metrics__default) as host of syncjenkins
Will use 172.18.0.1 (network 985960be794b18395bad082fc631b260_beam-test-infra-metrics__default) as host of grafana
Probing TCP socket on 172.18.0.1:5432 of service 'beampostgresql'
TCP socket on 172.18.0.1:5432 of service 'beampostgresql' is ready
Probing TCP socket on 172.18.0.1:3000 of service 'beamgrafana'
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
Waiting for TCP socket on 172.18.0.1:3000 of service 'beamgrafana' (Connection refused (Connection refused))
[...]
Removing beamsyncjenkins ... done
Removing beampostgresql  ... done
Removing beamgrafana     ... done
Removing beamsyncjira    ... done
```

I've filed [BEAM-5870](https://issues.apache.org/jira/browse/BEAM-5870); if it happens again we should investigate adding retries.

**Comment by swegner** [comment]
Run Community Metrics PreCommit

**Pull request merged**
