### PR TITLE
[BEAM-6608] Prepare to-be-staged files early enough in Flink Runner 

### PR DESCRIPTION
**Pull request by mxm**
#### [BEAM-6608] Prepare to-be-staged files early enough in Flink Runner 

Before execution, the Flink Runner prepares all necessary files, in order for
them to be shipped to the remote cluster.

Due to a recent regression via BEAM-2873, the preparation is performed after the
execution environment has been initialized. This skips the preparation phase and
results in invalid files being shipped.

#### [BEAM-6609] Default tempLocation in FlinkPipelineOptions to default tmp directory

Includes this second commit because it is an easy fix and works on the same files. There should be a sensible default, so users don't have to configure the temp path by default.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Turns out there is a general issue with the path generation if the path does not end with a slash.

**Comment by kennknowles** [comment]
And _thank you_ for providing a regression test!

**Comment by mxm** [comment]
>In the prior change, the preparation of staged files is deliberately (and, I think, correctly) moved after a graph rewrite. I'm not sure that can really change the set of staged files in practice, but in theory it certainly could. I don't see that rewrite code anymore. Just checking - it is obsolete/deleted?

The graph rewrite is still performed before: https://github.com/apache/beam/pull/7748/files#diff-2133745bace88d112aee725d114c2940R85

I don't think the rewrite could change the staged files. They are effectively the classpath which won't change during pipeline translation. 

Btw, I reviewed the pull request (https://github.com/apache/beam/pull/4760) and also did not spot it.

**Comment by mxm** [comment]
Tests passed but squashing the history again. @kennknowles will open a PR for `release-2.10.0`.

**Comment by mxm** [comment]
Thanks for checking out the PR. You are right that it is theoretically possible for the classloader dependencies to change. We should keep it in mind for future changes.

**Pull request merged**
