### PR TITLE
Make class loading consistent for generated Function implementations

### PR DESCRIPTION
**Pull request by cushon**
This change resolves `Caused by: java.lang.IllegalArgumentException: ... must be defined in the same package as org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Function` errors.

The lookup used by `ClassLoadingStrategy.UsingLookup` "can define types only in the same class loader and in the same package as the type within which it was created" 

https://github.com/apache/beam/issues/26981

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by chamikaramj** [comment]
Thanks. Will it be possible to add a unit test for this ?

**Comment by chamikaramj** [comment]
There's a dev list discussion here: https://lists.apache.org/list.html?dev@beam.apache.org

Seems like we do have test that would have failed for this on Java 11. But we don't run such tests for Java 11.

cc: @damondouglas @kennknowles

**Comment by bvolpato** [comment]
Run Java PreCommit

**Review by bvolpato — APPROVED** [review]

**Review by kennknowles — COMMENTED** [review]
I read it wrong. The functionality itself was already very focused on this one class :-)

Thanks for the quick fix!

I would also repeat the request for a red test that turns green from this change.

**Comment by Abacn** [comment]
Confirm that this fixes unit tests on Java 11:

Command:
```
./gradlew :sdks:java:core:test --tests org.apache.beam.sdk.schemas.JavaBeanSchemaTest
```

previously (java -version shows java11), it fails with

```
> Task :sdks:java:core:test FAILED

org.apache.beam.sdk.schemas.JavaBeanSchemaTest > testMapFieldSetters FAILED
    java.lang.IllegalArgumentException at JavaBeanSchemaTest.java:460

org.apache.beam.sdk.schemas.JavaBeanSchemaTest > testRecursiveArraySetters FAILED
    java.lang.IllegalArgumentException at JavaBeanSchemaTest.java:385

org.apache.beam.sdk.schemas.JavaBeanSchemaTest > testMapFieldGetters FAILED
    java.lang.IllegalArgumentException at JavaBeanSchemaTest.java:437

org.apache.beam.sdk.schemas.JavaBeanSchemaTest > testRecursiveArrayGetters FAILED
    java.lang.IllegalArgumentException at JavaBeanSchemaTest.java:369

29 tests completed, 4 failed, 1 skipped
```
Now:

```
BUILD SUCCESSFUL in 18s

29 tests

0 failures

1 ignored

0.575s duration
```

**Review by Abacn — APPROVED** [review]

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
I noticed that the java precommit is red on master branch so this will probably fail. it was due to caching issues, which may or may not be persistent to this

**Comment by Abacn** [comment]
The cron job error seems due to jenkins-node-03 has corrupted gradle cache. And the schedule always schedule the job to that node.

Here test runs,  having one failing test `org.apache.beam.runners.fnexecution.control.RemoteExecutionTest.testMetrics` not likely related

triggering again

**Comment by Abacn** [comment]
run java precommit

**Pull request merged**
