### PR TITLE
Update Beam's root pom.xml to use a newer API client library.

### PR DESCRIPTION
**Pull request by pedapudi**
A new API client library has been made available with updates to the Dataflow API. This PR updates the declared dependency for Beam to make use of the updated API.

### CODE REVIEW

**Comment by pedapudi** [comment]
@tgroh Thomas, could you please take a look at this PR?

**Comment by tgroh** [comment]
LGTM if word counts pass

**Comment by lukecwik** [comment]
retest this please

**Comment by tgroh** [comment]
Java example ITs passed for dataflow in both modes, so I'm going to merge this

**Pull request closed without merging**
