### PR TITLE
[BEAM-2346] Revert "Include Additional PTransform inputs in Transform Nodes"

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This reverts commit 9336230d2a5c18bae89908bcd60db8ea96b7906d.

It appears to break `BigQueryTornadoesIT`: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_MavenInstall/3884/

I have confirmed that the failure is eliminated by this revert.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tgroh or anyone

Since the break is postcommit and easy to identify, it shouldn't slow down the whole community so I won't merge it right away. If you disagree, feel free to merge.

**Comment by kennknowles** [comment]
Unsurprisingly, I have confirmed that it is the changes to `TransformHierarchy' alone that cause the breakage.

**Comment by kennknowles** [comment]
Run Java PostCommit

**Comment by tgroh** [comment]
LGTM as revert

**Pull request closed without merging**
