### PR TITLE
[release-2.44.0]Install sklearn < 1.20.0 for sklearn postcommit tests (#24788)

### PR DESCRIPTION
**Pull request by AnandInguva**
* Install sklearn < 1.20.0

* fixup syntax

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
R: @kennknowles

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Comment by kennknowles** [comment]
It looks like there is some problem with the GitHub Actions. Does it look familiar?

**Comment by kennknowles** [comment]
I tried "re-run failed jobs" but the error didn't look like anything flaky...

**Comment by kennknowles** [comment]
```
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line [34](https://github.com/apache/beam/actions/runs/3841272211/jobs/6541297299#step:6:35), in <module>
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py37/tmp/pip-req-build-ehxcjqv9/setup.py", line 180, in <module>
          generate_protos_first()
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py[37](https://github.com/apache/beam/actions/runs/3841272211/jobs/6541297299#step:6:38)/tmp/pip-req-build-ehxcjqv9/setup.py", line 150, in generate_protos_first
          gen_protos.generate_proto_files()
        File "/home/runner/work/beam/beam/sdks/python/target/.tox/py37/tmp/pip-req-build-ehxcjqv9/gen_protos.py", line 476, in generate_proto_files
          raise RuntimeError(error_msg)
      RuntimeError: Not in apache git tree, unable to find proto definitions.
      [end of output]
```

**Comment by kennknowles** [comment]
I don't think it has anything to do with this pull request but is probably broken for the release branch entirely.

**Comment by AnandInguva** [comment]
I think I encountered this issue and created a PR that resolved this. Another cherry-pick should be made

**Comment by AnandInguva** [comment]
Okay. When we merge https://github.com/apache/beam/pull/24884, then the tests will pass on the release branch.

**Comment by kennknowles** [comment]
I merged the other one - rebase this one now?

**Comment by AnandInguva** [comment]
I don't think rebase is necessary. Can we rerun the GHA tests?

**Comment by kennknowles** [comment]
I'm not sure if it updates the merge commit that it runs against. I kicked them off. But it might just make sense to rebase this PR against the release-2.44.0 branch to be sure you've pulled in the latest.

**Comment by AnandInguva** [comment]
okay. I will rebase and ping you again.

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Comment by AnandInguva** [comment]
Run Python_PVR_Flink PreCommit

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
