### PR TITLE
update concurrency group definition

### PR DESCRIPTION
**Pull request by volatilemolotov**
Adds comment body to concurrency group definition to prevent different PRs canceling other jobs. 
Fixes part of: #28320 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by volatilemolotov** [comment]
R: @Abacn

**Review by Abacn — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
ah it's still in draft status (and looks good for me)

**Comment by volatilemolotov** [comment]
@Abacn Yeah i left in in draft until confirmation. Its ready now.

**Review by Abacn — APPROVED** [review]

**Comment by volatilemolotov** [comment]
@Abacn @damccorm Seems like this is causing issues of perpetually queued jobs somehow. Could be connected to some Actions outage which would explain the first queued job getting stuck but all further are considered the same group somehow. Think the issue is the body of comment :

https://github.com/apache/beam/actions/workflows/beam_PerformanceTests_BigQueryIO_Batch_Java_Json.yml?query=is%3Aqueued

and looking at the first job trigger we get to https://github.com/apache/beam/pull/28272#issuecomment-1725951616
which is a multiline comment with code embedded and that might be causing the group to be broken somehow.

Should we perhaps use comment id or something https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment

**Comment by Abacn** [comment]
fair - let's use comment id

**Pull request merged**
