### PR TITLE
Make sure there is a space between closing round bracket and opening …

### PR DESCRIPTION
**Pull request by coheigea**
Ensure that there is a single space between a round closing bracket and an opening curly bracket, for code consistency.

### CODE REVIEW

**Comment by kennknowles** [comment]
Nice. I will merge this. Can you encode this into our checkstyle rules? Otherwise it will just go back at some point.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
This didn't break it, but I want to get it green or confirm a flaky test to file a bug about.

**Comment by coheigea** [comment]
Will do, but I'll leave it to a separate PR as adding the check ends up enforcing more changes (for example {} will no longer be allowed)

**Comment by kennknowles** [comment]
Please rebase to resolve conflicts.

**Pull request merged**
