### PR TITLE
Allow MoreFutures.allAsList/allAsListWithExceptions to have the passed in list to be mutated

### LINKED ISSUE #23809: [Bug]: MoreFutures.allAsList/allAsListWithExceptions does not allow mutation of passed in list
### What happened?

Source of bug report: https://github.com/apache/beam/pull/22645#issuecomment-1289308040

We (spotify) are seeing ConcurrentModificationException errors due to https://github.com/apache/beam/pull/22645.

The issue starts in [WriteFiles.java](https://github.com/apache/beam/blame/master/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L964) where you construct a new future, then clear the existing closeFutures.

I think the underlying cause is in [MoreFutures.java](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/MoreFutures.java#L172) where you close over the input futures inside thenApply. If you instead used the array result of futuresToCompletableFutures I suspect the issue could be avoided.

Something like this?
```
      CompletableFuture<? extends T>[] f = futuresToCompletableFutures(futures);
      CompletionStage<Void> blockAndDiscard = CompletableFuture.allOf(f);

      return blockAndDiscard.thenApply(
          nothing ->
              Arrays.stream(f)
                  .map(CompletableFuture::join)
                  .collect(Collectors.toList()));
```
Similarly for allAsListWithExceptions.

Stack trace for the error (from a scio test):
```
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:374)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:309)
[info]   at com.spotify.scio.ScioContext.execute(ScioContext.scala:586)
[info]   at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:573)
[info]   at com.spotify.scio.ScioContext$$anonfun$run$1.apply(ScioContext.scala:561)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:652)
[info]   ...
[info]   Cause: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
[info]   at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[info]   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
[info]   at org.apache.beam.sdk.util.MoreFutures.get(MoreFutures.java:60)
[info]   at org.apache.beam.sdk.io.WriteFiles$WriteShardsIntoTempFilesFn.processElement(WriteFiles.java:984)
[info]   ...
[info]   Cause: java.util.ConcurrentModificationException:
[info]   at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
[info]   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[info]   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[info]   at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[info]   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[info]   at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[info]   at org.apache.beam.sdk.util.MoreFutures.lambda$allAsList$5(MoreFutures.java:174)
[info]   at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
[info]   at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
[info]   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
```

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-java-core

### PR DESCRIPTION
**Pull request by lukecwik**
This resolves ConcurrentModificationExceptions seen within WriteFiles and other places that use MoreFutures.allAsList* methods.

Fixes #23809

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @kellen @kennknowles

**Comment by kennknowles** [comment]
It seems unfortunate to add copying overhead rather than fixing things at the use sites.

**Comment by kennknowles** [comment]
Specifically, can we document that the passed in list should be not be mutable, and then only those places that require mutation pay the penalty?

**Comment by lukecwik** [comment]
We are already making a copy in the `allAsList` method, why would we ask the callers to make another copy outside of the method?

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Review by kellen — APPROVED** [review]
LGTM

**Comment by kennknowles** [comment]
Can you eliminate the current copy?

**Review by kennknowles — APPROVED** [review]
nvm I see what you are doing. LGTM. Mostly reacting to the premise of the pull request, which is to allow bad programming outside of this method.

**Comment by kennknowles** [comment]
I misread it and jumped to the conclusion that you were changing the allocation behavior here instead of putting the burden on the caller where it belongs. Since it is already copying, it is gravy.

**Pull request merged**
