### PR TITLE
[BEAM-1239] Updates more examples to use Beam text source/sink

### PR DESCRIPTION
**Pull request by chamikaramj**
Updates snippets.py and  custom_ptransform.py.

Removes the dependency snippets_test.py has on Dataflow native text sink.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM. Thank you @chamikaramj this is great.

**Comment by chamikaramj** [comment]
Thanks.

R: @robertwb can you merge ?

**Comment by chamikaramj** [comment]
Thanks.

**Pull request merged**
