### PR TITLE
Fix failing test beam_PerformanceTests_PubsubIOIT_Python_Streaming

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixing a failing test: https://ci-beam.apache.org/job/beam_PerformanceTests_PubsubIOIT_Python_Streaming/

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by chamikaramj** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by kileys** [comment]
Run PubsubIO Performance Test Python

**Comment by kileys** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Comment by ahmedabu98** [comment]
Run PubsubIO Performance Test Python

**Pull request closed without merging**
