### PR TITLE
[BEAM-4184] s3 resource id test has had a masked failure

### PR DESCRIPTION
**Pull request by adude3141**
Beam-4184 reenable sickbayed test case
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
Ah, sorry I missed this! Reviewing now.

**Comment by kennknowles** [comment]
I think the `checkArgument` for a slash in the component name makes sense, if that is something that is really expected to fail. But can they not be escaped? To me if you have `fromComponents("invalid/", "something")` that should resolve to `"invalid\//something"`. This is what we get for reinventing URLs...

**Comment by kennknowles** [comment]
Ah, but I forget that this is not actually a hierarchically structured URL, but simply a schema:scheme-specific-part URL. So yes I think just adding the logic that rejects slash is fine and then deleting the spurious test about underscore.

**Comment by kennknowles** [comment]
Wait again - per https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html as of March 2018 underscores are not allowed. So keep the test and reject it.

**Comment by adude3141** [comment]
Regarding underscores, I was worried about buckets created before March 2018. Beam will then not be able to read any bucket created as such. I ve no idea about the numbers and if that imposes any real issue, but AFAIU there will be no way to work around that. And as the other rules aren't implemented either, I thought it might be 'safer' to just let it pass.

WDYT?

**Comment by kennknowles** [comment]
Ah, I thought it was a policy change where they would force migrations of some sort. In retrospect that is a crazy thought :-)

Yea, let's support things and let it fail in the service. We could conceivably add a flag to `S3PipelineOptions` (does this exist?)

**Comment by adude3141** [comment]
Of course we could add an option to skip that validation to S3Options. On the other hand, there seems to be not too much validation implemented on beam resource ids anyway. Dunno, whether there are similar constraints which could/should be tested for other file systems.

And, of course, it seems reasonable to extend validation to the whole restriction ruleset then. Which most likely deserves a separate task if we really want to implement those...

**Comment by kennknowles** [comment]
LGTM. Thanks for the discussion!

**Comment by kennknowles** [comment]
beam1 is not healthy but should be good soon. Since this is not blocking release or others' development I am inclined to wait a little bit and get everything green, for the record.

**Comment by adude3141** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by adude3141** [comment]
+1. Thx for taking the time.

**Comment by adude3141** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by adude3141** [comment]
Thx!

**Pull request merged**
