### PR TITLE
[BEAM-7042] remove antlr from shadow configuration

### PR DESCRIPTION
**Pull request by adude3141**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by iemejia** [comment]
The tests passed but the antlr dependency is still leaking, it seems antlr gradle plugin leaks it in the compile scope when colled at `antlr library.java.antlr`

**Comment by iemejia** [comment]
If you move it into the generateFromSource task, it still leaks I triied this way but I have a really low level of gradle-fu so maybe there is a way to remove it afterwards.
```diff
diff --git a/sdks/java/core/build.gradle b/sdks/java/core/build.gradle
index a4a1264922..f271733284 100644
--- a/sdks/java/core/build.gradle
+++ b/sdks/java/core/build.gradle
@@ -34,6 +34,7 @@ applyAvroNature()
 applyAntlrNature()
 
 generateGrammarSource {
+  dependencies { antlr library.java.antlr }
   arguments += ["-visitor"]
 }
 
@@ -58,7 +59,6 @@ test {
 }
 
 dependencies {
-  antlr library.java.antlr
   // Required to load constants from the model, e.g. max timestamp for global window
   shadow project(path: ":beam-model-pipeline", configuration: "shadow")
   shadow project(path: ":beam-model-job-management", configuration: "shadow")
@@ -69,7 +69,6 @@ dependencies {
   compile library.java.commons_compress
   compile library.java.commons_lang3
   compile library.java.guava_testlib
-  shadow library.java.antlr
   shadow library.java.jackson_core
   shadow library.java.jackson_annotations
   shadow library.java.jackson_databind
```

**Comment by adude3141** [comment]
Sorry, what does 'it is still leaking' mean. Obviously I did not understand the issue here

**Comment by iemejia** [comment]
Leaking means that we do not want the main `antlr4` dependency to be available in the compile classpath, only `antlr4-runtime` because it is the only one needed. However it seems the `gradle antlr plugin` is adding it to the compile class path (leaking it).

**Comment by adude3141** [comment]
I used
```
./gradlew -p sdks/java/core/ generatePomFileForMavenJavaPublication -Ppublishing
```
to generate the pom file.

Diff shows
```
Michaels-MBP-2:beam michel$ diff sdks/java/core/build/publications/mavenJava/pom-default.xml sdks/java/core/build/publications/mavenJava/pom-default-bak.xml 
157,184d156
<       <groupId>org.antlr</groupId>
<       <artifactId>antlr4</artifactId>
<       <version>4.7</version>
<       <scope>compile</scope>
<       <exclusions>
<         <exclusion>
<           <groupId>com.google.guava</groupId>
<           <artifactId>guava-jdk5</artifactId>
<         </exclusion>
<         <exclusion>
<           <groupId>jdk.tools</groupId>
<           <artifactId>jdk.tools</artifactId>
<         </exclusion>
<         <exclusion>
<           <groupId>com.google.protobuf</groupId>
<           <artifactId>protobuf-lite</artifactId>
<         </exclusion>
<         <exclusion>
<           <groupId>org.hamcrest</groupId>
<           <artifactId>hamcrest-all</artifactId>
<         </exclusion>
<         <exclusion>
<           <groupId>org.mockito</groupId>
<           <artifactId>mockito-all</artifactId>
<         </exclusion>
<       </exclusions>
<     </dependency>
<     <dependency>
```

**Comment by iemejia** [comment]
Oh I understood now, thanks @adude3141. Gradle has a different view of dependencies and generated pom. Seems so error-prone, but well then your fix is ok.

**Pull request merged**
