### PR TITLE
Solace Read connector: Use ByteBuffer instead of BytesString in the Record class

### PR DESCRIPTION
**Pull request by bzablocki**
Beam Schemas don't support `ByteString` types. The pipeline was throwing the following exception in runtime:

```
    SEVERE: Error occurred within org.apache.beam.runners.direct.DirectTransformExecutor@3df140ba
    java.lang.VerifyError: Bad type on operand stack
    Exception Details:
      Location:
        org/apache/beam/sdk/io/solace/data/SchemaUserTypeCreator$SchemaCodeGen$uTIIUHuv.create([Ljava/lang/Object;)Ljava/lang/Object; @90: invokevirtual
      Reason:
        Type 'java/lang/Iterable' (current frame, stack[2]) is not assignable to 'org/apache/beam/vendor/grpc/v1p60p1/com/google/protobuf/ByteString'
      Current Frame:
        bci: @90
        flags: { }
        locals: { 'org/apache/beam/sdk/io/solace/data/SchemaUserTypeCreator$SchemaCodeGen$uTIIUHuv', '[Ljava/lang/Object;' }
        stack: { 'org/apache/beam/sdk/io/solace/data/AutoValue_Solace_Record$Builder', 'org/apache/beam/sdk/io/solace/data/AutoValue_Solace_Record$Builder', 'java/lang/Iterable' }
```

I changed the field type to BufferString, which is supported by the Schemas.
(addresses #31440).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by bzablocki** [comment]
Run Java PreCommit

**Comment by bzablocki** [comment]
assign set of reviewers

**Review by m-trieu — APPROVED** [review]
LGTM

**Comment by bzablocki** [comment]
Thank you @m-trieu ! Is it ready to merge or are we waiting for another LGTM?

**Pull request merged**
