### PR TITLE
[Go SDK]: Implement natsio.Read transform for reading from NATS

### LINKED ISSUE #29000: [Feature Request][Go SDK]: NATS IO connector
### What would you like to happen?

Create a NATS JetStream IO connector with a Read transform for consuming messages and a Write transform for producing messages.

Features in a first iteration:

**Read**
- Read messages from a subject in a stream with an existing durable consumer
- Allow the user to configure watermark estimation based on publishing time or processing time
- Deduplicate messages based on message ID

**Write**
- Write messages to a subject in a stream
- Rely on the NATS server built-in deduplication of messages based on message ID

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by johannaojeling**
Implements a `natsio.Read` transform for reading from NATS JetStream. Fixes #29000.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by johannaojeling** [comment]
R: @lostluck

I have taken inspiration from unbounded sources/SDFs in the Java SDK (KafkaIO, PulsarIO, etc.) and have tried to keep it simple in this first iteration. It is the first streaming connector I write so let me know if there are any best practices I'm missing out on.

**Comment by lostluck** [comment]
Thank you for your patience for the delay in reviewing. I've been distracted with chasing flakes with Prism, and have also fallen sick. It's going to take a little longer.

**Comment by johannaojeling** [comment]
> Thank you for your patience for the delay in reviewing. I've been distracted with chasing flakes with Prism, and have also fallen sick. It's going to take a little longer.

No worries, hope you feel better soon!

**Review by lostluck — APPROVED** [review]
Thanks for your patience!

As always, your code remains a delight to read. I don't have much to add, as AFAICT you're using all the parts correctly. The trick is whether different runners split in a reasonable fashion (specifically Prism, which will probably be very aggressive).

**Comment by damccorm** [comment]
Looks like there's another conflict in CHANGES.md unfortunately, @johannaojeling would you mind resolving again? @lostluck is this good to merge otherwise?

**Comment by lostluck** [comment]
Thank you for your patience WRT merging it in. Thanks Danny for the reminder!

**Pull request merged**
