### PR TITLE
[BEAM-3105] Cancel Jenkins builds when an update to a PR makes a prior build irrelevant

### PR DESCRIPTION
**Pull request by lukecwik**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
Run SeedJob

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/464/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/465/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/545/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/466/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15366/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15367/<h2>Build result: ABORTED</span></h2>[...truncated 222.75 KB...]2017-10-26T22:58:41.973 [INFO] Excluding com.google.instrumentation:instrumentation-api:jar:0.3.0 from the shaded jar.2017-10-26T22:58:41.973 [INFO] Excluding io.grpc:grpc-stub:jar:1.2.0 from the shaded jar.2017-10-26T22:58:41.973 [INFO] Excluding joda-time:joda-time:jar:2.4 from the shaded jar.2017-10-26T22:58:41.973 [INFO] Excluding org.slf4j:slf4j-api:jar:1.7.25 from the shaded jar.2017-10-26T22:58:45.483 [INFO] Replacing original artifact with shaded artifact.2017-10-26T22:58:45.483 [INFO] Replacing /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/src/runners/core-java/target/beam-runners-core-java-2.3.0-SNAPSHOT.jar with /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/src/runners/core-java/target/beam-runners-core-java-2.3.0-SNAPSHOT-shaded.jar2017-10-26T22:58:45.483 [INFO] Replacing original test artifact with shaded test artifact.2017-10-26T22:58:45.484 [INFO] Replacing /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/src/runners/core-java/target/beam-runners-core-java-2.3.0-SNAPSHOT-tests.jar with /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/src/runners/core-java/target/beam-runners-core-java-2.3.0-SNAPSHOT-shaded-tests.jar2017-10-26T22:58:45.484 [INFO] Dependency-reduced POM written at: /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/src/runners/core-java/dependency-reduced-pom.xml2017-10-26T22:58:45.742 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.util.concurrent.ExecutionException: Invalid object ID 14 iota=842017-10-26T22:58:45.743 [INFO] 2017-10-26T22:58:45.743 [INFO] --- maven-javadoc-plugin:3.0.0-M1:jar (attach-javadocs) @ beam-runners-core-java ---Build was abortedAborted by lcwikchannel stopped2017-10-26T22:58:46.666 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.io.IOException: Backing channel 'channel' is disconnected.2017-10-26T22:58:46.666 [WARNING] Failed to notify spy hudson.maven.Maven3Builder$JenkinsEventSpy: java.io.IOException: Backing channel 'channel' is disconnected.2017-10-26T22:58:46.667 [INFO]                                                                         2017-10-26T22:58:46.667 [INFO] ------------------------------------------------------------------------2017-10-26T22:58:46.667 [INFO] Skipping Apache Beam :: ParentAdding one-line test results to commit status...Setting status of 715b8681530432ed0384d989cdef43e316f11849 to FAILURE with url https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15367/ and message: 'FAILURE 2690 tests run, 5 skipped, 0 failed.'Using context: default

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15369/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/542/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/538/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/543/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/547/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/468/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15371/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/548/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/470/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/471/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/549/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15373/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15374/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/550/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/472/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15375/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/473/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/551/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/474/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15376/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/552/

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Go_MavenInstall/475/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15377/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/553/

**Pull request closed without merging**
