### PR TITLE
[Beam-4687]/Automate JIRA for Dependency check

### PR DESCRIPTION
**Pull request by yifanzou**
Add jira_client and jira_manager to handle the issue operations like creating, reopening, updating, etc. The Jira automation rule is available at [dependency guide](https://beam.apache.org/contribute/dependencies/#jira-automation)
Add a config file to specify constants used by the report generator.
More unit tests.
More logging.

+R: @chamikaramj 
cc: @charlesccychen 

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by yifanzou** [comment]
Run Seed Job

**Comment by yifanzou** [comment]
Run Dependency Check

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by cclauss** [comment]
__print()__ is a function in Python 3.  ~500 days until Python 2 end of life so we should stop writing new Python 2 code.


flake8 testing of https://github.com/apache/beam on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
/home/travis/virtualenv/python3.7.0/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
./.test-infra/jenkins/dependency_check/dependency_check_report_generator_test.py:47:23: E999 SyntaxError: invalid syntax
    print "\n\nTest : " + self._testMethodName
                      ^
./.test-infra/jenkins/jira_utils/jira_manager.py:69:30: E999 SyntaxError: invalid syntax
            print parent_issue.key
                             ^
./.test-infra/jenkins/jira_utils/jira_manager_test.py:45:23: E999 SyntaxError: invalid syntax
    print "\n\nTest : " + self._testMethodName
                      ^
3     E999 SyntaxError: invalid syntax
3
```

**Pull request merged**
