### PR TITLE
Do not pre-install beam in tensorrt container

### PR DESCRIPTION
**Pull request by Abacn**
Fix Python PostCommit tensorrttest

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
The change already applied to gcr. WIll wait to see if Python PostCommit passes

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
Run Python PreCommit 3.8

**Comment by Abacn** [comment]
Actually it requires to have a pre-installed beam SDK: 

```
2024/03/07 06:41:34 Downloaded: /var/opt/google/staged/dataflow_python_sdk.tar (sha256:
b3e497c7adc062ee3fb5e9ca90b9d32ff96a5e423a5f7a321106530fc7ab9a9f, size: 2424308)

2024-03-07 01:46:53.456 EST
failed to install required packages: Apache Beam is not installed in the runtime environment. If you use a custom container
image, you must install apache-beam package in the custom image using same version of Beam as in the pipeline
submission environment. For more information, see: the https://beam.apache.org/documentation/runtime/environments/
```

**Comment by tvalentyn** [comment]
> Actually it requires to have a pre-installed beam SDK:
> 
> ```
> 2024/03/07 06:41:34 Downloaded: /var/opt/google/staged/dataflow_python_sdk.tar (sha256:
> b3e497c7adc062ee3fb5e9ca90b9d32ff96a5e423a5f7a321106530fc7ab9a9f, size: 2424308)
> 
> 2024-03-07 01:46:53.456 EST
> failed to install required packages: Apache Beam is not installed in the runtime environment. If you use a custom container
> image, you must install apache-beam package in the custom image using same version of Beam as in the pipeline
> submission environment. For more information, see: the https://beam.apache.org/documentation/runtime/environments/
> ```

it's a bug. let me try to build an image that includes a fix.

**Comment by tvalentyn** [comment]
I pushed an updated version of us.gcr.io/apache-beam-testing/python-postcommit-it/tensor_rt:latest that reflects https://github.com/apache/beam/pull/30565

**Comment by tvalentyn** [comment]
(still uploading, but we should be able to retry the test in a few mins)

**Comment by tvalentyn** [comment]
test passed: https://pantheon.corp.google.com/dataflow/jobs/us-central1/2024-03-07_14_51_22-12424512300057262799;graphView=0?project=apache-beam-testing

**Pull request merged**
