### PR TITLE
BEAM-1760 Potential null dereference in HDFSFileSink#doFinalize

### PR DESCRIPTION
**Pull request by tedyu**
Check whether s.getPath().getParent() is null.
If it is null, break out of the loop.

### CODE REVIEW

**Comment by francesperry** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Hi @tedyu ,

I'm not quite sure I understand this change:

* when does this case happen?
* why is breaking out of the loop the correct case -- the files are not in their expected final names?

Can you please provide more information?

**Comment by tedyu** [comment]
If s.getPath().getParent() becomes null, that means we come to the end of the file path.
There is no need to create the part file.

**Comment by dhalperi** [comment]
Hi @tedyu,

Sure -- can you explain more how this actually happens, or provide a reproduction using this sink where this would happen? We're not recursively walking up the file structure, from what I can tell.

**Comment by tedyu** [comment]
Before I come up with a test, let me close this for now.

**Pull request closed without merging**
