### PR TITLE
Fix compatibility with dill 0.3.6.

### PR DESCRIPTION
**Pull request by tvalentyn**
Fix some known compatibility issues with newer versions of dill.

See: #24143 , https://github.com/apache/beam/pull/24143

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @AnandInguva

**Comment by AnandInguva** [comment]
Run Python 3.8 PostCommit

**Comment by AnandInguva** [comment]
This still leaves dill on 0.3.1.1 right?

**Comment by tvalentyn** [comment]
Yes, not changing current default dill version, but it will give more options to affected users and Py 3.11 users.

**Pull request merged**
