### PR TITLE
Revert "Exclude protobuf 3.20.2"

### PR DESCRIPTION
**Pull request by Abacn**
Reverts apache/beam#23226

Validating https://github.com/protocolbuffers/protobuf/issues/10564

### CODE REVIEW

**Comment by Abacn** [comment]
Tests likely will pass.

**Comment by Abacn** [comment]
R: @tvalentyn

**Comment by Abacn** [comment]
"apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithGrpcAndMultiWorkers.test_batch_pardo_trigger_flush" failed due to known flake #21104

**Comment by tvalentyn** [comment]
LGTM

**Pull request merged**
