### PR TITLE
Use Flink 1.13 for load tests

### PR DESCRIPTION
**Pull request by Abacn**
FIrst step to kick #21696

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
At least Python combine load test is using flink 1.12 job server: https://pantheon.corp.google.com/gcr/images/apache-beam-testing/global/beam_portability/beam_flink1.12_job_server which has not been updated long time ago (>1 year).

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Go Combine Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
Python Error now becomes the same as go error:
```
RuntimeError: Pipeline load-tests-python-flink-batch-combine-1-1021132626_df5ef80a-43a7-4157-b9d5-ada850e6a7e5 failed in state FAILED: org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot map `null` into type `long` (set DeserializationConfig.DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES to 'false' to allow)
10:14:00  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.apache.flink.runtime.rest.messages.job.JobDetailsInfo["maxParallelism"])
```
manually add `--max_parallelism=5` to pipeline options does not work.

**Comment by Abacn** [comment]
R: @tvalentyn

**Comment by Abacn** [comment]
Set up a flink job server docker environment and a local flink cluster for flink 1.13, and I cannot reproduce this locally... The example job just succeeded. Adding --parallelism pipeline options the job never ends though, but I do not see the error message, maybe because local cluster does not have more than 1 nodes to submit the job.

**Comment by tvalentyn** [comment]
LGTM

**Pull request merged**
