### PR TITLE
Update generated version of Fn API code.

### PR DESCRIPTION
**Pull request by wcn3**
This is based on the latest version of the Fn API proto definition. Need this to start experimenting with user counters.

### CODE REVIEW

**Comment by wcn3** [comment]
r:@herohde r:@lostluck

**Comment by herohde** [comment]
Can you do the change in master instead and merge? I'd rather not have the model Go code diverge.

**Comment by wcn3** [comment]
Sure.

**Comment by herohde** [comment]
LGTM

**Pull request merged**
