### PR TITLE
In SdkComponents (portability support lib), use equality to compare Coders

### PR DESCRIPTION
**Pull request by CraigChambersG**
In SdkComponents, Coders (and other model pipeline concepts) get registered.  Previously, identity was used to compare Coders, instead of Coder equals().  This leads to equivalent Coders being created leading to separate Coder ids and entries in the model pipeline proto etc.  It also leads to Coders created during internal expansion of PTransforms (e.g. Combine.perKey()'s accumulatorCoder) appearing to be different (and getting a different id) than the equivalent Coder known when the model pipeline proto was computed.  This PR switches to equals() to compare Coders, so that it's no longer a problem to create equivalent Coder representations.

R: @kennknowles 

------------------------

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by CraigChambersG** [comment]
Run Java PostCommit

**Comment by CraigChambersG** [comment]
Run Python PreCommit

**Comment by kennknowles** [comment]
Run Java PortabilityApi PostCommit

**Comment by kennknowles** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by kennknowles** [comment]
(just digging through https://github.com/apache/beam/blob/master/.test-infra/jenkins/ for jobs that look possibly relevant)

**Comment by CraigChambersG** [comment]
Run Java PostCommit
Run Java PortabilityApi PostCommit
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
Run Java PostCommit

**Comment by CraigChambersG** [comment]
Run Java PostCommit

**Comment by kanterov** [comment]
Does it fix a similar exception?

```
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: kind:varint=org.apache.beam.runners.dataflow.util.CloudObjectTranslators$8@6ef20733 and kind:varint=org.apache.beam.runners.dataflow.worker.RunnerHarnessCoderCloudObjectTranslatorRegistrar$1@d0533eb at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:100) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:86) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:300) at org.apache.beam.runners.dataflow.util.CloudObjects.populateCloudObjectTranslators(CloudObjects.java:60) at org.apache.beam.runners.dataflow.util.CloudObjects.<clinit>(CloudObjects.java:39) ... 15 more
```

**Comment by CraigChambersG** [comment]
> Does it fix a similar exception?
> 
> ```
> Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: kind:varint=org.apache.beam.runners.dataflow.util.CloudObjectTranslators$8@6ef20733 and kind:varint=org.apache.beam.runners.dataflow.worker.RunnerHarnessCoderCloudObjectTranslatorRegistrar$1@d0533eb at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:100) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:86) at org.apache.beam.repackaged.beam_runners_google_cloud_dataflow_java.com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:300) at org.apache.beam.runners.dataflow.util.CloudObjects.populateCloudObjectTranslators(CloudObjects.java:60) at org.apache.beam.runners.dataflow.util.CloudObjects.<clinit>(CloudObjects.java:39) ... 15 more
> ```

No, that's a different issue, which is being addressed by rolling back an earlier PR.

**Comment by CraigChambersG** [comment]
(PR #7452)

**Comment by kennknowles** [comment]
BTW `SdkComponents` is not part of the DataflowRunner but portability support code that should be used by all runners.

**Comment by CraigChambersG** [comment]
Run Java PreCommit

**Comment by CraigChambersG** [comment]
Run Java PostCommit

**Comment by CraigChambersG** [comment]
Run Java PortabilityApi PostCommit
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
Run Java PortabilityApi PostCommit

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by kanterov** [comment]
@kennknowles got it, thanks! I thought that Dataflow uses the same proto as in Job API from portability.

**Comment by CraigChambersG** [comment]
Run Portable_Python PreCommit

**Comment by kennknowles** [comment]
Run Java PortabilityApi PostCommit

**Comment by kennknowles** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by kennknowles** [comment]
LGTM based on content and intent here, regardless of flakes or tweaks to get it green.

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner
Run Python PreCommit

**Comment by CraigChambersG** [comment]
Run Python PreCommit

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by robertwb** [comment]
The error string issue is https://issues.apache.org/jira/browse/BEAM-6280

There doesn't seem to be much in the logs for the ValidatesRunner ones. 

Does `./gradelw --scan :beam-runners-google-cloud-dataflow-java:validatesRunnerFnApiWorkerTest` pass for you locally?

**Comment by CraigChambersG** [comment]
The Python PreCommit test failure seems to be a known issue:  https://issues.apache.org/jira/browse/BEAM-6280.

I still don't know how to reproduce or further diagnose the PortabilityApi ValidatesRunner test failures.

**Comment by CraigChambersG** [comment]
Run Java PostCommit
Run Java PortabilityApi PostCommit
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
Run Java PreCommit

**Comment by CraigChambersG** [comment]
Run Java PostCommit

**Comment by CraigChambersG** [comment]
Run Java PortabilityApi PostCommit

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
Run Java PreCommit

**Comment by CraigChambersG** [comment]
When run locally, the Dataflow PortabilityApi ValidatesRunner test (:beam-runners-google-cloud-dataflow-java:validatesRunnerFnApiWorkerTest) passes for me.  Should I consider that earlier failure a flake?  The Java Precommit failure likewise seems to be a flake, since it passed previously with the same PR code.  How should I proceed?

**Comment by CraigChambersG** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
I can't seem to have "Run Dataflow PortabilityApi ValidatesRunner" actually
cause that test to run on github, but apparently you can.  I do seem to be
able to "Run Java PreCommit" though.  Is there something about permissions
that I'm not allowed to run fancier tests?

**Comment by kennknowles** [comment]
There's nothing I'm aware of. The source for the job is https://github.com/apache/beam/blob/24f83f096f28d902257ccdc3c8ffcdc4f5cee5a7/.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_PortabilityApi_Dataflow.groovy

**Comment by CraigChambersG** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by CraigChambersG** [comment]
I was able to get Run Dataflow PortabilityApi ValidatesRunner to notice me
this time, after importing changes from master to my branch.  Weird.

**Comment by CraigChambersG** [comment]
Now the Dataflow PortabilityApi ValidatesRunner test is passing -- yay!  (Although I didn't change anything.)  The Java PreCommit test is still failing, but I think that's an unrelated flake or failure.

Run Java PreCommit

**Comment by CraigChambersG** [comment]
Run Java PreCommit

**Comment by CraigChambersG** [comment]
Hmpf, can't get the Java PreCommit test to rerun.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
This level of unreliability is unfortunate. Twice before we have had issues where Jenkins was unhealthy enough it could not even ack these requests. It also goes into a black hole during a reboot, which seems to happen regularly :-/

**Comment by CraigChambersG** [comment]
run java postcommit

**Comment by CraigChambersG** [comment]
run java precommit

**Comment by CraigChambersG** [comment]
ok, now the java precommit test failed, but the runtime grpc failing test is now passing (so a flake?).  the failure now is simply a checkstyle violation in direct-runner, which my PR doesn't touch.  I can reproduce this style violation locally, but it's also reproducible on master, so a preexisting problem.  What should I do?

**Comment by kennknowles** [comment]
1. Fix master (probably someone else)
2. `git fetch github`
3. `git rebase github/master` (you might do `--interactive` and curate the commits if you want)
4. `git push -f`

That'll certainly run all the tests synced up against fixed master anyhow. It is too bad that Jenkins doesn't have a memory of the auxiliary tests that we want to re-check.

**Comment by kennknowles** [comment]
I think we've tortured this PR enough. I am going to merge it as-is.

**Comment by kennknowles** [comment]
(squashing - looks like your intent is really just one tiny change)

**Pull request merged**
