### PR TITLE
[BEAM-7341] Elements produced by bounded GBK are always ON_TIME and ONLY_FIRING

### PR DESCRIPTION
**Pull request by dmvk**
R: @iemejia

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by ibzib** [comment]
Thanks for looking into this.

As Ismaël mentioned, please add a comment inline explaining the reason hard-coding the pane is a) necessary and b) correct.

**Comment by ibzib** [comment]
Ping @iemejia -- is this ready to merge?

**Comment by ibzib** [comment]
Ping @dmvk and @iemejia

**Comment by iemejia** [comment]
Merged manually now.

**Pull request closed without merging**
