### PR TITLE
Fix GCP import check in bigquery.py

### PR DESCRIPTION
**Pull request by charlesccychen**
This change fixes the following warning which occurs when "import apache_beam" is run in an interactive session directly from the "sdks/python/" directory.

```
apache_beam/io/gcp/bigquery.py:326: SyntaxWarning: import * only allowed at module level
  def __init__(self, table=None, dataset=None, project=None, query=None,
apache_beam/io/gcp/bigquery.py:431: SyntaxWarning: import * only allowed at module level
  def __init__(self, table, dataset=None, project=None, schema=None,
```

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM, I can merge it after tests.

**Comment by aaltay** [comment]
There are pylint errors, could you fix them?

**Comment by charlesccychen** [comment]
Thanks, fixed; PTAL.

**Comment by aaltay** [comment]
LGTM. Thank you.

**Pull request closed without merging**
