### PR TITLE
[BEAM-1395] SparkGroupAlsoByWindowFn not sorting grouped elements by timestamp

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @dhalperi / @kennknowles

**Comment by dhalperi** [comment]
Suggest some added testing:

- that this behavior is working as intended
- a regression test for the user issue (is there a new RunnableOnService test needed? is there something more targeted at Spark?)

**Comment by amitsela** [comment]
Mmmm.. testing is a good question - even now, it might pass sometime, if by chance elements are ordered, so a test could be added (ROS) to check this and it should ALWAYS pass if no regression, but it might also pass if broken. Am I wrong here ?

**Comment by dhalperi** [comment]
You're right that it would be hard to guarantee a test would fail, but hopefully we can think of a test that would be flaky at least. It might be we get this "for free" as soon as we start running full integration tests with the ongoing performance work.

For the short term, I would expect to see a `SparkGroupAlsoByWindowFnTest` that unit tests the function here. (You can probably crib straight from the `GroupAlsoByWindowsViaOutputBufferDoFnTest` for much of the test setup/teardown/structure).

**Comment by amitsela** [comment]
Let me think about it. I'd prefer adding/enhancing a ROS test because it feels funny to do this specifically here since this exact code (sort the grouped elements) also exists in Spark runner CombinePerKey/Globally and this might be (unresolved) for anyone using `GroupAlsoByWindowsViaOutputBufferDoFn`, so it feels something in a bit of a larger scope.

Ironically though: `Coverage increased (+0.01%)`

**Comment by dhalperi** [comment]
(Those coverage numbers are crap, but the link is sometimes useful.

I need to go file a JIRA for why -- basically, https://github.com/apache/beam/pull/1824#issuecomment-276735672

**Comment by dhalperi** [comment]
Filed https://issues.apache.org/jira/browse/BEAM-1399

**Comment by dhalperi** [comment]
I agree we want a cross-runner/e2e test. But I also think it's worth testing the SparkGroupAlsoByWindows sorts correctly before invoking the old code. You can do that in a pretty small unit test, I hope.

**Comment by kennknowles** [comment]
Pause on this, because let's not bother sorting. See issue comment.

**Comment by kennknowles** [comment]
See https://github.com/apache/beam/pull/1924

**Comment by amitsela** [comment]
@kennknowles stop indeed. Makes more sense to do it the way you did in #1924.

**Comment by amitsela** [comment]
Removed chunking as done in #1924.
I don't see a reason to add tests here, I would if it was straight forward but its not - I'd have to open ugly APIs and mock some of the parameters and eventually this is a Spark FlatMapFunction so the natural way to test it is as part of a Spark pipeline. ROS should do, and since order is not required any more, I think current tests are enough.

**Comment by dhalperi** [comment]
Sgtm

**Pull request closed without merging**
