### PR TITLE
[BEAM-2280] Remove generated archetype folders.

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @davorbonaci @dhalperi 

I think we should fix BEAM-2280 before the release in master, but I think it doesn't have to be cherry-picked.

**Comment by davorbonaci** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Already fixed by https://github.com/apache/beam/pull/2913

Can you please close this PR ? Thanks !

**Comment by peihe** [comment]
Cool, thanks @jbonofre

**Pull request closed without merging**
