### PR TITLE
Remove ValidatesRunner_V1 suite

### PR DESCRIPTION
**Pull request by damccorm**
We are able to safely remove this since Dataflow is migrating all jobs to runner v2 starting in 2.50.

Part of #26546

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
I'm going to wait to do that until closer to the cut to avoid merge conflicts

**Comment by AnandInguva** [comment]
File a tracking issue?

**Comment by damccorm** [comment]
#26546

**Comment by damccorm** [comment]
R: @tvalentyn

**Review by AnandInguva — APPROVED** [review]

**Review by AnandInguva — COMMENTED** [review]
Can we also remove https://github.com/apache/beam/blob/33518fb108d7c0870ad3a13e9c7bf7ce5fabfeac/sdks/python/test-suites/gradle.properties#L32  and https://github.com/apache/beam/blob/33518fb108d7c0870ad3a13e9c7bf7ce5fabfeac/sdks/python/test-suites/dataflow/common.gradle#L234

**Comment by damccorm** [comment]
Done, good call

**Comment by damccorm** [comment]
There's a little more simplification that can be done around the `dataflow/build.gradle` suites, but I'll save that for a follow-on PR

**Comment by AnandInguva** [comment]
Thanks. This LGTM

**Comment by damccorm** [comment]
Run Python_Transforms PreCommit

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
