### PR TITLE
[BEAM-5079] Update BigQuery dependency to 1.5.0

### PR DESCRIPTION
**Pull request by ThatRfernand**
0.25.0 -> 1.5.0

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by ThatRfernand** [comment]
retest this please

**Comment by ThatRfernand** [comment]
R: @markflyhigh

**Comment by ThatRfernand** [comment]
R:@markflyhigh

**Comment by ThatRfernand** [comment]
R: @chamikaramj

**Comment by markflyhigh** [comment]
Thanks for the update. Can you also run python postcommit since it's basically used in integration test infra to query bq data.

**Comment by ThatRfernand** [comment]
Run Python PostCommit

**Comment by chamikaramj** [comment]
Looks like task ':beam-sdks-python:postCommitITTests' failed. Not sure if it's related.

**Comment by chamikaramj** [comment]
Run Python PostCommit

**Comment by ThatRfernand** [comment]
Unclear, looking:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Verify_PR/src/sdks/python/build.gradle' line: 228

* What went wrong:
Execution failed for task ':beam-sdks-python:postCommitITTests'.
> Process 'command 'sh'' finished with non-zero exit value 1

**Comment by markflyhigh** [comment]
From Jenkins log:
```
slave/workspace/beam_PostCommit_Python_Verify_PR/src/sdks/python/apache_beam/io/gcp/tests/bigquery_matcher.py", line 97, in _query_with_retry
    query = bigquery_client.run_sync_query(self.query)
AttributeError: 'Client' object has no attribute 'run_sync_query'
```
New version has breaking API change. We should update few places in the code.

**Comment by ThatRfernand** [comment]
there is parallel work by @charlesccychen , yielding

**Pull request closed without merging**
