### PR TITLE
[BEAM-13008] Create gradle tasks for the Beam Playground

### PR DESCRIPTION
**Pull request by damondouglas**
This PR creates gradle tasks for the Beam Playground project as well as a bundled `playgroundPrecommit` task.  Future work needs to configure the precommit process to install necessary dependencies to properly run the `playgroundPrecommit` task.  Note that when running `./gradlew playgroundPrecommit` in the current state will show multiple issues and errors in the playground code.

I'd like to request the following reviewers or whomever they delegate.
R: @pabloem 
R: @tvalentyn 

```
./gradlew playground:tasks
```

```
./gradlew playground:backend:tasks
```

```
./gradlew playground:frontend:tasks
```

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damondouglas** [comment]
(cc: @pabloem )
The following is the output running:

```
./gradlew playgroundPrecommit
```

@ilya-kozyrev would you mind to fix the following and make a PR to https://github.com/damondouglas/beam/tree/BEAM-13008-playground-build-gradle.
 
```
> Task :playground:backend:tidy FAILED
go: finding module for package beam.apache.org/playground/backend/internal/environment
beam.apache.org/playground/backend/cmd/server imports
        beam.apache.org/playground/backend/internal/environment: cannot find module providing package beam.apache.org/playground/backend/internal/environment: unrecognized import path "beam.apache.org/playground/backend/internal/environment": reading https://beam.apache.org/playground/backend/internal/environment?go-get=1: 404 Not Found
```

@ElessarST would you mind to fix the following and make a PR to https://github.com/damondouglas/beam/tree/BEAM-13008-playground-build-gradle.  For the mockito related errors, I realize there is this [SOF post](https://stackoverflow.com/questions/67927401/should-we-source-control-the-mocks-dart-files-created-by-build-runner-for-mocki) about commiting/notcommiting mockito generated code.  I personally am in favor of commiting but I'll leave it to your judgement to figure out a way to make the `./gradlew playgroundPrecommit` pass either through another gradle task that would generate these dependencies.

> Task :playground:frontend:analyze FAILED

  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:21:8 - Target of URI doesn't exist: 'package:playground/generated/playground.pbgrpc.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist. - uri_does_not_exist
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:103:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:103:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:105:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:105:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:107:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:107:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:109:12 - Case expressions must be constant. - non_constant_case_expression
  error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:109:12 - Case expressions must be constant. - non_constant_case_expression
  error - test/modules/editor/repository/code_repository/code_repository_test.dart:31:8 - Target of URI doesn't exist: 'code_repository_test.mocks.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist. - uri_does_not_exist
  error - test/modules/editor/repository/code_repository/code_repository_test.dart:54:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function
  error - test/modules/editor/repository/code_repository/code_repository_test.dart:87:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function
  error - test/modules/editor/repository/code_repository/code_repository_test.dart:121:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function

13 issues found.

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by ilya-kozyrev** [comment]
> (cc: @pabloem ) The following is the output running:
> 
> ```
> ./gradlew playgroundPrecommit
> ```
> 
> @ilya-kozyrev would you mind to fix the following and make a PR to https://github.com/damondouglas/beam/tree/BEAM-13008-playground-build-gradle. Also you'll want to confirm that the `./gradlew playground:generateProto` task either generates in the right place or change the go dependency references.
> 
> ```
> > Task :playground:backend:tidy FAILED
> go: finding module for package beam.apache.org/playground/backend/internal/environment
> beam.apache.org/playground/backend/cmd/server imports
>         beam.apache.org/playground/backend/internal/environment: cannot find module providing package beam.apache.org/playground/backend/internal/environment: unrecognized import path "beam.apache.org/playground/backend/internal/environment": reading https://beam.apache.org/playground/backend/internal/environment?go-get=1: 404 Not Found
> ```
> 
> @ElessarST would you mind to fix the following and make a PR to https://github.com/damondouglas/beam/tree/BEAM-13008-playground-build-gradle.
> 
> 1. For the mockito related errors, I realize there is this [SOF post](https://stackoverflow.com/questions/67927401/should-we-source-control-the-mocks-dart-files-created-by-build-runner-for-mocki) about commiting/notcommiting mockito generated code.  I personally am in favor of commiting but I'll leave it to your judgement to figure out a way to make the `./gradlew playgroundPrecommit` pass either through another gradle task that would generate these dependencies.
> 2. Also you'll want to confirm that the `./gradlew playground:generateProto` task either generates in the right place or change the dart dependency references.
> 
> ```
> > Task :playground:frontend:analyze FAILED
> 
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:21:8 - Target of URI doesn't exist: 'package:playground/generated/playground.pbgrpc.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist. - uri_does_not_exist
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:103:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:103:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:105:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:105:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:107:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:107:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:109:12 - Case expressions must be constant. - non_constant_case_expression
>   error - lib/modules/editor/repository/code_repository/code_client/grpc_code_client.dart:109:12 - Case expressions must be constant. - non_constant_case_expression
>   error - test/modules/editor/repository/code_repository/code_repository_test.dart:31:8 - Target of URI doesn't exist: 'code_repository_test.mocks.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist. - uri_does_not_exist
>   error - test/modules/editor/repository/code_repository/code_repository_test.dart:54:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function
>   error - test/modules/editor/repository/code_repository/code_repository_test.dart:87:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function
>   error - test/modules/editor/repository/code_repository/code_repository_test.dart:121:22 - The function 'MockCodeClient' isn't defined. Try importing the library that defines 'MockCodeClient', correcting the name to the name of an existing function, or defining a function named 'MockCodeClient'. - undefined_function
> 
> 13 issues found.
> ```

@damondouglas Regarding this error
```
> Task :playground:backend:tidy FAILED
go: finding module for package beam.apache.org/playground/backend/internal/environment
beam.apache.org/playground/backend/cmd/server imports
        beam.apache.org/playground/backend/internal/environment: cannot find module providing package beam.apache.org/playground/backend/internal/environment: unrecognized import path "beam.apache.org/playground/backend/internal/environment": reading https://beam.apache.org/playground/backend/internal/environment?go-get=1: 404 Not Found

```

It happened because we are still waiting for https://github.com/apache/beam/pull/15654 to get merged. Can we merge Environments first of all to resolve it?

**Comment by damondouglas** [comment]
@pabloem 
```
./gradlew playgroundPrecommit
```

has the following output:
```
BUILD SUCCESSFUL in 21s
5 actionable tasks: 5 executed
```

**Comment by pabloem** [comment]
LGTM. Merging.

**Pull request merged**
