### PR TITLE
[BEAM-4113] Install latest pip/virtualenv in Gradle Python precommit.

### PR DESCRIPTION
**Pull request by udim**
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by robertwb** [comment]
I like the idea of always using an up-to-date pip/virtualenv, but I think it'd be preferable to not mess with the user's environment when they run gradle test. Note also that the --user flag is incompatible with already being in a virtual environment. 

Maybe run these commands (or at least the pip one) once the virtual environment is already created?

**Comment by udim** [comment]
@robertwb I created a JIRA for this as well. I'm not sure if this PR is needed. Will reevaluate after #5167 is merged.

**Comment by robertwb** [comment]
Should we close this?

**Comment by udim** [comment]
Yep. Closing.

**Pull request closed without merging**
