### PR TITLE
Assert pipeline results in performance tests

### LINKED ISSUE #23026: [Bug]: Java Performance tests could incorrectly showing Success while pipeline actual fail
### What happened?

Many performance tests (BigQueryIOPushDownIT.java, BigQueryIOIT.java, CdapIOIT.java, AvroIOIT.java, ParquetIOIT.java, TextIOIT.java, TFRecordIOIT.java, XmlIOIT.java, HadoopFormatIOIT.java, JdbcIOIT.java, KafkaIOIT.java, MongoDBIOIT.java) are designed similarly:
```
...
pipeline.run().waitUntilFinish()
publishResults()
```
This does not detect the pipeline failure.

### Issue Priority

Priority: 2

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #23026

* Fix possible false possitive test status

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java KafkaIO Performance Test

**Comment by Abacn** [comment]
Run Java JdbcIO Performance Test

**Comment by Abacn** [comment]
Run SQLBigQueryIO Batch Performance Test Java

**Comment by Abacn** [comment]
Run BigQueryIO Batch Performance Test Java Avro

**Comment by Abacn** [comment]
Run BigQueryIO Batch Performance Test Java Json

**Comment by Abacn** [comment]
Run Java CdapIO Performance Test

**Comment by Abacn** [comment]
Run Java AvroIO Performance Test

**Comment by Abacn** [comment]
Run Java ParquetIO Performance Test

**Comment by Abacn** [comment]
Run Java TextIO Performance Test

**Comment by Abacn** [comment]
Run Java TFRecordIO Performance Test

**Comment by Abacn** [comment]
Run Java XmlIO Performance Test

**Comment by Abacn** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by Abacn** [comment]
Run Java MongoDBIO Performance Test

**Comment by Abacn** [comment]
Kafka IO performance test has "failed correctly", previous success prior to https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_Kafka_IO/3005 was false positive [runs between run 3006 to 3026 there was another cause of failure (#23020)]. 
That is, the pipeline always fails with the following log message but previously not detected as fail test:
```
SEVERE: 2022-08-29T13:06:00.196Z: Workflow failed. Causes: S01:Generate records+Measure write time+Write to Kafka/Kafka ProducerRecord/Map+Write to Kafka/KafkaIO.WriteRecords/ParDo(KafkaWriter) failed., The job failed because a work item has failed 4 times.
```

**Comment by bvolpato** [comment]
Just curious, can the job end with another terminal state other than DONE or FAILED? e.g., ran in a Runner that supports cancellation. 
If so, we could expect for DONE explicitly, instead of checking for not FAILED.

**Comment by Abacn** [comment]
> Just curious, can the job end with another terminal state other than `DONE` or `FAILED`? e.g., if executed in a runner that supports cancellation. 
> 
> If so, we could expect for `DONE` explicitly, instead of checking for not `FAILED`. 

Yes you are right, cancel is missed in this assertion. I thought about if assert DONE or assert not FAILED. There exists some streaming tests that set to cancel the pipeline after certain time (because streaming pipelines generally does not DONE by themself); For simplicity I add same assertions for all performance tests.

Yes if we investigate each tests, including cancel as failure sounds more accurate; even more accurate the test should be marked as Aborted because a cancellation is initiated outside of the pipeline execution  and done by runner (e.g. someone cancelled the pipeline at Dataflow). I just did not go this far. Assert not FAIL should suffice for the testing of Beam SDK.

**Comment by johnjcasey** [comment]
LGTM

**Comment by Abacn** [comment]
The two failed tests: SQL BigQueryIO is already perma-red; KafkaIO is failed "correctly" and would be fixed seperately

**Comment by Abacn** [comment]
Kafka Performance test is running two exact same pipelines (after a pipeline option removed in #14168). Removed one of them.

**Comment by johnjcasey** [comment]
Gotcha. LGTM

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Pull request merged**
