### PR TITLE
[BEAM-3139] Update dataflow.version on the beam root pom.xml

### PR DESCRIPTION
**Pull request by ajamato**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Update dataflow.version on the beam root pom.xml to v1b3-rev218-1.22.0

### CODE REVIEW

**Comment by ajamato** [comment]
R: @kennknowles

**Comment by ajamato** [comment]
retest this please

**Comment by kennknowles** [comment]
run Dataflow ValidatesRunner

**Comment by kennknowles** [comment]
LGTM

**Comment by kennknowles** [comment]
Can you squash the commits to make it really easy for me to merge it?

**Comment by ajamato** [comment]
Done, is that the proper way to squash them?

**Comment by kennknowles** [comment]
Looks good to me. Any set of commits is OK as long as they are each something that makes sense on their own, and is legible in the history. Also, pragmatically, the easiest unit of rollback in addition to the atomic unit of history/blame.

**Pull request merged**
