### PR TITLE
[BEAM-5091] New wordcount integration test on DataflowRunner in Python 3

### PR DESCRIPTION
**Pull request by markflyhigh**
This is an integration test that runs a simple version of wordcount pipeline and verifies output file content in Python 3.

Due to BEAM-6158, the test disables `save_main_sessions` flag. Since it duplicates from the existing wordcout example's behavior, we don't need to run it in existing Python 2 suite. Create `Py3IT` tag for integration tests that's available in Python 3.

Tests are done by running this test using DataflowRunner in Python 3.5.

@tvalentyn @aaltay @RobbeSneyders 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by markflyhigh** [comment]
Run Python PreCommit

**Comment by markflyhigh** [comment]
Ready for review. @tvalentyn @aaltay

**Comment by tvalentyn** [comment]
Thanks, @markflyhigh. I support adding a wordcount test that does not require a main session for the purposes of improving existing Python 3 coverage. However I'd like us to have a better understanding whether we want to keep this test after BEAM-6158 is fixed.  Possible reason to keep: in the future we may have another feature for which we will be adding test coverage gradually, and for which --save_main_session will not work out of the box. Reason not to keep - this test is a subset of regular wordcount test.

- If we want to keep this test, I suggest we modify https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/wordcount_minimal.py to allow all pipeline options be passed as args, and write wordcount_minimal_it on top of that pipeline.
- If we don't want to keep this test, let's make it as easy as possible to switch current pipeline to a regular wordcount pipeline, while preserving the consistency of how tests are organized. We could think about it this way: how would we add a FnAPI Py3 integration test right now if we didn't have BEAM-6158. Would we put it in https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/wordcount_it_test.py ?  
- It looks like current test adds a new test folder, which I personally like, however now we will have two sets of tests in different places. I would suggest that we reorganize the suites in a different change, or move other tests to new folder in another commit on this PR.

**Comment by markflyhigh** [comment]
@tvalentyn PTAL

**Comment by tvalentyn** [comment]
Thank you!

**Pull request merged**
