### PR TITLE
[release-2.42.0] Use existing pickle_library flag in expansion service.

### PR DESCRIPTION
**Pull request by tvalentyn**
Cherry-pick https://github.com/apache/beam/pull/23111 into the release branch.

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @robertwb @lostluck

**Comment by robertwb** [comment]
org.apache.beam.sdk.io.pulsar.PulsarIOTest.testReadFromSimpleTopic failure is unrelated.

**Comment by robertwb** [comment]
Run Java PreCommit

**Review by robertwb — APPROVED** [review]

**Review by lostluck — APPROVED** [review]
LGTM

**Pull request merged**
