### PR TITLE
Update cloud spanner library to 0.29.0

### PR DESCRIPTION
**Pull request by mairbek**
R: @jkff

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
(bumping grpc version by +5 seems welcome but quite risky, hence the ValidatesRunner tests)

**Comment by aaltay** [comment]
What is the next action on this PR?

**Comment by jkff** [comment]
ValidatesRunner tests passed back then, but now this needs to be rebased. I think if after rebase tests pass again, then we can merge this. @mairbek could you rebase?

**Comment by aaltay** [comment]
@mairbek could you rebase this please?

**Comment by mairbek** [comment]
Rebased, PTAL

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
Seems you might need to rebase one more time due to the snapshot version change :-\ But at least seems that this dependency change doesn't break Dataflow runner.

**Comment by mairbek** [comment]
Resolved the conflict, ptal

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Seems that the PR currently doesn't compile.

**Comment by mairbek** [comment]
Fixed LocalFileSystemArtifactStagerServiceTest

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Still doesn't compile actually:

```
:examples:java:checkstyleMain/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_GradleBuild/src/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/GcpApiSurfaceTest.java:65: error: package com.google.api.gax.rpc does not exist
            Matchers.<Class<?>>equalTo(com.google.api.gax.rpc.ApiException.class),
                                                             ^
/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_GradleBuild/src/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/GcpApiSurfaceTest.java:66: error: package com.google.api.gax.rpc does not exist
            Matchers.<Class<?>>equalTo(com.google.api.gax.rpc.StatusCode.class),
                                                             ^
/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_GradleBuild/src/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/GcpApiSurfaceTest.java:67: error: package com.google.api.gax.rpc.StatusCode does not exist
            Matchers.<Class<?>>equalTo(com.google.api.gax.rpc.StatusCode.Code.class),
                                                                        ^
```

Please do a local "mvn clean compile test-compile" before the next push.

**Comment by jkff** [comment]
OK tests seem to be green now (perhaps previous time github didn't update the links to test runs). Merging.

**Comment by akedin** [comment]
i'm seeing this error locally and in jenkins: https://builds.apache.org/job/beam_PreCommit_Java_GradleBuild/2010/consoleFull

**Comment by jkff** [comment]
Hmm indeed - it compiles fine with maven but not with Gradle; I didn't realize they might be non-equivalent. I'm going to revert this until further investigation.

**Comment by kennknowles** [comment]
Is it getting caught in a shading rule?

**Comment by jkff** [comment]
@kennknowles Doesn't seem so, this PR just missed updating dependencies in build.gradle.

**Comment by lukecwik** [comment]
This will likely break many users since they will also all need to upgrade protobuf/grpc/netty/tcnative versions in their applications.

This is the reason why we have stuck with a single version of gRPC and protobuf for such a long time and not upgraded it.

**Comment by NathanHowell** [comment]
@lukecwik what is the plan to upgrade gcp client libraries? there are many important fixes in later versions (currently we need authenticated proxy support in the spanner client, this necessitates grpc >= 1.5) and it is not currently possible to pull in a new version of one library (spanner + associated dependencies) without upgrading the entire suite.

with the recently published [gcp bom](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bom) it is fairly easy to pull in the correct set of netty/grpc/etc dependencies for gcp. publishing a beam bom would reduce the amount of pain required to get a functioning set of dependencies in user jobs. shading is still necessary (thanks at least to netty) but it's much less painful than trying to find the magic version intersection that lets spark or flink use pubsub and spanner... assuming one exists.

**Comment by lukecwik** [comment]
No plan has been formulated, only a request to perform an upgrade of the gRPC libraries (https://issues.apache.org/jira/browse/BEAM-3098).

It would be best to have this discussion on the Apache Beam dev@ mailing list to see what the community wants so that a plan can be formulated and someone who owns funding the effort. A plan which improves the world for only one runner at the expense of the other runners is unlikely to gain traction.

**Pull request merged**
