### PR TITLE
[BEAM-3629] Send the windowing strategy and whether its a merging window fn to Dataflow.

### PR DESCRIPTION
**Pull request by lukecwik**
This is to support using the correct windowing strategy in any GBKs that Dataflow service adds for the materialization of a PCollectionView.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by kennknowles** [comment]
If the windowing strategy is propagated, why do you also need to indicate merging vs not?

**Comment by kennknowles** [comment]
No objections, of course, assuming it is a quirk of Dataflow. Just seems redundant.

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by lukecwik** [comment]
Since Dataflow worker can look at the windowing strategy but the service does not and it needs this piece of information for optimization reasons.

**Comment by lukecwik** [comment]
run dataflow validatesrunner

**Comment by lukecwik** [comment]
run dataflow validatesrunner

**Pull request merged**
