### PR TITLE
BEAM-1269: Update bigtable library dependency and add cached data pools.

### PR DESCRIPTION
**Pull request by mdshalda**
Hi @dhalperi, 

Can you review these changes to add the new bigtable library and cached data pools?

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Hi Mark,
It looks like you were not quite on head and have some conflicts with the existing code. Can you git fetch latest master and rebase?

**Comment by mdshalda** [comment]
I think I fixed this now.

**Comment by dhalperi** [comment]
My guess: Bigtable upgraded their transitive requirements on gRPC and Protobuf:

https://github.com/GoogleCloudPlatform/cloud-bigtable-client/commit/a227311ba33e3e2ffa45d856e90ff3ca394e640a#diff-600376dffeb79835ede4a0b285078036

mimic those in the root pom.xml, and ignore the guava downgrade for now.

https://github.com/GoogleCloudPlatform/cloud-bigtable-client/commit/a227311ba33e3e2ffa45d856e90ff3ca394e640a#diff-600376dffeb79835ede4a0b285078036

**Comment by dhalperi** [comment]
Kicked off https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_MavenInstall/3111/ to see if the test passes

**Comment by mdshalda** [comment]
@dhalperi - Made the adjustments to the dependencies as discussed

**Comment by dhalperi** [comment]
Kicked off https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_MavenInstall/3160/ as a test.

**Comment by dhalperi** [comment]
Kicked the postocmmit : https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_MavenInstall/3183/

**Comment by dhalperi** [comment]
Postcommit passed. Merging, thanks Mark!

**Pull request closed without merging**
