### PR TITLE
Fix repository path for Python Jenkins builds. Source directory was c…

### PR DESCRIPTION
**Pull request by tvalentyn**
…hanged in PR/3976

This should fix BEAM-3120.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by kennknowles** [comment]
You can `run seed job` and it will actually be installed right away. It can then be rolled back if broken. Other than that, you need to have a test Jenkins cluster, which is a bit of work.

**Comment by tvalentyn** [comment]
Thanks, that's helpful.

**Comment by tvalentyn** [comment]
run seed job

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
run seed job

**Comment by tvalentyn** [comment]
run seed job

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Performance Test

**Comment by tvalentyn** [comment]
run seed job

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Performance Test

**Comment by tvalentyn** [comment]
run seed job

**Comment by tvalentyn** [comment]
Run Python Performance Test

**Comment by tvalentyn** [comment]
Run Python Performance Test

**Comment by tvalentyn** [comment]
R: @aaltay 
Postsubmit and ValidatesRunner suites are fixed in this PR, performance test failure is unrelated and needs to be addressed separately. Java tests in gradle suite seem to have an unrelated failure, but passed in Maven suite.

**Comment by aaltay** [comment]
LGTM. Thank you

**Comment by aaltay** [comment]
@asfgit merge

**Pull request merged**
