### PR TITLE
Fix java synthetic build broken for release branch

### PR DESCRIPTION
**Pull request by boyuanzz**
Release build failed in synthetic javadoc: https://scans.gradle.com/s/g5ttvskascs2e/console-log#L3779
Fix commit: https://github.com/apache/beam/pull/5982/commits/c9e794af94de86f51a4b2fe4e836d8482f6642be

Release build failed in synthetic spotlessJava: https://scans.gradle.com/s/r557o6zkbm25e/failure?openFailures=WzBd&openStackTraces=WzEse31d#top=0
Fix commit: https://github.com/apache/beam/pull/5982/commits/8419fd49f567e0e7be18694101294777d87531c4

r: @pabloem @aaltay

### CODE REVIEW

**Comment by pabloem** [comment]
This LGTM. You've run the build, right? Also, is there a fix for this on master?

**Comment by boyuanzz** [comment]
re: @pabloem 
Yes, synthetic build succeeded with this fix. I'll create a new PR against master later.

**Comment by lukecwik** [comment]
It is a best practice to make the change against master first and then cherry pick to release.

**Comment by boyuanzz** [comment]
Open pr in master: https://github.com/apache/beam/pull/5987

**Comment by boyuanzz** [comment]
Hey Luke @lukecwik , is it better for me to close this PR and let release manager(@pabloem ) cherrypick fix commit from master branch?

**Comment by pabloem** [comment]
Precommit seems to have stalled...

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Release build succeeded with this PR: https://github.com/apache/beam/pull/5982

**Comment by lukecwik** [comment]
Just make sure that the release branch gets the same commit as what was merged into master https://github.com/apache/beam/pull/5987/commits/9c67bc85dac25b0a51871333e389ea9d3738a790. This will prevent merge conflicts and it makes it easier to retain history and track lineage of the commit.

Is there a reason why this commit has a different id then the one on master?

**Comment by lukecwik** [comment]
sgtm

**Pull request closed without merging**
