### PR TITLE
[#23043] Re-enable single iteration for the Go SDK.

### LINKED ISSUE #23043: [Task]: Reenable single iteration
### What needs to happen?

Single iteration was temporarily disabled in #23042 and should either be turned back on or ripped out entirely. This should also address the issue raised in #22933

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by lostluck**
Re-enable single iteration "decode on-demand" stream for the Go SDK.

Originally disabled due to #22933, in #23042, the principle remains sound, and it's long past time to look at why it failed in the first place.

The issue was that we didn't drain the iterable properly if there were no reads at all, so we go with the slightly more ham fisted approach of iterating until io.EOF, or stream != nil. If the stream isn't nil, it means the reader got handed off, and it's up to that stream to close.

This avoids unnecessarily draining something off of the main reader which could be very large and costly.

Fixes #23043

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
Run Go Spark ValidatesRunner

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Comment by lostluck** [comment]
Run Go Samza ValidatesRunner

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Whoops. Forgot to mark this as draft Jack. Just wanted to see if we could replicate the failure still (as listed in the description).

It doesn't occur on Prism (validated on laptop).

**Comment by lostluck** [comment]
Run Go Spark ValidatesRunner

**Comment by lostluck** [comment]
Run Go Spark ValidatesRunner

**Comment by lostluck** [comment]
It's very strange, since that element doesn't exist, it's just a windowed value header with no element, since there's only one element at all. Current idea is that element "always" exists, and it's being skipped somehow in the non-singleIterate path.

**Comment by lostluck** [comment]
Run Go Spark ValidatesRunner

**Comment by lostluck** [comment]
Ready for a look. Ready to submit if the Spark Validates runner passes.

**Comment by lostluck** [comment]
Run Go Spark ValidatesRunner

**Comment by jrmccluskey** [comment]
Looks like everything is good apart from the `go fmt` check

**Comment by lostluck** [comment]
Thanks for the review!

**Pull request merged**
