### PR TITLE
Revert "DataflowRunner: experimental support for issuing FnAPI based jobs

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This reverts commit 131c9f916dae6345ec77a869112ae5901b568f23.

This actually doesn't have coverage in Jenkins and we've discovered breakage. Should be easy to patch up and roll forwards in a bit.

### CODE REVIEW

**Comment by tgroh** [comment]
LGTM

**Comment by vikkyrk** [comment]
LGTM

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Actually I'm going to cancel that as rely on postcommit, to spare the queue.

**Pull request merged**
