### PR TITLE
Fix JaCoCo test report

### PR DESCRIPTION
**Pull request by Amar3tto**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Please don't merge yet, I'm running final tests

**Comment by Abacn** [comment]
Because each jacoco report does not cover the whole java code base, in order to get accurate coverage, previously the jacoco is only included in certain paths, e.g. https://github.com/apache/beam/blob/6ce85e5f8ae908024c2b22afd06901551ce72a49/.test-infra/jenkins/job_PreCommit_SQL.groovy#L50 and https://github.com/apache/beam/blob/release-2.49.0/.test-infra/jenkins/job_PreCommit_Java.groovy is it able to retain this behavior?

**Comment by Amar3tto** [comment]
> Because each jacoco report does not cover the whole java code base, in order to get accurate coverage, previously the jacoco is only included in certain paths, e.g.
> 
> https://github.com/apache/beam/blob/6ce85e5f8ae908024c2b22afd06901551ce72a49/.test-infra/jenkins/job_PreCommit_SQL.groovy#L50
> 
> and https://github.com/apache/beam/blob/release-2.49.0/.test-infra/jenkins/job_PreCommit_Java.groovy is it able to retain this behavior?
> basically, "precommit java" does not run tests in "sdks/java/io" and "sdks/java/extensions/sql"; and GCP_IO only run tests in "sdks/java/io/google-cloud-platform" and "sdks/java/extensions/sql"

Yes, currently we will get reports only for _PreCommit_Java_ (will **not** generate specific IOs reports because does not run tests in "sdks/java/io"), _GCP IO_ and _SQL_.
If we want to have the reports for the whole java code base, we will need to add this flag `-PenableJacocoReport` to the specific workflows (e.g. _beam_PreCommit_Java_Kafka_IO_Direct, beam_PreCommit_Java_Jms_IO_Direct_, ...). We can do that, but if I'm not mistaken, you mentioned that all the reports might take up too much space.
If your question was about _'inclusionPattern'_ then yes, it works correctly, it only includes what is needed.

**Comment by Abacn** [comment]
My question is about if `inclusionPattern` is considered in this PR (I did not see it explicitly configured somewhere). And yes the space was a concern and only enroll Java/SQL/GCP_IO precommit is fine. We can merge and see how the report shows.

**Review by Abacn — APPROVED** [review]

**Pull request merged**
