### PR TITLE
[DRAFT ] To test out gradle build in jenkins.

### PR DESCRIPTION
**Pull request by HuangLED**
**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Java TextIO Performance Test

**Comment by HuangLED** [comment]
Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by HuangLED** [comment]
Run RAT PreCommit

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Java TextIO Performance Test

**Comment by HuangLED** [comment]
Run Seed Job

**Comment by lgajowy** [comment]
as mentioned in JIRA

you could modify `integrationTest` task like this (line 1126): 

```
project.task('integrationTest', type: Test) {

        // Disable Gradle cache (it should not be used because the IT's won't run).
        outputs.upToDateWhen { false }

        include "**/*IT.class"

        if(configuration.runner?.equalsIgnoreCase('dataflow')) {
          // append the "--workerHarnessContainerImage"// option to configuration.integrationTestPipelineOptions
        }

        systemProperties.beamTestPipelineOptions = configuration.integrationTestPipelineOptions
      }
```

you can also build the dataflow container image and add the worker jar if "dataflow" runner is chosen (line 1150): 

```
if (runner?.equalsIgnoreCase('dataflow')) {
          testCompile it.project(path: ":beam-runners-google-cloud-dataflow-java", configuration: 'shadowTest')

          // build anything that is needed (worker jar) 
        }
```


I was unable to comment in code for some reason, sorry...

**Comment by HuangLED** [comment]
> as mentioned in JIRA
> 
> you could modify `integrationTest` task like this ([line 1136](https://github.com/apache/beam/blob/916c3b46c726e63ac2f7b60d8abb9c66202dec0b/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L1136)):
> 
> ```
> project.task('integrationTest', type: Test) {
> 
>         // Disable Gradle cache (it should not be used because the IT's won't run).
>         outputs.upToDateWhen { false }
> 
>         include "**/*IT.class"
> 
>         if(configuration.runner?.equalsIgnoreCase('dataflow')) {
>           // append the "--workerHarnessContainerImage"// option to configuration.integrationTestPipelineOptions
>         }
> 
>         systemProperties.beamTestPipelineOptions = configuration.integrationTestPipelineOptions
>       }
> ```
> you can also build the dataflow container image and add the worker jar if "dataflow" runner is chosen ([line 1164](https://github.com/apache/beam/blob/916c3b46c726e63ac2f7b60d8abb9c66202dec0b/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L1164)):
> 
> ```
> if (runner?.equalsIgnoreCase('dataflow')) {
>           testCompile it.project(path: ":beam-runners-google-cloud-dataflow-java", configuration: 'shadowTest')
> 
>           // build anything that is needed (worker jar) 
>         }
> ```
> For some reason I was unable to comment in code for some reason, sorry...

Thanks, Lukasz.  Let me look into this direction. 

Just to confirm, in your opinion, by changing integrationTest, we then no longer need to change jenkins file at all, right?

**Comment by lgajowy** [comment]
Yes - I believe we should be able to do what's needed in the Gradle code using this approach.

**Pull request closed without merging**
