### PR TITLE
[BEAM-230] Remove deprecated WindowedValue.valueInEmptyWindows

### PR DESCRIPTION
**Pull request by kennknowles**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

I noticed this branch sitting around and tests seem to pass for me. I think things are probably quite different than when PR #1440 didn't get in.

### CODE REVIEW

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
There were real failures, I believe caused by bugs in the Dataflow worker, but also the Jenkins worker ran out of ability to launch threads.

**Comment by kennknowles** [comment]
Failure in elasticsearch; seems probably unrelated. Re-running.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
retest this please

**Comment by iemejia** [comment]
Is this still ongoing, It looks like it is almost done, no ? can it make it for 2.3.0 ?

**Comment by kennknowles** [comment]
There are some really wacky uses of this in Dataflow that I haven't quite worked out. It is close, but not quite ready.

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
Basically, the status is that I've ported Dataflow off `valueInEmptyWindows` but it still creates its own hacked subclass of `WindowedValue` that has no windows. I will move the safety checks to some place where Dataflow can skip them but only by calling a method that makes it obvious something is being done wrong and should be fixed.

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
ValidatesRunner passed finally. Rebasing and merging when green again (the non-VR tests got hung up)

**Comment by kennknowles** [comment]
retest this please

**Pull request merged**
