### PR TITLE
[CdapIO] HasOffset interface was implemented

### PR DESCRIPTION
**Pull request by sorokin-andrey**
In SparkReceiverIO we will have different functions for working with Spark receivers that support offsets and those that don't. To determine if a receiver supports offsets, we need the HasOffset interface.

The goal of this PR is to implement it plus add some minor infrastructure needed changes.

Fixes https://github.com/apache/beam/issues/22148

### CODE REVIEW

**Comment by Lizzfox** [comment]
Run Java PreCommit

**Comment by Lizzfox** [comment]
Run Python PreCommit

**Comment by sorokin-andrey** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Python PreCommit

**Comment by sorokin-andrey** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Thanks. LGTM.

**Pull request merged**
