### PR TITLE
[release-2.26.0][BEAM-11264] Add Reshuffle in pd.read_*

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Another fix for using DataframeTransform at scale. Without this it's not possible to distribute reading distinct files on distinct workers.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
R: @robertwb 
R: @lostluck

**Review by robertwb — APPROVED** [review]
LGTM

**Comment by lostluck** [comment]
Run Python PreCommit

**Comment by lostluck** [comment]
Run Python 3.8 PostCommit

**Comment by lostluck** [comment]
Run Python 3.7 PostCommit

**Comment by lostluck** [comment]
I'm not worried about the windows failures, but the precommit flake needed a quick re-run. LGTM and merging.

**Comment by lostluck** [comment]
Run Python PreCommit

**Comment by TheNeuralBit** [comment]
I think it's expected that Python test suites fail on the release branch until a Dataflow container release. Let me verify that

**Comment by TheNeuralBit** [comment]
Well I can't find any documentation stating that Python tests will fail, just that Dataflow tests will fail. But looking at the last [Python PreCommit failure](https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2316) it looks like the issue was hanging Dataflow tests:

```
12:24:47 > Task :sdks:python:test-suites:dataflow:py36:preCommitIT_batch_V2
12:24:47 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:24:29.045Z: JOB_MESSAGE_BASIC: Your project already contains 100 Dataflow-created metric descriptors, so new user metrics of the form custom.googleapis.com/* will not be created. However, all user metrics are also available in the metric dataflow.googleapis.com/job/user_counter. If you rely on the custom metrics, you can delete old / unused metric descriptors. See https://developers.google.com/apis-explorer/#p/monitoring/v3/monitoring.projects.metricDescriptors.list and https://developers.google.com/apis-explorer/#p/monitoring/v3/monitoring.projects.metricDescriptors.delete
12:24:49 
12:24:49 > Task :sdks:python:test-suites:dataflow:py37:preCommitIT_batch_V2
12:24:49 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:24:46.063Z: JOB_MESSAGE_DETAILED: Autoscaling: Raised the number of workers to 1 based on the rate of progress in the currently running stage(s).
12:25:17 
12:25:17 > Task :sdks:python:test-suites:dataflow:py36:preCommitIT_batch_V2
12:25:17 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:24:47.927Z: JOB_MESSAGE_DETAILED: Autoscaling: Raised the number of workers to 1 based on the rate of progress in the currently running stage(s).
12:25:19 
12:25:19 > Task :sdks:python:test-suites:dataflow:py37:preCommitIT_batch_V2
12:25:19 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:25:16.445Z: JOB_MESSAGE_DETAILED: Workers have started successfully.
12:25:19 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:25:16.480Z: JOB_MESSAGE_DETAILED: Workers have started successfully.
12:25:47 
12:25:47 > Task :sdks:python:test-suites:dataflow:py36:preCommitIT_batch_V2
12:25:47 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:25:23.244Z: JOB_MESSAGE_DETAILED: Workers have started successfully.
12:25:47 INFO:apache_beam.runners.dataflow.dataflow_runner:2020-11-16T20:25:23.307Z: JOB_MESSAGE_DETAILED: Workers have started successfully.
12:48:35 Build was aborted
```

It looks like the same suites didn't fail on your verification branch though.. maybe something has changed?

**Comment by lostluck** [comment]
Right, I knew this. Python and Java have dataflow in the precommits, which isn't how the Go SDK organises it's tests, which is why it's a surprise. 

SGTM. Merging.

**Comment by TheNeuralBit** [comment]
Thanks!

**Pull request merged**
