### PR TITLE
[BEAM-79] Activate pre-commit tests and fix failure

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by manuzhang** [comment]
cherry-picked a390109c06227fa74b8e4aa882bb397dee698ab5 to see whether tests pass

**Comment by aaltay** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
I think the first commit here looks obviously correct. Since it passed unit tests and will get us closer to success, I can merge just that bit quite easily.

**Comment by kennknowles** [comment]
Well, let's actually just continue to work through the failures here. Best to be on your PR than mine.

**Comment by manuzhang** [comment]
It's weird that none of those failures can be reproduced locally. I'll work on it, though

**Comment by manuzhang** [comment]
superseded by #3292

**Pull request closed without merging**
