### PR TITLE
Removes or moves away all OldDoFn code from SDK except OldDoFn itself

### PR DESCRIPTION
**Pull request by jkff**
This is possible now that the Dataflow worker no longer uses this code.

R: @kennknowles

### CODE REVIEW

**Comment by jkff** [comment]
(actually I wonder if I need to build a new Dataflow worker image first?..)

**Comment by kennknowles** [comment]
If you do need a new worker image, then you should also be able to move OldDoFn to runners-core, perhaps?

**Comment by kennknowles** [comment]
This should be subject to a RunnableOnService oneshot for all the runners, though I think all the ones in the codebase are caught by compile errors.

**Comment by kennknowles** [comment]
Jenkins is happy. Is this ready for a look?

**Comment by kennknowles** [comment]
Actually can you squash since I haven't actually started? And then I'll also re-run the oneshots, or if you have a Jenkins login you can do so.

**Comment by kennknowles** [comment]
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Dataflow/2025/
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1358/
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Spark/671/
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Apex/233/

**Comment by jkff** [comment]
Squashed. No changes obviously, so test results should still apply.

**Pull request merged**
