### PR TITLE
[AWS2] Bump AWS v2 SDK 

### LINKED ISSUE #26323: [Task]: Bump AWS 2 SDK version
### What needs to happen?

Bump to latest SDK, related to #26295

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by mosche**
Bump AWS SDK v2 to latest.
This also fixes a bug in ProfileCredentialsProvider that made the behavior rather indeterministic when providing a custom profile name. See test changes below. 

(closes #26323)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @aromanenko-dev 
R: @psolomin

**Comment by mosche** [comment]
Retest this

**Comment by mosche** [comment]
retest this please

**Comment by mosche** [comment]
> However, when I reset AwsModule.java to the version from master branch, the tests from your version still pass. Is that intended? Just wonder if some tests are missing.

The code removed in AwsModule is more or less irrelevant, that's just to log a warning to catch a bug in the older SDK version. If you reset the tests to master you will see some failures because initialization of the provider was changed to lazy init when first loading credentials.

**Comment by mosche** [comment]
Retest this please

**Review by aromanenko-dev — APPROVED** [review]
LGTM, thanks

**Review by psolomin — APPROVED** [review]
Ah, you are referring to this change? https://github.com/aws/aws-sdk-java-v2/commit/1fafd9e87a0dd913f276705feddffcff719927a1

It's clear now, thanks for clarifying 👍

**Pull request merged**
