### PR TITLE
[fixes #22980] Migrate BeamFnLoggingClient to the new execution state sampler.

### LINKED ISSUE #22980: [Bug]: PTransform id unavailable for logs produced for portable Apache Beam Java SDK 2.41
### What happened?

The BeamFnApi.LogEntry transform id has not been populated due to the new ExecutionStateTracker implementation in https://github.com/apache/beam/commit/fbe61507ca

We use to have the per thread ExecutionStateTracker that we can use to correlate log thread id with the tracker state, from the state we can read pTransformId https://github.com/apache/beam/blob/434427e90b55027c5944fa73de68bff4f9a4e8fe/sdks/java/harness/src/main/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClient.java#L232. But the old ExecutionStateSampler is no longer used so we lost that bit of information in logging.

CC: @y1chi 

### Issue Priority

Priority: 0

### Issue Component

Component: sdk-java-harness

### PR DESCRIPTION
**Pull request by lukecwik**
This fixes the logging issue to include the transform id.

There is now a public unit test that will prevent a similar regression in the future.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @y1chi

**Review by y1chi — APPROVED** [review]
LGTM

**Comment by lukecwik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by lukecwik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Pull request merged**
