### PR TITLE
[BEAM-3441] Adds support for ValueProvider in JdbcIO.DataSourceConfiguration methods

### PR DESCRIPTION
**Pull request by sabhyankar**
Allows JdbcIO transforms to be fully templatized by providing ValueProvider support for the following methods:
- create
- withConnectionProperties
- withPassword
- withUsername

### CODE REVIEW

**Comment by aaltay** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM. 

Missed this. Sorry about the delay.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Java Gradle PreCommit

**Comment by chamikaramj** [comment]
Run Java Maven PreCommit

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Pull request merged**
