### PR TITLE
Fix caching in the Spark streaming, doing the cache update in the str…

### PR DESCRIPTION
**Pull request by jbonofre**
…eaming context

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @amitsela 
R: @aviemzur

**Comment by jbonofre** [comment]
Run Spark RunnableOnService

**Comment by aviemzur** [comment]
Run Spark RunnableOnService

**Comment by jbonofre** [comment]
Tests passed (including ROS).

**Comment by aviemzur** [comment]
LGTM!

**Comment by amitsela** [comment]
I'll merge since this became a blocker for other PRs.

**Pull request closed without merging**
