### PR TITLE
[BEAM-6981] use beam module global configuration for javadoc creation

### PR DESCRIPTION
**Pull request by adude3141**
Currently we do not set file encoding for javadoc creation and therefore rely on system default encoding.

This might lead to unexpected results.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by adude3141** [comment]
@udim
As your comments on PR https://github.com/apache/beam/pull/8200 made me look into that again I realised above problem. Of course we might add an additional reviewer if you think it is more appropriate.

**Comment by udim** [comment]
Ah, I just commented on #8200 but I hadn't realized that `applyJavaNature` isn't applied to `aggregateJavadoc`. Cool, so both PRs together should fix the issue.
CC @swegner to double check it's okay to use applyJavaNature here

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by swegner** [comment]
Note that I am no longer actively involved in the Beam project [dev@ thread](https://lists.apache.org/thread.html/de0c1d55784b2f7831a29bad422deea6fd03fdf80aae86a6a75e2994@%3Cdev.beam.apache.org%3E).

I can add some thoughts, though I'm not up-to-date on the codebase; I'll leave it to you to validate:

* `applyXYZNature()` is a convention we invented inside of the Beam codebase, not a Gradle-primitive. So validating whether it's safe to apply here means validating whether the custom logic within `applyJavaNature()` is safe here.
* For this to be safe, it should be the case that either a) only `applyJavadocNature()` gets applied without `applyJavaNature()` for any module, or b) the logic in`applyJavaNature()` is idempotent or safe to be applied multiple times in a project. One heuristic to check would be whether this pattern is present in other `applyXYZNature()` usages.
* If it's not safe, I would expect this to fail outright, rather than introduce a subtle bug. So if tests are passing it's probably ok. But it would be good to document explicitly assumptions or guarantees about `applyXYZNature()` idempotence.

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by udim** [comment]
Thanks @swegner (and sorry to bug you - I forgot you're no longer active in this project).
@adude3141,  I've skimmed applyJavaNature and I believe it shouldn't break anything.

**Comment by adude3141** [comment]
Thanks @udim and @swegner for your help here. I am also very confident, that the change does not brake things.

So lets wait for the tests pass. Afterwards merge.

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Java PreCommit

**Pull request merged**
