### PR TITLE
[BEAM-1817] Remove build machine pinning for python postcommit verify.

### PR DESCRIPTION
**Pull request by udim**
At this point no one knows why this exists any more and it's slowing
things down.

DESCRIPTION HERE

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
run seed job

**Comment by alanmyrvold** [comment]
I tried unpinning the python validatescontainer and it failed when run on beam8. x86_64-linux-gnu-gcc: error: src/python/grpcio/grpc/_cython/cygrpc.c: No such file or directory

https://builds.apache.org/view/A-D/view/Beam/job/beam_PostCommit_Python_ValidatesContainer_Dataflow/100/console

**Comment by udim** [comment]
@alanmyrvold Please see my response on https://issues.apache.org/jira/browse/BEAM-1817

**Comment by udim** [comment]
Already done in: https://github.com/apache/beam/pull/5214

**Pull request closed without merging**
