### PR TITLE
Structured logging support - Java SDK

### PR DESCRIPTION
**Pull request by udim**
edit: part of #26460

This enables logging data in the SLF4J MDC to the Fn Logging API by default.
This is safe:
1. No measurable change in performance (see below).
2. FnAPI changes are only in a new field (`custom_data`), which should be ignored by older implementations.

Benchmark | --logMdc | Mode | Cnt | Score (avg) | Error (CI 99.9%) | Units
-- | -- | -- | -- | -- | -- | --
BeamFnLoggingClientBenchmark.testLogging | FALSE | thrpt | 15 | 250797.094 | ± 6472.762 | ops/s
BeamFnLoggingClientBenchmark.testLoggingWithAllOptionalParameters | FALSE | thrpt | 15 | 248842.826 | ± 7465.302 | ops/s
BeamFnLoggingClientBenchmark.testLoggingWithCustomData | FALSE | thrpt | 15 | 240627.748 | ± 11956.723 | ops/s
BeamFnLoggingClientBenchmark.testLogging | TRUE | thrpt | 15 | 259780.715 | ± 2568.376 | ops/s
BeamFnLoggingClientBenchmark.testLoggingWithAllOptionalParameters | TRUE | thrpt | 15 | 258343.644 | ± 3613.817 | ops/s
BeamFnLoggingClientBenchmark.testLoggingWithCustomData | TRUE | thrpt | 15 | 253175.462 | ± 19008.712 | ops/s

Benchmark command: `./gradlew :sdks:java:harness:jmh:jmh -Pbenchmark=BeamFnLoggingClientBenchmark`
`--logMdc` set by changing the default value in SdkHarnessOption

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by udim** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by udim** [comment]
@Abacn ping for review

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Run Java PreCommit

**Pull request merged**
