### PR TITLE
[BEAM-1310] updates to JdbcIO k8 scripts & data loading

### PR DESCRIPTION
**Pull request by ssisk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

We have started setting up the k8 cluster & postgres instances, and I had a few small updates as I got things working. 

R @jbonofre 
cc @jasonkuster

### CODE REVIEW

**Comment by ssisk** [comment]
cc @davorbonaci in case you want to take a look at this.

**Comment by jasonkuster** [comment]
LGTM

**Comment by ssisk** [comment]
@davorbonaci @kennknowles @jbonofre - jason has reviewed the content of the CL, can we get a committer to submit?

**Comment by kennknowles** [comment]
LGTM. I can merge it.

**Pull request closed without merging**
