### PR TITLE
Refactor Select transform

### PR DESCRIPTION
**Pull request by reuvenlax**
This is a pure refactor, in preparation for a future PR - code that was previously inline is pulled into a helper class. No functionality should change.

### CODE REVIEW

**Comment by apilloud** [comment]
This doesn't build.

**Comment by reuvenlax** [comment]
@apilloud it does. A previous PR broke compilation, which is why this doesn't build. Should be fixed now.

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
@apilloud any more comments?

**Comment by reuvenlax** [comment]
Run Python_pytest PreCommit

**Comment by reuvenlax** [comment]
R: @kanterov

**Comment by kanterov** [comment]
@reuvenlax I will review on Wednesday if it's okay

**Comment by kanterov** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
@reuvenlax can you rebase?

**Comment by kanterov** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
@kanterov  done

**Comment by kanterov** [comment]
LGTM 👍 Now I see that it's only moving the code without changing anything.

**Pull request merged**
