### PR TITLE
Fixes #23627: Speed up website checks

### LINKED ISSUE #23627: [Bug]: Website precommit flaky
### What happened?

Occasionally the website precommit has taken 2 hours to run and has timed out. Normally it takes <30 minutes.

Example from cron job - https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/5938/
Many examples from precommit - https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/

### Issue Priority

Priority: 1

### Issue Component

Component: website

### PR DESCRIPTION
**Pull request by pabloem**
This should speed up the workflow significantly, and get it to pass most of the time.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
r: @damccorm

**Comment by damccorm** [comment]
@pabloem were you able to repro #23627 at all? I'm pretty happy to merge this since it seems like a strict improvement, but it seems unlikely that it was the cause of the problems (since it would still have to go through 4 tries to hit 2 hours.

It doesn't look like this has been happening lately, so it may be moot. This will also hopefully at least give us a clearer signal if it is the problem

**Review by damccorm — APPROVED** [review]

**Comment by pabloem** [comment]
I did not try to repro. I looked at a couple of the sample runs:

- https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/9524/console
- https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/9527/console

And both of these runs failed because it took too long to test for links in the website. My rationale is that testing links in the website actually does not cause failure - it only verifies whether there are broken links but due to the potential for flakiness, it only reports them rather than fully fail the check.

So if we speed up this check, we should be able to finish the checks faster without seeing failures on the test.

**Comment by damccorm** [comment]
> It doesn't look like this has been happening lately, so it may be moot. 

Oops, was looking at the wrong history.

> I did not try to repro. I looked at a couple of the sample runs:
>
> https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/9524/console
https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/9527/console
And both of these runs failed because it took too long to test for links in the website. My rationale is that testing links in the website actually does not cause failure - it only verifies whether there are broken links but due to the potential for flakiness, it only reports them rather than fully fail the check.
>
> So if we speed up this check, we should be able to finish the checks faster without seeing failures on the test.

Sounds good, lets maybe merge, leave the issue open for a few days, and close if the flakes stop?

**Pull request merged**
