### PR TITLE
Flink runner: support per transform parallelism through PipelineOptions.

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @aljoscha @kennknowles

**Comment by kennknowles** [comment]
I think this is a topic that deserves some discussion on the dev@beam.apache.org mailing list.

**Comment by davorbonaci** [comment]
This should probably be experimental for the time being.

@peihe, how do you see the importance of this flag vs. taking the time to get the right API for this type of configuration?

**Comment by reuvenlax** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
I will close this PR based on the [stale PR policy](https://beam.apache.org/contribute/contribution-guide/#stale-pull-requests), please reopen if you would like to continue working on it.

**Pull request closed without merging**
