### PR TITLE
[BEAM-545] PipelineOptions: fix parameter name

### PR DESCRIPTION
**Pull request by dhalperi**
Seems like a cut and paste error. R: @peihe

### CODE REVIEW

**Comment by dhalperi** [comment]
Opening it up to folks who appear to be active; any LGTM would be useful.

R: @lukecwik @davorbonaci @eljefe6a @staslev

**Comment by eljefe6a** [comment]
LGTM

**Comment by dhalperi** [comment]
Thanks! Merged

**Comment by peihe** [comment]
LGTM

**Pull request closed without merging**
