### PR TITLE
Exclude slf4j 2.x for arrow dependency

### LINKED ISSUE #30304: [Bug]: org.apache.arrow dependency introduced  unsupported SLF4J 2
### What happened?

We bumped org.apache.arrow to major version 15. It contains slf4j 2.x binding, causing Beam pipelines having slf4j 2 runtime dependency which is not supported:

pipeline submission log:
```
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/.../.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.36/4a18af6554bfe48b0f76eec98119c417da23c7e1/slf4j-jdk14-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

Dataflow worker log:
```
2024-02-13 13:33:28.310 EST
Please use a logger instead of System.out or System.err. Please switch to using org.slf4j.Logger. See: https://cloud.google.com/dataflow/pipelines/logging
2024-02-13 13:33:28.383 EST
Please use a logger instead of System.out or System.err. Please switch to using org.slf4j.Logger. See: https://cloud.google.com/dataflow/pipelines/logging
```

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #30304

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by Abacn** [comment]
There are lots of BigQuery test failing. So arrow 15 is necessary.

**Comment by Abacn** [comment]
changed to exclude slf4j from arrow dependency

**Comment by Abacn** [comment]
testTeardownCalledAfterExceptionInProcessElementStateful known flaky test. Ready for review now

**Comment by Abacn** [comment]
assign set of reviewers

**Comment by Abacn** [comment]
R: @shunping

**Comment by shunping** [comment]
Run Java PreCommit

**Comment by shunping** [comment]
LGTM!

**Pull request merged**
