### PR TITLE
Revert bigdataoss version upgrade

### LINKED ISSUE #23588: [Bug]: use_grpc_for_gcs experiment broken by big dataoss library upgrade from 2.2.6 to 2.2.8
### What happened?

The `use_grpc_for_gcs` experiment was broken by the upgrade of the big dataoss library from 2.2.6 to 2.2.8 (https://github.com/apache/beam/pull/23300) and was caught by internal testing within Google (b/251766179).

I used the following flags when creating the pipeline:
```
--experiments=use_grpc_for_gcs --gcsUploadBufferSizeBytes=16777216
```

The pipeline fails to upload artifacts during pipeline creation. An example dump of the failure is below:
```
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
Oct 11, 2022 3:39:58 PM org.apache.beam.runners.dataflow.DataflowRunner fromOptions
INFO: PipelineOptions.jobName did not match the service requirements. Using df2-source-bench-text-100g-staging-10111534327073 instead of df2-source-bench-text-100G-staging-10111534327073.
Oct 11, 2022 3:39:59 PM org.apache.beam.runners.dataflow.DataflowRunner run
INFO: Executing pipeline on the Dataflow Service, which will have billing implications related to Google Compute Engine usage and other Google Cloud Services.
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Uploading 2 files from PipelineOptions.filesToStage to staging location to prepare for execution.
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil tryStagePackage
INFO: Uploading /usr/local/google/_blaze_lcwik/1fc426c8a75c8141859a9e8595f2fd0a/execroot/google3/blaze-out/k8-opt/bin/cloud/dataflow/testing/integration/perf/source_bench_text_100G_gcs_with_grpc.runfiles/google3/cloud/dataflow/testing/framework/options/conscrypt.jar to gs://deft-guitar-sandbox-e2e-test/df2-source-bench-text-100G-staging/10111534327072/staging/lcwik/conscrypt-AfnHQstZKhUeLmK9U5eomAYoqWcAH82s1KpHRGeGhfM.jar
Oct 11, 2022 3:40:00 PM org.apache.beam.runners.dataflow.util.PackageUtil tryStagePackage
INFO: Uploading /usr/local/google/_blaze_lcwik/1fc426c8a75c8141859a9e8595f2fd0a/execroot/google3/blaze-out/k8-opt/bin/cloud/dataflow/testing/integration/perf/source_bench_text_100G_gcs_with_grpc.runfiles/google3/javatests/com/google/cloud/dataflow/v2/beam-testing-bundle.jar to gs://deft-guitar-sandbox-e2e-test/df2-source-bench-text-100G-staging/10111534327072/staging/lcwik/beam-testing-bundle-VMTQVJGM2Ldw1dAThX5bn1C7UwZoBdhVhq6XD-GXCHU.jar
Oct 11, 2022 3:43:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:46:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:46:11 PM com.google.cloud.hadoop.util.ResilientOperation nextSleep
INFO: Transient exception caught. Sleeping for 710, then retrying.
java.io.IOException: Got transient error for UploadID 'ADPycdtUrXxAYd3LoEhcLfF-VNMfY2kvwpyIzERGjfcVAaDWbGF7Ep1We5NSt0n9gJiLc7MxBGcZgSv5WwfjyKRgK87Ekw'
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.doResumableUpload(GoogleCloudStorageGrpcWriteChannel.java:325)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:105)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:206)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 408:Request Timeout
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:802)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:436)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more

Oct 11, 2022 3:49:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:52:00 PM org.apache.beam.runners.dataflow.util.PackageUtil stageClasspathElements
INFO: Still staging 2 files
Oct 11, 2022 3:52:20 PM com.google.cloud.hadoop.util.ResilientOperation nextSleep
INFO: Transient exception caught. Sleeping for 580, then retrying.
java.io.IOException: Got transient error for UploadID 'ADPycdtUrXxAYd3LoEhcLfF-VNMfY2kvwpyIzERGjfcVAaDWbGF7Ep1We5NSt0n9gJiLc7MxBGcZgSv5WwfjyKRgK87Ekw'
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.doResumableUpload(GoogleCloudStorageGrpcWriteChannel.java:325)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:66)
	at com.google.cloud.hadoop.util.ResilientOperation.retry(ResilientOperation.java:105)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:206)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageGrpcWriteChannel$UploadOperation.call(GoogleCloudStorageGrpcWriteChannel.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: 408:Request Timeout
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:802)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.census.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:436)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
```

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-gcp

### PR DESCRIPTION
**Pull request by johnjcasey**
Fixes #23588
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
R: @lukecwik R: @scwhittle

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by johnjcasey** [comment]
run java precommit

**Comment by johnjcasey** [comment]
run java precommit

**Pull request merged**
