### PR TITLE
[BEAM-3182][Nexmark][SQL] Implement sql query 2

### PR DESCRIPTION
**Pull request by akedin**
[BEAM-3182](https://issues.apache.org/jira/browse/BEAM-3182)

[Java version of the same query](https://github.com/apache/beam/blob/64ff21f35ee2946d38645fb0a51678628e49e62a/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/Query2.java#L46)

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery2.java, line 45 at r1](https://reviewable.io:443/reviews/apache/beam/4351#-L2SASAidDrgnhxMHcKR:-L2SASAj5XJBJZWDuS3c:bmid721) ([raw file](https://github.com/apache/beam/blob/57fb26a28afd89647caeab7852d152beebaf5f36/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery2.java#L45)):*
> ```Java
>  * <p>As written that query will only yield a few hundred results over event streams of
>  * arbitrary size. To make it more interesting we instead choose bids for every
>  * {@code auctionSkip}'th auction.
> ```

I think now `auctionSkip` is called `skipFactor`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4351)*

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
:lgtm: - can you squash the fixup and I'll merge?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4351#-:-L31jvqoL4-4-_qbh-Ww:b-6m50vh)*

**Comment by akedin** [comment]
squashed, rebased. waiting for tests

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4351#-:-L34GnOjl0oAxfEthDHZ:b-pjwnno)*

**Comment by kennknowles** [comment]
These failures are known issues. Ugh.

**Pull request merged**
