### PR TITLE
Fix testKafkaIOReadsAndWritesCorrectlyInStreaming failing for kafka performance test

### PR DESCRIPTION
**Pull request by benWize**
Kafka performance tests are failing just after being enabled, with stacktrace

`02:10:31 org.apache.beam.sdk.io.kafka.KafkaIOIT > testKafkaIOReadsAndWritesCorrectlyInStreaming FAILED
02:10:31     java.lang.IllegalStateException: withTopic() is required
02:10:31         at org.apache.beam.sdk.util.Preconditions.checkStateNotNull(Preconditions.java:471)
02:10:31         at org.apache.beam.sdk.io.kafka.KafkaIO$Write.expand(KafkaIO.java:2906)
02:10:31         at org.apache.beam.sdk.io.kafka.KafkaIO$Write.expand(KafkaIO.java:2699)
02:10:31         at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
02:10:31         at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
02:10:31         at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:376)
02:10:31         at org.apache.beam.sdk.io.kafka.KafkaIOIT.testKafkaIOReadsAndWritesCorrectlyInStreaming(KafkaIOIT.java:173)`

https://ci-beam.apache.org/job/beam_PerformanceTests_Kafka_IO/2791/console

Might be related to #21752 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by benWize** [comment]
Run Java KafkaIO Performance Test

**Comment by benWize** [comment]
Run Java KafkaIO Performance Test

**Comment by benWize** [comment]
Run Java KafkaIO Performance Test

**Comment by benWize** [comment]
R: @johnjcasey 
R: @pabloem, could you help me to trigger KafkaIO Performance Test?

**Comment by johnjcasey** [comment]
LGTM.

**Comment by johnjcasey** [comment]
run java postcommit

**Comment by pabloem** [comment]
kafkaIO perf test: https://ci-beam.apache.org/job/beam_PerformanceTests_Kafka_IO/2794/

**Comment by benWize** [comment]
> let me know if I should merge

The run was a success, I think we can merge it

**Comment by benWize** [comment]
Thank you all!

**Pull request merged**
