### PR TITLE
[BEAM-1740] Upgrade to bigtable-client-core 0.9.5.1

### PR DESCRIPTION
**Pull request by andrewsmartin**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @dhalperi (welcome back!)

**Comment by dhalperi** [comment]
LGTM assuming the tests pass!

@tgroh -- any additional changes regarding shading?

**Comment by dhalperi** [comment]
@davorbonaci @ssisk @jasonkuster I did not see BigtableITs being run in the precommit where they used to be run. Where are they being run now?

**Comment by tgroh** [comment]
No, this should be fine. We may still not be able to shade the Google Cloud Platform IOs without additional changes as bigtable-client-core still exposes Guava on its API surface in return types (specifically in `BigtableDataClient` with listenable futures and `ImmutableList sampleRowKeys(...)`

**Comment by tgroh** [comment]
BigtableITs are run in postcommit.

[here's one](https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/2959/)

**Comment by dhalperi** [comment]
So it looks like this commit breaks those tests. @andrewsmartin can you please take a look? It might be there there has been a change in the version of some Bigtable dependency (gRPC, netty, etc.) https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/org.apache.beam$beam-sdks-java-io-google-cloud-platform/2959/testReport/junit/org.apache.beam.sdk.io.gcp.bigtable/BigtableReadIT/testE2EBigtableRead/

**Comment by dhalperi** [comment]
Btw, apparently @andrewsmartin does not have privileges to run the tests without one of the commiters running it for him.

Andrew, I'm assuming you have access to your own Bigtable cluster (if you use BigtableIO) -- suggest running the IT manually in your local developer environment.

**Comment by andrewsmartin** [comment]
@dhalperi You're right, there was a version conflict with netty. This version of the bigtable client relies on a class that only exists in `netty-common:4.1.6.Final`. I added another commit to bump the netty version project-wide.

**Comment by dhalperi** [comment]
I kicked off https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_MavenInstall/2972/ to run the ITs manually. Thanks @andrewsmartin

**Comment by dhalperi** [comment]
Passed! Merged, thanks!

**Pull request closed without merging**
