### PR TITLE
Use async as a suffix rather than a prefix for asynchronous variants.

### PR DESCRIPTION
**Pull request by robertwb**
This is better aligned with standard javascript convention.

Often libraries have the default version be asynchronous, and
name the Sync one explicitly, we are marking the async ones as
they are by far the most common and usable for pipeline
construction.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @pskevin

**Review by pskevin — APPROVED** [review]
LGTM.

**Comment by pabloem** [comment]
I was wondering if we should default to making all apply calls be Async (they would return some sort of Future<PCollection>) and we could have futures applied on futures... wdyt Robert?

This is of course a big change to the API - I'm just spitballing...

**Comment by robertwb** [comment]
I did consider this, but it would make chaining much more verbose. E.g. instead of 

```
lines
    .map((s: string) => s.toLowerCase())
    .flatMap(function* splitWords(line: string) {
      yield* line.split(/[^a-z]+/);
    })
    .apply(beam.countPerElement())
```

one would have to write

```
(await 
    (await 
        (await lines
            .map((s: string) => s.toLowerCase())
        ).flatMap(function* splitWords(line: string) {
      yield* line.split(/[^a-z]+/);
    })
    ).apply(beam.countPerElement()))
```

or 

```
lines
   .map((s: string) => s.toLowerCase())
   .then((result) => {
      return result.flatMap(function* splitWords(line: string) {
        yield* line.split(/[^a-z]+/);
      })
    })
    .then((result) => {
      return result.apply(beam.countPerElement());
    })
```

which gets really painful. (Note that the future here is Javascript's Promise, which is a kind of special builtin).

**Comment by pabloem** [comment]
I thought of something like this:

```
chainedPromises = lines
  .map((s: string) => s.toLowerCase())
  .flatMap(function* splitWords(line: string) {
        yield* line.split(/[^a-z]+/);
      })
    .apply(beam.countPerElement());

countPcoll = chainedPromises.resolve();

// In case of error while expanding an intermediate PCollection, then we can throw/return an error from there when resolving the PCollection
// (error e.g. to resolve schema, or to match input/output types / etc).
```

Where each `apply(...)` returns a `Promise<PCollection<...>>` and the actual expansion is deferred... 

though I haven't researched JS enough, I think this is doable...

**Comment by robertwb** [comment]
To do this one would have to add methods like flatMap to the Promise prototype (affecting all Promises across Javascript) or return a subclass (well, really a hierarchy of subclasses) of Promise (which I looked into and looks pretty sketchy). This would work if Promise could be a proxy object to the type it was promising, but it's not. 

It looks like another alternative is 

```
lines
    .invoke("map", (s: string) => s.toLowerCase())
    .invoke("flatMap", function* splitWords(line: string) {
      yield* line.split(/[^a-z]+/);
    })
    .invoke("apply", beam.countPerElement())
```

but this is still a bit icky, and looses type safety.

**Comment by pabloem** [comment]
Well thanks for doing the research and sharing your thoughts:)

**Pull request merged**
