### PR TITLE
[DNM] Test LTS bom version candidates

### PR DESCRIPTION
**Pull request by apilloud**
[DNM] Test LTS bom version candidates

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by apilloud** [comment]
Run CommunityMetrics PreCommit

**Comment by apilloud** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by apilloud** [comment]
Run Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by apilloud** [comment]
Run Dataflow Runner V2 Nexmark Tests

**Comment by apilloud** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by apilloud** [comment]
Run Dataflow ValidatesRunner Java 11

**Comment by apilloud** [comment]
Run Dataflow ValidatesRunner Java 17

**Comment by apilloud** [comment]
Run Dataflow ValidatesRunner

**Comment by apilloud** [comment]
Run Direct Runner Nexmark Tests

**Comment by apilloud** [comment]
Run Direct ValidatesRunner Java 11

**Comment by apilloud** [comment]
Run Direct ValidatesRunner Java 17

**Comment by apilloud** [comment]
Run Direct ValidatesRunner

**Comment by apilloud** [comment]
Run Flink Runner Nexmark Tests

**Comment by apilloud** [comment]
Run Flink ValidatesRunner Java 11

**Comment by apilloud** [comment]
Run Flink ValidatesRunner

**Comment by apilloud** [comment]
Run Go Flink ValidatesRunner

**Comment by apilloud** [comment]
Run Go PostCommit

**Comment by apilloud** [comment]
Run Go PreCommit

**Comment by apilloud** [comment]
Run Go Samza ValidatesRunner

**Comment by apilloud** [comment]
Run Go Spark ValidatesRunner

**Comment by apilloud** [comment]
Run GoPortable PreCommit

**Comment by apilloud** [comment]
Run Java 11 Examples on Dataflow Runner V2

**Comment by apilloud** [comment]
Run Java 17 Examples on Dataflow Runner V2

**Comment by apilloud** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by apilloud** [comment]
Run Java Dataflow V2 ValidatesRunner

**Comment by apilloud** [comment]
Run Java Examples on Dataflow Runner V2

**Comment by apilloud** [comment]
Run Java Examples_Direct

**Comment by apilloud** [comment]
Run Java Examples_Spark

**Comment by apilloud** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by apilloud** [comment]
Run Java Portability examples on Dataflow with Java 11

**Comment by apilloud** [comment]
Run Java PostCommit

**Comment by apilloud** [comment]
Run Java PreCommit

**Comment by apilloud** [comment]
Run Java Samza PortableValidatesRunner

**Comment by apilloud** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by apilloud** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by apilloud** [comment]
Run Java Spark v3 PortableValidatesRunner Streaming

**Comment by apilloud** [comment]
Run Java examples on Dataflow Java 11

**Comment by apilloud** [comment]
Run Java examples on Dataflow with Java 11

**Comment by apilloud** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by apilloud** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by apilloud** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by apilloud** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by apilloud** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by apilloud** [comment]
Run Javadoc PostCommit

**Comment by apilloud** [comment]
Run Jpms Dataflow Java 11 PostCommit

**Comment by apilloud** [comment]
Run Jpms Dataflow Java 17 PostCommit

**Comment by apilloud** [comment]
Run Jpms Direct Java 11 PostCommit

**Comment by apilloud** [comment]
Run Jpms Direct Java 17 PostCommit

**Comment by apilloud** [comment]
Run Jpms Flink Java 11 PostCommit

**Comment by apilloud** [comment]
Run Jpms Spark Java 11 PostCommit

**Comment by apilloud** [comment]
Run PortableJar_Flink PostCommit

**Comment by apilloud** [comment]
Run PortableJar_Spark PostCommit

**Comment by apilloud** [comment]
Run Portable_Python PreCommit

**Comment by apilloud** [comment]
Run PostCommit_Java_Dataflow

**Comment by apilloud** [comment]
Run PostCommit_Java_DataflowV2

**Comment by apilloud** [comment]
Run PostCommit_Java_Hadoop_Versions

**Comment by apilloud** [comment]
Run Python 3.7 PostCommit

**Comment by apilloud** [comment]
Run Python 3.8 PostCommit

**Comment by apilloud** [comment]
Run Python 3.9 PostCommit

**Comment by apilloud** [comment]
Run Python Dataflow V2 ValidatesRunner

**Comment by apilloud** [comment]
Run Python Dataflow ValidatesContainer

**Comment by apilloud** [comment]
Run Python Dataflow ValidatesRunner

**Comment by apilloud** [comment]
Run Python Examples_Dataflow

**Comment by apilloud** [comment]
Run Python Examples_Direct

**Comment by apilloud** [comment]
Run Python Examples_Flink

**Comment by apilloud** [comment]
Run Python Examples_Spark

**Comment by apilloud** [comment]
Run Python Flink ValidatesRunner

**Comment by apilloud** [comment]
Run Python PreCommit

**Comment by apilloud** [comment]
Run Python Samza ValidatesRunner

**Comment by apilloud** [comment]
Run Python Spark ValidatesRunner

**Comment by apilloud** [comment]
Run PythonDocker PreCommit

**Comment by apilloud** [comment]
Run PythonDocs PreCommit

**Comment by apilloud** [comment]
Run PythonFormatter PreCommit

**Comment by apilloud** [comment]
Run PythonLint PreCommit

**Comment by apilloud** [comment]
Run Python_PVR_Flink PreCommit

**Comment by apilloud** [comment]
Run RAT PreCommit

**Comment by apilloud** [comment]
Run Release Gradle Build

**Comment by apilloud** [comment]
Run SQL PostCommit

**Comment by apilloud** [comment]
Run SQL PreCommit

**Comment by apilloud** [comment]
Run SQL_Java11 PreCommit

**Comment by apilloud** [comment]
Run SQL_Java17 PreCommit

**Comment by apilloud** [comment]
Run Spark Runner Nexmark Tests

**Comment by apilloud** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by apilloud** [comment]
Run Spark ValidatesRunner Java 11

**Comment by apilloud** [comment]
Run Spark ValidatesRunner

**Comment by apilloud** [comment]
Run Spotless PreCommit

**Comment by apilloud** [comment]
Run Twister2 ValidatesRunner

**Comment by apilloud** [comment]
Run Typescript PreCommit

**Comment by apilloud** [comment]
Run ULR Loopback ValidatesRunner

**Comment by apilloud** [comment]
Run Whitespace PreCommit

**Comment by apilloud** [comment]
Run XVR_Direct PostCommit

**Comment by apilloud** [comment]
Run XVR_JavaUsingPython_Dataflow PostCommit

**Comment by apilloud** [comment]
Run XVR_PythonUsingJavaSQL_Dataflow PostCommit

**Comment by apilloud** [comment]
Run XVR_PythonUsingJava_Dataflow PostCommit

**Comment by apilloud** [comment]
Run XVR_Samza PostCommit

**Comment by apilloud** [comment]
Run XVR_Spark PostCommit

**Comment by apilloud** [comment]
Run XVR_Spark3 PostCommit

**Comment by apilloud** [comment]
Run PostCommit_Java_Dataflow

**Comment by apilloud** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by apilloud** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by apilloud** [comment]
Run PostCommit_Java_Dataflow

**Comment by apilloud** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by kileys** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by kennknowles** [comment]
Seems there are a number of problems storing the gradle cache entry hmm.

**Comment by kennknowles** [comment]
Run Spotless PreCommit

**Comment by kileys** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by kennknowles** [comment]
run dataflow postcommit

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Java precommit failure here: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/24479/

May be a hard failure.

**Comment by kileys** [comment]
I did some more testing on https://github.com/apache/beam/pull/23834. Only failure remaining is https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1_PR/143/

**Comment by kileys** [comment]
I'm running it locally to see where it gets stuck

**Comment by kennknowles** [comment]
Run PostCommit_Java_Dataflow

**Comment by kileys** [comment]
Ignored the Python/XL failures since we introduced 3.10 after the release

**Pull request closed without merging**
