### PR TITLE
Enable testWithShardedKeyInGlobalWindow on Dataflow V2 VR

### LINKED ISSUE #25675: [Feature]: Implement and reenable GroupIntoBatchesTest.testWithShardedKeyInGlobalWindow: causes dataflow suite to be permared
### What happened?

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/ is permared. The failing test is `testWithShardedKeyInGlobalWindow`.

I looked at an example job and it isn't even starting up correctly - https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-03-01_02_18_07-687229064971437925;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=apache-beam-testing&pageState=%28%22dfTime%22:%28%22l%22:%22dfJobMaxTime%22%29%29&e=-13802955&jsmode=o&mods=dataflow_dev - in the Dataflow backend I see Job 2023-03-01_02_18_07-687229064971437925 failed to start with status: generic::invalid_argument: Autosharding is not supported with Unified Worker/Runner v2.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
and disable it on Dataflow V1 VR, fixes #25675

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by damccorm** [comment]
Run Java Dataflow ValidatesRunner Streaming

**Review by damccorm — APPROVED** [review]
LGTM (assuming suites pass)

**Comment by Abacn** [comment]
btw realize Dataflow V2 ValidatesRunner Streaming is taking more than 6 hr to run. May need an audit on the tests check if all are necessary.

**Comment by Abacn** [comment]
Related test passed: https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming_PR/83/testReport/org.apache.beam.sdk.transforms/GroupIntoBatchesTest/testWithShardedKeyInGlobalWindow/

though there are multiple test failing due to quota exceeded (creation failed: The zone 'projects/apache-beam-testing/zones/us-central1-a' does not have enough resources available to fulfill the request.)

merging for now

**Pull request merged**
