### PR TITLE
[BEAM-7012] Support TestStream in streaming Flink Runner

### PR DESCRIPTION
**Pull request by mxm**
TestStream is a way to construct a stream with control over elements and
time. In total, 40 ValidatesRunner tests make use of this feature (tagged via
UsesTestStream). So far only the DirectRunner supported TestStream which meant
that those tests were not executed for other Runners, e.g. Flink.

Implementing TestStream for Flink was not hard, except for supporting the
processing time functionality for which a clean solution seems impossible.
However, only 2 of the 40 UsesTestStream tests make use of processing time.
An annotation (UsesTestStreamWithProcessingTime) was added to allow Runners to
exclude those tests.

This still adds 38 new ValidatesRunner tests in Flink streaming mode.

CC @tweise @kennknowles 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
@iemejia I've updated the PR to use Coders instead of Serializable to ship TestStream Events.

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Run Python_PVR_Flink PreCommit

**Comment by iemejia** [comment]
Run Direct ValidatesRunner

**Comment by iemejia** [comment]
Mmm curious it seems swe don't have a way to trigger ValidatesRunner tests for Direct runner. I just run it locally via `/gradlew :beam-runners-direct-java:validatesRunner` and everything passes so merging.

**Comment by mxm** [comment]
Thanks!

**Comment by kennknowles** [comment]
Nice! It is great to have an example of this for a runner other than the direct runner. I will read this later for sure. Sorry I didn't have time to review it promptly.

**Comment by mxm** [comment]
I just came across this and wondered why we hadn't implemented this. Turns out, this was not hard to implement for streaming. Well, minus the processing time functionality for which I couldn't find a good solution, so I excluded two tests which make use of that feature. I'm planning to also add TestStream for the portable Runner.

**Comment by robertwb** [comment]
Very cool.

One of the things that TestStream needs to ensure determinism is the notion
of quiescence, that is between each event one needs to ensure that the
downstream elements and watermarks are processed as completely as possible.
Is this guaranteed by the checkpoint lock? If so, it's worth at least a
couple of comments.

**Comment by mxm** [comment]
Yes, I was wondering about quiescence as well. It looks to me that it is nice to have but not necessary when a strict order of all TestStream events can be guaranteed. I see that quiescence in the case of Dataflow is necessary because of the global watermark service for which we cannot update the watermark unless elements have been fully processed. Flink's Watermarks are propagated through the graph just like regular data elements (in case of multiple outputs of a operator they will be send to each of the outputs). Thus, any events triggered by the TestStream source are guaranteed to be processed one after another and should not influence each other.

**Comment by robertwb** [comment]
Thanks for clarifying this; good to know.

**Pull request merged**
