### PR TITLE
Fix StringSet tests on portable runners

### PR DESCRIPTION
**Pull request by Abacn**
Reverts apache/beam#31818

### CODE REVIEW

**Comment by Abacn** [comment]
after #31838 now portable runners can see stringset metrics, however, the result is different from non-portable ones and still failing the assert

Previous:

```
java.lang.AssertionError: 
Expected: iterable with items [
     MetricResult{inNamespace="org.apache.beam.sdk.metrics.MetricsTest", name="sources", step="MyStep1", attempted=<StringSetResult{stringSet=[gcs]}>},
     MetricResult{inNamespace="org.apache.beam.sdk.metrics.MetricsTest", name="sinks", step="MyStep2", attempted=<StringSetResult{stringSet=[kafka, bq]}>},
     MetricResult{inNamespace="org.apache.beam.sdk.metrics.MetricsTest", name="sideinputs", step="MyStep1", attempted=<StringSetResult{stringSet=[bigtable, spanner]}>},
     MetricResult{inNamespace="org.apache.beam.sdk.metrics.MetricsTest", name="sideinputs", step="MyStep2", attempted=<StringSetResult{stringSet=[sql, bigtable]}>}
] in any order
     but: no item matches: ... in []
```

now:

```
but: not matched: <
MetricResult{key=MyStep1-ParMultiDo-Anonymous-:org.apache.beam.sdk.metrics.MetricsTest:sources, committedOrNull=null, attempted=StringSetResult{stringSet=[gcs]}}>
```

checked that `metrics.getStringSets()` now returns

```
[
MetricResult{key=MyStep2:org.apache.beam.sdk.metrics.MetricsTest:sinks, committedOrNull=null, attempted=StringSetResult{stringSet=[kafka, bq]}},
MetricResult{key=MyStep1-ParMultiDo-Anonymous-:org.apache.beam.sdk.metrics.MetricsTest:sources, committedOrNull=null, attempted=StringSetResult{stringSet=[gcs]}},
MetricResult{key=MyStep2:org.apache.beam.sdk.metrics.MetricsTest:sideinputs, committedOrNull=null, attempted=StringSetResult{stringSet=[bigtable, sql]}},
MetricResult{key=MyStep1-ParMultiDo-Anonymous-:org.apache.beam.sdk.metrics.MetricsTest:sideinputs, committedOrNull=null, attempted=StringSetResult{stringSet=[spanner, bigtable]}},
MetricResult{key=MyStep2:org.apache.beam.sdk.metrics.MetricsTest:sinks, committedOrNull=null, attempted=StringSetResult{stringSet=[kafka, bq]}},
MetricResult{key=MyStep1-ParMultiDo-Anonymous-:org.apache.beam.sdk.metrics.MetricsTest:sources, committedOrNull=null, attempted=StringSetResult{stringSet=[gcs]}},
MetricResult{key=MyStep2:org.apache.beam.sdk.metrics.MetricsTest:sideinputs, committedOrNull=null, attempted=StringSetResult{stringSet=[bigtable, sql]}},
MetricResult{key=MyStep1-ParMultiDo-Anonymous-:org.apache.beam.sdk.metrics.MetricsTest:sideinputs, committedOrNull=null, attempted=StringSetResult{stringSet=[spanner, bigtable]}}
]
```

the problem is each result duplicated one more time

**Comment by Abacn** [comment]
Java PVR Spark Batch two tests failed: testValueStateCoderInferenceFromInputCoder testValueStateCoderInference unrelated to the change

Java ULR stringset test failed, still need to exclude it

**Comment by Abacn** [comment]
Dataflow v2 test Still failing:

```
org.apache.beam.sdk.metrics.MetricsTest$AttemptedMetricTests > testAttemptedStringSetMetrics FAILED
    java.lang.AssertionError at MetricsTest.java:417
org.apache.beam.sdk.metrics.MetricsTest$CommittedMetricTests > testCommittedStringSetMetrics FAILED
    java.lang.AssertionError at MetricsTest.java:288
```

will investigate further

**Comment by Abacn** [comment]
Ready for review. Latest commit reverted trigger file change. See test results of f302fb1

**Comment by Abacn** [comment]
R: @robertwb @rohitsinha54

**Review by rohitsinha54 — APPROVED** [review]

**Pull request merged**
