### PR TITLE
Fix seed job

### LINKED ISSUE #22676: [Bug]: Seed job failing to access LDAP
### What happened?

```
ERROR:root:Couldn't generate the list of committers
Traceback (most recent call last):
  File "main.py", line 70, in get_committers_github_usernames
    people = connection.search_s(
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 631, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 624, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 614, in search_ext
    return self._ldap_call(
  File "/home/jenkins/jenkins-slave/workspace/beam_SeedJob/.test-infra/jenkins/committers_list_generator/ve3/lib/python3.8/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'errno': 107, 'ctrls': [], 'info': 'Transport endpoint is not connected'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 142, in <module>
    generate_groovy(args.output_dir, args.ldap_uris, args.cert_path)
  File "main.py", line 53, in generate_groovy
    github_usernames=get_committers_github_usernames(
  File "main.py", line 104, in get_committers_github_usernames
    raise CommittersGeneratorException("Could not fetch LDAP data") from e
CommittersGeneratorException: Could not fetch LDAP data
```

https://ci-beam.apache.org/job/beam_SeedJob/10122/

### Issue Priority

Priority: 1

### Issue Component

Component: infrastructure

### PR DESCRIPTION
**Pull request by damccorm**
Per infra we can just let the system do chain based auth here and so we don't need to explicitly supply a cert file.

This fixes the issue and adds some logging

Fixes #22676

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
R: @TheNeuralBit

**Review by TheNeuralBit — APPROVED** [review]
Nice, thanks. It's fun when a negative diff solves a problem :)

**Pull request merged**
