### PR TITLE
Updating Dataflow API client protobufs

### PR DESCRIPTION
**Pull request by pabloem**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by pabloem** [comment]
r: @chamikaramj 
Updating the Dataflow API Client protobuffs to include counter structured names. `mvn clean verify` runs successfully, and a [wordcount job has also run fine](http://i.imgur.com/jFryioY.png).

**Comment by pabloem** [comment]
The failed jenkins run is due to the Spark runner tests. Note that all else passes.

**Comment by chamikaramj** [comment]
LGTM

**Comment by pabloem** [comment]
@aaltay can you merge please?

**Pull request closed without merging**
