### PR TITLE
mr-runner: use SerializablePipelineOptions to serde PipelineOptions

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by huafengw** [comment]
R: @peihe

**Comment by peihe** [comment]
retest this please

**Comment by peihe** [comment]
retest this please

**Comment by aaltay** [comment]
Hey @peihe any progress on this?

**Comment by reuvenlax** [comment]
R: @peihe any status on this PR?

**Comment by peihe** [comment]
retest this please

**Comment by peihe** [comment]
LGTM

**Comment by peihe** [comment]
merged, thanks @huafengw!
This PR can be closed.

**Pull request closed without merging**
