### PR TITLE
Fix for #22631 KafkaIO considers readCommitted() as it would commit back the offsets, which it doesn't

### LINKED ISSUE #22631: [Bug]: KafkaIO considers readCommitted() as it would commit back the offsets, which it doesn't
### What happened?

I have been reading from Kafka and trying to figure out which offset management would be the best for my use-case. During that I noticed something odd.

https://github.com/apache/beam/blob/c9c161d018d116504fd5f83b48853a7071ec9ce4/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java#L2359-L2362

    private boolean configuredKafkaCommit() {
      return getConsumerConfig().get("isolation.level") == "read_committed"
          || Boolean.TRUE.equals(getConsumerConfig().get(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG));
    }
https://github.com/apache/beam/blob/c9c161d018d116504fd5f83b48853a7071ec9ce4/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java#L2292-L2298
https://github.com/apache/beam/blob/c9c161d018d116504fd5f83b48853a7071ec9ce4/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java#L2321-L2334

The name of the method, and how it's being used in the code certainly suggest that using read_committed isolation level handles and commits kafka offsets.Seemed strange, but I'm not a Kafka pro, so let's test it. Well it does not.

- using ONLY ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG does commit it
- using ONLY commitOffsetsInFinalize() does commit it

- using ONLY withReadCommitted() does NOT commit it

Dataflow, 2.40.0 Java SDK, without explicitly enabling SDF-read

So is it a bug, or what am I missing here?

If it is indeed a bug, then is it with the read_committed (so it should commit it although found no explicit documentation about that anywhere), or having that isolation level shouldn't prefer the commit in the finalize and that method is wrong?

------------
@johnjcasey: 
withReadCommitted() doesn't commit messages when read, it instead specifies that the kafka consumer should only read messages that have themselves been committed to kafka.

Its use is for exactly once applications.
------------
@johnjcasey 
Which looking at your message again, would imply that the configuredKafkaCommit() method shouldn't inspect isolation.level

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-kafka

### PR DESCRIPTION
**Pull request by nbali**
See #22631 

fixes #22631 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~[ ] Update `CHANGES.md` with noteworthy changes.~
 - ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by nbali** [comment]
R: @johnjcasey

**Comment by nbali** [comment]
Run Java PreCommit

**Comment by johnjcasey** [comment]
LGTM

**Comment by aromanenko-dev** [comment]
Thanks for a fix! It would be great to have a regression test on this issue.

**Comment by nbali** [comment]
@aromanenko-dev I'm not sure it's possible in a meaningful way. The problem wasn't with a complex logic, but that it called basically an invalid equality check on a getter. Any random getter might be checked later on, not only this one. S unless we cover every possible permutation the test would only catch if somebody reintroduces the read_committed check.

**Comment by aromanenko-dev** [comment]
> So unless we cover every possible permutation the test would only catch if somebody reintroduces the read_committed check.

@nbali I was talking mostly about this. My point was like that one - if we fix a bug, then in the first order, we need to introduce a regression test that reproduces it and only after that a bugfix. In this case, I believe that checking different combinations of config options would be enough.

**Pull request merged**
