### PR TITLE
Add Tour of Beam Page

### LINKED ISSUE #27241: [Bug]: Tour of Beam URL Broken
### What happened?

When searching `A Tour of Beam` on Google, the search result returns https://beam.apache.org/get-started/tour-of-beam/
, which is a broken link.

We should have this page redirect to https://tour.beam.apache.org/

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by svetakvsundhar**
Fixes #27241 

`Note`: I didn't re-add this page onto the nav bar. I don't think its needed, as once a user is on the site, they can navigate directly to `Tour of Beam (Beta)`. This is just a landing page for those that search through a search engine, to provide better UX w/o a broken link.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by svetakvsundhar** [comment]
R: @damccorm

**Comment by damccorm** [comment]
Run RAT PreCommit

**Comment by svetakvsundhar** [comment]
Run RAT PreCommit

**Comment by damccorm** [comment]
This LGTM, once Jenkins stops having issues I'll merge

**Comment by damccorm** [comment]
retest this please

**Comment by damccorm** [comment]
(comment is for bot)

**Comment by svetakvsundhar** [comment]
Run Website PreCommit

**Comment by damccorm** [comment]
Run Website_Stage_GCS PreCommit

**Review by damccorm — APPROVED** [review]
Thanks!

**Pull request merged**
