### PR TITLE
[BEAM-2795] Key FlinkRunner batch translation by URN

### PR DESCRIPTION
**Pull request by bsidhom**
Before this change, the translator downcasts pipeline transforms. This cannot be done with jobs that have been submitted portably through the Job API. This change uses URNs (available on rehydrated pipelines) for translation.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by bsidhom** [comment]
`mvn clean verify` failed due to an error when running the Python SDK tests.

From what I can see, the [Jenkins WordCount test](https://builds.apache.org/job/beam_PreCommit_Java_GradleBuild/627/testReport/org.apache.beam.examples/WordCountIT/) failed for the Apex runner.

**Comment by bsidhom** [comment]
run Flink ValidatesRunner

**Comment by aljoscha** [comment]
retest this please

**Comment by aljoscha** [comment]
The changes look good! I'm rerunning tests to see if this is flaky or a real problem but it cannot be caused by these changed.

**Comment by bsidhom** [comment]
Some presumably-unrelated tests are still failing. Not sure if they're flaky or really failing at this point.

**Comment by aljoscha** [comment]
Can you try rebasing this on master? The `mvn clean install` job still failed.

You can still merge but I won't be at a machine where I can review code well and merge starting today.

**Comment by bsidhom** [comment]
I've rebased on master, but it still appears to be flaking.

**Pull request merged**
