### PR TITLE
SpannerIO - Do not use .get() on ValueProvider during pipeline creation

### PR DESCRIPTION
**Pull request by bvolpato**
Fixes issue https://github.com/apache/beam/issues/22146 (also reported on [StackOverflow](https://stackoverflow.com/questions/73765145/apache-beam-illegalstateexception-value-only-available-at-runtime-after-upgra)).

[ValueProvider](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/options/ValueProvider.html) can be used to pass runtime parameters not available during pipeline creation (which is heavily used by [Dataflow Templates](https://cloud.google.com/dataflow/docs/concepts/dataflow-templates)).

In case a `RuntimeValueProvider` is being used, using `.get()` will throw the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider{propertyName=spannerInstanceId, default=defaultinstanceid}
        at org.apache.beam.sdk.options.ValueProvider$RuntimeValueProvider.get(ValueProvider.java:254)
        at org.apache.beam.sdk.io.gcp.spanner.SpannerConfig.withInstanceId(SpannerConfig.java:165)
        at .... my code constructing SpannerConfig ...
```

So my changes adjust that behavior, to validate only if there is a reference to a provider, but not trying to use the value.
Ideally those can be validated elsewhere when not using the ValueProvider (the other entry methods do not specify `@Nullable`, so that should be handled already). 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] ~Update `CHANGES.md` with noteworthy changes.~
 - [x] ~If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
(unrelated test failing, seems like a flake)

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM. It would be great to update CHANGES.md to make this fix more visible in release notes.

Also, I was wondering why it was not caught by Spanner integration tests but, iinm, they are not running periodically on Jenkins like others. So, it would be great to add this as a separate issue/PR.

**Comment by bvolpato** [comment]
> Thanks, LGTM. It would be great to update CHANGES.md to make this fix more visible in release notes.

Done, thank you. Please merge it if you agree with the CHANGES entry.


> Also, I was wondering why it was not caught by Spanner integration tests but, iinm, they are not running periodically on Jenkins like others. So, it would be great to add this as a separate issue/PR.

From what I checked all tests are using the `.withXyz(String)`, which end up instantiating `.withXyz(StaticValueProvider)`, and then it works fine.

I think that the usage of `.get()` on a `ValueProvider` doesn't make sense as it kills the purpose of using providers. Maybe that could be enforced automatically (e.g., block any `ValueProvider.get()` outside a DoFn/PTransform) or at least pushed back on code review, but I am not sure how to proceed to improve the process here.

**Comment by bvolpato** [comment]
Run Java PreCommit

**Pull request merged**
