### PR TITLE
[BEAM-2964]  Exclude incompatible six release, part 2

### PR DESCRIPTION
**Pull request by charlesccychen**
R: @robertwb

### CODE REVIEW

**Comment by charlesccychen** [comment]
retest this please

**Comment by robertwb** [comment]
LGTM. Does this mean we can remove the one in the test requirements, or should we leave that there?

**Comment by charlesccychen** [comment]
It seems that we can't remove the one in the test requirements--for some reason if we do, nose pulls in the latest version of six.

**Comment by charlesccychen** [comment]
I have verified that `python setup.py test` and `tox -e lint` succeed with this change.  I have also verified that the correct version of `six` is installed in a clean environment with a tarball built with this change.

Presubmits at head are broken by https://github.com/apache/beam/pull/3255#issuecomment-330996163.

@robertwb, can you PTAL?

**Comment by robertwb** [comment]
Thanks. Safe to leave both in. LGTM, I'll merge.

**Pull request closed without merging**
