### PR TITLE
Use only ValueProviders in SpannerConfig

### PR DESCRIPTION
**Pull request by bvolpato**
Fine-grained access control was added to Spanner, and the property DatabaseRole was added to Beam's SpannerConfig (https://github.com/apache/beam/pull/23377).

However, unlike the rest of the configuration class, ValueProvider support wasn't added, which is necessary to use it in Template jobs (more information [here]( https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#use-valueprovider-in-your-pipeline-options)).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] ~Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~
 - [ ] ~Update `CHANGES.md` with noteworthy changes~.
 - [x] ~If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf)~.

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
This looks good/seems reasonable to me, but I'm not particularly well versed in how value providers are supposed to be used or if switching to them can break anything else - @johnjcasey could you take a look?

**Comment by johnjcasey** [comment]
Do we need valueproviders? My understanding is that they were only necessary for classic templates, and that new templates would be flextemplates

**Comment by robertwb** [comment]
I don't think we should proliferate the use of ValueProviders. People can use FlexTemplates instead.

**Comment by johnjcasey** [comment]
> We have a couple of Legacy/Classic templates for Spanner [1]. I agree on new templates being Flex, that's a route we want to pursue, including migrating classic to Flex when feasible. With this change in specific, we have some inheritance from Beam that requires some rework, so I am trying to keep it consistent.
> 
> Not changing to a ValueProvider would mean that we can only configure a subset of the parameters (or at this time, all but one).
> 
> [1] https://github.com/GoogleCloudPlatform/DataflowTemplates/tree/main/v1/src/main/java/com/google/cloud/teleport/spanner

got it. If we are already using this for classic templates, we should keep it consistent

**Pull request merged**
