### PR TITLE
Drops usage of setWindowingStrategyInternal in favour of direct use of WindowFn

### LINKED ISSUE #21690: Exception from ElasticSearch Write Module in DataFlow
I am seeing the following exception being thrown from the ElasticSearch Write module when running my streaming pipeline from Google DataFlow. I am using Apache Beam 2.39.0. I hope someone will be able to help me or tell me if this is a bug. Thanks a lot.

 
```

2022-06-02T02:21:07.023945713ZError message from worker: java.lang.ClassCastException: class org.apache.beam.sdk.transforms.windowing.GlobalWindow
cannot be cast to class org.apache.beam.sdk.transforms.windowing.IntervalWindow (org.apache.beam.sdk.transforms.windowing.GlobalWindow
and org.apache.beam.sdk.transforms.windowing.IntervalWindow are in unnamed module of loader 'app') org.apache.beam.sdk.transforms.windowing.IntervalWindow$IntervalWindowCoder.registerByteSizeObserver(IntervalWindow.java:142)
org.apache.beam.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:209) org.apache.beam.sdk.coders.IterableLikeCoder.registerByteSizeObserver(IterableLikeCoder.java:59)
org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:640)
org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:558)
org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:403)
org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:128)
org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:67)
org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:251)
org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:85)
org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnFinishBundleArgumentProvider$Context.output(SimpleDoFnRunner.java:309)
org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnFinishBundleArgumentProvider$Context.output(SimpleDoFnRunner.java:304)
org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO$BulkIO$BulkIOBaseFn$FinishBundleContextAdapter.output(ElasticsearchIO.java:2415)
org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO$BulkIO$BulkIOBaseFn.flushAndOutputResults(ElasticsearchIO.java:2422)
org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO$BulkIO$BulkIOBaseFn.finishBundle(ElasticsearchIO.java:2382)
```

Imported from Jira [BEAM-14551](https://issues.apache.org/jira/browse/BEAM-14551). Original Jira may contain additional context.
Reported by: Declan.

### PR DESCRIPTION
**Pull request by egalpin**
Fixes #21690.  Rather than using `setWindowingStrategyInternal`, use the more common `Window.into` with captured WindowFn from input PCollection.  This is an alternative to https://github.com/apache/beam/pull/21884

I validated in Dataflow where an upgrade to 2.39.0 resulted in the exact behaviour described in #21690, then upgrading the pipeline to the version of code in this PR and the casting error no longer occurred.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by egalpin** [comment]
R: @steveniemitz

**Comment by egalpin** [comment]
Agreed @steveniemitz , I originally misunderstood `setWindowingStrategyInternal` to be exactly what you described.  The slightly longer form version that I believe works is:

```java
WindowingStrategy<Document, ?> originalStrategy =
      (WindowingStrategy<Document, ?>) input.getWindowingStrategy();
 
...     
 
input.apply(
    Window
        .into(originalStrategy.getWindowFn())
        .triggering(originalStrategy.getTrigger())
        .withAllowedLateness(originalStrategy.getAllowedLateness()))

```

**Comment by kennknowles** [comment]
Which is the test that exposed the problem?

**Comment by egalpin** [comment]
@kennknowles the unfortunate part is I haven't been able to reproduce the issue in https://github.com/apache/beam/issues/21690 via unit tests.  I tried creating a windowed PCollection as input to Elasticsearch#Write, but it succeeded using 2.39.0 despite the failures while running in dataflow.

**Comment by kennknowles** [comment]
Does the same pipeline behave differently on Dataflow and other runners? That would be a pretty interesting thing to dig in to.

**Comment by egalpin** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Yea. I commented on https://github.com/apache/beam/pull/21740 and I'm confirming a revert now.

**Comment by kennknowles** [comment]
Our policy is ambiguous. I would _love_ for us to be stable enough that we can have a "don't merge when master is red" policy but these days we have too many flakes. In this case it is pretty clear that that signal is irrelevant. Really those tests shouldn't even have been run on your PR. I'm working on splitting up our signals so we don't run "all java tests" just because an IO was modified.

**Comment by kennknowles** [comment]
Based on what failed, I am going to say we merge this so it can go for a cherrypick.

**Pull request merged**
