### PR TITLE
[runners-spark] Do not set accTimestamp to null in SparkCombineFn (#28256)

### LINKED ISSUE #28256: [Failing Test]: Various TPC-DS queries throw NPEs using SparkRunner
### What happened?

Various TPC-DS queries started throwing NPEs with the SparkRunner some while back (see [here](http://metrics.beam.apache.org/d/tkqc0AdGk2/tpc-ds-spark-classic-new-sql?orgId=1&from=1689370909359&to=1690703369717)):

```
java.lang.NullPointerException
        at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
        at org.apache.beam.sdk.util.WindowedValue$TimestampedWindowedValue.<init>(WindowedValue.java:312)
        at org.apache.beam.sdk.util.WindowedValue$TimestampedValueInGlobalWindow.<init>(WindowedValue.java:329)
        at org.apache.beam.sdk.util.WindowedValue.of(WindowedValue.java:95)
```

Without looking further into the underlying root cause, this seems to be related to #27617.

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by je-ik**
Fixes #28256

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Spark Runner Nexmark Tests

**Comment by aromanenko-dev** [comment]
CC: @mosche @echauchot

**Comment by je-ik** [comment]
I'm not convinced this fix is 100% correct. I'd need an instance of a failing job to see what exactly causes the timestamp to be `null`.

**Comment by je-ik** [comment]
@aromanenko-dev I think I have the complete understanding. The condition in the assignment was wrong (don't have any clue how it was reasoned), the problem is that it was hidden, because until there was at least one call to `add` to the accumulator (which is nearly always the case), the timestamp was overwritten.

The bug manifested itself under the following conditions:
 a) Combine.withHotKeyFanout, because that merges accumulators without any elements being added (in the postHotFanoutCombine phase)
 b) TimestampCombiner.EARLIEST, because that can create accumulator timestamps of `BoundedWindow.TIMESTAMP_MIN_VALUE`.
 
Both conditions are satisfied in the case of query 3 in TPC-DS.

**Comment by je-ik** [comment]
Run Spark Runner Nexmark Tests

**Comment by je-ik** [comment]
Run Spark Runner Tpcds Tests

**Comment by je-ik** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark Runner Tpcds Tests

**Review by aromanenko-dev — APPROVED** [review]
Great, LGTM, thanks a lot! It sounds reasonable for me

> The condition in the assignment was wrong (don't have any clue how it was reasoned)

=) It was added 4+ years ago...

> The combination is somewhat niche, which is why it was not caught by VR tests. We can add a VR test for this, but I think that the bug was so specific, that it makes little sense.

Actually, according to TPC-DS Grafana dashboard, it caused a lot of queries failed without catching it with VR tests, that worried me. TBH, I didn't see if any of users were affected (mostly because I guess SparkRunner is not so popular now) but it would be great to add any kind of regression test of this if possible.

Let's just wait for TPC-DS job results before merging.

**Comment by aromanenko-dev** [comment]
Run Spark Runner Tpcds Tests

**Comment by je-ik** [comment]
Added the test, it is surely better to have a test proving the fix, though in this case it is only "the code does not contain this bug". Nevertheless the line of thinking that introduced in could in theory reappear. :+1:

**Comment by je-ik** [comment]
Run Spark Runner Tpcds Tests

**Comment by je-ik** [comment]
Run Java PreCommit

**Comment by je-ik** [comment]
Run Spark ValidatesRunner

**Pull request merged**
