### PR TITLE
One more TaggedOutput name change.

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by robertwb** [comment]
Thanks. I think you just set a record for speed-of-review :). Will merge once the light is green.

**Comment by chamikaramj** [comment]
:) (probably number of lines should be included in that record.)

**Comment by robertwb** [comment]
The failure is in Apache Beam :: Runners :: Spark, Python is all happy.

**Pull request closed without merging**
