### PR TITLE
[BEAM-3968] Skip IT tests in PreCommit tests

### PR DESCRIPTION
**Pull request by echauchot**
These IT tests are still run in PostCommit. 
I could have just removed `jenkins-precommit` profile from the executed profiles but in case this profile gets bigger in the future than just configuring IT tests it would lead to dysfunctions.
I preferred to overload the profile setting with a system property

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @tgroh Might be relevant to any investigation into WordCount failures.

**Comment by echauchot** [comment]
@kennknowles yes totally agree. I think part of the definition of integration tests is that they use external services. That is why I skipped all IT tests in that PR.

**Comment by echauchot** [comment]
I have created https://issues.apache.org/jira/browse/BEAM-3968 to track this and referenced the ticket in PR and commit

**Comment by echauchot** [comment]
if it is ok for you guys, I'll merge the PR

**Comment by echauchot** [comment]
preCommit Maven Install

**Comment by echauchot** [comment]
beam_PreCommit_Java_MavenInstall

**Comment by echauchot** [comment]
preCommit Maven Install

**Comment by echauchot** [comment]
Run preCommit Maven Install

**Comment by echauchot** [comment]
retest this please

**Comment by tgroh** [comment]
run java precommit

**Comment by echauchot** [comment]
@tgroh sure, dataflow IT tests need to pass. But this PR has a larger scope than that. To explain a little more my previous comment: IT tests use external services so, IHMO tests that use external services should not be part of preCommit tests but should be part of postCommit tests only.

**Pull request closed without merging**
