### PR TITLE
[BEAM-4496] Fix #2 for branch fetch failure on job_PostCommit_Website_Publish

### PR DESCRIPTION
**Pull request by alanmyrvold**
Failures in job_PostCommit_Website_Publish  still, 

Like https://builds.apache.org/job/beam_PostCommit_Website_Publish/42
05:01:04 FAILURE: Build failed with an exception.
05:01:04 
05:01:04 * Where:
05:01:04 Build file '/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Website_Publish/src/website/build.gradle' line: 129
05:01:04 
05:01:04 * What went wrong:
05:01:04 Execution failed for task ':beam-website:commitWebsite'.
05:01:04 > org.eclipse.jgit.api.errors.RefNotFoundException: Ref asf-site cannot be resolved
05:01:04 

And (to test this) fix up failures because 2.6.0 is in archives.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by alanmyrvold** [comment]
Run Seed Job

**Comment by alanmyrvold** [comment]
Run Website Publish

**Comment by alanmyrvold** [comment]
Run Website Publish

**Comment by alanmyrvold** [comment]
+R: @swegner PTAL?

**Comment by swegner** [comment]
Generally looks good; I submitted a patch to make the variable read from a property from the command-line: https://github.com/alanmyrvold/beam/pull/3

**Pull request merged**
