### PR TITLE
[BEAM-6766] Metadata file implementation for Sort Merge Bucket source/sink

### PR DESCRIPTION
**Pull request by ClaireMcGinty**
This PR is a small, discrete chunk of the Sort-Merge Bucket algorithm implementation ([design doc](https://docs.google.com/document/d/1AQlonN8t4YJrARcWzepyP7mWHTxHAd6WIECwk1s3LQQ/edit?usp=sharing)), extracted into a smaller PR for easier reviewing as suggested [in the JIRA ticket](https://issues.apache.org/jira/browse/BEAM-6766). It contains a JSON-serializable `BucketMetadata` abstract class and specific implementations for JSON, Avro, and TensorFlow (`org.tensorflow.example.Example`) collections. The intention here is that during an SMB write, a `metadata.json` file will be written alongside the bucketed record files, and read again at join time to ensure compatibility, reconstruct key coders, etc.

CC @kennknowles @nevillelyh @reuvenlax @kanterov 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by kanterov** [comment]
What do you think about having a design doc for the metadata format and discussing it on dev@? Not saying that there is anything wrong, but it would be a good way to collect feedback before being invested in the approach, you can find inspiration and template on [desing-documents].

[desing-documents]: https://beam.apache.org/contribute/design-documents/

**Comment by kanterov** [comment]
Something you might find useful is the design proposal for [cost-estimation].

[cost-estimation]: https://lists.apache.org/thread.html/5f1dcd775daee55a8005db9ae87898a8e5efaee140a89417703dc823@%3Cdev.beam.apache.org%3E

**Comment by aaltay** [comment]
@kanterov are you planning to review this change?

**Comment by kanterov** [comment]
@aaltay no, I want to get feedback from dev@ before we proceed

**Comment by aaltay** [comment]
That makes sense. I pinged the thread today, hopefully there will be some feedback.

**Comment by tvalentyn** [comment]
Please say "PTAL" and/or reach out to reviewers of this change (@kanterov) once this PR is ready for review. Thank you.

**Comment by ClaireMcGinty** [comment]
@tvalentyn , @kanterov , PTAL?

**Comment by kennknowles** [comment]
Ping. Just back from vacation and noticed the email thread. @kanterov or @tvalentyn if you don't have time now can you comment so we know? or recommend someone?

**Comment by tvalentyn** [comment]
I am not sufficiently familiar with these bits of code, so I'd prefer to find another reviewer to merge this faster. My earlier comment was to make sure that this PR receives attention once ready.

**Comment by kanterov** [comment]
@kennknowles we are having discussions (internally) on a few changes to the structure of metadata

**Pull request closed without merging**
