### PR TITLE
[BEAM-11419] Update Flink supported versions in the website

### PR DESCRIPTION
**Pull request by iemejia**
R: @dmvk

### CODE REVIEW

**Review by ibzib — CHANGES_REQUESTED** [review]
Since Python was not updated along with Java, we will need to document that Flink 1.11 and 1.12 are not supported in Beam Python yet (at least not in a way that works with the instructions).

**Comment by iemejia** [comment]
Oh I was not aware of that :S why did this not happen? Now I understand why we did not have the docker images too.

**Comment by ibzib** [comment]
> Oh I was not aware of that :S why did this not happen? Now I understand why we did not have the docker images too.

There are all these manual updates we must have just neglected to do when adding new Flink versions. Part of the problem is there are too many sources of truth for the Flink versions. Having fewer sources of truth would make it easier to update properly. https://issues.apache.org/jira/browse/BEAM-9541

**Comment by iemejia** [comment]
I added a small note WDYT @ibzib ?

**Review by ibzib — APPROVED** [review]
LGTM

**Pull request merged**
