### PR TITLE
[BEAM-12342] Upgrade Spark 2 to version 2.4.8

### PR DESCRIPTION
**Pull request by iemejia**
R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Review by ibzib — APPROVED** [review]
LGTM!

**Pull request merged**
