### PR TITLE
[BEAM-4070]: Make cython: profile=False by default

### PR DESCRIPTION
**Pull request by boyuanzz**
Make cython profiling disabled by default
[BEAM-4070](https://issues.apache.org/jira/browse/BEAM-4070)

R: @aaltay

### CODE REVIEW

**Comment by aaltay** [comment]
Thank you @boyuanzz, could you look at the failing tests? Could you also run a simple benchmark, curious if we can get improvements this way?

@robertwb is there a reason to keep these profiles in. (Based on http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html I do not think so.)

**Comment by robertwb** [comment]
The motivation to keep these profiles is so that one can use standard tools
like cProfile to understand the code. I would disable them only for
modules/functions where they can be shown to be non-negligable.

**Comment by boyuanzz** [comment]
retest this please

**Comment by boyuanzz** [comment]
retest this please

**Comment by aaltay** [comment]
> At least, I prefer to disable profiling in DataflowDistributionCounter since I'll call it very often in new features. How about just disable profiling in distribution counter first and leave others into further discussion?

I disagree with this. We can either look at macro benchmarks, and understand the impact first and make a global decision or postpone this decision. I would not make a decision based on the currently available information.

**Pull request closed without merging**
