### PR TITLE
[BEAM-7993] Run Portable PreCommit tests sequentially

### PR DESCRIPTION
**Pull request by markflyhigh**
Let's run portable precommit tests sequentially to see if the ImportError is caused by parallel execution.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by markflyhigh** [comment]
Run Seed Job

**Comment by markflyhigh** [comment]
Run Seed Job

**Comment by markflyhigh** [comment]
Run Portable_Python PreCommit

**Comment by markflyhigh** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
Failure with py3 still happens. Error is the same.
example: https://builds.apache.org/job/beam_PreCommit_Portable_Python_Phrase/372/
I don't think this change run preCommit test sequentially. If I check task execution timeline from Gradle, all tasks which precommit tests depend on are running parallel, same as before.

**Comment by markflyhigh** [comment]
Thank you @Hannah-Jiang ! Actually this PR touches `groovy` file so we need to run seed job before trigger the test job to have Jenkins pickup those configs first. However, the configs can also be overwritten by other seed jobs. 

Two failure examples you mentioned in https://github.com/apache/beam/pull/9460#issuecomment-526868076 seems still use old configs. New job should look like https://builds.apache.org/job/beam_PreCommit_Portable_Python_Phrase/362/

**Comment by markflyhigh** [comment]
Run Seed Job

**Comment by Hannah-Jiang** [comment]
Thanks @markflyhigh. I see, that's why log still shows it is running parallel, the job would be overwritten. I will test my PR after this PR is merged.

**Comment by markflyhigh** [comment]
Run Portable_Python PreCommit

**Comment by Hannah-Jiang** [comment]
This looks working! I tested with my PR and the test passed twice(100%). Can we merge it?

**Comment by markflyhigh** [comment]
Test is passing. I'll merge it.

**Pull request merged**
