### PR TITLE
Update snippets to fix pickling and clarify encoding issues

### PR DESCRIPTION
**Pull request by charlesccychen**
This change fixes some pickling issues in the snippet tests.  This change also clarifies the undefined behavior of explicitly using incorrect type information.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @robertwb

**Comment by charlesccychen** [comment]
Rebased to head and tests pass; this is ready for review.

**Comment by charlesccychen** [comment]
Note also that a related documentation update is also ready for review: https://github.com/apache/beam-site/pull/385.

**Comment by robertwb** [comment]
The loss of locality is unfortunate, but seems necessary. LGTM.

**Pull request merged**
