### PR TITLE
[BEAM-2080]: Add a custom enforcer rule to check for banned classes.

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
- Add a custom rule to catch banned classes which can be specified using full path like `org/apache/beam/Foo.class` or using wildcards like `org/apache/maven/**` 
- Disable enforcer plugin in parent pom to avoid circular dependency issues with the custom rule
- Move enforcer executions to `pluginManagement` and explicitly include them in `sdks`, `examples` and `runners`.

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @davorbonaci . Feel free to add other maven experts in the team for review if needed.

**Comment by jbonofre** [comment]
Thanks for the contribution ! Can you provide a quick abstract about the enforcer rule ?

**Comment by vikkyrk** [comment]
@jbonofre The enforcer rule that I have added in this PR basically looks at all the classes within the artifacts generated by Beam (like sdks-core-*.jar, examples-*.jar etc.) and makes sure that we do not included unintended classes like `com.google.guava` or `org.apache.maven` etc. (configurable from the pom file). This is particularly useful for when using shade plugin to build a uber bundled jar but accidentally forget to shade libraries like guava.

**Comment by vikkyrk** [comment]
Retest this please

**Comment by vikkyrk** [comment]
Retest this please

**Comment by kennknowles** [comment]
Since development here, we've started migrating to Gradle. This same functionality might be handy in a Gradle task of some sort. Are you planning on working on this any more?

**Pull request closed without merging**
