### PR TITLE
Fix compilation and test issues

### PR DESCRIPTION
**Pull request by reuvenlax**
Fix compilation and broken guava import. Disable broken test.

### CODE REVIEW

**Comment by reuvenlax** [comment]
@ryan-williams

**Comment by ryan-williams** [comment]
lgtm. Up to you to wait for precommit to pass or just merge 😄 

thanks for quick fix

**Comment by reuvenlax** [comment]
I'll wait for precommit

**Comment by reuvenlax** [comment]
Run Flink ValidatesRunner

**Pull request merged**
