### PR TITLE
Use beam-master-$DATE pattern for default Dataflow containers in unre…

### PR DESCRIPTION
**Pull request by tvalentyn**
…leased BEAM SDK.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @aaltay

**Comment by aaltay** [comment]
Looks good. Do we already have a containers ready with the updated names? I would recommend running post commit tests before merging.

**Comment by tvalentyn** [comment]
Yes, we have containers.

**Comment by tvalentyn** [comment]
Run Python Postcommit

**Comment by tvalentyn** [comment]
Thanks for review and suggestions, @aaltay .

**Comment by aaltay** [comment]
Do you know why the tests are failing?

**Comment by tvalentyn** [comment]
I don't. Jenkins UI takes forever to load right now, I suspect test infrastructure is not doing well.

**Comment by tvalentyn** [comment]
There was a lint complaint. I created this change in the UI and did not notice some line exceeded 80 characters.

**Comment by tvalentyn** [comment]
Run Python Postcommit

**Comment by aaltay** [comment]
LGTM, thank you.

**Pull request merged**
