### PR TITLE
Beam-2461 Ln function

### PR DESCRIPTION
**Pull request by app-tarush**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by app-tarush** [comment]
@takidau Please review this PR #3387. This also includes implementations of other functions log10 and exp.

**Comment by takidau** [comment]
Apologies for the delay. Some fires elsewhere came up and then I'm in training all day today and tomorrow. Will try to get this and other PRs taken care of later today if possible. Thanks for your patience.

**Comment by app-tarush** [comment]
@takidau @xumingming No worries, actually I have clubbed this PR with another PR #3400.

**Comment by takidau** [comment]
No problem, please close this one then.

**Comment by app-tarush** [comment]
Closing this PR as this pr has been merged with PR #3400

**Pull request closed without merging**
