### PR TITLE
[Website] Update pages with table content overflow

### LINKED ISSUE #23460: [Bug]: tables content overflow
### What happened?

Steps to reproduce:

1. [Open Beam ZetaSQL lexical structure page](https://beam.apache.org/documentation/dsls/sql/zetasql/data-types/) in the browser
2. Reduce the width of the page to 1080px
3. Scroll to the section Data type properties
4. Scroll down that the right menu overlaps the table

Same issue on pages:
- https://beam.apache.org/community/presentation-materials/index.html
- https://beam.apache.org/documentation/dsls/sql/zetasql/operators/index.html
- https://beam.apache.org/documentation/dsls/sql/zetasql/lexical/index.html

Actual result: Right nav menu overlaps the table
Expected result: Right nav menu doesn't overlap the table

before_table_1
before_table_2
before_table_3

### Issue Priority

Priority: 3

### Issue Component

Component: website

### PR DESCRIPTION
**Pull request by bullet03**
NB!!! Please merge this PR first before https://github.com/apache/beam/pull/24195
Resolves #23460
- update pages with table content overflow, add scroll.
https://beam.apache.org/documentation/dsls/sql/zetasql/data-types/
https://beam.apache.org/documentation/dsls/sql/zetasql/query-syntax/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/operators/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/lexical/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/lexical-structure/
https://beam.apache.org/community/presentation-materials/index.html
https://beam.apache.org/community/contact-us/index.html
------------------------
before:
before_table_1
before_table_2
before_table_3
after:
after_table_1
after_table_2
after_table_3
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, help with review of current PR?

**Review by pcoet — APPROVED** [review]
Nice fixes. Thanks!

**Comment by bullet03** [comment]
@aromanenko-dev, could you kindly help with merge?

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by bullet03** [comment]
> LGTM

Thank you!

**Comment by bullet03** [comment]
@aromanenko-dev, I'm really sorry for bothering. Current PR was merged 5 dayes ago, but changes are not present on the prod. Could you, please, help me with that?

**Comment by aromanenko-dev** [comment]
@bullet03 No worries, thanks for alert. It looks that it's again related to an issue with running [beam_PostCommit_Website_Publish](https://ci-beam.apache.org/job/beam_PostCommit_Website_Publish/) job because of  not available nodes with a proper label.

**Comment by bullet03** [comment]
> @bullet03 It should be fixed now - Jenkins job works as expected. Could you check your changes, please?

It works fine! Thank you very much for the assistance.

**Pull request merged**
