### PR TITLE
Revert "Remove unused is_pair_like hack."

### PR DESCRIPTION
**Pull request by angoenka**
Reverts apache/beam#6956

This breaks dataflow.

### CODE REVIEW

**Comment by aaltay** [comment]
run python postcommmit

**Comment by angoenka** [comment]
Sure, Also running an internal test to make sure this works.

**Comment by aaltay** [comment]
Run Python PostCommit

**Comment by angoenka** [comment]
Post commit is failing because of unrelated hdfs issue.
Committing the change.

**Pull request merged**
