### PR TITLE
[Dataflow Streaming] Add workToken to thread name for easier debugging

### PR DESCRIPTION
**Pull request by arunpandianp**
cc: @scwhittle

### CODE REVIEW

**Comment by arunpandianp** [comment]
R: @m-trieu

**Review by m-trieu — APPROVED** [review]
Lgtm

**Comment by m-trieu** [comment]
Do we need cache token as well? If yes can log 'Work.id()'

**Comment by arunpandianp** [comment]
R: @lostluck

**Review by lostluck — APPROVED** [review]

**Pull request merged**
