### PR TITLE
[BEAM-3581] Make sure calcite gets an appropriate charset PRIOR to an…

### PR DESCRIPTION
**Pull request by dkulp**
[BEAM-3581] Make sure calcite gets an appropriate charset PRIOR to any static intializers

### CODE REVIEW

**Comment by kennknowles** [comment]
Please wait to hear from @akedin who has been looking at this too. This is not just a test problem, but something that can certainly hit our users.

**Comment by kennknowles** [comment]
We actually don't want to mask this by setting the property in our tests.

**Comment by akedin** [comment]
@kennknowles I am not sure if there's a better workaround for this.

Current developments from Jira:

@dkulp found that simply referencing `SqlTypeName.VARCHAR` in the test reproduces the issue. 
This seems to be because `SqlTypeName` has a static field that is [initialized with help of `Util` class](https://github.com/apache/calcite/blob/cb8376b13ad50003134e398a87161bec68908606/core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java#L138), which in turn has a static member that [will initialize SaffronProperties](https://github.com/apache/calcite/blob/cb8376b13ad50003134e398a87161bec68908606/core/src/main/java/org/apache/calcite/util/Util.java#L142) if it wasn't initialized before. 

So it looks like we need to override the saffron properties before we use even the `SqlTypeName` anywhere. We can do it either by providing a `saffron.properties` file in the working dir, or overriding the system properties.

**Comment by akedin** [comment]
So suggestion is to go with this implementation and document it.

Later we should upgrade to Calcite version that loads the `saffron.properties` from resources and use that to initialize the default charset instead of system properties.

**Comment by dkulp** [comment]
Rebased on latest master, should apply cleanly.

**Comment by kennknowles** [comment]
retest this please

**Comment by akedin** [comment]
run java gradle precommit

**Comment by akedin** [comment]
tis green! (aside from goPreCommit)

**Pull request merged**
