### PR TITLE
Fix FlatMapTuple typehint bug

### PR DESCRIPTION
**Pull request by hjtran**
(fixes https://github.com/apache/beam/issues/33014)
`FlatMapTuple` throws false positive type hint errors in certain situations, e.g.
```python
 def identity(x: Tuple[str, int]) -> Tuple[str, int]:
    return x
  with beam.Pipeline() as p:
    with beam.Pipeline() as p:
      A = (p
                | "Generate input" >> beam.Create([('P1', [2])])
                | "Flat" >> beam.FlatMapTuple(lambda k, vs: [(k, v) for v in vs])
                | "Identity" >> beam.Map(identity))
```
raises the following exception:
```
E         apache_beam.typehints.decorators.TypeCheckError: The transform 'Identity' requires PCollections of type 'Tuple[<class 'str'>, <class 'int'>]' but was applied to a PCollection of type 'Tuple[<class 'type'>, <class 'int'>]' (produced by the transform 'Flat').
```

This is a downstream effect of a bug in the `trivial_inference.py` code. I couldn't really figure out the underlying bug but we can work around it by adding a `tuple` coercion before unpacking in `FlatMapTuple`. 

I've created a spinoff issue for the underlying inference issue: https://github.com/apache/beam/issues/33308

### CODE REVIEW

**Comment by hjtran** [comment]
R: @jrmccluskey

**Review by jrmccluskey — APPROVED** [review]
LGTM mod the linting fixes

`str` getting turned into a generic type is interesting, I will see what I can dig up next week as far as the underlying bug

**Comment by hjtran** [comment]
I can't seem to get this isorted correctly. It's not a part of the pre-commit hook and the isort version isn't compatible with my py3.11. @jrmccluskey would you mind doing it before merging if it's easy for you env?

**Comment by liferoad** [comment]
Have you tried to manually change the import orders?

```
2024-12-06T18:03:21.6023142Z ERROR: /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/trivial_inference_test.py Imports are incorrectly sorted.
2024-12-06T18:03:21.6025546Z Command exited with non-zero status 1
2024-12-06T18:03:21.6026715Z 613.13user 32.61system 1:24.90elapsed 760%CPU (0avgtext+0avgdata 874112maxresident)k
2024-12-06T18:03:21.6028325Z 10928inputs+1120outputs (8major+2025317minor)pagefaults 0swaps
2024-12-06T18:03:21.6030229Z --- /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/trivial_inference_test.py:before	2024-12-06 17:57:32.050442
2024-12-06T18:03:21.6033655Z +++ /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/trivial_inference_test.py:after	2024-12-06 18:03:19.361962
2024-12-06T18:03:21.6035359Z @@ -21,8 +21,8 @@
2024-12-06T18:03:21.6035826Z  
2024-12-06T18:03:21.6036256Z  import types
2024-12-06T18:03:21.6036738Z  import unittest
2024-12-06T18:03:21.6037179Z +
2024-12-06T18:03:21.6037906Z  import apache_beam as beam
2024-12-06T18:03:21.6038613Z -
2024-12-06T18:03:21.6039092Z  from apache_beam.typehints import row_type
2024-12-06T18:03:21.6039735Z  from apache_beam.typehints import trivial_inference
2024-12-06T18:03:21.6040397Z  from apache_beam.typehints import typehints
2024-12-06T18:03:21.6041736Z ERROR: /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/typed_pipeline_test.py Imports are incorrectly sorted.
2024-12-06T18:03:21.6043773Z --- /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/typed_pipeline_test.py:before	2024-12-06 17:57:32.054441
2024-12-06T18:03:21.6045808Z +++ /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/apache_beam/typehints/typed_pipeline_test.py:after	2024-12-06 18:03:19.484289
2024-12-06T18:03:21.6047036Z @@ -22,8 +22,8 @@
2024-12-06T18:03:21.6047434Z  import typing
2024-12-06T18:03:21.6047893Z  import unittest
2024-12-06T18:03:21.6048591Z  from typing import Tuple
2024-12-06T18:03:21.6049002Z +
2024-12-06T18:03:21.6049370Z  import apache_beam as beam
2024-12-06T18:03:21.6049765Z -
2024-12-06T18:03:21.6050178Z  from apache_beam import pvalue
2024-12-06T18:03:21.6050718Z  from apache_beam import typehints
2024-12-06T18:03:21.6051435Z  from apache_beam.options.pipeline_options import OptionsContext
2024-12-06T18:03:21.6053182Z lint: exit 1 (84.91 seconds) /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python> time /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/scripts/run_pylint.sh pid=1228
2024-12-06T18:03:21.6055705Z lint: commands_post[0]> bash /runner/_work/beam/beam/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/scripts/run_tox_cleanup.sh
```

**Pull request merged**
