### PR TITLE
[BEAM-789] Review python sdk dependencies

### PR DESCRIPTION
**Pull request by tibkiss**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @aaltay PTAL

**Comment by aaltay** [comment]
LGTM.

I ran a few tests and have not seen an issue. One thing I cannot be sure is, if one of our dependencies depends on one of these and they do not install it by default. Far fetched but possible, we need to monitor post commit tests closely after this is merged.

**Comment by tibkiss** [comment]
@aaltay : Thanks for the quick response!

I'm wondering if .tux directory is intentionally located under `beam/sdks/python`? 
If it would reside in `sdks/python/target` then maven could clean it up.

**Comment by davorbonaci** [comment]
It would be _terrific_ if all build-generated files are under `target/` directory.

**Comment by tibkiss** [comment]
@davorbonaci : Thanks for the insights, will create a separate JIRA for this work item soon.

**Comment by aaltay** [comment]
Thank you @tibkiss. The .tox directory was not intentionally chosen, we can move it under target, please make sure everything else still works after the move.

**Comment by tibkiss** [comment]
Thanks for merging @aaltay, will create a separate issue about .tox relocation shortly.

**Pull request closed without merging**
