### PR TITLE
[BEAM-2006] window support 

### PR DESCRIPTION
**Pull request by XuMingmin**
Add support for aggregation: global, `HOP`, `TUMBLE`, `SESSION`, only aggregation function `COUNT`

Some other changes:
1. upgrade to Apache Calcite 1.12.0;
2. support data type TIMESTAMP, TIME;

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
LGTM (superficial).

@xumingming, would you also like to take a look?

**Comment by xumingming** [comment]
LGTM too. Great work!

**Comment by XuMingmin** [comment]
conflict resolved. @davorbonaci can you help to merge it?

**Comment by XuMingmin** [comment]
retest this please

**Comment by dhalperi** [comment]
Does not rebase cleanly on `DSL-SQL`. Not sure how to merge.

**Comment by XuMingmin** [comment]
retest this please

**Comment by XuMingmin** [comment]
retest this please

**Comment by dhalperi** [comment]
2017-05-10T06:30:05.953 [INFO] -------------------------------------------------------------
2017-05-10T06:30:05.953 [ERROR] COMPILATION ERROR : 
2017-05-10T06:30:05.953 [INFO] -------------------------------------------------------------
2017-05-10T06:30:05.953 [ERROR] /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_MavenInstall/dsls/sql/src/test/java/org/apache/beam/dsls/sql/schema/text/BeamTextCSVTableTest.java:[177,12] constructor BeamSQLRow in class org.apache.beam.dsls.sql.schema.BeamSQLRow cannot be applied to given types;
  required: org.apache.beam.dsls.sql.schema.BeamSQLRecordType
  found: org.apache.beam.dsls.sql.schema.BeamSQLRecordType,java.util.List<java.lang.Object>
  reason: actual and formal argument lists differ in length
2017-05-10T06:30:05.954 [INFO] 1 error

**Comment by XuMingmin** [comment]
@dhalperi seems new conflict after PR 2942 is merged. 

I've created a new one PR 3039 to replace this, with a clear base. Will let you know when Jenkins finishes.

**Comment by XuMingmin** [comment]
close it and use PR 3039 instead

**Pull request closed without merging**
