### PR TITLE
[BEAM-2610] upgrade to version 2.2.0

### PR DESCRIPTION
**Pull request by XuMingmin**
As described in task [BEAM-2610](https://issues.apache.org/jira/browse/BEAM-2610), this is the first PR to do the job. Feel free to merge it if no mis-operation during creating the PR as any issues are supposed to be fixed in the second PR.

Btw, the failure is expected as dsl/sql is still using `2.1.0-SNAPSHOT`, and be fixed in PR 2

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @takidau @xumingming 
CC: @jbonofre @davorbonaci

**Comment by takidau** [comment]
Can you please stage the second PR as a branch that builds on this one first? I don't want the branch to be left in a broken state for too long.

**Comment by XuMingmin** [comment]
I create a draft PR #3554 there, as far as I know that's just a simple version change.

**Comment by takidau** [comment]
Thanks, merging.

**Comment by takidau** [comment]
Merged.

**Comment by XuMingmin** [comment]
Thanks!

**Comment by XuMingmin** [comment]
@takidau I'm afraid the merge of this task has some issues, or maybe I'm using the wrong method. --I tried to create a pull request from DSL_SQL based on Master, in web page, and it's shown as 'Can’t automatically merge'. I see lots of files from master branch will be listed.

**Pull request closed without merging**
