### PR TITLE
Saved version numbers in variables to make it consistent with the dat…

### PR DESCRIPTION
**Pull request by huygaa11**
…aflow pom file.

DESCRIPTION HERE

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lukecwik** [comment]
Wouldn't you also want to make updates to the archetype pom.xml files wrt to archetype-packaging.version, maven-archetype-plugin.version, maven-invoker.version similar to what you did in https://github.com/GoogleCloudPlatform/DataflowJavaSDK/commit/ae3df14d89604a8852865372ea3009d1ce1f3caf

**Comment by huygaa11** [comment]
I will definitely do them. Just not enough time during the summit here. :(

**Comment by aaltay** [comment]
@huygaa11 any updates on this one?

**Comment by robertwb** [comment]
I'm going to close this as obsolete due to the gradle move. Feel free to re-open (or create a gradle-based PR) if needed.

**Pull request closed without merging**
