### PR TITLE
[BEAM-8481] Fix a race condition in proto stubs generation.

### PR DESCRIPTION
**Pull request by tvalentyn**
The `installGcpTest` task is installing SDK in developer mode (aka editable mode via `pip install -e`), which creates a race condition with the task  `:sdk:python:sdist`, because the order of execution is not established, and both tasks modify the SDK sources at proto stub generation step, see BEAM-8481 for pointers. 

This change establishes a depends-on relationship, which enforces that sdist must finish before installation. Installing SDK from a tarball would provide a better isolation and be closer to the typical installation scenario.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
R: @udim 
cc: @markflyhigh

**Comment by udim** [comment]
Opened https://issues.apache.org/jira/browse/BEAM-8966 for :sdks:python:test-suites:direct:py37:hdfsIntegrationTest failure

**Comment by udim** [comment]
There are other errors though which I haven't triaged, such as `beam-runners-flink-1.9-job-server-2.19.0-SNAPSHOT.jar not found`

**Comment by ibzib** [comment]
Filed and assigned self [BEAM-8968](https://issues.apache.org/jira/browse/BEAM-8968) for missing jar issue.

**Comment by tvalentyn** [comment]
Thanks, @ibzib  and @udim. Precommits have timeout after 3 hrs. Looking at https://builds.apache.org/job/beam_PreCommit_Python_Cron/, 1 in 10 precommit jobs times out, but most finish under an hour. Opened https://issues.apache.org/jira/browse/BEAM-8973.

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Another precommit error: https://issues.apache.org/jira/browse/BEAM-8977

**Comment by tvalentyn** [comment]
run python precommit

**Comment by tvalentyn** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
[BEAM-8979] Remove mypy-protobuf dependency

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
New errors: https://issues.apache.org/jira/browse/BEAM-8988. 
Overall, postcommits are running and no longer timing out. I suggest we merge this PR since it will help reduce flakiness, which in turn will help verify fixes for BEAM-8988. @udim could you please review and/or merge if that sounds good to you?

**Comment by tvalentyn** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Looked at this together with @ibzib. Portable postcommit errors are caused by this PR. Since this PR switches from installing Python SDK in developer mode to installing the SDK from a tarball, it changes the path on Jenkins workers where the SDK sources will be located after the installation. In particular, after installing the SDK from a tarball into a virtual environment, the SDK source files will be located in a location like `$path_to_virtual_env/lib/python2.7/site-packages/apache_beam/`. 
It appears that the default path for job service jar is defined by the location of SDK sources: https://github.com/apache/beam/blob/7346cf201e847fc7596389ff8406f8352859495e/sdks/python/apache_beam/utils/subprocess_server.py#L162. Therefore with this PR, Portable Flink Runner tests look for flink-job-server.jar in a different location and cannot find it.

The error can be reproed via: gradlew :sdks:python:test-suites:portable:py37:postCommitPy37

**Comment by ibzib** [comment]
Run Python 3.7 PostCommit

**Comment by ibzib** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Run Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python 3.5 Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run XVR_Flink PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.5 Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run XVR_Flink PostCommit

**Comment by tvalentyn** [comment]
PTAL @udim or @ibzib

**Comment by tvalentyn** [comment]
Thanks, @ibzib for the fix for BEAM-9070!

**Pull request merged**
