### PR TITLE
`COALESCE` should infer correct non-null return type

### PR DESCRIPTION
**Pull request by judahrand**
#19730

This is adding a test to demonstrate that the issue still exists and needs fixing. I'm yet to identify a fix.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by judahrand** [comment]
R: @damccorm 

I'm struggling to get the tests to run locally on an M1 MacBook so was hoping to be able to use the CI to demonstrate the issue. But it looks like the extensions unit tests don't run by default.

**Comment by damccorm** [comment]
From the conversation in https://issues.apache.org/jira/browse/BEAM-7610 and related PRs, this should have been fixed by https://github.com/apache/beam/pull/14146

@apilloud could you take a look at this one since you have more context here?

**Comment by judahrand** [comment]
> From the conversation in https://issues.apache.org/jira/browse/BEAM-7610 and related PRs, this should have been fixed by #14146
> 
> @apilloud could you take a look at this one since you have more context here?

It's an issue we're definitely having in Dataflow SQL. A query which looks roughly like this:

```
SELECT
    window_start,
    window_end,
    COALESCE(ARRAY_AGG(foo), []) AS data
FROM HOP(
       (SELECT * FROM pubsub.topic.`project_id`.`topic`),
       DESCRIPTOR(event_timestamp),
       "INTERVAL 5 MINUTE",
       "INTERVAL 15 MINUTE"
   ) as data
   GROUP BY window_start, window_end
```

results in an error downstream which says that Data Catalog does not support `NULLABLE ARRAYS`. This means that the output schema of the query must not be correctly handling the `COALESCE`.

**Comment by judahrand** [comment]
This is another important detail for our particular query: according to the ZetaSQL spec[1] a `NULL` array and an empty array are distinct and so our query should work.

[1] https://github.com/google/zetasql/blob/master/docs/data-types.md#nulls-and-the-array-type

**Comment by damccorm** [comment]
Sorry, I wasn't clear. I'm not making a claim about whether or not this is actively an issue; I was just saying that given the conversation around the calcite upgrade I'm surprised that it is still a problem. I would have expected that upgrade to fix the problem given my loose understanding of the issue

**Comment by damccorm** [comment]
Looks like Andrew is on vacation, @kileys could you weigh in here?

**Comment by apilloud** [comment]
Your new test is running in the SQL Precommit and passing: https://ci-beam.apache.org/job/beam_PreCommit_SQL_Commit/5807/testReport/org.apache.beam.sdk.extensions.sql.zetasql/ZetaSqlDialectSpecTest/testCoalesceNotNull/

Beam ZetaSQL has significant issues with null handling, so an issue like this existing wouldn't surprise me. I think you need a schema that supports nullable fields though? Try this:
`final Schema schema = Schema.builder().addNullableField("field1", FieldType.STRING).build();`

The latest release of Dataflow SQL is based on df6efe3644d08bda747d9d4434ab9e033073c8de (somewhere between v2.38.0 and v2.39.0), which is several months old so it is possible that it has been fixed since. I know #17387 is more recent, which fixes some null bugs. Possibly try rebasing on that commit?

**Comment by judahrand** [comment]
> This pull request has been marked as stale due to 60 days of inactivity. It will be closed in 1 week if no further activity occurs. If you think that’s incorrect or this pull request requires a review, please simply write any comment. If closed, you can revive the PR at any time and @mention a reviewer or discuss it on the [dev@beam.apache.org](mailto:dev@beam.apache.org) list. Thank you for your contributions.

I think this is still an issue.

**Pull request closed without merging**
