### PR TITLE
[BEAM-2021] Convert Coder into an Abstract Static Class

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles @dhalperi 

Will require a worker dance.

**Comment by dhalperi** [comment]
This LGTM

**Comment by tgroh** [comment]
Had to also update the CoderFactories to be able to resolve the parent Coder type.

**Comment by dhalperi** [comment]
Still LGTM

**Comment by tgroh** [comment]
Updated worker version for new worker that is compatible.

**Pull request closed without merging**
