### PR TITLE
Fix accidental rename of AwsModuleTest to AwsModuleAmazonSNSMock

### PR DESCRIPTION
**Pull request by jhalaria**
While working on https://github.com/apache/beam/commit/fb50ccdca728cd0c89cb8f0afb9847eaa9e0e882,
I accidentally renamed AwsModuleTest to AwsModuleAmazonSNSMock. I am undoing that change.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by jhalaria** [comment]
@iemejia - While looking at the merge to master, I noticed that I accidentally had modified these 2 files. I am undoing that change.

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by jhalaria** [comment]
@iemejia - I don't get any errors locally when i run 
```
./gradlew clean :beam-sdks-java-io-amazon-web-services:compileTestJava
```. locally.

**Comment by jhalaria** [comment]
While looking at the logs, I see that the build was successful but it fails with 
```
10:57:40 BUILD SUCCESSFUL in 20m 5s
10:57:40 811 actionable tasks: 806 executed, 5 from cache
10:57:40 
10:57:40 Publishing build scan...
10:57:41 https://gradle.com/s/ydwhlnaah4fw2
10:57:41 
10:57:42 Build step 'Invoke Gradle script' changed build result to SUCCESS
10:57:42 [Gradle] - Launching build.
10:57:42 FATAL: The Gradle wrapper has not been found in these directories: /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit
10:57:42 Build step 'Invoke Gradle script' marked build as failure
10:57:42 Recording test results
10:57:46 Setting status of c5d55697182459e8b0d19bcfa5d92fa2b3bd08f8 to FAILURE with url https://builds.apache.org/job/beam_PreCommit_Java_Commit/1088/ and message: 'FAILURE
10:57:46  '
10:57:46 Using context: Java ("Run Java PreCommit")
10:57:46 Finished: FAILURE
```

Looking at the build scan, I don't see any errors either
https://scans.gradle.com/s/ydwhlnaah4fw2/console-log#L1722

**Pull request merged**
