### PR TITLE
[BEAM-3480] Temporarily run PerfKit jobs on Jenkins on subset of workers

### PR DESCRIPTION
**Pull request by DariuszAniszewski**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
This PR is a walk-around related to [BEAM-3480](issues.apache.org/jira/browse/BEAM-3480) - it forces Jenkins to schedule PerfKit jobs on subset of workers on which there are no issues. **The actual problem still persists and should be solved.**
@chamikaramj PTAL, thanks.

**Comment by chamikaramj** [comment]
R: @alanmyrvold Alan, can you take a look ?

cc: @jasonkuster

**Comment by chamikaramj** [comment]
Is this for all Jenkins jobs ? If so this sounds like a serious issue and we should try to find the root cause instead of limiting the number of executors.

**Comment by DariuszAniszewski** [comment]
@chamikaramj  It's on all Jenkins jobs running PerfKit and I totally agree that root cause should be fixed. However in case issue is hard to fix or time-consuming this walk-around could be merged - it's up to you.

**Comment by chamikaramj** [comment]
I slightly misunderstood this PR and assumed this test to be updating the set of Jenkins executors that get considered by all tests. But looks like this will only affect PerfKit-based tests that are already heavily flaky due to BEAM-3480. I'm fine with getting this in till the underlying issue is resolved to make the tests blue.

@alanmyrvold WDYT ?

**Comment by alanmyrvold** [comment]
Instead of restricting the executor, can we try setting the perfkit temp_dir flag?

https://issues.apache.org/jira/browse/BEAM-3480?focusedCommentId=16344125&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16344125

**Comment by DariuszAniszewski** [comment]
@alanmyrvold @chamikaramj There is an option for pass tmp_dir indeed, you can see it in #4537.

But honestly it's just another walk-around for the main, unresolved, issue. And one more problem is that some workers are having different problem. Take a look on [build 85](https://builds.apache.org/view/A-D/view/Beam/job/beam_PerformanceTests_TextIOIT/85/console) of `beam_PerformanceTests_TextIOIT` - it's failing because it tries to install dependency that is not system-wide available.

**Comment by chamikaramj** [comment]
We can try to get #4537 in once it's ready.

Based on a quick Web search, the solution to dependency issue might be updating setuptools: https://github.com/ansible/ansible/issues/31741

**Comment by DariuszAniszewski** [comment]
@chamikaramj thanks for the hint, it seems to work fine as shown in [this build](https://builds.apache.org/job/beam_PerformanceTests_TextIOIT/97/console).

Therefore #4537 is ready to be merged as walkaround for permission issue.

This PR can be closed.

**Pull request closed without merging**
