### PR TITLE
Fix the test 'test_user_agent_passed' without skipping it

### PR DESCRIPTION
**Pull request by shunping**
* Here we skip the credential authentication, and
* we also mock gcp_bigquery so it won't raise an exception that causes this test to be skipped.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by bvolpato — APPROVED** [review]
LGTM

I have the context, but I think you could add a brief comment explaining why mocking each

**Comment by shunping** [comment]
> LGTM
> 
> I have the context, but I think you could add a brief comment explaining why mocking each

Do you mean the comment of this commit or the comment in code?

**Comment by bvolpato** [comment]
> > LGTM
> > I have the context, but I think you could add a brief comment explaining why mocking each
> 
> Do you mean the comment of this commit or the comment in code?

I meant in the code for future reference -- I should've highlighted that this is just a nitpick

**Comment by shunping** [comment]
> > > LGTM
> > > I have the context, but I think you could add a brief comment explaining why mocking each
> > 
> > 
> > Do you mean the comment of this commit or the comment in code?
> 
> I meant in the code for future reference -- I should've highlighted that this is just a nitpick

Thanks! I put more explanation in the commit message.

**Comment by tvalentyn** [comment]
> Thanks! I put more explanation in the commit message.

Nice, thanks. Noting for future changes that commit messages are not as easy to lookup as seeing a comment in the code.

**Review by tvalentyn — APPROVED** [review]

**Review by tvalentyn — APPROVED** [review]

**Comment by shunping** [comment]
> > Thanks! I put more explanation in the commit message.
> 
> Nice, thanks. Noting for future changes that commit messages are not as easy to lookup as seeing a comment in the code.

Understood. I will keep that in mind. Thanks for merging.

**Pull request merged**
