### PR TITLE
[BEAM-2899] Move the Job Server into a Submodule

### PR DESCRIPTION
**Pull request by tgroh**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
This permits separation of the Job Server and the Java Runner which
submits to it, while both being part of the 'ReferenceRunner'

### CODE REVIEW

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Seems reasonable. I guess I just hope that the dependency for a user is reasonable and the main entry point is simple to understand, when it gets to that point.

**Comment by tgroh** [comment]
My plan is to name the java `PipelineRunner` '`beam-runners-reference`', which is basically as easy as it is possible to be.

**Comment by kennknowles** [comment]
LGTM

**Pull request closed without merging**
