### PR TITLE
Remove verifyDeterministic from StructuredCoder

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
This is replaced within all uses in the Core SDK by
Coder.verifyDeterministic(Coder, String, List<Coder>), which is a
general utility.

I believe that this change was already authored but lost in a merge.

@kennknowles @lukecwik @davorbonaci 

This is opened against the release branch to determine if it's worth merging. It cherry-picks cleanly into master, and I can create the appropriate PR if desired.

### CODE REVIEW

**Comment by lukecwik** [comment]
This trades off the burden between implementers of StructuredCoders to all callers of verifyDeterministic. It would be better if the StructuredCoder.verifyDeterministic was final and also defined a different method that should be overridden like verifySelfIsDeterministic (but with a much better name).

**Comment by tgroh** [comment]
This could easily be altered to something like `verifyComponentsDeterministic`; these have "replacements" in the static methods `Coder.verifyDeterministic(Coder<?>, String, List<Coder<?>>)`

If the methods are kept, they should certainly be made final. I would like to avoid the suggestion that the verifyDeterministic methods are interchangeable, given that only the argument-free version will be called by the runner.

**Comment by kennknowles** [comment]
LGTM

These methods are silly at best, whether they are `protected` methods (yuck!) or static utilities. No actual coder needs this generalization. Every structured coder has some small number of component coders. The loop is less readable, through needless indirection as well as visual complexity, and results in an inadequate error message. Every coder _should_ improve upon the underlying error message that the loop would produce.

And, tellingly, there is no sensible default for a structured coder. Knowing that it is defined by its components tells you nothing about its determinism.

**Comment by tgroh** [comment]
retest this please

**Comment by kennknowles** [comment]
After some in-person discussion, noting that previously all other structured coders were already ported off this - my comment really applies to future improvements to those (which are not API changes).

**Pull request closed without merging**
