### PR TITLE
Merge master into python-sdk

### PR DESCRIPTION
**Pull request by aaltay**

### CODE REVIEW

**Comment by aaltay** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
This did not apply using the rebase script, so I just, er, made something up. Not happy, but as I understand it the Python branch does not yet follow the contribution guide.

**Comment by dhalperi** [comment]
Hope it's not broken.

**Comment by aaltay** [comment]
Thank you @dhalperi. First postcommit after the merge was successful, (https://builds.apache.org/view/Beam/job/beam_PostCommit_Python_Verify/1110/). Nothing seems to be broken.

How should I applied rebase script? I could not find the information on the contribution guide.

**Pull request merged**
