### PR TITLE
Jupyter notebook for monitoring precommit job times

### PR DESCRIPTION
**Pull request by udim**
This is part of the effort to have fast precommit times for Apache Beam.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by udim** [comment]
R: @alanmyrvold 
I'm still having issues with Rat (how do you add license text to a JSON file?).
Note that hitting the `view` button on the `.ipynb` file will render it in a much more readable fashion than raw JSON.

**Comment by pabloem** [comment]
Udi, I believe you can add it to the exclusions of the rat task here: https://github.com/apache/beam/blob/master/build.gradle#L92

**Comment by udim** [comment]
run go precommit for rat check

**Comment by udim** [comment]
Run Go PreCommit

**Comment by pabloem** [comment]
There's a bit of delay on tests, but they should run in a bit.

**Comment by udim** [comment]
@aaltay for merge

**Pull request merged**
