### PR TITLE
[BEAM-4792] Adds a naive implementation of bounded SDFs to all runners

### PR DESCRIPTION
**Pull request by jkff**
And uses it in all runners.

This makes it possible for people to use SDF-based bounded IOs in production. As of writing, there's only one such IO - HBaseIO.readAll() - but this enables writing more of them without being worried that people can't use them.

This does *not* yet necessarily make it possible to rewrite existing bounded IOs to be SDF-based rather than BoundedSource-based:

* For those that support liquid sharding and are frequently used in production with Dataflow (file-based sources, Bigtable, HBase), rewriting them would require SDF to support it too, otherwise performance degradation will be too large.
* For those that don't support liquid sharding but support size estimation or splitting into chunks of given size - actually these could probably be rewritten, implementing `@SplitRestriction` by splitting into chunks of some reasonable size computed from the size estimate: https://github.com/apache/beam/pull/5886 is a pretty good example and may be good enough.

R: @iemejia 
CC: @lukecwik @jbonofre @aljoscha @tweise

### CODE REVIEW

**Comment by jkff** [comment]
Run Java PreCommit

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
CC: @aljoscha

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
I rebased to get rid of the RAT error, but Dataflow VR is still running at https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle_PR/24/

**Comment by jkff** [comment]
Woohoo, Dataflow actually passes SDF tests in batch mode with this PR!

On the downside, it *only* runs them in batch mode now - because SplittableDoFnTest no longer forces streaming, but it uses a BoundedPerElement DoFn.

Not sure what's the best way to organize a fix to this. Maybe make SplittableDoFnTest test everything both with a BoundedPerElement and UnboundedPerElement DoFn; or maybe, rather, run it both in batch mode and streaming mode. I am not sure what's our current story with running Dataflow VR tests in batch and streaming.

**Comment by aljoscha** [comment]
Nice! You beat me to it. 😃

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by echauchot** [comment]
@jkff for batch and streaming VR tests, we usually have a single test case and we force batch or streaming mode with the --streaming=[true|false] runner parameter. There are some special cases like Spark that needs `CreateStream` to trigger streaming mode even if streaming=true is set. But for the other runners AFAIK it works fine with forcing streaming mode.

**Comment by jkff** [comment]
@echauchot Do you know if there's a phrase for triggering Dataflow Streaming ValidatesRunner then?

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
OK, I ended up changing SDFTest to exercise both bounded and unbounded cases.

**Comment by jkff** [comment]
Dataflow VR tests running at https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle_PR/25/

Meanwhile, I added support for bounded SDF to *all* runners. PTAL :) If it looks good then I'll also change the compatibility matrix.

**Comment by jkff** [comment]
Run Apex ValidatesRunner

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
Run Gearpump ValidatesRunner

**Comment by jkff** [comment]
Run Samza ValidatesRunner

**Comment by jkff** [comment]
Run Spark ValidatesRunner

**Comment by jkff** [comment]
OK, all VR tests passed; the one issue in Java PreCommit is a bug in the test itself, pushing commit to fix it - all other passing tests should still be valid so I'm not going to rerun them.

**Comment by jkff** [comment]
Run Spark ValidatesRunner

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Pull request merged**
