### PR TITLE
avoid infinite recursion if cls.__dict__ refers to cls

### PR DESCRIPTION
**Pull request by martindemello**
The python pickler does a recursive check through a class's __dict__ to find containing classes. Some classes (issue discovered via typing.List) contain a self-reference within their __dict__, leading to infinite recursion.

This PR fixes the simple case of a single level of self-reference; checking for mutually recursive classes seems like overkill.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by angoenka** [comment]
Thanks for the fix.
We are still having bug in the case where A => B and B => A
Should we handle that case as well.
cc: @robertwb

**Comment by martindemello** [comment]
can someone help with the failing jenkins checks? when i click through for details all i see is "no changes" - are these existing failures?

**Comment by martindemello** [comment]
confirmed that ` ./gradlew --info --continue --rerun-tasks :pythonPreCommit` fails locally on `master`

**Comment by martindemello** [comment]
fixed in https://github.com/apache/beam/pull/5072

**Pull request closed without merging**
