### PR TITLE
[BEAM-12164] Fix flaky tests

### PR DESCRIPTION
**Pull request by zoercai**

### CODE REVIEW

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
I see this failure: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/4757/ 
: (

Are occassional failures an indication of a problem? If they are, then there is at least one test failing.
If they are acceptable, then you could add a retry mechanism like this one: https://github.com/apache/beam/blob/master/sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOAutoPartitioningIT.java#L96-L127

This should at least diminish the frequency of failures enough that we can bring it in?

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
does this fix the issue @zoercai ? how does it fix it?

**Comment by zoercai** [comment]
> does this fix the issue @zoercai ? how does it fix it?

I changed the end timestamp to 1 nanosecond after the start timestamp so that splitting doesn't occur. The flaky error was caused by lack of mocking for the different timestamps that would be queried from splits that were only created sometimes.

I will keep re-running the test a bunch more times today to see if any of the runs fails again

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
I was able, unfortunately, to make these tests flake after 5 tries, and then again after 19 tries.

I added these three lines to `sdks/java/io/google-cloud-platform/build.gradle`:

```
test {
  outputs.upToDateWhen { false }
}

```

The purpose of these three lines is to avoid 'caching' test results, and making sure that the tests will run every time even if the code did not change (but artifacts won't be rebuilt).

Then I used these commands:

```
declare -i ITERATIONS=0

while ./gradlew :sdks:java:io:google-cloud-platform:test --tests=*SpannerChangeStreamErrorTest*; 
do   
ITERATIONS=$ITERATIONS+1;   
if [[ "$ITERATIONS" -eq 100 ]]; then     break;   fi; 
done
```

The iterations stopped after `5` and `19` runs. So I think flakiness in the tests is still high, unfortunately : /

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by zoercai** [comment]
> I was able, unfortunately, to make these tests flake after 5 tries, and then again after 19 tries.
> 
> I added these three lines to `sdks/java/io/google-cloud-platform/build.gradle`:
> 
> ```
> test {
>   outputs.upToDateWhen { false }
> }
> ```
> 
> The purpose of these three lines is to avoid 'caching' test results, and making sure that the tests will run every time even if the code did not change (but artifacts won't be rebuilt).
> 
> Then I used these commands:
> 
> ```
> declare -i ITERATIONS=0
> 
> while ./gradlew :sdks:java:io:google-cloud-platform:test --tests=*SpannerChangeStreamErrorTest*; 
> do   
> ITERATIONS=$ITERATIONS+1;   
> if [[ "$ITERATIONS" -eq 100 ]]; then     break;   fi; 
> done
> ```
> 
> The iterations stopped after `5` and `19` runs. So I think flakiness in the tests is still high, unfortunately : /

Thanks @pabloem! I used this to run the tests locally and fix the test that was failing. I ran this a few hundred times locally. Hopefully it's finally stable!

**Comment by pabloem** [comment]
thanks a lot @zoercai ! LGTM

**Comment by lukecwik** [comment]
This is still flaking a bunch, see: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/21723/ which failed just under 2 hrs ago.

**Comment by lukecwik** [comment]
Filed BEAM-14152 and disabled flaky test in https://github.com/apache/beam/pull/17158

**Pull request merged**
