### PR TITLE
[BEAM-11657] Reduce reflection calls when reading from Kafka

### PR DESCRIPTION
**Pull request by scwhittle**
When headers are not supported, there are no reflection calls remaining as this knowledge is computed once in the ConsumerSpEL singleton.
When headers are supported but the decoder does not implement the method to examine headers, there are no reflection calls based upon a cache keyed by decoder in the ConsumerSpeEL singleton.
When headers are supported and possibly used by the coder, a reflection-based expression is still evaluated for each deserialization.  I tried to enable expression compilation but was unable to get it working, I believe due to the generics as part of the Deserializer<T> object but I am not sure.  That is a possible performance improvement for the future for uses that require headers.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @lukecwik

**Comment by boyuanzz** [comment]
It seems like Luke is still on vacation. I can help review it and cc: @aromanenko-dev

**Comment by scwhittle** [comment]
Another idea I had was to change the deserialize method to attempt calling the kafka deserialize method taking headers and catch an exception if the method is not found during execution (due to previous kafka version).

This could be cached so that future attempts would avoid the exception and just call the method without headers.  We could remove the cache map of deserializer -> bool in that case.

Thoughts?

**Comment by aromanenko-dev** [comment]
I think it could be a good idea. Btw, did you take a look on what we do to [check](https://github.com/apache/beam/blob/67989cafecf3f5d4bce879e9f6b9a690955e84d5/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ProducerSpEL.java#L54) if Kafka producer supports transactions? Can we do similar things here?

**Comment by scwhittle** [comment]
PTAL, I updated to better match ProducerSpEL by using static initializer and static methods instead of a singleton object.  I removed the map of deserializer to if it examines headers by instead just delegating to calling either the method with our without headers provided based upon the existence of the method in static initialization.

From my understanding this should work because the SDK is compiled with a kafka version supporting the header method, and if during execution the method does not exist it is ok to have the implementation reference it as long as it is not executed. This matches how ConsumerSpEL.getRecordTimestamp works.

**Comment by aromanenko-dev** [comment]
Run Java KafkaIO Performance Test

**Comment by aromanenko-dev** [comment]
@scwhittle Thanks, I'll take a look asap

**Comment by scwhittle** [comment]
Not sure if there are dashboards but the perf results from console output were:
16:21:21 org.apache.beam.sdk.io.kafka.KafkaIOIT > testKafkaIOReadsAndWritesCorrectlyInStreaming STANDARD_OUT
16:21:21     Load test results for test (ID): 539adecb-21ea-4aaf-935c-95c9bb9b91c5 and timestamp: 2021-01-28T15:02:34.094000000Z:
16:21:21                      Metric:                    Value:
16:21:21                    read_time                     1.385
16:21:21                   write_time                     9.316
16:21:21                     run_time                    10.701

The subsequent run https://ci-beam.apache.org/job/beam_PerformanceTests_Kafka_IO/1871/console had results:
20:34:52 org.apache.beam.sdk.io.kafka.KafkaIOIT > testKafkaIOReadsAndWritesCorrectlyInStreaming STANDARD_OUT
20:34:52     Load test results for test (ID): cb47f5d5-0102-49ce-8fd1-73eb3e6bbe40 and timestamp: 2021-01-28T19:16:14.211000000Z:
20:34:52                      Metric:                    Value:
20:34:52                    read_time                     2.873
20:34:52                   write_time                     14.97
20:34:52                     run_time                    17.843

I'm not sure how stable these are, write_time shouldn't directly be effected, but if the pipeline is doing both in parallel the CPU waste on reading could impact write performance as well.

**Comment by aromanenko-dev** [comment]
I checked randomly the results of Performance test from other runs and seems that we have some improvement with this PR. 
It LGTM
CC: @boyuanzz @chamikaramj fyi

**Review by boyuanzz — APPROVED** [review]
Thanks for this improvement!

**Review by aromanenko-dev — APPROVED** [review]

**Pull request merged**
