### PR TITLE
Use the same trigger for Py2 and Py3 PostCommit test suites.

### PR DESCRIPTION
**Pull request by tvalentyn**
Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](../.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python Postcommit

**Comment by tvalentyn** [comment]
R: @markflyhigh 
Looks like the PR need to be submitted first for the change to take effect.

**Comment by pabloem** [comment]
Run Seed Job

**Comment by pabloem** [comment]
Run Python Postcommit

**Comment by pabloem** [comment]
The Seed job is what we use to "commit" configuration of tests on jenkins. You just need to run it in your PR and the changes will be picked up. The pitfall is that it updates configurations for everyone.

**Comment by pabloem** [comment]
LGTM.

**Comment by tvalentyn** [comment]
@pabloem , thanks. The tests will probably fail, but as long Py3 suite is triggered, feel free to merge this. Thank you!

**Comment by markflyhigh** [comment]
should also update the trigger phrase in https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md

**Comment by tvalentyn** [comment]
FYI - @RobbeSneyders , @Juta

**Pull request merged**
