### PR TITLE
Increase visibility of some Metrics methods

### PR DESCRIPTION
**Pull request by bjchambers**
Also revise the Javadoc on MetricsContainers.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [*] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [*] Make sure tests pass via `mvn clean verify`.
 - [*] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [*] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by bjchambers** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM. I can easily see that runners need access to these.

**Comment by kennknowles** [comment]
Maven success, Jenkins failure due to external service downtime. I'll merge it.

**Comment by kennknowles** [comment]
I want to note that _all_ of `runners/core-java` and `runner/core-construction-java` are internal. The annotations are fine anyhow.

**Pull request merged**
