### PR TITLE
[Go SDK] S3 implementation of the Beam filesystem

### LINKED ISSUE #23991: [Feature Request][Go SDK]: S3 implementation of the Beam filesystem
### What would you like to happen?

I would like to have an S3 implementation of the Beam filesystem in the Go SDK to support reading and writing objects in S3 from textio, avroio etc.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by johannaojeling**
Creates an S3 implementation of the Beam filesystem, which enables objects in S3 to be read from and written to e.g. from textio DoFns. Fixes #23991.

A pipeline using `textio.Read` and `textio.Write` with S3 uris has been tested with the Direct Runner and Dataflow Runner. Identity federation was used to access AWS from Dataflow as described [here](https://github.com/johannaojeling/dataflow-gcp-aws-identity-federation).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johannaojeling** [comment]
R: @lostluck

**Review by lostluck — APPROVED** [review]
This is excellent! Thank you very much! This is a phenomenal first contribution to beam, from filing the issue, to separate examples, and so on.

My only complaint is that it's hard to test these things generally, because neither GCS nor S3 provide good in-memory fakes for themselves.

It does look like someone has one for s3, https://github.com/johannesboyne/gofakes3#example-for-v2-aws-sdk-go-v2 but I'd be perfectly content to get this in first anyway.

**Comment by lostluck** [comment]
Once the go.mod conflict is resolved, I'm happy to merge this in, or allow you to try to unit test it with a fake. Your choice. Welcome to Beam!

**Comment by johannaojeling** [comment]
> This is excellent! Thank you very much! This is a phenomenal first contribution to beam, from filing the issue, to separate examples, and so on.
> 
> My only complaint is that it's hard to test these things generally, because neither GCS nor S3 provide good in-memory fakes for themselves.
> 
> It does look like someone has one for s3, https://github.com/johannesboyne/gofakes3#example-for-v2-aws-sdk-go-v2 but I'd be perfectly content to get this in first anyway.

Thank you! Cool, thanks, I will look into the S3 fake client. I might do that in a separate issue though, so please go ahead and merge

**Comment by lostluck** [comment]
Thanks again and welcome to Beam!

**Comment by johannaojeling** [comment]
> Thanks again and welcome to Beam!

Thank you 😊

**Pull request merged**
