### PR TITLE
Fix GroupIntoBatches hold

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @damccorm

**Comment by damccorm** [comment]
Looks like this may be causing precommit issues - testE2EWordCount is failing for multiple tasks. Might be flakes, so I'll retry

**Comment by damccorm** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Review by damccorm — APPROVED** [review]
This seems right to me, so I'm good to merge if it doesn't actually cause test failures. If it does, we should dig in and figure out why

**Comment by damccorm** [comment]
Java PreCommit is also hanging, that smells like a Jenkins issue to me though - its been stuck without making progress for >1 hour

**Comment by damccorm** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Pull request merged**
