### PR TITLE
[BEAM-2477] BeamAggregationRel should use Combine.perKey instead of GroupByKey

### PR DESCRIPTION
**Pull request by JingsongLi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @XuMingmin @xumingming @takidau

**Comment by JingsongLi** [comment]
retest this please

**Comment by JingsongLi** [comment]
retest this please

**Comment by takidau** [comment]
Thanks a lot, nice improvement. LGTM. Will merge as soon as I can.

**Comment by takidau** [comment]
Merged, feel free to close. Thank you!

**Pull request closed without merging**
