### PR TITLE
Adding support for GCS-stored files for consumer config overrides

### PR DESCRIPTION
**Pull request by pabloem**
r: @johnjcasey 

This is for users to pass truststore / keystore files for Kafka consumers that are stored in GCS, and we can then store them in the local worker for Kafka to create a consumer properly. It's an 'ease-of-use' feature for x-lang (and syndeo) users.

It can be extended to other filesystems (e.g. s3)

fyi @chamikaramj @bvolpato I'd also like your thoughts on this...

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java_Kafka_IO_Direct PreCommit

**Review by bvolpato — APPROVED** [review]
That's awesome, thanks! Can we also do it for the ProducerFactory? (could be separate, though)

**Comment by bvolpato** [comment]
cc @pranavbhandari24 -- as I know we have to workaround this for Kafka.

**Comment by pabloem** [comment]
thanks y'all - yes, I can add this for the producer factory

**Pull request merged**
