### PR TITLE
Fix Pytest Unknown Marker Error for Xlang Kafka IT Test

### PR DESCRIPTION
**Pull request by jrmccluskey**
The Kafka Xlang IT tests were seemingly not running because the `uses_io_expansion_service` tag was not defined. This should fix those warnings and enable those tests. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by Abacn — APPROVED** [review]

**Comment by jrmccluskey** [comment]
Run Python_Xlang_IO_Dataflow PostCommit

**Comment by jrmccluskey** [comment]
CC: @johnjcasey

**Comment by riteshghorse** [comment]
Tests for xlang_kafka_it_test.py are running in this suite https://ci-beam.apache.org/job/beam_PostCommit_Python_Xlang_IO_Dataflow/

image

**Review by riteshghorse — APPROVED** [review]
LGTM!

**Comment by Abacn** [comment]
Test passed: https://ci-beam.apache.org/job/beam_PostCommit_Python_Xlang_IO_Dataflow_PR/9/testReport/apache_beam.io.external.xlang_kafkaio_it_test/CrossLanguageKafkaIOTest/

**Pull request merged**
