### PR TITLE
[BEAM-7744] LTS backport: Temporary directory for WriteOperation may not be unique in FileBaseSink

### PR DESCRIPTION
**Pull request by ihji**
Temporary directory for WriteOperation in FileBasedSink is generated
from a second-granularity timestamp (yyyy-MM-dd_HH-mm-ss) and unique
increasing index. Such granularity is not enough to make temporary
directories unique between different jobs. When two jobs share the same
temporary directory, output file may not be produced in one job since
the required temporary file can be deleted from another job.

To avoid fore-mentioned issue, this commit changes the temporary
directory name from a second-granularity timestamp to UUID.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by ihji** [comment]
R: @chamikaramj @aaltay 
CC: @kennknowles

**Comment by kennknowles** [comment]
Can you please include some description of the change in the commit message and the pull request title and body?

**Comment by kennknowles** [comment]
Thanks! That is a great description. It seems we had a problem that does not have to do with your change. I will try again and see if we still have this problem with maven central.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Timeline of build that failed to fetch deps: https://scans.gradle.com/s/3q7zofz6vgbso/timeline (it failed on zookeeper but I think this is not important)

**Comment by kennknowles** [comment]
run java precommit

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Hmm now I have seen this reliably. Last time I checked that dep was fine but maybe something is wrong specifically.

```
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':beam-sdks-java-io-google-cloud-platform:shadowTestJar'.Open stacktrace
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':beam-sdks-java-io-google-cloud-platform:testRuntime'.Open stacktrace
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: 
Could not find powermock-api-mockito-sources.jar (org.powermock:powermock-api-mockito:1.6.4).
Searched in the following locations:
    file:/home/jenkins/.m2/repository/org/powermock/powermock-api-mockito/1.6.4/powermock-api-mockito-1.6.4-sources.jar
```

**Comment by kennknowles** [comment]
Yea, just built locally and I see:

`Download https://repo.maven.apache.org/maven2/org/powermock/powermock-api-mockito/1.6.4/powermock-api-mockito-1.6.4-sources.jar`

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
I wonder if actually these are symptoms of the disk being filled. I could not find evidence clearly in the console log, and I was unable to SSH to the machine to check. But it does seem reliable with this PR.

**Comment by ihji** [comment]
Run Java PreCommit

**Comment by ihji** [comment]
Run JavaPortabilityApi PreCommit

**Comment by ihji** [comment]
@kennknowles @aaltay Java precommit passed. PTAL. Thanks!

**Comment by aaltay** [comment]
I am guessing the other error for JavaPortabilityApi test is fine because the error is "14:13:05 Task 'javaPreCommitPortabilityApi' not found in root project 'beam'." It does not look like test exists in this branch.

**Pull request merged**
