### PR TITLE
[BEAM-12164] Add javadocs to SpannerConfig

### PR DESCRIPTION
**Pull request by zoercai**
Add javadocs to settings in SpannerConfig.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
javadoc changes look good to me!

**Comment by pabloem** [comment]
there's a few style errors flagged by our build: https://scans.gradle.com/s/gl4wjr7echz54/console-log?task=:sdks:java:io:google-cloud-platform:checkstyleMain

Basically, end all of the fist lines in Javadoc with a period

**Comment by pabloem** [comment]
fyi @zoercai

**Comment by zoercai** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
ok LGTM thanks @zoercai !

**Pull request merged**
