### PR TITLE
[BEAM-1782] Updates BigQuery read transform to correctly process empty repeated fields.

### PR DESCRIPTION
**Pull request by chamikaramj**
This fixes DirectRunnner. DataflowRunner is already processing these fields correctly.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @sb2nov

**Comment by sb2nov** [comment]
LGTM

**Comment by chamikaramj** [comment]
Thanks.

**Comment by dhalperi** [comment]
@chamikaramj should this be merged?

**Comment by chamikaramj** [comment]
This was merged. Forgot to close.

**Pull request closed without merging**
