### PR TITLE
[#27692] Set non-playground Go versions to use Go 1.21.0

### PR DESCRIPTION
**Pull request by lostluck**
Beam release cut is tomorrow (August 9th, 2023), and Go 1.21.0 was released today, so it's the latest version we can use for the release tomorrow.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
Run Go PreCommit

**Comment by jrmccluskey** [comment]
This gives us access to `slog`, right?

**Comment by lostluck** [comment]
> This gives us access to `slog`, right?

Technically no. We'd need to update the go.mod version to 1.21 for that, and we are not going to do that before the 2.50 cut tomorrow. We could do it for 2.51 if we like, paired with the change to the standard library version of slog in Prism. 

Doing the work of adding a slog handler for beam for 2.51 is a different question entirely.

**Comment by jrmccluskey** [comment]
I mostly want it for the sections of the boot loaders where we don't have the logging service yet since I'm still living in that world. Noted.

**Comment by lostluck** [comment]
Sounds good. Also a good reason to move to 1.21, but lets please not make that change the day before the 2.50 cut :).

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by lostluck** [comment]
Requiring Go 1.21 for beam has a dozen small changes and fixes and documentation bits to update, which we just did for 2.50 to get us to 1.20. 

I'd rather avoid skipping release versions, and forcing users that hard to update their Go versions (as unlikely as it is that Beam will be why they do so anyway.)

**Comment by lostluck** [comment]
The remaining jobs succeeded, github just didn't get the update. Merging.

**Pull request merged**
