### PR TITLE
[BEAM-13590]Update Pytest version to support Python 3.10

### PR DESCRIPTION
**Pull request by AnandInguva**
Update pytest dependencies to support Python 3.10

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
R: @tvalentyn

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python 3.8 PostCommit

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Took a quick look. need to investigate if this is related to our change.

```
18:27:31 ================== 1 passed, 3 warnings in 683.71s (0:11:23) ===================
18:27:31 
18:27:31 > Task :sdks:python:test-suites:dataflow:preCommitIT_V2
18:27:31 
18:27:31 FAILURE: Build failed with an exception.
18:27:31 
18:27:31 * What went wrong:
18:27:31 Execution failed for task ':sdks:python:test-suites:tox:py38:testPy38CloudCoverage'.
18:27:31 > Process 'command 'sh'' finished with non-zero exit value 1
18:27:31 
18:27:31 * Try:
18:27:31 > Run with --stacktrace option to get the stack trace.
18:27:31 > Run with --info or --debug option to get more log output.
18:27:31 > Run with --scan to get full insights.
18:27:31 
18:27:31 * Get more help at https://help.gradle.org/
18:27:31 
18:27:31 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

**Comment by AnandInguva** [comment]
> Took a quick look. please investigate if this is related to this change.
> 
> ```
> 18:27:31 ================== 1 passed, 3 warnings in 683.71s (0:11:23) ===================
> 18:27:31 
> 18:27:31 > Task :sdks:python:test-suites:dataflow:preCommitIT_V2
> 18:27:31 
> 18:27:31 FAILURE: Build failed with an exception.
> 18:27:31 
> 18:27:31 * What went wrong:
> 18:27:31 Execution failed for task ':sdks:python:test-suites:tox:py38:testPy38CloudCoverage'.
> 18:27:31 > Process 'command 'sh'' finished with non-zero exit value 1
> 18:27:31 
> 18:27:31 * Try:
> 18:27:31 > Run with --stacktrace option to get the stack trace.
> 18:27:31 > Run with --info or --debug option to get more log output.
> 18:27:31 > Run with --scan to get full insights.
> 18:27:31 
> 18:27:31 * Get more help at https://help.gradle.org/
> 18:27:31 
> 18:27:31 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> ```

Yes. I will take a look

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by AnandInguva** [comment]
> Took a quick look. please investigate if this is related to this change.
> 
> ```
> 18:27:31 ================== 1 passed, 3 warnings in 683.71s (0:11:23) ===================
> 18:27:31 
> 18:27:31 > Task :sdks:python:test-suites:dataflow:preCommitIT_V2
> 18:27:31 
> 18:27:31 FAILURE: Build failed with an exception.
> 18:27:31 
> 18:27:31 * What went wrong:
> 18:27:31 Execution failed for task ':sdks:python:test-suites:tox:py38:testPy38CloudCoverage'.
> 18:27:31 > Process 'command 'sh'' finished with non-zero exit value 1
> 18:27:31 
> 18:27:31 * Try:
> 18:27:31 > Run with --stacktrace option to get the stack trace.
> 18:27:31 > Run with --info or --debug option to get more log output.
> 18:27:31 > Run with --scan to get full insights.
> 18:27:31 
> 18:27:31 * Get more help at https://help.gradle.org/
> 18:27:31 
> 18:27:31 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> ```

I looked into it. pytest-cov needs to be updated as well because of https://github.com/pytest-dev/pytest-cov/pull/412. Now everything passes. 

PTAL @tvalentyn

**Pull request merged**
