### PR TITLE
[BEAM-13857] Switched Go IT script to using Go flags for expansion services

### PR DESCRIPTION
**Pull request by youngoli**
This is a followup to a previous PR (https://github.com/apache/beam/pull/16908) which added the feature but didn't switch existing tests to using it. This switches existing tests to using the feature (along with making sure it's set up properly in a way that works).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by youngoli** [comment]
R: @lostluck @riteshghorse

**Comment by youngoli** [comment]
I'd like to note for future reference that the cross-language postcommits for Python Direct, Flink, and Spark all seem to currently be failing, so while running them I'm not going to be checking that they succeed, but that the failures don't change, and we can be reasonably sure that this PR didn't change anything. Since this only affects the way expansion services are initialized for Go, any errors should probably be visible over existing errors.

**Comment by youngoli** [comment]
Run XVR_Direct PostCommit

**Comment by youngoli** [comment]
Run XVR_Flink PostCommit

**Comment by youngoli** [comment]
Run XVR_Spark PostCommit

**Comment by lostluck** [comment]
Run XVR_Flink PostCommit

**Comment by lostluck** [comment]
Run Flink CrossLanguageValidatesRunner Tests

**Comment by lostluck** [comment]
Run XVR_Flink PostCommit

**Comment by youngoli** [comment]
I'm inclined to think this is a flake for the Flink XVR tests, since this change shouldn't be doing anything to the specific of Flink connections. And looking at the Non-PR version, looks like it's failing with the same error (ex. https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/5215/)

Java Precommit I already know is being flaky due to timeouts and this change isn't modifying Java at all. CommunityMetrics Precommit similarly is currently not working for unrelated reasons.

**Comment by youngoli** [comment]
That said, before I merge this I'm going to double check it doesn't conflict with #16819

**Comment by lostluck** [comment]
Run XVR_Flink PostCommit

**Comment by lostluck** [comment]
Run CommunityMetrics PreCommit

**Comment by lostluck** [comment]
Seems like a flake.
```
=== RUN   TestKafkaIO_BasicReadWrite
--- FAIL: TestKafkaIO_BasicReadWrite (0.01s)
panic: 	tried cross-language for beam:transform:org.apache.beam:kafka_write:v1 against localhost:45851 and failed
	expanding external transform
	expanding transform with ExpansionRequest: components:{pcollections:{key:"n4" value:{unique_name:"n4" coder_id:"c1@GihEXlkPLs" is_bounded:BOUNDED windowing_strategy_id:"w0@GihEXlkPLs"}} windowing_strategies:{key:"w0@GihEXlkPLs" value:{window_fn:{urn:"beam:window_fn:global_windows:v1"} merge_status:NON_MERGING window_coder_id:"c2@GihEXlkPLs" trigger:{default:{}} accumulation_mode:DISCARDING output_time:END_OF_WINDOW closing_behavior:EMIT_IF_NONEMPTY OnTimeBehavior:FIRE_IF_NONEMPTY environment_id:"go"}} coders:{key:"c0@GihEXlkPLs" value:{spec:{urn:"beam:coder:bytes:v1"}}} coders:{key:"c1@GihEXlkPLs" value:{spec:{urn:"beam:coder:kv:v1"} component_coder_ids:"c0@GihEXlkPLs" component_coder_ids:"c0@GihEXlkPLs"}} coders:{key:"c2@GihEXlkPLs" value:{spec:{urn:"beam:coder:global_window:v1"}}} environments:{key:"go" value:{}}} transform:{unique_name:"External" spec:{urn:"beam:transform:org.apache.beam:kafka_write:v1" payload:"\n}\n\x1c\n\x0eProducerConfig\x1a\n*\x08\n\x02\x10\x07\x12\x02\x10\x07\n\x0b\n\x05Topic\x1a\x02\x10\x07\n\x13\n\rKeySerializer\x1a\x02\x10\x07\n\x15\n\x0fValueSerializer\x1a\x02\x10\x07\x12$d97fbd8d-dde2-46d8-babd-f5372b6ab5e6\x12\xda\x01\x04\x00\x00\x00\x00\x01\x11bootstrap.servers\x0flocalhost:38215=xlang_kafkaio_basic_test_1f77995b-3f76-4225-a30a-37f34017bee79org.apache.kafka.common.serialization.ByteArraySerializer9org.apache.kafka.common.serialization.ByteArraySerializer"} inputs:{key:"i0" value:"n4"} environment_id:"go"} namespace:"GihEXlkPLs"
expansion failed
	caused by:
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:45851: connect: connection refused" [recovered]
	panic: 	tried cross-language for beam:transform:org.apache.beam:kafka_write:v1 against localhost:45851 and failed
	expanding external transform
	expanding transform with ExpansionRequest: components:{pcollections:{key:"n4" value:{unique_name:"n4" coder_id:"c1@GihEXlkPLs" is_bounded:BOUNDED windowing_strategy_id:"w0@GihEXlkPLs"}} windowing_strategies:{key:"w0@GihEXlkPLs" value:{window_fn:{urn:"beam:window_fn:global_windows:v1"} merge_status:NON_MERGING window_coder_id:"c2@GihEXlkPLs" trigger:{default:{}} accumulation_mode:DISCARDING output_time:END_OF_WINDOW closing_behavior:EMIT_IF_NONEMPTY OnTimeBehavior:FIRE_IF_NONEMPTY environment_id:"go"}} coders:{key:"c0@GihEXlkPLs" value:{spec:{urn:"beam:coder:bytes:v1"}}} coders:{key:"c1@GihEXlkPLs" value:{spec:{urn:"beam:coder:kv:v1"} component_coder_ids:"c0@GihEXlkPLs" component_coder_ids:"c0@GihEXlkPLs"}} coders:{key:"c2@GihEXlkPLs" value:{spec:{urn:"beam:coder:global_window:v1"}}} environments:{key:"go" value:{}}} transform:{unique_name:"External" spec:{urn:"beam:transform:org.apache.beam:kafka_write:v1" payload:"\n}\n\x1c\n\x0eProducerConfig\x1a\n*\x08\n\x02\x10\x07\x12\x02\x10\x07\n\x0b\n\x05Topic\x1a\x02\x10\x07\n\x13\n\rKeySerializer\x1a\x02\x10\x07\n\x15\n\x0fValueSerializer\x1a\x02\x10\x07\x12$d97fbd8d-dde2-46d8-babd-f5372b6ab5e6\x12\xda\x01\x04\x00\x00\x00\x00\x01\x11bootstrap.servers\x0flocalhost:38215=xlang_kafkaio_basic_test_1f77995b-3f76-4225-a30a-37f34017bee79org.apache.kafka.common.serialization.ByteArraySerializer9org.apache.kafka.common.serialization.ByteArraySerializer"} inputs:{key:"i0" value:"n4"} environment_id:"go"} namespace:"GihEXlkPLs"
expansion failed
	caused by:
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:45851: connect: connection refused"
```

**Comment by lostluck** [comment]
Run XVR_Flink PostCommit

**Comment by lostluck** [comment]
Up, just an unrelated flake. Merging.

**Pull request merged**
