### PR TITLE
Adding documentation to DirectRunner functions.

### PR DESCRIPTION
**Pull request by pabloem**
r: @aaltay

### CODE REVIEW

**Comment by robertwb** [comment]
The "Also marking Fn API Runner as supporting metrics." seems like a much bigger change that should probably be pulled out into its own PR.

**Comment by pabloem** [comment]
oops - I guess I got confused about5 this. Thanks Robert. I think this is ready for review now.

**Comment by aaltay** [comment]
I do not follow where "Also marking Fn API Runner as supporting metrics." is happening. Otherwise change looks good. 

Please update the PR description and self merge.

**Comment by pabloem** [comment]
That marking FnAPI runner...etc stuff is not happening anymore. This is apure pydoc PR now. Thanks Ahmet.

**Pull request merged**
