### PR TITLE
Fix NPE in ComputationState constructor introduced by PR/7846

### PR DESCRIPTION
**Pull request by drieber**
The root cause was assuming an empty transformUserNameToStateFamily map was passed, when instead null was passed.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](../.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by drieber** [comment]
R: @reuvenlax

**Comment by ryan-williams** [comment]
Thanks for the quick fix here @drieber! 

One question I had was why the `Java_Examples_Dataflow` precommit didn't run on #7846 (and so far doesn't seem to have run here)?

**Comment by drieber** [comment]
I don't know.

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
Run Java PostCommit

**Comment by reuvenlax** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by reuvenlax** [comment]
@drieber thanks for the quick fix! For future reference, when changing a specific runner, it's best to run the ValidatesRunner tests for that runner before merging (see the run I triggered above for the Dataflow runner). Unfortunately the documentation on these trigger phrases is still a bit spotty.

**Comment by ryan-williams** [comment]
@reuvenlax per [my comment above](https://github.com/apache/beam/pull/7869#issuecomment-464564639), do you know why "Java_Examples_Dataflow PreCommit" ran on our PRs (#7823, #7865) that didn't seem to have to do with Dataflow, but not #7846 (where the bug was introduced) nor here (where the bug was fixed)?

**Comment by reuvenlax** [comment]
Here is the trigger pattern (from
job_PreCommit_Java_Examples_Dataflow.groovy
<https://github.com/apache/beam/pull/6802/files#diff-29c78beae45d057dc4643ea33166a399>
)

I think the path runners/google-cloud-dataflow in the trigger is incorrect.
The actual code path is runners/dataflow.

PrecommitJobBuilder builder = new PrecommitJobBuilder(
    scope: this,
    nameBase: 'Java_Examples_Dataflow',
    gradleTask: ':javaExamplesDataflowPreCommit',
    gradleSwitches: ['-PdisableSpotlessCheck=true'], // spotless
checked in separate pre-commit
    triggerPathPatterns: [
      '^model/.*$',
      '^sdks/java/.*$',
      '^runners/google-cloud-dataflow/.*$',
      '^examples/java/.*$',
      '^release/.*$',
    ]
)

**Pull request merged**
