### PR TITLE
Remove generated code from srcSets.

### PR DESCRIPTION
**Pull request by reuvenlax**
This fixes spotless issues encountered by users

### CODE REVIEW

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
LGTM when green.

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Pull request merged**
