### PR TITLE
[BEAM-7984] The coder returned for typehints.List should be IterableCoder

### PR DESCRIPTION
**Pull request by chadrik**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by chadrik** [comment]
R: @robertwb

**Comment by chadrik** [comment]
Addressed

**Comment by robertwb** [comment]
Run Python PreCommit

**Comment by chadrik** [comment]
I find the python precommit test rather inscrutable.  It seems that it _always_ fails on :sdks:python:setupVirtualenv and I don't understand whether I should care or not.

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
These failures could be related to the PR changes: https://builds.apache.org/job/beam_PreCommit_Python_Phrase/761/

**Comment by robertwb** [comment]
Run Python PreCommit

**Comment by robertwb** [comment]
I can't reproduce these test failures locally.

**Comment by mxm** [comment]
Tests are also failing locally for me with the same error: 

```
TypeError: can only concatenate list (not "bytes") to list [while running 'FormatOutput']```

**Comment by chadrik** [comment]
There are a handful of levels from which the python tests can be invoked
(gradle, tox, setup.py, nose): can you provide the exact command you're
running?

**Comment by mxm** [comment]
Haven't fully figured out how to run a specific test through Gradle. What I do is to run this from the test directory (`/sdks/python/test-suites/tox/py2/build/srcs/sdks/python`: 

```
python setup.py nosetests --tests apache_beam.testing.synthetic_pipeline_test
```

You need to activate the virtual environment that Gradle uses first. It's in `/build/gradleenv`

**Comment by chadrik** [comment]
I gave up trying to figure out how to run specific tests from gradle as well, so I just created a PR https://github.com/apache/beam/pull/9474  to enable running individual tests using tox.  This should theoretically be the same environment as gradle, since gradle calls tox.  

I'm cherry-picking the commit from my PR and running the tests like this:

```
tox -e py27 -- --tests apache_beam.testing.synthetic_pipeline_test
```

Running this on my Macbook Pro succeeds, so I'm not sure where to go from here.

**Comment by chadrik** [comment]
Update:  I get the error using python 3.7, and I confirmed that I do _not_ get it on master:

```
tox -e py37 -- --tests apache_beam.testing.synthetic_pipeline_test.SyntheticPipelineTest
```

**Comment by mxm** [comment]
That makes sense. I was testing with 3.7 as well.

**Comment by chadrik** [comment]
What's happened here is that this change has exposed a difference in the inference code between python2 and python3. 

Here's the function that's being analyzed differently:

```python
def rotate_key(element):
  """Returns a new key-value pair of the same size but with a different key."""
  (key, value) = element
  return key[-1:] + key[:-1], value
```

python3:

```python
In [1]: from apache_beam.typehints.trivial_inference import infer_return_type                                                                                                                                                                                           
In [2]: from apache_beam.testing.synthetic_pipeline import rotate_key                                                                                                                                                                                                   
In [3]: from apache_beam.typehints import Any                                                                                                                                                                                                                           
In [4]: infer_return_type(rotate_key, [Any])                                                                                                                                                                                                                            
Out[4]: Tuple[List[Any], Any]
```

python2:

```python
In [1]: from apache_beam.typehints.trivial_inference import infer_return_type                                                                                                                                                                                           
In [2]: from apache_beam.testing.synthetic_pipeline import rotate_key                                                                                                                                                                                                   
In [3]: from apache_beam.typehints import Any                                                                                                                                                                                                                           
In [4]: infer_return_type(rotate_key, [Any])                                                                                                                                                                                                                            
Out[4]: Any
```

Perviously, `List[Any]` resulted in the `FastPrimitiveCoder` coder, so even though the hint was wrong, the data was properly round-tripped.  After this change, the coder became `IterableCoder[FastPrimitiveCoder]` and so it failed, because the data was in fact `bytes` (The _actual_ return type of `rotate_key` is `Tuple[bytes, bytes]`).

Personally, it seems like an overreach to infer that `key[-1:] + key[:-1]` is a `List`.

**Comment by robertwb** [comment]
Thanks for tracking this down. https://github.com/apache/beam/pull/9486

**Comment by robertwb** [comment]
Run Python PreCommit

**Comment by chadrik** [comment]
wow, Python PreCommit takes _forever_

**Comment by chadrik** [comment]
yay, it works!

**Comment by robertwb** [comment]
Long queue...

**Pull request merged**
