### PR TITLE
[BEAM-3966] Move `sdks/java/fn-execution` to `util/java/fn-execution`

### PR DESCRIPTION
**Pull request by bsidhom**
This also renames the Java package itself to match the new module name.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by bsidhom** [comment]
R: @tgroh

**Comment by tgroh** [comment]
LGTM; R: @kennknowles as I know you also dislike 'util' as a name, but it seems reasonable here

**Comment by lukecwik** [comment]
Can we defer doing moves/renames like this till we are further along?

This will cause a bunch of pain for people integrating back changes on hacking branches.

**Comment by kennknowles** [comment]
LGTM.

True that I generally dislike `util` as a name because it is extremely unspecific / meaningless and usually ends up containing ~everything. The Java libraries are a good example. If you went with `everything` it would make it clear that the prefix is not useful. I often go with `misc` to indicate that things that are _not_ `misc` should gradually move out once they have a real theme.

In this case, having a bucket for "everything not SDK or runner" seems useful, so I'm fine with it.

**Comment by kennknowles** [comment]
Looks like about 27 days of conflicts there. Can you rebase?

**Comment by kennknowles** [comment]
It might be helpful to coordinate with a committer on Slack just to time this. Since the move is approved, you could just re-automatically-do-it and get it in within a couple minutes.

**Comment by bsidhom** [comment]
OK. I though it was still contentious, but if things look good as they are, I'll rebase and ping someone when it's ready for merging.

**Pull request closed without merging**
