### PR TITLE
[release-2.19.0][BEAM-9144] Beam's own Avro TimeConversion class in beam-sdk-java-core

### PR DESCRIPTION
**Pull request by iemejia**
A cherry pick that fixes an issue reported by an incompatibility with Avro versions reported by an user on dev@

R: @boyuanzz 
CC: @suztomo

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by boyuanzz** [comment]
Thanks Ismaël!  Has this commit been included in the master branch?

**Comment by boyuanzz** [comment]
Okay I found these 2 commits in the master branch:

- https://github.com/apache/beam/commit/0983792f51747378bd8664f3a134b7ddb8fbd625#diff-145f60794b76e622185950a746fec215

- https://github.com/apache/beam/commit/709aab419ce7c55de353a6a8d9263cdcb24c2496#diff-145f60794b76e622185950a746fec215

**Comment by iemejia** [comment]
Yes, it was merged via PR #10628 Thanks for merging @boyuanzz !

**Pull request merged**
