### PR TITLE
[BEAM-6821] FileBasedSink improper paths

### PR DESCRIPTION
**Pull request by gkovelman**
File path generated in open_writer method is not according to target filesystem, because os.path.join is used and not FileSystems.join.
This created incompatibilities between, for example, Windows and GCS.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by gkovelman** [comment]
R: @tvalentyn

**Comment by gkovelman** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
Thanks, @gkovelman . I didn't look why the test failed for this PR, but we might need to wait for a rollback to be merged: https://github.com/apache/beam/pull/8059.

**Comment by gkovelman** [comment]
Run Python PreCommit

**Comment by gkovelman** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by gkovelman** [comment]
Run Python PreCommit

**Comment by gkovelman** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Please take a look at test failures: Click on Details -> Gradle Build Scan.

There is a lint error and a test failure. 

To run an individual test locally see: https://cwiki.apache.org/confluence/display/BEAM/Contribution+Testing+Guide#ContributionTestingGuide-HowtorunPythonunittests

Perhaps that's a flake.

**Comment by gkovelman** [comment]
Run Python PreCommit

**Comment by gkovelman** [comment]
Run Python PostCommit

**Comment by gkovelman** [comment]
@tvalentyn It's fixed now

**Comment by tvalentyn** [comment]
Ping @chamikaramj

**Comment by tvalentyn** [comment]
Sorry, @gkovelman, looks like this PR fell off the radar - please ping the PR thread if you don't receive a response within couple of days.

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Python PostCommit

**Pull request merged**
