### PR TITLE
Use writer schema only for BigQueryIO Read API

### LINKED ISSUE #23541: BigQuerySamplesIT.testTableIO is breaking in Java PostCommits
### What happened?

beam_PostCommit_Java_DataflowVX and beam_PostCommit_Java_Dataflow_Examples_Dataflow_V2_X are failing due to the following exception:
`
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.VerifyException: Expected Decimal logical type
`

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

### PR DESCRIPTION
**Pull request by kkdoon**
This PR fixes #23541
 
PR [22718](https://github.com/apache/beam/pull/22718) updated the behavior of BigQueryIO **read** and **readTableRows** API where it uses both the Avro writer and reader schema to decode BigQuery elements. However, before this change, these APIs only relied on the writer schema to deserialize elements. The issue with using reader schema is that its derived via the `BigQueryAvroUtils.toGenericAvroSchema` function that does not correctly handle _TableFieldSchema -> Avro schema_ conversion for Avro schemas containing LogicalTypes.

R: @steveniemitz 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [X] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by steveniemitz** [comment]
Can we get unit test coverage on this case as well?  I still don't completely understand how this fixed it (or how it broke in the first place).

**Comment by steveniemitz** [comment]
ah I see, before we were passing a parseFn so it was bypassing the validation that we needed to have a schema.  It seems like that coder from AvroSource is never actually used in our case, but I understand why the validation would be there in general.

Fixing `toGenericAvroSchema` seems like a good solution no matter what, but for now what you have here I think makes a lot of sense as a work around until we can fix the root cause.

**Comment by kkdoon** [comment]
> ah I see, before we were passing a parseFn so it was bypassing the validation that we needed to have a schema. It seems like that coder from AvroSource is never actually used in our case, but I understand why the validation would be there in general.
> 
> Fixing `toGenericAvroSchema` seems like a good solution no matter what, but for now what you have here I think makes a lot of sense as a work around until we can fix the root cause.

sounds good, let me update the toGenericAvroSchema logic and try adding a unit test for the same.

**Comment by steveniemitz** [comment]
@ahmedabu98 thoughts on landing this now to get things back to working, then follow up with fixing the root cause later?

**Comment by ahmedabu98** [comment]
@steveniemitz SGTM

**Comment by steveniemitz** [comment]
cool, the failing postcommit tests are unrelated to this now.

**Review by steveniemitz — APPROVED** [review]

**Pull request merged**
