### PR TITLE
Eliminate nullness errors from GenerateSequence

### PR DESCRIPTION
**Pull request by kennknowles**
The inconsistent nullness annotations on the autovalue for GenerateSequence cause nondeterministic code generation. This in turn made it impossible to get to the point of reproducing a flake I was tracking down.

This PR simply eliminates the existing nullness errors and makes this particular file consistent, removing the suppression of the type checker.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
LGTM

**Comment by reuvenlax** [comment]
Unfortunately this PR seems to have broken tests :( Somehow it's caused AutoValue to decide that maxReadTime was a required parameter, which was not the case before).

**Comment by kennknowles** [comment]
Amusingly, that is exactly why I opened this PR. Previously, local to my machine, autovalue decided that `maxReadTime` (and all the others) were required parameters.

**Comment by kennknowles** [comment]
Is there a revert or a forward fix I can LGTM?

**Comment by kennknowles** [comment]
Here is an existing autovalue issue that is what happened here: google/auto#1338

**Pull request merged**
