### PR TITLE
Large set of mechanical changes after switch to Java8

### PR DESCRIPTION
**Pull request by jkff**
Performed these cleanups mechanically using IntelliJ's "clean up code" feature:
* Replace anonymous classes with lambdas
* Remove explicit type arguments (Java8 has better type inference)

Ran google-java-format-diff to reformat changed statements after each.

Plus a very small number of manual cleanups where the above mechanical transformations were buggy and lead to a compile error or a test failure (lambdas lose more type information than anonymous classes, we'll need to address that later). No semantic changes anywhere.

### CODE REVIEW

**Comment by jbonofre** [comment]
That's great one ! Can you please resolve the conflict on `BigtableIO` ? Thanks !

**Comment by jkff** [comment]
I expect that conflicts will keep appearing while this PR is reviewed because it affects nearly every file in Beam; I'd like to avoid re-triggering the test suite every time that happens, I'd rather do it once during merge.

**Comment by kennknowles** [comment]
:lgtm: I looked at enough bits to get a sense of the mechanical changes. Looks like history could be squashed. I made a comment on one that wasn't actually more helpful. You could fix now or later. I think going back over the examples is a good idea, to make sure they are as nice as can be. But after this PR is fine.

---

Reviewed 61 of 653 files at r1.
Review status: 61 of 653 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[examples/java/src/main/java/org/apache/beam/examples/complete/TopWikipediaSessions.java, line 115 at r1](https://reviewable.io:443/reviews/apache/beam/4470#-L3dh5i-xvECs6J0xkCN:-L3dh5i0FH_6LUzWhp02:b-regts1) ([raw file](https://github.com/apache/beam/blob/d220663ae4b7a22ff7a3d97f0627b243020fabc4/examples/java/src/main/java/org/apache/beam/examples/complete/TopWikipediaSessions.java#L115)):*
> ```Java
>               Top.of(
>                       1,
>                       (SerializableComparator<KV<String, Long>>)
> ```

This particular change does not seem like a great improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4470#-:-L3djT-WCKrCAdIDT_3r:bnqgsns)*

**Comment by jkff** [comment]
Thanks Kenn - I fixed that example and some formatting issues in MinimalWordCountJava8.

**Pull request merged**
