### PR TITLE
Add boilerplate Java21 security properties support for Java SDK containers

### PR DESCRIPTION
**Pull request by cwrothrock**
Changes:

* Add Java version-specific override to the security property jdk.tls.disabledAlgorithms via a container image meta option. Noting that the property value is derived from openjdk 21-ea and this action does not reflect that a Beam SDK container officially supporting Java 21 is available. 

See #24619 for more historical context. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by cwrothrock** [comment]
Run Java PreCommit

**Comment by cwrothrock** [comment]
R: @kennknowles

**Comment by Abacn** [comment]
@cwrothrock is this ready to merge or wait until Java 21 official release?

**Comment by cwrothrock** [comment]
Yes this can be merged, as the existence of the folder/files should not affect any container builds since there is no gradle or dockerfile for Java 21.

**Pull request merged**
