### PR TITLE
Copy PR5987: Fix synthetic javadoc and spotlessJava broken for release build

### PR DESCRIPTION
**Pull request by boyuanzz**
(cherry picked from commit 9c67bc8)

r: @aaltay

### CODE REVIEW

**Comment by pabloem** [comment]
./gradlew publish

**Comment by pabloem** [comment]
Run Gradle Publish

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Always failed on org.apache.beam.examples.WordCountIT.testE2EWordCount. Seems like job got stuck: 
https://builds.apache.org/job/beam_PreCommit_Java_Phrase/63/console

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
The issue here is that the container is not yet created. Merging.

**Pull request merged**
