### PR TITLE
[BEAM-1385] Add license header to website Jenkins job descriptions

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
Because this unbreaks the build, I am going to merge before review.

**Comment by kennknowles** [comment]
R: @davorbonaci

**Comment by kennknowles** [comment]
(or any committer, since we are now switching which side of the Earth is in daylight :-)

**Comment by davorbonaci** [comment]
LGTM.

Thanks @kennknowles; much appreciated. FYI @jasonkuster.

**Comment by jasonkuster** [comment]
@peihe created #1911 to fix too, looks like this got in before his.

**Pull request merged**
