### PR TITLE
TImeout StreamingDataflowWorkerTest when test stuck

### PR DESCRIPTION
**Pull request by Abacn**
mitigate #28957

A testing PR #23785 found a stuck test path

```
Class org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest

testActiveThreadMetric[0: [streamingEngine=false]]
org.junit.runners.model.TestTimedOutException: test timed out after 600 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest.testActiveThreadMetric(StreamingDataflowWorkerTest.java:2850)
...
```

this would make the test under this test class timeout after 600s, instead the whole test suite hanging indefinitely

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @ahmedabu98
CC: @kerrydc

**Comment by Abacn** [comment]
e.g. this happened again in jenkins: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/28702/

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by edman124** [comment]
The notify could be called before we enter the synchronized block causing wait to wait indefinitely, this test should be fixed in https://github.com/apache/beam/pull/29041
LGTM as a temporary stopgap

**Pull request merged**
