### PR TITLE
[BEAM-3480] use build $WORKSPACE as pkb temp_dir

### PR DESCRIPTION
**Pull request by DariuszAniszewski**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java CompressedTextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TFRecordIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java CompressedTextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TFRecordIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java CompressedTextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Seed Job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java CompressedTextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TFRecordIO Performance Test

**Comment by DariuszAniszewski** [comment]
@chamikaramj @alanmyrvold As mentioned in #4416 this change is ready. As you can see above, tests are running properly on various workers, including the ones with former permission denied issue and pip install issues. PTAL

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Can you squash the commits into a single commit ?

**Comment by DariuszAniszewski** [comment]
@chamikaramj sure - done. PTAL

**Comment by chamikaramj** [comment]
Thanks. 

Retest this please

**Pull request merged**
