### PR TITLE
[DO NOT MERGE] [BEAM-4775] Second take on portable metrics over the job-server API

### PR DESCRIPTION
**Pull request by ryan-williams**
Umbrella PR tracking metrics over the job API, cf. https://s.apache.org/get-metrics-api.

### [Here is a direct link to what's in this PR but not yet rebased on top of component PRs below](https://github.com/ryan-williams/beam/pull/3).

[](https://github.com/ryan-williams/beam/pull/3/commits)

Progress!

### Approved / Ready to merge:
- #7890: consolidate MetricResult implementations
- #7883: Add MetricQueryResults.allMetrics() helper

### Iterating / Discussing
- #7868: MonitoringInfo URN tweaks
- #7876: Clean up metric protos; support integer distributions, gauges

### Holding pattern: java-core dependency-graph questions
- #7867: make `MetricResult`'s "key" explicitly a `MetricKey`, and route call-sites through that API (in preparation for expanding a `MetricKey` to encompass pcollection-scoped "system" metrics)

### Merged
- #7866: move function helpers from fn-harness to sdks/java/core

cc @robertwb @ajamato the factored-out PRs above are ready for review

## Likely pieces still to be factored out:
- fully supporting MonitoringInfo data types ({URN, labels}) inside `MetricKey` (comprised of `MetricName`,`MetricLabels`)
- adding the job-API metrics RPC
- python support

## Summary

- implements counter, distribution, and gauge metrics over the Job API
  - "int" versions only; removed "double" versions
  - works in Java; I think some of them may still be TODO in Python 
  - main RPC looks similar to that in the design doc, but adds an extra `MetricResults` proto that wraps "attempted" and "committed" lists of MonitoringInfos
- bypasses a lot of proto-additions and moves from #7641 that caused some `import`-thrashing
  - moving metrics-related protos to their own file/package may still make sense
  - this PR is a net remover of metric protos, so on balance I decided saving such a move for later is OK
- creates Java SDK counterparts of various MonitoringInfo components:
  - MetricKey ≈ MonitoringInfo ({URN, labels map})
  - MetricName ≈ URN
  - MetricLabels ≈ labels map
- encodes that metrics today must either be PTRANSFORM- or PCOLLECTION-scoped (not both)
- consolidates `MetricResult`s, and attempted/committed metrics logic, across all runners

## TODO
- Make sure all the metric types are being surfaced in Python.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by ryan-williams** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by ajamato** [comment]
I'm not sure if you want me to review this one or not. This PR is a bit massive.

Is this the one that introduces the new layer to extract the new MonitoringInfo metrics over an RPC?
https://s.apache.org/get-metrics-api

**Comment by ryan-williams** [comment]
> I'm not sure if you want me to review this one or not. This PR is a bit massive.

Yea, there are probably 4 chunks I will still pull out of this into separate PRs, that are hopefully more manageable:
- consolidating MetricResult implementations
  - already out at #7890, though I need to fix a couple tests
  - I haven't had a chance to factor those changes out of this PR yet
- fully supporting MonitoringInfo data types ({URN, labels}) inside `MetricKey` (comprised of `MetricName`,`MetricLabels`)
- adding the job-API metrics RPC
- python support

In the meantime, [this link will show all the changes that still live only in this PR](https://github.com/ryan-williams/beam/compare/octo...ryan-williams:mk); this PR's main view still displays all the changes it is rebased on top of.

> Is this the one that introduces the new layer to extract the new MonitoringInfo metrics over an RPC?
https://s.apache.org/get-metrics-api

Yea, that is in here! Swimming to the surface…

**Comment by ryan-williams** [comment]
(I've updated the PR description above with the latest state of the world, and will keep it up to date as things change)

**Comment by ryan-williams** [comment]
I've moved all the info in this PR's description to [BEAM-4775](https://issues.apache.org/jira/browse/BEAM-4775), which is probably a better place to track the state of this work! Closing this and adding a note to this effect to the title message.

**Pull request closed without merging**
