### PR TITLE
Revert "[BEAM-14084] iterable_input_value_types changed from list to iterable"

### PR DESCRIPTION
**Pull request by tvalentyn**
Reverts apache/beam#17066

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @lukecwik

**Comment by aaltay** [comment]
Is this also in the release branch?

/cc @youngoli

**Comment by tvalentyn** [comment]
@aaltay it's not.

**Comment by tvalentyn** [comment]
ping. still waiting for an LGTM.

**Review by ryanthompson591 — APPROVED** [review]
So if this is something we shouldn't do, what do you think about just removing the todo.

**Comment by tvalentyn** [comment]
It still sounds like the right thing to do, however it causes a breaking change, so we would need to document the breaking change in CHANGES.MD. Given that we have the opportunity to onboard this change to the internal customers first, I would suggest to do that first, as it could allow us to better word the recommendations for the external users.

**Pull request merged**
