### PR TITLE
[BEAM-4691] (do-not-merge-yet!) Move perf tests to a separate directory and rename them (conventionally)

### PR DESCRIPTION
**Pull request by lgajowy**
This PR renames and reorganizes jenkins Job definitions in ./test_infra/jenkins directory
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Spark
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
I did a small test in order to check if we can refactor the code this way (split to directories, change to CamelCase). Below are some things I've found out:

1. I am not sure if I can change the job_00_seed.groovy name. Jenkins didn't change the glob pattern used to search for other job definitions when the name was `Seed.groovy` (like it wasn't able to find the seed job when it's name changed). Am I missing something here? Is path to seed job hardcoded in the workspace/jenkins config (see: [the seed job run that cannot find jobs using the old "job_" pattern](https://builds.apache.org/view/A-D/view/Beam/job/beam_SeedJob/2133/console)).

2. I cannot import CommonProperties everywhere when the directory structure is more than 1 level deep. This is described here:  [LINK](https://github.com/jenkinsci/job-dsl-plugin/wiki/Real-World-Examples#import-other-files-ie-with-class-definitions-into-your-script). I will try to simplify the directory tree to be one level and check if it works for our case.

3. I think we should split the CommonProperties file (former common_job_properties). It's a "god object" to me and knows way too much.

Another good thing of having directories would be the possibility to hide PreCommitBuilder in pre_commit directory (and so on) - so this is more than just clean structure. 

CC: @kennknowles @swegner request for comments :)

**Comment by swegner** [comment]
This is awesome, thanks for working on this. A couple thoughts:

> 1. I am not sure if I can change the job_00_seed.groovy name.

I suspect this is a bootstrapping problem. i.e., remember that when you run the seed job, it's running the currently configured job from `master`, and generating and publishing new job definitions from it. The currently published job looks for `job_*`, so you might need a two-step process, i.e.:

1. Rename the files as planned, but also keep the original `job_00_seed.groovy` version, and in that file add both glob patterns
2. Run that job to generate the new seed job definition
3. Once your change is merged to master and the new seed job is successfully running, submit the change to remove the old seed job.

> 2. I cannot import CommonProperties everywhere when the directory structure is more than 1 level deep. 

Bummer. thanks for investigating this.

> 3. I think we should split the CommonProperties file (former common_job_properties). It's a "god object" to me and knows way too much.

+:100: Any improvements we can make to this code is welcome. I recently stumbled up this page on [Design patterns in Groovy](http://groovy-lang.org/design-patterns.html)


CC @Ardagan

**Comment by lgajowy** [comment]
@swegner @Ardagan  ok, today I learned a little bit more about the possibilities we have. I've done another PR to dig into this from a different angle (https://github.com/apache/beam/pull/5915). 

__I think we cannot have both:__ directories and common files. I successfully moved `HadoopInputFormatIOIT` to a separate directory but no matter what I tried (keeping CommonProperties in .jenkins and import or moving it to a "common" directory and then import) I couldn't run the seed job successfully. 

One last idea that comes to my mind is to merge job files that have the same category. We would then have `PerformanceTests.groovy`, `PostCommit.groovy`, `PreCommit.groovy`, etc. I consider this idea because: 
 - we could have multiple jobs per one file
 - we could extract some handy methods for creating jobs per each category. Such methods could be hidden in corresponding files (eg. method for creating a post-commit job would reside in PostCommit.groovy class)
 - because we're using groovy here, methods for creating jobs could accept a map as a parameter. Such map can be very readable and clean. We do something like this in [FileBasedIOIT](https://github.com/apache/beam/blob/master/.test-infra/jenkins/job_PerformanceTests_FileBasedIO_IT.groovy)
 - we could keep stuff like CommonProperties etc. where it is now and use it as before. At the same time, category specific methods can remain hidden in categories' files (eg. kubernetes related methods could be hidden in a PerformanceTests.groovy file). 

The drawbacks I see: 
 - it may be harder to find a specific job in a common file
 - it may be easier to break many things at once due to common code (IMO, we're vulnerable to this either way)
 - ???

WDYT? I ask for your opinions first because you recently worked on some refactoring and maybe have some thoughts in this matter.

**Comment by lgajowy** [comment]
I am also considering this as an alternative solution, but it would require much more effort (maybe worth it): https://jenkins.io/doc/book/pipeline/jenkinsfile/

**Comment by Ardagan1** [comment]
Hi Łukasz,
Thank you for looking into this. Out of what I've seen so far: 

If we stay in current JobDSL world: 
I like your idea to generalize code for common job categories and define jobs via methods that accept map as parameters. If we can extract that map into separate file, that would be even better. 

Current amount of files is just too huge for amount of work that is done. In the state of pre- and post- commit world it already moves in the direction of splitting job definition into logic and data files. I believe finishing this work would be a good thing to do.

If we move to jenkinsfile world:

I believe it is worth at least looking into before rejecting. Main reasons I would vote for switching to jenkinsfile is that it is jenkins native way of doing things. 

Good [write up](https://marcesher.com/2016/08/04/jenkins-as-code-comparing-job-dsl-and-pipelines/) is mentioned on [job dsl wiki](https://github.com/jenkinsci/job-dsl-plugin/wiki/Talks-and-Blog-Posts).

My opinion is that we should give jenkinsfile a try and make decision based on estimated amount of work required.

One of the starting points can be [auto-convert plugin](https://wiki.jenkins.io/display/JENKINS/Convert+To+Pipeline+Plugin) that converts free-style jobs to jenkins pipeline.

We can first try it on combination of forked repo and local jenkins docker instance to be safe.

**Comment by lgajowy** [comment]
@Ardagan1 thanks for all the ideas and links you posted! I agree with all your points.

I saw on the mailing list that you have a tutorial on spinning up Jenkins via Docker - really looking forward to this! While we have it it will be totally safe to test the options that are left (Jenkins files) and decide which way is best.  I'll stay tuned. 

Meanwhile, I'm closing this PR (nothing more to do here).

**Comment by Ardagan** [comment]
@lgajowy The doc is work-in progress. Dumped docs in my fork for now, will move them to corresponding wiki once we come up with one. Please see it here:
https://github.com/Ardagan/beam/blob/JenkinsDoc/devdocstemp/jenkins.md

Feel free to update doc if you find any bugs.

**Pull request closed without merging**
