### PR TITLE
[BEAM-8606][BEAM-13029][BEAM-10713][BEAM-8607][BEAM-7369] Allow more recent testing utilities

### PR DESCRIPTION
**Pull request by TheNeuralBit**
pytest, pytest-timeout, pytest-xdist, mock, and tenacity (used for retrying tests) are all restricted to at least one major version behind the latest. This PR upgrades them all.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Run Python 3.8 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python 3.8 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python PreCommit

**Comment by robertwb** [comment]
Looks like there's merge conflicts that now need to be resolved.

**Pull request closed without merging**
