### PR TITLE
[BEAM-14065] Upgrade vendored bytebuddy to version 1.12.8

### PR DESCRIPTION
**Pull request by cushon**
R: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.

**Comment by aaltay** [comment]
What is next on this PR?

**Comment by cushon** [comment]
@aaltay https://github.com/apache/beam/pull/17028 needs to be merged first, and then I think a release of the vendored copy of bytebuddy needs to be made

**Comment by cushon** [comment]
I rebased this past https://github.com/apache/beam/commit/0b37864eeb299bd84db066d5bf495b44cc8f3a64.

> The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.

What is the process for releasing the new vendored version?

**Comment by lukecwik** [comment]
> I rebased this past [0b37864](https://github.com/apache/beam/commit/0b37864eeb299bd84db066d5bf495b44cc8f3a64).
> 
> > The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.
> 
> What is the process for releasing the new vendored version?

See https://github.com/apache/beam/blob/master/vendor/README.md, specifically http://s.apache.org/beam-release-vendored-artifacts

**Comment by cushon** [comment]
> > I rebased this past [0b37864](https://github.com/apache/beam/commit/0b37864eeb299bd84db066d5bf495b44cc8f3a64).
> > > The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.
> > 
> > 
> > What is the process for releasing the new vendored version?
> 
> See https://github.com/apache/beam/blob/master/vendor/README.md, specifically http://s.apache.org/beam-release-vendored-artifacts

Thanks, is that something you or someone else could help with? It looks like it require some one-time setup, and permissions I don't have (e.g. to create release branches).

**Comment by lukecwik** [comment]
> > > I rebased this past [0b37864](https://github.com/apache/beam/commit/0b37864eeb299bd84db066d5bf495b44cc8f3a64).
> > > > The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.
> > > 
> > > 
> > > What is the process for releasing the new vendored version?
> > 
> > 
> > See https://github.com/apache/beam/blob/master/vendor/README.md, specifically http://s.apache.org/beam-release-vendored-artifacts
> 
> Thanks, is that something you or someone else could help with? It looks like it require some one-time setup, and permissions I don't have (e.g. to create release branches).

I cannot at this time. You'll want to ask on dev@beam.apache.org for a committer or PMC to help.

**Comment by cushon** [comment]
> > > > I rebased this past [0b37864](https://github.com/apache/beam/commit/0b37864eeb299bd84db066d5bf495b44cc8f3a64).
> > > > > The reason you are having a bad time in the CI results is that actually we need to create and release the new vendored version first. Unfortunately we don't have monorepo magic around this.
> > > > 
> > > > 
> > > > What is the process for releasing the new vendored version?
> > > 
> > > 
> > > See https://github.com/apache/beam/blob/master/vendor/README.md, specifically http://s.apache.org/beam-release-vendored-artifacts
> > 
> > 
> > Thanks, is that something you or someone else could help with? It looks like it require some one-time setup, and permissions I don't have (e.g. to create release branches).
> 
> I cannot at this time. You'll want to ask on [dev@beam.apache.org](mailto:dev@beam.apache.org) for a committer or PMC to help.

Thanks, done: https://lists.apache.org/thread/246qgvp55kzcmwn7xorxwylzt9nqh5z4

**Comment by aaltay** [comment]
What is the next step on this PR? Should it be closed based on the mailing list discussion?

**Comment by cushon** [comment]
> What is the next step on this PR? Should it be closed based on the mailing list discussion?

Yes, thanks--it sounds like there may be a path forward for the alternative in https://github.com/apache/beam/pull/17317, so I'll close this for now.

**Pull request closed without merging**
