### PR TITLE
Add @yields_batches and @yields_elements

### LINKED ISSUE #21656: Add @DoFn.yields_batches and @DoFn.yields_elements decorators to override defaults
Imported from Jira [BEAM-14293](https://issues.apache.org/jira/browse/BEAM-14293). Original Jira may contain additional context.
Reported by: bhulette.
Subtask of issue #21650

### PR DESCRIPTION
**Pull request by TheNeuralBit**
This PR adds two new decorators, `@yields_batches` and `@yields_elements`, which override the default interpretation for the output of `DoFn.process` and `DoFn.process_batch`. These decorators are handled via changes to `OutputProcessor` (now renamed to `OutputHandler` for clarity), which branches depending on whether batches or elements are expected in the `results` iterable.

Where possible, common logic in `OutputHandler` was extracted into private helper methods that are re-used. The .pxd definition for these methods indicates they should be inlined in cython-generated code so they don't affect performance.

Fixes #21656

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Despite the inlining this PR seems to have a minor effect (0.1-0.2 microseconds/element) on map_fn_microbenchmark`, presumably due to the new branch.  Benchmarks on my desktop with Intel Xeon W-2135 CPU. 

c77971053d2e:
```
Fixed cost   1.6063439090633391                                                                                                                                                                                                         Per-element  7.317467689514159e-07                                                                                  
R^2          0.9972847477152673
```

This PR:
```
Fixed cost   1.630842854329745
Per-element  7.487253376931855e-07
R^2          0.998137270424781
```

**Comment by robertwb** [comment]
The "per element" line seems to be missing from the benchmarks. What is the relative difference?

**Comment by TheNeuralBit** [comment]
Apologies, somehow the formatting was such that the per-element line was hidden after a bunch of spaces. It's there now.

**Comment by robertwb** [comment]
Thanks. The difference looks more like 0.01-0.02 microseconds, or a couple percent, which is more acceptable.

**Comment by TheNeuralBit** [comment]
retest this please

**Comment by TheNeuralBit** [comment]
Run Portable_Python PreCommit

**Comment by TheNeuralBit** [comment]
Run PythonDocker PreCommit

**Comment by TheNeuralBit** [comment]
Run PythonDocker PreCommit

**Comment by TheNeuralBit** [comment]
Run Portable_Python PreCommit

**Review by robertwb — APPROVED** [review]

**Pull request merged**
