### PR TITLE
Update google-api-services versions.

### PR DESCRIPTION
**Pull request by tysonjh**
Update google-api-services* versions and google-client version to latest.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tysonjh** [comment]
retest this please

**Comment by tysonjh** [comment]
Ah, seems like there are failures i'll need to resolve. No need to review  yet.

**Comment by tysonjh** [comment]
Breakages were due to major version bumps -- woops -- minor version bumps are available and resolve the issues.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by tysonjh** [comment]
Hard to tell what the precommit failure is from the logs or scan. It references a local file on the Jenkins agent. I'll run locally.

https://scans.gradle.com/s/opclpkpolskh6/console-log?anchor=20400

**Comment by kennknowles** [comment]
https://scans.gradle.com/s/opclpkpolskh6/tests/:sdks:java:io:google-cloud-platform:test/org.apache.beam.sdk.io.gcp.pubsub.PubsubJsonClientTest/pullOneMessage#1

**Comment by kennknowles** [comment]
Notably, the failing test does a bunch of mocking. So I wouldn't assume anything is actually wrong.

**Comment by kennknowles** [comment]
But it also probably isn't a flake, since it is a pretty simple unit test. Most likely the assumptions of the mock were overconstrained so changes in the Pubsub client library can break it.

**Comment by tysonjh** [comment]
run java postcommit

**Comment by tysonjh** [comment]
More test failures. NPEs in what seems like unrelated code, but notably the pubsub one again which passes locally when I run it for some reason.

**Comment by tysonjh** [comment]
rerun java precommit

**Comment by tysonjh** [comment]
run java precommit

**Comment by tysonjh** [comment]
No, my mistake. It fails locally too, I was running it incorrectly.

**Comment by tysonjh** [comment]
R: @apilloud 

Could you take a look at this please?

**Comment by apilloud** [comment]
LGTM. There is a script `sdks/java/build-tools/beam-linkage-check.sh` that is suppose to validate version changes don't introduce new compatibility issues. Can you run it and ensure it passes?

**Comment by tysonjh** [comment]
Failed to publish publication 'mavenJava' to repository 'mavenLocal'
> Invalid publication 'mavenJava': supplied version does not match POM file (cannot edit version directly in the POM file).

Not sure what this means, will need to investigate unless you know.

**Comment by tysonjh** [comment]
> Failed to publish publication 'mavenJava' to repository 'mavenLocal'
> 
> > Invalid publication 'mavenJava': supplied version does not match POM file (cannot edit version directly in the POM file).
> 
> Not sure what this means, will need to investigate unless you know.

May just need to run a ./gradlew clean (https://issues.apache.org/jira/browse/BEAM-9437). Trying that.

**Comment by tysonjh** [comment]
> > Failed to publish publication 'mavenJava' to repository 'mavenLocal'
> > > Invalid publication 'mavenJava': supplied version does not match POM file (cannot edit version directly in the POM file).
> > 
> > 
> > Not sure what this means, will need to investigate unless you know.
> 
> May just need to run a ./gradlew clean (https://issues.apache.org/jira/browse/BEAM-9437). Trying that.

What a mess. I spent a good amount of time, ~3hr or so, trying to get the beam-linkage-check.sh to work. I ran into numerous issues from a problem with the ':sdks:java:bom:publishMavenJavaPublicationToMavenLocal' task, problems building flink tests for 1.8 and 1.9, apex runner tasks executing even though the runner is gone, major/minor version mismatches in Java classes, unsupported errorprone versions. I reached out to a @lukecwik and@apilloud for help as well (thank you both).

What worked in the end:
  * ensure using Java 8 (both binary and classpath)
  * a fresh new clone of apache/beam

https://gist.github.com/tysonjh/d8d28689fc18b536b32498cb0fd27382

**Comment by tysonjh** [comment]
> @tysonjh Hey, Seems like this commit breaks my code. Building my code, I get a `NoSuchMethodError` over `setOrderingKey`/`getOrderingKey` for the `pubsubMessage` (the `protoMessage` methods do exist). I will be happy to understand what do I miss, and whether there is a referrer to a solution for my problem. 10x!

What version of the pubsub library are you using?

**Pull request merged**
