### PR TITLE
[release] Revert "[BEAM-5442] Pass SDK-unknown PipelineOptions to Runner"

### PR DESCRIPTION
**Pull request by mxm**
As for the previous releases, we are reverting PRs #6557 #6589 #6600 due to a
mailing list discussion: https://lists.apache.org/thread.html/78fe33dc41b04886f5355d66d50359265bfa2985580bb70f79c53545@%3Cdev.beam.apache.org%3E

This reverts commit f274757e53d811e49575dcbefd4e8864f92cc96c.
This reverts commit 9ae79fe40c09ef9d0ce5cfd54820ba88dabac52c.
This reverts commit db1e6a1c79e44b7026e78d4f0df168234a13eed7.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Portable Python fails with ```ImportError: No module named tenacity```. It runs fine on my machine.

No idea why ```:beam-sdks-python-precommit-dataflow:precommitIT``` fails, possible the same reason.

**Comment by kennknowles** [comment]
Run Portable_Python PreCommit

**Comment by kennknowles** [comment]
Run Python PreCommit

**Comment by kennknowles** [comment]
I'm hoping to get green for the release merge. Should this also get into `master`?

**Comment by mxm** [comment]
> Should this also get into master?

No, as per mailing list discussion we decided to leave this in master as some of our users depend on this. A solution is being worked for the next release.

**Comment by mxm** [comment]
This is essentially the same as https://github.com/apache/beam/pull/6675. It looks like the option parsing that is reverted here is required by the failing tests.

**Comment by mxm** [comment]
https://jira.apache.org/jira/browse/BEAM-6469

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
Looks indeed like we depend on the reverted feature. Will add the missing PipelineOptions to the Python SDK.

**Comment by mxm** [comment]
I am not sure why `:beam-sdks-python-precommit-dataflow:precommitIT` fails. Someone from Dataflow maybe can chime in here?

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
Doesn't seem to be flaky. Previously only `:beam-sdks-python-precommit-dataflow:precommitIT` failed. Now it's also the linting and unit tests due:
```no such option: --process-dependency-links```

**Comment by kennknowles** [comment]
Failure looks like https://issues.apache.org/jira/browse/BEAM-6489

**Comment by mxm** [comment]
Cherry-picked the commit fixing it. Let's see if Python PreCommit passes.

**Comment by mxm** [comment]
That brings us back to 

```19:56:56 > Task :beam-sdks-python-precommit-dataflow:precommitIT FAILED``

Can't really see an error besides it timing out.

**Comment by kennknowles** [comment]
Yea, I don't see anything informative in the job's logs either.

**Comment by kennknowles** [comment]
Ah, this is just a case of very bad error messaging / logging. The problem is missing Dataflow worker image.

**Comment by kennknowles** [comment]
You have to follow the link to the StackDriver logs to discover this.

**Comment by mxm** [comment]
Do we want to fix the missing image or assume this is working working correctly since all other tests pass?

**Comment by kennknowles** [comment]
I am fixing the image now, but I am happy to merge this, too. Final verification suffices.

**Comment by mxm** [comment]
Thanks!

**Pull request merged**
