### PR TITLE
[BEAM-1038] Rollforwards "Allow stateful DoFn in DataflowRunner""

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

This rolls forward 42bb15d, allowing stateful DoFn in DataflowRunner.

Building full postcommit at https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Dataflow/1974/

### CODE REVIEW

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
Probably should kick off the DataflowRunner RunnableOnService postcommit against this branch, but LGTM

**Comment by kennknowles** [comment]
I did. Link is in the PR description.

**Comment by dhalperi** [comment]
Thanks -- sorry I missed it.

**Comment by kennknowles** [comment]
Building with new worker at https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Dataflow/1982/.

This has already passed all tests repeatedly but looks like there might be some new issue recently introduced. I'll keep track of it.

**Comment by kennknowles** [comment]
My mistake. Build is happy. I'll merge.

**Pull request merged**
