### PR TITLE
[BEAM-2166]  Mark coders using context as experimental.

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @kennknowles

**Comment by robertwb** [comment]
I just saw that Coder was made into an abstract class, which could obviate the need for an intermediate ContextSensitiveCoder class (and make it possible to adapt existing coders gradually over time, possibly post-stable-release if the APIs are appropriately marked). Let me know what you think.

**Comment by robertwb** [comment]
@tgroh

**Comment by kennknowles** [comment]
FWIW we made it an abstract class explicitly to make it easier to adapt. All the usual reasons.

**Comment by robertwb** [comment]
See https://github.com/apache/beam/pull/2930 instead.

**Comment by robertwb** [comment]
Superseded by #2930 and #2933.

**Pull request closed without merging**
