### PR TITLE
Include ffmpeg in Python SDK Docker images

### PR DESCRIPTION
**Pull request by carlthome**
## Background
https://github.com/tensorflow/datasets lets users create versioned datasets for training machine learning (ML) models on raw multimedia data (text, images, audio, video), and [it integrates wonderfully with Beam](https://www.tensorflow.org/datasets/beam_datasets) (and Dataflow).

## Problem
A current pain point in the user journey is that in order to use `tfds.features.Audio` or `tfds.features.Video`, the worker runtime has to have `ffmpeg` available which means that `setup.py` hackery (with `apt-get` commands within it), or prebuilding your own image with e.g. Google Cloud Build is necessary. This significantly worsens the UX for ML engineers who expect that a requirements.txt mentioning `librosa` and `apache_beam` should suffice. Frustrations are especially exacerbated by the fact that DirectRunner development usually just works (since many have `ffmpeg` or equivalent on their development machines), and that these issues surface quite late at runtime.

## Solution?
Thus, I'm curious if we couldn't just include `ffmpeg` in Beam's Docker Hub hosted images, with the goal of making it easier to create large audio and video datasets. Thoughts?

## Examples of user journeys
- https://stackoverflow.com/questions/55581449/installing-ffmpeg-package-from-setup-py-in-apache-beam-pipeline-running-on-goo
- https://stackoverflow.com/questions/45494952/reading-video-during-cloud-dataflow-using-gcsfuse-download-locally-or-write-n
- https://stackoverflow.com/questions/35321113/can-google-cloud-dataflow-apache-beam-use-ffmpeg-to-process-video-or-image-dat
- https://stackoverflow.com/questions/56996028/google-cloud-dataflow-dependencies
- https://stackoverflow.com/questions/45124289/posthoc-connect-ffmpeg-to-opencv-python-binary-for-google-cloud-dataflow-job
- https://lists.apache.org/thread/jhgfb2o3c7ms4mg1qlsgqh470nltoosj :wave:

### CODE REVIEW

**Comment by AnandInguva** [comment]
Since this is one of the may use cases out there where a user needs to install a package that is not available on Pypi, we recommend using a `setup.py`[1] for these dependencies. Even though the packages are not so big, this will still increase the size of Docker container and we want to avoid that. 

Right now, we support installing packages through `pip` but in the future, we have plans to support `conda` then it would provide more flexibility to the users. 


[1] https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/#nonpython

**Comment by carlthome** [comment]
Figured image size was the reasoning, but worth a shot. :smiling_face_with_tear: 

Perhaps there could be a `-slim` variant of tags instead, like how the official Python images does it?

Feels to me like that might be a nicer UX compared to teaching data scientists to build/push Docker images, or requiring Debian specific tricks with setuptools that only seem to confuse people about which `setup.py` is meant for local development, and which is only meant for configuring a remote worker runtime (I've seen this cause confusion before, especially for Mac users).

`conda` sounds like a nice future complement. Looking forward to it! :+1:

**Comment by AnandInguva** [comment]
Yes, slim version seems like a good choice. I recall we had that discussion previously to support slim version for the apache_beam container image. lets see whats the road map for this.

**Comment by AnandInguva** [comment]
Can we close the PR if there isn’t anything else?

**Comment by carlthome** [comment]
> Can we close the PR if there isn’t anything else?

👍

**Comment by robertwb** [comment]
I think the idea of a thin and fat container makes a lot of sense.
Probably worth proposing on the list rather than a PR to pound out the
details.

**Pull request closed without merging**
