### PR TITLE
[BEAM-11659] Allow Kafka sql table provider to have a nested mode and raw binary payloads

### PR DESCRIPTION
**Pull request by dpcollins-google**
This modifies the Kafka sql table provider to have a nested mode like Pub/Sub currently does, that exposes the headers and event timestamp from the record. It also allows the payload field in this mode to be BYTES type, remaining unparsed in this case.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by dpcollins-google** [comment]
R: @amaliujia

**Comment by amaliujia** [comment]
R: @robinyqiu this is a very important change so also requesting review from Robin.

**Comment by robinyqiu** [comment]
cc: @TheNeuralBit as well

**Comment by TheNeuralBit** [comment]
It was my intention to ultimately remove the nested mode from the pubsub table provider, once we had other options for accessing the message publish time and attributes.

See https://lists.apache.org/thread.html/bf4c37f21bda194d7f8c40f6e7b9a776262415755cc1658412af3c76%40%3Cdev.beam.apache.org%3E, and specifically https://lists.apache.org/thread.html/rb83f154846a3a38eae30b667cee52d6b8f0e94769e71b2b7516cb2ce%40%3Cdev.beam.apache.org%3E

**Comment by TheNeuralBit** [comment]
That being said I think there's value in this sort of "raw" mode. In an ideal world, the flattened structure would be a VIEW on the nested/raw version.

**Comment by TheNeuralBit** [comment]
Daniel and I discussed this offline. Some notes:
- It makes sense to just keep both the nested and flattened modes for now. We can easily detect which one the user is trying to use. In the future the "flattened" option should be re-architected to be a view on the nested mode.
- However, we should be aware that with the nested mode users will run up against issues with nested rows until we upgrade calcite (BEAM-9378)

**Comment by robinyqiu** [comment]
Thanks Brian for sharing this info. It makes sense to me to keep both the nested and flattened modes for now.

**Review by robinyqiu — APPROVED** [review]
LGTM. Thanks for working on this!

**Comment by suztomo** [comment]
@dpcollins-google @robinyqiu "SQL Post Commit Tests" has been failing since 2 days ago. I found this PR from the https://ci-beam.apache.org/job/beam_PostCommit_SQL/6022/ . Do you think the test failures are related to this PR?

```
13:14:54 > Task :sdks:java:extensions:sql:integrationTest
13:15:15 
13:15:15 org.apache.beam.sdk.extensions.sql.meta.provider.kafka.KafkaTableProviderIT > testFakeNested[0] FAILED
13:15:15     org.apache.beam.sdk.extensions.sql.impl.ParseException at KafkaTableProviderIT.java:227
13:15:15         Caused by: java.lang.RuntimeException at SqlParseException.java:171
13:15:23 
13:15:23 org.apache.beam.sdk.extensions.sql.meta.provider.kafka.KafkaTableProviderIT > testFakeNested[1] FAILED
13:15:23     org.apache.beam.sdk.extensions.sql.impl.ParseException at KafkaTableProviderIT.java:227
13:15:23         Caused by: java.lang.RuntimeException at SqlParseException.java:171
13:15:32 
13:15:32 org.apache.beam.sdk.extensions.sql.meta.provider.kafka.KafkaTableProviderIT > testFakeNested[2] FAILED
13:15:32     org.apache.beam.sdk.extensions.sql.impl.ParseException at KafkaTableProviderIT.java:227
13:15:32         Caused by: java.lang.RuntimeException at SqlParseException.java:171
13:15:40 
13:15:40 org.apache.beam.sdk.extensions.sql.meta.provider.kafka.KafkaTableProviderIT > testFakeNested[3] FAILED
13:15:40     org.apache.beam.sdk.extensions.sql.impl.ParseException at KafkaTableProviderIT.java:227
13:15:40         Caused by: java.lang.RuntimeException at SqlParseException.java:171
13:15:51 
13:15:51 org.apache.beam.sdk.extensions.sql.meta.provider.kafka.KafkaTableProviderIT > testFakeNested[4] FAILED
13:15:51     org.apache.beam.sdk.extensions.sql.impl.ParseException at KafkaTableProviderIT.java:227
13:15:51         Caused by: java.lang.RuntimeException at SqlParseException.java:171
13:21:21 
13:21:21 55 tests completed, 5 failed
```

**Comment by dpcollins-google** [comment]
Yes, sorry I had Identified the issue here https://github.com/apache/beam/pull/13980/files#diff-5d769184e0be9fad0074aaf1a90eb5eb059148261b1d82161fc11dea74ada4be but forgot to upstream it. Will do so now.

**Comment by suztomo** [comment]
Thank you!

**Pull request merged**
