### PR TITLE
Fix beam_BiqQueryIO_Streaming_Performance_Test_Java

### LINKED ISSUE #23856: [Bug]: beam_BiqQueryIO_Streaming_Performance_Test_Java permared
### What happened?

The last success run was on Jul 28, 2022: https://ci-beam.apache.org/job/beam_BiqQueryIO_Streaming_Performance_Test_Java/4066/

Now write stuck:
```
Operation ongoing in step Write to BQ/StreamingInserts/StreamingWriteTables/StreamingWrite/BatchedStreamingWrite.ViaBundleFinalization/ParMultiDo(BatchAndInsertElements) for at least 05m00s without outputting or completing in state finish
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:502)
  at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
  at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1160)
  at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1244)
  at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.flushRows(BatchedStreamingWrite.java:403)
  at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.access$900(BatchedStreamingWrite.java:67)
  at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite$BatchAndInsertElements.finishBundle(BatchedStreamingWrite.java:286)
  at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite$BatchAndInsertElements$DoFnInvoker.invokeFinishBundle(Unknown Source)
```

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #23856

* Unify test name to make the test listed as Performance Test
    
* Run STREAM_INSERT write with streaming pipeline

* Fix Json write bytes

* Better logging to insert failure

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Write still stuck at
```
Operation ongoing in step Write to BQ/StreamingInserts/StreamingWriteTables/StreamingWrite/BatchedStreamingWrite.ViaBundleFinalization/ParMultiDo(BatchAndInsertElements) for at least 05m00s without outputting or completing in state finish at sun.misc.Unsafe.park(Native Method) at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:502) at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1158) at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl.insertAll(BigQueryServicesImpl.java:1242) at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.flushRows(BatchedStreamingWrite.java:379) at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite.access$900(BatchedStreamingWrite.java:67) at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite$BatchAndInsertElements.finishBundle(BatchedStreamingWrite.java:268) at org.apache.beam.sdk.io.gcp.bigquery.BatchedStreamingWrite$BatchAndInsertElements$DoFnInvoker.invokeFinishBundle(Unknown Source)
```
The cause is not the reverted commit

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Catched error message: `{"debugInfo":"","location":"data","message":"Array specified for non-repeated field: data.","reason":"invalid"}`

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Now the worker experiences OOM error.

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Well, turns out that using streaming insert in batch mode is discouraged and unsupported. The performance tests needs rewrite.

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by Abacn** [comment]
Test now passed: https://ci-beam.apache.org/job/beam_BiqQueryIO_Streaming_Performance_Test_Java/4443/

Clean up and rebase

**Comment by Abacn** [comment]
Run BigQueryIO Batch Performance Test Java Avro

**Comment by Abacn** [comment]
Run BigQueryIO Batch Performance Test Java Json

**Comment by Abacn** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by johnjcasey** [comment]
LGTM

**Pull request merged**
