### PR TITLE
[BEAM-13229] side nav bug fixed

### PR DESCRIPTION
**Pull request by bullet03**
NB!!! Merge this PR before https://github.com/apache/beam/pull/21731.
- add refresh to srcoll spy for language-switch-v2.js and page-nav.js
- add scrollTo new position after language switch
- change styles, add & sign to before pseudoselector, put before inside 'a' tag
- change html structure of language-switch buttons, delete 'a' tag, add langSwitch-content class to 'li' tag
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
R: @nausharipov @aromanenko-dev

**Review by nausharipov — APPROVED** [review]

**Comment by dariabezkorovaina** [comment]
@pcoet @kennknowles can you please review this PR? looks like the bug has been fixed and looks good on staging:)

**Comment by pcoet** [comment]
There seems to be a regression here. The language tab styling isn't working right. After selecting a language at the top of the page, you don't see the corresponding language tabs highlighted in the rest of the page.

The language highlighting functionality is really brittle and just ... hairy. I'd suggest not touching **language-switch-v2.js** unless you have to. If you do, make sure that any changes are not having unexpected side effects.

**Comment by pcoet** [comment]
There seems to be a regression here. The language tab styling isn't working right. After selecting a language at the top of the page, you don't see the corresponding language tabs highlighted in the rest of the page.

The language highlighting functionality is really brittle and just ... hairy. I'd suggest not touching **language-switch-v2.js** unless you have to. If you do, make sure that any changes are not having unexpected side effects.

**Review by aromanenko-dev — CHANGES_REQUESTED** [review]
This PR contains a lot of unrelated commits.
Please, use `git rebase` for your feature branch and commit only related for this PR changes!

**Comment by bullet03** [comment]
> This PR contains a lot of unrelated commits. Please, use `git rebase` for your feature branch and commit only related for this PR changes!

I tried to pull a remote branch and messed up the commit history a bit. I fixed it.

**Comment by aromanenko-dev** [comment]
@bullet03 Thanks! Yes, it's ok now.

**Comment by aaltay** [comment]
What is the next step on this PR? Are we confident that all issues are resolved?

/cc @aijamalnk

**Comment by AKosolapov** [comment]
We are doing additional reviews and will update comments when it's ready for review

**Comment by aaltay** [comment]
> We are doing additional reviews and will update comments when it's ready for review

Thank you very much! I appreciate the diligence.

**Comment by bullet03** [comment]
@pcoet, could you kindly review this PR? It is ready. 
Related summary is in the [documentation ](https://docs.google.com/document/d/1tVjkAFhHAMHHhEVgJZTPdRAd2y3Crw_hwLB0nKzGlRI/edit#heading=h.uakjqdiaib9q)

**Review by pcoet — APPROVED** [review]

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, merge this PR? It was approved.

**Comment by aromanenko-dev** [comment]
@bullet03 Sure, thanks!

**Pull request merged**
