### PR TITLE
[BEAM-3040] Use tox instead of detox

### PR DESCRIPTION
**Pull request by aaltay**

### CODE REVIEW

**Comment by robertwb** [comment]
Hopefully this resolves things; will be keeping an eye on the tests. 

Could you at least reference the original commit (if not creating as a rollback) and give a reason in the commit description?

**Comment by aaltay** [comment]
Thank you @robertwb. I wanted to just run the pre-commit with the change to see if it helps. I will update the commit message with relevant information.

**Comment by aaltay** [comment]
Linter failed due to: https://github.com/apache/beam/pull/3972, but other tox targets passed and did not timeout.

R: @robertwb

**Comment by robertwb** [comment]
LGTM

**Pull request merged**
