### PR TITLE
Adding beam blog info to the Community page

### LINKED ISSUE #21245: add external references to the Beam Community page
There's lots of good third party content out there about Beam; we should highlight it as well:

[https://stackoverflow.com/questions/tagged/apache-beam](https://stackoverflow.com/questions/tagged/apache-beam) 

[https://towardsdatascience.com/tagged/apache-beam](https://towardsdatascience.com/tagged/apache-beam)

 

Imported from Jira [BEAM-12972](https://issues.apache.org/jira/browse/BEAM-12972). Original Jira may contain additional context.
Reported by: sachinag.

### PR DESCRIPTION
**Pull request by rszper**
fixes #21245

Adding information about and a link to the Beam content in Towards Data Science to the community page, collocated with the link to the Beam section on StackOverflow.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by rszper** [comment]
R: @sachinag

**Comment by sachinag** [comment]
I'd suggest the broader Medium target instead of that specific publication, like so: https://medium.com/tag/apache-beam

**Comment by rszper** [comment]
@sachinag I agree. I updated the link to point to Medium, and I updated the title to say "Blog posts" instead of naming the publication.

**Comment by sachinag** [comment]
LGTM, thank you Rebecca!

**Review by melap — APPROVED** [review]

**Pull request merged**
