### PR TITLE
Publish python test results to jenkins.

### PR DESCRIPTION
**Pull request by robertwb**
This switches the command to nosetests, but we were already using
nose.collector so that shouldn't be an issue.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by robertwb** [comment]
@jasonkuster this should give us the same test breakdowns as we have for Java, rather than having to scroll through the console output. I can't remember how to get the groovy changes to apply though.

**Comment by cclauss** [comment]
Given the note at the top of https://nose.readthedocs.io would it make sense to update to https://nose2.readthedocs.io or https://docs.pytest.org ?

**Comment by robertwb** [comment]
Good point. Filed https://issues.apache.org/jira/browse/BEAM-3713 (as this is a separate issue).

**Comment by robertwb** [comment]
Run Seed Job

**Comment by robertwb** [comment]
Run Seed Job

**Comment by lukecwik** [comment]
Superseded by #5042

**Pull request closed without merging**
