### PR TITLE
[Beam-1245] Use @unittest.skip to skip avroio_test cases

### PR DESCRIPTION
**Pull request by yk5**
when python-snappy is not installed, instead of except ImportError.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by yk5** [comment]
R: @aaltay

FYI, without snappy installed, test log would look like:
WARNING:root:snappy is not installed; some tests will be skipped.
...
Ran 21 tests in 13.840s

OK (skipped=3)
---

And, with installed:
...
Ran 21 tests in 14.464s

OK

**Comment by aaltay** [comment]
LGTM. Thank you for cleaning this.

R: @robertwb

**Comment by robertwb** [comment]
Thanks. Merged.

**Comment by yk5** [comment]
Thanks! closing.

**Pull request closed without merging**
