### PR TITLE
[BEAM-6440] Fix leakage of timer de-duplication map

### PR DESCRIPTION
**Pull request by tweise**
The FlinkStateInternals use a keyed map of pending timers to make up for Flink's
limitation to only be able to delete timers with their original timestamp, not
via timer id.

The Map leaked memory because subclasses of DoFnOperator overwrote `fireTimer`
which was responsible for performing cleanup in the map upon firing a timer.

**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
Looks like trouble in the precommits

**Comment by mxm** [comment]
FYI This is backported from https://github.com/apache/beam/pull/7517.

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
Run Python_ValidatesRunner_Flink PreCommit

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Above failing PreCommit Python_ValidatesRunner_Flink has been temporarily removed: https://github.com/apache/beam/pull/7533

**Comment by mxm** [comment]
Python PreCommit fails but is unrelated:

```
10:54:15 > Task :beam-sdks-python-precommit-dataflow:precommitIT FAILED
10:54:15 
10:54:15 FAILURE: Build failed with an exception.
10:54:15 
10:54:15 * Where:
10:54:15 Build file '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/precommit/dataflow/build.gradle' line: 36
10:54:15 
10:54:15 * What went wrong:
10:54:15 Execution failed for task ':beam-sdks-python-precommit-dataflow:precommitIT'.
10:54:15 > Process 'command 'sh'' finished with non-zero exit value 1
```

**Pull request merged**
