### PR TITLE
[BEAM-8442] Unify bundle register in Python SDK harness

### PR DESCRIPTION
**Pull request by sunjincheng121**
Motivation

- Cleanup the code of `sdk_worker.py` on register process boundle descriptor.
- Correct the implementation of Fn API, i.e., would be better to cater to the asynchronous design principles of the Beam API.

Changes
 - 6868333: 
 	Update the client side implementation of Fn API to make sure registration is executed successfully before executing process_bundle. Personally I think that the client side implementation of Fn API should not assume that the implementation of registration in SDK harness is synchronous. The registration API itself is asynchronous and the client side implementation should check if the registration succeed. This will decouple the implementation dependency between the runner and the SDK harness.

 - 79d21b1:
 	Remove duplicate registration logic in the Python SDK harness.  It changed the registration implementation of Python SDK harness to asynchronous.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by sunjincheng121** [comment]
R: @mxm @ibzib @aaltay @lukecwik

**Comment by mxm** [comment]
Run Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by sunjincheng121** [comment]
Thanks for the review @mxm !
I am appreciate if you can have a look at the PR. @aaltay @ibzib @lukecwik :)

**Comment by ibzib** [comment]
Run XVR_Flink PostCommit

**Comment by sunjincheng121** [comment]
Thanks for your review @ibzib !

**Comment by sunjincheng121** [comment]
Can we merge this change :)

**Comment by mxm** [comment]
Run Java PortabilityApi PostCommit

**Comment by sunjincheng121** [comment]
Run Java PortabilityApi PostCommit

**Comment by sunjincheng121** [comment]
@mxm Thanks a lot for triggering the tests. The test failure seems because of quota issues. I'll re-trigger the test to see if it still happens.  

log的链接：https://builds.apache.org/job/beam_PostCommit_Java_PortabilityApi_PR/47/testReport/org.apache.beam.examples.cookbook/BigQueryTornadoesIT/testE2EBigQueryTornadoesWithExport/

**Comment by mxm** [comment]
Thanks, failure looks unrelated. Test is passing in the second run.

**Comment by robertwb** [comment]
The control plane is asynchronous, but still ordered. IIRC bundle registration was synchronous before such that if a bundle was not registered, an error could be thrown rather than waiting around for a registration that may never come. What is the behavior after this CL if the registration does not complete before the process bundle instruction is seen?

**Comment by sunjincheng121** [comment]
@robertwb 
Thanks a lot for comments. After this change, if the registration failed, the data channel between the runner and the SDK harness will not be established and so the data transmission from the runner to the SDK harness will be [timedout](https://github.com/apache/beam/blob/74ea7496ff486640affbf2e6ab4a45d3ea25efc8/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/data/GrpcDataService.java#L170). At that time, the registration failure could be reported. This is also the same case for the process bundle instruction before and after this change. Are you concerning that we should detect the registration failure at the early time? If it's the case, how do we deal with the process bundle instruction, should we keep the same behavior for both the registration and process bundle instruction.
What do you think?
Best, Jincheng

**Comment by robertwb** [comment]
Actually, looking at the code, if SdkWorker.register (which is now
asynchronous) does not complete before SdkWorker.process_bundle
starts, process_bundle fails. We could be getting lucky as register is
fast, but there's a race here now that it's not synchronous.

https://github.com/sunjincheng121/beam/blob/79d21b11ca31963bd1be84a26502e5577bbefbdf/sdks/python/apache_beam/runners/worker/sdk_worker.py#L371

**Comment by sunjincheng121** [comment]
Runner will only send process bundle instruction after the registration is finished and so I think there is no race condition here. This is also the purpose of the first commit of this PR. Am I missing something else?

**Comment by robertwb** [comment]
That first commit only applies to Java runners (or, specifically, those
that are using the shared library). It complicates the protocol in that a
runner now must wait for the registration to succeed before sending further
requests (i.e. it cannot pipeline them).

**Comment by chamikaramj** [comment]
Seems like this can result in a race condition for non Java runners ? I'm seeing some errors for Dataflow that might be related. Is there a fix ?

**Comment by sunjincheng121** [comment]
@robertwb The reason that the first commit only applies to Java runners is because there is no such problems for  the Python Universal Local Runner(FnApiRunner) that process bundle request should be sent after registration succeeded: https://github.com/apache/beam/blob/5dbaf6607cd7e1e698004fa775c15339fa75c3f3/sdks/python/apache_beam/runners/portability/fn_api_runner.py#L1730

@chamikaramj could you please share the error message? and does the `Dataflow` runner  thyou mentioned is in the beam repo ? (I remember @robertwb had mentioned in somewhere that there is a Dataflow runner which is written in C++, not in beam repo) If not, may be we should to change the runner side logic to asynchronous. 

What do you think?

**Comment by chamikaramj** [comment]
Error is from Dataflow Java and seems to be due to SDK not being able to find the bundle descriptor.

apache_beam/runners/worker/sdk_worker.py", line 305, in get
    self.fns[bundle_descriptor_id],
KeyError: u'-47'

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.beam.sdk.util.MoreFutures.get(MoreFutures.java:57)
	at org.apache.beam.runners.dataflow.worker.fn.control.RegisterAndProcessBundleOperation.finish(RegisterAndProcessBundleOperation.java:330)
	at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:85)
	at org.apache.beam.runners.dataflow.worker.fn.control.BeamFnMapTaskExecutor.execute(BeamFnMapTaskExecutor.java:125)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380)
	at org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:305)
	at org.apache.beam.runners.dataflow.worker.DataflowRunnerHarness.start(DataflowRunnerHarness.java:195)
	at org.apache.beam.runners.dataflow.worker.DataflowRunnerHarness.main(DataflowRunnerHarness.java:123)
	Suppressed: java.lang.IllegalStateException: Already closed.
		at org.apache.beam.sdk.fn.data.BeamFnDataBufferingOutboundObserver.close(BeamFnDataBufferingOutboundObserver.java:93)
		at org.apache.beam.runners.dataflow.worker.fn.data.RemoteGrpcPortWriteOperation.abort(RemoteGrpcPortWriteOperation.java:220)
		at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:91)

**Comment by sunjincheng121** [comment]
Hi, Thanks for the log info, @chamikaramj !
From the exception log(the line number of RegisterAndProcessBundleOperation), it seems that the [commit](https://github.com/apache/beam/commit/686833381ecc92f0fbe04e576a582a7640ca7bbd) is not included in the DataFlow runner. Could you help to check this as this commit ensures that registration is executed successfully before executing process bundle request?

**Comment by sunjincheng121** [comment]
Hi @chamikaramj,  I have create a JIRA. [BEAM-8733](https://issues.apache.org/jira/browse/BEAM-8733) to trace the discussion of this issue. 

I think it's better to continue the discussion in the JIRA.  Feel free to correct me if this not make sense to you :)

**Pull request merged**
