### PR TITLE
#25232 bump log4j2 to 2.20.0

### PR DESCRIPTION
**Pull request by masahitojp**
**Please** add a meaningful description for your change here

#25232
- bump log4j2 to 2.19.0
- I'd liket update version to lates for log4j2 https://logging.apache.org/log4j/2.x/download.html
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by masahitojp** [comment]
Run Java PreCommit

**Comment by masahitojp** [comment]
R: @aromanenko-dev

I checked this PR https://github.com/apache/beam/commit/95e53916b6c9de6052ce8fc8409a53bad3d9d517

I didn't know how to request a reviewer, so I will contact you (the way I did [before](https://github.com/apache/beam/pull/16287)) for the time being. Please let me know if there is someone else who would be more suitable.

**Comment by masahitojp** [comment]
How about this PR?

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
Sorry for delay with review. Seems like the latest version is 2.20.0 for now. Could you update it?

**Comment by masahitojp** [comment]
Ach Ok, I'll update it

**Comment by masahitojp** [comment]
Run Java_hadoop_IO_Direct PreCommit

**Comment by masahitojp** [comment]
Run Website PreCommit

**Comment by masahitojp** [comment]
I have not made any changes to the file displayed in this message. So I will try to re-run it.
```
21:24:05 java.lang.IllegalArgumentException: com.gradle.enterprise.gradleplugin.internal.extension.a is not an interface
21:24:05 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:590)
21:24:05 	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
21:24:05 	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
21:24:05 	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
21:24:05 	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
21:24:05 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
21:24:05 	at com.gradle.ProxyFactory$ProxyingInvocationHandler.createLocalProxy(ProxyFactory.java:66)
21:24:05 	at com.gradle.ProxyFactory$ProxyingInvocationHandler.lambda$adaptActionArg$1(ProxyFactory.java:61)
21:24:05 	at com.gradle.enterprise.gradleplugin.internal.extension.b$3.run(SourceFile:100)
21:24:05 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21:24:05 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:24:05 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:24:05 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:24:05 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by masahitojp** [comment]
Run Java PreCommit

**Comment by masahitojp** [comment]
Run Website PreCommit

**Comment by masahitojp** [comment]
@aromanenko-dev I was late in contacting you. I have completed the update to 2.20.0. Please review. :-)

**Comment by masahitojp** [comment]
How about this?

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
