### PR TITLE
Allow writing JSON data with BigQuery FILE_LOADS

### PR DESCRIPTION
**Pull request by ahmedabu98**
JSON insertion via batch loads has until recently only been supported via CSV format. It is now supported with JSON and Avro format (see [here for documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data#use_a_batch_load_job)).

It does not seem to allow repeated JSON fields, however. These changes allow JSON writes with FILE_LOADS but still throw an early error when detecting repeated JSON fields.

**Update**:
JSON repeated fields are now allowed

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @johnjcasey 
R: @chamikaramj

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by ahmedabu98** [comment]
Run Python PreCommit

**Comment by ahmedabu98** [comment]
Run Python PreCommit

**Comment by ahmedabu98** [comment]
retest this please

**Comment by ahmedabu98** [comment]
FYI repeated JSON values are available. Updating the scope to include writing any JSON data with file loads

**Comment by chamikaramj** [comment]
What's the status here ? Should this be merged ?

**Pull request closed without merging**
