### PR TITLE
[BEAM-79] Sync gearpump-runner branch with master

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Hmm Jenkins failed, I'm checking why.

**Comment by kennknowles** [comment]
The gearpump-runner `ValidatesRunner` tests are known to be broken right now. They got disabled for a while and got into a bad state. So now we don't really have signal from Jenkins about the runner.

@manuzhang are you expecting Jenkins to be fixable soon? Perhaps we should pause the syncing with master while we fix it up, unless it is not possible, so that we know that our fixups when we sync are good.

**Comment by manuzhang** [comment]
@kennknowles I can create a separate PR to try fixingJenkins. The problem is I cannot reproduce Jenkins failure locally and don't know what to fix.

**Comment by kennknowles** [comment]
I am even more worried that we cannot reproduce Jenkins failures locally. I really want to dig in to what the difference is.

**Comment by kennknowles** [comment]
I ran the full `ValidatesRunner` suite locally and it succeeded for me as well. So I will merge this.

**Pull request merged**
