### PR TITLE
Pin runner harness also for official BEAM releases.

### PR DESCRIPTION
**Pull request by tvalentyn**
Another change to address https://issues.apache.org/jira/browse/BEAM-3011 as discussed offline today.

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @aaltay 
cc: @charlesccychen

**Comment by aaltay** [comment]
LGTM. Thank you. (Please try to run a manual job.)

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
manual works as expected.

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
This is ready to merge. Also CP'd onto  https://github.com/apache/beam/pull/3970.

**Pull request merged**
