### PR TITLE
[Java11 Migration] Migrate Go testing to use Java11 container image for xlang

### PR DESCRIPTION
**Pull request by lostluck**
The default Xlang transforms got moved to Java 11, but we were only building the Java8 ones, so 11 wasn't available.

Move to use Java 11 to unbreak the existing tests.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @Abacn 
cc: @damondouglas

**Review by Abacn — COMMENTED** [review]
Thanks, I'm also activing fixing tests. Let's do somthing like this:

https://github.com/apache/beam/pull/32190/files#diff-3b0c84ea390ab209fe959cda93b113ce47f7485f1b6046bbc5597da7d17f784dR44

So it always depend on current Java version

**Comment by lostluck** [comment]
I went a slightly different direction to go with the same way we set the Flink version string, instead of making all the files do an import (which they don't do presently), and needing a side variable. Let's see if I did it right...

**Comment by Abacn** [comment]
> I went a slightly different direction to go with the same way we set the Flink version string, instead of making all the files do an import (which they don't do presently), and needing a side variable. Let's see if I did it right...

Yeah this should work well. For the link above it was due to the file being "commons.gradle" instead of "build.gradle", where not explicitly applied (though all reference to "commons.gradle" called the plugin before) so I chose not to depend on project.ext initialized by apply : beamModulePlugin

**Review by Abacn — APPROVED** [review]

**Pull request merged**
