### PR TITLE
Cherry pick #3093: [BEAM-2256] Add the last previous range filter

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @davorbonaci @dhalperi

**Comment by dhalperi** [comment]
It looks like this has been merged; if so, close at your leisure?

**Comment by lukecwik** [comment]
This was for https://issues.apache.org/jira/browse/BEAM-2275

**Comment by davorbonaci** [comment]
LGTM

**Pull request closed without merging**
