### PR TITLE
Support Dataflow runner v2 in SparkRecieverIO 

### LINKED ISSUE #26011: [Bug]: SparkRecieverIO doesn't support Dataflow runner v2
### What happened?
The pipeline that uses SparkReceiverIO gets stuck processing the [0,0] restriction on Dataflow Runner V2.
The same pipeline on Dataflow Runner V1 works correctly. 
#### Steps to reproduce
Run pipeline using SparkReceiverIO on Dataflow Runner V2. 
#### Reason
The initial restriction is set to [0, +infinity). SparkReceiverIO tries to split restrictions before processing data to [0,0] and [0, +infinity). That leads to already processed [0,0] being empty and the pipeline hung there.

### Issue Priority

Priority: 3 (minor)

### Issue Components
io-java-cdap

### PR DESCRIPTION
**Pull request by Amar3tto**
Changes:
- Resolves #26011
- Fixed `numWorkers` parameter for SparkReceiverIO Performance test job
- Added dataflow runner dependency to Hubspot and Salesforce CDAP examples
- Updated version of CDAP Salesforce plugin dependency in examples 
- Fixed logger _StackOverflow_ issues (Dataflow) in CDAP examples
- Added additional logging in SparkReceiverIO SDF
- Fixed test RabbitMQ Receiver
- Added `setCheckpoint` method for Receivers that implement `HasOffset`

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by aromanenko-dev** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
R: @aromanenko-dev

**Review by aromanenko-dev — APPROVED** [review]
LGTM, just a minor comment

**Pull request merged**
