### PR TITLE
[BEAM-1145] Remove classifier from shaded spark runner artifact

### PR DESCRIPTION
**Pull request by aviemzur**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aviemzur** [comment]
R: @amitsela

**Comment by amitsela** [comment]
@aviemzur this looks like it breaks the integration test running from [`examples-java`](https://github.com/apache/incubator-beam/blob/master/examples/java/pom.xml#L87).

**Comment by aviemzur** [comment]
It shouldn't affect any of the tests, all test passed locally.
Could this be an issue with the Jenkins run?
The exception in Jenkins log is:

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (spark-runner-integration-tests) on project beam-examples-java: Execution spark-runner-integration-tests of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`

**Comment by amitsela** [comment]
retest this please.

**Comment by aviemzur** [comment]
retest this please.

**Comment by aviemzur** [comment]
retest this please.

**Comment by aviemzur** [comment]
retest this please.

**Comment by kennknowles** [comment]
The build is timing out at 100 minutes. In the ~30 seconds I spent looking at the log, the timeout does occur in the Spark integration tests and I don't see anything else obvious. Is it possible there is some retry loop happening?

#1640 should make it easier to quickly estimate issue in cases like this.

Separate from that, I believe we have surefire configured to redirect test method output to a file, but I don't know that the file is archived or accessible, so it might be hard to diagnose until that is changed, too.

**Comment by aviemzur** [comment]
Resolved the issue with spark runner integration tests hanging by removing failsafe's parallelism for these tests.

**Comment by aviemzur** [comment]
Looks like `kryo` shading in spark runner causes issues for the apex runner integration tests. This should be resolved when https://github.com/apache/incubator-beam/pull/1613 is merged

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by aviemzur** [comment]
R: @amitsela 
All tests pass now, as expected.

**Comment by amitsela** [comment]
LGTM, I'll merge.

**Pull request closed without merging**
