### PR TITLE
Upgrade Debian Bullseye to Bookworm

### PR DESCRIPTION
**Pull request by bvolpato**
Bookworm is the new Debian stable release (https://www.debian.org/releases/stable/) and has a much smaller vulnerability footprint (and is smaller!)

# Bullseye
Size: 55.06 mb
Vulnerabilities: 25
 
image

# Bookworm
Size: 49.58 mb
Vulnerabilities: 17

image

### CODE REVIEW

**Comment by Abacn** [comment]
Beam playground build fail: https://storage.googleapis.com/playground-cloudbuild-logs-public/CI_PR29721_2dc825be4b6f57f496aa0a2a1ce7f140ebfb90ca_63a5f4a1-e8fc-4704-b2b2-8f953823bcce.txt

The error was not obvious. Ran locally I reproduced the error:
```
#19 2.344 is only available from another source
#19 2.344 
#19 2.348 E: Package 'openjdk-11-jre-headless' has no installation candidate
#19 ERROR: executor failed running [/bin/sh -c apt-get update && apt-get install -y openjdk-11-jre-headless]: exit code: 100
------
 > [15/18] RUN apt-get update && apt-get install -y openjdk-11-jre-headless:
------
executor failed running [/bin/sh -c apt-get update && apt-get install -y openjdk-11-jre-headless]: exit code: 100
```

This was due to openjdk-11 removed from debian bookworm: https://www.reddit.com/r/debian/comments/14fjgus/need_help_installing_openjdk11_on_debian_12/

**Comment by bvolpato** [comment]
Thanks Yi! I'll keep playground untouched for now, and we can revisit this later.

Perhaps it should use the Temurin images and not rely on apt-getting the JDK, but it's a bit outside of the my scope here (reducing vulnerability footprint)

**Comment by Abacn** [comment]
> Perhaps it should use the Temurin images and not rely on apt-getting the JDK

Yeah that could be an approach. Though from my observation Temurin image does not help much for reducing vulneribility

**Comment by bvolpato** [comment]
Run Java PreCommit

**Pull request merged**
