### PR TITLE
[BEAM-3932] Adds handling of array null values to MutationSizeEstimator

### PR DESCRIPTION
**Pull request by mairbek**
R: @jkff

### CODE REVIEW

**Comment by jkff** [comment]
Ismael could you take a look?

**Comment by iemejia** [comment]
Sure, looking right now.

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Thanks @mairbek

**Comment by mairbek** [comment]
Awesome! Thank you, Ismaël

**Pull request merged**
