### PR TITLE
[BEAM-4145] Populate the worker_id metadata in the Java SDK Harness

### PR DESCRIPTION
**Pull request by jkff**
This is a take-over of #5456 since Thomas is currently unavailable.

I took the PR verbatim, rebased it / resolved conflicts, and addressed the review comments:

- Added a comment about lifetime of logging service.
- To "We are loosing the original list of interceptors here." - I think it's conventional to have a withFoo(List) method overwrite the list rather than append, so no action on this one.

R: @angoenka

### CODE REVIEW

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Run Java PreCommit

**Comment by jkff** [comment]
Test passed (but didn't propagate status to Github), PTAL.

**Comment by angoenka** [comment]
Thanks!

**Pull request merged**
