### PR TITLE
re-add testing package to pydoc

### PR DESCRIPTION
**Pull request by pabloem**
r: @TheNeuralBit 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by TheNeuralBit — APPROVED** [review]
Unfortunately this will only effect future released SDKs, should we consider backporting and re-building the pydoc on the 2.30-2.38 release branches?

**Comment by pabloem** [comment]
hm I suppose it's just a matter of regenerating the pydocs and running a PR against the website, huh?

**Comment by TheNeuralBit** [comment]
oh yeah great point, we don't need to backport. we might want to use (or at least reference) the relevant portion of the build_release_candidate script for that: https://github.com/apache/beam/blob/master/release/src/main/scripts/build_release_candidate.sh#L356-L376

**Comment by pabloem** [comment]
what are the chances that @y1chi could help us run this script to update older releases? :sweat_smile:

**Comment by y1chi** [comment]
> what are the chances that @y1chi could help us run this script to update older releases? 😅

I can try.

**Pull request merged**
