### PR TITLE
[release-2.17.0][BEAM-8917][BEAM-8967] jsr305 dependency declaration for Nullable class (#10324)

### PR DESCRIPTION
**Pull request by iemejia**
R: @Ardagan 
CC: @suztomo @kennknowles

### CODE REVIEW

**Comment by Ardagan** [comment]
Run SQL postcommit

**Comment by Ardagan** [comment]
Hi Ismael,
Should I start building RC after this pr goes in, or will there be more changes required?

**Comment by iemejia** [comment]
Yes you can go ahead once this one is in. Nothing else is missing AFAIK. Thanks @Ardagan !

**Comment by iemejia** [comment]
Oups we discovered one minor issue I will cherry-pick an extra commit here and then it is ok to go. For more details https://issues.apache.org/jira/browse/BEAM-8967

**Comment by iemejia** [comment]
Run SQL postcommit

**Comment by Ardagan** [comment]
run python precommit

**Comment by Ardagan** [comment]
run python precommit

**Comment by aaltay** [comment]
I suggest merging this. The change is unrelated to python and it is blocking the RC.

**Pull request merged**
