### PR TITLE
Followup sharding javaPostCommit

### PR DESCRIPTION
**Pull request by Abacn**
Follow up of #21800

* Remove integration test depsOn that already sharded

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java PostCommit

**Comment by Abacn** [comment]
Run Java PostCommit

**Comment by Abacn** [comment]
@fernando-wizeline @benWize Jobs created in #21800 and #21804 have file name prefix and templates from `PreCommit`. But should these be `PostCommit` ? Also `.test-infra/jenkins/README.md` needs update

**Comment by benWize** [comment]
> @fernando-wizeline @benWize Jobs created in #21800 and #21804 have file name prefix and templates from `PreCommit`. But should these be `PostCommit` ? Also `.test-infra/jenkins/README.md` needs update

@Abacn here is a discussion about it https://github.com/apache/beam/pull/21808#issuecomment-1157307494

**Comment by Abacn** [comment]
beam_PreCommit_Java_GCP_IO_Direct links not working yet. Likely need to run seed job. Otherwise ready for review

**Comment by Abacn** [comment]
R: @benWize
R: @fernando-wizeline

**Comment by fernando-wizeline** [comment]
LGTM.
Thanks for the help @Abacn!

**Comment by benWize** [comment]
LGTM. Thanks, @Abacn

**Comment by Abacn** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
