### PR TITLE
Remove Travis CI configuration

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

During this period of limited Jenkins service, reducing our Travis needs until they can be effectively served.

### CODE REVIEW

**Comment by davorbonaci** [comment]
R: @davorbonaci

**Comment by kennknowles** [comment]
Pulling out the error:

```
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) 
on project beam-sdks-parent:
Failed during checkstyle execution:
Unable to find suppressions file at location: beam/suppressions.xml:
Could not find resource 'beam/suppressions.xml'. -> [Help 1]
```

To be honest, it seems wrong that it ever works, since the actually invalid relative path is resolved sort of randomly to a place that the `pom.xml` in question doesn't even own but is pulled in by the dependency set up. But best would be to just fix it for Travis (if we care; Jenkins is back) rather than spend time on it.

Side note: we should probably also fully qualify our resources, so `org/apache/beam/suppressions.xml`.

**Comment by kennknowles** [comment]
Possibly maven version? We could `apt-get` it if so.

**Comment by davorbonaci** [comment]
This is likely a versioning issue. The thing is that after we solve this one, there are more issues coming up, unfortunately. Overall, I don't think this is worth the time right now. I'd prefer just to disable Travis.

**Comment by kennknowles** [comment]
Let's disable it then. It has obscured our signal for months. Infra needs to flip this switch? I'll wipe out the file here.

**Comment by davorbonaci** [comment]
Yes, Infra has to disable the switch. @jasonkuster

**Comment by jasonkuster** [comment]
This will be best handled by an infra ticket -- I've filed https://issues.apache.org/jira/browse/INFRA-14027 to track.

**Comment by kennknowles** [comment]
Well, we could make travis vacuous to get signal but I suppose it will not matter for long.

**Comment by kennknowles** [comment]
I predict this will be the first green PR in months :-)

**Comment by jasonkuster** [comment]
Infra has removed the travis webhook, so we're good to go on that front.

**Comment by sb2nov** [comment]
There is still value Travis CI provides for python as that is the only way we can test installation on mac. Is it possible to just keep the Python tests around and remove all things related to Java.

cc @aaltay

**Comment by aaltay** [comment]
I agree with @sb2nov. Python tests in Travis is green, and it is providing an especially valuable signal with macos tests. Until we can have macos coverage in other forms, I am in favor of keeping python tests in Travis.

**Comment by davorbonaci** [comment]
It's not so simple as that. Travis could possibly be used to test "a little" -- this feature or that feature of the project, but it cannot test the project. How could we justify testing one component and not the other?

Then, Travis is not nearly as configurable as Jenkins, and really doesn't align with the future growth of the project.

MacOS signal, indeed, is valuable, but that's the only pro -- everything else are cons that are really hard to justify.

**Comment by sb2nov** [comment]
I don't understand that argument completely though. It is not like Travis is stopping us from running tests for other parts on Jenkins. 

The main reason we faced issues with Travis was that our tests took longer than an hour in contrast python tests finish in about 10 mins have generally been pretty stable on Travis as well. So if it can help with development in certain parts of the project I fail to see the rational that we shouldn't use it.

**Comment by sb2nov** [comment]
I think one way to think about it could be that we don't have a CI system, we just have a suite of CI systems where we prefer Jenkins whenever possible but shouldn't discard others if they can provide some value.

**Comment by davorbonaci** [comment]
Nearly every component we have finishes tests within the 10 minute mark when executed alone. The thing is that we have so many components. How could we justify testing one component and not the other?

"Some value" is not enough, because there's a cost involved too. All contributors will have to wait for the signal to come back, someone has to maintain the infrastructure around it, cognitive load, etc.

**Comment by kennknowles** [comment]
I don't think the technical portrayal of Travis is accurate here. We did hit some actual issues (a bit improved now with auto cancelation) but we were trying to use a wrench to hammer a nail. It is easy to use Travis in a way so that you have ~zero cost for a little benefit. It doesn't need to scale if you don't try to do everything. I view our failure to benefit from Travis as almost entirely our fault.

This discussion and decision about whether and how we choose to utilize the tool do not belong on a PR. I started this PR just to mitigate the Jenkins outage; now we don't have that option without flipping it back on anyhow so I am just going to close the PR.

**Comment by robertwb** [comment]
In particular, "failure to benefit from Travis" doesn't at all hold from Python's perspective, especially with the recent (ongoing? looks like the most recent build was 4 hours ago) Jenkins outages. 

At the very least, it can provide a smoke signal while jenkins is down and/or slow. Say, testing Python + Java Core. 

FWIW, I looked for an on-list discussion of this decision to remove travis, and didn't see one.

**Comment by davorbonaci** [comment]
The community had a discussion looong ago -- with Jenkins being our preferred solution and Travis-CI being a temporary patch. In fact, folks have been working on unification for a while now. With the aggregate Travis signal being broken for *months* now and nobody stepping in to fix it, it certainly seems like the right kind of clean up.

**Pull request closed without merging**
