### PR TITLE
[BEAM-12471] Fixes NumberFormatException

### PR DESCRIPTION
**Pull request by pgillet**
Please see the associated JIRA ticket [BEAM-12471](https://issues.apache.org/jira/projects/BEAM/issues/BEAM-12471).

### CODE REVIEW

**Comment by iemejia** [comment]
Tests are failing because of autoformatting issues. You can run `./gradlew :sdks:java:extensions:sql:spotlessApply` and update the PR please

**Comment by pgillet** [comment]
My bad! That's better now.

**Review by iemejia — APPROVED** [review]
LGTM Thanks @pgillet

**Comment by pgillet** [comment]
Great! Simple & fast!
Thanks :+1:

**Pull request merged**
