### PR TITLE
Suppress checker framework memory constraint warning

### LINKED ISSUE #20819: Java build flakes: "Memory constraints are impeding performance"
Java Wordcount Direct Runner (ubuntu-latest) failed a couple times on me with the following warning/error. It doesn't seem like "impeding performance" should cause the build to fail altogether, so I'm wondering if there's some way we can silence this warning.

```

> Task :sdks:java:extensions:protobuf:compileJava
warning: Memory constraints are impeding performance;
please increase max heap size.

...
> Task :sdks:java:extensions:protobuf:compileJava
error: warnings
found and -Werror specified
Note: Some input files use or override a deprecated API.
Note: Recompile
with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note:
Recompile with -Xlint:unchecked for details.
1 error
1 warning

> Task :sdks:java:extensions:protobuf:compileJava
FAILED
> Task :runners:core-construction-java:compileJava
Note: Some input files use or override a
deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked
or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with
an exception.

* What went wrong:
Execution failed for task ':sdks:java:extensions:protobuf:compileJava'.
>
Compilation failed; see the compiler error output for details.

```

Imported from Jira [BEAM-11837](https://issues.apache.org/jira/browse/BEAM-11837). Original Jira may contain additional context.
Reported by: ibzib.

### PR DESCRIPTION
**Pull request by kennknowles**
Fixes #20819

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Hrmm. Many of the "in progress" builds are successful, while the failed build is not restarting. We may need to do something different to effectively run just appropriate tests on PRs if this is a capacity/quota issue. I mean, we are talking about "I forgot how to count that low" numbers but we've seen issues still.

**Comment by kennknowles** [comment]
I haven't actually seen a memory constraint failure recently, but this should eliminate them totally so they don't recur.

**Comment by kennknowles** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Portable_Python PreCommit

**Comment by kennknowles** [comment]
Run Java_Clickhouse_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Azure_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Amqp_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Cdap_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_ElasticSearch_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by kennknowles** [comment]
Run Java_HBase_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_HBase_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Kudu_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Jms_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Parquet_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Redis_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Solr_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Java_Splunk_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run SQL_Java17 PreCommit

**Comment by kennknowles** [comment]
Run Typescript PreCommit

**Comment by kennknowles** [comment]
Run Python_PVR_Flink PreCommit

**Comment by kennknowles** [comment]
Run PythonFormatter PreCommit

**Comment by kennknowles** [comment]
Run Python PreCommit

**Review by damccorm — APPROVED** [review]

**Pull request merged**
