### PR TITLE
[BEAM-10403] Cherrypick #12171 to the release branch.

### PR DESCRIPTION
**Pull request by tvalentyn**
See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @chamikaramj @kkucharc

**Comment by chamikaramj** [comment]
LGTM.

**Comment by tvalentyn** [comment]
Run Java Precommit

**Comment by tvalentyn** [comment]
Previous run: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/12469/

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Previous run: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/2510/

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by kkucharc** [comment]
LGTM, thank you a lot @tvalentyn !

**Pull request merged**
