### PR TITLE
Evaluate removal of RDD caching for MEMORY_ONLY in the Spark Dataset runner

### PR DESCRIPTION
**Pull request by mosche**
A small simplification ... removing RDD caching for the Spark Dataset runner.

With the recent RDD linage fix (#25187) there's no visible improvement that justifies the added complexity. Moreover, the recommended storage level with Spark Datasets is MEMORY_AND_DISK (rather than MEMORY_ONLY). This makes RDD caching fairly irrelevant for production use cases with the Dataset runner.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Nexmark Tests

**Comment by mosche** [comment]
Run Spark Runner Nexmark Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Java PreCommit

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by mosche** [comment]
R: @echauchot 
R: @aromanenko-dev

**Comment by echauchot** [comment]
@mosche need to finish something, I'll take a look tomorrow or wednesday

**Comment by echauchot** [comment]
@mosche reviewing ...

**Pull request merged**
