### PR TITLE
[BEAM-2817] BigQuery queries are allowed to run in either BATCH or INTERACTIVE mode

### PR DESCRIPTION
**Pull request by justintumale**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
The Read.Builder for BigQueryIO takes in the priority as one of it's parameters and passes it through from the createSource method. This will allow for queries to be run in either batch mode or interactive mode.

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by aaltay** [comment]
@justintumale Can you rebase and clean up the commit history?

**Comment by justintumale** [comment]
Hi @aaltay, I created a new pull request which will be easier to work with https://github.com/apache/beam/pull/4226. When I synced my forked repository with the main repository, the previous commits kept showing up on my pull request. If you have any advise on how to remedy this that would be great 👍 Thanks

**Pull request closed without merging**
