### PR TITLE
Cherry Pick #32178: Loose BigQuery GCP project ID regex restrictions

### PR DESCRIPTION
**Pull request by kberezin-nshl**
Cherry pick of this PR: https://github.com/apache/beam/pull/32178

cc @lostluck

### CODE REVIEW

**Comment by lostluck** [comment]
It does not make the cut to require a new RC to be generated (it's clearly not a release blocker), but it's also so small in scope to not be a problem.

So what will happen is I'll look at this again in the morning, and most likely merge it in. That way, if there's a release blocking issue in RC1, it will be included in RC2. Otherwise it'll have to wait until 2.60.0.

**Comment by kberezin-nshl** [comment]
Great, thank you @lostluck . 

It is quite a big annoyance for us, so we'd appreciate removing our dirty hacks to work that around after migrating to 2.59. But obviously not _that_ a big deal because we have workarounds in place.

**Review by shunping — APPROVED** [review]
LGTM

**Review by lostluck — APPROVED** [review]

**Comment by lostluck** [comment]
Due to the *conditional* nature of the cherry pick, It should *not* be added to the release milestone at this time. It may or may not make it into 2.59.0, per reasons I stated above. It *will* be a part of 2.60.0 though.

**Pull request merged**
