### PR TITLE
24441: Update Jackson version from 2.13.3 to 2.14.1.

### LINKED ISSUE #24441: [Task] Upgrade Jackson version.
### What needs to happen?

There are known vulnerabilities with the current used version (2.13.3), resolved in newer versions (2.14.1).

https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

This shows up in security scanners, which may indicate a risk to users. Resolution is to update them.

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-java-core

### PR DESCRIPTION
**Pull request by lostluck**
Fixes #24441, and gets fixes for some CVEs.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
Run Java_Kinesis_IO_Direct PreCommit

**Comment by lostluck** [comment]
Run Portable_Python PreCommit

**Comment by lostluck** [comment]
Run Java PreCommit

**Comment by lostluck** [comment]
R: @kennknowles

**Comment by lostluck** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Could be #23745 or could be a fresh flake.

**Review by kennknowles — APPROVED** [review]

**Comment by kennknowles** [comment]
Given the testing situation I am confident this is green. Can you open a cherrypick to the `release-2.44.0` branch with the same commit?

**Comment by kennknowles** [comment]
Chatted with @damccorm and this is fixed on `master` so you actually do need to merge it in or rebase/sync this PR up. The cherrypick should be green right away.

**Comment by lostluck** [comment]
I had hoped to catch it before the cut :P, but yes. Going to make the cherry pick for this.

**Pull request merged**
