### PR TITLE
[BEAM-7806] Revert "[BEAM-7785] synchronize watermark update with bundle processing"

### PR DESCRIPTION
**Pull request by kennknowles**
This reverts commit 84ef8aa21aa350fb248a60e88a0cb195118fe1f5.

After this commit, org.apache.beam.sdk.extensions.sql.meta.provider.pubsub.PubsubJsonIT.testSelectsPayloadContent began failing. Rolling back to restore green/red signal while we deduce whether the problem is with the test or this change.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by kennknowles** [comment]
CC: @je-ik 

As according to https://beam.apache.org/contribute/postcommits-policies-details/index.html#rollback_first I am rolling back first. And then we can figure out what needs to be done.

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
Noting from the Jira:

 - Scan at suspect commit: https://gradle.com/s/c26wtkpfaayuw (fail)
 - Scan at parent of suspect commit: https://gradle.com/s/gea2suqcv45vk (succeed)
 - Scan at master with suspect commit reverted: https://gradle.com/s/zy5z2mnneveps (succeed)

**Comment by akedin** [comment]
+1 to rollback first.

Though it's not obvious how this change would directly cause the test to fail. The failing run seems to be unable to get the result signal within a timeout, is there a chance that it's a flake? (I recognize it's not likely given the scans :) The test itself I think is also relatively flaky and complicated and is probably full of race conditions, so depending on what makes it pass/fail this change can be either fixing something that was wrong and allowed the test to accidentally pass, or the test accidentally exercises some edge case that this change breaks, unclear. However, there is also another test that is `@Ignored` in the same file at the moment because it fails consistently and I don't know why. Maybe this change triggers a similar failure in this test

**Comment by kennknowles** [comment]
No, it is not a flake. It went perma-red after the commit for many runs, and then I could reproduce it locally every time.

**Comment by kennknowles** [comment]
But we should definitely consider that it could be the test that is broken. However, I commented on the other PR that the way to get consistency is not through locks but by immutable snapshots. It could even be that it just created a major performance problem that took more than the timeout. TBH I am not sure.

**Comment by boyuanzz** [comment]
Given that post commit back to green now: https://builds.apache.org/job/beam_PostCommit_SQL/, I would think that watermark changes break the test, or at least has side effect on that.

**Comment by je-ik** [comment]
Yes, the test accidentally caused deadlock in the test. Synchronizing the watermark update unintentionally limited parallelism of bundle processing to 1. This didn't cause any issues with existing tests or validates runner, but affected the integration test, because it performs blocking IO (and depends on another bundle to be unblocked). I have added test case to direct runner that exhibits this behavior and will fix the original issue without limiting the parallelism.

**Pull request merged**
