### PR TITLE
[BEAM-5322] Partially port typehints

### PR DESCRIPTION
**Pull request by splovyt**
This is is part of a series of PRs with goal to make Apache Beam PY3 compatible. The proposal with the outlined approach has been documented [here](https://s.apache.org/beam-python-3).

Fixing the tests for Python 3 requires a lot of cross-package fixes. I'm therefore submitting this PR with the failing tests skipped during Python 3 testing. This will allow us to build on these fixes while porting the other packages. Since the remaining errors might be caused by other packages, porting of these packages might already solve some of these errors.

In a later stage, these errors should be un-skipped and fixed if they are still failing.

@tvalentyn @Fematich @charlesccychen @aaltay 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by tvalentyn** [comment]
Thanks for the PR, @splovyt !
Looks like we'd have to fix lint failure before we can merge this.

You can find Linter output  in Jenkins logs: https://builds.apache.org/job/beam_PreCommit_Python_Commit/1546/ -> Console Output -> Full Log:

04:05:13 Using config file /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/.pylintrc
04:05:59 ************* Module apache_beam.typehints.native_type_compatibility_test
04:05:59 C: 41, 0: Wrong continued indentation.
04:05:59                                               'fixed on Python 3')
04:05:59                    |                         |^ (bad-continuation)
04:05:59 C: 84, 0: Wrong continued indentation.
04:05:59                                               'fixed on Python 3')
04:05:59                    |                         |^ (bad-continuation)
04:05:59 ************* Module apache_beam.typehints.typed_pipeline_test
04:05:59 C: 51, 0: Wrong continued indentation.
04:05:59                                               'fixed on Python 3')
04:05:59                    |                         |^ (bad-continuation)
04:05:59 
04:05:59 --------------------------------------------------------------------
04:05:59 Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
04:05:59 
04:05:59 Command exited with non-zero status 16
04:05:59 334.43user 7.72system 0:45.60elapsed 750%CPU (0avgtext+0avgdata 313032maxresident)k
04:05:59 0inputs+200outputs (0major+676039minor)pagefaults 0swaps
04:05:59 ERROR: InvocationError for command '/usr/bin/time /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/scripts/run_pylint.sh' (exited with code 16)
04:05:59 ___________________________________ summary ____________________________________
04:05:59 ERROR:   py27-lint: commands failed
04:05:59 
04:05:59 > Task :beam-sdks-python:lintPy27 FAILED

You should be able to reproduce linter errors locally by executing  `../../gradlew lintPy27` or `../../gradlew/lint` from `beam/sdk/python` directory.

**Comment by splovyt** [comment]
Hi @tvalentyn,
Thanks for the introduction and feedback!
I have updated the indents and currently deciphering the log in order to get the whole thing in the green.

**Comment by Fematich** [comment]
run python precommit

**Comment by tvalentyn** [comment]
Thanks, @splovyt, LGTM.

@aaltay - could you please squash the commits during the merge? 

@splovyt : In the future you can also squash fixup commits (minor follow up changes), with something like `git pull --rebase=interactive origin master`. It's fine to keep independent changes that make sense on their own as separate commits.  Also, when a new iteration is ready for review, feel free to give reviewers a heads-up with 'PTAL' or a comment like that.

**Comment by splovyt** [comment]
@tvalentyn thanks for your patience and feedback on this one. I appreciate it!

**Comment by tvalentyn** [comment]
@splovyt No worries - congrats with you first contribution to Beam :)

**Pull request merged**
