### PR TITLE
[BEAM-5396] Assign portable operator uids

### PR DESCRIPTION
**Pull request by mxm**
This adds operator uids to portable operators with state. A test verifies
restoring from a Savepoint for both legacy and portable pipelines.

CC @tweise 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by tweise** [comment]
@mxm thank! There is a commit from another PR included here, is that intentional?

Also, we you able to reproduce the restore error? If not, then I would need to do some more extensive testing for this.

**Comment by mxm** [comment]
>There is a commit from another PR included here, is that intentional?

Yes, this is based on #7359 (see description) because the test wouldn't otherwise run.

> Also, we you able to reproduce the restore error?

As you wrote in the JIRA, it depends on the pipeline. We shouldn't see the restore error anymore because of the uid assigned to all stateful operators. Before it would depend on the internal operator ids which only works if the pipeline generation is deterministic. Perhaps you could re-run your pipeline with this PR to verify that the restore works?

**Comment by tweise** [comment]
OK, I will test it with the original pipeline but it may take a bit before getting to it.

Can we rebase the PR though?

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
@tweise Rebased to latest master.

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Java PreCommit

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Portable_Python PreCommit

**Comment by tweise** [comment]
@mxm test failures appear repeatable: https://builds.apache.org/job/beam_PreCommit_Portable_Python_Phrase/

**Comment by tweise** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Python Validates Runner is fixed now.

Jenkins: Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Blocked on https://jira.apache.org/jira/browse/BEAM-6469

**Comment by mxm** [comment]
PreCommit failing due to #7575.

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Broken PreCommit tests: ```    org.apache.beam.runners.fnexecution.data.GrpcDataServiceTest.testMessageReceivedBySingleClientWhenThereAreMultipleClients
    org.apache.beam.sdk.io.FileIOTest.testMatchWatchForNewFiles```

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Python Flink ValidatesRunner

**Pull request merged**
