### PR TITLE
Swap Java SDK container to use eclipse-temurin as the base instead of OpenJDK

### LINKED ISSUE #25371: [Task]: Migrate to supported JDK8 and JDK11 containers
### What needs to happen?

Retiring OpenJDK Project Builds for JDK 11 and JDK 8 are retired as per https://github.com/docker-library/openjdk/issues/505

Find and use a replacement to pickup security fixes.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by lukecwik**
As discussed on https://lists.apache.org/thread/h4m02o0br5g5t3o3m8r4lkl431vvzhsg

Fixes #25371

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
R: @apilloud

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Review by apilloud — APPROVED** [review]
LGTM

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by kennknowles** [comment]
Is flink docker PVR real signal? Is it signal we care about?

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
No to my knowledge since it passed here https://ci-beam.apache.org/job/beam_PreCommit_Java_PVR_Flink_Docker_Commit/2457/ on my WIP PR https://github.com/apache/beam/pull/25408 that added additional docker logging to try to get more error details.

I'll try running again and merge if green.

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Currently failing due to license pulling falling over

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Turns out that boot.go is crashing:
```
[CHAIN MapPartition (MapPartition at [4]PAssert$0/GroupGlobally/{Create.Values, Flatten.PCollections, Window.Into(), WithKeys}) -> FlatMap (FlatMap at ExtractOutput[0]) (1/2)#0] ERROR org.apache.beam.runners.fnexecution.environment.DockerEnv
ironmentFactory - Docker container f6bb1afde12f48ad8d8179ef5fe67df2979eb73ac90cbda9a910bb48d85de742 logs:
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f8430b84a7c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f8430b84a7c
stack: frame={sp:0x7fffac802010, fp:0x0} stack=[0x7fffac003590,0x7fffac8025a0)
0x00007fffac801f10:  0x0000000000000000  0x00007fffac8022f0 
0x00007fffac801f20:  0x00007fffac8023e0  0x00000000027db2e0 
0x00007fffac801f30:  0x0000000000000178  0x00007f8430d34cee 
0x00007fffac801f40:  0x0000000000000000  0x00007f8430b89c9b 
0x00007fffac801f50:  0x0000000000000000  0x00007fffac8023e0 
0x00007fffac801f60:  0x00007f8430d08723  0x00007f8430d08723 
0x00007fffac801f70:  0x000000ffffffffff  0x0000000000000000 
0x00007fffac801f80:  0x000000ffffffffff  0x0000000000000000 
0x00007fffac801f90:  0x415353454d5f434c  0x505f434c00534547 
0x00007fffac801fa0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fb0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fc0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fd0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fe0:  0x6e75720000000000  0x6f67632f656d6974 
0x00007fffac801ff0:  0x0000000000000000  0x0000000000000000 
0x00007fffac802000:  0x00000000009710db  0x00007f8430b84a6e 
0x00007fffac802010: <0x0000000000ddf64a  0x0000000000000000 
0x00007fffac802020:  0x000000000096f77e  0x0000000000000004 
0x00007fffac802030:  0x0000000000ddf64c  0x0000000000000000 
0x00007fffac802040:  0x000000000097027a  0x0000000000000005 
0x00007fffac802050:  0x0000000000000000  0x0000000000000000 
0x00007fffac802060:  0x0000000000000000  0x0000000000000000 
0x00007fffac802070:  0x0000000000000000  0x0000000000000000 
0x00007fffac802080:  0x0000000000000000  0x0000000000000000 
0x00007fffac802090:  0x0000000000000000  0x5c5d1ab52c477200 
0x00007fffac8020a0:  0x00007f8430aeb740  0x0000000000000006 
0x00007fffac8020b0:  0x00000000027db2e0  0x0000000000000178 
0x00007fffac8020c0:  0x0000000000daed00  0x00007f8430b30476 
0x00007fffac8020d0:  0x00007f8430d08e90  0x00007f8430b167f3 
0x00007fffac8020e0:  0x0000000000000020  0x0000000000000000 
0x00007fffac8020f0:  0x0000000000000000  0x0000000000000000 
0x00007fffac802100:  0x0000000000000000  0x0000000000000000 
runtime: g 0: unknown pc 0x7f8430b84a7c
stack: frame={sp:0x7fffac802010, fp:0x0} stack=[0x7fffac003590,0x7fffac8025a0)
0x00007fffac801f10:  0x0000000000000000  0x00007fffac8022f0 
0x00007fffac801f20:  0x00007fffac8023e0  0x00000000027db2e0 
0x00007fffac801f30:  0x0000000000000178  0x00007f8430d34cee 
0x00007fffac801f40:  0x0000000000000000  0x00007f8430b89c9b 
0x00007fffac801f50:  0x0000000000000000  0x00007fffac8023e0 
0x00007fffac801f60:  0x00007f8430d08723  0x00007f8430d08723 
0x00007fffac801f70:  0x000000ffffffffff  0x0000000000000000 
0x00007fffac801f80:  0x000000ffffffffff  0x0000000000000000 
0x00007fffac801f90:  0x415353454d5f434c  0x505f434c00534547 
0x00007fffac801fa0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fb0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fc0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fd0:  0x0000000000000000  0x0000000000000000 
0x00007fffac801fe0:  0x6e75720000000000  0x6f67632f656d6974 
0x00007fffac801ff0:  0x0000000000000000  0x0000000000000000 
0x00007fffac802000:  0x00000000009710db  0x00007f8430b84a6e 
0x00007fffac802010: <0x0000000000ddf64a  0x0000000000000000 
0x00007fffac802020:  0x000000000096f77e  0x0000000000000004 
0x00007fffac802030:  0x0000000000ddf64c  0x0000000000000000 
0x00007fffac802040:  0x000000000097027a  0x0000000000000005 
0x00007fffac802050:  0x0000000000000000  0x0000000000000000 
0x00007fffac802060:  0x0000000000000000  0x0000000000000000 
0x00007fffac802070:  0x0000000000000000  0x0000000000000000 
0x00007fffac802080:  0x0000000000000000  0x0000000000000000 
0x00007fffac802090:  0x0000000000000000  0x5c5d1ab52c477200 
0x00007fffac8020a0:  0x00007f8430aeb740  0x0000000000000006 
0x00007fffac8020b0:  0x00000000027db2e0  0x0000000000000178 
0x00007fffac8020c0:  0x0000000000daed00  0x00007f8430b30476 
0x00007fffac8020d0:  0x00007f8430d08e90  0x00007f8430b167f3 
0x00007fffac8020e0:  0x0000000000000020  0x0000000000000000 
0x00007fffac8020f0:  0x0000000000000000  0x0000000000000000 
0x00007fffac802100:  0x0000000000000000  0x0000000000000000 

goroutine 1 [running]:
runtime.systemstack_switch()
        /home/lcwik/sdk/go1.19.3/src/runtime/asm_amd64.s:459 fp=0xc000074780 sp=0xc000074778 pc=0x465480
runtime.main()
        /home/lcwik/sdk/go1.19.3/src/runtime/proc.go:170 +0x6d fp=0xc0000747e0 sp=0xc000074780 pc=0x439b0d
runtime.goexit()
        /home/lcwik/sdk/go1.19.3/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x4676a1

rax    0x0
rbx    0x7f8430aeb740
rcx    0x7f8430b84a7c
rdx    0x6
rdi    0x1
rsi    0x1
rbp    0x1
rsp    0x7fffac802010
r8     0x7fffac8020e0
r9     0x7fffffff
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0xdaed00
r15    0x7f840977a35b
rip    0x7f8430b84a7c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

It looks like the issue is an out of date docker installation which explains why the tests pass locally but fail on Jenkins.
Jenkins is using Docker version 18.09.4, build d14af54 while when testing locally I'm using Docker version 20.10.21, build baeda1f

Filed https://issues.apache.org/jira/browse/INFRA-24205 to upgrade Docker on Beam's Jenkins hosts to 20.10.21+

**Comment by kennknowles** [comment]
Could this impact users?

**Comment by lukecwik** [comment]
> Could this impact users?

Yes, users will need a new enough version of Docker. Even the swap to Ubuntu Focal will need a new enough version of Docker as well. I updated the dev@ thread with these details, lets keep the discussion going on there.

**Comment by lukecwik** [comment]
Run Java Examples on Dataflow Runner V2

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Docker has been upgraded on the Jenkins hosts

**Pull request merged**
