### PR TITLE
[BEAM-4076] Enable schemas for more runners

### PR DESCRIPTION
**Pull request by reuvenlax**
This PR enables schemas for all runners except for gearpump (gearpump is more complicated due to the Scala indirection).

Schemas still are not enabled for the Dataflow runner, as that requires a change on the internal Dataflow side.

### CODE REVIEW

**Comment by reuvenlax** [comment]
@echauchot do you have time to help review this? It enables Schemas for most Beam runners

**Comment by echauchot** [comment]
@reuvenlax yes sure ! But I'm leaving on holidays tomorrow night. I'm currently on a review of RabitMQIO for JB. I'll take at least a quick look to this PR before going and resume after my return if it is not already merged.

**Comment by echauchot** [comment]
Run Spark ValidatesRunner

**Comment by echauchot** [comment]
Run Flink Validates Runner

**Comment by echauchot** [comment]
Run Apex ValidatesRunner

**Comment by echauchot** [comment]
Run Flink ValidatesRunner

**Comment by echauchot** [comment]
Run Samza ValidatesRunner

**Comment by reuvenlax** [comment]
@echauchot thanks for the review! Some comments:

  1. Schemas are plumbed through the NewDoFn implementation, which is why we needed the input and output coders. Schemas are implemented as a special type of coder (SchemaCoder), so NewDoFn needs those coders to infer schemas. Other transforms such as CoGroupByKey are (currently) untouched by schemas. There will be a new schema-specific Join transform (allowing you to join by specific field names, etc.), but I don't currently plan on changing CoGroupByKey itself.

  2. I'll take a look at the apex runner failures, and rebase.

  3. I'll look at variable names. I tried to rename a number of them to be less confusing, but might've missed a few :)

**Comment by reuvenlax** [comment]
Run Apex ValidatesRunner

**Comment by reuvenlax** [comment]
Run Flink ValidatesRunner

**Comment by reuvenlax** [comment]
Run Samza ValidatesRunner

**Comment by reuvenlax** [comment]
Run Spark ValidatesRunner

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
retest this please.

**Comment by reuvenlax** [comment]
@echauchot all comments addressed. You were correct about the Apex failure - it was caused by a typo between inputCoder and windowedInputCoder.

**Comment by echauchot** [comment]
Thanks for that @reuvenlax !

**Pull request merged**
