### PR TITLE
added methods for support ValueProvider in `MqttIO`

### LINKED ISSUE #19378: Add ValueProvider support for MqttIO
Imported from Jira [BEAM-6967](https://issues.apache.org/jira/browse/BEAM-6967). Original Jira may contain additional context.
Reported by: iemejia.

### PR DESCRIPTION
**Pull request by twosom**
**Please** add a meaningful description for your change here
fixes #19378

This PR contains thease changes
- add `ValueProvider` methods for `MqttIO.ConnectionConfiguration`

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Hi, is there a requirement in your use case that needs to serve ValueProvider? In the past ValueProviders were mainly used in Dataflow classic templates, which is superceded by flex templates that no longer need ValueProvider

**Comment by twosom** [comment]
> Hi, is there a requirement in your use case that needs to serve ValueProvider? In the past ValueProviders were mainly used in Dataflow classic templates, which is superceded by flex templates that no longer need ValueProvider

@Abacn 
Hello, thank you for your comment.
We are still using the classic template with ValueProvider and we are planning to move to the flex template in the future.
In my opinion, once we use flex templates, we may not need ValueProviders, but it would be nice to at least give users the option to use the existing classic templates.

**Comment by robertwb** [comment]
Now that we have flex templates, we prefer not propagating the ValueProvider boilerplate elsewhere without good reason, and advise flex templates for any template use that uses non-ValueProvider-enabled features. Is there a reason you cannot use flex templates?

**Comment by twosom** [comment]
> Now that we have flex templates, we prefer not propagating the ValueProvider boilerplate elsewhere without good reason, and advise flex templates for any template use that uses non-ValueProvider-enabled features. Is there a reason you cannot use flex templates?

Flex templates require a Docker image to be built, which is more complex than uploading a JAR file to Google Storage. For our company, it's easier to upload the classic templates with a single Gradle task than to use the artifact registry.

**Comment by twosom** [comment]
This may be specific to our company. I can't guarantee it's the same for other companies.
I agree that we shouldn't propagate ValueProviders without a good reason.
I'll close the PR for now, but I still think users should have a choice.

**Comment by robertwb** [comment]
> > Now that we have flex templates, we prefer not propagating the ValueProvider boilerplate elsewhere without good reason, and advise flex templates for any template use that uses non-ValueProvider-enabled features. Is there a reason you cannot use flex templates?
> 
> Flex templates require a Docker image to be built, which is more complex than uploading a JAR file to Google Storage. For our company, it's easier to upload the classic templates with a single Gradle task than to use the artifact registry.

This is good feedback. My reading of https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#build-template is that you don't have to build the docker image yourself, just provide the jar and other metadata (just like classic templates). Hopefully it shouldn't be too hard to package this gcloud command in a gradle task directly.

**Comment by twosom** [comment]
> > > Now that we have flex templates, we prefer not propagating the ValueProvider boilerplate elsewhere without good reason, and advise flex templates for any template use that uses non-ValueProvider-enabled features. Is there a reason you cannot use flex templates?
> > 
> > 
> > Flex templates require a Docker image to be built, which is more complex than uploading a JAR file to Google Storage. For our company, it's easier to upload the classic templates with a single Gradle task than to use the artifact registry.
> 
> This is good feedback. My reading of https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#build-template is that you don't have to build the docker image yourself, just provide the jar and other metadata (just like classic templates). Hopefully it shouldn't be too hard to package this gcloud command in a gradle task directly.

@robertwb 
Thanks for sharing this article.
It will help my team migrate to Flex Templates.

**Pull request closed without merging**
