### PR TITLE
[BEAM-2963] Stage the portable pipeline; put URL in pipeline options

### PR DESCRIPTION
**Pull request by kennknowles**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @lukecwik 

Same story, new place to put the info.

**Comment by lukecwik** [comment]
To my knowledge, arbitrary pipeline options don't make it to the runner harness.
Why the swap away from worker metadata configuration, did using a map -> list of kv conversion not work?

**Comment by kennknowles** [comment]
The metadata field is a Map. That wouldn't typecheck.

**Comment by kennknowles** [comment]
You mean hacking it with a custom jackson hook? I'd rather not mess with that, since pipelineoptions is already a pretty arbitrary bag and actually sort of better than VM metadata for this kind of data.

**Comment by lukecwik** [comment]
Arbitrary pipeline options still don't make it to the runner harness.

**Comment by kennknowles** [comment]
@herohde can you comment on this? I think that we have adequate control to get this info to the right place noninvasively.

**Comment by herohde** [comment]
Pipeline options are available to the runner harness in Dataflow, so this approach would work fine. It's trivial to make the runner harness grab what it needs here.

**Comment by herohde** [comment]
LGTM

**Comment by lukecwik** [comment]
LGTM

**Pull request merged**
