### PR TITLE
[BEAM-5559] Upgrade version of guava to 32.1.2-jre for all vendored a…

### PR DESCRIPTION
**Pull request by hlteoh37**
…rtifacts containing guava

Create the vendored version of 32_1_2-jre for Beam

Following guide here.
https://docs.google.com/document/d/1ztEoyGkqq9ie5riQxRtMuBu3vb6BUO91mSMn1PU0pDA/edit

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by bvolpato** [comment]
Run Go PreCommit

**Comment by bvolpato** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by damccorm** [comment]
cc/ @Abacn who was looking into this and filed https://github.com/apache/beam/issues/27801

**Comment by Abacn** [comment]
Hi, thanks for volunteering this. Can we use 32.1.2-jre? Since there were issue found in 32.1.1-jre (context: #27780)

**Comment by bvolpato** [comment]
Thanks @hlteoh37!

Guava 32.1.1-jre has a bug around dependencies that was fixed on 32.1.2-jre -- so we are jumping straight to it to avoid any related issues.

Can we bump here too?

**Comment by hlteoh37** [comment]
Sure thing, no problemos. Just upgraded it to 32.1.2-jre

**Comment by hlteoh37** [comment]
@damccorm @bvolpato   Let me know if anything else needs to be done! Since this is part of a two-part PR, once this is released I can open the 2nd PR to upgrade Beam to use this vendored dependency!

**Comment by Abacn** [comment]
Hi, I am testing the change: #27825 looks like the upgrade is non-trivial

**Comment by Abacn** [comment]
Will merge this once tests in #27825 passed

**Review by Abacn — APPROVED** [review]

**Comment by Abacn** [comment]
Validate that tests could pass in #27825 - after many newly introduced check fix. Could proceed. Merge for now

**Pull request merged**
