### PR TITLE
Revert "[BEAM-12456] Parallel querying in JdbcIO"

### PR DESCRIPTION
**Pull request by tysonjh**
Reverts apache/beam#15049

### CODE REVIEW

**Comment by tysonjh** [comment]
Run SQL PostCommit

**Comment by aromanenko-dev** [comment]
@tysonjh Why #15049 should be reverted?

**Comment by tysonjh** [comment]
> @tysonjh Could you elaborate why #15049 should be reverted?

I am investigating flakiness of the beam_PostCommit_SQL job. I'm not sure it should be reverted, but a "draft" PR is an easy way to check this on the Jenkins infra.

**Comment by aromanenko-dev** [comment]
Ok, thanks! Please, let me know if that PR is a real cause.

**Comment by tysonjh** [comment]
Run SQL PostCommit

**Comment by tysonjh** [comment]
@aromanenko-dev I think we need to revert. There are timeouts in testSQLSelectsArrayAttributes that only started after the PR was merged (see BEAM-12571), this draft PR hasn't had a single timeout in that test.

**Comment by tysonjh** [comment]
I'm running the post commits one more time to confirm.

**Comment by aromanenko-dev** [comment]
Does this test use somehow the new functionality that was added in #15049? I don't see that any old functionality was changed there.
R: @daria-malkova

**Comment by tysonjh** [comment]
False alarm! Someone pointed out to me that the test has been flaky for a while,

https://issues.apache.org/jira/plugins/servlet/mobile#issue/BEAM-12320

**Pull request closed without merging**
