### PR TITLE
[BEAM-12137] docs: incremental --> patch

### PR DESCRIPTION
**Pull request by elharo**
@suztomo @melap bring this doc into line with the terminology defined by the semver specification

### CODE REVIEW

**Comment by suztomo** [comment]
Would you create a BEAM ticket and add the ticket number in this pull request's subject line?

**Comment by melap** [comment]
I don't know the history of this, but my concern would be that it seems that Beam's "incremental" is different from semver's "patch", as incremental is listed as forward compatible, while semver's patch is backwards compatible, so I'm wondering if this is named differently as "incremental" by design/on purpose so it's more obvious to users that it's different from semver's patch definition? @aaltay do you know the history of calling it incremental vs. patch?

**Comment by aaltay** [comment]
I do not remember the history. I also do not think this wording was chosen intentionally. I think this change makes sense.

Adding @kennknowles in case he know if there is a reason for this current word choice. (If Kenn also doesn't remember then we can merge this PR.)

**Review by kennknowles — APPROVED** [review]

**Comment by kennknowles** [comment]
We did just mean to use the semver definitions: `major` is anything goes, `minor` means user can upgrade without changing their pipeline, `patch` means user can upgrade or downgrade without changing their pipeline (aka in case of diamond dependency issue that downgrades it should still work)

We don't have to be absolutist about it - if a data loss or security bug requires a breaking change we have to make it. But the spirit is useful and is our intent.

**Comment by elharo** [comment]
Thanks. Someone will need to merge this; I'm not a committer.

**Pull request merged**
