### PR TITLE
[release-2.47.0] Cherry pick #26179 into release branch

### LINKED ISSUE #26182: [Failing Test]: :sdks:java:io:jms:integrationTest Failing
### What happened?

When running the :sdks:java:io:jms:integrationTest target on the release-2.47.0 branch the following error occurs:

```
16:26:21 org.apache.beam.sdk.io.jms.JmsIOIT > testPublishingThenReadingAll[with client class class org.apache.qpid.jms.JmsConnectionFactory] FAILED
16:26:21     java.lang.AssertionError at JmsIOIT.java:195
```

This assertion is [here](https://github.com/apache/beam/blob/209c8c9cf7eeccc0b58b922d200c6a2785ea4681/sdks/java/io/jms/src/test/java/org/apache/beam/sdk/io/jms/JmsIOIT.java#L195) and is a check on the number of records read. 

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 0 (outage / failing precommit test impacting development)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #26182

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java_Jms_IO_Direct PreCommit

**Comment by Abacn** [comment]
Run Java_Jms_IO_Direct PreCommit

**Comment by Abacn** [comment]
Test passed: https://ci-beam.apache.org/job/beam_PreCommit_Java_Jms_IO_Direct_Phrase/10/

R: @jrmccluskey

**Comment by jrmccluskey** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by jrmccluskey** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by jrmccluskey** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Review by jrmccluskey — APPROVED** [review]

**Pull request merged**
