### PR TITLE
Upgrade Gradle to version 4.8

### PR DESCRIPTION
**Pull request by swegner**
https://docs.gradle.org/4.8/release-notes.html

### CODE REVIEW

**Comment by swegner** [comment]
R: @pabloem

**Comment by pabloem** [comment]
Very nice. LGTM. I'll let precommits run just to be safe, and then merge.

**Comment by pabloem** [comment]
retest this please

**Comment by pabloem** [comment]
Go was broken yesterday, so I'll go ahead and merge this.

**Pull request merged**
