### PR TITLE
Disable defensive_copy by default in InMemoryUnmergedState

### PR DESCRIPTION
**Pull request by aaltay**
Disable defensive_copy by default in InMemoryUnmergedState

Defensive copy results in lulls with the following stack trace:

 File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
 File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals)
 File "/usr/local/lib/python3.7/site-packages/dataflow_worker/start.py", line 144, in <module> main()
 File "/usr/local/lib/python3.7/site-packages/dataflow_worker/start.py", line 140, in main batchworker.BatchWorker(properties, sdk_pipeline_options).run()
 File "/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py", line 843, in run deferred_exception_details=deferred_exception_details)
 File "/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py", line 647, in do_work work_executor.execute()
 File "/usr/local/lib/python3.7/site-packages/dataflow_worker/executor.py", line 179, in execute op.start()
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 1172, in process_elements for output in uncombined:
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 1280, in process_elements state.add_state(window, self.WATERMARK_HOLD, output_time)
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 941, in add_state self.raw_state.add_state(self._get_id(window), tag, value)
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 998, in _get_id self._persist_window_ids()
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 1013, in _persist_window_ids self.raw_state.set_global_state(self.WINDOW_IDS, self.window_ids)
 File "/usr/local/lib/python3.7/site-packages/apache_beam/transforms/trigger.py", line 1404, in set_global_state value = copy.deepcopy(value)
 File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy y = copier(x, memo)
 File "/usr/local/lib/python3.7/copy.py", line 241, in _deepcopy_dict y[deepcopy(key, memo)] = deepcopy(value, memo)
 File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy y = copier(x, memo)
 File "/usr/local/lib/python3.7/copy.py", line 216, in _deepcopy_list append(deepcopy(a, memo))
 File "/usr/local/lib/python3.7/copy.py", line 141, in deepcopy d = id(x)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark
--- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aaltay** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by aaltay** [comment]
@robertwb - ping to break this back to your notification list hopefully.

**Comment by tvalentyn** [comment]
LGTM, although consider waiting for @robertwb's input. Let me know if you need me to take a deeper look on the impact of this change.

**Comment by robertwb** [comment]
I think this should be OK as long as our trigger implementations are correct (and in particular we're no longer treating triggers as UserFns but as an enumerated set so that's safer too). 

LGTM. though I am curious why this would ever get invoked in a production batch pipeline.

**Comment by aaltay** [comment]
> I think this should be OK as long as our trigger implementations are correct (and in particular we're no longer treating triggers as UserFns but as an enumerated set so that's safer too).

Ack. Do you recommend running any additional tests?

> 
> LGTM. though I am curious why this would ever get invoked in a production batch pipeline.

This is triggered by a 20 minute sliding window with 1 minute intervals and and accumulation mode accumulating. Something like:

```
beam.WindowInto(
            beam.window.SlidingWindows(size=20 * 60, period=60),
            accumulation_mode=beam.transforms.trigger.AccumulationMode.ACCUMULATING,
        )
```

**Pull request merged**
