### PR TITLE
[BEAM-1793] Pin the python postcommit jenkins nodes

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Testing:
Python SDK PostCommit Tests

### CODE REVIEW

**Comment by sb2nov** [comment]
Run Python PostCommit

**Comment by jasonkuster** [comment]
beam2 is probably fine as well.

**Comment by sb2nov** [comment]
@jasonkuster fixed

**Comment by jasonkuster** [comment]
Looks reasonable to me. Let's deploy it and see how it does.

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by jasonkuster** [comment]
Run Python PostCommit

**Comment by sb2nov** [comment]
Seems to have started on beam3

**Comment by sb2nov** [comment]
R: @jasonkuster PTAL

**Comment by jasonkuster** [comment]
Looks like this has been working well for us. I'm still following up on what's going on in the environment, so for now let's get this in. LGTM.

**Comment by sb2nov** [comment]
R: @aaltay Please merge

**Comment by aaltay** [comment]
Could you add a comment with a JIRA link, so that this can be resolved when the issue is fixed.

**Comment by sb2nov** [comment]
@aaltay done.

**Pull request closed without merging**
