### PR TITLE
Got rid of the WindmillServiceUseStreamingRpcs option from StreamingD…

### PR DESCRIPTION
**Pull request by drieber**
Streaming engine now always uses streaming RPCs. Appliance never uses streaming RPCs.

### CODE REVIEW

**Comment by drieber** [comment]
R: @dpmills

**Comment by drieber** [comment]
retest this please

**Comment by dpmills** [comment]
LGTM

**Comment by drieber** [comment]
R: @youngoli

**Comment by drieber** [comment]
R: @aaltay

**Comment by aaltay** [comment]
Run Java PreCommit

**Comment by aaltay** [comment]
@drieber could you fix the test errors?

**Comment by drieber** [comment]
retest this please

**Comment by drieber** [comment]
Sorry I missed those test errors before. I am new to the process and still learning the ropes. Because of flakes in tests on another PR I was blinded to these failures. I am still working on fixing the tests, and running into some issues. No need to look at this right now, I will hopefully have an update soon.

**Comment by drieber** [comment]
retest this please

**Comment by drieber** [comment]
retest this please

**Comment by drieber** [comment]
@aaltay, I don't know what the recent test failure means. It looks unrelated.

**Comment by drieber** [comment]
@dpmills Please take another look. I had to make test changes. I don't know what is going on with the Java PreCommit errors, they seem unrelated to me.

**Comment by drieber** [comment]
Run Java PreCommit

**Comment by dpmills** [comment]
LGTM

**Pull request merged**
