### PR TITLE
Fix topic URIs.

### PR DESCRIPTION
**Pull request by postmasters**
Just a trivial fix to the help messages.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @charlesccychen

**Comment by aaltay** [comment]
retest this please

**Comment by charlesccychen** [comment]
Looks like lint is failing.  @aaltay, can you fix this with the merge?

```
Running pylint for module apache_beam:
************* Module apache_beam.examples.streaming_wordcap
C: 38, 0: Line too long (81/80) (line-too-long)
C: 41, 0: Line too long (82/80) (line-too-long)
```

**Comment by aaltay** [comment]
Merged.

**Pull request closed without merging**
