### PR TITLE
Migrate Gradle Enterprise Plugin to Develocity Plugin

### PR DESCRIPTION
**Pull request by clayburn**
This PR updates usage of the `com.gradle.enterprise` plugin to the equivalent `com.gradle.develocity` plugin as a result of renaming Gradle Enterprise to Develocity. This change will result in no functional changes to the Beam project.

For convenience, the changes have been broken up into 4 commits:
* Applying and configuring the Develocity plugin via the new `develocity` configuration
* Mass renaming GRADLE_ENTERPRISE_ACCESS_KEY to DEVELOCITY_ACCESS_KEY for the new plugin in GitHub Actions workflows (sorry, there are lots 😅)
* Applying the most recent Common Custom User Data Gradle Plugin (2.0.1)
* Ensuring remote cache push is disabled in forks that cannot write to the remote cache

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by damccorm — COMMENTED** [review]
Thanks! This LGTM, would you just mind resolving conflicts? We should also verify that the whitespace failure is just a flake (it looks like it to me though)

**Comment by clayburn** [comment]
Merge confict is fixed 👍 

I suspect the whitespace check is a flake here too. I ran it locally from the new commit and it passed successfully: https://ge.solutions-team.gradle.com/s/72mmccuyaynyg/console-log?page=2#L1534. But I'm also not familiar with what all it is checking for.

**Review by damccorm — APPROVED** [review]
Thanks!

**Comment by tommyang** [comment]
I think this PR is causing the below build error on `settings.gradle.kts`

```
Script compilation errors:

  Line 39:   server = "[https://ge.apache.org](https://www.google.com/url?q=https://ge.apache.org&sa=D)"
             ^ Val cannot be reassigned

  Line 39:   server = "[https://ge.apache.org](https://www.google.com/url?q=https://ge.apache.org&sa=D)"
                      ^ Type mismatch: inferred type is String but Property<String!>! was expected

  Line 42:     uploadInBackground = !isCi
               ^ Val cannot be reassigned

  Line 42:     uploadInBackground = !isCi
                                    ^ Type mismatch: inferred type is Boolean but Property<Boolean!>! was expected

4 errors
```

My best guess is that Kotlin version need to use .set() instead of assignment.

**Comment by clayburn** [comment]
@tommyang  - what version of Gradle are you building with? The `=` operator has been supported by default since Gradle 8.2. With Beam being on 8.4, I'm surprised you are seeing any issue.

**Comment by tommyang** [comment]
@clayburn Thanks for the explanation. It was indeed because the Gradle version of our particular repo was out of date. Long story short, that repo has its another Gradle project with an old wrapper and the build script invoked that for Beam src code as well. Sorry for the noise.

**Comment by clayburn** [comment]
No problem, glad to help!

**Pull request merged**
