### PR TITLE
[BEAM-11922] remove broken test

### PR DESCRIPTION
**Pull request by reuvenlax**
This file was checked in by mistake - remove it.

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @tysonjh

**Comment by suztomo** [comment]
Run Java Postcommit

**Review by tysonjh — APPROVED** [review]

**Review by kennknowles — APPROVED** [review]

**Review by suztomo — APPROVED** [review]
https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/626/ says

```
Test Result (4 failures / +2)
org.apache.beam.examples.cookbook.BigQueryStorageAPIStreamingIT.testStorageAPIStreaming
org.apache.beam.examples.cookbook.BigQueryStorageAPIStreamingIT.testStorageAPIStreaming
org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPubsubMessageId
org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPublicData
--
```

MapClassIntegrationIT is not there. It's a progress toward green build. Thanks.

**Comment by tysonjh** [comment]
Bump for merge...

**Pull request merged**
