### PR TITLE
[BEAM-3112] Improve error messages in ElasticsearchIO test utils

### PR DESCRIPTION
**Pull request by echauchot**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [X] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
R: @iemejia

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Minor minor comment, don't forget to add an extra space before curly braces (I will fix this on merge).
See point 3 on https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

**Comment by echauchot** [comment]
Thanks for the review guys!
@iemejia 
1.`checkForErrors` is already tested in `ElasticsearchIOTest.testWriteWithErrors` which tries to insert 2 malformed docs. I just added a call to this method in `ElasticsearchTestUtils.insertTestDocuments` 
2. about the curly braces, I thought about adding this rule to `checktyle.xml`

**Comment by echauchot** [comment]
retest this please

**Comment by iemejia** [comment]
@echauchot It is a good idea to fix the braces issue on the checkstyle if you find a way to enforce it (I am surprised it is not enforced there), from a quicklook however it seems you will need to fix ~70 classes that don't respect the braces style.

**Pull request closed without merging**
