### PR TITLE
[BEAM-10474] Relax matchers to match display data from the specific tests, not from all options.

### PR DESCRIPTION
**Pull request by aaltay**
This is a follow up to https://github.com/apache/beam/pull/11744/files. Newly added pipeline option breaks these tests because `contains_inanyorder` requires all items to match the matcher list. Changed this to `has_items` which reverses the relationship and require each matcher to match an item.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aaltay** [comment]
@TobKed - question related to failed "Build python wheels / Build wheels on macos-latest" (https://github.com/apache/beam/pull/12288/checks?check_run_id=879924787) I do not see any logs other that "This check failed" message. How do we debug this?

**Comment by TobKed** [comment]
"This check failed" is really weird, I never seen this before. Looks like GitHub Actions issue.
I found related issue: https://github.com/actions/virtual-environments/issues/841

@aaltay do you have permission to rerun workflow? If not please push some changes e.g. rebase. It should re-trigger run and hopefully we will get more info.

**Comment by TobKed** [comment]
I found information:

> The request: 1087213 was abandoned due to an infrastructure failure. Notification of assignment to a runner was never received.

It is visible in **Annotations** section here:
https://github.com/apache/beam/actions/runs/172037362

**Comment by aaltay** [comment]
@TobKed 
- I was able to re-run the workflow, but they did not remove the failed runs for the github UI. It looked like a mix of failed/pending runs. I re-pushed to restart all tests.
- Could you add notes to the wiki (https://cwiki.apache.org/confluence/display/BEAM/Python+Tips) about troubleshooting/restarting these pipelines?
- Should we also file an issue with github? Could this be a quota issue?

**Comment by aaltay** [comment]
@tysonjh - Gradle is failing with "java.io.IOException: No space left on device" errors. Link to failing tests: https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Commit/12004/

@chamikaramj @ihji test_expand_kafka_read and test_external_transform are failing on Flink. Link to failing tests: https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Commit/5854/

**Comment by aaltay** [comment]
Restarting tests, since this failures are not related to the specific flake this PR is fixing. And triaged the issues in the previous comment.

**Comment by aaltay** [comment]
Run Portable_Python PreCommit

**Comment by aaltay** [comment]
Run Python2_PVR_Flink PreCommit"

**Comment by aaltay** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by pabloem** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by aaltay** [comment]
@chamikaramj @ihji test_expand_kafka_read and test_external_transform are failing on Flink. Link to failing tests: (https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Phrase/304/) -- same error as before. This looks like an issue, I will find the JIRA issue or file a new one.

**Comment by aaltay** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by aaltay** [comment]
> @chamikaramj @ihji test_expand_kafka_read and test_external_transform are failing on Flink. Link to failing tests: (https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Phrase/304/) -- same error as before. This looks like an issue, I will find the JIRA issue or file a new one.

I think this is fixed by (https://github.com/apache/beam/pull/12303). (@ibzib to confirm.)

**Comment by aaltay** [comment]
Re-pushed to pick up (https://github.com/apache/beam/pull/12303)

**Comment by ibzib** [comment]
Now all the external transform tests in Python2_PVR_Flink are timing out instead. I'm thinking about either increasing the timeouts to these tests, or removing them since they might be redundant (XVR_Flink has its own postcommit already).

**Comment by aaltay** [comment]
@ibzib - May I ignore the failure and merge this change? I think this change is good (passing other tests). And it would be good to merge this as it address another flakiness.

**Comment by ibzib** [comment]
> @ibzib - May I ignore the failure and merge this change? I think this change is good (passing other tests). And it would be good to merge this as it address another flakiness.

Yes, I think the failure is fine to ignore.

**Comment by TobKed** [comment]
@aaltay 

> - Could you add notes to the wiki (https://cwiki.apache.org/confluence/display/BEAM/Python+Tips) about troubleshooting/restarting these pipelines?

Sure. What is the process to do it?

> - Should we also file an issue with github? Could this be a quota issue?

I see it is still happens: https://github.com/apache/beam/actions/runs/175737977
I think it is not related to the quota, at least not from project side. Seems like GitHub have some issues with infrastructure.
There is issue created: https://github.com/actions/virtual-environments/issues/841 . I will observe it.

**Comment by aaltay** [comment]
> @aaltay
> 
> > * Could you add notes to the wiki (https://cwiki.apache.org/confluence/display/BEAM/Python+Tips) about troubleshooting/restarting these pipelines?
> 
> Sure. What is the process to do it?

Thank you.

There is really not much of a process. Anyone can signup and edit the wiki. After you signup/login, you can go to the page I linked, edit and add a small section about these tests. Does it make sense?

> 
> > * Should we also file an issue with github? Could this be a quota issue?
> 
> I see it is still happens: https://github.com/apache/beam/actions/runs/175737977
> I think it is not related to the quota, at least not from project side. Seems like GitHub have some issues with infrastructure.
> There is issue created: [actions/virtual-environments#841](https://github.com/actions/virtual-environments/issues/841) . I will observe it.

**Comment by tysonjh** [comment]
> @tysonjh - Gradle is failing with "java.io.IOException: No space left on device" errors. Link to failing tests: https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Commit/12004/

This was fixed AFAICT by running some Jenkins jobs to clean up the local storage. Sorry about the delayed response.

**Comment by TobKed** [comment]
I created PR with documentation for GItHub Actions CI https://github.com/apache/beam/pull/12405

**Pull request merged**
