### PR TITLE
Update maven-dependency-plugin to version 3.0.1

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @jbonofre 
This is a trivial one just updated the plugin because it addresses
https://issues.apache.org/jira/browse/MDEP-409
And some other fixes.

**Comment by iemejia** [comment]
I had to rebase to add two extra missing dependencies found by the new version of the plugin.
It should be ok now.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
The build fails on python, I'm checking on my machine.

**Comment by iemejia** [comment]
It looks good now it seems.

**Comment by jbonofre** [comment]
It looks good now !

**Comment by iemejia** [comment]
Can you merge it, or do I?

**Comment by jbonofre** [comment]
Done

**Comment by iemejia** [comment]
Thx JB.

**Pull request merged**
