### PR TITLE
[BEAM-1035][BEAM-1115] Support for new State and Timer API in Spark batch runner

### PR DESCRIPTION
**Pull request by JingsongLi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @aviemzur

**Comment by aviemzur** [comment]
Run Spark ValidatesRunner

**Comment by aviemzur** [comment]
I think @amitsela should be the reviewer for this one.

**Comment by JingsongLi** [comment]
I close it and start a new PR with BEAM-2175

**Pull request closed without merging**
