### PR TITLE
feat: optimize Spanner changestream metadata table

### PR DESCRIPTION
**Pull request by thiagotnunes**
Adds indexes to the SpannerIO change streams metadata table. This serves to optimize two specific queries:

1. `getUnfinishedMinWatermark`
2. `getAllPartitionsCreatedAfter`

(micro-)Benchmarking results with a metadata table containing 11 million rows:

| Method | No Indexes (current) | Index (this PR) |
| --------- | -------- | ------- |
| getUnfinishedMinWatermark | 3.190s (+/- 0.91s) | 0.020s (+/- 0.002s) |
| getAllPartitionsCreatedAfter | 1.250s (+/- 0.230s) | 0.012s (+/- 0.001s) |

Customers can add these index manually if they want to by running the following DDL statements:

```sql
-- For GoogleSQL dialect
CREATE INDEX WatermarkIndex ON <Metadata Table Name> (Watermark) STORING (State);
CREATE INDEX CreatedAtStartTimestampIndex ON <Metadata Table Name> (CreatedAt, StartTimestamp);

-- For PostgreSQL dialect
CREATE INDEX "WatermarkIndex" ON <Metadata Table Name> ("Watermark") INCLUDE ("State");
CREATE INDEX "CreatedAtStartTimestampIndex" ON <Metadata Table Name> ("CreatedAt", "StartTimestamp");
```

### CODE REVIEW

**Comment by thiagotnunes** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by thiagotnunes** [comment]
assign set of reviewers

**Review by Abacn — APPROVED** [review]
LGTM, From the benchmark it sounds a great optimization!

**Comment by velamkao** [comment]
Hi @thiagotnunes would you know if this change to add the index is going to be part of Beam 2.59.0 release?

**Comment by velamkao** [comment]
> feat: index creation toga4/spream#106

Never mind, I can see its there https://github.com/apache/beam/blob/v2.59.0-RC1/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/changestreams/dao/PartitionMetadataAdminDao.java

**Pull request merged**
