### PR TITLE
[BEAM-2020] Remove Coder.asCloudObject and related methods

### PR DESCRIPTION
**Pull request by tgroh**
These methods belong in the Dataflow module.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
LGTM, assuming tests pass this can be merged.

**Comment by lukecwik** [comment]
retest this please

**Comment by lukecwik** [comment]
Opened #2825 as a rebase of this on top of apache/master

**Comment by tgroh** [comment]
This is going to need a new worker to be able to handle the TimerOrElementCoder

**Comment by lukecwik** [comment]
Built `beam-master-20170502` which includes `TimerOrElementCoder` translator, please update worker and retest.

**Comment by tgroh** [comment]
Done

**Comment by lukecwik** [comment]
woot, merged

**Pull request closed without merging**
