### PR TITLE
GA migration Precommit Pylint, PyDocs, PythonFormatting

### PR DESCRIPTION
**Pull request by benEng**
As part of the migration of Precommit and Postcommit Jobs from Jenkins to GA in self-hosted runners, this PR contains:

- Migrated workflow [job-precommit-pythondocs](https://github.com/apache/beam/blob/d9d893b835ecc2f50942c19dc11918dd005f4102/.github/workflows/job-precommit-pythondocs.yml)
- Migrated workflow [job-precommit-pythonformatter](https://github.com/apache/beam/blob/d9d893b835ecc2f50942c19dc11918dd005f4102/.github/workflows/job-precommit-pythonformatter.yml)
- Migrated workflow [job-precommit-pythonlint](https://github.com/apache/beam/blob/d9d893b835ecc2f50942c19dc11918dd005f4102/.github/workflows/job-precommit-pythonlint.yml)

The migrated workflows were removed from [.test-infra/jenkins/README.md](https://github.com/apache/beam/blob/d9d893b835ecc2f50942c19dc11918dd005f4102/.test-infra/jenkins/README.md) and added to [CI.md](https://github.com/apache/beam/blob/d9d893b835ecc2f50942c19dc11918dd005f4102/CI.md)

**DO NOT MERGE** until the effort to use **self-hosted runners** is completed https://github.com/apache/beam/pull/22703

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by benWize** [comment]
Successful executions on self-hosted runners:

- Pylint https://github.com/benWize/beam/runs/8234978027?check_suite_focus=true
- Python Formatter https://github.com/benWize/beam/runs/8234363500?check_suite_focus=true
- Python Docs https://github.com/benWize/beam/actions/runs/3009699275

**Comment by benWize** [comment]
Run Whitespace PreCommit

**Comment by fernando-wizeline** [comment]
LGTM!

**Review by damccorm — APPROVED** [review]
LGTM, thanks

**Pull request closed without merging**
