### PR TITLE
[BEAM-7092] Fix artifact names for Spark separated modules + upgrade to Spark 3.1.1

### PR DESCRIPTION
**Pull request by iemejia**
Some minor details I forgot and I realized were not ok after double checking with the generated SNAPSHOTs
R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by iemejia** [comment]
Thanks for the prompt review @ibzib!

**Pull request merged**
