### PR TITLE
Add Lineage metrics to PubsubIO

### PR DESCRIPTION
**Pull request by Abacn**
Covers

UnboundedReader
PubsubBoundedWriter
PubsubUnboundedWriter (PubsubSink / PubsubDynamicSink)

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
tested on integration test (rebased on #32022)

PubsubReadIT:

after

```
PipelineResult job = pipeline.run();
```

print

```
(job.metrics().queryMetrics(MetricsFilter.builder().addNameFilter(MetricNameFilter.named(LINEAGE_NAMESPACE, SOURCE_METRIC_NAME)).build()).getStringSets());
```

get

```
StringSetResult{stringSet=[pubsub:topic:pubsub-public-data.taxirides-realtime]}}
```

PubsubWriteIT:

replace to use `SINK_METRIC_NAME`, query gets

```
StringSetResult{stringSet=[pubsub:topic:apache-beam-testing.pubsub-write-1722451794792
```

**Comment by Abacn** [comment]
R: @rohitsinha54

**Review by rohitsinha54 — APPROVED** [review]
Would it be possible to update any of the PubSub integration tests which runs in dataflow runner to assert for lineage metrics?

**Comment by Abacn** [comment]
We can and should do this after runner support cleared. currently Pubsub integration tests are running on both direct runner / legacy Dataflow / Dataflow v2. When I add asserts currently it will only pass on Legacy runner suite (Direct runner suite will also pass after #32022 in)

**Comment by Abacn** [comment]
a couple of unit tests failed due to that the fake topic/subscription does not follow the expected topic/subscription format, direct runner integration tests all passed however

**Pull request merged**
