### PR TITLE
refactor HCLS IO ITs to support stores in other projects

### PR DESCRIPTION
**Pull request by jaketf**
This will enable more flexibility in test suites for putting stores in other projects.
Motivating use case: negative integration testing for writing to stores outside VPC-SC perimeter.

R: @pabloem 
CC: @tvalentyn 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by pabloem** [comment]
retest this please

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
LGTM

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
ah there seem to be failures in FhirIOWriteIT

**Comment by pabloem** [comment]
https://builds.apache.org/job/beam_PostCommit_Java_PR/399/console

**Comment by pabloem** [comment]
fyi @jaketf

**Comment by pabloem** [comment]
@jaketf @lastomato let me know if I should take a look at this

**Comment by aaltay** [comment]
@jaketf - what is the next step on this PR?

**Comment by jaketf** [comment]
My focus has been shifted to other customers.
Taking a look at why this test was failing now, will update this thread with a commit to fix or findings.

**Comment by jaketf** [comment]
I was able to reproduce this failure.
It occurs when using the import method and [falling back to using the temp storage](https://github.com/apache/beam/blob/e68a38b1706225c3b95216471e331ae410fadc0f/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java#L801)
namely "`gs://temp-storage-for-end-to-end-tests`" rather than using the
"`gs://temp-storage-for-healthcare-io-tests`" for which the appropriate permissions have been granted to the Healthcare Service Account.

I thought this should be handled by setting the gcsTempPath pipeline options [here](https://github.com/apache/beam/pull/11959/files#diff-24800457f8326467edabf56d21f334ffR79)

I'll try to pin down if the option is not being properly set or if this is a Bug in how FhirIO reads this parameter.

**Comment by jaketf** [comment]
ultimately we need to make sure service-[project_number]@gcp-sa-healthcare.iam.gserviceaccount.com has Storage Object Viewer on the buckets we are importing from.

**Comment by aaltay** [comment]
We can add you to the GCP project we use for testing to setup what you need. Would that work?

**Comment by jaketf** [comment]
I have some level of access but I need additional permissions to modify IAM

**Comment by jaketf** [comment]
retest this please

**Comment by jaketf** [comment]
Run Java PostCommit

**Comment by jaketf** [comment]
Run Java PostCommit

**Comment by jaketf** [comment]
@aaltay @pabloem checks seem good now. LMK if this needs anything else

**Comment by aaltay** [comment]
@pabloem - Could you merge this if this looks good? I have not reviewed the PR.

**Comment by pabloem** [comment]
thanks everyone!

**Pull request merged**
