### PR TITLE
[BEAM-7390] Add code snippet for GroupIntoBatches

### PR DESCRIPTION
**Pull request by davidcavazos**
Adding the code snippets for `GroupIntoBatches`.

R: @chamikaramj   

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by davidcavazos** [comment]
@aaltay, I have some questions in this one:

* What is the difference between `GroupIntoBatches` and `BatchElements`?
* Which is the recommended approach?
* I found that `BatchElements` was both more intuitive and flexible since it doesn't require a key, should we get rid of the `GroupIntoBatches` example in favor of `BatchElements` or is there a scenario where `GroupIntoBatches` make more sense?

**Comment by aaltay** [comment]
> Hi @chamikaramj and @raheelkhan, this code snippet will be displayed in the docs. I have some questions:
> 
> * What is the difference between `GroupIntoBatches` and `BatchElements`?
> * Which is the recommended approach?
> * I found that `BatchElements` was both more intuitive and flexible since it doesn't require a key, should we get rid of the `GroupIntoBatches` example in favor of `BatchElements` or is there a scenario where `GroupIntoBatches` make more sense?

See the discussion on https://github.com/apache/beam/pull/8914 for differences between the two transforms.

**Comment by davidcavazos** [comment]
@aaltay, from your [comment](https://github.com/apache/beam/pull/8914#issuecomment-504609011) and the rest of the discussion I'm gathering the following:

`BatchElements`
- Does **not** use state and timer APIs (more portable across runners that don't support them)
- Does **not** support streaming (is this correct?)
- Can use keyed or un-keyed elements
- Supports batch auto-sizing
- Does **not** match any Java transform

`GroupIntoBatches`
- Uses state and timer APIs (can't be used in some runners)
- Supports streaming
- Must use keyed elements
- Fixed-sized batches only
- Matches the Java transform

Are these observations correct? Am I missing anything?

If so, it might be worthwhile to have samples for both transforms and have a note on these differences in the docs, as well as a link to [BEAM-6696](https://issues.apache.org/jira/browse/BEAM-6696) for more details.

I noticed that `GroupIntoBatches` *requires* keyed inputs, but I couldn't figure out what the keys are used for. I used `None` keys in the sample, but it seems cumbersome to have to add keys to use this transform.

**Comment by davidcavazos** [comment]
@aaltay friendly ping :)

**Comment by aaltay** [comment]
I think we would like to converge on one of the transforms. Probably to GroupIntoBatches once state is supported in all runners. Not sure if it makes sense to have snippets for both for now. It is a bit confusing and we might not want to advertise it.

**Comment by davidcavazos** [comment]
I can remove the sample for `BatchElements` then, but do you at least know what the key in `GroupIntoBatches` is used for? I couldn't find any use, but it's still required so I used `None` keys.

**Comment by aaltay** [comment]
> I can remove the sample for `BatchElements` then, but do you at least know what the key in `GroupIntoBatches` is used for? I couldn't find any use, but it's still required so I used `None` keys.

State and timer are keyed. This pardo will keep batches per-key, and release bundles per key. Each batch seemingly will have values from the same key.

**Comment by davidcavazos** [comment]
I will get rid of `BatchElements` and keep `GroupIntoBatches`. I will also update the sample to use keys as well.

**Comment by davidcavazos** [comment]
@aaltay sorry for the delay on this, this should be ready for review.

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
Last 3 test runs failed, could you check the logs?

**Comment by davidcavazos** [comment]
It looks like the test was not deterministic under certain environments, especifically Python 2 and Cloud tests. I changed it so it only checks the size of the batches, but not the actual elements.

**Comment by davidcavazos** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by davidcavazos** [comment]
Sorry, forgot to run the linter. I changed the nested function to a lambda and `yapf`ed over the files so that shouldn't be an issue anymore.

**Comment by davidcavazos** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
Do you know why tests are failing?

**Comment by aaltay** [comment]
retest this please

**Comment by davidcavazos** [comment]
I have no idea, there are a bunch of unrelated errors like `ERROR:apache_beam.runners.worker.data_plane:Failed to read inputs in the data plane.`, as well as some errors with the flink runner.

I'll try refreshing to the latest version.

**Comment by aaltay** [comment]
Tests passed, merging this.

**Pull request merged**
