### PR TITLE
[BEAM-4233] [SQL] Use the same javacc and fmpp as calcite

### PR DESCRIPTION
**Pull request by apilloud**
Calcite uses very specific versions of javacc and fmpp. We should use those so we don't hit bugs caused by incompatibilities.

### CODE REVIEW

**Comment by apilloud** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Seems wise. I'll merge when green.

**Comment by apilloud** [comment]
FYI this is green.

**Comment by swegner** [comment]
FYI, this pins up to a very old version of javacc, which produces lint warnings when compiling the generated code: see #5669

https://github.com/swegner/beam/commit/fe3232cdf6990b3ad282f1c4e588308e1ff30483 fixes this compiler warning by upgrading the javacc version.

Do we need to stay pinned to this old version? Were we seeing particular incompatibilities?

**Comment by apilloud** [comment]
Unfortunately we are pinned to the version that calcite is on. The newer versions make incompatible changes, which results in generated code that doesn't work.

**Comment by swegner** [comment]
Thanks for the context @apilloud. I don't think it's worth pursuing the upstream change to get rid of a lint warning. I'm fine suppressing this.

@cademarkegard check out https://github.com/cademarkegard/beam/pull/2 which adds the configuration to add lint suppressions per-project.

**Pull request merged**
