### PR TITLE
Suppress FutureWarnings for Pandas < 2

### PR DESCRIPTION
**Pull request by caneff**
~600 warnings due to stuff that is deprecated by Pandas 1.5 and removed by 2.  It would be too annoying to capture them individually.

### CODE REVIEW

**Comment by caneff** [comment]
R: @tvalentyn

**Comment by caneff** [comment]
R: @tvalentyn

**Comment by caneff** [comment]
Run PythonLint PreCommit

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
ptal at lint errors

**Comment by tvalentyn** [comment]
Run PythonLint PreCommit

**Pull request merged**
