### PR TITLE
[BEAM-3031] Use blocking grpc dial in Go unit tests

### PR DESCRIPTION
**Pull request by herohde**
Debugging Go unit test failure on Jenkins only.

### CODE REVIEW

**Comment by herohde** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
The Go precommits passed - kicking them again just to see if it was luck.

**Comment by herohde** [comment]
retest this please

**Comment by herohde** [comment]
That run failed in setup before even getting to any Go tests

**Comment by herohde** [comment]
retest this please

**Pull request merged**
