### PR TITLE
[BEAM] Fixed handling of --use_public_ips.

### PR DESCRIPTION
**Pull request by mdvorsky**
R: @aaltay

### CODE REVIEW

**Comment by aaltay** [comment]
LGTM

**Comment by kennknowles** [comment]
Unfortunately it seems that `store_true` still allows a value via `--use_public_ips=false` but our usage of the result does not take this into account (https://issues.apache.org/jira/browse/BEAM-13709)

**Comment by aaltay** [comment]
Thank you Kenn. @tvalentyn - assigned (issues.apache.org/jira/browse/BEAM-13709) to you.

**Comment by AnandInguva** [comment]
> Unfortunately it seems that `store_true` still allows a value via `--use_public_ips=false` but our usage of the result does not take this into account (https://issues.apache.org/jira/browse/BEAM-13709)

From my understanding, we shouldn't allow the use of booleans `--use_public_ips=False` programmatically with `PipelineOptions` class(to maintain consistency with `argparse`). We would only allow boolean options with `True` and discard/ignore the options with value `False`.

**Comment by aaltay** [comment]
@AnandInguva - Let's move the discussion to the jira.

> We would only allow boolean options with True and discard/ignore the options with value False.

This is fine. But it needs to be very obvious to the user. (like an error or a very visible warning.)

**Pull request closed without merging**
