### PR TITLE
[#25417][go] copy env details to dataflow images

### PR DESCRIPTION
**Pull request by lostluck**
Handle #25417 but in the Go SDK.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @chamikaramj

**Review by chamikaramj — APPROVED** [review]
LGTM. Thanks.

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Definitely making it to dataflow now:

```
     "sdkHarnessContainerImages": [
14:43:16           {
14:43:16             "capabilities": [
14:43:16               "beam:protocol:progress_reporting:v1",
14:43:16               "beam:protocol:multi_core_bundle_processing:v1",
14:43:16               "beam:transform:sdf_truncate_sized_restrictions:v1",
14:43:16               "beam:protocol:worker_status:v1",
14:43:16               "beam:protocol:monitoring_info_short_ids:v1",
14:43:16               "beam:version:sdk_base:go:apache/beam_go_sdk:2.46.0.dev",
14:43:16               "beam:coder:bytes:v1",
14:43:16               "beam:coder:bool:v1",
14:43:16               "beam:coder:varint:v1",
14:43:16               "beam:coder:double:v1",
14:43:16               "beam:coder:string_utf8:v1",
14:43:16               "beam:coder:length_prefix:v1",
14:43:16               "beam:coder:kv:v1",
14:43:16               "beam:coder:iterable:v1",
14:43:16               "beam:coder:state_backed_iterable:v1",
14:43:16               "beam:coder:windowed_value:v1",
14:43:16               "beam:coder:global_window:v1",
14:43:16               "beam:coder:interval_window:v1",
14:43:16               "beam:coder:row:v1",
14:43:16               "beam:coder:nullable:v1"
14:43:16             ],
14:43:16             "containerImage": "us.gcr.io/apache-beam-testing/jenkins/beam_go_sdk:20230210-201800",
14:43:16             "environmentId": "go"
```

**Pull request merged**
