### PR TITLE
[BEAM-14437] Raise Java HTTP KeepAliveCache size

### PR DESCRIPTION
**Pull request by arunpandianp**
Java HTTP[S]Connection's keep alive by default keeps 5 idle connections alive. Dataflow user workers could make 1000s of connection to the same endpoint. The HTTPS handshake overhead is significant in pipelines using BigQueryIO streaming inserts and bumping up the keep alive limit reduces it.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by arunpandianp** [comment]
R: @kennknowles

**Comment by arunpandianp** [comment]
I have some trouble with my local docker setup, so couldn't build the containers with the gradle targets locally and test.

**Comment by kennknowles** [comment]
Is this going to be a safe default across lots of different contexts? This same code runs locally, during testing, on Spark & Flink & Samza, etc.

**Comment by arunpandianp** [comment]
> Is this going to be a safe default across lots of different contexts?

Thinking more about this, It is hard to say for sure. Since there is a way to set the setting using JvmInitializers, I'll close this PR.

**Pull request closed without merging**
