### PR TITLE
[GO SDK] - avroio null fix

### PR DESCRIPTION
**Pull request by jgill02**
Fixes [#26316](https://github.com/apache/beam/issues/26316).

In situations where there are nullable fields in an avro ocf file, previously a previous row's non-null value for a given column would be passed into a pcollection for a subsequent datum if that column was null.

Added a new test case to check for this, which failed using the previous logic.

Additionally, the previous avroio package was using a legacy version (2.1.0) which is ~3-4+ years old. Upgraded to the latest goavro/v2 version. 

Amongst other bug fixes, this release of goavro is ~3-4x faster than the previous version (as documented on the goavro github [page](https://github.com/linkedin/goavro#major-improvements-in-v2-over-v1).)

I am not 100% sure if there are additional dependencies to the previous goavro package which I do not understand, in which case this PR can be scoped to solely the bug fix mentioned above as an alternative.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by riteshghorse — APPROVED** [review]
Thank you for contributing! Mostly looks good!

One question - can we use the test avro file from GCS or any other bucket instead of storing it in the repo?

**Comment by jgill02** [comment]
Hi Ritesh, thank you so much for your review. Regarding using a GCS bucket or something of that nature, I would certainly be happy to implement that, but just wanted to call out I was trying to replicate the existing set-up I saw (e.g. existing test case has a [tweet.avro](https://github.com/apache/beam/blob/master/sdks/go/data/tweet.avro) file added to the repo). 

I could instead use a GCS location, but could use a suggestion on which public bucket to add it to so it will be persistent and available.

Thank you again for your review and help!

**Comment by riteshghorse** [comment]
Thanks John, that sounds good!

I'll merge once the checks pass. Thanks again!

**Comment by riteshghorse** [comment]
Run Go PreCommit

**Comment by riteshghorse** [comment]
Failure not related to this PR. Merging!

**Pull request merged**
