### PR TITLE
Revert "[BEAM-8335] Add PCollection to DataFrame logic for InteractiveRunner."

### PR DESCRIPTION
**Pull request by kamilwu**
Reverts apache/beam#10915
Changes break PythonLint and PreCommit (pycommon:docs is failing)

### CODE REVIEW

**Comment by kamilwu** [comment]
Run Python PreCommit

**Comment by kamilwu** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by kamilwu** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by kamilwu** [comment]
R: @mwalenia

**Comment by mwalenia** [comment]
LGTM, merging. Thanks!

**Pull request merged**
