### PR TITLE
[BEAM-3029] Sets user agent in BigTableIO.Read.getBigTableService().

### PR DESCRIPTION
**Pull request by chamikaramj**
Cherry-picking this commit to 2.2.0 release branch.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @reuvenlax

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by reuvenlax** [comment]
lgtm for self-merge.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Retest this please.

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Seems like Jenkins runs are failing for unrelated reasons. But "mvn clean verify" passed for me locally and all Jenkins runs passed for HEAD. So will go ahead and merge.

**Comment by kennknowles** [comment]
This was not closed properly because the "closes #3998" trick only applies to master. For the release branch, I recommend doing a proper merge commit instead. You can always rebase the PR first, and then do a merge. This will put the PR in a nearly linear chain but still maintain the correct git lineage.

**Comment by chamikaramj** [comment]
Thanks. Closing.

**Pull request closed without merging**
