### PR TITLE
[BEAM-7750] Don't map transforms to PubSub subscriptions unless necessary

### PR DESCRIPTION
**Pull request by ostrokach**
Streaming pipelines that read from a PubSub topic and are executed using `BundleBasedDirectRunner` are never garbage collected because the [`_PubSubReadEvaluator._subscription_cache`](https://github.com/apache/beam/blob/27bb5bc7b244809e7f6022adb2730d10204ce4d3/sdks/python/apache_beam/runners/direct/transform_evaluator.py#L418) class attribute keeps references to all `ReadFromPubSub` transforms for the duration of the Python session. This is not ideal in the case of interactive pipeline prototyping and development, where the user may start and stop multiple pipelines from the same session

This PR makes two functional changes:
- Change `_PubSubReadEvaluator._subscription_cache` to keep references to only those subscriptions that are created by `_PubSubReadEvaluator`. This means that Pipelines will be correctly garbage collected if the user supplies a subscription, rather than a topic, to `ReadFromPubSub`.
- Use [`atexit.register`](https://docs.python.org/3/library/atexit.html#atexit.register) rather than [`__del__`](https://docs.python.org/3/reference/datamodel.html#object.__del__) to clean up subscriptions created by the `_PubSubReadEvaluator` class. According to the CPython documentation, "it is not guaranteed that `__del__()` methods are called for objects that still exist when the interpreter exits". Since the `_PubSubReadEvaluator._subscription_cache` class attribute will keep references to all created subscriptions until interpreter exists, it is not guaranteed that `__del__()` is called for any of those subscriptions. Using `atexit.register` is a better fit in this case. This partially (or fully?) addresses [BEAM-2988](https://issues.apache.org/jira/browse/BEAM-2988).

CC: @ivant @ananvay 
R: @aaltay 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by ostrokach** [comment]
Run Portable_Python PreCommit
Run Python_PVR_Flink PreCommit

**Comment by ostrokach** [comment]
Run Portable_Python PreCommit

**Comment by ostrokach** [comment]
Run Portable_Python

**Comment by ostrokach** [comment]
Run Portable PreCommit

**Comment by ostrokach** [comment]
retest this please

**Comment by ostrokach** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
LGTM.

cc: @charlesccychen in case he has additional comments since he is the original author.

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

**Pull request merged**
