### PR TITLE
Move _CreateSource to its own package to make it pickelable

### PR DESCRIPTION
**Pull request by aljoscha**
This is needed because executing a Read as a
Impulse() | ParDo(Split) | ParDo(Read) requires the source to be
pickelable in the splits we emit in ParDo(Split).

### CODE REVIEW

**Comment by robertwb** [comment]
Modulo a lint error

`W: 47, 4: Reimport 'iobase' (imported line 18) (reimported)`

**Comment by robertwb** [comment]
Jenkins: retest this please.

**Comment by robertwb** [comment]
Looks good, can you squash?

**Comment by aljoscha** [comment]
@robertwb squashed and rebased on master

**Comment by aljoscha** [comment]
retest this please

**Pull request merged**
