### PR TITLE
[BEAM-10496] Eliminate some null errors from core SDK coders

### PR DESCRIPTION
**Pull request by kennknowles**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @y1chi

since now you are expert at coders :-)

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by kennknowles** [comment]
Run Kotlin_Examples PreCommit

**Review by y1chi — APPROVED** [review]
LGTM

**Comment by kennknowles** [comment]
org.apache.beam.sdk.io.pulsar.PulsarIOTest.testReadFromSimpleTopic: `Trying to claim offset 1655243286428 before start of the range [1655243286848, 1655243286859)`

**Comment by kennknowles** [comment]
run java precommit

**Pull request merged**
