### PR TITLE
[runners-flink] #29558 emit watermark before source shutdown

### LINKED ISSUE #29558: [Bug]: Impulse in FlinkRunner does not emit watermark
### What happened?

Impulse in Flink creates FlinkBoundedSource and does not emit watermarks until `--shutdownSourcesAfterIdleMs` time elapses (default is infinite).

Related issues is that if job fails and is restored before the Impulse reader is shutdown, the impulse is resent, which might retrigger recomputation downstream.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by je-ik**
* added position to FlinkBoundedSource checkpoint

Fixes #29558 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by je-ik** [comment]
@becketqin I created this WIP solution which seems to fix the issue for me. Can you take a look? If the solution looks good, I'd add some more tests.

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
@JozoVilcek Added test for the watermark emission, the checkpointing is covered by the updated test.

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by je-ik** [comment]
stop reviewer notifications

**Comment by je-ik** [comment]
R: @JozoVilcek

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by JozoVilcek** [comment]
R: @JozoVilcek

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Pull request merged**
