### PR TITLE
[BEAM-3213] MongodbIO performance test

### PR DESCRIPTION
**Pull request by lgajowy**
An IT for MongoDBIO. 

I suggested different Kubernetes scripts naming for mongo than for postgres scripts. The postgres' naming is quite confusing to me - the "local" scripts are used everywhere right now, not only while running tests locally, so why call them "local"?

There is another thing that bothers me: the node port service Kubernetes setup can be used only if the **whole** test (including `setup()` and `teardown()` methods) is run in the same network, as the k8 cluster is (to have direct access to pod IPs). This doesn't happen on Jenkins nor while running locally. This can happen if we are running sole pipeline without settingUp()/tearingDown() any connections but it's a rare situation for tests using databases. Also it works for Dataflow runner only.

Maybe we should consider dropping the node port service from Kubernetes scripts and keep load balancer service only? Maybe there are some historical reasons I am not aware of?

@chamikaramj @alanmyrvold could you take a look?

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by chamikaramj** [comment]
cc: @jbonofre

**Comment by lgajowy** [comment]
@jbonofre could you take a look?

**Comment by jbonofre** [comment]
Sure, I gonna take a look later today or tomorrow. Thanks. Sorry for the delay.

**Comment by chamikaramj** [comment]
Thanks JB. I'll merge after tests pass.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by lgajowy** [comment]
Run Java PreCommit

**Comment by lgajowy** [comment]
> Build timed out (after 150 minutes). Marking the build as aborted.

The failure seems to be unrelated with this PR. Should we try again?

**Pull request merged**
