### PR TITLE
[BEAM-4034] Fix hooks panic with Go on Flink

### PR DESCRIPTION
**Pull request by herohde**
Downgrading the panic to a warning.

### CODE REVIEW

**Comment by herohde** [comment]
Thanks!

R: @robertwb (please merge)

**Comment by herohde** [comment]
CC: @aljoscha @tweise (feel free to merge, too)

**Comment by wcn3** [comment]
Bit late, but could we have GetOptionWithDefault as a vehicle? That way, the default value could be "{}" which would unmarshal as empty options, and then we wouldn't need the warning paths. WDYT?

**Comment by herohde** [comment]
In this particular case, I think we do want a warning (or error, even). It's an expectation that every running using the harness serializes hooks and we want to notice if that was not done.

**Pull request merged**
