### PR TITLE
[BEAM-4181] Add ReadFiles transform to TfRecordIO

### PR DESCRIPTION
**Pull request by RyanSkraba**
Minor improvement to add a FileIO-based `readFiles()` to the TensorFlow IO.

https://issues.apache.org/jira/browse/BEAM-4181

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by RyanSkraba** [comment]
R: @chamikaramj  Can you take a look?

**Comment by RyanSkraba** [comment]
Run JavaPortabilityApi PreCommit

**Comment by RyanSkraba** [comment]
Heyo -- just a quick question on reflection.  Should I refactor the existing `Read`/`read()` transform to use this proposed `ReadFiles`/`readFiles()` ?  I see that some other FileIOs do this.

If yes, how do you feel about the `read().withHintMatchesManyFiles()` to switch between the original `read()` and new `readFiles()` technique?  I see TextIO and AvroIO do this, but I'm not sure whether this is "best practices".  

It's weird to me to refactor the original `read()` to require a "hint" to use the new implementation, when the new implement is ... just right there below it!  WDYT?

**Comment by chamikaramj** [comment]
R: @pabloem 

Sorry about the delay here. Pablo agreed to take over this review so passing to him.

**Comment by chamikaramj** [comment]
Usually, the difference between Read and ReadFiles transforms is that, ReadFiles currently does not support dynamic work rebalancing while Read does (this will change with SDF).

I see that, for TFRecordIO, we do not support dynamic work rebalancing anyways, so refactoring Read transform to use proposed ReadFiles should be fine.

I don't think we need the hint if we use ReadFiles for both implementations.

**Comment by pabloem** [comment]
Thanks Cham. It's useful to get your advice here : )

I've looked at the implementation, and it LGTM. @RyanSkraba let me know if you'd like to do any refactoring, or if you'd just like me to merge this.

**Comment by RyanSkraba** [comment]
Thanks for the review!  Please go ahead and merge it -- before doing any additional internal refactoring (which wouldn't make much difference here), I'd like to take a tour around the existing file-based IOs to identify where they're consistent or different.

**Pull request merged**
