### PR TITLE
Cherrypick #31550 and #31602 onto release branch

### PR DESCRIPTION
**Pull request by shunping**
Cherry-pick #31550 and #31602 onto release branch

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by kennknowles — APPROVED** [review]
will merge when green

**Comment by kennknowles** [comment]
This may be red on the release branch:

```
apache_beam/internal/gcp/auth.py:82: error: Incompatible return value type (got "Optional[_ApitoolsCredentialsAdapter]", expected "Optional[Credentials]")  [return-value]
apache_beam/internal/gcp/auth_test.py:29: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
Found 2 errors in 2 files (checked 1147 source files)
```

**Comment by shunping** [comment]
right. I think that has been fixed in master recently but needs to be cherry-picked as well. https://github.com/apache/beam/commit/47d9bca8bf1f2ce9109df86377b6162823794888

@jrmccluskey

**Comment by kennknowles** [comment]
it will make me happy if you will rebase so it can be green for sure (yes, I know it is very obvious and we are confident what the problem was)

**Comment by shunping** [comment]
Tests are alll green now.

**Comment by shunping** [comment]
@kennknowles Could you help to merge this?

**Comment by shunping** [comment]
@kennknowles:

This PR is causing certain internal test failure. If you have not merged that, please skip it for this release (2.57.0).

**Comment by kennknowles** [comment]
I can cp both. There is time. go ahead and open the other one to cherrypick as well

**Comment by shunping** [comment]
> I can cp both. There is time. go ahead and open the other one to cherrypick as well

The fix PR depends on the previous change. It may be easier to put both into one.

**Comment by shunping** [comment]
Run Python PreCommit 3.11

**Pull request merged**
