### PR TITLE
Cherrypick iceberg autosharding

### PR DESCRIPTION
**Pull request by ahmedabu98**
Cherrypicking #32612

### CODE REVIEW

**Comment by Abacn** [comment]
this cherry pick has different diff than the original PR, could you please simply run `git cherry-pick d84cfffd017342542cc1dc3e7ae30452a485e3b1` on `release-2.60.0` branch and push to the PR?

**Comment by ahmedabu98** [comment]
I think the only missing change is to `.github/trigger_files/IO_Iceberg_Integration_Tests.json`:
image

but the identical has already been committed (probably from #32621): https://github.com/apache/beam/blob/release-2.60.0/.github/trigger_files/IO_Iceberg_Integration_Tests.json

**Comment by Abacn** [comment]
sorry if not clear,  `git cherry-pick ...` will give a single commit to this PR, currently there are 9 commits. But on the master branch history the original PR merged into a single commit (d84cfffd017342542cc1dc3e7ae30452a485e3b1)

**Comment by ahmedabu98** [comment]
I see. Let's move to #32663 then

**Pull request closed without merging**
