### PR TITLE
[SQL] Fix CREATE EXTERNAL TABLE in non-default schema

### PR DESCRIPTION
**Pull request by kanterov**
With `BeamSqlEnv#addSchema` it's possible to add new schemas, however, 
"CREATE EXTERNAL TABLE" didn't work.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by kanterov** [comment]
R: @amaliujia @akedin

**Comment by amaliujia** [comment]
LGTM

This is awesome! Now we can support multi schema in SQL CLI

**Comment by kanterov** [comment]
@akedin thanks for the feedback.

From my perspective, what matters is `BeamSqlEnv`, so I added a separate test for it. On the other side, it still matters to check that DDL parser behaves as expected, so I removed everything irrelevant and left test there as well.

One tricky moment is that `BeamSqlEnv#connection` isn't exposed in public API, but needed to verify that everything works as expected. The other way would be to explicitly parse the query and build Beam graph, but it seems unnecessarily complicated.

**Comment by kanterov** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by kanterov** [comment]
@akedin if it looks good, can you merge? I haven't got merge permissions yet

**Pull request merged**
