### PR TITLE
[Website] add linkedIn case-study

### PR DESCRIPTION
**Pull request by bullet03**
- add linkedIn case-study with related files
------------------------
before:
before_linkedIn
after:
after_linkedIn
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by dariabezkorovaina** [comment]
@aaltay we've prepared this draft PR for the LinkedIn case study, but for the past 6 hours, the staging has been failing to build for some reason... Can you please help with this?

**Comment by aaltay** [comment]
@liferoad - would it be possible for someone in the team to look at the failing beam_PreCommit_Whitespace . I looked at the logs, it seems to be failing because it is failing to setup the dependencies to run whitespace check and not because it is failing the whitespace check.

**Comment by aaltay** [comment]
Run Whitespace PreCommit

**Comment by aaltay** [comment]
Run Whitespace PreCommit

**Comment by liferoad** [comment]
I doubt this is related to this PR. cc @damccorm

**Comment by bullet03** [comment]
R: @andreydevyatkin, could you, please help with the review of current PR?

**Comment by damccorm** [comment]
> I doubt this is related to this PR. cc @damccorm

Whitespace is back to green - https://github.com/apache/beam/actions/workflows/beam_PreCommit_Whitespace.yml?query=event%3Aschedule - there were several issues around checking for the new error of pip and downloading it that show up in the failures, guessing it was a transient pip remote issue.

Regardless, should be safe to ignore

**Comment by bullet03** [comment]
R: @aaltay , could you, please help with the review of current PR?

**Comment by aaltay** [comment]
Looks great, thank you!

**Review by aaltay — APPROVED** [review]

**Comment by aaltay** [comment]
Published: https://beam.apache.org/case-studies/linkedin/

**Pull request merged**
