### PR TITLE
Adapt Flink StateInternals to new state semantics

### PR DESCRIPTION
**Pull request by aljoscha**
This was changed in #3876.

R: @tgroh (not sure I caught all the places where this needs to change)

### CODE REVIEW

**Comment by tgroh** [comment]
LGTM

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
@jasonkuster Do you know if the two PreCommits should currently pass?

**Comment by jasonkuster** [comment]
Clean install should pass; precommit pipeline is now active (email coming soon!) but should be ignored for the time being.

**Comment by jasonkuster** [comment]
fwiw though, clean install has been timing out and having several other problems recently -- use your best judgment

**Pull request closed without merging**
