### PR TITLE
Skip dataflow_exercise_metrics_pipeline_test.ExerciseMetricsPipelineTest.test_metrics_it

### PR DESCRIPTION
**Pull request by yeandy**
Sickbay `test_metrics_it` due to bug reported here https://github.com/apache/beam/issues/22605. Will unskip when finish investigating issue.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by yeandy** [comment]
Run Python PreCommit

**Comment by yeandy** [comment]
R: @TheNeuralBit

**Comment by TheNeuralBit** [comment]
Run Python 3.7 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python 3.8 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python 3.9 PostCommit

**Review by TheNeuralBit — APPROVED** [review]

**Comment by TheNeuralBit** [comment]
Run Python 3.7 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python 3.8 PostCommit

**Comment by TheNeuralBit** [comment]
Run Python 3.9 PostCommit

**Comment by TheNeuralBit** [comment]
It's unclear if this is helping, the PostCommits are all timing out now

**Comment by yeandy** [comment]
Looks like a grpc issue https://github.com/apache/beam/issues/22643

**Comment by yeandy** [comment]
`test_metrics_it` gets skipped Screen Shot 2022-08-09 at 10 34 43 AM

Looking into the grpc timeouts

**Comment by TheNeuralBit** [comment]
> `test_metrics_it` gets skipped

Ok, I can go ahead and merge this. It does look like test_metrics_it was a hard failure, at least in 3.8 PostCommit:
image

**Comment by yeandy** [comment]
Thanks @TheNeuralBit !

**Pull request merged**
