### PR TITLE
Unpin Dataflow legacy worker container for Nexmark test

### PR DESCRIPTION
**Pull request by Abacn**
`fix` #30606

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
> Instead of doing this, should we be fixing [#30606 (comment)](https://github.com/apache/beam/issues/30606#issuecomment-2501536500) so that it points to a java 11 container?

This PR is to fix that comment. The effect of '--workerHarnessContainerImage=' is to direct the container to an internally built (Java 8) container, which made it incompatible with pipeline submission environment. Remove it, it will use beam-master container with the same Java version of the host, while still overrides dataflowWorkerJar

**Comment by damccorm** [comment]
My question was: should we make `--workerHarnessContainerImage=` cause Dataflow to point to a Java 11 container? I think there might still be some advantages to doing this per https://github.com/apache/beam/pull/6694#discussion_r226009082

**Comment by Abacn** [comment]
I see, yeah, we should move the internal one to java11, will raise internal tracker for that

**Comment by Abacn** [comment]
Opened an internal issue (tracking: 381121973) and initial changes. It seems the scope of change for migrating the staging container to Java11 is nontrivial, and needs rollouts from Dataflow service side (which is currently blocked). Could we proceed with this change for this workflow at the moment?

**Comment by damccorm** [comment]
> Opened an internal issue (tracking: 381121973) and initial changes. It seems the scope of change for migrating the staging container to Java11 is nontrivial, and needs rollouts from Dataflow service side (which is currently blocked). Could we proceed with this change for this workflow at the moment?

Yeah, that is fine - thanks

**Review by damccorm — APPROVED** [review]

**Pull request merged**
