### PR TITLE
[21794 ] Fix output timestamp in Dataflow.

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by reuvenlax** [comment]
R: @steveniemitz

**Comment by steveniemitz** [comment]
oh this is awesome.

**Comment by reuvenlax** [comment]
@steveniemitz any comments on the PR?

**Comment by steveniemitz** [comment]
> @steveniemitz any comments on the PR?

nope LGTM, adding the output timestamp to the timer metadata like this is way cleaner than encoding it into the timer key too.

**Comment by kileys** [comment]
retest this please

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by kileys** [comment]
Run Dataflow ValidatesRunner

**Comment by kileys** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
