### PR TITLE
Override BQ load job location when necessary

### PR DESCRIPTION
**Pull request by ahmedabu98**
Found a case where if we retry a successful load job (e.g. due to bundle failure), we get a 409 `ALREADY_EXISTS` error along with a job reference that **does not contain a location**. 

In finish bundle, we perform wait operations on job references, where we get and poll until the job is finished. If we attempt to get a job without a location, the API will default it to US multi region. However, this is problematic when we're writing to a different region because BQ won't be able to find the job and we encounter a 404 `NOT_FOUND` error.

In such a case where the job reference has null location, we should override it with the table's location

### CODE REVIEW

**Comment by shunping** [comment]
Looks like there are some presubmit error caused by the code change.
```
apitools.base.protorpclite.messages.ValidationError: Expected type <class 'str'> for field location, found <Mock name='mock.tables.Get().location' id='133722614311760'> (type <class 'mock.mock.Mock'>) 
```

I think we need to mock `location` when creating the mocked object of `bq_client`.

**Comment by shunping** [comment]
waiting on author

**Comment by ahmedabu98** [comment]
@shunping can you PTAL?

**Review by shunping — APPROVED** [review]
LGTM. Thanks!

**Comment by Abacn** [comment]
There is a racing condition here such that the retry job could happen when the conflict job is running, and then get_table_location will fail on 404, thus failing the Dataflow job.

**Pull request merged**
