### PR TITLE
[BEAM-14226] Remove standalone seed job.

### PR DESCRIPTION
**Pull request by ibzib**
@kennknowles you introduced the standalone seed job originally - do you know if we still need it?

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ibzib** [comment]
R: @kennknowles 

ping :)

**Comment by kennknowles** [comment]
We had cases where the seed job recreated itself and the new seed job was broken. If the seed job still recreates itself and a bug in the groovy could break it, we probably still want some back up plan. Perhaps the seed job just doesn't create itself any more? That would probably be smart.

**Review by kennknowles — APPROVED** [review]
I expect it is out of date as well.

**Comment by kennknowles** [comment]
Ah, and specifically, the seed job shared "library" code with all the other jobs, so it could be broken by breakage in the shared groovy files. It is all extremely fragile so this is a layer of protection. But I don't know if it still serves the same purpose, or just causes problems, etc.

**Comment by ibzib** [comment]
> Perhaps the seed job just doesn't create itself any more? That would probably be smart.

Whoa, judging from the logs the seed job does generate itself. That definitely doesn't seem ideal. 

>     GeneratedJob{name='beam_SeedJob'}
>     GeneratedJob{name='beam_SeedJob_Standalone'}

> Ah, and specifically, the seed job shared "library" code with all the other jobs, so it could be broken by breakage in the shared groovy files.

At least it looks like it doesn't share code with other jobs anymore. The only thing it imports is Committers.groovy, which is just a placeholder.

https://github.com/apache/beam/blob/f90379a67f9cbc89425cd161452cdf6172354e93/.test-infra/jenkins/job_00_seed.groovy#L21

> I expect it is out of date as well.

It's only trivially different. 

```diff
$ diff .test-infra/jenkins/job_seed_standalone.groovy .test-infra/jenkins/job_00_seed.groovy

23c23
< job('beam_SeedJob_Standalone') {
—
> job('beam_SeedJob') {
77c77
< cron('0 */5 * * *')
—
> cron('H */6 * * *')
85c85
< triggerPhrase('Run Standalone Seed Job')
—
> triggerPhrase('Run Seed Job')
90c90
< context("Jenkins: Standalone Seed Job")
—
> context("Jenkins: Seed Job")
110c110
< python3.8 -m venv ve3 && source ./ve3/bin/activate &&
—
> python3.8 -m venv ve3 && source ve3/bin/activate &&
```

**Comment by ibzib** [comment]
So it seems the main reason for having a standalone seed job still stands. But we probably don't need to run both of them as cron jobs. What do you think about leaving the standalone job enabled, but removing its cron scheduling?

**Comment by kennknowles** [comment]
SGTM

**Pull request closed without merging**
