### PR TITLE
[BEAM-1941] Add Source Watermark Metrics

### PR DESCRIPTION
**Pull request by JingsongLi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @aviemzur  Not fully finish yes, the `min` amongst all splits watermark need some discussion.

**Comment by JingsongLi** [comment]
@aviemzur It is ready to review now.

**Comment by JingsongLi** [comment]
retest this please

**Comment by aviemzur** [comment]
As per chat with @JingsongLi a proposal will be coming for this written by him and sent to the dev list.

**Comment by davorbonaci** [comment]
@JingsongLi, is this PR maybe obsolete in light of the discussion on the dev@ list?

**Comment by JingsongLi** [comment]
I will take a reminder to dev@ list.

**Pull request closed without merging**
