### PR TITLE
Run cred rotation every month

### PR DESCRIPTION
**Pull request by damccorm**
Jenkins recently went down for a while because our creds expired. Running the IODatastores rotation job fixed it. Given that its relatively cheap, we should probably run that job every month so that we're not cutting it close on expirations. I could actually be convinced that running it even more frequently is a good idea.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
@eilnk21 are there any reasons that you know of not to run this more frequently? (asking since you added this in https://github.com/apache/beam/pull/17383)

**Comment by damccorm** [comment]
@elink21 are there any reasons that you know of not to run this more frequently? (asking since you added this in https://github.com/apache/beam/pull/17383)

**Comment by elink21** [comment]
> @elink21 are there any reasons that you know of not to run this more frequently? (asking since you added this in #17383)

The initial bi-monthly frequency was proposed given the credentials lifetime reported by this [command](https://cloud.google.com/kubernetes-engine/docs/how-to/credential-rotation#check_credential_lifetime). As all the jobs get their cluster credentials dynamically through gcloud, I think there won't be a huge impact if those are rotated on a more frequent basis.

**Comment by damccorm** [comment]
R: @Abacn

**Comment by Abacn** [comment]
Thanks. Is the original every other month setting never working?

**Comment by damccorm** [comment]
It ran for the first time a little less than 2 months ago, but the creds expired before the second run. Had there been a run in between we would've most likely avoided the problem

**Review by Abacn — APPROVED** [review]
Thanks. Let's hope it works a month later

**Pull request merged**
