### PR TITLE
[Tour Of Beam] saving user code

### PR DESCRIPTION
**Pull request by eantyshev**
We introduce `postUserCode` endpoint to save user code as a Playground snippet
For that, it uses Playground GRPC API SaveSnippet endpoint

- [x] Generation of Playground GRPC stubs
- [x] Playground router service in docker-compose.yml
- [x] Mock Playground GRPC API client generation
- [x] Datastore save user code
- [x] Update integration_tests/* and GH workflow

addresses #23539

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Thanks for the work! Not quite familiar with go stuff. Could try out if there is a way to build/access the website with change.

**Comment by Abacn** [comment]
assign to next reviewer

**Review by olehborysevych — APPROVED** [review]

**Comment by olehborysevych** [comment]
LTGM (internal review)

**Comment by olehborysevych** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
