### PR TITLE
[BEAM-2530] Upgrade maven plugins to the latest versions

### PR DESCRIPTION
**Pull request by iemejia**
This is part of the ongoing work to support java 9

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
This upgrade was done in particular to include the recent support for Java 9 added to the enforcer and javadoc plugins.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Upgrade is just for better Java 9 support ?

**Comment by iemejia** [comment]
Retest this please

**Comment by iemejia** [comment]
@jbonofre yes, this solves some issues with Java 9 (not all of them, this probably will take months since other plugins are broken + also we need to fix more issues before this). This PR also fixes another issue I found with the starter archetype that was not inheriting the versions of the plugins correctly..

**Pull request closed without merging**
