### PR TITLE
[BEAM-14196] add test verifying output watermark propagation in bundle

### PR DESCRIPTION
**Pull request by je-ik**
Add test verifying output watermark handling when bundle being processed.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by je-ik** [comment]
Run Java Samza PortableValidatesRunner

**Comment by je-ik** [comment]
Run Dataflow ValidatesRunner

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Samza ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Twister2 ValidatesRunner

**Comment by je-ik** [comment]
Retest this please

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Twister2 ValidatesRunner

**Comment by je-ik** [comment]
Run Java Dataflow V2 ValidatesRunner

**Comment by je-ik** [comment]
Run Samza ValidatesRunner

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Dataflow ValidatesRunner

**Comment by je-ik** [comment]
Run Java Spark v3 PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Java Spark v2 PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Java Samza PortableValidatesRunner

**Comment by je-ik** [comment]
Run Samza ValidatesRunner

**Comment by je-ik** [comment]
Run Java Samza PortableValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
R: @dmvk

**Comment by je-ik** [comment]
Run Java PreCommit

**Comment by je-ik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by je-ik** [comment]
Run Java PreCommit

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by je-ik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Review by dmvk — COMMENTED** [review]
The overall sentiment of the fix and the approach LGTM, but I don't have time to dig deeper to find out whether this could break something so consider this a "soft +1".

**Comment by je-ik** [comment]
@ibzib I think it would be good to get this to 2.39.0 which is cut today, would you like to have a look? Or could you recommend someone? Maybe @reuvenlax?

**Comment by kennknowles** [comment]
The test title and the PR description says "tests that it is correct" but does not describe _what_ correctness should be or what the problem is. I noticed this test failing in some cases and I would like to be able to know if it is a bug or an unsupported feature. Can you describe what property this test is for?

**Comment by je-ik** [comment]
Which runner does the test fail on?

**Comment by kennknowles** [comment]
It was Dataflow; I noticed that the test is disabled in our internal ValidatesRunner test suite (we just re-run the same as external but using Google's build system too). But now I see it is not explicitly sickbayed externally, so it is probably excluded due to limitations in TestStream.

**Pull request merged**
