### PR TITLE
Fix javadoc generation for AmqpIO, CassandraIO and HCatalogIO

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
I'm checking why Jenkins failed.

**Comment by iemejia** [comment]
It looks like a timeout getting the JDBC deps, let's see if it works now.

**Comment by iemejia** [comment]
Retest this please

**Comment by iemejia** [comment]
Retest this please

**Pull request closed without merging**
