### PR TITLE
[BEAM-6239] Add session side input join to Nexmark

### PR DESCRIPTION
**Pull request by kennknowles**
This is a new benchmark of sessionization then a join with a side input.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @akedin 

@echauchot I know you are a bit busy but tagging you so you see this

**Comment by kennknowles** [comment]
run java precommit

**Comment by echauchot** [comment]
@kennknowles, cool ! That makes 3 side-input join queries !

**Comment by kennknowles** [comment]
@echauchot yea - I wanted to see how the overheads of side inputs vs sessionization would interact. Since sessionization might be sensitive to how it is buffered and how the output iterable is handled.

**Comment by echauchot** [comment]
> @echauchot yea - I wanted to see how the overheads of side inputs vs sessionization would interact. Since sessionization might be sensitive to how it is buffered and how the output iterable is handled.

I see

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
Looks like infrastructure issue that hit while HIFIO test was running. Will re-run to see.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Hmm, getting the same issue with HIFIO. Or maybe the problem is with the Jenkins worker.

**Comment by kennknowles** [comment]
Rebased (w/ squash) just in case the problem was at a particular commit on master. If it happens again I will follow up with bug filing.

**Comment by kennknowles** [comment]
@echauchot @akedin finally all the unrelated failures green. WDYT?

**Pull request merged**
