### PR TITLE
Flag fix.

### PR DESCRIPTION
**Pull request by jasonkuster**
Changed this flag as a result of review -- have to update here. This will cease to be a problem once we land in PKB mainline.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
R: @tgroh

### CODE REVIEW

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by tgroh** [comment]
LGTM, assuming infrastructure agrees.

Will merge on https://builds.apache.org/job/beam_PerformanceTests_JDBC/15/ success

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by tgroh** [comment]
Same, but with https://builds.apache.org/job/beam_PerformanceTests_JDBC/16/

**Comment by tgroh** [comment]
https://builds.apache.org/job/beam_PerformanceTests_JDBC/17/

**Pull request closed without merging**
