### PR TITLE
[BEAM-1755] Add a directory with build-specific scripts to clear up the Python SDK dir

### PR DESCRIPTION
**Pull request by pabloem**
r: @tvalentyn 
This is just a proposal. Let me know if you think it makes sense.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
Makes sense to me; you could also call the folder `testing` instead of scripts, although generate_pydoc.sh would have to stay or go into a different place.

**Comment by pabloem** [comment]
@tvalentyn

**Comment by tvalentyn** [comment]
Giving folders meaningful names could be more mnemonic as it to the purpose of the content in the folder, but I don't have a strong opinion on this; in fact I have a scripts folder on my dev box that serves a similar purpose. Your call.

**Comment by tvalentyn** [comment]
And, thanks for the ping, I missed the previous update.

**Comment by charlesccychen** [comment]
It seems like with this change, you would still need to run scripts with the current directory as `sdks/python` and do `scripts/[...].sh`.  In particular, if you run the script in the `sdks/python/scripts` directory directly, it looks like many of the scripts just won't work, and this isn't documented, since it looks like the scripts depend on the current working directory.  Is it possible to fix this so that it works both ways?

**Comment by pabloem** [comment]
I've added code in all scripts to check and switch their current directory. PTAL.

**Comment by pabloem** [comment]
Run Python PostCommit

**Comment by tvalentyn** [comment]
LGTM

**Pull request merged**
