### PR TITLE
[BEAM-966] Activate WindowedWordCountIT on Apex runner

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

@tweise throwing this up to see what happens, as a strawman

### CODE REVIEW

**Comment by tweise** [comment]
Looks like there is an issue with parallel execution of the tests. They both seem to write to the same directory.

**Comment by kennknowles** [comment]
What is the right way to configure the location of `com.datatorrent.stram.StramLocalCluster/meta.json` here?

**Comment by kennknowles** [comment]
Since it is landing `examples/java/target/com.datatorrent.stram.StramLocalCluster/meta.json` perhaps it is relative to the jar and just needs an explicit prefix or some such?

**Comment by tweise** [comment]
Yes, unfortunately there is https://issues.apache.org/jira/browse/APEXCORE-598 and we will need the new release before it can be fixed. Until then, can we set the tests to execute sequentially?

**Comment by tweise** [comment]
LGTM

**Pull request merged**
