### PR TITLE
[BEAM-9865] Cleanup Jenkins WS on successful jobs

### PR DESCRIPTION
**Pull request by udim**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
Started seed job manually: https://ci-beam.apache.org/job/beam_SeedJob/6623/

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
Run Seed Job

**Comment by damgad** [comment]
Run Seed Job

**Comment by udim** [comment]
Lastest failure:
```
Warning: (CommonJobProperties.groovy, line 238) plugin 'ws-cleanup' needs to be installed
```

**Comment by damgad** [comment]
With that change, all workspaces will be always cleared, just after the build. Isn't that a problem in case of some possible investigations in the future?

We may implement something like [this](https://blog.clairvoyantsoft.com/jenkins-cleanup-workspace-reduce-disk-usage-18310097d3ef), WDYT?

**Comment by udim** [comment]
> With that change, all workspaces will be always cleared, just after the build. Isn't that a problem in case of some possible investigations in the future?
> 
> We may implement something like [this](https://blog.clairvoyantsoft.com/jenkins-cleanup-workspace-reduce-disk-usage-18310097d3ef), WDYT?

I wasn't aware that you were working on this bug. The ws-cleanup plugin can be configured not to clean up after failures. However, I don't recall the last time I needed to ssh into a workspace because I needed to look at the files.

**Comment by damgad** [comment]
No worries, I didn't actively work on this bug yet, just had some thoughts.

I have no strong opinion here, both approaches are fine if access to the workspace isn't needed.

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
R: @damgad

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run rat precommit

**Comment by udim** [comment]
Run Spotless PreCommit

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run rat precommit

**Comment by udim** [comment]
Run Spotless PreCommit

**Comment by udim** [comment]
Finally verified that this works:
```
17:54:20 [WS-CLEANUP] Deleting project workspace...
17:54:20 [WS-CLEANUP] Deferred wipeout is used...
17:54:20 [WS-CLEANUP] done
```
https://ci-beam.apache.org/job/beam_PreCommit_RAT_Phrase/71/console
Also ssh-ed into machine and verified workspace dir was not there.

**Comment by udim** [comment]
Run Spotless PreCommit

**Comment by damgad** [comment]
> R: @damgad

LGTM, however, I'm not a committer and can't merge :)

**Comment by kennknowles** [comment]
Since you pointed me here, the problem is that there are important transparent caches in the workspace, such as the maven dep downloads. It is slow and wasteful for all parties to hit maven central on every build, but more importantly it is flaky.

TBH "pure" caches could/should probably live outside the workspace. I think the Gradle dep cache must be, or we'd see huge flakiness of Gradle jobs. We can clone `--depth 1` to eliminate the costs of the repo history. But I kind of agree with the simple approach of wiping out the workspace to keep it simple and not depend on details of what happens in the workspace. The issue is we need to get the replacement in place first. I think setting up the `.m2` to be outside the workspace is the move in this case.

**Comment by kennknowles** [comment]
Turns out the flaky process in question sets .m2 to a subdirectory of a wiped out temp dir. Once that is fixed, we'll still need an outside-the-workspace location for the cache to avoid it being wiped out.

**Pull request merged**
