### PR TITLE
Remove stripping of step name and replace with substring search

### PR DESCRIPTION
**Pull request by AnandInguva**
The strip methods strips out the characters mentioned in it. For the PytorchRunInference metrics, it strips out the p and outputs `ytorchruninfernece` instead.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Review by TheNeuralBit — APPROVED** [review]
Is there anywhere we can test this?

**Comment by AnandInguva** [comment]
> Is there anywhere we can test this?

I couldn't find any tests related to it. Any suggestions?

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Comment by TheNeuralBit** [comment]
> > Is there anywhere we can test this?
> 
> I couldn't find any tests related to it. Any suggestions?

How did you detect the issue?

**Comment by AnandInguva** [comment]
> > > Is there anywhere we can test this?
> > 
> > 
> > I couldn't find any tests related to it. Any suggestions?
> 
> How did you detect the issue?

When I was trying to publish metrics to InfluxDB and BigQuery, the metrics were named like this `INFO:apache_beam.testing.load_tests.load_test_metrics_utils:Metric: RunInferencePytorch_ytorchruninference/pardo(_runinferencedofn)_max_inference_batch_latency_micro_secs Value: 1592367`

**Comment by TheNeuralBit** [comment]
> > > > Is there anywhere we can test this?
> > > 
> > > 
> > > I couldn't find any tests related to it. Any suggestions?
> > 
> > 
> > How did you detect the issue?
> 
> When I was trying to publish metrics to InfluxDB and BigQuery, the metrics were named like this `INFO:apache_beam.testing.load_tests.load_test_metrics_utils:Metric: RunInferencePytorch_ytorchruninference/pardo(_runinferencedofn)_max_inference_batch_latency_micro_secs Value: 1592367`
> 
> https://ci-beam.apache.org/job/beam_Inference_Python_Benchmarks_Dataflow_PR/9/console

Ah ok, thanks. I suppose this is just testing infrastructure so we don't need to be too picky.

**Pull request merged**
