### PR TITLE
[BEAM-1772] Support merging WindowFn other than IntervalWindow on Flink Runner

### PR DESCRIPTION
**Pull request by JingsongLi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @aljoscha

**Comment by aljoscha** [comment]
Thanks a lot for working on this, @JingsongLi. 😃 

I have one quick initial comment: `FlinkNonSortedCombineRunner` is a (somewhat different) reimplementation of `ReduceFnRunner` with the difference that `ReduceFnRunner` does the merging of windows on the fly, while processing elements, whereas `FlinkNonSortedCombineRunner` does two passes over the input elements, one for determining the merged windows and another one for processing the data which requires materialising all input elements in a list because Flink only allows iterating over the input once.

I think we should either change `FlinkNonSortedCombineRunner` to also only require one pass or reuse `ReduceFnRunner` directly. This is a quick sketch of what that would look like:

```java
public class FlinkMergingNonShuffleReduceFunction<
    K, InputT, AccumT, OutputT, W extends BoundedWindow>
    extends RichGroupReduceFunction<WindowedValue<KV<K, InputT>>, WindowedValue<KV<K, OutputT>>> {

  private final AppliedCombineFn<K, InputT, AccumT, OutputT> combineFn;

  private final WindowingStrategy<Object, W> windowingStrategy;

  private final Map<PCollectionView<?>, WindowingStrategy<?, ?>> sideInputs;

  private final SerializedPipelineOptions serializedOptions;

  public FlinkMergingNonShuffleReduceFunction(
      AppliedCombineFn<K, InputT, AccumT, OutputT> keyedCombineFn,
      WindowingStrategy<Object, W> windowingStrategy,
      Map<PCollectionView<?>, WindowingStrategy<?, ?>> sideInputs,
      PipelineOptions pipelineOptions) {

    this.combineFn = keyedCombineFn;

    this.windowingStrategy = windowingStrategy;
    this.sideInputs = sideInputs;

    this.serializedOptions = new SerializedPipelineOptions(pipelineOptions);

  }

  @Override
  public void reduce(
      Iterable<WindowedValue<KV<K, InputT>>> elements,
      final Collector<WindowedValue<KV<K, OutputT>>> out) throws Exception {

    FlinkSideInputReader sideInputReader =
        new FlinkSideInputReader(sideInputs, getRuntimeContext());

    final Iterator<WindowedValue<KV<K, InputT>>> iterator = elements.iterator();

    // get the first value, we need this for initializing the state internals with the key.
    // we are guaranteed to have a first value, otherwise reduce() would not have been called.
    final WindowedValue<KV<K, InputT>> currentValue = iterator.next();
    final K key = currentValue.getValue().getKey();

    final InMemoryStateInternals<K> stateInternals = InMemoryStateInternals.forKey(key);

    // Used with Batch, we know that all the data is available for this key. We can't use the
    // timer manager from the context because it doesn't exist. So we create one and advance
    // time to the end after processing all elements.
    final InMemoryTimerInternals timerInternals = new InMemoryTimerInternals();
    timerInternals.advanceProcessingTime(Instant.now());
    timerInternals.advanceSynchronizedProcessingTime(Instant.now());

    ReduceFnRunner<K, InputT, OutputT, W> reduceFnRunner = new ReduceFnRunner<>(
        currentValue.getValue().getKey(),
        windowingStrategy,
        ExecutableTriggerStateMachine.create(
            TriggerStateMachines.stateMachineForTrigger(
                Triggers.toProto(windowingStrategy.getTrigger()))),
        stateInternals,
        timerInternals,
        new OutputWindowedValue<KV<K, OutputT>>() {
          @Override
          public void outputWindowedValue(
              KV<K, OutputT> output,
              Instant timestamp,
              Collection<? extends BoundedWindow> windows,
              PaneInfo pane) {
            out.collect(
                WindowedValue.of(output, timestamp, windows, PaneInfo.ON_TIME_AND_ONLY_FIRING));
          }

          @Override
          public <SideOutputT> void sideOutputWindowedValue(
              TupleTag<SideOutputT> tag,
              SideOutputT output,
              Instant timestamp,
              Collection<? extends BoundedWindow> windows,
              PaneInfo pane) {
            throw new UnsupportedOperationException("A ReduceFn cannot use side outputs.");
          }
        },
        sideInputReader,
        null,
        SystemReduceFn.<K, InputT, AccumT, OutputT, W>combining(null, combineFn),
        serializedOptions.getPipelineOptions());

    reduceFnRunner.processElements(new Iterable<WindowedValue<InputT>>() {
      @Override
      public Iterator<WindowedValue<InputT>> iterator() {
        Iterator<WindowedValue<KV<K, InputT>>> concatenated =
            Iterators.concat(Iterators.singletonIterator(currentValue), iterator);
        return Iterators.transform(
            concatenated,
            new Function<WindowedValue<KV<K, InputT>>, WindowedValue<InputT>>() {
              @Nullable
              @Override
              public WindowedValue<InputT> apply(@Nullable WindowedValue<KV<K, InputT>> input) {
                return input.withValue(input.getValue().getValue());
              }
            });
      }
    });

    // Finish any pending windows by advancing the input watermark to infinity.
    timerInternals.advanceInputWatermark(BoundedWindow.TIMESTAMP_MAX_VALUE);

    // Finally, advance the processing time to infinity to fire any timers.
    timerInternals.advanceProcessingTime(BoundedWindow.TIMESTAMP_MAX_VALUE);
    timerInternals.advanceSynchronizedProcessingTime(BoundedWindow.TIMESTAMP_MAX_VALUE);

    fireEligibleTimers(timerInternals, doFnRunner);

  }

}
```

Either of those options seems fine to me. What do you think?

**Comment by JingsongLi** [comment]
I don't have a good way to change `FlinkNonSortedCombineRunner` to only require one pass. We should reuse `ReduceFnRunner` directly since `FlinkNonSortedCombineRunner` do the same work to `ReduceFnRunner`. Thank you to your nice code~

**Comment by JingsongLi** [comment]
@aljoscha  I think we can't modify `FlinkPartialReduceFunction` and `FlinkReduceFunction`. They use `FlinkNonSortedCombineRunner` just in `GroupByKey`. `ReduceFnRunner` api is difficult to split into a partial combination and a final combination.

We can't just concat iterators because `ReduceFnRunner` does two passes over the input elements too. I don't think `ReduceFnRunner` does the merging of windows on the fly. `ReduceFnRunner` is different from sorted combination. Can you check again?

**Comment by davorbonaci** [comment]
@aljoscha, any comments perhaps?

**Comment by aljoscha** [comment]
I was too busy with Flink Forward but I'm now getting back to reviewing stuff. 😅

**Comment by kennknowles** [comment]
Putting this on my wishlist for first stable release. Not necessarily hampered by API freeze, but good for users.

**Comment by iemejia** [comment]
Sorry @JingsongLi we were refactoring the flink runner in the last two days so this isn't mergeable anymore (mea culpa) can you please rebase it.

**Comment by JingsongLi** [comment]
OK, resolve conflicts and rebase.

**Comment by kennknowles** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
@aljoscha does this LGTY ? One of the latest missing for flink on Nexmark.

**Comment by aljoscha** [comment]
@JingsongLi Thanks for working on this! 😃 

I did some small refactorings. Among other things, the base for Flink combine runners is now `AbstractFlinkCombineRunner` and there is a `SortingFlinkCombineRunner` and a `HashingFlinkCombineRunner`.  I hope that's alright.

**Comment by JingsongLi** [comment]
Great!
That is more clear.

**Pull request closed without merging**
