### PR TITLE
[#25896] Add an initial UI to standalone prism command.

### PR DESCRIPTION
**Pull request by lostluck**
This PR makes a compile target to deploy prism in a stand alone fashion. This is very basic functionality at this time, and should not be relied upon, and is subject to change.

Submitted jobs are displayed with their name and state

Job details can then be examined

Prism doesn't yet support container execution so jobs must still run in loopback mode.
`--runner=universal --endpoint=localhost:8073 --environment_type=LOOPBACK`

I recommend setting the unused worker binary to an empty dummy file: `touch dummy` then `--worker_binary=dummy` to avoid the development compile step when in Loopback mode.

* Adds prism as a stand alone command that hosts runner JobManagmeent and the web UI.
* Add a basic web UI package to prism. It uses a JobManagement client directly, so a future change can enable it to point to any JobManagement instance.
  * Uses Go "html/template" package to generate static pages on demand.
* Implements the GetJobs and GetPipeline RPCs to the prism management server.
* Minor cleanup to reduce log verbosity when submitting Go SDK jobs.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
Friendly ping.

**Comment by lostluck** [comment]
Ah, Jack is OOO today, so I'll iterate on this a little more then. Needs some unit test coverage at least, and I would much rather get all the metrics aligned with their Transforms, instead of having a separate table for PCollection metrics.

**Review by jrmccluskey — APPROVED** [review]
LGTM! I glossed over the HTML/CSS a bit since I'm not particularly familiar, but everything else was extremely straightforward. Docstrings and tests continue to make reviewing easier

**Comment by lostluck** [comment]
Now to make the UI actually more usable, and probably update some of the documentation in the README.

**Pull request merged**
