### PR TITLE
Fix failing BQ tests on XVR GoUsingJava tests

### LINKED ISSUE #26865: [Failing Test]: beam_PostCommit_XVR_GoUsingJava_Dataflow_PR
### What happened?

BigqueryIO Test in Go SDK fails with error:
```
java.lang.IllegalArgumentException: Triggering frequency or number of file shards can be specified only when writing an
unbounded PCollection via FILE_LOADS or STORAGE_API_WRITES, but: the collection was BOUNDED and the method was
STORAGE_WRITE_API
```

https://ci-beam.apache.org/job/beam_PostCommit_XVR_GoUsingJava_Dataflow_PR/34/consoleText

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #26865

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run XVR_GoUsingJava_Dataflow PostCommit

**Comment by ahmedabu98** [comment]
R: @riteshghorse

**Comment by riteshghorse** [comment]
I'd like this to get it in for 2.48

**Comment by ahmedabu98** [comment]
Run XVR_GoUsingJava_Dataflow PostCommit

**Review by riteshghorse — APPROVED** [review]
Thanks for the quick fix, Ahmed!

**Comment by riteshghorse** [comment]
Well the BigQueryIO test passed
https://lists.apache.org/thread/qtzokyoymgz8px11sqch6nby47v0pofs

but different XLang test failed mostly because of grpc connection issue which I think could be a flake.
```
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.beam.vendor.grpc.v1p54p0.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

**Pull request merged**
