### PR TITLE
[BEAM-3613] Correct typo in SpannerIO.Write.withHost

### PR DESCRIPTION
**Pull request by davidyan74**
Just correcting some typos.

### CODE REVIEW

**Comment by davidyan74** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by chamikaramj** [comment]
Run Java Gradle PreCommit

**Comment by chamikaramj** [comment]
Run Java Gradle PreCommit

**Comment by lukecwik** [comment]
Isn't this a backwards incompatible change?

The 2.3.0 release candidate has these typos.

**Comment by davidyan74** [comment]
Yes, but the SpannerIO is marked Experimental.

From beam/sdks/java/core/src/main/java/org/apache/beam/sdk/annotations/Experimental.java:
```
 * Signifies that a public API (public class, method or field) is subject to incompatible changes,
 * or even removal, in a future release.
```

**Comment by chamikaramj** [comment]
Yeap, I think it's fine to get this in since it's experimental.

cc: @mairbek

**Comment by lukecwik** [comment]
Ah, missed the experimental annotation. Anyways, if you want you could ask to get this cherry picked into the 2.3.0 RC since it's likely that another 2.3.0 RC will be released.

**Comment by davidyan74** [comment]
Run Java Gradle PreCommit

**Comment by davidyan74** [comment]
@chamikaramj The latest java presubmit was successful. Can you merge this when you get a chance? Thanks!

**Comment by mairbek** [comment]
Thanks for fixing this!

**Pull request merged**
