### PR TITLE
fixed problem when client id is not set

### PR DESCRIPTION
**Pull request by hepeknet**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-1686] Added random client id assignment`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by hepeknet** [comment]
not sure why coverage decreased.. I did add new test for case when client id is not set. Previously code would throw NPE when client id was not set directly.

**Comment by tibkiss** [comment]
Could you please create a tracking JIRA stating the problem this PR solves?

**Comment by hepeknet** [comment]
https://issues.apache.org/jira/browse/BEAM-1686

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
As it's minor, no Jira needed. I gonna merge.

**Pull request closed without merging**
