### PR TITLE
Make side inputs a map, rather than embedding the name in the message.

### PR DESCRIPTION
**Pull request by robertwb**
The "local" name only make sense in context.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by robertwb** [comment]
RFC: @kennknowles 

A downside of this change is that a single PCollection used multiple times as a side input would be listed as multiple inputs. Not sure if we want that.

**Comment by kennknowles** [comment]
In fact, I believe you prior change that removed PCollection references from `SideInput` makes this change mandatory:

 - Previously, the local names could be different and the validation condition was that the PCollection refs in side inputs were a subset of the PCollection refs in the generic graph inputs.
 - Now, that cannot be validated. This change makes it much more clear that a subset check on the keys is the new validation condition.

I think the new world after your two PRs is better, more constrained in a good way. I'm not bothered by a PCollection appearing multiple times as a generic graph node input.

Caveat: What I _do_ care about is that it is easy for an SDK to implement positional access to side inputs but I think they could do this by embedding generated tags in the serialized UDF.

We will find out more when we start replacing existing bits with `ParDo` payloads. So LGTM, but I think we should pause the micro edits until we are using the API in Java, then Python.

**Comment by robertwb** [comment]
I just thought of a big downside to this: likely the local name will be used in the side input (state) protocol (and in particular the cache). Not allowing multiple names would mean the SDK would have to keep track of which ones actually represent the same collection. 

(As an aside, it seems edits are easier before we have code using them...)

**Comment by kennknowles** [comment]
I don't understand what you mean by "not allowing multiple names". If a collection is side input twice, it will appears under two different names in the generic graph inputs and also under the same different names in the side inputs map. In general, the two specs in the side input map will be different and cached separately by the SDK harness post-`ViewFn`.

If you are suggesting adding a pre-`ViewFn` cache, and a desire to share whenever it has the same (PCollection, materialization) key, that seems pretty easy to implement too.

Perhaps you can say more to make me more worried?

**Comment by robertwb** [comment]
Yes, I was thinking a pre-ViewFn cache. It's a question of imposing the
implementation of deduplicating the cache on something other than the local
name on *each* SDK. That being said, it could be that this is an uncommon
(and easy to implement if need be) improvement, so still worth doing this
change (I'm leaning that way) but wanted to call this out.

**Comment by kennknowles** [comment]
OK, still not worried :-)

I envision the SDK focusing on post-`ViewFn` cache since then it will have constructed a language-appropriate data structure that could actually be potentially expensive - today it is dramatically the case. So assuming smart decisions there, a pre-`ViewFn` cache might not actually have much benefit except in just this rare case where the same PCollection is viewed two ways. I wouldn't characterize it as deduplication, since the two different accesses to the same PCollection could easily have different enough access patterns to violate caching assumptions.

Out of scope here is that the runner's worker will likely manage a pre-`ViewFn` protocol including caching that is tightly coupled with the runner's private implementation of the materialization and possibly much more complex.

And if this turns out to be a wrong view of the future, I really thing the adaptation code will be quite trivial, ~zero in the scheme of things. Seems worth it for the clarity, though I don't care strongly either way; just a smidge more than style.

**Pull request closed without merging**
