### PR TITLE
Relax pydot requirements.

### PR DESCRIPTION
**Pull request by tvalentyn**
Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status] (https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status] (https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status] (https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status] (https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @aaltay

**Comment by tvalentyn** [comment]
Run Portable_Python PreCommit

**Comment by kamilwu** [comment]
@tvalentyn Is there a particular reason why the maximum version of pydot was changed? Because in this pending PR ([https://github.com/apache/beam/pull/8939](url)) we introduced a `tensorflow-transform` dependency which requires pydot's version not to be greater than 1.3. As a result, the build now constantly fails. Are you OK with getting back the original pydot requirement?

**Comment by robertwb** [comment]
It should not generally be an error to have dependencies with wider (but
still overlapping) common dependencies (and it's also brittle in general to
count on one dependency to provide constraints for another). What build
errors are you getting?

**Comment by kamilwu** [comment]
`ERROR: tensorflow-transform 0.13.0 has requirement pydot<1.3,>=1.2.0, but you'll have pydot 1.4.1 which is incompatible.`

Unfortunately, no newer version of tensorflow-transform is available from what I can see

**Comment by aaltay** [comment]
@kamilwu There is a newer version of pydot and that is why the requirement was relaxed.

@katsiapis @zoyahav would it be possible to relax this requirement in tensorflow-transform (https://github.com/tensorflow/transform/blob/master/setup.py#L42) ?

**Comment by tvalentyn** [comment]
I second robert's opinion. If you install tft before installing beam in your execution environment, or if you install the version of pydot that satifisfies constraints for both beam and tft, you should no longer see the warning above. @katsiapis @zoyahav, we should still agree on a version of pydot to install in Dataflow containers for 2.14.0, currently it is `pydot==1.4.1`.

**Comment by kamilwu** [comment]
@aaltay Thanks for this contribution, it'll resolve our issue.

**Comment by zoyahav** [comment]
I believe we can change the requirement in tensorflow-transform, we initially chose it based on beam's IIRC.
TFT only uses pydot for tests, so feel free to choose whichever version that makes most sense to install in DF containers.

**Comment by aaltay** [comment]
Thank you @zoyahav. I prepared https://github.com/tensorflow/transform/pull/132 to update this in TFT. Feel free to use it if it makes sense.

**Pull request merged**
