### PR TITLE
[BEAM-3172] CP #4112, #4122: Properly handle side input exception when all reader threads complete

### PR DESCRIPTION
**Pull request by charlesccychen**
R: @reuvenlax 
CC: @chamikaramj

### CODE REVIEW

**Comment by charlesccychen** [comment]
retest this please

**Comment by charlesccychen** [comment]
Python tests pass; Java test failures are unrelated.

**Comment by charlesccychen** [comment]
R: @aaltay @reuvenlax 

Can one of you look at this CP?  This blocks 2.2.0 RC4 due to https://issues.apache.org/jira/browse/BEAM-3172.

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by reuvenlax** [comment]
Sorry I'm on Japan timezone right now. In the meanwhile, it appears that
the PR has been merged.

**Comment by tvalentyn** [comment]
Latest commit merged on the branch is d28ee9b  (3 days ago), I think we still have to merge this one.

**Comment by reuvenlax** [comment]
lgtm

**Comment by chamikaramj** [comment]
Thanks. Merging.

**Comment by chamikaramj** [comment]
Merged. Charles, please close this manually.

**Pull request merged**
