### PR TITLE
[BEAM-12164] Synchronize access queue in ThroughputEstimator and reenable integration tests

### PR DESCRIPTION
**Pull request by nancyxu123**
Synchronize access queue in ThroughputEstimator to avoid corrupted queue during SpannerIO change streams connector executions.

Also, fix some failing integration tests

### CODE REVIEW

**Comment by nancyxu123** [comment]
R: @thiagotnunes 
R: @pabloem

**Review by thiagotnunes — APPROVED** [review]

**Comment by pabloem** [comment]
lgtm - I'll merge once tests are passing

**Comment by pabloem** [comment]
@nancyxu123 there seem to be some failed tests that are related to this change (see Java_GCP_IO_Direct suite). Could you check to see if the change caused them?

**Comment by pabloem** [comment]
ah great : )

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
oops there's this one: https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Commit/270/testReport/junit/org.apache.beam.sdk.io.gcp.spanner.changestreams.it/SpannerChangeStreamOrderedWithinKeyGloballyIT/testOrderedWithinKey/

@nancyxu123

**Comment by pabloem** [comment]
LGTM thanks!

**Pull request merged**
