### PR TITLE
Fix failing BQ file loads test for Py37

### LINKED ISSUE #23264: [Bug]: Py37 PostCommit Failure test apache_beam.io.gcp.bigquery_file_loads_test.BigQueryFileLoadsIT.test_bqfl_streaming
### What happened?

Has been failing since Sep 14, from https://ci-beam.apache.org/job/beam_PostCommit_Python37/5719/. The test was skipped in Py38 PostCommit and only run on Py37 PostCommit.

Error message:

```
Error Message
google.api_core.exceptions.NotFound: 404 Not found: Table apache-beam-testing:python_bq_file_loads_1663183712232.output_table_ints was not found in location US

Location: US
Job ID: baf2a9a6-ecd8-49b7-a6ef-9965c7fd0cd9
```

Caused by #23012

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #23264

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Python 3.7 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by ahmedabu98** [comment]
Run Python PreCommit

**Comment by ahmedabu98** [comment]
Run Python 3.7 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.8 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.7 PostCommit

**Comment by ahmedabu98** [comment]
Run Python 3.7 PostCommit

**Comment by ryanthompson591** [comment]
This looks fine, but I don't really understand how this fixes the issue. Can you explain that in the comments of the test?

It's not really clear why we would instantiate the pipeline once with the class instead of for each test.

**Pull request closed without merging**
