### PR TITLE
BEAM-1569 support file patterns containing spaces

### PR DESCRIPTION
**Pull request by adude3141**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @jbonofre 

JB, would you like to take a look? It looks good to me, but I think you said you saw bugs as well in private tests.

**Comment by jbonofre** [comment]
Sure. Thanks, I gonna take a look.

**Comment by aaltay** [comment]
@jbonofre any progress on reviewing this?

**Comment by ZxXinZhang** [comment]
Hi, why I cannot find the file hdfs/HDFSFileSource.java

**Pull request closed without merging**
