### PR TITLE
[BEAM-1862] SplittableDoFnOperator should close the ScheduledExecutor…

### PR DESCRIPTION
**Pull request by JingsongLi**
…Service

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
R: @aljoscha

**Comment by aljoscha** [comment]
@JingsongLi I'm currently busy with preparations for Flink Forward (http://sf.flink-forward.org). I'll get back to reviews and discussions once that's over. (Or maybe I'll be able to sneak in a review or two at the conference. 😅)

**Comment by JingsongLi** [comment]
It's OK. I also want to go to Flink Forward, but San Francisco is too far away.

**Comment by JingsongLi** [comment]
Rebase and Resolve conflicts.

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
retest this please

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
I just merged. Thanks for working on this, @JingsongLi ! 👍

**Pull request closed without merging**
