### PR TITLE
[BEAM-4186] Enable withQuerySplitter

### PR DESCRIPTION
**Pull request by fyellin**
The Jira issue explains the need for this change.

This simply adds withQuerySplitter() to DatastoreV1.Read  The change is relatively straightforward.  I've also added a test.  Because one constructor changed arguments, I changed all calls to the constructor.

I did not make changes to boot.go or piputil.go.   I'm not sure how they got pulled into this, or how to make them go away.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @chamikaramj

**Comment by fyellin** [comment]
To fix failures, I have added `com.google.rpc`.  This package consists of nothing but protocol buffers giving error codes and status.

**Comment by chamikaramj** [comment]
Replied to the thread. I think we should consider alternatives since allowing users to customize the source splitting process could result in serious data loss/duplication related issues.

**Comment by fyellin** [comment]
I am going to drop this request. 

Appengine/Mapreduce made QuerySplitter smarter.   That's probably the best solution here, too

https://github.com/GoogleCloudPlatform/appengine-mapreduce/blob/master/java/src/main/java/com/google/appengine/tools/mapreduce/inputs/DatastoreShardStrategy.java

**Pull request closed without merging**
