### PR TITLE
[BigQueryIO] Use final destination table schema and metadata when creating temp tables

### LINKED ISSUE #22372: [Bug]: PR 17365 breaks BQ loads in some cases
### What happened?

In beam 2.39, this used to work:
```
BigQueryIO
   .write()
   .optimizedWrites()
   .to(OutputTable)
   .withAvroFormatFunction(abc)
   .withAvroSchemaFactory(xyz)
   .withCreateDisposition(CreateDisposition.CREATE_NEVER)
   .withWriteDisposition(WriteDisposition.WRITE_TRUNCATE))
```

but now throws an exception if you end up in MultiPartitionsWriteTables:

```
Caused by: java.lang.IllegalArgumentException: Unless create disposition is CREATE_NEVER, a schema must be specified, i.e. DynamicDestinations.getSchema() may not return null. However, create disposition is CREATE_IF_NEEDED, and org.apache.beam.sdk.io.gcp.bigquery.DynamicDestinationsHelpers$ConstantTableDestinations@52e95e1 returned null for destination tableSpec: <table>
	at org.apache.beam.sdk.util.Preconditions.checkArgumentNotNull(Preconditions.java:436)
	at org.apache.beam.sdk.io.gcp.bigquery.WriteTables$WriteTablesDoFn.processElement(WriteTables.java:207)
```

The reason seems like now, the create disposition is set to `CreateDisposition.CREATE_IF_NEEDED` in WriteTables no matter what the user sets it to.

cc @pabloem @MarcoRob 

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #22372

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @MarcoRob 
R: @Abacn

**Comment by Abacn** [comment]
The test failure looks relevant: https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Commit/988/testReport/junit/org.apache.beam.sdk.io.gcp.bigquery/BigQuerySchemaUpdateOptionsIT/runWriteTestTempTables/

**Comment by ahmedabu98** [comment]
Run Java PreCommit

**Comment by ahmedabu98** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Thanks for the quick fix. Just wondering why we do not need the condition of `if (createDisposition.equals(CreateDisposition.CREATE_IF_NEEDED)
        || createDisposition.equals(CreateDisposition.CREATE_NEVER))` that is removed in https://github.com/apache/beam/pull/17365/files#diff-3edb3abd8909e7075e679e8b93420d4119858d6a9418b6ec10a204a592f062abL682-L692 ?

**Comment by ahmedabu98** [comment]
I believe it's an unnecessary check, since those are the only two existing CreateDispositions: https://github.com/apache/beam/blob/46919b7bbf7d9c68a182c78edc84e97cd7d6b95a/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java#L2170

that condition will always be true

**Review by Abacn — APPROVED** [review]
Thanks! This LGTM

**Comment by Abacn** [comment]
java precommit test failure irrelevant flake: `org.apache.beam.runners.dataflow.worker.StreamingDataflowWorkerTest.testLatencyAttributionToQueuedState[0: [streamingEngine=false]]`

**Pull request merged**
