### PR TITLE
Minor changes to Python fileio

### LINKED ISSUE #24362: [Bug]: Innaccurate default shard naming with fileio
### What happened?

 When fileio writes several shards, the last shard will have as name "00123-of-00124" which may look like incomplete processing.

The first shard should be "00001-of-XXXXX" and not "00000-of-XXXX", and the last shard should be "00124-of-00-124" (in this case for an example with 124 shards).

### Issue Priority

Priority: 3

### Issue Component

Component: io-py-files

### PR DESCRIPTION
**Pull request by iht**
This PR fixes #24362 and adds a slight change to the documentation, to make it clear that the `file_naming` function also receives `destination` as a parameter (it is mentioned at the beginning of the documentation page, but in `WriteToFiles` that parameter description is missing).

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
run python precommit

**Comment by johnjcasey** [comment]
LGTM, just rerunning python

**Comment by Abacn** [comment]
This makes more sense, obviously. Just have worried that if, ever, some user apps could assume the (00123-of-00124) naming pattern and we will break them mysteriously. It may deserve to be noted in "breaking change".

**Comment by johnjcasey** [comment]
Agreed with Yi. Can you add a note to the changes file?

**Comment by Abacn** [comment]
I also suspect same issue also exists elsewhere in the code base. e.g. here: https://github.com/apache/beam/blob/3477d4a76d46c1ad3c89acb636ea7807bfc23e15/sdks/python/apache_beam/io/filebasedsink.py#L208
https://github.com/apache/beam/blob/3477d4a76d46c1ad3c89acb636ea7807bfc23e15/sdks/java/core/src/main/java/org/apache/beam/sdk/io/ShardNameTemplate.java#L57
unfortunately changing all these would be tedious...

**Comment by Abacn** [comment]
Sorry, I mean the finding is great, however due to same issue elsewhere, partial fix would then make the indexing inconsistent throughout the code base.

**Comment by iht** [comment]
> Sorry, I mean the finding is great, however due to same issue elsewhere, partial fix would then make the indexing inconsistent throughout the code base.

Ah, ok. I have checked that this is used in fileio and in the dataframes module. I will update this PR with more details about the potential impact. So far, in my tests, this does not break anything anywhere else in the Python SDK.

Or do you mean that the behavior should be the same in the Java and Python SDKs? I can also add a similar change to the Java SDK, and check where is that used in the rest of the SDK to evaluate potential impact.

**Comment by Abacn** [comment]
> Or do you mean that the behavior should be the same in the Java and Python SDKs? I can also add a similar change to the Java SDK, and check where is that used in the rest of the SDK to evaluate potential impact.

Yes, ideally naming should be consistent throughout SDKs. Currently it is consistent (though weird). Would appreciate if you are willing to find the appearance in both the Java and Python SDKs.

**Comment by AnandInguva** [comment]
stop reviewer notifications

**Comment by ZhengLin-Li** [comment]
> > Or do you mean that the behavior should be the same in the Java and Python SDKs? I can also add a similar change to the Java SDK, and check where is that used in the rest of the SDK to evaluate potential impact.
> 
> Yes, ideally naming should be consistent throughout SDKs. Currently it is consistent (though weird). Would appreciate if you are willing to find the appearance in both the Java and Python SDKs.

@Abacn 

I'd like to keep working on and change the Go and Java SDK. What should I do with Git? Should I create a new branch from master? Seams that I can not create a branch based on this branch([iht:minor_python_doc](https://github.com/iht/beam/tree/minor_python_doc))

**Comment by Abacn** [comment]
thanks for the interests. I would expect many places to change and imo limited benefit compared to the risk.

**Comment by iht** [comment]
> 


> thanks for the interests. I would expect many places to change and imo limited benefit compared to the risk.

I am going to close this PR now, and I will be sending a new one with consistent changes between the Python and Java SDKs. After the holidays, this branch is outdated, and I prefer just to start over than resolving the conflcits.

**Pull request closed without merging**
