### PR TITLE
[BEAM-2390] added time partitioning to BigQueryIO

### PR DESCRIPTION
**Pull request by ericjohnston1989**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by dhalperi** [comment]
retest this please

(testing jenkins integration)

**Comment by aaltay** [comment]
@ericjohnston1989 thank you for this PR. Could you please rebase it to resolve merge conflicts?

**Comment by aaltay** [comment]
R: @reuvenlax

**Comment by reuvenlax** [comment]
Two initial comments:
1. I would like to spend a minute thinking holistically how to add partitioning to BQIO, and mkae sure we are doing so in a consistent way.

2. This PR only affects the streaming branch. All BQIO features need to work on both batch and streaming.

**Comment by ericjohnston1989** [comment]
Should we look into adding batch?  This feature is pretty critical for our application, so I assume others face the same issues. We'd like to get this merged with master in one form or another.

**Comment by reuvenlax** [comment]
After looking over the PR, a few more comments:

1. TimePartitioning belongs in TableDestination. Different TableDestinations specify completely different tables - it doesn't make sense to force a global time partitioning on all of them.

2. Yes, we need to plumb this through in batch as well.  You'll need to pass the shortened name through when we patch the table description.

3. We'll want to plumb this through in BigQueryIOTest so we can test the new functionality.

**Comment by kennknowles** [comment]
@ssisk might also be interested in this

**Comment by SJAnderson** [comment]
any update on this? this feature is pretty critical to my team's pipeline.

**Comment by reuvenlax** [comment]
@ericjohnston1989 are you still interested in this PR? I can help you with the modifications needed.

**Comment by reuvenlax** [comment]
This PR is now obsolete.

**Comment by reuvenlax** [comment]
Duplicate of #3663

**Comment by aaltay** [comment]
I will close this PR based on the [stale](https://beam.apache.org/contribute/contribution-guide/#stale-pull-requests) PR policy, please reopen if you would like to continue working on it.

**Pull request closed without merging**
