### PR TITLE
[BEAM-14410] Add test to demonstrate BEAM-14410 issue in non-cython environments

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Reproduce issue discovered in #17384, verify that it afffects master branch and not just that PR.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by aaltay** [comment]
Could this be closed now? Or were you planning to get it merged?

**Comment by TheNeuralBit** [comment]
This should be merged, I forgot to send it for review.

**Comment by TheNeuralBit** [comment]
R: @AnandInguva

**Review by aaltay — APPROVED** [review]

**Comment by aaltay** [comment]
LGTM. Please self merge after tests pass.

**Comment by TheNeuralBit** [comment]
Looks like these test results not showing up in the GitHub UI is a bug:
- https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Commit/11037/
- https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Commit/9051/

Both passed so I'll go ahead and merge. Thanks @aaltay!

**Pull request merged**
