### PR TITLE
[BEAM-3217] Jenkins job for HadoopInputFormatIOIT

### PR DESCRIPTION
**Pull request by lgajowy**
This PR adds jenkins jobs for HadoopInputFormatIOIT. 

Before this PR there was only one test that used postgres kubernetes scripts (JDBC IOIT). Right now, while having more than one test using those, there is a strong possiblility that two tests will try to create kubernetes resources (eg. service or replication controller) of the same name (say, "postgres"). This will result in one test being unable to run successfully (due to names collision). 

This PR proposes a solution to above problem. Every kubernetes test resource is being created in it's own namespace. This avoids the name collisions and allows running them "in isolation". 

This solution has some other (minor) advantages: 
 - if a Jenkins job gets killed and doesn't clean up it's Kubernetes resources on the cluster we don't have to manually delete them to be able to run other test (now the test fails due to name collisions with the "dangling" resources that are left there)
 - we can easily clean up the cluster with one command. To delete every resource (service, rc, pods etc) it's sufficient to delete the namespace only (`kubectl delete namespace foo`) it deletes it's "inner resources" too. 

Remarks: 
 - Port collisions are still possible even when using namespaces. If two services from different namespaces want bind to the same port we get an error from Kubernetes ("port is already allocated"). This doesn't happen while using load balancer service so it's not a problem for our IOIT tests now.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
@chamikaramj could you take a look?

**Comment by lgajowy** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by lgajowy** [comment]
Closing due to some new problems I noticed

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by lgajowy** [comment]
@chamikaramj sorry for the above mess in comments - I had to run this on Jenkins properly. Now it's ready for review. Could you please take a look?

**Comment by lgajowy** [comment]
Run Java JdbcIO Performance Test

**Comment by lgajowy** [comment]
Run Java JdbcIO Performance Test

**Comment by lgajowy** [comment]
I was able to confirm that HadoopInputFormat Performance test will fail due to dataflow runner issue as well. See [here](https://issues.apache.org/jira/browse/BEAM-3798). 

@chamikaramj could you take a look either way?

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java JdbcIO Performance Test

**Comment by chamikaramj** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by chamikaramj** [comment]
Run seed job

**Comment by lgajowy** [comment]
Retest this please

**Comment by chamikaramj** [comment]
LGTM. Merged.

**Pull request merged**
