### PR TITLE
[BEAM-6705] Fixes ConcurrentModificationException in RowCoderGenerator

### PR DESCRIPTION
**Pull request by mwalenia**
After running ValidatesRunner test suite for Direct Runner using Java 11 I ran into a ConcurrentModificationException in `RowCoderGenerator.generate` method. 

The cause of the exception was a race condition in a pipeline in `ParDoSchemaTest.testReadAndWrite`, `ParDoSchemaTest.testReadAndWriteMultiOutput` and `ParDoSchemaTest.testReadAndWriteWithSchemaRegistry`, where `RowCoderGenerator.generate` (and, as a result, `HashMap.computeIfAbsent`) was called with the same arguments from different threads. This resulted in tests failing with the exception.

Due to the fact that `HashMap.computeIfAbsent` now throws this exception if an external change is detected, it seems that the simplest solution is to change the map class to `ConcurrentHashMap`, which safeguards against such problems.

@reuvenlax, WDYT?  

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mwalenia** [comment]
R: @reuvenlax

**Comment by reuvenlax** [comment]
I ran into something similar, and tried to change to ConcurrentHashMap at
the time. Unfortunately I found that the change is not quite so simple,
because ConcurrentHashMap is not reentrant. In the case of nested Rows,
computeIfAbsent will recursively call generate() again, which could
deadlock everything.

I think the simplest fix to the deadlock would be to replace the recursive
call to generate() (in RowCoderGenerator::getCoder) with an instantiation
of the actual RowCoder class. RowCoder already lazily calls into
RowCoderGenerator the first time encode or decode is called, so this will
remove reentrant call from inside computeIfAbsent. Let me know if you need
some help making that change!

**Comment by mwalenia** [comment]
Thanks for a fast reply! I think I need to understand this part a little bit better in order to modify it properly. If I instantiate the coder in RowCoderGenerator::getCoder, how would I make sure it gets cached in the RowCoderGenerator.generatedCoders map?

Would just calling `RowCoder.coderForFieldType(fieldType)` be sufficient?

**Comment by reuvenlax** [comment]
Maybe a simpler approach for now would be to simply stop using computeIfAbsent, and replace it with an explicit check. Something like this:

Coder<Row> coder = generatedCoders.get(coderId);
if (coder = null) {
  coder = /* compute coder */
  generatedCoders.put(coderId, coder);
}
return coder;

This creates more of a chance of wasted work during a race condition, but will not cause a deadlock. Please add a short comment explaining that computeIfAbsent would deadlock in this situation.

**Comment by mwalenia** [comment]
@reuvenlax Sorry, I force pushed a spotless fix. I reverted the map back to ConcurrentMap.

**Comment by reuvenlax** [comment]
run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
run Flink ValidatesRunner

**Comment by reuvenlax** [comment]
run Spark ValidatesRunner

**Pull request merged**
