### PR TITLE
Better test assertion.

### PR DESCRIPTION
**Pull request by robertwb**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @angoenka

**Comment by robertwb** [comment]
Unrelated failure in apache_beam.transforms.userstate_test.StatefulDoFnOnDirectRunnerTest.test_dynamic_timer_clear_then_set_timer

**Comment by robertwb** [comment]
Run Python PreCommit

**Review by angoenka — APPROVED** [review]
Thanks!

**Comment by tvalentyn** [comment]
I think this broke postcommits cc: @TheNeuralBit 

```
E         apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
E         Traceback (most recent call last):
E           File "apache_beam/runners/common.py", line 1404, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
E           File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python38/src/sdks/python/apache_beam/io/gcp/bigquery_json_it_test.py", line 103, in process
E             self.assertEqual(country_expected, country_actual)
E           File "/usr/local/lib/python3.8/unittest/case.py", line 911, in assertEqual
E             assertion_func = self._getAssertEqualityFunc(first, second)
E           File "/usr/local/lib/python3.8/unittest/case.py", line 892, in _getAssertEqualityFunc
E             asserter = self._type_equality_funcs.get(type(first))
E         AttributeError: 'CompareJson' object has no attribute '_type_equality_funcs'
E         
E         During handling of the above exception, another exception occurred:
E         
E         Traceback (most recent call last):
E           File "/usr/local/lib/python3.8/site-packages/dataflow_worker/batchworker.py", line 646, in do_work
E             work_executor.execute()
E           File "/usr/local/lib/python3.8/site-packages/dataflow_worker/executor.py", line 208, in execute
E             op.start()
E           File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
E           File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
E           File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
E           File "dataflow_worker/native_operations.py", line 54, in dataflow_worker.native_operations.NativeReadOperation.start
E           File "apache_beam/runners/worker/operations.py", line 514, in apache_beam.runners.worker.operations.Operation.output
E           File "apache_beam/runners/worker/operations.py", line 226, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
E           File "apache_beam/runners/worker/operations.py", line 893, in apache_beam.runners.worker.operations.DoOperation.process
E           File "apache_beam/runners/worker/operations.py", line 894, in apache_beam.runners.worker.operations.DoOperation.process
E           File "apache_beam/runners/common.py", line 1406, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py", line 1478, in apache_beam.runners.common.DoFnRunner._reraise_augmented
E           File "apache_beam/runners/common.py", line 1404, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py", line 623, in apache_beam.runners.common.SimpleInvoker.invoke_process
E           File "apache_beam/runners/common.py", line 1585, in apache_beam.runners.common._OutputProcessor.process_outputs
E           File "apache_beam/runners/worker/operations.py", line 226, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
E           File "apache_beam/runners/worker/operations.py", line 893, in apache_beam.runners.worker.operations.DoOperation.process
E           File "apache_beam/runners/worker/operations.py", line 894, in apache_beam.runners.worker.operations.DoOperation.process
E           File "apache_beam/runners/common.py", line 1406, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py", line 1494, in apache_beam.runners.common.DoFnRunner._reraise_augmented
E           File "apache_beam/runners/common.py", line 1404, in apache_beam.runners.common.DoFnRunner.process
E           File "apache_beam/runners/common.py", line 624, in apache_beam.runners.common.SimpleInvoker.invoke_process
E           File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python38/src/sdks/python/apache_beam/io/gcp/bigquery_json_it_test.py", line 103, in process
E             self.assertEqual(country_expected, country_actual)
E           File "/usr/local/lib/python3.8/unittest/case.py", line 911, in assertEqual
E             assertion_func = self._getAssertEqualityFunc(first, second)
E           File "/usr/local/lib/python3.8/unittest/case.py", line 892, in _getAssertEqualityFunc
E             asserter = self._type_equality_funcs.get(type(first))
E         AttributeError: 'CompareJson' object has no attribute '_type_equality_funcs' [while running 'Validate rows']

apache_beam/runners/dataflow/dataflow_runner.py:1672: DataflowRuntimeException
```

**Pull request merged**
