### PR TITLE
[release-2.18.0][BEAM-9123] HadoopResourceId returns wrong directoryName bugfix

### PR DESCRIPTION
**Pull request by dmvk**
backport of https://issues.apache.org/jira/browse/BEAM-9123

### CODE REVIEW

**Comment by dmvk** [comment]
cc @aromanenko-dev

**Comment by tvalentyn** [comment]
Please do not merge commits into release branches without an approval from the release manager. This has been discussed on Beam mailing least a few times.

**Comment by udim** [comment]
Since 2.19 has the same cherrypick, could we make this a known issue for 2.18 and revert this?

**Comment by aromanenko-dev** [comment]
@tvalentyn Sorry for messing things up. I'm fine to revert this commit from `release-2.18.0` branch since it's not a blocker.

**Pull request merged**
