### PR TITLE
Add Spanner Integration tests to verify exception handling

### PR DESCRIPTION
**Pull request by nielm**
Verifies that Exceptions during read should abort the pipeline.
issue #21564

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by nielm** [comment]
r: @pabloem @chamikaramj

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
test seems broken: https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/1067/testReport/junit/org.apache.beam.sdk.io.gcp.spanner/SpannerReadIT/testReadFailsBadSession/

**Comment by nielm** [comment]
Unable to serialize a MapElements function?!
Weird.
Didn't see that in my local testing, nor when I ran integration tests on dataflow...

Will investigate further...

```
java.lang.IllegalArgumentException: unable to serialize DoFnWithExecutionInformation{doFn=org.apache.beam.sdk.transforms.MapElements$1@7e8011e2, mainOutputTag=Tag<output>, sideInputMapping={}, schemaInformation=DoFnSchemaInformation{elementConverters=[], fieldAccessDescriptor=*}}
```

**Comment by nielm** [comment]
> Unable to serialize a MapElements function?! Weird. Didn't see that in my local testing, nor when I ran integration tests on dataflow...

Missed the `Caused by: java.io.NotSerializableException` lower down - I was using a lambda in a non-serializable class. Dunno how it passed my local testing /shrug

**Comment by nielm** [comment]
Run Java PostCommit

**Comment by nielm** [comment]
Run Java PreCommit

**Comment by nielm** [comment]
Run Java PostCommit

**Comment by nielm** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
phrase triggering is disabled for now it seems

**Comment by nielm** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
thanks! LGTM

**Pull request merged**
