### PR TITLE
[BEAM-3060] split one job into several jobs, one for each IO.

### PR DESCRIPTION
**Pull request by DariuszAniszewski**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run seed job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
@chamikaramj  For this PR to properly run, following tables must be created in BigQuery:
```
beam_performance.textioit_pkb_results
beam_performance.compressed_textioit_pkb_results
beam_performance.avroioit_pkb_results
beam_performance.tfrecordioit_pkb_results
```
or [this PR on PerfKit](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1554) that allows automatic creation must be merged.

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run seed job

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java AvroIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java CompressedTextIO Performance Test

**Comment by DariuszAniszewski** [comment]
Run Java TFRecordIO Performance Test

**Comment by DariuszAniszewski** [comment]
@chamikaramj Alan created tables and as you can see above tests are now passing. Each IO has own Jenkins job and pushes data to dedicated BQ table, there will be dedicated dashboard as well. 
This PR is ready to review, PTAL
Thanks

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Pull request merged**
