### PR TITLE
[BEAM-2609] refine UDF interface

### PR DESCRIPTION
**Pull request by XuMingmin**
A proposal solution for UDF interface.

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @xumingming @takidau @jbonofre

**Comment by xumingming** [comment]
Do not quite understand the purpose of `BeamSqlUdf`, seems no methods defined in it, and so it can not restrict what methods user need to implement.

**Comment by XuMingmin** [comment]
In Java we cannot define a __static `eval`__ method with variable parameters, --maybe I miss some features.

However with an interface here it helps to centralize the usage of UDF, and enable to load UDF classed automate in BEAM-2445(for BeamSqlCli I think);

**Comment by jbonofre** [comment]
R: @jbonofre

**Pull request merged**
