### PR TITLE
[BEAM-1994] Remove Flink examples package

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
R: @aljoscha

**Comment by aljoscha** [comment]
This also LGTM once Jenkins is green! 👍

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by jbonofre** [comment]
Can you rebase to fix the conflict ? It should be OK on Jenkins after that.

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Pull request merged**
