### PR TITLE
[BEAM-1356] mvn clean install -DskipTests still runs python tests

### PR DESCRIPTION
**Pull request by aviemzur**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aviemzur** [comment]
R: @aaltay 
CC: @dhalperi

**Comment by aaltay** [comment]
Thank you @aviemzur. I assume you tested with `mvn clean install -DskipTests`. LGTM.

@dhalperi do you have comments?

**Comment by dhalperi** [comment]
Tried it, LGTM. @aaltay  can you please merge?

**Comment by aviemzur** [comment]
Rebased on master

**Comment by aaltay** [comment]
I will merge it. Thank you.

**Pull request merged**
