### PR TITLE
Pin runner harness container image for Dataflow distributions of BEAM…

### PR DESCRIPTION
**Pull request by tvalentyn**
… Python SDK

This fixes https://issues.apache.org/jira/browse/BEAM-3011

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @aaltay 
CC: @reuvenlax

**Comment by aaltay** [comment]
LGTM. For the record this CP #3970 and #3972.

**Comment by tvalentyn** [comment]
Thanks Ahmet. Small correction of the record: this CP #3966 and #3972.

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
There was one passing run of Python tests yesterday for the commit id on the PR ce388bc51fbb6eb704db210d33a027e65bcdc6f9 , https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/180/. 

I'll try to figure out what exactly Jenkins is unhappy about, but I believe the failures are not related to this PR. In fact, Python Jenkins test suite fails without this PR: https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/191/.

**Comment by aaltay** [comment]
cc: @herohde @jasonkuster 

I think the test failures in the release branch is related to https://github.com/apache/beam/pull/3965. If I understand correctly Jenkins execute tests based on the groovy files from the master. This PR updated one of those files with a project reference to `sdks/python/container`. However that project was only added to the master branch and not to the release branch. That is why precommit tests in release branch are failing.

We can either rollback the groovy change, or if it is safe CP the original change to the release branch.

**Comment by herohde** [comment]
CC: @kennknowles 

We should really not use test scripts from master in release branches. The groovy change would break master, if rolled back. CPing the Python container PR is probably safe assuming the changes it depends on are present, but sets a poor precedent.

Alternatively, given that the container is last in the test, perhaps just ignore the failure?

**Comment by aaltay** [comment]
I agree that the testing setup needs to change.

The alternative (ignoring the results) is not viable because tests fails early on without executing anything else. The error is "Could not find the selected project in the reactor: sdks/python/container". Someone with maven knowledge can comment on why that is happening.

> CPing the Python container PR is probably safe assuming the changes it depends on are present

What are the the things that it depends? Since the release branch is cut recently, I guess that will be the case.

**Comment by kennknowles** [comment]
I agree _strongly_ that the test scripts should live alongside the code.

The test scripts reference aspects of the repo which change, such as which modules are present. That is what is going wrong now. We have previously had issues with the scripts referencing maven profiles and whatnot which either do or do not exist when needed. It has only gotten worse, and I expect the trend to continue, since the flaw is conceptual.

When we moved from Travis to Jenkins I wanted to keep this property of tests evolving with code, which Travis-CI has naturally, by having a script in the repo that Jenkins would invoke. This also minimizes Jenkins churn, which is quite tedious to debug and very hard to test in advance.

There were some specious objections about execution of arbitrary code, which you can always do and is sort of the point. Beyond that, the tight integration with Jenkins plugins may not be possible. The current issue is strong evidence that technical necessity outweighs those niceties.

It is some real work, but if the hacks below don't immediately solve things, it may be simplest to move in the right direction here and alter the Jenkins jobs to just invoke a script so it can be different on `master` and this branch.

> The error is "Could not find the selected project in the reactor: sdks/python/container". Someone with maven knowledge can comment on why that is happening.

This is happening because `sdks/python/container` does not exist, just as the discussion has mentioned. The Python precommit specifies `--projects 'sdks/python,!sdks/python/container'` to avoid building the container. It is unfortunate that this is a fatal error.

Possibilities:

 - One hack to avoid this would be to control this with a profile, which is not a fatal error if missing. The new toggle would be  `--activate-profiles '!python-container'`. That is not a good long-term solution because poms are gross enough with hacks kept to a minimum.
 - We could also remove the `--also-make-dependents` since I think the Python SDKs model of including all code in a single module makes it irrelevant. My experience trying to run build all submodules, as with `--projects runners` is that it does _not_ build submodules by default, so you can build `--projects sdks/python` and it will not automatically build the submodule.

**Comment by kennknowles** [comment]
I'll ask around a little and maybe move the larger discussion to the dev list. But it looks like [Pipeline / Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/) is something along these lines.

**Comment by tvalentyn** [comment]
> One hack to avoid this would be to control this with a profile, which is not a fatal error if missing. The new toggle would be --activate-profiles '!python-container'. That is not a good long-term solution because poms are gross enough with hacks kept to a minimum.
We could also remove the --also-make-dependents since I think the Python SDKs model of including all code in a single module makes it irrelevant. My experience trying to run build all submodules, as with --projects runners is that it does not build submodules by default, so you can build --projects sdks/python and it will not automatically build the submodule.

It sounds like these hacks would silence the problem but it can still manifest in a different context down the road. If we consider hacks for the sake of this release branch, I would cherrypick 38a9cdb08f3d682f7c0d32aadbc645a34dd56639 into the branch, which adds sdks/python/containers/pom.xml and presumably will make Jenkins happy. And then we should figure out a long-term solution that uses job configs from the branch for Jenkins presubmit runs for the branch. Filed: https://issues.apache.org/jira/browse/BEAM-3047.

> The alternative (ignoring the results) is not viable because tests fails early on without executing anything else. 

I ran locally in the brach directory the following commands. Does this gives us enough confidence that PR is safe to merge?
```
mvn clean install -pl sdks/python -am -amd 
mvn clean install -pl sdks/java/core,runners/direct-java -am -amd
```
Both runs were successful and finished within 4 and 20 min respectively. Jenkins runs take around an hour.

**Comment by herohde** [comment]
My mistake for misreading the Jenkins logs, so ignoring the error is indeed not a good alternative.

+1 to @tvalentyn's proposal of cherrypicking the container commit he mentions. It is safe (adds only the python container code, which is not part of the release anyway and to be ignored by the test) and fixes the problem, so it seems to be the simplest and fastest way forward for the 2.2.0 release.

**Comment by tvalentyn** [comment]
I was not able to cherrypick 38a9cdb since I could not find it on any branch, including herohde/containers. 38a9cdb is a subset of 79c55db, so I cherrypicked 79c55db and manually reverted eeb4d73 which is also a part of  79c55db, in case it matters. I am curious if there is a way to cherrypick a subset of commits from a PR merged into another branch.

**Comment by aaltay** [comment]
The commits were squashed while merging, that is why you can only find one of them. Current changes on this PR looks correct to me.

**Comment by kennknowles** [comment]
Cherrypicking a commit is independent of whether it is on any branch. The problem is likely that your `git fetch` did not pull it down because it was not reachable from any public tag or branch, or that it was garbage collected. GitHub is pretty aggressive about GC so it must be referenced somewhere...

**Comment by kennknowles** [comment]
Side note - if changes in a PR have reasonable meaning and can stand alone, they shouldn't be squashed. Our contribution guide is a bit contrary to best practice in this regard.

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
In the latest run Python tests failed again with:

CalledProcessError: Command '['pip', 'install', '--target', '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_MavenInstall/sdks/python/.eggs/grpcio-wheels', '--build', '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_MavenInstall/sdks/python/.eggs/grpcio-wheels-build', '--upgrade', 'grpcio-tools>=1.3.5']' returned non-zero exit status 1
Traceback (most recent call last):
  File "setup.py", line 203, in <module>
    'test': generate_protos_first(test),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 143, in run
    gen_protos.generate_proto_files()
  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_MavenInstall/sdks/python/gen_protos.py", line 86, in generate_proto_files
    raise ValueError("Proto generation failed (see log for details).")
ValueError: Proto generation failed (see log for details).

Suspecting Jenkins may be using sdks/python/gen_protos.py version updated by this PR https://github.com/apache/beam/pull/3924.

**Comment by tvalentyn** [comment]
Java suite keeps failing with "Maven JVM terminated unexpectedly with exit code 137".
https://stackoverflow.com/questions/24989653/jenkins-maven-build-137-error suggests the machine running Jenkins may be running out of virtual memory. @jasonkuster Is there something we should do about this?

Given current test infrastructure is not using correct source files, and Pytnonthe tests past locally, I'm going to stop investigating test failures on this PR. Ahmet, do you feel comfortable merging it in the current state?

**Comment by kennknowles** [comment]
Can we get the logged details? FWIW I also essentially always get a failure there unless I run it in a virtualenv. Presumably something about my system installs.

**Comment by kennknowles** [comment]
The `gen_protos.py` has not been changed for this branch, and Jenkins doesn't do anything with them.

**Comment by tvalentyn** [comment]
Looks like the error is a flake, since Python tests just passed.

gen_protos.py runs `pip install command` https://github.com/apache/beam/blob/9c2a6e771d30e3e120b941bd2d450a00d8b7f091/sdks/python/gen_protos.py#L122

Then something goes wrong:
Temp directory GC'ed? Never created?

> writing list of installed files to '/tmp/pip-UOKO_n-record/install-record.txt'
> error: [Errno 2] No such file or directory: '/tmp/pip-UOKO_n-record/install-record.txt'

Then pip attempts to clean up temp directory, also fails:
> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>  ...
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 751, in install
>     os.rmdir(temp_location)
> OSError: [Errno 2] No such file or directory: '/tmp/pip-UOKO_n-record'

Then pip fails to join a list of string being unable to perform byte encoding. Unexpected symbols happen to be in the log message? Or memory corruption?

> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
>   File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
>     return command.main(cmd_args)
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
>     text = '\n'.join(complete_log)

> UnicodeDecodeError:`
 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

This is the full log https://builds.apache.org/job/beam_PreCommit_Python_MavenInstall/228/consoleFull

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
It's a very exciting experience so far - the Java tests keep failing for all sorts of reasons. I'll go over over them tomorrow and send a summary, and in the mean time filed a bug about another Python flake: https://issues.apache.org/jira/browse/BEAM-3053

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
This time, Python tests failed with a timeout (likely https://issues.apache.org/jira/browse/BEAM-3040), Java tests failed with 
java.lang.RuntimeException: Dataflow job 2017-10-12_22_23_17-7302708842156212183 terminated in state UNKNOWN but did not return a failure reason.

**Comment by tvalentyn** [comment]
retest this please.

**Comment by tvalentyn** [comment]
3 out of 7 runs for Java integration tests failed to due to flakes:
https://issues.apache.org/jira/browse/BEAM-3054
https://issues.apache.org/jira/browse/BEAM-3055
https://issues.apache.org/jira/browse/BEAM-3057

4 out of 7 seems to fail with due to a failure in dataflow-runner-integration-tests @ beam-examples-java :  https://issues.apache.org/jira/browse/BEAM-3056. @aaltay  Can you please trigger run Jenkins on the branch to double check if the error happens on the branch itself without this PR?

**Comment by aaltay** [comment]
I triggered: https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15069/

**Comment by tvalentyn** [comment]
@aaltay Thank you!

**Comment by tvalentyn** [comment]
And it failed with a seemingly same reason. I will mark https://issues.apache.org/jira/browse/BEAM-3056 a release blocker.

**Comment by reuvenlax** [comment]
how is this PR going?

**Comment by tvalentyn** [comment]
@reuvenlax The PR is ready to be merged, however Java precommit tests on this branch are not passing, even without this PR. So committers do not have a green test signal to merge this PR. I didn't have time today to rootcause the failure due to concurrent efforts. Do you have suggestions for who should be driving the process of fixing the release branch: https://issues.apache.org/jira/browse/BEAM-3056 ?

**Comment by kennknowles** [comment]
The tests timed out during streaming integration tests of examples on Dataflow. The log lines showing it starting ~7:30 and aborting ~8:30 so it looks like a real crash loop situation to me.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
run java postcommit

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
Let's go ahead and get a bunch of signal if we can.

**Comment by tvalentyn** [comment]
Precommit suite flaked out.  https://issues.apache.org/jira/browse/BEAM-3056 has links to and log snippets from the runs failed in the past. Maybe let's move the discussion there?

**Comment by tvalentyn** [comment]
Dataflow test passed, the test suite just did not make it in 150 min, although it was making consistent progress. Test run aborted while executing Gearpump tests.

**Comment by tvalentyn** [comment]
run java precommit

**Comment by tvalentyn** [comment]
Looks like 'run java precommit' spell has no power here.

**Comment by tvalentyn** [comment]
Run PreCommit Pipeline Java

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Pull request merged**
