### PR TITLE
[BEAM-6333] allow disabling idle partition watermark advancement

### PR DESCRIPTION
**Pull request by domsj**
This change allows disabling the automatic watermark advancement for idle kafka partitions.
This is needed for pipelines that require watermarks to be absolutely correct (see e.g. my experiment [streamy-db](https://github.com/domsj/streamy-db), although I've worked around this issue by defining [my own timestampPolicyFactory](https://github.com/domsj/streamy-db/blob/594b8db1a1008f8c46a5483ea9284cb2ea714dbb/src/main/scala/domsj/streamy/db/beam/package.scala#L20-L46)).

I'm not sure what the best road is towards making this contribution, how much discussion it would need, and via which channel. So I'm just opening this preliminary PR and hoping you will enlighten me about the proper way forward :-)

------------------------
Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
@domsj Thank you for contribution! 
Could you create a Jira issue for this change (if it doesn't exist yet) and add an issue ID to your PR and commit messages as a prefix? 
Please, let me know if you don't have a Jira account and/or needed permissions. 
You can find more details about Beam contribution workflow here: https://beam.apache.org/contribute/#share-your-intent

Also, seems like Spotless job is failing because of spotlessApply violation. Please, run `gradlew spotlessApply` to fix this.

**Comment by aromanenko-dev** [comment]
R: @rangadi

**Comment by domsj** [comment]
Thanks for the feedback. I applied the spotless java step and force pushed the change.

I created https://issues.apache.org/jira/browse/BEAM-6333, will update PR title next.

**Comment by rangadi** [comment]
Left a comment on the Jira. Lets discuss about actual usecase and what we want to do there. We can then look into specific changes.. I have a few minor comments on the implementation. Would like to understand the motivation more.

**Comment by domsj** [comment]
Closing as agreed on jira

**Pull request closed without merging**
