### PR TITLE
Added per-computation map transform->state_family to windmill's GetConfigResponse.

### PR DESCRIPTION
**Pull request by drieber**
Added per-computation map transform->state_family to windmill's GetConfigResponse.

Added field computation_config_map to GetConfigResponse. It maps from computation_id to ComputationConfig. ComputationConfig has transform_user_name_to_state_family. This is necessary because in some optimized graphs, the same stateful transform appears in more than one stage, and each instance must use its own state_family.

### CODE REVIEW

**Comment by drieber** [comment]
@dpmills 
@lukecwik

**Comment by drieber** [comment]
@kennknowles

**Comment by drieber** [comment]
retest this please

**Comment by drieber** [comment]
R: @youngoli 
R: @kennknowles

**Comment by drieber** [comment]
The error is unrelated:

11:08:06 > Task :beam-runners-core-construction-java:test
11:08:06 Error occurred during initialization of VM
11:08:06 java.lang.OutOfMemoryError: unable to create new native thread
11:08:06 Error occurred during initialization of VM
11:08:06 java.lang.OutOfMemoryError: unable to create new native thread
11:08:06 Process 'Gradle Test Executor 13' finished with non-zero exit value 1

**Comment by drieber** [comment]
retest this please

**Comment by kennknowles** [comment]
LGTM. If the Python test fails in a way that looks flaky you can re-run just that one via the words in quotes: "Run Python PreCommit" (not case-sensitive)

**Comment by drieber** [comment]
@kennknowles What are the next steps here? Sorry I am not too familiar with the process yet.

**Comment by kennknowles** [comment]
You are g2g. Thanks!

**Comment by kennknowles** [comment]
It looks like maybe you have two meaningful commits and a bunch of merge commits. Do you intend that, or are they actually just one to be squashed?

**Comment by drieber** [comment]
I think it is just one to be squashed. Should I do something on my end?

**Comment by kennknowles** [comment]
Nope! Squashed & merged.

**Pull request merged**
