### PR TITLE
[BEAM-14087] Mapped JOB_STATE_RESOURCE_CLEANING_UP to State.RUNNING

### PR DESCRIPTION
**Pull request by paul-tlh**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by chamikaramj** [comment]
Could you create a Jira ? https://beam.apache.org/community/contact-us/

**Comment by paul-tlh** [comment]
> 

Done, please see https://issues.apache.org/jira/browse/BEAM-14087.

**Comment by chamikaramj** [comment]
Just to clarify a bit, the Jira says "This is likely due to using an older version of Beam." but this change will only be added to latest Beam. Does that help ?

Also, should we do the same update the Python SDK ? (in a separate PR)

**Comment by paul-tlh** [comment]
> 
re the error message "This is likely due to using an older version of Beam." 
It's because JOB_STATE_RESOURCE_CLEANING_UP doesn't match with any state in this switch statement so it logs the error in the "default". To avoid this warning, the customer needs to upgrade their SDK after this PR has been included in the latest Beam SDK

re python 
The state has been added in python sdk (https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/dataflow/internal/clients/dataflow/dataflow_v1b3_messages.py#L2188).

**Comment by chamikaramj** [comment]
That's the client. I think you need to update Python SDK here: https://github.com/apache/beam/blob/e97afe9fdf1ec600bbd29f53ddec12dbb4a0ec71/sdks/python/apache_beam/runners/dataflow/dataflow_runner.py#L1565

But that can be a separate PR.

**Pull request merged**
