### PR TITLE
Fix Spark 3 job-server jar path for Python test suites 

### LINKED ISSUE #23935: [Bug]: Portable runner tests use invalid path to Spark 3 job-server jar
### What happened?

See https://github.com/apache/beam/issues/23907:

> Seeing a lot of ValueError: Unable to parse jar URL "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Examples_Spark/src/runners/spark/2/job-server/build/libs/beam-runners-spark-3-job-server-2.44.0-SNAPSHOT.jar". If using a full URL, make sure the scheme is specified. If using a local file path, make sure the file exists; you may have to first build the job server using './gradlew runners:spark:3:job-server:shadowJar'.
Is this familiar to anyone?

This was caused by https://github.com/apache/beam/pull/23751 when migrating to the Spark 3 job-server

### Issue Priority

Priority: 1

### Issue Component

Component: testing

### PR DESCRIPTION
**Pull request by mosche**
This slipped in https://github.com/apache/beam/pull/23751 when migrating to the Spark 3 job-server.
Closes #23935, related to #23907

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @aromanenko-dev

**Comment by ahmedabu98** [comment]
Run Python Examples_Spark

**Review by aromanenko-dev — APPROVED** [review]
LGTM, thanks

**Comment by aromanenko-dev** [comment]
Run Python PreCommit

**Comment by aromanenko-dev** [comment]
Run Python Examples_Spark

**Comment by ahmedabu98** [comment]
The failing Spark example tests are due to another issue #23907

**Comment by mosche** [comment]
@aromanenko-dev No @aromanenko-dev ... it's yet another issue

**Comment by ahmedabu98** [comment]
@aromanenko-dev I think there are two separate issues blocking the release. This solves one of them, the other is a BQ issue (see [comment](https://github.com/apache/beam/issues/23907#issuecomment-1298954833)) that affects both Spark and Flink example test suites

**Comment by aromanenko-dev** [comment]
Ok, so I think we can move forward and merge it

**Pull request merged**
