### PR TITLE
[BEAM-1871] Clean-up org.apache.beam.sdk.util, move BitSetCoder from util to coder

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @tgroh @kennknowles 
Kicked off https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10060/

**Comment by kennknowles** [comment]
This should be moved to runners-core unless we really really like it. It is used only by trigger state machines.

**Comment by lukecwik** [comment]
BitSet is a generic java type, I could see others using it which is why I kept it in sdks/core instead of hiding it.

**Comment by lukecwik** [comment]
Unfortunately Dataflow worker is shading runners core, instead will duplicate BitSetCoder, update Dataflow Worker, and delete original.

**Comment by lukecwik** [comment]
Scheduled rebuild with both BitSetCoders:
https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10066/

**Pull request closed without merging**
