### PR TITLE
[BEAM-9285] Add Postcommit ValidatesRunner CI Job for Flink on Java 11

### PR DESCRIPTION
**Pull request by iemejia**
The failing tests are due to some issues with bytebuddy code generation tracked on
https://issues.apache.org/jira/browse/BEAM-9370 

R: @mwalenia 
CC: @mxm @sunjincheng121 (for awareness)

### CODE REVIEW

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Flink ValidatesRunner Java 11

**Comment by mwalenia** [comment]
Take a look at https://github.com/apache/beam/pull/11076
Pawel found a better, more maintainable way of making sure tests are compiled and ran with proper versions of Java. Can we wait until his PR is merged and migrate your PR to that solution as well?

**Comment by iemejia** [comment]
Sure no problem, but from a quick look at the PR this looks to be only for precommits or will it work easily for postcommits too? @mwalenia ?

**Comment by pawelpasterz** [comment]
@iemejia Let me answer, once this small part of gradle script is merged it should be easy to add more jobs/tests. It might happen it would require small refactor.

**Comment by iemejia** [comment]
Any news on this @pawelpasterz ? Otherwise I think we should just merge this one and get it refactored afterwards once the new approach is ready, WDYT?

**Comment by pawelpasterz** [comment]
@iemejia Fine to me, sorry for delay.

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Flink ValidatesRunner Java 11

**Comment by iemejia** [comment]
Just rebased and re run the tests, can you take a look please @mwalenia

**Comment by mwalenia** [comment]
Run Flink ValidatesRunner Java 11

**Comment by mwalenia** [comment]
The tests themselves look good, @iemejia you need to remember to refactor them after a better solution is posted, since this is unfortunately not easy to maintain.

**Comment by iemejia** [comment]
I will once we have a recommended way to do it. Notice that the test failure is expected and reported as [BEAM-9370](https://issues.apache.org/jira/browse/BEAM-9370) (to be fixed)

**Comment by mwalenia** [comment]
LGTM then :) Thanks!

**Comment by iemejia** [comment]
Thanks @mwalenia

**Comment by iemejia** [comment]
and don't hesitate to ping me guys when you have the updated proper version to fix it.

**Pull request merged**
