### PR TITLE
[BEAM] Submitting final communication strategy

### PR DESCRIPTION
**Pull request by macruzbar**
_**Please** add a meaningful description for your change here_

I am submitting the finalized files for the Apache Beam communication strategy that we have been discussing [over email](https://lists.apache.org/list.html?dev@beam.apache.org:lte=1M:communication%20strategy), so that they can be incorporated to the repository for anyone to use and reference. All files are in the folder /channels and communication strategy. 

The goal of the communication strategy is to grow Apache Beam projects by driving more new users, and accelerating the conversion of users to contributors. It outlines 3 specific proposals for implementation.  

I'm requesting the following reviewers, based on who gave feedback on the mailing list:
- @tweise 
- @pabloem 
- @kennknowles 
- @matthiasa4 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by macruzbar** [comment]
I'm requesting the following reviewers, based on who gave feedback on the mailing list:

@tweise
@pabloem
@kennknowles
@matthiasa4

**Comment by tweise** [comment]
+1 for wiki

**Comment by macruzbar** [comment]
> +1 for wiki

ok great! Do I need to submit a new pull request?

**Comment by pabloem** [comment]
The wiki is here: https://cwiki.apache.org/confluence/display/BEAM

Wiki edits are not done via pull requests. You can create an account, and I'll assign you privileges to add pages.

**Comment by matthiasa4** [comment]
LGTM! I think some of the artifacts could also go on the [community part](https://beam.apache.org/community/) of the website if rewritten as guidelines?

**Comment by macruzbar** [comment]
> The wiki is here: https://cwiki.apache.org/confluence/display/BEAM
> 
> Wiki edits are not done via pull requests. You can create an account, and I'll assign you privileges to add pages.
@pabloem  I have an account already on cwiki with my work email. Feel free to give me privileges and I'll add it there.

**Comment by macruzbar** [comment]
> Overall, I think this content may be most appropriate to the wiki where we are accumulating more detailed dev-oriented information. I wonder what the other reviewers think.

@kennknowles @tweise I was reflecting more on this and have a question: being that the Github repository is usually the second platform new users explore after the website, wouldn't it make sense to have some information on the repo about Beam channels and what to expect in each one? I think [this map](https://github.com/macruzbar/beam/blob/master/channels%20and%20communication%20strategy/Comms-channels-map.md) might come in handy for someone who is new to the community.

**Comment by kennknowles** [comment]
It is an interesting point. I do think the map is helpful for a consumer of the channels.

**Comment by aaltay** [comment]
What should be the next action for this PR? Should we close it, if it is going to the wiki?

**Pull request closed without merging**
