### PR TITLE
[BEAM-12515] Revert "[BEAM-12119] [BEAM-12122] Add integer and string `_id` keys support to Python IO MongoDB"

### PR DESCRIPTION
**Pull request by tysonjh**
Reverts apache/beam#14460

### CODE REVIEW

**Comment by kennknowles** [comment]
Can you add some details about what is broken that the revert fixes?

**Comment by tysonjh** [comment]
> Can you add some details about what is broken that the revert fixes?

I have no details. This was basically a test to verify some theories discussed in https://github.com/apache/beam/pull/15104 .

More info in https://issues.apache.org/jira/browse/BEAM-12515

**Comment by kennknowles** [comment]
Well it does seem to alleviate the problem, mysteriously. Having a clear test signal is quite important so I think it is worthwhile to revert. But let's work together to roll it forward because I don't think this code is the actual problem. CC @MaksymSkorupskyi  with apologies for this trouble.

**Comment by kennknowles** [comment]
run pythondocker precommit

**Comment by kennknowles** [comment]
run python precommit

**Review by kennknowles — APPROVED** [review]
Based on Brian's testing, I think this does somehow relieve the problem. Going to merge.

**Comment by MaksymSkorupskyi** [comment]
> Well it does seem to alleviate the problem, mysteriously. Having a clear test signal is quite important so I think it is worthwhile to revert. But let's work together to roll it forward because I don't think this code is the actual problem. CC @MaksymSkorupskyi with apologies for this trouble.

no problem at all, no worries :)

**Pull request merged**
