### PR TITLE
SolaceIO.Write: add data classes, connector interface

### PR DESCRIPTION
**Pull request by iht**
This is a followup PR to #31906, and part of the issue #31905

This adds the interface of the Write connector and a few classes (data classes, POutput) that are used by the connector.

More changes are coming in a subsequent PR.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by iht** [comment]
assign set of reviewers

**Comment by shunping** [comment]
Code change looks good. 

Are we expecting unit and integration tests to come in the follow-up PR?

**Comment by iht** [comment]
@shunping Yes, integration tests, and the actual code of the connector are prepared in an upcoming PR. I am sending them in "chunks" because it is thousands of lines of code, to facilitate the review.

**Comment by Abacn** [comment]
merge this after received a lgtm review above

**Pull request merged**
