### PR TITLE
[BEAM-2163] Remove the dependency on examples from ptransform_test

### PR DESCRIPTION
**Pull request by JavierAntonioGonzalezTrejo**
The test_read_metrics function no longer depends on the snippets file. The CountingSource class is contained in io.utils which forms part of the library.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `./gradlew build` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by pabloem** [comment]
Hello Javier.
Since `CountingSource` might be used in other cases (e.g. other tests), could you add it to `beam/sdks/python/apache_beam/io/` instead?

**Comment by pabloem** [comment]
I was trying to find a file that it's appropriate for. I'm thinking that a new file should be fine for it.

**Comment by JavierAntonioGonzalezTrejo** [comment]
Hi Pablo
I put the class on a general snippets file inside the io folder. I put named the file snippets in case any other function or class that is required on the io folder, but does not makes sense under any other file.

**Comment by pabloem** [comment]
Hi Javier!
I'm sorry about the back-and-forth. Could you rename the file to 'utils' instead of 'snippets', and remove the `[START model_custom_source_new_source]` and `[END model_custom_source_new_source]`?
Thanks!

**Comment by JavierAntonioGonzalezTrejo** [comment]
Hi Pablo
Thanks for the feedback : )
Changed file name and removed comments as suggested.

**Pull request merged**
