### PR TITLE
[BEAM-2953] Part 1 of Multipart advanced timeseries examples

### PR DESCRIPTION
**Pull request by rezarokni**
Hi @kennknowles 
This is part 1 of the multipart example dealing with backfill via a heartbeat of timeseries data.
The update is in multiple parts to allow the PR to be easier to review.
Cheers

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by reuvenlax** [comment]
R: @kennknowles

**Comment by aaltay** [comment]
any updates?

**Comment by rezarokni** [comment]
As this commit is too big and impractical to review for a example, I am going to close this PR and create smaller bit sized pieces.

**Pull request closed without merging**
