### PR TITLE
[BEAM-5446] SplittableDoFn: Remove "internal" methods for public API surface

### PR DESCRIPTION
**Pull request by lukecwik**
Note that this change modifies the @ProcessElement method to require users to use RestrictionTracker
instead of a concrete sub-type.

This change enables us to remove the synchronization requirement for users as we will
wrap the underlying restriction tracker allowing us to add appropriate synchronization as
needed and also to watch any calls that pass through the object such as the claim calls.

RestrictionTrackers was placed within sdks/java/fn-execution since watching claim observers will
be needed within the Java SDK harness in addition to the legacy implementation found in runners/core-java.

Eventually the code can be moved out of sdks/java/fn-execution and placed only within the SDK harness
itself once all pipelines run portably.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @iemejia @swegner 
CC: @robertwb

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
@iemejia @swegner it seems that `WatchTest` are failing on master because transform needs to be refactored to comply with this change.

**Comment by kanterov** [comment]
It seems that `org.apache.beam.sdk.io.TextIOReadTest$BasicIOTest#testReadWatchForNewFiles` is broken for the same reason.

**Comment by swegner** [comment]
Is there a JIRA or additional context on the test failure you can share? This change went in a couple months ago; did the test just start failing or has it been failing for the last two months?

**Comment by kanterov** [comment]
@swegner there is no JIRA, issue needs to be investigated. It was failing since this change, but it was never executed on Jenkins because we don’t run runner tests in Java pre commit due to a different issue.

**Comment by kanterov** [comment]
@swegner https://issues.apache.org/jira/browse/BEAM-6354

**Comment by swegner** [comment]
FYI, this was reverted in #7540. Details are in [[BEAM-6352]](https://issues.apache.org/jira/browse/BEAM-6352).

**Pull request merged**
