### PR TITLE
Fix kotlin warnings

### PR DESCRIPTION
**Pull request by harshithdwivedi**
@pabloem @alexvanboxel this PR should eliminate the warnings that started showing up in builds due to the addition of kotlin snippets.

Opened as a replacement of #10204

### CODE REVIEW

**Comment by alexvanboxel** [comment]
Please make a single commit out of this

**Comment by harshithdwivedi** [comment]
Can't you squash these on your end while merging?
I'll be happy to do so otherwise.

**Comment by alexvanboxel** [comment]
I can, but then it's up to github (I don't know what will be left of your street cred when it's squached :). If you don't care I can squach. Your sure that the deleted files are obsolete right?

**Comment by harshithdwivedi** [comment]
Haha, it's alright.
Github will preserve the commit history made by me.

And yeah, the files I deleted were tests that were not needed :)

**Comment by pabloem** [comment]
thanks Alex, Harshit!

**Pull request merged**
