### PR TITLE
Fix google-api-services-bigquery to match new google-cloud-bigquery

### PR DESCRIPTION
**Pull request by bvolpato**
Got the following error in a few tests with `2.50.0-SNAPSHOT`

```
java.lang.NoSuchMethodError: 'com.google.api.services.bigquery.model.TableConstraints com.google.api.services.bigquery.model.Table.getTableConstraints()'
	at com.google.cloud.bigquery.StandardTableDefinition.fromPb(StandardTableDefinition.java:409)
	at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:161)
	at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:253)
	at com.google.cloud.bigquery.Table.fromPb(Table.java:690)
	at com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:298)
```

We bumped libraries to 26.21.0, which uses BigQuery 2.31.0, which depends on this version (see https://mvnrepository.com/artifact/com.google.cloud/google-cloud-bigquery/2.31.0).

Ideally we would rely on a BOM for this, but it seems that `libraries-bom` doesn't bring it -- so this is more of a short term fix to avoid error above.

### CODE REVIEW

**Comment by bvolpato** [comment]
FYI @lostluck, this is important to get in before cutting 2.50.0

**Comment by bvolpato** [comment]
retest this please

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
Run Python_Integration PreCommit

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Thanks!

Other than bigquery, we may need to go through the client lib of `rev-202x` versions once

**Comment by bvolpato** [comment]
Makes sense, I just noticed this error after running all Templates. But we could (and are in this case) missing coverage for sure, I can take a better look and bump others to match -- another PR is better?

**Comment by Abacn** [comment]
Thanks. I am also trying to examine the other apis dependencies at the same time, but yet find a good way to do it. What currently I get is that these api artifacts are keep bumping versions:

e.g.

https://repo1.maven.org/maven2/com/google/apis/google-api-services-pubsub/v1-rev20230529-2.0.0/

https://repo1.maven.org/maven2/com/google/apis/google-api-services-dataflow/v1b3-rev20230529-2.0.0/

but not yet find a way to confirm which version the bom eventually use

Another interesting find is that Beam actually does not depend on `google_cloud_bigquery`. Although a version is set here:
https://github.com/apache/beam/blob/76290b83c506e018255b9a8b164b339c1bee6137/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L666

it is not used in io-gcp, only used in test-utils and examples/tests (from code search)

```
// Try to keep version consistent with google_cloud_bigquery version in google_cloud_platform_libraries_bom
```

as we are doing for other libs that need attention when bump bom

**Comment by bvolpato** [comment]
Run Java_IOs_Direct PreCommit

**Review by Abacn — APPROVED** [review]

**Comment by Abacn** [comment]
Run Java_IOs_Direct PreCommit

**Comment by Abacn** [comment]
Run Java_GCP_IO_Direct PreCommit

**Pull request merged**
