### PR TITLE
Cherry picking PR #28618 into 2.51.0 (setting numShards for Python BigQuery xlang)

### PR DESCRIPTION
**Pull request by ahmedabu98**
Cherry picking PR #28618 into 2.51.0

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Dataflow PostCommit

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Direct PostCommit

**Comment by ahmedabu98** [comment]
R: @kennknowles

**Comment by ahmedabu98** [comment]
retest this please

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Direct PostCommit

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Dataflow PostCommit

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Direct PostCommit

**Comment by ahmedabu98** [comment]
Previous iteration of xlang direct GCP tests [failed](https://ci-beam.apache.org/job/beam_PostCommit_Python_Xlang_Gcp_Direct_PR/90/consoleFull) because it was running on another PR concurrently.. shows another occurrence of #27445

**Comment by Abacn** [comment]
fyi test passed on GitHub Action also: https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python_Xlang_Gcp_Direct.yml?query=event%3Aissue_comment

Though current phrase trigger on GitHub Action is not conveniently visible (we're investigating a solution)

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Dataflow PostCommit

**Comment by kennknowles** [comment]
`PreCommit Python Dataframes / Test Results (pull_request_target)` only has the option to re-run all jobs. I don't know what causes that but I'm afraid of causing flakiness by rerunning too much. WDYT? Is that the way to go? Is there a real problem? It didn't dump me to the console I was expecting to see in order to triage it.

**Comment by kennknowles** [comment]
Ah, I see the failures are still Fhir. Why is it running in the dataframes precommit? Well anyhow I will merge this cherrypick also. However, those jobs should be disabled until they are healthy.

**Pull request merged**
