### PR TITLE
[BEAM-12280] Upgrade Flink runner to Flink version 1.12.3

### PR DESCRIPTION
**Pull request by iemejia**
R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
Run Flink ValidatesRunner

**Review by ibzib — APPROVED** [review]
LGTM

**Pull request merged**
