### PR TITLE
HourlyTeamScore writes to a file

### PR DESCRIPTION
**Pull request by slykar**
@melap  The docs say the data is written to a BigQuery database. It's not what's in the code. The data is written to a text file.

### CODE REVIEW

**Comment by melap** [comment]
Thanks for the PR! I looked at this, and it looks like the Python code example writes to BigQuery, and the Java one writes to text files.  For now, we might have to tag the last part of that sentence as language dependent so it displays the appropriate one depending on language toggle. Our current solution at the word level isn't great unfortunately -- you'd need to use something like this:

<span class="language-java">text file</span><span class="language-py">Google BigQuery</span>

@davidcavazos is there a plan to update the code examples to be consistent?

**Comment by davidcavazos** [comment]
Sure, I can update it

**Comment by davidcavazos** [comment]
I tried changing it to use TextIO and it failed with errors about the windowing setup not being supported for TextIO. I then remembered that at the time of writing, we decided to use BigQuery for that reason, so it can't be updated until the product supports that feature.

Melissa's solution on dynamically changing the documentation text depending on the language seems to be the way to go for now. Please go ahead with that change.

**Comment by slykar** [comment]
@melap I've added another commit with the change you suggested after I saw @davidcavazos comment.

**Pull request merged**
