### PR TITLE
[WIP][BEAM-10670] Make SparkRunner opt-out for using an SDF powered Read transform.

### PR DESCRIPTION
**Pull request by lukecwik**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
Build python source distribution and wheels

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
Spark Runner Nexmark Tests

**Comment by lukecwik** [comment]
Run Spark ValidatesRunner

**Comment by lukecwik** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by lukecwik** [comment]
CC: @iemejia I got this passing all the tests but what is the state of streaming pipelines? I see that there is code for evaluating UnboundedSources but don't see any test coverage.

**Comment by lukecwik** [comment]
Run Spark Runner Nexmark Tests

**Comment by ibzib** [comment]
cc: @ibzib @annaqin418

**Comment by lukecwik** [comment]
@iemejia I have updated the code and added a `SparkProcessedKeyedElements` using `updateStateByKey` to evaluate a splittable DoFn. I based the logic off of the `SparkGroupAlsoByWindowViaWindowSet` logic. I also added some `SplittableDoFnTest`s and have been using `org.apache.beam.runners.spark.translation.streaming.SplittableDoFnTest#testPairWithIndexBasicUnbounded` as my base test to get it working. So far I am able to get output produced including having the splittable DoFn state saved and restored for the next round of execution. I do see most of output via the `LoggingDoFn` that I added to the test but the `PAssert` is failing because it doesn't see any of the output and it is also triggering too early as not all the output has been produced. Any suggestions as to what to take a look at?

**Comment by lukecwik** [comment]
@iemejia I figured out that the issue is that watermark holds aren't implemented for spark so the first batch completes which computes new watermarks so the watermark hold that was set by the splittable dofn implementation is ignored. This leads to timers being dropped and hence only some of the results being produced.

This is likely the cause for why the PAssert is dropping the elements that were produced as well but I haven't validated this yet.

**Comment by iemejia** [comment]
The phenomenon of microbatches producing results early I noticed it too in the past when trying to enable the Read.Unbounded tests. I could not understand why, and I thought it was probably due to some glitch in Spark implementation or us screwing their scheduling but I struggled to debug the issue properly.

> Since watermark holds don't seem to be implemented, does the GroupAlsoViaWindowSet hold back the watermark for elements that it currently has buffered?

Probably, at least that may explain some of the inconsistencies.

> Can you explain how the GlobalWatermarkHolder works, can I register anything as a sourceId?

In all honesty I am not so familiar with watermark handling on the Spark runner. I took a look at the GlobalWatermarkHolder class and tried to figure out but it was not really evident.

My impression is that the sourceId is aligned somehow with Spark's assigned streamId, but I might be misinterpreting it.
https://github.com/apache/spark/blob/13664434387e338a5029e73a4388943f34e3fc07/streaming/src/main/scala/org/apache/spark/streaming/scheduler/InputInfoTracker.scala#L30

I wish I could help more but that part of the code is also not so well documented. I doubt that the original authors of the code still remember the details but maybe they remember at least the intentions of `GlobalWatermarkHolder` and its use, and maybe if there were any open issues. Just in case :crossed_fingers: maybe: @amitsela @aviemzur @staslev

**Comment by lukecwik** [comment]
> The phenomenon of microbatches producing results early I noticed it too in the past when trying to enable the Read.Unbounded tests. I could not understand why, and I thought it was probably due to some glitch in Spark implementation or us screwing their scheduling but I struggled to debug the issue properly.
> 
> > Since watermark holds don't seem to be implemented, does the GroupAlsoViaWindowSet hold back the watermark for elements that it currently has buffered?
> 
> Probably, at least that may explain some of the inconsistencies. 

The Java based trigger implementation relies on this to produce correct results. Implementing this would like enable a bunch of streaming use cases.

> > Can you explain how the GlobalWatermarkHolder works, can I register anything as a sourceId?
> 
> In all honesty I am not so familiar with watermark handling on the Spark runner. I took a look at the GlobalWatermarkHolder class and tried to figure out but it was not really evident.
> 
> My impression is that the sourceId is aligned somehow with Spark's assigned streamId, but I might be misinterpreting it.
> https://github.com/apache/spark/blob/13664434387e338a5029e73a4388943f34e3fc07/streaming/src/main/scala/org/apache/spark/streaming/scheduler/InputInfoTracker.scala#L30
> 
> I wish I could help more but that part of the code is also not so well documented. I doubt that the original authors of the code still remember the details but maybe they remember at least the intentions of `GlobalWatermarkHolder` and its use, and maybe if there were any open issues. Just in case 🤞 maybe: @amitsela @aviemzur @staslev

That would be great if someone could give guidance here.

**Comment by lukecwik** [comment]
@iemejia Since streaming is effectively broken due to lack of support for watermark holds. What do you think about enabling SDF for Spark and it only working in batch?

I'll see what I can do about watermark holds but decoupling the two would be convenient.

**Comment by iemejia** [comment]
> @iemejia Since streaming is effectively broken due to lack of support for watermark holds. What do you think about enabling SDF for Spark and it only working in batch?

Can you be more explicit on what you mean on 'it only working in batch'? Isn't it the current case for Bounded SDF?
Or what you mean is to have now Unbounded Reads translated using SDF still with the same level of functionality than the old translation (no holds)?

**Comment by lukecwik** [comment]
> > @iemejia Since streaming is effectively broken due to lack of support for watermark holds. What do you think about enabling SDF for Spark and it only working in batch?
> 
> Can you be more explicit on what you mean on 'it only working in batch'? Isn't it the current case for Bounded SDF?
> Or what you mean is to have now Unbounded Reads translated using SDF still with the same level of functionality than the old translation (no holds)?

BoundedSource converted to an SDF will work just as well as the current BoundedSource implementation since they don't rely on watermark holds. The current implementation of UnboundedSource and the new implementation using UnboundedSource as an SDF both set the watermark but nothing honors it since there is lack of support for watermark holds.

**Comment by iemejia** [comment]
I see, so it is the full switch from Read.Bounded/Unbounded to SDF by default. Can you get this one green so we can test it and then merge it, I would like to see if there is some perf impact, and probably that we document how to get the previous `Unbounded` translation in case any existing users find any difference.

If I understood correctly you might intend to tackle watermark holds in the 'future'? Just for learning curiosity I assume this will be done in `SparkProcessKeyedElements` for Gbk/Stateful translation, might this need some extra changes? asking just because I am reading the translation of Portable Streaming runner and I see watermarks are taken into account from Impulse so I was wondering if something was missing here or if this is done in a different place maybe in core.

**Comment by lukecwik** [comment]
> I see, so it is the full switch from Read.Bounded/Unbounded to SDF by default. Can you get this one green so we can test it and then merge it, I would like to see if there is some perf impact, and probably that we document how to get the previous `Unbounded` translation in case any existing users find any difference.
> 
> If I understood correctly you might intend to tackle watermark holds in the 'future'? Just for learning curiosity I assume this will be done in `SparkProcessKeyedElements` for Gbk/Stateful translation, might this need some extra changes? asking just because I am reading the translation of Portable Streaming runner and I see watermarks are taken into account from Impulse so I was wondering if something was missing here or if this is done in a different place maybe in core.

I'll be going on paternity soon so I'll try to see what I can get working with the GlobalWatermarkHolder implementation that exists. I think we should be able to use arbitrary ids in it it just might be really slow since the readers/writers should really care about their upstream watermarks (main and side input) so having a global broadcast seems less then desirable.

**Comment by iemejia** [comment]
Excellent idea to break the PR into little ones, first one merged. waiting for the next!

**Pull request closed without merging**
