### PR TITLE
[BEAM-6339] Add paddedcell fix to spotlessJava rules.

### PR DESCRIPTION
**Pull request by HuangLED**
SpotlessJava fails to work when certain format issue exists in new code. 

Plugin has official page refering to this issue with a fix, details see: https://github.com/diffplug/spotless/blob/master/PADDEDCELL.md

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by HuangLED** [comment]
R: @swegner

**Comment by kennknowles** [comment]
What was the actual issue? It looks like paddedCell has bugs, itself. It seems that we are OK at current head.

**Comment by HuangLED** [comment]
> What was the actual issue? It looks like paddedCell has bugs, itself. It seems that we are OK at current head.

oops...   The story was:  I was testing whether our tools were able to catch code style violations as they claim.   I thus intentionally created different violations, for verification purpose. 

The issue happened with those intentional changes. That is, instead of reporting those actual, although intentional, violations, the build system was failing.  I didn't keep my changes, thus will need to check which exactly violation (something related to class level javadoc). 

Back then, I thought it would be an improvement, which is even though minor, but good to have, thus requested this PR since I was already on it. 

Is this causing issue? Do you prefer us to revert this PR?

**Comment by HuangLED** [comment]
Saw you comment in the other thread. Got it.  Thanks!

**Pull request merged**
