### PR TITLE
Use parent pom version of hadoop, move common deps into the hadoop parent pom

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
retest this please

(seeing if Jenkins will suck less now)

**Comment by dhalperi** [comment]
LGTM, please self-merge if green.

**Comment by iemejia** [comment]
retest this please

**Comment by dhalperi** [comment]
Any committer can kick the build manually at builds.apache.org

Try that and paste the link here?

**Comment by iemejia** [comment]
cool, didn't know that, nice !

**Comment by iemejia** [comment]
https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10079/

**Comment by iemejia** [comment]
Built passed so merging.

**Pull request closed without merging**
