### PR TITLE
Revert "Remove subprocess.PIPE usage by using a temp file"

### PR DESCRIPTION
**Pull request by chamikaramj**
Reverts apache/beam#22654

gRPC 1.48.1 has been released and released Beam is working without any issues. So we should not need to include this change in future releases.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @tvalentyn

**Review by tvalentyn — APPROVED** [review]

**Comment by chamikaramj** [comment]
Thanks!

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Python PreCommit seems very flaky and failing tests are completely unrelated to this clean revert. So merging this.

[apache_beam.io.gcp.bigquery_test.PipelineBasedStreamingInsertTest.test_batch_size_with_auto_sharding_0](https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/3112/testReport/junit/apache_beam.io.gcp.bigquery_test/PipelineBasedStreamingInsertTest/test_batch_size_with_auto_sharding_0/)
[apache_beam.runners.portability.fn_api_runner.fn_runner_test.FnApiRunnerTestWithDisabledCaching.test_batch_to_element_pardo](https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/3112/testReport/junit/apache_beam.runners.portability.fn_api_runner.fn_runner_test/FnApiRunnerTestWithDisabledCaching/test_batch_to_element_pardo/)

**Pull request merged**
