### PR TITLE
[BEAM-3153] Add TestClock to test

### PR DESCRIPTION
**Pull request by mariapython**
This was forgotten in https://github.com/apache/beam/pull/4425

### CODE REVIEW

**Comment by mariapython** [comment]
R: @aaltay

**Comment by mariapython** [comment]
cc: @charlesccychen, @robertwb

**Comment by mariapython** [comment]
@charlesccychen: it seems that part of the code is not exercised. Because yes, it passes all tests (you can try tox on master).

**Comment by mariapython** [comment]
That does fail on the precise line that will be fixed by this PR.
But nosetests apache_beam/transforms/trigger_test.py passes all tests.

**Comment by aaltay** [comment]
I meant, could you run `python setup.py test -s apache_beam.transforms.trigger_test.TranscriptTest` with this change, and see that it fixes the problem?

**Comment by mariapython** [comment]
Yes.

**Comment by aaltay** [comment]
LGTM, Thank you.

**Pull request merged**
