### PR TITLE
[BEAM-6439] Move Python Validates Runner Flink test to PreCommit

### PR DESCRIPTION
**Pull request by angoenka**
**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by angoenka** [comment]
Run Seed Job

**Comment by angoenka** [comment]
Run Python_VR PreCommit

**Comment by angoenka** [comment]
Run Python_VR_Flink PreCommit

**Comment by angoenka** [comment]
Run Python_VR_Flink PreCommit

**Comment by angoenka** [comment]
Can't test the job as beam1 is down and all runs are scheduled on beam1.

**Comment by angoenka** [comment]
Run Seed Job

**Comment by angoenka** [comment]
Run Seed Job

**Comment by angoenka** [comment]
Run Seed Job

**Comment by angoenka** [comment]
Run Seed Job

**Comment by angoenka** [comment]
Need to name job to Python_**PVR**_Flink as beam_PreCommit_Python_VR_Flink_Cron already existed. We can try deleting beam_PreCommit_Python_VR_Flink_Cron and then try to use Python_VR_Flink.
Successful run: https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Phrase/1/

**Comment by angoenka** [comment]
cc: @tweise @robertwb

**Comment by angoenka** [comment]
Ping: @tweise @robertwb

**Comment by angoenka** [comment]
Ping: @tweise @robertwb

**Comment by tweise** [comment]
`git grep 'beam_PostCommit_Python_VR_Flink'` - see earlier comment

**Comment by angoenka** [comment]
Now I see what you mean. Thanks!
Updated the PR comments and readme to remove reference for the old postcommit job.
But I would say that having these run available in post commit and visible in PR gave a lot of confidence in the system.

**Comment by tweise** [comment]
@angoenka it does not appear that the job actually runs in pre-commit.

https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Commit/

**Pull request merged**
