### PR TITLE
[BEAM-4046] decouple gradle project names and maven artifact ids

### PR DESCRIPTION
**Pull request by adude3141**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by adude3141** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by adude3141** [comment]
Run JavaPortabilityApi PreCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Website PreCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Python Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Python PreCommit

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner Java 11

**Comment by adude3141** [comment]
Run Dataflow Portability ExecutableStage ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Dataflow Portability ExecutableStage ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Java PreCommit

**Comment by adude3141** [comment]
Run Dataflow Portability ExecutableStage ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by kennknowles** [comment]
Wow, this is so much really detail intensive work. I love this.

**Comment by adude3141** [comment]
Run Dataflow Portability ExecutableStage ValidatesRunner

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow Portability ExecutableStage ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python Dataflow ValidatesContainer

**Comment by adude3141** [comment]
Run Apex ValidatesRunner

**Comment by adude3141** [comment]
Run Flink ValidatesRunner

**Comment by adude3141** [comment]
Run Gearpump ValidatesRunner

**Comment by adude3141** [comment]
Run Samza ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run SQL PostCommit

**Comment by adude3141** [comment]
Run Python PostCommit

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
Run Go PostCommit

**Comment by adude3141** [comment]
Run Java PortabilityApi PostCommit

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by adude3141** [comment]
Run Dataflow ValidatesRunner

**Comment by adude3141** [comment]
Run Python_PVR_Flink PreCommit

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Spark ValidatesRunner

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Hi, @kennknowles 

would you mind to have a look again? From my point of view, we could merge. Probably some issues will come up anyway which we will need to fix as soon we detect them.

Tried to trigger most tests. The current failing test `Java Flink PortableValidatesRunner Streaming Tests` seems to be already on master [1], so nothing I could fix here. And I would really prefer to not be forced to do a rebase again.

Thanks!

[1] https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/buildTimeTrend

**Comment by adude3141** [comment]
Thanks Kenn for your time. I ll merge this tonight and try to stay on for a few hours after just in case.

Happy to get this from my desk :)

**Comment by kennknowles** [comment]
Looks like `project("sdk:java:core")` style dependencies did not end up with the right pom deps. In `BeamModulePlugin` I think we hack our own pom. It could be that, or it could be artifact and group ids not being quite right.

**Comment by apilloud** [comment]
I can't find "Run Seed Job" anywhere in the comments here, which means this wasn't actually tested. Reports suggest it broke things. Should we revert?

**Comment by adude3141** [comment]
Wouldn't revert right now, unless it is blocking. Seems to be easy fixes.

**Pull request merged**
