### PR TITLE
[BEAM-9836] Exclude Spark runner from UsesKeyInParDo tests

### PR DESCRIPTION
**Pull request by rehmanmuradali**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by rehmanmuradali** [comment]
R: @reuvenlax 
CC: @iemejia

**Comment by reuvenlax** [comment]
run spark validatesrunner

**Comment by reuvenlax** [comment]
run flink validatesrunner

**Comment by reuvenlax** [comment]
run portable flink validatesrunner

**Comment by reuvenlax** [comment]
run flink portable validatesrunner

**Comment by reuvenlax** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by rehmanmuradali** [comment]
> Can we please rename that test Category to something more clear than `UsesKey`, that name is just too general.
> 
> Can you also please create a Jira issue to tackle the implementation of this functionality for the Spark runner, and eventually self assign it if you intend to work on it.

**Comment by rehmanmuradali** [comment]
> Can we please rename that test Category to something more clear than `UsesKey`, that name is just too general.
> 
> Can you also please create a Jira issue to tackle the implementation of this functionality for the Spark runner, and eventually self assign it if you intend to work on it.

Jira filed here: https://issues.apache.org/jira/browse/BEAM-9850

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by rehmanmuradali** [comment]
> Can we please rename that test Category to something more clear than `UsesKey`, that name is just too general.
> 
> Can you also please create a Jira issue to tackle the implementation of this functionality for the Spark runner, and eventually self assign it if you intend to work on it.

@iemejia I suggest `UsesKeyParameterInParDo`.

**Comment by iemejia** [comment]
Is this only used for Timers? If so what about `UsesKeyInTimers` or `UsesKeyTimers`.

**Comment by rehmanmuradali** [comment]
> Is this only used for Timers? If so what about `UsesKeyInTimers` or `UsesKeyTimers`.

@iemejia  I think `Key` also makes sense in `OnWindowExpiration`

**Comment by reuvenlax** [comment]
Key also makes sense in OnWindowExpiration, and it might make sense in processElements as well. However for test exclusion categories we can create overly-specific category names.

**Comment by iemejia** [comment]
I see, thanks for the info @rehmanmuradali and @reuvenlax.

It seems this is only for `ParDo`, my point here is not to be annoying it is that I can imagine in the future someone annotating their tests with `UsesKey` just because the tests use a Key (like in KV) and I want to prevent this. What about naming it `UsesKeyInParDo` ?

Also it seems then that the current documentation for the class is not ok too, can you please also mention of the `OnWindowExpiration` and `ProcessElement` case.

```java
/**
 * Category tag for validation tests which use key. Tests tagged with {@link UsesKey} should be run
 * for runners which support key parameter in {@link OnTimer}.
 */
```

Thanks

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Merged manually, closing now.

**Pull request closed without merging**
