### PR TITLE
[BEAM-6558] Add IWYU plugin, activate for Beam SQL, fix errors

### PR DESCRIPTION
**Pull request by kennknowles**
Beam SQL was successfully compiling and passing tests even though it had a totally straightforward compile-time dependency on commons-codec, which it did not declare.

I had thought that Gradle made this issue a thing of the past, but it is not so. This adds the capability that we got from `mvn dependency:analyze` plugin. It found the known error and a couple other issues, which may or may not be spurious.

This needs to be cherrypicked for 2.10.0 as Beam SQL was nonfunctional for 2.9.0. We can advise on a workaround to simply add the necessary dependency. We also need an end-to-end test that will ensure our shipped artifact works for users.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by amaliujia** [comment]
If `commons-codec` was not declared, where did BeamSQL find it and use it to pass tests? Was that because one or more of BeamSQL's dependencies include ``commons-codec` in some ways?

**Comment by kanterov** [comment]
I didn't dig deep, but I see a similar problem with `ClassNotFoundException: javax.annotation.Nullable` using new `DefaultSchema` providers that traverse class methods using reflection and check for annotations. My solution to the problem was adding extra jar to the classpath. 

I'm wondering if it's the same kind of problem as we have with `commons-codec` in Beam SQL?

**Comment by nickpan47** [comment]
@kennknowles liked the idea to add end-to-end tests. I noticed that there are some user example project such as word-count-example that are generated as part of the build. It would be nice to add some SQL example projects their as well, and make sure the release validation process actually builds and runs those example applications. I can create a JIRA to add BeamSQL example project, if it is not there yet.

**Comment by kennknowles** [comment]
@amaliujia yes, one of the dependencies (actually lots of them) depend on commons-codec. Since they probably depend on it in `compile` scope, which means it could be on the API surface, they are put on the classpath during compilation, rather than just at runtime.

**Comment by kennknowles** [comment]
OK, got past legit failures. Deflaking time.

**Comment by kennknowles** [comment]
Run java precommit

**Pull request merged**
