### PR TITLE
Change dataflow Job log from info to debug

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @chamikaramj 
CC: @aaltay

**Comment by chamikaramj** [comment]
LGTM

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
cc: @jasonkuster Do you know why Jenkins didn't trigger here ?

**Comment by jasonkuster** [comment]
Jenkins had a hiccup over the weekend as I understand it; watching new PRs to see how they behave.

**Pull request closed without merging**
