### PR TITLE
[BEAM-1897] Remove Sink in favor of FileBasedSink

### PR DESCRIPTION
**Pull request by reuvenlax**
The Sink base class has turned out to be mostly useful for file sinks. Remove Sink, and replace it with FileBasedSink.

R: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
The breakage here is in `master`. Check back in a bit.

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
Merged to master

**Comment by kennknowles** [comment]
You'll also need to rebase yet again. You might as well squash into fewer commits. Maybe just one, given the situation, but maybe there are a couple that make sense.

**Comment by kennknowles** [comment]
Checked offline and I am happy. Noting for posterity that the extremely high line count is spurious. Please resolve conflicts and run ValidatesRunner suites and then I'll be about ready to merge.

This blocks stable release, so we need to get in the large scale migration then iterate on the API details. We already needed to do this - this PR does not create more blocking work, but just blocks work we already needed to do.

**Comment by reuvenlax** [comment]
Rebased and squashed

**Comment by kennknowles** [comment]
Run Flink ValidatesRunner

**Comment by kennknowles** [comment]
Run Dataflow ValidatesRunner

**Comment by kennknowles** [comment]
Run Flink ValidatesRunner

**Comment by kennknowles** [comment]
Run Dataflow ValidatesRunner

**Comment by kennknowles** [comment]
Run Apex ValidatesRunner

**Comment by kennknowles** [comment]
Run Spark ValidatesRunner

**Comment by kennknowles** [comment]
Nice. I'll merge shortly.

**Comment by nguyenvietyen** [comment]
I have my own ElasticSearch sink that relied on Sink to function. Now Sink being deprecated, what's the current intended approach for custom sinks?

**Comment by kennknowles** [comment]
This is a good thing to bring up on dev@beam.apache.org so that the whole community can be part of the conversation. I'm sure everyone will be interested in how you use the `Sink` design pattern.

I will give a quick answer right here: `Write.to(Sink)` was never a primitive but just a design pattern. The design pattern did not work correctly with unbounded data, windowing, or triggers. We found many connectors where it just wasn't the right design anyhow. And when it _was_ used, most of its capabilities were left blank most of the time. So we decided to inline it and do only the parts needed for different IO connectors.

The recommendation now is to build the composite transform directly. You may notice that most of the IO connectors in the Beam codebase never used `Sink`, because it just was not helpful. There is a longer IO authoring guide at https://beam.apache.org/documentation/io/authoring-overview/, which still needs update for this change.

**Pull request closed without merging**
