### PR TITLE
[BEAM-1328] DataflowRunner: Send WindowingStrategy as proto

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @dhalperi I think you have some context on this. About to run the `ValidatesRunner` suite.

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Run Dataflow RunnableOnService

**Comment by kennknowles** [comment]
Fixed deps and pushed. I'll check it again later.

**Comment by dhalperi** [comment]
Weird -- those tests are looking for a function that only exists in proto 3.2.0, but I am pretty sure we only use proto 3.1.0. Looking around a bit, asynchronously -- feel free to investigate on your own.

**Comment by dhalperi** [comment]
I lied, the function has been there since 3.0.0: https://github.com/google/protobuf/commit/9086d9643903c608ab015b0b7d903547a4e7b6f3

hmmmm

**Comment by kennknowles** [comment]
Curious circumstance - it compiles, but has a runtime error at construction time. I suspect something to do with the examples' configuration. Checking.

**Comment by kennknowles** [comment]
I haven't dealt with proto library pain so much yet, but I do see that we've got protobuf-lite 3.0.1, protobuf-java-3.1.0, and protobuf-utils-3.0.0, and a mesos shaded-protobuf-0.21.1 (hopefully actually relocated) on the runtime classpath. I am guessing these are not pairwise disjoint libraries.

**Comment by davorbonaci** [comment]
Looks obsolete. Close?

**Comment by kennknowles** [comment]
Yup, looks like it was duped to #2495

**Pull request closed without merging**
