### PR TITLE
Move gradle-spotless plugin to buildscript for offline build

### PR DESCRIPTION
**Pull request by markflyhigh**
Dependency of spotless plugin is redirected from Gradle repository to Maven central which makes offline dependency hard to manage. Move this plugin to buildscript makes dependency structure simpler and easy for offline build.

Also add ":buildSrc" to `settings.gradle` in order to run spotless plugin from root.

R: @lukecwik 
cc: @kennknowles 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
This moves from the non-deprecated way of setting up a plugin to the deprecated way of setting up a plugin. Is this because it needs to pick up extra repos?

**Comment by lukecwik** [comment]
No, its because it requires importing additional maven dependencies into Google that aren't needed.
These artifacts don't have licenses attached to them, e.g.: https://mvnrepository.com/artifact/com.diffplug.gradle.spotless/com.diffplug.gradle.spotless.gradle.plugin/3.6.0

**Comment by kennknowles** [comment]
Ugh, no licenses? Derp.

**Comment by lukecwik** [comment]
I opened up https://discuss.gradle.org/t/what-is-the-license-of-a-gradle-plugins-meta-plugin-pom-xml/27610 to ask for a resolution for the license issue for the plugins meta-plugin pom.xml.

**Pull request merged**
