### PR TITLE
[BEAM-9476] KinesisIO retry LimitExceededException

### PR DESCRIPTION
**Pull request by ameihm0912**
During Kinesis stream setup DescribeStream is used. This API call has
quota limits that can become very problematic when attempting to
configure multiple Kinesis streams in the same AWS account.

This change modifies the caller of describeStream (listShards) such that
transient failures are retried up to 10 times with a one second delay in
between each try (the time used to assess the quota), at which point if
it has still failed the exception is thrown.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Thank you for contribution! Have you seen this PR #9765 and a discussion over this topic there? I think it tries to solve the similar problem, if I'm not mistaken.

**Comment by ameihm0912** [comment]
> Thank you for contribution! Have you seen this PR #9765 and a discussion over this topic there? I think it tries to solve the similar problem, if I'm not mistaken.

@aromanenko-dev thank you for the response.

I had a quick look at the referenced PR and I suspect that may be solving a different issue, that being transient errors associated with hitting read throughput rate limiting.

Some additional context on the issue we are running into: in our case, we have a large number of Kinesis streams in a single account. By default, Kinesis `DescribeStream` calls are limited to 10 per second per account. So we easily run into this during graph construction as we have a large number of streams that need to be setup in the same pipeline. This results in a `RuntimeException` being thrown by the pipeline. So, our issue is happening during stream initialization right off the bat, where as the referenced PR I believe is more to address issues that are occurring while reading from an already initialized stream.

It is possible I am misinterpreting something in the other PR however.

**Comment by aromanenko-dev** [comment]
@ameihm0912 Yes, I see your point and this is actually a different but similar issue imo. 
One of the option to overcome this could be using internal AWS `RetryPolicy` as I showed in [this comment](https://github.com/apache/beam/pull/9765#issuecomment-562136257) - in this case you just need to create new `AWSClientsProvider`, based on current `BasicKinesisProvider`, and override the method `getKinesisClient()` with configured custom `RetryPolicy` and `BackoffStrategy`. Then set this new `AWSClientsProvider` by `withAWSClientsProvider(AWSClientsProvider)`. Though, be aware that this policy will be applied to all other `AmazonKinesis ` requests as well afaik.

**Comment by ameihm0912** [comment]
@aromanenko-dev interesting, that's definitely an option but as you mention I am unclear on what the implications of applying a global retry/backoff policy to all API requests would be. For this particular PR I tried to just focus on the `DescribeStream` initialization issue itself, but am happy to revisit the approach here if you prefer.

**Comment by aromanenko-dev** [comment]
@ameihm0912 Could you use Beam `FluentBackoff` instead own implementation? I believe it should simplify the code.

**Comment by aromanenko-dev** [comment]
Also, please, create a Jira for this feature and name PR/commits using Jira ID as a prefix, `[BEAM-1234]` where `1234` is Jira ID (see [Contribution Guide](https://beam.apache.org/contribute/#make-your-change) for details).

**Comment by ameihm0912** [comment]
@aromanenko-dev updated to use `FluentBackoff` and references to Jira issue added

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
@ameihm0912 kindly pinging to prevent this PR get staled

**Comment by ameihm0912** [comment]
> @ameihm0912 kindly pinging to prevent this PR get staled

@aromanenko-dev apologies for the delay here, I'll try to get that test added this week.

**Comment by aromanenko-dev** [comment]
@ameihm0912 Not a problem, thank you for keep working on this!

**Comment by ameihm0912** [comment]
@aromanenko-dev I have added a couple test cases to verify both the retry behavior and the retry limit behavior to `KinesisMockReadTest`. When you have a moment please let me know if that is OK.

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
retest this please

**Comment by aromanenko-dev** [comment]
@ameihm0912 Thanks, all is fine for me except that Spotless fails. Please, run `gradlew spotlessApply` (or more precise `./gradlew :sdks:java:io:kinesis:spotlessApply`) to fix these violations and `./gradlew :sdks:java:io:kinesis:check` before pushing to make sure that all tests passed. 
Once it will be fixed, I think we can merge it.

**Comment by ameihm0912** [comment]
@aromanenko-dev this should be fixed up now

**Comment by aromanenko-dev** [comment]
Retest this please

**Comment by aromanenko-dev** [comment]
Retest this please

**Comment by aromanenko-dev** [comment]
Retest this please

**Comment by ameihm0912** [comment]
@aromanenko-dev I'm not too sure why the tests are indicated as still failing here, they seemed to pass for me locally. I had a look at the Jenkins output as well and don't see anything obvious in there.

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
Run JavaPortabilityApi PreCommit

**Comment by aromanenko-dev** [comment]
@ameihm0912 I think it's not related to your changes, so I just rerun this tests

**Comment by ameihm0912** [comment]
Looks like we still had a failure; if you'd like me to rebase this off current master let me know, I'm not sure if maybe that might help?

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Pull request merged**
