### PR TITLE
[BEAM-14004] fix(mongodb): Ignore error `Command not supported` because of CosmosDB not support `splitKeys` command

### PR DESCRIPTION
**Pull request by Miuler**
fix(mongodb): Ignore error `Command not supported` because of CosmosDB not support `splitKeys` command

Reviewed-by: @jbonofre
Refs: # (pull request) [BEAM-14004] (jira)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Miuler** [comment]
@jbonofre , I'm create pull #16972 with 2.36.1 version.

**Comment by chamikaramj** [comment]
Can you revert the release version related changes ? Cutting a patch version requires a separate process an I don't think it's worth it just for this change. Beam releases minor versions approximately every six weeks so this should be picked up by the next minor release.

**Comment by Miuler** [comment]
> Can you revert the release version related changes ? Cutting a patch version requires a separate process an I don't think it's worth it just for this change. Beam releases minor versions approximately every six weeks so this should be picked up by the next minor release.

Ok, but where do I put this?

## Bugfixes

* Ignore error `Command not supported` because of CosmosDB not support `splitKeys` command in Java SDK ([BEAM-14004](https://issues.apache.org/jira/browse/BEAM-14004)).

**Comment by kileys** [comment]
You can put it under the bug fixes for 2.39.0

https://github.com/apache/beam/blob/master/CHANGES.md#2390---unreleased

**Comment by aaltay** [comment]
Run Java PreCommit

**Comment by aaltay** [comment]
What is the next step on this PR?

**Comment by aaltay** [comment]
Could we remove the changes to the changes.md and merge the rest (if that part is reviewed & tested) ?

**Comment by Miuler** [comment]
@chamikaramj @kileys @aaltay , I'm closing this pull and open the new PR #17511 pointing the version 2.39 (master)

**Pull request closed without merging**
