### PR TITLE
Install Beam from wheels in Dependency Compat Test Suite.

### PR DESCRIPTION
**Pull request by tvalentyn**
Dependency postcommit suite runs multiple small suites of unit tests. Installing beam takes 3-4 minutes to build a wheel. Using a wheel to install beam should speed up the suite, since the wheel will be built once.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Currently testing this on https://github.com/apache/beam/actions/runs/9101961896

**Comment by Abacn** [comment]
if I remember correctly, useWheelDistribution is only effective for Dataflow test (it changes sdk_location pipeline option to wheel). However these tests are running on direct runner. This change alone is a no-op yet?

**Comment by tvalentyn** [comment]
I thought so too, but i looked closer in https://github.com/apache/beam/blob/6cb30cc5c86ce394ca558c431af55a935b8d9d6b/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L3078C121-L3078C136 
and it does make a difference for tox . Note that in https://github.com/apache/beam/actions/runs/9101961896 , the runtime is 1hr 5 min, even though I added a bit more tests to that suite (see: https://github.com/apache/beam/pull/31305). On the other hand, exact same suite without this change times out after 2hrs.

**Comment by tvalentyn** [comment]
> exact same suite without this change times out after 2hrs: [apache/beam/actions/runs/9101921047/job/25020312963?pr=31305](https://github.com/apache/beam/actions/runs/9101921047/job/25020312963?pr=31305).

reminder that due to nature of GHA permissions, the signal on the PR #31305 itself is not accurate, even though it includes a commit from this PR, GHA still runs long because it hasn't taken effect yet.

**Comment by Abacn** [comment]
> I thought so too, but after you dug up the PR for me (thanks!) that added this option, i looked closer in https://github.com/apache/beam/blob/6cb30cc5c86ce394ca558c431af55a935b8d9d6b/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L3078C121-L3078C136 and it does make a difference for tox . Note that in https://github.com/apache/beam/actions/runs/9101961896 , the runtime is 1hr 5 min, even though I added a bit more tests to that suite (see: #31305). On the other hand, exact same suite without this change times out after 2hrs: https://github.com/apache/beam/actions/runs/9101921047/job/25020312963?pr=31305.

Oh, I see, yeah, the functionality is added in #28385 making useWheelDistribution working for tox

**Review by Abacn — APPROVED** [review]

**Pull request merged**
