### PR TITLE
Handle a user whose account was deleted.

### PR DESCRIPTION
**Pull request by tvalentyn**
One of PR Bot workflows is failing because the  PR #29347 has a comment from a now-deleted account.

Attempting to fix this in this PR.

https://github.com/apache/beam/actions/runs/7602366264/job/20702841060

```
Processing PR 29347
/runner/_work/beam/beam/scripts/ci/pr-bot/lib/updateReviewers.js:93
            if (comment.user.login &&
                             ^

TypeError: Cannot read properties of null (reading 'login')
    at /runner/_work/beam/beam/scripts/ci/pr-bot/lib/updateReviewers.js:93:30
    at Generator.next (<anonymous>)
    at fulfilled (/runner/_work/beam/beam/scripts/ci/pr-bot/lib/updateReviewers.js:22:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Process completed with exit code 1.
```

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @Abacn

**Comment by tvalentyn** [comment]
Test (in flight): https://github.com/apache/beam/actions/runs/7750207100

**Comment by Abacn** [comment]
CC: @shunping

**Review by Abacn — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
