### PR TITLE
[BEAM-2610] upgrade to version 2.2.0

### PR DESCRIPTION
**Pull request by XuMingmin**
placeholder for 2nd PR, may need update after #3553

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @takidau @xumingming

**Comment by takidau** [comment]
Okay, seems like you should be able to branch off the other one and actually find and fix any errors that you'll run into, but that's okay. I'll go ahead and merge the other one now.

**Comment by takidau** [comment]
retest this please

**Comment by XuMingmin** [comment]
rebased, local build pass, let's see the result of CI build.

**Comment by XuMingmin** [comment]
retest this please

**Comment by takidau** [comment]
LGTM. Merging.

**Comment by takidau** [comment]
Merged, thank you!

**Pull request merged**
