### PR TITLE
[Website] fix navbar footer overlap

### LINKED ISSUE #22698: [Bug]: Navigation bar overlaps footer when there is little information on the page
### What happened?

Steps to reproduce:
1. Open the website [page](https://beam.apache.org/documentation/sdks/python-dependencies/)
2. Scroll to the bottom of the page
3. Look at the navigation bar

Actual result: Navigation bar overlaps footer when there is little information on the page
Expected result: Navigation bar doesn't overlap footer when there is little information on the page

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22698
- change styles of main content and left menu. Left navbar is no longer positioned absolute, it's in the flow with main content, so left menu doesn't overlap footer in case when content of the page is too short and left menu contains too many bullet points
- limit width of playground, so it fits 
------------------------
before:
before_navbar
after:
after_navbar
before:
before_playground
after:
after_playground
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please help with review of PR?

**Comment by bullet03** [comment]
> The changes look good, but I can't repro the original problem at https://beam.apache.org/documentation/sdks/python-dependencies/. No sure why... But thanks for working on this!

Thank you. Not sure exactly, but the reason might be that the screen resolution was too narrow or too wide (then the bug can't be reporoduced) . Here is my resolution with bug being reproduced: 1200*1020px

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please help with merge? PR was approved.

**Review by aromanenko-dev — APPROVED** [review]
Thanks!

**Comment by bullet03** [comment]
@aromanenko-dev, sorry for bothering.
The PR was merged 3 days ago, but changes are still not present on prod https://beam.apache.org/documentation/sdks/python-dependencies/. Could you kindly help me with the issue?

**Comment by aromanenko-dev** [comment]
@bullet03 It looks that there is an issue with running [beam_PostCommit_Website_Publish](https://ci-beam.apache.org/job/beam_PostCommit_Website_Publish/) job that publishes Beam website into asf-site branch for hosting. Let me find out the reason and fix it.

**Comment by aromanenko-dev** [comment]
@bullet03 Jenkins job issue is resolved. So, do you see your website changes published now?

**Comment by bullet03** [comment]
> @bullet03 Jenkins job issue is resolved. So, do you see your website changes published now?

yes, it's perfect, Thank you so much!

**Pull request merged**
