### PR TITLE
Revert "Make GCP OAuth scopes configurable via pipeline options."

### PR DESCRIPTION
**Pull request by AnandInguva**
Reverts apache/beam#23644

### CODE REVIEW

**Comment by AnandInguva** [comment]
Run Python 3.7 PostCommit

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Comment by AnandInguva** [comment]
Run Python 3.8 PostCommit

**Comment by lukecwik** [comment]
Note that I filed https://github.com/apache/beam/issues/23676 for the failure

**Comment by lukecwik** [comment]
I believe I have a forward fix in https://github.com/apache/beam/pull/23677, waiting on postcommit to ensure that it passes.

**Comment by lukecwik** [comment]
https://github.com/apache/beam/pull/23677 resolved the problem

**Pull request closed without merging**
