### PR TITLE
use strimzi kafka on beam_utility cluster

### LINKED ISSUE #30526: The PerformanceTests xlang KafkaIO Python job is flaky
The PerformanceTests xlang KafkaIO Python is failing over 50% of the time 
Please visit https://github.com/apache/beam/actions/workflows/beam_PerformanceTests_xlang_KafkaIO_Python.yml?query=is%3Afailure+branch%3Amaster to see the logs.

### PR DESCRIPTION
**Pull request by volatilemolotov**
Use strimzi kafka for PerformanceTests xlang KafkaIO Python

Fixes #30526
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
thanks. Let me duplicate this branch and run the workflow once

**Comment by Abacn** [comment]
https://github.com/apache/beam/actions/runs/8696844369/job/23850939058

There is error

```
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
kafka.kafka.strimzi.io/beam-testing-cluster unchanged
Error from server (NotFound): kafkas.kafka.strimzi.io "beam-testing-cluster" not found
Error: Process completed with exit code 1.
```
Looks like it needs to setup a persistent cluster? Can we setup cluster if not exist, so the workflow can run with either cluster exist or not.

nice if can resolve the deprecated API also

**Comment by volatilemolotov** [comment]
> https://github.com/apache/beam/actions/runs/8696844369/job/23850939058
> 
> There is error
> 
> ```
> # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> kafka.kafka.strimzi.io/beam-testing-cluster unchanged
> Error from server (NotFound): kafkas.kafka.strimzi.io "beam-testing-cluster" not found
> Error: Process completed with exit code 1.
> ```
> 
> Looks like it needs to setup a persistent cluster? Can we setup cluster if not exist, so the workflow can run with either cluster exist or not.
> 
> nice if can resolve the deprecated API also

Ill check it out not sure why it does not work

**Comment by Abacn** [comment]
waiting on author

**Comment by volatilemolotov** [comment]
> > https://github.com/apache/beam/actions/runs/8696844369/job/23850939058
> > There is error
> > ```
> > # Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
> > kafka.kafka.strimzi.io/beam-testing-cluster unchanged
> > Error from server (NotFound): kafkas.kafka.strimzi.io "beam-testing-cluster" not found
> > Error: Process completed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Looks like it needs to setup a persistent cluster? Can we setup cluster if not exist, so the workflow can run with either cluster exist or not.
> > nice if can resolve the deprecated API also
> 
> Ill check it out not sure why it does not work

This should be fixed now. Issue was that the kustomization files were specifying the namespace which has been fixed since

**Review by Abacn — APPROVED** [review]
thanks!

**Pull request merged**
