### PR TITLE
[BEAM-1251] Revert #5887 to unbreak Python PostCommit

### PR DESCRIPTION
**Pull request by charlesccychen**
This change reverts #5887 to fix issues with the Python PostCommit.  I will take care of undoing this rollback after an appropriate fix.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @angoenka

**Comment by charlesccychen** [comment]
Run Python PostCommit

**Comment by angoenka** [comment]
Run Python Dataflow ValidatesRunner

**Comment by charlesccychen** [comment]
Tests pass; merging.

**Pull request merged**
