### PR TITLE
[BEAM-4393]: Copy root repo's LICENSE & NOTICE into shadowJar

### PR DESCRIPTION
**Pull request by boyuanzz**
r: @kennknowles 
cc: @apilloud

### CODE REVIEW

**Comment by apilloud** [comment]
LGTM! I verified that this fixes BEAM-4393.

Only one question: should this go in jar instead of shadowJar?

**Comment by boyuanzz** [comment]
Hey @apilloud , my understanding so far is, we use shadowJar to rewrite Jar. How do you feel like? @lukecwik

**Comment by apilloud** [comment]
I believe we run the jar rule to build a jar with only our code, then we run the shadowJar rule to bundle that jar with third party code. This only needs to be in shadowJar, but that leaves our code in jar without a LICENSE file.

**Comment by kennknowles** [comment]
That seems wrong. The shadowJar is the real thing and the "normal" jar is just an intermediate calculation.

**Comment by boyuanzz** [comment]
I didn't find any Jar{} closure so far in https://github.com/apache/beam/blob/master/build_rules.gradle, which means, we possibly use the default configuration. I'm not sure whether we need LICENSE in Jar.

**Comment by kennknowles** [comment]
Yea, OK. I didn't mean this PR is wrong. It seems this PR does put the LICENSE in the actual thing we want to ship to users. I guess the rest has to do with the release process.

**Comment by kennknowles** [comment]
Merging in the interest of moving things slightly better. _If_ our current release process is mostly right, _then_ this PR fixes it.

**Pull request merged**
