### PR TITLE
[BEAM-1265] Fix PValue input in _PubSubReadEvaluator

### PR DESCRIPTION
**Pull request by charlesccychen**
This incorporates @davidcavazos' change proposed in #3483.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM

**Comment by aaltay** [comment]
I will merge after the tests pass.

**Comment by aaltay** [comment]
Merged. @charlesccychen  Could you send a PR to cherry pick it to the release branch?

**Comment by aaltay** [comment]
Ignore the previous comment. CP PR: https://github.com/apache/beam/pull/3504

**Pull request closed without merging**
