### PR TITLE
[BEAM-2170] A few fixes to PubsubIO coders

### PR DESCRIPTION
**Pull request by jkff**
R: @reuvenlax

### CODE REVIEW

**Comment by jkff** [comment]
Actually need a little bit more than this - PubsubMessagePayloadOnlyCoder should be able to handle non-whole-stream contexts. Testing..

**Comment by jkff** [comment]
PTAL. I verified this stuff manually against local Dataflow in a more rigorous test that involves using / not using attributes, and involves forcing / not forcing the encoding of the messages via reshuffle (unfortunately I can't think of a way to quickly add proper TestPipeline unit tests for reading from Pubsub...).

**Comment by jkff** [comment]
Alternatively
R: @lukecwik 

since Reuven is at GCP Next.

**Comment by lukecwik** [comment]
R: @davorbonaci

**Pull request closed without merging**
