### PR TITLE
[BEAM-1491]Identify HADOOP_CONF_DIR(or YARN_CONF_DIR) environment variables when read/write HDFS file

### PR DESCRIPTION
**Pull request by 397090770**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by 397090770** [comment]
R: @ssisk @davorbonaci can you please review my PR? thank you.

**Comment by lukecwik** [comment]
CC: @lukecwik

**Comment by lukecwik** [comment]
HDFSFileSource/HDFSFileSink is to be deprecated and being replaced with a HadoopFileSystem which can be used with all file based sources and sinks like TextIO, AvroIO, etc...

Once #2762 is merged, please rebase on top of apache/master and add your logic to the ConfigurationLocator found within HadoopFileSystemOptions:
https://github.com/apache/beam/pull/2762/files#diff-6365d505a27aadc172e5efde96e6e541

**Comment by lukecwik** [comment]
#2762 has been merged.

**Pull request closed without merging**
