### PR TITLE
[8229] Revert "[7746] Create a more user friendly external transform API"

### PR DESCRIPTION
**Pull request by aaltay**
Reverts apache/beam#9098

Py 3.7 tests are failing with a syntax error.

### CODE REVIEW

**Comment by aaltay** [comment]
R: @chadrik @robertwb @udim

**Comment by chadrik** [comment]
I introduced some tests of a feature that makes use of PEP526 syntax changes introduced in python 3.6.  I got everything passing for the pre-commit tests but did not anticipate the post-commit problems.  I'll get those fixed up ASAP.

**Comment by chadrik** [comment]
Note that the _other_ solution to this is dropping support for python 3.5, but that's a bigger discussion.

**Comment by aaltay** [comment]
I was wrong in my JIRA issue. Py2 post commit is failing on py3.7 test. I thought py2 post commit was meant to skip these files.

**Comment by aaltay** [comment]
Run Portable_Python PreCommit

**Comment by aaltay** [comment]
Run Python 2 PostCommit

**Comment by aaltay** [comment]
Closing this. https://github.com/apache/beam/pull/9570 - addressed the test issues.

**Pull request closed without merging**
