### PR TITLE
[BEAM-13657] Sunset python 3.6

### PR DESCRIPTION
**Pull request by AnandInguva**
**Python 3.6 has reached EOL. Sunset Python3.6 support from Apache Beam**

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
Run Seed Job

**Comment by AnandInguva** [comment]
Run Portable_Python PreCommit

**Comment by AnandInguva** [comment]
Run Seed Job

**Comment by AnandInguva** [comment]
retest this please

**Comment by AnandInguva** [comment]
Run Seed Job

**Comment by AnandInguva** [comment]
retest this please

**Comment by AnandInguva** [comment]
Run Seed Job

**Comment by AnandInguva** [comment]
retest this please

**Comment by AnandInguva** [comment]
Run Seed Job

**Comment by AnandInguva** [comment]
retest this please

**Review by TheNeuralBit — APPROVED** [review]
Thanks @AnandInguva this looks good. Before we run the seed job (and drop the Python 3.6 PostCommits), can you send a message to dev@ to let people know there won't be any verification of Py 3.6?

**Comment by TheNeuralBit** [comment]
Please also resolve the conflict in tox.ini

**Review by bschoening — APPROVED** [review]
+1

**Comment by TheNeuralBit** [comment]
Run Portable_Python PreCommit

**Comment by TheNeuralBit** [comment]
Run SQL PreCommit

**Comment by TheNeuralBit** [comment]
Run SQL_Java17 PreCommit

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
Run Seed Job

**Comment by TheNeuralBit** [comment]
Run CommunityMetrics PreCommit

**Comment by TheNeuralBit** [comment]
Turns out you can't run seed job if the author of the PR is not a committer. I cloned your PR in #17307 to run the seed job there.

**Comment by ibzib** [comment]
ok to test

**Comment by ibzib** [comment]
run seed job

**Comment by TheNeuralBit** [comment]
Run Portable_Python PreCommit

**Comment by TheNeuralBit** [comment]
CommunityMetrics is perma-red: BEAM-14017

**Comment by TheNeuralBit** [comment]
Run GoPortable PreCommit

**Comment by TheNeuralBit** [comment]
Run Python PreCommit

**Comment by AnandInguva** [comment]
cc: @emilymye

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
