### PR TITLE
add worker metadata to windmill* protos

### PR DESCRIPTION
**Pull request by m-trieu**
add workermetadata to windmill protos

R: @scwhittle @dustin12 
-----------------------

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by dustin12** [comment]
LGTM

**Comment by dustin12** [comment]
Please include the updated WorkerMetadataProto with the directpath endpoints otherwise we will have to change this in a few days.

**Comment by m-trieu** [comment]
> Please include the updated WorkerMetadataProto with the directpath endpoints otherwise we will have to change this in a few days.

added

**Comment by m-trieu** [comment]
thanks @dustin12 !

@johnjcasey this is ready for a final review/merge thank you

**Comment by m-trieu** [comment]
Thanks! @johnjcasey

**Pull request merged**
