### PR TITLE
Update versions based on libraries-bom, and add comment to keep consistency

### PR DESCRIPTION
**Pull request by bvolpato**
Follow up to https://github.com/apache/beam/pull/27828

The versions list can be obtained from:

```
wget https://repo1.maven.org/maven2/com/google/cloud/libraries-bom/26.21.0/libraries-bom-26.21.0.pom -O base.pom && mvn help:effective-pom -f base.pom -Doutput=effective.pom && cat effective.pom | grep -v 'dependencyManagement' > cleanup.pom && mvn dependency:tree -f cleanup.pom 
```

### CODE REVIEW

**Comment by bvolpato** [comment]
Run GoPortable PreCommit

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
Run Java_Amazon-Web-Services2_IO_Direct PreCommit

**Comment by bvolpato** [comment]
Run PythonFormatter PreCommit

**Comment by bvolpato** [comment]
Run PythonLint PreCommit

**Comment by bvolpato** [comment]
Run Python_Dataframes PreCommit

**Comment by bvolpato** [comment]
Run Python_Runners PreCommit

**Comment by bvolpato** [comment]
Run SQL_Java11 PreCommit

**Comment by bvolpato** [comment]
Run Website PreCommit

**Review by Abacn — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
It may worth automate this process in general, could open a FR for detecting and update dependencies that are also transitive dependency in BOM.

**Pull request merged**
