### PR TITLE
[BEAM-4328] Upgrade Gradle shadowJar plugin to latest.

### PR DESCRIPTION
**Pull request by swegner**
http://imperceptiblethoughts.com/shadow/#change_log

This is an attempt to fix release build issues described in [BEAM-4328](https://issues.apache.org/jira/browse/BEAM-4328). I don't have any confidence that it fixes the build. But it might, and it's general goodness to keep our dependencies up-to-date.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `./gradlew build` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by swegner** [comment]
R: @pabloem 

CC: @boyuanzz @lukecwik

**Comment by pabloem** [comment]
LGTM. I'll merge after getting passing precommit.

**Comment by swegner** [comment]
Java pre-commits fail on task `:beam-sdks-java-maven-archetypes-starter:generateAndBuildArchetypeTest`: https://builds.apache.org/job/beam_PreCommit_Java_GradleBuild/5505/

@pabloem points out that this also failed on another PR which doesn't change Java: https://scans.gradle.com/s/kr23q43mh6fmk

**Comment by swegner** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Nice. Merging.

**Pull request merged**
