### PR TITLE
[BEAM-14187] Fix NPE

### PR DESCRIPTION
**Pull request by baeminbo**
Fix NPE when `rawChannelReference` has a `null` reference.

### CODE REVIEW

**Comment by baeminbo** [comment]
R: @lukecwik

**Comment by baeminbo** [comment]
@apilloud Fix for b/229785377

**Comment by baeminbo** [comment]
@lukecwik Hi, this is for b/229439039. I changed the wrong JIRA ticket number in the PR title.

**Review by lukecwik — APPROVED** [review]
LGTM

**Pull request merged**
