### PR TITLE
[BEAM-4401] Use ElementEncoders for beam.Create

### PR DESCRIPTION
**Pull request by schroederc**
This ensures that any valid pipeline element can be passed to beam.Create.  The JSON encodings only work for a subset of valid PCollection types.

### CODE REVIEW

**Comment by schroederc** [comment]
R: @herohde

**Comment by schroederc** [comment]
Done.  I manually wrote a type that implements the proto.Message interface and cannot be JSON marshaled due to the faux oneof field.

**Comment by lostluck** [comment]
LGTM

R: @jasonkuster Please merge! Thank you.

**Comment by jasonkuster** [comment]
LGTM

**Pull request merged**
