### PR TITLE
[BEAM-3620] Remove older Kafka versions from build time support.

### PR DESCRIPTION
**Pull request by rangadi**
Deprecated Kafka client versions before 0.10.1.0. Building KafkaIO with older version (with `-Dkafka.clents.version=0.9.0.1`) will fail. The older versions should work fine at run time, we log a
warning about deprecation. This is the first step towards removing support for older versions entirely in future versions. 0.10.1 and above have much better support for record timestamps. 

Immediate benefit : we can remove some reflection based calls in
ConsumerSpEL and KafkaIOTests. 'timestamp' method was invoked through
reflection for every record.

### CODE REVIEW

**Comment by rangadi** [comment]
+R: @XuMingmin, @iemejia, @jbonofre. +CC @jkff @chamikaramj

**Comment by rangadi** [comment]
Hi @iemejia & @XuMingmin, 
Could one of you review this? Thanks! I think it is fairly safe and I have run a simple pipeline with 0.9.1 at runtime.

**Comment by XuMingmin** [comment]
@rangadi  wanna to confirm the scenarios after this change:
a). developers cannot build with kafka-client:0.9.*, is that right?
b). If developers do have a Kafka cluster running with version 0.9.*, KafkaIO works because kafka-client 0.10 can access kafka server 0.9, right?

**Comment by rangadi** [comment]
a) yes.
b) both developers and users would do the same while building a Beam app: 
  * Along with beam-kafkaio dependency, they would include a specific version of kafka-clients library (e.g. kafka-clients version 0.9.0.1), and force the version in their dependency, or
  * Include specific version kafka-client library in their fat jar or set of jars at runtime.

I thought we had moved kafka-clients dependency in Beam to 'provided' scope. That way it is always the user who decides which version to include at runtime. Looks like it is not case, I will look into it. Moving the dependency to provided is good signal that KafkaIO supports multiple versions at runtime.

**Comment by XuMingmin** [comment]
If developers are allowed to included a kafka-client 0.9, methods like `rawRecord.timestamp()` and `consumer.offsetsForTimes()` would fail to compile. Suppose kafka-client 0.10 is backward compatible(to access Kafka server 0.9*), I would suggest to not support kafka-client 0.9.

**Comment by iemejia** [comment]
+1 to the provided change, sorry to came late to the review, I will take a look once this is changed to validate that everything works as expected with version 0.9.0.1

**Comment by rangadi** [comment]
@XuMingmin, you are right. Those methods won't compile, that's why we don't support buiding KafkaIO with 0.9.x. But it is fine at runtime since those methods are not called if the version 0.9x. If the user uses 0.10.x to talk to 0.9.x servers, then it is fine. We just don't want to force users to use 0.10.1+ (@iemejia & @jbonofre commented about it on user@ thread).

**Comment by rangadi** [comment]
I will move the dependency to provided scope.

**Comment by rangadi** [comment]
Thanks @XuMingmin.
@iemejia can you +1 'provided' scope change? Should we update any documentation? This essentially requires users to update their dependencies to include kafka-clients.

**Comment by iemejia** [comment]
I just tested, works perfectly with Kafka 0.9.0.1. I suppose we need to update the documentation but I am not sure where is the right place. I will merge it as it is and we will look afterwards for the doc.

**Pull request merged**
