### PR TITLE
[BEAM-3612] Generate type assertion shims for beam.

### PR DESCRIPTION
**Pull request by lostluck**
This resolves the work for [BEAM-3612] to make it easy to generate type assertion shims, in particular with the starcgen tool. With this nothing in the main beam core generates unnecessary reflection overhead. We are likely able to delete the .../exec/optimized package as well, which added unnecessary bloat to binaries with questionable gain.

This PR is large, but most of the bulk is in the generated code, which is in any *.shims.go file. 
The rest is adding go:generate lines to invoke the starcgen tool to generate the registrations and shims.

The changes to the starcgen tool make it more convenient to use within a package, and also possible to write out diagnostic output to the generated file.
The change to the shimx package (which does the actual code generation) makes the closured method wrappings for StructuralDoFns stably sorted to avoid unnecessary re-ordering on subsequent generations. 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by apilloud** [comment]
Run Go PreCommit

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
R: @apilloud Ready for another look. Freshly pulled in master, and passes the Pre and PostCommits. Thanks!

**Comment by lostluck** [comment]
Ping @apilloud

**Comment by lostluck** [comment]
@aaltay  Please merge! Thanks! :D

**Pull request merged**
