### PR TITLE
Remove submodule

### PR DESCRIPTION
**Pull request by swegner**
This seems to have been added by accident

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by swegner** [comment]
R: @lostluck

**Comment by lostluck** [comment]
Agreed. It's clearly something I added, but I have no idea what it is. Thanks for catching it! (it was added in https://github.com/apache/beam/pull/5696 accidentally)

**Comment by lostluck** [comment]
LGTM

**Comment by swegner** [comment]
Thanks, now just need a committer to merge. /cc @jkff

**Pull request merged**
