### PR TITLE
[BEAM-7119] Change Nexmark URL to use an archive.org link

### PR DESCRIPTION
**Pull request by iemejia**
R: @mxm

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by iemejia** [comment]
Run Website PreCommit

**Comment by iemejia** [comment]
Run RAT PreCommit

**Comment by iemejia** [comment]
Run Websie PreCommit

**Comment by iemejia** [comment]
Run Website PreCommit

**Comment by iemejia** [comment]
Run Website PreCommit

**Comment by ibzib** [comment]
Run Website PreCommit

**Comment by iemejia** [comment]
Run Website PreCommit

**Comment by iemejia** [comment]
Run Website PreCommit

**Pull request merged**
