### PR TITLE
[BEAM-2973] Reverting change to attempt to fix Jenkins PreCommit

### PR DESCRIPTION
**Pull request by youngoli**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This reverts commit ab975317e1aa532053b68ccc105e13afff0c0b1a. That commit seems to be causing issues with Jenkins for whatever reason.

### CODE REVIEW

**Comment by youngoli** [comment]
R: @tgroh

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
+ @aljoscha

**Comment by tgroh** [comment]
This LGTM as a rollback, pending green jenkins

**Comment by youngoli** [comment]
Seeing as this was fixed already with #3875 I'll close this PR

**Pull request closed without merging**
