### PR TITLE
[BEAM-1221] Run Wordcount IT in Python Postcommit Using Test Framework

### PR DESCRIPTION
**Pull request by markflyhigh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

Use test framework to start e2e wordcount test ([wordcount_it_test.py](https://github.com/apache/beam/blob/python-sdk/sdks/python/apache_beam/examples/wordcount_it_test.py)), in order to:
 - Simplify postcommit run script.
 - Provide an example that shows how to use test framework to run integration test on a service.

Test is done by running `run_postcommit.sh` on Dataflow service (didn't run ValidatesRunner tests). Result is [here](https://pantheon.corp.google.com/dataflow/job/2016-12-27_14_34_56-9345778248827508642?project=google.com:clouddfe)

### CODE REVIEW

**Comment by markflyhigh** [comment]
+R: @aaltay

**Comment by aaltay** [comment]
LGTM

**Comment by markflyhigh** [comment]
@dhalperi please merge

**Comment by dhalperi** [comment]
LGTM, merged.

**Pull request closed without merging**
