### PR TITLE
Fix container startup fail when requirement exists

### LINKED ISSUE #27641: [Bug]: beam_PostCommit_XVR_Direct is consistently failing to complete its runs
### What happened?

[beam_PostCommit_XVR_Direct](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/) hasn't completed a run since July 22nd and hasn't had a successful run since July 20th.

This is possibly related to #27640 , failures on a similar test that began around the same time.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #27641

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run XVR_Direct PostCommit

**Comment by Abacn** [comment]
Test passed, ready for review now

https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct_PR/170/

R: @jrmccluskey

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
3 tests already passed, status not updated to GitHub UI. Merging for now

**Comment by tvalentyn** [comment]
Thanks for the fix, @Abacn ! could you please add some details to PR description about the nature of the error and the fix?

**Comment by Abacn** [comment]
> Thanks for the fix, @Abacn ! could you please add some details to PR description about the nature of the error and the fix?

Yeah, updated description

**Pull request merged**
