### PR TITLE
Revert "[BEAM-7513] Adding Row Count for Bigquery Table"

### PR DESCRIPTION
**Pull request by akedin**
Reverts apache/beam#8822

Breaks Nexmark

https://issues.apache.org/jira/browse/BEAM-7583

### CODE REVIEW

**Comment by akedin** [comment]
R: @lukecwik @riazela @apilloud

**Comment by akedin** [comment]
run sql postcommit

**Comment by akedin** [comment]
Direct Runner Nexmark Tests

**Comment by akedin** [comment]
dataflow runner nexmark tests

**Comment by akedin** [comment]
Run Direct Runner Nexmark Tests

**Comment by akedin** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by akedin** [comment]
run sql postcommit

**Comment by akedin** [comment]
run flink runner nexmark tests

**Comment by akedin** [comment]
run spark runner nexmark tests

**Comment by riazela** [comment]
LGTM

**Comment by akedin** [comment]
Run Java_Examples_Dataflow PreCommit

**Pull request merged**
