### PR TITLE
Clear side input caches of dofninvoker when finishing bundle.  Add microbenchmarks for map_fn with side inputs.

### PR DESCRIPTION
**Pull request by scwhittle**
Improve the map_fn test by using common utilities.
Add support to benchmarks to add profiling.  I was originally trying to optimize the code other ways but most of the overhead appears to be due to cython/Python interactions so the fast-past cache for repeated process invocations is important.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by scwhittle** [comment]
fixes #28776

**Comment by scwhittle** [comment]
fixed lint issue, remaining test failures seem unrelated but they are rerunning anyway

**Comment by scwhittle** [comment]
@roberwb @tvalentyn as you have context from before and had performance concerns.
From the benchmark, clearing on finish_bundle doesn't appear to impact runtime.
You were correct that doing it every time slowed down the process time by about 25%.  I tried to optimize by using a placeholder approach similar to other placeholders but it still was slow, I believe due to going back and forth between cython/python as shown by cython annotate see 
[see test.html.txt](https://github.com/apache/beam/files/15408015/test.html.txt)
(uploading as text to workaround github filter). It might be something to investigate to improve performance if desired for process()

**Comment by tvalentyn** [comment]
Thanks, @scwhittle !

> doing it every time slowed down the process time by about 25%. 

Have you observed this regression on Dataflow runner as well?

> From the benchmark, clearing on finish_bundle doesn't appear to impact runtime.

Seems like a great idea! Have you checked whether Dataflow runtime has changed  on any of the perf tests using side-inputs ?

**Review by tvalentyn — APPROVED** [review]

**Comment by scwhittle** [comment]
Without the sdk cache enabled (not on by default), removing the PerWindowInvoker cache mans that there is lots of FnApi traffic to fetch side inputs which contributed to latency in Dataflow runner.

I think that we should postpone making this always on until the sdk cache is enabled by default. If that is too far out we could modify this to not clear after every bundle but modify finish_bundle to clear it only after some timeout.

Enabling the sdk cache will let the runner control the refresh via the side-input cache token.

**Comment by robertwb** [comment]
I agree, and this will likely slow things down a lot more on a real runner without SDK cache than is shown in the microbenchmarks. How hard would it be to only clear the cache if it's reached a certain age (at least until we have sdk cache is enabled by default).

**Comment by scwhittle** [comment]
It would be pretty easy to do so but it could still cause latency regressions on pipelines that have a global side input that is not refreshing.

I was looking into doing so only if the pcollection generating the side input was unbounded as a non-updating side input seems like it would be bounded. I was using the AsSideInput [pcollection](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/pvalue.py#L363) but then it looked like some additional plumbing was necessary to keep this metadata in [SideInputData](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/pvalue.py#L451) which is what is unpickled and used for execution. I didn't get a chance to get it all working yet.

@robertwb  Do you forsee issues with that approach before I work further on completing it? IIUC the pickling just needs to be consistent between pipeline submission and execution so it wouldn't be an update compatibility issue.

**Comment by tvalentyn** [comment]
waiting on author

**Comment by tvalentyn** [comment]
FWIW I am planning to look into enabling side input cache again next quarter

**Comment by scwhittle** [comment]
Recreated with https://github.com/apache/beam/pull/37123 as I can't reopen after force push.

**Pull request closed without merging**
