### PR TITLE
Init go mod for start-build-env.sh

### PR DESCRIPTION
**Pull request by mohamedawnallah**
Addresses #28096

This PR adds `go.mod` to be able to `go get github.com/linkedin/goavro/v2` as `go get` is no longer supported outside a module. Please refer to [go-get-install-deprecation](https://golang.org/doc/go-get-install-deprecation)

https://github.com/apache/beam/assets/69568555/a02495f7-2efb-43f3-abac-221a010093f8

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by AnandInguva — APPROVED** [review]

**Review by AnandInguva — APPROVED** [review]

**Comment by damccorm** [comment]
R: @lostluck for go comments

**Comment by lostluck** [comment]
I'm pretty sure we 1) don't need a go mod environment (All go code in the repo is under a module, which is where it gets built anyway) and 2) don't need to explicitly manually install any given go package. If we depend on them, they need to be in the module file.

I would instead remove the `go get ...avro...`  line from the script.

**Comment by lostluck** [comment]
[go-get-install-deprecation](https://golang.org/doc/go-get-install-deprecation) also only applies to having go get install binaries for you. goavro is a package, not a command.

**Comment by damccorm** [comment]
@mohamedawnallah @lostluck what are next steps on this PR?

**Comment by mohamedawnallah** [comment]
Hey @damccorm sorry I got busier my university. I will try to look at this issue tomorrow and let you know

**Pull request closed without merging**
