### PR TITLE
Revert "Replace OutputTimeFn UDF with TimestampCombiner enum"

### PR DESCRIPTION
**Pull request by kennknowles**
This reverts commit f38e4271334fced94e8dc1dc97f47b60fa810586.

It will require a synchronous Dataflow worker container bump.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This requires a new Dataflow worker container. A number of things appear to be possibly broken, so we can merge this in any time in order to see what the other things are.

### CODE REVIEW

**Comment by kennknowles** [comment]
https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/2942/ should eventually be a build against this. It is unlikely to be green, as it was already broken to my knowledge.

**Comment by kennknowles** [comment]
Since it is entirely certain (from logs) that the worker will get ClassNotFound errors, and Jenkins is busted again, I will merge this.

**Comment by kennknowles** [comment]
R: @tgroh (original reviewer) or anyone after the fact

**Comment by tgroh** [comment]
LGTM

**Pull request merged**
