### PR TITLE
Using Teardown context instead of deprecated finalize

### PR DESCRIPTION
**Pull request by scott-strong**
This method is deprecated as of Java 9. I have also been having trouble with connections leaking and staying open after encountering database errors and think this is the culprit.

I believe this is also the issue occurring in #22299 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Thanks for the catch! Entered #24181 for tracking.

**Comment by Abacn** [comment]
Run Java JdbcIO Performance Test

**Review by Abacn — APPROVED** [review]
LGTM. Though I am not sure if this is the only cause of #22299 because FinishBundle also called cleanUpConnection. Will monitoring of course.

**Comment by scott-strong** [comment]
@Abacn thanks yeah that's fair, but does `FinishBundle` get called even if `processElement` encounters an exception? That's the use case I was looking to fix.

**Comment by Abacn** [comment]
performance test passed. Thanks for the fix! Will monitor.

**Pull request merged**
