### PR TITLE
Remove legacy windowfn translation.

### PR DESCRIPTION
**Pull request by robertwb**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @herohde

**Comment by robertwb** [comment]
Jenkins failure: ERROR: beam8 is offline

Jenkins: retest this please

**Comment by herohde** [comment]
LGTM (but I'm not a committer)

**Comment by robertwb** [comment]
@lukecwik Any ideas on errors like

java.lang.NoClassDefFoundError: org/apache/beam/runners/direct/repackaged/com/google/protobuf/util/Durations

in code that compiles and used to work? Is this a shading issue?

**Comment by kennknowles** [comment]
TBH not sure how this worked before, especially since your change is subtractive. I probably am missing something, but here's my $0.02:

The class is part of `com.google.protobuf:protobuf-util-java` which is a dependency of `runners-core-construction-java` where the reference is made, but the shading of the direct runner relocates `com.google.protobuf.**` without bundling that artifact. It bundles the core protobuf artifact, which will not contain everything that is needed. So my reading is that the config is just wrong.

Editorial: I used to be annoyed that it was hard to distribute `x.y` separately from `x.y.z` in Python but that practice in java is a positive nightmare. The most fun part is where `x.y.q` might be in the same jar and `x.y.z` is in a separate jar.

**Comment by robertwb** [comment]
Thanks. Can you give any pointers on how to fix (unshade) this? I'm not
sure where this happens in the poms.

**Comment by robertwb** [comment]
Hmm... I'm also getting errors in "Apache Beam :: SDKs :: Java :: Maven Archetypes :: Examples - Java 8" (but not the Java  7 ones): 

```
2017-12-05T01:41:32.073 [INFO] java.lang.NoClassDefFoundError: org/apache/beam/runners/direct/repackaged/com/google/protobuf/util/Durations
2017-12-05T01:41:32.074 [INFO] 	at it.pkg.complete.game.LeaderBoardTest.testTeamScoresOnTime(LeaderBoardTest.java:116)
2017-12-05T01:41:32.074 [INFO] 
```

which seems to be the opposite problem. Still digging.

**Comment by lukecwik** [comment]
ITs run on post shaded artifacts while tests run on pre-shaded classes in our current Maven and Gradle setup. It would be best if all our tests ran on the post shaded artifacts. 

Are the additional classes being supplied by the Dataflow worker and now because of some change they are missing?

**Comment by lukecwik** [comment]
Most of this has been subsumed by https://github.com/apache/beam/pull/4367, please update PR.

**Comment by robertwb** [comment]
Rebased on #4367, it's just a minor cleanup now. PTAL.

**Comment by kennknowles** [comment]
Ah, I didn't see this. Sorry for the duplication!

**Comment by kennknowles** [comment]
(I mean I didn't see it just now - obviously I saw it when I first commented :-)

**Comment by kennknowles** [comment]
LGTM

**Comment by robertwb** [comment]
Jenkins: retest this please.

**Pull request merged**
