### PR TITLE
Set streaming engine option to fix V1 tests

### PR DESCRIPTION
**Pull request by ahmedabu98**

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Test passed: https://github.com/apache/beam/actions/runs/11821541636/job/32936533690?pr=33100

**Review by claudevdm — APPROVED** [review]
LGTM, thanks

**Review by damccorm — APPROVED** [review]
Thanks!

**Comment by damccorm** [comment]
Looks like `PreCommit Xlang Generated Transforms` is hung, it seems unrelated to this PR though. I'm going to cancel/rerun, but also optimistically merge so we can get the release branch going. If needed, we can cherry-pick in another fix

**Pull request merged**
