### PR TITLE
[BEAM-5684] Adding a BQNestedRecords Test

### PR DESCRIPTION
**Pull request by pabloem**
This change also includes utilities to perform BQ export jobs that do/do not flatten the output.

r: @jasonkuster

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java Dataflow PostCommit

**Comment by pabloem** [comment]
Run Dataflow ValidatesRunner

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by jasonkuster** [comment]
LGTM

**Pull request merged**
