### PR TITLE
[BEAM-5024] Remove reference to dataflow-distribution.properties

### PR DESCRIPTION
**Pull request by aaltay**
cc: @ThatRfernand

### CODE REVIEW

**Comment by ThatRfernand** [comment]
LGTM

**Comment by aaltay** [comment]
Added a JIRA. Thank you both.

**Comment by aaltay** [comment]
Two failed tests are:
:beam-sdks-java-extensions-protobuf:extractIncludeTestProto FAILED
:beam-sdks-java-io-elasticsearch-tests-2:compileTestJava FAILED

I do not know how they are related to this change.

**Comment by aaltay** [comment]
retest this please

**Pull request merged**
