### PR TITLE
[BEAM-8685] sdks/java: google_auth_version 0.19.0

### PR DESCRIPTION
**Pull request by suztomo**
Upgrading the following two libraries to 0.19.0.

```
        google_auth_library_credentials             : "com.google.auth:google-auth-library-credentials:$google_auth_version",
        google_auth_library_oauth2_http             : "com.google.auth:google-auth-library-oauth2-http:$google_auth_version",
```

This is preparation for BEAM-8676 (gax-grpc upgrade); `com.google.api
gax:1.52.0` requires `com.google.auth:google-auth-library-oauth2-http:0.19.0` or higher.

# Linkage Check

## beam-sdks-java-extensions-google-cloud-platform-core
- before: https://gist.github.com/suztomo/aec41839abec689eb379fd9c70575325
- after: https://gist.github.com/suztomo/be1388f48fb13c75813992cab9400067

Diff:
```
suztomo@suxtomo24:~/beam6$ diff /tmp/linkagecheck-beam-sdks-java-extensions-google-cloud-platform-core-785609f2 /tmp/linkagecheck-beam-sdks-java-extensions-google-cloud-platform-core-ea012f73
184c184
< (guava-20.0.jar) com.google.common.collect.ImmutableList's method toImmutableList() is not found;
---
> (guava-28.1-android.jar) com.google.common.collect.ImmutableList's method toImmutableList() is not found;
```

The transitive dependency of Guava in beam-sdks-java-extensions-google-cloud-platform-core got higher version (from 20.0 to 28.1-android) but this missing method has been there even for the old version 20.0.

## beam-runners-google-cloud-dataflow-java
- before: https://gist.github.com/suztomo/8917ae65a8aa90940b6c090b83d04c0a
- after: https://gist.github.com/suztomo/2c0c264f55e44ae6ced36cf6cc4a1114 (same as above)

## beam-examples-kotlin
- before: https://gist.github.com/suztomo/fe6008ab53694c82c896f9d6c31e9806
- after: https://gist.github.com/suztomo/66c4494daab25365f0407a156f2a311d (same as above)

## beam-examples-java
- before: https://gist.github.com/suztomo/afd80975287007db7800e869c6cb2c54
- after: https://gist.github.com/suztomo/64f9ae4aac13c9c1add0a0c73ac17b17 (same as above)

## beam-sdks-java-extensions-sql-datacatalog

Linkage Checker fails to resolve dependencies (Bug: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1087 ).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by suztomo** [comment]
R: @lukecwik, @kennknowles

**Comment by suztomo** [comment]
retest this please

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Run Java PostCommit

**Comment by iemejia** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by iemejia** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by iemejia** [comment]
Run Dataflow ValidatesRunner

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run SQL Postcommit

**Comment by iemejia** [comment]
Run CommunityMetrics PreCommit

**Comment by suztomo** [comment]
Strange. Python build failed. https://builds.apache.org/job/beam_PreCommit_Python_Commit/10669/testReport/junit/(root)/(empty)/apache_beam_examples_streaming_wordcount_it_test/ says:
```
E     File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py2/build/srcs/sdks/python/target/.tox-py27-cython-pytest/py27-cython-pytest/local/lib/python2.7/site-packages/hamcrest/library/object/hasproperty.py", line 174
E       ),
E       ^
E   SyntaxError: invalid syntax
```

@iemejia Thank you.

**Comment by suztomo** [comment]
Run Python PreCommit

**Comment by suztomo** [comment]
All green for Java; only Python precommit (which I believe was caused by their flakiness) checks failed.

@lukecwik Would you review and merge this?

**Comment by suztomo** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by lukecwik** [comment]
Waiting on tests before merging.

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by suztomo** [comment]
21 successful checks

**Pull request merged**
