### PR TITLE
Align vendored and non-vendored gRPC versions

### PR DESCRIPTION
**Pull request by iemejia**
R: @lukecwik

### CODE REVIEW

**Comment by iemejia** [comment]
Run Portable_Python PreCommit

**Comment by iemejia** [comment]
Mmmm... looks like hadoop was not happy when I tried to align guava's version so better go for the memonte only with gRPC

**Comment by iemejia** [comment]
Run Portable_Python PreCommit

**Comment by iemejia** [comment]
It is green now. PTAL @lukecwik  (sorry to bother you with all these reviews), will shuffle reviewers now that other people are back from holidays.

**Comment by lukecwik** [comment]
Run Java PostCommit

**Comment by iemejia** [comment]
Oups postcommit failed with panic message, probably better to abort this then, I imagine the dependency web for the GCP deps as daunting. Save if you have any suggestion.

**Comment by lukecwik** [comment]
I think updating gRPC will require a significant effort (dealing with the transitive closure of dependency upgrades as well) in updating all users of gRPC to a newer compatible version.

**Pull request closed without merging**
