### PR TITLE
[BEAM-13101] [Playground] load examples using the api

### PR DESCRIPTION
**Pull request by ElessarST**
Update examples to work with the API instead of using mocks
https://issues.apache.org/jira/browse/BEAM-13101
Depends on the implementation https://github.com/apache/beam/pull/15957

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ElessarST** [comment]
R: @damondouglas

cc: @pabloem

**Review by damondouglas — COMMENTED** [review]
@ElessarST did `./gradlew playgroundPrecommit` give you the same error output as I saw?

```
> Task :playground:frontend:test
00:00 +0: loading beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart                                             00:01 +0: loading beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart                                                  ../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/io_bits/io_bits_web.dart:16:1: Error: Not found: 'dart:html'
export 'dart:html' show HttpStatus;
^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:33:9: Error: Type 'HttpRequest' not found.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:159:27: Error: Type 'HttpRequest' not found.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:169:3: Error: Type 'HttpRequest' not found.
  HttpRequest createHttpRequest() => HttpRequest();
  ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:133:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.ok: StatusCode.ok,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:134:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.badRequest: StatusCode.invalidArgument,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:135:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.unauthorized: StatusCode.unauthenticated,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:136:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.forbidden: StatusCode.permissionDenied,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:137:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.notFound: StatusCode.notFound,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:138:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.conflict: StatusCode.aborted,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:139:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.preconditionFailed: StatusCode.failedPrecondition,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:140:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.tooManyRequests: StatusCode.resourceExhausted,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:141:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.clientClosedRequest: StatusCode.cancelled,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:142:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.internalServerError: StatusCode.unknown,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:143:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.notImplemented: StatusCode.unimplemented,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:144:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.serviceUnavailable: StatusCode.unavailable,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:145:5: Error: Getter not found: 'HttpStatus'.
    HttpStatus.gatewayTimeout: StatusCode.deadlineExceeded,
    ^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:33:9: Error: 'HttpRequest' isn't a type.
  final HttpRequest _request;
        ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:61:14: Error: Getter not found: 'HttpRequest'.
        case HttpRequest.HEADERS_RECEIVED:
             ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:64:14: Error: Getter not found: 'HttpRequest'.
        case HttpRequest.DONE:
             ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:71:30: Error: 'ProgressEvent' isn't a type.
    _request.onError.listen((ProgressEvent event) {
                             ^^^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:159:27: Error: 'HttpRequest' isn't a type.
  void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                          ^^^^^^^^^^^
../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:169:38: Error: The method 'HttpRequest' isn't defined for the class 'XhrClientConnection'.
 - 'XhrClientConnection' is from 'package:grpc/src/client/transport/xhr_transport.dart' ('../../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
  HttpRequest createHttpRequest() => HttpRequest();
                                     ^^^^^^^^^^^
00:02 +0: loading beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart                                             00:02 +0 -1: loading beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart [E]                                           
  Failed to load "beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart": Compilation failed for testPath=beam/playground/frontend/test/pages/playground/states/example_selector_state_test.dart
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 10:3  throwToolExit
  package:flutter_tools/src/compile.dart 778:9     DefaultResidentCompiler._compile.<fn>
  dart:async/zone.dart 1436:47                     _rootRunUnary
  dart:async/zone.dart 1335:19                     _CustomZone.runUnary
  
00:05 +0 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:05 +0 -1: beam/playground/frontend/test/pages/playground/states/playground_state_test.dart: Playground State initial value should be java         00:05 +1 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:05 +1 -1: beam/playground/frontend/test/pages/playground/states/playground_state_test.dart: ... state should notify all listeners about sdk change00:05 +2 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:05 +2 -1: beam/playground/frontend/test/pages/playground/states/playground_state_test.dart: ... should reset source to example notify all listener00:05 +3 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:05 +3 -1: beam/playground/frontend/test/pages/playground/states/playground_state_test.dart: ... update source and example and notify all listeners00:05 +4 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:06 +4 -1: loading beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart                               00:06 +4 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... complete finished run code reques00:06 +5 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... complete finished run code reques00:06 +5 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... output from compilation if failed00:06 +6 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... output from compilation if failed00:06 +6 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... if failed and compile output is e00:06 +7 -1: beam/playground/frontend/test/modules/editor/repository/code_repository/code_repository_test.dart: ... if failed and compile output is e00:06 +7 -1: Some tests failed.                                                                                                                                                                        

> Task :playground:frontend:test FAILED
```

**Comment by ElessarST** [comment]
> @ElessarST did `./gradlew playgroundPrecommit` give you the same error output as I saw?
> 
> ```
> Task :playground:frontend:analyze
> Analyzing ....
> 
>   error - test/pages/playground/states/example_selector_state_test.dart:28:8 - Target of URI doesn't exist: 'example_selector_state_test.mocks.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist. - uri_does_not_exist
>   error - test/pages/playground/states/example_selector_state_test.dart:32:30 - The function 'MockExampleClient' isn't defined. Try importing the library that defines 'MockExampleClient', correcting the name to the name of an existing function, or defining a function named 'MockExampleClient'. - undefined_function
> ```

@damondouglas sorry, one file was not pushed

**Review by damondouglas — CHANGES_REQUESTED** [review]
Hello @ElessarST thank you for all this work.  When I run `buf lint` in the `beam/playground` directory, I receive the following output.  Did we want to follow its recommendation?

```
api/v1/api.proto:49:3:Enum value name "EXAMPLE" should be prefixed with "PRECOMPILED_OBJECT_TYPE_".
api/v1/api.proto:49:3:Enum zero value name "EXAMPLE" should be suffixed with "_UNSPECIFIED".
api/v1/api.proto:50:3:Enum value name "KATA" should be prefixed with "PRECOMPILED_OBJECT_TYPE_".
api/v1/api.proto:51:3:Enum value name "UNIT_TEST" should be prefixed with "PRECOMPILED_OBJECT_TYPE_".
api/v1/api.proto:164:3:".api.v1.GetRunOutputResponse" is used as the request or response type for multiple RPCs.
api/v1/api.proto:179:3:".api.v1.GetPrecompiledObjectRequest" is used as the request or response type for multiple RPCs.
api/v1/api.proto:179:32:RPC request type "GetPrecompiledObjectRequest" should be named "GetPrecompiledObjectCodeRequest" or "PlaygroundServiceGetPrecompiledObjectCodeRequest".
api/v1/api.proto:182:3:".api.v1.GetPrecompiledObjectRequest" is used as the request or response type for multiple RPCs.
api/v1/api.proto:182:3:".api.v1.GetRunOutputResponse" is used as the request or response type for multiple RPCs.
api/v1/api.proto:182:34:RPC request type "GetPrecompiledObjectRequest" should be named "GetPrecompiledObjectOutputRequest" or "PlaygroundServiceGetPrecompiledObjectOutputRequest".
api/v1/api.proto:182:72:RPC response type "GetRunOutputResponse" should be named "GetPrecompiledObjectOutputResponse" or "PlaygroundServiceGetPrecompiledObjectOutputResponse".
```

**Comment by miamihotline** [comment]
Hello @damondouglas, thank you for the suggestion, I fixed this issue, please review this PR again

**Review by damondouglas — APPROVED** [review]
@pabloem LGTM

**Pull request merged**
