### PR TITLE
validated  the input schema matches with the bigquery output schema

### PR DESCRIPTION
**Pull request by xianhualiu**
Validated the input schema is assignable to the output schema for BigQuery SchemaIO write transform.  
------------------------

Currently when input schema does not match with the BigQuery output table schema, the pipeline runs normal without reporting any error. The schema validation implemented in this PR will cause pipeline with mis-matched schema fail to start with appropriate error reported in log.

### CODE REVIEW

**Comment by pabloem** [comment]
could you write a test for this here? https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProviderTest.java#L61 -

perhaps one where the check fails and one where it passes to have confidence in the change?

**Comment by xianhualiu** [comment]
> could you write a test for this here? https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProviderTest.java#L61 -
> 
> perhaps one where the check fails and one where it passes to have confidence in the change?

added successful and failed test cases.

**Comment by pabloem** [comment]
lgtm1

**Comment by slilichenko** [comment]
There is a valid use case where this approach will not work - writing to a table with a required field and a default value and relying on BigQuery to use the default value. The only way to use default values at the moment is to explicitly specify the schema without the field.

**Pull request merged**
