### PR TITLE
fix FlinkCombiningStateWithContext read null accum bug

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @mxm

**Comment by mxm** [comment]
LGTM

I'm wondering, couldn't https://github.com/apache/beam/blob/master/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java#L978 also give us a NPE?

**Comment by peihe** [comment]
https://github.com/apache/beam/blob/master/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/state/FlinkStateInternals.java#L978 will return null for empty state.

I feel we should label @Nullable in the state interface, given the current contracts for read() are not consistent between different states.

@kennknowles thoughts?

**Comment by kennknowles** [comment]
I think you could make a case that `ReadableState#read()` should be `@Nullable` but I don't quite like it.

My perspective is more that `ReadableState<T>#read()` does not return a `@Nullable T` but rather `ValueState<T>` really implements `ReadableState<@Nullable T>` because the other types of state don't need to return `null`.

**Comment by kennknowles** [comment]
(the change in this PR is an example of just what I mean)

**Comment by aljoscha** [comment]
If this bug could go by unnoticed then maybe the semantics of the different state types are not defined clearly enough and we are also missing `ValidatesRunner` tests. The bug might be re-introduced in the future and other Runners might have the same bug.

btw, welcome back @mxm 😃

**Pull request closed without merging**
