### PR TITLE
[BEAM-3425] Get the range start & end as String

### PR DESCRIPTION
**Pull request by jbonofre**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [X] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
I'm testing on a concrete Cassandra instance (using IT).

**Comment by jkff** [comment]
Does this PR make CassandraIOIT, run against a real Cassandra instance, be able to split into >1 splits successfully?

**Comment by iemejia** [comment]
@jbonfre and @jkff any chance this one gets merged and included in 2.3.0, looks quite important IMO.

**Comment by jbonofre** [comment]
I tested with a local Cassandra instance. So, for me it's OK even if I should have added a specific test. It's up to @jkff

**Comment by jkff** [comment]
JB - did you confirm that the test not only runs, but also uses more than 1 split? Because from the original StackOverflow issue, there were 3 bugs:

https://issues.apache.org/jira/browse/BEAM-3424
https://issues.apache.org/jira/browse/BEAM-3425
https://issues.apache.org/jira/browse/BEAM-3485

And the current PR addresses only 1 of them but I believe all 3 need to be addressed in order to get proper splitting. It may be advisable to also add an explicit option for number of splits in case it can't be estimated for whatever reason (I think this falls under the rule of thumb "if not providing the parameter can be catastrophically bad in some cases").

**Comment by jbonofre** [comment]
I have a branch with different changes. I just extracted the range parsing commit for this PR. Let me move forward on the other PRs.

**Comment by jkff** [comment]
I think it makes sense to group it into 1 PR fixing all 3 issues and making CassandraIO split properly. Each individual fix is small and doesn't have value on its own, only in combination.

**Comment by jbonofre** [comment]
It makes sense. Let me prepare a new PR, I will close this one.

**Comment by kubum** [comment]
Hi @jbonofre! Do you know what is the state of spliting at the moment? I see it is still the same in master, do you need any help with that?

**Comment by aromanenko-dev** [comment]
@kubum This PR was closed and there is another PR #5124 which is supposed to fix these 3 CassandraIO issues. The work is in progress but we expect that it will be merged soon.

**Pull request closed without merging**
