### PR TITLE
[BEAM-1265] Allow production of unprocessed bundles, introduce TestStream evaluator in DirectRunner

### PR DESCRIPTION
**Pull request by charlesccychen**
This change depends on #3405.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay

**Comment by aaltay** [comment]
@charlesccychen could you rebase this?

**Comment by charlesccychen** [comment]
Rebased to head, PTAL.  Thanks!

**Comment by aaltay** [comment]
LGTM

**Pull request closed without merging**
