### PR TITLE
[BEAM-1626] Remove cache of MapWithStateDStream on read.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
Run Spark RunnableOnService

**Comment by amitsela** [comment]
R: @staslev

**Comment by staslev** [comment]
Just for the record, we assume this change is ok since `DStream#mapWithState()` caches the dstream as part of its [checkpoint method](https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/dstream/DStream.scala#L182), thus we do not need to explicitly do it ourselves.

**Comment by amitsela** [comment]
Yup

**Comment by staslev** [comment]
Cool. Would you mind if I changed the commit message to reflect it?
Something along the lines of `Remove *extra*- cache of MapWithStateDStream on read`?

**Comment by amitsela** [comment]
I'm merging now.

**Comment by amitsela** [comment]
It's not "extra" per-se since the checkpoint's cache might not have kicked-in immediately as we discussed.

**Pull request closed without merging**
