### PR TITLE
[release-2.19.0][BEAM-9123] HadoopResourceId returns wrong directoryName bugfix

### PR DESCRIPTION
**Pull request by dmvk**
backport of https://issues.apache.org/jira/browse/BEAM-9123

### CODE REVIEW

**Comment by dmvk** [comment]
cc @aromanenko-dev

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by aromanenko-dev** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by aromanenko-dev** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by boyuanzz** [comment]
Thanks! Should the master branch also include this fix?

**Comment by mareksimunek** [comment]
> Thanks! Should the master branch also include this fix?

@boyuanzz it was already merged to master -> https://github.com/apache/beam/pull/10597

**Comment by dmvk** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by aromanenko-dev** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by aromanenko-dev** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by boyuanzz** [comment]
Java_Examples_Dataflow fails for tests misconfiguration: https://github.com/apache/beam/pull/10635

I'm going to merge this commit into release branch. Thanks for your help!

**Comment by aromanenko-dev** [comment]
@boyuanzz Thanks!

**Pull request merged**
