### PR TITLE
[BEAM-6362] remove --info from gradle invocations 

### PR DESCRIPTION
**Pull request by udim**
This should significantly reduce Gradle output and Jenkins job log
sizes, by only logging WARN and above log entries from Java tests.

Logs for failed Java tests will still be available via `Test Result`
links on the Jenkins job.

Python should see no difference in logging verbosity.

Please see JIRA issue for plan of action.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by udim** [comment]
run java precommit

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run python precommit

**Comment by udim** [comment]
run python precommit

**Comment by udim** [comment]
run java precommit

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run java precommit

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run seed job

**Comment by udim** [comment]
run java precommit

**Comment by udim** [comment]
R: @chamikaramj 
C: @swegner

**Comment by udim** [comment]
@lostluck do Go pre/post-commit jobs require `--info` to debug? Should add the flag specifically for Go?

**Comment by kennknowles** [comment]
LGTM

**Comment by lostluck** [comment]
@udim Not that I'm aware of. The Go Gradle we use ([formerly called the blindpirate one](https://github.com/gogradle/gogradle)) does seem to support better test parsing with Go1.10+. We may simply need to update to the latest version of the plugin: https://github.com/gogradle/gogradle#snapshot

Presumably it does that in the appropriate format for general gradle usage. 

A cursory search doesn't seem to indicate much. The --info flag does print out the coverage report to the output, but I don't think it would do anything to affect debugability.

**Comment by udim** [comment]
Thank you all!

**Pull request merged**
