### PR TITLE
Deleted initialNumReaders paramter.

### PR DESCRIPTION
**Pull request by AdalbertMemSQL**
Deleted initialNumReaders paramter.
Pre-split restrictions to the maximum number of readers.
See the [discussion in the design doc](https://docs.google.com/document/d/1WU-hkoZ93SaGXyOz_UtX0jXzIRl194hCId_IdmEV9jw/edit?disco=AAAAjCSqPvs
) for more details.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AdalbertMemSQL** [comment]
addresses https://github.com/apache/beam/issues/22617

**Comment by AdalbertMemSQL** [comment]
R: @lukecwik

**Comment by AdalbertMemSQL** [comment]
R: @Abacn

**Comment by AdalbertMemSQL** [comment]
R: @johnjcasey

**Comment by Abacn** [comment]
Run Java SingleStoreIO Performance Test

**Comment by Abacn** [comment]
Thanks. Followed the discussion but in case I missed something, could you please summarize the pros/cons of removing this parameter?

**Comment by AdalbertMemSQL** [comment]
Hi @Abacn 

Sure.
Pros:
 - it will make configuration easier as users will have fewer parameters
 - the runner will fully control the parallelism and the user won't need to worry about it
I don't see any cons.

@lukecwik Do you have something to add?

**Review by Abacn — COMMENTED** [review]
Thanks, this looks good to me.

**Comment by Abacn** [comment]
okay, let us get this in to get rid of a breaking change

**Pull request merged**
