### PR TITLE
[BEAM-8019] Updates Dataflow client

### PR DESCRIPTION
**Pull request by chamikaramj**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by robertwb** [comment]
Thanks! Any notes as to how this generated?

**Comment by chamikaramj** [comment]
There's documentation available internally. Not sure if this can be easily generate purely using Beam repo.

**Comment by lukecwik** [comment]
Do you know why the Google Cloud Dataflow client library is not part of https://github.com/googleapis/google-cloud-python?

**Comment by aaltay** [comment]
I do not know the answer.

@busunkim96 @tseaver -- Do you know what is need to include Dataflow apis in the google-cloud-python package?

**Comment by tseaver** [comment]
@aaltay I'm not sure which API you mean:  is it this [REST API](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/)?  If so, we would need to have somebody from within Google commission adding support for that API.

**Comment by busunkim96** [comment]
We recently moved all the code in `google-cloud-python` to separate repos named `python-{api}`. For example, the repository `python-bigquery` has the `google-cloud-bigquery` package.

Is the Dataflow client generated using `google-api-python-client`? That library is used to generate libraries at runtime from the discovery document (https://dataflow.googleapis.com/$discovery/rest?version=v1b3).

@leahecole is there a good DPE to direct this question to?

**Comment by aaltay** [comment]
The client file in this repo is generated by https://github.com/google/apitools. I assume they will generate client libraries with same capabilities even if there might be slight changes.

The generated version here is also for the rest api. I am not sure who/how often the related discovery document is updated.

**Comment by chamikaramj** [comment]
Dataflow client was generated by running apitools genclient utility [1] on the Dataflow discovery document [2].

[1] https://github.com/google/apitools/blob/master/apitools/gen/gen_client.py
[2] https://www.googleapis.com/discovery/v1/apis/dataflow/v1b3/rest

**Comment by busunkim96** [comment]
Hmm, the cloud client libraries team doesn't maintain that repo. The GitHub team (https://github.com/orgs/google/teams/apitools) looks promising if you're looking for someone to reach out to.

**Comment by aaltay** [comment]
@busunkim96 - let's say we can consider switching to `google-api-python-client`. What would be the process? Who would own the new repo?

**Comment by busunkim96** [comment]
Hi @aaltay. You can already talk to the API using `google-api-python-client`.

1. `pip install google-api-python-client`
2. 
```python
from googleapiclient import discovery

client = discovery.build("dataflow", "v1b3")
```

I think I'm missing important context here about Beam and/or Dataflow. Adding @davidcavazos who works on Dataflow in Cloud DevRel.

**Pull request merged**
