### PR TITLE
[BEAM-5513] Upgrade Python SDK to PubSub 0.35.4

### PR DESCRIPTION
**Pull request by udim**
This change affects DirectRunner and integration tests.

- No longer has separate protobuf dependency
(proto-google-cloud-pubsub-v1).
- Updated integration tests to work with new client version. Example and
test pipeliens did not need changes, demonstrating backwards
compatibility.
- game_stats_it_test, leader_board_it_test were verified to work on
Dataflow. Could not get these to run correctly on DirectRunner
(complaints about missing BQ tables).
- pubsub_test.py refactored and simplified.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks, this LGTM.  Looks like a probable flake in postcommits.

**Comment by charlesccychen** [comment]
run python postcommit

**Comment by udim** [comment]
Rererunning postcommits after https://github.com/apache/beam/pull/6589 has been merged.

**Comment by udim** [comment]
run python postcommit

**Comment by udim** [comment]
@aaltay for merge

**Pull request merged**
