### PR TITLE
[cherry-pick] Remove setting _beam_schema_proto (#29754)

### PR DESCRIPTION
**Pull request by riteshghorse**
CP of #29754 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by riteshghorse** [comment]
Run Python 3.11 PostCommit

**Comment by riteshghorse** [comment]
R: @Abacn @jrmccluskey

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by jrmccluskey** [comment]
Will merge once checks pass just for safety

**Comment by riteshghorse** [comment]
The failing PC test passed
image

**Comment by riteshghorse** [comment]
The failure is because of a bigquery test timeout
```
[1m[31mE     RuntimeError: Timeout after 600 seconds while waiting for job 2023-12-13_13_37_27-7365213249556534026 enters expected state RUNNING. Current state is PENDING.[0m

[1m[31mapache_beam/runners/dataflow/test_dataflow_runner.py[0m:103: RuntimeError

[33mDuring handling of the above exception, another exception occurred:[0m

self = <apache_beam.io.gcp.bigquery_io_read_it_test.BigqueryIOReadIT testMethod=test_bigquery_read_1M_python>

    @pytest.mark.it_postcommit
    def test_bigquery_read_1M_python(self):
>     self.run_bigquery_io_read_pipeline('1M')

[1m[31mapache_beam/io/gcp/bigquery_io_read_it_test.py[0m:68: 
```

**Comment by riteshghorse** [comment]
Run Python 3.11 PostCommit

**Pull request merged**
