### PR TITLE
Switch Flink load test with lcg synthetic data

### PR DESCRIPTION
**Pull request by Abacn**
As for Dataflow load test in #26697

The reason for a separate PR is that Python Flink load test runs on nightly container (gcr.io/apache-beam-testing/beam_portability/beam_python3.7_sdk:latest), unlike Dataflow test where an sdk_location parameter is passed to runner

btw we publish same Python container on two places, e.g.

- gcr.io/apache-beam-testing/beam_portability/beam_python3.7_sdk:latest 
  daily by https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/ 

- gcr.io/apache-beam-testing/beam-sdk/beam_python3.7_sdk
  every 4 hours by https://ci-beam.apache.org/job/beam_Publish_Beam_SDK_Snapshots

The first place also has java-sdk and go-sdk containers but no longer continuously publishing (last time was in 2022). Shall we also stop publish Python SDK snapshot in this dir and switch to use the ones in gcr.io/apache-beam-testing/beam-sdk ?

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
[Test result](https://ci-beam.apache.org/job/beam_LoadTests_Python_Combine_Flink_Batch_PR/55/console)

python_flink_batch_combine_1_runtime Value: 3235

on master, latest 3 results:
python_flink_batch_combine_1_runtime Value: 5362 5398 5272

It's 40% "improvement", similar to the Dataflow case

**Comment by Abacn** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by Abacn** [comment]
It appears that read from SyntheticSource is still slower than read from ReShuffle service. For kafka xlang test:

read from SyntheticSource (lcg) write_runtime Value: 403 s that is 6.7 min
read from ReShuffle service, write_runtime is now < 5 min

Unrelated but there is an improvement on May 13 where the run time for both write and read reduced significantly. Before that write time is 6.5 min

image

**Comment by Abacn** [comment]
Revert kafka test change for now (it was for testing purpose only); mark the PR as ready for review

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
Run Load Tests Python Combine Flink Batch

**Comment by Abacn** [comment]
R: @tvalentyn

**Comment by tvalentyn** [comment]
Thank you, this LGTM.

Using a consistnt place for containers for all languages makes sense to me.

**Comment by Abacn** [comment]
Thanks. Opened #26921 for consolidating docker image

**Pull request merged**
