### PR TITLE
Fix Python PostCommit Example CustomPTransformIT on portable

### LINKED ISSUE #24163: [Bug]: beam_PostCommit_Python_Examples_Spark and beam_PostCommit_Python_Examples_Flink failing test custom_ptransform_it_test.CustomPTransformIT
### What happened?

https://ci-beam.apache.org/job/beam_PostCommit_Python_Examples_Spark/ and https://ci-beam.apache.org/job/beam_PostCommit_Python_Examples_Flink/

```
ValueError: Pipeline has validations errors: 
Option environment_config is not compatible with environment type LOOPBACK.
```
The environment_config parameter is non null and with environment type specified triggered validation exception here: https://github.com/apache/beam/blob/2adb68bd12743566cc89b596bf204d7c807eb62d/sdks/python/apache_beam/options/pipeline_options_validator.py#L378

The options passed from command line does not specify environment_config, but it gets added when pipeline.run() initiated:
https://github.com/apache/beam/blob/2adb68bd12743566cc89b596bf204d7c807eb62d/sdks/python/apache_beam/runners/portability/portable_runner.py#L427

and get assigned the worker address.

We should resolve this conflict.

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #24163

This fixes custom_ptransform_it_test.CustomPTransformIT failing and makes PostCommit Example Spark turning back green. For PostCommit Example Flink there is still two tests failing.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
The failing test added in #23546 seems misconfigured

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
Run Python Examples_Spark

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
R: @damccorm

**Comment by damccorm** [comment]
Run Python Examples_Flink

**Review by damccorm — APPROVED** [review]

**Comment by damccorm** [comment]
> For PostCommit Example Flink there is still two tests failing.

Oops, missed that this is known - feel free to merge before that check completes

**Comment by Abacn** [comment]
PTAL @damccorm  though not sure this will fix flink issue. These tests successes locally even without configuring flink-conf-dir so not able to debug then locally. We will see.

**Comment by Abacn** [comment]
Run Python Examples_Flink

**Comment by Abacn** [comment]
Well, needs seed job for groovy script takes effect. Getting this in at this point and see the effect.

**Review by damccorm — APPROVED** [review]
SGTM

**Pull request merged**
