### PR TITLE
[Release-2.55] Cherry-pick #30551 into release branch

### LINKED ISSUE #30534: [Bug]: Upgrade compatibility broken when upgrading BQ read/write transforms to 2.55.0.dev
### What happened?

Seems like we added two required constructions properties in https://github.com/apache/beam/commit/6a8c27ef6fb945921b4f70766c1f1bd6c493dadc.

These properties are not available in previous BQ transform versions, hence upgrade compatibility will be broken.

Is it possible to make these properties optional in the transform ?

If above can be done, we can also avoid adding such properties during construction (see https://github.com/apache/beam/pull/30032) which would preserve upgrade compatibility.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #30534

Will wait until PostCommit https://github.com/apache/beam/actions/runs/8193778498 and https://github.com/apache/beam/actions/runs/8193799778 done

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @chamikaramj

**Review by chamikaramj — COMMENTED** [review]
Thanks. LGTM.

**Comment by Abacn** [comment]
strange, cherry pick cannot pass PreCommit Java Dataflow. But on master branch it had no issue

**Comment by Abacn** [comment]
```
"Error syncing pod, skipping" err="failed to \"StartContainer\" for \"java-batch\" with ImagePullBackOff: \"Back-off pulling
image \\\"gcr.io/cloud-dataflow/v1beta3/beam-java-batch:2.55.0\\\"\"" pod="default/df-testpipeline-runner-03072
03071557-igqr-harness-z9kd" podUID=c20e7b66b3c52efad073bb707b125c45
```

This is due to gcr.io/cloud-dataflow/v1beta3/beam-java-batch:2.55.0 does not exist yet. https://github.com/apache/beam/commit/1b03f8ed179b52580937e9b4a41efc8f0ba6fcc4

Seems this is always the case. So merge for now

**Pull request merged**
