### PR TITLE
Fix num workers

### PR DESCRIPTION
**Pull request by Amar3tto**
- Fixed num workers for `Pytorch Imagenet Classification with Resnet 152 with Tesla T4 GPU`, as the quota for the `apache-beam-testing` project is 32 T4 GPUs as of _November 28th, 2022_.
- Added InfluxDB envs

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
@Abacn We noticed that the current quota limit in the **"_us-central1_"** region is 48 **"NVIDIA T4 GPUs"** machines. The test seems passes successfully even with the less number of workers and the only difference is the execution time (e.g. [Jenkins run](https://ci-beam.apache.org/job/beam_Inference_Python_Benchmarks_Dataflow/398/consoleFull)). Do we need to increase quota limits or is it fine to reduce the number of workers?

**Comment by Abacn** [comment]
I'm good with the change. R: @AnandInguva who created this test

**Review by AnandInguva — APPROVED** [review]

**Comment by Abacn** [comment]
We probably still need Jenkins test - currently the GitHub Action job does not publish the metrics to InfluxDB:

```
WARNING:apache_beam.testing.load_tests.load_test_metrics_utils:Failed to publish metrics to InfluxDB. Received status code 401 with an error message: unable to parse authentication credentials
```

**Comment by Amar3tto** [comment]
> We probably still need Jenkins test - currently the GitHub Action job does not publish the metrics to InfluxDB:
> 
> ```
> WARNING:apache_beam.testing.load_tests.load_test_metrics_utils:Failed to publish metrics to InfluxDB. Received status code 401 with an error message: unable to parse authentication credentials
> ```

I returned the groovy file, and added InfluxDB envs that should fix publish metrics issue.
We can remove the groovy file later in the separate PR if everything will work as expected.

**Comment by Abacn** [comment]
Thanks!

**Comment by Amar3tto** [comment]
Run Inference Benchmarks

**Comment by Amar3tto** [comment]
Run Inference Benchmarks

**Comment by Amar3tto** [comment]
Run Inference Benchmarks

**Pull request merged**
