### PR TITLE
[BEAM-10496] Eliminate some null errors from sdks/java/core

### PR DESCRIPTION
**Pull request by kennknowles**
Re-activated nullness type checking for a portion of `org.apache.beam.sdk.values` namespace.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by kennknowles** [comment]
amusingly, NPEs in elasticsearch test, plus flaking in pulsar test and file io

**Comment by kennknowles** [comment]
Our flakes are driving me nuts - confirmed some of these tests seem OK locally. I'll rebase and push just to get any recent fixes and have to kick jenkins less.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
On https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5298/ we see failures

[org.apache.beam.sdk.io.gcp.datastore.RampupThrottlingFnTest.testRampupThrottler](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5298/testReport/junit/org.apache.beam.sdk.io.gcp.datastore/RampupThrottlingFnTest/testRampupThrottler/)
[org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped[0: DEADLINE_EXCEEDED]](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5298/testReport/junit/org.apache.beam.sdk.io.gcp.spanner/SpannerIOWriteExceptionHandlingTest/testExceptionHandlingForWriteGrouped_0__DEADLINE_EXCEEDED_/)

**Comment by kennknowles** [comment]
[Test Result](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5299/testReport/) (1 failure / -1)
[org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImplTest.testInsertWithinRowCountLimits](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5299/testReport/junit/org.apache.beam.sdk.io.gcp.bigquery/BigQueryServicesImplTest/testInsertWithinRowCountLimits/)

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by robertwb** [comment]
Any update on this PR?

**Comment by kennknowles** [comment]
Still waiting to find time to resolve conflicts and address comments.

**Review by kileys — APPROVED** [review]

**Comment by kennknowles** [comment]
Hrmm. One of the licenses that we download the server is down. bouncycastle.org

**Comment by kennknowles** [comment]
run java precommit

**Pull request merged**
