### PR TITLE
#21869: Close GRPC connections on cancel

### LINKED ISSUE #21869: [Bug]: [Go-SDK] Harness connections aren't cleaned up, leaving hanging goroutines
### What happened?

Run several tests in loopback mode or similar, this can leave a large number of grpc related goroutines dangling, since they're never cleaned up. 

This shouldn't be a problem during production runs as the worker is more likely to be terminated. However, an abundance of goroutines can make panic traces larger and harder to read, making other bugs harder to find. 

### Issue Priority

Priority: 3

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by lostluck**
Ensure that grpc channels are closed on context termination or other errors, to avoid leaking grpc goroutines.

Data and State now close their grpc channels on error. They already terminated goroutines, and handled multiplexing.
Logging, and sampler goroutines are now similarly cleaned up.

Makes the dial log clearer about purpose of the new connection.

Overall, only affects testing situations and simplifies local debugging by reducing additional goroutines.

Fixes #21869

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @youngoli

**Comment by lostluck** [comment]
Ping.

**Comment by lostluck** [comment]
assign set of reviewers

**Review by youngoli — APPROVED** [review]
Everything looks good to me.

**Pull request merged**
