### PR TITLE
[Website] Update from-spark page table content overflow

### LINKED ISSUE #22896: [Website]: Code in tables overflows on Getting Started from Spark page
### What happened?

On [Getting Started from Apache Spark](https://beam.apache.org/get-started/from-spark/), there are a couple of tables that contain code. If you view the page at small viewport widths (e.g. 393px for the Pixel 5 emulator), the code overflows the table and breaks the page layout. We should see if we can prevent that. Note that this may be fixed by a pending change.
Screen Shot 2022-08-25 at 1 02 08 PM

### Issue Priority

Priority: 2

### Issue Component

Component: website

### LINKED ISSUE #22914: [Bug]:
### What happened?

Steps to reproduce:

1. Open the website [page](https://beam.apache.org/get-started/from-spark/)
2. Scroll to the table Transforms
3. Change the screen size to 337px x 667px
4. Look at the screen width

Actual result: table content overflows and stretches the page
Expected result: table content overflow is handled and doesn't stretch the page
___________________________________________________________________________________________________________________________________
before_from_spark

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22896
- add table-container-wrapper to tables Setup and Transform on [from-spark page ](https://beam.apache.org/get-started/from-spark/)
------------------------
before:
before_from_spark
after:
after_from_spark
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by alevtinaboiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, review this PR?

**Review by pcoet — APPROVED** [review]
Thanks so much!

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please help with merge? PR was approved.

**Review by aromanenko-dev — APPROVED** [review]

**Pull request merged**
