### PR TITLE
Temporarily fix pip check failure on xgboost and grpcio

### LINKED ISSUE #31285: The PreCommit Python ML tests with ML deps installed job is flaky
The PreCommit Python ML tests with ML deps installed is failing over 50% of the time.
Please visit https://github.com/apache/beam/actions/workflows/beam_PreCommit_Python_ML.yml?query=is%3Afailure+branch%3Amaster to see all failed workflow runs.
See also Grafana statistics: http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1&viewPanel=7&var-Workflow=PreCommit%20Python%20ML%20tests%20with%20ML%20deps%20installed

### PR DESCRIPTION
**Pull request by shunping**
Originally, this PR is to pin pip to version 24.1, so that `pip check` would not fail on xgboost-1.7.6 and grpcio-1.66.1.

After some attempts, it seems it is a bit inconvenient to enforce pip version, especially inside the venv set up by tox.
 
Therefore, we decide to make the following changes
1) for xgboost, since we don't have any plan to invest further on it, we are going to remove it from deps.  After that, the xgboost related tests in the ML test suite will be skipped. We can put it back in the future if we decide to support xgboost again (https://github.com/apache/beam/issues/31252) .

2) for grpcio, the failure only occurs on MacOS, so we decide to skip `pip check` on MacOS until https://github.com/grpc/grpc/issues/37660 is fixed.

#fixes #31285

### CODE REVIEW

**Comment by shunping** [comment]
@tvalentyn @Abacn

**Comment by Abacn** [comment]
Note that the PR triggered workflow won't run on the change in `.github/`, which means the passed `Python tests / Python Unit Tests (macos-latest, ...) ` is passed without the changes of .github/workflows/python_tests.yml (and sdks/python/tox.ini) in this PR. Do we still need them?

**Comment by shunping** [comment]
> Note that the PR triggered workflow won't run on the change in `.github/`, which means the passed `Python tests / Python Unit Tests (macos-latest, ...) ` is passed without the changes of .github/workflows/python_tests.yml (and sdks/python/tox.ini) in this PR. Do we still need them?

Are you sure? I see the new tox environment I made from for macos is used in the tests. For example:
https://github.com/apache/beam/actions/runs/10821274842/job/30022967680?pr=32432

**Comment by Abacn** [comment]
ah you are right, I remembered there is this kind of limitation but looks like it does not applies to this specific test. Turns out the limitation applies to `pull_request_target` but not `pull_request` trigger

**Comment by shunping** [comment]
Also, I had changes in `setup.py` and I think Python tests will be triggered anyway.

**Review by damccorm — APPROVED** [review]
Thanks - lets just try to revert the mac pieces once grpc is ready

**Comment by shunping** [comment]
Thanks! I have created the task for reverting the mac change #32431.

**Pull request merged**
