### PR TITLE
[Website] Update case-studies logo images

### LINKED ISSUE #22799: [Bug]: Case studies logos stretching too much on mobile resolutions
### What happened?

Steps:

1. Open the website page https://beam.apache.org/case-studies/
2. Click on the button "Intuit" case-study card (https://beam.apache.org/case-studies/intuit/)
3. Find the left menu section with logo
4. Change the screen size to 620.60px x 693.6px
5. Take a look on the logo

Actual result: The logo is too wide
Expected result: the logo maintains proportions

Gif:
before_logos

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22799
- change css prop from width to max-width to fit logos with rectangle images, so it wouldn't stretch too much (Intuit, Paloalto, Ricardo, Seznam case-studies)
- add case-study-opinion-img-center class to center logos with narrow images (Hop, Lyft case-studies)
------------------------

before:
before_logos
after:
after_logos
after_2
after_3
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by alevtinaboiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, help with review of current PR?

**Review by pcoet — APPROVED** [review]

**Comment by bullet03** [comment]
@pabloem, could you, please, help with merging?

**Comment by bullet03** [comment]
@aromanenko-dev, could you, kindle help with merge? PR was approved.

**Comment by pabloem** [comment]
my apologies

**Pull request merged**
