### PR TITLE
[BEAM-2021] Re-add AtomicCoder

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Make Coder an abstract class instead of an interface.

Update CustomCoder parent to Coder. Move most StandardCoder 
behavior (not Component-Coder related) to Coder.

Parent all existing coders within the SDK which are AtomicCoders to
AtomicCoder, and those that are StructuredCoders but marked as a
CustomCoder to StructuredCoder.

### CODE REVIEW

**Comment by tgroh** [comment]
@kennknowles

**Comment by tgroh** [comment]
Fun fact - we have multiple coders which had over-accepting equals methods, which this change inverts (overly restrictive equals methods). Over-accepting is more dangerous, as workers should be able to use the equality methods in a meaningful sense.

Users who extend `StructuredCoder` are responsible for ensuring their coder conforms to the `StructuredCoder` contract. Users who extend `Coder` should (and will benefit from) implementing a meaningful `equals` and `hashCode` method, but are not required to do so.

**Comment by tgroh** [comment]
Also thinking about the name. "ConstantCoder"? "UnparameterizableCoder"? "ComponentlessCoder"? "SingletonCoder"?

**Comment by tgroh** [comment]
This will require a worker dance, as although the change to `Coder` is API-compatible, it is not binary-compatible

**Comment by tgroh** [comment]
I've split this into a few smaller commits, of which 	815e576 may be useful to re-review, given the recent activity on coder methods.

@kennknowles

**Comment by kennknowles** [comment]
This is nice. I think this PR shouldn't affect any runner.

**Pull request closed without merging**
