### PR TITLE
[BEAM-1224] Rename options.py to pipeline_options.py

### PR DESCRIPTION
**Pull request by mariapython**
options.py contains the class PipelineOptions (and other classes derived from it) and should be renamed pipeline_options.py for clarity. Its test file is pipeline_options_test.py.

### CODE REVIEW

**Comment by aaltay** [comment]
LGTM, please wait for all tests to pass.

**Comment by mariapython** [comment]
R: @charlesccychen

**Comment by mariapython** [comment]
R: @dhalperi 
Dan, please merge this.

**Comment by dhalperi** [comment]
LGTM. @mariapython or @aaltay please file JIRA and/or submit another PR to `beam-site`.

**Comment by dhalperi** [comment]
Merged.

**Comment by aaltay** [comment]
Thank you @dhalperi.

@mariapython, snippets are all(?) in the programming guide page, you can find them here:
https://github.com/apache/beam-site/blob/asf-site/src/documentation/programming-guide.md
http://beam.apache.org/documentation/programming-guide/

**Pull request closed without merging**
