### PR TITLE
[BEAM-831] ParDo Chaining in Apex Runner

### PR DESCRIPTION
**Pull request by tweise**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
R: @kennknowles 
based on #2216

### CODE REVIEW

**Comment by kennknowles** [comment]
run apex validatesrunner

**Comment by tweise** [comment]
Current logic is handling multiple inputs for side inputs, but not for flatten. Should be easy to fix.

**Comment by tweise** [comment]
run apex validatesrunner

**Comment by tweise** [comment]
run apex validatesrunner

**Comment by kennknowles** [comment]
LGTM. Ready to merge? Also cherry-pick and open a PR to the release.

**Comment by tweise** [comment]
Yes, please go ahead and merge.

**Pull request merged**
