### PR TITLE
[BEAM-6766] Add Sort Merge Bucket sink and join source

### PR DESCRIPTION
**Pull request by ClaireMcGinty**
Master ticket for the SMB work.
https://en.wikipedia.org/wiki/Sort-merge_join

BEAM issue: https://issues.apache.org/jira/browse/BEAM-6766

cc: @nevillelyh , @reuvenlax , @kanterov 

This is a first pass that successfully runs on DataflowRunner with test input. There are a few To-Do items listed below, as well as much more thorough/modular unit tests to write, but we wanted some feedback on this initial design before continuing.

Todo
- [ ] support compression
- [x] decouple intermediate layer e.g. `Metadata`, `FileOperations`, `BucketedInputIterator` for easy testing
- [x] work around `JsonSubTypes` limit in `BucketMetadata`
- [ ] reuse temp directory logic in `FileBasedSink`
- [ ] reuse file handling logic in `FileBasedSink`
- [x] support mixing sources of different number of buckets
- [ ] how to provide better hints to auto-scaling so runners can pick better initial `numWorkers` instead of one
- [ ] Cleanup temp files after failed writes
- [x] (Potentially) Option to shard files per bucket based on a target file byte size, in case of unexpectedly skewed bucket sizes.
- [ ] Make Iterables in `SMBCoGbkResult` truly lazy
- [ ] Support nullable keys, with the assumption most users won't be interested in including them in the join results (some options: 1) write all nulls to a separate bucket, easy to ignore at join time; 2) don't write to a separate bucket, but include a "allowNullableKeys" field in `BucketMetadata` to identify whether keys are encoded with `NullableCoder` or not; 3) wrap all keys in `NullableCoder`. We're leaning toward (1). )

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by nevillelyh** [comment]
R: @reuvenlax

**Comment by kanterov** [comment]
I can take a look on Tuesday. Before the review, please check out PTransform style guide [1] and dependencies guide [2] and testing guide [3], if you didn't find it yet.

[1]: https://beam.apache.org/contribute/ptransform-style-guide/
[2]: https://beam.apache.org/contribute/dependencies/
[3]: https://cwiki.apache.org/confluence/display/BEAM/Contribution+Testing+Guide

**Comment by nevillelyh** [comment]
Some extra considerations.

Ones that will affect backwards compatibility:
- [ ] version in metadata, so we can reject joining data written by incompatible SMB versions
- [ ] explicit bucket->`numShards` mapping in metadata, in order to have variable `numShards`

Ones that are nice to have but can be added safely:
- [ ] multiple (date/hour) partitions of any input source, e.g. when joining events with lookup table
- [ ] determine `numBuckets` automatically
- [ ] determine `numShards` (per bucket) automatically

**Comment by ClaireMcGinty** [comment]
@nevillelyh Re: versioning the metadata. If we wrote the version as, say the Beam version we'd have to add extra logic to specify which Beam versions have compatible SMB implementations, which seems undesirable... we could also use just a monotonic integer or something like serial version ID and increment that when there's a breaking change. Or store information like sharding/bucketing strategy as String enums and compare those. However, I'm concerned about the implementation of SMB having truly backwards-incompatible changes across Beam versions--if the only way to read old SMB data is for the user to downgrade Beam I think that's a bit scary. Ideally at least all SMB reads are backwards-compatible, even if they're a bit less performant with older data. Wdyt?

**Comment by nevillelyh** [comment]
Agree on monotonic integer versioning. Seems the simplest. If necessary we can branch in reader code path to handle old data, assuming there shouldn't be many breaking changes?

**Comment by ClaireMcGinty** [comment]
cool! I can't envision many truly breaking changes in sharding strategy that would affect reads...e.g. dynamic # of shards per bucket shouldn't really impact reads. A sharding strategy based on target byte size rather than a random split is the main breaking change I can think of. It would be nice to support multiple sharding strategies with a reasonable default, and encode that in metadata, but the implementations are so different it's hard to envision how we could abstract it.

**Comment by ClaireMcGinty** [comment]
Closing this PR so we can focus on smaller, more granular PRs. We'll keep implementation details updated in the [design doc](https://docs.google.com/document/d/1AQlonN8t4YJrARcWzepyP7mWHTxHAd6WIECwk1s3LQQ/edit?usp=sharing).

**Pull request closed without merging**
