### PR TITLE
Pushes format function to lowest level in BigQueryIO

### PR DESCRIPTION
**Pull request by jkff**
This likely shuffles a lot fewer data, and also will at some point allow using a format function that formats to an Avro GenericRecord, rather than to the inefficient JSON TableRow. (though that will be usable only with BATCH_LOADS method, but that's fine)

Also makes sure that getSchema() is called once per destination rather than once per element (https://issues.apache.org/jira/browse/BEAM-3083).

R: @steveniemitz 
CC: @reuvenlax

### CODE REVIEW

**Comment by reuvenlax** [comment]
Is this update safe?

**Comment by jkff** [comment]
Unfortunately I can only give the same answer as in previous BigQueryIO refactorings: it's most likely not update-safe, but there also most likely is no way to get where we want to be while keeping it update-safe, and I'm suggesting to ignore this issue because we don't have a general approach to making any but trivial changes update-safe, nor a strict requirement to do that.

**Comment by reuvenlax** [comment]
We should think about this then. This transform is largely used by Dataflow
users, many of whom do rely on update. It is also probably the most common
sink used by streaming Dataflow users, so we risk making the majority of
pipelines not updatable. The previous time I believe we were able to limit
the scope sufficiently.

**Comment by aaltay** [comment]
What is the plan for this PR?

**Comment by jkff** [comment]
I'm going to isolate the getSchema() optimization part of this PR and revert other things until I (or someone else) have time to figure out how to deal with update incompatibility.

**Comment by jkff** [comment]
Mostly superseded by #4493. I'm going to close this PR. It's useful but I don't have time to work on it.

**Pull request closed without merging**
