### PR TITLE
[BEAM-13980] Re-add method gone missing in af2f8ee6

### PR DESCRIPTION
**Pull request by phoerious**
`get_object_metadata()` went missing in 2.36.0. This PR adds it back.

Fixes BEAM-13980

R: @mosche @aaltay

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/validate-runner/README.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by aaltay** [comment]
Could you also please fix the tests?

**Comment by phoerious** [comment]
The tests are not failing because of this change. There's some timeout on the CI side. I suppose you just need to retrigger them.

**Comment by phoerious** [comment]
There you go. Hope the previously failing tests pass this time.

**Review by aaltay — APPROVED** [review]

**Comment by aaltay** [comment]
It LGTM. I will merge it.

Question: How did you notice this? And would it be possible to add a test to catch this and similar issues?

**Comment by aaltay** [comment]
Actually, I do not see all precommit tests being triggered.

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
(Jenkins CI issues are impacting this PR and probably all PRs.)

**Comment by aaltay** [comment]
@tvalentyn - Should we merge PRs or wait for ci to come back? (I am guessing GH tests will at least cover lint and basic unit tests.)

**Comment by phoerious** [comment]
> Question: How did you notice this?

I noticed it, because my job suddenly failed with a "no such attribute" error after updating to the lastest Beam image. I have no idea why that method got deleted. It certainly wasn't deleted on my local copy, because that one worked when I tested it. But somehow it made it into the final diff and nobody noticed.

**Comment by mosche** [comment]
> I am guessing GH tests will at least cover lint and basic unit tests.

@aaltay there's pretty much no unit test coverage at all as discussed previously. As said I'm not familiar with the python api at all and don't know if this is a general pattern. but imho this is a serious issue...

**Comment by phoerious** [comment]
Also, so far nobody else has complained on Jira as far as I can tell, so there doesn't seem to be much user coverage eitehr.

**Comment by aaltay** [comment]
I remember we had the code coverage discussion. I agree it is a serious issue. I am not familiar with this part of the code path either but I agree that this is not great.

I will still merge this change because it looks like an obvious regressions to remove a method.

**Comment by kennknowles** [comment]
This seems worth a cherrypick?

**Comment by TheNeuralBit** [comment]
> This seems worth a cherrypick?

agreed

**Pull request merged**
