### PR TITLE
[BEAM-3182] [Nexmark][SQL] Implement query 5

### PR DESCRIPTION
**Pull request by apilloud**
This implements Nexmark query 5 in SQL.

[Java version of the same query](https://github.com/apache/beam/blob/1488cb90a69ee2bf3adc43f7157ba3641ed3e04d/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/Query5.java#L55)

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand:
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.

### CODE REVIEW

**Comment by akedin** [comment]
run java gradle precommit

**Comment by akedin** [comment]
LGTM

**Comment by akedin** [comment]
run java maven precommit

**Comment by kennknowles** [comment]
Yup, looks good. Known issue with charset. I'll just run the tests one more time to make sure that didn't mask anything since it is the SQL module after all.

**Comment by kennknowles** [comment]
run java precommit

**Comment by apilloud** [comment]
@kennknowles java is green now.

**Comment by apilloud** [comment]
Rebased and all green now.

**Pull request merged**
