### PR TITLE
Allow streaming mobile examples to read from either a topic or a subscription

### PR DESCRIPTION
**Pull request by mariapython**

### CODE REVIEW

**Comment by mariapython** [comment]
retest this please

**Comment by charlesccychen** [comment]
Thanks! Do we want to do `sys.exit(1)` here, like the other places this pattern is used?

**Comment by mariapython** [comment]
R: @charlesccychen 
Yes, thanks!

**Comment by mariapython** [comment]
retest this please

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

**Pull request merged**
