### PR TITLE
Revert "[BEAM-11659] Extract common payload serialization behavior for Row transforms."

### PR DESCRIPTION
**Pull request by amaliujia**
Reverts apache/beam#13825

### CODE REVIEW

**Comment by amaliujia** [comment]
Run Java PreCommit

**Comment by amaliujia** [comment]
Java precommit is flaky.

**Review by TheNeuralBit — APPROVED** [review]
LGTM, thanks Rui

**Comment by dpcollins-google** [comment]
Please prefer https://github.com/apache/beam/pull/13963 to this?

**Comment by TheNeuralBit** [comment]
> Please prefer #13963 to this?

As long as we can finish #13963 before the release cut, this is fine with me.

**Comment by TheNeuralBit** [comment]
(and FYI the next release cut isn't until 10 March according to the release calendar, so there's plenty of time)

**Pull request closed without merging**
