### PR TITLE
[BEAM-3108] Align names with those produced by the dataflow runner harness.

### PR DESCRIPTION
**Pull request by aaltay**
CP ec192d15d3e83d6fe2127619c8bbd69e83277918 and d91ebd9f5fa3cf5c250f02096c27c21354dce859 from https://github.com/apache/beam/pull/3941

R: @reuvenlax 
cc: @robertwb

### CODE REVIEW

**Comment by reuvenlax** [comment]
Tests still failing. Is this part of the wider test issue?

**Comment by aaltay** [comment]
Yes, this is part of a wider issue. Python tests here and in other PRs in the release branch are failing with a Jenkins error (`java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer`). This happens before executing any python tests.

Java test failures looks more like a flake and unrelated to this PR.

**Comment by aaltay** [comment]
Python test failures seemingly started after running the seed job (https://github.com/apache/beam/pull/4045). After that only the jobs that run on beam3 node succeeded, and all other jobs executed on beam8 node and failed with the above error.

@jasonkuster I vaguely remember beam1-3 nodes having a different setup. Is this still true?

cc: @lukecwik

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Comment by aaltay** [comment]
retest this please

**Comment by reuvenlax** [comment]
RuntimeError being thrown during test?

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
python post commit failed because it executed using master branch code: https://issues.apache.org/jira/browse/BEAM-3120

java pre-commit failed because it executed on the bad worker (beam8). There are no java related changes here.

I think this is ready to merge. Could you PTAL?

**Comment by reuvenlax** [comment]
lgtm

**Pull request closed without merging**
