### PR TITLE
[BEAM-5467] Log job server termination.

### PR DESCRIPTION
**Pull request by tweise**
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
@robertwb since I was suspecting that the segmentation faults may have something to do with how we run the job server, I added the logging. I was able to reproduce the segmentation fault with this change (you usually get it in one of five runs):
```
[flink-runner-job-server] INFO org.apache.beam.runners.flink.FlinkRunner - Execution finished in 9755 msecs
.INFO:root:Job server terminated.

----------------------------------------------------------------------
Ran 26 tests in 220.072s

OK (skipped=7)
Segmentation fault (core dumped)

> Task :beam-sdks-python:flinkCompatibilityMatrixBatchDOCKER FAILED
:beam-sdks-python:flinkCompatibilityMatrixBatchDOCKER (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 3 mins 47.265 secs.
:beam-sdks-python:flinkCompatibilityMatrixStreamingDOCKER (Thread[Task worker for ':' Thread 3,5,main]) started.
```
https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink_PR/71/

This excludes the job server as suspect. It rather points to the Python process crashing, after all unit tests run. Please take a look. Is it possible that in the Jenkins environment we are loading additional/different dependencies that cause this?

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
Run Python Flink ValidatesRunner

**Comment by tweise** [comment]
@robertwb I wonder if the segmentation faults are in any way related to the `signal.alarm(0)` in `tearDown`. That gets executed after the summary line was printed. I added an override here.

**Comment by robertwb** [comment]
If we disable canceling the alarm on teardown, we should probably also disable it on setup.

**Pull request closed without merging**
