### PR TITLE
GA Migration PostCommit Javadoc

### PR DESCRIPTION
**Pull request by MarcoRob**
`DO NOT MERGE` 

As part of the migration of Precommit and Postcommit Jobs from Jenkins to GA in self-hosted runners, this PR contains:

- Migrated workflow **job-precommit-javadoc.yml**

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by MarcoRob** [comment]
Hi @damccorm 
I am reaching out to get feedback on this job, we previously discussed it with @kerrydc to leave it to the bottom of the queue since we have the following issue:
- The [Javadoc in Jenkins](https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Javadoc/) uses some plugins to get reports of warnings like compilation issues and warnings and display the Javadoc site. So when we migrated the job to GitHub Actions, we were unable to fully migrate the job since the plugins don't exist in GA.

We want to check if the job can be left in Jenkins and think of a plan of action for the next steps regarding this job?

We currently have some alternatives like:
- We found there is a GitHub action which [publish the javadoc](https://github.com/MathieuSoysal/Javadoc-publisher.yml) in the [Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site) inside the current repository into another branch but it requires to enable the GitHub pages. Or we could export the Javadoc dir, so it could be downloaded as an artifact inside the GA.
- And for the Javadoc warnings metrics, it could be possible to get the data and push it to InfluxDB and connect it with Grafana. But for this one is just a concept at this point or an idea to solve the issue.

**Comment by damccorm** [comment]
> The [Javadoc in Jenkins](https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Javadoc/) uses some plugins to get reports of warnings like compilation issues and warnings and display the Javadoc site. So when we migrated the job to GitHub Actions, we were unable to fully migrate the job since the plugins don't exist in GA.

**"display the Javadoc site"** To be clear, this doesn't actually publish the javadoc to the beam website, right? Or does it? What do you mean by display the Javadoc site?

> We found there is a GitHub action which [publish the javadoc](https://github.com/MathieuSoysal/Javadoc-publisher.yml) in the [Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site) inside the current repository into another branch but it requires to enable the GitHub pages. Or we could export the Javadoc dir, so it could be downloaded as an artifact inside the GA.

Assuming this is just for developer purposes I think publishing it as an artifact is probably fine.

> And for the Javadoc warnings metrics, it could be possible to get the data and push it to InfluxDB and connect it with Grafana. But for this one is just a concept at this point or an idea to solve the issue.

@apilloud do you know if anyone uses these metrics? In general, would just appreciate your thoughts on what our requirements for this job actually should be.

**Comment by MarcoRob** [comment]
> > The [Javadoc in Jenkins](https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Javadoc/) uses some plugins to get reports of warnings like compilation issues and warnings and display the Javadoc site. So when we migrated the job to GitHub Actions, we were unable to fully migrate the job since the plugins don't exist in GA.
> 
> **"display the Javadoc site"** To be clear, this doesn't actually publish the javadoc to the beam website, right? Or does it? What do you mean by display the Javadoc site?
> 
>>> @damccorm **No, it doesn't; I mean, the job generates the javadoc HTML files and then you can access them through the Jenkins job site to take a look at the generated doc.** 


> > We found there is a GitHub action which [publish the javadoc](https://github.com/MathieuSoysal/Javadoc-publisher.yml) in the [Github Pages](https://github.com/marketplace/actions/deploy-github-pages-site) inside the current repository into another branch but it requires to enable the GitHub pages. Or we could export the Javadoc dir, so it could be downloaded as an artifact inside the GA.
> 
> Assuming this is just for developer purposes I think publishing it as an artifact is probably fine.
> 
> > And for the Javadoc warnings metrics, it could be possible to get the data and push it to InfluxDB and connect it with Grafana. But for this one is just a concept at this point or an idea to solve the issue.
> 
> @apilloud do you know if anyone uses these metrics? In general, would just appreciate your thoughts on what our requirements for this job actually should be.

**Comment by damccorm** [comment]
@apilloud or @kileys could you weigh in on this one - I'm not totally sure what this job is doing so I'll have a hard time giving a good review (see comments above)

**Comment by kileys** [comment]
AFAIK, no one looks at the metrics and it's not worth the effort to migrate (if not available). This test was to check for build errors before the release.

**Pull request closed without merging**
