### PR TITLE
Add single job to run python coverage

### PR DESCRIPTION
**Pull request by damccorm**
Right now, the coverage report is repeatedly overwritten by the sharded out precommit jobs (thanks Yi for [the report](https://github.com/apache/beam/pull/24866#issuecomment-1379520978)). This should fix the problem by only running coverage in a single job which will run over the entire sdk.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
Run seed job

**Comment by damccorm** [comment]
Run Seed Job

**Comment by damccorm** [comment]
Run Python_Coverage PreCommit

**Comment by damccorm** [comment]
Run Python_Runners PreCommit

**Comment by damccorm** [comment]
Run Python PreCommit

**Comment by damccorm** [comment]
R: @Abacn

**Review by Abacn — APPROVED** [review]
Validated by the above codecov comment "Merging #24988 (a41b9a4) into master (ad4410a) will increase coverage by 10.10%."

**Comment by damccorm** [comment]
Docs precommit is currently broken, ignoring that for the moment.

**Pull request merged**
