### PR TITLE
Adding a custom coder test

### PR DESCRIPTION
**Pull request by pabloem**
This test has been ported from an internal Dataflow test to a general test in Beam.

r: @boyuanzz

### CODE REVIEW

**Comment by pabloem** [comment]
Ah dang we don't have tests... that's terrible. FWIW, this passes `:beam-sdks-java-core:check` and `:beam-runners-direct-java:needsRunnerTests`.

**Comment by pabloem** [comment]
Currently these tests will run only over direct runner, but should be enabled to run on the ULR, which should give the test coverage we're looking for.

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Run Gradle Publish

**Comment by boyuanzz** [comment]
gradle rat failed: https://scans.gradle.com/s/nzwfwj6iqlgrg/console-log?task=:rat

**Comment by pabloem** [comment]
@boyuanzz you ran gradle publish before I added the license. The newest precommit already runs rat, and it passed.

**Comment by huygaa11** [comment]
friendly ping for review!

**Comment by pabloem** [comment]
@boyuanzz

**Pull request merged**
