### PR TITLE
Fix Kafka performance test sourceOption to match expected hash

### LINKED ISSUE #22944: [Bug]: Kafka Performance Tests actually failing but not marked as failed on Jenkins
### What happened?

Grafana dashboard shows zero read time of kafkaIO | 1 GB:
image
Taking a closer look to the log, the Dataflow job actually failed:
```
Aug 29, 2022 1:06:01 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:06:01     SEVERE: 2022-08-29T13:06:00.196Z: Workflow failed. Causes: S01:Generate records+Measure write time+Write to Kafka/Kafka ProducerRecord/Map+Write to Kafka/KafkaIO.WriteRecords/ParDo(KafkaWriter) failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these ****s: 
09:06:01 
09:06:01       kafkaioit0testkafkaioread-08290559-7f48-harness-wvf0
09:06:01           Root cause: Work item failed.,
09:06:01 
09:06:01       kafkaioit0testkafkaioread-08290559-7f48-harness-4gm7
09:06:01           Root cause: Work item failed.,
09:06:01 
09:06:01       kafkaioit0testkafkaioread-08290559-7f48-harness-m1h9
09:06:01           Root cause: Work item failed.,
09:06:01 
09:06:01       kafkaioit0testkafkaioread-08290559-7f48-harness-t0qh
09:06:01           Root cause: Work item failed.
09:06:01     Aug 29, 2022 1:06:01 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:06:01     INFO: 2022-08-29T13:06:00.262Z: Cleaning up.
09:06:01     Aug 29, 2022 1:06:01 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:06:01     INFO: 2022-08-29T13:06:00.350Z: Stopping **** pool...
09:08:16     Aug 29, 2022 1:08:16 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:08:16     INFO: 2022-08-29T13:08:15.939Z: Autoscaling: Resized **** pool from 5 to 0.
09:08:16     Aug 29, 2022 1:08:16 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:08:16     INFO: 2022-08-29T13:08:15.989Z: Worker pool stopped.
09:08:29     Aug 29, 2022 1:08:29 PM org.apache.beam.runners.dataflow.DataflowPipelineJob logTerminalState
09:08:29     INFO: Job 2022-08-29_05_59_45-207371049498193911 failed with status FAILED.

...

Kafka/KafkaIO.Read.ReadFromKafkaViaUnbounded/Read(KafkaUnboundedSource)/Reshuffle/Reshuffle/GroupByKey/Write failed., The job failed because a work item has failed 4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information, see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these ****s: 
09:10:35 
09:10:35       kafkaioit0testkafkaioread-08290608-wu0a-harness-1nt9
09:10:35           Root cause: Work item failed.,
09:10:35 
09:10:35       kafkaioit0testkafkaioread-08290608-wu0a-harness-1nt9
09:10:35           Root cause: Work item failed.,
09:10:35 
09:10:35       kafkaioit0testkafkaioread-08290608-wu0a-harness-mmtp
09:10:35           Root cause: Work item failed.,
09:10:35 
09:10:35       kafkaioit0testkafkaioread-08290608-wu0a-harness-mmtp
09:10:35           Root cause: Work item failed.
09:10:35     Aug 29, 2022 1:10:35 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:10:35     INFO: 2022-08-29T13:10:34.131Z: Cleaning up.
09:10:35     Aug 29, 2022 1:10:35 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:10:35     INFO: 2022-08-29T13:10:34.248Z: Stopping **** pool...
09:12:43     Aug 29, 2022 1:12:43 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:12:43     INFO: 2022-08-29T13:12:41.822Z: Autoscaling: Resized **** pool from 5 to 0.
09:12:43     Aug 29, 2022 1:12:43 PM org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler process
09:12:43     INFO: 2022-08-29T13:12:41.930Z: Worker pool stopped.
09:13:19     Aug 29, 2022 1:13:19 PM org.apache.beam.runners.dataflow.DataflowPipelineJob logTerminalState
09:13:19     INFO: Job 2022-08-29_06_08_39-15433867759668129710 failed with status FAILED.
09:13:19 
09:13:19 org.apache.beam.sdk.io.kafka.KafkaIOIT > testKafkaIOReadsAndWritesCorrectlyInBatch STANDARD_OUT
09:13:19     Load test results for test (ID): 1cfab208-e4d1-4262-9a47-a8cfa54e8d8a and timestamp: 2022-08-29T12:59:31.874000000Z:
09:13:19                      Metric:                    Value:
09:13:19                    read_time                       0.0
09:13:19                   write_time                    13.829
09:13:19                     run_time                    13.829
09:13:20 
09:13:20 Gradle Test Executor 1 finished executing tests.
```

It can be seen that write has failed and read never happens, which explains the zero read_time. However, the jenkins job still marked as Pass.

Taking a look at the source code, `writeResult.waitUntilFinish();` does not follow an assert of job succeeded. Gradle then does not detect job failing.

Other performance test jobs may have the same issue.

### Issue Priority

Priority: 2

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by Abacn**
Finally Fixes #22944

~Hash were obtained from #23270 with pipeline bypassing kafka (generate records directly and calculate hash)~

Hash assertion fail because performance test used different sourceOption (1 byte key size) than the expected hash (10 bytes key size)

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java KafkaIO Performance Test

**Comment by Abacn** [comment]
Java_Kafka_IO_Direct and Java KafkaIO Performance Test used different key size in sourceOptions that's why hash was not the same.

**Comment by johnjcasey** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
> It looks like this causes the batch tests to fail though

Found the precommit and performance test used different sourceOption. Change the performance test to be the same as precommit should fix.

**Comment by Abacn** [comment]
R: @johnjcasey PTAL, thanks!

**Pull request merged**
