### PR TITLE
[BEAM-3357] Add generated pb2 files to mvn clean.

### PR DESCRIPTION
**Pull request by udim**

### CODE REVIEW

**Comment by udim** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM. (This looks unrelated to the issue in mentioned in the title.)

**Comment by udim** [comment]
If you tried to build in a repo affected by the issue and it generated pb2 files, then you'd still get an error until you forced their regeneration.

**Comment by aaltay** [comment]
Is the Java failure related to this change?

**Comment by udim** [comment]
jenkins: retest this please

**Comment by udim** [comment]
I am 95% sure that these Java failures are unrelated.
%5 unsure because I haven't seen these Java failures before.

**Comment by aaltay** [comment]
LGTM. I will merge. (For the 5% please pay attention to mailing list, in case this merge causes for failures for others.)

**Pull request merged**
