### PR TITLE
Remove brackets from lambdas with a single parameter

### PR DESCRIPTION
**Pull request by coheigea**
Brackets are optional with lambdas when we have a single parameter, removing them makes the code more concise and readable.

### CODE REVIEW

**Comment by kennknowles** [comment]
I believe the failed test was run at a time when it did not work.

**Comment by kennknowles** [comment]
Run Java PortabilityApi PreCommit

**Comment by lukecwik** [comment]
Kenn, the Jenkins job was renamed from `Run Java PortabilityApi PreCommit` to `Run JavaPortabilityApi PreCommit`, so if the latter passes we are good.

**Comment by kennknowles** [comment]
Curiously that latter did trigger after https://github.com/apache/beam/pull/6900#issuecomment-435534719, before I requested the re-run of the wrong thing. Anyhow all looks green, so LGTM and I'll merge.

**Pull request merged**
