### PR TITLE
[BEAM-14138] Revert "[BEAM-14112] Avoid storing a generator in _CustomBigQuerySource"

### PR DESCRIPTION
**Pull request by chamikaramj**
Reverts apache/beam#17100

Caused Python PostCommit to fail: https://ci-beam.apache.org/job/beam_PostCommit_Python38/2407/

### CODE REVIEW

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
R: @tvalentyn @chunyang @KevinGG

**Comment by tvalentyn** [comment]
LGTM

**Comment by chamikaramj** [comment]
Thanks.

**Pull request merged**
