### PR TITLE
[WIP] Change PubsubIO sinks to use the proto message in their interfaces.

### PR DESCRIPTION
**Pull request by dpcollins-google**
Also add WriteWireMessages to PubsubIO.

Diffbased on #10480

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by dpcollins-google** [comment]
+R: @boyuanzz

I'm going to need some help with this one- I know the dataflow runner overrides PubsubUnboundedSink, but I don't know where whatever the dataflow wire format is is converted to the individual messages in the transformed PCollection.  Can you point me in the right direction?

**Comment by boyuanzz** [comment]
> +R: @boyuanzz
> 
> I'm going to need some help with this one- I know the dataflow runner overrides PubsubUnboundedSink, but I don't know where whatever the dataflow wire format is is converted to the individual messages in the transformed PCollection. Can you point me in the right direction?

@chamikaramj Hey Cham, could you please help answer this question? Thanks for your help!

**Comment by boyuanzz** [comment]
> I'm going to need some help with this one- I know the dataflow runner overrides PubsubUnboundedSink, but I don't know where whatever the dataflow wire format is is converted to the individual messages in the transformed PCollection. Can you point me in the right direction?
> 
Hope following pointers would be helpful:

- [dataflow runner enables overrides](https://github.com/apache/beam/blob/e4a3594c69210706c00a0e13f11c2e21000a3cea/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java#L428)

- [StreamingPubsubIOWriteOverrideFactory](https://github.com/apache/beam/blob/e4a3594c69210706c00a0e13f11c2e21000a3cea/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java#L1836) This class creates `StreamingPubsubIOWrite` to replace `PubsubUnboundedSink`

- [StreamingPubsubIOWrite](https://github.com/apache/beam/blob/e4a3594c69210706c00a0e13f11c2e21000a3cea/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java#L1302) gives a different implementation of `PTransform.expand`

- [StreamingPubsubIOWriteTranslator](https://github.com/apache/beam/blob/e4a3594c69210706c00a0e13f11c2e21000a3cea/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java#L1318) tanslates `StreamingPubsubIOWrite` into dataflow internal representation

**Comment by chamikaramj** [comment]
Don't have much context on this change. Is there a JIRA ?

In general, Dataflow overrides the PubSub source/sink implementations with a native version that is implemented in the Dataflow service.

**Comment by dpcollins-google** [comment]
> In general, Dataflow overrides the PubSub source/sink implementations with a native version that is implemented in the Dataflow service.

Basically, I'm trying to figure out where I need to modify if I change the input type of the PubsubUnboundedSink from PCollection<PubsubMessage> to PCollection<google.pubsub.v1.PubsubMessage>, or if that would be even possible.

How does the client's code send a (beam) PubsubMessage to dataflow? StreamingPubsubIOWriteTranslator doesn't seem to address this. Is it serialized into some other representation or is something more magical going on?

**Comment by dpcollins-google** [comment]
Closing, needs to be entirely rewritten

**Pull request closed without merging**
