### PR TITLE
[BEAM-1871] Move GCP specific serialization CloudObject and supporting translation code to Dataflow runner module

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @dhalperi @kennknowles

**Comment by lukecwik** [comment]
Run Dataflow ValidatesRunner

**Comment by dhalperi** [comment]
Confirming: This is taking code that only DataflowRunner uses and either moving it into Dataflow module or deleted it entirely. Looks awesome to me!

**Comment by lukecwik** [comment]
@dhalperi That is correct.

**Comment by kennknowles** [comment]
So much deletion. So happy.

**Comment by lukecwik** [comment]
The build succeeded https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/10664 but reported failure to Jenkins because it was married with a build in 10665 which seems unrelated.

**Comment by lukecwik** [comment]
retest this please

**Pull request closed without merging**
