### PR TITLE
[BEAM-6630] upgrade to gradle 5.2

### PR DESCRIPTION
**Pull request by adude3141**
Upgrade to the latest gradle 5.2.1

This will
- reenable the build cache, i.e. test results will be cacheable again. 
- unlock java11 support

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by adude3141** [comment]
R: @swegner

**Comment by adude3141** [comment]
We need to fix
- https://issues.apache.org/jira/browse/BEAM-6634
- https://issues.apache.org/jira/browse/BEAM-6635

**Comment by swegner** [comment]
Exciting! Some other features that 5.0 brings which we might find useful:

* ["**Production ready" Kotlin DSL**"](https://docs.gradle.org/5.0/release-notes.html#kotlin-dsl-1.0). According to [Google trends](https://trends.google.com/trends/explore?date=today%205-y&q=%2Fm%2F0_lcrx4,%2Fm%2F02js86), Kotlin is now more popular than Groovy with much greater momentum. We haven't had great contributor adoption working on the Gradle build; perhaps moving to a more palatable language would help. /cc @kennknowles 
* [**Dependency-version alignment**](https://docs.gradle.org/5.0/release-notes.html#dependency-version-alignment) This allows using consistent dependency versions defined in a Maven BOM file /cc @garrettjonesgoogle
* [**Jacoco parallel test execution support**](https://docs.gradle.org/5.0/release-notes.html) This should make it easier to collect code coverage across our many test suites. /cc @Ardagan

**Comment by kennknowles** [comment]
Definitely excited to try the Kotlin DSL. Even better than just getting types, it is getting one of the most modern type systems available in a mainstream language.

**Comment by adude3141** [comment]
Run Java PostCommit

**Comment by adude3141** [comment]
@swegner 
Unless u have more test in mind we should run before merging, I d say we should merge.

**Comment by adude3141** [comment]
Thx, @swegner 

Will monitor next few Jenkins build to see which impact this has.

**Comment by swegner** [comment]
> Will monitor next few Jenkins build to see which impact this has.

I skimmed through the Jenkins jobs that run continuously; I don't see anything broken, and the only significant execution time diff I noticed is [`beam_PostCommit_Java_ValidatesRunner_Flink`](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/buildTimeTrend):

image

Before ([#3174](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/3174/)): 16min, after ([#3175](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/3175/)): 8min.

Comparing the Gradle scans ([before](https://scans.gradle.com/s/eyniu3ovxijik), [after](https://scans.gradle.com/s/yrqwt6ki77is4)), the `:beam-runners-flink_2.11:validatesRunnerBatch` task is dramatically faster (12min -> 2.5 min). The scans show we're still running the same number of tests (475 in both cases), so I believe this is actual improvement.

I wonder what the cause of the improvement is; maybe the differences in how Gradle allocated memory to the test tasks? /cc @mxm @tweise

**Comment by adude3141** [comment]
Hmm... nice.

Unfortunately, I have now idea how this is (or even could be) related to the gradle upgrade. We probably reduced memory available to the test jvm (was: 1/4th of physically available mem, is: 2G). I assume, we do have more than 8G on the Jenkins agents, but I did not find yet any documentation on that.

Even if mem would be increased now - and test jvm was gc'ing all the time, I have no idea, why batch should require significantly more memory compared to streaming?

**Comment by mxm** [comment]
Thanks for sharing @swegner. That's indeed an interesting change. It could come from the batch algorithms spilling to disk which is terribly slow compared to processing everything in memory. I've seen deletion of spilling directories while running tests.

Looking at the tests, it is surprising some of them take so long. There is room for improvement because every test brings up a mini Flink cluster at the moment. Some form of caching would be desirable.

**Comment by swegner** [comment]
One hypothesis: the overall reduction in Gradle task memory usage has left more available memory for the local Flink cluster. It's to say for sure, the Gradle scan doesn't give a whole lot of context.

At any rate, the improvement has stuck over the last 15 runs, and the [first run showing improvement](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/3175/) only has the Gradle 5 upgrade in the delta.

**Comment by angoenka** [comment]
The apex validate runner test has started to fail since this change https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/buildTimeTrend 
The gradle scans and the logs are not very useful.

**Comment by adude3141** [comment]
I ll have a look. Thank you very much for reporting.

**Comment by adude3141** [comment]
Opened https://github.com/apache/beam/pull/7861 to fix Apex Runner failing with OutOfMemoryError.

**Comment by adude3141** [comment]
Yet another one:
https://issues.apache.org/jira/browse/BEAM-6698

Any hint whom to ask about that portable runner flink stuff?

**Comment by mxm** [comment]
Please ask me :) Also `@angoenka`, `@tweise`, `@ryan-williams`, `@robertwb` (quoted to avoid pinging them here).

**Comment by adude3141** [comment]
thx @mxm... will try to understand what's going on there and come back to ask questions

**Comment by aaltay** [comment]
Release publish fails with this change. Reverting one commit (https://github.com/apache/beam/pull/7787/commits/cadb6f7fabc6faedc6037104338306688f17652f) to downgrade gradle resolves the issue: https://issues.apache.org/jira/browse/BEAM-6726

**Pull request merged**
