### PR TITLE
Pass getattr calls in AbstractDoFnWrapper to the wrapped dofn for stateful dofns.

### PR DESCRIPTION
**Pull request by jonathanasdf**
Otherwise there is an error

```
  File "/private/tmp/beam/sdks/python/apache_beam/transforms/userstate.py", line 304, in validate_stateful_dofn
    if (timer_spec._attached_callback != getattr(dofn, method_name,
AttributeError: 'NoneType' object has no attribute '__func__'
```

R: @charlesccychen 

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by jonathanasdf** [comment]
R: @charlesccychen

**Comment by jonathanasdf** [comment]
bump

**Comment by AnandInguva** [comment]
I will go ahead and review this. I suspect the reviewer you tagged is not active in Beam

**Comment by jonathanasdf** [comment]
Thanks, it was the only choice from https://github.com/apache/beam/blob/master/sdks/python/apache_beam/typehints/OWNERS maybe that should be updated.

**Comment by AnandInguva** [comment]
@jonathanasdf Hi sorry, This was slipped from my plate. Is this still relevant?

**Pull request closed without merging**
