### PR TITLE
Improve BQ test utils to support JSON in a more simple manner

### PR DESCRIPTION
**Pull request by pabloem**
BigQuery testing utilities (and some prod utilities as well) default to converting individual data values into strings when converting data to JSON-encoded TableRow objects. This makes some testing difficult, as data types can't be recovered properly.

This change ensures that JSON conversion preserves the data type when possible in JSON (boolean, int32, float, double) so that testing and other consumers of TableRow data can expect correct types.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
r: @Abacn

**Comment by Abacn** [comment]
Thanks for the fix. Could you please providing some context of the change, like what current issue we have using INT32?

**Comment by pabloem** [comment]
thanks @Abacn - I've added an explanation on the top comment of the PR.

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
feels like jenkins is targeting me personally : ) lol

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by pabloem** [comment]
uggg these don't repro in my local env

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
errors unrelated. Feel free to review @Abacn 
Errors in previous run: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/23775/

**Review by Abacn — APPROVED** [review]
LGTM, thanks

**Comment by pabloem** [comment]
Run Java PreCommit

**Pull request merged**
