### PR TITLE
Various release script fixes

### LINKED ISSUE #27315: [Failing Test]: PubsubReadIT timeout pollForResultForDuration
### What happened?

happens here: https://github.com/apache/beam/blob/7890bdcee843851ae32354df051f8b8abec12bc6/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadIT.java#L85C5-L85C5

```
Error Message
java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/start-subscription--2539694162040025434 in 300s
Stacktrace
java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/start-subscription--2539694162040025434 in 300s
	at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.pollForResultForDuration(TestPubsubSignal.java:334)
	at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.lambda$waitForStart$4(TestPubsubSignal.java:276)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPubsubMessageId(PubsubReadIT.java:85)
...
at org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:323)
	at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal$1.evaluate(TestPubsubSignal.java:131)
```

Pipeline startup usually takes 3.5 min (and could be longer). The timeout is 5 min. This pipeline reads from public data (projects/pubsub-public-data/topics/taxirides-realtime) Could it be that no message between pipeline startup and timeout and causing flaky test?

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #27320: [Failing Test]: beam_Release_Gradle_Build permared
### What happened?

This test suite (https://ci-beam.apache.org/job/beam_Release_Gradle_Build/) only runs during release verification and does not have a cron job. From the history the last successful build was #25600 for beam 2.46.0. Since them several projects failing for different reasons. beam2.47.0-2.48.0 released without this suite passing

We need to decide either fix or deprecate this test suite

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #27521: [Task]: Update Deploy docker image script and documentation for GitHub Action built candidate
### What needs to happen?

The current [publish_docker_images](https://github.com/apache/beam/blob/master/release/src/main/scripts/publish_docker_images.sh) script assumes rc images existed locally, It fetches IMAGES via `docker images` command which only looks up locally existed images (either built or pulled). As we have migrated to use github action to build rc images, we need to figure out a way to fetch rc images from remote.

A possible way is change the line to
```bash

IMAGES=$(docker search apache/beam_ --format "{{.Name}}" --limit 100)
```
then inside the loop,
```bash

if ! docker pull "${IMAGE}:${RELEASE}${RC_VERSION}" ; then
  continue
fi
```

this has two minor issue though
- docker cli does not support search image having specific tag, nor sort by update date
- the default --limit is 25, causing some images not get listed. We can bump --limit of course, but as time goes and more image name added, it can be risky to miss some image

Please comment if there are better way to do that.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix various minor issue encountered in 2.49.0 release process

Fixes #27521
Fixes #27315
Fixes #27320

* Remove Release_Gradle_Build job from release verification

  See discussion in #27320

* Fix publish docker image script to work with remotely built images

  Tested locally (add echo before the docker push):

```
================Setting Up Environment Variables===========
Which release version are you working on: 
2.49.0
Which release candidate will be the source of final docker images? (ex: 1)
2
================Pull RC Containers from DockerHub===========
We are using rc2 to push docker images for 2.49.0.
2.49.0rc2: Pulling from apache/beam_python3.8_sdk
...
================Confirming Release and RC version===========
Publishing the following images:
apache/beam_flink1.12_job_server
apache/beam_flink1.13_job_server
apache/beam_flink1.14_job_server
apache/beam_flink1.15_job_server
apache/beam_flink1.16_job_server
apache/beam_go_sdk
apache/beam_java11_sdk
apache/beam_java17_sdk
apache/beam_java8_sdk
apache/beam_java_expansion_service
apache/beam_python3.10_sdk
apache/beam_python3.11_sdk
apache/beam_python3.8_sdk
apache/beam_python3.9_sdk
apache/beam_spark3_job_server
apache/beam_transform_service_controller
apache/beam_typescript_sdk
Do you want to proceed? [y|N]
y
docker push apache/beam_flink1.12_job_server:2.49.0
docker push apache/beam_flink1.12_job_server:latest
docker push apache/beam_flink1.13_job_server:2.49.0
docker push apache/beam_flink1.13_job_server:latest
docker push apache/beam_flink1.14_job_server:2.49.0
docker push apache/beam_flink1.14_job_server:latest
docker push apache/beam_flink1.15_job_server:2.49.0
docker push apache/beam_flink1.15_job_server:latest
docker push apache/beam_flink1.16_job_server:2.49.0
docker push apache/beam_flink1.16_job_server:latest
docker push apache/beam_go_sdk:2.49.0
docker push apache/beam_go_sdk:latest
docker push apache/beam_java11_sdk:2.49.0
docker push apache/beam_java11_sdk:latest
docker push apache/beam_java17_sdk:2.49.0
docker push apache/beam_java17_sdk:latest
docker push apache/beam_java8_sdk:2.49.0
docker push apache/beam_java8_sdk:latest
docker push apache/beam_java_expansion_service:2.49.0
docker push apache/beam_java_expansion_service:latest
docker push apache/beam_python3.10_sdk:2.49.0
docker push apache/beam_python3.10_sdk:latest
docker push apache/beam_python3.11_sdk:2.49.0
docker push apache/beam_python3.11_sdk:latest
docker push apache/beam_python3.8_sdk:2.49.0
docker push apache/beam_python3.8_sdk:latest
docker push apache/beam_python3.9_sdk:2.49.0
docker push apache/beam_python3.9_sdk:latest
docker push apache/beam_spark3_job_server:2.49.0
docker push apache/beam_spark3_job_server:latest
docker push apache/beam_transform_service_controller:2.49.0
docker push apache/beam_transform_service_controller:latest
docker push apache/beam_typescript_sdk:2.49.0
docker push apache/beam_typescript_sdk:latest
```

* Change empty file to .json to make RAT_PreCommit happy

Otherwise PreCommit_RAT job will fail. json is explicitly excluded from license check:

https://github.com/apache/beam/blob/62a8087b98d9a885c9c11b30e8767a9e2b293459/build.gradle.kts#L98

* Set base branch to the release branch for start_snapshot_build PR

If cut the release using github action, the auto-generated pull request used for start_snapshot_build default base branch is master. This would then build next version snapshot. The base branch should be release-2.xx.0, as in the release verification PR generated here:

https://github.com/apache/beam/blob/62a8087b98d9a885c9c11b30e8767a9e2b293459/release/src/main/scripts/verify_release_build.sh#L145

* Bump pubsub signal wait for pipeline start to 8 min in integration tests

The flakinesses reported in #27315 are due to worker startup > 5 min. It usually takes 4-6 min depending on the staging bandwidths, 8 min should suffice.

* Change message head from Warning to Level for PubsubInjector as it follows by an exit(1)

Even when this exit(1) hit, the program exits quitely but the validation script still runs and validation fails with no data written. This should be an Error.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
pylint appears non-deterministic?

**Review by damccorm — APPROVED** [review]
Looks great, thank you!

**Review by bvolpato — APPROVED** [review]
Looks good to me too! Thanks Yi!

**Comment by Abacn** [comment]
SpannerIT flake not related, merging for now

**Pull request merged**
