### PR TITLE
[BEAM-1542] OrderedCode library

### PR DESCRIPTION
**Pull request by mairbek**
provides encoding a sequence of typed entities into a byte array that can be lexicographically sorted.

R: @chamikaramj

### CODE REVIEW

**Comment by chamikaramj** [comment]
Please fix the test failure: https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/14768/org.apache.beam$beam-sdks-java-core/console

**Comment by chamikaramj** [comment]
Also, what's the reason for adding this to util ? Do you think this will be useful for other I/O connectors ?

How about just adding this to io/gcp/spanner ?

cc: @lukecwik @kennknowles

**Comment by lukecwik** [comment]
We should make it package private in io/gcp/spanner and then share it once there is a need.

**Comment by mairbek** [comment]
Moved to io/gcp/spanner

**Comment by chamikaramj** [comment]
LGTM.

 Will merge after tests pass.

**Comment by chamikaramj** [comment]
Retest this please.

**Comment by chamikaramj** [comment]
Retest this please.

**Pull request closed without merging**
