### PR TITLE
CassandraIO: Fix generic SelectAll clauses provided by ValueProvider<String> causing CassandraIO.read to fail

### LINKED ISSUE #31622: [Bug]: CassandraIO creates bad query with ValueProvider query string
### What happened?

Check my PR for tests that check for this condition failing. 

Steps to reproduce:
1. Create a ValueProvider<String> that provides a String query into CassandraIO.read.withQuery(new someQueryValueProvider()); The ValueProvider can simply passthrough a query e.g. "SELECT * FROM KEYSPACE.TABLE";
2. Run CassandraIO Read 
3. Note that CassandraIO fails. 

The exact reason it fails is because CassandraIO read naively appends "AND" to all spec.query() values. In the reproduced steps, "SELECT * FROM KEYSPACE.TABLE" will change to "SELECT * FROM KEYSPACE.TABLE **AND** ..." which is invalid CQL syntax. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by georgecma**
Fix CassandraIO read function failing when withQuery is provided with a generic selectAll query. 

Fixes #31622 .

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [N/A] Update `CHANGES.md` with noteworthy changes.
 - [N/A] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by georgecma** [comment]
As an aside, running `./gradlew :buildSrc:spotlessApply -PdisableSpotlessCheck=true` did not do anything, but PreCommit Spotless check is failing. What should I run to lint my changes?

**Comment by Abacn** [comment]
there are format check failure 

Run './gradlew :sdks:java:io:cassandra:spotlessApply' to fix these violations.

**Review by Abacn — APPROVED** [review]
The issue sounds similar to #24829 and occurring in different code path if clause is a ValueProvider

**Comment by georgecma** [comment]
> The issue sounds similar to #24829 and occurring in different code path if clause is a ValueProvider

It looks like it.

On a side note, this issue only occurs on Integration Tests that use CassandraIO. On CassandraIO usage on Dataflow Runner this issue is not replicated.

**Comment by georgecma** [comment]
Fixes #31622

**Pull request merged**
