### PR TITLE
Unpin google-cloud-storage.

### PR DESCRIPTION
**Pull request by tvalentyn**
Don't pin google-cloud-storage to a narrow range without a particular reason.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by johnjcasey** [comment]
LGTM

**Comment by BjornPrime** [comment]
As recorded in #27326, this was done because we are relying on an internal field of google-cloud-storage. If the feeling is that this is unlikely to be an issue, that's fine, but I felt like I should articulate the rationale for pinning the version in the first place.

**Comment by tvalentyn** [comment]
> As recorded in https://github.com/apache/beam/issues/27326, t

Thanks, that context is had to access to a passer-by like me in this case. See the  dependency guidance management  here: https://docs.google.com/document/d/1euZogGjbW4VZNJMFrA5AL1keR5gZO5l45H9b9CoQ0SI/edit  (I plan to publish it this week to a more visible location).

If you feel that a stronger pin is required, let's add it back and add a comment.

**Comment by tvalentyn** [comment]
I sent a rollback, let's try to work with GCS team to have a resolution for this that would allow us to remove this pin.

**Pull request merged**
