### PR TITLE
Enable verbose output for RAT Precommit

### LINKED ISSUE #23259: [Task]: RAT check is uncelar and unactionable for new contributors
### What needs to happen?

The RAT check verifies that every file has an Apache license at the top, but when it fails the Jenkins log just contains the message: 

```
08:22:05 FAILURE: Build failed with an exception.
08:22:05 
08:22:05 * What went wrong:
08:22:05 Execution failed for task ':rat'.
08:22:05 > A failure occurred while executing org.nosphere.apache.rat.RatWork
08:22:05    > Apache Rat audit failure - 19 unapproved licenses
08:22:05      	See file:///home/jenkins/jenkins-slave/workspace/beam_PreCommit_RAT_Commit/src/build/reports/rat/index.html
```

This is problematic for two reasons:
- It's unclear to new contributors that this is complaining about license headers in newly added files.
- The file outlining the issue is on a remote worker and inaccessible. Authors need to run the check locally so they can view the file with details.

At the very least we should update the message to reference "license headers in files" or similar. It would also be nice if we could dump the contents of the file to the log, or somewhere else in the UI.

### Issue Priority

Priority: 2

### Issue Component

Component: infrastructure

### PR DESCRIPTION
**Pull request by damccorm**
Right now, when a file is missing its header RAT precommit fails but its not clear why if you don't know what RAT does. This helps make things a little clearer by calling out all of the files with the violation and adding 

This adds the following output when headers are removed:

```
16:21:05 Files with unapproved licenses:
16:21:05  - /home/jenkins/jenkins-slave/workspace/beam_PreCommit_RAT_Commit/src/build.gradle.kts
16:21:05  - /home/jenkins/jenkins-slave/workspace/beam_PreCommit_RAT_Commit/src/examples/java/README.md
```

example run: https://ci-beam.apache.org/job/beam_PreCommit_RAT_Commit/43830/console

Closes #23259

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run RAT PreCommit

**Comment by damccorm** [comment]
R: @TheNeuralBit

**Review by bvolpato — APPROVED** [review]
LGTM (non committer, though)

--

A nit/suggestion would be to add a better description at [the job on Jenkins too](https://ci-beam.apache.org/job/beam_PreCommit_RAT_Commit/) (if possible):

image

**Comment by damccorm** [comment]
> A nit/suggestion would be to add a better description at [the job on Jenkins](https://ci-beam.apache.org/job/beam_PreCommit_RAT_Commit/) too (if possible):

Unfortunately, that is driven from the same config that controls the commands/precommit status, which I don't really want to change since it would be jarring to our existing contributors.

**Comment by TheNeuralBit** [comment]
Thanks @damccorm and @bvolpato!

**Pull request merged**
