### PR TITLE
[BigQueryIO] Don't update schema of destination table when no schema is provided

### PR DESCRIPTION
**Pull request by ahmedabu98**
Follow up for #24471

Users are facing a problem when writing to BigQuery with `CREATE_IF_NEEDED` disposition and without providing a schema. After #24471, the destination schema is used to create temp tables when the user-provided schema is null. 

This PR fixes something that #24471 missed, which is to skip the schema update step when user-provided schema is null. Also adds tests to verify.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Waiting for #24699

**Comment by ahmedabu98** [comment]
Run Java_GCP_IO_Direct PreCommit

**Review by Abacn — COMMENTED** [review]
Thanks for the fix!  I'm trying to understand without this PR what kind of problem would one encounter, and how serious is it?

**Comment by ahmedabu98** [comment]
@Abacn 
Without this PR, this wouldn't work with large writes (ie. writing without specifying a schema):

```
BigQueryIO
   .writeTableRows()
   .to(OutputTable)
   .withCreateDisposition(CreateDisposition.CREATE_NEVER))
```

As it is now, the write would get stuck in `UpdateSchemaDestination` trying to update final destination table schema with a null schema.

**Comment by ahmedabu98** [comment]
Run Java_GCP_IO_Direct PreCommit

**Review by Abacn — APPROVED** [review]
LGTM

**Pull request merged**
