### PR TITLE
[DO NOT MERGE] Migrate GKE cluster off basic authentication 

### PR DESCRIPTION
**Pull request by elink21**
[DO NOT MERGE] Migrate GKE cluster off basic authentication 

https://issues.apache.org/jira/browse/BEAM-12542

### CODE REVIEW

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run Java 17 Examples on Dataflow Runner V2

**Comment by elink21** [comment]
Run Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by elink21** [comment]
Dataflow Runner V2 Java 11 Nexmark Tests

**Comment by elink21** [comment]
Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by elink21** [comment]
Run Dataflow Runner V2 Nexmark Tests

**Comment by elink21** [comment]
Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by elink21** [comment]
Dataflow Runner V2 Java 17 Nexmark Tests

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java JdbcIO Performance Test

**Comment by elink21** [comment]
Run Python MongoDBIO Load Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Metrics Report

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run Metrics Report

**Comment by elink21** [comment]
Run Metrics Report

**Comment by elink21** [comment]
Run Metrics Report

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run RAT PreCommit

**Comment by elink21** [comment]
Run Whitespace PreCommit

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Community Metrics Prober

**Comment by elink21** [comment]
Run CommunityMetrics PreCommit

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by dannymartinm** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Beam Metrics deployment

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java MongoDBIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Comment by elink21** [comment]
Run Java InfluxDbIO Performance Test

**Pull request closed without merging**
