### PR TITLE
Update dataflow container tag

### PR DESCRIPTION
**Pull request by AnandInguva**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by AnandInguva** [comment]
R : @damccorm @tvalentyn @jrmccluskey

**Review by damondouglas — APPROVED** [review]
LGTM

**Comment by tvalentyn** [comment]
FYI the image might not have the changes you need:

docker run --rm -it --entrypoint=/bin/bash gcr.io/cloud-dataflow/v1beta3/beam_python3.11_sdk:beam-master-20231215
Status: Downloaded newer image for gcr.io/cloud-dataflow/v1beta3/beam_python3.11_sdk:beam-master-20231215
root@c33b833dc7c7:/# pip list | grep storage
google-cloud-bigquery-storage   2.23.0
google-cloud-storage            2.13.0

**Comment by tvalentyn** [comment]
i'll re-run internal cloning workflow to clone latest images with the same tag.

**Comment by AnandInguva** [comment]
The change I need was `google-cloud-bigtable==2.22.0`. Let me check the container.

**Comment by AnandInguva** [comment]
```
google-cloud-aiplatform         1.37.0
google-cloud-bigquery           3.13.0
google-cloud-bigquery-storage   2.23.0
google-cloud-bigtable           2.22.0
google-cloud-core               2.3.3
google-cloud-datastore          2.18.0
google-cloud-dlp                3.13.0
google-cloud-language           2.11.1
google-cloud-profiler           4.1.0
google-cloud-pubsub             2.18.4
google-cloud-pubsublite         1.8.3
google-cloud-recommendations-ai 0.10.5
google-cloud-resource-manager   1.10.4
google-cloud-spanner            3.40.1
google-cloud-storage            2.13.0
google-cloud-videointelligence  2.11.4
google-cloud-vision             3.4.5
```

These are the dependencies in the container.

**Comment by tvalentyn** [comment]
fyi, there as a recent change: https://github.com/apache/beam/pull/29765/files#diff-1275c48808de339ef6f282d844c83ec441b5cfa0debc373fdcb7dba497da4fc8R376

**Comment by tvalentyn** [comment]
google-cloud-storage>=2.14.0 is missing

**Comment by AnandInguva** [comment]
Yes for the commit 1ce707c38650a7f9c5120061adfeed37889cc634, the base image requirements was not updated. So the cloning containers is not picking up the change. I will make a PR updating base image requirements and then merge the new container tag.

**Comment by AnandInguva** [comment]
https://github.com/apache/beam/pull/29800/ - this will update the python base image dependencies.

**Comment by AnandInguva** [comment]
I reran the cloning containers. latest container dependencies

```
google-cloud-aiplatform         1.38.1
google-cloud-bigquery           3.14.1
google-cloud-bigquery-storage   2.24.0
google-cloud-bigtable           2.22.0
google-cloud-core               2.4.1
google-cloud-datastore          2.19.0
google-cloud-dlp                3.14.0
google-cloud-language           2.12.0
google-cloud-profiler           4.1.0
google-cloud-pubsub             2.19.0
google-cloud-pubsublite         1.9.0
google-cloud-recommendations-ai 0.10.6
google-cloud-resource-manager   1.11.0
google-cloud-spanner            3.40.1
google-cloud-storage            2.14.0
google-cloud-videointelligence  2.12.0
google-cloud-vision             3.5.0
```

**Pull request merged**
