### PR TITLE
[BEAM-8691] Declare newer google-cloud-bigtable explicitly

### PR DESCRIPTION
**Pull request by suztomo**
Upgrading bigtable-client-core to the latest and explicitly declaring a newer version of google-cloud-bigquery (a dependency of bigtable-client-core).

com.google.cloud.bigtable:bigtable-client-core is a library
for an implementation deatil of bigtable access. For Java 7
support, the library declares old version of google-cloud-bigtable
library. However the old version does not work with latest GAX
library. Beam users would face AbstractMethodError.
By explicitly declaring google-cloud-bigtable at this module, we
ensure that Beam users get newer version of google-cloud-bigtable
that is compatible with latest GAX library.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by suztomo** [comment]
CommunityMetrics  is known to be failing for a while https://lists.apache.org/thread/5r8t14rkqb4r79x57ntnljy886ojxs2y

**Comment by suztomo** [comment]
Run SQL PreCommit

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by suztomo** [comment]
Run PostCommit_Java_Dataflow

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run SQL Postcommit

**Review by emilymye — APPROVED** [review]

**Comment by emilymye** [comment]
Run Java PreCommit

**Comment by emilymye** [comment]
Run SQL Postcommit

**Comment by suztomo** [comment]
# Dataflow Java Post Commit Tests

Dataflow Java Post Commit Tests has been failing before this PR:

Screen Shot 2022-04-14 at 8 06 33 PM

# Dataflow V2 Java Post Commit Tests

Dataflow V2 Java Post Commit Tests has been failing before this PR:

Screen Shot 2022-04-14 at 8 07 50 PM

# SQL PreCommit

SQL PreCommit failed again with the same error message:

```
17:37:06 * What went wrong:
17:37:06 Execution failed for task ':runners:flink:1.14:job-server:shadowJar'.
17:37:06 > Failed to load cache entry for task ':runners:flink:1.14:job-server:shadowJar'
```

Will retry.

# Java PreCommit

Java precommit failed.

```
18:17:47 * What went wrong:
18:17:47 Execution failed for task ':sdks:java:io:google-cloud-platform:analyzeClassesDependencies'.
18:17:47 > Dependency analysis found issues.
18:17:47   unusedDeclaredArtifacts
18:17:47    - com.google.cloud:google-cloud-bigtable:2.5.3@jar
```

I need to fix.

**Comment by suztomo** [comment]
39 successful, 1 skipped, and 1 failing checks. Onlyl CommunityMetrics is failing.

**Pull request merged**
