### PR TITLE
[BEAM-7807] Test classes should not use TestNG imports

### PR DESCRIPTION
**Pull request by iemejia**
R: @pabloem

### CODE REVIEW

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Finally green! PTAL @pabloem

**Comment by pabloem** [comment]
LGTM!

**Pull request merged**
