### PR TITLE
[BEAM-14118, fixes #21639] Use vendored gRPC 1.48.1

### LINKED ISSUE #21639: beam-vendor-grpc-1_43_2 shades vulnerable Netty version
The [beam-vendor-grpc-1_43_2](https://mvnrepository.com/artifact/org.apache.beam/beam-vendor-grpc-1_43_2) dependency (that is pulled transitively by the beam-runners-flink-1.13) shades a vulnerable Netty version, i.e. 4.1.63.Final: [https://mvnrepository.com/artifact/io.netty/netty-all/4.1.63.Final](https://mvnrepository.com/artifact/io.netty/netty-all/4.1.63.Final)

In turn, our Beam pipelines builds are marked as vulnerable and we're having issues promoting them to higher environments. 

Because Netty is shaded, we can't simply override the version in the build tool.

Imported from Jira [BEAM-14118](https://issues.apache.org/jira/browse/BEAM-14118). Original Jira may contain additional context.
Reported by: jigga.

### PR DESCRIPTION
**Pull request by lukecwik**
This change:
* swaps java imports
* fixes a new deprecation issue TextFormat.printToString -> TextFormat.printer().printToString caused by the update
* deletes the old 1.43.2 package

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @emilymye 
CC: @jigga

**Comment by lukecwik** [comment]
Run Spotless PreCommit

**Comment by lukecwik** [comment]
Run SQL PreCommit

**Comment by lukecwik** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by lukecwik** [comment]
Run Java_Examples_Dataflow PreCommit

**Review by emilymye — APPROVED** [review]

**Comment by Abacn** [comment]
Seems it breaks Java Wordcount Dataflow github action: https://github.com/apache/beam/runs/7774388676?check_suite_focus=true

**Pull request merged**
