### PR TITLE
[BEAM-13660] Add types and queries in Spanner's Postgresql dialect

### PR DESCRIPTION
**Pull request by libingye816**
Add the PG_NUMERIC type and PG specific queries on  information_schema table to SpannerIO. Add a dialect parameter to SpannerIO.Write. The change is used to support the Dataflow Import/Export of Cloud Spanner Postgresql Interface.

Also add NUMERIC and JSON types that we didn't include in the past due to a type casting workaround.

We are targeting the incoming cutoff date on Mar 23.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by libingye816** [comment]
R: @pabloem

**Comment by libingye816** [comment]
R: @nielm

**Comment by libingye816** [comment]
R: @lukecwik

**Comment by libingye816** [comment]
The following task is causing the failure of CommunityMetrics, it doesn't seem to be relevant to the changes made in this PR. Any insight why it fails?

task validateConfiguration(type: Exec) {
  commandLine 'sh', '-c', 'kubectl apply --dry-run=true -Rf kubernetes'
}

**Comment by libingye816** [comment]
Same here, why does this Java test fail? I didn't change anything in runners folder.

org.apache.beam.runners.dataflow.worker.status.WorkerStatusPagesTest.testThreadz
java.lang.AssertionError: Test method should appear in stack trace
Expected: a string containing "WorkerStatusPagesTest.testThreadz"
     but: was "HTTP/1.1 200 OK

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
@libingye816 you don't need to worry about that. It has been broken for a while, and it's not related to your changes as you correctly observed.

LGTM

**Comment by nielm** [comment]
LGTM for the code... 
The [post-commit tests are failing](https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/984/) because the project used is not enabled to have Spanner-postgres dialect database. 

I am not sure who would be the correct person to contact to get this enabled would be, or even the project ID used by the integration tests, but this does need to be fixed before the code is merged.

**Comment by libingye816** [comment]
The apache-beam-testing should be on the allowlist now. There is one IT that fails because of an error on spanner's backend and the fix hasn't propagated to the prod env yet. Remove it for the time being.

@pabloem Can you approve to run PostCommit again?

**Comment by libingye816** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Retest this please

**Comment by pabloem** [comment]
current postcommit: https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/985/

**Review by nielm — APPROVED** [review]

**Comment by pabloem** [comment]
LGTM. Also, updated spanner version only affects test dependnecies.

**Comment by libingye816** [comment]
ACK. The current bom version 24.4.0 already uses java-spanner version 6.20.0.

https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/24.4.0/artifact_details.html

**Pull request merged**
