### PR TITLE
Update Playground and other location usage of Go  to use latest released version by default.

### LINKED ISSUE #32441: [Bug]: Playground needs to be updated to use a more recent version of Go (minimum Go 1.21)
### What happened?

Validating the staging deployment of the Beam Playground with 2.59.0, we can't modify Go examples, since the minimum Go SDK version is 1.21.0 While the playground seems to be using 1.20.0, so it should just be a docker image change.

Shouldn't be hard to fix, since I believe the playground deploys from head when we push it.

This issue is also causing the Playground Nightly to fail, so it should be resolved.

https://github.com/apache/beam/actions/workflows/beam_Playground_CI_Nightly.yml

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by lostluck**
Where possible stop being specific about which Go image version to use, or which Go version to download.

* As of Go 1.21+, modules are built using their version of the Go language toolchain.
* The playground should be using the latest version of Go anyway, when updated.

Also including the go-licences image because it's not used for specific builds, but it does need to run on any of our go code to produce the container license manifests.

Fixes #32441  (In particular, it's required to fix the Playground CI Nightly build).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
Tour of Beam is failing because Docker Compose isn't present. It's not clear what happened there.

https://github.com/apache/beam/actions/workflows/tour_of_beam_backend_integration.yml

But it's not a new failure, something happened between the 2.58.0 release and the 2.58.1 release.

**Comment by lostluck** [comment]
The GoPortable pre-commit has been failing the last 3 weeks. It's not clear what's going on, but mostly seems like the Python GRPC servers are dying.

**Review by kennknowles — APPROVED** [review]
Insert standard concern about stability benefits of fixed versions. But also I like progress and don't mind occasional turbulence.

**Comment by lostluck** [comment]
As a rule, I generally agree, but given the infrequency that we do anything with the Playground, and the single-homedness of Go knowledge among the Beam maintainers, it's not worth the manual toil to document trying to keep things up to date, and keeps us on the Go update train.

**Pull request merged**
