### PR TITLE
Fix user_score example.

### PR DESCRIPTION
**Pull request by tvalentyn**
This is CP of PR/4141 onto 2.2.0 branch.  Hope it is still possible to include it into RC4.

It appears that PR/4102 did not completely fix the finding we observed on RC3. Given the manual nature of actions required to validate RCs, we should really try to automate the validation to iterate faster.

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @reuvenlax 
cc: @aaltay 
cc: @davidcavazos

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by aaltay** [comment]
Error in the java tests is not relevant. Other tests passed.

**Comment by tvalentyn** [comment]
Run Python PostCommit

**Pull request closed without merging**
