### PR TITLE
CP for #28624 into release 2.51.0 (Bigtable Python timestamp bug fix)

### PR DESCRIPTION
**Pull request by ahmedabu98**
Cherry picking #28624 into 2.51.0

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Direct PostCommit

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Dataflow PostCommit

**Comment by ahmedabu98** [comment]
R: @kennknowles

**Comment by ahmedabu98** [comment]
Run Python_Xlang_Gcp_Dataflow PostCommit

**Comment by bvolpato** [comment]
Run Java_GCP_IO_Direct

**Comment by bvolpato** [comment]
Run Python_Runners PreCommit

**Comment by kennknowles** [comment]
OK since all the failures are in the Fhir test that seems to OOM on GitHub Actions, I will merge this cherrypick.

**Pull request merged**
