### PR TITLE
[BEAM-11648] Update to new StreamWriterV2 API

### PR DESCRIPTION
**Pull request by reuvenlax**
R: @yirutang

### CODE REVIEW

**Comment by yirutang** [comment]
@yayi-google

**Review by yirutang — APPROVED** [review]

**Review by yayi-google — APPROVED** [review]

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Python PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java Precommit

**Comment by suztomo** [comment]
Run PostCommit_Java_Dataflow

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run SQL Postcommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Pull request merged**
