### PR TITLE
Fix assertion of global window w/ Non-default trigger w/o allowedLateness

### PR DESCRIPTION
**Pull request by mrkm4ntr**
Following test codes cause `java.lang.IllegalArgumentException: Except when using GlobalWindows, calling .triggering() to specify a trigger requires that the allowed lateness be specified using .withAllowedLateness() to set the upper bound on how late data can arrive before being dropped. See Javadoc for more details.
`
```java
PCollection<Integer> pcollection = pipeline.apply(Create.of(42))
            .apply(Window.<Integer>into(new GlobalWindows())
                    .triggering(AfterPane.elementCountAtLeast(1))
                    .discardingFiredPanes());
PAssert.that(pcollection).inEarlyGlobalWindowPanes().containsInAnyOrder(42);
```

This is too confusing because I use GlobalWindows.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mrkm4ntr** [comment]
R: @robertwb

**Comment by damccorm** [comment]
@robertwb or @kileys could you take a look?

**Comment by mrkm4ntr** [comment]
@robertwb or @kileys could you take a look?

**Comment by damccorm** [comment]
@robertwb or @klk could you please take a look?

**Pull request closed without merging**
