### PR TITLE
Obtain Flink Views from the Context Output

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @aljoscha

**Comment by aljoscha** [comment]
Yes, thank you, that does the trick! 😃 

I'll put my PR on top of this commit.

**Comment by tgroh** [comment]
Run Flink RunnableOnService

**Comment by tgroh** [comment]
This is probably safe to merge independently, if it LGTYou

**Comment by aljoscha** [comment]
LGTM! Will you merge or should I?

**Comment by tgroh** [comment]
Thanks!

**Pull request closed without merging**
