### PR TITLE
[BEAM-9352] Align version of transitive jackson dependencies with Beam version

### PR DESCRIPTION
**Pull request by iemejia**
Linkage checker analysis
https://gist.github.com/iemejia/9680bd161eeaf36e7a0963c7853f0cbc

R: @lukecwik

### CODE REVIEW

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Run CommunityMetrics PreCommit

**Comment by iemejia** [comment]
Run SQL PostCommit

**Comment by iemejia** [comment]
Run PythonLint PreCommit

**Comment by iemejia** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run Portable_Python PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Adding the deps to runtimeOnly doesn't fix the generated pom our users will have.

Would it make sense to mark them as provided or better yet make them part of the Apache Beam BOM?
Should we make all our "fixed" dependency versions part of the Apache Beam BOM?

**Comment by iemejia** [comment]
You are right, fixed now. I am not really that familiar with Beam's BOM, but can try to tackle this afterwards if we agree that it is a good idea. Opinions on that maybe also @suztomo.

**Pull request merged**
