### PR TITLE
(#25314) Have boot loaders log to logging service where possible.

### LINKED ISSUE #25314: [Feature Request]: SDK process termination bypasses Fn Logging API
### What would you like to happen?

When the language-specific SDK process terminates, the boot.go harness will simply log out the `ExitError`:

* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/go/container/boot.go#L169
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/java/container/boot.go#L236
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/python/container/boot.go#L265
* https://github.com/apache/beam/blob/679d30256c6bd64d9760702c667d7d355e70166b/sdks/typescript/container/boot.go#L179

These logs are important - you would imagine that the user would want to know if their process was terminated due to things like segfaults, panics or OOM killer SIGKILL.  

However, these logs do NOT go through the Fn Logging API and therefore does not have any important annotations - like the portability worker id and severity (i.e. `INFO`, `FATAL`). 

In Cloud Dataflow, this makes the important process termination logs show up in `worker-startup` with `INFO` severity:
bad_c++_logs copy

Instead, I think that these process termination logs should be formatted into the Fn API [LogEntry](https://github.com/apache/beam/blob/14e8de6e99a031ba7376bdb6837d471648878932/model/fn-execution/src/main/proto/org/apache/beam/model/fn_execution/v1/beam_fn_api.proto#L996) protobuf message and sent to the Fn Logging API.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [X] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by lostluck**
Have the boot loaders log to the logging service once we have an endpoint. This allows their severity to be recorded properly for better surfacing in runners, such as for fatal errors.

Sets the default log level to Debug for boot loader logging instead of Info, since boot loader configuration is unlikely to be of interest to most Beam users. Previously fatal logs use.

Also moves the "provision" code to a package path to indicate it's for Beam's container bootloader use, and not for Beam Go SDK users. It was never intended for end users, so this reduction in surface clarifies the intention among Go SDK packages.

Fixes #25314 and #24470 which were both around the incorrect surfacing of these errors as "info", and how they hampered debugging.

This also serves as a stopgap for issues in #25582 until that's resolved. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
Since this is changing the boot loaders, the test set is rather large.

**Comment by lostluck** [comment]
> Are we okay to delete the provision package in pkg/beam with this change?

I'm of the opinion it shouldn't be there, as it promotes arbitrary use of implementation details, and makes an already difficult to learn system, harder.

I would concede to leave in vestigial functions that call the new location for the functions. 

But it seems unlikely that there are more than [the 0 public users](https://pkg.go.dev/github.com/apache/beam/sdks/v2/go/pkg/beam/provision?tab=importedby) of the package who would benefit from the migration.

**Comment by lostluck** [comment]
Hmmm, there are some uses internal to Dataflow. I'll add things back so those can be more gracefully migrated.

**Comment by lostluck** [comment]
R: @robertwb  for typescript and general experience with the bootloaders commentary.

**Comment by lostluck** [comment]
@robertwb has confirmed offline that the typescript tests can be ignored for now (they don't push their own build/dev containers WRT testing PRs.) Ah, the trials of an experimental SDK.

**Comment by lostluck** [comment]
The go test action failure was https://github.com/dominikh/go-tools/issues/1034 which appears to be fixed in more recent staticheck versions (currently on 2022.1). I'll move us to a more recent version.

This seems to have resolved it too. Actions also now use Go 1.20+

**Comment by lostluck** [comment]
Looks like github API quota was hit, and that killed a few of the jenkins jobs.

**Comment by lostluck** [comment]
Run GoPortable PreCommit

**Comment by lostluck** [comment]
Run Java PreCommit

**Comment by lostluck** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by lostluck** [comment]
Run Portable_Python PreCommit

**Comment by lostluck** [comment]
Run PythonDocker PreCommit

**Comment by lostluck** [comment]
Run Python_PVR_Flink PreCommit

**Comment by lostluck** [comment]
Run Spotless PreCommit

**Comment by lostluck** [comment]
Failures and pending are the CodeCov (can't help it right now, due to the boot loaders being untested), and the non-blocking typescript tests. Merging!

**Comment by kennknowles** [comment]
Nice. Thank you!

**Pull request merged**
