### PR TITLE
[BEAM-2443] apply AutoValue to BeamSqlRecordType

### PR DESCRIPTION
**Pull request by xumingming**

### CODE REVIEW

**Comment by xumingming** [comment]
R: @XuMingmin 
R: @takidau

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Waiting Jenkins build and eventually another reviewer approval before merging.

**Comment by takidau** [comment]
LGTM. Very nice, although I'd rather the pluralization be "fieldNames" instead of "fieldsName", etc., as that's more natural sounding. I'll go ahead and make that change as I merge. If you feel strongly about the other naming, let me know and we can discuss.

**Comment by takidau** [comment]
Merged (with naming changes). Feel free to close. Thank you!

**Comment by xumingming** [comment]
Thanks @jbonofre @takidau .

**Pull request closed without merging**
