### PR TITLE
Migrate lineage counters to bounded tries.

### PR DESCRIPTION
**Pull request by robertwb**
Also cleans up the filesystem-specific logic.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @rohitsinha54

Depends on #33378.

**Comment by robertwb** [comment]
Rebased on master now that upstream is merged.

**Review by rohitsinha54 — APPROVED** [review]
Thank you. 
Has this change tested on Dataflow runner to see how the service behaves once 2.62.0 start sending BoundedTrie as a metric which it does not know about? If not then, I can help with that if needed. Since on submission of this PR 2.62.0 jobs will start sending it. 

One thing I am thinking is if we need `stringSetDisabled` kind of flag for BoundedTrie in python or not. We do not have `stringSetDisabled` for python as of now. I think it will be ok to go without it because
1. The race issue we saw for large GCS IO filepaths was java specific, given Python does a traditional blocking lock this should not happen here.
2. Python SDK usage is lower compared to Java but we have also not verified the very large GCSIO behavior at scale. This I can do this month.

**Comment by robertwb** [comment]
The UW gracefully ignores metric types it does not recognize. (This is why the string set changes could go in the SDK before they went into the service as well.) In addition, IIRC the PreCommit Python Integration (and others) run a couple of tests against dataflow. (I'll ensure all the tests pass before merging.)

I also don't think we need a `stringSetDisabled` equivalent.

**Comment by rohitsinha54** [comment]
SG. Oh yes UW part I remember now. IIRC we had to disable reporting StringSet for legacy worker though as tests started failing. I believe router will reject these with fail-close

https://source.corp.google.com/piper///depot/google3/cloud/dataflow/router/translation/v1beta3.cc;l=1361

**Comment by robertwb** [comment]
Yes. Python doesn't have to worry about the legacy worker anymore.

**Pull request merged**
