### PR TITLE
Fix Python Flink runner load tests & Stop publish Python SDK image in beam_portability

### LINKED ISSUE #26921: [Task]: Consolidate dev container image
### What needs to happen?

We publish same Python container in two places, e.g.

gcr.io/apache-beam-testing/beam_portability/beam_python3.7_sdk:latest
daily by https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/

gcr.io/apache-beam-testing/beam-sdk/beam_python3.7_sdk
every 4 hours by https://ci-beam.apache.org/job/beam_Publish_Beam_SDK_Snapshots

The first place also has java-sdk and go-sdk containers but no longer continuously publishing (last time was in 2022). This task involves stop publish Python SDK snapshot in this dir and switch to use the ones in gcr.io/apache-beam-testing/beam-sdk.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [x] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #26921
Should fix #27595 (need job-server snapshot built on master to take effect)

* Use beam-sdk images for load tests

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Go ParDo Flink Batch

**Comment by Abacn** [comment]
See https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/1062/ no longer build python containers, now build only job servers (flink and spark)

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Found that Python Flink runner load tests all broken since Jul 20, e.g. https://ci-beam.apache.org/view/LoadTests/job/beam_LoadTests_Python_Combine_Flink_Batch/

```
01:40:48 ERROR:root:java.util.concurrent.TimeoutException: Timed out while waiting for command 'docker run -d --network=host --env=DOCKER_MAC_CONTAINER=null gcr.io/apache-beam-testing/beam_portability/beam_python3.8_sdk:latest --id=1-1 --provision_endpoint=localhost:43365'
01:40:52 INFO:apache_beam.runners.portability.portable_runner:Job state changed to FAILED
01:40:52 Traceback (most recent call last):
01:40:52   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
01:40:52     return _run_code(code, main_globals, None,
01:40:52   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
01:40:52     exec(code, run_globals)
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/testing/load_tests/combine_test.py", line 129, in <module>
01:40:52     CombineTest().run()
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/testing/load_tests/load_test.py", line 152, in run
01:40:52     state = self.result.wait_until_finish(duration=self.timeout_ms)
01:40:52   File "/home/jenkins/jenkins-slave/workspace/beam_LoadTests_Python_Combine_Flink_Batch/src/sdks/python/apache_beam/runners/portability/portable_runner.py", line 614, in wait_until_finish
01:40:52     raise self._runtime_exception
01:40:52 RuntimeError: Pipeline load-tests-python-flink-batch-combine-1-0720035125_c0b4d9c6-53f4-489b-90a5-f3885a9192b8 failed in state FAILED: java.util.concurrent.TimeoutException: Timed out while waiting for command 'docker run -d --network=host --env=DOCKER_MAC_CONTAINER=null gcr.io/apache-beam-testing/beam_portability/beam_python3.8_sdk:latest --id=1-1 --provision_endpoint=localhost:43365'
```

the first failing test run on Jul 20, 2023, 5:28 AM UTC using snapshot containers on Jul 19, 2023, 8:45 PM UTC.

It appears some changes on July 18-19 broke Python container.

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
Run Load Tests Python ParDo Flink Batch

**Comment by Abacn** [comment]
It appears pull python image locally takes 1min40s, below the timeout of 2 min: https://github.com/apache/beam/blob/98cef8bb6178c4bc18a0db5bae7eac1c1ea449d6/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/environment/DockerCommand.java#L57

while it is experimented that dataproc master it takes 3 min to finish:

```
11:51:27 latest: Pulling from apache-beam-testing/beam_portability/beam_python3.8_sdk
...
11:54:34 a0eb10d78f36: Pull complete
```

changed to command to increase the timeout to 10 min. However need to build a snapshot from master to take effect though

**Comment by Abacn** [comment]
As a check, change the timeout

https://github.com/apache/beam/blob/4ffeae4d2b800f2df36d2ea2eab549f2204d5691/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/environment/DockerCommand.java#L57

to 10s from master and run the test (https://github.com/apache/beam/pull/27595#issuecomment-1646005465) indeed encounters exact same error:

```
RuntimeError: Pipeline BeamApp-yathu-0721182603-43bbd017_08810687-bc69-441f-ae7e-a4a7f94c1855 failed in state FAILED: java.util.concurrent.TimeoutException: Timed out while waiting for command 'docker run -d --mount type=bind,src=/Users/yathu/.config/gcloud,dst=/root/.config/gcloud --network=host --env=DOCKER_MAC_CONTAINER=null gcr.io/apache-beam-testing/beam_portability/beam_python3.8_sdk:latest --id=1-1 --provision_endpoint=host.docker.internal:60233'
```

**Comment by Abacn** [comment]
R: @tvalentyn @damccorm

**Comment by Abacn** [comment]
previously successful seed job run can be found in the test status of the first commit: https://github.com/apache/beam/pull/27595/commits/ba7cace17bca25130b9aa8f6e9604219f16c8aea

**Review by tvalentyn — APPROVED** [review]

**Comment by Abacn** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Pull request merged**
