### PR TITLE
[BEAM-12918] Add PostCommit_Java_Tpcds_Flink job

### PR DESCRIPTION
**Pull request by aromanenko-dev**
Add PostCommit_Java_Tpcds_Flink Jenkins job

https://github.com/apache/beam/issues/21253
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
@echauchot Could you take a look, please?

**Comment by echauchot** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
@echauchot Yes, it works fine with `parallelism=4` (just tested)

**Comment by aromanenko-dev** [comment]
https://ci-beam.apache.org/job/beam_PostCommit_Java_Tpcds_Flink/14/
Not sure why it's not displayed in check results filed above

**Comment by echauchot** [comment]
> https://ci-beam.apache.org/job/beam_PostCommit_Java_Tpcds_Flink/14/ Not sure why it's not displayed in check results filed above

I does not seem to have worked as the elapsed time is  0.0  even though the script finished sucessfully

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Spark Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
Run Flink Runner Tpcds Tests

**Comment by aromanenko-dev** [comment]
@echauchot Actually, the job worked fine - it was just an issue with properly setting a start time for a pipeline that is used to calculate elapsed time. So I fixed this and tested it locally. Though, it seems that Jenkins experiences some issues and doesn't run a new job now (even after seed job).

**Comment by aromanenko-dev** [comment]
It's ok now:
https://ci-beam.apache.org/job/beam_PostCommit_Java_Tpcds_Flink/15/console

**Comment by echauchot** [comment]
> It's ok now: https://ci-beam.apache.org/job/beam_PostCommit_Java_Tpcds_Flink/15/console

Thanks for the fix Alexey. What is the Dialect = Calcite in the output table ?

**Comment by aromanenko-dev** [comment]
> What is the Dialect = Calcite in the output table ?
It's a dialect of SQL query parser that is used in Beam SQL.

**Comment by aromanenko-dev** [comment]
I self-merge it since it was already LGTM'ed before and the issue with parallelism is fixed.

**Pull request merged**
