### PR TITLE
Small fix to sync gh prs metrics when a json data is incomplete

### PR DESCRIPTION
**Pull request by benWize**
When I was configuring my local environment of the metrics dashboard, I found out that some JSON data for GH PRs was incomplete, so the code breaks with an error, the sync is cycled, and never finishes.
Skipping the bad JSON and letting the sync continue would be better.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by benWize** [comment]
R: @damccorm

**Comment by benWize** [comment]
> Thanks for doing this - what kind of exceptions were you hitting? Could you share the exception message?
> 
> I'm wondering if it makes more sense to extract incomplete/partial data vs skipping and risking data loss

Here is the exception 
`beamsyncgithub      | Failed to extract data. Exception:  'NoneType' object is not subscriptable  pr:  {'cursor': 'Y3Vyc29yOjQ2', 'node': {'number': 2226, 'createdAt': '2017-03-11T03:04:38Z', 'updatedAt': '2017-03-31T23:56:53Z', 'closedAt': '2017-03-12T10:13:51Z', ...`

**Comment by benWize** [comment]
> Does it give you a line number in the stack trace? Wondering which piece of data in particular is missing

It doesn't show a line number but after debugging a little I've found the function that fails is https://github.com/apache/beam/blob/4dac210a1725d9a368784c3289376f68acbc0599/.test-infra/metrics/sync/github/sync.py#L236 because a user in the array of comments has `None` as author value
https://github.com/apache/beam/blob/4dac210a1725d9a368784c3289376f68acbc0599/.test-infra/metrics/sync/github/sync.py#L241
<pre>
                "node":{
                   "author":"None",
                   "body":"R: @amitsela can you please take a look and merge if you agree (since I can't). Thanks.",
                   "createdAt":"2017-03-12T09:56:08Z"
                }
</pre>
  It could be because the user account was deleted https://github.com/apache/beam/pull/2226#issuecomment-285934052

**Comment by damccorm** [comment]
Thanks for investigating! In that case, rather than skipping the reviewer, could we just do a check for this none condition and set the login to unknown (or ghost) in those cases? Looks like there are 10 instances of this, so it probably makes sense to refactor it out into a small helper function.

**Comment by benWize** [comment]
Thanks, I added a helper function to validate all references to `login`

**Review by damccorm — APPROVED** [review]
Looks great, thanks!

**Comment by benWize** [comment]
Thanks @damccorm

**Pull request merged**
