### PR TITLE
[BEAM-2128] Remove PipelineRunner.fromOptions call

### PR DESCRIPTION
**Pull request by TheNeuralBit**
As far as I can tell this call, added in https://github.com/apache/beam/pull/2795, is no longer needed to make BigQueryTornadoesIT work on the DataflowRunner.

There's a risk that other runners mutate PipelineOptions and depend on this though.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
R: @kennknowles

**Comment by TheNeuralBit** [comment]
Run Flink ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Spark ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Dataflow ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Spark ValidatesRunner

**Comment by TheNeuralBit** [comment]
Spark failure is a known issue: https://issues.apache.org/jira/browse/BEAM-9836

**Comment by TheNeuralBit** [comment]
@mxm it looks like the tests you added in https://github.com/apache/beam/pull/7748 depend on the call to `PipelineRunner.fromOptions`, which I'm attempting to remove in this PR. Is there any simple way to fix these failures?

**Comment by TheNeuralBit** [comment]
I think I've figured out how to fix it (or at least how to make these tests pass). I'll push a commit here soon

**Comment by mxm** [comment]
I just had a look as well :)

**Comment by TheNeuralBit** [comment]
So it looks like the issue is FlinkRunner modifies the pipeline options here: https://github.com/apache/beam/blob/master/runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkRunner.java#L77-L86

I'm proposing moving that logic into or around [`prepareFilesToStageForRemoteClusterExecution`](https://github.com/apache/beam/blob/master/runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkPipelineExecutionEnvironment.java#L124).

Do you see any issue with that?

**Comment by mxm** [comment]
@TheNeuralBit Exactly. I had just pushed a commit which moves the logic.

**Comment by TheNeuralBit** [comment]
oh perfect. Thanks :)

**Comment by TheNeuralBit** [comment]
@kennknowles any concerns with the other two commits I pushed to fix unit test failures?

https://github.com/apache/beam/pull/11571/commits/7df26276b0d711fb3f1accaef8f3108960c2aee2 relaxes the test added for [BEAM-3493](https://issues.apache.org/jira/browse/BEAM-3493) to just verify that we throw an exception when `run()` is called, rather than on `create()`.

https://github.com/apache/beam/pull/11571/commits/775bb7d45f04f1ec373bdf5f42c8906b65f9068b ensures that the gs:// scheme is added for `BatchStatefulParDoOverridesTest`, previously this was happening inside PipelineOptions.fromRunner.

**Pull request merged**
