### PR TITLE
[BEAM-5462] Fix <pipeline>.options in game example since it's deprecated

### PR DESCRIPTION
**Pull request by markflyhigh**
Replace `<pipeline>.options` with `<pipeline>._option` to get rid of warnings in tests.

R: @udim @aaltay 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by aaltay** [comment]
I agree with @udim. The solution would be to explicitly pass required options to transforms directly. (e.g. pass project to TeamScoresDict and use it from the passed argument.)

**Comment by robertwb** [comment]
Yep, exactly.

**Comment by udim** [comment]
The design principle is to not rely on `pipeline.options` but to pass the options directly to invocations that need it.
The reasoning is (partially) in this thread:
https://lists.apache.org/thread.html/7ed9a48f827bf7f196eab43c7b053e1b37cfdff676d92586577964ff@%3Cdev.beam.apache.org%3E

**Comment by markflyhigh** [comment]
I think our current discussion goes beyond my initial goal which is to get rid of deprecation warning messages. I still don't have a clear idea how runners should look like, but believe Java SDK (like `DirectRunner` or `DataflowRunner`) should be in a good state and has a clear example for this problem. 

If we don't want to get rid of deprecation message now (which makes sense because people can easily notice this problem and investigate it), I can close this PR.

**Comment by aaltay** [comment]
I think some of these cases could be easily fixed, by moving the inputs to be direct inputs to transform. I agree that the general solutions is might be a larger scope than what is intended here.

It is your call. Feel free to either fix partially, or close the PR, or fix all by increasing the scope.

**Comment by markflyhigh** [comment]
PTAL @aaltay @udim

**Pull request merged**
