### PR TITLE
Remove builder method tests from BigtableIO, it uses AutoValue now

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @dhalperi

**Comment by dhalperi** [comment]
Why is this code not still providing useful coverage?

Specifically, it tests that the code that we wrote around the AutoValue builder is correct.

**Comment by dhalperi** [comment]
(e.g., https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java#L274)

**Comment by iemejia** [comment]
You have a point, I did this PR since I have seen some discussion around removing 'obvious' test cases in the moment we were reviewing the PTransform/IO guides. If this is not the expected behavior I will close then this PR.

**Pull request closed without merging**
