### PR TITLE
[release-2.13.0] Apply StringUtf8 coder related fixes for Dataflow/Flink

### PR DESCRIPTION
**Pull request by mxm**
This fixes two problems:

1. Applies the corrected StringUtf8 coder fix; the old version broke Dataflow on master (Reverted: #8544, Readded: #8557)
2. Fixes Flink key encoding issues which were partly revealed by the aforementioned changes (#8557)

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mxm** [comment]
R: @ihji

**Comment by mxm** [comment]
Run Python_PVR_Flink PreCommit

**Comment by mxm** [comment]
There is some issue on Jenkins at the moment.

**Comment by mxm** [comment]
Run Python_PVR_Flink PreCommit

**Comment by ihji** [comment]
run python precommit

**Comment by mxm** [comment]
Retest this please

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
@ihji Appears to be still breaking Dataflow. Is there any change that I missed?

**Comment by ihji** [comment]
@mxm I think it's the problem of Dataflow service. Seems like Dataflow fails to load a proper SDK harness image when the version string is neither a snapshot (.dev) nor an official release. `2.13.0` branch is just created few days ago so I guess there's no SDK harness image yet for `2.13.0`. I'll look into it further.

**Comment by ihji** [comment]
CC: @angoenka

**Comment by mxm** [comment]
Thanks for the info. I will re-test when the image has been created.

**Comment by mxm** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by angoenka** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by angoenka** [comment]
Run Python PreCommit

**Comment by angoenka** [comment]
The image is updated and tests are passing now.

**Comment by ihji** [comment]
Run python postcommit

**Comment by ihji** [comment]
Run java postcommit

**Comment by mxm** [comment]
Thanks for merging!

**Pull request merged**
