### PR TITLE
[BEAM-8616] Make hadoop-client a provided dependency on ParquetIO

### PR DESCRIPTION
**Pull request by iemejia**
Follow up of the one you were reviewing before, should be quite straight forward now.
Notice that I triggered this time in advance the SQL postcommit tests to avoid any surprises.
R: @lgajowy

### CODE REVIEW

**Comment by iemejia** [comment]
Run SQL PostCommit

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test HDFS

**Comment by lgajowy** [comment]
Thanks!

**Comment by iemejia** [comment]
Thanks Łukasz!

**Pull request merged**
