### PR TITLE
Changing BigQuery insertAll error from INFO level logging to WARNING

### PR DESCRIPTION
**Pull request by chishankar-work**
When users are debugging beam, often times there are filters on log severity level that make it easier to look at details that threw errors. In many pipeline, BigQuery insertAll errors get missed because they are reported as INFO, and a good handful of users end up having to enable INFO level logging in order to see errors. Since BigQuery insertAll errors often times can lead to the pipeline being stuck for hours, being able to log this at the WARNING level would make this easier for debugging and monitoring. 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
LGTM.

**Comment by pabloem** [comment]
FYI @chamikaramj @ajamato @ihji

**Comment by chamikaramj** [comment]
Makes sense. Thanks.

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by pabloem** [comment]
hi Chirag. It looks like there's a test that checks the log message from BQ, and you may need to change it slightly: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/14404/testReport/junit/org.apache.beam.sdk.io.gcp.bigquery/BigQueryServicesImplTest/testInsertRateLimitRetry/

**Comment by ihji** [comment]
IMHO, warning level log might be too noisy here since this line only prints quota exceeded and rate limited errors. These errors are generally safe to be ignored.

**Comment by chamikaramj** [comment]
Actually, I kind of agree with what Heejong said after looking closely. Seems like this update is for only quota exceeded errors and rate limit errors. Heejong recently did an update to better surface such errors: https://github.com/apache/beam/pull/12295

Won't that be adequate ?

**Comment by pabloem** [comment]
this change is prompted by a pipeline from a user where a specific bundle was causing errors because the apiary request was larger than 10mb - the customer had logging set to WARN level, and had to update the pipeline to enable INFO-level logging to figure out what the problem was. I guess instead we could just handle the too-large request error by breaking down the request automatically, and leave the logs at INFO level - but are we sure that quota exceeded errors are the only other errors we would encounter?

**Comment by chamikaramj** [comment]
Which Beam version was the user using ? There was a bug related to streaming inserts where this block used to capture all errors. This was fixed in [1]. Now it only captures quota errors and rate limit errors (other errors are raised [2]). Which we also raise (and report to UI) if observed two often [3].

[1] https://github.com/apache/beam/pull/12106
[2] https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java#L868
[2]https://github.com/apache/beam/pull/12295

**Comment by chishankar-work** [comment]
Hey Chamikara,

Thanks for that. The user was running beam 2.19, which seems to be the problem causing a few other errors like [BEAM-9792]. If this is now being surfaced correctly in >= 2.24 then I don't mind closing this. 

However, to Pablos comment, I do think that if the buffer to write the rows is > 10mb, we should be splitting this into two separate requests upon limit exceeded error. The write for the accumulated rows into BigQuery for streaming [1], afaik, doesn't yet split this unless I am wrong or this has been implemented in a newer version. 

Thanks


[1] https://github.com/apache/beam/blob/18404e65855eac5a2d4f7993c1a9b994d013fd56/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StreamingWriteFn.java#L181-L208

**Comment by chamikaramj** [comment]
Yeah, the error fix was included in Beam 2.24.0. So newer versions should better resurface errors. I don't think rows > 10MB errors will result in quota errors or rate limit errors so they should be resurfaced as errors logs after Beam 2.24.0. Can you (or user) try a pipeline with latest Beam version ?

**Comment by chamikaramj** [comment]
"if the buffer to write the rows is > 10mb, we should be splitting this into two separate requests" this seems like a separate feature request. Also I'm not sure if this can be automatically done by BigQueryIO without updating the user pipeline.

**Comment by aaltay** [comment]
@chishankar-work - What is the next step for this PR?

**Comment by chamikaramj** [comment]
I think the next step is to try out Beam 2.24.0 or later to see if this is really needed.

**Review by ajamato — APPROVED** [review]

**Pull request closed without merging**
