### PR TITLE
Improvement to Seed job configuration so we can launch seed jobs against PRs

### PR DESCRIPTION
**Pull request by pabloem**
r: @kennknowles 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
here's an example of a seed job that ran where I manually added the parameter: https://ci-beam.apache.org/job/beam_SeedJob/9589/console

Note the output in this failed seed job: https://ci-beam.apache.org/job/beam_SeedJob/9588/console

It needs the `ghprbPullId` parameter.

**Comment by kennknowles** [comment]
Interesting. The weird thing is https://ci-beam.apache.org/job/beam_SeedJob/9555/ where I ran it from Jenkins with the same `origin/pr/X/head` parameter and it succeeded.

**Review by kennknowles — APPROVED** [review]
Why actually does it need the number? Isn't it just for reporting the status back to the PR? Well actually that is super useful too...

**Comment by pabloem** [comment]
it needs the number to replace it in the templated commands (https://github.com/apache/beam/blob/9cd53228d9938791114ef3dcfd1e9deea8ca0d4b/.test-infra/jenkins/job_seed_standalone.groovy#L47) - I did not look much further to figure out if we could rewrite the job to not need it - I just figured that this works : )

**Comment by tvalentyn** [comment]
I think Seed job broke after this change. Sample error:

https://ci-beam.apache.org/job/beam_SeedJob/9598/console

**Comment by tvalentyn** [comment]
I can still run seed jobs from open PRs but seed job fails when I trigger it from master via Jenkins UI, cron runs also fail.

**Comment by tvalentyn** [comment]
Seed job still failing, let's try to revert this and see if it recovers.

**Pull request merged**
