### PR TITLE
[BEAM-79] Merge master into gearpump-runner branch

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by manuzhang** [comment]
R: @kennknowles @jbonofre

**Comment by kennknowles** [comment]
If my git skills are in place, then this LGTM and I'll merge it. Specifically, there's no output from `git log --no-merges github/pr/3479 ^github/master ^github/gearpump-runner` so that means no fixup was needed.

**Comment by kennknowles** [comment]
I see the `runnable-on-service-tests` (should rename that execution so it is easier to find) and it looks like it passed with the new snapshot version. Great!

**Comment by manuzhang** [comment]
@kennknowles Thanks, I'm learning new git skills from you again😄. The vote for gearpump 0.8.4 release is a bit slow somehow.

**Pull request merged**
