### PR TITLE
[Python] Increase test_wordcount_it timeout to 3600

### LINKED ISSUE #27013: [Failing Test]: Wordcount Integration Test in python is failing because of timeout
### What happened?

The test `apache_beam/examples/wordcount_it_test.py::WordCountIT::test_wordcount_it --capture=no --numprocesses=2 --timeout=1800` fails due to timeout

`FAILED apache_beam/examples/wordcount_it_test.py::WordCountIT::test_wordcount_it - Failed: Timeout >1800.0s`

Full log:https://ci-beam.apache.org/job/beam_PreCommit_Python_Integration_Phrase/58/consoleText

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by riteshghorse**
Fixes #27013 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by riteshghorse** [comment]
assign set of reviewers

**Comment by tvalentyn** [comment]
why is it that wordcount doesn't finish in 30 min ?

**Comment by tvalentyn** [comment]
cc: @AnandInguva

**Comment by tvalentyn** [comment]
It's because the container doesn't exist:

"PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/cloud-dataflow/v1beta3/python37-fnapi:beam-master-20230601 not found: manifest unknown: Failed to fetch \"beam-master-20230601\" from request \"/v2/cloud-dataflow/v1beta3/python37-fnapi/manifests/beam-master-20230601\"." image="gcr.io/cloud-dataflow/v1beta3/python37-fnapi:beam-master-20230601"

**Pull request closed without merging**
