### PR TITLE
[Website] update commits link

### LINKED ISSUE #22520: [Bug]: Contact us page. The link commits@beam.apach.org moves to https://s.apache.org/beam-slack-channel
### What happened?

Steps:
1. Open the website https://beam.apache.org/
2. Click on the button "Contact Us" in the Footer
3. Find the section "Available contact channels"
4. Find the line with purpose "Firehose of build notifications from Jenkins"
5. Click on the link "commits@beam.apache.org" in CHANNEL column

Actual result: The page with address "https://the-asf.slack.com/?redir=%2Fmessages%2FC9H0YNP3P%2F" opens 
Expected result: The page with address "https://lists.apache.org/list.html?commits@beam.apache.org" opens 

### Issue Priority

Priority: 1

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22520
- update commits link on contact-us page from `https://s.apache.org/beam-slack-channel` to `https://lists.apache.org/list.html?commits@beam.apache.org`
_______________________________________________________________________________________________________________________________________
before:
before_commits_list
after:
after_commits_list
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by alevtinaboiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, review current PR?

**Review by pcoet — APPROVED** [review]

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, help with merge?

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by bullet03** [comment]
> LGTM

Thank you for the help!

**Pull request merged**
