### PR TITLE
Feature/name all java threads

### PR DESCRIPTION
**Pull request by Geddy05**
Name all Java threads to aid in debugging https://github.com/apache/beam/issues/23049

R: @kennknowles for label java.
R: @Abacn for label io.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by apilloud** [comment]
Run Java Precommit

**Comment by apilloud** [comment]
It looks like this is still failing quite a few spotless checks. Can you run :spotlessApply on the failing packages? See output here: https://ci-beam.apache.org/job/beam_PreCommit_Spotless_Commit/22861/console

**Comment by Geddy05** [comment]
i don't understand why the pre commit runs successful on my machine and not with gitactions.
Some help with that would be appreciated.
Thanks

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by Geddy05** [comment]
I did a couple times and i do not get any error.

**Comment by lukecwik** [comment]
We have flakes that show up and fail precommit runs. Also my comment above was to launch the test suite again since that is how Jenkins is integrated with Github for Apache Beam

**Comment by lukecwik** [comment]
Run Java PreCommit

**Pull request merged**
