### PR TITLE
[BEAM-2051] Remove all methods from PCollectionView

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Cast to SimplePCollectionView everywhere a method is used.

PCollectionView is a marker interface. Runners can expect to
always recieve a subclass of SimplePCollectionView, and cast to it when
methods are required.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by tgroh** [comment]
https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/3451/ is a postcommit oneshot of this pR

**Comment by tgroh** [comment]
https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/3453/ now

**Comment by kennknowles** [comment]
And this is just a forceful way of saying "these methods are just for runner authors"?

**Comment by tgroh** [comment]
yes.

**Comment by tgroh** [comment]
run dataflow validatesrunner

**Comment by tgroh** [comment]
run flink validatesrunner

**Comment by tgroh** [comment]
run spark validatesrunner

**Comment by tgroh** [comment]
run apex validatesrunner

**Comment by tgroh** [comment]
run flink validatesrunner

**Comment by tgroh** [comment]
run apex validatesrunner

**Comment by tgroh** [comment]
run spark validatesrunner

**Comment by tgroh** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
LGTM, though there are a lot more places in the SDK where we don't use this technique. I'd say it should be only temporary.

**Comment by kennknowles** [comment]
Just noting the alternative of leaving the methods and heavily documenting that they are internal only, which is what we've done most places.

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
With the `@Internal` annotation we don't actually want this.

**Pull request closed without merging**
