### PR TITLE
Fix broken format on master

### PR DESCRIPTION
**Pull request by kennknowles**
Ran `spotlessApply` globally

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Thanks for fixing. Do you have any idea how this could have slipped through? PreCommit ran fine before merging and this is a new file. It seems PreCommit doesn't run spotless?

**Comment by kennknowles** [comment]
Hmm, that would be a major issue. On `master` when I run `./gradlew --dry-run :javaPreCommit` it does seem to include spotless tasks.

**Comment by kennknowles** [comment]
I do see the appropriate green checkboxes on #6726:
https://builds.apache.org/job/beam_PreCommit_Java_Commit/2017/
https://scans.gradle.com/s/fpucua3h2plj6/timeline?taskFilter=:beam-runners-flink_2.11:spotlessJavaCheck

But of course the issue was found because the very same precommit was failing, in its `Cron` variant:
https://builds.apache.org/job/beam_PreCommit_Java_Cron/502/
https://scans.gradle.com/s/byyjmuj377jgy/console-log?task=:beam-runners-flink_2.11:spotlessJava

**Comment by kennknowles** [comment]
@mxm what occurred was that #6791 modified the spotless configuration concurrently. Since we don't have a serialized merge queue, this sort of thing can happen.

**Comment by mxm** [comment]
That makes perfect sense! Thanks for taking the time to clarify.

It would be very convenient and less erorr-prone if we had a bot which merged pull requests serially.

**Comment by kennknowles** [comment]
We had one for the web site, but it is probably not something we want to maintain or administer. There are a few others out there; most have weird processes/rules/limitations. This one looks OK at first glance: https://github.com/bors-ng/bors-ng

**Comment by mxm** [comment]
Yes, I remember the ASF merge bot was fragile. Bors looks good, but whichever we would choose, the question is, how do we integrate it with the ASF infrastructure? 

Asked INFRA to clarify: https://issues.apache.org/jira/browse/INFRA-17177

**Comment by kennknowles** [comment]
To be clear, this should go to dev@, and we frankly have a lot of infrastructure churn lately so folks might want to relax on that for a bit.

**Comment by mxm** [comment]
The discussion about whether the community wants a serial merge feature of course needs to go to dev@. Just wanted to know about the formalities. Yes, I agree, Infra should not be bothered too much :)

**Pull request merged**
