### PR TITLE
Add documentaton for quickstart tasks

### PR DESCRIPTION
**Pull request by swegner**
These show up when running `./gradlew tasks`:

```
> Task :tasks                                                          
            
------------------------------------------------------------
All tasks runnable from root project                   
------------------------------------------------------------                              

// ...                     
            
Verification tasks
------------------
check - Runs all checks.
examplesJavaIntegrationTest
googleCloudPlatformIntegrationTest
jacocoTestCoverageVerification - Verifies code coverage metrics based on specified rules for the test task.
jacocoTestReport - Generates code coverage report for the test task.
needsRunnerTests - Runs tests that require a runner to validate that piplines/transforms work correctly
postCommit - Various integration tests using the Dataflow runner.
runQuickstartJavaApex - Run the Beam quickstart with the Apex runner
runQuickstartJavaDataflow - Run the Beam quickstart with the Dataflow runner
runQuickstartJavaDirect - Run the Beam quickstart with the Direct runner
runQuickstartJavaFlinkLocal - Run the Beam quickstart with the FlinkLocal runner
runQuickstartJavaSpark - Run the Beam quickstart with the Spark runner
runQuickstartsJava - Run the Beam quickstart across all Java runners
spotlessApply - Applies code formatting steps to sourcecode in-place.
spotlessCheck - Checks that sourcecode satisfies formatting steps.
test - Runs the unit tests.
validatesRunner - Validates Apex runner
validatesRunnerBatch
validatesRunnerStreaming - Validates the streaming runner
validatesRunnerTest

// ...
```

### CODE REVIEW

**Comment by swegner** [comment]
R: @kennknowles

**Comment by swegner** [comment]
ping @kennknowles

**Comment by kennknowles** [comment]
Ah, sorry for the delay. I like it. One nit: does this task actually run the quickstart, or just the pipeline contained in it? As I see it, a major part of the quickstart would be testing the install from archetype.

**Comment by swegner** [comment]
It generates from archetype. Check out https://github.com/apache/beam/blob/master/release/src/main/groovy/quickstart-java-dataflow.groovy

Note that @lukecwik did the work for this; I'm just adding some Gradle metadata.

**Comment by kennknowles** [comment]
I thought it did - that's boss. The metadata kind of implies a narrower scope. Maybe "Run the Beam quickstart with the Foobizzle runner". I would even drop https://beam.apache.org/get-started/quickstart-java/ in the description if it fit.

**Comment by swegner** [comment]
Done. @kennknowles PTAL

**Comment by kennknowles** [comment]
I like it. Are we suffering from general flakiness here?

**Comment by swegner** [comment]
retest this please

**Comment by swegner** [comment]
retest this please

**Comment by swegner** [comment]
retest this please

**Comment by swegner** [comment]
retest this please

**Comment by swegner** [comment]
retest this please

**Comment by swegner** [comment]
Run Java PreCommit

**Comment by swegner** [comment]
Run Java PreCommit

**Comment by swegner** [comment]
Tests are green, I believe this is ready to merge. 

@kennknowles PTAL

**Comment by pabloem** [comment]
merged : D

**Pull request merged**
