### PR TITLE
[BEAM-10051] Scope instruction data. 

### PR DESCRIPTION
**Pull request by lostluck**
Make DataChannels instruction scope aware so that whenever data arrives, it will either be used, or safely dropped.

In particular, the start of an instruction isn't coupled to when the data will arrive. So there are a few cases that needed particular handling.

* Happy Path: Instruction starts processing, creating a reader, and starts to read data before any data arrives.
   * This case was handled very well already.
* Initial data arrives before instruction start, and reader creation.
  * This case was also handled well, data would be cached, and eventually cause push back until the instruction requests a reader, at which point it's the same as the happy path.
* Initial data arrives and instruction never creates a reader.
  * This can happen if there are issues initializing a DoFn in Setup or StartBundle. This can cause the worker to be hung for other bundles.
* Initial data arrives after instruction ends.
  * Similarly to the never creates a reader case, this can cause a hung worker. The data channel needs to be aware at least temporarily that the instruction is over and shouldn't create readers for it.

When the ScopedDataManager is closed, all channels are notified to remove the instruction and close the readers and writers. 
At the point in the stack where ScopedDataMana

ger is closed, readers needed to be handled carefully, but writers do not. Writers are only created by the DataSink node, and managed by the framework. In particular, if the writer was already closed, it would have removed themselves from the writer map on the Close call, preventing the ScopedDataManager from a double close. Otherwise, the writer would be in the map (such as due to a panic preventing the ordinary close), and need closing.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
R: @youngoli

**Comment by lukecwik** [comment]
`Initial data arrives and instruction never creates a reader` and `Initial data arrives after instruction ends` should eventually allow progress via a timeout on how long we expect this data to sit there without an active bundle. Anything on the order of 10s of seconds seems like plenty of time since we expect the ProcessBundle instruction to be in the control stream already (albeit possibly stuck in a network buffer or so). The SDK just needs to record the id in memory and if it ever sees a bundle for such an id, it would fail it immediately since it had dropped the data already.

**Comment by lostluck** [comment]
This PR does have the assumption baked in that we'll always get a data message and a control message for an instruction.

It doesn't handle the less well behaved cases of "only receive instructions, and never any data" or the "only data, never instructions" cases, which, as you say, probably require a time component to handle them properly. 

Only instruction, is a bit of a waste of CPU, and ends up using little to no CPU while it's waiting for a channel send. On the other hand, it will then never signal the runner half or self terminate. So if the runner is waiting on that, it's it's own fault, and not well behaved. This may cause problems for a stage as a whole if the runner doesn't decide to disregard this bundle.

Only data is a bigger risk for an individual worker, since it will block the worker eventually with what I call the Boulder problem, since the channel buffer may fill, and will start "pushback" on the data channel preventing data messages from reaching the other processing threads. This is overall desirable behavior, up until it isn't and the instruction for that data never comes.

**Pull request merged**
