### PR TITLE
[BEAM-5115] Make ValueProvider API consistent between XmlIO and XmlSource

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Thanks, LGTM in general. 
Could you add a unit test that uses this new added public method `from(ValueProvider<String>)`?

**Comment by iemejia** [comment]
Done, Added missing call to the new signature. Should be ok now @aromanenko-dev

**Comment by aromanenko-dev** [comment]
Thanks! Just one more note - please, apply `gradlew spotlessApply`, otherwise `Spotless PreCommit` is failing

**Comment by iemejia** [comment]
Done, now waiting until Mr Jenkins get happy.

**Pull request merged**
