### PR TITLE
[BEAM-5121] Test complex types of Row and Array

### PR DESCRIPTION
**Pull request by amaliujia**
Test flattening behavior of nested Row.

Note `BeamDDLNestedTypesTest` has tested ROW so not modifying it in this PR.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @akedin 
cc: @apilloud

**Comment by amaliujia** [comment]
Check 
https://github.com/apache/beam/blob/master/sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/impl/parser/BeamDDLNestedTypesTest.java#L49

 and 

https://github.com/apache/beam/blob/master/sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/utils/QuickCheckGenerators.java#L105

for how Row is being tested in `BeamDDLNestedTypesTest`.

**Comment by akedin** [comment]
This looks good. I would also add more complicated cases though e.g. arrays and field access:

```
SELECT col.row_field2.array_field[3]

SELECT top_level_array_field_after_first_row_field[3]
```

**Comment by amaliujia** [comment]
@akedin I updated this test and include the following:

```
select row_field.array_field[0]
select row_field
select nested_row_field (which returned flattened values)
select array_field[0][1] (which tests access to two dimensional array)
select array_of_row_field
```

**Comment by akedin** [comment]
run java precommit

**Comment by akedin** [comment]
Can you add a non-working cases with `@Ignore("link to jira")`?

**Comment by amaliujia** [comment]
Added the failed nested row field access case with `@Ignore` and JIRA

**Comment by akedin** [comment]
LGTM

**Pull request merged**
