### PR TITLE
[BEAM-2245] Remove Timer.cancel() from user-facing API

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

R: @aljoscha @JingsongLi 
CC: @davorbonaci ideally for FSR, but not required since it is experimental and seemingly no one needs it

### CODE REVIEW

**Comment by kennknowles** [comment]
run flink validatesrunner

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by aljoscha** [comment]
It seems two Flink tests are flaky but I didn't yet manage to reproduce locally with thousands of test runs. I'll keep investigating.

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by kennknowles** [comment]
The flink tests that are failing certainly aren't related to this. The spark failure is also a known flake. The signal is not great, but I think it is right to go ahead with this.

**Pull request merged**
