### PR TITLE
Automatically clean up old metrics containers

### PR DESCRIPTION
**Pull request by damccorm**
These get automatically generated as part of https://github.com/apache/beam/blob/e03a14c7d524629f0167f6860a17252382f34af6/.test-infra/metrics/build.gradle#L120 but we only use the latest ones. We should be periodically cleaning up old containers

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
Note, I'm not going to trigger the job until after review since its not idempotent

**Review by Abacn — APPROVED** [review]
Sorry for the delay, LGTM

**Comment by damccorm** [comment]
Run Clean Prebuilt Images

**Comment by damccorm** [comment]
Job has been failing for a few days, so this one failed but only after successfully deleting the metrics containers - https://ci-beam.apache.org/job/beam_CleanUpPrebuiltSDKImages/1549/console

**Comment by Abacn** [comment]
It appears that gcloud command crashes when trying to delete arm images created by https://github.com/apache/beam/commits/master/.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml

```
01:06:38 Digests:
01:06:38 - us.gcr.io/apache-beam-testing/github-actions/beam_go_sdk@sha256:056467618368608608eae556c7f952849d0371ebfc559d3d69cc5f1a9b5d98b4
01:06:39 ERROR: gcloud crashed (V2DiagnosticException): response: {'docker-distribution-api-version': 'registry/2.0', 'content-type': 'application/json', 'content-encoding': 'gzip', 'date': 'Sun, 06 Aug 2023 05:06:38 GMT', 'server': 'Docker Registry', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'transfer-encoding': 'chunked', 'status': 400}
```

Until gcloud solved this issue, probably we can do something similar to https://github.com/apache/beam/blob/master/.test-infra/tools/stale_bq_datasets_cleaner.sh that is fail the suite at the end

**Comment by damccorm** [comment]
I'm trying something like that in https://github.com/apache/beam/pull/27905 - I'm hoping to solve the underlying problem with that though too

**Pull request merged**
