### PR TITLE
[Website] fix code tags content overflow

### LINKED ISSUE #22888: [Bug]: code tag content overflow stretches the page on mobile resolution
### What happened?

Steps:
1. Open the website page https://beam.apache.org/documentation/programming-guide/#1314-defining-a-urn
2. Find the section 13.1.4.2. Examples
3. Change the screen size to 375px x 667px
4. Take a look on the code tag

Actual result:  content of code tag overflows and stretches the page
Expected result: content of code tag doesn't stretch the page
__________________________________________________________________________________________________________________________________
180792387-b842cdcd-9dd2-4fb6-9e5c-a61a4b91eff3

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22888
- add overflow to all `code` tags, so content would fit on screen on small mobile resoultions on pages like https://beam.apache.org/documentation/programming-guide/#1314-defining-a-urn or https://beam.apache.org/documentation/runners/spark 
____________________________________________________________________________________________________________________________________

before:
before

after:
after_with_scroll

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
Propose to enhance multiline tag `code `to display as block (without white space between lines).
before:

after:

**Review by pcoet — APPROVED** [review]
@bullet03 Thanks for this fix! If you have time, could you see if this change fixes the code overflow in the tables on this page? https://beam.apache.org/get-started/from-spark/ I fixed a bug the other day about the column width in the tables (the middle column was using way too much space), and I noticed that the code in the right column of the tables breaks the layout at small widths (e.g. 393px for Pixel 5). 
Screen Shot 2022-08-25 at 12 54 10 PM

**Comment by pcoet** [comment]
@bullet03 I created an issue: https://github.com/apache/beam/issues/22896 Not a high priority, but if you have time, it'd be great to see if we can fix it. Thanks!

**Comment by bullet03** [comment]
> @bullet03 I created an issue: #22896 Not a high priority, but if you have time, it'd be great to see if we can fix it. Thanks!

Thank you for noticing. Created the PR: https://github.com/apache/beam/pull/22915

**Comment by bullet03** [comment]
@pabloem, could you, please, help with merge?

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, help with merge? PR was approved.

**Comment by pabloem** [comment]
lgtm

**Pull request merged**
