### PR TITLE
[BEAM-6056] Rename v1_13_1 to v1p13p1

### PR DESCRIPTION
**Pull request by kennknowles**
This is a clone and rebase of #7255. I did not reproduce the Jenkins failures there, so I am opening this up to see if it repros only on Jenkins environment (vs my OSX env I was working in).

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by swegner** [comment]
From my comment on #7255, I could get it to repro with the following set of tasks: `:beam-sdks-java-core:compileJava :beam-vendor-grpc-1_13_1:jar`. Have you tried that?

**Comment by kennknowles** [comment]
Looks like it worked, but we have other problems with the build right now. Closing in favor of the approach in #7324 anyhow.

**Comment by swegner** [comment]
Thanks for the pointer. I admit that in #7324 I worked to get the build passing without fully understanding the problem/solution.

I'm not super-familiar at this point with how these declarations fit into the JNI puzzle. The `META-INF/native/libnetty` declaration you link to above: is that instructing some JNI wrapper C code on where to find our relocated netty?

Now that we've found the "correct" workaround for JNI: should we change the course now and integrate this change now or continue on the path to releasing new vendored jars before changing the world again?

I'll try to find you on Slack so we can discuss and then bring the discussion back to the dev@ list.

**Comment by kennknowles** [comment]
@swegner it turns out that we have _both_ problems: our string is wrong and netty has a bug.

I just followed the links from [BEAM-6249](https://issues.apache.org/jira/browse/BEAM-6249) which pretty much pointed right to where the fix was needed.

So FWIW:

 - filed netty/netty-tcnative#419
 - wrote a quick fix (probably bad C since I'm rusty) at netty-tcnative#421
 - if we upgrade to that point, then we can go back as per #7332

**Pull request closed without merging**
