### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by youngoli**
You can run many tests automatically using release/src/main/scripts/mass_comment.py.

### CODE REVIEW

**Comment by youngoli** [comment]
Run Release Gradle Build

**Comment by youngoli** [comment]
Run Go PostCommit

**Comment by youngoli** [comment]
Run Java PostCommit

**Comment by youngoli** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by youngoli** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by youngoli** [comment]
Run Dataflow ValidatesRunner

**Comment by youngoli** [comment]
Run Flink ValidatesRunner

**Comment by youngoli** [comment]
Run Samza ValidatesRunner

**Comment by youngoli** [comment]
Run Spark ValidatesRunner

**Comment by youngoli** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by youngoli** [comment]
Run Python Spark ValidatesRunner

**Comment by youngoli** [comment]
Run Python Dataflow ValidatesContainer

**Comment by youngoli** [comment]
Run Python Dataflow ValidatesRunner

**Comment by youngoli** [comment]
Run Python 3.5 Flink ValidatesRunner

**Comment by youngoli** [comment]
Run Twister2 ValidatesRunner

**Comment by youngoli** [comment]
Run Python 2 PostCommit

**Comment by youngoli** [comment]
Run Python 3.5 PostCommit

**Comment by youngoli** [comment]
Run Python 3.6 PostCommit

**Comment by youngoli** [comment]
Run Python 3.7 PostCommit

**Comment by youngoli** [comment]
Run Python 3.8 PostCommit

**Comment by youngoli** [comment]
Run SQL PostCommit

**Comment by youngoli** [comment]
Run Go PreCommit

**Comment by youngoli** [comment]
Run Java PreCommit

**Comment by youngoli** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by youngoli** [comment]
Run JavaPortabilityApi PreCommit

**Comment by youngoli** [comment]
Run Portable_Python PreCommit

**Comment by youngoli** [comment]
Run PythonLint PreCommit

**Comment by youngoli** [comment]
Run Python PreCommit

**Comment by youngoli** [comment]
Run Python DockerBuild PreCommit

**Comment by youngoli** [comment]
Run Samza ValidatesRunner

**Comment by youngoli** [comment]
Run Samza ValidatesRunner

**Comment by youngoli** [comment]
Run Release Gradle Build

**Comment by pabloem** [comment]
the PythonDocs test was added separately by me, and you can ignore it for now

**Comment by youngoli** [comment]
Ah, thanks Pablo, good to know.

**Comment by youngoli** [comment]
Run Release Gradle Build

**Pull request closed without merging**
