### PR TITLE
Bump snappy-java version to 1.1.10.4

### PR DESCRIPTION
**Pull request by bvolpato**
Upgrade due to GitHub security advisory: GHSA-55g7-9cwv-5qfv

### CODE REVIEW

**Comment by bvolpato** [comment]
beam_PreCommit_Java_Amazon-Web-Services2_IO_Direct

**Comment by bvolpato** [comment]
Run Java_Pulsar_IO_Direct

**Comment by bvolpato** [comment]
Run Java_Amazon-Web-Services2_IO_Direct PreCommit

**Comment by bvolpato** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Review by Abacn — APPROVED** [review]

**Comment by damccorm** [comment]
Noting that this surprisingly ended up being a backwards incompatible change since it changed the serialized form of the SnappyCoder so now anything which uses SnappyCoder can't be upgraded from `<=2.51.0` to `>=2.52.0`. I noticed this in PubSub read.

**Comment by damccorm** [comment]
Documenting this in https://github.com/apache/beam/pull/32753

**Pull request merged**
