### PR TITLE
[BEAM-6735] Add noSpilling option to WriteFiles.

### PR DESCRIPTION
**Pull request by kyle-winkelman**
Construct a simplified pipeline in the event that the number of writers isn't prohibitive. User must opt into this by using FileIO, TextIO, or WriteFiles withNoSpilling.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](../.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by kyle-winkelman** [comment]
R: @lukecwik

**Comment by kyle-winkelman** [comment]
Build is failing due to FileIO.Write#defaultNaming not having a javadoc. I did not make a change to this method and I am unsure of what to write for its javadoc. Also there is another overloaded defaultNaming method and a relativeFileNaming method that may also require javadocs.

**Comment by kyle-winkelman** [comment]
Build is failing due to FileIO.Write#defaultNaming not having a javadoc. I did not make a change to this method and I am unsure of what to write for its javadoc. Also there is another overloaded defaultNaming method and a relativeFileNaming method that may also require javadocs.

**Comment by pabloem** [comment]
Kyle could you rebase this? And would you mind adding the Javadoc? <3 Luke is out on leave, but he'll be back soon and he can review...

**Comment by pabloem** [comment]
Ismael may also be able to review if Luke can't

**Comment by kyle-winkelman** [comment]
Done!

**Comment by lukecwik** [comment]
For continuity it makes sense for @chamikaramj to take a look at this.

R: @chamikaramj

**Comment by kyle-winkelman** [comment]
I added a NeedsRunner test testWriteNoSpilling.
I also cleaned up testWriteSpilling which contrary to its naming didn't actually test spilling because spilling only occurs withRunnerDefinedSharding.

**Comment by kyle-winkelman** [comment]
Sorry to be impatient but can I get a review @lukecwik or @chamikaramj?

**Comment by pabloem** [comment]
I took a look. I worked on similar code recently (for py BQ). I understand the change; and it seems to do what it intends. Would you consider passing an argument that explicitly tells WriteFiles to have unlimited files per bundle? e.g. `if (maxFilesPerBundle < 0 ||   writers.size() <= getMaxNumWritersPerBundle())` , instead of making the spilled records tag `null`. That'd be clearer.

Just so I can understand where you're coming from to propose this change, what use case does this cover @kyle-winkelman ?

Thanks.

**Comment by kyle-winkelman** [comment]
I mainly use the spark-runner in batch mode. The pipeline, as it is now, has WriteUnshardedTempFilesFn be a ParDo.MultiOutput. The way ParDo.MultiOutputs are implemented in the spark-runner are to immediately cache the output and use it twice. Currently this is the only location in my pipeline with caching.

I use spark.dynamicAllocation so that I can release idle executors, but because of this caching those executors are not eligible to be released. This means at the end of my job I am holding onto hundreds of executors while only one of them does the copy from temp location to final location.

**Comment by kyle-winkelman** [comment]
I added a commit addressing your comment. I kept it separate so it was easy to review but let me know if I should squash the two commits into one before this gets merged.

**Comment by pabloem** [comment]
Thank you Kyle. That makes sense to me. Thanks.

**Comment by pabloem** [comment]
And yes, could you squash the changes?
Thanks

**Comment by kyle-winkelman** [comment]
Run Java PreCommit

**Comment by kyle-winkelman** [comment]
Run Java PreCommit

**Comment by kyle-winkelman** [comment]
Squashed. Thanks for the review @pabloem.

**Pull request merged**
