### PR TITLE
[BEAM-646] Add a Base OverrideFactory class for 1-to-1 overrides

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
These overrides are relatively common, and this reduces the
reimplementation of mapping singletons and casting them.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @aljoscha

**Comment by tgroh** [comment]
I'm not convinced that the travis failures are providing any actual signal other than "travis and our build don't get along" - there's a Javadoc timeout, there's the eclipse compile acting up, and there are a couple of generic travis timeouts

**Comment by aljoscha** [comment]
Thought so too. We're also hitting the 50 min limit quite often now.

**Comment by aljoscha** [comment]
Just to be clear, LGTM without waiting for Travis for now.

**Pull request closed without merging**
