### PR TITLE
[BEAM-7240] Kinesis IO Watermark Computation Improvements

### PR DESCRIPTION
**Pull request by ajothomas**
Currently, watermarks in kinesis IO are computed taking into account the record arrival time in a `KinesisRecord`. The arrival time might not always be the right representation of the event time. Also, as the per current logic, the end user of the IO cannot control watermark computation in any way.

This PR addresses these concerns through an interface `KinesisWatermarkPolicy`, through which an end user can provide custom watermark computation logic. I have also provided some standard watermark policies:
    - Arrival time policy: takes arrival time of the kinesis record as the event time
    - Processing time policy: returns`Instant.now()` as the current watermark 
    - Custom watermark policy: which takes a `SerializableFunction` to extract an event time from the record.
    I have used a configurable watermark idle duration threshold for watermark computation. The watermark should be advanced once a watermark has not been updated for the threshold duration. This prevents the stalling of a watermark (in the event that a shard is stalled/down).

Please review @iemejia @aromanenko-dev 

------------------------

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Thank you for contribution! I took a quick look on this PR and it looks as a great improvement. I'm going to do more detailed review later. 
For the moment, could you create a Jira for this change and update PR title / commit messages according to [Contribution Guide](https://beam.apache.org/contribute/#make-your-change)? Thanks.

**Comment by aromanenko-dev** [comment]
R: @krzysztof-tr 
As original author of last changes in `KinesisWatermark`and related code, could you take a look on this PR too, please?

**Comment by aromanenko-dev** [comment]
@ajothomas Please, don't merge master branch into your feature brach since it will rewrite commits history. Instead, please, use `git rebase` command, like this:
```
git rebase -i origin/master
```
Also, during rebase, it would be useful to squash your commits into only one.

**Comment by ajothomas** [comment]
Hey @aromanenko-dev, thanks for your feedback. I have addressed your comments. Apologies for rebasing the master on to the feature branch. I have cleaned it up by rebasing.

As for testing, I have used the IO to write pipelines and tested it out through a Flink runner. The pipeline consumes data from a high traffic Kinesis stream (approx. 100 records/sec being pushed to the stream) and uses the default watermark policy which takes the record arrival time of the record as the event time. It works fine and watermarks seem to advance as expected(checked watermarks in Flink's UI and it keeps getting updated to `Instant.now()`).

For low traffic streams, I also wrote a pipeline to consume from a low traffic stream where I push records to the stream at intermittent intervals. With the default watermark policy, the watermark advances to `Instant.now()` whenever I push a new record. Whenever there is a period when no record was pushed, the watermark still advances to `Instant.now() - 2 mins`. The default watermark lag threshold defined in the IO is 2 mins and if there are no records pushed in that period, the watermark still advances. This is the default behavior and the threshold value is configurable.

Hope I was clear. Please let me know your thoughts.

**Comment by aromanenko-dev** [comment]
@ajothomas LGTM, this is great improvement, thank you again for your contribution!

**Pull request merged**
