### PR TITLE
[BEAM-14350] - beam_PerformanceTests_ManyFiles_TextIOIT_HDFS missing kubeconfig

### PR DESCRIPTION
**Pull request by dannymartinm**
* Moved up get-credentials instruction for getting the kubeconfig file before copy it to the given path.
`Note`: In [PR#17396](https://github.com/apache/beam/pull/17396) was updated metrics test to get credentials every time the job is triggered and, as a best practice, a cleanup was introduced as well, this may be causing the issue in this task. 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by dannymartinm** [comment]
Run Java ManyFilesTextIO Performance Test

**Comment by dannymartinm** [comment]
Run Java ManyFilesTextIO Performance Test HDFS

**Comment by dannymartinm** [comment]
Run Java ManyFilesTextIO Performance Test HDFS

**Comment by dannymartinm** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by dannymartinm** [comment]
Hi @apilloud , could you help me running a `Run Java ManyFilesTextIO Performance Test HDFS`  seed job for this PR please?
Thanks

**Comment by apilloud** [comment]
Run Seed Job

**Comment by apilloud** [comment]
Seed job running: https://ci-beam.apache.org/job/beam_SeedJob/9565/console

**Comment by dannymartinm** [comment]
Thanks @apilloud

**Comment by apilloud** [comment]
Run Java ManyFilesTextIO Performance Test HDFS

**Review by apilloud — APPROVED** [review]
LGTM, test is passing. Can I merge this?

**Pull request merged**
