### PR TITLE
Upgrade checker framework to 3.27.0

### LINKED ISSUE #21068: Update checkerframework to 3.16+
https://github.com/typetools/checker-framework/issues/3217

Imported from Jira [BEAM-12687](https://issues.apache.org/jira/browse/BEAM-12687). Original Jira may contain additional context.
Reported by: kileys.

### LINKED ISSUE #24397: [Task]: Upgrade checkerframework to 3.21.1 for better incremental builds
### What needs to happen?

Starting at that version, individual java build targets will have intra-target incremental build.

### Issue Priority

Priority: 2

### Issue Component

Component: build-system

### PR DESCRIPTION
**Pull request by kennknowles**
This upgrades all the way to the most recent checkerframework. Some added exclusions and some fixes. This should enable even finer-grained incremental compilation.

Fixes #21068 
Fixes #24397

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Java_Cassandra_IO_Direct PreCommit

**Comment by kennknowles** [comment]
This one is ready now. This will be checker framework up to the latest release, which brings in our ability to suppress the memory constraint warning and also adds per-file incremental compilation to gradle+checker plugin builds.

**Comment by kennknowles** [comment]
Noting that all commits are independent, and we can easily revert just the last one if we hit problems. All the prior commits address other issues or are benign.

**Review by kileys — APPROVED** [review]

**Pull request merged**
