### PR TITLE
[BEAM-1832] Fix for potentially unclosed streams in ApexYarnLauncher

### PR DESCRIPTION
**Pull request by rekhajoshm**
[BEAM-1832] Fix for potentially unclosed streams in ApexYarnLauncher

Using try-resources to handle closeable close issue
Removed redundant semicolons, string null assignment
Checkstyle passes. mvn clean verify passes.

### CODE REVIEW

**Comment by rekhajoshm** [comment]
@tweise please check.thanks

**Comment by tweise** [comment]
retest this please

**Comment by tweise** [comment]
@rekhajoshm thanks for the fix. Can you please ask on the mailing list to be added as contributor (with your existing JIRA user name), so the issue can be assigned to you:

https://issues.apache.org/jira/browse/BEAM-1832

Thanks

**Comment by rekhajoshm** [comment]
Not sure which mailing list. As you r component lead, just informing you should do the magic? :-) 
my jira handle: rekhajoshm 
thanks!

**Comment by tweise** [comment]
@rekhajoshm I don't have access, otherwise of course I would add you. You can add a comment to the JIRA asking to be added as contributor also. Mailing lists are mentioned here: https://beam.apache.org/get-started/support/

**Pull request merged**
