### PR TITLE
[BEAM-2375] upgrade beam-version to 2.0.0

### PR DESCRIPTION
**Pull request by xumingming**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by xumingming** [comment]
R: @XuMingmin

**Comment by xumingming** [comment]
Retest this please.

**Comment by xumingming** [comment]
@jbonofre can you take a peek at this one please?

**Comment by xumingming** [comment]
Retest this please

**Comment by jbonofre** [comment]
I'm reviewing this one right now.

**Comment by jbonofre** [comment]
I created https://github.com/apache/beam/pull/3287 which is a direct jump to master.

**Comment by jbonofre** [comment]
@xumingming do you mind to take a look on #3287 and maybe close this one in favor of the other.

**Comment by xumingming** [comment]
Closing this one.

**Pull request closed without merging**
