### PR TITLE
Tune ByteStringCoder allocations

### LINKED ISSUE #22143: [Bug]: Tune ByteStringCoder allocations
### What happened?

ByteStringCoder uses ByteString.readFrom, which is suboptimal when we know the full string size.  This can be optimized.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by steveniemitz**
This fixes #22143

R: @lukecwik (sorry to keep tagging you, you're the only one thats touched this in a long time)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by lukecwik — APPROVED** [review]

**Comment by lukecwik** [comment]
No worries Steve. These are very useful improvements for all pipelines.

It seems as though ByteString.readFrom honors the size we pass in so it only creates one chunk, but then it copies the bytes again (for immutability purposes): https://github.com/protocolbuffers/protobuf/blob/7a07be5ad5e5dfe5af65f8101e99fec9604d15e5/java/core/src/main/java/com/google/protobuf/ByteString.java#L595

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by steveniemitz** [comment]
> It seems as though ByteString.readFrom honors the size we pass in so it only creates one chunk, but then it copies the bytes again (for immutability purposes)

Yeah, there's a couple problems with it:
- we end up allocating a 10 element object[] in the `results` ArrayList to hold a single element.
- since readChunk is called twice (one to read all the data, another to return null), we allocate an extra buffer there which gets thrown away once it realizes that there's nothing left to read (read returns -1).
- as you mentioned, a copy from the temp buffer into the resulting ByteString.

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by steveniemitz** [comment]
everything green, all good to merge this?

**Pull request merged**
