### PR TITLE
[BEAM-1345] Make a couple more things private in the Python SDK

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @aaltay 

Most important is removal of GroupByKeyOnly.

**Comment by aaltay** [comment]
LGTM.

Thank you!

**Comment by aaltay** [comment]
This PR should be tagged with https://issues.apache.org/jira/browse/BEAM-1345

**Comment by robertwb** [comment]
Failure in Apache Beam :: SDKs :: Java :: IO :: Hadoop, retest this please.

**Comment by aaltay** [comment]
LGTM

**Pull request closed without merging**
