### PR TITLE
[BEAM-6698] increase maxHeapSize to prevent OutOfMemoryError (direct …

### PR DESCRIPTION
**Pull request by adude3141**
…memory)

Direct memory size is directly correlated to java heap space. As we significantly reduced maxHeapSize with upgrade to gradle 5 we increase here again to prevent test failures

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](../.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by adude3141** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by adude3141** [comment]
Did run PVR tests several times and was unable to provoke a test failure. So 4g seems to be sufficient.

I d like to get this in as to restore green state. Still looking into why we need so much direct memory on test runner side.

R: @mxm ptal

**Comment by adude3141** [comment]
Ah, yes. Thanks for that pointer. Will look into that.

**Comment by adude3141** [comment]
@mxm Could you help merging? I forgot to change title when asking for review.

**Comment by mxm** [comment]
Sure! Thanks for the fix.

**Comment by adude3141** [comment]
Thx for merging!

**Pull request merged**
