### PR TITLE
ReshuffleTest: replace Iterable equal tests with matchers.

### PR DESCRIPTION
**Pull request by peihe**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @tgroh

**Comment by peihe** [comment]
Reason of this PR:
Iterables produced by GroupByKey in JStorm runner are not List. It is not equal to the expected List, even though they contain the same contents.

AssertThatHasExpectedContents is ContainsKVsInAnyOrderAndWithIterableValueInAnyOrder. It is more specific than ContainsKVs.

**Comment by tgroh** [comment]
That's a reasonable reason.

However, I assert that the latter part of your claim is largely untrue. The matchers that are constructed within both SerializableFunctions appear identical, as all iterables are matched with `containsInAnyOrder`

**Comment by peihe** [comment]
Thanks Thomas
Filed https://issues.apache.org/jira/browse/BEAM-2663

merging

**Pull request closed without merging**
