### PR TITLE
[BEAM-7121] Add deterministic proto coder

### PR DESCRIPTION
**Pull request by yifanmai**
Implement DeterministicProtoCoder, a deterministic coder for protos.

Beam currently uses Protobuf 3.5.0 or later, which supports deterministic serialization if [`deterministic=True` is passed to SerializeToString()](https://github.com/protocolbuffers/protobuf/blob/2761122b810fe8861004ae785cc3ab39f384d342/python/google/protobuf/message.py#L193-L194).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by yifanmai** [comment]
R: charlesccychen

**Comment by yifanmai** [comment]
@aaltay could you help find a reviewer for this, since @charlesccychen is OOO?

**Comment by aaltay** [comment]
I believe @charlesccychen will be in office tomorrow. If Charles cannot review, ping me again please.

**Comment by charlesccychen** [comment]
Thanks.

@yifanmai @aaltay @robertwb What is the rationale for keeping both ProtoCoder and DeterministicProtoCoder going forward?  Is there so much of a performance difference?

**Comment by charlesccychen** [comment]
Also note that precommits fail because of lint:

```
11:31:44 > Task :beam-sdks-python:lintPy27 FAILED
11:31:44 ************* Module apache_beam.coders.coders_test
11:31:44 C: 95, 0: Line too long (102/80) (line-too-long)
11:31:44 
11:31:44 --------------------------------------------------------------------
11:31:44 Your code has been rated at 10.00/10 (previous run: 10.00/10, -0.00)
11:31:44 
11:31:44 Command exited with non-zero status 16
11:31:44 601.37user 16.20system 2:47.52elapsed 368%CPU (0avgtext+0avgdata 422480maxresident)k
11:31:44 0inputs+224outputs (0major+828313minor)pagefaults 0swaps
11:31:44 ERROR: InvocationError for command '/usr/bin/time /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/build/srcs/sdks/python/scripts/run_pylint.sh' (exited with code 16)
```

**Comment by robertwb** [comment]
I see little, if any, motivation for both. But it'd be good for someone to verify (looking at code and maybe simple benchmarks) if it really matters performance wise before making this call.

**Comment by lukecwik** [comment]
This is great (and could be done in our other languages as well) but the fact that the deterministic isn't equivalent across languages is sad: https://github.com/protocolbuffers/protobuf/issues/2830#issuecomment-286144573

**Comment by aaltay** [comment]
Could we run some of the Jenkins benchmarks with this change and compare to it? Or perhaps add a micro benchmark for this coder. I am guessing there will be some performance implication of this.

**Comment by yifanmai** [comment]
Currently the only effect of `deterministic` is to [require MapEncoder to call `sorted()` on the map keys](https://github.com/protocolbuffers/protobuf/blob/d9ccd0c0e6bbda9bf4476088eeb46b02d7dcd327/python/google/protobuf/internal/encoder.py#L822-L826).

**Comment by yifanmai** [comment]
The deterministic coder is 20% slower with 10 keys, 65% slower with 100 keys, and 70% slower with 1000 keys.

Should we keep the deterministic coder separate then?

Benchmark setup:
```
def benchmark_proto_coder(num_keys, deterministic):
  setup = (
      "import random\n"
      "from apache_beam.coders import coders\n"
      "from apache_beam.coders import "
      "proto2_coder_test_messages_pb2 as test_message\n"
      "message = test_message.MessageWithMap()\n"
      "coder = coders.ProtoCoder(message.__class__, deterministic=%s)\n"
      "keys = range(%d)\n"
      "random.shuffle(keys)\n"
      "for i in keys:\n"
      "    message.field1['key_%%s' %% i].field1 = "
      "'Hello world %%s' %% i") % (deterministic, num_keys)
  timings = timeit.repeat(
      'coder.encode(message)', setup=setup, number=10000, repeat=5)
  print(
      'Benchmark timings for (num_keys=%d, deterministic=%s): %s' %
      (num_keys, deterministic, timings))```
```
Benchmark results:

```
Benchmark timings for (num_keys=10, deterministic=False): [0.11162495613098145, 0.11867713928222656, 0.09691786766052246, 0.09254908561706543, 0.0923910140991211]
Benchmark timings for (num_keys=10, deterministic=True): [0.12508201599121094, 0.12107491493225098, 0.1263580322265625, 0.12426280975341797, 0.12407898902893066]
Benchmark timings for (num_keys=100, deterministic=False): [0.765225887298584, 0.7647609710693359, 0.7648091316223145, 0.7889750003814697, 0.794219970703125]
Benchmark timings for (num_keys=100, deterministic=True): [1.1826050281524658, 1.2132699489593506, 1.3479349613189697, 1.328895092010498, 1.3238089084625244]
Benchmark timings for (num_keys=1000, deterministic=False): [7.4996819496154785, 7.6137168407440186, 7.3893210887908936, 7.379233121871948, 7.4038591384887695]
Benchmark timings for (num_keys=1000, deterministic=True): [12.842539072036743, 12.79149603843689, 12.759114027023315, 12.604343891143799, 13.032737970352173]
```

**Comment by aaltay** [comment]
> Should we keep the deterministic coder separate then?
Yes, let's keep it separate for now.

Consider using/updating https://github.com/apache/beam/blob/master/sdks/python/apache_beam/tools/coders_microbenchmark.py with your benchmark.

**Comment by yifanmai** [comment]
Added microbenchmarks:
```
small_message_with_map, ProtoCoder, 1000 element(s): run 1 of 20, per element time cost: 1.59318e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 2 of 20, per element time cost: 1.4535e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 3 of 20, per element time cost: 1.4518e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 4 of 20, per element time cost: 1.38509e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 5 of 20, per element time cost: 1.60599e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 6 of 20, per element time cost: 1.2928e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 7 of 20, per element time cost: 1.17121e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 8 of 20, per element time cost: 1.18802e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 9 of 20, per element time cost: 1.24202e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 10 of 20, per element time cost: 1.71099e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 11 of 20, per element time cost: 1.61979e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 12 of 20, per element time cost: 1.1765e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 13 of 20, per element time cost: 1.28272e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 14 of 20, per element time cost: 1.13361e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 15 of 20, per element time cost: 1.11871e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 16 of 20, per element time cost: 1.20051e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 17 of 20, per element time cost: 1.2253e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 18 of 20, per element time cost: 1.1971e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 19 of 20, per element time cost: 1.1992e-05 sec
small_message_with_map, ProtoCoder, 1000 element(s): run 20 of 20, per element time cost: 1.24671e-05 sec

large_message_with_map, ProtoCoder, 1000 element(s): run 1 of 20, per element time cost: 3.93291e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 2 of 20, per element time cost: 3.4997e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 3 of 20, per element time cost: 4.39081e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 4 of 20, per element time cost: 3.50349e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 5 of 20, per element time cost: 3.8208e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 6 of 20, per element time cost: 3.45418e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 7 of 20, per element time cost: 3.6797e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 8 of 20, per element time cost: 3.8079e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 9 of 20, per element time cost: 3.90592e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 10 of 20, per element time cost: 3.8846e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 11 of 20, per element time cost: 3.8914e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 12 of 20, per element time cost: 3.8697e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 13 of 20, per element time cost: 3.9917e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 14 of 20, per element time cost: 4.14879e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 15 of 20, per element time cost: 3.91412e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 16 of 20, per element time cost: 4.4534e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 17 of 20, per element time cost: 3.98979e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 18 of 20, per element time cost: 4.05421e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 19 of 20, per element time cost: 4.1333e-05 sec
large_message_with_map, ProtoCoder, 1000 element(s): run 20 of 20, per element time cost: 4.23539e-05 sec

small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 1 of 20, per element time cost: 1.46439e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 2 of 20, per element time cost: 1.8162e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 3 of 20, per element time cost: 1.2713e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 4 of 20, per element time cost: 1.26729e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 5 of 20, per element time cost: 1.2538e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 6 of 20, per element time cost: 1.27809e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 7 of 20, per element time cost: 1.2578e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 8 of 20, per element time cost: 1.29151e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 9 of 20, per element time cost: 1.384e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 10 of 20, per element time cost: 1.9423e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 11 of 20, per element time cost: 1.5723e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 12 of 20, per element time cost: 1.33312e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 13 of 20, per element time cost: 1.2516e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 14 of 20, per element time cost: 1.25978e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 15 of 20, per element time cost: 1.2943e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 16 of 20, per element time cost: 1.32768e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 17 of 20, per element time cost: 1.31061e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 18 of 20, per element time cost: 1.3788e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 19 of 20, per element time cost: 1.27299e-05 sec
small_message_with_map, DeterministicProtoCoder, 1000 element(s): run 20 of 20, per element time cost: 1.5681e-05 sec

large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 1 of 20, per element time cost: 4.14329e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 2 of 20, per element time cost: 4.75399e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 3 of 20, per element time cost: 6.64539e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 4 of 20, per element time cost: 5.57411e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 5 of 20, per element time cost: 5.8033e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 6 of 20, per element time cost: 4.9984e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 7 of 20, per element time cost: 4.93789e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 8 of 20, per element time cost: 5.10612e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 9 of 20, per element time cost: 4.96809e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 10 of 20, per element time cost: 4.8228e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 11 of 20, per element time cost: 4.77509e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 12 of 20, per element time cost: 4.04549e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 13 of 20, per element time cost: 5.21371e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 14 of 20, per element time cost: 4.62301e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 15 of 20, per element time cost: 4.9046e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 16 of 20, per element time cost: 4.38449e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 17 of 20, per element time cost: 5.07569e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 18 of 20, per element time cost: 5.47261e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 19 of 20, per element time cost: 4.92008e-05 sec
large_message_with_map, DeterministicProtoCoder, 1000 element(s): run 20 of 20, per element time cost: 4.90022e-05 sec
```

**Comment by yifanmai** [comment]
`apache_beam.transforms.util_test.BatchElementsTest.test_numpy_regression` fails for _only_ `:beam-sdks-python-test-suites-tox-py36:testPy36Cython` with `AssertionError: 5.010096933686919 != 5 within 0.01 delta`.

This seems non-deterministic and unrelated. Might have to do with this PR changing the PRNG state. Can I bump the threshold up from 0.01 to 0.02?

**Comment by charlesccychen** [comment]
@yifanmai: That sounds like a good idea
@robertwb: FYI on the flakiness since I believe that test was introduced in https://github.com/apache/beam/commit/57c8f93c04ee2ddff1d7b3166d8124f7723f39ab

**Comment by yifanmai** [comment]
Made the change to the flaky test in #8556. Turns out I only need a _little_ bit more tolerance.

**Comment by yifanmai** [comment]
Tests are passing now. @charlesccychen PTAL?

**Pull request merged**
