### PR TITLE
[BEAM-4415] Add jenkins job for HDFS ParquetIOIT

### PR DESCRIPTION
**Pull request by lgajowy**
This PR adds the jenkins job for the ParquetIOIT but now on HDFS filesystem.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test HDFS

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test HDFS

**Comment by lgajowy** [comment]
@aaltay could you take a look?

**Comment by lgajowy** [comment]
@aaltay in the meantime @szewi has finished his PR with Large HDFS cluster. I will start a new PR that uses it with larger amount of records. Closing this one.

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test HDFS

**Comment by lgajowy** [comment]
@aaltay https://github.com/apache/beam/pull/5441 was merged in the meantime. It provides a large HDFS cluster consisting of 3 data nodes and 1 master. Currently, all HDFS Jenkins jobs run on it so it was sensible to run the test on large cluster before merging it. It passed so it seems to be ok. 

Keep in mind that underlying kubernetes cluster (GKE) should be enlarged from 1 to more nodes to achieve better results. This is addressed in a thread on the devlist: [LINK](https://lists.apache.org/thread.html/bb761d22a237fe910f3ca143a556508000e39e3533c8295273e45601@%3Cdev.beam.apache.org%3E)


@szewi @aaltay could you take a look?

**Comment by szewi** [comment]
Looks good to me. Jenkins job was created and during job execution proper testing infra was created and used by Perfkit and deleted afterwards.

**Comment by lgajowy** [comment]
@aaltay ping :)

**Pull request merged**
