### PR TITLE
[BEAM-7101] Remove usages of deprecated self.assertEquals in Python codebase

### PR DESCRIPTION
**Pull request by elwinarens**
This PR replaces the deprecated `self.assertEquals` with the new naming `self.assertEqual` @tvalentyn 

------------------------

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Thanks, @elwinarens ! Please take a look at lint erros - you can find them if you click "Details" and then "Console Output" on the left. The failures are after the line "09:05:19 > Task :sdks:python:lintPy27".

**Comment by tvalentyn** [comment]
Once new iteration of the PR is ready for review, please say something like 'PTAL' on the PR.

**Comment by tvalentyn** [comment]
PTAL = please take another look - a signal to reviewer that the updated PR is ready for review.

**Comment by elwinarens** [comment]
Thanks, will do

**Comment by elwinarens** [comment]
PTAL @tvalentyn tests passed. After fixing linting issues the test still seem to randomly fail, because the different between this run and the previous is none, other than triggering another run with a git force push and `--amend --allow-empty`.

**Comment by tvalentyn** [comment]
This change looks good to me, thanks a lot, @elwinarens. Feel free to file JIRA issues for flaky tests when you see them. Also, when you need to re-run tests on a PR, you can add a comment "retest this please", which is an instruction for Jenkins to rerun tests suites.

**Comment by adude3141** [comment]
Done. Thx @elwinarens and @tvalentyn for your work here.

I resolved corresponding jira. Please feel free to reopen, if anything is left to do.

**Pull request merged**
