### PR TITLE
Updating dataflow client protos

### PR DESCRIPTION
**Pull request by pabloem**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by pabloem** [comment]
r: @chamikaramj 
I have tried and succeeded running a job in Dataflow. The `mvn clean verify` command also runs successfully.

**Comment by chamikaramj** [comment]
LGTM

**Comment by pabloem** [comment]
@robertwb can you merge these changes please?

**Comment by robertwb** [comment]
Could you add the motivation to the commit message?

**Comment by chamikaramj** [comment]
Please create a JIRA and update the PR title as well.

**Comment by pabloem** [comment]
Oops. My bad. Added.

**Pull request merged**
