### PR TITLE
replace clock.milliseconds with stopwatch

### PR DESCRIPTION
**Pull request by clmccart**
per go/java-practices/time#stopwatch, replace references to clock.milliseconds with the Stopwatch abstraction.

### CODE REVIEW

**Comment by clmccart** [comment]
cc: @tudorm

**Comment by clmccart** [comment]
from tudorm: https://paste.googleplex.com/6292253921771520

**Review by damccorm — APPROVED** [review]
Thanks - sorry for the slow review, this slipped through the cracks a bit

**Comment by damccorm** [comment]
Could you please resolve conflicts? Then I'll merge

**Review by damccorm — APPROVED** [review]

**Pull request merged**
