### PR TITLE
[BEAM-2380] Forward additional outputs to DoFnRunner in Flink Batch

### PR DESCRIPTION
**Pull request by aljoscha**
R: @iemejia or anyone, really 😃

### CODE REVIEW

**Comment by aljoscha** [comment]
Jenkins: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_ValidatesRunner_Flink/2968/

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
Succesfull Jenkins run: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_ValidatesRunner_Flink/2970/

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Run Flink ValidatesRunner

**Comment by dhalperi** [comment]
LGTM, thanks!

cc: @tgroh

**Comment by iemejia** [comment]
Thanks for merging @dhalperi I was AFK most of the day but expected to do it later on.

**Comment by aljoscha** [comment]
Thanks @dhalperi!

**Pull request merged**
