### PR TITLE
[BEAM-6510] Use TestFlinkRunner for Nexmark tests 

### PR DESCRIPTION
**Pull request by mxm**
In streaming mode, the FlinkRunner does not shutdown after executing a pipeline
because checkpointing does not work correctly otherwise. There was logic in the
past that did an auto-shutdown in case checkpointing was disabled. The logic has
been removed because it caused confusion for users.

The `TestFlinkRunner` still has the auto-shutdown logic in place.

CC @kennknowles 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Ah, forgot to run the seed job.

**Comment by mxm** [comment]
Run Seed Job

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by kennknowles** [comment]
Sounds like kind of an interesting problem that might eventually have a solution - since there will be no more input (watermarks all at +inf) can you shut down after a final checkpoint?

**Comment by mxm** [comment]
This is definitely solveable, but only directly in Flink. The root problem is that once any operator shuts down, even after taking a final checkpoint, downstream operators can't take checkpoints anymore. Often the source is done early (think of an Impulse source), but there is still work to do which needs to be checkpointed.

We need a global view of the watermarks, at least of the sink watermarks, to ensure that the job can safely be shutdown. The JobManager could maintain such a view and instruct all operators to shutdown once the global min watermark is Long.MAX_VALUE and a final checkpoint has been taken.

**Pull request merged**
