### PR TITLE
Apply shallow clone for jenkins

### PR DESCRIPTION
**Pull request by Abacn**
It is found that when Jenkins is putting much pressure on GitHub, GitHub refuses to connect and the job stucks at fetching github. As far as I know all jobs are either run on branch head (master, release branches, etc) or pull request head, so we should be able use shallow clone and skip tags.

Ref: https://plugins.jenkins.io/git/#plugin-content-checkout-with-a-shallow-clone-to-reduce-data-traffic

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
run seed job

**Comment by Abacn** [comment]
without this change the command run and content need to download:
```
git fetch --tags --force --progress -- https://github.com/apache/beam.git +refs/heads/*:refs/remotes/origin/*
remote: Enumerating objects: 815863, done.
remote: Counting objects: 100% (696/696), done.
remote: Compressing objects: 100% (307/307), done.
Receiving objects:  11% (95363/815863), 54.54 MiB | 6.38 MiB/s
```

with this change:
```
git fetch --no-tags --force --progress --depth=1 -- https://github.com/apache/beam.git +refs/heads/*:refs/remotes/origin/*
remote: Enumerating objects: 131961, done.
remote: Counting objects: 100% (131961/131961), done.
remote: Compressing objects: 100% (60854/60854), done.
Receiving objects:  72% (95012/131961), 29.93 MiB | 6.06 MiB/s
```

seedjob passed: https://ci-beam.apache.org/job/beam_SeedJob/11157/

**Comment by Abacn** [comment]
R: @riteshghorse

**Comment by Abacn** [comment]
hopefully this can more or less mitigate jenkins issue we are long experiencing

**Review by riteshghorse — APPROVED** [review]
Thanks Yi!

**Pull request merged**
