### PR TITLE
[BEAM-8146,BEAM-8204,BEAM-8205] Add equals and hashCode to SchemaCoder and RowCoder

### PR DESCRIPTION
**Pull request by TheNeuralBit**
- Adds a `typeDescriptor` parameter to SchemaCoder, and plumbs through a descriptor everywhere instances are created (https://github.com/apache/beam/pull/9493/commits/3bafcb0f6ccebd7534789f6247e50c247ceccb2c).
- Modifies `GetterBasedSchemaProvider` so that the toRow/fromRow functions it creates have a meaningful equals and hashCode function (https://github.com/apache/beam/pull/9493/commits/d41579541c4fe1337a8f53386162e60b705df60d).
- Adds an `equals` function to SchemaCoder that checks schema, typeDescriptor, fromRow, and toRow.
- Adds some tests for the above features
  - Each sub-class of `GetterBasedSchemaProvider` has at least one test checking that toRow and fromRow are equal after serialization (https://github.com/apache/beam/pull/9493/commits/36a601473b0b83ef4270c584798d4a1130fd6e24).
  - Adds `SchemaCoderTest` which checks some instances of `SchemaCoder` with `CoderProperties.{coderSerializable, coderConsistentWithEquals}` (https://github.com/apache/beam/pull/9493/commits/ab18bd5c202fcb1b3c4d72cd186f28268bd6e4ce).
- This change resolves BEAM-8204 and BEAM-8205, so the PR also re-enables `AvroSchemaTest.testAvroPipelineGroupBy` for Flink and Apex (https://github.com/apache/beam/pull/9493/commits/17c264602cd5917f7e7b68ee178bcafad3655f2e).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Run Flink ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Apex ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Flink ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Apex ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Apex ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Flink ValidatesRunner

**Comment by TheNeuralBit** [comment]
R: @reuvenlax

I know you said Flink/Apex shouldn't be relying on coder equality and that should be the real fix for BEAM-8204 and BEAM-8205, but I think this is helpful for testing anyway.

**Comment by TheNeuralBit** [comment]
Run Flink ValidatesRunner

**Comment by TheNeuralBit** [comment]
Run Apex ValidatesRunner

**Comment by reuvenlax** [comment]
is this ready for review?

**Comment by TheNeuralBit** [comment]
Yep!

**Comment by kennknowles** [comment]
Thing to watch out for is update (in)compatibility. It happened once when a contribution made a good refactor.

**Comment by kennknowles** [comment]
Since it is already a CustomCoder hence not really update compatible, this is g2g after you resolve the rebase.

**Comment by TheNeuralBit** [comment]
Thanks @kennknowles, I resolved the merge conflicts so I think this is ready. 

It may be good to get a review from @reuvenlax before merging though, at least an approval of the high-level approach. Plumbing through the type descriptor and changing the `GetterBasedSchemaProvider` interface is a pretty substantial change. The latter one will also cause a small conflict with #8690.

**Comment by kennknowles** [comment]
Interesting. If toRow and fromRow are equal, is it possible for the type descriptor to be different? (other than, I suppose, loss of generics reflection information due to erasure)

**Comment by TheNeuralBit** [comment]
That's a good point, I don't think so. Initially I added the type descriptor as something we can verify as a proxy for `toRow`/`fromRow` but now that I've made the functions created by our `SchemaProvider` implementations comparable, that check is redundant. Do you think I should back out the type descriptor changes to make this simpler? It's mostly its own commit so it wouldn't be too hard.

**Comment by kennknowles** [comment]
I would say keep as-is. Being able to implement `getEncodedTypeDescriptor` adds value on its own.

**Comment by kennknowles** [comment]
Given how long you've been waiting on this, I'm inclined to merge. Last chance to comment @reuvenlax ?

**Comment by TheNeuralBit** [comment]
+1 on merging @kennknowles

**Pull request merged**
