### PR TITLE
[BEAM-3238][SQL] Add BeamRecordSqlTypeBuilder

### PR DESCRIPTION
**Pull request by akedin**
From [BEAM-3238](https://issues.apache.org/jira/browse/BEAM-3238):

Currently it's hard to match field names with types when constructing a BeamRecordSqlType, like [here](https://github.com/apache/beam/blob/39e66e953b0f8e16435acb038cad364acf2b3a57/sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/integrationtest/BeamSqlBuiltinFunctionsIntegrationTestBase.java#L64-L71):

```java
BeamRecordSqlType type = BeamRecordSqlType.create(
    Arrays.asList("ts", "c_tinyint", "c_smallint",
        "c_integer", "c_bigint", "c_float", "c_double", "c_decimal",
        "c_tinyint_max", "c_smallint_max", "c_integer_max", "c_bigint_max"),
    Arrays.asList(Types.DATE, Types.TINYINT, Types.SMALLINT,
        Types.INTEGER, Types.BIGINT, Types.FLOAT, Types.DOUBLE, Types.DECIMAL,
        Types.TINYINT, Types.SMALLINT, Types.INTEGER, Types.BIGINT)
);
```
It would be much more readable to have a builder, along these lines:
```java
BeamRecordSqlType.builder()
  .withField("f_int", Types.INTEGER)
  .withStringField("f_str")
  .build();
```

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by akedin** [comment]
R: @echauchot @xumingming @kennknowles 
Please take a look.

**Comment by xumingming** [comment]
I like this idea!

One minor comment: Can we put the `BeamRecordSqlTypeBuilder` inside `BeamRecordSqlType`? it will keep the surface api of `org.apache.beam.sdk.extensions.sql` cleaner.

**Comment by kennknowles** [comment]
@xumingming what do you think now?

**Comment by xumingming** [comment]
retest this please.

**Comment by akedin** [comment]
retest this please.

**Pull request merged**
