### PR TITLE
[BEAM-8932]  Modify PubsubClient to use the proto message throughout.

### PR DESCRIPTION
**Pull request by dpcollins-google**
**Please** add a meaningful description for your change here

This change will enable creating a PubsubIO transform that reads and writes the full proto, useful if there are proto changes in the future.

It also accomodates the orderingKey field in the JSON client library.

R: boyuanz

 - [ x ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ x ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ x ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by boyuanzz** [comment]
+R: @boyuanzz

**Comment by boyuanzz** [comment]
Please run `./gradlew spotlessApply` under your root dir of beam project to address `Spotless` failures.

**Comment by boyuanzz** [comment]
Please fix unit test failure: `org.apache.beam.sdk.io.gcp.GcpApiSurfaceTest.testGcpApiSurface`. For more failure details, please refer to: https://builds.apache.org/job/beam_PreCommit_Java_Commit/9162/testReport/junit/org.apache.beam.sdk.io.gcp/GcpApiSurfaceTest/testGcpApiSurface/

**Comment by dpcollins-google** [comment]
> ./gradlew spotlessApply

Done

> Please fix unit test failure

Done

**Comment by kennknowles** [comment]
If I recall correctly, the GCP connectors already leak proto so it cannot be vendored. (On mobile now so cannot effectively look into it). If this use is independent of that, then the vendored version should be used. If you can wait a bit, I'll give a more thorough review.

**Comment by kennknowles** [comment]
Can you please separate the dependency upgrade?

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by boyuanzz** [comment]
Python PreCommit is failing consistently. Let's try this:
Please try to rebase your commits at the HEAD of master branch:
`git rebase -i HEAD~3`
`git pull origin master --rebase`
`git push -f dpcollins-google:master`

**Comment by dpcollins-google** [comment]
The suggested commands didn't work for me for whatever reason? I ended up pulling in another merge commit from apache:master.

**Comment by boyuanzz** [comment]
Run CommunityMetrics PreCommit

**Comment by boyuanzz** [comment]
Run Go PreCommit

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Retest this please

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Retest this please

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by suztomo** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by suztomo** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by suztomo** [comment]
Run Dataflow ValidatesRunner

**Comment by suztomo** [comment]
Run Spark ValidatesRunner

**Comment by suztomo** [comment]
Run SQL Postcommit

**Comment by boyuanzz** [comment]
Run Java PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by suztomo** [comment]
@dpcollins-google @boyuanzz beam_PostCommit_SQL started failing after master was merged with this PR. (Somehow my "Run SQL Postcommit" did not trigger the build).

https://builds.apache.org/job/beam_PostCommit_SQL/3571/

> Test Result (1 failure / +1)
> org.apache.beam.sdk.extensions.sql.meta.provider.pubsub.PubsubJsonIT.testSQLReadAndWriteWithSameFlatTableDefinition

I appreciate if you can check whether the test failure is related to this PR or not.

image

**Comment by udim** [comment]
Opened: https://issues.apache.org/jira/browse/BEAM-9036

**Pull request merged**
