### PR TITLE
[release-2.44.0] Cherry-pick: Revert 23969 sqlttypes

### LINKED ISSUE #24415: [Bug]: Cannot find a matching Calcite SqlTypeName for Beam type: LOGICAL_TYPE seen in 2.44.0 SNAPSHOT
### What happened?

There is a report of seeing following exception in current Beam 2.44.0 SNAPSHOT. It workes in 2.43.0. Possibly  #23891 and/or #24013 break Beam SQL.

```
WARNING: No NameResolverProviders found via ServiceLoader, including for DNS. This is probably due to a broken build. If using ProGuard, check your configuration
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find a matching Calcite SqlTypeName for Beam type: LOGICAL_TYPE
	at org.apache.beam.sdk.extensions.sql.impl.utils.CalciteUtils.toSqlTypeName(CalciteUtils.java:198)
	at org.apache.beam.sdk.extensions.sql.impl.utils.CalciteUtils.toRelDataType(CalciteUtils.java:305)
	at org.apache.beam.sdk.extensions.sql.impl.utils.CalciteUtils.toRelDataType(CalciteUtils.java:312)
	at org.apache.beam.sdk.extensions.sql.impl.utils.CalciteUtils.lambda$toCalciteRowType$0(CalciteUtils.java:280)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
```

### Issue Priority

Priority: 1

### Issue Component

Component: dsl-sql

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #24415

**Please** add a meaningful description for your change here

Cherry pick #24489 into release-2.44.0 branch.

Justification: #23969 introduced a regression in 2.44.0. It introduces SqlType.TIMESTAMP (micros_instant) logical type when converting from avro logical type TimestampMicros, but this Beam portable logical type is not yet supported in Beam SQL. Similar regression may occur other than Beam SQL where micros_instant is not supported.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM and I will merge once it is green.

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
changes on sdk.core often makes the first run of precommit timeout as gradle cache is not used and it tries to re-compile all codes.

**Comment by Abacn** [comment]
Tests actually ended. Java Precommit fail `org.apache.beam.sdk.io.pulsar.PulsarIOTest.testReadFromSimpleTopic` known flake, the other two are succeeded.

**Comment by Abacn** [comment]
Just a reminder (don't want this PR to block the release) @kennknowles

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
it was a pulsar flake, but I have time to kick it again to get green

**Comment by Abacn** [comment]
`org.apache.beam.sdk.io.pulsar.PulsarIOTest.testReadFromSimpleTopic` failed again

**Pull request merged**
