### PR TITLE
Fix Python postcommit

### PR DESCRIPTION
**Pull request by ahmedabu98**
HDFS integration test script is failing because `standard_external_transforms.yaml` is missing from the temp directory the test is creating

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Before applying fix: https://github.com/apache/beam/actions/runs/8144016209/job/22257187341?pr=30480#step:9:471

**Comment by tvalentyn** [comment]
What are the next steps on this PR?

**Comment by Abacn** [comment]
This is superseded by #30458

**Comment by tvalentyn** [comment]
thanks!

**Pull request closed without merging**
