### PR TITLE
Avoid Circular imports related to bigquery_schema_tools

### PR DESCRIPTION
**Pull request by svetakvsundhar**
[PR 17159](https://github.com/apache/beam/pull/17159) contains logic to convert a BQ Schema into a Beam Schema, but it seems like there's an issue with the new Beam release in calling the `bigquery_schema_tools.py` file. This PR fixes that. Note that this issue was highlited in my local IDE, but still compiled anyway and didn't get caught in our testing infrastructure.

Fixes https://github.com/apache/beam/issues/23760

Screen Shot 2022-10-19 at 1 13 11 PM

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by svetakvsundhar** [comment]
R: @ahmedabu98

**Comment by TheNeuralBit** [comment]
Hm I'm not sure this is a circular import, I think those usually manifest as an ImportError that specifially identifies it as such, not an AttributeError like your screenshot. Let's sync on this tomorrow

**Comment by svetakvsundhar** [comment]
Run Python 3.7 PostCommit

**Comment by svetakvsundhar** [comment]
Run Python 3.8 PostCommit

**Comment by TheNeuralBit** [comment]
@chamikaramj I think we'd like to CP this change, if possible

**Comment by chamikaramj** [comment]
Yes, but did we confirm this to be an actual issue ? Seems like we are just pushing imports to the module level ?

**Comment by chamikaramj** [comment]
And if so, is there a test that this should have broken ?

**Comment by TheNeuralBit** [comment]
I put an explanation for how this got through testing in the issue: https://github.com/apache/beam/issues/23760#issuecomment-1286252080

@svetakvsundhar verified that this addresses the issue by using read_gbq in a clean python environment, could you share the evidence here Svetak?

**Comment by svetakvsundhar** [comment]
Yes, ran it on a local Python shell and confirmed the error does not surface. 

Screen Shot 2022-10-20 at 9 05 41 PM

**Comment by chamikaramj** [comment]
Sound good. Thanks. Feel free to send a cherry-pick.

**Pull request merged**
