### PR TITLE
Revert #30533: Automatically execute unbounded pipelines in streaming mode.

### PR DESCRIPTION
**Pull request by damondouglas**
This reverts commit 1c55117fc3349508edf8af07b1b361313c4b8a33.

This commit has been associated with failures related to data sampling in Dataflow.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - N/A internal: ~Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by riteshghorse — APPROVED** [review]
Thanks!

**Comment by riteshghorse** [comment]
Do we have any issue tracking this or failure run we can link?

**Comment by damccorm** [comment]
My understanding is that this has caused some Dataflow tests to fail, but has it actually had negative impact on real pipelines? Is the problem here or is it with the tests themselves?

FYI @robertwb

**Comment by kennknowles** [comment]
The description is not accurate - we have an underlying bug in dataflow and some erroneous tests. The original commit was a correct change. This is reverted while we fix our tests and service.

**Comment by kennknowles** [comment]
The tests are entirely internal to Google so there is no externally tracked failure. You would have to write a pipeline with unbounded data and then insist on running it in batch mode, which presumably not many people do.

**Pull request merged**
