### PR TITLE
[BEAM-1053] ApexGroupByKeyOperator serialization issues

### PR DESCRIPTION
**Pull request by tweise**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
R: @jkff 

Probably this code will go away after the SDF work but this bug is trivial to fix and has been there for a while, so let's close it out separately. For stateInternals it was already addressed.

### CODE REVIEW

**Comment by jkff** [comment]
Failed tests: 
  WordCountTest.testWordCountExample:133
  ParDoTranslatorTest.testMultiOutputParDoWithSideInputs:308 expected:<[processing: 666: [11, 222], processing: -42: [11, 222], processing: 3: [11, 222]]> but was:<[]>
Tests in error: 
  ParDoTranslatorTest.testSerialization:225 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer
  ApexStateInternalsTest.initStateInternals:83 » NullPointer

Tests run: 35, Failures: 2, Errors: 16, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Beam :: Parent .............................. SUCCESS [  3.074 s]
[INFO] Apache Beam :: SDKs :: Java :: Build Tools ......... SUCCESS [  3.623 s]
[INFO] Apache Beam :: SDKs ................................ SUCCESS [  0.834 s]
[INFO] Apache Beam :: SDKs :: Common ...................... SUCCESS [  0.519 s]
[INFO] Apache Beam :: SDKs :: Common :: Fn API ............ SUCCESS [ 19.869 s]
[INFO] Apache Beam :: SDKs :: Common :: Runner API ........ SUCCESS [ 17.656 s]
[INFO] Apache Beam :: SDKs :: Java ........................ SUCCESS [  0.692 s]
[INFO] Apache Beam :: SDKs :: Java :: Core ................ SUCCESS [01:55 min]
[INFO] Apache Beam :: SDKs :: Java :: IO .................. SUCCESS [  0.903 s]
[INFO] Apache Beam :: SDKs :: Java :: IO :: Common ........ SUCCESS [  4.599 s]
[INFO] Apache Beam :: Runners ............................. SUCCESS [  0.452 s]
[INFO] Apache Beam :: Runners :: Core Java Construction ... SUCCESS [ 10.466 s]
[INFO] Apache Beam :: Runners :: Core Java ................ SUCCESS [ 36.748 s]
[INFO] Apache Beam :: Runners :: Direct Java .............. SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: Elasticsearch . SKIPPED
[INFO] Apache Beam :: Runners :: Google Cloud Dataflow .... SUCCESS [ 32.354 s]
[INFO] Apache Beam :: SDKs :: Java :: IO :: Google Cloud Platform SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: Hadoop Common . SUCCESS [  9.777 s]
[INFO] Apache Beam :: SDKs :: Java :: IO :: Hadoop ........ SUCCESS [  3.726 s]
[INFO] Apache Beam :: SDKs :: Java :: IO :: Hadoop :: input-format SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: Hadoop :: jdk1.8-tests SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: HBase ......... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: HDFS .......... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: JDBC .......... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: JMS ........... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: Kafka ......... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: Kinesis ....... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: MongoDB ....... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: IO :: MQTT .......... SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Maven Archetypes .... SUCCESS [  0.909 s]
[INFO] Apache Beam :: SDKs :: Java :: Maven Archetypes :: Starter SUCCESS [  8.892 s]
[INFO] Apache Beam :: SDKs :: Java :: Maven Archetypes :: Examples SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Maven Archetypes :: Examples - Java 8 SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Extensions .......... SUCCESS [  0.877 s]
[INFO] Apache Beam :: SDKs :: Java :: Extensions :: Jackson SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Extensions :: Join library SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Extensions :: Sorter  SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Harness ............. SUCCESS [ 32.842 s]
[INFO] Apache Beam :: SDKs :: Java :: Java 8 Tests ........ SKIPPED
[INFO] Apache Beam :: SDKs :: Python ...................... SKIPPED
[INFO] Apache Beam :: Runners :: Flink .................... SUCCESS [  0.333 s]
[INFO] Apache Beam :: Runners :: Flink :: Core ............ SUCCESS [ 23.465 s]
[INFO] Apache Beam :: Runners :: Flink :: Examples ........ SUCCESS [  5.142 s]
[INFO] Apache Beam :: Runners :: Spark .................... SKIPPED
[INFO] Apache Beam :: Runners :: Apex ..................... FAILURE [01:24 min]
[INFO] Apache Beam :: Examples ............................ SUCCESS [  0.482 s]
[INFO] Apache Beam :: Examples :: Java .................... SKIPPED
[INFO] Apache Beam :: Examples :: Java 8 .................. SKIPPED
[INFO] Apache Beam :: SDKs :: Java :: Aggregated Javadoc .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------




Example error:
testMergeEarliestWatermarkIntoSource(org.apache.beam.runners.apex.translation.utils.ApexStateInternalsTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException
        at com.datatorrent.netlet.util.Slice.<init>(Slice.java:54)
        at org.apache.beam.runners.apex.translation.utils.ApexStateInternals$ApexStateInternalsFactory.stateInternalsForKey(ApexStateInternals.java:461)
        at org.apache.beam.runners.apex.translation.utils.ApexStateInternalsTest.initStateInternals(ApexStateInternalsTest.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

**Comment by jkff** [comment]
Please rebase against master and take a look?

**Comment by tweise** [comment]
Ouch, this is the same issue @jbonofre run into (see thread on dev list). Please delete the offending netlet artifact from your local .m2 and it should all work.

**Comment by jkff** [comment]
Thanks, trying. Will merge once it passes.

**Pull request closed without merging**
