### PR TITLE
[BEAM-1641] Use processing time for synchronized processing time in Flink runner

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

There are some esoteric expectations that this might violate, like exactly one hourly downstream output aligned to an hour, versus a cfewuple, but we should rephrase docs to remove those expectations IMO.

R: @aljoscha @JingsongLi

### CODE REVIEW

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
LGTM! once Jenkins is green

Thanks for fixing this, @kennknowles! 👍

**Comment by kennknowles** [comment]
Worker `beam6` has been unhappy for a while. Since this affect only Flink and the `ValidatesRunner` passed, I will also run the thorough verify manually I guess.

**Comment by kennknowles** [comment]
retest this please

**Pull request merged**
