### PR TITLE
(No need to review) Testing google_cloud_bigtable 2.25.2 with Beam 2.49.0

### PR DESCRIPTION
**Pull request by burkedavison**
**Do not merge.**

Updating google_cloud_bigtable to 2.25.2 to test against Beam 2.49.0.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by burkedavison** [comment]
Java Tests / Java Unit Tests (ubuntu-latest) failure:
```
org.apache.beam.fn.harness.logging.BeamFnLoggingClientTest > testClosableWhenBlockingForOnReady FAILED
    java.lang.AssertionError at BeamFnLoggingClientTest.java:446
```

Java Tests / Java Unit Tests (windows-latest)
```
org.apache.beam.fn.harness.logging.BeamFnLoggingClientTest > testClosableWhenBlockingForOnReady FAILED
    java.lang.AssertionError at BeamFnLoggingClientTest.java:446
```

Java ("Run Java PreCommit")
```
18:43:29 Execution failed for task ':sdks:java:io:snowflake:compileJava'.
18:43:29 > Failed to store cache entry 2b3b0d96babb3c50b448068acc361fa2 for task ':sdks:java:io:snowflake:compileJava': Timeout waiting to lock Build cache (/home/jenkins/.gradle/caches/build-cache-1). It is currently in use by another Gradle instance.
...
18:43:29 Execution failed for task ':runners:java-fn-execution:test'.
18:43:29 > Process 'Gradle Test Executor 15' finished with non-zero exit value 143
18:43:29   This problem might be caused by incorrect test process configuration.
```



Display name in pull request | Command in pull request comments | Gradle goals | Success?
-- | -- | -- | --
Java SDK Post Commit Tests | Run Java Postcommit | :sdks:java:io:google-cloud-platform:postCommit | ?
Java_PVR_Flink_Batch | Run Java_PVR_Flink_Batch PreCommit | :runners:flink:1.13:job-server:validatesPortableRunnerBatch | ?
Java Spark PortableValidatesRunner Batch Tests | Run Java Spark PortableValidatesRunner Batch | :runners:spark:2:job-server:validatesPortableRunnerBatch, :runners:spark:3:job-server:validatesPortableRunnerBatch | ?
Dataflow V2 Java Post Commit Tests | Run PostCommit_Java_DataflowV2 | :runners:google-cloud-dataflow-java:validatesRunnerV2 | ?
Google Cloud Dataflow Runner V2 Java ValidatesRunner Tests | Run Java Dataflow V2 ValidatesRunner Streaming | :runners:google-cloud-dataflow-java:validatesRunnerV2Streaming | ?

**Comment by burkedavison** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by burkedavison** [comment]
Run Java Postcommit

**Comment by burkedavison** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by burkedavison** [comment]
Run PostCommit_Java_DataflowV2

**Comment by burkedavison** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by kennknowles** [comment]
Extracting the stack traces rather than just the boolean failed / not failed will make this easier to diagnose for a passerby like myself.

**Comment by burkedavison** [comment]
> Extracting the stack traces rather than just the boolean failed / not failed will make this easier to diagnose for a passerby like myself.

I will certainly try to do that, but the console output only shows what I've already provided and I can't find how to extract more information from the results.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Run Python_Integration PreCommit

**Comment by kennknowles** [comment]
Run SQL PreCommit

**Comment by kennknowles** [comment]
The Jenkins UI has browseable test results which will have the details. I like the Gradle Scan UI best, though. It may also be in the console log somewhere up higher, but that's more of a pain to dig through.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Python_Integration PreCommit

**Comment by damccorm** [comment]
Closing since it looks like this testing process is no longer active. If I'm wrong, feel free to reopen

**Pull request closed without merging**
