### PR TITLE
[BEAM-9573] Correct computing of watermark hold for timer output timestamp

### PR DESCRIPTION
**Pull request by mxm**
With the introduction of timer output timestamps, a new watermark hold had been
added to the Flink Runner. The watermark computation works on the keyed state
backend which computes a key-scoped watermark hold and not the desired
operator-wide watermark hold.

Computation: https://github.com/apache/beam/blob/b564239081e9351c56fb0e7d263495b95dd3f8f3/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1140

Key-scoped state: https://github.com/apache/beam/blob/b564239081e9351c56fb0e7d263495b95dd3f8f3/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1130

The solution is to iterate over all available state backend keys.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
I decided to pull back the fix for https://issues.apache.org/jira/browse/BEAM-9566 in favor of first fixing https://issues.apache.org/jira/browse/BEAM-9573 which is a more serious issue.

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
The downgrade of Flink for Nexmark is just a work around for https://issues.apache.org/jira/browse/BEAM-9580 good idea, it will help to test the cherry pick.

**Comment by mxm** [comment]
Run Seed Job

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by amaliujia** [comment]
LGTM

Please squash your commits into one by a way that will be easier for cherry-pick.

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
Sure. I'll cherry-pick this via a PR to the `release-2.20` branch once it is merged. Will ping you.

**Comment by mxm** [comment]
As one can see in the beginning of https://builds.apache.org/job/beam_PostCommit_Java_Nexmark_Flink_PR/35/console, this is still using Flink 1.10 for Nexmark: 
```
[src] $ /home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_Nexmark_Flink_PR/src/gradlew --continue --max-workers=12 -Dorg.gradle.jvmargs=-Xms2g -Dorg.gradle.jvmargs=-Xmx4g -Pnexmark.runner=:runners:flink:1.10 "-Pnexmark.args=--bigQueryTable=nexmark --project=apache-beam-testing --resourceNameMode=QUERY_RUNNER_AND_MODE --exportSummaryToBigQuery=true --tempLocation=gs://temp-storage-for-perf-tests/nexmark --manageResources=false --monitorJobs=true --suite=SMOKE --streamTimeout=60 --shutdownSourcesOnFinalWatermark=true --runner=FlinkRunner --bigQueryDataset=nexmark_PRs --streaming=false" :sdks:java:testing:nexmark:run
```
Not sure why because I ran the seed job.

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Turns out there are flags which are not used. Need to trigger the seed again.

**Comment by mxm** [comment]
Run Seed Job

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Java PreCommit is flaky due to https://issues.apache.org/jira/browse/BEAM-9578

**Pull request merged**
