### PR TITLE
Update website source release link

### PR DESCRIPTION
**Pull request by charlesccychen**
This change addresses issues identified by the Apache announce list owners:

```
Hi! This is the ezmlm program. I'm managing the
announce@apache.org mailing list.

I'm sorry, your message (enclosed) was not accepted by the moderator.
If the moderator has made any comments, they are shown below.

>>>>> -------------------- >>>>>
Sorry, but the download page is not acceptable.

Download links of source releases must use the ASF mirror system, i.e. must
be of the form:

http://www.apache.org/dyn/closer.cgi/beam/2.7.0/apache-beam-2.7.0-source-release.zip
(KEYS, sigs and hashes use https://www.apache.org/dist/beam/...)

Please correct the download page and resubmit the announce.

Sebb.
<<<<< -------------------- <<<<<
```

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @chamikaramj

**Comment by charlesccychen** [comment]
Run Website PreCommit

**Comment by charlesccychen** [comment]
Run Website PreCommit

**Comment by charlesccychen** [comment]
Looks like the website precommit is broken with:

```
13:12:35 Step 3/7 : RUN gem install bundler
13:12:35  ---> Running in 5cedb6a0631a
13:12:35 grpc: the connection is unavailable
```

CC: @swegner

**Comment by charlesccychen** [comment]
Run Website PreCommit

**Comment by swegner** [comment]
LGTM

**Comment by swegner** [comment]
For posterity, the flaky precommit job was here: https://builds.apache.org/job/beam_PreCommit_Website_Commit/339/

I'll file a JIRA

**Pull request merged**
