### PR TITLE
Add try-except for process.send_signal so it can work on Windows.

### LINKED ISSUE #21069: subprocess_server.stop_process fails on Windows
subprocess_server's stop_process method uses send_signal(signal.SIGINT) which is not a cross-platform way to terminate a process. We should probably use [terminate or kill](https://github.com/apache/beam/blob/acc0f76a2f3292276ae144f84c4130c504a334a1/sdks/python/apache_beam/transforms/external.py#L294) here instead.

This is callled when closing the [context](https://github.com/apache/beam/blob/acc0f76a2f3292276ae144f84c4130c504a334a1/sdks/python/apache_beam/transforms/external.py#L294) in ExternalTransform. From [user@ bug report](https://lists.apache.org/thread.html/rd0e83292391e8d214ffca8eedae7d096b7fb463dc17971472c78c463%40%3Cuser.beam.apache.org%3E)

```

Traceback (most recent call last):
  File "beam-sql.py", line 18, in <module>
    |'sql print' >>
beam.Map(print)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\pvalue.py",
line 142, in __or__
    return self.pipeline.apply(ptransform, self)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\pipeline.py",
line 641, in apply
    transform.transform, pvalueish, label or transform.label)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\pipeline.py",
line 651, in apply
    return self.apply(transform, pvalueish)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\pipeline.py",
line 694, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)

 File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\runners\runner.py",
line 188, in apply
    return m(transform, input, options)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\runners\runner.py",
line 218, in apply_PTransform
    return transform.expand(input)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\transforms\external.py",
line 304, in expand
    pipeline.local_tempdir)
  File "c:\users\XXX\appdata\local\programs\python\python37\lib\contextlib.py",
line 119, in __exit__
    next(self.gen)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\transforms\external.py",
line 351, in _service
    yield stub
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\transforms\external.py",
line 503, in __exit__
    self._service_provider.__exit__(*args)
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\utils\subprocess_server.py",
line 72, in __exit__
    self.stop()
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\utils\subprocess_server.py",
line 131, in stop
    self.stop_process()
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\utils\subprocess_server.py",
line 181, in stop_process
    return super(JavaJarServer, self).stop_process()
  File "C:\Users\XXX\Documents\8-Git\apache_beam\venv\lib\site-packages\apache_beam\utils\subprocess_server.py",
line 141, in stop_process
    self._process.send_signal(signal.SIGINT)
  File "c:\users\XXX\appdata\local\programs\python\python37\lib\subprocess.py",
line 1306, in send_signal
    raise ValueError("Unsupported signal: {}".format(sig))
ValueError: Unsupported
signal: 2

```

Imported from Jira [BEAM-12501](https://issues.apache.org/jira/browse/BEAM-12501). Original Jira may contain additional context.
Reported by: bhulette.

### PR DESCRIPTION
**Pull request by jamesroseman**
The current subprocess_server uses process.send_signal to terminate the process. On Windows, this will raise a ValueError, as .terminate() should be used instead.

**Please** add a meaningful description for your change here

This would close #21069

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by tvalentyn — APPROVED** [review]
Thanks!
Curious, in which scenario  are you using Beam + Windows?

**Comment by jamesroseman** [comment]
> Thanks! Curious, in which scenario are you using Beam + Windows?

Doing some prototyping at work where we're stuck on Windows machines (even though we deploy on Linux boxes). We also aren't allowed access to Docker on dev boxes which is another hurdle for using Beam...

**Comment by victorrgez** [comment]
We use it for debugging code in Local with DirectRunner before uploading changes to Dataflow. Because of this issue we had some problems and could not use in Local some Java cross-language transforms

> Thanks! Curious, in which scenario are you using Beam + Windows?

**Comment by the-xentropy** [comment]
I think this patch regressed at some point. The stop code now is a raw SIGINT with no try-except block.

**Pull request merged**
