### PR TITLE
Add support for all Java based portable runners to consume elements embedding on the control response.

### LINKED ISSUE #25462: [Feature Request]: Java Portable Runners use control_response_elements_embedding optimization
### What would you like to happen?

Now that the Dataflow JRH is gone and the shared runner code has been migrated to use the newer BeamFnDataInboundAggregator and BeamFnDataOutboundObserver we can add the optimization where for small undles we embed the data on the process bundle request and the response building on the SDK specific solution in https://issues.apache.org/jira/browse/BEAM-13193

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [X] Component: Flink Runner
- [X] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by lukecwik**
Fixes #25462

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by lukecwik** [comment]
R: @y1chi

**Comment by lukecwik** [comment]
Note that the 3 pending checks passed but Github has yet to update the UI:
https://ci-beam.apache.org/job/beam_PreCommit_Kotlin_Examples_Commit/3759/
https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Commit/13459/
https://ci-beam.apache.org/job/beam_PreCommit_RAT_Commit/50364/

**Review by y1chi — APPROVED** [review]
LGTM

**Pull request merged**
