### PR TITLE
[Website] update runners table content overflow

### LINKED ISSUE #22708: [Bug]: Right navigation bar overlaps the table of runners, due to the fact that some tables do not shrink when the screen size is reduced.
### What happened?

**What happened?**

Steps to reproduce:
1. [Open the samza runner page](https://beam.apache.org/documentation/runners/samza/) in the browser
2. Click on the button "Documentation/Runners" in the navbar
3. Reduce the width of the page to 1080px
4. Scroll to the section with table Pipeline options for the Samza Runner
5. Scroll down that the right menu overlaps the table

Actual result: Right nav menu overlaps the table
Expected result: Right nav menu doesn't overlap the table

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22708
- add container with overflow-x property to runners with table with content overflow
________________________________________________________________________________________________________________________________
before:
table_before

after: 
tabler_after

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by alevtinaboiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, help with review?

**Review by pcoet — APPROVED** [review]

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, help with merging?

**Comment by aromanenko-dev** [comment]
Thanks! Merged

**Comment by bullet03** [comment]
> @aromanenko-dev, could you, please, help with merging?



> Thanks! Merged

Thank you!

**Comment by bullet03** [comment]
> Thanks! Merged

Thank you for the quick response!

**Pull request merged**
