### PR TITLE
[BEAM-2188]  Cherry-pick #3024

### PR DESCRIPTION
**Pull request by aaltay**
R: @kennknowles 
cc: @davorbonaci

### CODE REVIEW

**Comment by kennknowles** [comment]
Confirmed that diffs are identical. LGTM upon green.

**Comment by dhalperi** [comment]
Tests passed except for an HBase flake. merging.

**Comment by dhalperi** [comment]
Merged, close at your leisure :)

**Comment by aaltay** [comment]
Thank you.

**Pull request closed without merging**
