### PR TITLE
BEAM-2373 Upgrade commons-compress dependency version to 1.14

### PR DESCRIPTION
**Pull request by adude3141**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

@iemejia plz have a look

### CODE REVIEW

**Comment by adude3141** [comment]
comons-compress seems to be used currently by
- java-sdk-core, shaded, not epxosed
- spark-runner, provided dep
- flink-runner, version upgrade of the transitive flink dependency

So it might be helpful if someone of the flink-runner team has also a look, wether this incurs any issues.

**Comment by dhalperi** [comment]
R: @aljoscha 

This LGTM, especially as it fixes a bug in the core SDK. We can separately version Spark/Flink as needed, but since Spark is provided may not matter much.

I think we can

**Comment by adude3141** [comment]
This PR shouldnt be merged right now. It seems to break https://github.com/apache/beam/blob/master/sdks/java/extensions/google-cloud-platform-core/src/test/java/org/apache/beam/sdk/extensions/gcp/GcpCoreApiSurfaceTest.java

At least currently i am not able to do a (private) release.

**Comment by adude3141** [comment]
Stacktrace

```
[INFO] java.lang.NoClassDefFoundError: Lorg/brotli/dec/BrotliInputStream;
[INFO]  at java.lang.Class.getDeclaredFields0(Native Method)
[INFO]  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[INFO]  at java.lang.Class.getDeclaredFields(Class.java:1916)
[INFO]  at org.apache.beam.sdk.util.ApiSurface.addExposedTypes(ApiSurface.java:739)
[INFO]  at org.apache.beam.sdk.util.ApiSurface.constructExposedToExposers(ApiSurface.java:536)
[INFO]  at org.apache.beam.sdk.util.ApiSurface.getExposedToExposers(ApiSurface.java:517)
[INFO]  at org.apache.beam.sdk.util.ApiSurface.getExposedClasses(ApiSurface.java:426)
[INFO]  at org.apache.beam.sdk.util.ApiSurface$Matchers$ClassesInSurfaceMatcher.verifyNoDisallowed(ApiSurface.java:273)
[INFO]  at org.apache.beam.sdk.util.ApiSurface$Matchers$ClassesInSurfaceMatcher.matchesSafely(ApiSurface.java:302)
[INFO]  at org.apache.beam.sdk.util.ApiSurface$Matchers$ClassesInSurfaceMatcher.matchesSafely(ApiSurface.java:168)
[INFO]  at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:55)
[INFO]  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
[INFO]  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
[INFO]  at org.apache.beam.GcpCoreApiSurfaceTest.testApiSurface(GcpCoreApiSurfaceTest.java:56)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[INFO]  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[INFO]  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[INFO]  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[INFO]  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[INFO]  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[INFO]  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[INFO]  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[INFO]  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[INFO]  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[INFO]  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[INFO]  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[INFO]  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[INFO]  at org.junit.runners.Suite.runChild(Suite.java:128)
[INFO]  at org.junit.runners.Suite.runChild(Suite.java:27)
[INFO]  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[INFO]  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[INFO]  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[INFO]  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[INFO]  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[INFO]  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
[INFO]  at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
[INFO]  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
[INFO] Caused by: java.lang.ClassNotFoundException: org.brotli.dec.BrotliInputStream
[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO]  ... 48 more
```

**Comment by aljoscha** [comment]
I think it's save to merge from the Flink side. We already have a version that is different from the version in Flink.

**Comment by dhalperi** [comment]
retest this please

**Comment by dhalperi** [comment]
The issue with `ApiSurfaceTest` seems to be that 1.14 has added new, optional compile-time dependencies (such as brotli) that are causing ClassLoader errors when iterating over the binary classes in SDK-java-core.

**Comment by adude3141** [comment]
@dhalperi Yes. But but unfortunately i have no idea, how that should/could be fixed :(

**Comment by dhalperi** [comment]
https://issues.apache.org/jira/browse/BEAM-2389 is implicated.

**Comment by aaltay** [comment]
@kennknowles is this something you can help @adude3141 ?

**Comment by adude3141** [comment]
Created a [PR for BEAM-2389](https://github.com/apache/beam/pull/3436)

After merge of that, this should not break anymore.

**Comment by lukecwik** [comment]
Now that [PR for BEAM-2389](https://github.com/apache/beam/pull/3436) is in and tests are green, merging.

**Pull request closed without merging**
