### PR TITLE
[BEAM-8944] Change to use single thread in py sdk bundle progress report

### PR DESCRIPTION
**Pull request by y1chi**
Use UnboundedThreadWorkerExecutor in bundle progress report introduces performance complications (by using too many threads. Experiment shows that a typical streaming wordcount pipeline which can deal with 360 messages/(second, worker) is only capable of process around 200 messages/(second, worker) with same resource. This PR aim to mitigate the performance and cost change of existing pipeline by change the use of UnboundedThreadWorkerExecutor in bundle progress report to just single thread executor.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by y1chi** [comment]
retest this please

**Comment by y1chi** [comment]
R: @angoenka @lukecwik

**Comment by y1chi** [comment]
retest this please

**Comment by y1chi** [comment]
Run PythonLint PreCommit

**Comment by y1chi** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Would it be better to have the runner request progress less frequently?

**Comment by y1chi** [comment]
> Would it be better to have the runner request progress less frequently?

I think that helps too. I believe right now JRH requests every 0.1 sec.

**Comment by y1chi** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
> > Would it be better to have the runner request progress less frequently?
> 
> I think that helps too. I believe right now JRH requests every 0.1 sec. Not exactly sure how the frequency is picked.

0.1 secs is a lot and doesn't seem right.

**Comment by y1chi** [comment]
> > > Would it be better to have the runner request progress less frequently?
> > 
> > 
> > I think that helps too. I believe right now JRH requests every 0.1 sec. Not exactly sure how the frequency is picked.
> 
> 0.1 secs is a lot and doesn't seem right.

I think this is where it is set, we can try to tune that down.
https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L296

Single thread should be good enough for progress report in python sdk harness and shouldn't incur stuckness issues, and it could also help limiting its impact on the bundle processing critical path.

**Comment by lukecwik** [comment]
> > > > Would it be better to have the runner request progress less frequently?
> > > 
> > > 
> > > I think that helps too. I believe right now JRH requests every 0.1 sec. Not exactly sure how the frequency is picked.
> > 
> > 
> > 0.1 secs is a lot and doesn't seem right.
> 
> I think this is where it is set, we can try to tune that down.
> https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L296
> 
> Single thread should be good enough for progress report in python sdk harness and shouldn't incur stuckness issues, and it could also help limiting its impact on the bundle processing critical path.

Yeah, thats the wrong constant to use since that is meant to be used in a tight read loop using a lock which is inappropriate for API calls. I believe the Dataflow service has used 30 seconds for progress updates between the server and the worker so we could do anywhere between 5 and 30 seconds and still be fine.

**Comment by y1chi** [comment]
> > > > > Would it be better to have the runner request progress less frequently?
> > > > 
> > > > 
> > > > I think that helps too. I believe right now JRH requests every 0.1 sec. Not exactly sure how the frequency is picked.
> > > 
> > > 
> > > 0.1 secs is a lot and doesn't seem right.
> > 
> > 
> > I think this is where it is set, we can try to tune that down.
> > https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L296
> > Single thread should be good enough for progress report in python sdk harness and shouldn't incur stuckness issues, and it could also help limiting its impact on the bundle processing critical path.
> 
> Yeah, thats the wrong constant to use since that is meant to be used in a tight read loop using a lock which is inappropriate for API calls. I believe the Dataflow service has used 30 seconds for progress updates between the server and the worker so we could do anywhere between 5 and 30 seconds and still be fine.

it seems that it will slow down the bundle processing scheduling if I increase the period and the pipeline can become super slow. I'm guessing it will affect the time when a bundle process instruction can be considered finished.

**Comment by lukecwik** [comment]
> > > > > > Would it be better to have the runner request progress less frequently?
> > > > > 
> > > > > 
> > > > > I think that helps too. I believe right now JRH requests every 0.1 sec. Not exactly sure how the frequency is picked.
> > > > 
> > > > 
> > > > 0.1 secs is a lot and doesn't seem right.
> > > 
> > > 
> > > I think this is where it is set, we can try to tune that down.
> > > https://github.com/apache/beam/blob/master/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L296
> > > Single thread should be good enough for progress report in python sdk harness and shouldn't incur stuckness issues, and it could also help limiting its impact on the bundle processing critical path.
> > 
> > 
> > Yeah, thats the wrong constant to use since that is meant to be used in a tight read loop using a lock which is inappropriate for API calls. I believe the Dataflow service has used 30 seconds for progress updates between the server and the worker so we could do anywhere between 5 and 30 seconds and still be fine.
> 
> it seems that it will slow down the bundle processing scheduling if I increase the period and the pipeline can become super slow. I'm guessing it will affect the time when a bundle process instruction can be considered finished.

Progress updates are independent of the bundle processing and it finishing since those are separate messages over the control channel so updating the progress update interval will only impact how "fresh" the progress data. See [this call flow for processing a bundle](https://docs.google.com/document/d/1NehB__CxJTmjxkt7hDYIJWNDLJyEoE0b-AUJvInHPCI/edit#heading=h.uru28odsw263) and [this call flow for progress updates](https://docs.google.com/document/d/1qs57tupLFEBbWpQK5KJtRdB7wsaQhkaafz033eixys8/edit#).

**Comment by y1chi** [comment]
Then I guess delayed update on https://github.com/apache/beam/blob/6a63c065687445dd914a60fc47ade7b9f6a84ad2/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L368 might have a throttling effect?

I've tried 2, 3, 5 secs, and the performance looks pretty poor for any of these periods.

**Comment by lukecwik** [comment]
> Then I guess delayed update on
> 
> https://github.com/apache/beam/blob/6a63c065687445dd914a60fc47ade7b9f6a84ad2/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L368
> 
> might have a throttling effect?
> I've tried 2, 3, 5 secs, and the performance looks pretty poor for any of these periods.

I see that there is throttling going on there but it is unnecessary now. The SDK is responsible for performing push back. The server needs to be configured to not use too much buffer space. At this point in time we may just want to leave this as is and wait for the UW to be released since it doesn't rely on this 0.1 second polling interval or go with your original plan of using a single thread with a TODO to remove it.

WDYT?

**Comment by y1chi** [comment]
> > Then I guess delayed update on
> > https://github.com/apache/beam/blob/6a63c065687445dd914a60fc47ade7b9f6a84ad2/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L368
> > 
> > might have a throttling effect?
> > I've tried 2, 3, 5 secs, and the performance looks pretty poor for any of these periods.
> 
> I see that there is throttling going on there but it is unnecessary now. The SDK is responsible for performing push back. The server needs to be configured to not use too much buffer space. At this point in time we may just want to leave this as is and wait for the UW to be released since it doesn't rely on this 0.1 second polling interval or go with your original plan of using a single thread with a TODO to remove it.
> 
> WDYT?



> > Then I guess delayed update on
> > https://github.com/apache/beam/blob/6a63c065687445dd914a60fc47ade7b9f6a84ad2/runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/fn/control/BeamFnMapTaskExecutor.java#L368
> > 
> > might have a throttling effect?
> > I've tried 2, 3, 5 secs, and the performance looks pretty poor for any of these periods.
> 
> I see that there is throttling going on there but it is unnecessary now. The SDK is responsible for performing push back. The server needs to be configured to not use too much buffer space. At this point in time we may just want to leave this as is and wait for the UW to be released since it doesn't rely on this 0.1 second polling interval or go with your original plan of using a single thread with a TODO to remove it.
> 
> WDYT?

I fully agree that we should try to remove the throttling and lower the frequency in JRH and opened https://issues.apache.org/jira/browse/BEAM-8998, meanwhile I think it's still better we use a single thread as a intermediate solution since user may take sometime to adopt UW.
Also added TODO.

**Comment by angoenka** [comment]
Thanks!
LGTM too.

**Pull request merged**
