### PR TITLE
[BEAM-3348] Set utf-16 as SQL DSL default charset

### PR DESCRIPTION
**Pull request by Alienero**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by Alienero** [comment]
hi, @XuMingmin  can you please take a look

**Comment by XuMingmin** [comment]
retest this please

**Comment by Alienero** [comment]
hi @XuMingmin , I hava run `mvn clean verify` in `beam/sdks/java/extensions/sql`, all unit test passwd. please take a look

**Comment by Alienero** [comment]
retest this please.

**Comment by robertwb** [comment]
What's the motivation for UTF-16? Everywhere else we seem to use UTF-8.

**Comment by Alienero** [comment]
hi @XuMingmin，I made some additions: add default `national charset` and `collation`. `uft-16` also as default charset for the N'string' construct

**Comment by XuMingmin** [comment]
retest this please

**Comment by XuMingmin** [comment]
retest this please

**Pull request merged**
