### PR TITLE
[BEAM-2571] CombineTest.testSlidingWindowsCombineWithContext

### PR DESCRIPTION
**Pull request by aljoscha**
This is a rebased version of #3550. I didn't want to mess with the comments and history on that other PR.

R: @peihe (and the others from the older PR)

### CODE REVIEW

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
@peihe Do you think this is good to merge now? I added the separate function for the Flink watermark.

**Comment by peihe** [comment]
LGTM

**Comment by peihe** [comment]
@asfgit merge

**Comment by aljoscha** [comment]
Thanks! Yes will do, unfortunately we don't yet have a merge bot on the main repo.

**Pull request closed without merging**
