### PR TITLE
Disable Gradle agent for Jenkins build jobs.

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
What about job_beam_PreCommit_Python_GradleBuild.groovy and job_beam_Release_Gradle_NightlySnapshot.groovy?

Using setGradleSwitches works less well due to the little variations between the runs. Your choice if you want to keep it or go back to enumerating them all each time.

**Comment by swegner** [comment]
Added `PostRelease_NightlySnapshot` and `Release_Gradle_NightlySnapshot`. 

`job_beam_PreCommit_Python_GradleBuild.groovy` is already converted.

@lukecwik PTAL

**Comment by lukecwik** [comment]
Run Seed Job

**Comment by swegner** [comment]
Run Seed Job

**Comment by swegner** [comment]
Run Seed Job

**Comment by swegner** [comment]
SeedJob succeeded. @lukecwik PTAL

**Pull request merged**
