### PR TITLE
[BEAM-9283] Add Java 11 Jpms compatibility tests for Spark runner

### PR DESCRIPTION
**Pull request by iemejia**
R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Jpms Spark Java 11 PostCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Jpms Spark Java 11 PostCommit

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by iemejia** [comment]
Thanks @ibzib

**Pull request merged**
