### PR TITLE
[prism] UI improvements.

### PR DESCRIPTION
**Pull request by lostluck**
Does a number of things to improve the Prism runner UI experience.

* Allows the UI to be pointed to any JobManagement instance, where it will render the information it gets.
* Improve the JobDetails page with topologically sorted transforms, and the input and output pcollection element counts.
* Have the state included in the details page.
* Include basic instructions on using the stand alone prism command.
* Allow the command to run either the management server or the UI as desired. This allows using the UI against any JobManagement endpoint, including a different instance of itself. This allows better iteration on the UI since the state of the JobManagement server doesn't need to restart from scratch each time for checking changes. Probably allows for automatic recompiles in the future.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
The next PR in this space is going to re-factor and test the various sub bits of the web server, since that coverage number bothers me.

**Review by riteshghorse — APPROVED** [review]
LGTM, thanks!

**Comment by lostluck** [comment]
Run Go Precommit

**Comment by riteshghorse** [comment]
Run GoPortable PreCommit

**Comment by riteshghorse** [comment]
Run RAT PreCommit

**Comment by riteshghorse** [comment]
Run Whitespace PreCommit

**Comment by riteshghorse** [comment]
There were a couple of whitespace lint. I went ahead and did it

**Comment by lostluck** [comment]
Thank you kindly for that! Meant yo merge this a bit earlier but vacation is vacation.

**Pull request merged**
