### PR TITLE
[BEAM-5334] Fix java performance test - No Beam python setup for other language

### PR DESCRIPTION
**Pull request by markflyhigh**
Few steps in Jenkins setup are specific for Beam Python SDK which should not be called when running Java performance benchmarks.

This refactor should isolate current test failure only to beam_Performance_Python_test.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by markflyhigh** [comment]
Run Seed Job

**Comment by markflyhigh** [comment]
Run Java TextIO Performance Test

**Comment by markflyhigh** [comment]
Java TextIO Performance Test passed with this change. Ready for review.

+R: @chamikaramj

**Comment by lgajowy** [comment]
I also took the liberty of reviewing this change because recently I was looking closely at what is going on with IO Performance Tests and searched for a sensible solution to the problem (still no luck). 

This change LGTM. I think that even without the current problems with python setup this should have been done like this.

**Comment by lgajowy** [comment]
Run Seed Job

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by lgajowy** [comment]
Thank you Mark! I'm merging this

**Pull request merged**
