### PR TITLE
Actually test the fn_api_runner.

### PR DESCRIPTION
**Pull request by robertwb**
The test suite was not being run due to a typo.
Fix breakage due to changes in the code in the meantime.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by robertwb** [comment]
retest this please (hadoop failure)

**Comment by robertwb** [comment]
retest this please

**Pull request closed without merging**
