### PR TITLE
Support SqlTypes Date in AvroUtils

### LINKED ISSUE #23299: [Feature Request]: AvroUtils.toAvroSchema supports a logicaltypes.Date type
### What would you like to happen?

Hi, folks,
I'm using a SQLTransform to read & write a Date field to parquet files. However, AvroUtils.toAvroSchema can't convert org.apache.beam.sdk.schemas.logicaltypes.Date to a avro date type. Because its identifier is `beam:logical_type:date:v1`, which can't be handled in method org.apache.beam.sdk.schemas.utils.AvroUtils.genericFromBeamField

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #23299

Re-introduce part of #23969 (one direction  SqlTypes Date to Avro Date) which was later reverted due to breaking change to Beam SQL. The breaking change of  #23969 was the introduce of bi-direction Avro TimestampMicros and SqlTypes DateTime support which is not included in this PR.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
This PR suffices to fix the requested use case of #23299 (beam:logical_type:date:v1 which is SqlTypes.DATE) , though SqlTypes.TIMESTAMP remains unsupported to AvroUtils

**Comment by Abacn** [comment]
R: @apilloud

**Comment by Abacn** [comment]
[Java_Examples_Dataflow_Java17](https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java17_Commit/4923/) and [Java_GCP_IO_Direct](https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Commit/1170/) actually passed but did not show status on GitHub

**Review by apilloud — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
There is an ongoing migration of avro-related stuff from core to extension (#24292). The first step (#24293) copied AvroUtils into an extension project not including this PR. Mark here and need to synchronize newly added code changes of core avro to avro extension before #24748 resolved.

**Pull request merged**
