### PR TITLE
[BEAM-10785] Add support for coder argument in WriteToBigQuery

### PR DESCRIPTION
**Pull request by harrydrippin**
This PR fixes BEAM-10785 by adding the `coder` argument from `WriteToBigQuery` to `JsonRowWriter` to enable users to modify the coder for various reasons on batch pipeline. The `coder` argument will be defaulted to `RowAsDictJsonCoder` if user didn't specify.

This modification needs to add `coder` argument on below classes and functions. This PR also applies changes for them.

* `BigQueryBatchFileLoads`
* `WriteRecordsToFile`
* `WriteGroupedRecordsToFile`
* `_make_new_file_writer()`
* `JsonRowWriter`

This version was tested on `DataflowRunner` and there were no any problems while using custom coder. But this PR does not have any additional unit tests now, so it will be great if reviewers can provide some directions about appropriate unit tests. Please let me know if there are any concerns on this PR. Thank you!

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by harrydrippin** [comment]
R: @aaltay
R: @charlesccychen

**Comment by harrydrippin** [comment]
Run Python_PVR_Flink PreCommit

**Comment by aaltay** [comment]
R: @johnjcasey

**Comment by johnjcasey** [comment]
This LGTM. I don't think we need a test case for this, because ultimately it is just passing the coder downstream

**Comment by aaltay** [comment]
Could you please resolve the conflicts? And I can merge after that.

**Comment by pabloem** [comment]
my apologies on the delay to review this, but it is still not clear to me why we need to add this feature to WriteToBQ.

I see in https://issues.apache.org/jira/browse/BEAM-10785 that non-ascii characters are replaced when formatting in JSON - is that correct? Does this cause a problem when inserting into BigQuery? Can you explain the problem in more detail?

Generally, I'd prefer if we did not have to define a new parameter - but rather fix the existing coder if it has any issues. Can you please share the use case that this would address?

**Comment by harrydrippin** [comment]
@pabloem The problem in my case was occurred when I was processing the chat data including emojis and putting it into BigQuery (they were all replaced to replacement character), so our major need in this problem was to disable `ensure_ascii` from `True` to `False` on  `json.dumps()`. But there was no exposed control for replacing that argument, so I temporarily customized `RowAsDictJsonCoder` and `WriteToBigQuery` in my environment like below:

```python
class CustomRowAsDictJsonCoder(coders.Coder):

    def encode(self, table_row):
        try:
            # ...
            return json.dumps(table_row, ensure_ascii=False, default=default_encoder).encode("utf-8")
            #                            ------------------
        # except: ...
```

I also prefer to not define any additional parameters if possible, but I thought that we don't have any possible way to modify parameters inside the coder, or replace the coder. Please correct me if you have any concern over this.

**Comment by harrydrippin** [comment]
@aaltay Conflict is resolved.

**Comment by pabloem** [comment]
@harrydrippin thanks for the analysis, and great catch! - I think your fix to the coder itself would be a much better fix. Would you be willing to perform that fix instead?

**Comment by harrydrippin** [comment]
@pabloem Just for sure, do you mean it is good if I apply the change to the original `RowAsDictJsonCoder` implementation just like my custom one? (adding `ensure_ascii=False` on the `json.dumps`)

I will submit another PR for this if you confirm. Thanks!

**Comment by aaltay** [comment]
@harrydrippin - What is the next step on this PR?

**Comment by harrydrippin** [comment]
@aaltay I am going to submit another PR (fixing coder) for this issue.

**Comment by pabloem** [comment]
I'll close this as we got the other fix. Sorry again about the big delay!

**Pull request closed without merging**
