### PR TITLE
Upgrade to latest Gradle

### PR DESCRIPTION
**Pull request by swegner**
https://docs.gradle.org/4.6/release-notes.html

### CODE REVIEW

**Comment by swegner** [comment]
R: @lukecwik

**Comment by kennknowles** [comment]
Nice maven and testing enhancements. The new custom commandline support may be just the thing for the Nexmark run, though looks like you have to switch to a high-boilerplate mode.

**Comment by kennknowles** [comment]
Wait we could be writing Kotlin instead of Groovy !?!?

**Comment by swegner** [comment]
R: @kennknowles since @lukecwik is on vacation.

**Comment by kennknowles** [comment]
This actually now looks like a downgrade to a very old gradle. Typo? Bad merge?

**Comment by swegner** [comment]
Hah, good catch. I had run the wrong command-line. Re-ran with `gradle wrapper --gradle-version=4.6`

Note for posterity that we've added Apache license headers to the wrapper files, which need to be re-added after running the above command.

@kennknowles PTAL

**Comment by kennknowles** [comment]
run java precommit

**Comment by swegner** [comment]
run java precommit

**Comment by swegner** [comment]
run java precommit

**Comment by swegner** [comment]
Ok, we finally got a green run. Merge before Jenkins changes his mind! @kennknowles

**Comment by swegner** [comment]
ping @kennknowles, tests are green and this is ready to merge.

**Comment by kennknowles** [comment]
Well, _Java_ tests are green...

**Comment by kennknowles** [comment]
Is the Python precommit known broken?

**Comment by swegner** [comment]
run python precommit

**Comment by swegner** [comment]
All checks passed :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: 
@kennknowles PTAL

**Pull request merged**
