### PR TITLE
[BEAM-10779] Support multiple main inputs and side inputs for PTransformOverride

### PR DESCRIPTION
**Pull request by yifanmai**
Currently, `PTransformOverride` only supports overriding `PTransform` s that have a single input. This change adds support for multiple main inputs and side inputs.

The change introduces a new method `PTransformOverride.get_replacement_inputs(self, applied_ptransform)` that can be overridden by end users. This method will be called to get the inputs for the replacement `PTransform.` The default implementation will return a tuple of all the main inputs in order, concatenated with the all the side inputs `PValue` s in order.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
Build python source distribution and wheels
Python tests

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by yifanmai** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Please address test failures. You should be able to rerun test suites by adding the trigger (mention in quotes) as a comment.

**Comment by yifanmai** [comment]
The remaining failing tests seem unrelated and non-spurious. How should I resolve this?

**Portable_Python**
> docker: Error response from daemon: Conflict. The container name "/license-container-python" is already in use by container "a52b4fd35d9c5c813b2318e1ca5d4da3c8649f2756a78890f61648f1f450c6c0". You have to remove (or rename) that container to be able to reuse that name.

**Python**

Tasks :sdks:python:test-suites:tox:py35:testPy35Cloud and :sdks:python:test-suites:tox:py35:testPy35Cython both fail with:

> SystemError: Parent module 'setuptools' not loaded, cannot perform relative import

**Comment by yifanmai** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Yeah, seems like Python PreCommit is broken currently. We'll have to wait till HEAD is fixed to retry tests.

cc: @ibzib

**Comment by ibzib** [comment]
> Yeah, seems like Python PreCommit is broken currently. We'll have to wait till HEAD is fixed to retry tests.

Thanks for the notification, I filed and am triaging BEAM-10841

**Comment by chamikaramj** [comment]
Thanks Kyle.

**Comment by ibzib** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Retest this please

**Comment by yifanmai** [comment]
Run PythonDocker PreCommit

**Comment by yifanmai** [comment]
Now I'm running into:

> Traceback (most recent call last):
>  File "/tmp/license_scripts/pull_licenses_py.py", line 146, in <module>
    raise RuntimeError(
>RuntimeError: Could not retrieve licences for packages ['pbr'] in Python3.8 environment. 
> These licenses were not able to be pulled automatically. Please search code source of the dependencies on the internet and add urls to RAW license file at sdks/python/container/license_scripts/dep_urls_py.yaml for each missing license and rerun the test. If no such urls can be found, you need to manually add LICENSE and NOTICE (if available) files at sdks/python/container/license_scripts/manual_licenses/{dep}/ and add entries to sdks/python/container/license_scripts/dep_urls_py.yaml.

**Comment by yifanmai** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Run PythonDocker PreCommit

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
Run Python 3.5 PostCommit

**Comment by yifanmai** [comment]
Run Python 3.8 PostCommit

**Comment by yifanmai** [comment]
Precommits (besides codecov) look good.

**Review by chamikaramj — APPROVED** [review]
Thanks.

**Pull request merged**
