### PR TITLE
[BEAM-9150] Fix beam_PostRelease_Python_Candidate (python RC validation scripts)

### PR DESCRIPTION
**Pull request by emilymye**
This PR:

* Adds clean-up step prior to running HourlyTeamScore
* Fixes variable/naming of tables to make table name (per-runner) more clear 
* `s/verify_steaming_result/verify_streaming_result`

We may also want to consider not failing on first test failure (we have set -e) so we can get other test signals at least.

Tested by cherry-picking into a 2.37.0 test branch (https://github.com/apache/beam/pull/16944), [test run](https://ci-beam.apache.org/job/beam_PostRelease_Python_Candidate/229/)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by emilymye** [comment]
R: @TheNeuralBit

**Comment by emilymye** [comment]
(running beam_PostRelease_Python_Candidate won't work on this PR because it looks for a version at https://dist.apache.org/repos/dist/dev/beam/`$VERSION`)

**Comment by tvalentyn** [comment]
Took a quick look, didn't see anything so LGTM.

> We may also want to consider not failing on first test failure (we have set -e) so we can get other test signals at least.
+1

**Comment by emilymye** [comment]
Run Java PreCommit

**Review by TheNeuralBit — APPROVED** [review]

**Comment by emilymye** [comment]
Given that these files shouldn't affect Java PreCommit at all (all release scripts), I feel safe ignoring the Java PreCommit failure

**Pull request merged**
