### PR TITLE
[BEAM-1272] Align the naming of "generateInitialSplits" and "splitIntoBundles" to better reflect their intention

### PR DESCRIPTION
**Pull request by echauchot**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).
---
As discussed in the ML, rename `generateInitialSplits` and `splitIntoBundles` methods to `splitIntoSubSources` as well as `@Test` methods and description in javadoc.
R: @jkff 
R: @staslev

### CODE REVIEW

**Comment by echauchot** [comment]
linked to https://github.com/apache/beam-site/pull/210

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by staslev** [comment]
Sorry I did not mention this in on the dev list thread, but I have a minor preference towards `split` over `splitIntoSubSources`, mainly because `SubSource` sounds like a new term we have not used before (as opposed to a `split`).

@echauchot  @jkff What do you think?

**Comment by jbonofre** [comment]
@staslev me too (as mentioned on the mailing list).

**Comment by echauchot** [comment]
I find `split` a bit less precise on the intent than `splitInto*Sources`. But I agree than **subSource** seems like a new term. Maybe a simple `splitIntoSources` ?

**Comment by jbonofre** [comment]
The purpose of a `split` (in an IO) is to create sources anyway.

**Comment by staslev** [comment]
> The purpose of a split (in an IO) is to create sources anyway.

+1

> Maybe a simple splitIntoSources?

`Source#splitIntoSources()` looks a bit confusing, perhaps because it may not be immediately apparent why one needs to have more sources from the source she already has. I guess that while this method does return a list of things that are technically sources, it may not be intuitive for us humans to thinks of this process as splitting a source into sources (sounds a bit off).

What I like about simply `split` is that it does not put the emphasis on what the source is **being split into** (bundles/sources/sub-sources, etc.), but on the mere fact the it is **being split** (so that it can be parallelised).

Makes sense?

**Comment by jkff** [comment]
I'm fine with `split`.

**Comment by jbonofre** [comment]
It seems we have an consensus about `split()`. @echauchot can you update the PR accordingly please ? Thanks !

**Comment by echauchot** [comment]
sure I'll update it. I'm fine with `split` also considering it is a method of *Source object, it's precise enough. Thanks for your feedback guys !

**Comment by jkff** [comment]
@echauchot This test error is no fault of this PR - it is because Dataflow worker depends on this method. Dealing with that in 1 commit requires a rather complicated process. Meanwhile, I suggest to simply add a (final and `@Deprecated`) method splitIntoBundles back to BoundedSource, which simply calls split(), and I'll help remove it afterwards.

**Comment by dhalperi** [comment]
+1 @jkff 

@echauchot this is great stuff -- need any help pushing it through?

**Comment by jbonofre** [comment]
retest this please

**Comment by dhalperi** [comment]
@jbonofre this won't be mergeable until Etienne updates it with the (temporary) suggestion from Eugene in https://github.com/apache/beam/pull/2523#issuecomment-294162285

**Comment by jbonofre** [comment]
Good point, I missed that. Thanks.

**Comment by jbonofre** [comment]
It's still not good on the `WordCount`.

**Comment by jbonofre** [comment]
Yes, that's why it failed on the previous build. Let's wait this one.

**Comment by echauchot** [comment]
Yes, I'm trying without the final method right now :)

**Comment by echauchot** [comment]
It's ok with the non-final deprecated `splitIntoBundles` method in `BoundedSource` for the dataflow integration. The build now passes.
PTAL

**Comment by jkff** [comment]
LGTM; @jbonofre feel free to merge. Thanks @echauchot !

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
actually please wait for this Dataflow test to pass, just in case.

**Comment by echauchot** [comment]
@jkff , with pleasure ! Do you want that I fill a jira in DataflowRunner component to remember to rebuild the dataflow worker and remove the deprecated method?

**Comment by echauchot** [comment]
@jbonofre @jkff: if you merge this PR, please don't forget that there is also a website update with it (https://github.com/apache/beam-site/pull/210)

**Comment by jbonofre** [comment]
Yeah, fixing the conflict and doing a new pass.

**Pull request closed without merging**
