### PR TITLE
[BEAM-7269] remove StateSpec from hashCode of SimpleStateTag

### PR DESCRIPTION
**Pull request by je-ik**
[BEAM-7269] remove StateSpec from hashCode of SimpleStateTag

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lukecwik** [comment]
There are some unit tests which need to be updated in [StateTagTest.java](https://scans.gradle.com/s/rdq7azgo7xsks/tests/failed)

The fixes seem trivial as in the tests should say the two state tags are the same even if the coders are different.

**Comment by je-ik** [comment]
Oops, I thought I have run the tests, but apparently I haven't. :-) Fixed.

**Comment by lukecwik** [comment]
Run Java PostCommit

**Comment by lukecwik** [comment]
@je-ik Do you want to take a look at https://issues.apache.org/jira/browse/BEAM-2777 since it also seems to be related to state incorrectly being stored in a map using the wrong key?

**Comment by lukecwik** [comment]
Thanks @je-ik

**Comment by je-ik** [comment]
@lukecwik sorry I didn't respond, is the issue you mentioned related to this? It seems to me, that it refers to storing user supplied keys in user states (which currently behaves similarily to how java collections work, which might not be an issue), or am I missing something?

**Comment by lukecwik** [comment]
Storing user keys inside a Java map assumes that equals and hashCode work correctly. Imagine the user uses a byte[] as there key (note byte[] only has object identity equality), then the map will store multiple keys with byte[]'s containing the same contents because we aren't using the [structural value](https://github.com/apache/beam/blob/b6f22efe9302f4e91d8d1eaf5a847f99ff33e2bf/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java#L249).

**Comment by je-ik** [comment]
Sure, that was exactly how I understood it, but my point was that that's exactly the way HashMap and HashSet work, so that probably won't be any surprise to Java developers. Although a simple fix would probably be to use coder and store serialized key wrapped in ByteBuffer or something similar. Question is if it is "worth it", because as noted previously, there will probably not be many people storing byte arrays as keys. Just my 2 cents.

**Comment by lukecwik** [comment]
A coder already has a method to return a value which implements equality without encoding the actual value (that is what [consistentWithEquals](https://github.com/apache/beam/blob/b6f22efe9302f4e91d8d1eaf5a847f99ff33e2bf/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java#L250) and [structuralValue](https://github.com/apache/beam/blob/b6f22efe9302f4e91d8d1eaf5a847f99ff33e2bf/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java#L249) is about). While other coders like [ByteArrayCoder](https://github.com/apache/beam/blob/b6f22efe9302f4e91d8d1eaf5a847f99ff33e2bf/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/ByteArrayCoder.java#L122) just return an equivalence wrapper around the object.

It is worth it because people will hit correctness issues otherwise around missing/wrong values stored in user state.

**Pull request merged**
