### PR TITLE
[BEAM-1763] Ensure run waitUntilFinish in TestPipeline.

### PR DESCRIPTION
**Pull request by peihe**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
Run Spark ValidatesRunner

**Comment by peihe** [comment]
Run Flink ValidatesRunner

**Comment by peihe** [comment]
Run Dataflow ValidatesRunner

**Comment by peihe** [comment]
Run Apex ValidatesRunner

**Comment by peihe** [comment]
Run Gearpump ValidatesRunner

**Comment by peihe** [comment]
@aviemzur

**Comment by aviemzur** [comment]
Run Dataflow ValidatesRunner

**Comment by aviemzur** [comment]
This change seems innocuous as all tests still pass, I'm wondering why you feel this change is needed though?

**Comment by aviemzur** [comment]
Can this PR be closed?

**Comment by reuvenlax** [comment]
update?

**Comment by aviemzur** [comment]
Closed for inactivity.

**Pull request closed without merging**
