### PR TITLE
Disable incremental compilation for SQL module

### PR DESCRIPTION
**Pull request by iemejia**
Calcite uses code generation for parsing. However in certain settings
(TieredCompilation) Maven does not generate the code when using
incremental compilation so disabling it is a defensive measure against
build breaks.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by echauchot** [comment]
should we not sync the gradle build?

**Comment by echauchot** [comment]
compilation times of module sql with and without incremental build are similar around 8s. So I guess deactivating it as a defensive measure is a good thing. Besides Jenkins fails on workcounts which is not related to this PR I think. LGTM, but I wonder if all PRs should update gradle build as soon as the change maven build.

**Comment by iemejia** [comment]
I suppose we should update the gradle build in every case, however the gradle build does not break because of this issue (at least in my tests) so I don't think it needs to be updated. Thanks for the review.

**Comment by jbonofre** [comment]
Sorry to been late on this one. It looks good to me.

**Pull request merged**
