### PR TITLE
[BEAM-3608] WIP: Vendored Guava 20

### PR DESCRIPTION
**Pull request by kennknowles**
This adds a module `beam-vendor-guava-20` that is just a namespaced redistribution of Guava 20.0. We would then depend on and ship this.

Benefits

 - Faster build, since we don't shade every project, only these vendor modules (which actually are very fast because there are far fewer classes being scraped)
 - Smaller jars, since we don't copy Guava 10x+
 - We can just ban a direct Guava dep easily
 - Trivial to verify that jar is 1:1 with namespace
 - Readable code because it doesn't get modified during build
 - You can actually use two versions and adapt between them if you need to

Reference: https://lists.apache.org/thread.html/12383d2e5d70026427df43294e30d6524334e16f03d86c9a5860792f@%3Cdev.beam.apache.org%3E

Open questions:

 - Should I put minor version in everything? Technically it shouldn't be needed, but in practice I imagine it could be.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by kennknowles** [comment]
@lukecwik Gradle does make this trivial. Huzzah.

I tried doing a closure-based config for the new function and it does seem like a huge pain where you have to make a bunch of boilerplate builders.

Seems like not worth it to mess with poms, even though still probably easy. It doesn't have benefits until we port our modules anyhow.

And the most benefit is when we've done this for all the shaded libs so we can turn off the whole process.

**Comment by kennknowles** [comment]
Suspiciously, when I depend on this in `runners-core-construction-java` it does not break the compile.

**Comment by lukecwik** [comment]
If you do `./gradlew -p vendor/guava/20 publishToMavenLocal`, what does the artifact look like (and what classifier does it use)?

Which configuration are you depending on in `vendor/guava/20` from `runners-core-construction-java`

**Comment by kennknowles** [comment]
BTW I did notice that we seem to put `shaded` classifier on a lot of artifacts which seem like they should be the default jar. I was trying to avoid that here.

**Comment by kennknowles** [comment]
There is no such task. Baked into java nature? I also want to avoid going through that code path since most of it is irrelevant. I will refactor the build rules.

**Comment by lukecwik** [comment]
We decouple the Gradle build (so it keeps around the pre-shaded and post-shaded artifacts) from what is uploaded to Maven (the post-shaded artifacts using the default classifier).

**Comment by kennknowles** [comment]
I think publishing is very relevant anyhow, right? I expected that these artifacts would be actually published even once we are fully migrated. I will definitely include publishing in this PR.

**Comment by kennknowles** [comment]
I won't be working on this for a while.

**Pull request closed without merging**
