### PR TITLE
Pin setup-gcloud to v0 instead of master

### PR DESCRIPTION
**Pull request by sethvargo**
setup-gcloud will be updating the branch name from master to main in
a future release. Even though GitHub will establish redirects, this
will break any GitHub Actions workflows that pin to master. This PR
updates your GitHub Actions workflows to pin to v0, which is the
recommended best practice.

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue. N/A
 - [x] Update `CHANGES.md` with noteworthy changes. N/A
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf). N/A

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by sethvargo** [comment]
There doesn't seem to be an obvious owner for this. @damccorm @jrmccluskey you edited these files more recently.

**Review by jrmccluskey — APPROVED** [review]
LGTM, we'll just have to get a committer to approve running those workflows to confirm that nothing breaks with the change

**Comment by jrmccluskey** [comment]
R: @lostluck @youngoli 

Can we get approval to run the workflows?

**Comment by lostluck** [comment]
Done. The Collect and Deploy workflow seems a bit heavy handed in when it runs (I've seen it on everything), but I can ensure the setup-gcloud step passes at least.

**Review by lostluck — APPROVED** [review]
LGTM Thanks for the forward fix!

**Comment by lostluck** [comment]
It passes that step, and fails on the a later step about JSON parsing. I'm happy to call this PR good though. Merging.

**Pull request merged**
