### PR TITLE
[BEAM-10278] Move Dataflow v2 cross-language tests out of runner module.

### PR DESCRIPTION
**Pull request by ibzib**
R: @kennknowles @ihji 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ibzib** [comment]
run seed job

**Comment by ibzib** [comment]
Run XVR_Dataflow PostCommit

**Comment by ibzib** [comment]
R: @amaliujia

**Comment by ibzib** [comment]
Run Java PreCommit

**Review by ihji — APPROVED** [review]
LGTM. Thanks for addressing the issue!

**Comment by ihji** [comment]
Please wait for merging this yet. I wanted try the other solution before merging this. We may also enable JavaUsingPython tests later and it will be little strange if we move this whole task under python test-suite.

**Comment by ibzib** [comment]
> I wanted try the other solution before merging this.

What other solution do you have in mind?

I agree that it is kind of awkward to have runner tests in the Python module, but I don't know of a better place to put them currently, since these tests inherently need dependencies from across SDKs and runners.

**Comment by ihji** [comment]
> > I wanted try the other solution before merging this.
> 
> What other solution do you have in mind?
> 
> I agree that it is kind of awkward to have runner tests in the Python module, but I don't know of a better place to put them currently, since these tests inherently need dependencies from across SDKs and runners.

It looks like the root cause is that we don't have python build.gradle in google3. I'm trying to skip createCrossLanguageValidatesRunnerTask if :sdks:python subproject doesn't exist. It's okay since we don't use that task in google3.

**Comment by ibzib** [comment]
> It looks like the root cause is that we don't have python build.gradle in google3. I'm trying to skip createCrossLanguageValidatesRunnerTask if :sdks:python subproject doesn't exist. It's okay since we don't use that task in google3.

That would probably work, but I'm not sure it's the best solution. I prefer moving the tests to `dataflow/common.gradle` because that way all of the tests that depend on both the Dataflow runner and Python are in the same place.

Also note that `dataflow/common.gradle` already transitively depends on the Java SDK, so this PR is only removing dependencies through consolidation.

**Comment by ihji** [comment]
> > It looks like the root cause is that we don't have python build.gradle in google3. I'm trying to skip createCrossLanguageValidatesRunnerTask if :sdks:python subproject doesn't exist. It's okay since we don't use that task in google3.
> 
> That would probably work, but I'm not sure it's the best solution. I prefer moving the tests to `dataflow/common.gradle` because that way all of the tests that depend on both the Dataflow runner and Python are in the same place.

I see. Please note that `createCrossLanguageValidatesRunnerTask` creates not only the python tests but also java tests. When we put `createCrossLanguageValidatesRunnerTask` in the build file, it creates four variants of xlang tests:

- Java pipeline using Python external transforms
- Java pipeline using Java external transforms
- Python pipeline using Python external transforms
- Python pipeline using Java external transforms

It's not totally impossible but it may look awkward to launch Java pipelines using Java external transforms from python:test-suites module.

> 
> Also note that `dataflow/common.gradle` already transitively depends on the Java SDK, so this PR is only removing dependencies through consolidation.

**Comment by ihji** [comment]
> > > I wanted try the other solution before merging this.
> > 
> > 
> > What other solution do you have in mind?
> > I agree that it is kind of awkward to have runner tests in the Python module, but I don't know of a better place to put them currently, since these tests inherently need dependencies from across SDKs and runners.
> 
> It looks like the root cause is that we don't have python build.gradle in google3. I'm trying to skip createCrossLanguageValidatesRunnerTask if :sdks:python subproject doesn't exist. It's okay since we don't use that task in google3.

Alternative fix: https://github.com/apache/beam/pull/13425

**Comment by ibzib** [comment]
Okay, let's go with #13425 instead. We can always revisit this or a similar solution later if we need to for some reason.

**Pull request closed without merging**
