### PR TITLE
[BEAM-2271] Remove files from source assembly

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

@aaltay I can't test this as I don't have permissions to follow the release guide. Can you test this out?

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by sb2nov** [comment]
cc @davorbonaci as he had concerns about not adding a descriptor file as we have been inheriting that from org.apache.apache so far.

I've been poking more at other ways to make this work so any help would be great.

**Comment by aaltay** [comment]
Any progress on this?

**Comment by sb2nov** [comment]
@jbonofre said he'll take a look but I wasn't able to make much more progress beyond this.

**Pull request closed without merging**
