### PR TITLE
[BEAM-6950] Upgrade spotbugs to version 4.0.3

### PR DESCRIPTION
**Pull request by iemejia**
R: @pabloem

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by iemejia** [comment]
Run JavaPortabilityApiJava11 PreCommit

**Comment by pabloem** [comment]
lgtm given that the we can get precommit to pass before merging

**Pull request closed without merging**
