### PR TITLE
[rollback][release-2.38.0][BEAM-14116] Rollback of #17004: Chunk commit requests dynamically

### PR DESCRIPTION
**Pull request by youngoli**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by youngoli** [comment]
R: @lukecwik @dpcollins-google @TheNeuralBit (whoever gets to it first)

For now I'm rolling these back to give the RC a try.

**Comment by dpcollins-google** [comment]
For #17004: the issue mentioned by @lukecwik was not reproducible, and I think we should import again
For #17094: This revealed an issue somewhere else in the codebase, what is the triggering test? I'll run it and fix that location as well

**Comment by dpcollins-google** [comment]
#17228 fixes the metrics issue

**Comment by dpcollins-google** [comment]
I don't think either of these needs to be rolled back on master or the release branch. I think the issue with https://github.com/apache/beam/pull/17004 was a false positive (or at least not reproducible) and #17094 just revealed an issue that would otherwise have failed later in processing on runnerv2

**Comment by dpcollins-google** [comment]
https://github.com/apache/beam/pull/17228 is merged.

**Comment by youngoli** [comment]
After some offline investigation, we were able to reproduce the error. As for cherry-picking #17228, I'm going forward with rollback because I'm hesitant to delay any further for a cherry-pick (I already should've started the RC yesterday).

**Comment by youngoli** [comment]
Nevermind, I finally understood what people have been trying to explain about #17094 which is that it only reveals a bug that would still be present without it. So rolling back the PR wouldn't fix anything, a cherry-pick is actually necessary.

I'll change this PR to only roll back #17004 and create a new cherry-pick PR.

**Comment by TheNeuralBit** [comment]
@youngoli you said earlier:

> I think the issue with https://github.com/apache/beam/pull/17004 was a false positive (or at least not reproducible)

If it was a false positive do we need to roll it back on the release branch?

**Review by TheNeuralBit — APPROVED** [review]

**Comment by youngoli** [comment]
That was @dpcollins-google btw. But at the time he wasn't able to reproduce it and was saying the error we originally got was the false positive (i.e. an error when there wasn't actually a problem).

But like I said, we investigated it offline (Daniel, Luke, and I) and we were able to replicate it after all. So it does look like a rollback on master may be necessary too.

**Comment by dpcollins-google** [comment]
@TheNeuralBit it was a flaky failure, so I wasn't able to reproduce it but it replicated like 50/100 runs

**Pull request merged**
