### PR TITLE
[BEAM-6349] Revert "Treat VarInt encoding as a Beam primitive encoding in Dataflo…

### PR DESCRIPTION
**Pull request by lgajowy**
…w runner (#7351)"

This reverts commit bac909b8e237ef8a2ab7e17ac986e5cc90143e5b.
We've encountered some blocking issues while developing load tests (both batch and streaming) due to the issues described here: https://issues.apache.org/jira/browse/BEAM-6349. If there's no better solution I suggest reverting the PR.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by CraigChambersG** [comment]
The errors on your load tests show that they're running old code before the PR you're rolling back -- the duplicate binding being reported is no longer being created in code with the PR.  Is there some other part of the set-up for running load tests that has a frozen old jar or something, maybe an old container image, and so mixing old code with new code?

**Comment by lgajowy** [comment]
@CraigChambersG was able to run this on his project so it seems to be a problem with apache-beam-testing project (some old jars? Gradle cache on my machine?) Either way closing.

Thanks @CraigChambersG

**Comment by CraigChambersG** [comment]
I think my PR should probably be reverted, so can you go ahead and reopen this PR, and get it merged?

**Comment by lgajowy** [comment]
@CraigChambersG after some further investigation we understand the issue now and it is not due to your changes. You were right about the old code - I just couldn't find the exact cause until I got help from people working closely with Dataflow. The reason was that you modified both worker code and beam SDK code. Worker code didn't get updated on dataflow when we run the tests without recompiling the worker and using the newest worker version. 

More details here: https://issues.apache.org/jira/browse/BEAM-6349
I also suggested a solution that avoids such problems: https://github.com/apache/beam/pull/7435

Thank you for all your help.

**Pull request closed without merging**
