### PR TITLE
Fixed [Playground] DeployExamples, modified "get difference" step, execution tr…

### PR DESCRIPTION
**Pull request by MakarkinSAkvelon**
The following flow will be applied:
Once a [Playground] merged to master branch, this pipeline will be triggered. It executes both jobs: collect examples and deploy examples. The change between examples is controlled by "get Difference" step: it's compare previous commit with the current one (git diff --name-only ${{ github.event.before }} ${{ github.event.after }}) (assuming that all PRs are squashed to 1 commit on merge to master). Pipeline trigger was also change: Now it will execute once pull request will me merged

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by VladMatyunin** [comment]
There is an assumption: "... all PRs are squashed to 1 commit on merge to master".
I've checked some PRs in the repository, and seems like there are all squashed before merge. Please LMK if you have concerns on that.

**Comment by pabloem** [comment]
lgtm

**Comment by pabloem** [comment]
... wait - we don't always squash commits before merging. Do you htink we could use the branch in the PR and compare against master before the merge?

**Comment by pabloem** [comment]
seems like this may be possible (https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)

**Pull request merged**
