### PR TITLE
[BEAM-1812]  Allow external checkpoint configurations in PipelineOptions

### PR DESCRIPTION
**Pull request by geojins**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Hi @aljoscha , Can you please review.

### CODE REVIEW

**Comment by aljoscha** [comment]
@geojins I'm currently very busy with Flink Forward (http://sf.flink-forward.org) but I'll get back to reviews as soon as I have time again.

Thanks for working on this! 👍

**Comment by geojins** [comment]
Thanks! I will be attending flink-forward. see you!

**Comment by davorbonaci** [comment]
R: @aljoscha

**Comment by geojins** [comment]
@aljoscha, can you please review these changes.

**Comment by aljoscha** [comment]
@geojins Yes, I'm planning to review tomorrow. I'm very sorry for the long delay, my backlog after Flink Forward was quite high.

**Comment by aljoscha** [comment]
@geojins Thanks for implementing this. 👍 

I moved the unit test to the existing `PipelineOptionsTest`, I hope that's alright.

**Comment by geojins** [comment]
Perfect! Thanks @aljoscha

**Pull request closed without merging**
