### PR TITLE
Add equals, hashCode, and structuralValue to Nexmark model objects

### PR DESCRIPTION
**Pull request by kennknowles**
Experiment to see if good equals, hashCode, and structuralValue improves Query10 performance regression.

Unless I am missing something in how I invoke it - no.

@iemejia

### CODE REVIEW

**Comment by iemejia** [comment]
checkstyle not happy so jenkins no happy.

**Comment by kennknowles** [comment]
A lot has happened - rebased to get current Jenkins status.

**Comment by kennknowles** [comment]
@iemejia right now it is my turn to update the code to get the tests passing. There's no hurry. Thanks for leaving a message, though!

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
Looks like it is happy now.

**Pull request merged**
