### PR TITLE
[BEAM-5180] Relax back restriction on parsing file scheme

### PR DESCRIPTION
**Pull request by JozoVilcek**

### CODE REVIEW

**Comment by apilloud** [comment]
From your bug report, it looks like you need `hdfs:/some/path` to work?

**Comment by apilloud** [comment]
FYI @angoenka @jkff

**Comment by angoenka** [comment]
HDFS file names are expected to start with "hdfs://" so I would fix the file name instead of regex.

**Comment by JozoVilcek** [comment]
True, code is using the `hdfs:/some/path` when I enter paths without authority `hdfs:///some/path`. 
I looked around and hadoop filesystem does this. Commented about this here:

https://issues.apache.org/jira/browse/BEAM-2277?focusedCommentId=16587202&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16587202

**Comment by JozoVilcek** [comment]
Actually, after more thoughts, is this a non valid URI or ResourceId `hdfs:/`. Given that authority component is optional, extra `//` can be dropped. `java.net.URI` parse that just fine

**Comment by JozoVilcek** [comment]
I am not sure how failed `GrpcDataServiceTest` relates to this PR

**Comment by angoenka** [comment]
From the java.net.URI docs,

A hierarchical URI is subject to further parsing according to the syntax

`[scheme:][//authority][path][?query][#fragment]`
Which enforces  //

But to support HDFS and unblock our selves we should go with the rollback.

**Comment by apilloud** [comment]
This is effectively a partial rollback of https://github.com/apache/beam/pull/5808
LGTM

**Comment by JozoVilcek** [comment]
@apilloud , yes by personal experience, #5808 is not fun. For me, the most straight forward solution would be not get rid of default `scheme` and never guess. It is not that difficult to always put `schema` to paths even if it is `file`

**Pull request merged**
