### PR TITLE
Add a workaround for BEAM-20873 for optimized list side inputs.

### PR DESCRIPTION
**Pull request by robertwb**
This triggered a case with Dataflow Runner v1 and PTransformOverrides that exposed https://github.com/apache/beam/issues/20873 .

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @abacn

**Comment by Abacn** [comment]
Looks like `cacheCandidatesUpdaterTest (org.apache.beam.runners.spark.CacheTest) failed` in 2 attempts.

**Review by damondouglas — CHANGES_REQUESTED** [review]
@robertwb ~Could you address the spotless check? Thank you for doing this.~ Nevermind. I don't see the spotless warning is gone. I'm examing https://ge.apache.org/s/fwq2iecehys5m/console-log?anchor=8812&page=9 and as Yi pointed out, looks related to the cache. Re-running. After passing, I will LGTM/merge.

**Review by damondouglas — APPROVED** [review]
LGTM. The one [failing test](https://ge.apache.org/s/xmgxzucxdu7u2/console-log/task/:runners:spark:3:test?anchor=5&page=1), `cacheCandidatesUpdaterTest` has nothing to do with this PR.

**Comment by Abacn** [comment]
THe failing test is caused by this PR. After merged java precommit is read on master branch, and the same failure see in other PRs (e.g. #31175: https://github.com/apache/beam/actions/runs/8943529889/job/24568447748?pr=31175)

I checked locally that it fails on latest master

```
cacheCandidatesUpdaterTest
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
```

and passes when reverting this PR

```
$ git checkout HEAD^
$ ./gradlew :runners:spark:3:test --tests org.apache.beam.runners.spark.CacheTest
```

get 

```
Tests Standard error
Test	Duration	Result
cacheCandidatesUpdaterTest	0.333s	passed
shouldCacheTest	1.137s	passed
```

**Comment by robertwb** [comment]
https://github.com/apache/beam/pull/31184

**Pull request merged**
