### PR TITLE
[BEAM-6197] Log time for Dataflow GCS upload of staged files + add a test program

### PR DESCRIPTION
**Pull request by alanmyrvold**
Create a log message for time taken for Dataflow GCS upload of staged files.
Add a standalone test program to test the GCS upload without running a pipeline.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by alanmyrvold** [comment]
Run Spotless PreCommit

**Comment by alanmyrvold** [comment]
@aaltay PTAL?

**Comment by aaltay** [comment]
Run Java PreCommit

**Comment by aaltay** [comment]
@alanmyrvold do you know why tests are failing?

**Comment by alanmyrvold** [comment]
> @alanmyrvold do you know why tests are failing?

Yes. checkstyle was failing due to the format of the class comment. Fixed the comment and re-trying

**Comment by alanmyrvold** [comment]
Run Portable_Python PreCommit

**Comment by alanmyrvold** [comment]
Run Portable_Python PreCommit

**Comment by aaltay** [comment]
Thank you. I can merge it after the last test passes.

**Comment by alanmyrvold** [comment]
Run Portable_Python PreCommit

**Comment by alanmyrvold** [comment]
Run Portable_Python PreCommit

**Comment by alanmyrvold** [comment]
@aaltay The remaining Portable_Python PreCommit test is failing consistently on master, https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/ and tracked by https://issues.apache.org/jira/browse/BEAM-6242

**Comment by alanmyrvold** [comment]
@aaltay Is this ready to merge?

**Pull request merged**
