### PR TITLE
[BEAM-8889] Upgrades gcsio to 2.0.0

### PR DESCRIPTION
**Pull request by veblush**
This is part of [BEAM-8889](https://issues.apache.org/jira/projects/BEAM/issues/BEAM-8889) to get new GCS connector. Since new GCS connector is based on gcsio 2.0.0, beam dependency should be upgraded to catch up the recent changes. Since it doesn't have breaking changes, it doesn't expect to have any code migration related with this.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @chamikaramj`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by suztomo** [comment]
Would you try running this to see if any new linkage error is added or not?
https://gist.github.com/suztomo/ec4834151a81f8e1d26aa0afb278818b

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by veblush** [comment]
> Would you try running this to see if any new linkage error is added or not?
> https://gist.github.com/suztomo/ec4834151a81f8e1d26aa0afb278818b

I ran `./gradlew ... :checkJavaLinkage` manually on both master and this PR and your script on this PR as well. I don't see the difference from both `:checkJavaLinkage` runs but `beam-linkage-check.sh` got an error but about old gcsio 1.9.16 dependency. [result](https://gist.github.com/veblush/5a34c5de8cbe48389520894e25567c08)

**Comment by suztomo** [comment]
That's great finding.

```
UnsolvableVersionConflictException: Could not resolve version conflict among [
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:jar:2.20.0-SNAPSHOT -> com.google.cloud.bigdataoss:gcsio:jar:1.9.16 -> io.grpc:grpc-alts:jar:1.24.2 -> io.grpc:grpc-core:jar:[1.24.2,1.24.2],
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:jar:2.20.0-SNAPSHOT -> com.google.cloud.bigdataoss:gcsio:jar:1.9.16 -> io.grpc:grpc-netty-shaded:jar:1.24.2 -> io.grpc:grpc-core:jar:[1.24.2,1.24.2],
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> com.google.cloud:google-cloud-bigquerystorage:jar:0.120.1-beta -> io.grpc:grpc-core:jar:1.25.0, org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-all:jar:1.25.0 -> io.grpc:grpc-core:jar:[1.25.0,1.25.0],
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-all:jar:1.25.0 -> io.grpc:grpc-okhttp:jar:1.25.0 -> io.grpc:grpc-core:jar:[1.25.0,1.25.0],
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-all:jar:1.25.0 -> io.grpc:grpc-testing:jar:1.25.0 -> io.grpc:grpc-core:jar:[1.25.0,1.25.0], 
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-core:jar:1.25.0, org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-grpclb:jar:1.25.0 -> io.grpc:grpc-core:jar:[1.25.0,1.25.0],
org.apache.beam:beam-runners-google-cloud-dataflow-java:jar:2.20.0-SNAPSHOT -> org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.20.0-SNAPSHOT -> io.grpc:grpc-netty:jar:1.25.0 -> io.grpc:grpc-core:jar:[1.25.0,1.25.0]]
```

Let me try to reproduce that in master.

**Comment by suztomo** [comment]
@veblush For "checkJavaLinkage", did you check artifact beam-sdks-java-extensions-google-cloud-platform-core, which uses gcsio?

```
./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-extensions-google-cloud-platform-core  :checkJavaLinkage
```

I couldn't reproduce UnsolvableVersionConflictException in master 4c92739a. Is your master up-to-date?

**Comment by suztomo** [comment]
Updated beam-linkage-check.sh https://gist.github.com/suztomo/ec4834151a81f8e1d26aa0afb278818b to show commit ID.

**Comment by chamikaramj** [comment]
Can you also run a large scale perf test to make sure that we do not introduce a significant performance regression when reading/writing to GCS with the new library ?

**Comment by veblush** [comment]
@suztomo Since this PR is based on the HEAD of yesterday so it shouldn't be out-dated but I suspect that my local maven repo could be in a bad shape due to my hacky experiments. Therefore I cleaned up the repo, rebased the PR on top of HEAD of today, and ran your latest script again. This is [result](https://gist.github.com/veblush/a9470a977ed8dfa2f3e94f4c9f3957c7) and it said `no difference`.

**Comment by suztomo** [comment]
@veblush Thank you for the result. Unfortunately, it shows incompatibilities among libraries.

- Beam uses Guava 25.1-jre. This version of Guava does not have `Uninterruptibles.sleepUninterruptibly`. This method is used by gcsio:2.0.0.
  https://gist.github.com/veblush/a9470a977ed8dfa2f3e94f4c9f3957c7#file-gistfile1-txt-L62
- gcsio:2.0.0 has dependency on gson-2.2.4. This gson does not have `JsonReader.getPath`.
  https://gist.github.com/veblush/a9470a977ed8dfa2f3e94f4c9f3957c7#file-gistfile1-txt-L83

**Comment by veblush** [comment]
@suztomo Oh I missed the messages in between. For those dependencies, what I need to address that? For the first one, probably using the old function which is available on that version would be feasible. For the last one, it seems a bit strange.

**Comment by suztomo** [comment]
The second one seems wrong. Filed a bug in our tool: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1185 .

**Comment by veblush** [comment]
@suztomo I chatted with @medb, the author of gcsio and he confirmed that gcsio.cooplock & gcsio.testing won't be used by Beam because it's controlled by the option. And then it seems like a false positive. WDTY?

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
Run Java PostCommit

**Comment by amaliujia** [comment]
Seems like commands not working. Let's wait a bit to see if latency is just high.

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by suztomo** [comment]
@veblush What prevents us upgrading Guava? (Last time I checked it was Cassandra.)

**Comment by veblush** [comment]
@suztomo I'm curious about that, too. @chamikaramj might know the answer?

**Comment by suztomo** [comment]
Try upgrading Guava to the version that has the missing methods, then get (potential) errors from tests and from beam-linkage-check.sh

**Comment by veblush** [comment]
@suztomo With the upgrade of `guava` to `28.0-jre`, `beam-linkage-check.sh` shows the following. `28.0-jre` is the oldest one with the new symbol.

```
Linkage Check difference on beam-runners-google-cloud-dataflow-java between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
Lines starting with '<' mean the errors are remedied in the branch (good)
Lines starting with '>' mean the errors are introduced in the branch (bad)
8030a8031,8033
> (gson-2.2.4.jar) com.google.gson.stream.JsonReader's method getPath() is not found;
>   referenced by 1 class file
>     io.grpc.internal.JsonParser (grpc-core-1.25.0.jar)
8043a8047,8051
> gson-2.2.4.jar is at:
>   org.apache.beam:beam-runners-google-cloud-dataflow-java:2.20.0-SNAPSHOT (compile) / org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.20.0-SNAPSHOT (compile) / com.google.cloud.bigdataoss:gcsio:2.0.0 (compile) / com.google.code.gson:gson:2.2.4 (provided)
>   and 1 dependency path.
> grpc-core-1.25.0.jar is at:
>   org.apache.beam:beam-runners-google-cloud-dataflow-java:2.20.0-SNAPSHOT (compile) / org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.20.0-SNAPSHOT (compile) / io.grpc:grpc-core:1.25.0 (compile)
```

**Comment by suztomo** [comment]
Nice. Does the Guava version add new linkage errors for the two artifacts below?
- beam-sdks-java-io-hadoop-format
- beam-sdks-java-io-cassandra

Added beam-sdks-java-io-cassandra to https://gist.github.com/suztomo/ec4834151a81f8e1d26aa0afb278818b

**Comment by chamikaramj** [comment]
cc: @lukecwik

**Comment by veblush** [comment]
@suztomo Other modules don't have differences.

```
Linkage Check difference on beam-sdks-java-core between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
(no difference)


Linkage Check difference on beam-sdks-java-io-google-cloud-platform between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
(no difference)


Linkage Check difference on beam-runners-google-cloud-dataflow-java between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
Lines starting with '<' mean the errors are remedied in the branch (good)
Lines starting with '>' mean the errors are introduced in the branch (bad)
8030a8031,8033
> (gson-2.2.4.jar) com.google.gson.stream.JsonReader's method getPath() is not found;
>   referenced by 1 class file
>     io.grpc.internal.JsonParser (grpc-core-1.25.0.jar)
8043a8047,8051
> gson-2.2.4.jar is at:
>   org.apache.beam:beam-runners-google-cloud-dataflow-java:2.20.0-SNAPSHOT (compile) / org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.20.0-SNAPSHOT (compile) / com.google.cloud.bigdataoss:gcsio:2.0.0 (compile) / com.google.code.gson:gson:2.2.4 (provided)
>   and 1 dependency path.
> grpc-core-1.25.0.jar is at:
>   org.apache.beam:beam-runners-google-cloud-dataflow-java:2.20.0-SNAPSHOT (compile) / org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.20.0-SNAPSHOT (compile) / io.grpc:grpc-core:1.25.0 (compile)


Linkage Check difference on beam-sdks-java-io-hadoop-format between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
(no difference)


Linkage Check difference on beam-sdks-java-io-cassandra between master (1f94c99b) and upgrade-gcsio(a4cd4b4b):
(no difference)
```

**Comment by suztomo** [comment]
@veblush Great. Thank you for checking. Let's see how the post commit checks work after you push the Guava upgrade:

Run Java PostCommit
Run Java HadoopFormatIO Performance Test
Run BigQueryIO Streaming Performance Test Java
Run Dataflow ValidatesRunner
Run Spark ValidatesRunner
Run SQL Postcommit

**Comment by veblush** [comment]
@suztomo I just pushed the commit for guava upgrade.

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
Run Java PostCommit

**Comment by iemejia** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by iemejia** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by iemejia** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by iemejia** [comment]
Run Dataflow ValidatesRunner

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run SQL Postcommit

**Comment by veblush** [comment]
Test failures seemed to be caused by build infra.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by suztomo** [comment]
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: DIGIT
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:431)
```
https://builds.apache.org/job/beam_PreCommit_Java_Phrase/1722/testReport/junit/org.apache.beam.sdk.io.hadoop.format/HadoopFormatIOCassandraTest/classMethod/

**Comment by veblush** [comment]
@suztomo How about splitting this PR into two separate PRs; i) Upgrading gcsio and ii) Upgrading guava? Because I like to have gcsio soon.

**Comment by suztomo** [comment]
(I'm not a committer and cannot approve this PR)
Right. I agree that Guava cannot be upgraded at the moment.

Regarding the risk of [the three classes](https://gist.github.com/veblush/a9470a977ed8dfa2f3e94f4c9f3957c7#file-gistfile1-txt-L62)(`com.google.cloud.hadoop.gcsio.cooplock.CoopLockOperationDao`, `com.google.cloud.hadoop.gcsio.testing.InMemoryObjectEntry`, and `com.google.cloud.hadoop.gcsio.cooplock.CoopLockRecordsDao`) that use the missing methods in Guava 25.

- if the classes are unused in Beam users' environment, it shouldn't be a problem.
- if they are used by Beam users environment (even for other purposes than Beam uses), then it will cause the problem to the users.
  - The package "gcsio.testing" sounds testing. This doesn't seem bother Beam users unless they test their system using the class.
  - "gcsio.cooplock" seems for Cloud Storage Connector for Hadoop's [Cooperative locking](https://cloud.google.com/blog/products/data-analytics/new-release-of-cloud-storage-connector-for-hadoop-improving-performance-throughput-and-more) 
- In future, Beam or Beam's dependency may touch the class.

**Comment by suztomo** [comment]
@veblush I don't approve or disapprove this PR. I don't know how many people use Apache Beam and GCS's Cooperative Locking together.

**Comment by chamikaramj** [comment]
Probably call this out in the dev list ?

**Comment by veblush** [comment]
@suztomo I don't think that cooplock is used by Beam.

**Comment by suztomo** [comment]
@veblush Added diagram to clarify "use Apache Beam and GCS's Cooperative Locking together".

**Comment by iemejia** [comment]
> Would you try running this to see if any new linkage error is added or not?
> https://gist.github.com/suztomo/ec4834151a81f8e1d26aa0afb278818b

@suztomo can you contribute this script maybe into Beam's build-tools directory so we can improve it a bit for further use?

**Comment by suztomo** [comment]
@iemejia I’m happy to do so. Will fix them.

**Comment by iemejia** [comment]
> @iemejia I’m happy to do so. Will fix them.

Extra suggestion @suztomo maybe let's do ARTIFACTS be received via args too.

Sorry @veblush for the extra discussion in your PR I will stop now.

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Did we get a resolution on the conscrypt discussion in BEAM-9288?
Did gcsio mark conscrypt as a provided dependency or shade it itself?

**Comment by veblush** [comment]
@lukecwik This version 2.0 doesn't introduce a new dependency against gRPC. The next version will.

**Comment by lukecwik** [comment]
> @lukecwik This version 2.0 doesn't introduce a new dependency against gRPC. The next version will.

sgtm, will let any committer merge once tests are green

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run CommunityMetrics PreCommit

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run CommunityMetrics PreCommit

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Run Java11 PreCommit

**Comment by chamikaramj** [comment]
Run Java11 PreCommit

**Comment by veblush** [comment]
It seems that `Java11`, `JavaPortabilityApiJava11`, and  `Java_Examples_Dataflow_Java11` are stuck?

**Comment by chamikaramj** [comment]
Yeah, I'll go ahead and merge since the regular pre-commits and the ValidatesRunner test seems to have all passed.

**Pull request merged**
