### PR TITLE
Update dataflow worker container version

### PR DESCRIPTION
**Pull request by boyuanzz**
Update worker container to include latest changes: https://github.com/apache/beam/pull/8217
R: @lukecwik

### CODE REVIEW

**Comment by boyuanzz** [comment]
Run Gradle Publish

**Comment by boyuanzz** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Comment by kennknowles** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by kennknowles** [comment]
Checked on the job and it actually succeeded.

**Pull request merged**
