### PR TITLE
Re-enable GroupIntoBatchesTest.testWithShardedKeyInGlobalWindow

### LINKED ISSUE #25675: [Feature]: Implement and reenable GroupIntoBatchesTest.testWithShardedKeyInGlobalWindow: causes dataflow suite to be permared
### What happened?

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/ is permared. The failing test is `testWithShardedKeyInGlobalWindow`.

I looked at an example job and it isn't even starting up correctly - https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-03-01_02_18_07-687229064971437925;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=apache-beam-testing&pageState=%28%22dfTime%22:%28%22l%22:%22dfJobMaxTime%22%29%29&e=-13802955&jsmode=o&mods=dataflow_dev - in the Dataflow backend I see Job 2023-03-01_02_18_07-687229064971437925 failed to start with status: generic::invalid_argument: Autosharding is not supported with Unified Worker/Runner v2.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by danielarn**
Autosharding support for Java pipelines is now fixed on Dataflow. Un-sickbays GroupIntoBatches tests, fixes #25675.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by danielarn** [comment]
R: @damccorm @kennknowles

**Comment by damccorm** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by damccorm** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by damccorm** [comment]
(trying this again since on the first run we ran into lots of quota issues)

**Review by damccorm — APPROVED** [review]
LGTM, thanks!

**Comment by Abacn** [comment]
This test is still failing after re-enabled: https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/

Are there additional change need to be made? @danielarn

**Comment by Abacn** [comment]
Still permared after test re-enabled: https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/

error message:
```
java.lang.IllegalArgumentException: Runner determined sharding not available in Dataflow for GroupIntoBatches for non-Streaming-Engine jobs. In order to use runner determined sharding, please use --streaming --enable_streaming_engine
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at org.apache.beam.runners.dataflow.DataflowRunner.maybeRecordPCollectionWithAutoSharding(DataflowRunner.java:1644)
	at org.apache.beam.runners.dataflow.GroupIntoBatchesOverride$StreamingGroupIntoBatchesWithShardedKey.expand(GroupIntoBatchesOverride.java:335)
	at org.apache.beam.runners.dataflow.GroupIntoBatchesOverride$StreamingGroupIntoBatchesWithShardedKey.expand(GroupIntoBatchesOverride.java:314)
	at org.apache.beam.sdk.Pipeline.applyReplacement(Pipeline.java:576)
```

shall we lift the check argument at the exception path?

**Comment by damccorm** [comment]
The failures are non-v2, so this seems different...

**Comment by Abacn** [comment]
The change is made for V1 validate runner test task "validatesRunnerStreaming". If it itended to re-enable v2 test then should change here: https://github.com/apache/beam/blob/7a060c5c95f2fbff07bdf455a86705cd6b5e8ee7/runners/google-cloud-dataflow-java/build.gradle#L532

**Comment by damccorm** [comment]
Yep, that's the issue - thanks @Abacn

**Comment by damccorm** [comment]
https://github.com/apache/beam/pull/26415 should fix this

**Comment by damccorm** [comment]
closed in favor of #26416 which Yi put up at the same time

**Pull request merged**
