### PR TITLE
Eliminate google-python-cloud-debugger dependency in base_image_requirements

### LINKED ISSUE #23487: [Task]: Eliminate google-python-cloud-debugger dependency in base_image_requirements
### What needs to happen?

google-python-cloud-debugger has been deprecated and will be shutdown by May 31,2023. https://cloud.google.com/debugger/docs/release-notes

We need to eliminate this dependency in our container image by that time.
The tasks involves the investigation how this dependency works currently (beam does not use it directly) and either remove it or find alternatives.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-harness

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #23487

Per https://cloud.google.com/debugger/docs/release-notes: "Cloud Debugger is deprecated and will be shutdown May 31, 2023."

This dep is also a blocker of building python container on a mac.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @tvalentyn

**Review by tvalentyn — APPROVED** [review]
Thank you.

**Comment by tvalentyn** [comment]
noting that this CL doesn't regenerate the dependencies, but this happens regularly, and done at least before a release.

**Comment by Abacn** [comment]
yeah thanks for reminding.

**Pull request merged**
