### PR TITLE
Fix playground build for Beam 2.55.0 change

### PR DESCRIPTION
**Pull request by Abacn**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Playground PreCommit failed with `Task :playground:backend:runLint FAILED`

```
2024-03-25T18:08:43.0331811Z > Task :playground:backend:installLinter
2024-03-25T18:08:43.0333109Z golangci/golangci-lint info checking GitHub for tag 'v1.51.2'
2024-03-25T18:08:43.0334362Z golangci/golangci-lint info found version: 1.51.2 for v1.51.2/linux/amd64
2024-03-25T18:08:43.0335660Z golangci/golangci-lint info installed /home/runner/go/bin/golangci-lint
2024-03-25T18:08:54.6329834Z 
2024-03-25T18:08:54.6330597Z > Task :playground:backend:runLint
2024-03-25T18:08:54.6331919Z ../../../../../../../opt/hostedtoolcache/go/1.21.8/x64/src/net/http/internal/chunked.go:79:14: undefined: max (typecheck)
2024-03-25T18:08:54.6333164Z 	cr.excess = max(cr.excess, 0)
2024-03-25T18:08:54.6333679Z 	            ^
2024-03-25T18:08:54.6334675Z ../../../../../go/pkg/mod/golang.org/x/net@v0.9.0/http2/server.go:2522:9: trailer declared and not used (typecheck)
2024-03-25T18:08:54.6335854Z 	for _, trailer := range rws.trailers {
2024-03-25T18:08:54.6336423Z 	       ^
2024-03-25T18:08:54.6337457Z ../../../../../go/pkg/mod/cloud.google.com/go/longrunning@v0.4.1/longrunning.go:27:2: "fmt" imported and not used (typecheck)
2024-03-25T18:08:54.6338627Z 	"fmt"
2024-03-25T18:08:54.6338964Z 	^
2024-03-25T18:08:54.6340175Z ../../../../../go/pkg/mod/cloud.google.com/go/longrunning@v0.4.1/longrunning.go:36:2: "google.golang.org/grpc/status" imported and not used (typecheck)
2024-03-25T18:08:54.6341636Z 	"google.golang.org/grpc/status"
2024-03-25T18:08:54.6342149Z 	^
2024-03-25T18:08:54.6343800Z ../../../../../go/pkg/mod/google.golang.org/grpc@v1.56.3/balancer/grpclb/grpclb_remote_balancer.go:306:12: s.Context undefined (type *balanceLoadClientStream has no field or method Context) (typecheck)
2024-03-25T18:08:54.6345860Z 		case <-s.Context().Done():
2024-03-25T18:08:54.6346342Z 		         ^
2024-03-25T18:08:54.6347723Z ../../../../../go/pkg/mod/google.golang.org/grpc@v1.56.3/credentials/oauth/oauth.go:42:19: ts.Token undefined (type TokenSource has no field or method Token) (typecheck)
2024-03-25T18:08:54.6349272Z 	token, err := ts.Token()
```

**Comment by Abacn** [comment]
these go codes were all from depenencies. Should they be excluded from lint ?

**Comment by Abacn** [comment]
PreCommit passed after disable goLint, which confirms the change does not introduce regression to PreCommit Playground, revert the last change and will mark as ready for review

**Comment by Abacn** [comment]
assign set of reviewers

**Comment by Abacn** [comment]
R: @damccorm

**Review by lostluck — APPROVED** [review]
LGTM

**Pull request merged**
