### PR TITLE
Remove coveralls invocations from all Jenkins jobs

### PR DESCRIPTION
**Pull request by kennknowles**
It is flaking, and I don't think it has added such value that we need to put effort into it.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15349/<h2>Build result: FAILURE</span></h2>[...truncated 1.56 MB...]2017-10-26T22:49:24.767 [INFO] Apache Beam :: SDKs :: Java :: Nexmark ............. SUCCESS [05:59 min]2017-10-26T22:49:24.767 [INFO] Apache Beam :: SDKs :: Java :: Harness ............. SUCCESS [01:52 min]2017-10-26T22:49:24.767 [INFO] Apache Beam :: SDKs :: Java :: Java 8 Tests ........ SUCCESS [ 36.438 s]2017-10-26T22:49:24.767 [INFO] Apache Beam :: Runners :: Gearpump ................. SUCCESS [01:18 min]2017-10-26T22:49:24.767 [INFO] Apache Beam :: SDKs :: Java :: Aggregated Javadoc .. SUCCESS [01:47 min]2017-10-26T22:49:24.767 [INFO] ------------------------------------------------------------------------2017-10-26T22:49:24.768 [INFO] BUILD FAILURE2017-10-26T22:49:24.768 [INFO] ------------------------------------------------------------------------2017-10-26T22:49:24.768 [INFO] Total time: 01:49 h2017-10-26T22:49:24.768 [INFO] Finished at: 2017-10-26T22:49:24+00:002017-10-26T22:49:29.001 [INFO] Final Memory: 351M/1951M2017-10-26T22:49:29.001 [INFO] ------------------------------------------------------------------------2017-10-26T22:49:29.104 [ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project beam-parent: I/O operation failed: No source found for org/apache/beam/examples/Snippets.java -> [Help 1]2017-10-26T22:49:29.105 [ERROR] 2017-10-26T22:49:29.105 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.2017-10-26T22:49:29.105 [ERROR] Re-run Maven using the -X switch to enable full debug logging.2017-10-26T22:49:29.106 [ERROR] 2017-10-26T22:49:29.106 [ERROR] For more information about the errors and possible solutions, please read the following articles:2017-10-26T22:49:29.109 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExceptionchannel stoppedAdding one-line test results to commit status...Setting status of 7eb2446fa77e63e9c05d21599452ff7d4ff68105 to FAILURE with url https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15349/ and message: 'FAILURE 5574 tests run, 10 skipped, 0 failed.'Using context: default

**Comment by kennknowles** [comment]
run seed job

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
run seed job

**Pull request merged**
