### PR TITLE
[Python SDK] Re-enable PipelineOptionsTest.test_display_data

### PR DESCRIPTION
**Pull request by BjornPrime**
Addresses #21116 by re-enabling non-flaky test.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Portable_Python PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by TheNeuralBit** [comment]
What testing was done to ensure this is no longer flaky?

**Comment by BjornPrime** [comment]
I ran it locally 1000 times without reproducing the error. Further analysis of the paper trail seems to indicate that the issue was resolved over a year ago but the bug was never closed and the test wasn't re-enabled.

**Comment by TheNeuralBit** [comment]
> I ran it locally 1000 times without reproducing the error. Further analysis of the paper trail seems to indicate that the issue was resolved over a year ago but the bug was never closed and the test wasn't re-enabled.

Ack, thank you!

**Review by TheNeuralBit — APPROVED** [review]

**Pull request merged**
