### PR TITLE
[BEAM-13099] Add build files for vendored Calcite 1.28.0

### PR DESCRIPTION
**Pull request by TheNeuralBit**
The build file is largely the same as for Calcite 1.26.0, there are just a few additional exclusions (see ab2ddaa).

Tested locally with:
```
./gradlew -p vendor/calcite-1_28_0 -PvendoredDependenciesOnly validateVendoring
./gradlew -Ppublishing -PvendoredDependenciesOnly -PjavaLinkageArtifactIds=beam-vendor-calcite-1_28_0:0.1-SNAPSHOT :checkJavaLinkage
./gradlew sdks:java:extensions:sql:test sdks:java:extensions:sql:zetasql:test
```

Note the last test command was run with the changes in https://github.com/apache/beam/pull/15836.

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
Do you diff for the output for checkJavaLinkage from the current version and from the new version?

**Comment by TheNeuralBit** [comment]
> Do you diff for the output for checkJavaLinkage from the current version and from the new version?

Mm all I did was run `checkJavaLinkage`, I'm not sure how to diff the output with the output from the current version (1.26.0).

**Comment by TheNeuralBit** [comment]
If the output is supposed to be logged to stdout/stderr, it seems there is no output for 1.28.0

**Review by lukecwik — CHANGES_REQUESTED** [review]
Can we remove the 1.26 version build rules because the rest of the project relies on the already released artifact?

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
> If the output is supposed to be logged to stdout/stderr, it seems there is no output for 1.28.0

Yes, there should be output like:
```
Exception in thread "main"   referenced by 1 class file
com.google.cloud.tools.opensource.classpath.LinkageCheckResultException: Found 27 linkage errors
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyNpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:76)
  Cause:
    Unknown
Class org.bouncycastle.asn1.x500.X500Name is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.bouncycastle.operator.jcajce.JcaContentSignerBuilder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.bouncycastle.cert.X509v3CertificateBuilder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.bouncycastle.cert.jcajce.JcaX509CertificateConverter is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.bouncycastle.jce.provider.BouncyCastleProvider is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.eclipse.jetty.npn.NextProtoNego$ServerProvider is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyNpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.eclipse.jetty.alpn.ALPN$ServerProvider is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyAlpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.eclipse.jetty.alpn.ALPN is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyAlpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.eclipse.jetty.alpn.ALPN$ClientProvider is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyAlpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.eclipse.jetty.npn.NextProtoNego$ClientProvider is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.ssl.JettyNpnSslEngine (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class com.jcraft.jzlib.JZlib$WrapperType is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibUtil (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class com.jcraft.jzlib.JZlib is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibUtil (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class com.jcraft.jzlib.Inflater is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibUtil (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class com.jcraft.jzlib.Deflater is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibUtil (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.JZlibEncoder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibCodecFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.JZlibDecoder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.handler.codec.compression.ZlibCodecFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.slf4j.LoggerFactory is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Slf4JLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.slf4j.helpers.NOPLoggerFactory is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Slf4JLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.slf4j.spi.LocationAwareLogger is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Slf4JLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.LocationAwareSlf4JLogger is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Slf4JLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Log4J2LoggerFactory is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.InternalLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Log4JLoggerFactory is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.InternalLoggerFactory (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class org.slf4j.Logger is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.logging.Slf4JLogger (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class reactor.blockhound.integration.BlockHoundIntegration is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.Hidden (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Class reactor.blockhound.BlockHound$Builder is not found;
  referenced by 1 class file
    org.apache.beam.vendor.grpc.v1p36p0.io.netty.util.internal.Hidden (org.apache.beam:beam-vendor-grpc-1_36_0:0.2)
  Cause:
    Unknown
Problematic artifacts in the dependency tree:
org.apache.beam:beam-vendor-grpc-1_36_0:0.2 is at:
  org.apache.beam:beam-vendor-grpc-1_36_0:jar:0.2
```

**Comment by TheNeuralBit** [comment]
Hm ok I think there are no linkagge errors then. I see output like that for the artifact id `beam-sdks-java-io-google-cloud-platform`, but for `beam-vendor-calcite-1_28_0:0.1-SNAPSHOT` the output is just:

```
> Task :checkJavaLinkage
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
NOTE: This task published artifacts into your local Maven repository. You may want to remove them manually.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 23s
1163 actionable tasks: 217 executed, 946 up-to-date
```

**Comment by TheNeuralBit** [comment]
> Can we remove the 1.26 version build rules because the rest of the project relies on the already released artifact?

I was advised to leave it in until we've fully migrated off of the 1.26.0 artifacts.

**Comment by lukecwik** [comment]
Great on no linkage errors.

**Review by lukecwik — APPROVED** [review]

**Pull request merged**
