### PR TITLE
Improve performance of BigQueryIO connector when withPropagateSuccessfulStorageApiWrites(true) is used

### PR DESCRIPTION
**Pull request by slilichenko**
Minor updates to the way TableRows are re-constructed from the proto messages used for calls to the Storage Write API. 

Profiling showed over 50% improvement in the CPU utilization in the code branch related to this re-construction.

Additional optimization is possible if the STORAGE_API_AT_LEAST_ONCE method is used. Another PR will be submitted as the follow up to this one.

### CODE REVIEW

**Review by ahmedabu98 — APPROVED** [review]
LGTM

**Comment by slilichenko** [comment]
@ahmedabu98 - I don't have permissions to merge the PR. Could you please, or someone with committer privileges, merge it and mention which release this PR will be available in?

**Comment by ahmedabu98** [comment]
Release 2.58.0 has been cut a while ago. This will make it in for version 2.59.0.

Sorry for not asking earlier, but could you add an entry in CHANGES.md mentioning this improvement?

**Comment by slilichenko** [comment]
@ahmedabu98 - added a line to the 2.59.0 section. When is the SNAPSHOT build going to be available and what's the tentative release date?

**Comment by ahmedabu98** [comment]
We build snapshots on a daily basis, so probably tomorrow. If all goes well, 2.59.0 should be released mid/late September

**Pull request merged**
