### PR TITLE
[BEAM-2281] Improve SQL expression testing so SQL syntax tests suffice; delete extraneous unit tests

### PR DESCRIPTION
**Pull request by kennknowles**
Previously, we had unit tests because we implemented a lot of standard functions from scratch. Now we use Calcite's implementations and we don't need tests for them. We need some smoke tests that we have plumbed things correctly. The SQL syntax tests are more more concise and work well for that (and actually for all purposes).

To make this feasible, the base testing infrastructure needed a tweak to give more informative errors, by having separate asserts for each test case.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by kennknowles** [comment]
run go precommit

**Comment by kennknowles** [comment]
run go precommit

**Comment by kennknowles** [comment]
run go precommit

**Comment by kennknowles** [comment]
R: @apilloud since you said I should be deleting a lot more code...

**Comment by kennknowles** [comment]
run go precommit

**Comment by apilloud** [comment]
Delete all the code! LGTM

**Pull request merged**
