### PR TITLE
[BEAM-1495] Implement Single-Output ParDo as a composite

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This reduces the number of primitive transforms in the Java SDK. There
is no functional change for any pipeline as a result of this change.

### CODE REVIEW

**Comment by tgroh** [comment]
@francesperry @davorbonaci

The meat of this PR is in https://github.com/apache/beam/pull/2145/files#diff-3e1c028dfd4b9b6b3e02849efa893c95R741, which replaces the expansion of `ParDo.Bound` with an application of `ParDo.BoundMulti` rather than a primitive output. The remaining work deletes all special handling performed by runners on the `ParDo.Bound` transform, as it's now merely a convenience for users rather than a primitive transform.

This brings the Java SDK definition of ParDo in line with the runner API definition.

@amitsela @tweise @aljoscha 

It is possible that specialized translations for a `ParDo.Bound` should still exist, and instead be applied to all `ParDos` with a single output, if there is a performance-sensitive choice made between the translation of the two 'types' of ParDo.

@kennknowles

**Comment by jkff** [comment]
Oooooh nice!

**Comment by kennknowles** [comment]
I believe the failure of `TrackStreamingSourcesTest` is just another place you need to switch the `ParDo` class being used.

**Comment by davorbonaci** [comment]
High-level LGTM. Will leave the details to @kennknowles for review.

**Comment by amitsela** [comment]
Can ignore `ResumeFromCheckpointStreamingTest.testWithResume`, see: https://issues.apache.org/jira/browse/BEAM-1582.

**Comment by amitsela** [comment]
@tgroh I think you only changed the streaming translator for Spark. Unfortunately there's also a separate batch translator, and you'd be looking for [this](https://github.com/apache/beam/blob/master/runners/spark/src/main/java/org/apache/beam/runners/spark/translation/TransformTranslator.java#L334).

**Comment by amitsela** [comment]
Run Spark RunnableOnService

**Comment by amitsela** [comment]
I'm assuming the ROS tests for Spark will break because of the missing changes for batch.

**Comment by tgroh** [comment]
Fixed spark batch

**Comment by tgroh** [comment]
Run Spark RunnableOnService

**Comment by kennknowles** [comment]
Run Flink RunnableOnService

**Comment by kennknowles** [comment]
Wrong PR, sorry

**Comment by tgroh** [comment]
Run Dataflow RunnableOnService

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by kennknowles** [comment]
In fact, I think this would break wordcount. But best to be thorough.

**Comment by kennknowles** [comment]
LGTM.

If we want to improve the UI for any runner, they can do their own override. One primitive in the SDK is nice.

**Comment by tgroh** [comment]
Run Dataflow RunnableOnService

**Comment by tgroh** [comment]
Run Dataflow RunnableOnService

**Pull request closed without merging**
