### PR TITLE
[BEAM-1345] Remove FileSystems.setDefaultConfigInWorkers since Dataflow no longer depends on this

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @dhalperi

**Comment by lukecwik** [comment]
Dataflow worker for master still needs to be updated, this is to be held till that occurs

**Comment by dhalperi** [comment]
LGTM, once Dataflow worker for master is updated and examples precommit is green.

**Comment by lukecwik** [comment]
retest this please

**Pull request closed without merging**
