### PR TITLE
[BEAM-1674] Add unicode type to the typeDict attribute in Python SDK

### PR DESCRIPTION
**Pull request by yuya-tajima**
When I executed Biq Query exection on the Google Cloud Dataflow,  the following error occurred.

```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 73-78: ordinal not in range(128)
```

It seems there is a problem when the executed SQL is UTF-8 strings(unicode type).

```python:apache_beam/transforms/display.py
    #TODO: Fix Args: documentation once the Python classes handling has changed
    type_ = cls.typeDict.get(type(value))
    if type_ is None:
      type_ = 'CLASS' if inspect.isclass(value) else None
    if type_ is None and value is None:
      type_ = 'STRING'
    return type_
```
so unicode type is always considered as unexpected type.

the actual error occurrence place is here(if self.type is None).
```python:apache_beam/transforms/display.py
    if self.key is None:
      raise ValueError('Invalid DisplayDataItem. Key must not be None')
    if self.namespace is None:
      raise ValueError('Invalid DisplayDataItem. Namespace must not be None')
    if self.value is None:
      raise ValueError('Invalid DisplayDataItem. Value must not be None')
    if self.type is None:
      raise ValueError(
          'Invalid DisplayDataItem. Value {} is of an unsupported type.'
          .format(self.value)
```
So I fixed the problem the following code.

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @pabloem

**Comment by pabloem** [comment]
The code looks good. Could you add a test case to `display_test.py`?

Something simple like:

    def test_unicode_type_display_data(self):
      class MyDoFn(beam.DoFn):
        def display_data(self):
          return {'unicode_string': unicode('my string')}

    fn = MyDoFn()
    dd = DisplayData.create_from(fn)
    [...] # Match the result

**Comment by yuya-tajima** [comment]
@pabloem 

Thank you for your review.
I will try to add a test case.

**Comment by yuya-tajima** [comment]
@pabloem 

I tried writing new test code and it was passed the test at my local machine.
Would you be able to check it?

https://github.com/apache/beam/pull/2210/commits/7ca8a1519a67072e0bab9060bd57c3deea827d84

**Comment by sb2nov** [comment]
@yuya-tajima if you look at https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/8295/org.apache.beam$beam-sdks-python/consoleFull

Then you will the tests passed but the linter failed as L128 in the test file is longer than 80 characters.

**Comment by yuya-tajima** [comment]
@sb2nov 

Thank you for your advice.
I fixed it.

**Comment by pabloem** [comment]
@yuya-tajima thanks a lot for your contribution! LGTM! : )

**Comment by pabloem** [comment]
@aaltay can you merge please?

**Pull request closed without merging**
