### PR TITLE
[BEAM-6170] Change Nexmark stuckness warnings to not fail pipeline

### PR DESCRIPTION
**Pull request by scwhittle**
The monitoring in the NexmarkLauncher watches the pipeline results and source for events.  If no events are consumed from the source or published to the output for over
STUCK_WARNING_DELAY it prints an warning message:

 "WARNING: streaming query appears to have been stuck for %d min.",

However it also adds this to the errors list, which causes the pipeline to terminate with an exception.  There is a separate STUCK_TERMINATE_DELAY which is used to terminate the pipeline.  It seems inconsistent to cause the pipeline to fail with the warning timeout.  It is also not entirely accurate to say the pipeline is stuck since it may be busy processing stages other than the input or output.

R: @echauchot

### CODE REVIEW

**Comment by echauchot** [comment]
@kennknowles @lgajowy @scwhittle I'm a bit busy on the spark runner. I plan to take a look before the end of the week.

**Comment by echauchot** [comment]
starting the review

**Comment by scwhittle** [comment]
retest this please

**Comment by scwhittle** [comment]
Thanks Etienne and Lukasz, I made that change as you suggested. I also cleaned up some comments and made logging a little more consistent. Let me know what you think

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
Failure is unrelated (beam-sdks-java-io-hadoop-format), merging

**Pull request merged**
