### PR TITLE
Makes gradle findbugs plugin produce an html report rather than xml

### PR DESCRIPTION
**Pull request by jkff**

### CODE REVIEW

**Comment by jkff** [comment]
retest this please

**Comment by lukecwik** [comment]
Rerun Java Gradle PreCommit

**Comment by lukecwik** [comment]
Run Java Gradle PreCommit

**Comment by lukecwik** [comment]
LGTM but waiting for green gradle build.

**Comment by lukecwik** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4295)*

**Comment by lukecwik** [comment]
Run Java Gradle PreCommit

**Pull request merged**
