### PR TITLE
Avoid pr-bot state desync

### PR DESCRIPTION
**Pull request by damccorm**
In https://github.com/apache/beam/pull/17285 the PR bot exhibited 2 pieces of broken behavior:

1) It requested a second review from me after having already requested one from `@riteshghorse`
2) Once I approved, it requested an extra review from me again.

These were caused by 2 underlying issues:
1) Git failed to correctly checkout the pr-bot-state branch causing the first issue. This led the bot to believe nobody had been assigned, and it tried to assign me, but it wasn't able to persist that state back to the state branch (See this [broken run](https://github.com/apache/beam/runs/5852769678?check_suite_focus=true)). To fix this, I added an extra git push step to make sure we're actually able to push to the pr-bot-state branch before we try to do any state manipulation.
2) Because the state got out of sync, the bot didn't realize I had been assigned and thought Ritesh was still assigned. When I approved, it revealed a bug that will cause a new reviewer to get assigned when a non-reviewer approves. To fix this, I added an early return in those cases.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @jrmccluskey

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by damccorm** [comment]
R: @lostluck

**Review by lostluck — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
