### PR TITLE
[BEAM-4592] Make Dataflow understand kind:varint as a well known coder since it already treats beam:coder:varint:v1 as a well known coder kind

### PR DESCRIPTION
**Pull request by lukecwik**
This also fixes the JSON side input representation.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by lukecwik** [comment]
Run Python Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
Run Python Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
Run Java Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
Run Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
Run Python Dataflow ValidatesRunner

**Comment by alanmyrvold** [comment]
https://builds.apache.org/job/beam_PostCommit_Python_Verify/ started failing after this change?

**Pull request merged**
