### PR TITLE
Adds a list of requirements to the expansion request

### PR DESCRIPTION
**Pull request by chamikaramj**
This should be used to interpret the components provided with the request.

For example, this may be used to provide the `StandardRequirements` related to `ParDo`s which otherwise cannot be derived from the components provided.

https://github.com/apache/beam/blob/f3636f32b3f5a97bdd5c8421bf3b1f702ad0980f/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto#L1668

This fixes https://github.com/apache/beam/issues/29354.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by chamikaramj** [comment]
assign set of reviewers

**Review by jrmccluskey — APPROVED** [review]
LGTM

**Comment by chamikaramj** [comment]
Thanks.

I believe Go failures are unrelated: https://github.com/apache/beam/issues/29355

**Comment by robertwb** [comment]
Requirements specify capabilities the runner must understand to execute a pipeline. 

While retuning a set of requirements along with the response make sense (though I don't see that being done or these being incorporated into the final pipeline's requirements, which is a bug we need to fix) I and struggling to understand why one would send a set of "requirements" with a request.

**Pull request merged**
