### PR TITLE
Tests for python gaming examples

### PR DESCRIPTION
**Pull request by davidcavazos**
Hi @aaltay 

Adds unit tests for the examples added on [BEAM-2484]

### CODE REVIEW

**Comment by aaltay** [comment]
LGTM, thank you!

**Comment by aaltay** [comment]
This change is merged, I do not know why PR was not auto-closed.

**Comment by aaltay** [comment]
@davidcavazos could you verify that your change is merged and manually close this PR?

**Comment by davidcavazos** [comment]
Confirmed: it is merged, closing

**Pull request closed without merging**
