### PR TITLE
[BEAM-6245] Add integration test for FlinkTransformOverrides

### PR DESCRIPTION
**Pull request by mxm**
A related follow-up which I noticed while reviewing #4760.

R @dawidwys 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Run Python PreCommit

**Comment by mxm** [comment]
Python tests are flaky due to venv issues. Portable_Python as well until is merged: #7298

**Comment by dawidwys** [comment]
Hi @mxm, generally I think it is a reasonable improvement. One think I don't like is that the `shouldUseTransformOverrides` uses very internal APIs + mocks and in my opinion is fragile for any change. 

How about check if the pipeline has everything replaced correctly? I mean if the overrides were actually applied to the pipeline. But I might be just nitpicking. Other than the test it looks good.

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
@dawidwys I think your point is fair. Mocks tend to be fragile. The idea was to simply check if the overrides are applied at all, we have separate tests for checking what they override and how.

**Comment by dawidwys** [comment]
I see, but then I see very little value of this test. In the end we are not testing if other methods inside of the implementation of `Piepline#translate` are called, right? As I said this test is ok I guess, but with or without the test I would feel equally comfortable in regards to test coverage.

**Comment by mxm** [comment]
This is a safe guard in case during a refactoring we removed the replaceAll method. I think it does provide value as a lightweight integration test. Testing only the transform replacement itself does not guarantee they are applied during translation.

Just to clarify, the test coverage in your PR is excellent. The wording "followup" is a bit misleading. Sorry about that.

**Pull request merged**
