### PR TITLE
Improve autoscaler throughput estimates and account for heartbeats

### PR DESCRIPTION
**Pull request by jackdingilian**
The throughput estimates are improved by storing the estimates per partition (in StreamProgress) rather than per dofn instance. This required some refactoring of ThroughputEstimator/SizeEstimator. It now estimates throughput (per second) of the last ReadChangeStream request and stores it in StreamProgress (current SDF position).

The motivation for changing the measurement is that the DoFn instance level ThroughputEstimator can lead to inaccuracy because partitions move around between DoFn instances constantly. This has caused us to see cases where we estimate a small backlog and prevent scaling down when there is no backlog. 

We account for heartbeats in order to prevent dataflow from scaling down too much when there are little to no mutations, so that it can't hit a point where it can no longer keep up with heartbeats.  

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by jackdingilian** [comment]
R: @pabloem

**Comment by tonytanger** [comment]
addresses: #27183

**Review by pabloem — COMMENTED** [review]
sorry about the delay, and thanks for the detailed comments. They help clarify the reasoning and read through the code. LGTM.

Have you validated this on larger tests?

**Comment by jackdingilian** [comment]
Thanks! Yes, we've thoroughly load tested this with high variation in the load

**Pull request merged**
