### PR TITLE
Remove SnakeYaml dependency

### PR DESCRIPTION
**Pull request by ahmedabu98**
SnakeYaml dependency was introduced in #30808 but it led to conflicts with the existing jackson YAML dependency (see #31405 and [#26743 (comment)](https://github.com/apache/beam/issues/26743#issuecomment-2123695723))

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @chamikaramj 
R: @Abacn 
R: @kennknowles

**Comment by Abacn** [comment]
This is motivated by breaking change of jackson-databind 2.15.x. Can we revert #31473 at the moment also.

**Comment by chamikaramj** [comment]
I don't think we should revert. https://github.com/apache/beam/issues/31405 was already fixed.

**Comment by kennknowles** [comment]
Should this be closed, then? And not blocking 2.57.0?

**Pull request closed without merging**
