### PR TITLE
Made changes to scripts to release multi-arch Beam SDK containers

### PR DESCRIPTION
**Pull request by celeste-zeng**
- Change the default architectures for release containers to be both amd64 and arm64.
- Change all the dockerPush tasks called by the release pushAll task to be docker instead, since multi-arch containers are pushed during build.
- Details see the [Change the release process to release multi-arch Beam SDK containers](https://docs.google.com/document/d/1ikbEJNsFH1D9HqiMqiVyyMlNpDgSqxXK22nUoetzW6I/edit#heading=h.tt3a4uydtlxx) section in the doc.
- Github action test suites that build multi-arch Beam SDK containers: 
1. Python ValidatesContainer Dataflow ARM
2. PostCommit Go Dataflow ARM
3. PostCommit Java Examples Dataflow ARM
Those tests build and push multi-arch Beam SDK containers to `us.gcr.io/apache-beam-testing/github-actions`.
The tests will fail for now since the Dataflow service side change is not yet completed, but by checking the repository we can see the multi-arch containers are tagged and pushed properly.

Test suites that test ARM components of the multi-arch containers:
1. [beam_PostCommit_Go_Dataflow_ARM.yml](https://github.com/apache/beam/blob/master/.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml)
2. [beam_PostCommit_Java_Examples_Dataflow_ARM.yml](https://github.com/apache/beam/blob/master/.github/workflows/beam_PostCommit_Java_Examples_Dataflow_ARM.yml)
3. [beam_Python_ValidatesContainer_Dataflow_ARM.yml](https://github.com/apache/beam/blob/master/.github/workflows/beam_Python_ValidatesContainer_Dataflow_ARM.yml)
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Changes look good to me, cc: @lostluck next release manager. We will need to announce this in CHANGES.md as well.

**Comment by tvalentyn** [comment]
Please document in PR description which test suites exercise the ARM containers so that other folks can see the status of that before mering.

**Comment by celeste-zeng** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by lostluck** [comment]
> Changes look good to me, cc: @lostluck next release manager. We will need to announce this in CHANGES.md as well.

Then be sure to send the PR that updates the CHANGES.md before the cut please.

**Review by lostluck — APPROVED** [review]

**Review by lostluck — APPROVED** [review]
LGTM

**Comment by lostluck** [comment]
Run Go PreCommit

**Comment by celeste-zeng** [comment]
Run Python_Integration PreCommit

**Comment by celeste-zeng** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by lostluck** [comment]
@celeste-zeng What actions remain for this?

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
