### PR TITLE
[BEAM-7606] Fix JDBC time conversion tests

### PR DESCRIPTION
**Pull request by charithe**
This is an attempt to fix the JDBC time conversion tests which seems to depend on the timezone of the user who runs the tests.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by charithe** [comment]
Run Java PreCommit

**Comment by charithe** [comment]
R: @iemejia

**Comment by iemejia** [comment]
Test still fails in my machine:
```
> Task :sdks:java:io:jdbc:test FAILED

expected:<Row:[2019-05-24T00:00:00.000Z, 1970-01-01T17:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]> but was:<Row:[2019-05-24T00:00:00.000Z, 1970-01-01T18:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]>
Expected :Row:[2019-05-24T00:00:00.000Z, 1970-01-01T17:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]
Actual   :Row:[2019-05-24T00:00:00.000Z, 1970-01-01T18:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]
<Click to see difference>

java.lang.AssertionError: expected:<Row:[2019-05-24T00:00:00.000Z, 1970-01-01T17:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]> but was:<Row:[2019-05-24T00:00:00.000Z, 1970-01-01T18:41:50.000Z, 2019-05-24T17:41:50.000Z, 2019-05-24T17:41:50.000Z]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.apache.beam.sdk.io.jdbc.SchemaUtilTest.testBeamRowMapperDateTime(SchemaUtilTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
org.apache.beam.sdk.io.jdbc.SchemaUtilTest > testBeamRowMapperDateTime FAILED
    java.lang.AssertionError at SchemaUtilTest.java:256
1 test completed, 1 failed
FAILURE: Build failed with an exception.
```

**Comment by iemejia** [comment]
More info in my execution environment (I could reproduce this with both debian and ubuntu).
```
$ java -version 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
$ uname -a 
Linux myhost 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
$ env | grep TZ
TZ=Europe/Paris
```

**Comment by charithe** [comment]
Thanks for the information. I think the tests should pass now. I ran the tests in my default timezone as well as `Europe/Paris` and `America/Chicago` (`-Duser.timezone=Europe/Paris`), and they passed in all instances.

**Comment by iemejia** [comment]
Merged now!

**Pull request closed without merging**
