### PR TITLE
cherry pick #24041: fixing BigQuery Query retry vulnerability

### PR DESCRIPTION
**Pull request by ahmedabu98**
CP for #24041

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by ahmedabu98** [comment]
Run Java PreCommit

**Comment by ahmedabu98** [comment]
Run Java PreCommit

**Comment by ahmedabu98** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Failed test is completely unrelated and this already passed at HEAD. So I think we can ignore it.

**Pull request merged**
