### PR TITLE
Sql rebase

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @xumingming

**Comment by xumingming** [comment]
@jbonofre the commits from `DSL_SQL` is also included in this PR? e.g. this one: [[BEAM-301] Initial skeleton for Beam SQL](https://github.com/apache/beam/pull/3311/commits/fba26af58c3e78e2d393c0212df02fab41798356)

**Comment by jbonofre** [comment]
Yes, it should: I started from the `DSL_SQL` branch and rebased from master.

**Comment by jbonofre** [comment]
I confirm: `git log` on the branch shows:

```
commit 7867ce62e43bef7bfd8011c605379df05494dfcf
Author: mingmxu <mingmxu@ebay.com>
Date:   Sun Apr 9 19:49:08 2017 -0700

    [BEAM-301] Initial skeleton for Beam SQL
```

**Comment by xumingming** [comment]
Yeah, make sense, you are right.

**Comment by xumingming** [comment]
LGTM(once the conflict is resolved).

**Comment by XuMingmin** [comment]
A little bit confused here, in the tab __Files Changed__ seems many existing files are shown as _new files_, please correct me if any mis-understanding. 

If this one-step rebase is too complex, can we move back to the two-steps option, and solve this task quickly?

**Comment by davorbonaci** [comment]
Why we cannot simply merge master into this branch? There should be no conflicts of any kind. (Not a rebase, just a merge.)

If we do this, and there was any merge issue, actual work could be permanently lost!

Generally speaking, I think we should be rebasing pull requests -- they represent a little piece of work by the same author -- likelihood of a bad merge is small. For feature branches, however, I think we should just merge, not rebase. If we rebase, sooner or later, somebody will make an error, and we'll lose data with a force push.

**Comment by jbonofre** [comment]
Ok. Let me force push with a merge.

**Comment by jbonofre** [comment]
@XuMingmin I don't see any reason why doing this in two steps. Simply what I did just worked on my branch. Let me just do a merge and update this PR.

**Comment by XuMingmin** [comment]
The two-steps means 1) a direct pull request from master branch to DSL_SQL branch, merge it by ignoring any build errors as nothing in  master relies on SQL, then 2) another PR to upgrade versions, fix any potential error.

The existing PR has too many changes there, 10s of thousands lines, from both master/sql branches, it's hard to do a review.

Mingmin

**Comment by jbonofre** [comment]
Got your point. What do you want me to do then ?

**Comment by jbonofre** [comment]
I would propose to just push the merge on dsl_sql

**Comment by XuMingmin** [comment]
If the 2-step option makes sense, could you help with step 1? I could do the second step after that. IMO this is  more straightforward.

Mingmin

**Comment by XuMingmin** [comment]
I'm working on another option, feel free to close it.

**Pull request closed without merging**
