### PR TITLE
Fix JdbcIOIT, which seems to have never worked

### PR DESCRIPTION
**Pull request by pabloem**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: "addresses #123), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment "fixes #<ISSUE NUMBER>" instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Running with 1000 rows: https://ci-beam.apache.org/job/beam_PerformanceTests_JDBC/6514/

**Comment by pabloem** [comment]
Running with numrows parameter: https://ci-beam.apache.org/job/beam_PerformanceTests_JDBC/6515/

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by Abacn** [comment]
Run Java JdbcIO Performance Test

**Comment by Abacn** [comment]
Got
```
org.apache.beam.sdk.io.jdbc.JdbcIOIT > testWriteWithAutosharding FAILED
    java.lang.OutOfMemoryError: Java heap space
```
and then 
```
org.apache.beam.sdk.io.jdbc.JdbcIOIT > testWriteThenRead FAILED
    java.lang.RuntimeException: Failed to create a workflow job: The size of the serialized JSON representation of the pipeline exceeds the allowable limit. For more information, please see the documentation on job submission:
```

**Comment by johnjcasey** [comment]
@pabloem are you still working on this PR?

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
ok I'll try to drive this PR to be complete

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Passing run: https://ci-beam.apache.org/job/beam_PerformanceTests_JDBC/6978/

Testing once more to check reliability

**Comment by pabloem** [comment]
Run Java JdbcIO Performance Test

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
r: @johnjcasey 
feel free to review or delegate : )

**Comment by johnjcasey** [comment]
run java precommit

**Comment by johnjcasey** [comment]
LGTM

**Pull request merged**
