### PR TITLE
[BEAM-1966] ApexRunner: register standard IOs when deserializing pipeline options

### PR DESCRIPTION
**Pull request by dhalperi**
This needs to be done once per JVM using the Job's pipeline options. The following
is a hack that is tolerant of multiple initialization.

R: @tweise

Is there a better way to execute something like this exactly once?

### CODE REVIEW

**Comment by tweise** [comment]
@dhalperi just a related thought, would it not be better to have serializable PipelineOptions in runners core to cut down on repeated code?

**Comment by dhalperi** [comment]
@tweise -- yes, of course. Then this solution wouldn't even work for Apex tho of course ;)

**Comment by dhalperi** [comment]
(probably in `runners-core-construction` so it's available to runners before pipeline submission.)

**Comment by tweise** [comment]
Yep, that would be great.

Is there better way of doing it? I cannot think of any (other than again relying on static fields). This "hack" is safe since container processes in Apex are not shared between different pipelines. 

LGTM

**Pull request closed without merging**
