### PR TITLE
[BEAM-475] pom.xml: produce aggregate javadoc for the project

### PR DESCRIPTION
**Pull request by dhalperi**
Please do not merge -- still needs some fixes.

### CODE REVIEW

**Comment by dhalperi** [comment]
Hey @jbonofre can you suggest some fixes for this? Current things I'm unhappy with:

* it seems to run before actually compiling the modules -- I think it builds javadoc based on last night's snapshot rather than based on the current code.
* it runs unconditionally rather than behind a profile
* it seems to find a different list of failures than the normal Javadoc build does.

**Comment by jbonofre** [comment]
Let me take a look.

R: @jbonofre

**Comment by jbonofre** [comment]
I think we should change the execution phase. Let me prepare something on that (including profile activation).

**Comment by jbonofre** [comment]
I will provide a link to gist containing some improvements proposal.

**Comment by jbonofre** [comment]
Finally, I will provide a PR on @dhalperi repo.

**Comment by jbonofre** [comment]
By the way, I will check if there's no execution conflict with the javadoc goal performed in the release profile and the default one present in the main `pom.xml`.

**Comment by jbonofre** [comment]
What do you think about this gist: https://gist.github.com/jbonofre/b87f7b8eee03da1b228bc4b1af91fd87 ?

**Comment by jbonofre** [comment]
@dhalperi did you have time to take a look on the gist ? Thanks !

**Comment by jbonofre** [comment]
@dhalperi ping ?

**Comment by jbonofre** [comment]
@dhalperi any update about this ?

**Comment by jbonofre** [comment]
@dhalperi new ping ;)

**Comment by nssalian** [comment]
@dhalperi was going through the open PRs... any update on this one?

**Comment by jbonofre** [comment]
I pinged Dan on some pending requests where I'm waiting for LGTM tag.

**Comment by davorbonaci** [comment]
The underlying issue here is that none of the approaches proposed so far solves the problems @dhalperi enumerated above.

Any solution that solely modifies build plugins in the top-level `pom.xml` will run *before* the actual modules are built and, therefore, is inadequate. The actual solution is something along the lines of a reporting plugin, or some sort of a new module that runs after everything else.

Any specific ideas along those lines?

**Pull request closed without merging**
