### PR TITLE
Documenting AfterProcessingTime delay

### PR DESCRIPTION
**Pull request by pabloem**
r: @charlesccychen

### CODE REVIEW

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by charlesccychen** [comment]
Should this really be milliseconds and not seconds?  (See https://github.com/apache/beam/blob/636732e90e9f9a8743c139067d9e48b2571a1b17/sdks/python/apache_beam/transforms/trigger.py#L300 and https://github.com/apache/beam/blob/636732e90e9f9a8743c139067d9e48b2571a1b17/sdks/python/apache_beam/transforms/trigger.py#L726).

Maybe this is an inconsistency we should fix...

**Comment by pabloem** [comment]
Ah well, the inconsistency arises here: https://github.com/apache/beam/blob/636732e90e9f9a8743c139067d9e48b2571a1b17/sdks/python/apache_beam/transforms/trigger.py#L328

I'm happy to make the correct change. Which is it?

**Pull request closed without merging**
