### PR TITLE
[SQL] Fix PubsubsJsonIT

### PR DESCRIPTION
**Pull request by akedin**
Make schema fields nullable, increase timeout to 5 min

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles @apilloud

**Comment by kennknowles** [comment]
LGTM.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by apilloud** [comment]
Lgtm

**Comment by akedin** [comment]
Failed in postcommit:

- org.apache.beam.examples.subprocess.ExampleEchoPipelineTest.testExampleEchoPipeline
- org.apache.beam.sdk.io.elasticsearch.ElasticsearchIOTest.testWriteWithIdFn

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
Failed in postcommit:

- org.apache.beam.sdk.io.elasticsearch.ElasticsearchIOTest.testWriteWithIdFn

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
green

**Pull request merged**
