### PR TITLE
[BEAM-10835] Improve Github Actions cancelling duplicated runs

### PR DESCRIPTION
**Pull request by TobKed**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace
--- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
Build python source distribution and wheels
Python tests
Java tests

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TobKed** [comment]
@potiuk what do you think about such usage of your `cancel-workflow-runs` action?

**Comment by potiuk** [comment]
I think there is one thing missing in my action - I do not have 'workflow_dispatch' as a cancellable run so it won't cancel duplicated runs of that type. But this should be super-easy to fix (just add it to "CANCELLABLE_RUNS" variable. And I am happy to release a 2.0.1 version :). Would you like to make a PR for that one  ?

**Comment by TobKed** [comment]
Great! I made PR: https://github.com/potiuk/cancel-workflow-runs/pull/3

**Comment by potiuk** [comment]
Actually  - since (I believe)  you want to run it also for fork pull request, you do not need all those. All these cancels should be replaced by one single workflow to cancel them all, triggered by 'workflow_run event'. Otherwise your cancel jobs will have no permission to cancel the duplicates. 

It should follow exactly the example here: 

https://github.com/potiuk/cancel-workflow-runs#cancel-duplicate-runs-for-the-source-workflow

There is enough to have one "workflow_run" triggered by all the different workflows you have. 

You just need something like this as separate "Cancelling" workflow. Then you can remove all other cancels:

```
name: Cancelling
on:
  workflow_run:
    workflows:
      - "Build python source distribution and wheels"
      - "Java Tests"
      - "Python tests"
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - uses: potiuk/cancel-workflow-runs@v2
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: duplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
```

**Comment by potiuk** [comment]
v2.0.1 released - you can start using it

**Comment by potiuk** [comment]
Wait - not yet. I must check something in an hour or so I will fix it

**Comment by potiuk** [comment]
For some reason the  ts-> js pre-ommit did not fail in your PR but it should - can you re-run pre-commit --all-files locally @TobKed

**Comment by potiuk** [comment]
Note that in order to test `workflow_run', you need to push it as "master" in your fork  `git push <fork> improve-gs-jobs-cancellling:master`

This is the only way you can test worklfow_run type of event

**Comment by TobKed** [comment]
@potiuk if you meant PR potiuk/cancel-workflow-runs#3 I just ran `pre-commit --all-files` locally and it fails. Moreover i checked it on master branch and it failed as well.

**Comment by potiuk** [comment]
Yeah. I just wonder why it did not fail in PR :)\

**Comment by potiuk** [comment]
I added the missing generated file, but interestingly enough pre-commit did not fail (I know why - because npm immediately git-add on the newly generated .js file and pre-commit does not fail. I will fix it separately y and I pushed the generated file to your PR.

**Comment by potiuk** [comment]
https://github.com/marketplace/actions/cancel-workflow-runs - v2.0.1 ready :)

**Comment by TobKed** [comment]
Should v2.0.1 contain `workflow_dispatch`?
https://github.com/potiuk/cancel-workflow-runs/blob/v2.0.1/src/main.ts#L6

**Review by potiuk — APPROVED** [review]
LGTM - but test it after pushing to your fork's master.

**Comment by potiuk** [comment]
> Should v2.0.1 not contain `workflow_dispatch`?
> https://github.com/potiuk/cancel-workflow-runs/blob/v2.0.1/src/main.ts#L6

It should :(

**Comment by potiuk** [comment]
It does now @TobKed !

**Comment by TobKed** [comment]
Thank you @potiuk !

**Comment by potiuk** [comment]
And the output log of the action is pretty verbose - it prints the workflow ids it finds (by name), it lists all the runs it finds and tells you exactly why it's cancelling or not given run :). So you should be able to test all cases easily :)

**Comment by TobKed** [comment]
I tested on my local fork and it seems to work as expected. I rebased on the latest master and squashed commits,

**Comment by TobKed** [comment]
R: @kamilwu @tvalentyn @aaltay @brucearctor @robertwb

**Review by potiuk — COMMENTED** [review]
LGTM :)

**Review by mik-laj — APPROVED** [review]

**Review by damgad — APPROVED** [review]

**Comment by kamilwu** [comment]
Tested on my own fork, works as intended. Python tests were cancelled too. Thanks @TobKed, nice improvement!

**Review by kamilwu — APPROVED** [review]

**Comment by potiuk** [comment]
🎉

**Comment by aaltay** [comment]
Sorry I am late. What is the specific improvement? Does this cancel on previous duplicate runs?

**Comment by potiuk** [comment]
@aaltay: It does cancel all previous, duplicate runs - including those from the forks. It works in a robust way and it removes the need of having a regular (every five minutes or so) cron job doing that. 

It was not possible previously to do it differently, because builds from fork did not have (for a good reason) permissions to cancel the jobs from the main repository. It has only be made possible by introducing the new `workflow_run` type of event by Github Actions: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

It works in the way, that every PR runs an accompanying "workflow_run" event that runs with the "write" permission to the "beam" project, and it runs from the "master" of the Beam repo (not the PR). This way you can run a cancel of duplicate runs for a build from fork without running any of the code coming from the fork. 
I've implemented [Cancel Workflow Runs](https://github.com/potiuk/cancel-workflow-runs/) action (based initially on the [cancel-previous-runs by n1hility](https://github.com/n1hility/cancel-previous-runs) that implements all that is need to have it nicely handled and used it in the Apache Airflow project where I am a committer and PMC member. This and general usage of 'workflow_run' helped us in Airflow to speed up our CI builds by ~25%  and make it 10x more reliable).  

In your case it will optimise the use of jobs from GA for runs that are submitted from the same fork/branch in quick succession without having to rely on regular cron jobs run every few minutes. In the future you might also use some of the more complex features of my pluing (fast-fail for non-matrix jobs and killing heavy "workflow_run") - we utilise both in Apache Airflow and you might find it useful at some point in time in Beam.

As I was helping @TobKed and @damgad as "consultant" in the project of improving Beam infrastructure, I also discussed the cancel one and since my action was ready to use, I helped @TobKed to get it configured and used.  I hope you find it useful :)

**Comment by aaltay** [comment]
Thank you for the detailed explanation.

**Pull request merged**
