### PR TITLE
Update postgres Jdbc version to 42.2.2 (Java 8)

### PR DESCRIPTION
**Pull request by iemejia**
We forgot to move to the newer version of the JDBC driver for postgres (used only for the tests. I also updated the version to the latest available.
R: @jbonofre

### CODE REVIEW

**Comment by iemejia** [comment]
CC: @lgajowy (in case this has some side effect in the ITs but hopefully not).

**Comment by iemejia** [comment]
run java precommit

**Comment by lgajowy** [comment]
Run Java JdbcIO Performance Test

**Comment by lgajowy** [comment]
The IOIT succeeded so it seems to work. The previous run failed due to connection problems not related to this PR (this kind of flakiness is currently getting fixed here: https://github.com/apache/beam/pull/5434)

**Pull request merged**
