### PR TITLE
Flink runner: specify CheckpointingMode and CheckpointingTimeout through PipelineOptions.

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @mxm @aljoscha

**Comment by aljoscha** [comment]
@peihe The Flink ValidatesRunner tests are currently failing, I have a fix for that in #3258.

**Comment by peihe** [comment]
retest this please

**Comment by aljoscha** [comment]
@peihe Could you please rebase now that #3258 is in?

**Comment by peihe** [comment]
rebased, PTAL

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
This LGTM once Jenkins is giving the green light! 👍

**Pull request closed without merging**
