### PR TITLE
Gradle Build Optimizations

### PR DESCRIPTION
**Pull request by clayburn**
This change includes a few Gradle Build optimizations, including:

- Updating to Gradle 7.6.1
- Improving caching of the Checkstyle tasks

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
Looks like a lot of tests are red. I didn't look into why, but it seems likely to do with this change?

**Comment by clayburn** [comment]
@kennknowles I rebased the changes on master. Observing the re-ran builds, it seems the failures may be CI infrastructure related:

**Comment by kennknowles** [comment]
Some of the failures appear to be new intra-project dependency issues discovered by the upgrade to that analysis plugin. I suggest separating that upgrade from the gradle upgrade, if possible.

**Comment by clayburn** [comment]
@kennknowles Thanks for the feedback. I rebased yesterday but didn't get a chance to analyze the results. I've removed the analysis plugin update from this PR.

**Comment by kennknowles** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by kennknowles** [comment]
Seeing enough green that I am optimistic. Kicking the test that had an NPE.

**Comment by damccorm** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
What are next steps on this PR?

**Comment by tvalentyn** [comment]
.waiting on author

**Comment by tvalentyn** [comment]
waiting on author

**Comment by damccorm** [comment]
As best I can tell, this still requires author attention. If that's not right, please let us know @clayburn

**Comment by clayburn** [comment]
@damccorm apologies, I missed that this was merge conflicted. I've rebased the PR.

**Comment by kennknowles** [comment]
Run Java_Spark3_Versions PreCommit

**Comment by kennknowles** [comment]
Run Java_Spark3_Versions PreCommit

**Comment by kennknowles** [comment]
run java precommit

**Comment by damccorm** [comment]
R: @kennknowles

**Comment by damccorm** [comment]
(could you take this one to completion since you've started reviewing?)

**Comment by kennknowles** [comment]
Ha! If by "started review" you mean "kicked the tests" :-p

**Comment by kennknowles** [comment]
Everything is green now but we have to resolve the conflicts.

**Comment by clayburn** [comment]
@kennknowles, the conflicts should now be resolved ✅

**Comment by kennknowles** [comment]
Filed https://github.com/apache/beam/issues/27666 for the Kinesis failure.

Filed https://github.com/apache/beam/issues/27667 for the Python coverage failure.

**Comment by kennknowles** [comment]
Run Python_Coverage PreCommit

**Comment by kennknowles** [comment]
Run Java_Amazon-Web-Services2_IO_Direct Precommit

**Comment by Abacn** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by kennknowles** [comment]
Green. Hooray!

**Pull request merged**
