### PR TITLE
Fix Java 11 Example PreCommit GItHub Action

### PR DESCRIPTION
**Pull request by Abacn**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by damccorm** [comment]
@celeste-zeng could you please take a look?

**Comment by celeste-zeng** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Review by celeste-zeng — APPROVED** [review]

**Comment by celeste-zeng** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Review by celeste-zeng — COMMENTED** [review]
Actually, this will cause PostCommit Java11 Dataflow ARM to fail because `error: option -source cannot be used together with --release` and `error: option -target cannot be used together with --release`.

**Comment by Abacn** [comment]
I see, https://github.com/apache/beam/actions/runs/6081096373/job/16496105989 it appears at some place both `--release` and `-source -target` are set

**Comment by celeste-zeng** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by celeste-zeng** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by celeste-zeng** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Comment by Abacn** [comment]
Run SQL_Java17 PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 8

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by Abacn** [comment]
looks like github comment event will kill ongoing phrase jobs. In addition, if the job hasn't been triggered by commit, the job status is not updated to the PR page.

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 17

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 11

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by Abacn** [comment]
Issues revealed in detail

1. duplicate compiler flags have always been added to TestCompileJava under Java11/17, however, because the latter option will overwrite the previous one, it did not show error.

2. #28291 changed all occurrance of `--release` to `-source X -target X`. They are not equivalent, actually: ((ref)[https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler]). In particular, here it has to be `--release`:

https://github.com/apache/beam/blob/e28e95811081fd0f73304b70ebfeedcc6cfb0514/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L1095

Otherwise, using Java9+ compile beam main code then run on Dataflow runner will see the error in https://github.com/apache/beam/pull/28291#issuecomment-1707479834 (current master java11 example precommit error)

**Pull request merged**
