### PR TITLE
[BEAM-7209][BEAM-9351][BEAM-9428] Upgrade Hive to version 3.1.3

### PR DESCRIPTION
**Pull request by Abacn**
* This eliminated the pentaho dependency

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Finally able to make the integration test run:

image

The current integration test is written in a way that needs both metastore and hiveserver2 services running and essentially operating the same database. Did not find a way to make both services run locally (in local embedded mode, metastore or hiveserver2 will occupy the same Derby database and cannot be setup at the same time.) The test is conducted by manually doing setup of HCataogIOIT (thus commenting out these parts in HCataogIOIT.java), running a metastore service and then run the integration test.

**Comment by Abacn** [comment]
retest this please

**Comment by Abacn** [comment]
R: @TheNeuralBit
R: @chamikaramj 
R: @timrobertson100

**Comment by Abacn** [comment]
Known build flake "warning: Memory constraints are impeding performance; please increase max heap size." unrelated to this change.

**Comment by TheNeuralBit** [comment]
Do we expose hive in any of our public APIs? I was under the impression that we do, so we can't just bump a major version without risking breaking users.

**Comment by Abacn** [comment]
> Do we expose hive in any of our public APIs? I was under the impression that we do, so we can't just bump a major version without risking breaking users.

Yes we do. The HCatalog read and write transforms is in the type of `org.apache.hive.hcatalog.data.HCatRecord`. However the user are allowed to provide their own version of Hive as part of Beam (hive dependencies are configured as "provided" in gradle build), and the source code of HCatalogIO (other than test and test helper codes) are unchanged.

One of the motivation of this change is the old pentaho dependencies that hive 2.x depended on has been removed from repos gradually and generated build issues to the Beam several times ([BEAM-6811]; #17734 (BEAM-14298)) and this upgrade may be considered to increase its priority.

**Comment by TheNeuralBit** [comment]
> > Do we expose hive in any of our public APIs? I was under the impression that we do, so we can't just bump a major version without risking breaking users.
> 
> Yes we do. The HCatalog read and write transforms is in the type of `org.apache.hive.hcatalog.data.HCatRecord`. However the user are allowed to provide their own version of Hive as part of Beam (hive dependencies are configured as "provided" in gradle build), and the source code of HCatalogIO (other than test and test helper codes) are unchanged.

I see, please also update CHANGES.md to note this as a breaking change and recommend users override the Hive version if they need to. 

A couple more questions:
- I see some code changes, will that code still work with Hive 2.x?
- Do we need to release another vendored Calcite? Note that release process is separate from the rest of Beam (https://s.apache.org/beam-release-vendored-artifacts)

**Comment by Abacn** [comment]
> * I see some code changes, will that code still work with Hive 2.x?

The changes are only involved in unit tests. Unit tests needs to run with Hive 3.x. The artifact built should not be affected.

`EmbeddedMetastoreService.java`: this file is only used in unit test. The file itself is a trimmed-down version of a test in Hive source, as recorded in its comment. The change updated the file content to that in Hive 3.1.3 release.

`resources/hive-site.xml`: hive config file used for EmbeddedMetastoreService which is only used in unit test. Also updated the file content to that in Hive 3.1.3 release.

`HCatalogIOTest.java` and `BeamSqlHiveSchemaTest.java` are unit tests. The change reflects a breaking change of Hive 3 which removed CommandNeedRetryException and thus removed from EmbeddedMetastoreService.executeQuery's signature.

> * Do we need to release another vendored Calcite? Note that release process is separate from the rest of Beam

Probably not. Hive 2.1.0 used Calcite 1.6.0 and now Hive 3.1.3 uses Calcite 1.16.0 as dependencies. Looked at Beam release history vendored Calcite started on v1.20.0 since the release of Beam 2.16.0 and the reason of vendoring were not related to Hive. Will confirm with others.

**Comment by Abacn** [comment]
retest this please

**Comment by Abacn** [comment]
commenting `retest this please` not triggering retest, trying do a push

**Comment by johnjcasey** [comment]
is it possible to move hive-site.xml to the test resources folder to make sure all hive dependencies are in the test side of the world?

**Comment by Abacn** [comment]
> is it possible to move hive-site.xml to the test resources folder to make sure all hive dependencies are in the test side of the world?

Agree. Those files were marked as `@Internal` and should not be used outside. It was in main module because `:sdks:java:extensions:sql:hcatalog` project unit tests also used it. However this can be avoided by claiming test deps in the latter.

**Comment by Abacn** [comment]
retest this please

**Comment by Abacn** [comment]
R: @johnjcasey

**Comment by johnjcasey** [comment]
LGTM

**Comment by TheNeuralBit** [comment]
Run PythonLint PreCommit

**Pull request merged**
