### PR TITLE
Flink runner: support MapState in FlinkStateInternals.

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @aljoscha

**Comment by aljoscha** [comment]
The changes look good! Have you tried removing the exclusion of `UsesMapState` tests for the `ValidatesRunner` tests in the Flink Runner pom?

**Comment by peihe** [comment]
Run Flink ValidatesRunner

**Comment by peihe** [comment]
retest this please

**Comment by peihe** [comment]
PTAL
Turned on UsesMapState tests, and ValidatesRunner passed.

**Comment by aljoscha** [comment]
LGTM! 👍 

While on this, we can probably also easily add support for `SetState`.

**Pull request closed without merging**
