### PR TITLE
[BEAM-7093] Support Spark 3 in Spark runner

### PR DESCRIPTION
**Pull request by iemejia**
I am reopening this one because I was not able to trigger any 'hand made' invocated test in the other one, so trying again.

R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Review by ibzib — APPROVED** [review]
LGTM!

Should we announce this in CHANGES.md and the Spark runner page? or should we wait to do that in a separate PR

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark ValidatesRunner Java 11

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark ValidatesRunner Java 11

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run GoPortable PreCommit

**Comment by iemejia** [comment]
Run Seed Job

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Comment by iemejia** [comment]
Failing tests on Spakr Strucutred Streaming VR Tests are expected and already tracked by BEAM-11023

**Comment by iemejia** [comment]
> LGTM!
> 
> Should we announce this in CHANGES.md and the Spark runner page? or should we wait to do that in a separate PR

Yes, I will take care of that as part of BEAM-11655 Thanks @ibzib for the review

**Pull request merged**
