### PR TITLE
Get rid of Apache Commons dependency

### PR DESCRIPTION
**Pull request by mairbek**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by mairbek** [comment]
R: @kennknowles

**Comment by jbonofre** [comment]
CC: @jbonofre

**Comment by kennknowles** [comment]
Since it is already prefixed with `beam-test-db` you could really just generate a random number and append it. That would remove all the utility code as well as the dependency.

**Comment by jbonofre** [comment]
It sounds reasonable to me.

**Comment by mairbek** [comment]
I'm also using it to generate a random value.

**Comment by kennknowles** [comment]
But really Apache Commons has the same status as Guava as "the standard library that you are going to reimplement anyhow" so unless we can replace it with ~zero lines of utility code I'm not so sure about ditching it. Another example is https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/StringUtils.java#L37

But we can fix the build and revisit later, so I'm going to merge if postcommit is g2g.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by kennknowles** [comment]
CC @jbonofre the `pom.xml` at HEAD has `commons-lang3` as a `provided` dependency. So that is overriding the straightforward main dependency from `commons-text` to `commons-lang3` I think. I cannot recall why changing that from `provided` to `test` did not work, or whether there were other problems going on.

**Comment by mairbek** [comment]
Huh, I wish there was something like this in Guava https://github.com/google/guava/issues/2113

**Comment by kennknowles** [comment]
Well, on the other hand Commons is a more stable library so we could use it without shading.

**Pull request merged**
