### PR TITLE
[BEAM-4824] Batch BigQueryIO returns job results

### PR DESCRIPTION
**Pull request by calonso**
Adds the batch load results to the `WriteResults` returned by BigQueryIO.write

This PR is still WIP, but I wanted to open it ASAP to get feedback. Meanwhile:
* Unify the returned results, so that if a load required many jobs. Only one element is returned on the PCollection, making that "split into many jobs" transparent to the user
* Add the job's error information to the `BigQueryWriteResult` class so that it is also returned and can be actionable.

@reuvenlax @jkff 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by reuvenlax** [comment]
Thanks! Sorry for the delay, I didn't see this review earlier.

Some initial thoughts:

  1. Changing internal types of PCollections (e.g. PCollection<String> -> PCollection<BigQueryWriteResult>)  in common transforms is something we try to avoid doing, as many users rely on being able to in-place updates of their pipelines which is impossible when types change. Not a blocker, we just might need to make the new behavior opt-in instead of the default.

 2. The set of load jobs generated is kind of an internal detail in BigQueryIO. It might split an insert into multiple load jobs (and then run a copy job to merge them), or in the case of streaming it might keep generating load jobs. In addition some of these load jobs might simply be retry jobs for previously-failed load jobs. I'm not sure that outputting per load-job information is going to give us what we want, when the logical model is per record.

**Comment by calonso** [comment]
Sorry for the delay, been on holidays.

I think I can make the new behaviour opt-in by adding a new method to the builder, similar to what I did in #5341.

I'm not sure though on what to do about your second comment. Maybe just limiting to batch jobs? (using `expandUntriggered`?) although I think having the job result information is really valuable in all cases, even if it changes the record granularity.

**Comment by calonso** [comment]
Hi @reuvenlax, any idea about this? I'd like your input before proceeding.

**Comment by calonso** [comment]
Hi @reuvenlax Just a friendly reminder about this outstanding WIP... Could you please give us a hand?

**Comment by reuvenlax** [comment]
Sorry for the long delay! Looking again

**Comment by reuvenlax** [comment]
BTW my second comment still stands I think. BigQueryIO currently uses load jobs as an implementation detail. It might end up creating one load job per table, or it might end up creating multiple load jobs per table (if the table is very large). Collapsing the multiple jobs together might be very confusing. I think making information about these jobs part of the public API is very confusing, when the actual logical model is per record.

Another thing: there will be upcoming changes to the BigQuery API, and we plan on getting rid of load jobs entirely from BigQueryIO. If we make information about load jobs part of the public API, it might be problematic when we remove the load jobs.

Is this something that could be accomplished with better logging, or are there concrete use cases for wanting the output in a PCollection?

**Comment by reuvenlax** [comment]
Oh, @calonso this was intended to make Wait.on work, right? Let me see if I can think of something.

**Comment by calonso** [comment]
Hi @reuvenlax. Many thanks for your comments. Yes, the idea behind this PR is to make Wait.on work with it, but I'd ideally like to have some information on the insert operation result, so that pipelines know the result of the insertion and can make decisions based on it.

Looking forward to your suggestions....

Thanks again!

**Comment by aaltay** [comment]
@reuvenlax any updates on this one?

**Comment by reuvenlax** [comment]
@calonso sorry I've been traveling internationally a lot recently (on vacation now) and haven't stayed on top of this.

I have some concerns about adding this capability given that there will be a new BigQuery connector that doesn't use these inserts at all, and code that relies on this functionality simply will not function with the new connector. However as long as the capability is guarded behind Experimental (meaning that the functionality will change, and no compatibility guarantees are made), I think it's ok to add this.

My biggest concern with the current PR is changing the types of PCollections (e.g. from String -> BigQueryWriteResult). Several runners (Dataflow, Flink) support updating streaming pipelines. However if one of these PCollections has changed types, the update must fail. Is there any way to structure this without changing intermediate types?

**Comment by calonso** [comment]
Hi @reuvenlax , thanks for your comments.

I think I've got an idea on how to approach this. Let me know what do you think:
1. Return the job result information as a side output from the `WriteTables` transform
1. Only make it available downstream if the user requests so by adding a new `withLoadJobsStatus` method to the builder

I'll write an end to end solution but only covering the untriggered single partition codepath to get your input on it before investing more time, does it make sense?

Another question, just out of curiosity, how will the next BQ connector work with inserts?

**Comment by giogit** [comment]
This pull request is very important, in my opinion.
With other connectors, like JdbcIO or TextIO, it is possible to use Wait.on correctly and I think this is a useful feature for batch pipelines.
At the moment, using BigQueryIO, the Wait.on works correctly only with streaming inserts.
I use Wait.on to send PubSub messages at the end of my batch pipelines with JdbcIO and I'd like to do the same also with BigQueryIO
Thank you

**Comment by djaneluz** [comment]
@calonso Thank you for your work with this important feature, any updates on this matter?

**Pull request closed without merging**
