### PR TITLE
[BEAM-9272] Remove obsolete SDF URNs

### PR DESCRIPTION
**Pull request by epicfaace**
Remove obsolete SDF URNs.

I just updated the protos, but did notice that the URNs for PROCESS_ELEMENTS and PROCESS_KEYED_ELEMENTS and SPLIT_RESTRICTION are still used elsewhere in the code -- would it be fine to just delete them, @robertwb ?

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by robertwb** [comment]
`PROCESS_KEYED_ELEMENTS` can definitely go. I think we're at the point that I'd feel good about removing the others as well. Do you have any thoughts, @lukecwik ?

**Comment by lukecwik** [comment]
> `PROCESS_KEYED_ELEMENTS` can definitely go. I think we're at the point that I'd feel good about removing the others as well. Do you have any thoughts, @lukecwik ?

I think getting rid `PROCESS_KEYED_ELEMENTS` should definitely go. Some runner might want/care about having the non sized versions of **process elements** and **split restriction**.

Note that the `PROCESS_KEYED_ELEMENTS` are still used in Java but not used in portable pipeline execution so this PR would need to address that. If we can't do a full clean-up, an interim solution would be to hardcode the few references to that constant.

**Comment by robertwb** [comment]
On Tue, May 12, 2020 at 7:43 PM Lukasz Cwik <notifications@github.com>
wrote:

> PROCESS_KEYED_ELEMENTS can definitely go. I think we're at the point that
> I'd feel good about removing the others as well. Do you have any thoughts,
> @lukecwik <https://github.com/lukecwik> ?
>
> I think getting rid PROCESS_KEYED_ELEMENTS should definitely go. Some
> runner might want/care about having the non sized versions of *process
> elements* and *split restriction*.
>
The burden here is would we want all SDKs to have to provide support for
these URNs. I would lean towards having one way to do things and runners
that don't care about sizes could just ignore them.

> Note that the PROCESS_KEYED_ELEMENTS are still used in Java but not used
> in portable pipeline execution so this PR would need to address that. If we
> can't do a full clean-up, an interim solution would be to hardcode the few
> references to that constant.
>

+1

**Comment by lukecwik** [comment]
> On Tue, May 12, 2020 at 7:43 PM Lukasz Cwik ***@***.***> wrote: PROCESS_KEYED_ELEMENTS can definitely go. I think we're at the point that I'd feel good about removing the others as well. Do you have any thoughts, @lukecwik <https://github.com/lukecwik> ? I think getting rid PROCESS_KEYED_ELEMENTS should definitely go. Some runner might want/care about having the non sized versions of *process elements* and *split restriction*.
> The burden here is would we want all SDKs to have to provide support for these URNs. I would lean towards having one way to do things and runners that don't care about sizes could just ignore them.

That sounds good to me as it will reduce the amount of complexity for something that is effectively unused. The Java SDK harness does implement those URNs and would need to be cleaned up, others may need it as well.

> Note that the PROCESS_KEYED_ELEMENTS are still used in Java but not used in portable pipeline execution so this PR would need to address that. If we can't do a full clean-up, an interim solution would be to hardcode the few references to that constant.
> +1

**Comment by robertwb** [comment]
OK, so let's completely remove `PROCESS_ELEMENTS` and `SPLIT_RESTRICTION` in the code and protos, and make `PROCESS_KEYED_ELEMENTS` a constant in Java (removing it from the proto). This'll be a nice cleanup. Could you update your PR, @epicfaace?

**Comment by lukecwik** [comment]
Feel free to break up your PR into two if you wish since removing `PROCESS_KEYED_ELEMENTS` won't really overlap with removing `PROCESS_ELEMENTS` and `SPLIT_RESTRICTION`

**Comment by epicfaace** [comment]
Working on this

**Comment by lukecwik** [comment]
> Working on this

I had done some clean-up in this space and updated BEAM-9272. The remaining work after #12055 is to clean-up the usage of PROCESS_ELEMENTS and PROCESS_KEYED_ELEMENTS from Beam Java by making them internal to the runners that require them and nowhere else and not in PTransformTranslation.java

**Pull request closed without merging**
