### PR TITLE
[BEAM-1352] Remove dataflow-runner dependency from io/gcp.

### PR DESCRIPTION
**Pull request by peihe**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by dhalperi** [comment]
What JIRA is this under? What's the rationale for this change?

I kicked off the Dataflow runner postcommit: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Dataflow/2127/

Can you confirm that the same integration tests still run? Specifically, BigtableIO is running?

**Comment by peihe** [comment]
PTAL

filed jira BEAM-1352

And, RunnableOnService tests are all ignored in BigQueryIOTest.

**Comment by dhalperi** [comment]
Can you confirm that Bigtable integration tests (not RunnableOnService tests) are still executed with this change?

**Comment by peihe** [comment]
@dhalperi 
BigtableReadIT and BigtableWriteIT are in beam_PostCommit_Java_MavenInstall

Could you help me to kick it off?
I don't have Jenkins access.

**Comment by dhalperi** [comment]
Will be number 1126 here: https://builds.apache.org/view/Beam/job/beam_PostCommit_Python_Verify/

**Comment by dhalperi** [comment]
Postcommit failed: https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/2487/

**Comment by dhalperi** [comment]
You can also run this locally by running integration tests (get command line from the console output) on your own project, so should not need me to run for you.

**Pull request closed without merging**
