### PR TITLE
[BEAM-2981] Update Dataflow worker version to attain ProtoCoder serialVersionUID fix

### PR DESCRIPTION
**Pull request by kennknowles**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @jkff

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Comment by jkff** [comment]
Please also confirm that you were able to manually run one of the failing tests https://builds.apache.org/job/beam_Release_NightlySnapshot/540/org.apache.beam$beam-runners-google-cloud-dataflow-java/#showFailuresLink with this change and it succeeded.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by kennknowles** [comment]
All the ITs are included in the Java SDK Post Commit Tests and have passed.

 - BigTable: https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/4858/org.apache.beam$beam-runners-google-cloud-dataflow-java/testReport/org.apache.beam.sdk.io.gcp.bigtable/
 - Datastore: https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/4858/org.apache.beam$beam-runners-google-cloud-dataflow-java/testReport/org.apache.beam.sdk.io.gcp.datastore/

Example drilling all the way in to a test case: https://builds.apache.org/job/beam_PostCommit_Java_MavenInstall/4858/org.apache.beam$beam-runners-google-cloud-dataflow-java/testReport/org.apache.beam.sdk.io.gcp.bigtable/BigtableReadIT/testE2EBigtableRead/

**Comment by jkff** [comment]
LGTM modulo passing of ValidatesRunner tests.

**Pull request merged**
