### PR TITLE
Update google-cloud-bigquery-storage to require 2.11.0 or later

### PR DESCRIPTION
**Pull request by kmjung**
This change updates the dependency requirements for the google-cloud-bigquery-storage library to require version 2.11 or later in order to pick up https://github.com/googleapis/python-bigquery-storage/pull/366.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by chamikaramj — APPROVED** [review]
Thanks. LGTM.

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
Ah, actually you also need to run following.
./gradlew :sdks:python:container:generatePythonRequirementsAll

See: https://github.com/apache/beam/blob/master/sdks/python/container/py38/base_image_requirements.txt#L17

**Comment by aaltay** [comment]
What is the next step on this PR?

**Comment by aaltay** [comment]
Could this be merged?

**Comment by aaltay** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
It seems like tests are failing. I can trigger once again.

**Pull request closed without merging**
