### PR TITLE
Kafka adaptive timeout implementation to handle empty topic cases

### PR DESCRIPTION
**Pull request by talatuyarer**
We noticed a consistent increase in Kafka consumer lag, especially with topics that had higher message traffic when we use Flink Runner. Our investigation revealed that the lag was related to how Apache Beam's **UnboundedSourceWrapper** and **KafkaUnboundedReader** were handling Kafka partitions. We found that for topics with lower traffic, the processing thread would wait unnecessarily, causing a lag in processing higher traffic topics. To address this We created adaptive timeout on KafkaUnboundReader. 

More detailed explanation done by Intuit team also too. Blog post is old but it is even applicable current master 

https://antonio-si.medium.com/how-intuit-debug-consumer-lags-in-apache-beam-22ca3b39602e

Please help me to merge this change. We used this solution on production. We dont observe any issue so far. 

Thanks

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by talatuyarer** [comment]
@johnjcasey Could you review this ?

Thanks

**Comment by johnjcasey** [comment]
Reading through this, the logic is that whenever we get no records, we lower the the timeout by 1 ms, to a minimum of 1, and when we get records, we raise it, to a maximum of 20?

This makes a lot of sense to me. Is there a way we can add a test case for this?

**Comment by talatuyarer** [comment]
Thank you @johnjcasey for review. We figured out the issue when we have two topic (idle and heavy log rate) together in one KafkaIO. DO you have any suggestion to reuse or influence for test ?

**Comment by talatuyarer** [comment]
@johnjcasey I believe this very simole change. If you are ok without testing. I would like to merge this as is. At least in the company we implement without testing as you mentioned it is very flaky.

**Comment by johnjcasey** [comment]
Reasonable. I'm ok with this as is then.

**Comment by talatuyarer** [comment]
Thank you @johnjcasey

**Pull request merged**
