### PR TITLE
Beam pre commit java examples dataflow

### PR DESCRIPTION
**Pull request by andreydevyatkin**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by andreydevyatkin** [comment]
Run Java_Examples_Dataflow PreCommit

**Review by Abacn — APPROVED** [review]
This reverts #27420

Fine to make it enabled if its convenient to investigate the issue

**Comment by Abacn** [comment]
> Run Java_Examples_Dataflow PreCommit

This won't be effective as it runs the github action yml script on master

**Comment by Abacn** [comment]
So let's get this in first then one can use dumb pull request to trigger the test and investigate the issue

**Comment by andreydevyatkin** [comment]
> > Run Java_Examples_Dataflow PreCommit
> 
> This won't be effective as it runs the github action yml script on master

The root cause of this issue is the lack of roles for the service account. Since we already have `beam_PreCommit_Java_Examples_Dataflow` merged into master, this helps determine which gradle tasks keep failing after changing the permissions for the service account.

**Comment by andreydevyatkin** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by andreydevyatkin** [comment]
Run Java_Examples_Dataflow PreCommit

**Pull request merged**
