### PR TITLE
[BEAM-1663] Use stable naming strategy for ByteBuddy invokers

### PR DESCRIPTION
**Pull request by kennknowles**
This helps to coalesce related failures across multiple
JVM instances, over time, across machines, etc.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
CC: @ajamato 

To lighten the Jenkins queue, I'll wait for basic precommit to pass before running all the RunnableOnService tests. This affects every single runner and pipeline, so kind of a big deal.

**Comment by davorbonaci** [comment]
Any updates perhaps?

**Comment by kennknowles** [comment]
No time to debug this at the moment. At first glance, a warning in Findbugs escalating to an error.

**Comment by davorbonaci** [comment]
@kennknowles, any progress perhaps?

**Comment by kennknowles** [comment]
This isn't API blocking, so I'll just reopen it when I have a chance to sort out what is going wrong.

**Pull request closed without merging**
