### PR TITLE
[BEAM-9820] Upgrade Flink 1.9.x to 1.9.3

### PR DESCRIPTION
**Pull request by iemejia**
R: @sunjincheng121 @mxm

### CODE REVIEW

**Comment by sunjincheng121** [comment]
Thanks for the PR. @iemejia

**Comment by sunjincheng121** [comment]
Run Java PreCommit

**Comment by sunjincheng121** [comment]
Run Flink ValidatesRunner

**Comment by sunjincheng121** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by sunjincheng121** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by sunjincheng121** [comment]
Apache Flink Runner ValidatesRunner Tests

**Comment by sunjincheng121** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Thanks everyone, merging now.

**Comment by iemejia** [comment]
@mxm the error above is on Flink's translation or is somehow part of all the recent changes on runners core for SDF?

**Comment by mxm** [comment]
Fix is here: #11533

**Pull request merged**
