### PR TITLE
Add SessionPoolOptions.setFailIfPoolExhausted in SpannerAccessor

### PR DESCRIPTION
**Pull request by manitgupta**
Configures SpannerAccessor to set the `setFailIfPoolExhausted`  `SessionPoolOption` which ensures that the Spanner client throws an error if the session pool is exhausted.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by nielm** [comment]
Can you explain why you believe this is necessary to add? 

The default session pool options in Java are: 
* MinSessions =100
* MaxSessions = 400
* WriteSessionsFraction = 0.2

These will apply to each worker indivudually.

@olavloite for comment.

**Comment by manitgupta** [comment]
This is my primary motivation - 
https://github.com/googleapis/java-spanner/blob/main/session-and-channel-pool-configuration.md#automatically-clean-inactive-transactions

Currently, there is no way to set `setWarnAndCloseIfInactiveTransactions()`. `SpannerAccessor` is used in Dataflow templates like `DatastreamToSpanner`, which customers use as a black box, therefore, having this enabled by default makes sense.

**Comment by nielm** [comment]
In theory there should never be an inactive transaction left open by SpannerIO. 
If there is, then it is a bug in SpannerIO.

Writes use blind writes by calling [DatabaseClient.writeAtLeastOnce](https://cloud.google.com/java/docs/reference/google-cloud-spanner/latest/com.google.cloud.spanner.DatabaseClient#com_google_cloud_spanner_DatabaseClient_writeAtLeastOnce_java_lang_Iterable_com_google_cloud_spanner_Mutation__), which internally uses the [single_use_transaction feature of the Commit API](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.CommitRequest) so that a transaction is automatically started and closed by the Spanner server. 

Reads use a single read transaction, which is shared across all workers. By their nature these are long-running transactions.

SpannerIO is intended to isolate users from needing to worry about transactions, and to just pass their data in and let the connecter deal with it. 

If you are experiencing issues with session pool exhaustion, and believe that there may be a bug, then please raise an issue.

**Comment by manitgupta** [comment]
Bump! @nielm @olavloite

**Comment by nielm** [comment]
Result of out-of-band discussion between @manitgupta  and @olavloite  - Change the PR such that SpannerAccessor always sets
```
SessionPoolOptions.setFailIfPoolExhausted()
```
to avoid expanding the SpannerIO public API surface while also catching potential session leak bugs.

**Comment by nielm** [comment]
LGTM

Precommit fails for unrelated reason in 
`org.apache.beam.sdk.io.gcp.spanner.changestreams.it.SpannerChangeStreamOrderedWithinKeyIT > restOrderedWithinKey`

**Review by nielm — APPROVED** [review]

**Comment by nielm** [comment]
reverted in #32694

**Pull request merged**
