### PR TITLE
Beam-2329 ABS function

### PR DESCRIPTION
**Pull request by app-tarush**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Hi @xumingming , can you please take a look? I have break it into jira tickets wise.

### CODE REVIEW

**Comment by xumingming** [comment]
LGTM

**Comment by xumingming** [comment]
@jbonofre can you take a peek at this one?

**Comment by jbonofre** [comment]
R: @jbonofre

Sure ! Thanks !

**Comment by jbonofre** [comment]
Merged on `DSL_SQL`. Can you please close this PR ? Thanks !

**Comment by app-tarush** [comment]
@jbonofre @xumingming Thanks!!

**Pull request closed without merging**
