### PR TITLE
[BEAM-1185] Remove references to PipelineRunner

### PR DESCRIPTION
**Pull request by sb2nov**
R: @aaltay PTAL

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by sb2nov** [comment]
retest this please

**Comment by sb2nov** [comment]
The python build passed so should be ready for review.

**Comment by aaltay** [comment]
LGTM

**Comment by aaltay** [comment]
@sb2nov Could you rebase this PR to resolve conflicts?

**Comment by sb2nov** [comment]
Thanks Done.

**Pull request closed without merging**
