### PR TITLE
[DO NOT MERGE] Test change to a examples/ file

### PR DESCRIPTION
**Pull request by swegner**
**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by swegner** [comment]
I see some previous prototype jobs are still present; @jasonkuster are you able to clean these up on Jenkins? #5583 had added `beam_SeedJob_TriggerPrototype` and `beam_PreCommit_TriggerPrototype` jobs.

**Comment by jasonkuster** [comment]
To ensure I understand, you want to delete `beam_SeedJob_TriggerPrototype` and `beam_PreCommit_TriggerPrototype` from Jenkins entirely?

**Comment by swegner** [comment]
Yes please :)  thanks for checking

**Comment by jasonkuster** [comment]
http://www.hrwiki.org/w/images/thumb/c/c6/delorted.png/180px-delorted.png

https://www.youtube.com/watch?v=07h0ksKx5sM

**Pull request closed without merging**
