### PR TITLE
Cherry-pick #26503: fix dataloss bug in batch Storage API sink.

### PR DESCRIPTION
**Pull request by bvolpato**
Cherry-picking https://github.com/apache/beam/pull/26503 to release 2.47.0.

### CODE REVIEW

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
R: @jrmccluskey 

(your discretion whether it could be cherry-picked or not -- likely in case there's a new RC)

**Comment by jrmccluskey** [comment]
Run Java PreCommit

**Comment by jrmccluskey** [comment]
Run Java PreCommit

**Comment by jrmccluskey** [comment]
Run Java PreCommit

**Comment by jrmccluskey** [comment]
Failures in the Java PreCommit are unrelated, merging

**Pull request merged**
