### PR TITLE
Add drive scope to GCP Auth

### LINKED ISSUE #23290: [Feature Request]: Add Google Drive scope to GCP Auth
### What would you like to happen?

The current Python SDK doesn't include the `https://www.googleapis.com/auth/drive` scope when sending the authentication request to Google Cloud. This means that it's not possible to access Google Drive backed tables in BigQuery.

Adding the scope does indeed provide the required access. I'm only interested in the Python SDK, but this change should be easy to apply on all other SDKs as well if there's interest in that.

I can work on this change and submit a pull request.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by ricardograca-scratch**
This adds the ability to access Google Drive backed BigQuery tables in the Python and Java SDKs. Fixes #23290.

Note: I couldn't find the GCP Auth in the TypeScript and Go SDKs.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ricardograca-scratch** [comment]
Can you review this @kennknowles?

**Comment by kennknowles** [comment]
R: @tvalentyn

**Comment by lukecwik** [comment]
I think we want to minimize the number of scopes that are requested on behalf of a user. Users can already set their own credential factory in Beam Java and configure it to request any scopes when creating the credential object. We could use something similar for Beam Python.

For a simple improvement, we could make a pipeline option that each user can configure with the existing scopes being the default?

**Comment by tvalentyn** [comment]
> For a simple improvement, we could make a pipeline option that each user can configure with the existing scopes being the default?

FWIW this is straightforward. `pipeline_options` are available in both places `CLIENT_SCOPES` is currently used. we can add, for example an option `--custom_oauth_scopes` , that will store semicolon-separated strings here:

https://github.com/apache/beam/blob/2d84233009ffe7488649efbb0acdfb9fea7fdf31/sdks/python/apache_beam/options/pipeline_options.py#L767

We can add the contents of that option the the default scopes currently hardcoded.

**Comment by lukecwik** [comment]
> > For a simple improvement, we could make a pipeline option that each user can configure with the existing scopes being the default?
> 
> FWIW this is straightforward. `pipeline_options` are available in both places `CLIENT_SCOPES` is currently used. we can add, for example an option `--custom_oauth_scopes` , that will store semicolon-separated strings here:
> 
> https://github.com/apache/beam/blob/2d84233009ffe7488649efbb0acdfb9fea7fdf31/sdks/python/apache_beam/options/pipeline_options.py#L767
> 
> We can add the contents of that option the the default scopes currently hardcoded.
> 
> Note: it is sufficient to do this just for Python, Java already has a capability to create and supply custom credentials.

Can we use a list type instead of using semi-colons as pipeline_options.py supports lists already?

Having an equivalent in Java is convenient so that the user experience is the same. This will also help with xlang so that those additional scopes can be specified for IO reasons.

Also suggest `--oauth_scopes` instead of `--custom_oauth_scopes`

**Comment by ricardograca-scratch** [comment]
@lukecwik @tvalentyn I can certainly add the `parser.add_argument()` part, I think, but how do I specify what kind of value it accepts? And do I then just merge that value with `CLIENT_SCOPES`, or is there a more involved process that's required?

**Comment by tvalentyn** [comment]
@lukecwik good point.
@ricardograca-scratch you can mirror the implementation of dataflow_service_options. See:

https://github.com/apache/beam/blob/2d84233009ffe7488649efbb0acdfb9fea7fdf31/sdks/python/apache_beam/options/pipeline_options.py#L742-L753

https://github.com/apache/beam/blob/2d84233009ffe7488649efbb0acdfb9fea7fdf31/sdks/python/apache_beam/options/pipeline_options.py#L814

https://github.com/apache/beam/blob/45cc0854be553b5138753cf649fa863a80ff2b04/sdks/python/apache_beam/options/pipeline_options_test.py#L624

a repeatable option :  ` --oauth_scopes + --oauth_scope (alias)` sounds good.

you can then combine the content with the `CLIENT_SCOPES` wherever scopes are consumed. `CLIENT_SCOPES` can be renamed into `REQUIRED_OAUTH_SCOPES` to disambiguate required + additional.

**Comment by lukecwik** [comment]
This was superseded by https://github.com/apache/beam/pull/23644, feel free to reopen PR if you want to continue with this change.

**Pull request closed without merging**
