### PR TITLE
[BEAM-7171] Ensure bundle finalization during Flink checkpoint

### PR DESCRIPTION
**Pull request by mxm**
Watermarks are held back during execution of a portable bundle. When a
checkpoint is taken, the bundle needs to be finished to ensure consistent
state. After the bundle has finished, the watermark is updated. This can trigger
additional bundles which need to be finished as well.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tweise** [comment]
Didn't have the time to work on it yet, but I would like to implement the approach that I had already proposed in the JIRA. That way no extra bundles are created whenever the watermark advances. Should get to it in the next few days.

**Comment by mxm** [comment]
Do you think we could merge this in the meantime to fix the bundle finalization which prevents correct checkpointing?

**Comment by mxm** [comment]
Advancing the watermark later could work; as you pointed out, it avoids creating additional bundles.

I've modified the PR to ensure a finished bundle upon checkpointing. That avoids creating an additional bundle in case of a normal bundle finish. I'll merge these changes to fix the checkpointing. Feel free to take the issue over afterwards.

**Comment by tweise** [comment]
LGTM with the change to have the extra bundle on checkpoint only.

**Comment by tweise** [comment]
Curious what prompted to add the coders?

**Comment by mxm** [comment]
When I added the check for the number of states in the state backend, I needed to supply a coder for the state in the test. Supplying`null` there threw a NullPointerException when writing user state in the test. When I added a `checkNotNull` to `CoderTypeSerializer`, this triggered also for the non-testing state clearing which used `null` as a coder. I added VoidCoder because we do not need a coder to clear the state. Arguably this is not perfectly clean but I didn't see the need to pass through the coder as it is not needed for clearing state.

**Pull request merged**
