### PR TITLE
[WEBSITE] fix relative paths bug on staging in js files

### PR DESCRIPTION
**Pull request by bullet03**
Current state: img src didn't get correct path on staging in js and css files. Not resolved images make staging functionality differ from production and complicate review of impacted website changes.

Improvement: Below changes will enable staging resolve image sources with relative URLs, and staging will behave the same as production for images loaded in Javascript files.

- add absURL to page-nav.js and copy-to-clipboard.js, _case_study.scss to fix incorrect img src on staging
- add `resources.ExecuteAsTemplate` to head.html, head_homepage.html

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
before:
staging_bug

after:
staging_fixed

**Comment by alevtinaboiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
R: @pcoet

**Comment by bullet03** [comment]
@pcoet, PR is ready. Could you review it, please?

**Review by pcoet — APPROVED** [review]

**Comment by AKosolapov** [comment]
@pabloem Could you please help with reviewing and merging this PR?

**Comment by bullet03** [comment]
@aromanenko-dev, current PR was approved. Could you, please, help with merging?

**Comment by bullet03** [comment]
> Thanks, merged

Thank you for the help!

**Pull request merged**
