### PR TITLE
Fix scope for dependencies needed only for test purposes

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @aviemzur

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by aviemzur** [comment]
Run Spark ValidatesRunner

**Comment by aviemzur** [comment]
Run Apex ValidatesRunner

**Comment by aviemzur** [comment]
Run Dataflow ValidatesRunner

**Comment by aviemzur** [comment]
Run Flink ValidatesRunner

**Comment by iemejia** [comment]
Please don't review this yet, I still have some pending things to fix.

**Comment by iemejia** [comment]
I am closing this one and creating a JIRA and a new PR to explain the case with more details.

**Pull request closed without merging**
