### PR TITLE
Update Dataflow Python container to beam-master-20201005

### PR DESCRIPTION
**Pull request by ajamato**
Update Dataflow Python container to beam-master-20201005

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ajamato** [comment]
R: @tvalentyn

**Comment by tvalentyn** [comment]
LGTM, please rerun the suite once images are released.

**Comment by ajamato** [comment]
Run Python PreCommit

**Comment by ajamato** [comment]
Hmm. Looks like some java tests failed.

16:41:02 ======================================================================
16:41:02 FAIL: test_streaming_wordcount_it (apache_beam.examples.streaming_wordcount_it_test.StreamingWordCountIT)
16:41:02 ----------------------------------------------------------------------
16:41:02 Traceback (most recent call last):
16:41:02   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/apache_beam/examples/streaming_wordcount_it_test.py", line 107, in test_streaming_wordcount_it
16:41:02     save_main_session=False)
16:41:02   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/apache_beam/examples/streaming_wordcount.py", line 108, in run
16:41:02     output | beam.io.WriteToPubSub(known_args.output_topic)
16:41:02   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/apache_beam/pipeline.py", line 568, in __exit__
16:41:02     self.result = self.run()
16:41:02   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/apache_beam/pipeline.py", line 547, in run
16:41:02     return self.runner.run_pipeline(self, self._options)
16:41:02   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Phrase/src/sdks/python/apache_beam/runners/dataflow/test_dataflow_runner.py", line 72, in run_pipeline
16:41:02     hc_assert_that(self.result, pickler.loads(on_success_matcher))
16:41:02 AssertionError: 
16:41:02 Expected: (Test pipeline expected terminated in state: RUNNING and Expected 500 messages.)
16:41:02      but: Expected 500 messages. Got 0 messages. Diffs (item, count):
16:41:02   Expected but not in actual: dict_items([(b'0: 1', 1), (b'1: 1', 1), (b'2: 1', 1), (b'3: 1', 1), (b'4: 1', 1), (b'5: 1', 1), (b'6: 1', 1), (b'7: 1', 1), (b'8: 1', 1), (b'9: 1', 1), (b'10: 1', 1), (b'11: 1', 1), (b'12: 1', 1), (b'13: 1', 1), (b'14: 1', 1), (b'15: 1', 1), (b'16: 1', 1), (b'17: 1', 1), (b'18: 1', 1), (b'19: 1', 1), (b'20: 1', 1), (b'21: 1', 1), (b'22: 1', 1), (b'23: 1', 1), (b'24: 1', 1), (b'25: 1', 1), (b'26: 1', 1), (b'27: 1', 1), (b'28: 1', 1), (b'29: 1', 1), (b'30: 1', 1), (b'31: 1', 1), (b'32: 1', 1), (b'33: 1', 1), (b'34: 1', 1), (b'35: 1', 1), (b'36: 1', 1), (b'37: 1', 1), (b'38: 1', 1), (b'39: 1', 1), (b'40: 1', 1), (b'41: 1', 1), (b'42: 1', 1), (b'43: 1', 1), (b'44: 1', 1), (b'45: 1', 1), (b'46: 1', 1), (b'47: 1', 1), (b'48: 1', 1), (b'49: 1', 1), (b'50: 1', 1), (b'51: 1', 1), (b'52: 1', 1), (b'53: 1', 1), (b'54: 1', 1), (b'55: 1', 1), (b'56: 1', 1), (b'57: 1', 1), (b'58: 1', 1), (b'59: 1', 1), (b'60: 1', 1), (b'61: 1', 1), (b'62: 1', 1), (b'63: 1', 1), (b'64: 1', 1), (b'65: 1', 1), (b'66: 1', 1), (b'67: 1', 1), (b'68: 1', 1), (b'69: 1', 1), (b'70: 1', 1), (b'71: 1', 1), (b'72: 1', 1), (b'73: 1', 1), (b'74: 1', 1), (b'75: 1', 1), (b'76: 1', 1), (b'77: 1', 1), (b'78: 1', 1), (b'79: 1', 1), (b'80: 1', 1), (b'81: 1', 1), (b'82: 1', 1), (b'83: 1', 1), (b'84: 1', 1), (b'85: 1', 1), (b'86: 1', 1), (b'87: 1', 1), (b'88: 1', 1), (b'89: 1', 1), (b'90: 1', 1), (b'91: 1', 1), (b'92: 1', 1), (b'93: 1', 1), (b'94: 1', 1), (b'95: 1', 1), (b'96: 1', 1), (b'97: 1', 1), (b'98: 1', 1), (b'99: 1', 1), (b'100: 1', 1), (b'101: 1', 1), (b'102: 1', 1), (b'103: 1', 1), (b'104: 1', 1), (b'105: 1', 1), (b'106: 1', 1), (b'107: 1', 1), (b'108: 1', 1), (b'109: 1', 1), (b'110: 1', 1), (b'111: 1', 1), (b'112: 1', 1), (b'113: 1', 1), (b'114: 1', 1), (b'115: 1', 1), (b'116: 1', 1), (b'117: 1', 1), (b'118: 1', 1), (b'119: 1', 1), (b'120: 1', 1), (b'121: 1', 1), (b'122: 1', 1), (b'123: 1', 1), (b'124: 1', 1), (b'125: 1', 1), (b'126: 1', 1), (b'127: 1', 1), (b'128: 1', 1), (b'129: 1', 1), (b'130: 1', 1), (b'131: 1', 1), (b'132: 1', 1), (b'133: 1', 1), (b'134: 1', 1), (b'135: 1', 1), (b'136: 1', 1), (b'137: 1', 1), (b'138: 1', 1), (b'139: 1', 1), (b'140: 1', 1), (b'141: 1', 1), (b'142: 1', 1), (b'143: 1', 1), (b'144: 1', 1), (b'145: 1', 1), (b'146: 1', 1), (b'147: 1', 1), (b'148: 1', 1), (b'149: 1', 1), (b'150: 1', 1), (b'151: 1', 1), (b'152: 1', 1), (b'153: 1', 1), (b'154: 1', 1), (b'155: 1', 1), (b'156: 1', 1), (b'157: 1', 1), (b'158: 1', 1), (b'159: 1', 1), (b'160: 1', 1), (b'161: 1', 1), (b'162: 1', 1), (b'163: 1', 1), (b'164: 1', 1), (b'165: 1', 1), (b'166: 1', 1), (b'167: 1', 1), (b'168: 1', 1), (b'169: 1', 1), (b'170: 1', 1), (b'171: 1', 1), (b'172: 1', 1), (b'173: 1', 1), (b'174: 1', 1), (b'175: 1', 1), (b'176: 1', 1), (b'177: 1', 1), (b'178: 1', 1), (b'179: 1', 1), (b'180: 1', 1), (b'181: 1', 1), (b'182: 1', 1), (b'183: 1', 1), (b'184: 1', 1), (b'185: 1', 1), (b'186: 1', 1), (b'187: 1', 1), (b'188: 1', 1), (b'189: 1', 1), (b'190: 1', 1), (b'191: 1', 1), (b'192: 1', 1), (b'193: 1', 1), (b'194: 1', 1), (b'195: 1', 1), (b'196: 1', 1), (b'197: 1', 1), (b'198: 1', 1), (b'199: 1', 1), (b'200: 1', 1), (b'201: 1', 1), (b'202: 1', 1), (b'203: 1', 1), (b'204: 1', 1), (b'205: 1', 1), (b'206: 1', 1), (b'207: 1', 1), (b'208: 1', 1), (b'209: 1', 1), (b'210: 1', 1), (b'211: 1', 1), (b'212: 1', 1), (b'213: 1', 1), (b'214: 1', 1), (b'215: 1', 1), (b'216: 1', 1), (b'217: 1', 1), (b'218: 1', 1), (b'219: 1', 1), (b'220: 1', 1), (b'221: 1', 1), (b'222: 1', 1), (b'223: 1', 1), (b'224: 1', 1), (b'225: 1', 1), (b'226: 1', 1), (b'227: 1', 1), (b'228: 1', 1), (b'229: 1', 1), (b'230: 1', 1), (b'231: 1', 1), (b'232: 1', 1), (b'233: 1', 1), (b'234: 1', 1), (b'235: 1', 1), (b'236: 1', 1), (b'237: 1', 1), (b'238: 1', 1), (b'239: 1', 1), (b'240: 1', 1), (b'241: 1', 1), (b'242: 1', 1), (b'243: 1', 1), (b'244: 1', 1), (b'245: 1', 1), (b'246: 1', 1), (b'247: 1', 1), (b'248: 1', 1), (b'249: 1', 1), (b'250: 1', 1), (b'251: 1', 1), (b'252: 1', 1), (b'253: 1', 1), (b'254: 1', 1), (b'255: 1', 1), (b'256: 1', 1), (b'257: 1', 1), (b'258: 1', 1), (b'259: 1', 1), (b'260: 1', 1), (b'261: 1', 1), (b'262: 1', 1), (b'263: 1', 1), (b'264: 1', 1), (b'265: 1', 1), (b'266: 1', 1), (b'267: 1', 1), (b'268: 1', 1), (b'269: 1', 1), (b'270: 1', 1), (b'271: 1', 1), (b'272: 1', 1), (b'273: 1', 1), (b'274: 1', 1), (b'275: 1', 1), (b'276: 1', 1), (b'277: 1', 1), (b'278: 1', 1), (b'279: 1', 1), (b'280: 1', 1), (b'281: 1', 1), (b'282: 1', 1), (b'283: 1', 1), (b'284: 1', 1), (b'285: 1', 1), (b'286: 1', 1), (b'287: 1', 1), (b'288: 1', 1), (b'289: 1', 1), (b'290: 1', 1), (b'291: 1', 1), (b'292: 1', 1), (b'293: 1', 1), (b'294: 1', 1), (b'295: 1', 1), (b'296: 1', 1), (b'297: 1', 1), (b'298: 1', 1), (b'299: 1', 1), (b'300: 1', 1), (b'301: 1', 1), (b'302: 1', 1), (b'303: 1', 1), (b'304: 1', 1), (b'305: 1', 1), (b'306: 1', 1), (b'307: 1', 1), (b'308: 1', 1), (b'309: 1', 1), (b'310: 1', 1), (b'311: 1', 1), (b'312: 1', 1), (b'313: 1', 1), (b'314: 1', 1), (b'315: 1', 1), (b'316: 1', 1), (b'317: 1', 1), (b'318: 1', 1), (b'319: 1', 1), (b'320: 1', 1), (b'321: 1', 1), (b'322: 1', 1), (b'323: 1', 1), (b'324: 1', 1), (b'325: 1', 1), (b'326: 1', 1), (b'327: 1', 1), (b'328: 1', 1), (b'329: 1', 1), (b'330: 1', 1), (b'331: 1', 1), (b'332: 1', 1), (b'333: 1', 1), (b'334: 1', 1), (b'335: 1', 1), (b'336: 1', 1), (b'337: 1', 1), (b'338: 1', 1), (b'339: 1', 1), (b'340: 1', 1), (b'341: 1', 1), (b'342: 1', 1), (b'343: 1', 1), (b'344: 1', 1), (b'345: 1', 1), (b'346: 1', 1), (b'347: 1', 1), (b'348: 1', 1), (b'349: 1', 1), (b'350: 1', 1), (b'351: 1', 1), (b'352: 1', 1), (b'353: 1', 1), (b'354: 1', 1), (b'355: 1', 1), (b'356: 1', 1), (b'357: 1', 1), (b'358: 1', 1), (b'359: 1', 1), (b'360: 1', 1), (b'361: 1', 1), (b'362: 1', 1), (b'363: 1', 1), (b'364: 1', 1), (b'365: 1', 1), (b'366: 1', 1), (b'367: 1', 1), (b'368: 1', 1), (b'369: 1', 1), (b'370: 1', 1), (b'371: 1', 1), (b'372: 1', 1), (b'373: 1', 1), (b'374: 1', 1), (b'375: 1', 1), (b'376: 1', 1), (b'377: 1', 1), (b'378: 1', 1), (b'379: 1', 1), (b'380: 1', 1), (b'381: 1', 1), (b'382: 1', 1), (b'383: 1', 1), (b'384: 1', 1), (b'385: 1', 1), (b'386: 1', 1), (b'387: 1', 1), (b'388: 1', 1), (b'389: 1', 1), (b'390: 1', 1), (b'391: 1', 1), (b'392: 1', 1), (b'393: 1', 1), (b'394: 1', 1), (b'395: 1', 1), (b'396: 1', 1), (b'397: 1', 1), (b'398: 1', 1), (b'399: 1', 1), (b'400: 1', 1), (b'401: 1', 1), (b'402: 1', 1), (b'403: 1', 1), (b'404: 1', 1), (b'405: 1', 1), (b'406: 1', 1), (b'407: 1', 1), (b'408: 1', 1), (b'409: 1', 1), (b'410: 1', 1), (b'411: 1', 1), (b'412: 1', 1), (b'413: 1', 1), (b'414: 1', 1), (b'415: 1', 1), (b'416: 1', 1), (b'417: 1', 1), (b'418: 1', 1), (b'419: 1', 1), (b'420: 1', 1), (b'421: 1', 1), (b'422: 1', 1), (b'423: 1', 1), (b'424: 1', 1), (b'425: 1', 1), (b'426: 1', 1), (b'427: 1', 1), (b'428: 1', 1), (b'429: 1', 1), (b'430: 1', 1), (b'431: 1', 1), (b'432: 1', 1), (b'433: 1', 1), (b'434: 1', 1), (b'435: 1', 1), (b'436: 1', 1), (b'437: 1', 1), (b'438: 1', 1), (b'439: 1', 1), (b'440: 1', 1), (b'441: 1', 1), (b'442: 1', 1), (b'443: 1', 1), (b'444: 1', 1), (b'445: 1', 1), (b'446: 1', 1), (b'447: 1', 1), (b'448: 1', 1), (b'449: 1', 1), (b'450: 1', 1), (b'451: 1', 1), (b'452: 1', 1), (b'453: 1', 1), (b'454: 1', 1), (b'455: 1', 1), (b'456: 1', 1), (b'457: 1', 1), (b'458: 1', 1), (b'459: 1', 1), (b'460: 1', 1), (b'461: 1', 1), (b'462: 1', 1), (b'463: 1', 1), (b'464: 1', 1), (b'465: 1', 1), (b'466: 1', 1), (b'467: 1', 1), (b'468: 1', 1), (b'469: 1', 1), (b'470: 1', 1), (b'471: 1', 1), (b'472: 1', 1), (b'473: 1', 1), (b'474: 1', 1), (b'475: 1', 1), (b'476: 1', 1), (b'477: 1', 1), (b'478: 1', 1), (b'479: 1', 1), (b'480: 1', 1), (b'481: 1', 1), (b'482: 1', 1), (b'483: 1', 1), (b'484: 1', 1), (b'485: 1', 1), (b'486: 1', 1), (b'487: 1', 1), (b'488: 1', 1), (b'489: 1', 1), (b'490: 1', 1), (b'491: 1', 1), (b'492: 1', 1), (b'493: 1', 1), (b'494: 1', 1), (b'495: 1', 1), (b'496: 1', 1), (b'497: 1', 1), (b'498: 1', 1), (b'499: 1', 1)])
16:41:02   Unexpected: dict_items([])
16:41:02

**Comment by ajamato** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2239/consoleFull

**Comment by ajamato** [comment]
Run Python PreCommit

**Comment by ajamato** [comment]
Run Python PreCommit

**Comment by ajamato** [comment]
Current failure

https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/2241/testReport/junit/apache_beam.runners.interactive.display.pcoll_visualization_test/PCollectionVisualizationTest/test_dynamic_plotting_return_handle/

Error MessageAssertionError: None is not an instance of <class 'timeloop.app.Timeloop'>Stacktraceself = <apache_beam.runners.interactive.display.pcoll_visualization_test.PCollectionVisualizationTest testMethod=test_dynamic_plotting_return_handle> def test_dynamic_plotting_return_handle(self): h = pv.visualize( self._stream, dynamic_plotting_interval=1, display_facets=True)> self.assertIsInstance(h, timeloop.Timeloop)E AssertionError: None is not an instance of <class 'timeloop.app.Timeloop'>apache_beam/runners/interactive/display/pcoll_visualization_test.py:93: AssertionErrorStandard Output<IPython.core.display.HTML object><IPython.core.display.HTML object> 00 01 12 23 34 4

**Comment by ajamato** [comment]
Run Python PreCommit

**Pull request merged**
