### PR TITLE
[BEAM-3684] Integrate master to go-sdk and fixup coder urns

### PR DESCRIPTION
**Pull request by herohde**

### CODE REVIEW

**Comment by herohde** [comment]
R: @lostluck @wcn3 (for the coder update)

**Comment by wcn3** [comment]
Looks like it does as advertised.

Should we sync from master on a more regular basis to not make these sorts of PRs look so complex?

**Comment by wcn3** [comment]
LGTM

**Comment by wcn3** [comment]
@chamikaramj please merge this

**Pull request merged**
