### PR TITLE
[BEAM-4535] Add a custom _url_dirname for local filesystems.

### PR DESCRIPTION
**Pull request by udim**
Cherrypick for 2.5.0

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by udim** [comment]
R: @jbonofre 

Added this cherrypick as well, which Cham mentioned in the voting thread yesterday.
If fixes https://issues.apache.org/jira/browse/BEAM-4535

**Comment by udim** [comment]
CC: @chamikaramj

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by aaltay** [comment]
I would guess that `IllegalStateException` is unrelated to this python only change. Is it correct?

**Pull request merged**
