### PR TITLE
[BEAM-59] Minor changes that can be separated out from big PR

### PR DESCRIPTION
**Pull request by dhalperi**
All these are minor changes, correct at HEAD, and standalone from #2779

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @jkff 

Can you take a quick look?

**Comment by peihe** [comment]
LGTM
(based on the context from each commit)

**Comment by dhalperi** [comment]
thanks @peihe !

Rebased on top of master to pickup build fix.

**Comment by jkff** [comment]
LGTM as well.

**Pull request closed without merging**
