### PR TITLE
ElasticsearchIO: Added compatibility check with v2.x

### PR DESCRIPTION
**Pull request by echauchot**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Some users of the ElasticsearchIO try to use it with Elasticsearch v5.x which is not supported yet (see https://issues.apache.org/jira/browse/BEAM-1637), this PR just adds a compatibility warning in the IO javadoc. I did not create a jira for it.

R: @jbonofre

### CODE REVIEW

**Comment by echauchot** [comment]
@jbonofre, @iemejia  suggested to add a version test in the IO in addition to the javadoc warning. I find it's a good idea, I'll push another commit, can you wait for it before merging to avoid the work of multiple merges? Thanks

**Comment by echauchot** [comment]
Also pushed an Elasticsearch version check. Checks that Elasticsearch version to connect to is 2.x. Fails in ConnectionConfiguration.create() otherwise. Also throws an IOException if connection error in ConnectionConfiguration.create()

R: @jbonofre

**Comment by jbonofre** [comment]
Good idea. Let me take a look ;)

**Comment by echauchot** [comment]
@jbonofre now that this PR is no more just a javadoc update, do you want that I open a jira ticket for the version check code?

**Comment by jbonofre** [comment]
@echauchot no Jira needed: the PR doesn't change the API or behavior, it's just a javadoc update and not necessary appearing in the Release Notes. I will  merge pretty soon.

**Comment by echauchot** [comment]
@jbonofre: ok, please note, that there is a little behavior change: `ConnectionConfiguration.create()` now connects to ES to check version. So it now throws an IOException if connection failed.

**Pull request closed without merging**
