### PR TITLE
Fix a bunch of no-op typos

### PR DESCRIPTION
**Pull request by bvolpato**

### CODE REVIEW

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
Run Java_ElasticSearch_IO_Direct PreCommit

**Comment by bvolpato** [comment]
Run Java_IOs_Direct PreCommit

**Comment by bvolpato** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by bvolpato** [comment]
retest this please

**Comment by bvolpato** [comment]
assign set of reviewers

**Review by riteshghorse — APPROVED** [review]
Wow, that's a lot of typos gone unnoticed.. Thank you for fixing this Bruno!

**Comment by svetakvsundhar** [comment]
Nice finds. I imagine more of these exist for some of the more legacy code. Perhaps filing a GH issue and linking to the PR here of the places you looked could be helpful so that no one duplicates this work?

**Review by svetakvsundhar — APPROVED** [review]

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
Run Java_Amazon-Web-Services2_IO_Direct PreCommit

**Comment by bvolpato** [comment]
Run Java_Amazon-Web-Services_IO_Direct PreCommit

**Comment by bvolpato** [comment]
Rebased to re-run tests, I think there were some systematic failures when I opened the PR. Thanks!

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by bvolpato** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by bvolpato** [comment]
Run Java_IOs_Direct PreCommit

**Comment by bvolpato** [comment]
Please help in merging this

**Comment by bvolpato** [comment]
Run Java PreCommit

**Comment by riteshghorse** [comment]
Thanks again, Bruno!

**Pull request merged**
