### PR TITLE
Cherrypicks for 2 2 0 rc 4

### PR DESCRIPTION
**Pull request by tvalentyn**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @reuvenlax 
cc: @lukecwik @robertwb @davidcavazos @aaltay

**Comment by tvalentyn** [comment]
All commits are cherrypicks from master.

**Comment by reuvenlax** [comment]
Are the test faiures understood?

**Comment by reuvenlax** [comment]
lgtm

**Comment by tvalentyn** [comment]
Java test suite fails with [ERROR] Could not find the selected project in the reactor: sdks/java/fn-execution. This is caused by https://issues.apache.org/jira/browse/BEAM-3047. 
The maven project in question was added to master in https://github.com/apache/beam/commit/fdd5971d95df3219954023c6806f09dce87a1f8c but we don't have it in the release branch. 

This PR does not affect Java codebase and is safe to merge.

**Comment by reuvenlax** [comment]
approved for self-merge then.

**Comment by tvalentyn** [comment]
I am afraid I am not an authorized committer to run @asfgit merge.

**Comment by lukecwik** [comment]
I'll merge

**Pull request merged**
