### PR TITLE
make TransformingMap serializable

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Comment by reuvenlax** [comment]
run PostCommit Python Xlang IO Dataflow / beam_PostCommit_Python_Xlang_IO_Dataflow

**Comment by reuvenlax** [comment]
RUN beam_PostCommit_Python_Xlang_IO_Dataflow

**Comment by reuvenlax** [comment]
R: @ahmedabu98 
R: @chamikaramj

**Review by ahmedabu98 — APPROVED** [review]
LGTM, thanks

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Pull request merged**
