### PR TITLE
[BEAM-7390] Add combineperkey code snippets

### PR DESCRIPTION
**Pull request by davidcavazos**
Add `CombinePerKey` code snippets.

R: @aaltay 
R: @rosetn 

Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12277/documentation/transforms/python/aggregation/combineperkey/index.html

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by davidcavazos** [comment]
It looks like my IDE reformatted the xml automatically, I'll get rid of all the unnecessary edits

**Comment by aaltay** [comment]
- The correct staging link seems to be (http://apache-beam-website-pull-requests.storage.googleapis.com/12277/documentation/transforms/python/aggregation/combineperkey/index.html). I reviewed that it LGTM.
- Please revert the changes to other files. It makes the history much more cleaner and focused.
- A question to both you and @rosetn - There is a quite a bit of content duplication between this page and CombineGlobally page. Is there a more de-duplicated way of presenting this content?

**Comment by davidcavazos** [comment]
> * The correct staging link seems to be (http://apache-beam-website-pull-requests.storage.googleapis.com/12277/documentation/transforms/python/aggregation/combineperkey/index.html). I reviewed that it LGTM.

Thanks, forgot to update that part.

> * Please revert the changes to other files. It makes the history much more cleaner and focused.

Will do

> * A question to both you and @rosetn - There is a quite a bit of content duplication between this page and CombineGlobally page. Is there a more de-duplicated way of presenting this content?

They are different transforms and so they both have their own code snippets, we could try to merge both into a single page but that might be a little too long since it would have 2 code snippets for each example. @rosetn any thoughts?

**Comment by davidcavazos** [comment]
Also, similarly there is [`CombineValues`](https://beam.apache.org/releases/pydoc/current/apache_beam.transforms.core.html#apache_beam.transforms.core.CombineValues) which also has its own set of code snippets. I'll wait for this to resolve before opening a PR for it.

**Comment by aaltay** [comment]
@rosetn - Any comments about David's question about merging different snippets into a single page?

**Comment by davidcavazos** [comment]
We're not linking to colab for the moment. After the Hugo migration, the entire Markdown templating system is no longer Jinja-compatible and I need to write an extensible Markdown parser from scratch. I was exploring that in Python but it's really cumbersome and hard to maintain.

I'll be re-writing the notebook generator with the parser in a [real functional language](https://elm-lang.org/) which will make things a lot easier and will give us the guarantee of **no runtime exceptions**.

**Comment by rosetn** [comment]
I don't think we should merge the snippets into a single page for the following reasons:

1. The merged page is too long. The goal is to provide a friendly, quick reference catalog where you can immediately run transforms and understand various ways to use them. Scrolling through content that you are not looking for can be intimidating.
2. It'd be harder to quickly spot a specific transform if we start combining pages. If you're exploring different transforms, it's easier to find if there are individual listings in the left navigation bar. The transforms Overview page also provide a way to do this, but the left nav exists on every documentation page.

**Comment by aaltay** [comment]
Ack. Thank you @rosetn. 

@davidcavazos - please revert the unrelated changes, then we can merge this.

**Comment by davidcavazos** [comment]
@aaltay I thought I had commits changing history on unrelated files, but now that I'm double checking I think there aren't any.

* I'm linking from `CombineGlobally` since they are related (and I'll probably do the same for `CombineValues` once I create that PR)
* `combineperkey.md` is a new file since it didn't exist earlier (I'll also have to create `combinevalues.md` in a later PR)
* `overview.md` adds the `CombineGlobally` link to the overview page since it didn't exist earlier (and a couple style changes)
* `documentation.html` adds the `CombineGlobally` link to the side navigation bar, plus my editor automatically formatted the HTML mostly for indentations, but with no content changes other than adding the new page

I can revert the style changes if that's what you're referring to, but it's mostly indenting the HTML so I think it's fine as a one time only thing. Would you prefer me to go back and revert those changes back and only leave adding the new link?

**Comment by aaltay** [comment]
I think it would be good to revert changes to style (mostly in the documentation.html), or separate it to a different commit, or to a new pr.

**Comment by davidcavazos** [comment]
@aaltay style changes on `documentation.html` are reverted.

**Pull request merged**
