### PR TITLE
[BEAM-1402] Makes TextIO comply with PTransform style guide

### PR DESCRIPTION
**Pull request by jkff**
Migration guide: TextIO.Read.from() -> TextIO.read().from; TextIO.Write.to() -> TextIO.write().to()

Also converts both to AutoValue and moves some utility classes to upper level to declutter TextIO.java.

Each individual commit should be trivial to review.

R: @reuvenlax

### CODE REVIEW

**Comment by dhalperi** [comment]
Please, please no churn on FileBased-Write transforms while I'm still hacking on FileBasedSink.

**Comment by dhalperi** [comment]
Hmm ,well, that's unfair. This is a lot of work, too.

**Comment by reuvenlax** [comment]
This PR doesn't appear to touch the FileBasedSink base class.

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Here too, the test failures are flakes - it passes mvn verify -Prelease locally.

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Since Reuven is traveling
R: @jbonofre 

(though if you approve, please don't merge: I'll merge myself, upon coordinating with @dhalperi)

**Comment by jkff** [comment]
retest this please

**Comment by jbonofre** [comment]
R: @jbonofre

**Pull request closed without merging**
