### PR TITLE
[KafkaIO] Share size and offset estimators among ReadFromKafkaDoFn instances per PTransform

### PR DESCRIPTION
**Pull request by sjvanrossum**
This change adds shared caches among unique instances of `ReadFromKafkaDoFn`, identified by a static `AtomicLong` which is stored as an instance field and incremented during construction of the `DoFn`. The constructor is bypassed during deserialization at execution time, thus providing a shared identifier for all instances of `ReadFromKafkaDoFn` for a single transform.

Note: this PR is stacked on top of #32921, #32920 and #32889

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by sjvanrossum** [comment]
assign set of reviewers

**Comment by johnjcasey** [comment]
LGTM, please fix the conflicts and this should be good to go

**Comment by sjvanrossum** [comment]
Done, should be good to go once #32921 is merged.

**Review by johnjcasey — APPROVED** [review]

**Comment by sjvanrossum** [comment]
@johnjcasey rebased and updated where required. `PreCommit Spotless` is failing, so I ran its action (`./gradlew spotlessCheck checkStyleMain checkStyleTest :buildSrc:spotlessCheck`) locally and that passed.

@Abacn any thoughts?

**Comment by sjvanrossum** [comment]
Run Spotless PreCommit

**Comment by sjvanrossum** [comment]
`PreCommit Spotless` passed: https://github.com/apache/beam/actions/runs/11817154535

Not sure why the check overview doesn't update.

**Comment by Abacn** [comment]
> Done, should be good to go once #32921 is merged.

#32921 is merged, need to rebase this PR onto the current master branch

**Comment by sjvanrossum** [comment]
Run Spotless PreCommit

**Pull request merged**
