### PR TITLE
Use github actions to cut release branch

### PR DESCRIPTION
**Pull request by damccorm**
This currently only doesn't work because it relies on self hosted runners. Our Actions queue has actually been low enough that we can probably get away with just using hosted. It might just slow things down a bit, but that's better than dealing with environmental problems.

I tested this against my fork and it produced the following commit against master (note, this was the only commit produced and I've since force pushed my branch back to apache/beam head): https://github.com/damccorm/beam/commit/0ebe7edec167559adb82b1ded1c03ac253fdeab2

and against the release branch that it created: https://github.com/damccorm/beam/commit/0548e6676fd0ba59aaae9f70bd35ed6280fc3591

For comparison, here are the corresponding commits from the last release against master: https://github.com/apache/beam/commit/eb169f5bb95a8e91112f2d8122f5e7068039713b

and the release branch: https://github.com/apache/beam/commit/3b44dc61bc515bdee1d810402b155780b752226a

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @jrmccluskey (this should keep us from future problems with this script 🙃 )

**Review by jrmccluskey — APPROVED** [review]
LGTM (if we can avoid a human ever directly pushing to master again I will be a happy person)

**Comment by kennknowles** [comment]
Commented on the postmortem doc - could it make sense to have two separate actions with simpler scripts? Advancing the SNAPSHOT version on the master branch is actually separable from cutting the branch. Only advancing the version should require a push to master and isolating that could potentially simplify everything to reduce the likelihood of problems.

**Comment by damccorm** [comment]
I don't see a ton of value in separating it out since these will always be run together (and I don't personally see them as being particularly complicated scripts). In my mind, it just creates an extra button to press. One option would be to give users an option to skip the job that pushes to master via an input (a la https://github.com/apache/beam/blob/d7ded3f07064919c202c81a2c786910e20a834f9/.github/workflows/build_release_candidate.yml#L16)

I don't feel strongly one way or another; if you do, feel free to put up a PR

**Comment by kennknowles** [comment]
I mean in the event that "cut release branch" encounters an issue after advancing master branch, there's no reason to rerun the whole thing. Trying to revert and rerun appears to have been a trigger for the deletion.

**Comment by kennknowles** [comment]
I agree that extra button is not useful.

**Comment by damccorm** [comment]
This should be a good middle ground - https://github.com/apache/beam/pull/26793 - it defaults to chaining them, but you can opt out

**Pull request merged**
