### PR TITLE
[BEAM-13590]Add support for python 3.10

### PR DESCRIPTION
**Pull request by AnandInguva**
Add Python 3.10 infrastructure and test suites

Fixes: https://github.com/apache/beam/issues/21971
Fixes: https://github.com/apache/beam/issues/21458
FIxes: https://github.com/apache/beam/issues/21671

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
What is the next step on this PR?

**Comment by AnandInguva** [comment]
> What is the next step on this PR?

There are type hint related bugs. I will do more investigation next week and try to find the solution or ask help.

**Comment by robertwb** [comment]
Is this still being worked on? Are there intermediate milestones that could be checked in sooner rather than later?

**Comment by AnandInguva** [comment]
> Is this still being worked on? Are there intermediate milestones that could be checked in sooner rather than later? 

Yes, it is still being worked on. There are some blockers and we filed GH issues on them.

**Comment by AnandInguva** [comment]
Run Python 3.10 PostCommit

**Comment by AnandInguva** [comment]
Run Python 3.10 PostCommit

**Comment by AnandInguva** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
Just checking: Is this PR blocked? What are the next steps?

**Comment by AnandInguva** [comment]
> Just checking: Is this PR blocked? What are the next steps?

Waiting on Shuffle client for Runner v1. Planning to include this PR before next release cut.

**Comment by AnandInguva** [comment]
Run Python Dataflow V2 ValidatesRunner

**Comment by AnandInguva** [comment]
Run Python 3.10 PostCommit

**Comment by AnandInguva** [comment]
Run Python Examples_Direct

**Comment by AnandInguva** [comment]
Run Python Dataflow ValidatesContainer

**Comment by AnandInguva** [comment]
Run Python Dataflow ValidatesContainer

**Comment by AnandInguva** [comment]
Run Python 3.10 PostCommit

**Comment by AnandInguva** [comment]
@tvalentyn Can you enable the gh workflow?

**Comment by AnandInguva** [comment]
Run Python Dataflow ValidatesRunner

**Comment by AnandInguva** [comment]
Run Python Dataflow ValidatesContainer

**Comment by AnandInguva** [comment]
Run Dataflow Python ValidatesRunner

**Comment by AnandInguva** [comment]
Run Python Dataflow ValidatesRunner

**Comment by AnandInguva** [comment]
Run Python Dataflow V2 ValidatesRunner

**Comment by AnandInguva** [comment]
Run Python Examples_Direct

**Comment by AnandInguva** [comment]
Run Python 3.10 PostCommit

**Comment by tvalentyn** [comment]
> @tvalentyn Can you enable the gh workflow?

I clicked the button to approve the run, lmk if other action is necessary.

**Comment by aaltay** [comment]
Was this merged?

**Comment by AnandInguva** [comment]
Yes. This changed was merged in a different branch - https://github.com/apache/beam/pull/23587

**Pull request closed without merging**
