### PR TITLE
Remove Jenkins Python Formatter PreCommit

### LINKED ISSUE #28426: [Task]: Shutdown Jenkins PreCommits
### What needs to happen?

All precommits are now migrated to GitHub Action, and we agreed start the process of remove the Jenkins counterpart.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Address #28426

This PR shutdowns the following Jenkins suite. Their GitHub Actions are in healthy state. And they do not rely on test report (Jenkins Go and TypeScript tests did not have test report either)

| Name | Jenkins status | GitHub Action status |
|-----|-----|-----|
| PreCommit_PythonFormatter | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonFormatter_Cron/) | [.github/workflows/beam_PreCommit_PythonFormatter.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_PythonFormatter.yml)
| PreCommit_Kotlin_Examples | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Kotlin_Examples_Cron/) | [.github/workflows/beam_PreCommit_Kotlin_Examples.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_Kotlin_Examples.yml)
| PreCommit_Go | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/) | [.github/workflows/beam_PreCommit_Go.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_Go.yml)
| PreCommit_GoPortable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/) | [.github/workflows/beam_PreCommit_GoPortable.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_GoPortable.yml)
| PreCommit_TypeScript | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_TypeScript_Cron/) | [.github/workflows/beam_PreCommit_Typescript.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_Typescript.yml)
| PreCommit_CommunityMetrics | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_CommunityMetrics_Cron/) | [.github/workflows/beam_PreCommit_CommunityMetrics.yml](https://github.com/apache/beam/actions/workflows/beam_PreCommit_CommunityMetrics.yml)

For convenience we should merge them into one. Either test does not take long to run.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Run PythonLint PreCommit

**Comment by Abacn** [comment]
R: @damccorm

**Comment by damccorm** [comment]
I'm not sure I see the advantage of doing this; personally I actually like getting a more specific signal for failure and this also lengthens the time to get the signal (which can be important for first-time folks who aren't familiar with our build system and rely on precommits)

**Comment by Abacn** [comment]
Run Java_HBase_IO_Direct PreCommit

**Comment by Abacn** [comment]
Run Java_HBase_IO_Direct PreCommit

**Comment by Abacn** [comment]
R: @damccorm 

PreCommits that does not rely on test report (Java/Python) should be done after this PR. Then I will check if the test report plugin works well / do adjustments / asks for feedback then proceed to shutdown java precommits

**Review by damccorm — APPROVED** [review]
This LGTM, thanks!

**Pull request merged**
