### PR TITLE
[BEAM-9399] Ensure that empty messages are not flushed to handler.

### PR DESCRIPTION
**Pull request by scwhittle**
Fix an issue introduced by 
https://github.com/apache/beam/pull/11096
where empty messages could end up being published to the handler if the PrintStream was flushed when empty.  Added a unit test ensuring no empty messages are published.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
retest this please

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
This was only part of the fix and this change appeared in the 2.21 release. The last part of the fix appears in the 2.25 release.

**Comment by kplanes** [comment]
Hi @lukecwik  -  Interestingly enough the codebase which is failing is on the 2.23.0 version ? Do you think there might be a sub dependency which wasn't appropriately updated or similar ? It's surprising

**Comment by lukecwik** [comment]
That would work.

> Hi @lukecwik - Interestingly enough, I'm having it failing on the 2.23.0 version ?
> 
> Code : catch (Exception e) {
> System.out.println("Failed to filter user data " + c.element());
> e.printStackTrace();
> 
> I assume to work around would be to change it from send it to StackTrace to another print out ?
> 
> Errror :
> java.lang.IllegalStateException: [BEAM-9399](https://issues.apache.org/jira/browse/BEAM-9399): publish should not be called with the lock as it may cause deadlock
> at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:507)
> at org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.publishIfNonEmpty(JulHandlerPrintStreamAdapterFactory.java:380)
> at org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.println(JulHandlerPrintStreamAdapterFactory.java:332)
> at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
> at java.lang.Throwable.printStackTrace(Throwable.java:655)
> at java.lang.Throwable.printStackTrace(Throwable.java:643)
> at java.lang.Throwable.printStackTrace(Throwable.java:634)
> at com.metix.historic.transforms.FilterAndMapPatientsByAge.processElement(FilterAndMapPatientsByAge.java:25)

Yes, using another printstream would work around the issue.

@scwhittle Any ideas as to why it would be broken in 2.23?

**Comment by scwhittle** [comment]
On Wed, Oct 14, 2020, 7:06 PM Lukasz Cwik <notifications@github.com> wrote:

> That would work.
>
> Hi @lukecwik <https://github.com/lukecwik> - Interestingly enough, I'm
> having it failing on the 2.23.0 version ?
>
> Code : catch (Exception e) {
> System.out.println("Failed to filter user data " + c.element());
> e.printStackTrace();
>
> I assume to work around would be to change it from send it to StackTrace
> to another print out ?
>
> Errror :
> java.lang.IllegalStateException: BEAM-9399
> <https://issues.apache.org/jira/browse/BEAM-9399>: publish should not be
> called with the lock as it may cause deadlock
> at
> org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:507)
> at
> org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.publishIfNonEmpty(JulHandlerPrintStreamAdapterFactory.java:380)
> at
> org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.println(JulHandlerPrintStreamAdapterFactory.java:332)
> at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
> at java.lang.Throwable.printStackTrace(Throwable.java:655)
> at java.lang.Throwable.printStackTrace(Throwable.java:643)
> at java.lang.Throwable.printStackTrace(Throwable.java:634)
> at
> com.metix.historic.transforms.FilterAndMapPatientsByAge.processElement(FilterAndMapPatientsByAge.java:25)
>
> Yes, using another printstream would work around the issue.
>
Could also avoid e.printStackTrace() and instead print the stack trace to a
string and then print, for example using

https://guava.dev/releases/23.0/api/docs/com/google/common/base/Throwables.html#getStackTraceAsString-java.lang.Throwable-

System.out.println("Failed to filter user data " + c.element() + " " +
Throwables.getStackTraceAsString(e));

> @scwhittle <https://github.com/scwhittle> Any ideas as to why it would be
> broken in 2.23?
>
It is broken because https://github.com/apache/beam/pull/11096 changed a
potential deadlock into consistent IllegalStateException.  This was
unintended, I didn't consider that other things might synchronize on the
overridden System.err PrintStream.  Throwable.printStackTrace does this.
This was fixed by  https://github.com/apache/beam/pull/12825 which was
cherrypicked to the 2.25 release. The commit comment there has more details.

**Comment by wclaralee** [comment]
Hello, I am now getting this error since adding usage of BigQuery Storage API when reading from a table using `.withMethod(Method.DIRECT_READ)` using beam 2.21.0. The error stack trace I get is similar to the one above: 
`Error message from worker: java.lang.IllegalStateException: BEAM-9399: publish should not be called with the lock as it may cause deadlock org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:507) org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.publishIfNonEmpty(JulHandlerPrintStreamAdapterFactory.java:380) org.apache.beam.runners.dataflow.worker.logging.JulHandlerPrintStreamAdapterFactory$JulHandlerPrintStream.println(JulHandlerPrintStreamAdapterFactory.java:332) java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748) java.lang.Throwable.printStackTrace(Throwable.java:655) java.lang.Throwable.printStackTrace(Throwable.java:643) java.lang.Throwable.printStackTrace(Throwable.java:634) org.slf4j.helpers.Util.report(Util.java:124) `
(^truncated a bit.)
Please let me know. Thank you.

**Pull request merged**
