### PR TITLE
[BEAM-3292][SQL] Replace java.sql.Types with SqlTypeCoder

### PR DESCRIPTION
**Pull request by akedin**
[BEAM-3292](https://issues.apache.org/jira/browse/BEAM-3292)
Most of the logic is mechanical replacement of `BeamRecordSqlType` with its parent class `BeamRecordType`.

Overall, what happens here:
 - added `SqlTypeCoder` which contains a set of coders for supported SQL types;
 - replaced usages of `java.sql.Types` with corresponding `SqlTypeCoder`;
 - this allows to remove `BeamRecordSqlType` as a custom SQL-specific row type and rely on core `BeamRecordType` instead;
 - couple of things had to be added to the `BeamRecordType`, like exposing a getter for the field coders, and `equals()/hash()` implementation;

Most functional changes are in [`SqlTypeCoder`](https://github.com/apache/beam/compare/master...akedin:sql-remove-recordsqltype?expand=1#diff-649352076765585a0e0e5ad4746f76e9) and [`CalciteUtils`](https://github.com/apache/beam/compare/master...akedin:sql-remove-recordsqltype?expand=1#diff-405b8ce2112ec4714ba6a11586b26040). 

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles , please take a look, if this makes sense

**Comment by kennknowles** [comment]
This is really nice IMO. You even made the tests more readable :-). Most of it I am happy to merge right away. The main thing that I would not merge is the bit where you have a `CustomCoder` with a URN in it. Is that required right now? Let's sort out how Java coder <-> proto coder is going to work.

---

Reviewed 65 of 65 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/values/BeamRecordType.java, line 42 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j4QKSY46JU2MvnQqc:-L3j4QKSY46JU2MvnQqd:bkb08xk) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/core/src/main/java/org/apache/beam/sdk/values/BeamRecordType.java#L42)):*
> ```Java
>    * Create a {@link BeamRecordType} with a name and Coder for each field.
>    */
>   public BeamRecordType(List<String> fieldNames, List<Coder> fieldCoders) {
> ```

Two things that would be more readable and impossible to get wrong: Having a `Field` POJO or accepting a `Map<String, Coder>`.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/values/BeamRecordType.java, line 70 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j5BT-8fuATwVzoMMP:-L3j5BT-8fuATwVzoMMQ:bvltkrs) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/core/src/main/java/org/apache/beam/sdk/values/BeamRecordType.java#L70)):*
> ```Java
>    * Return the field coder for {@code index}.
>    */
>   public Coder getFieldCoder(int index){
> ```

So if I want the coder for a named field I first find the index and then look it up here? I guess I see that mostly by-name access is not important since it didn't really exist before.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/BeamRecordSqlType.java, line 53 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j5YFL5tNbIxOsu9yI:-L3j5YFL5tNbIxOsu9yJ:bkoz77q) ([raw file](https://github.com/apache/beam/blob/f7dd0505efe88a28f020ffc88c993589f48b3f98/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/BeamRecordSqlType.java#L53)):*
> ```Java
>  *
>  */
> public class BeamRecordSqlType extends BeamRecordType {
> ```

So basically this now is just a fancy builder for SQL-friendly `BeamRecordType`. That makes sense to me. I definitely like eliminating inheritance between them, and mostly deleting this class where I can't really tell the use of it. Maybe we can eventually trim even more.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/BeamSqlRecordHelper.java, line 45 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j6N7QySj72uk7bQr3:-L3j6N7QySj72uk7bQr4:bvionxo) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/BeamSqlRecordHelper.java#L45)):*
> ```Java
>    * {@link Coder} for Java type {@link Short}.
>    */
>   public static class ShortCoder extends AtomicCoder<Short> {
> ```

Yes to this: these are all `AtomicCoder`. Separately, it seems like we should just map SQL types to existing Beam coders unless we know these are a big win. Mostly, I expect they are not, reading their code. Since encoding/decoding can dominate a CPU-bound pipeline and shuffle costs are also important, we should measure this.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/SqlTypeCoder.java, line 49 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j7MTEmlcRb30WoZWk:-L3j7MTEmlcRb30WoZWl:b-k4rq3w) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/SqlTypeCoder.java#L49)):*
> ```Java
>  * <p>Relies on URN for equality and hashcode.
>  */
> public class SqlTypeCoder extends CustomCoder<Object> {
> ```

A `CustomCoder` is really a shorthand/shortcut for users, to mean "A coder that only the Java SDK understands and is serialized via Java serialization".

I had thought there was a registry from coder class to translator. I think we need such a thing. So coders are unchanged and the URN would like in the `CoderTranslator`. Basically a registry with a `Map<Class<? extends Coder>, CoderTranslator>` to see how to turn a coder into a proto and then a `Map<URN, CoderTranslator>` to know how to turn it back into a Java coder.

@tgroh didn't you do something along these lines?

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/example/BeamSqlExample.java, line 52 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j8EwqKTytaJhcWPXm:-L3j8EwqKTytaJhcWPXn:b9y13yf) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/example/BeamSqlExample.java#L52)):*
> ```Java
> 
>     //define the input row format
>     BeamRecordType type = BeamRecordSqlType
> ```

+1 nice and readable

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamJoinRel.java, line 130 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j8SlQ8tuIfJjj5kpH:-L3j8SlQ8tuIfJjj5kpI:b-clvfq) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/rel/BeamJoinRel.java#L130)):*
> ```Java
>       types.add(leftRowType.getFieldCoder(pairs.get(i).getKey()));
>     }
>     BeamRecordType extractKeyRowType = new BeamRecordType(names, types);
> ```

This reads like unusually low-level code for what it does. If `BeamRecordType` had an autovalue builder or was built from a map, you would just convert the pairs directly without these lists.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/schema/BeamTableUtils.java, line 88 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j8xC9kCx-aE0f39FU:-L3j8xC9kCx-aE0f39FV:btm1f5b) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/schema/BeamTableUtils.java#L88)):*
> ```Java
>     }
> 
>     SqlTypeName columnType = CalciteUtils.toCalciteType((SqlTypeCoder) coder);
> ```

`checkArgument(coder instanceof SqlTypeCoder)`

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/BeamAggregationTransforms.java, line 127 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j93ZQG2vs-UzmxAbs:-L3j93ZQG2vs-UzmxAbt:b-q71yv0) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/BeamAggregationTransforms.java#L127)):*
> ```Java
>         fieldTypes.add(dataType.getFieldCoder(idx));
>       }
>       return new BeamRecordType(fieldNames, fieldTypes);
> ```

Same nit here about a builder or map.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java, line 82 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j9UdO2dfg0kg06BCV:-L3j9UdO2dfg0kg06BCW:b-lcsc0x) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java#L82)):*
> ```Java
>    */
>   public static SqlTypeName getFieldCalciteType(BeamRecordType schema, int index) {
>     return toCalciteType((SqlTypeCoder) schema.getFieldCoder(index));
> ```

I see how your change causes the need for these downcasts. I think it is still good, though. What we should really be doing is converting from a `BeamRecordType` to some kind of schema all up front at once and giving good error messages.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java, line 101 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3j9nf70AlGbv_A5Hvg:-L3j9nf70AlGbv_A5Hvh:bf38mzl) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java#L101)):*
> ```Java
>    * Create an instance of {@code RelDataType} so it can be used to create a table.
>    */
>   public static RelProtoDataType toCalciteRowType(final BeamRecordType recordType) {
> ```

Same here. So I would look at where this method is called and see if you can convert the whole `BeamRecordType` at some earlier moment. No need for it in this PR, just commenting.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/text/BeamTextCSVTableIOWriter.java, line 44 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3jA9TeNrZbBQfFSvug:-L3jA9TeNrZbBQfFSvuh:b948bgf) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/meta/provider/text/BeamTextCSVTableIOWriter.java#L44)):*
> ```Java
> 
>   public BeamTextCSVTableIOWriter(BeamRecordType beamRecordType, String filePattern,
>                                   CSVFormat csvFormat) {
> ```

nit: formatting

---

*[sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamRecordSqlTypeTest.java, line 26 at r1](https://reviewable.io:443/reviews/apache/beam/4488#-L3jAHJQXITR5zNhzB2a:-L3jAHJQXITR5zNhzB2b:bc13v7j) ([raw file](https://github.com/apache/beam/blob/b96407aa84967a71caef6e88db35c603b7f0557c/sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamRecordSqlTypeTest.java#L26)):*
> ```Java
> public class BeamRecordSqlTypeTest {
> 
> //  private static final List<Integer> TYPES = ImmutableList.of(
> ```

This test seems like it can be deleted. No need to uncomment. I don't see the point of checking that `withTimestamp` builds a timestamp coder. It'll break somewhere else and doesn't test any interesting property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4488#-:-L3jB74VKqTa1g5Ke85p:b2wyhi0)*

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
This looks good to me now. And, of course, rebase :-)

**Comment by akedin** [comment]
rebased

---

Review status: 40 of 66 files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4488#-:-L44SIiiMvYFhRX7_MiI:b-hm0ll1)*

**Comment by akedin** [comment]
rebased again on top of variance refactor PR to resolve conflicts

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
tis green!

**Pull request merged**
