### PR TITLE
Cherry-pick pull requests #2907 and #2911 into release-2.0.0 branch

### PR DESCRIPTION
**Pull request by davorbonaci**
R: @dhalperi, @vikkyrk

### CODE REVIEW

**Comment by vikkyrk** [comment]
LGTM

**Comment by dhalperi** [comment]
LGTM

**Comment by dhalperi** [comment]
confirmed correct branch.

**Comment by dhalperi** [comment]
@davorbonaci please close at leisure, has been merged into release branch.

**Pull request closed without merging**
