### PR TITLE
Revert Flink 1.18 support

### PR DESCRIPTION
**Pull request by Abacn**
Revert #31062 and #31217 (partially), reason - breaks PostRelease test suite.

Tested that revert these two PR, Failed Flink validation task in PostRelease back green

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
`./gradlew :runners:flink:1.17:runQuickstartJavaFlinkLocal` now also failing: https://github.com/apache/beam/actions/runs/9068053305/job/24914468708

**Comment by Abacn** [comment]
Running a Nightly Snapshot on this branch: https://github.com/apache/beam/actions/runs/9068716106

then will run a PostRelease test to see if revert two PRs will fix PostRelease test

**Comment by Abacn** [comment]
I have cleaned up this test PR and ready for review

**Comment by shunping** [comment]
LGTM once all testing is passed.

**Comment by shunping** [comment]
Also adding @thebozzcl and @je-ik for awareness.

**Comment by shunping** [comment]
Run Python_Coverage PreCommit

**Review by je-ik — APPROVED** [review]
LGTM, though as you mentioned, this probably will not resolve the issue, but at least we can be sure.

**Comment by Abacn** [comment]
This exposes a separate issue that Flink 1.18 class (presumably the highest supported one) is used when running the Flink 1.17 QuickStart test. This makes the trat now failing in both 1.18 and 1.17 version and confused us

**Comment by Abacn** [comment]
The test entry is here: https://github.com/apache/beam/blob/master/release/src/main/groovy/quickstart-java-flinklocal.groovy

One can see the invocation only has "--runner=FlinkRunner -Pflink-runner" parameter. The first tells beam to use Flink runner, the second tells maven to activate flink related java dependencies, which pinned to "project.ext.latestFlinkVersion":

https://github.com/apache/beam/blob/c1d1bd642d152f05ff5bcf64b4630e059c681ba7/sdks/java/maven-archetypes/examples/build.gradle#L50

**Comment by je-ik** [comment]
The check passes on current master. After reverting this PR the test for Flink 1.18 pass locally. I'm not familiar with the mechanics how the test is executed, though. It uses maven, but I'm unable to get the `pom.xml` used to execute the test to compare it for differences with 1.17. Any clues anyone?

**Comment by je-ik** [comment]
https://github.com/apache/beam/pull/31328

**Pull request merged**
