### PR TITLE
[BEAM-1227] Cherrypick from #1701 to remove incubating status

### PR DESCRIPTION
**Pull request by dhalperi**
This is everything in #1701 except the version change, since the release scripts already did that.

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
I noted:

1. dataflow runner still have 0.4.0-incubating references in `runners/google-cloud-dataflow-java/src/main/resources/org/apache/beam/runners/dataflow/dataflow.properties`:

```
worker.image.batch=dataflow.gcr.io/v1beta3/beam-java-batch:beam-0.4.0-incubating
worker.image.streaming=dataflow.gcr.io/v1beta3/beam-java-streaming:beam-0.4.0-incubating
```

1. Sorter extension in the Java SDK contains `dependency-reduced-pom.xml` (generated by Maven) containing `0.5.0-incubating-SNAPSHOT` references. This file should be removed (not sure this file is in the upstream, so please ignore if it's the case).

1. Archetype resources still refer to `incubating`:

* in the examples, starter and examples-java8 archetypes: 

** `archetype-resources/pom.xml` contains `0.4.0-incubating`
** `archetype-resources/src/main/java/WordCount.java` contains `http://beam.incubator.apache.org` in the header

**Comment by jbonofre** [comment]
Oh archetype is part of #1713. Sorry about that.

**Comment by dhalperi** [comment]
Great.

* The archetype stuff will come in #1713.
* `dependency-reduced-pom.xml` is not checked in, it is a local file in your repo.

The Dataflow properties file is an issue, but one that I can handle in a separate PR. Good catch.

**Pull request closed without merging**
