### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by lostluck**
Tests run on GHA should be queued shortly.

### CODE REVIEW

**Comment by lostluck** [comment]
* PostCommit XVR GoUsingJava Dataflow - Permared  ( low priority to investigate and fix. (#30519, and earlier with #28339), likely a docker push issue)
* XVR_Direct PostCommit 3.8 - (Other python versions passing, but times out after 2 hours.)
* PostCommit Java Examples Dataflow ARM - Flaky for Java 8 only (sometimes can't find symbols like, PCollection)) #31901
* PostCommit Python Arm - Flaky #31203 (inconsistent with python versions)
* PostCommit Java IO Performance Tests - Permared #30527 (Authentication errors from the looks of it)
* PostCommit Java PVR Spark Batch - (Flaky #30512)

**Comment by tvalentyn** [comment]
https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Direct.yml?query=branch%3Amaster looks permared

**Comment by lostluck** [comment]
> https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Direct.yml?query=branch%3Amaster looks permared

Yup. That one is #30517

**Comment by tvalentyn** [comment]
Which of the errors above are a regression in 2.59.0 (if any) ?

**Comment by lostluck** [comment]
> Which of the errors above are a regression in 2.59.0 (if any) ?

None of them, given the age of the root issues that I linked.

**Pull request closed without merging**
