### PR TITLE
[BEAM-12164]  Added integration test for transaction boundaries and transaction ID ordering. Made small fixes in ordered by key integration test.

### PR DESCRIPTION
**Pull request by nancyxu123**
Added integration test for transaction boundaries and transaction ID ordering. Made small fixes in ordered by key integration test.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by nancyxu123** [comment]
Seems like Java PostCommit did not run.

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
LGTM

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
LGTM thanks @nancyxu123 !

**Comment by kennknowles** [comment]
Oops - we have test suites that pull this in but it needs to be excluded: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1/1390/

Filed https://issues.apache.org/jira/browse/BEAM-14151 and gave to Pablo since I couldn't find your account.

**Comment by pabloem** [comment]
Sent out https://github.com/apache/beam/pull/17156

**Comment by lukecwik** [comment]
Pablo, it looks like the Java PostCommit fails for some of these ITs with the direct runner, filed https://issues.apache.org/jira/browse/BEAM-14193.

**Pull request merged**
