### PR TITLE
[BEAM-11992] Run CrossLanguage ValidatesRunner tests only for Spark 2

### PR DESCRIPTION
**Pull request by iemejia**
R: @chamikaramj @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Comment by chamikaramj** [comment]
Thanks. LGTM.

Any idea why it's failing for Spark 3 ?

**Comment by iemejia** [comment]
No clue, I am not really familiar with these tests and I tried to reproduce it locally with the version previous to my change (Spark 2) and it does not pass too (in my machine).

**Comment by ibzib** [comment]
It looks like it's failing in CI because of a networking error, which is probably a problem with the test setup, I doubt it's anything to do with Spark 3 specifically.

```
Caused by: org.apache.beam.vendor.grpc.v1p26p0.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:18091
```

@iemejia I'm guessing you're missing some Python tool/package in your dev environment.

**Comment by ibzib** [comment]
LGTM, but we should leave the JIRA open until we can figure out what went wrong and run the test on both versions.

**Comment by iemejia** [comment]
Sure let's merge it to avoid the red signal and in the meantime try to find what is going on. If someone of you can do just the minor patch locally to use the Spark 3 module and see if it passes locally that would be good until I try to figure out what is wrong with my setup

**Comment by iemejia** [comment]
Oh wait why wait if i can make the CI test it for me. Opened #14255 to check Spark 3 only run

**Comment by chamikaramj** [comment]
Run Seed Job

**Comment by chamikaramj** [comment]
Run XVR_Spark PostCommit

**Comment by chamikaramj** [comment]
LGTM. Thanks.

(+1 for keeping the JIRA open till we can actually run tests for Spark 3)

**Pull request merged**
