### PR TITLE
[BEAM-6405] Let PortableValidatesRunner tests run in EMBEDDED environment

### PR DESCRIPTION
**Pull request by mxm**
We have seen repeated OOM errors on the Jenkins machines. We could potentially
reduce the number of parallel tests further but the test runtime is already
about an hour. Using the EMBEDDED environment should give us less memory
problems and faster test execution.

Note that EMBEDDED makes sense for these tests because they are purely
Java-based.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by mxm** [comment]
CC @tweise

**Comment by mxm** [comment]
Just noticed we can further decrease the build time by removing the dependency of the task on `:beam-sdks-java-container:docker`.

**Comment by tweise** [comment]
Only 2 tests fail :)

**Comment by mxm** [comment]
Had to fix the `PipelineOptions` not being passed on correctly for the `EmbeddedEnvironmentFactory`.

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tweise** [comment]
Looks like this cuts the build time by ~30% - nice!

**Comment by mxm** [comment]
```
18:29:07 Execution failed for task ':beam-runners-flink_2.11-job-server:validatesPortableRunnerBatch'.
18:29:07 > Process 'Gradle Test Executor 1' finished with non-zero exit value 137
```
Killed by OS. Wonder if that is related to #7489.

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tweise** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tweise** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Pull request merged**
