### PR TITLE
[BEAM-1871] Drop usage of Jackson/CloudObject from CoGbkResultSchema

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Note that the schema is only java serialized within the ConstructCoGbkResultFn (a DoFn) and hence the CloudObject/Jackson annotations represent dead code.

### CODE REVIEW

**Comment by lukecwik** [comment]
Kicked off: https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10058/

**Comment by lukecwik** [comment]
R: @kennknowles @dhalperi

**Comment by kennknowles** [comment]
LGTM when green. There might be a size concern.

**Comment by lukecwik** [comment]
The shouldn't be a size concern since we were always using Java serialization for the format, Jackson annotations/asCloudObject was never being invoked.

**Pull request closed without merging**
