### PR TITLE
Fix remaining tests for pandas 2 compatibility

### PR DESCRIPTION
**Pull request by caneff**
Fix the remaining tests without open questions.

1) Fix doctests. The new skips are all just new examples in Pandas 2 docs of things we were already skipping with Pandas 1.x doctests.
2) Expose set_eng_float_format, not new with Pandas 2 but has doc examples now where it didn't before so they caught that this should be exposed.
3) Skip remaining tests that have level in them that I missed earlier
4) Explicitly set numeric_only=True in the interactive runner test as I have in other tests (this test is not testing the functionality of numeric_only so it doesn't matter).

Umbrella Issue: #27221

### CODE REVIEW

**Comment by caneff** [comment]
R: @tvalentyn

**Comment by tvalentyn** [comment]
noticing some assertion errors in https://ci-beam.apache.org/job/beam_PreCommit_Python_Coverage_Commit/4145/testReport/junit/apache_beam.dataframe.pandas_doctests_test/DoctestTest/test_groupby_tests/

**Comment by tvalentyn** [comment]
Run Python_Coverage PreCommit

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
which of the 1-4 chages affected pandas 1.4 ?

**Comment by caneff** [comment]
None, I had just removed a doc test thinking it was covered by something
else but it wasn't.

**Pull request merged**
