### PR TITLE
[BEAM-14222] Fix the error of SpannerReadIT

### PR DESCRIPTION
**Pull request by libingye816**
Cloud spanner backend recently changed the table catalog field to return null instead of databaseId. Update the query in SpannerReadIT.testReadAllRecordsInDb to fix the issue.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kileys** [comment]
Failures in the post commit are unrelated. The test that was failing seems fixed, thanks!
https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/1007/#showFailuresLink

**Comment by kileys** [comment]
Run Java PreCommit

**Comment by youngoli** [comment]
Run PostCommit_Java_Dataflow

**Comment by kileys** [comment]
SpannerReadIT.testReadAllRecordsInDb is fixed. The other test failures are currently failing on post commits

**Review by kileys — APPROVED** [review]

**Comment by youngoli** [comment]
Yep, that's what I was checking for.

**Review by youngoli — APPROVED** [review]

**Comment by libingye816** [comment]
Can someone merge this PR?

**Pull request merged**
