### PR TITLE
[Spark Dataset runner] Change default storage level to Sparks respective default MEMORY_AND_DISK

### LINKED ISSUE #25737: [Task]: Spark Dataset runner should use default storage level MEMORY_AND_DISK
### What needs to happen?

Depending on the API Spark uses different defaults as storage level:
- RDD API: `MEMORY_ONLY`
- Dataset API: `MEMORY_AND_DISK`

Currently, the default storage level is set to `MEMORY_ONLY` for all runners. However, the default storage level of the Dataset runner should match Sparks default `MEMORY_AND_DISK`.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by mosche**
Change the default storage level to the respective default of Spark's Dataset API (`MEMORY_AND_DISK` ) rather than using the default of the RDD API / the SparkRunner (`MEMORY_ONLY`).

Closes #25737

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
Run Java PreCommit

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Pull request merged**
