### PR TITLE
[BEAM-13983] changed file name from sklearn_loader to sklearn_inference

### PR DESCRIPTION
**Pull request by ryanthompson591**
changed file name from sklearn_loader to sklearn_inference

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by ryanthompson591** [comment]
R: @yeandy 
R: @TheNeuralBit

**Comment by yeandy** [comment]
We have plans to change `pytorch` to `pytorch_inference`

**Review by TheNeuralBit — APPROVED** [review]
I would advocate for `sklearn` and `pytorch`, as `inference` is already in the namespace, but I don't want to block this on that bikeshed

**Comment by ryanthompson591** [comment]
@TheNeuralBit Originally, I felt the same. sklearn and pytorch, let me know if I'm wrong.  The problem I was seeing was name collision.

For example if someone had the following imports.

import sklearn
from apache_beam.ml.inference import sklearn
there would be a name collision. Problem is that python does raise an exception here, but simply has the last import stand. So this will cause our users debugging head aches.

Instead they would need to do something like.

import sklearn
import apache_beam.ml.inference.sklearn as apache_sklearn  (or sklearn_inference or whatever)

Our feeling is that users will often also import sklearn to use some of the libraries there.  So in order to avoid error, we plan to use framework_inference as the name.  I liked loader and andy liked inference.  So we flipped a coin.

**Comment by TheNeuralBit** [comment]
Thanks for the explanation! That makes sense, I didn't realize that Python wouldn't error in the event of a collision.

I might avoid the duplication of "inference" and just have an ml package with {module}_inference then, e.g. `apache_beam.ml.sklearn_inference`

**Comment by yeandy** [comment]
I'm ok with `apache_beam.ml.sklearn_inference` (or keeping as is). But I'm wondering if, in the future, there will be other ML related apis --not related to RunInference -- that we would develop. For example, we would want to have `ml/inference` and `ml/training` to minimize confusion. But we can refactor if/when that arises.

**Pull request merged**
