### PR TITLE
Remove artificial timeout in FirestoreV1IT, Dataflow runner is very slow

### PR DESCRIPTION
**Pull request by yixiaoshen**
Dataflow runner takes much longer to run any IT test, the artificial timeout added in FirestoreV1IT makes the test flaky, other IT tests don't set this timeout and many of them can run >10 minutes on Dataflow runner.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by yixiaoshen** [comment]
Run PostCommit_Java_Dataflow

**Comment by yixiaoshen** [comment]
Run PostCommit_Java_DataflowV2

**Comment by yixiaoshen** [comment]
R: @ahmedabu98

**Comment by ahmedabu98** [comment]
LGTM
R: @robertwb

**Review by ahmedabu98 — APPROVED** [review]
LGTM
R: @robertwb

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Firestore tests passed for both Dataflow v1 and v1 in the above runs (failures are unrelated) so we can merge when Java PreCommit passes.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Pull request merged**
