### PR TITLE
[BEAM-1348] Add Runner API constructs to ProcessBundleDescriptor.

### PR DESCRIPTION
**Pull request by lukecwik**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
This is towards removing the Fn API constructs once code has been migrated.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @vikkyrk 
CC: @kennknowles

**Comment by dhalperi** [comment]
retest this please

(testing jenkins integration)

**Comment by lukecwik** [comment]
retest this please

**Comment by vikkyrk** [comment]
LGTM once tests pass.

**Comment by lukecwik** [comment]
retest this please

**Comment by lukecwik** [comment]
retest this please

**Pull request merged**
