### PR TITLE
[BEAM-7389] Generate notebook for FlatMap

### PR DESCRIPTION
**Pull request by davidcavazos**
Generates the notebook for `FlatMap`.

R: @aaltay [script/code]
R: @rosetn [writing/formatting]

**FlatMap**:
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/9584/documentation/transforms/python/elementwise/flatmap/index.html
Notebook: https://colab.research.google.com/github/davidcavazos/beam/blob/notebook-flatmap/examples/notebooks/documentation/transforms/python/element-wise/flatmap-py.ipynb

*[updated] Filter*:
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/9584/documentation/transforms/python/elementwise/filter/index.html
Notebook: https://colab.research.google.com/github/davidcavazos/beam/blob/notebook-flatmap/examples/notebooks/documentation/transforms/python/element-wise/filter-py.ipynb

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by davidcavazos** [comment]
> Is there any major difference between the website content and the notebook here? I glanced over and it looks good.
> 
> It is hard to see differences in notebook files and if there is a major difference please let me know and I can take a more careful look.

There should be no major differences between them. The docs are the source of truth and the notebook is an "executable clone" of the docs. There are slight differences:

* The notebooks import sections like the setup instructions
* The notebooks hide the "outputs" of the code blocks as well as the "Run code now" button that is present in the docs
* The notebooks add a button to "View the docs" at the top and at the bottom.

Other than that, they should be exactly the same.

**Comment by rosetn** [comment]
Are you able to change the Beam site, Pydoc, and source code links to the "button" class? And left align (these docs read in an F-pattern)? Maybe make the images larger--40x40?

Everything else LGTM

**Comment by davidcavazos** [comment]
> Are you able to change the Beam site, Pydoc, and source code links to the "button" class? And left align (these docs read in an F-pattern)? Maybe make the images larger--40x40?
> 
> Everything else LGTM

Do you mean in the notebooks? Unfortunately, the Markdown in Colab does not support arbitrary CSS styles, so I can make the images larger but not apply the button styles. The workaround was putting them inside a `<table>` and that made the borders gray. I could also align all the buttons to the left.

**Comment by davidcavazos** [comment]
Updated FlatMap and Filter as well, I included both links in the description at the top.

**Pull request merged**
