### PR TITLE
Move Runner API protos to portability/runners/api

### PR DESCRIPTION
**Pull request by charlesccychen**
This fixes a circular import issue between transforms/ and runners/.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay 
CC: @chamikaramj

**Comment by charlesccychen** [comment]
R: @chamikaramj 
CC: @aaltay, @robertwb

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Comment by robertwb** [comment]
Don't check in the auto-generated files; they're now generated in setup.py.

**Comment by charlesccychen** [comment]
Robert: thanks, Cham pointed out this mistake to me but I haven't corrected it yet.  Will do before final review and merge.

**Comment by charlesccychen** [comment]
Thanks, PTAL.  I have removed the generated proto files and tests have passed: https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/12223/

**Comment by chamikaramj** [comment]
LGTM. Merging.

**Comment by robertwb** [comment]
LGTM, modulo I would have put this in portability/api (the runners package isn't really needed).

**Pull request closed without merging**
