### PR TITLE
[BEAM-11941] Upgrade Flink runner to Flink version 1.12.2

### PR DESCRIPTION
**Pull request by iemejia**
R: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by ibzib** [comment]
@iemejia It looks like `testMergingCustomWindowsWithoutCustomWindowTypes` is a new test that should probably just be sickbayed: BEAM-11887

**Comment by iemejia** [comment]
Ah ok I was not aware you are right it is broken since some time ago.
https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/
So we should be then good to go.

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by iemejia** [comment]
Thanks @ibzib !

**Pull request merged**
