### PR TITLE
Go SDK: Update memory file system to return an io.ReadSeekCloser.

### PR DESCRIPTION
**Pull request by gonzojive**
When writing tests for spittable DoFns that need to seek within files, it's
helpful to use memfs. Before this change, memfs returned an io.ReadCloser that
did not implement io.Seeker.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by gonzojive** [comment]
I can add a test if desired.

**Comment by jrmccluskey** [comment]
I would definitely like to see a unit test to demonstrate the functionality you're adding.

**Comment by jrmccluskey** [comment]
Having thought about it more, a runnable example demonstrating the usage you're proposing would also be really helpful (totally up to you.)

**Comment by gonzojive** [comment]
I added tests and revised the implementation. I noticed there is another gotcha with memfs: open readers don't see the results of writers. I addressed this in the code as well and added tests for it (that break before the commits).

> Having thought about it more, a runnable example demonstrating the usage you're proposing would also be really helpful (totally up to you.)

Done. Please see the updated implementation of TextIO that uses Seek to dramatically reduce the total # of read bytes.

When making a change like that in TextIO, it's helpful if memfs behaves very similarly to a local file system and also implements io.Seeker.

**Review by jrmccluskey — APPROVED** [review]
LGTM, going to loop in @lostluck for a second set of eyes.

**Comment by gonzojive** [comment]
One idea is to update the interface of the memfa package to expose bytes
read rather than copying a lot of the memfs implementation into the TextIO
test.

**Comment by jrmccluskey** [comment]
I'm cool with merging this once the branch conflicts are resolved

**Pull request closed without merging**
