### PR TITLE
Add Storage API streaming max retries parameter for BigQueryOptions

### LINKED ISSUE #25382: [Feature Request]: Making number of retries configurable in BigQuery Storage Write connector
### What would you like to happen?

Hi,
Is it possible to make this instance of retry manager configurable?
https://github.com/apache/beam/blob/f5020e7ac2bdd3363619aafbf257f2ebf8e3fe2b/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java#L658
Retrying the request to BQ Storage Write API a thousand times seems to be a bit too generous, especially with some nonrecoverable errors, but I guess, it may have its justification in some cases. However, in streaming mode, it clogs the pipeline for an unreasonable amount of time. Maybe clients should be allowed to configure this value?

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Amar3tto**
Fixes #25382

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
R: @Abacn

**Comment by Abacn** [comment]
multiple band-aid fix has made the retry behavior more complicated. Specifically, for batch job, the max retry number is not longer to be 500

#26503 - fail the work item after retry 5 times, in StorageApiWriteUnshardedRecords, this is for batch

#31253 - retry 10 times (instead of 5) for quota error

and this change works for streaming (which uses StorageApiWritesShardedRecords or StorageApiWriteRecordsInconsistent)

Let's update the description mention that this is only for streaming, or update to make it also work with batch (but need more care, batch and streaming currently have different default)

**Review by Abacn — COMMENTED** [review]
thanks.

When we come back to the batch pipeline retry it's good to not introducing another pipeline option. How about keep `getStorageWriteApiMaxRetries` naming and in the description noting that currently it is only applicable for streaming pipeline?

Or noting in javadoc that this opition is experimental and could change?

**Comment by Amar3tto** [comment]
> thanks.
> 
> When we come back to the batch pipeline retry it's good to not introducing another pipeline option. How about keep `getStorageWriteApiMaxRetries` naming and in the description noting that currently it is only applicable for streaming pipeline?
> 
> Or noting in javadoc that this opition is experimental and could change?

Agree, fixed

**Review by Abacn — APPROVED** [review]

**Pull request merged**
