### PR TITLE
[release-2.17.0][BEAM-8858] sdks/java/extensions/sql to declare used-but-undeclared dependencies

### PR DESCRIPTION
**Pull request by iemejia**
R: @Ardagan 
CC: @suztomo @kennknowles

### CODE REVIEW

**Comment by iemejia** [comment]
Note: We should ignore the "Run SQL PreCommit" error. that CI task was not part of 2.17.0

**Comment by iemejia** [comment]
Run SQL PostCommit

**Comment by Ardagan** [comment]
Run SQL PreCommit

**Comment by suztomo** [comment]
@Ardagan iemejia commented expected SQL PreCommit failures. https://github.com/apache/beam/pull/10351#issuecomment-564573190

**Comment by Ardagan** [comment]
Run SQL Postcommit

**Comment by kennknowles** [comment]
The SQL precommit did not "fail". It just does not exist on the branch. On this branch, it is part of the Java precommit. But since Jenkins configs come from master, not the branch, the exclusion is still in place so the Java precommit doesn't run.

**Comment by kennknowles** [comment]
run java precommit

**Pull request merged**
