### PR TITLE
[BEAM-4375] Replaces usage of JUnit runners that do not work well with Gradle

### PR DESCRIPTION
**Pull request by jkff**
RunWith(Enclosed.class) causes tests to be skipped https://github.com/gradle/gradle/issues/2985 (in this PR I also fixed MetricsTests which was actually failing).
RunWith(Suite.class) causes them to be duplicated https://github.com/gradle/gradle/issues/5484 .

Additionally, fixed :beam-runners-direct-java:validatesRunner to actually run those tests too - it had an empty classpath and didn't run anything.

R: @swegner

### CODE REVIEW

**Comment by swegner** [comment]
Run Run Flink ValidatesRunner

**Comment by swegner** [comment]
Run Flink ValidatesRunner

**Comment by swegner** [comment]
Run Dataflow ValidatesRunner

**Comment by swegner** [comment]
Yikes, good catch, and thanks for putting together a fix.

In general looks good to me. I checked to verify there are no other references to `Enclosed.class` in the codebase (`git grep Enclosed`). I kicked off Flink + Dataflow ValidatesRunner tests so we can verify that the tests actually get run.

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
Ugh, forgot the debugging leftover where I was ensuring that ValidatesRunner tests run at all by throwing an exception. Now they do, and the exception failed Flink ValidatesRunner, WAI.

**Comment by jkff** [comment]
Run Flink ValidatesRunner

**Comment by jkff** [comment]
The only failing tests are the archetype tests unrelated to this PR, which fail randomly. Merging.

**Comment by swegner** [comment]
Thanks for this. I can see from the [Gradle build scan](https://scans.gradle.com/s/zehazergdsv7q) that tests such as `	ParDoTest$TimerTests` are now being run.

**Pull request merged**
