### PR TITLE
Simplify MoreFutures.supplyAsync and MoreFutures.runAsync using a wrapper instead of chained stages and multiple completions.

### LINKED ISSUE #29926: [Bug]: FileIO: lack of timeouts may cause the pipeline to get stuck indefinitely
### What happened?

A java pipeline running on Dataflow using Beam 2.47 (but the latest 2.52 is affected by the same issue) went into an unrecoverable state, with workers being stuck for at least 4 days with the following stack trace:
```
  java.base@11.0.9/jdk.internal.misc.Unsafe.park(Native Method)
  java.base@11.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
  java.base@11.0.9/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
  java.base@11.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
  java.base@11.0.9/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
  java.base@11.0.9/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
  app//org.apache.beam.sdk.util.MoreFutures.get(MoreFutures.java:61)
  app//org.apache.beam.sdk.io.WriteFiles$WriteShardsIntoTempFilesFn.finishBundle(WriteFiles.java:1027)
  app//org.apache.beam.sdk.io.WriteFiles$WriteShardsIntoTempFilesFn$DoFnInvoker.invokeFinishBundle(Unknown Source)
  app//org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.finishBundle(SimpleDoFnRunner.java:221)
  app//org.apache.beam.runners.dataflow.worker.SimpleParDoFn.finishBundle(SimpleParDoFn.java:433)
  app//org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.finish(ParDoOperation.java:56)
  app//org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:94)
  app//org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.process(StreamingDataflowWorker.java:1401)
  app//org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker.access$800(StreamingDataflowWorker.java:153)
  app//org.apache.beam.runners.dataflow.worker.StreamingDataflowWorker$4.run(StreamingDataflowWorker.java:1043)
  app//org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutor.lambda$executeLockHeld$0(BoundedQueueExecutor.java:133)
  app//org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutor$$Lambda$251/0x00000008005e7840.run(Unknown Source)
  java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  java.base@11.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  java.base@11.0.9/java.lang.Thread.run(Thread.java:834)
```
The source is [here](https://github.com/apache/beam/blob/0b1b07398cf139ee0824a75c6ac1c9d3b49616ce/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L1007): on FinishBundle, `WriteFiles` waits for all futures that close writers to complete, but they never do. 

`writer.cleanup` from [here](https://github.com/apache/beam/blob/0b1b07398cf139ee0824a75c6ac1c9d3b49616ce/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L1018) produces a log message, which we didn't observe in this case, so the futures seemed to be stuck on `writer.close`. It's unclear why (possibly, some network issues, or other issues with Cloud Storage, which was the target file system), but I think Beam SDK should implement a timeout here: if a writer can't be closed within reasonable time, it should fail and the bundle should be re-processed.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by scwhittle**
This is clearer how it interacts with ForkJoinPool execution as there are not separate completion stages.

I was unable to reproduce observed stuckness in pipeline where runAsync scheduled tasks appear not to have completed on forkjoinpool and the pool workers appears idle. I am wondering if this could be a possible cause because with the existing code, the futures on the fork join pool are not being directly joined and thus perhaps not explicilty tied to the async work. This may affect if the tasks not being pushed into execution.  The common pool used is not in asyncMode and ForkJoinExecutor indicates it is safer for non-joining use if asyncMode is set.

Fix #29926

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @Abacn

**Comment by scwhittle** [comment]
Failures appear unrelated

**Comment by scwhittle** [comment]
Run Java PreCommit

**Review by Abacn — APPROVED** [review]
thank you!

**Comment by scwhittle** [comment]
Run Java PreCommit

**Pull request merged**
