### PR TITLE
Minor: Make IOTypeHints a real NamedTuple

### PR DESCRIPTION
**Pull request by TheNeuralBit**
GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by udim — APPROVED** [review]
LGTM (2 failures but I don't think they're related).
Out of curiosity, what prompted this change?

**Comment by TheNeuralBit** [comment]
> Out of curiosity, what prompted this change?

It's just a silly cleanup that I noticed while working on some adjacent code.

**Comment by TheNeuralBit** [comment]
Run Python_PVR_Flink PreCommit

**Comment by TheNeuralBit** [comment]
PythonDocs issue is BEAM-14172

**Pull request merged**
