### PR TITLE
[BEAM-10785] Change RowAsDictJsonCoder to not ensure ASCII while encoding

### LINKED ISSUE #20532: Support for coder argument in WriteToBigQuery
When using WriteToBigQuery to transfer data to BigQuery, non-ascii characters are replaced with replacement characters.

This was due to the RowAsDictJsonCoder being set as the coder for the BigQueryBatchFileLoads called inside WriteToBigQuery.

I want to add coder to the argument of WriteToBigQuery so that I can set a coder other than RowAsDictJsonCoder.

If no problem, I will create a Pull Request next weekend.

Imported from Jira [BEAM-10785](https://issues.apache.org/jira/browse/BEAM-10785). Original Jira may contain additional context.
Reported by: chanyou.

### PR DESCRIPTION
**Pull request by harrydrippin**
This PR fixes BEAM-10785 (#20532 on Github) by an alternative way: Adding `ensure_ascii=False` to `json.dumps` on `RowAsDictJsonCoder`.

The original way for fixing this issue was enabling `coder` argument on WriteToBigQuery and passing it downstream, but other way was discussed on #17518.

Resolves #20532.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by harrydrippin** [comment]
R: @aaltay, @pabloem

**Comment by aaltay** [comment]
R: @johnjcasey

**Comment by johnjcasey** [comment]
R: @pabloem as original reviewer

**Comment by johnjcasey** [comment]
This looks good to me, but Pablo I think you already have context

**Comment by pabloem** [comment]
ah yes lgtm!

**Comment by pabloem** [comment]
merging as tests already passed in previous commit

**Pull request merged**
