### PR TITLE
Define the projectId in the SpannerIO Read Test (utest, not itest)

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
It fixes issue on `SpannerIO` test (not itest) saying the `projectId` is not defined and precondition fails.

R: @kennknowles 
CC: @mairbek

### CODE REVIEW

**Comment by jbonofre** [comment]
For the record, this is the exception I have on my machine on the read test:

```
Caused by: java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:238)
        at com.google.cloud.spanner.SpannerOptions.<init>(SpannerOptions.java:81)
        at com.google.cloud.spanner.SpannerOptions.<init>(SpannerOptions.java:43)
        at com.google.cloud.spanner.SpannerOptions$Builder.build(SpannerOptions.java:180)
        at org.apache.beam.sdk.io.gcp.spanner.SpannerConfig.buildSpannerOptions(SpannerConfig.java:60)
        at org.apache.beam.sdk.io.gcp.spanner.AbstractSpannerFn.setup(AbstractSpannerFn.java:39)
```

**Comment by mairbek** [comment]
lgtm

**Comment by jbonofre** [comment]
Thanks @mairbek 

@kennknowles I'm waiting your approval before merging. Thanks !

**Comment by kennknowles** [comment]
LGTM. Thanks for checking it out @mairbek since I'm new to this code.

**Comment by jbonofre** [comment]
Thanks, I'm merging.

**Pull request closed without merging**
