### PR TITLE
Exclude javadocs for experimental SparkStructuredStreamingRunner

### PR DESCRIPTION
**Pull request by mosche**
While still experimental and in a "pre alpha" phase with lots of changes to expect, it's probably not a good idea to publish Javadocs for the `SparkStructuredStreamingRunner` yet. Likely it will just confuse users.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @echauchot 
R: @aromanenko-dev 
(just a tiny gradle config)

**Review by aromanenko-dev — CHANGES_REQUESTED** [review]
I'm afraid that it may be even more confusing to stop publishing these javadocs while they are available since this runner was added and there is already a user documentation on Beam website. Actually, we mention that this runner is still experimental on https://beam.apache.org/documentation/runners/spark/ page.

Instead, we may want to annotate all `org.apache.beam.runners.spark.structuredstreaming.*` classes with `@Exeremental`.

**Comment by mosche** [comment]
IMHO, with almost absolute certainty, you can count on the fact that every single user looking for Spark runner related Javadocs isn't looking for the ones of the SparkStructuredStreamingRunner. Also, the RDD runner is at least conscious about which Javadocs get published. All translation classes, the user should never interact with, are explicitly excluded and hidden there.

The other side to this is the pure amount of breaking changes to expect... most critical, expecting a new name (and package structure) for the runner. IMHO, regardless of the status quo, having these Javadocs there is by far more harmful than helpful.

**Comment by aromanenko-dev** [comment]
I'd agree to not have these Javadocs if they have not been published yet. For now, until we have these classes available for users (even if we are 99% sure that they mostly not used), I'd prefer to keep them for a sake of integrality since Beam  still provide them.

> IMHO, with almost absolute certainty, you can count on the fact that every single user looking for Spark runner related Javadocs isn't looking for the ones of the SparkStructuredStreamingRunner. 

Agree but it also means that they very likely won't be confused or mislead with that =) To annotate them `@Experimental`, as I proposed before, will make it easier to change the naming or other API changes in the future.

**Comment by mosche** [comment]
> Agree but it also means that they very likely won't be confused or mislead with that =)

Actually, isn't it the opposite? Users are looking for Javadocs of the RDD Spark runner but find themselves having to Javadocs

**Comment by mosche** [comment]
ok, not worth having a discussion on this ... closing it

**Pull request closed without merging**
