### PR TITLE
[BEAM-3412] Updates BigTable client version to 1.0

### PR DESCRIPTION
**Pull request by chamikaramj**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by lukecwik** [comment]
Perform the same change in the gradle build file.

Note that updating bumps up the version numbers for gRPC and protobuf. Other then the bigtable version bump, did any of the transitive dependencies version change?

**Comment by sduskis** [comment]
I did a diff before and after this change:

```
87,88c87,88
< [INFO] +- com.google.cloud.bigtable:bigtable-protos:jar:1.0.0-pre3:compile
< [INFO] +- com.google.cloud.bigtable:bigtable-client-core:jar:1.0.0-pre3:compile
---
> [INFO] +- com.google.cloud.bigtable:bigtable-protos:jar:1.0.0:compile
> [INFO] +- com.google.cloud.bigtable:bigtable-client-core:jar:1.0.0:compile
90a91,92
> [INFO] |  +- io.opencensus:opencensus-contrib-grpc-util:jar:0.7.0:compile
> [INFO] |  |  \- io.opencensus:opencensus-api:jar:0.7.0:compile
```

*Note*: this doesn't change the version of grpc.  The version of grpc used by Beam remains at 1.2.0, where as Cloud Bigtable is on 1.8.0.

**Comment by chamikaramj** [comment]
Solomon, this change causes BigTable connector post-submit tests to fail. Looks like we need to update dependencies (which results in other issues) or to shard dependencies away. See https://issues.apache.org/jira/browse/BEAM-3387

I filed https://issues.apache.org/jira/browse/BEAM-3412 for this.

**Comment by chamikaramj** [comment]
Closing this in favor of a solution that fixes the dependency issue.

**Pull request closed without merging**
