### PR TITLE
[BEAM-8696] sdks/java: upgrade protobuf to 3.11.1

### PR DESCRIPTION
**Pull request by suztomo**
sdks/java: upgrade protobuf to 3.11.1.

### beam-sdks-java-io-google-cloud-platform
- before: https://gist.github.com/suztomo/2a9d5e9a62b3364764bc1c9a8868449a
- after: https://gist.github.com/suztomo/d39fc30121e87365c716edc22cffa529 (same as above)

### beam-sdks-java-core
- before: https://gist.github.com/suztomo/f5ae20da3ea4e07442bfa8c992b04ec6
- after: https://gist.github.com/suztomo/bb5802bc9ea411fbd08da6b462a52b0c (same as above)

### beam-sdks-java-extensions-protobuf
- before: https://gist.github.com/suztomo/ef0ba4ac0d23356b0c243f0a48cd63a9
- after: https://gist.github.com/suztomo/ce6f4759fe2a11ef305279013ef2506a (same as above)

### beam-sdks-java-extensions-sql-zetasql
Linkage Checker did not work for beam-sdks-java-extensions-sql-zetasql. Filed https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1087

### beam-vendor-calcite-1_20_0
It did not find artifact "beam-vendor-calcite-1_20_0" https://gist.github.com/suztomo/1f01efd8665d82d9c740b36e65a44ce2

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by suztomo** [comment]
Run Java PostCommit

**Comment by lukecwik** [comment]
You'll want to check the linkage of all beam modules that depend on Guava (and/or transitively depend on Guava). It won't be just the GCP IO module.

**Comment by suztomo** [comment]
(I assume you meant protobuf, not guava) Yes, I'll check them.

```
suztomo@suxtomo24:~/beam6$ find . -name 'build.gradle' |xargs grep -ir library.java.protobuf
./sdks/java/core/build.gradle:      include(dependency(library.java.protobuf_java))
./sdks/java/core/build.gradle:  compile library.java.protobuf_java
./sdks/java/io/google-cloud-platform/build.gradle:  compile library.java.protobuf_java
./sdks/java/extensions/protobuf/build.gradle:  compile library.java.protobuf_java
./sdks/java/extensions/sql/zetasql/build.gradle:  compile library.java.protobuf_java
./sdks/java/extensions/sql/zetasql/build.gradle:  compile library.java.protobuf_java_util
./vendor/calcite-1_20_0/build.gradle:                library.java.protobuf_java,
suztomo@suxtomo24:~/beam6$ 
```

**Comment by lukecwik** [comment]
> (I assume you meant protobuf, not guava) Yes, I'll check them tomorrow.
> 
> ```
> suztomo@suxtomo24:~/beam6$ find . -name 'build.gradle' |xargs grep -ir library.java.protobuf
> ./sdks/java/core/build.gradle:      include(dependency(library.java.protobuf_java))
> ./sdks/java/core/build.gradle:  compile library.java.protobuf_java
> ./sdks/java/io/google-cloud-platform/build.gradle:  compile library.java.protobuf_java
> ./sdks/java/extensions/protobuf/build.gradle:  compile library.java.protobuf_java
> ./sdks/java/extensions/sql/zetasql/build.gradle:  compile library.java.protobuf_java
> ./sdks/java/extensions/sql/zetasql/build.gradle:  compile library.java.protobuf_java_util
> ./vendor/calcite-1_20_0/build.gradle:                library.java.protobuf_java,
> suztomo@suxtomo24:~/beam6$ 
> ```

Yes, protobuf, sorry for the confusion.

**Comment by suztomo** [comment]
Run SQL PostCommit

**Comment by suztomo** [comment]
R: @lukecwik 

Added Linkage Check result in the description of this PR (No change)

**Comment by suztomo** [comment]
Run Dataflow ValidatesRunner

**Comment by suztomo** [comment]
Jenkins does not trigger the checks.

**Pull request merged**
