### PR TITLE
[SQL] Pubsub to BigQuery e2e integration test

### PR DESCRIPTION
**Pull request by akedin**
Select from a Pubsub topic and insert into a BigQuery table.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
R: @kennknowles @apilloud @amaliujia

**Comment by akedin** [comment]
run java precommit

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
org.apache.beam.runners.direct.portable.ReferenceRunnerTest.pipelineExecution

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
elastic search failed

**Comment by akedin** [comment]
run java postcommit

**Comment by akedin** [comment]
green

**Comment by kennknowles** [comment]
LGTM

**Pull request merged**
