### PR TITLE
[25119] Change test-infra Kafka outside service to NodePort

### LINKED ISSUE #25119: [Task]: Refactor kubernetes kafka External load balancer dependency in tests
### What needs to happen?

This task explores and refactors [.test-infra/kubernetes/kafka-cluster](.test-infra/kubernetes/kafka-cluster) use of type LoadBalancer to NodePort.  This task may relate to #19465.

Below are measures of ready and done.

## Ready

- [ ] Inventory tests that depend on [.test-infra/kubernetes/kafka-cluster](.test-infra/kubernetes/kafka-cluster) kubernetes Service
- [ ] Inventory .test-infra containing scripts that execute `kubectl get svc <service> '-ojsonpath={.status.loadBalancer.ingress[*].ip}'`
- [ ] Inventory GKE cluster network and kafka related tests Dataflow jobs network provisioning

## Done

- [ ] Refactor [.test-infra/kubernetes/kafka-cluster](.test-infra/kubernetes/kafka-cluster) to kubernetes Service NodePort
- [ ] Refactor `kubectl get svc` scripts to query NodePort IP and port
- [ ] Refactor Google Cloud virtual private cloud (VPC) network usage, if needed, based on network provisioning findings

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by damondouglas**
This PR closes #25119 and addresses #19465 by:
1. Change .test-infra/kubernetes/kafka-cluster/04-outside-services from LoadBalancer to NodePort
2. Refactor .test-infra/kubernetes/kafka-cluster/05-kafka/10broker-config.yml to query `OUTSIDE_HOST` from k8s node `InternalIP` and `OUTSIDE_PORT` to query `outside-${KAFKA_BROKER_ID}`'s NodePort
3. Added `nodeIPAddress` and `nodePort` methods to .test-infra/jenkins/Kubernetes.groovy and cooresponding .test-infra/kubernetes/kubernetes.sh to enable Node InternalIP and NodePort querying within a jenkins job context
4. Refactor the following with `usePublicIps=false`
    - .test-infra/jenkins/job_PerformanceTests_xlang_KafkaIO_Python.groovy
    - .test-infra/jenkins/job_PerformanceTests_KafkaIO_IT.groovy
5. terraform code to validate and provision Google Cloud networking requirements to support `usePublicIps=false` (Note: I already executed the terraform code, per personal communication, on apache-beam-testing GCP project)

I was unable to test end-to-end the new workflow from jenkins job creation to seeing a Dataflow Job executing successfully in my own Google Cloud environment.  However, I was able to validate:
1. Using a private IP compute engine instance in the same GCP network, https://kafka.apache.org/quickstart worked using the kubernetes cluster's node InternalIP and NodePort as the `--bootstrap-server`
2. Spinning up .test-infra/dockerized-jenkins and seeding `job_PerformanceTests_xlang_KafkaIO_Python.groovy` from github.com/damondouglas/beam from branch `25119-fix-test-infra-kafka-service` built the test job using the queried kubernetes Node InternalIP and NodePort as the bootstrap_server arguments

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~Update `CHANGES.md` with noteworthy changes.~
 - ~If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by Abacn** [comment]
adter a seedjob looks like it still trying to access to loadBalancer somewhere (which is replaced to NodePort in this PR)
```
eval 'kubectl --kubeconfig=/home/jenkins/jenkins-slave/workspace/beam_PerformanceTests_xlang_KafkaIO_Python/config-beam-performancetests-xlang-kafkaio-python-37 --namespace=beam-performancetests-xlang-kafkaio-python-37 get svc outside-0 -ojsonpath='\''{.status.loadBalancer.ingress[0].ip}'\'''
```

**Comment by Abacn** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by damondouglas** [comment]
@Abacn is the jenkins job seeding from https://github.com/damondouglas/beam/tree/25119-fix-test-infra-kafka-service?

**Comment by Abacn** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Java KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Java KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Java KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Python xlang KafkaIO Performance Test

**Comment by damondouglas** [comment]
@Abacn I set this to draft to take a break and focus on other projects.  The job set the parameters like this:  kafkaBootstrapServerAddresses=$NODE_IP_0:32401,$NODE_IP_1:32402,$NODE_IP_2:32403","--kafkaTopic=beam-sdf","--readTimeout=1500","--numWorkers=5","--autoscalingAlgorithm=NONE","--experiments=use_runner_v2,use_unified_****" 

I was expecting instead of $NODE_IP_<some number> to be an actual IP address.

**Comment by damondouglas** [comment]
Run Java KafkaIO Performance Test

**Comment by damondouglas** [comment]
Run Python xlang KafkaIO Performance Test

**Pull request closed without merging**
