### PR TITLE
Enabling phrase triggering of Python PreCommit

### PR DESCRIPTION
**Pull request by pabloem**
r: @jasonkuster 
cc: @kennknowles

### CODE REVIEW

**Comment by kennknowles** [comment]
It should also automatically trigger on any pull request, and then "Retest this please" will trigger it.

**Comment by pabloem** [comment]
Yes, but wouldn't that also trigger Java tests? I'd like to be able to run only the Python PreCommit tests if those are the ones I care about. Does that seem reasonable?

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by pabloem** [comment]
Retest this please.

**Comment by pabloem** [comment]
Retest this please.

**Comment by jasonkuster** [comment]
Agree with your justification Pablo -- LGTM

**Comment by pabloem** [comment]
Can you merge please? - Thanks

**Comment by kennknowles** [comment]
Yea LGTM

**Pull request merged**
