### PR TITLE
[BEAM-9066] Add javax.annotation-api dependency.

### PR DESCRIPTION
**Pull request by tysonjh**
As of jdk-9 only non-EE modules are present by default including those
like the javax.annotation.Generated annotations which are required for
generated code with grpc et al. Adding this as a compileOnly dependency
prepares Beam for Java 11.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Samza | Spark
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by kennknowles** [comment]
Most important is noting the license, which is the same as JDK stdlib stuff: GPL 2.0 with classpath exception. (even with source retention)

**Comment by tysonjh** [comment]
> Most important is noting the license, which is the same as JDK stdlib stuff: GPL 2.0 with classpath exception. (even with source retention best to be clear and safe)

I found that the annotation is under both CDDL 1.1 and GPL 2.0 so I updated the comments accordingly. Could you review this please? I'd like to be sure it is correct.

This PR doesn't fix the linked issue but is required AFAICT for building Beam locally with Java 11. I'm not sure exactly how the precommit phase is set up to do this so I need to investigate before merging this.

**Comment by tysonjh** [comment]
> > Most important is noting the license, which is the same as JDK stdlib stuff: GPL 2.0 with classpath exception. (even with source retention best to be clear and safe)
> 
> I found that the annotation is under both CDDL 1.1 and GPL 2.0 so I updated the comments accordingly. Could you review this please? I'd like to be sure it is correct.
> 
> This PR doesn't fix the linked issue but is required AFAICT for building Beam locally with Java 11. I'm not sure exactly how the precommit phase is set up to do this so I need to investigate before merging this.

The postcommit phase builds the direct runner with Java 8 and runs the validatesRunner task with Java 11: https://github.com/apache/beam/blob/master/.test-infra/jenkins/job_PostCommit_Java_ValidatesRunner_Direct_Java11.groovy

I'll try this out.

**Comment by kennknowles** [comment]
Neither CDDL nor GPL 2.0 would be allowable.

But I believe [this library's license](https://github.com/javaee/javax.annotation/blob/83417807ad402ee1022c0307208d4510c80c68b6/LICENSE#L743) is [GPL 2.0 with the classpath exception](https://openjdk.java.net/legal/gplv2+ce.html), which is noted as an exception under the [Category X licenses](https://www.apache.org/legal/resolved.html#category-x).

**Comment by kennknowles** [comment]
Ah, I'm wrong. [CDDL is Category B](https://www.apache.org/legal/resolved.html#category-b)

**Comment by tysonjh** [comment]
> Ah, I'm wrong. [CDDL is Category B](https://www.apache.org/legal/resolved.html#category-b)

Should I update the comments to be more clear? Perhaps having it mention GPL 2.0 and the prohibited link is confusing and I should just reference CDDL?

**Comment by tysonjh** [comment]
retest this please

**Comment by kennknowles** [comment]
TBH I am not sure. I believe that GPL + classpath exception is standard and probably best. It is what allows all Java users to make Java programs that are not GPL.

**Comment by tysonjh** [comment]
> TBH I am not sure. I believe that GPL + classpath exception is standard and probably best. It is what allows all Java users to make Java programs that are not GPL.

I went with the GPL with Classpath Exception and removed CDDL and updated the links to be more explicit.

**Comment by tysonjh** [comment]
retest this please

**Comment by kennknowles** [comment]
Run SQL_Java11 PreCommit

**Comment by kennknowles** [comment]
It looks like a hard failure unrelated to your change, and yet it is green on master.

**Comment by kennknowles** [comment]
Run PythonFormatter PreCommit

**Comment by kennknowles** [comment]
Run PythonFormatter PreCommit

**Comment by kennknowles** [comment]
Run Python PreCommit

**Comment by kennknowles** [comment]
Run SQL_Java11 PreCommit

**Comment by kennknowles** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Python_Phrase/1985/ took more than twice the normal amount of time. I certainly don't think Python precommits are relevant, but I will kick them off again just to be good about being green. If we factor the different "natures" into different modules we could isolate the Jenkins build triggers.

**Comment by kennknowles** [comment]
Run Python PreCommit

**Comment by kennknowles** [comment]
Hmmm. DisplayData doesn't seem like it should flake, but the failures differed this time. https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/ has not been steadily green for a week. I will poke it once more but really this is a spurious test run anyhow.

**Comment by kennknowles** [comment]
Run Python PreCommit

**Pull request merged**
