### PR TITLE
Always consider Read to be a primitive for dataflow pipelines.

### PR DESCRIPTION
**Pull request by robertwb**
This fixes the breakage caused by #5685.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by robertwb** [comment]
Jenkins: Run Python Postcommit

**Comment by charlesccychen** [comment]
Did you figure out why running "Python Dataflow ValidatesRunner" didn't pick up the previous problem?

**Comment by lukecwik** [comment]
WordCount was failing and WordCount isn't a ValidatesRunner test

**Comment by lukecwik** [comment]
Run Python Postcommit

**Comment by lukecwik** [comment]
Tests failed due to quota issue. Kicking off again.

**Comment by lukecwik** [comment]
Run Python Postcommit

**Pull request merged**
