### PR TITLE
Enable non-merging window test on Dataflow Runner v2.

### PR DESCRIPTION
**Pull request by robertwb**
R: @kennknowles 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
Are these tests run as pre-commit? Also, how does one run (one of them) manually?

**Comment by boyuanzz** [comment]
Run Java Dataflow V2 ValidatesRunner

**Comment by boyuanzz** [comment]
> Are these tests run as pre-commit?

It's part of Dataflow VR test. 

>  Also, how does one run (one of them) manually?

I usually change the validatesRunnerV2 target to include just one test case and if you have write access to apache-beam-testing, you can invoke the test locally by ./gradlew :runners:google-cloud-dataflow-java:validatesRunnerV2 directly.

**Comment by kennknowles** [comment]
Here's a rundown of the command line options: https://stackoverflow.com/questions/22505533/how-to-run-only-one-unit-test-class-using-gradle

This only works if Gradle knows it is a `Test` type task. Some of our configs are complex enough that this somehow gets obscured.

**Review by kennknowles — APPROVED** [review]
LGTM when green.

**Comment by boyuanzz** [comment]
It seems like the `testNonPartitioningWindowing` failed in the latest run: https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_PR/18/testReport/org.apache.beam.sdk.transforms.windowing/WindowingTest/testNonPartitioningWindowing/

**Comment by kennknowles** [comment]
Pretty-printed output:

```
Expected: iterable with items [
    "a:1:1:[1969-12-31T23:59:59.995Z..1970-01-01T00:00:00.005Z)",
    "a:2:5:[1970-01-01T00:00:00.000Z..1970-01-01T00:00:00.010Z)",
    "a:1:10:[1970-01-01T00:00:00.005Z..1970-01-01T00:00:00.015Z)",
    "b:1:8:[1970-01-01T00:00:00.000Z..1970-01-01T00:00:00.010Z)",
    "b:1:10:[1970-01-01T00:00:00.005Z..1970-01-01T00:00:00.015Z)"
] in any order
     but: not matched: "a:2:1:[1970-01-01T00:00:00.000Z..1970-01-01T00:00:00.010Z)"
```

**Comment by kennknowles** [comment]
Parsing:

 - value `"a"`
 - multiplicity 2
 - timestamp 1
 - window `[0, 10)`

That timestamp is wrong. It implies a timestamp combiner of MIN (or just a major bug). The default should be END_OF_WINDOW.

I believe the submitted job always has an explicit timestamp combiner and does not leave default up to the service. No?

**Comment by kennknowles** [comment]
I am wrong. The test configures timestamp combiner to be earliest.

**Comment by kennknowles** [comment]
The issue is the adjustment of timestamps to allow the watermark to move forward in sliding windows.

**Comment by kennknowles** [comment]
https://github.com/apache/beam/blob/595c25263638b3d5624875e46b69a442cedb09a7/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/SlidingWindows.java#L209

**Review by kennknowles — CHANGES_REQUESTED** [review]
Based on this evidence, this should not be unsickbayed until Dataflow is fixed.

**Comment by robertwb** [comment]
I actually think it's sliding windows that has the wrong behavior here in Java.

**Comment by kennknowles** [comment]
The behavior is very deliberate to avoid a watermark holdup.

**Comment by kennknowles** [comment]
To be clear: the behavior is odd. I would like to not have it. But it does date back to before Beam.

**Comment by robertwb** [comment]
This behavior is also @Experimental(Kind.OUTPUT_TIME). It is also inconsistent between Java and Python (both of which claim to support it as `beam:window_fn:sliding_windows:v1`.) I say we revert this behavior.

**Comment by kennknowles** [comment]
"Revert" to a state it was never in :-)

**Comment by kennknowles** [comment]
We still need a solution for the underlying problem: sliding windows and friends are pretty nonfunctional without this.

**Comment by robertwb** [comment]
The default timestamp is now end-of-window. (I wonder if this predates that change...)

**Comment by kennknowles** [comment]
It does predate that change. But in the event EARLIEST is chosen (as it must be for e.g. SQL joins) the problem still applies.

**Comment by kennknowles** [comment]
Opened dev list discussion for visibility and looking for good options.

**Comment by kennknowles** [comment]
After #14268 this should go in

**Review by kennknowles — APPROVED** [review]
Changing my response to pre-approval but it won't be green until `getOutputTime` is removed.

**Pull request closed without merging**
