### PR TITLE
[Jenkins,Spark] Stop running Nexmark suite for deprecated Spark 2 runners

### LINKED ISSUE #23634: [Bug]: Nexmark SparkStructuredStreamingRunner v2 and v3 publishing to same metric
### What happened?

The Nexmark SparkStructuredStreamingRunner v2 and v3 tests are both publishing results to the same metric since the feature went in #15529 resulting in bad data:
oeKw8uaYtyHxsdT

cc: @echauchot

### Issue Priority

Priority: 1

### Issue Component

Component: testing-nexmark

### PR DESCRIPTION
**Pull request by mosche**
The Nexmark SparkStructuredStreamingRunner v2 and v3 tests are currently both publishing results to the same metric, the same issue applies to the "normal" SparkRunner.

Stop running Nexmark suite for deprecated Spark 2 runners. 
Additionally,  following the approach taken for Flink, this ensures a consistent version of Spark is used for Nexmark tests (fixes #23634).

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @apilloud 
R: @aromanenko-dev 
R: @echauchot

**Comment by mosche** [comment]
Note, besides being deprecated, it also turns out the Spark 2 runners are completely broken. The version of Jackson Beam requires is not compatible with the one available / loaded on a Spark 2 cluster. Due to that deserialization of PipelineOptions fails. 
https://github.com/apache/beam/issues/23568

**Review by apilloud — APPROVED** [review]
LGTM

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Spark Runner Nexmark Tests

**Pull request merged**
