### PR TITLE
Inline jwalton/gh-find-current-pr

### PR DESCRIPTION
**Pull request by damccorm**
Right now, the stage gcs workflow is failing because it uses the jwalton/gh-find-current-pr action which hasn't been blessed by infra. We could ask infra to allow list it, but its a small enough piece of code that its probably easier to just roll our own, plus that decreases our vulnerability/supply chain surface

Example failing run: https://github.com/apache/beam/actions/runs/5716072272

Example success after this change on my fork: https://github.com/damccorm/beam/actions/runs/5719430241/job/15497299667?pr=173 (it eventually fails on authing to GCP because I don't have the right env vars set)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @Abacn @andreydevyatkin

**Review by Abacn — COMMENTED** [review]
Thanks for the quick fix! Shall we mention the original author / credit?

**Comment by damccorm** [comment]
> Thanks for the quick fix! Shall we mention the original author / credit?

Yes, good call - forgot I hadn't done this. Done

**Review by Abacn — APPROVED** [review]
LGTM

**Pull request merged**
