### PR TITLE
[BEAM-14100] Fixed bigquery io to work with Interactive Beam

### PR DESCRIPTION
**Pull request by KevinGG**
Made the split_result picklable when the code is executed in an IPython
environment.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by KevinGG** [comment]
R: @pabloem 
PTAL, thx

**Comment by KevinGG** [comment]
Tested with the change:
image

**Comment by pabloem** [comment]
can you add a comment explaining why this is necessary?

**Comment by KevinGG** [comment]
>

**Comment by KevinGG** [comment]
> can you add a comment explaining why this is necessary?

Thanks! Added a comment to explain it.

**Comment by KevinGG** [comment]
Retest this please

**Comment by KevinGG** [comment]
> Oops, looks like we tried to solve the same problem. What do you think of my approach here: #17100 ? It avoids branching behavior based on the runner.

Thanks [chunyang](https://github.com/chunyang), your PR looks so much better!

**Comment by chunyang** [comment]
Thanks @KevinGG !

**Pull request closed without merging**
