### PR TITLE
[BEAM-6009] Modify Github template to include Flink PVR for batch/str…

### PR DESCRIPTION
**Pull request by mxm**
The old build task has been split into a batch and a streaming job.

This is how it looks: https://github.com/mxm/beam/blob/bd8de6de159bc92daaea4d0cccbd7dfae80f0b86/.github/PULL_REQUEST_TEMPLATE.md

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
As a follow-up, I think we could rotate the matrix and have the SDKs as columns?

**Comment by tweise** [comment]
The changes also need to be made in README.md. I notice that the formatting looks a bit messed up on the pull request page (before and after this PR) and that the Flink entries are not stacked vertically.

**Comment by mxm** [comment]
They are stacked vertically for me, but it depends on the browser and screen size. I think we can address the design separately. I'd like to fix the broken link to the Flink PVR tests before.

The README only includes the PreCommit tests. So nothing is broken there. Good idea though to include all links.

**Comment by tweise** [comment]
This should list the exact same (post commit) builds: https://github.com/apache/beam/blob/master/README.md

**Comment by mxm** [comment]
@tweise I updated the matrix in the README. Should be good to go now.

**Pull request merged**
