### PR TITLE
Revert "Enable remote gradle cache and build scan for GitHub Actions workflows"

### PR DESCRIPTION
**Pull request by tvalentyn**
Reverts apache/beam#28539

Suspecting this has caused may flakes in GHA suites due to `Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`, see: https://github.com/apache/beam/pull/28539#issuecomment-1728049974

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @damccorm @andreydevyatkin

**Comment by tvalentyn** [comment]
Noting the RAT failure - were there dependent changes or it's safe to ignore?

**Comment by damccorm** [comment]
I think these errors might be caused by inconsistencies in the yaml that is initially checked out/used for comoposite actions and the composite action that exists by the end of the run (and reverting might expose the same issue for newer PRs).

For PRs seeing this, if we update with the latest master does the problem go away?

**Comment by tvalentyn** [comment]
> For PRs seeing this, if we update with the latest master does the problem go away?

I'll keep an eye on new PRs, pr in question has been merged after manually inspecting logs

**Pull request closed without merging**
