### PR TITLE
[BEAM-20807] Support Beam docker images on ARM64.

### PR DESCRIPTION
**Pull request by robertwb**
A start for #20807. This just allows building the images; full testing, etc. remains to be done.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @byronellis

**Comment by jihad-akl** [comment]
Any status updates on this?
I am getting: Image is up to date for apache/beam_java8_sdk:2.44.0 docker: Error response from daemon: image with reference apache/beam_java8_sdk:2.44.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.

**Comment by robertwb** [comment]
Did you try patching this PR? This PR needs to be reviewed (you could do this), merged, and arm images released.

**Review by kennknowles — APPROVED** [review]
LGTM. I might separate the buildSrc dependency upgrade into its own commit.

**Comment by robertwb** [comment]
> LGTM. I might separate the buildSrc dependency upgrade into its own commit.

Done.

**Comment by lostluck** [comment]
Why was the Go container skipped? Or even the Typescript one? Uneven updates like this prevent a unified beam vision.

**Comment by robertwb** [comment]
Go is a bit trickier as the artifact itself must match the container (unlike, e.g., Java where the user-provided jars can work in either container). 

That being said, we can still create the containers. https://github.com/apache/beam/pull/26047

**Pull request merged**
