### PR TITLE
[BEAM-12164] Convert all static instances to be transient in the connector in order to enable concurrent testing

### PR DESCRIPTION
**Pull request by nancyxu123**
Convert all static instances to be transient in the connector in order to enable concurrent testing

### CODE REVIEW

**Review by thiagotnunes — APPROVED** [review]

**Comment by pabloem** [comment]
ah I'm glad you found this. thanks for looking into it!

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
LGTM

**Comment by pabloem** [comment]
errrors in precommit unrelated so moving forward with merge

**Pull request merged**
