### PR TITLE
Update dataflow container version for Pandas upgrade

### LINKED ISSUE #24531: [Failing Test]: Python Postcommits are failing.
### What happened?

https://ci-beam.apache.org/job/beam_PostCommit_Python38/3457/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_aggregation/

Failing tests
[apache_beam.examples.dataframe.taxiride_it_test.TaxirideIT.test_aggregation](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_aggregation/)
[apache_beam.examples.dataframe.flight_delays_it_test.FlightDelaysTest.test_flight_delays](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.flight_delays_it_test/FlightDelaysTest/test_flight_delays/)
[apache_beam.examples.dataframe.taxiride_it_test.TaxirideIT.test_enrich](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_enrich/)
[apache_beam.dataframe.io_it_test.ReadUsingReadGbqTests.test_ReadGbq_with_computation](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.dataframe.io_it_test/ReadUsingReadGbqTests/test_ReadGbq_with_computation/)

The postcommits are failing. This happened on Dec 2, 2022. https://github.com/apache/beam/pull/23973 might be the root cause. 

Running tests on revered PR https://github.com/apache/beam/pull/24530 to see if that PR is causing errors.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by damccorm**
I missed doing this in #23973 and it is currently causing postcommits to fail

Fixes #24531 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Python Postcommit

**Comment by damccorm** [comment]
R: @AnandInguva

**Comment by damccorm** [comment]
Run Python 3.9 PostCommit

**Comment by AnandInguva** [comment]
LGTM once the Post commit passes. Thanks for the fix.

**Comment by damccorm** [comment]
Run Python PreCommit

**Pull request merged**
