### PR TITLE
Use built-in cmp python function in comparing Datastore paths

### PR DESCRIPTION
**Pull request by vikkyrk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by vikkyrk** [comment]
R: @aaltay

**Comment by aaltay** [comment]
LGTM, I can merge after tests. 

Is there a unit test for `compare_path` ?

**Comment by vikkyrk** [comment]
Yes they are here, https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/datastore/v1/helper_test.py. The problem is that `query_splitter` isn't being tested for both `name` and `id`. Fixed that.

**Comment by aaltay** [comment]
Thank you, LGTM. (I can merge after new tests.)

**Pull request closed without merging**
