### PR TITLE
[BEAM-9382] Clean up of TestStreamTranscriptTests.

### PR DESCRIPTION
**Pull request by acrites**
Removes check for final field in PaneInfo since it is not reported properly by direct runner. Updates index for session panes and changes test with Count(2) early trigger to only inject two elements since behavior with 3 is non-deterministic.

Added changes to trigger driver to delete pane info index and nonspeculative index when merging since otherwise the newly created window would inherit it from the merged away window resulting in incorrect values.

R: @robertwb 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lukecwik** [comment]
Drive by comment:
Shouldn't we disable the test for the direct runner if it isn't supported and file a bug instead of editing what the test does?
Alternatively, could we fix the direct runner?

**Comment by kennknowles** [comment]
Since we are doing drive by comments, perhaps a clear comment describing exactly what the test is trying to verify would allow us to be sure to have all the necessary verifications but no extraneous info.

Also I assume you mean the Python direct runner (each language has a direct runner for that language) since I think the Java direct runner does support pane info.

**Comment by acrites** [comment]
Along the lines of what Kenn is saying, I had originally thought that these tests weren't really testing whether or not PaneInfo.final gets set correctly in the various triggering strategies, but more so that it was outputting the correct elements. Maybe we want to test all aspects in a single test though.

I'm fine with sickbaying the tests for Python direct runner if you're ok with having a large number of tests inactive until we getting around to fixing direct runner. Maybe that'll motivate us to get it fixed faster...

**Comment by robertwb** [comment]
The Python direct runner does support PaneInfo, but it doesn't (yet) support allowed lateness, so the "final" bit is wrong. Yes, we should fix this, though hopefully on the FnApiRunner once it supports streaming rather than invest too much into the old direct runner (unless it's cheap to do). 

I would rather disable the "final" bit check for these tests (and add a new, disabled test that checks this bit) than disable these tests entirely for the direct runner. So as is, this change LGTM.

We could also consider expanding the API to indicate certain features are broken on certain runners, rather than entire tests, which would allow us to fully specify the expected results and still produce partial validation on incomplete/in-progress runners.

**Comment by acrites** [comment]
RE fixing the Python direct runner: right now we just use the return value
from on_fire for each trigger to set the final bit. This doesn't take into
account allowed lateness. So we'd probably need to update all of the
triggers.

Maybe just a single test for now that is disabled and has the final bit
check? Or did you want to duplicate all the tests? I'm thinking something
like this one:

name: fixed_allowed_lateness_final_set
broken_on:
  - SwitchingDirectRunner  # Doesn't set final field properly with late
data.
window_fn: FixedWindows(10)
trigger_fn: AfterWatermark(early=AfterCount(2), late=AfterCount(1))
timestamp_combiner: OUTPUT_AT_EOW
allowed_lateness: 10
transcript:
  - input: [1, 2]
  - expect:
      - {window: [0, 9], values: [1, 2], timestamp: 9, final: false}
  - input: [3]
  - watermark: 100
  - expect:
      - {window: [0, 9], values: [1, 2, 3], timestamp: 9, final: true}

**Comment by acrites** [comment]
Actually, that last example doesn't fail like I would expect. So I guess the Python direct runner sets final = true sometimes...

**Comment by acrites** [comment]
Run Python PreCommit

**Comment by acrites** [comment]
It looks like TriggerDriverTranscriptTest.test_early_late_sessions is failing (since there's no way to sickbay that test). Am I understanding the semantics of PaneInfo index correctly? The first firing of each window should have index 0 even if that window was the result of merging another window, right?

**Comment by kennknowles** [comment]
Yea, that's right.

**Comment by acrites** [comment]
Run Python PreCommit

**Comment by acrites** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
retest this please

**Comment by robertwb** [comment]
I'm not convinced that reseting the indices to 0 on merging windows is the desired semantics, but that discussion is probably out of scope for this PR. Other than that, LGTM.

**Comment by kennknowles** [comment]
Yea I don't think anyone is happy about it. But it has always been that way and also is the only way we meet the spec of panes being (EARLY* ON_TIME? LATE*)

**Comment by acrites** [comment]
Apparently the failing test in the PreCommit has been "Failing for the past 11,721 builds (Since #0 )"

**Pull request merged**
