### PR TITLE
[BEAM-2222] Remove sdk & example README.md that are covered in web site

### PR DESCRIPTION
**Pull request by aaltay**
R: @davorbonaci 

`pom.xml` changes are for copying root README.md into the packaged python distribution.

### CODE REVIEW

**Comment by aaltay** [comment]
@davorbonaci ping

**Comment by aaltay** [comment]
I agree with that, but I also did not want to leave an almost empty README.md. Would it make sense to leave a README.md that points to quick start?

**Comment by davorbonaci** [comment]
I think the general prose about examples is ~fine: intro, start with wordcount, beyond wordcount. I'd certainly cut how to build & run, and point to the website.

**Comment by aaltay** [comment]
PTAL, re-added examples README and trimmed execution parts, pointing to the website.

**Pull request closed without merging**
