### PR TITLE
[BEAM-1523] Remove PValue.getProducingTransformInternal

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
This exposes too much information on the structure of the Graph to be
appropriate for non-graph related APIs. It also is not stable, and
subject to change at any point due to Pipeline Surgery APIs.

Update DataflowRunner to use the visited TransformHierarchy to obtain
the producing transforms for PValues, and store these values to
construct the graph.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
LGTM if it goes green.

**Comment by andrewsmartin** [comment]
@tgroh @kennknowles Hi, is there an easy way in user code to get the producing transform after this change?

**Comment by kennknowles** [comment]
@andrewsmartin this method was actually never intended to be used in user code, or at least not with any stability. The APIs for analyzing and executing pipelines are still evolving rapidly - just the construction and launch of a pipeline are stable.

That said, if you are comfortable with that, perhaps you can say more about what you want to do with it? Most runners do a global pass using `Pipeline.traverseTopologically` to get their work done, such as setting up producers for underlying storage, etc. If you need to do something where this is inconvenient, we could imagine adding runner-facing APIs for it. This would be a good discussion to move to `dev@beam.apache.org`.

**Comment by andrewsmartin** [comment]
@kennknowles actually the global pass with `Pipeline.traverseTopologically` works for our need, thanks! We have some custom logic when it comes to assigning transform names, and mainly we just needed this information to get the transform name during tests.

**Pull request closed without merging**
