### PR TITLE
Remove GPL findbugs dependency

### PR DESCRIPTION
**Pull request by pabloem**
r: @jbonofre

### CODE REVIEW

**Comment by pabloem** [comment]
retest this please

**Comment by kennknowles** [comment]
From the gradle build scan:

```
:beam-sdks-java-core:compileJava FAILED
/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy/1.8.11/byte-buddy-1.8.11.jar(/net/bytebuddy/description/type/TypeList.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy/1.8.11/byte-buddy-1.8.11.jar(/net/bytebuddy/description/type/TypeList.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy/1.8.11/byte-buddy-1.8.11.jar(/net/bytebuddy/implementation/bytecode/assign/Assigner.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings'
/home/jenkins/.m2/repository/net/bytebuddy/byte-buddy/1.8.11/byte-buddy-1.8.11.jar(/net/bytebuddy/implementation/bytecode/assign/Assigner.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
error: warnings found and -Werror specified
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
4 warnings
```

**Comment by swegner** [comment]
From [mvnrepository](https://mvnrepository.com/artifact/com.github.stephenc.findbugs/findbugs-annotations) it appears that 1.3.9-1 is the latest version for this artifact.

If the sdks-java-core warnings are blocking the release, feel free to set `failOnWarnings` to false and I'll follow-up separately.

**Comment by pabloem** [comment]
r: @kennknowles

**Comment by swegner** [comment]
FYI, I've opened [[BEAM-4556]](https://issues.apache.org/jira/browse/BEAM-4556) to re-enable `failOnWarnings`

**Pull request merged**
