### PR TITLE
[SQL] Refactor Variance

### PR DESCRIPTION
**Pull request by akedin**
Existing implementation breaks when non-trivial windowing is introduced, contains duplicated code, and does not have a lot of test coverage.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by vectorijk** [comment]
@akedin Is this already to merge? After that, I can refactoring covariance function correspondingly.

**Comment by kennknowles** [comment]
:lgtm:

---

Reviewed 5 of 13 files at r1, 6 of 9 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/agg/package-info.java, line 22 at r2](https://reviewable.io:443/reviews/apache/beam/4448#-L42k98HbCtPtbSP4WqZ:-L42k98HbCtPtbSP4Wq_:b-28dxz5) ([raw file](https://github.com/apache/beam/blob/4070b788ccb12e746a7bbe46228ea5a12bcf5581/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/agg/package-info.java#L22)):*
> ```Java
>  * Implementation of standard SQL aggregation functions, e.g. VAR_POP, VAR_SAMP.
>  */
> package org.apache.beam.sdk.extensions.sql.impl.transform.agg;
> ```

Annotate with `@DefaultAnnotation(NonNull.class)`. But actually let's merge to unblock other work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4448#-:-L43OGBt_4h1ii8GEoKY:bnfp4nl)*

**Comment by kennknowles** [comment]
Can you prepare the commit history for merge? And FWIW I think reviewable works just fine even if you force push instead of pushing fixup commits.

**Comment by akedin** [comment]
Done

---

Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/agg/package-info.java, line 22 at r2](https://reviewable.io:443/reviews/apache/beam/4448#-L42k98HbCtPtbSP4WqZ:-L43qWf-iCYACmMz772W:bb6un1j) ([raw file](https://github.com/apache/beam/blob/4070b788ccb12e746a7bbe46228ea5a12bcf5581/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/transform/agg/package-info.java#L22)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

Annotate with `@DefaultAnnotation(NonNull.class)`. But actually let's merge to unblock other work.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4448#-:-L43qYeqFnm8TRsmnc8-:bb6un1j)*

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by vectorijk** [comment]
@akedin Recent jenkin builds are unhappy due to failed building `Apache Beam :: SDKs :: Java :: Maven Archetypes :: Examples`

**Comment by vectorijk** [comment]
maybe due to d11e5030f3a011c6fecba1f3d3b2bf6ebd8913c8

**Comment by akedin** [comment]
@vectorijk hm, didn't realize that. I'll take a look

**Comment by kennknowles** [comment]
The flakiness of our build is driving me crazy. If we had a good system of only testing things potentially affected they would not even have run so I can't see blocking on this any longer.

**Comment by akedin** [comment]
Broke the build by not declaring Findbugs-annotations. Fix: #4547

**Pull request merged**
