### PR TITLE
[DON'T MERGE] [BEAM-11992] Run CrossLanguage ValidatesRunner tests only for Spark 3

### PR DESCRIPTION
**Pull request by iemejia**

### CODE REVIEW

**Comment by iemejia** [comment]
Run XVR_Spark PostCommit

**Comment by ibzib** [comment]
Huh, looks like I was wrong - guess we'll have to investigate where this error is coming from.

**Comment by iemejia** [comment]
Yep my suspicion without knowing anything is something being hardcoded or some parameter missing from the python side. Any help is extremely welcomed

**Comment by ibzib** [comment]
Just kidding - we forgot to run the seed job. So the failed job was still running both tests.

**Comment by ibzib** [comment]
run seed job

**Comment by ibzib** [comment]
Run XVR_Spark PostCommit

**Comment by iemejia** [comment]
Oh how silly ok it is green so maybe the easiest path is to just create a second set of XVR tests for Spark 3. I I will prepare a PR for that.

**Pull request closed without merging**
