### PR TITLE
Apply spotless across Beam

### PR DESCRIPTION
**Pull request by reuvenlax**
Spotless changes seem to have changed, and not all were caught by @kennknowles previous PR. Apply the result of spotlessApply across the codebase.

### CODE REVIEW

**Comment by kennknowles** [comment]
Some of the diffs look familiar. Was something reverted? Either way, spotless is happy so I'm happy too. LGTM.

**Comment by kennknowles** [comment]
Very suspicious that #7505 passed spotless.

**Comment by reuvenlax** [comment]
Run Python_ValidatesRunner_Flink PreCommit

**Comment by reuvenlax** [comment]
Python change is being caused by virtualenv, and this PR only touches Java files.

**Pull request merged**
