### PR TITLE
Miscellaneous touch ups

### PR DESCRIPTION
**Pull request by kennknowles**
R: @iemejia (randomly chosen victim)

Very trivial PR for warnings that I kept seeing and addressed just because they were there.

### CODE REVIEW

**Comment by iemejia** [comment]
retest this please

**Comment by kennknowles** [comment]
Thanks!

**Comment by kennknowles** [comment]
Too bad about Jenkins. I'll keep looking at ways to improve it.

**Comment by kennknowles** [comment]
Ah, this time it was a reboot or other sort of disconnection of the Jenkins worker.

**Comment by iemejia** [comment]
You are welcome, glad to help and don't hesitate to ping me if you need help with any review when you guys have too much to do (I have the impression you guys do a lot of reviews), or also to take advantage of the time zones).

**Comment by iemejia** [comment]
Oh and thanks for your work on improving Mr. Jenkins health.

**Pull request merged**
