### PR TITLE
Clean up Go formatter suggestions

### PR DESCRIPTION
**Pull request by jrmccluskey**
Merge in code format changes made by `go fmt` in the Go SDK codebase. Ignores two formatting changes in the syscallx package that are found in generated code.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
R: @damccorm @riteshghorse @lostluck 

No code change, just cleaning up some fmt changes that were dangling

**Review by damccorm — APPROVED** [review]
LGTM - I do have a question (for you or others) though - is there a reason we don't have a CI check for this? It could be nice to add a quick actions or jenkins job do something like:

```
go fmt sdks/go/...
git diff-index --quiet HEAD -- || (echo "Run go fmt before checking in changes" && exit 1)
```

That way we don't end up with any files in this state going forward

**Comment by jrmccluskey** [comment]
That is a very good suggestion. Would be good to add to Actions along with giving the `go vet` run an actual consequence if there's output.

**Comment by riteshghorse** [comment]
LGTM. @damccorm good suggestion.

**Comment by lostluck** [comment]
Run Go PreCommit

**Comment by lostluck** [comment]
Nit: Do add the go fmt changes to the generated code. It's likely just older code that never had it run on it initially, but having automated formatting applied to automatically generated code is a win.

As for the reasons why? Where to start?

1. It was only in December when we got rid of the old GoGradle plugin, which didn't have the best support for formatting checks. Invoking by Gradle wasn't clear.
2. Github actions are very new to the project.
3. It's not a huge priority when only 2 engineers were changing the code and were running go fmt (or their editors were) anyway.

Should we? Absolutely. Lets do it.

**Comment by lostluck** [comment]
Oh yeah, the build tag convention changed a while back, so it's good go fmt corrects them for us.

**Pull request merged**
