### PR TITLE
Add more logging to QueryChangeStreamAction exceptions

### PR DESCRIPTION
**Pull request by scwhittle**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by nancyxu123** [comment]
> 

Hi Sam, thanks for the PR. PR looks good, the additional logging could potentially be helpful.

**Comment by bvolpato** [comment]
FYI Integration Tests are failing
```
10:47:45 > Task :sdks:java:io:google-cloud-platform:integrationTest
11:05:53 
11:05:53 org.apache.beam.sdk.io.gcp.spanner.SpannerReadIT > testReadWithDataBoost FAILED
11:05:53     org.apache.beam.sdk.Pipeline$PipelineExecutionException at SpannerReadIT.java:214
11:05:53         Caused by: com.google.cloud.spanner.SpannerException at SpannerExceptionFactory.java:291
11:05:53             Caused by: com.google.cloud.spanner.SpannerException at SpannerExceptionFactory.java:291
11:05:53                 Caused by: io.grpc.StatusRuntimeException at Status.java:539
11:15:42 
11:15:42 94 tests completed, 1 failed, 1 skipped

```

**Comment by bvolpato** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by scwhittle** [comment]
That error was an authorization issue before, I don't think it is related to this PR. (sorry thought I replied on this earlier with that)

**Comment by scwhittle** [comment]
R: @bvolpato  are you able to merge?

**Pull request merged**
