### PR TITLE
[BEAM-7709] Re-use node for explicit flattens

### PR DESCRIPTION
**Pull request by lostluck**
Have all the links for a given Flatten PTransform use the same instance. Subsequent calls for these links will hit the cached version.

Simple problem with a simple fix. Adding a test would require adding a full test suite (this particular  filebarely has one at present), and I've not yet reconstructed a Git development environment since my previous laptop died, which makes that trickier from the web interface.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @herohde

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
R: @youngoli @lukecwik 
(it looks like Henning is out this week, so no time to pull them in.)

**Comment by lukecwik** [comment]
It is valid to have multiple copies of downstream DoFns but it adds a lot of complexity to do it right and is unlikely to be performant. (The complexity comes from things like user state/timers expectations that readers/writers have a consistent view per key).

**Comment by lostluck** [comment]
Thanks!
Agreed. That would have been fine and wouldn't have triggered the bug I saw. In particular, subsequent links were creating new *flatten* nodes which meant there was no guarding each of them forwarding the startbundle request to a single downstream DoFn instance. The Go SDK treats each PTransform Node as a state machine to ensure the Bundle Lifecycle is followed.

**Comment by youngoli** [comment]
Just so I understand this change, when handling a link between a transform with a Flatten URN and one of its inputs: Before it would just create a Flatten instance and set it as the link, now it also uses the same Flatten for every other input to the PTransform, so that when those links get put into this function later it exits early at line 320?

**Comment by lostluck** [comment]
That's right! The "shortcut" on line 320 avoids repeating work in case something else is using that PCollection. Good ol' [memoization](https://en.wikipedia.org/wiki/Memoization).
Before it would, get a link from a PCollection, and just create a flatten *per* PCollection. As Luke mentions, this is totally fine if the runner "split" different upstream DoFns into different bundle executions, which naturally leads to multiple instances of the downstream DoFn. That's fine*. While it's unnecessary to have the flatten unit in that instance, it's not wrong.
However, if the two pcollections are in the *same* bundle execution, and there's only a single downstream consumer for the flatten, having multiple flatten nodes like the code was doing before is wrong, since the SDK side flatten has one job essentially: to ensure that the downstream StartBundles and FinishBundles are only ever called once per bundle. Naturally, this doesn't work with multiple instances of the same flatten node.
So the solution is to ensure all the inputs to a given Flatten Unit are mapped to a the same instance of that flatten unit.

*except as, Luke mentioned, for stateful processing, where we'll need to be sure if we're creating multiple instances of the same DoFn, that they're passed the same "state holder".

**Pull request merged**
