### PR TITLE
[BEAM-3268] Reshuffle filenames before returning them from WriteFilesResult

### PR DESCRIPTION
**Pull request by jkff**
R: @lgajowy 
CC: @chamikaramj @udim

### CODE REVIEW

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
retest this please

**Comment by lgajowy** [comment]
retest this please

**Comment by jkff** [comment]
OK seems tests went through this time.

**Comment by lgajowy** [comment]
(I have no write access so I cannot merge this :) )

**Pull request merged**
