### PR TITLE
[BEAM-9321] Add BigQuery Avro logical type support on write

### PR DESCRIPTION
**Pull request by regadas**
With 2.18.0 we are able to write GenericRecords to BigQuery. However, writing does not respect Avro <-> BigQuery data type conversion [docs](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types) we need to set the `useAvroLogicalTypes` option.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by regadas** [comment]
Run Java PreCommit

**Comment by regadas** [comment]
R: @lukecwik

**Comment by regadas** [comment]
R: @chamikaramj

**Comment by alexvanboxel** [comment]
I'm not qualified to give my ok, but I have a question: it there a reason why it's a an option, shouldn't it always handle the logical type?

**Comment by chamikaramj** [comment]
Thanks. Passing this to Pablo.

**Comment by pabloem** [comment]
I agree with Alex on this - I think we should just always handle the logical type. I have two questions:
- Would it be backwards incompatible if we forced always handling the logical types? I think we should just make it the default.

**Comment by regadas** [comment]
Hi, I think we need to consider a few things:

1) in BigQuery this is not the default behavior; Users need to explicitly enable `useAvroLogicalTypes` to have their types converted to the data types mentioned in the doc as opposed to the underlying avro raw type. This means that tables will have different schemas!

2) The previous Beam version was already released with this; Logical Types are not respected and created Table will have schemas where types match the avro raw types. 

It makes sense that logical types should be respected by default (it option to disable), but because of the previous points I don't think we can. or even if it's a good idea.

**Comment by pabloem** [comment]
According to the BQ API docs, for JobConfigurationLoad the default value will be true, but has not been enabled in the API. Is this correct?

If so, then once BQ enables the default value of true, our backwards compatibility could be lost anyway...
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job

**Comment by regadas** [comment]
Yup, correct it wasn't enabled and ti has been like this since 2018'ish or even earlier I guess? I don;t have access to the timeline so i don't know whats the plan there but I think it's going to be a risky move for them.

Regardless of that, I think we should keep in line with them and not break compatibility and only address that Once/if they release that. wdyt?

**Comment by alexvanboxel** [comment]
Agreed, let's not brake the current pipelines.

**Comment by alexvanboxel** [comment]
Run Java PreCommit

**Comment by alexvanboxel** [comment]
For me this LGTM, but I let the final judgement to the Googlers. I've retriggered the failed test.

**Comment by pabloem** [comment]
Run Java Precommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
lgtm. thanks @regadas

**Pull request merged**
