### PR TITLE
Gate GH actions so it only runs in main/upstream repo

### PR DESCRIPTION
**Pull request by emilymye**
**Please** add a meaningful description for your change here

- This change makes sure that GH actions only run in apache/beam by default, not in forks.

As far as I can tell, there's no way to disable the actual trigger of an action based on the repository right now. Hence, I added if-checks per job. 

Tested manually on my fork master: 
- [Actual change](https://github.com/emilymye/beam/actions/runs/164928025) (with `repository_head = 'apache'`)
- [An opt-in workflow](https://github.com/emilymye/beam/actions/runs/164944287) (with `repository_head = 'emilymye'`)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | --- | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by emilymye** [comment]
R: @TobKed
R: @aaltay

**Comment by aaltay** [comment]
LGTM. I will wait for @TobKed's review. He knows more about these files.

**Comment by TobKed** [comment]
What do you think about limiting the jobs that will be run only on apache repository to those ones which will fail without GCS credentials?
These jobs are `prepare_gcs` , `upload_source_to_gcs`, `upload_wheels_to_gcs`, `list_files_on_gcs`
and additionally: `tag_repo_nightly` 

In case someone don't want to run GitHub actions on the fork at all can disable it for the repository.
https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository

**Comment by mwalenia** [comment]
AFAIK it's possible to disable actions on your own fork in the settings: 
image

**Comment by emilymye** [comment]
I think my reasoning was that actions should be specifically opt-in, since disabling them per-fork still requires a manual opt-out step. I guess I'm not entirely sure why these need to run on forks automatically.

**Comment by aaltay** [comment]
I agree with both of you. Keeping tests by default would allow easy testing. (But is it free for all even if theirs forks are private?) And making it opt-in sounds like least disruptive way (But, would people discover this opt-in easily?). 

Is there a common convention for workflows in other github oss projects?

**Comment by emilymye** [comment]
I'm sure @TobKed knows more about Github actions than I do, but it seems there isn't a common convention. Based on the docs [docs](https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions) and some [issues](https://github.community/t/how-to-run-and-enable-github-actions-on-forked-repo-with-github-api/17232), it seems like GH used to disable actions for forked repos by default but have since changed it. 

My ideal workflow is that GH itself disables actions for a forked repo and asks if the fork owner wants to re-enable the actions as shown in the example issue. @TobKed do you know if that's a configuration step when setting up actions? 

Otherwise, I'm fine on closing this PR and waiting for GH to provide a better way to opt-out/opt-in if we can avoid these repo-owner-specific ifs and have a better opt-in flow.

**Comment by TobKed** [comment]
I checked actions tab in repository which I recently forked and I got information and question about enabling workflows.
Workflows aren’t being run on this forked repository. Because this repository contained workflow files when it was forked, we have disabled them from running on this fork. Make sure you understand the configured workflows and their expected usage before enabling Actions on this repository.

If I am not mistaken it looks exactly as you suggested it @emilymye :)
To be honest, I am not sure when github introduced this message. 

Despite of this, what do you think about my proposal from https://github.com/apache/beam/pull/12222#issuecomment-657426180 ?

**Comment by emilymye** [comment]
SGTM, especially if it is actually opt-out by default. I tried a new fork on a different account and got that disabled page, so now I'm very confused why they were enabled by default for me.

**Comment by aaltay** [comment]
This seems to be a setting. (https://github.community/t/stop-github-actions-running-on-a-fork/17965/2) Is it possible that you changed settings on your forks?

**Comment by emilymye** [comment]
I don't think I was given an option during the forking process so I don't think I changed it? I also didn't know actions were enabled on the repo until I got an email notification that they failed. I may try to test it out and reforking after I get this PR in, but it's probably not the highest priority :) I do still think it's a good idea to gate anything which requires credentials/calls to GCP.

**Comment by aaltay** [comment]
LGTM. Let's merge this. Thank you.

**Pull request merged**
