### PR TITLE
Updating dataflow API version to newer release.

### PR DESCRIPTION
**Pull request by pabloem**
r: @bjchambers 
This new release contains the changes to the Dataflow API protos for side input inter transform IO.

### CODE REVIEW

**Comment by pabloem** [comment]
retest this

**Comment by pabloem** [comment]
Retest this please

**Comment by bjchambers** [comment]
LGTM

**Comment by pabloem** [comment]
Commits have been squashed.

**Comment by bjchambers** [comment]
Retest this please

**Pull request merged**
