### PR TITLE
Fix Python3.7 PostCommit Azure integration test

### PR DESCRIPTION
**Pull request by Abacn**
Python3.7 PostCommit  Current failing with error
```
HttpResponseError(\'The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry.
If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch.
Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error.

RequestId:a37b6d7b-9698-45c1-a77c-e66a0e615a33
Time:2023-02-27T19:22:59.106Z
ErrorCode:InvalidHeaderValue\')}')}
```

recent update of blob-storage-client (https://pypi.org/project/azure-storage-blob/12.15.0/) likely bumped the azure API version and need azurite upgrade to run the integration test.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python3.7 PostCommit

**Comment by Abacn** [comment]
CC: @damccorm this also affects release-2.46.0 branch and causes Python3.7 PostCommit failing (checked https://ci-beam.apache.org/job/beam_PostCommit_Python37_PR/512/consoleText)

but I don't think it is a release blocker because this only affects test (azure-blob-storage. emulator)

**Comment by Abacn** [comment]
Run Python 3.7 PostCommit

**Comment by Abacn** [comment]
test succeeded:
```
test_1     | DEPRECATION WARNING: this will be an error in tox 4 and above!
test_1     | ___________________________________ summary ____________________________________
test_1     |   azure_integration_test: commands succeeded
test_1     |   congratulations :)
```

**Comment by Abacn** [comment]
Run Python_Runners PreCommit

**Comment by damccorm** [comment]
Run Python 3.7 PostCommit

**Comment by damccorm** [comment]
Python 3.7 postcommit may also fail due to https://github.com/apache/beam/pull/25661

**Review by damccorm — APPROVED** [review]
Failures are unrelated to this test, this pushes us towards green.

**Pull request merged**
