### PR TITLE
[BEAM-2345] Make versioning in root pom consistent.

### PR DESCRIPTION
**Pull request by jasonkuster**
Signed-off-by: Jason Kuster <jasonkuster@google.com>

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jasonkuster** [comment]
R: @dhalperi

**Comment by jasonkuster** [comment]
Main question -- should this be applied to maven version as well? I've done so, as you can see on last line (and another in the middle); sound good?

**Comment by dhalperi** [comment]
I do not think it's feasible to review this as-is. A few suggestions for improvement:

1. Please separate pure reorderings (alphabetization) with no believe semantic change in a separate commit from adding new ones.

2. Please keep plugin versions in a separate section from dependency versions, as in the current scheme.

3. Please ensure things like comments are preserved if you're moving versions -- e.g., the comment about keeping maven versions in sync seems to have been lost.

**Comment by davorbonaci** [comment]
Any updates?

**Comment by jasonkuster** [comment]
AIs here:
- Break into two commits at least -- alphabetization in the first, versioning fixes in the second.
- Create different sections for plugin and dependency versions (investigate whether this will be an actual XML separation or just comment blocks).

Dan's comment about the comments is I believe moot here -- the two numbers which had to be kept in sync are now just controlled by one version property, eliminating the possibility of becoming out of sync.

**Comment by davorbonaci** [comment]
Any updates?

**Comment by jasonkuster** [comment]
I've broken this into two changes -- alphabetization in the first, versioning fixes in the second. There are now sections for dependency and plugin versions.

PTAL @davorbonaci

**Comment by kennknowles** [comment]
Looks like this needs rebase

**Comment by aaltay** [comment]
@jasonkuster Is this PR still needed?

**Comment by reuvenlax** [comment]
ping

**Comment by reuvenlax** [comment]
@jasonkuster should we close this?

**Comment by dhalperi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/3205)*

**Comment by aaltay** [comment]
What are the next steps for this PR?

**Comment by aaltay** [comment]
I will close this PR based on the [stale](https://beam.apache.org/contribute/contribution-guide/#stale-pull-requests) PR policy, please reopen if you would like to continue working on it.

**Pull request closed without merging**
