### PR TITLE
[BEAM-12241] Update vendored bytebuddy to version 1.11.0

### PR DESCRIPTION
**Pull request by iemejia**
R: @kennknowles @reuvenlax

### CODE REVIEW

**Comment by reuvenlax** [comment]
Compile is failing. is this pr still waiting for the vendored bytebuy to be published?

**Comment by iemejia** [comment]
Yes exact, I should have waited to add you both as reviewers until ready. I just wanted to push it before I forgot.

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Spark Runner Nexmark Tests

**Comment by iemejia** [comment]
I did some local runs where I compared performance and I did not notice a remarkable change with even a tendency to be slightly faster with the upgraded bytebuddy, the Nexmark run is consistent with that, of course these are not proper JMH microbenchmarks of the like but it is what we have.

I did not notice any semantic change but it could be the case maybe that other circumstances will reveal this.
All green now so ready to review. PTAL @reuvenlax @kennknowles

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
