### PR TITLE
Improve Iterator error message

### LINKED ISSUE #23952: [Feature Request]: Error message about typehint missing an Iterator should be more informative
### What would you like to happen?

For example:
```
    output_batch_type = self.fn._get_output_batch_type_normalized(
  File "/tmp/tmp.PH23v4EA7w/venv/lib/python3.8/site-packages/apache_beam/transforms/core.py", line 828, in _get_output_batch_type_normalized
    self.get_output_batch_type(input_element_type))
  File "/tmp/tmp.PH23v4EA7w/venv/lib/python3.8/site-packages/apache_beam/transforms/core.py", line 872, in get_output_batch_type
    process_batch_type = self._get_element_type_from_return_annotation(
  File "/tmp/tmp.PH23v4EA7w/venv/lib/python3.8/site-packages/apache_beam/transforms/core.py", line 844, in _get_element_type_from_return_annotation
    raise TypeError(
TypeError: Expected Iterator in return type annotation for <bound method BatchedGenerateSamples.process_batch of <__main__.BatchedGenerateSamples object at 0x7f4bb1c88f70>>, did you mean Iterator[<class 'numpy.ndarray'>]?
```

This is pretty clear and actionable, but it could be a bit more informative. It could explain that Beam DoFns are one-to-N where N>=0, so they must always yield.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Fixes #23952

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
R: @pabloem

**Comment by pabloem** [comment]
lgtm

**Comment by TheNeuralBit** [comment]
Run Python PreCommit

**Comment by TheNeuralBit** [comment]
Run Python PreCommit

**Pull request merged**
