### PR TITLE
Do not skip latest blog entry from footer

### PR DESCRIPTION
**Pull request by bvolpato**
Fixes https://github.com/apache/beam/issues/26998.

### CODE REVIEW

**Comment by bvolpato** [comment]
Tested through  `./gradlew :website:serveWebsite`:

image

**Comment by riteshghorse** [comment]
Mostly looks like a bug because GCS staged website renders correctly without disturbing layout

**Comment by riteshghorse** [comment]
@Jakub-Sadowski

**Comment by bvolpato** [comment]
Layout is fine regardless of change, the difference is whether it will show up posts [0..1] or [1..2]

**Pull request merged**
