### PR TITLE
(No need to review) Testing v2.49.0 with gax 2.31.0, cloud spanner 6.43.2, grpc 1.55.3, guava 32.1.1-jre

### PR DESCRIPTION
**Pull request by burkedavison**
We are testing compatibility of gax 2.31.0, cloud spanner 6.43.2, grpc 1.55.3, guava 32.1.1-jre with Beam 2.49.0
This PR is just to check the CI status. **This PR does not need to be merged.**

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by suztomo** [comment]
@burkedavison This pull request hit Gradle's Guava version selection problem https://github.com/google/guava/issues/6642

```
00:01:59       > Module 'com.google.guava:guava' has been rejected:
00:01:59            Cannot select module with conflict on capability 'com.google.guava:listenablefuture:1.0' also provided by [com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava(runtime)]
00:01:59    > Could not resolve com.google.guava:guava:16.0.1.
00:01:59      Required by:
00:01:59          project :sdks:java:extensions:sql:jdbc > project :sdks:java:extensions:sql > project :sdks:java:io:parquet > org.apache.hadoop:hadoop-common:2.10.2 > org.apache.curator:curator-client:2.13.0
00:01:59       > Module 'com.google.guava:guava' has been rejected:
00:01:59            Cannot select module with conflict on capability 'com.google.guava:listenablefuture:1.0' also provided by [com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava(runtime)]
00:01:59 
```

**Comment by suztomo** [comment]
@burkedavison I was forgetting `-p` to specify a specific project. `suztomo@suztomo2:~/beam$ ./gradlew -p sdks/java/io/google-cloud-platform compileJava` . This avoids running `cd` many times.

**Comment by suztomo** [comment]
@burkedavison And the things named 'api', 'implementation', 'testImplementation' are called 'configuration' in Gradle. https://docs.gradle.org/current/userguide/declaring_dependencies.html

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by suztomo** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by suztomo** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by suztomo** [comment]
https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2_PR/201/console


```
20:57:17 * What went wrong:
20:57:17 Execution failed for task ':sdks:java:container:pullLicenses'.
20:57:17 > Process 'command './license_scripts/license_script.sh'' finished with non-zero exit value 1
```

**Comment by suztomo** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Run Java Postcommit

**Comment by suztomo** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by bvolpato** [comment]
FYI some of this was included here and is within scope for 2.50.0 https://github.com/apache/beam/pull/27725/

**Pull request closed without merging**
