### PR TITLE
[BEAM-13981] Remove Spark Runner specific code for event logging

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev 
CC: @ibzib 

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Go Spark ValidatesRunner

**Review by aromanenko-dev — APPROVED** [review]
LGTM since it fixes a problem with an empty event log. But what's about original issue stated in BEAM-11213 ?

**Comment by iemejia** [comment]
I understood it more like a user friendliness issue but since this broke metrics on Spark History Server I preferred to go straight to remove the behavior, because history server is more important.

**Pull request merged**
