### PR TITLE
[Website] update links from absolute to relative in md files

### PR DESCRIPTION
**Pull request by bullet03**
- update links from absolute path to relative one in md files
------------------------
after:
product_links
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
R: @aromanenko-dev, coould you, please help with review?

**Comment by aromanenko-dev** [comment]
@bullet03 What is a point of this change?

**Comment by aromanenko-dev** [comment]
@bullet03 Is it expected behaviour that it add `index.html` for relative links (see attached screenshot)? I didn't notice the same behaviour for absolute links as it was before? 
Also, if I drop `index.html` from the URL in browser, it got broken.

Screenshot 2022-12-27 at 16 12 52

**Review by aromanenko-dev — CHANGES_REQUESTED** [review]
Please, check if the old style links (without `index.html` in the end) are still working

**Comment by bullet03** [comment]
> @bullet03 Is it expected behaviour that it add `index.html` for relative links (e.g. see an attached screenshot)? I didn't notice the same behaviour for absolute links as it was before? Also, if I drop `index.html` from the URL in browser, it got broken.
> 
> Screenshot 2022-12-27 at 16 12 52

Had a consultation with devops from apache-beam. `index.html` is added to the end of the files in staging automatically. Links don't work without this part at the end only on staging. It worked like this before: here are some examples with staging from different PRs, one from December and another one from February. `index.html` part was present.

**Comment by bullet03** [comment]
> Please, check if the old style links (without `index.html` in the end) are still working

Since the path is relative, `index.html` in the end won't affect localhost or prod, just only staging.
For instance path like `/get-started/try-beam-playground/` will lead to `localhost:1313/get-started/try-beam-playground` on localhost, to `https://beam.apache.org/get-started/try-beam-playground` on production and to `http://apache-beam-website-pull-requests.storage.googleapis.com/24427/get-started/try-beam-playground/index.html` on staging.

Right now there are absolute links like `https://beam.apache.org/get-started/try-beam-playground` on both of 3 environments. If I  click on such a link on localhost, I won't get to another localhost page, but to production site instead.

**Review by aromanenko-dev — APPROVED** [review]
@bullet03 Thanks for verification! It would be great to have the same behaviour everywhere - locally, on staging and on production - for the future, if it's possible, of course, to avoid such confusion.

LGTM expecting that it just drops `https://beam.apache.org/` from absolute website links.

**Pull request merged**
