### PR TITLE
[BEAM-8129] Update Spark runner to use spark version 2.4.4

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by iemejia** [comment]
Merging, the failed Cassandra test is a well known flaky test. Thanks!

**Pull request merged**
