### PR TITLE
Revert "Replace StorageV1 client with GCS client"

### PR DESCRIPTION
**Pull request by damccorm**
Reverts apache/beam#25965 because it broke the Python PostCommits (https://ci-beam.apache.org/job/beam_PostCommit_Python311/358/ is the first failing run). This is the first successful PostCommit run for any python version since that PR was merged

### CODE REVIEW

**Comment by damccorm** [comment]
Run Python 3.10 PostCommit

**Comment by damccorm** [comment]
Run Python_Runners PreCommit

**Comment by damccorm** [comment]
R: @BjornPrime @Abacn

**Review by Abacn — COMMENTED** [review]
LGTM

Per discussion, #27390 should fix the specific issue in the description; but there is still internal test breakage. I am fine with revert for now and then do investigation

**Pull request merged**
