### PR TITLE
[BEAM-5519] Remove call to groupByKey in Spark Streaming

### PR DESCRIPTION
**Pull request by kyle-winkelman**
Prevent the duplication of encode/decode cycle in wasted call to groupByKey in spark streaming. It is a waste because after the groupByKey is a call to updateStateByKey which will ensure that the data is shuffled to the correct processing location.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kyle-winkelman** [comment]
I am not extremely confident in this code I just wanted to put something together to demonstrate my point. I also think there is some additional refactoring required such as renaming SparkGroupAlsoByWindowViaWindowSet.groupAlsoByWindow, but I would like to get some feedback before continuing.

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
This definitely seems like an improvement. Pinging @amitsela or @aviemzur in case they have some historical context on why this was done the way it was.

**Comment by kyle-winkelman** [comment]
I have also added some refactoring that we can take a look at I tried to group it logically by commits so we can pick and choose if we want.

**Comment by kyle-winkelman** [comment]
Any recommendations on how best to thoroughly test this? I have run validatesRunnerStreaming and the SparkCoGroupByKeyStreamingTest is functioning correctly, but I was wondering what additional steps I should take.

**Comment by amitsela** [comment]
Sure. Run on a cluster and make sure there's no shuffle on RDDs that contain deserialized data, otherwise the runner should use coders before/after a shuffle.

**Comment by iemejia** [comment]
I hadn't realized this one was auto-closed, we are still interested in this improvement @kyle-winkelman would you mind to re open it if you could validate it works. Thanks and sorry for not seeing this before.

**Comment by iemejia** [comment]
I just reopened it, but it needs a rebase @kyle-winkelman in case you still want to finish this.

**Comment by kyle-winkelman** [comment]
I would like to finish this because I think its an improvement, especially to readability. For my simple tests as well as those in validatesRunner everything appears to be working well.

One question I have is that I moved from mapPartitions to map in most places to improve readability and because it no longer is required to preserve partitioning (because we aren't doing groupByKey followed by updateStateByKey) as noted in these comments `// using mapPartitions allows to preserve the partitioner and avoid unnecessary shuffle downstream.` and `// we use mapPartitions with the RDD API because its the only available API that allows to preserve partitioning` . From my research this will not impact performance because we don't do any costly initialization in any of the `CoderHelpers` or `TranslationUtils` functions. Anyone have any reason not to do this?

**Comment by kyle-winkelman** [comment]
Any thoughts on naming and package for SparkGroupAlsoByWindowViaWindowSet (SparkStreamingGroupByKey)? And the naming for the method within (groupByKey)?

One thought was that groupByKey could instead be groupByKeyAndWindow.

**Comment by iemejia** [comment]
It seems this needs a rebase @kyle-winkelman. Apart of this is there anything other missing?
Asking @dmvk to please take a look too.

**Comment by kyle-winkelman** [comment]
@iemejia Rebased. I cannot think of anything left to do. If its possible to run performance tests before this is merged we could do that.

**Comment by dmvk** [comment]
Run Spark Run Spark ValidatesRunner

**Comment by dmvk** [comment]
Run Spark ValidatesRunner

**Comment by apilloud** [comment]
Is this ready?

**Comment by kyle-winkelman** [comment]
I never really got a review so I think the answer is no.

**Comment by kyle-winkelman** [comment]
@iemejia Did you want to review this? Can it be merged?

**Comment by iemejia** [comment]
You can find a rebased version of your PR here, please take a look, I added one extra commit to remove some stuff that it is now 'unused' after your PR. Or you can give me write access to your PR and I can push the changes if you prefer.
https://github.com/iemejia/beam/tree/review/BEAM-5519-spark-groupbykey-streaming

**Comment by kyle-winkelman** [comment]
I have spent a little bit of time trying to understand the Nexmark performance tests. I believe I have narrowed down the issue a little bit. The Nexmark BoundedEventSource splits based on the numEventsGenerator (which is 100). Before this PR, the first time there is a GroupByKey in these queries the RDD would be partitioned to the default parallelism (not 100). With this PR, the first time there is a GroupByKey in these queries the RDD would stay partitioned at 100. I believe this is what is affecting the performance. I would say we could accept this degradation in performance because in real use when we ask a Source to split itself in the way we asked. Unless there are a large number of sources that tend not to split well.

**Comment by iemejia** [comment]
Hello, have not forgotten about this one, just had nod had much time to think about what is going on. Pinging @ibzib too in case he can give us some idea9s). Btw this needs a rebase now, sorry.

**Comment by kyle-winkelman** [comment]
Rebased.

One other option I have come up with regarding the performance tests is to alter the Nexmark BoundedEventSource so that it splits properly. For example if it returns that the estimatedSizeBytes is 100 and the Spark Runner asks for desiredBundleSizeBytes of 10 then we split it into 10 equal pieces (instead of always splitting on numEventGenerators). This will unfortunately impact all batch performance numbers so I don't really want to do it, but it seems like it might be the best way.

**Comment by iemejia** [comment]
This is slightly staled but because of review discussion and should not be closed until we have some consensus.

**Comment by kyle-winkelman** [comment]
@iemejia I cleaned this up. Mainly just threw out the part where I was getting rid of the partitioner in batch mode, because [BEAM-7413](https://issues.apache.org/jira/browse/BEAM-7413) made me realize that approach would cause other issues.

**Comment by kyle-winkelman** [comment]
Run Spark ValidatesRunner

**Comment by kyle-winkelman** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by kyle-winkelman** [comment]
One other change that we can think about making now that we no longer need to preserve the partitioner. Just to clean things up and eliminate a possible source of confusion:
```
@@ -58,14 +58,9 @@ public class GroupCombineFunctions {
     JavaPairRDD<ByteArray, Iterable<byte[]>> groupedRDD =
         (partitioner != null) ? pairRDD.groupByKey(partitioner) : pairRDD.groupByKey();
 
-    // using mapPartitions allows to preserve the partitioner
-    // and avoid unnecessary shuffle downstream.
     return groupedRDD
-        .mapPartitionsToPair(
-            TranslationUtils.pairFunctionToPairFlatMapFunction(
-                CoderHelpers.fromByteFunctionIterable(keyCoder, wvCoder)),
-            true)
-        .mapPartitions(TranslationUtils.fromPairFlatMapFunction(), true);
+        .mapToPair(CoderHelpers.fromByteFunctionIterable(keyCoder, wvCoder))
+        .map(new TranslationUtils.FromPairFunction<>());
   }
```

**Comment by kyle-winkelman** [comment]
Yea in an intermediate commit I was attempting to remove the partitioner on defaultParallelism in GroupCombineFunctions...

**Comment by kyle-winkelman** [comment]
> One other change that we can think about making now that we no longer need to preserve the partitioner. Just to clean things up and eliminate a possible source of confusion:
> 
> ```
> @@ -58,14 +58,9 @@ public class GroupCombineFunctions {
>      JavaPairRDD<ByteArray, Iterable<byte[]>> groupedRDD =
>          (partitioner != null) ? pairRDD.groupByKey(partitioner) : pairRDD.groupByKey();
>  
> -    // using mapPartitions allows to preserve the partitioner
> -    // and avoid unnecessary shuffle downstream.
>      return groupedRDD
> -        .mapPartitionsToPair(
> -            TranslationUtils.pairFunctionToPairFlatMapFunction(
> -                CoderHelpers.fromByteFunctionIterable(keyCoder, wvCoder)),
> -            true)
> -        .mapPartitions(TranslationUtils.fromPairFlatMapFunction(), true);
> +        .mapToPair(CoderHelpers.fromByteFunctionIterable(keyCoder, wvCoder))
> +        .map(new TranslationUtils.FromPairFunction<>());
>    }
> ```

How do you feel about this change @RyanSkraba I was going to make this change as we no longer need to preseve the partitioner because the StreamingTransformTranslator no longer uses this method? And I think it cleans things up a little bit, but then you may need to rerun nexmark.

**Comment by RyanSkraba** [comment]
Sorry -- to be explicit, this LGTM (reviewed, compiled and tested locally) *and* the proposed change looks good too (reviewed only).  Go ahead and make the change!  I've got the nexmark setup ready to run if you want.

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by kyle-winkelman** [comment]
Run Spark ValidatesRunner

**Comment by kyle-winkelman** [comment]
First failed attempt for Spark ValidatesRunner looks unrelated to code change:
https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_PR/130/

**Pull request merged**
