### PR TITLE
Revert "[BEAM-5709] Changing sleeps to CountdownLatch in test"

### PR DESCRIPTION
**Pull request by youngoli**
Reverts apache/beam#8395

Seems like this change has caused the flakes to pop back up when they were previously gone.

### CODE REVIEW

**Comment by youngoli** [comment]
Example flake: https://builds.apache.org/job/beam_PreCommit_Java_Phrase/1056/testReport/org.apache.beam.runners.dataflow.worker.fn/BeamFnControlServiceTest/testClientConnecting/

**Comment by youngoli** [comment]
R: @boyuanzz @tvalentyn

**Comment by boyuanzz** [comment]
Just curious, will increasing timeout to a larger value help de-flaky?

**Comment by youngoli** [comment]
It might, but I'll test out that fix and make a new PR if it works. I don't want to block people waiting on the Precommit

**Comment by boyuanzz** [comment]
Run Python PreCommit

**Pull request merged**
