### PR TITLE
WIP: [BEAM-5798] Added "withTopicFn()" to set sink topics dynamically

### PR DESCRIPTION
**Pull request by aromanenko-dev**
Added `withTopicFn()` to set sink topics dynamically based upon contents of the data. 
It's not supported when `withEOS()` is using since we can't obtain exact number of all partitions in this case.

@rangadi please, take a look 
------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by aromanenko-dev** [comment]
Retest this please

**Comment by aromanenko-dev** [comment]
Retest this please

**Comment by lukecwik** [comment]
Just waiting on tests to pass, and will merge on green.

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by rangadi** [comment]
I don't think we want to merge this. @aromanenko-dev, could you confirm?

On the mailing list, we agreed that it is better to support writing ProducerRecords, which get all this flexibility and more.

**Comment by lukecwik** [comment]
@rangadi Thanks for pointing that out.

**Comment by aromanenko-dev** [comment]
@lukecwik Yes, we had a discussion about better solution with @rangadi on user mailing list (see: https://lists.apache.org/thread.html/a89d1d32ecdb50c42271e805cc01a651ee3623b4df97c39baf4f2053@%3Cuser.beam.apache.org%3E), so, I think I'll create another PR for this Jira. 
Sorry for inconvenience with that.

**Comment by lukecwik** [comment]
Closed PR as per authors comment.

**Pull request closed without merging**
