### PR TITLE
Align names with those produced by the dataflow runner harness.

### PR DESCRIPTION
**Pull request by robertwb**
These will be unused once the runner harness produces the correct
transform payloads.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
@kennknowles

**Comment by robertwb** [comment]
R: @kennknowles 

Jenkins: retest this please

**Comment by robertwb** [comment]
Jenkins: retest this please

**Comment by kennknowles** [comment]
On the other hand, the title should be "the Dataflow runner harness" so this is a move away from the SDK using the URNs that it should, and moving towards hardcoding for Dataflow.

**Comment by kennknowles** [comment]
Do you register both the OLD_RUNNER_HARNESS_PAR_DO_URN as well as the actual PAR_DO_URN?

**Comment by robertwb** [comment]
Yes, the actual PAR_DO_URN has been registered for a while (against code that actually expects the ParDo Payload).

**Comment by kennknowles** [comment]
SGTM

**Comment by aaltay** [comment]
Do we need this change in the release branch supporting python streaming on dataflow with the 2.2.0 release?

**Pull request closed without merging**
