### PR TITLE
[BEAM-11522] Revert "Optimizes extract_output for 1 element accumulator case."

### PR DESCRIPTION
**Pull request by tvalentyn**
Reverts apache/beam#13220

Context: https://github.com/apache/beam/pull/13220#issuecomment-750674335

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @y1chi @aaltay @pabloem

**Review by y1chi — APPROVED** [review]
LGTM. Thanks, Valentyn

**Review by aaltay — APPROVED** [review]

**Review by aaltay — APPROVED** [review]

**Comment by tvalentyn** [comment]
Seeing a strange linter flake:
```
17:33:08 apache_beam/dataframe/frames_test.py:1:0: F0002: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object (astroid-error)
```

**Comment by tvalentyn** [comment]
Run PythonLint Precommit

**Comment by tvalentyn** [comment]
Run PythonLint Precommit

**Pull request merged**
