### PR TITLE
Fix undefined name: StateSamplerInfo on line 58

### PR DESCRIPTION
**Pull request by cclauss**
__StateSamplerInfo__ definition copied from https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/worker/statesampler.py#L32-L34

flake8 testing of https://github.com/apache/beam

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./sdks/python/apache_beam/runners/worker/statesampler_slow.py:54:12: F821 undefined name 'StateSamplerInfo'
    return StateSamplerInfo(
           ^
```

### CODE REVIEW

**Comment by robertwb** [comment]
Perhaps this merits adding a test as well?

**Comment by cclauss** [comment]
#4610 is the test for finding regressions on this fix.

**Comment by cclauss** [comment]
Please retest this

**Comment by cclauss** [comment]
retest this please

**Comment by robertwb** [comment]
Though this is only a small amount of code, it seems odd to duplicate it. Is there a better common location to put it?

**Comment by cclauss** [comment]
Remove duplicate definition and switch to __from apache_beam.runners.worker.statesampler import StateSamplerInfo__.

**Comment by cclauss** [comment]
Retest this please

**Comment by cclauss** [comment]
Retest this please

**Comment by cclauss** [comment]
@robertwb Is this the solution you were looking for?

**Comment by robertwb** [comment]
Resolved merge conflicts. 

Jenkins: retest this please.

**Comment by cclauss** [comment]
No longer required.

**Pull request closed without merging**
