### PR TITLE
Use self hosted hadoop docker image in hdfsIntegrationTest

### PR DESCRIPTION
**Pull request by Abacn**
Fixes Python PostCommit current failing.

Tested locally:

```
test_1      | ___________________________________ summary ____________________________________
test_1      |   hdfs_integration_test: commands succeeded
test_1      |   congratulations :)
hdfs_it-non-jenkins_test_1 exited with code 0
Stopping hdfs_it-non-jenkins_datanode_1 ... 
Stopping hdfs_it-non-jenkins_namenode_1 ... 
Stopping hdfs_it-non-jenkins_datanode_1 ... done
Stopping hdfs_it-non-jenkins_namenode_1 ... done
Aborting on container exit...

real    2m16.029s
user    0m1.031s
sys     0m0.132s
+ finally
+ docker-compose -p hdfs_IT-non-jenkins down
Removing hdfs_it-non-jenkins_test_1     ... 
Removing hdfs_it-non-jenkins_datanode_1 ... 
Removing hdfs_it-non-jenkins_namenode_1 ... 
Removing hdfs_it-non-jenkins_datanode_1 ... done
Removing hdfs_it-non-jenkins_namenode_1 ... done
Removing hdfs_it-non-jenkins_test_1     ... done
Removing network hdfs_it-non-jenkins_test_net

real    0m0.759s
user    0m0.275s
sys     0m0.050s

BUILD SUCCESSFUL in 3m 19s
```

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python 3.10 PostCommit

**Comment by Abacn** [comment]
I also tried to bump the hadoop version to 3.x but it does not quite work. The test class cannot connect to the datanode. So the old version (2.8.1) is still used.

**Comment by Abacn** [comment]
R: @riteshghorse

**Review by riteshghorse — APPROVED** [review]
this is great! thanks Yi!

**Comment by Abacn** [comment]
PostCommit unrelated new failure. hdfsIntegrationTest passed

**Pull request merged**
