### PR TITLE
Revert "Reinstate proto round trip in Java DirectRunner" and fix masked errors in HBaseIOTest

### PR DESCRIPTION
**Pull request by kennknowles**
This reverts commit c0cb28c, which runs pipelines to proto and back for the direct runner. This introduced a severe performance degradation in the direct runner. It also seems to mask errors in stable names.

This supersedes #4609 by adding fixes for HBaseIO.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by jbonofre** [comment]
Thanks Kenn. I'm testing before merging.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
HBase tests are still failing. I'm taking a look.

**Comment by kennknowles** [comment]
Problem is the test methods are not isolated so the table names conflicted. https://issues.apache.org/jira/browse/BEAM-3637

**Comment by jbonofre** [comment]
Run Java Gradle PreCommit'

**Comment by jbonofre** [comment]
Run Java Gradle PreCommit

**Comment by kennknowles** [comment]
Looks like that did the trick.

**Comment by jbonofre** [comment]
Yes, just testing the perf on nextmark right now. I will merge just after.

**Comment by kennknowles** [comment]
Great. Be sure to also check #4621 for the release.

**Pull request merged**
