### PR TITLE
Speed up `IntervalWindow` argument construction

### PR DESCRIPTION
**Pull request by ryantam626**
In the original snippet, we create two instances of `Timestamp(micros=s)`, the later is rather short
lived as we immediately use the `__add__` dunder
method to create a brand new instance of `Timestamp`.

The change in this commit is to remove the construction of this short lived `Timestamp` and reuse the one already constructed for the `start` argument of `IntervalWindow`.

The speed gain of this change depends on the specification of the `SlidingWindows`. I have a pipeline that is relatively simple and with GCP's profiler in Dataflow, it revealed about ~2.5% of wall time is wasted in constructing this short lived `Timestamp`.

Given that `__add__` doesn't alter the `Timestamp` object inplace (and unlikely to be changed to that behaviour), I think this is a safe change.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

**This is just a oneliner change so I didn't bother, let me know if I should do any of the below.**

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
That's interesting finding, generally object creation of one or two should not make noticable difference, and Timestamp is light weight. This suggest the involved code path is a hot path, not limited to Timestamp creation.

Would you mind sharing more about the benchmark / codes that doing the test ?

**Comment by ryantam626** [comment]
> ... generally object creation of one or two should not make noticable difference, and Timestamp is light weight.

Yes I am surprised it showed up that prominently in the flamegraph we obtained as well.

> This suggest the involved code path is a hot path, not limited to Timestamp creation.

Smells like it!

> Would you mind sharing more about the benchmark / codes that doing the test ?

I can try - the pipeline we have is not really a benchmark, but rather a production-ish pipeline that we use for analysing our data, the first few steps goes like this

1. Read from a BigQuery query which returns a sparse minutely summary from data collection devices
2. Assign timestamp using the summary's timestamp (already in the minute level resolution)
3. Window into using a SlidingWindows, 30 days window size, 1 day increment.
4. Unrelated (to this ticket) steps that analyse patterns follows.

--------

I am curious to know if you have spotted any inefficiency in these first few steps.

We have since made some improvement to our pipeline which incidentally side-stepped this slowness [1], but regardless I thought this change would be a nice addition seeing as it's almost a risk-free change which supposedly improve performance.

[1] We went for a sliding window specification of 90 days window size, 30 days increment, trading extra memory usage (and small amount of correctness in our pipeline) for speed - as each minutely summary will only need to go into 3 bucket instead of 30 buckets under this sliding window specification.

**Review by Abacn — APPROVED** [review]
Thanks!

It is good that the colon operator introduced in Python 3.8, which is the lowest supported py version for beam now

**Comment by Abacn** [comment]
Run Python_Runners PreCommit

**Pull request merged**
