### PR TITLE
[BEAM-1511] Add wildcard import back again.

### PR DESCRIPTION
**Pull request by aaltay**
R: @jbonofre

### CODE REVIEW

**Comment by jbonofre** [comment]
Thanks, reviewing ;)

**Comment by aaltay** [comment]
Context: During the previous refactoring PR, I removed an import, I thought was unused. That was not the case. I verified this PR with one test, but have not run the full post commit locally.

**Comment by jbonofre** [comment]
I will merge as soon as Jenkins and Travis pass.

**Comment by sb2nov** [comment]
LGTM, where is this used ?

**Comment by aaltay** [comment]
Thank you @jbonofre. (Jenkins passed, Python parts of the Travis passed, and I ran a few more post commit tests locally.)

@sb2nov Used here: https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/google_cloud_dataflow/internal/apiclient.py#L389

**Comment by jbonofre** [comment]
OK, thanks for the merge (I planned to do it tonight anyway).

**Pull request closed without merging**
