### PR TITLE
Website update keywords table

### PR DESCRIPTION
**Pull request by bullet03**
Resolves https://github.com/apache/beam/issues/24194 https://github.com/apache/beam/issues/24193
- add `table-wrapper--equal-p` class to css in order to make tables 3rd column content not to stand out from other columns content and to make space between columns
- add `table-wrapper--pr` class to css to create space between 2 columns
- remove redundant styles from tables
- pages:
https://beam.apache.org/documentation/dsls/sql/extensions/create-external-table/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/lexical-structure/index.html
https://beam.apache.org/documentation/dsls/sql/calcite/data-types/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/conditional-expressions/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/conversion-rules/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/math-functions/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/query-syntax/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/data-types/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/operators/index.html
https://beam.apache.org/documentation/dsls/sql/zetasql/lexical/index.html
https://beam.apache.org/documentation/runners/nemo/index.html
https://beam.apache.org/documentation/programming-guide/index.html
https://beam.apache.org/get-started/from-spark/index.html
------------------------
before:
before_keywords_1
before_keywords_2
before_keywords_3
before_keywords_4
before_keywords_5
before_table_class
after:
after_1
after_2
after_3
after_table_class
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please help with review?

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM

**Comment by bullet03** [comment]
> Thanks, LGTM

Thank you!

**Pull request merged**
