### PR TITLE
[BEAM-3925] [DO NOT MERGE] KafkaIO : Value provider support for reader configuration. 

### PR DESCRIPTION
**Pull request by rangadi**
ValueProvider support for KafkaIO reader configuration (input topics & bootstrap servers).
[NOTE: This is not meant for merge into master yet]

This enables users to write Dataflow templates using KafkaIO.

The main funcational changes is that partition information for topics is fetched at runtime by each of the source splits just before reading. This is required since Kafka topic names and cluster configuration may not be available at graph construction time.

This implies that we cannot adjust number of splits based on number of Kafka partitions. In order to get around this limitation this lets users explicitly specify number of splits (`withNumSplits()`). We can handle this better if we can let some splits not to have any partitions assigned at runtime. We need to something like that to be able to merge this into master. 

For now, this PR will serve as good starting point for developing templates with KafkaIO.
[cc: @azurezyq, @pupamanyu]

### CODE REVIEW

**Comment by davidheryanto** [comment]
Hi @rangadi, any reason why this is not merged to the master branch?
Is it because it is not fully tested or is there any other concerns?

I see it has been merged here
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/kafka/connector/KafkaIO.java

Our deployment kind of needs this functinonality of specifying Kafka brokers at runtime using Dataflow templates.

**Comment by pseudomuto** [comment]
@rangadi would you be able to clarify why this was closed? Similar to @davidheryanto above, we're also trying to find a way to support ValueProvider options with KafkaIO, and it would be great to not have to maintain a separate connector if possible.

**Comment by rangadi** [comment]
@pseudomuto @davidheryanto : The main issue we need to address is proper support for `.numSplits()` interface. If user sets `numSplits` to 20 and Kafka topic has only 5 partitions, 15 splits (`readers`) will not have any work. We just need to handle that properly. I don't think it is that much more work. 
cc: @aromanenko-dev.

**Comment by aromanenko-dev** [comment]
> We just need to handle that properly. 
@rangadi Do you mean that we just need to shrink the number of split accordingly in this case to avoid empty splits in runtime?

**Comment by rangadi** [comment]
It might be a bit more than than 'just' :)
We can't shrink the splits since the compute graph is already constructed, I think. We would know only inside the reader during reader initialization what the total number of partitions we need to consumer. Each reader has to decide which partitions to consume based on reader id.

**Comment by aromanenko-dev** [comment]
Ok, I see. Thanks!

**Comment by davidscottturner** [comment]
Hi, is there any more progress on supporting Value provider? I've just hit the snag of this while trying to create a Dataflow template as well.

**Comment by aromanenko-dev** [comment]
@davidscottturner I'm not aware of if anyone works on this.

**Comment by pseudomuto** [comment]
FWIW, [Flex templates](https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates) bypass the requirement to use ValueProvider options in your pipelines (current in beta though)

**Comment by samle-ovo** [comment]
@pseudomuto : I dont think it helps. Flex templates requires people to write description of the pipeline manually. It is not really idea situation at all. @rangadi : Can we just change the numSplits to numPartitions ? Everything will be much clearer and people will not set not correct number.

**Comment by chamikaramj** [comment]
I agree with @pseudomuto. I think Flex templates allow using templates without adding ValueProviders by running the pipeline from a container. May be the pipeline you are trying to use is just not available as a Flex template yet ?

**Comment by samle-ovo** [comment]
@chamikaramj yeah, I check it again. It should help. For me at first, it is difficult to follow Google documents. They did not explain how to write the template file, it makes everything a bit confused. The Docker part is no brainer. @pseudomuto : Sorry, I take everything I said back :D

**Pull request closed without merging**
