### PR TITLE
[release-2.18.0][BEAM-8861] Disallow self-signed certificates by default in ElasticsearchIO

### PR DESCRIPTION
**Pull request by iemejia**
This is the cherry-picked mentioned in the ML
R: @udim

### CODE REVIEW

**Comment by udim** [comment]
Run Java PreCommit

**Comment by udim** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by udim** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by udim** [comment]
@iemejia Java_Examples_Dataflow is consistently timing out (3 last attempts). Could you investigate?

**Comment by iemejia** [comment]
Arrghh I screwed this one accidentally now. Damn, will cherry-pick again sorry.

**Comment by iemejia** [comment]
superceded by #10353

**Pull request closed without merging**
