### PR TITLE
[BEAM-8616] Make hadoop-client a provided dependency on ParquetIO

### PR DESCRIPTION
**Pull request by iemejia**
See the JIRA issue for the motivation on this.

R: @lgajowy

### CODE REVIEW

**Comment by lgajowy** [comment]
Run Java PreCommit

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by lgajowy** [comment]
Run Java ParquetIO Performance Test

**Comment by lgajowy** [comment]
Just run the ParquetIO test to be 100% sure but in general LGTM. Thanks!

**Comment by lgajowy** [comment]
Revert due to failing sql postCommit tests: https://github.com/apache/beam/pull/10087

**Pull request merged**
