### PR TITLE
[BEAM-1036] Support for new State API in streaming mode of FlinkRunner

### PR DESCRIPTION
**Pull request by JingsongLi**
Sorry, my configuration is a bit wrong again. zhixin.ljs is me.
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by JingsongLi** [comment]
@aljoscha Please take a look.

**Comment by kennknowles** [comment]
Running Flink postcommit here: https://builds.apache.org/view/Beam/job/beam_PostCommit_Java_RunnableOnService_Flink/1497/

**Comment by aljoscha** [comment]
I took a look and the code looks good!

@kennknowles The test failed in `BeamFnLoggerClientTest`, is this a known flaky test right now? (I think it's in Luke's new Fn API proposal package)

**Comment by kennknowles** [comment]
The code in question was not green on Travis when it was merged. I haven't tried to track down if it was ever green. You shouldn't block anything on the Fn harness prototype.

**Comment by aljoscha** [comment]
@JingsongLi I'll change the commit to refer to your "outside name" (JingsongLi <lzljs3620320@aliyun.com>) right?

**Comment by JingsongLi** [comment]
@aljoscha Yes.

**Comment by aljoscha** [comment]
Merged. Thanks for your work! 👍

**Pull request closed without merging**
