### PR TITLE
Forward integrate from `master` to `DSL_SQL`

### PR DESCRIPTION
**Pull request by davorbonaci**
This fixes Python SDK lint issue in the `DSL_SQL` branch.

R: @XuMingmin

### CODE REVIEW

**Comment by XuMingmin** [comment]
[Build 9694](https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/9694/) ends as status _unstable_, see failures in module `Apache Beam :: Runners :: Spark`

Will follow with more build instances.

**Comment by XuMingmin** [comment]
LGTM
[Build 9696](https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/9696/) was finished successfully. 

@davorbonaci  please help with the merge.

**Comment by davorbonaci** [comment]
Merging in progress (with @dhalperi).

**Comment by dhalperi** [comment]
```
git fetch --all
git checkout apache/DSL_SQL
git merge --no-ff -m "This closes #2584" github/pr/2584
git push apache HEAD:DSL_SQL
```

**Comment by XuMingmin** [comment]
Thanks @davorbonaci  @dhalperi

**Pull request merged**
