### PR TITLE
[BEAM-3043] Set user-specified PTransform names on Flink operators

### PR DESCRIPTION
**Pull request by grzegorz8**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by grzegorz8** [comment]
The names displayed in Flink UI have been slightly improved. Some examples below:

Batch before:
batch-before
Batch after:
batch-after

Streaming before:
stream-before
Streaming after:
stream-after

**Comment by kennknowles** [comment]
Nice. Also FYI @bsidhom.

**Comment by aljoscha** [comment]
retest this please

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by geojins** [comment]
Nice improvement. 
@aljoscha , does this change also set the unique id to operators which are in turn used for checkpointing stateful operators.

**Comment by aljoscha** [comment]
@geojins No, it doesn't but that's a very good point. Is there an open issue for that?

**Comment by aljoscha** [comment]
retest this please

**Comment by aljoscha** [comment]
@grzegorz8 If you want, you could open an issue for setting the uid on Flink operators

**Comment by grzegorz8** [comment]
I'm not quite sure, but I think that this strange `-&gt;` is a Flink's issue, not Beam's one. I saw it in "regular" Flink jobs as well.

When it comes to operator uids, I've created a corresponding jira task: https://issues.apache.org/jira/browse/BEAM-3800

**Pull request merged**
