### PR TITLE
Update Java expansion service to use distroless

### PR DESCRIPTION
**Pull request by damccorm**
This will drive down the number of vulnerabilities in this container and the expansion container shouldn't be relying on other things here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @chamikaramj

**Comment by damccorm** [comment]
Failing workflow (windows java tests) is currently permared

**Comment by chamikaramj** [comment]
LGTM. Thanks!

**Comment by Abacn** [comment]
the switch somehow introduced more vulneribility alerts

image

**Comment by damccorm** [comment]
> the switch somehow introduced more vulneribility alerts
> 
> image

Looks like maybe they aren't keeping this image up to date then? https://pantheon.corp.google.com/artifacts/docker/distroless/us/gcr.io/java?e=13802955&mods=-ai_platform_fake_service

**Comment by Abacn** [comment]
gcr.io/distroless/java:11 appears to use old system and java versions. There are multiple vulneribilities come from OS and openjdk. The original gcr repository does not have vulnerability scan enabled. However, doing a pull then push to a repo that enabled vulnerability scan indeed reports multiple vulneribilities:

gcr.io/google.com/clouddfe/yathu/distroless/java:11

**Comment by damccorm** [comment]
> gcr.io/distroless/java:11 appears to use old system and java versions. There are multiple vulneribilities come from OS and openjdk. The original gcr repository does not have vulnerability scan enabled. However, doing a pull then push to a repo that enabled vulnerability scan indeed reports multiple vulneribilities:
> 
> gcr.io/google.com/clouddfe/yathu/distroless/java:11

Yeah, agreed - I'm going to revert here, seems like this is not a viable path unless we upgrade our java version (not sure if that will help or not)

**Comment by Abacn** [comment]
it appears the repo has renamed to gcr.io/distroless/java11. The latest one has fewer vulnerabilities:

image

**Comment by damccorm** [comment]
> it appears the repo has renamed to gcr.io/distroless/java11. The latest one has fewer vulnerabilities:
> 
> image

I'm still inclined to revert since I think that is still worse than our current base

**Pull request merged**
