### PR TITLE
[BEAM-123] [BEAM-544] Add support for reading/writing headers to text files. Also adds a tell() method to fileio._CompressedFile.

### PR DESCRIPTION
**Pull request by sbilac**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by sbilac** [comment]
@robertwb

**Comment by sbilac** [comment]
See https://github.com/apache/beam/pull/1771 for previous instantiation of this PR.

**Comment by robertwb** [comment]
Thanks, LGTM.

**Comment by robertwb** [comment]
Looks like there's a merge conflict. Could you rebase?

**Comment by robertwb** [comment]
I'm seeing some errors: https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/7200/org.apache.beam$beam-sdks-python/consoleFull

**Comment by sbilac** [comment]
Tests are passing locally and I was able to merge the recent refactor of TextFileSink so we should be ready to merge now.

**Pull request closed without merging**
