### PR TITLE
Reapply "[#30789] Add support for Flink 1.18 (#31062)"

### PR DESCRIPTION
**Pull request by je-ik**
Reintroduce Flink 1.18 support.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by shunping** [comment]
+ @Abacn

**Comment by je-ik** [comment]
I don't think we should merge this as is. It would likely cause the same issues, because the underlying issue is not resolved.

**Comment by je-ik** [comment]
I was able to generate the `pom.xml` that is used in the test. The following command generates it into `word-count-beam`:
```bash
mvn archetype:generate \
  --update-snapshots \
  -DarchetypeGroupId=org.apache.beam -DarchetypeArtifactId=beam-sdks-java-maven-archetypes-examples \
  -DarchetypeVersion=2.57.0-SNAPSHOT \
  -DgroupId=org.example \
  -DartifactId=word-count-beam \
  -Dversion="0.1" \
  -Dpackage=org.apache.beam.examples \
  -DinteractiveMode=false
```

It needs to have apache snapshots repository configured in `~/.m2/settings.xml`. Now the issue is that in the current version, the generated pom references `beam-runners-flink-1.17`, while the gradle task runs on `1.18`. Because the archetype is updated asynchronously from the test, we should probably wait before the updated archetype is deployed?

There also seems to be some discrepancy in the release process of the archetype. Running the above command with `-DarchetypeVersion` set to 2.56.0 generates `pom.xml` with `<beam.version>2.55.0</beam.version>` which is likely a bug.

**Comment by je-ik** [comment]
The problem seems to be related to classloading. When running the test using `mvn exec:java` I can see the code (sometimes) tries to load flink-related classes using AppClassLoader (which contains only `apache-maven-3.8.4/boot/plexus-classworlds-2.6.0.jar`). Maven exec plugin created URLClassLoader, which contains all the required dependencies, but that is _sometimes_ not used. I can see it is used for loading *some* classes. This is very likely Flink bug (1.18).

I'll see if I can change the test to run using `mvn exec:exec`, with correct classpath.

**Comment by je-ik** [comment]
@Abacn [this][1] fixes the issue with the test. 

 [1]: https://github.com/apache/beam/pull/31328/commits/c4ea518a247f325ade7c094c1d4d1d69c3671a6c

**Review by Abacn — APPROVED** [review]

**Pull request merged**
