### PR TITLE
[BEAM-9557] Fix timer window boundary checking

### PR DESCRIPTION
**Pull request by reuvenlax**
R: @steveniemitz

### CODE REVIEW

**Comment by steveniemitz** [comment]
can we add a unit test to validate this behavior as well?

**Comment by amaliujia** [comment]
Run Java PreCommit

**Comment by amaliujia** [comment]
This failed test might be relevant to this PR: org.apache.beam.sdk.transforms.ParDoTest$TimerTests.testOutOfBoundsEventTimeTimer

**Comment by reuvenlax** [comment]
@amaliujia appears that test looks for specific strings in the exception (always a recipe for a brittle test). I changed "event time timer" to "event-time timer" which broke that test. Will fix.

**Comment by aaltay** [comment]
> @amaliujia appears that test looks for specific strings in the exception (always a recipe for a brittle test). I changed "event time timer" to "event-time timer" which broke that test. Will fix.

Agreed, it is brittle test.

@reuvenlax are you planning to fix the test, or could @amaliujia send a fixup commit here to change "event-time" to "event time"? This is only release blocking issue currently, I would like to unblock it sooner.

**Comment by reuvenlax** [comment]
@aaltay fixing this now

**Comment by reuvenlax** [comment]
@aaltay added new unit tests and fixed the broken one. However I'm noticing that test triggering seems broken on a number of PRs now. Is something wrong with the Jenkins master?

**Comment by aaltay** [comment]
> @aaltay added new unit tests and fixed the broken one. However I'm noticing that test triggering seems broken on a number of PRs now. Is something wrong with the Jenkins master?

Yes. Ongoing issue. @yifanzou is working on it. Repeating the test triggers a few times usually helps.

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
retest this please

**Comment by reuvenlax** [comment]
@steveniemitz tests added

**Comment by steveniemitz** [comment]
looks great!  These tests will be really helpful to ensure we don't have more regressions in the future.  Thanks!

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
@aaltay Has part of this change already been merged to master? I notice that SimpleDoFnRunner.java at head already contains these changes, but the unit tests are not it.

**Comment by steveniemitz** [comment]
it looks like #11252 was merged instead of this one.

**Comment by reuvenlax** [comment]
I see. We should still merge this so we get the unit-test coverage.

**Comment by amaliujia** [comment]
LGTM

**Comment by amaliujia** [comment]
@reuvenlax 

do you need help on the failed java tests?

**Pull request merged**
