### PR TITLE
[BEAM-1644] Move PipelineOptions for IO ITs into shared location.

### PR DESCRIPTION
**Pull request by ssisk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
* creates a common directory for IO 
* moves the current pipeline options (which are spread out into separate directories) into that common directory.

This is is useful/necessary because:
1. In order to run all the IO ITs in one run, they have to have a shared set of pipeline options - options on the command line but not present in the PipelineOptions being used to read them will cause an error
2. Data stores may be accessed in different IO modules, but should share common command line options - having them in a common directory makes that easier.

### CODE REVIEW

**Comment by ssisk** [comment]
cc @echauchot @jbonofre - mind taking a look? 
This is part one, I also want to move the kubernetes scripts into a shared place.

**Comment by jbonofre** [comment]
@ssisk Thanks ! Sure, gonna take a look later today !

**Comment by echauchot** [comment]
@ssisk, cool! I will take a look at this

**Comment by echauchot** [comment]
LGTM

**Comment by jbonofre** [comment]
@ssisk can you state pros/cons of having:
1. the `PipelineOptions` in each IO (providing integration tests)
vs
2. all options in a "big" `PipelineOptions`.

This module will also contain the Kubernetes scripts, right ? It's the "global" common-io-it shared by any IO providing integration tests.

This work as soon as we release all IOs and common-io-it in a row (in  the same release). If later, we go in a way where we will do individual release of each IO, this approach could be painful.

**Comment by ssisk** [comment]
PipelineOptions in each IO:
Pros: no additional benefits that I know (you may have some ideas on this from your experience on other apache projects - please let me know! Remember that we'd still want to do shared test runs)
Cons: 
* options on the command line but not present in the PipelineOptions being used to read them will cause an error (we could in theory remove this error)
* encourages code copying/different command line options even when using the same data store (eg what happens with elasticsearchio and hifio's elasticsearch)


Shared Big PipelineOptions: 
pros/cons are the inverse of the last.

>This module will also contain the Kubernetes scripts, right ?
correct. 

> If later, we go in a way where we will do individual release of each IO, this approach could be painful.
Can you explain that a bit more? I'm guessing you're referring to the idea that the individual IOs would all need to share the common-io-it. It seems like in that world they could still share a test jar. Is that bad?

**Comment by jbonofre** [comment]
Fair enough. Just wanted to double check.

**Comment by ssisk** [comment]
great! thank you. I fixed the new merge conflicts.

**Pull request closed without merging**
