### PR TITLE
Increment the Dataflow container version

### PR DESCRIPTION
**Pull request by swegner**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

This is necessary to enable new Dataflow features in the worker container.

### CODE REVIEW

**Comment by swegner** [comment]
R: @lukecwik 

Executing runner validation tests now via:
```
mvn clean && mvn install -T1C -DskipTests && mvn install -Pvalidates-runner-tests -f runners/google-cloud-dataflow-java
```

**Comment by swegner** [comment]
FYI, the tests all fail with:

```
java.lang.IllegalStateException: The test was annotated with a [@NeedsRunner] / [@ValidatesRunner] while the runner was set to [CrashingRunner]. Please re-check your configuration.
```

What is the correct command to run these tests?

**Comment by lukecwik** [comment]
Use the Jenkins git labels to run a Jenkins job.

**Comment by lukecwik** [comment]
Run Java Gradle Precommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by swegner** [comment]
Run Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
DataflowRunner is happy.

**Pull request merged**
