### PR TITLE
[BEAM-6237] Fix ULR not deleting artifacts after running jobs.

### PR DESCRIPTION
**Pull request by youngoli**
This change switches the ULR from using LocalFileSystemArtifact[Stager/Retrieval]Service to using BeamFileSystemArtifact[Staging/Retrieval]Service which has functionality to remove artifacts after running a job. With this change ValidatesRunner tests no longer leave huge amounts of artifacts when run with the ULR.

Other code had to be changed to allow this switch. In particular, the old code would store the path to the staged files after creating the staging service. This code instead stores an artifact staging session token, to keep track of a specific staging session (since the job server may have multiple staging sessions from different jobs). The new code also has changes to correctly pass the artifact retrieval token (passed to the ReferenceRunner as part of a RunJobRequest) to the BeamFileSystemArtifactRetrievalService.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by youngoli** [comment]
The Java PreCommit failure seems unrelated to this PR so I'll send it out for review regardless.

R: @HuangLED

**Comment by youngoli** [comment]
Run Java PreCommit

**Comment by youngoli** [comment]
Run Java PreCommit

@swegner for merging when you have time.

**Comment by swegner** [comment]
The java precommit failure is a known issue. I believe this is ok to merge.

**Pull request merged**
