### PR TITLE
Workaround for Jenkins DSL Sandboxing

### PR DESCRIPTION
**Pull request by jasonkuster**
Signed-off-by: Jason Kuster <jasonkuster@google.com>

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by jasonkuster** [comment]
This PR has been changed to copy the contents of common_job_properties.groovy into each job as a build step.

**Comment by jasonkuster** [comment]
Run Seed Job

**Comment by jasonkuster** [comment]
R: @davorbonaci

**Comment by davorbonaci** [comment]
Obsolete? Close?

**Pull request closed without merging**
