### PR TITLE
[BEAM-3817] Switch Go SDK BQ write to not use side input

### PR DESCRIPTION
**Pull request by herohde**
Otherwise, it does not do currently run on non-direct runners. Also consolidated the use of adding a fixed key for this purpose.

### CODE REVIEW

**Comment by herohde** [comment]
R: @lostluck

**Comment by herohde** [comment]
R: @bbassingthwaite-va

**Comment by herohde** [comment]
Thanks!

R: @robertwb

**Comment by herohde** [comment]
@robertwb Done. PTAL

**Comment by herohde** [comment]
@robertwb Any concerns about merging?

**Comment by robertwb** [comment]
Looks good, thanks.

**Comment by herohde** [comment]
Thanks!

**Pull request merged**
