### PR TITLE
BEAM-3863: AfterProcessingTime trigger firing at delayedUntil time

### PR DESCRIPTION
**Pull request by pbartoszek**
The issue with the current logic is that if `delayedUntil` timestamp is equal to the current time when `shouldFire` method is called than `shouldFire` method returns false and trigger doesn't fire and  never fires again unless there is some new element for the the same <key, window> or allowed lateness is hit. In reality when I tested with Flink runner on a cluster it's very likely on the powerful enough machines that it's actually the same millisecond timer fires at `delayedUntil` timestamp and  calls a method `public void onTimers(Iterable<TimerData> timers) throws Exception` from `ReduceFnRunner` and the time current time is probed via `getCurrentTime(context)` in `AfterDelayFromFirstElementStateMachine.shouldFire()` method. The suggested fix is to check if current timestamp is equal or greater than `delayedUntil` timestamp.

I created a test job that replicates the issue: https://github.com/pbartoszek/BEAM-3863_late_trigger 

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by pbartoszek** [comment]
As suggested by @aljoscha another way to fix the issue from Flink runner only would be to 
change the logic in toFlinkRuntimeWatermark method [here](https://github.com/apache/beam/blob/6e4de883efc5e3cb2278d9f2be5ab94e33cf1bf8/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L606)

**Comment by pbartoszek** [comment]
As suggested by @aljoscha the other way to fix this for Flink runner only would be to add 1 ms when registering a timer in Flink. + 1ms could be done for instance [here]( https://github.com/apache/beam/blob/6e4de883efc5e3cb2278d9f2be5ab94e33cf1bf8/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1051)

**Comment by aljoscha** [comment]
I would be in favour of fixing this on the Flink side, because there is a mismatch in what Flink thinks when a timer should fire. As highlighted by https://github.com/apache/beam/blob/6e4de883efc5e3cb2278d9f2be5ab94e33cf1bf8/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L606

**Comment by robertwb** [comment]
Should we close this PR if it was fixed on the Flink side.

**Comment by aljoscha** [comment]
@robertwb (and also @pbartoszek) when I said "Flink Side" I meant Flink Runner. We can't easily change the way Flink timers behave but we can adapt in the Flink Runner similarly to how we do it for event-time timers.

**Comment by aljoscha** [comment]
Basically the other option that @pbartoszek mentioned above.

**Comment by mxm** [comment]
It seems like this could be easily fixed by correctly converting the Beam timestamp into a Flink timestamp.

**Pull request closed without merging**
