### PR TITLE
[BEAM-9324] Fix incompatibility of direct runner with cython

### PR DESCRIPTION
**Pull request by Abacn**
This is due to `Cython.Shadow.cast(Receiver, value)` attempting to run Receiver(value) (probably very old code in Python 2 age where "old" class did not have `__call__`)

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python PreCommit

**Comment by Abacn** [comment]
R: @TheNeuralBit
R: @robertwb

**Comment by TheNeuralBit** [comment]
I've seen the errors from BEAM-9324 `TypeError: Receiver() takes no argument` before when I've got my build into an inconsistent state (some files Cythonized, some not). I wonder if there's a build system change we can make to help avoid this situation rather than branching throughout the code?

**Comment by TheNeuralBit** [comment]
Ah ok, one last question from me: should we remove this when/if cython 3 is out and we upgrade it? If so let's file a jira and maybe add TODOs.

**Comment by Abacn** [comment]
> Ah ok, one last question from me: should we remove this when/if cython 3 is out and we upgrade it? If so let's file a jira and maybe add TODOs.

Added TODO. used this jira for reference since Cython3 may still be pending in nearly future and thus not filing a ticket at this moment.

**Comment by TheNeuralBit** [comment]
Run Python PreCommit

**Comment by TheNeuralBit** [comment]
Run PythonDocker PreCommit

**Review by TheNeuralBit — APPROVED** [review]
Thanks!

**Pull request merged**
