### PR TITLE
Add TrafficRoutes Java IT

### PR DESCRIPTION
**Pull request by boyuanzz**
TrafficRoutesIT runs with dataflow runner in Java PostCommit.

R: @pabloem 
cc: @aaltay

### CODE REVIEW

**Comment by boyuanzz** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
This is a streaming pipeline. How are you passing data to it?

**Comment by boyuanzz** [comment]
Re: @pabloem 

the [pipeline](https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/complete/TrafficRoutes.java#L323) reads from a [input file](https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/complete/TrafficRoutes.java#L323) and uses [ExampleUtils](https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/complete/TrafficRoutes.java#L378) to stop the injector.

**Comment by boyuanzz** [comment]
Run Java PostCommit

**Comment by boyuanzz** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
LGTM. Thanks Boyuan.

**Comment by boyuanzz** [comment]
Re: @pabloem 
Reverted build file changes and squashed all commits into one. This PR is ready to merge. Thanks~

**Pull request merged**
