### PR TITLE
[BEAM-2166] Cherry-pick #2930 and #2933 onto release-2.0.0

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @lukecwik, @davorbonaci

**Comment by robertwb** [comment]
This requires new workers, Jenkins is happy otherwise.

**Comment by lukecwik** [comment]
Looks equivalent to PR #2930 and #2933 on apache/master

**Comment by lukecwik** [comment]
Merged, please close at your leisure

**Pull request closed without merging**
