### PR TITLE
[Beam-26692] Add implementation and tests for bypassFilesToStage option

### PR DESCRIPTION
**Pull request by Zawa-ll**
**Please** add a meaningful description for your change here

This change addresses issue #26692 by adding support for HDFS and bypassing the FilesToStage feature in the Apache Beam pipeline. The modifications include:

Adding a new option bypassFilesToStage in FileStagingOptions to allow users to enable or disable the bypassing of FilesToStage.
Updating the Pipeline class to handle the new option and apply it during pipeline execution.
Adding tests in PipelineTest to verify the functionality of the bypassFilesToStage option.
Key changes:

FileStagingOptions: Added getBypassFilesToStage and setBypassFilesToStage methods.
Pipeline: Modified run method to set bypassFilesToStage based on the provided options.
PipelineTest: Added tests to verify both enabled and disabled states of the bypassFilesToStage option.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by liferoad** [comment]
Please fix the precommit errors.

**Comment by Zawa-ll** [comment]
> Please fix the precommit errors.

Sure! Changes are on its way :)

**Comment by Abacn** [comment]
What is the need of this pipeline option here? There is a `--fileToStage` pipeline option, is that not working with HDFS?

**Comment by Zawa-ll** [comment]
> ~What is the need of this pipeline option here? There is a `--fileToStage` pipeline option, is that not working with HDFS?~
> 
> I see, it is #26692

Hi @Abacn! Thank you for your response!

The --fileToStage option has limitations with HDFS. When executing a Beam pipeline over Spark structured streaming on YARN, it failed because HDFS Compatibility, since FilesToStage uses Java IO, which doesn't support HDFS.

If you check #26692, this changes will addresses these issues for better HDFS compatibility.

**Comment by Abacn** [comment]
rather than introduces another pipeline option, is it possible to just use empty `--fileToStage=[]` option? If this is Spark specific could we refrain from changing the java core?

**Comment by Zawa-ll** [comment]
> rather than introduces another pipeline option, is it possible to just use empty `--fileToStage=[]` option? If this is Spark specific could we refrain from changing the java core?

Using an empty --fileToStage=[] option could be a workaround to avoid staging. However, this change I plan to make ensures compatibility with HDFS and avoids redundant staging, which is critical for Spark on YARN.

**Comment by Zawa-ll** [comment]
Hi I just notice that the 'PreCommit Java / beam_PreCommit_Java' check fails for some reason, but I don't think the log is quite relevant to my changes, can someone provide me with some clue on how this can be fixed?

**Comment by liferoad** [comment]
> @liferoad 
> Hi I just notice that the 'PreCommit Java / beam_PreCommit_Java' check fails for some reason, but I don't think the log is quite relevant to my changes, can someone provide me with some clue on how this can be fixed?

@Abacn should be able to help here.

**Comment by Zawa-ll** [comment]
@Abacn 
Hi I just notice that the 'PreCommit Java / beam_PreCommit_Java' check fails for some reason, but I don't think the log is quite relevant to my changes, can someone provide me with some clue on how this can be fixed?

**Pull request closed without merging**
