### PR TITLE
[BEAM-8433] Use JUnit parameterized runner for dialect-sensitive integration tests

### PR DESCRIPTION
**Pull request by kennknowles**
Two commits:

1. Inline base class. It is clearer to have all test code inlined. If you must make a separate utility method, better to do it in the same class. Inheritance is almost never good in test classes.
2. Use JUnit Parameterized test runner instead of utility method. Also converted to a PTransform instead of a method, which is good Beam style for pipelines. Also made the parameterized tests enclosed, because we could also have ITs that do not depend on SQL dialect.

The two commits are independent, please do not squash (for history to be most readable)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by amaliujia** [comment]
I tried this idea already but results in an illegal BQ table name error.

**Comment by amaliujia** [comment]
The test name can be customized. Here is an example: https://github.com/junit-team/junit4/wiki/parameterized-tests#example

However, it always add `[` and `]` into the test name, and test name are used to create temporary BQ table. Thus it leads a illegal BQ table name.

**Comment by kennknowles** [comment]
I'll fix up the test BQ to not create invalid names.

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
Getting an interesting failure that doesn't seem related. There may be something fragile being exposed by a minor change in how the test is executed.

**Comment by kennknowles** [comment]
(https://builds.apache.org/job/beam_PostCommit_SQL_PR/125/testReport/junit/org.apache.beam.sdk.extensions.sql.meta.provider.datacatalog/DataCatalogBigQueryIT$DialectSensitiveTests/testReadWrite_ZETASQL_/)

**Comment by kennknowles** [comment]
I notice that the CalciteQueryPlanner and ZetaSQLQueryPlanner do not share the codepath to set up the cluster's metatadata provider.

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
Filed https://issues.apache.org/jira/browse/BEAM-8453 for `JmsIOTest` failure.

Filed https://issues.apache.org/jira/browse/BEAM-8454 for Java SDK harness failure.

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
run sql postcommit

**Comment by kennknowles** [comment]
Got multiple local successes. Running here: https://gradle.com/s/l572gifqnx5pg

The metadata provider issue appears to be a flake. The two planners set up metadata totally differently. We should fix that.

Here one success: https://gradle.com/s/l572gifqnx5pg

**Pull request merged**
