### PR TITLE
[BEAM-2530] Updating to AutoValue 1.5.1 to support Java 9.

### PR DESCRIPTION
**Pull request by youngoli**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

A fix to a Java 9 build error caused by AutoValue was fixed in version 1.5.1. I updated the maven project to use 1.5.1, which meant excluding it from the ban on non-Java 7 dependencies.

I assume this change breaks Java 7 support, but I couldn't figure out how to test that to confirm my assumption.

### CODE REVIEW

**Comment by youngoli** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Finally passed: https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/15484/

**Comment by iemejia** [comment]
Wait doesn't this break Java 7 compatibility? or is just a step to move to the Java 8 world ? I wasn't sure we had a final consensus on the move, do we?

**Comment by lukecwik** [comment]
The SDK is still built with source and target of version 1.7. So the built artifacts are Java 7 compatible.

This change only requires people building the SDK to use JDK 8+.

**Comment by rmannibucau** [comment]
@lukecwik if you build with java 8, and source=target=1.7 then you can get compiled bytecode only running on Java 8 (see the ConcurrentHashMap#keyset change for instance which will make your code compiling but broken when running on java 7 since the JVM will not be able to lookup the method at runtime). This kind of change sounds very risky and not very reliable.

**Comment by lukecwik** [comment]
The project already requires you to use JDK 8+ in several modules. The only real way to fix this is to force users to correctly configure their bootstrap classpath and for the bootstrap classpath to be used when releasing artifacts to ensure compatibility.

**Comment by rmannibucau** [comment]
Ok then beam needs to move to toolchain asap to ensure it respects java7 constraint where it needs or just get rid of this constraint and move to java8. No other way to guarantee the bytecode compatibility otherwise cause of the few hidden breaking changes in java 8.

**Pull request closed without merging**
