### PR TITLE
[BEAM-14429] Fix SyntheticUnboundedSource data duplication with SDF wrapper

### PR DESCRIPTION
**Pull request by y1chi**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by y1chi** [comment]
R: @chamikaramj

**Comment by y1chi** [comment]
R: @lukecwik

**Comment by chamikaramj** [comment]
Thanks. LGTM.

May be fix the wording of the following log as well (it's logs splits not sizes of splits).
https://github.com/apache/beam/blob/5c21fbccec5e1e831dd0040bd7f631c050865430/sdks/java/io/synthetic/src/main/java/org/apache/beam/sdk/io/synthetic/SyntheticUnboundedSource.java#L112

**Comment by y1chi** [comment]
Run Kotlin_Examples PreCommit

**Comment by y1chi** [comment]
Run Java PreCommit

**Review by lukecwik — APPROVED** [review]
Just make sure that this change won't break the update compatibility tests or change the encoding to be `current+end` instead of `start+end`

**Comment by chamikaramj** [comment]
Thanks. LGTM.

**Comment by y1chi** [comment]
> Just make sure that this change won't break the update compatibility tests or change the encoding to be `current+end` instead of `start+end`

I believe update compatibility test pipeline doesn't involve this source directly.

**Review by lukecwik — COMMENTED** [review]
a test that shows the incorrect behavior is fixed?

Merging as is for the fix.

**Pull request merged**
