### PR TITLE
[BEAM-3006] fixing minor issue in PipelineTest#testReplacedNames

### PR DESCRIPTION
**Pull request by urisilberstein**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by urisilberstein** [comment]
R: @tgroh

**Comment by urisilberstein** [comment]
If I understand you correctly, the test purpose is to validate that we can replace a transformation with the same name. 
In that case, the assert at the end doesn't validate that.
1. Even if the replacement fails, this assert still passes:
`assertThat(names, hasItem("original_application/custom_name"));`
2. This assert will always pass as no one mentions "custom_name2" as a name:
`assertThat(names, hasItem("original_application/custom_name"));`

Maybe a better assert will be to validate that the transformation instance is now the `ReplacementTransform` and not the `OriginalTransform`.

What do you say?

**Comment by urisilber** [comment]
Thanks for the clarification.  
I'll update the PR and ask for your feedback again once it's done.

**Comment by urisilber** [comment]
@tgroh can you please have a look?
I kept the original assert that the transformation name hasn't been changed,
+ new assert that validates the transformation itself has been changed.

**Comment by tgroh** [comment]
However, please fix the checkstyle failures before submission

**Comment by urisilberstein** [comment]
@tgroh - I have fixed the checkstyle issues. Thanks

**Pull request closed without merging**
