### PR TITLE
[#22181] Fix java package for SDK java core benchmark org.apache.beam.sdk.schemas -> org.apache.beam.sdk.jmh.schemas

### PR DESCRIPTION
**Pull request by lukecwik**
Missed during review of https://github.com/apache/beam/pull/22182

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @mosche @TheNeuralBit

**Review by aaltay — APPROVED** [review]

**Comment by lukecwik** [comment]
Run GoPortable PreCommit

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run GoPortable PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by lukecwik** [comment]
Run Python_PVR_Flink_Docker PreCommit

**Comment by lukecwik** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by mosche** [comment]
Thanks for catching that @lukecwik

**Pull request merged**
