### PR TITLE
[BEAM-9392] Fix Multi TestStream assertion errors

### PR DESCRIPTION
**Pull request by rohdesamuel**
Change-Id: Ibbd99867c9bc96aaa7ca9d3f2874f3b1e75c2f98

Fixes failures from: https://builds.apache.org/job/beam_PreCommit_Python_Cron/2443/#showFailuresLink

resulting from PR/10934

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by rohdesamuel** [comment]
R: @aaltay

**Comment by rohdesamuel** [comment]
CC: @lukecwik

**Comment by rohdesamuel** [comment]
> So, wherever `TestStream` is used, `passthrough_pcollection_output_ids` needs to be specified. Is this correct?
> 
> Should we check in TestStream or add a note about it?

Yes, specifically for the multiple output TestStream. I added a comment about it and which flag to use.

**Comment by pabloem** [comment]
Restest this please

**Comment by rohdesamuel** [comment]
The linter failed due to "ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device"

**Comment by amaliujia** [comment]
Run PythonLint PreCommit

**Comment by aaltay** [comment]
> The linter failed due to "ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device"

@alanmyrvold @udim @yifanzou  -- Is this a symptom of the problem of growing temp directory?

**Comment by amaliujia** [comment]
Run PythonLint PreCommit

**Comment by rohdesamuel** [comment]
Run PythonLint PreCommit

**Comment by pabloem** [comment]
Run PythonLint PreCommit

**Comment by yifanzou** [comment]
> > The linter failed due to "ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device"
> 
> @alanmyrvold @udim @yifanzou -- Is this a symptom of the problem of growing temp directory?

The Jenkins workspace and the docker images are usually the two monsters eat the disk.

**Comment by aaltay** [comment]
Run PythonLint PreCommit

**Comment by aaltay** [comment]
retest this please

**Comment by aaltay** [comment]
retest this please

**Comment by amaliujia** [comment]
Run Python PreCommit

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
Run PythonLint PreCommit

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
Run Python2_PVR_Flink PreCommit

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
Run Python PreCommit

**Comment by aaltay** [comment]
Run Python PreCommit

**Comment by amaliujia** [comment]
@rohdesamuel precommit is still failing.

**Comment by kamilwu** [comment]
Run Python PreCommit

**Comment by kamilwu** [comment]
`pycommon:docs` task is failing due to: `docstring of apache_beam.testing.test_stream.TestStream:14: WARNING: Unexpected indentation. `

**Comment by kamilwu** [comment]
Retest this please

**Comment by kamilwu** [comment]
Retest this please

**Comment by kamilwu** [comment]
Tests passed. @mwalenia could you take a look?

**Comment by mwalenia** [comment]
LGTM. Thanks for the fix!

**Comment by amaliujia** [comment]
Thank you all!

**Pull request merged**
