### PR TITLE
fix NoSuchFieldException

### PR DESCRIPTION
**Pull request by ffly1985**
fix NoSuchFieldFieldException

### CODE REVIEW

**Comment by aaltay** [comment]
R: @XuMingmin could you review this change?

**Comment by aaltay** [comment]
Merged, please manually close the PR.

**Comment by dhalperi** [comment]
@ffly1985 can you please manually close this PR -- it has been merged into the feature branch, but GitHub will not close the PR automatically because it has not been merged to master.

**Comment by aaltay** [comment]
Hey @ffly1985, would you be able to manually close this PR? (It is already merged.)

**Pull request closed without merging**
