### PR TITLE
[BEAM-13229] [Website] bug side nav

### PR DESCRIPTION
**Pull request by bullet03**
[BEAM-13229]
- change offset to 10px to activate an element via bootstrap's scrollspy library

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by bullet03** [comment]
R: @AydarZaynutdinov

**Comment by AydarZaynutdinov** [comment]
I still can reproduce this bug on the [documentation page](http://apache-beam-website-pull-requests.storage.googleapis.com/17260/documentation/programming-guide/index.html#transforms)

**Comment by aaltay** [comment]
R: @riteshghorse - could you do a first pass review and tag a committer after that?

**Comment by riteshghorse** [comment]
It solves the original problem but introduces new orange lines under the side section 
image

**Comment by riteshghorse** [comment]
@bullet03 Thanks for the PR. It solves the original problem of changing sections on side nav. However, it looks like the orange scroll bar in side nav gets collapsed as horizontal lines before moving to its original position.
Could you do another pass? Would be happy to get this change in once the orange lines are gone.

**Comment by bullet03** [comment]
> @bullet03 Thanks for the PR. It solves the original problem of changing sections on side nav. However, it looks like the orange scroll bar in side nav gets collapsed as horizontal lines before moving to its original position. Could you do another pass? Would be happy to get this change in once the orange lines are gone.

The arrow images are not shown on staging in any PR, so it is not caused by the changes in 17260. They are shown correctly on localhost, so we couldn't reproduce the bug there. 

There is a high probability that, when we merge the code to master, this issue will be fixed. 

Which means, there might be another issue - with CI/CD - that is worth investigating. Should we create another ticket in Jira and describe the issue there?

**Comment by riteshghorse** [comment]
Sounds good to me. I'll tag a committer and let's see their take on it.
R: @kileys

**Comment by dariabezkorovaina** [comment]
@pabloem I heard that Kiley is OOO for this and next week, can you please help with merging this PR? :)

**Comment by pabloem** [comment]
Run Website_Stage_GCS PreCommit

**Comment by pabloem** [comment]
let's just make sure that the issue does not reproduce once merged...

**Comment by pabloem** [comment]
LGTM

**Comment by pabloem** [comment]
like I said, please let's make sure that the issue that ritesh caught did not just get merged

**Comment by nausharipov** [comment]
@pabloem Ritesh's issue with arrow images not being displayed on staging is not present on the master branch after the merge. We will create a separate Jira ticket describing this CI/CD issue.

We have created PR #17503 to revert the changes from this branch because the menu still works incorrectly.

**Comment by dariabezkorovaina** [comment]
Created a [ Jira ticket ](https://issues.apache.org/jira/browse/BEAM-14384) to investigate issue with CI/CD.

**Pull request merged**
