### PR TITLE
Properly tag test so it is excluded on unsupported runners

### PR DESCRIPTION
**Pull request by reuvenlax**
R:@Abacn

### CODE REVIEW

**Review by Abacn — APPROVED** [review]
Thanks! LGTM

**Comment by Abacn** [comment]
Run Samza ValidatesRunner

**Comment by Abacn** [comment]
Run ULR Loopback ValidatesRunner

**Comment by Abacn** [comment]
Need to add the category here: https://github.com/apache/beam/blob/7a2c22d10e344b3e7e7741074027cc4fb8c13165/runners/portability/java/build.gradle#L151

**Comment by reuvenlax** [comment]
Run ULR Loopback ValidatesRunner

**Review by kennknowles — APPROVED** [review]

**Comment by kennknowles** [comment]
LGTM but do confirm that it fixes the broken suites

**Comment by Abacn** [comment]
Confirmed that most validaterunners are back green. There is still one test suite flaky:

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/

it is passing on Dataflow V1 streaming test though:

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/3675/testReport/org.apache.beam.sdk.transforms/ViewTest/testTriggeredLatestSingleton/

Is Dataflow V2 unsupported for this feature? CC: @reuvenlax @kennknowles

**Comment by kennknowles** [comment]
I think that is right. This is not yet fixed for V2 @reuvenlax

**Comment by tvalentyn** [comment]
if this needs to be excluded from Dataflow V1 and Dataflow V2, wondering if this test should be disabled altogether temporarily?

**Comment by kennknowles** [comment]
It should work for v1

**Comment by tvalentyn** [comment]
ack, got it, we exclude in ULR but not V1. sent https://github.com/apache/beam/pull/26801

**Pull request merged**
