### PR TITLE
[BEAM-6526] Remove unneeded methods in AvroIO ReadFiles and ParseFiles

### PR DESCRIPTION
**Pull request by iemejia**
This is a fix to an API issue I found in the previously introduced ReadFiles/ParseFiles PR.
I also included an extra commit to refactor AvroIO Read/Parse to use FileIO + ReadFiles/ParseFiles.

R: @chamikaramj

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java AvroIO Performance Test

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
CI is green now, PTAL @chamikaramj

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Pull request merged**
