### PR TITLE
[BEAM-79] Prepare for merging gearpump-runner

### PR DESCRIPTION
**Pull request by manuzhang**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by kennknowles** [comment]
For the Jenkins problem, I think you'll need to add gearpump-runner profile to https://github.com/apache/beam/blob/master/.test-infra/jenkins/job_beam_PreCommit_Java_MavenInstall.groovy

**Comment by manuzhang** [comment]
@kennknowles gearpump-runner requires java8 so it can't be added to `jenkins-precommit` in `examples/java/pom.xml`.

**Comment by kennknowles** [comment]
Can it work to also upgrade the version of Java in that profile? Since it is just for running the tests, I think it is OK. The examples code will still be restricted to Java 7 language level.

**Comment by manuzhang** [comment]
The maven-enforcer-plugin says NO. It could be that I've not done it correctly, though

**Comment by manuzhang** [comment]
Try overriding maven-enforcer-plugin but it seems to have excluded `beam-sdks-java-core` from classpath. I'm afraid I have gone too far in that direction. Could you give some suggestions ?

**Comment by manuzhang** [comment]
Well, the exception `java.lang.NoClassDefFoundError: Could not initialize class org.apache.beam.sdk.options.PipelineOptionsFactory
` is caused by enabling `flink-runner` and `gearpump-runner` profiles simultaneously.

**Comment by kennknowles** [comment]
:-( OK let us skip enabling the WordCount presubmit. We really should not be enabling all runners at once - the whole point of the profiles is that they will conflict. Hopefully the new pipelined Jenkins config makes this better.

**Comment by manuzhang** [comment]
Okay, skipped for now. I will try enabling it once the new Jenkins config is in.

**Comment by manuzhang** [comment]
@kennknowles Jenkins is green now. Any more comments ?

**Comment by kennknowles** [comment]
Let's merge this and do another overall pass to file JIRAs for the things we can't solve without more work.

**Pull request merged**
