### PR TITLE
Cherry-pick #3070 #3087 #3088 #3095 #3096 #3090 #3098 #3089 #3075 #3099 #3094 #3086 #3065 #3101 #3076

### PR DESCRIPTION
**Pull request by aaltay**
R: @dhalperi 
cc: @davorbonaci @sb2nov @charlesccychen @robertwb @chamikaramj

### CODE REVIEW

**Comment by sb2nov** [comment]
LGTM

**Comment by robertwb** [comment]
Taking a close look to make sure nothing was lost.

**Comment by aaltay** [comment]
List of things cherry-picked:

https://github.com/apache/beam/pull/3070 - 0fa97ab78 ff589c711 aee918774
https://github.com/apache/beam/pull/3087 - c4d7ece24
https://github.com/apache/beam/pull/3088 - f703dbce7
https://github.com/apache/beam/pull/3095 - bbe31fc23
https://github.com/apache/beam/pull/3096 - c8317345a 1b89697e5
https://github.com/apache/beam/pull/3090 - 05557c858
https://github.com/apache/beam/pull/3098 - b5cc8b85f
https://github.com/apache/beam/pull/3089 - b81962957
https://github.com/apache/beam/pull/3075 - 2e6451dfe e10662df9
https://github.com/apache/beam/pull/3099 - 4c28f054e
https://github.com/apache/beam/pull/3094 - 7881fd5e6 16a3fff18 d531219fc
https://github.com/apache/beam/pull/3086 - 0b7356e32
https://github.com/apache/beam/pull/3065 - 98e685d85
https://github.com/apache/beam/pull/3101 - fc3e28de3

**Comment by robertwb** [comment]
Looks like you're missing https://github.com/apache/beam/commit/101141da32e01c6873be7479eadb3f7efb998b54

**Comment by robertwb** [comment]
https://github.com/apache/beam/pull/3076

**Comment by robertwb** [comment]
FYI, I compared `git diff apache/release-2.0.0..github/pr/3103` and `git diff 0fa97ab^..apache/master -- sdks/python/apache_beam`. Second derivatives to the rescue!

**Comment by aaltay** [comment]
@robertwb thank you. PTAL, added the missing commit.

**Comment by robertwb** [comment]
LGTM!

**Comment by aaltay** [comment]
Local run of python tests passed, I will merge it.

**Pull request merged**
