### PR TITLE
Hotfix: fix a typo in go installation link.

### PR DESCRIPTION
**Pull request by tysonjh**
Fix a typo in the go installation link.

### CODE REVIEW

**Comment by tysonjh** [comment]
@kennknowles would you please review?

**Comment by amaliujia** [comment]
LGTM

**Comment by amaliujia** [comment]
Run Website PreCommit

**Comment by amaliujia** [comment]
Run Website_Stage_GCS PreCommit

**Comment by amaliujia** [comment]
Thanks for catching this up!

**Comment by pabloem** [comment]
please hold back website changes, as community is in the process of a website migration review: https://github.com/apache/beam/pull/11554

**Pull request merged**
