### PR TITLE
[BEAM-1306] Refactors BigQueryServices interface to allow the client to set options

### PR DESCRIPTION
**Pull request by g-eorge**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by dhalperi** [comment]
R: @peihe

**Comment by james-woods** [comment]
Any news on this one?

**Comment by reuvenlax** [comment]
Can you explain how the user will specify these options?

**Comment by g-eorge** [comment]
@reuvenlax the user will be able to set options like .withoutValidation() on the pipeline. https://github.com/apache/beam/pull/1778 illustrates the idea, and will be refactored slightly once this one is resolved so that for streaming writes the options don't need to be passed around.

**Comment by davorbonaci** [comment]
R: @reuvenlax -@peihe

**Comment by davorbonaci** [comment]
@reuvenlax, any thoughts perhaps?

**Comment by aaltay** [comment]
@reuvenlax any thoughts on this PR?

**Comment by reuvenlax** [comment]
This PR needs to be rebased - the underlying BigQuery codebase has changed quite a bit underneat it.

**Comment by davorbonaci** [comment]
Hi @g-eorge, would you like to push this pull request forward? Please let us know if we can assist somehow.

**Comment by reuvenlax** [comment]
The underlying transforms have changed quite a bit, so this PR would need to be rebased.

**Comment by jkff** [comment]
Is this PR still active or should it be closed?

**Comment by dhalperi** [comment]
Suggest closure.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/2282#-:-L0hu4yvsv_7n7m7T1HR:b-3d3zak)*

**Pull request closed without merging**
