### PR TITLE
[BEAM-4836] IOIT tests fails on Jenkins because of numpy version

### PR DESCRIPTION
**Pull request by kkucharc**
Changed order of installing python requirements in `buildPerformanceTest`. Perfkit installation was failing because beam is using now 1.14. The Perfkit requirements have to be installed after beam's requirements to overwrite numpy-1.14 with 1.13.3 version.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ x ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by echauchot** [comment]
I'm leaving on vacation, @lgajowy can you please take a look ?

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Java MongoDBIO Performance Test

**Comment by kkucharc** [comment]
Run Java JdbcIO Performance Test

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java MongoDBIO Performance Test

**Comment by kkucharc** [comment]
Run Java JdbcIO Performance Test

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Seed Job

**Comment by kkucharc** [comment]
Run Java MongoDBIO Performance Test

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Java TextIO Performance Test

**Comment by kkucharc** [comment]
Run Java HadoopInputFormatIO Performance Test

**Comment by kkucharc** [comment]
Run Java JdbcIO Performance Test

**Comment by kkucharc** [comment]
@lgajowy Can you take a look at it? I finally tried all the tests and it seems to be ok now.

**Comment by lgajowy** [comment]
Run Python PreCommit

**Comment by lgajowy** [comment]
LGTM, merging. Thanks!

**Pull request merged**
