### PR TITLE
Remove flaky Notebooks tests

### PR DESCRIPTION
**Pull request by Polber**
This PR removes the flaky screenshots tests from Notebooks IT suite.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
Could you give some context on this? Where have we seen the flakes? Do we have adequate coverage without this?

**Comment by damccorm** [comment]
waiting on author

**Comment by Polber** [comment]
@damccorm These flakes block notebooks release and perform no real testing of the code itself. They essentially test the fonts and formatting of the output of the notebook cells

**Comment by damccorm** [comment]
Are there actually other tests in https://github.com/apache/beam/tree/3f434f07053d5a73be202cb6d7d70abca200f463/sdks/python/apache_beam/runners/interactive/testing

I ask for 2 reasons:
1) I'm hesitant to remove our primary source of testing of this code if it is just this
2) If they are and we decide to remove this, should we just remove the whole folder?

> @damccorm These flakes block notebooks release and perform no real testing of the code itself. They essentially test the fonts and formatting of the output of the notebook cells

That is testing something, even if its not the most effective test for that. Do we understand why they're flaky? Is it something that could be fixed? cc/ @KevinGG who may have thoughts here

**Comment by Polber** [comment]
Closing as these tests have not been an issue in a while.

**Pull request closed without merging**
