### PR TITLE
Fixes Java Examples ARM GHA on Java8

### PR DESCRIPTION
**Pull request by Abacn**
Follow up of #28969

After the change the PostCommit Java Example ARM failing due to

```
A problem occurred evaluating project ':runners:google-cloud-dataflow-java'.
> Unknown Java Version 8 for setting additional java options
```

This PR

* Skips unsupported ver for -PtestJavaVersion option. This fixes Java Examples ARM GHA on Java8

this preserve the original logic  before #28969 that is no-op when `-PtestJavaVersion=8` is set. This happens to be configured in PostCommit ARM.

* Fixes missing version matrix element in readme.md

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Testing Java21 on ARM has a few blockers under the current GHA setup (run everything in single Java version) . I have a working branch trying to resolve them, but currently blocked by shadow plugin not yet support java21: https://github.com/Abacn/beam/commit/7aff7b53c614a52a8309636756c97c33c37ec4b2

This essentially means beam does not yet support compiling on Java21. We need to restructure the ARM postcommit to be compiled with Java8 (beam) + Java21 (test) as what I just did for JPMS. Leave this as future task.

**Comment by Abacn** [comment]
R: @tvalentyn

**Review by tvalentyn — APPROVED** [review]
Thank you!

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_ARM PostCommit 8

**Pull request merged**
