### PR TITLE
[BEAM-3182][Nexmark][SQL] Implement sql query 3

### PR DESCRIPTION
**Pull request by akedin**
[BEAM-3182](https://issues.apache.org/jira/browse/BEAM-3182)

[Java version of the same query](https://github.com/apache/beam/blob/64ff21f35ee2946d38645fb0a51678628e49e62a/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/Query3.java#L74)

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java, line 72 at r1](https://reviewable.io:443/reviews/apache/beam/4352#-L2SB-hUTYasxcagt_GY:-L2SB-hUTYasxcagt_GZ:b-tdhqrn) ([raw file](https://github.com/apache/beam/blob/299013a7d96fdc36d16f23b485b5a1304cf18b3c/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java#L72)):*
> ```Java
>  * become available.
>  *
>  * <p>Correct join semantics implementation is tracked in BEAM-3190, BEAM-3191
> ```

Let's use a trigger configuration that yields correct results, like default trigger on FixedWindows, and port the example back to Java with the same so they can be compared.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4352)*

**Comment by akedin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java, line 72 at r1](https://reviewable.io:443/reviews/apache/beam/4352#-L2SB-hUTYasxcagt_GY:-L2SD7DiQ4iOT4j9vWVX:b-539gv5) ([raw file](https://github.com/apache/beam/blob/299013a7d96fdc36d16f23b485b5a1304cf18b3c/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java#L72)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

Let's use a trigger configuration that yields correct results, like default trigger on FixedWindows, and port the example back to Java with the same so they can be compared.
</blockquote></details>

Updated the window spec. Not sure why it is this way in the java query3.

Looking at the [original commit](https://github.com/apache/beam/commit/7c28b492aa17160d9a84914814e618716b7beb9f#diff-d5894fed6c92d9719184cf52b37bc0d2L195) for java query3, it was explicitly changed to `GlobalWindows` to comply with State/Timer APIs. Not sure what it means.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4352)*

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java, line 72 at r1](https://reviewable.io:443/reviews/apache/beam/4352#-L2SB-hUTYasxcagt_GY:-L31kOKGgPhFY51pc8Hu:bb73djm) ([raw file](https://github.com/apache/beam/blob/299013a7d96fdc36d16f23b485b5a1304cf18b3c/sdks/java/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/sql/SqlQuery3.java#L72)):*
<details><summary><i>Previously, akedin (Anton Kedin) wrote…</i></summary><blockquote>

Updated the window spec. Not sure why it is this way in the java query3.

Looking at the [original commit](https://github.com/apache/beam/commit/7c28b492aa17160d9a84914814e618716b7beb9f#diff-d5894fed6c92d9719184cf52b37bc0d2L195) for java query3, it was explicitly changed to `GlobalWindows` to comply with State/Timer APIs. Not sure what it means.
</blockquote></details>

SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4352#-:-L31kZfg9eWRw0WrPDAR:bnfp4nl)*

**Comment by kennknowles** [comment]
Conflict introduced, guessing it is just query 2 getting in. Can you rebase again?

**Comment by akedin** [comment]
> Conflict introduced, guessing it is just query 2 getting in. Can you rebase again?

Yes, that is the case. Rebased.

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
and again :-)

**Comment by kennknowles** [comment]
The failure is because after we cut the 2.3.0 release branch, the archetype refers to nonexistent 2.4.0-SNAPSHOT until the nightly build runs. I kicked one off early just to get it. We should add that to the release guide actually.

**Pull request merged**
