### PR TITLE
[BEAM-3837] Handle BundleSplitRequests in Python SDK Harness.

### PR DESCRIPTION
**Pull request by robertwb**
This should be sufficient to handle splits, including checkpointing, over the FnAPI.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by robertwb** [comment]
On Fri, Feb 8, 2019 at 10:48 AM Maximilian Michels <notifications@github.com>
wrote:

> *@mxm* commented on this pull request.
>
> PR looks good, but I'm struggling a bit to see this piece in the whole
> picture of portable SDF support.
>
Thanks for looking into this, and good questions. I'll try to answer them
as best I can.
>
> Looking at
> https://docs.google.com/document/d/1tUDb45sStdR8u7-jBkGdw3OGFK7aa2-V7eo86zYSE_4,
> this PR implements the Python SDK harness side of the splitting logic.
>
Correct.

> The Runner can make use of the splitting to balance work more evenly.
> Another use case is checkpointing during bundle processing.
>
Yep. Right now the runner is at the mercy of the SDF to decide to
checkpoint, this allows the runner to explicitly request that the SDK stop
processing a bundle (either ASAP, or some point in the future).

> The SDK harness will eventually support reorganizing the fusion to
> parallelize splits.
>
This is more speculative. Realistically, rather than adding such support
into SDKs, if the runner wants to change fusion it could request the
bundles stop ASAP, re-fuse, and then send different process descriptors for
the SDK harness to work on from that point forward.

Note that this PR does not request splits at arbitrarily deep points in the
fusion tree; it only splits into an SDF that is a root (immediately
following the GRPC read). Given that we generally want a "redistribute"
after the initial restriction splitting phase of an SDF this is not a huge
restriction; further work on extending this arbitrarily adds significant
complexity and can be done later if needed.

> How are the Runners going to make use of this feature? Doesn't this
> require that Runners know about all parallel instances of an SDF to
> estimate how long splits take to process? Or do Runners simply measure
> processing time of its own splits, in case there are more than one?
>
These changes are runner initiated, so there are various levels at which
they can take advantage of this.  The simplest is, of course, to never
request any splits at all. This works fine in batch, but in streaming one
would require sources that periodically checkpoint on their own (the
previous PR). The next level of sophistication is for the runner to
periodically checkpoint (e.g. after a certain amount of time has passed) to
be able to commit work and bound the re-processing required on failure
recovery (useful for batch, but almost essential for streaming). One step
more than that is supporting dynamic rebalancing, e.g. if twice as many
workers got added to a job, it could request that every existing worker
return half its remaining work. Or if some workers finish early, it could
see which workers have the most pending work ahead (progress not yet
implemented) and steal some of theirs to give to the idle one(s). These
require an increasingly global view of the state of the system.

> How far is the support in terms of rearranging fusion according to the
> splitting? Do we gain much from parallelizing splits on the same node or is
> this only useful if the Runner's execution engine provides a means to
> dynamically rebalance work on its workers?
>
Without the ability to rebalance work, the primary advantage to the runner
is the ability to checkpoint at the runner's request.

>

**Comment by mxm** [comment]
Thank you for the comments. I think it starts to make sense now.

>Note that this PR does not request splits at arbitrarily deep points in the fusion tree; it only splits into an SDF that is a root (immediately following the GRPC read).

That certainly simplifies the splitting because the fusion does not have to be changed after the splitting.

>This works fine in batch, but in streaming one would require sources that periodically checkpoint on their own (the previous PR).

Ah ok, and this is handled via the `ProcessBundleResponse`'s `DelayedBundleApplication` which can be checkpointed.

>Without the ability to rebalance work, the primary advantage to the runner is the ability to checkpoint at the runner's request.

FYI Rebalancing is supported by Flink and the Runner is theoretically ready to support it. However, the process is rather manual. You need to savepoint the current application state and then restart the job from that savepoint with a different parallelism. You also need to set the "maximum parallelism" before you first start the job which determines the partitioning degree of the state.

**Comment by robertwb** [comment]
Yes, I think Flink could take advantage of this as well, with some runner-side work.

**Comment by robertwb** [comment]
Thanks!

**Pull request merged**
