### PR TITLE
Fix tox error running hdfsIntegrationTest

### LINKED ISSUE #25443: [Failing Test]: Python PostCommit hdfsIntegrationTest failing due to tox error
### What happened?

After #24911 all python postcommit tests permared due to error of hdfsIntegrationTest task. Example error message (taken from https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python310/470/consoleFull):

```
04:11:40 test_1      | Traceback (most recent call last):
04:11:40 test_1      |   File "/usr/local/bin/tox", line 8, in <module>
04:11:40 test_1      |     sys.exit(cmdline())
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/session/__init__.py", line 42, in cmdline
04:11:40 test_1      |     main(args)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/session/__init__.py", line 62, in main
04:11:40 test_1      |     config = load_config(args)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/session/__init__.py", line 78, in load_config
04:11:40 test_1      |     config = parseconfig(args)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 262, in parseconfig
04:11:40 test_1      |     ParseIni(config, config_file, content)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1126, in __init__
04:11:40 test_1      |     raise tox.exception.ConfigError(
04:11:40 test_1      | tox.exception.ConfigError: ConfigError: py{38}-onnx-{113} failed with ConfigError: substitution key '38' not found at Traceback (most recent call last):
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1102, in run
04:11:40 test_1      |     results[name] = cur_self.make_envconfig(name, section, subs, config)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1226, in make_envconfig
04:11:40 test_1      |     res = meth(env_attr.name, env_attr.default, replace=replace)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1407, in getpath
04:11:40 test_1      |     path = self.getstring(name, defaultpath, replace=replace)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1486, in getstring
04:11:40 test_1      |     x = self._replace_if_needed(x, name, replace, crossonly)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1491, in _replace_if_needed
04:11:40 test_1      |     x = self._replace(x, name=name, crossonly=crossonly)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1517, in _replace
04:11:40 test_1      |     replaced = Replacer(self, crossonly=crossonly).do_replace(value)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1557, in do_replace
04:11:40 test_1      |     expanded = substitute_once(value)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1551, in substitute_once
04:11:40 test_1      |     return self.RE_ITEM_REF.sub(self._replace_match, x)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1598, in _replace_match
04:11:40 test_1      |     return self._replace_substitution(match)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1633, in _replace_substitution
04:11:40 test_1      |     val = self._substitute_from_other_section(sub_key)
04:11:40 test_1      |   File "/usr/local/lib/python3.10/site-packages/tox/config/__init__.py", line 1627, in _substitute_from_other_section
04:11:40 test_1      |     raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
04:11:40 test_1      | tox.exception.ConfigError: ConfigError: substitution key '38' not found
04:11:40 test_1      | 
```

Likely a misconfiguration of build script.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #25443

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Python 3.9 PostCommit

**Comment by AnandInguva** [comment]
Oh I created a duplicate. https://github.com/apache/beam/pull/25450

I will close that. Thanks @Abacn

**Comment by Abacn** [comment]
Run Python_Coverage PreCommit

**Comment by Abacn** [comment]
postcommit fixed: https://ci-beam.apache.org/job/beam_PostCommit_Python39_PR/115/
unit test still run correctly: https://ci-beam.apache.org/job/beam_PreCommit_Python_Coverage_Phrase/4/testReport/apache_beam.ml.inference.onnx_inference_test/

ready for review now R: @AnandInguva

**Comment by Abacn** [comment]
The 4 pending Jenkins tasks are passed but not updated their status to GitHub UI. Merging for now to get postcommits back green

**Comment by AnandInguva** [comment]
Thanks @Abacn

**Pull request merged**
