### PR TITLE
[BEAM-12479] Fixes UnsupportedOperationException

### PR DESCRIPTION
**Pull request by pgillet**
Please see the associated JIRA ticket [BEAM-12479](https://issues.apache.org/jira/projects/BEAM/issues/BEAM-12479).

### CODE REVIEW

**Comment by pabloem** [comment]
sorry about the super long delay reviewing this. Would you be willing to resolve merge conflicts?

**Comment by pgillet** [comment]
Sure done :heavy_check_mark: 

Some checks were not successful, but I don't think it is related to my changes. Do you confirm?

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
that's correct that these tests do not seem related

**Comment by pgillet** [comment]
:+1:

**Pull request merged**
