### PR TITLE
[BEAM-1682] Enable all GCP unit tests in Python-SDK

### PR DESCRIPTION
**Pull request by tibkiss**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by tibkiss** [comment]
This change increases the overall test coverage by 10%:

Name                                                                               Stmts   Miss  Cover
------------------------------------------------------------------------------------------------------
apache_beam/__init__.py                                                               10      1    90%
apache_beam/coders/__init__.py                                                         2      0   100%
apache_beam/coders/coder_impl.py                                                     414     23    94%
apache_beam/coders/coders.py                                                         392     69    82%
apache_beam/coders/observable.py                                                      10      0   100%
apache_beam/coders/slow_stream.py                                                    105      6    94%
apache_beam/coders/typecoders.py                                                      69      6    91%
apache_beam/error.py                                                                   7      0   100%
apache_beam/examples/__init__.py                                                       0      0   100%
apache_beam/examples/complete/__init__.py                                              0      0   100%
apache_beam/examples/complete/autocomplete.py                                         34     11    68%
apache_beam/examples/complete/estimate_pi.py                                          45     11    76%
apache_beam/examples/complete/juliaset/__init__.py                                     0      0   100%
apache_beam/examples/complete/juliaset/juliaset/__init__.py                            0      0   100%
apache_beam/examples/complete/juliaset/juliaset/juliaset.py                           47     12    74%
apache_beam/examples/complete/tfidf.py                                                56      1    98%
apache_beam/examples/complete/top_wikipedia_sessions.py                               63     12    81%
apache_beam/examples/cookbook/__init__.py                                              0      0   100%
apache_beam/examples/cookbook/bigquery_side_input.py                                  56     26    54%
apache_beam/examples/cookbook/bigquery_tornadoes.py                                   20     11    45%
apache_beam/examples/cookbook/bigshuffle.py                                           33      2    94%
apache_beam/examples/cookbook/coders.py                                               40     16    60%
apache_beam/examples/cookbook/custom_ptransform.py                                    45     23    49%
apache_beam/examples/cookbook/filters.py                                              24     11    54%
apache_beam/examples/cookbook/group_with_coder.py                                     41      4    90%
apache_beam/examples/cookbook/mergecontacts.py                                        44      2    95%
apache_beam/examples/cookbook/multiple_output_pardo.py                                44      2    95%
apache_beam/examples/snippets/__init__.py                                              0      0   100%
apache_beam/examples/snippets/snippets.py                                            443     16    96%
apache_beam/examples/wordcount.py                                                     51      2    96%
apache_beam/examples/wordcount_debugging.py                                           45      2    96%
apache_beam/examples/wordcount_minimal.py                                             27      2    93%
apache_beam/internal/__init__.py                                                       0      0   100%
apache_beam/internal/gcp/__init__.py                                                   0      0   100%
apache_beam/internal/gcp/auth.py                                                      73     37    49%
apache_beam/internal/gcp/json_value.py                                                64      8    88%
apache_beam/internal/pickler.py                                                       96     10    90%
apache_beam/internal/util.py                                                          30      0   100%
apache_beam/io/__init__.py                                                            15      2    87%
apache_beam/io/avroio.py                                                             138     14    90%
apache_beam/io/concat_source.py                                                      134     10    93%
apache_beam/io/filebasedsource.py                                                    124      4    97%
apache_beam/io/fileio.py                                                             409     70    83%
apache_beam/io/gcp/__init__.py                                                         0      0   100%
apache_beam/io/gcp/bigquery.py                                                       416     29    93%
apache_beam/io/gcp/datastore/__init__.py                                               0      0   100%
apache_beam/io/gcp/datastore/v1/__init__.py                                            0      0   100%
apache_beam/io/gcp/datastore/v1/datastoreio.py                                       170     33    81%
apache_beam/io/gcp/datastore/v1/fake_datastore.py                                     38      2    95%
apache_beam/io/gcp/datastore/v1/helper.py                                            126      8    94%
apache_beam/io/gcp/datastore/v1/query_splitter.py                                    102      7    93%
apache_beam/io/gcp/gcsio.py                                                          414     46    89%
apache_beam/io/gcp/internal/__init__.py                                                0      0   100%
apache_beam/io/gcp/internal/clients/__init__.py                                        0      0   100%
apache_beam/io/gcp/internal/clients/bigquery/__init__.py                               9      2    78%
apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py                   116     65    44%
apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_messages.py                 459      0   100%
apache_beam/io/gcp/internal/clients/storage/__init__.py                                9      2    78%
apache_beam/io/gcp/internal/clients/storage/storage_v1_client.py                     165     71    57%
apache_beam/io/gcp/internal/clients/storage/storage_v1_messages.py                   507      0   100%
apache_beam/io/gcp/pubsub.py                                                          27      4    85%
apache_beam/io/iobase.py                                                             151     26    83%
apache_beam/io/range_trackers.py                                                     265     22    92%
apache_beam/io/textio.py                                                             150     13    91%
apache_beam/io/tfrecordio.py                                                          86      4    95%
apache_beam/metrics/__init__.py                                                        1      0   100%
apache_beam/metrics/cells.py                                                         129     21    84%
apache_beam/metrics/execution.py                                                      87      2    98%
apache_beam/metrics/metric.py                                                         96      6    94%
apache_beam/metrics/metricbase.py                                                     21      3    86%
apache_beam/pipeline.py                                                              188     14    93%
apache_beam/pvalue.py                                                                177     13    93%
apache_beam/runners/__init__.py                                                        8      0   100%
apache_beam/runners/api/__init__.py                                                    0      0   100%
apache_beam/runners/api/beam_runner_api_pb2.py                                       370      0   100%
apache_beam/runners/common.py                                                        237     35    85%
apache_beam/runners/dataflow/__init__.py                                               0      0   100%
apache_beam/runners/dataflow/dataflow_metrics.py                                      49      4    92%
apache_beam/runners/dataflow/dataflow_runner.py                                      324    133    59%
apache_beam/runners/dataflow/internal/__init__.py                                      0      0   100%
apache_beam/runners/dataflow/internal/apiclient.py                                   342    130    62%
apache_beam/runners/dataflow/internal/clients/__init__.py                              0      0   100%
apache_beam/runners/dataflow/internal/clients/dataflow/__init__.py                     9      2    78%
apache_beam/runners/dataflow/internal/clients/dataflow/dataflow_v1b3_client.py       148     40    73%
apache_beam/runners/dataflow/internal/clients/dataflow/dataflow_v1b3_messages.py    1043      0   100%
apache_beam/runners/dataflow/internal/clients/dataflow/message_matchers.py            62     13    79%
apache_beam/runners/dataflow/internal/dependency.py                                  214     58    73%
apache_beam/runners/dataflow/internal/names.py                                        54      0   100%
apache_beam/runners/dataflow/native_io/__init__.py                                     0      0   100%
apache_beam/runners/dataflow/native_io/iobase.py                                      95     46    52%
apache_beam/runners/direct/__init__.py                                                 2      0   100%
apache_beam/runners/direct/bundle_factory.py                                          75      5    93%
apache_beam/runners/direct/clock.py                                                   17      6    65%
apache_beam/runners/direct/consumer_tracking_pipeline_visitor.py                      27      0   100%
apache_beam/runners/direct/direct_metrics.py                                          55      0   100%
apache_beam/runners/direct/direct_runner.py                                           83      2    98%
apache_beam/runners/direct/evaluation_context.py                                     134      6    96%
apache_beam/runners/direct/executor.py                                               304     14    95%
apache_beam/runners/direct/helper_transforms.py                                       48      0   100%
apache_beam/runners/direct/transform_evaluator.py                                    279     29    90%
apache_beam/runners/direct/transform_result.py                                        26      0   100%
apache_beam/runners/direct/watermark_manager.py                                      129      1    99%
apache_beam/runners/pipeline_context.py                                               42      0   100%
apache_beam/runners/runner.py                                                        142     30    79%
apache_beam/transforms/__init__.py                                                     6      0   100%
apache_beam/transforms/combiners.py                                                  282     23    92%
apache_beam/transforms/core.py                                                       558     75    87%
apache_beam/transforms/cy_combiners.py                                               195    102    48%
apache_beam/transforms/display.py                                                    118     11    91%
apache_beam/transforms/ptransform.py                                                 294     29    90%
apache_beam/transforms/sideinputs.py                                                  93      2    98%
apache_beam/transforms/timeutil.py                                                    57     13    77%
apache_beam/transforms/trigger.py                                                    599     72    88%
apache_beam/transforms/util.py                                                        75      5    93%
apache_beam/transforms/window.py                                                     206     25    88%
apache_beam/typehints/__init__.py                                                      3      0   100%
apache_beam/typehints/decorators.py                                                  170      9    95%
apache_beam/typehints/opcodes.py                                                     157     20    87%
apache_beam/typehints/trivial_inference.py                                           262     38    85%
apache_beam/typehints/typecheck.py                                                    96      1    99%
apache_beam/typehints/typehints.py                                                   401     38    91%
apache_beam/utils/__init__.py                                                          2      0   100%
apache_beam/utils/annotations.py                                                      21      0   100%
apache_beam/utils/counters.py                                                         58     31    47%
apache_beam/utils/path.py                                                              6      0   100%
apache_beam/utils/pipeline_options.py                                                168      7    96%
apache_beam/utils/pipeline_options_validator.py                                       94      1    99%
apache_beam/utils/processes.py                                                        22      0   100%
apache_beam/utils/proto_utils.py                                                      19      0   100%
apache_beam/utils/retry.py                                                            68      3    96%
apache_beam/utils/timestamp.py                                                       105      2    98%
apache_beam/utils/urns.py                                                              6      0   100%
apache_beam/utils/windowed_value.py                                                   42      3    93%
apache_beam/version.py                                                                22     17    23%
------------------------------------------------------------------------------------------------------
TOTAL                                                                              15682   1900    88%`

**Comment by aaltay** [comment]
R: @sb2nov

**Comment by sb2nov** [comment]
@tibkiss we cover these tests with different tox profiles [[1]](https://github.com/apache/beam/blob/master/sdks/python/tox.ini#L61). In the pre-submit tests for the python-sdk we have three profiles of tests right now (beam without dependencies, beam with GCP, beam with cython).

The default tests do not enable GCP by default so that a user can work/develop on beam without having to depend on any Google Cloud specific dependencies. I agree that coverage on the default profile is not correctly representative of the state of the project but this is done so that if someone runs `python setup.py test` that should just work without throwing errors due to any particular runner specific dependencies.

[1] https://github.com/apache/beam/blob/master/sdks/python/tox.ini#L61

**Comment by tibkiss** [comment]
@sb2nov : Thanks for your comments - I officially need glasses now to treat my shortsightedness.

**Pull request closed without merging**
