### PR TITLE
Undo changes to BeamModulePlugin.groovy

### PR DESCRIPTION
**Pull request by damccorm**
These were added in #28255 but it looks like the assumption that these would function normally was baked deeper than we were aware of.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by damccorm** [comment]
@volatilemolotov this actually works and the snapshot publishes correctly - https://github.com/apache/beam/actions/runs/6112953970/job/16591456917 publishes the most recent one on Sept 7. For example https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-transform-service-launcher/2.51.0-SNAPSHOT/

I guess the gradle publish job already automatically appends a unique timestamp

**Comment by volatilemolotov** [comment]
> I guess the gradle publish job already automatically appends a unique timestamp
This was not clear to me unfortunately. I guess it was deeper somewhere.

If the versioning is correct now then lets merge this

**Review by Abacn — APPROVED** [review]
LGTM, thanks!

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Just notice that this PR does not trigger Java PreCommit GitHub Action. We'll need to add beammoduleplugin to its triggering path

**Comment by damccorm** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by damccorm** [comment]
Run Java_Spark3_Versions PreCommit

**Comment by damccorm** [comment]
Run Python_Runners PreCommit

**Comment by damccorm** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
This is normal "maven dependency" behavior by design. "SNAPSHOT" is a magic keyword that turns into a date stamp when publishing.

**Comment by kennknowles** [comment]
It works at both ends: when a client depends on a SNAPSHOT version, it will grab the latest datestamped version available.

**Pull request merged**
