### PR TITLE
[BEAM-2179] Archetype generate-sources.sh cleanup the existing sources before rsync

### PR DESCRIPTION
**Pull request by jbonofre**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`.
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @dhalperi 
CC: @aviemzur

**Comment by dhalperi** [comment]
R: -@dhalperi @kennknowles 

I believe this can be done by simply changing the command-line arguments to `rsync`. Kenn knows more.

**Comment by kennknowles** [comment]
Adding `--delete` to the `rsync` command is the right way to do this bit. I think there's a further need for a couple of things like a `provided` scope dependency from examples to archetypes. I've hit issues even then so I think we may have a build order issue just within this module.

**Comment by jbonofre** [comment]
Thanks for the feedback. I'm updating the PR by adding `--delete` instead of `rm -r`.

**Comment by jbonofre** [comment]
Hmmm, it seems that `--delete` doesn't fully work. I'm digging and I will update the PR soon.

**Comment by jbonofre** [comment]
I got it: as `generate-sources.sh` calls `rsync` several times, the second execution removes the files copied from the first one. That's why `rsync --delete` doesn't work as `rm -r`.

**Comment by jbonofre** [comment]
@kennknowles I updated the PR to use `rsync --delete` instead of `rm -r`. Please, let me know if it's OK for you.

**Comment by kennknowles** [comment]
LGTM if presubmit passes. You should probably manually build the archetype and inspect it and also browse the Jenkins logs to see that the expected tests ran against the archetype.

**Comment by jbonofre** [comment]
Checks passed. I checked locally and it looks good. @kennknowles do you mind if I merged this pull request ? Thanks !

**Comment by kennknowles** [comment]
LGTM. Go ahead and squash and merge.

**Pull request closed without merging**
