### PR TITLE
[cherry-pick][release-2.38.0][BEAM-14282] Re-raise exceptions swallowed in several Python I/O connectors

### PR DESCRIPTION
**Pull request by chamikaramj**
This cherry-picks https://github.com/apache/beam/pull/17329 to the 2.38.0 release branch.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @youngoli

**Comment by chamikaramj** [comment]
Run PythonDocs PreCommit

**Comment by chamikaramj** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Run PythonDocs PreCommit

**Comment by chamikaramj** [comment]
PythonDocs failure doesn't seem to be related:

ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/jenkins/jenkins-slave/workspace/beam_PreCommit_PythonDocs_Phrase/src/sdks/python/test-suites/tox/pycommon/build/srcs/sdks/python/target/.tox-py38-docs/py38-docs/lib/python3.8/site-packages/jinja2/__init__.py)
18:46:23 Command exited with non-zero status 1

**Comment by chamikaramj** [comment]
Pydocs failure seems to be due to https://issues.apache.org/jira/browse/BEAM-14172 (unrelated to this PR).

cc: @kerrydc

**Comment by kennknowles** [comment]
Agree. LGTM.

**Comment by kennknowles** [comment]
(but obviously wait for release manager and let them do the merge)

**Review by youngoli — APPROVED** [review]

**Comment by youngoli** [comment]
Looks good to me and definitely worth cherry-picking.

**Pull request merged**
