### PR TITLE
[BEAM-11584] Upgrade junit to version 4.13.1

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev

### CODE REVIEW

**Comment by iemejia** [comment]
Done to get rid too of https://github.com/google/error-prone/issues/1059#issuecomment-399172780

**Comment by iemejia** [comment]
Run PythonDocs PreCommit

**Comment by aromanenko-dev** [comment]
Run PythonDocs PreCommit

**Comment by aromanenko-dev** [comment]
Hmm, some checks are failed. Can it be related?

**Comment by iemejia** [comment]
I doubt so, Python jobs are not touched and the Java examples one had a timeout, let's try that one again.

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run PythonDocs PreCommit

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
