### PR TITLE
Python localfilesystem test

### PR DESCRIPTION
**Pull request by jbonofre**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
This test doesn't work on my machine, and also on couple of other machines. Maybe it would be better to test the matched files whatever the order is.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
I reproduce the Python SDK build failure on my machine:

```
TypeError: __new__() got an unexpected keyword argument 'file'
ERROR: InvocationError: '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_MavenInstall/src/sdks/python/target/.tox/py27gcp/bin/python apache_beam/examples/complete/autocomplete_test.py'
```
Let me fix that in another PR.

**Comment by jbonofre** [comment]
retest this please

**Comment by aaltay** [comment]
I think tests are failing with https://issues.apache.org/jira/browse/BEAM-3343.

I do not believe failures are related to this PR.

**Comment by udim** [comment]
LGTM, was about to fix this myself. Thanks.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
The build failure is not related to this PR. I will merge anyway. Thanks for the review !

**Pull request merged**
