### PR TITLE
[BEAM-2223] PipelineOptionsFactory: improve debuggability

### PR DESCRIPTION
**Pull request by dhalperi**
Include the name of the offending interface in the error message

R: @lukecwik

### CODE REVIEW

**Comment by aaltay** [comment]
LGTM

**Comment by lukecwik** [comment]
I'm guessing that you added a wrapping runtime exception instead of improving all the messages of the places we currently throw because the exception your getting is from some location we don't have control over?

**Comment by dhalperi** [comment]
@lukecwik See the stack trace in BEAM-2223.

It is plausible that we could wrap the [ClassLoader](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/options/PipelineOptionsFactory.java#L606) invocations directly, but given that we get `Error` thrown in various places it seemed safer to have a catch-all at the front door.

Thoughts?

**Comment by lukecwik** [comment]
Its just that the message from the failure will not be the top exception so users will be:
failed to validate MyIface.class
...lines of stack trace...
actual validation failures
...some more lines of stack trace...

**Pull request closed without merging**
