### PR TITLE
Beam-2383 round function

### PR DESCRIPTION
**Pull request by app-tarush**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by app-tarush** [comment]
@XuMingmin The build is not complete due to error in the python module. help me how it can be resolved?

**Comment by app-tarush** [comment]
@xumingming plz help me on this. Build is failing due python module.

**Comment by xumingming** [comment]
@app-tarush the build failure is not related to your changes. It's already fixed in master, once #3287 is merged, this error will be gone.

**Comment by app-tarush** [comment]
@xumingming thank you!! I request you to kindly review this PR #3301.

**Comment by app-tarush** [comment]
@xumingming I am closing this PR and will open a new one for Round function. Please ignore this PR #3301.

**Pull request closed without merging**
