### PR TITLE
[BEAM-2366] Don't try to pickle gen_protos in tests.

### PR DESCRIPTION
**Pull request by robertwb**
Tests that pickle the main session but are run from setup.py attempt
to pickle everything visible in setup.py.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
@aaltay

**Comment by aaltay** [comment]
Error is seems to be related to the cleanup of generated protos: "stderr: fatal: Not a git repository: sdks/python/.eggs/grpcio-wheels-build/grpcio/third_party/boringssl/../../.git/modules/third_party/boringssl" 

Could you also run a post commit with this change?

**Comment by robertwb** [comment]
Well that's a new error...

Jenkins: retest this please.

Also running post-commit at https://builds.apache.org/view/Beam/job/beam_PostCommit_Python_Verify/2318/

**Comment by aaltay** [comment]
It might be a leftover file that is causing an error. I am not sure how well jenkins does the cleanup.

**Comment by robertwb** [comment]
IIRC, cleanup on Jenkins is spotty at best.

**Comment by robertwb** [comment]
retest this please

**Comment by robertwb** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Pull request closed without merging**
