### PR TITLE
[BEAM-4406] Updating portable Dataflow major version numbers

### PR DESCRIPTION
**Pull request by youngoli**
Updating the major version numbers used for portable Dataflow pipelines in the Java and Python SDKs to match the version for native pipelines.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by lukecwik** [comment]
Run Dataflow ValidatesRunner

**Comment by youngoli** [comment]
Seems no new failures were introduced, but there are pre-existing failures from a few days ago.

I think this CL can wait until the ValidatesRunner tests are fixed if we want to be sure it succeeds.

**Comment by lukecwik** [comment]
There are a lot of failing tests there, better to have the validates runner tests fixed and rerun the tests.

**Comment by lukecwik** [comment]
Run Dataflow ValidatesRunner

**Comment by lukecwik** [comment]
Dataflow validates runner passed

**Pull request merged**
