### PR TITLE
Add retry logic for job creation

### PR DESCRIPTION
**Pull request by mariapython**

### CODE REVIEW

**Comment by mariapython** [comment]
R: @aaltay

**Comment by aaltay** [comment]
This is not the right level for retrying. The retry should happen around `submit_job_description`. This function has side effects like creating files in GCS location etc. and does not have a clean way for retrying. On the other `submit_job_description` is the integration point and is limited to http request.

**Comment by mariapython** [comment]
@aaltay: PTAL

**Comment by aaltay** [comment]
LGTM

**Pull request closed without merging**
