### PR TITLE
[test only] Test PostCommit runs for #31116

### PR DESCRIPTION
**Pull request by Abacn**
Reverts apache/beam#30770

the newly added test `TestFastAvro::test_avro_schema_to_beam_schema_with_nullable_atomic_fields` failing XVR test:

https://github.com/apache/beam/pull/30770#issuecomment-2077343964

### CODE REVIEW

**Comment by Abacn** [comment]
#30770 was several bug fix together. We can add them back one at a time for those did not have issue.

**Comment by Abacn** [comment]
R: @benkonz @ahmedabu98

**Comment by benkonz** [comment]
yeah, for some reason, in the flink runner specifically, after the `SqlTransform("SELECT * FROM PCOLLECTION")` in the `test_avro_schema_to_beam_schema_with_nullable_atomic_fields` test, there aren't any records outputted. I verified that the test works locally when I run `pytest -v apache_beam/io/avroio_test.py::TestFastAvro::test_avro_schema_to_beam_schema_w
ith_nullable_atomic_fields`, but with flink it just outputs an empty PCollection, still looking into this, but feel free to merge the revert. I'll post a new PR once I can get the test working, also open to feedback if anyone knows what's causing this behavior!

**Comment by benkonz** [comment]
@Abacn I found the cause of the issue in the test. The Flink runner wasn't able to access the local file-system with `avroio.ReadFromAvro(...)` and `avroio.WriteToAvro(...)`. I refactored the test in https://github.com/apache/beam/pull/31116 to create a PCollection from memory, rather than using temp directories, and verified that the previously failing gradle command works (`./gradlew :runners:flink:1.15:job-server:validatesCrossLanguageRunnerPythonUsingSql`). Could you take a look?

**Comment by Abacn** [comment]
@benkonz thanks for the fix. The test wasn't only failing on Flink runner, it's also failing on direct runner (and all runners)

See https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Spark3.yml?query=event%3Aschedule https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Samza.yml?query=event%3Aschedule https://github.com/apache/beam/actions/runs/8847577228/job/24295682944

Let me trigger tests for #31116 to see if the test is fixed on all runners

**Pull request closed without merging**
