### PR TITLE
Simplify SchemaTransform API

### PR DESCRIPTION
**Pull request by ahmedabu98**
Reduce boilerplate when writing a SchemaTransform. Context in this thread: https://lists.apache.org/thread/69cv98s9fr8qqvvg67wy9ydfmm8v12wd

These changes make SchemaTransform an empty abstract class extending `PTransform<PCollectionRowTuple, PCollectionRowTuple>`. This decision was made in part to keep `SchemaTransform` in the codebase instead of reducing the word to just a concept. Another reason of keeping it is for better readability (SchemaTransformProvider provides a SchemaTransform; a SchemaTransform is a transform that works with Row inputs/outputs). 
Open to changes regarding this (ie. if it makes more sense to remove the SchemaTransform class in favor of `PTransform<PCollectionRowTuple, PCollectionRowTuple>`.

The rest of the changes are for updating the SchemaTransformProviders in our codebase to reflect this change. The way we go from SchemaTransformProvider to PTransform is simplified, but this does not affect the way it's used

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Java_Debezium_IO_Direct PreCommit

**Comment by ahmedabu98** [comment]
Run Java_Debezium_IO_Direct PreCommit

**Comment by johnjcasey** [comment]
run java precommit

**Comment by johnjcasey** [comment]
run java precommit

**Comment by ahmedabu98** [comment]
Bigtable write schematransform was merged yesterday, will need to sync with head and change that one too

**Review by johnjcasey — APPROVED** [review]
LGTM, though a third set of eyes would be good here

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Pull request merged**
