### PR TITLE
Fix TestPipeline.runWithAdditionalOptionArgs ignore additionalArgs

### LINKED ISSUE #25699: [Bug]: Loss of pipeline options in validate if run TestPipeline with runWithAdditionalOptionArgs
### What happened?

Working example:

```java
@RunWith(JUnit4.class)
public class TestPipelineTest {

  @Rule public TestPipeline pipeline = TestPipeline.create();
  @Test
  public void testTestPipelineOptions() {
    pipeline.getOptions().setTempLocation("gs://some-location/");

    ArrayList<String> pipelineArgs = new ArrayList<String>();
    pipelineArgs.add("--tempLocation=gs://some-location/");

    pipeline.apply(Create.of(1, 2, 3)).apply(new ValidateTempLocation<>());

    // PipelineResult.State result = pipeline.run().waitUntilFinish(); // <-- replace with run(), test succeeded
    PipelineResult.State result = pipeline.runWithAdditionalOptionArgs(pipelineArgs).waitUntilFinish();
    assert(result == PipelineResult.State.DONE);
 }

 static class ValidateTempLocation<T> extends PTransform<PCollection<T>, PCollection<T>> {
   @Override
   public void validate(PipelineOptions pipelineOptions) {
    assert(!Strings.isNullOrEmpty(pipelineOptions.getTempLocation()));
   }

   public PCollection<T> expand(PCollection<T> input) {
     // assert(!Strings.isNullOrEmpty(pipelineOptions.getTempLocation()));
     return input.apply(ParDo.of(new PassthroughFn<>()));
   }
 }

 static class PassthroughFn<T> extends DoFn<T, T> {
   @ProcessElement
   public void process(ProcessContext ctx) {
     ctx.output(ctx.element());
   }
 }
}
```

in this example, the pipeline option "tempLocation" is set both manually and in pipelineArgs, neither of them was effective. The validate fails with null tempLocation.

Actually, the option is present in pipeline expansion time (commented out the asset in `expand` verifies this (done when apply() is called). However, the pipeline option is just not present in validate time.

If run with run(), instead of `runWithAdditionalOptionArgs()`, test succeeded.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #25699

* Fix TestPipeline.runWithAdditionalOptionArgs ignore additionalArgs when system property PROPERTY_BEAM_TEST_PIPELINE_OPTIONS is empty

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by Abacn** [comment]
R: @pabloem

**Comment by pabloem** [comment]
LGTM!

**Pull request merged**
