### PR TITLE
[BEAM-12572] - Java examples should get continuously exercised on at least 2 runners

### PR DESCRIPTION
**Pull request by fernando-wizeline**
Hi everyone,
This is a companion PR to [PR16609](https://github.com/apache/beam/pull/16609)

UserScore and HourlyTeamScore have been updated to better mimic the way the examples would be executed: instead of getting the data from memory, it is now being pulled from a csv file.

Hi @kileys! Adding you as a reviewer for this one, since it looks like you'll be also reviewing PR16609.

The rest of the tests for DataTokenization, LeaderBoard and StatefulTeamScore will be submitted in another PR, but wanted to get these two out there since they are already working as expected.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kileys** [comment]
Is there a reason we have to use csv files? Could you also fix the test failures?

**Comment by kileys** [comment]
Unless I'm misunderstanding this PR, I believe the files you're changing are meant to be unit tests for the example classes. You'll want to create a test file that ends with *It.java and the example classes should have csv files uploaded in GCS you can use for your end to end test

For example:
https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/complete/game/UserScore.java#L216

**Comment by kileys** [comment]
Example for an integration test: https://github.com/apache/beam/blob/master/examples/java/src/test/java/org/apache/beam/examples/complete/TopWikipediaSessionsIT.java

**Comment by fernando-wizeline** [comment]
> Unless I'm misunderstanding this PR, I believe the files you're changing are meant to be unit tests for the example classes. You'll want to create a test file that ends with *It.java and the example classes should have csv files uploaded in GCS you can use for your end to end test
> 
> For example: https://github.com/apache/beam/blob/master/examples/java/src/main/java/org/apache/beam/examples/complete/game/UserScore.java#L216

**Pull request closed without merging**
