### PR TITLE
Changed BeamPython FnAPI state channel to use secure connection when credentials provided

### PR DESCRIPTION
**Pull request by CraigChambersG**
This allows using a single secure port for all communication between SDK harness and runner harness over the FnAPI, rather than a mix of secure and insecure channels.

R: @tvalentyn 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by CraigChambersG** [comment]
run python postcommit

**Comment by tvalentyn** [comment]
Note that you can combine (squash) the commits to keep commits meaningful. I usually do this via:
```  
git pull --rebase=interactive origin master
git push tvalentyn local_branch_name --force
```

**Comment by CraigChambersG** [comment]
Thanks!  I'd love to learn how to do this.  Of those names like "origin"
"master" "local_branch_name" which are fixed constants and which are
supposed to refer to things in my own client?  I've previously been burned
by copying too literally commands that work for one person but break for
me.  For example, "upstream" seems to mean different things for different
sources, and mixing leads to hosed clients.

**Comment by robertwb** [comment]
Thanks, this looks good. Merging.

**Comment by robertwb** [comment]
The names here are generally conventions.

In your client, you can do

    git remote -v

to list all your "remotes" i.e. other repositories that you push and pull
to. You can also do

    git branch

to list all your branches.

By default when you clone a fresh repository, you get a remote called
"origin" that points to wherever you cloned it from. New (and most
existing) branches have a "master" branch by default (e.g. beam HEAD is the
master branch on https://github.com/apache/beam). So

    git pull --rebase=interactive origin master

pulls the branch "master" from the remote "origin" (presumably
github.com/apache/beam) into your own branch, and the --rebase=interactive
means take all your local commits and attempt to apply them on top of
origin/master, rather than creating a merge commit, interactively.
(Personally I typically do this in two steps, "git fetch origin master"
pulls all the remote changes into my repo (but not into any of my branches)
then "git rebase [-i]" rebases my current branch on top of it.

    git push [remote_name] [branch_name] [--force]

will push branch_name (defaults to the current branch) to remote (branches
can have a default remote set up) and the force means overwrite what's
there if it differs (needed after a rebase).

Another thing you can to save your work is if you're on a branch and
concerned about messing it up, you can do "git checkout -b
some-branch-backup" to make a copy of your current branch and then if you
mess up your current branch horrendously you can delete it (git branch -d
branch-name) and re-create the branch from your backup (git branch -b
some-branch some-branch-backup). Hopefully that's useful for being able to
experiment more freely, which will help in learning git.

**Pull request merged**
