### PR TITLE
Add pytest logging in VC tests.

### PR DESCRIPTION
**Pull request by tvalentyn**
fixes: #23277

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Dataflow Python ValidatesContainer ARM

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer ARM

**Comment by tvalentyn** [comment]
Run Python ValidatesContainer Dataflow ARM (3.9)

**Comment by tvalentyn** [comment]
Run Python ValidatesContainer Dataflow ARM 3.9

**Comment by tvalentyn** [comment]
R: @celeste-zeng

**Review by celeste-zeng — APPROVED** [review]

**Comment by tvalentyn** [comment]
Tested on: https://github.com/apache/beam/pull/28000#issuecomment-1678157955
GHA: https://github.com/apache/beam/actions/runs/5860964019/job/15890128945#step:38:1421

**Pull request merged**
