### PR TITLE
Functional interface for Fn API instructions

### PR DESCRIPTION
**Pull request by kennknowles**
Adds a simple functional interface so you can use lambdas to serve Fn API instructions

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by kennknowles** [comment]
Question on that - currently `SdkHarnessClient` closes the `FnApiControlClient`. I'm not sure it should do that since it is injected and I think it is reasonable that an `InstructionRequestHandler` could be safe for multiple users. More pragmatically, it largely exists to inject a lambda for testing. Ownership should be made utterly explicit either way. So in current revision I removed that.

**Comment by tgroh** [comment]
I'm fine with that flow, but then you should make sure that the `FnApiControlClientPoolService` closes its clients when it is closed

**Comment by kennknowles** [comment]
Considering it, really these should both in try-with-resources. So, it is far fetched, but I can see something like:

```java
try (FnApiControlClient controlClient = beamFnControlService.get()) {
   ... do things ...
   try (SdkHarnessClient sdkClient = SdkHarnessClient.usingFnApiClient(controlClient, ...)) {
      ... do inner things ...
   }
   ... do other things ...
}
```

Let's see where experience leads us, once we have 1 or 2 runners using this.

**Comment by kennknowles** [comment]
Squashed mechanically.

**Pull request merged**
