### PR TITLE
[BEAM-8183] restructure Flink portable jars to support multiple pipel…

### PR DESCRIPTION
**Pull request by ibzib**
…ines

R: @angoenka @tweise 

This is basically just a restructuring of the Flink portable jars to enable them to include and toggle between different pipelines. Specifically, this PR changes only the _structure_ and _execution_ of portable jars. This PR does not change the existing behavior and *does not implement a way to actually create portable jars with multiple pipelines*, although it would be fairly straightforward to roll such a jar oneself from existing single-pipeline jars.

Each pipeline lives in the jar under a subdirectory of `BEAM-PIPELINE`, and different subdirectories can be chosen using the new `--base-job-name` flag at runtime.

I included this in the Javadoc, but here it is formatted:
<p>Jar layout:
<ul>
  <li>META-INF/
      <ul>
        <li>MANIFEST.MF
      </ul>
  <li>BEAM-PIPELINE/
      <ul>
        <li>[1st pipeline (default)]
            <ul>
              <li>pipeline.json
              <li>pipeline-options.json
              <li>artifact-manifest.json
              <li>artifacts/
                  <ul>
                    <li>...artifact files...
                  </ul>
            </ul>
        <li>[nth pipeline]
            <ul>
              Same as above
        </ul>
  </ul>
  <li>...Java classes...
</ul>

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by tweise** [comment]
@ibzib thanks, this comes timely as I'm already using the 2.16 release to create the jar and also got it working in our deployment. So I will be able to try this PR in real world! 

Just for clarification, is the intention that the user creates a multi-pipeline jar by merging multiple output jars using zip tooling? Or can I perhaps simply use the previous iteration output jar as input to keep on adding pipelines?

**Comment by tweise** [comment]
I tested the inclusion of multiple pipelines using output jar as jobserver jar (just had to hack MANIFEST) and see multiple pipelines included:
```
$ jar -tvf beam-pipeline.jar | grep BEAM
 43760 Thu Oct 10 07:27:00 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010142647-d4df5a63/pipeline.json
  2104 Thu Oct 10 07:27:00 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010142647-d4df5a63/pipeline-options.json
  1700 Thu Oct 10 07:27:00 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010142647-d4df5a63/artifacts/ba316acc-a9f7-4443-9373-84c4ee7e1d72
   365 Thu Oct 10 07:27:00 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010142647-d4df5a63/artifact-manifest.json
 43760 Thu Oct 10 07:43:44 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010144331-363120ad/pipeline.json
  2041 Thu Oct 10 07:43:44 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010144331-363120ad/pipeline-options.json
  1700 Thu Oct 10 07:43:46 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010144331-363120ad/artifacts/d7674a76-2391-426e-918d-5b68a2c0e6b7
   365 Thu Oct 10 07:43:46 PDT 2019 BEAM-PIPELINE/BeamApp-tweise-1010144331-363120ad/artifact-manifest.json
```
I'm going to create a separate PR to allow for readable job names.

**Comment by tweise** [comment]
I don't think the default job name is picked up though:
```
$ flink run beam-pipeline.jar 
Starting execution of program

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Resource BEAM-PIPELINE/null/pipeline.json not found on classpath.
```

**Comment by tweise** [comment]
The default job name is not picked up, hence the NPE.

When I specify the job name, it works:
`flink run beam-pipeline.jar --base-job-name BeamApp-tweise-1010160808-d2be94ef`

**Comment by ibzib** [comment]
Run PortableJar_Flink PostCommit

**Comment by ibzib** [comment]
Huh, it's failing to get the default job name on Jenkins too. Weird. Works on my machine.

**Comment by ibzib** [comment]
Run PortableJar_Flink PostCommit

**Comment by ibzib** [comment]
Run PortableJar_Flink PostCommit

**Comment by ibzib** [comment]
Run PortableJar_Flink PostCommit

**Comment by ibzib** [comment]
@tweise I couldn't figure out what was going on with the jar manifests (the manifest it was fetching from the classpath was somehow different than the manifest I was writing) so I gave up and decided to add my own `pipeline-manifest.json` file that just contains the default job name as its only field.

**Comment by tweise** [comment]
@ibzib I don't think with the previous code there was a guarantee that you would get the manifest from the same jar: `PortablePipelineJarUtils.class.getClassLoader().getResourceAsStream(resourcePath);`

You would probably have to loop through the manifests available on the classpath until you find the attribute:

https://stackoverflow.com/questions/3777055/reading-manifest-mf-file-from-jar-file-using-java/18741685

**Comment by tweise** [comment]
Also verified that the original `--job_name` pipeline option will be honored.

**Pull request merged**
