### PR TITLE
[BEAM-10015] Fix output timestamp on dataflow runner

### PR DESCRIPTION
**Pull request by reuvenlax**
This issue is fixed by encoding the output timestamp in the timer tag so that we can recover it when firing the timer.

We also remove the old TimerData.of builders, as their accidental use caused the original bug.

### CODE REVIEW

**Comment by reuvenlax** [comment]
run dataflow validatesrunner

**Comment by reuvenlax** [comment]
R: @rehmanmuradali

**Comment by reuvenlax** [comment]
run dataflow validatesrunner

**Comment by rehmanmuradali** [comment]
LGTM. Thanks for taking care of it.

**Pull request merged**
