### PR TITLE
Eliminate null errors from JdbcIO

### PR DESCRIPTION
**Pull request by kennknowles**
This adds enough annotation and checks to re-enable nullness checking in JdbcIO. It does not do any significant refactor that might make it less error-prone.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by chamikaramj — APPROVED** [review]
Thanks. LGTM.

**Comment by kennknowles** [comment]
Just noting that I somehow broke `expand()` and haven't narrowed down how, so this is not ready for review.

**Comment by kennknowles** [comment]
R: @chamikaramj

**Comment by kennknowles** [comment]
Setting reviewer so the bot is happy. I need to find some time to fix up the tests

**Comment by apilloud** [comment]
r: @chamikaramj

**Comment by apilloud** [comment]
R: @chamikaramj

**Comment by apilloud** [comment]
stop reviewer notifications

**Comment by apilloud** [comment]
Review bot seems to be having problems...

**Comment by kennknowles** [comment]
Run Java_JDBC_IO_Direct PreCommit

**Comment by kennknowles** [comment]
The spotbugs failure does not reproduce for me locally so I will pull shenanigans to get the report from the jenkins box. We should probably find a way to at least archive the artifacts with the job.

**Comment by kennknowles** [comment]
Run Java_JDBC_IO_Direct PreCommit

**Comment by kennknowles** [comment]
I don't know why spotbugs succeeded locally. There is a multi-statement try-with-resources that I had to annotate to ignore the warning. By grabbing the file off the Jenkins box it was straightforward.

**Pull request merged**
