### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by lostluck**
You can run many tests automatically using release/src/main/scripts/mass_comment.py.

### CODE REVIEW

**Comment by tszerszen** [comment]
Run Seed Job

**Comment by lostluck** [comment]
Retest this

**Comment by lostluck** [comment]
Run Python 3.7 PostCommit

**Comment by lostluck** [comment]
Hmmm it seems I was mistaken and this did not automatically run all the post commits. Doing so now.

**Comment by lostluck** [comment]
Run Release Gradle Build

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Run Java PostCommit

**Comment by lostluck** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lostluck** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by lostluck** [comment]
Run Dataflow ValidatesRunner

**Comment by lostluck** [comment]
Run Flink ValidatesRunner

**Comment by lostluck** [comment]
Run Samza ValidatesRunner

**Comment by lostluck** [comment]
Run Spark ValidatesRunner

**Comment by lostluck** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by lostluck** [comment]
Run Python Spark ValidatesRunner

**Comment by lostluck** [comment]
Run Python Dataflow ValidatesContainer

**Comment by lostluck** [comment]
Run Python Dataflow ValidatesRunner

**Comment by lostluck** [comment]
Run Python Flink ValidatesRunner

**Comment by lostluck** [comment]
Run Twister2 ValidatesRunner

**Comment by lostluck** [comment]
Run Python 3.6 PostCommit

**Comment by lostluck** [comment]
Run Python 3.7 PostCommit

**Comment by lostluck** [comment]
Run Python 3.8 PostCommit

**Comment by lostluck** [comment]
Run SQL PostCommit

**Comment by lostluck** [comment]
Run Go PreCommit

**Comment by lostluck** [comment]
Run Java PreCommit

**Comment by lostluck** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by lostluck** [comment]
Run JavaPortabilityApi PreCommit

**Comment by lostluck** [comment]
Run Portable_Python PreCommit

**Comment by lostluck** [comment]
Run PythonLint PreCommit

**Comment by lostluck** [comment]
Run Python PreCommit

**Comment by lostluck** [comment]
Run Python DockerBuild PreCommit

**Comment by lostluck** [comment]
Run XVR_Direct PostCommit

**Comment by lostluck** [comment]
Run XVR_Flink PostCommit

**Comment by lostluck** [comment]
Run XVR_Spark PostCommit

**Comment by tszerszen** [comment]
Run Spotless PreCommit

**Comment by lostluck** [comment]
Retest This Please

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Google Cloud Dataflow Runner Python ValidatesContainer Tests

**Comment by lostluck** [comment]
Java Flink PortableValidatesRunner Batch Tests

**Comment by lostluck** [comment]
Run Python Dataflow ValidatesContainer

**Comment by lostluck** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by lostluck** [comment]
Run Python 3.7 PostCommit

**Comment by lostluck** [comment]
Run Python PreCommit

**Comment by lostluck** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by lostluck** [comment]
Run Python PreCommit

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Pull request closed without merging**
