### PR TITLE
[BEAM-3428] Merge Java8 examples in "main" Java examples

### PR DESCRIPTION
**Pull request by jbonofre**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [X] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jbonofre** [comment]
Good point. For now, I just merged all examples in an unique module and do the cleanup. Let me check the content ;)

**Comment by jkff** [comment]
Actually I just looked and I think MinimalWordCount is the only one. Others just need a regular Java8 cleanup (done in my PR).

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Yes, I think so. Do you want me to remove the "deprecated" `MinimalWordCountJava8` ?

**Comment by jkff** [comment]
Yes please :) Or more like: remove MinimalWordCount, and instead rename MinimalWordCountJava8 to MinimalWordCount.

**Comment by jbonofre** [comment]
Sounds good, I do it ;) Thanks !

**Comment by jbonofre** [comment]
Rebased using @jkff update ;)

**Comment by jkff** [comment]
MinimalWordCount still needs to be replaced with the code from MinimalWordCountJava8, right? Other than that, LGTM!

**Comment by jbonofre** [comment]
Correct for the `MinimalWordCount`, I'm changing that ;)

**Comment by jbonofre** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by iemejia** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
