### PR TITLE
[BEAM-8756] Google cloud client libraries to use 2019 versions

### PR DESCRIPTION
**Pull request by suztomo**
Fixes https://issues.apache.org/jira/projects/BEAM/issues/BEAM-8756

- google_clients_version from 1.28.0 to 1.30.3
- libraries related to google-api-client; `proto-google-` and `google-api-services-` libraries
- google-cloud-core from 1.61.0 to 1.92.2
- proto-google-cloud-datacatalog-v1beta1 from 0.27.0-alpha to 0.29.0-alpha. This is not latest, which would require code change (I will raise another PR for this)

# Linkage Check Result

The following modules use the affected libraries

## beam-sdks-java-extensions-google-cloud-platform-core
- before: https://gist.github.com/suztomo/c31254c5cc4a4f6942a7ea6784f823f3
- after: https://gist.github.com/suztomo/8bc7b55b796c492191a3a80463828da1 (same as above)

## beam-sdks-java-io-google-cloud-platform
- before: https://gist.github.com/suztomo/ce0b4b9c8e347ec8f27e7f2a03129f41
- after: https://gist.github.com/suztomo/159579ecd899796ecf1a268ab608a4df (same as above)

## beam-runners-google-cloud-dataflow-java
- before: https://gist.github.com/suztomo/8cce31ad29289fa7f4ac92862a430f37
- after: https://gist.github.com/suztomo/28059da42ceceb3224b81df42beb8a03 (same as above)

## beam-sdks-java-io-hadoop-format
- before: https://gist.github.com/suztomo/119063490c5e6e517c31a64b619a52c4
- after: https://gist.github.com/suztomo/de96101b13488cb7d4150a836a3108bc (same as above)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by amaliujia** [comment]
retest this please

**Comment by amaliujia** [comment]
Run Java PostCommit
Run Java HadoopFormatIO Performance Test
Run BigQueryIO Streaming Performance Test Java
Run Dataflow ValidatesRunner
Run Spark ValidatesRunner
Run SQL Postcommit

**Comment by suztomo** [comment]
@amaliujia Would you run one command per one comment? (I don't think Jenkins recognizes multiple at once)

**Comment by amaliujia** [comment]
Run Java PostCommit

**Comment by amaliujia** [comment]
Run Java HadoopFormatIO Performance Test

**Comment by amaliujia** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by amaliujia** [comment]
Run BigQueryIO Streaming Performance Test Java

**Comment by amaliujia** [comment]
Run Dataflow ValidatesRunner

**Comment by amaliujia** [comment]
Run Spark ValidatesRunner

**Comment by amaliujia** [comment]
Run SQL Postcommit

**Comment by suztomo** [comment]
Too many open files ?

```
14:34:34 > Task :sdks:java:io:hbase:compileTestJava
14:34:34 /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/hbase/src/test/java/org/apache/beam/sdk/io/hbase/HBaseResultCoderTest.java:18: error: cannot access org.apache.beam.sdk.io.hbase
14:34:34 package org.apache.beam.sdk.io.hbase;
14:34:34 ^
14:34:34   /home/jenkins/.gradle/caches/modules-2/files-2.1/ognl/ognl/3.1.12/a7fa0db32f882cd3bb41ec6c489853b3bfb6aebc/ognl-3.1.12.jar: Too many open files
14:34:34 /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/hbase/src/test/java/org/apache/beam/sdk/io/hbase/HBaseMutationCoderTest.java:34: error: cannot access java.lang
14:34:34 public class HBaseMutationCoderTest {
14:34:34        ^
14:34:34   /home/jenkins/.gradle/caches/modules-2/files-2.1/ognl/ognl/3.1.12/a7fa0db32f882cd3bb41ec6c489853b3bfb6aebc/ognl-3.1.12.jar: Too many open files
```
https://builds.apache.org/job/beam_PreCommit_Java_Commit/9724/console

@amaliujia Thanks.

**Comment by amaliujia** [comment]
Run Java PreCommit

**Comment by amaliujia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by amaliujia** [comment]
Run JavaPortabilityApi PreCommit

**Comment by suztomo** [comment]
R: @lukecwik @kennknowles 

21 successful checks!

**Comment by udim** [comment]
This broke nightly snapshots: https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/874/console

https://issues.apache.org/jira/browse/BEAM-9246

Any idea what needs to be done?

**Comment by ibzib** [comment]
cc self @ibzib

**Comment by suztomo** [comment]
Created PR to fix that.
https://github.com/apache/beam/pull/10756

**Comment by lukecwik** [comment]
Thanks for the fix, sorry for the miss during review.

**Pull request merged**
