### PR TITLE
[BEAM-4624] add comparison operator test

### PR DESCRIPTION
**Pull request by amaliujia**
Test a part of comparison operators.

##### What is missing
ALL and SOME kind of comparison operators (e.g. < ALL).

ALL and SOME need to expand a sub query (e.g. `< ALL (SELECT * FROM table)`). However current config  option `expand ` is true where Calcite requires `ALL is only supported if expand = false`. 
(check https://calcite.apache.org/apidocs/org/apache/calcite/sql2rel/SqlToRelConverter.Config.html#isExpand-- for more information).

### CODE REVIEW

**Comment by amaliujia** [comment]
java run precommit

**Comment by amaliujia** [comment]
R @kennknowles 
cc @akedin @apilloud

**Comment by amaliujia** [comment]
run java precommit

**Comment by kennknowles** [comment]
LGTM too. Squash the commits?

**Comment by amaliujia** [comment]
Commits squashed

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
run python precommit

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
@kennknowles Ping

**Pull request merged**
