### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by markflyhigh**
Please comment as instructions below, one phrase per comment:

  **Run Release Gradle Build**
Run Go PostCommit
Run Java PostCommit
Run Java PostCommit
Run Java PortabilityApi PostCommit
Run Java Flink PortableValidatesRunner Batch
Run Java Flink PortableValidatesRunner Streaming
Run Apex ValidatesRunner
Run Dataflow ValidatesRunner
Run Flink ValidatesRunner
Run Gearpump ValidatesRunner
Run Dataflow PortabilityApi ValidatesRunner
Run Samza ValidatesRunner
Run Spark ValidatesRunner
Run Python Dataflow ValidatesContainer
Run Python Dataflow ValidatesRunner
Run Python Flink ValidatesRunner
Run Python PostCommit
Run SQL PostCommit
Run Go PreCommit
Run Java PreCommit
Run Java_Examples_Dataflow PreCommit
Run JavaPortabilityApi PreCommit
Run Portable_Python PreCommit
Run Python PreCommit

### CODE REVIEW

**Comment by markflyhigh** [comment]
Run Release Gradle Build

**Comment by markflyhigh** [comment]
Run Go PostCommit

**Comment by markflyhigh** [comment]
Run Java PostCommit

**Comment by markflyhigh** [comment]
Run Java PortabilityApi PostCommit

**Comment by markflyhigh** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by markflyhigh** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by markflyhigh** [comment]
Run Apex ValidatesRunner

**Comment by markflyhigh** [comment]
Run Dataflow ValidatesRunner

**Comment by markflyhigh** [comment]
Run Flink ValidatesRunner

**Comment by markflyhigh** [comment]
Run Gearpump ValidatesRunner

**Comment by markflyhigh** [comment]
Run Samza ValidatesRunner

**Comment by markflyhigh** [comment]
Run Spark ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python Flink ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python Dataflow ValidatesContainer

**Comment by vectorijk** [comment]
Run Spark Runner Nexmark Tests

**Comment by vectorijk** [comment]
Run Dataflow Runner Nexmark Tests

**Comment by vectorijk** [comment]
Run Flink Runner Nexmark Tests

**Comment by markflyhigh** [comment]
Since we have few cherry-picks to release branch. I just rebased my test branch and rerun tests on that.

**Comment by markflyhigh** [comment]
Run Portable_Python PreCommit

**Comment by markflyhigh** [comment]
Run Python_PVR_Flink PreCommit

**Comment by markflyhigh** [comment]
Run Release Gradle Build

**Comment by markflyhigh** [comment]
Run Java PortabilityApi PostCommit

**Comment by markflyhigh** [comment]
Run Java PreCommit

**Comment by markflyhigh** [comment]
Run SQL PostCommit

**Comment by markflyhigh** [comment]
Run Go PreCommit

**Comment by markflyhigh** [comment]
Run Flink ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python Flink ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python PreCommit

**Comment by markflyhigh** [comment]
Run Python 2 PostCommit

**Comment by markflyhigh** [comment]
Run Python 3.6 PostCommit

**Comment by markflyhigh** [comment]
Run Python 3.6 PostCommit

**Comment by markflyhigh** [comment]
Run Python 3.6 PostCommit

**Comment by markflyhigh** [comment]
Run Python 3.7 PostCommit

**Comment by markflyhigh** [comment]
Run Python 2 PostCommit

**Comment by markflyhigh** [comment]
Run Python 2 PostCommit

**Comment by markflyhigh** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by markflyhigh** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by markflyhigh** [comment]
Run Python Dataflow ValidatesRunner

**Comment by markflyhigh** [comment]
Run Python Dataflow ValidatesContainer

**Comment by markflyhigh** [comment]
Run Java PostCommit

**Comment by markflyhigh** [comment]
RC1 is out for voting. We can close this PR.

**Pull request closed without merging**
