### PR TITLE
Send error response for process bundle progress instead of throwing and catching exception

### PR DESCRIPTION
**Pull request by angoenka**
DESCRIPTION HERE

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

The current implementation throws and catches the exception if worker has not yet started working on the process_bundle request. 
Runner harness schedules 300 process_bundle requests and only a few of them are in process at any time. This cause the process_bundle_progress request to fail with exception. This frequent exception fills up the disk and cause issues. So instead of throwing exception, we can simply return error response.

### CODE REVIEW

**Comment by angoenka** [comment]
@robertwb Can you please have a look?

**Comment by robertwb** [comment]
Do we expect to be able to interpret these errors more intelligently in the runner harness?

**Comment by angoenka** [comment]
We do send the error response back to the RunnerHarness so it can choose to act upon it accordingly.
RunnerHarness start progressReport check after 100ms from processBundle request hence the 1st few progress report almost always fails which makes this exception part of normal work flow. So in this case we should only let RunnnerHarness know that the work is not started instead of throwing an exception.

**Comment by robertwb** [comment]
OK, I'm fine with that. Could you look at the Python failures?

**Comment by angoenka** [comment]
retest this please

**Comment by angoenka** [comment]
@robertwb testing after rebasing worked.

**Pull request merged**
