### PR TITLE
[BEAM-6028] Revert "Merge pull request #6979: Add helper task to print pipeline options for Dataflow portability

### PR DESCRIPTION
**Pull request by swegner**
This appears to be breaking post-commit tests:
https://builds.apache.org/job/beam_PreCommit_JavaPortabilityApi_Cron/26

This reverts commit 42984a821b3e73aee2966d11d7fb436b5ff22b68, reversing
changes made to b558c4d4f21ae1a48fb51afedd849b1f75ff3325.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by swegner** [comment]
Run JavaPortabilityApi Precommit

**Comment by swegner** [comment]
It seems highly likely that PR #6979 is the culprit. This is a pure revert (`git revert 42984a8 -m 1`).

I believe it would be safe to merge without waiting for a test signal. Although the beam_PreCommit_JavaPortabilityApi_Cron historically runs in [about 20 mins](https://builds.apache.org/job/beam_PreCommit_JavaPortabilityApi_Cron/buildTimeTrend), so I believe it would be ok to wait for this signal.

R: @chamikaramj

**Comment by chamikaramj** [comment]
Thanks. Let's wait for the signal.

**Comment by swegner** [comment]
Previously failing portability tests now [succeed](https://builds.apache.org/job/beam_PreCommit_JavaPortabilityApi_Phrase/2/). I believe this is ready to merge.

@chamikaramj PTAL

**Comment by chamikaramj** [comment]
LGTM. Thanks. 

Looks like pre-commit failed. Rerunning.

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by swegner** [comment]
Tests pass now; merging.

**Pull request merged**
