### PR TITLE
[BEAM-14269] PulsarIOTest.testReadFromSimpleTopic flaky test

### PR DESCRIPTION
**Pull request by MarcoRob**
PulsarIOTest uses a shared client across all tests, looks is the reason for the flaky test since is a race condition when multiple tests run in parallel.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Status update: looks the issue regarding this flaky test is due the `seek function` from Pulsar Client, when it was seeking the timestamp, sometimes it sought a previous timestamp that was already processed then the error that the timestamp was not in the new range
Solution approach: set a validation when the start timestamp or initial restriction is greater than the current timestamp, then re-run the process until it grabs the correct timestamp.

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Run Java PreCommit

**Comment by MarcoRob** [comment]
Hi @johnjcasey 
I have been monitoring this flaky test which is throwing the following issue
`Caused by: java.lang.IllegalArgumentException: Trying to claim offset 1648580086959 before start of the range [1648580087254, 1648580087266)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at org.apache.beam.sdk.transforms.splittabledofn.OffsetRangeTracker.tryClaim(OffsetRangeTracker.java:97)
	at org.apache.beam.sdk.transforms.splittabledofn.OffsetRangeTracker.tryClaim(OffsetRangeTracker.java:38)
	at org.apache.beam.repackaged.direct_java.sdk.fn.splittabledofn.RestrictionTrackers$RestrictionTrackerObserver.tryClaim(RestrictionTrackers.java:59)
	at org.apache.beam.sdk.io.pulsar.ReadFromPulsarDoFn.processElement(ReadFromPulsarDoFn.java:170)`

The issue looks like is due when the [processElement](https://github.com/apache/beam/blob/345452c6819e4c56891dd6145d751323ee4c89b2/sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFn.java#L156) search for the timestamp it fails because sometimes it set the cursor of the offset to a previous position that has already been processed which produces the above issue.

I set the following [validation](https://github.com/apache/beam/blob/345452c6819e4c56891dd6145d751323ee4c89b2/sdks/java/io/pulsar/src/main/java/org/apache/beam/sdk/io/pulsar/ReadFromPulsarDoFn.java#L171) when this issue happens and if it does resume again the process until it is correct, let me know what do you think about it?

**Comment by MarcoRob** [comment]
Hi @johnjcasey 
Could you help me to validate if my fix to this issue is correct? 
You can see above this comment the detail on the current issue
Thanks in advance

**Comment by johnjcasey** [comment]
It seems like this is an issue with your seeking & committing logic to me. If seek is finding an element that has already been claimed, it would imply that that element hasn't been committed properly, or that your splitting logic isn't splitting correctly. Just retrying doesn't seem like a good pattern

**Comment by MarcoRob** [comment]
> It seems like this is an issue with your seeking & committing logic to me. If seek is finding an element that has already been claimed, it would imply that that element hasn't been committed properly, or that your splitting logic isn't splitting correctly. Just retrying doesn't seem like a good pattern

Since the current client we are using is a `Reader Interface` and this interface doesn't commit the message, only reads. Then it would require committing/acknowledging the message using the `Consumer interface` or the `Admin client` which as well is another thing to add within the `TODO list` for the current IO.

Maybe @nlu90 can give us a better approach to the current issue?

**Comment by hpvd** [comment]
added this to [Parent issue] Support for Apache Pulsar #31078

**Pull request closed without merging**
