### PR TITLE
[BEAM-5907] Disable DF worker tests that do not work under parallel build

### PR DESCRIPTION
**Pull request by kennknowles**
I have unfortunately not had enough time to figure out the best way to refactor these tests. It appears that the entire test class may have similar issues, but only this method is known to have failed.

If skipping this method or the class enables parallel tests, I think that is worthwhile. The tests themselves do add value for Dataflow in portability, so it should be temporary or they can be run another way.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @boyuanzz 

What do you think about these tests temporarily being disabled? I do think it might be a medium project to rewrite them. I also am afraid that after I fix one, the next one might fail in the same way. It could end up being the whole class.

**Comment by kennknowles** [comment]
@adude3141 has analyzed this on #6864 that the particular method appears to also just have a real race condition, not necessarily a Mockito usage problem.

**Comment by adude3141** [comment]
Prepared something with countdown latch here [1]

[1] https://github.com/apache/beam/pull/6877

**Comment by kennknowles** [comment]
Yea, and this is just made worse by parallel builds. It is easy to repro without them, as shown in #6878.

**Comment by kennknowles** [comment]
Closing this to make a PR that is clearer.

**Pull request closed without merging**
