### PR TITLE
Add javadoc to getEstimatedSizeBytes

### PR DESCRIPTION
**Pull request by wtanaka**
based on code comment in BoundedReadFromUnboundedSource.java

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Gonna merge.

**Comment by jbonofre** [comment]
retest this please

**Comment by wtanaka** [comment]
rebasing

**Comment by jbonofre** [comment]
By the way, I fixed the checkstyle issue: you forgot `<p>` at the beginning of the new line.

**Comment by dhalperi** [comment]
Hmm -- I'm not sure the new Javadoc is correct. Where did you base this information on?

cc: @jkff

**Comment by jkff** [comment]
I'm fine with the current phrasing, though I'd replace "may" with "should". Even though in practice runners will gracefully treat multiple things as "unknown", I'd prefer to explicitly advertise only one of those things.

**Pull request closed without merging**
