### PR TITLE
[BEAM-8470] Create a new Spark runner based on Spark Structured streaming framework

### PR DESCRIPTION
**Pull request by echauchot**
- the runner passes 93% of the validates runner tests in batch mode. 

- Streaming mode is barely started (waiting for the multi-aggregations support in spark Structured Streaming framework from the Spark community)

- Runner can execute Nexmark

- Some things are not wired up yet

    - Beam Schemas not wired with Spark Schemas

    - Optional features of the model not implemented:  state api, timer api, splittable doFn api, … 

The history represents 11 months of work, it has already been squashed to isolable meaningful commits.

R: @aromanenko-dev 
CC: @kennknowles 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by echauchot** [comment]
@aromanenko-dev: I forgot to rebase on master and also, I need to put the ticket number in all commits

**Comment by echauchot** [comment]
@aromanenko-dev added the ticket name to the commit messages, will do rebase on master another time

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by aromanenko-dev** [comment]
I did run tests for old Spark Runner to make sure that nothing is broken

**Comment by aromanenko-dev** [comment]
Run Website PreCommit

**Comment by echauchot** [comment]
@aromanenko-dev I think this command runs the validates runner tests only for the "old" runner. I need to add a new jenkins script to be able to run the new ones

**Comment by echauchot** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
@echauchot  Yes, as I mentioned above I did it for **old runner** to make sure that nothing is broken because new runner is in the same package. 
Btw, could you run `spotlessApply` against spark runner package? Seems like many fails are because of this.

**Comment by echauchot** [comment]
Run Seed Job

**Comment by echauchot** [comment]
Run Seed Job

**Comment by echauchot** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by echauchot** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by echauchot** [comment]
@aromanenko-dev I think the error on the build is due to an out of sync with master, I'll do the rebase on master

**Comment by echauchot** [comment]
rebased on master

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
failure is in an unrelated part (dataflow). I suspect flakiness

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
dataflow still failing

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by echauchot** [comment]
@aromanenko-dev FYI it is normal the UTests are failing. I just figured that the tests were not properly configured after the merge of the 2 modules (wrong pipelineOptions used) + the changes on PipelineResult (no set of the testMode to true in the pipelineOptions to wait for PAssert). As a consequence all UTests passed no matter what. I fixed that with the last commit but PipelineResults tests fail. @RyanSkraba who authored this part will take a look at it when he has time.

**Comment by echauchot** [comment]
Run Java PreCommit

**Comment by echauchot** [comment]
@aromanenko-dev triggers are failing again. Maybe related to jenkins failure like before ?

**Comment by aromanenko-dev** [comment]
@lgajowy Don't you know by chance why Jenkins triggers are failing and there are not checks results here?

**Comment by aromanenko-dev** [comment]
Run Java PreCommit

**Comment by aromanenko-dev** [comment]
@echauchot Seems that it's already fixed

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by aromanenko-dev** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by echauchot** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Seed Job

**Comment by aromanenko-dev** [comment]
@echauchot I guess you need to run seed job every time when you push changes to be able run new added Jenkins job, like StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Spark ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Python PreCommit

**Comment by echauchot** [comment]
@aromanenko-dev is this so ? I thought seed job was only needed when jenkins scripts are modified

**Comment by echauchot** [comment]
@aromanenko-dev can we merge the PR now ?

**Comment by aromanenko-dev** [comment]
@echauchot Thanks! Yes, I think we are almost there. 
Do we show a warning message while running a pipeline with this new runner to prevent user that it's ready to use in production and should be used only on its own risk?

**Comment by echauchot** [comment]
@aromanenko-dev yes. The message in both LOG.info and javadoc is: 

> SparkStructuredStreamingRunner is based on spark structured streaming framework and is no more based on RDD/DStream API. See https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html It is still experimental, its coverage of the Beam model is partial.

+ @Experimental annotation

**Pull request merged**
