### PR TITLE
[BEAM-14464] More efficient grouping keys in precombiner table.

### PR DESCRIPTION
**Pull request by robertwb**
The current code constructs, hashes, and compares full WindowedValues
for the grouping key, which ends up dominating the time spent in the
combining table when using trivial combiners (like Sum.integers()).
We only need compare the (structural value of the) key and windows,
and can emit the windows in the global case.

Per added microbenchmarks, this is roughly a 50% improvement for
singly-windowed values, and roughly 2.5x improvement for the common
GlobalWindows case.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @y1chi

**Comment by lukecwik** [comment]
I have been looking for someone to review https://github.com/apache/beam/pull/17327, do you mind if we get that merged first and then take on this change?

**Review by y1chi — APPROVED** [review]
LGTM

**Comment by robertwb** [comment]
Thanks, Yichi! As mentioned, I'm going to hold off merging this until that other PR goes in.

**Comment by robertwb** [comment]
Failures

org.apache.beam.sdk.io.aws2.kinesis.KinesisIOWriteTest.testWriteFailure
org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImplTest.testInsertWithinRequestByteSizeLimits
org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOElasticTest.classMethod

look unrelated.

**Comment by robertwb** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
precommit is broken again due to checkStyle warnings

**Comment by robertwb** [comment]
Sure, we can hold off on this until that is in to avoid conflicts.

**Pull request merged**
