### PR TITLE
[BEAM-4341] Enforce ErrorProne analysis in google-cloud-platform IO

### PR DESCRIPTION
**Pull request by timrobertson100**
Enforces error prone by failing the build on warnings and addresses remaining issues not covered [in my previous PR](https://github.com/apache/beam/pull/5364) already merged by @jkff .

Perhaps @jkff could review?

CC @iemejia @swegner

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

### CODE REVIEW

**Comment by iemejia** [comment]
retest this please

**Comment by iemejia** [comment]
R: @jkff It seems some things were some how cached by gradle and not addressed by the previous PR, it also enforces the validation by default now.

**Comment by timrobertson100** [comment]
Yes, sorry about this @jkff. 
Because we hadn't enforced a fail on warning before I managed to build once, overlook some warnings and had not cleared the cache properly so was watching only the test stuff go through on the console.  Another good reason for this to be enforced as a build failure...
(It is now linked to the jira as well - we were doing them jira-less for a while there)

**Comment by timrobertson100** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Little reminder @jkff or @chamikaramj

**Comment by chamikaramj** [comment]
LGTM. Thanks Ismaël.

**Comment by timrobertson100** [comment]
Thanks @chamikaramj

**Comment by chamikaramj** [comment]
Thanks. Merging.

**Pull request merged**
