### PR TITLE
[BEAM-4053] Add a Go postcommit

### PR DESCRIPTION
**Pull request by alanmyrvold**
Add a Go postcommit. Initially the same as the precommit, but easier to measure the reliability when it runs postcommit.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by alanmyrvold** [comment]
+R: @aaltay @herohde ... PTAL?

**Comment by alanmyrvold** [comment]
Run Seed Job

**Comment by aaltay** [comment]
LGTM. @alanmyrvold do you want me to wait until you run tests? Or merge now?

**Comment by alanmyrvold** [comment]
Wait for tests.

**Comment by alanmyrvold** [comment]
Run Go PostCommit

**Comment by alanmyrvold** [comment]
Passed, https://builds.apache.org/view/A-D/view/Beam/job/beam_PostCommit_Go_GradleBuild/
@aaltay - can you merge?

**Pull request merged**
