### PR TITLE
[BEAM-6133] [SQL] Add support for TableMacro UDF

### PR DESCRIPTION
**Pull request by kanterov**
Now we support only ScalarFunction UDFs. In Calcite, there are other kinds of UDFs. With TableMacro UDFs users can connect external data sources in a similar way as in TableProvider, but without specifying a schema, or enumerating a list of existing tables in advance.

An example use case is connecting external metadata service and querying range of partitions.

```sql
SELECT COUNT(*) FROM table(my_udf('dataset', start = '2017-01-01', end = '2018-01-01'))
```

Where the implementation of `my_udf` will connect to this service, get file locations for a range of partitions, and translate to PTransform reading it.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kanterov** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
R: @apilloud @XuMingmin

**Comment by amaliujia** [comment]
This approach seems to be very useful. 

I have a question:

if a complicated query use TableMacro UDF to access the same table for multiple times, will underlying implementation connects the service only once, or multiple times? The latter case could limit the usage of TableMacro UDF due to redundant service requests.

**Comment by amaliujia** [comment]
This PR LGTM.

**Comment by kanterov** [comment]
@amaliujia table macros get expanded to relations during query planning, so it shouldn't query services a lot. It's possible to implement caching if needed, but, in my opinion, it's something that should be done by users, instead of being built-in.

**Comment by kanterov** [comment]
@apilloud @XuMingmin @amaliujia thanks for the review, I've addressed the comment, squashed, and rebased. As well as sent announcement email to dev@

**Comment by amaliujia** [comment]
Run Java PreCommit

**Comment by kanterov** [comment]
@apilloud @XuMingmin is there anything else to be done before merging?

**Pull request merged**
