### PR TITLE
flink-runner: constructs exception string only when neccessary, it re…

### PR DESCRIPTION
**Pull request by peihe**
…duces per-element expensive calls(String.format and getSimpleName) in FlinkAssignContext.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by peihe** [comment]
R: @JingsongLi @aljoscha

**Comment by peihe** [comment]
retest this please

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by aljoscha** [comment]
There's an unused import
```
2017-09-13T03:05:18.459 [ERROR] src/main/java/org/apache/beam/runners/flink/translation/functions/FlinkAssignContext.java:[20,15] (imports) UnusedImports: Unused import: com.google.common.base.Preconditions.checkArgument.
```

once that is fixed this LGTM! 👍

**Comment by peihe** [comment]
Run Flink ValidatesRunner

**Pull request closed without merging**
