### PR TITLE
Fix NullPointerException in ApexStateInternals

### PR DESCRIPTION
**Pull request by alexandrvl**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by alexandrvl** [comment]
Can someone please review?

**Comment by peihe** [comment]
R: @tweise

**Comment by tweise** [comment]
@alexandrvl the error you see is symptom of an invalid dependency artifact in your local .m2:
Please see https://lists.apache.org/thread.html/90282be28f7e2a617e431964f814e15a8032f6eb5e13623d5cc99b4c@%3Cdev.beam.apache.org%3E

**Comment by alexandrvl** [comment]
@tweise Thank you! Can this pull request be closed?

**Pull request closed without merging**
