### PR TITLE
[BEAM-1589]  Added @onWindowExpiration annotation.

### PR DESCRIPTION
**Pull request by huygaa11**
Added @onWindowExpiration annotation for annotating a user defined method (similar to a method annotated with @onTimer), which allows user to do some work before garbage collection. For example, users can use this annotation to write a method that extracts a value saved in a state before garbage collection.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by huygaa11** [comment]
@kennknowles , I am writing some tests right now to attach to this PR. In the meantime, could you do an overall review and let me know if I am on the right track? Thanks.

**Comment by kennknowles** [comment]
This is great. It could certainly use some more tests in `DoFnSignaturesTest` and eventually `ParDoTest`.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java, line 603 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iXKNppHMuvM7OcR5x:-L3iXKNq3BUR2O5zK4d-:bfi6am4) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java#L603)):*
> ```Java
>    *
>    * <p>Annotation that may be added to a {@link ProcessElement}, {@link OnTimer}, or
>    * {@link OnWindowExpiration} method to indicate that the runner must ensure that the observable
> ```

Very nice noticing that it needs mention here.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java, line 384 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iXbloaqbNOG_zWiEy:-L3iXbloaqbNOG_zWiEz:b-agsy5t) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java#L384)):*
> ```Java
> 
>   /** Delegates method with extra parameters to the given method if available, or does nothing. */
>   private static Implementation delegateMethodWithExtraParametersOrNoop(
> ```

Also nice understanding that this is a new kind of method - it is optional like the lifecycle methods but accepts automated parameters.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java, line 519 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iY2Vk_4-EeWOhfAm3:-L3iY2Vk_4-EeWOhfAm4:bc3ka4e) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java#L519)):*
> ```Java
>    * "target method" of the wrapped {@link DoFn}.
>    */
>   static class DoFnMethodWithExtraParametersDelegation extends DoFnMethodDelegation {
> ```

Nice refactor here, too.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java, line 697 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iYPljK2NAnAQJrQ9O:-L3iYPljK2NAnAQJrQ9P:biww5m0) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java#L697)):*
> ```Java
>    */
>   private static final class ProcessElementDelegation extends
>       DoFnMethodWithExtraParametersDelegation {
> ```

It looks like we can almost delete `ProcessElementDelegation`. Incidentally, crashing on load as it happens below in the `static` block can really confuse tools that may actually surface `ClassNotFound` errors instead of the actionable error message. Instead we should make it lazy. Just a side comment.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnSignatures.java, line 107 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iYt9wavKJ6GelHhC_:-L3iYt9wavKJ6GelHhCa:bokr0g5) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnSignatures.java#L107)):*
> ```Java
>       ALLOWED_ON_WINDOW_EXPIRATION_PARAMETERS =
>       ImmutableList.of(
>           // TODO: Add support for OnWindowExpirationContextParameter.
> ```

Maybe we can avoid introducing such a thing if we work on the specific pieces of the context that are needed. I think an `OutputReceiver` or some such is the only thing you need. For a long time we have wanted to separate that and eliminate context parameters - because they are just collections of other parameters anyhow, and redundant with the way that DoFn supports a mixed bag of parameters.

---

*[sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java, line 62 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iZJAr0xw2SsPqYZTd:-L3iZJAr0xw2SsPqYZTe:bex1ol1) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java#L62)):*
> ```Java
> 
>     SimpleTimerDoFn fn = new SimpleTimerDoFn();
>     DoFnInvoker<String, String> invoker = DoFnInvokers.invokerFor(fn);
> ```

I think this test looks like it could go in `DoFnInvokersTest` since it basically tests that a proper invoker was created.

---

*[sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java, line 64 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iZO9XdLlCdYIuqi_r:-L3iZO9XdLlCdYIuqi_s:bgd0gth) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java#L64)):*
> ```Java
>     DoFnInvoker<String, String> invoker = DoFnInvokers.invokerFor(fn);
> 
>     invoker.invokeOnWindowExpiration(mockArgumentProvider);
> ```

You don't really need a mock, since it is a POJO. I think either way the default/stub/mock should already be set up in `DoFnInvokersTest`. Or maybe those methods are in ByteBuddyDoFnInvokerFactoryTest, which covers the same logic since `DoFnInvokers` right now just delegates to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4482#-:-L3iZd3FYhfkp9VukC8_:b-hzgnuz)*

**Comment by huygaa11** [comment]
Added `DoFnSignatures` tests. I will add ParDoTest after implementing it on direct runner 

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnSignatures.java, line 107 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iYt9wavKJ6GelHhC_:-L43RAYMWeYtfXFboJbs:b-jn5s6n) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/DoFnSignatures.java#L107)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

Maybe we can avoid introducing such a thing if we work on the specific pieces of the context that are needed. I think an `OutputReceiver` or some such is the only thing you need. For a long time we have wanted to separate that and eliminate context parameters - because they are just collections of other parameters anyhow, and redundant with the way that DoFn supports a mixed bag of parameters.
</blockquote></details>

Discussed offline.

---

*[sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java, line 62 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iZJAr0xw2SsPqYZTd:-L3p1cLAmu7f4weiAYLw:b-896fix) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java#L62)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

I think this test looks like it could go in `DoFnInvokersTest` since it basically tests that a proper invoker was created.
</blockquote></details>

Done.

---

*[sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java, line 64 at r1](https://reviewable.io:443/reviews/apache/beam/4482#-L3iZO9XdLlCdYIuqi_r:-L3p1lvsbJHpfGlHgSa8:bnfhmuy) ([raw file](https://github.com/apache/beam/blob/e0189797ea0c0f51bf1b4da92029c83273b4aee9/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/OnWindowExpirationInvokerTest.java#L64)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

You don't really need a mock, since it is a POJO. I think either way the default/stub/mock should already be set up in `DoFnInvokersTest`. Or maybe those methods are in ByteBuddyDoFnInvokerFactoryTest, which covers the same logic since `DoFnInvokers` right now just delegates to it.
</blockquote></details>

Moved it to the DoFnInvokersTest and used the default mock object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4482#-:-L43QhF7l9QavGGf2iwd:bvee08k)*

**Comment by kennknowles** [comment]
Looks like there's a checkstyle problem.

**Comment by huygaa11** [comment]
Fixed the checkstyle issue.

**Comment by huygaa11** [comment]
retest this please

**Comment by kennknowles** [comment]
run java gradle precommit

**Comment by kennknowles** [comment]
Looked like flakes in the Dataflow service.

**Comment by huygaa11** [comment]
retest this please

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
It failed to find Guava 20.0 when shading the sketching library. Not clear what that is about. Not related but I want to confirm build is OK.

**Comment by huygaa11** [comment]
run java precommit

**Comment by kennknowles** [comment]
Ah, sorry I waited long enough that this needs a rebase to resolve the conflicts.

**Comment by iemejia** [comment]
@huygaa11 any news on this one ?

**Comment by huygaa11** [comment]
I have been busy recently. I will pick it up in ~2 weeks.

**Comment by huygaa11** [comment]
@reuvenlax PTAL

**Comment by huygaa11** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
This PR looks good to me, sorry for the delay reviewing. I'll go ahead and merge it.

**Pull request merged**
