### PR TITLE
[BEAM-2016] Delete HdfsFileSource & Sink

### PR DESCRIPTION
**Pull request by dhalperi**
R: @jbonofre

### CODE REVIEW

**Comment by dhalperi** [comment]
I am generally anti README throughout the codebase. This should be well-documented on the Javadoc for `HadoopFileSystem`, and probably also on the Beam website.

**Comment by dhalperi** [comment]
The `README.md` files we have right now are typically left over from when these files were their own projects and not integrated with the old Dataflow 1.x SDKs.

**Comment by jbonofre** [comment]
Fair enough. And fully agree for the Beam website.

**Comment by dhalperi** [comment]
Thanks JB!

**Pull request merged**
