### PR TITLE
Don't cache pubsub subscription prematurely.

### PR DESCRIPTION
**Pull request by udim**

### CODE REVIEW

**Comment by udim** [comment]
R: @charlesccychen

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

R: @chamikaramj for merge.

**Comment by udim** [comment]
@chamikaramj friendly ping

**Comment by chamikaramj** [comment]
Sorry, missed this.

**Comment by chamikaramj** [comment]
Retest this please

Will merge after tests pass.

**Pull request merged**
