### PR TITLE
[Website] update upcoming-events calendar section

### LINKED ISSUE #22694: [Bug]: Home page. Stay Up To Date with Beam. Upcoming events out of frame at page size 366.40px x 693.6px
### What happened?

Steps to reproduce:
1. Open the website https://beam.apache.org/
2. Change the screen size to 366.40px x 693.6px
3. Look at Upcoming events in the section Stay Up To Date with Beam

Actual result: Upcoming events out of frame at page size 366.40px x 693.6px
https://dl.dropboxusercontent.com/s/2vgxn28343b59hj/sBNxyQl192.mp4
Expected result: Upcoming events doesn't out of frame

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

### PR DESCRIPTION
**Pull request by bullet03**
Resolves #22694
- on small mobile resolutions (max-width: 374px) make all 3 calendar blocks ( tweets, blogs, upcoming events) width no more than 260px, so they don't stretch the page or cling to the edges
- add horizontall scroll to upcoming events section on max-width: 374px
____________________________________________________________________________________________________________________
before:
calendar_before
after: 
calendar_after
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlyaBoiko** [comment]
Verified, works as expected. Reviewed and tested by QA

**Comment by bullet03** [comment]
@pcoet, could you, please, help with review of current PR?

**Comment by bullet03** [comment]
@aromanenko-dev, could you, please, help with review of current PR?

**Comment by aromanenko-dev** [comment]
@bullet03 I guess it should be unmarked as "draft".

**Comment by bullet03** [comment]
> @bullet03 I guess it should be unmarked as "draft".

Sorry, you're right. Changed to ready for review.

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by bullet03** [comment]
> LGTM

Thank you!

**Pull request merged**
