### PR TITLE
[BEAM-2555] add README page in dsl/sql

### PR DESCRIPTION
**Pull request by XuMingmin**
1. remove README.md to keep align with other BEAM modules;
2. update usages in BeamSqlExample;

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @xumingming @JingsongLi @takidau

**Comment by takidau** [comment]
LGTM. Merging.

**Comment by takidau** [comment]
Merged, thank you!

**Comment by XuMingmin** [comment]
Thank you @takidau !

**Pull request merged**
