### PR TITLE
[BEAM-79] Sync gearpump-runner with master

### PR DESCRIPTION
**Pull request by manuzhang**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`.
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by manuzhang** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
When I take a look at the build, it looks like we have lost the `ValidatesRunner` tests, which are helpful pretty much all the time on this feature branch. Probably something in a refactoring of the main poms or Jenkins.

**Comment by kennknowles** [comment]
Run Gearpump ValidatesRunner

**Comment by kennknowles** [comment]
Even though the tests aren't running quite right, I think we are already in that state so it shouldn't block this. I'll merge it and then we can move forward with getting the `ValidatesRunner` tests fixed.

**Pull request merged**
