### PR TITLE
[BEAM-2433] unify SQL/Sql words in class name

### PR DESCRIPTION
**Pull request by XuMingmin**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by XuMingmin** [comment]
R: @lukecwik  @xumingming

**Comment by XuMingmin** [comment]
retest this please

**Comment by lukecwik** [comment]
Only method that I could find that still used "SQL" instead of "Sql":
```
org.apache.beam.dsls.sql.schema.BeamTableUtils.beamSQLRow2CsvLine
```

I also noticed that "CSV" was used instead of "Csv" but this could be fixed at another time.

**Comment by lukecwik** [comment]
LGTM
Merging

**Pull request closed without merging**
