### PR TITLE
[Managed BigQuery] use file loads with Avro format for better performance

### PR DESCRIPTION
**Pull request by ahmedabu98**

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Failing test is not relevant

**Comment by ahmedabu98** [comment]
assign set of reviewers

**Comment by chamikaramj** [comment]
LGTM.

Can we add a unit test so that this doesn't regress ?

**Comment by ahmedabu98** [comment]
> Can we add a unit test so that this doesn't regress ?

Not sure what you mean by regress?

**Comment by chamikaramj** [comment]
I mean to make sure we do not accidentally change the default from Avro back to Json.

**Comment by ahmedabu98** [comment]
Is that necessary? We're just adjusting the write configuration here.

I'll add a comment to warn against changing this, would that be sufficient?

**Comment by kennknowles** [comment]
I think Cham's point is that someone else messing about in the code without knowing the context will not know what can or cannot be changed, and also might just make a mistake. So having a tiny test that makes sure they don't simply undo this change is the idea.

**Comment by ahmedabu98** [comment]
If we're serious about that risk, we'd be doing this type of test all over the place 😅

I'll add a test anyways to get this PR in

**Comment by chamikaramj** [comment]
Up to you.

Agree that we don't need such unit tests for all configs but might be useful to have some inexpensive unit tests to guard potentially expensive accidental regressions.

**Review by chamikaramj — APPROVED** [review]

**Comment by ahmedabu98** [comment]
Thanks, that's fair.
I added a short test that asserts the SchemaTransform uses Avro format. Will merge when tests go green

**Pull request merged**
