### PR TITLE
Add official govulncheck action to Go Tests workflow

### PR DESCRIPTION
**Pull request by jrmccluskey**
Adds the official govulncheck action to the Go test suite and adds a workflow dispatch trigger to the suite. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
R: @damccorm 

Three consecutive runs on my own branch pass but I had to increment to v1.0.1 to get the work-dir param. Is the allowlist scoped to specific versions, or is the action itself allowed?

**Comment by damccorm** [comment]
> R: @damccorm
> 
> Three consecutive runs on my own branch pass but I had to increment to v1.0.1 to get the work-dir param. Is the allowlist scoped to specific versions, or is the action itself allowed?

Depends on the ticket you opened. In this case you said `@v1` so it should be fine since IIRC it uses a prefix system.

Do we actually need v1.0.1 or does v1 work?

**Comment by jrmccluskey** [comment]
Unfortunately yes, since things like specifying the working directory to operate out of weren't added until 1.0.1 and govulncheck is pretty finicky about where it gets invoked.

**Comment by damccorm** [comment]
Oh, they do versioning weird... Usually `v1` is >= `v1.x.y`

**Review by damccorm — APPROVED** [review]
LGTM

**Pull request merged**
