### PR TITLE
[#28543][prism] Garbage collect side inputs.

### PR DESCRIPTION
**Pull request by lostluck**
Until now, side inputs were handled separately from most of the data handling, leading to
them remaining un-garbage-collected, leading to a memory leak for long running streaming pipelines. This PR resolves that by moving Side Input Data handling into the elementmanager, which allows the data to be GCd once the output watermark for a stage has moved beyond where a given window's side input could be referenced.

As a refresher: A transform T with a side input S, can only access data from S that is in the Same Window W as a given Element. This is what gives the "blocking" behavior of side inputs for consumers. On the other side, the side input can thus be cleaned up if there's no data that remains to be processed by T, that can be projected onto W.

Necessary precursor to add state and timers in #28543, which has the same garbage collection behavior WRT a stages watermark.

Bonus changes:
* Annotated some coder look up errors in the SDK's execution bundle translation, to clarify what was actually failing. The issue that needed this debugging was due to removing the calls that added the coders to the bundle's components.
* Removed some extra map nesting around side inputs.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
Run Go Prism Precommit

**Comment by lostluck** [comment]
It's looking like the standard PreCommit and Prism PreCommit (so, same runner) have been broken since I merged in Fusion.  Looking into it.

**Review by jrmccluskey — APPROVED** [review]
For being a decently sized delta, this was surprisingly easy to follow for the most part.

**Comment by lostluck** [comment]
Thanks! Holding off on merging this for a bit while I'm sorting out prism stability. Very likely not hurt or helped by this PR, but prudence.

**Comment by lostluck** [comment]
Scratch that. My client has extra println... so that "stability" bit was just the Examples failing. whoops.

**Pull request merged**
