### PR TITLE
[BEAM-2586] Accommodate custom delimiters in TextIO

### PR DESCRIPTION
**Pull request by cphbrt**
Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a JIRA issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Format the pull request title like [BEAM-1234] Fixes bug in ApproximateQuantiles, where you replace BEAM-1234 with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run mvn clean verify to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf). (Didn't file an ICLA, because I don't think this is a big enough contribution to warrant one. Let me know if I'm wrong.)

---

This pull request replaces the logic that separates input by newline delimiters with a default set of delimiters, a method for users to define custom delimiters, and logic that splits input by any set of custom delimiters.

Examples of use are included in a javadocs addition to TextIO.

Potential solution to [BEAM-2586](https://issues.apache.org/jira/browse/BEAM-2586).

### CODE REVIEW

**Comment by ChristophHebert** [comment]
Hi @jbonofre , can you please take a look? I see you've worked with TextIO a good bit on JIRA.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Can you please fix the conflict ?

**Comment by ChristophHebert** [comment]
Conflicts resolved.

**Comment by ChristophHebert** [comment]
Hi @jkff, can you please take a look?

**Comment by jkff** [comment]
Thanks! I'm concerned about a few things:
1) This introduces *a lot* of complexity into the hottest codepath in TextIO, finding the next separator. What previously was a loop comparing each `char` to `\n` or `\r`, now for each `char` loops over a set of separators and loops over each separator in the set. It seems likely to be a big performance regression - would you mind e.g. comparing how long it takes to sequentially read 1GB from a local file by manually using the `TextSource` class, say, in a unit test, before and after this change?
2) I'm also concerned about the complexity from the point of view of error-proneness. That codepath is already very hard to understand (I would hope that there is a way to make it simpler, but I've taken stabs at it before and failed), and I think this change pushes it well into nightmare territory.
3) The abstraction of having a set of separators and splitting by the longest one seems unnecessarily generic to me - I have a hard time imagining a text-based file format that requires such an abstraction to parse. Do you have use cases where you actually use a nontrivial set of separators, that is neither simply `{\r, \n, \r\n}`, nor a single marker string such as `--- next record ---` or something?

Let's discuss these and see if there's a reasonable API to ship with Beam here. E.g. I think, in addition to what TextIO currently does, it definitely makes sense to support reading whole files (no separator) and support reading multiline blocks of text separated by a marker line.

**Comment by ChristophHebert** [comment]
@jkff Thank you for your helpful feedback!

I agree that this PR probably over-generalizes and thus introduces more complexity and error-proneness than necessary, at least for a Beam API item with so much traffic.

This one generalization could be broken into three realistic tasks we'd like to do:

1. Append a single custom delimiter string to the default list of delimiters, `{\r, \n, \r\n}`.
2. Use a custom delimiter without using the default list of delimiters.
3. Have no delimiters, thereby reading a whole file as one.

Task 1 can be accomplished similarly to this current PR, except rather than replacing the original default delimiter logic with a double-nested for-loop, we would append a only a single loop immediately after the default delimiter logic that checks for the one provided custom delimiter if it exists. This single loop would look similar to the inner loop of my PR's logic. The custom delimiter would be passed through `withCustomDelimiter()` or such.

Task 2 can be achieved by adding a `withDefaultDelimiters()` option (similar to `withCompressionType()` or my `withDelimiters()`) that may be set to false. The original default delimiter logic will be wrapped in a simple conditional statement. If `withDefaultDelimiters()` is false, the default delimiters won't be applied. Otherwise, they will be applied exactly as in the original logic.

Task 3 can be achieved two ways:

1. Implement Task 2. Thus, to read a whole file, a user simply disables the default delimiters and the whole file gets read. Potentially, a convenience option like `wholeFile()` could select `withDefaultDelimiters(false)` for a user.
2. Create an alternative path through TextIO (or a different thing like "FileIO" or such) that ignores all searches for delimiters. This has the potential to be faster when reading the whole contents of a large file because it wouldn't have to call `findSeparatorBounds()` in TextSource.


How does this sound? Especially with Task 3, I'm not certain which way would be more Beamish. I appeal to you for that insight. It's possible that even my PR's logic would be reasonable if brought out into a separate Class, but that would duplicate a lot of functionality.

I'd be glad to dev these out if they sound reasonable. In the meantime, I may do some performance tests like you mentioned in your list item 1.

**Comment by jkff** [comment]
Thanks - however, I'm still confused by "Task 1". Can you elaborate on what the file format you have in mind looks like, that is delimited both by newlines and by some non-newline delimiter? It seems like you could accomplish that by using a stock TextIO and applying a ParDo that splits every String on that delimiter.

For Task 2, I think we can also narrow the scope if we know more about the file format. E.g. if a delimiter is a marker line like `--- next record ---`, then we again can reuse the high-performant TextIO code for splitting bytes into lines, and then match whole lines against the delimiter.

Task 3 should be implemented altogether differently, because in that case the files should also be marked non-splittable, to avoid wastefully producing byte ranges of the file while all but the one starting at 0 will be scanned in vain and produce empty results.

**Comment by cphbrt** [comment]
@jkff I've begun to see your perspective.

Task 1 can be done with ParDo (as mentioned in the JIRA ticket, that's what we do currently).
Task 3 should be implemented separately from TextIO.
Task 2 can be done with Task 3 + ParDo.

The cons of building any further delimiting into TextIO itself outweigh any potential performance benefits.

Is there already an effort to build an IO that reads whole files as one?

**Comment by jkff** [comment]
I don't think there is such an effort yet. I think I agree that it should be separate from TextIO because reading whole files could also mean reading binary files; and because the API for that requires some design (e.g. I'm not sure if we want to return a whole file as a String, as a byte array, or provide a user callback for parsing an InputStream into a stream of values of their desired type, like in MongoDbGridFSIO https://github.com/apache/beam/blob/master/sdks/java/io/mongodb/src/main/java/org/apache/beam/sdk/io/mongodb/MongoDbGridFSIO.java#L144). It's definitely outside the scope of this PR and if you would like to make this contribution, it would be very welcome but I would recommend to first discuss the proposed API on dev@beam.apache.org.

"Task 2 can be done with Task 3 + ParDo" - this I'm not sure, because of the above - we might be reading very large files whose content doesn't fit into memory. I think it could be reasonable to implement Task 2 as a feature of TextIO and that would be within the scope of this PR. "Reading multiline blocks of text delimited by a given line" seems like a reasonable extension of "reading lines of text" and compatible with other properties of TextIO. We could also extend TextIO.Write to emit output in this format too.

**Pull request closed without merging**
