### PR TITLE
fix playground backend container builds

### PR DESCRIPTION
**Pull request by volatilemolotov**
1) Fixes python backend container build issue. After update to debian bookworm openjdk-11-jre-headless package is no longer availabile in stable. Fix downloads the package from bullseye repo and uses apt to install. This was chosen instead of adding bullseye as oldstable to avoid package conflicts. There was an option to update to openjdk-17 but was not sure if playground code would be affected. 

2) Fixes java container build where for some reason maven uses offline  mode when doing `dependency:list`. Instead of removing offline (it was there for some reason) we just add `mvn dependency:go-offline` to preload the needed dependencies
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by volatilemolotov** [comment]
R: @damccorm please check the comments i left in the description to understand some of the decisions made here

**Comment by Abacn** [comment]
Is Playground PreCommit failure related to this change?

**Comment by volatilemolotov** [comment]
No, seems like a test failure, that part of code was not touched

**Review by damccorm — APPROVED** [review]
Thanks

**Comment by damccorm** [comment]
Agreed this is unrelated to precommit failure (looks like a go lint issue)

**Pull request merged**
