### PR TITLE
Composite triggers and unit tests for Go SDK

### LINKED ISSUE #21759: [Feature Request]: Composite triggers for Go SDK
### What would you like to happen?

Add composite triggers like AfterAll, AfterEach, AfterAny, OrFinally triggers to Go SDK.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by riteshghorse**
Closes #21759 

Adds composite triggers. Tested on flink runner.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by riteshghorse** [comment]
Run GoPortable PostCommit

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Review by lostluck — APPROVED** [review]
LGTM, but the tests were enabled for flink but the validates runner for flink wasn't run.

Hmmm we could probably put the code phrase for each runner right near their filter lists to help folks learn what the code phrases are.

**Comment by lostluck** [comment]
One test failed. I thought flink didn't support ProcessingTime triggers?

```
--- FAIL: TestTriggerAfterSynchronizedProcessingTime
```

```
2022/06/10 01:50:02  (): java.lang.RuntimeException: Error received from SDK harness for instruction 9: process bundle failed for instruction 9 using plan 47-24 : while executing Process for Plan[47-24]:
2: ParDo[passert.errFn] Out:[]
3: PCollection[n12] Out:[2]
4: ParDo[beam.dropKeyFn] Out:[3]
5: PCollection[n11] Out:[4]
6: Combine[passert.elmCountCombineFn] Keyed:false Out:5
1: DataSource[S[fn/read/n10:0@localhost:41663], local_output] Coder:W;fn/wire/n10:0<CoGBK;c7<int[varintz;c3];c4,double;c0>>!GWC Out:6
	caused by:
DoFn[UID:2, PID:Global/passert.Count(total collections)/passert.errFn, Name: github.com/apache/beam/sdks/v2/go/pkg/beam/testing/passert.errFn] failed:
passert.Count(total collections) = 4, want 2
```

**Comment by riteshghorse** [comment]
Flink doesn't support advancing processing time. That's the reason after processing time trigger is skipped. 
`AfterSynchronizedProcessingTime` trigger however, may give different output in different runs depending on whether the processing time is synchronized with arrival time or not.

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Comment by riteshghorse** [comment]
Run Go Flink ValidatesRunner

**Comment by lostluck** [comment]
I did a bit of manual handling to trigger flink, and verified the new tests exist. Merging!

https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink_PR/145/ which passed.

**Pull request merged**
