### PR TITLE
Add TrafficMaxLaneFlowIT

### PR DESCRIPTION
**Pull request by boyuanzz**
TrafficMaxLaneFlowIT runs with dataflow runner in PostCommit.

r: @pabloem 
cc: @aaltay

### CODE REVIEW

**Comment by boyuanzz** [comment]
Run Java PostCommit

**Comment by boyuanzz** [comment]
PostCommit: https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild_PR/103/

**Comment by pabloem** [comment]
LGTM. Thanks!

**Comment by boyuanzz** [comment]
Re: @pabloem 
Reverted build file changes and squashed all commits into one. This PR is ready to merge. Thanks~

**Pull request merged**
