### PR TITLE
BEAM-3314 Endpoint host port configuration reset issue

### PR DESCRIPTION
**Pull request by vvarma**
fix for https://issues.apache.org/jira/browse/BEAM-3314.

---

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Run Java Gradle PreCommit

**Comment by jbonofre** [comment]
It seems that `RedisIOTest` is failing. I'm taking a look.

**Comment by jbonofre** [comment]
Run Java Maven PreCommit

**Comment by jbonofre** [comment]
Run Java PreCommit

**Comment by jbonofre** [comment]
Run Java Gradle PreCommit

**Comment by jbonofre** [comment]
`RedisIOTest` systematically fails with:

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Protocol family unavailable
```
I wanted to include this in 2.3.0 but, in order to give me time to investigate, I will fix/merge this one for 2.4.0.

**Comment by vvarma** [comment]
Run Java Gradle PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by jhendr** [comment]
Ran into this problem myself, but didn't find this Github issue until after I discovered the underlying problem myself.

Adding the word RedisIO to the comment section to make it turn up better in issue searches.

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
I found the reason why this is not working, I am going to cherry pick this one and open a new PR with @vvarma's commit and a rebased fix. Thanks @vvarma and sorry for having taking so long to review/merge this one.

**Pull request closed without merging**
