### PR TITLE
Add streaming test for Write API sink

### PR DESCRIPTION
**Pull request by AlexZMLyu**
Add streaming test for BigQuery Write API  
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AlexZMLyu** [comment]
@chamikaramj Hi Cham, please kindly review the patch.

**Comment by yirutang** [comment]
R: @chamikaramj

**Comment by AlexZMLyu** [comment]
R: @pabloem

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
@AlexZMLyu please run `./gradlew :sdks:java:io:google-cloud-platform:spotlessApply` to format the code and fix spotless issue

**Comment by AlexZMLyu** [comment]
Talked to @pabloem offline. The TestStream class that I used here as the streaming source is not compatible with Dataflow runner. I will edit the code using the **GenerateSequence** and overriding the **expand** method to serve as the streaming source instead.

**Comment by robertwb** [comment]
TestStream should work fine on Runner v2, and is preferable.

**Comment by AlexZMLyu** [comment]
Robert, thanks for letting me know.
Do I need to change my code to utilize the Runner V2?

**Comment by chamikaramj** [comment]
This test is disabled for Runner v2 currently: https://github.com/apache/beam/blob/67e6726ffeb47d2ada0122369fa230833ce0f026/runners/google-cloud-dataflow-java/build.gradle#L642

Trying to re-enable here: https://github.com/apache/beam/pull/21814

(you can try it on this PR similarly)

**Comment by AlexZMLyu** [comment]
Run PostCommit_Java_DataflowV2

**Comment by AlexZMLyu** [comment]
There was no failed test in https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2_PR/112/testReport/
Why the Dataflow V2 Java Post Commit Tests failed?

**Comment by AlexZMLyu** [comment]
Do I need to wait approval of [PR #21814 ](https://github.com/apache/beam/pull/21814) to run Runner v2 here?

**Comment by AlexZMLyu** [comment]
Run PostCommit_Java_DataflowV2

**Comment by chamikaramj** [comment]
Seems like Storage Write API tests are still failing for Runner v2: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2_PR/111/testReport/junit/org.apache.beam.sdk.io.gcp.bigquery/BigQueryIOStorageWriteIT/testBigQueryStorageWrite30MProto/

So we can just get the Runner v1 version in (this PR).

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Run PostCommit_Java_DataflowV1

**Comment by chamikaramj** [comment]
Run PostCommit_Java_Dataflow

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Seems like the new tests failed the post-commit test suite: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1_PR/124/

**Comment by AlexZMLyu** [comment]
Then I still need to change the streaming source from TestStream to something else, right?

**Comment by chamikaramj** [comment]
Yeah, I think it's probably ok to use GenerateSequence (a bounded source) for a simple integration test that use the streaming Runner v1. Separately we should check why this still failed for Runner v2.

**Comment by AlexZMLyu** [comment]
Run PostCommit_Java_DataflowV1

**Comment by AlexZMLyu** [comment]
Run PostCommit_Java_DataflowV1

**Comment by chamikaramj** [comment]
Run Spotless PreCommit

**Comment by AlexZMLyu** [comment]
Spotless test passed.

**Comment by chamikaramj** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by chamikaramj** [comment]
Seems like there's still one failing test suite. Probably unrelated. Retrying.

**Comment by AlexZMLyu** [comment]
Looks like all test passed

**Pull request merged**
