### PR TITLE
Better cross langauge support for dataframe reads.

### PR DESCRIPTION
**Pull request by robertwb**
Adds a new Read/WriteViaPandas transform and better
support for object types that are actually strings.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @TheNeuralBit

**Comment by TheNeuralBit** [comment]
What happens for object columns that aren't actually strings though? I wonder if a better approach would be to make sure that we get `StringDType` columns in cross-language contexts.

Unfortunately I don't see a way to configure read_csv to get StringDType out. Maybe could add something akin to [`convert_dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.convert_dtypes.html) that will attempt to coerce all object columns to strings (and raise an execution time error if it's impossible).

**Comment by robertwb** [comment]
If the columns aren't actually strings then an exception will be raised when trying to encode them at strings. I wasn't able to figure out how to get StringDType out of csv either, and convert_dtypes requires looking at the entire PCollection to figure out the proxy object. I think this is pretty safe because objects should be strings immediately following a csv (or json, or most other common types) read. If it's not, exposing this in a cross-langauge way would be hard anyway. (I suppose one may encounter the bytes type, and nested types (though IIRC pandas doesn't do to well with that anyway).

**Comment by TheNeuralBit** [comment]
> and convert_dtypes requires looking at the entire PCollection to figure out the proxy object

Right, I know we can't do `convert_dtypes` exactly, I just meant we could add something similar to it, that assumes all object columns are coercible to strings, and raises error at execution time if they're not.

I think doing that conversion explicitly with the DataFrame API would be preferable to plumbing the typehint through the schema code. But maybe that uglies things up to have to do `read_csv().coerce_objects_to_strings()`?

**Comment by robertwb** [comment]
OK, I've made this local to the transform. I agree that this is cleaner, thanks.

**Review by TheNeuralBit — APPROVED** [review]
Nice, thanks!

**Comment by robertwb** [comment]
I was thinking this could be more useful for other cases where the dtype(s)
could not be inferred as well, though I can see how that would be sketchy
as well. Would you prefer we add a new coerce_objects_to_strings operation
to deferred dataframes? (Or I suppose I could do it manually using
DataFrame.astype iterating over the columns.) Let me see what that looks
like.

**Pull request merged**
