### PR TITLE
[BEAM-10465] Add checksum for Python source distribution and wheels

### PR DESCRIPTION
**Pull request by TobKed**
Add sha512sum for later verification.

test on my fork:
https://github.com/TobKed/beam/actions/runs/161961085

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | --- | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by TobKed** [comment]
R: @tvalentyn @aaltay @mwalenia

**Comment by aaltay** [comment]
Do we expect workflows to run when there is a change to workflows?

**Comment by TobKed** [comment]
I am not sure did I understand your question @aaltay .
Updated workflow will run after merging it to the master.
Since workflows are run only when they merged to master it is not possible to verify them before merging. I think a good practice is to put the link to the example run executed on the fork.

Here is test on my fork:
https://github.com/TobKed/beam/actions/runs/161961085

**Comment by aaltay** [comment]
> I am not sure did I understand your question @aaltay .
> Updated workflow will run after merging it to the master.
> Since workflows are run only when they merged to master it is not possible to verify them before merging. I think a good practice is to put the link to the example run executed on the fork.
> 
> Here is the test on my fork:
> https://github.com/TobKed/beam/actions/runs/161961085

OK. This kind of answers my question. I was asking because:
- we are able to run workflows on PRs
- And changing the workflow code should be tested by running the workflow code.

And based on the other PR, it seems like not everyone will be able to run the workflow on their repo. (e.g. they might be missing GCS parts.)

My specific question, is it possible to trigger workflow similar to PR workflows if changes touch the workflow files?

**Comment by aaltay** [comment]
I will merge this, I do not want to block the PR. Please respond to my question when you get a chance.

**Comment by TobKed** [comment]
@aaltay thanks for merging :)

Actually I was wrong with statement: "workflows are run only when they merged to master".
It is possible to run workflows not merged to master e.g. in PR which introduces new workflow and it is triggered on 'push' event type this new workflow will run.

> My specific question, is it possible to trigger workflow similar to PR workflows if changes touch the workflow files?

It is possible to include `'.github/workflows/**'` in `paths`: 
https://github.com/apache/beam/blob/master/.github/workflows/build_wheels.yml#L30
Then any change in this dir in PR will trigger `Build python wheels` workflow run.
Do you think I should create PR with this change?

**Comment by aaltay** [comment]
> @aaltay thanks for merging :)
> 
> Actually I was wrong with statement: "workflows are run only when they merged to master".
> It is possible to run workflows not merged to master e.g. in PR which introduces new workflow and it is triggered on 'push' event type this new workflow will run.
> 
> > My specific question, is it possible to trigger workflow similar to PR workflows if changes touch the workflow files?
> 
> It is possible to include `'.github/workflows/**'` in `paths`:
> https://github.com/apache/beam/blob/master/.github/workflows/build_wheels.yml#L30
> Then any change in this dir in PR will trigger `Build python wheels` workflow run.
> Do you think I should create PR with this change?

Yes, I think it would be good to create that PR and test workflows when the workflow files change.

**Comment by TobKed** [comment]
Sorry for late response. I created PR with basic documentation for GItHub Actions CI https://github.com/apache/beam/pull/12405

**Pull request merged**
