### PR TITLE
[BEAM-5703]Migrate py integration test to using customized worker jar

### PR DESCRIPTION
**Pull request by HuangLED**
Py code change is in PR#6680. 

Passed on done following tests: 

**[Test1 passed by succeeding ]** ./gradlew validatesRunnerStreamingTests passed on local machine. 

**[Test2 passed by succeeding]** the default streaming+dataflowRunner case, only the shell script. 

./scripts/run_postcommit.sh ValidatesRunner,'!sickbay-streaming' streaming TestDataflowRunner $GCS_LOCATION $PROJECT \
../../runners/google-cloud-dataflow-java/worker/build/libs/beam-runners-google-cloud-dataflow-java-fn-api-worker-2.9.0-SNAPSHOT.jar

**[Test 3. passed by succeeding]** TestDirectRunner. Not affected. 

./scripts/run_postcommit.sh IT streaming TestDirectRunner $GCS_LOCATION  $PROJECT

**[Test 4. Passed by validation failure]** Specified ‘streaming’ and TestDataFlow, but no jar file provided.
 ./scripts/run_postcommit.sh ValidatesRunner,'!sickbay-streaming' streaming TestDataflowRunner $GCS_LOCATION $PROJECT

**[Test 5. Passed by timeOut failure]** Pass a corrupted artifact to worker. Test time out. 
./scripts/run_postcommit.sh ValidatesRunner,'!sickbay-streaming' streaming TestDataflowRunner gs://test-${USER} $PROJECT ./FakeJar.txt

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by HuangLED** [comment]
Run Python PostCommit

**Comment by HuangLED** [comment]
R: @charlesccychen, @markflyhigh   (please recommend others if there is someone else better reviewing this, Thanks! )
CC: @herohde

**Comment by HuangLED** [comment]
Run Python Dataflow ValidatesRunner

**Comment by charlesccychen** [comment]
Thanks! This LGTM.

**Comment by HuangLED** [comment]
Thanks for the helps Charles and Mark!

**Pull request merged**
