### PR TITLE
[BEAM-12164]: Fixes SpannerChangeStreamIT

### PR DESCRIPTION
**Pull request by thiagotnunes**
The GSON object was being initialized in a static context. When the DoFn that used it was called in another JVM, which did not initialized this object, we were getting a NPE exception.

Here, we move the initialization of the GSON object inside the DoFn itself (through a setup method).

### CODE REVIEW

**Comment by thiagotnunes** [comment]
R: @pabloem

**Comment by y1chi** [comment]
Run PostCommit_Java_DataflowV2

**Comment by y1chi** [comment]
Could you exclude the failing test classes in googleCloudPlatformLegacyWorkerIntegrationTest

**Comment by y1chi** [comment]
Run PostCommit_Java_DataflowV2

**Comment by y1chi** [comment]
LGTM.

**Pull request merged**
