### PR TITLE
(BQ Java) Explicitly set coder for multi-partition batch load writes 

### LINKED ISSUE #23561: 2.42.0 Release Branch: Flink Examples integration test failing
### What happened?

Release Validation branch https://github.com/apache/beam/pull/23200 has failures for the Flink Example post commits:

https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Flink_PR/8/

from the beam branch: `./gradlew :runners:flink:1.13:examplesIntegrationTest` replicates the same failure.

Errors are all the following InvalidProgramException

```
08:52:14 org.apache.beam.examples.snippets.transforms.io.gcp.bigquery.BigQuerySamplesIT > testTableIO FAILED
08:52:14     org.apache.beam.sdk.Pipeline$PipelineExecutionException at BigQuerySamplesIT.java:108
08:52:14         Caused by: org.apache.flink.api.common.InvalidProgramException at BigQuerySamplesIT.java:108
```

Other flink validation is passing so it appears related to gradle configuration or similar. This needs to be determined and or resolved before RC2 is built.

### Issue Priority

Priority: 1

### Issue Component

Component: runner-flink

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #23561 (once cherry picked into release-2.42.0)

Single partition writes set a coder `TableDestinationCoderV3` [here](https://github.com/ahmedabu98/beam/blob/ef85e6b948c4fd02b85f93e493e3dc50be2299c9/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java#L818) while multi partition writes doesn't set any coder explicitly, so it defaults to a serializable `TableDestination` coder. There is an attempt later to flatten the single and multi write PCollections [here](https://github.com/ahmedabu98/beam/blob/67d6e8aa1a7d8107e6fd84824364fc215269cc02/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BatchLoads.java#L504-L505), but because the coder types are different, the following error is thrown: 

`
org.apache.flink.api.common.InvalidProgramException: Cannot union inputs of different types. Input1=CoderTypeInformation{coder=WindowedValue$FullWindowedValueCoder(TableDestinationCoderV2,GlobalWindow$Coder)}, input2=CoderTypeInformation{coder=WindowedValue$FullWindowedValueCoder(SerializableCoder(org.apache.beam.sdk.io.gcp.bigquery.TableDestination),GlobalWindow$Coder)}
`

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run Java Examples_Flink

**Comment by ahmedabu98** [comment]
Run Java Examples_Flink

**Comment by ahmedabu98** [comment]
Run Java Examples_Flink

**Comment by ahmedabu98** [comment]
R: @lostluck 
`BigQuerySamplesIT.testTableIO` example is failing because of a different reason (#23541)

**Review by lostluck — APPROVED** [review]
LGTM Thanks!

Would you kindly send me a cherry pick of this to merge into the release branch?

**Comment by lostluck** [comment]
(merging after the precommit passes. The examples are in much better shape with this fix, and I acknowledge the new error is new).

**Comment by lostluck** [comment]
Actually, looks like the precommit is done, but github didn't pick up on it. Merging.

**Pull request merged**
