### PR TITLE
Fix clean up stale container workflow

### PR DESCRIPTION
**Pull request by Abacn**
https://github.com/apache/beam/actions/workflows/beam_CleanUpPrebuiltSDKImages.yml?page=3 has been failing since Nov 16th. The reason is that the multiarch consideration has a call `docker manifest inspect` rejected by some repositories.

While we can extend the permission, it is not necessary to do so as of quick fix.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Example run: https://github.com/apache/beam/actions/runs/7671957082/job/20911428103

**Comment by Abacn** [comment]
R: @damccorm

**Review by damccorm — APPROVED** [review]
Nice, thank you!

**Comment by Abacn** [comment]
ah this still does not fix the multiarch part - the issue is similar to https://github.com/docker/cli/issues/4345. 
docker manifest inspect requires push permission

**Comment by damccorm** [comment]
It looks to me like your job made significantly more progress (ran for 21 minutes instead of <10). The failure now seems to be:

```
Command gcloud container images list-tags gcr.io/***/beam-sdk/beam_go_sdk --sort-by=TIMESTAMP --filter=NOT tags:latest AND timestamp.datetime < 2023-12-15T18:28:40+00:00 --format=get(digest)
Get "https://gcr.io/v2/***/beam-sdk/beam_go_sdk/manifests/sha256:0031a0ab151ce189ca8a1c16646a18aafd24936febe7ab75e009518bf4d55514": unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by Abacn** [comment]
The script is now working but very slow: https://github.com/apache/beam/actions/runs/7673666730/job/20980246935 because https://github.com/apache/beam/pull/30132/files#diff-0253124400f88f401b2239e188b85c2348566472f9a11c3ff8d67f12fa0fbbfaR99-R104 is of O(n) to decide to delete the manifest

**Review by damccorm — APPROVED** [review]
I'd vote we merge and see if we need to optimize from there. Theoretically, once we catch up on our big backlog the number of containers to deal with should be much much smaller, so it might just be a matter of running this extra times to catch up

**Comment by Abacn** [comment]
> I'd vote we merge and see if we need to optimize from there. Theoretically, once we catch up on our big backlog the number of containers to deal with should be much much smaller, so it might just be a matter of running this extra times to catch up

agreed. The script is already very long and likely won't be able to invest more on it. The issue is essentially https://b.corp.google.com/issues/160346081 however, gcr is deprecated so won't expect this feature request get resolved.

**Pull request merged**
