### PR TITLE
[BEAM-8306] improve estimation datasize elasticsearch io

### PR DESCRIPTION
**Pull request by derekunimarket**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by iemejia** [comment]
R: @echauchot @timrobertson100 
Can some of you PTAL at this one, looks like an interesting improvement.

**Comment by timrobertson100** [comment]
I don't have time to do a thorough review until next week but I looked over this and my general impression is it looks like a good addition. 

(Commit message is not formatted correctly)

**Comment by derekunimarket** [comment]
Do you guys have time to review it now? Thanks a lot.

**Comment by timrobertson100** [comment]
Urff - sorry we forgot this one @derekunimarket 

I am heading into a hectic week of funding board meetings/conference from tomorrow, so can't look until the week after next. I've set a reminder to do so, but hope someone can beforehand.

**Comment by wscheep** [comment]
Sorry, I don't think I have enough experience to review this. Also, I changed jobs recently and am not working directly with BEAM and ES any more.

**Comment by timrobertson100** [comment]
I'll review this tomorrow. 
@derekunimarket can you please reformat that first commit message to follow the project style? It's missing `[ ]` around the Jira number.

**Comment by derekunimarket** [comment]
> I'll review this tomorrow.
> @derekunimarket can you please reformat that first commit message to follow the project style? It's missing `[ ]` around the Jira number.

Done. Thanks.

**Comment by timrobertson100** [comment]
Run Java PreCommit

**Comment by timrobertson100** [comment]
This LGTM - waiting to see green to merge

I am not entirely sure this will work when aliasing indexes. I don't believe you can get an estimate of size like this but as far as I can see the same is true in the current implementation too. I think we would need to determine the indices that form part of the alias and then accumulate the sizes. Surely out of the scope of this PR though.

**Comment by timrobertson100** [comment]
@derekunimarket can you please rebase against the master to avoid the two commits as `BEAM-7916` is already merged. I'll then merge this and open an issue to handle alias indexes in ES.

**Comment by derekunimarket** [comment]
> BEAM-7916

@timrobertson100 I checked that master branch, confirms that "BEAM-7916" is not in master yet. That's reason we still still see "BEAM-7916" in the PR. The fix of BEAM-7916 is only merged into apache:release-2.14.0 currently.

**Comment by timrobertson100** [comment]
Sorry, I could be missing something as it's very late here but isn't it merged on master with [this PR](https://github.com/apache/beam/pull/9314) that was cherry-picked after accidentally going onto the 2.14.0 release?

**Comment by derekunimarket** [comment]
@timrobertson100 
Sorry, it's my bad. The problem is that I created my feature branch based our own patched 2.14.0.
I can create a feature branch base on your master branch and cherry pick this fix into the feature branch.
And I make a new PR and then it's all clear. Is that Ok?

**Comment by derekunimarket** [comment]
@timrobertson100
new PR https://github.com/apache/beam/pull/9940 to replace this. Thanks.

**Comment by timrobertson100** [comment]
Closing this unmerged and moving to #9940

**Pull request closed without merging**
