### PR TITLE
[BEAM-3482] fix serialization error in BigQueryIO's DynamicDestinations

### PR DESCRIPTION
**Pull request by shashank64**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by jkff** [comment]
Hmm this object is not supposed to be serialized. This PR will make it simply deserialize as null, and I'm highly doubtful that the code will work correctly after that. Could you post a more complete deserialization error by running with `-Dsun.io.serialization.extendedDebugInfo=true` ? I wonder if Apex runner is serializing something unnecessarily.

**Comment by shashank64** [comment]
Hi Eugene,

I'm busy with something else and will not be able to test anytime soon. The
code I modified, I only copied from FileBasedSink.DynamicDestinations - it
appeared to be the same code (except not updated with transient modifier)
for BQIO.DynamicDestinations. It would seem someone faced similar issue
with FileBasedSink and made the changes there, but I'm not familiar enough
with beam to comment on whether it should be Serialized or not.

Regards,
Shashank

**Comment by jkff** [comment]
Hmm, okay, simpler question: did your pipeline start working correctly after this change? :)

**Comment by shashank64** [comment]
Yes it did.

**Comment by reuvenlax** [comment]
It would help if you could provide a code snippet that doesn't work without this.

**Comment by jkff** [comment]
I'm going to merge this because it seems to help for Apex runner and is harmless otherwise.

**Pull request merged**
