### PR TITLE
[BEAM-14185]: remove the metadata table after the pipeline finishes for Spanner Change Streams Connector

### PR DESCRIPTION
**Pull request by hengfengli**
This change removes the metadata table after the pipeline finishes. But note that if the pipeline is cancelled, the metadata table would not be deleted.

### CODE REVIEW

**Review by thiagotnunes — APPROVED** [review]

**Comment by thiagotnunes** [comment]
retest this please

**Comment by thiagotnunes** [comment]
retest this please

**Comment by thiagotnunes** [comment]
Test failures are unrelated (BigQuery test)

**Comment by thiagotnunes** [comment]
Run Java PostCommit

**Comment by thiagotnunes** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by thiagotnunes** [comment]
Disabled flaky SpannerIO.readChangeStream tests. Created a ticket to re-enable them (https://issues.apache.org/jira/browse/BEAM-14195)

**Comment by thiagotnunes** [comment]
R: @pabloem

**Comment by pabloem** [comment]
LGTM

**Pull request merged**
