### PR TITLE
[SparkReceiverIO] Add startPollTimeoutSec parameter. Fix splitting of restriction

### LINKED ISSUE #26621: [Failing Test]: beam_PerformanceTests_SparkReceiver_IO failing
### What happened?

Since Apr 25, 2023.

Error massage:

```
23:05:17 org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOIT > testSparkReceiverIOReadsInStreamingWithOffset FAILED
23:05:17     java.lang.AssertionError: expected:<5000000> but was:<4700000>
23:05:17         at org.junit.Assert.fail(Assert.java:89)
23:05:17         at org.junit.Assert.failNotEquals(Assert.java:835)
23:05:17         at org.junit.Assert.assertEquals(Assert.java:647)
23:05:17         at org.junit.Assert.assertEquals(Assert.java:633)
23:05:17         at org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOIT.testSparkReceiverIOReadsInStreamingWithOffset(SparkReceiverIOI
```

the actual number of element is fluctuating and always smaller than the expected. May indicates a data loss bug

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Amar3tto**
- Resolves #26621 
- Added `startPollTimeoutSec` parameter to `SparkReceiverIO` and `CdapIO` (previously it was constant)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Java SparkReceiverIO Performance Test

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
SparkReceiverIO performance test took 9.53 min with this fix, so there is no need to increase timeout.

**Comment by Amar3tto** [comment]
> @Amar3tto Thanks!
> 
> Could you explain a bit why this change accelerate the test execution?
> 
> Also, how did you calculate that now it takes only 9.53 min for this test? I see that [this build](https://ci-beam.apache.org/job/beam_PerformanceTests_SparkReceiver_IO/467/), that was run against this PR, took 36 mins. Do I misunderstand something?

This change prevents splitting restriction too often (now it won't split until there are no more records left in the queue), which was the reason for the Receivers to start and stop too many times - starting and stopping takes a while.
I ran the `SparkReceiverIO Performance test` 2 times on this PR. I got the results from the Grafana dashboard (9.53 and 18.3 min). Previous successful runs (before fix) have been around 27 min, too close to the 30 min timeout.

**Review by aromanenko-dev — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
