### PR TITLE
[BEAM-2105] Move TestCredential out of test suite artifact

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

The test jar is for packaging the test suite of `gcp-core`, but `TestCredential` is
not part of the test suite. It is simply a class that `gcp-core` offers to other
libraries and belongs in the main artifact. Otherwise any users will have to
depend on the test suite in order to test their code, which doesn't make sense.

@lukecwik @dhalperi @davorbonaci you probably each might have some opinions on this.

The test suite for XYZ is contained in the `test-jar` artifact aka `src/test` etc etc. Putting other things in here and asking users to take a dependency on the whole test suite doesn't make sense.

Maven's scopes prevent this from causing dependency hell, by simply possibly not pulling in needed transitive dependencies.

"user's tests"
    --(test scope) --> "TestCredential in test suite artifact"
    --(test scope)--> "any deps not also main deps"

If the last line is nonempty, the user will be broken. It only works by luck (yes, it usually will) because all of these deps will also be present as `compile` dependencies. So we've just forced the user to add cruft to their pom and pull in bundles of stuff they don't need.

### CODE REVIEW

**Comment by lukecwik** [comment]
I specifically placed this into test/ because I don't expect users to write tests that use TestCredential.

**Comment by kennknowles** [comment]
Then it should be package private. But it actually is used so that won't work.

**Comment by kennknowles** [comment]
I can make it private and dupe it, that's reasonable.

**Comment by kennknowles** [comment]
It turns out the default behavior already makes tests that would use this work. It'll be some time wiping them out. Not critical enough to do right now.

**Pull request closed without merging**
