### PR TITLE
[BEAM-5240] Add Jira data to Beam post-commits dashboard

### PR DESCRIPTION
**Pull request by Ardagan**
Add prototype script to fetch data from jira to postgresql for Beam Dashboard.
http://104.154.241.245/d/D81lW0pmk/post-commit-tests?orgId=1

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by Ardagan** [comment]
run go precommits

**Comment by Ardagan** [comment]
run go precommit

**Comment by Ardagan** [comment]
run python precommit

**Comment by Ardagan** [comment]
run go precommit

**Comment by Ardagan** [comment]
r: @swegner

**Comment by Ardagan** [comment]
run python precommit

**Comment by Ardagan** [comment]
Running precommits to execute :rat target. Need to implement BEAM-5499 to avoid it.

**Comment by swegner** [comment]
Taking a look now. I'm not very familiar with the BeamMetrics implementation yet, so my plan for reviewing it will be to run through the README.md steps.

**Comment by Ardagan** [comment]
That's a valid approach. I believe those steps were followed only twice: once me writing them, once by Huygaa while working on more metrics. Feel free to add comments.
This branch allows committers to patch PR, feel free to do that as well.

**Comment by swegner** [comment]
I wasn't able to follow this end-to-end, but I don't see anything problematic in this PR. Let's merge it and I'll follow-up on figuring out the issues I'm hitting.

LGTM

**Pull request merged**
