### PR TITLE
[BEAM-14148] Revert "[BEAM-14038] Auto-startup for Python expansion service."

### PR DESCRIPTION
**Pull request by lukecwik**
Reverts apache/beam#17035

The test is extremely flaky causing many Java PreCommits to fail due to it.

### CODE REVIEW

**Comment by robertwb** [comment]
Could we disable the test rather than rolling back the feature while I try to reproduce this?

**Comment by lukecwik** [comment]
R: @robertwb @chamikaramj

**Comment by lukecwik** [comment]
Run CommunityMetrics PreCommit

**Comment by aaltay** [comment]
LGTM. It is a clean rollback.

**Comment by lukecwik** [comment]
Run CommunityMetrics PreCommit

**Comment by chamikaramj** [comment]
Also noticed that this test fails for Mac.

**Comment by lukecwik** [comment]
Java precommit passed

**Comment by robertwb** [comment]
I couldn't get it to fail on my mac, despite repeated tries. Just once on Jenkins. Anyway, rolling back is fine to get the presubmits less flaky.

**Pull request merged**
