### PR TITLE
[BEAM-3412] Upgrade Cloud Bigtable to 1.0.0

### PR DESCRIPTION
**Pull request by sduskis**
The 1.0.0 Cloud Bigtable client upgrade included a non-backwards compatible change in protobuf generation.  Specifically, addAllXXXX() methods no longer work correctly.  `BigtableServiceImpl` used `addAllMutations()`, which caused run-time breakages.  To get around that, add each Mutation independently to the protobuf object.
This PR also adds unit tests for BigtableServiceImpl so that read/write interactions do not cause runtime problems.

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
Please update the bigtable version in `build.gradle`

Also, does this change the version of Netty, tcnative, protobuf, or gRPC that is required? If so, then we can't take this change in without those pieces being shaded away.

**Comment by sduskis** [comment]
I updated the `gradle.build` version.  This should not affect the maven dependencies, since the pom.xml explicitly includes specific versions of grpc, netty and protobuf.  Gradle looks like it does the same.

Is there a timeline for upgrading grpc to something newer?  1.2.0 was released march 2017.

**Comment by lukecwik** [comment]
No timeline, just this feature request: https://issues.apache.org/jira/browse/BEAM-3098

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by sduskis** [comment]
Unfortunately, 1.0.0 won't work.  We'll have to keep the dependency on 1.0.0-pre3 for now.  We'll work on making our 1.1.0 release compatible with Beam.  I should also raise a bug with the protobuf team.

FWIW, we are actively working on https://issues.apache.org/jira/browse/BEAM-2955 / "Create a Cloud Bigtable HBase connector".  The new HBase connector will be able to use the shaded client to skirt around these issues.

**Comment by sduskis** [comment]
I had a (hopefully) clever idea to have different versions of the proto and bigtable-client jars.  I kept the client at 1.0.0 and reverted the proto jar to 1.0.0-pre3.  That should hopefully fix the problem.

**Comment by lukecwik** [comment]
Run Java Gradle PreCommit

**Comment by lukecwik** [comment]
FYI: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableServiceImpl.java:[124,29] non-static variable options cannot be referenced from a static context

**Comment by sduskis** [comment]
I merged incorrectly.   I fixed the issue.

**Comment by sduskis** [comment]
The gradle failure looks unrelated to this PR: `org.apache.beam.sdk.io.hadoop.inputformat.HIFIOWithElasticTest.classMethod`

**Pull request merged**
