### PR TITLE
22805: Upgrade Jackson version from 2.13.0 to 2.13.3

### PR DESCRIPTION
**Pull request by perkss**
Fix issues #22805

Upgrade Jackson version from vulnerable 2.13.0 to 2.13.3. As per [snyk](https://security.snyk.io/package/maven/com.fasterxml.jackson.core:jackson-databind/2.13.0)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by perkss** [comment]
@pabloem can you please check on this review?

**Comment by damccorm** [comment]
retest this please

**Comment by damccorm** [comment]
@perkss looks like this is causing pulling licenses to fail with:

```
09:12:04 > Task :sdks:java:container:pullLicenses
09:12:04 ERROR:root:['jackson-bom-2.13.3']
09:12:04 ERROR:root:**************************************** Licenses were not able to be pulled automatically for some dependencies. Please search source code of the dependencies on the internet and add "license" and "notice" (if available) field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each missing license. Dependency List: [jackson-bom-2.13.3]
09:12:04 INFO:root:pull_licenses_java.py failed. It took 7.957456 seconds with 16 threads.
09:12:04 Traceback (most recent call last):
09:12:04   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/pull_licenses_java.py", line 326, in <module>
09:12:04     raise RuntimeError('{n} error(s) occurred.'.format(n=len(error_msg)),
09:12:04 RuntimeError: ('2 error(s) occurred.', ['**************************************** Licenses were not able to be pulled automatically for some dependencies. Please search source code of the dependencies on the internet and add "license" and "notice" (if available) field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each missing license. Dependency List: [jackson-bom-2.13.3]', '**************************************** License type of some dependencies were not identified. The license type is used to decide whether the source code of the dependency should be pulled or not. Please add "type" field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each dependency. Dependency List: [jackson-bom-2.13.3]'])
```

Could you take a look? Looks like we should just need to add a type field here - https://github.com/apache/beam/blob/e9089dd99630d939f0c38fbacbe97a283e429fc2/sdks/java/container/license_scripts/dep_urls_java.yaml#L56

**Comment by perkss** [comment]
> @perkss looks like this is causing pulling licenses to fail with:
> 
> ```
> 09:12:04 > Task :sdks:java:container:pullLicenses
> 09:12:04 ERROR:root:['jackson-bom-2.13.3']
> 09:12:04 ERROR:root:**************************************** Licenses were not able to be pulled automatically for some dependencies. Please search source code of the dependencies on the internet and add "license" and "notice" (if available) field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each missing license. Dependency List: [jackson-bom-2.13.3]
> 09:12:04 INFO:root:pull_licenses_java.py failed. It took 7.957456 seconds with 16 threads.
> 09:12:04 Traceback (most recent call last):
> 09:12:04   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/pull_licenses_java.py", line 326, in <module>
> 09:12:04     raise RuntimeError('{n} error(s) occurred.'.format(n=len(error_msg)),
> 09:12:04 RuntimeError: ('2 error(s) occurred.', ['**************************************** Licenses were not able to be pulled automatically for some dependencies. Please search source code of the dependencies on the internet and add "license" and "notice" (if available) field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each missing license. Dependency List: [jackson-bom-2.13.3]', '**************************************** License type of some dependencies were not identified. The license type is used to decide whether the source code of the dependency should be pulled or not. Please add "type" field to /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_PVR_Flink_Docker_Commit/src/sdks/java/container/license_scripts/dep_urls_java.yaml for each dependency. Dependency List: [jackson-bom-2.13.3]'])
> ```
> 
> Could you take a look? Looks like we should just need to add a type field here -
> 
> https://github.com/apache/beam/blob/e9089dd99630d939f0c38fbacbe97a283e429fc2/sdks/java/container/license_scripts/dep_urls_java.yaml#L56

Thanks yes should have spotted this updated now

**Comment by damccorm** [comment]
Run Typescript PreCommit

**Comment by damccorm** [comment]
Run Python PreCommit

**Comment by damccorm** [comment]
Run Python PreCommit

**Comment by damccorm** [comment]
Run Python PreCommit

**Review by damccorm — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
