### PR TITLE
Add Go stateful DoFns to CHANGES.md and fix linting violations

### PR DESCRIPTION
**Pull request by damccorm**
This adds state to CHANGES.md and fixes a few linting violations.

Part of #22736

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
Run Go Postcommit

**Comment by damccorm** [comment]
R: @riteshghorse

**Review by riteshghorse — APPROVED** [review]
Oh, I missed those naming lints earlier. LGTM, thanks!

**Comment by damccorm** [comment]
Run Go PostCommit

**Comment by damccorm** [comment]
Run Go PostCommit

**Comment by damccorm** [comment]
Run Go Postcommit

**Comment by damccorm** [comment]
Run Go Postcommit

**Comment by damccorm** [comment]
My last postcommit failed b/c of Jenkins issues and now triggering is broken, so I manually started a run for this PR - https://ci-beam.apache.org/job/beam_PostCommit_Go_PR/531/console

**Comment by damccorm** [comment]
Run Go PostCommit

**Comment by damccorm** [comment]
Even though its not showing up in the status checks, https://ci-beam.apache.org/job/beam_PostCommit_Go_PR/532/console succeeded so I'm going to merge

**Pull request merged**
