### PR TITLE
[BEAM-3934] Use try with resources to close the reader on JavaReadViaImpulse

### PR DESCRIPTION
**Pull request by iemejia**
R: @lukecwik

### CODE REVIEW

**Comment by iemejia** [comment]
Run Python_PVR_Flink PreCommit

**Comment by lukecwik** [comment]
Run Python_PVR_Flink PreCommit

**Comment by iemejia** [comment]
It seems the class of the container used by "Run Python_PVR_Flink PreCommit" is not getting updated and this is breaking the tests. Any hint on why this is happening @robertwb ?

**Comment by robertwb** [comment]
I have no idea. It should be taking these on as a dependency. Maybe it's pulling an old cache from somewhere?

**Comment by iemejia** [comment]
Mmm I am worried to merge and then breaking all tests after, anyone who may know/fix this ?

**Comment by iemejia** [comment]
@angoenka maybe?

**Comment by angoenka** [comment]
I think the failure is caused by missmatch in class version of Flink Job Server and Extension service. 
Checking how we build the extension service

**Comment by angoenka** [comment]
seems like we are not rebuilding the java container which is required now as we run java transforms while in python tests. 
Jira: https://issues.apache.org/jira/browse/BEAM-7422

**Comment by angoenka** [comment]
However, on a side note. This highlights that the containers are shared across tests in a machine.
Their is a race condition when multiple tests runs on on machine building container and can be a cause of flakiness.

**Comment by iemejia** [comment]
Run Python_PVR_Flink PreCommit

**Comment by iemejia** [comment]
Thanks a lot @angoenka for creating the related issue and for the quick fix.
What could be done to address the possible flakiness issue?

**Pull request merged**
