### PR TITLE
fixes [21715] - fix ring range read for CassandraIO read()

### PR DESCRIPTION
**Pull request by vmarquez**
fixes https://github.com/apache/beam/issues/21715 (missing data in CassandraIO)
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: "addresses #123), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment "fixes #<ISSUE NUMBER>" instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
looks like the test is failing: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/23003/testReport/junit/org.apache.beam.sdk.io.cassandra/CassandraIOTest/testWrapAroundRingRanges/

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by brucearctor** [comment]
Run Java PreCommit

**Comment by vmarquez** [comment]
@brucearctor thanks, looks like the unrelated, flaky test now passed.  What are the next steps to getting this merged?

**Comment by brucearctor** [comment]
I haven't worked with this component [ cassandraIO ] -- so hoping either for more context, or for someone that's worked closer with it to step in.  

Is there an associated issue [jira/github] that this relates to/addresses.  That would be a start to provide context on what this is/why - which is also useful more generally for anyone looking through the code/changes/history.  

Ex, from the PR template: `Mention the appropriate issue in your description (for example: "addresses https://github.com/apache/beam/pull/123), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment "fixes #" instead.`

**Comment by vmarquez** [comment]
@brucearctor thanks.  I had "fixing" instead of "fixes" so I guess it didn't auto pick up the issue it addresses, but at the top you should see the issue it's for: https://github.com/apache/beam/issues/21715

**Comment by brucearctor** [comment]
@KriKroff you wrote --> https://github.com/KriKroff/beam-cassandraio-bug

Can you take a look and verify addresses this issue?  

In principle LGTM, but hoping for a set of eyes more familiar with the component/issue.

**Comment by vmarquez** [comment]
Thanks for taking a look, really appreciate it @brucearctor

**Comment by pabloem** [comment]
so sorry. I can't look at this.

**Comment by pabloem** [comment]
r: @Abacn

**Review by Abacn — APPROVED** [review]
LGTM. The added unit test passed, and verified it fails on current master with `java.lang.AssertionError: counting/Flatten.PCollections.out: expected:<100> but was:<99>`, which means this change fixed the problem

**Comment by vmarquez** [comment]
@Abacn Thank you so much for the review! :)

**Pull request merged**
