### PR TITLE
Skip batching pipeline for unbatchable mutations.

### PR DESCRIPTION
**Pull request by nielm**
Ranged Deletes and large mutations (by bytes or cells) are not batchable,
so skip the entire batching pipeline for them.

This adds a step which filters mutations into two streams: those which can be batched, which are then passed on to the existing (serialize/sample/assign Partition/group by parttion/batch) pipeline, and those which by definition can not be batched -- ranged delete operations, large mutation groups...

These are then merged into one stream (Flatten) and then written to Spanner.

------------------------
@chamikaramj 

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @nithinsujir

**Comment by nithinsujir** [comment]
R: @biswanag

**Comment by chamikaramj** [comment]
Can we close this PR given that https://github.com/apache/beam/pull/6478 includes this ?

**Comment by nielm** [comment]
yes, closed.

**Pull request closed without merging**
