### PR TITLE
[BEAM-3326] Add a BundleProcessor to SdkHarnessClient

### PR DESCRIPTION
**Pull request by tgroh**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
This is the abstraction to interact with a registered
ProcessBundleDescriptor.

### CODE REVIEW

**Comment by tgroh** [comment]
run python precommit

**Comment by kennknowles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 118 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XhzRvPwrJoCMW93FC:-L2XhzRvPwrJoCMW93FD:bo0o458) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L118)):*
> ```Java
>               BeamFnApi.InstructionRequest.newBuilder()
>                   .setProcessBundle(
>                       BeamFnApi.ProcessBundleRequest.newBuilder()
> ```

At this point, I've paged out the details - why don't we pass a `bundleId` here?

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 157 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XiKdp4KvimnGN14PM:-L2XiKdp4KvimnGN14PN:b-8pl5g9) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L157)):*
> ```Java
>   private final FnApiControlClient fnApiControlClient;
> 
>   private final Cache<BeamFnApi.ProcessBundleDescriptor, BundleProcessor> clientProcessors =
> ```

Maybe should be keyed on id instead of the whole proto?

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 234 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XiT-2hWtkJGdc7p9A:-L2XiT-2hWtkJGdc7p9B:bc2b81v) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L234)):*
> ```Java
>   @AutoValue
>   public abstract static class RemoteInputDesination<T> {
>     public static <T> RemoteInputDesination<T> of(Coder<T> coder, BeamFnApi.Target target) {
> ```

Desination

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4266)*

**Comment by tgroh** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 118 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XhzRvPwrJoCMW93FC:-L2Xmff8aPX6ppT-e_UU:b-qz0c73) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L118)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

At this point, I've paged out the details - why don't we pass a `bundleId` here?
</blockquote></details>

That's a bug.

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 157 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XiKdp4KvimnGN14PM:-L2Xmgv-stI_wljQ05D4:byvyago) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L157)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

Maybe should be keyed on id instead of the whole proto?
</blockquote></details>

Yes. Done.

---

*[runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java, line 234 at r1](https://reviewable.io:443/reviews/apache/beam/4266#-L2XiT-2hWtkJGdc7p9A:-L2XmidkL3Zg6SRAki_V:bt2vr1b) ([raw file](https://github.com/apache/beam/blob/8799be4afeb2427964bed7e3d8e086d1d129bf8c/runners/java-fn-execution/src/main/java/org/apache/beam/runners/fnexecution/control/SdkHarnessClient.java#L234)):*
<details><summary><i>Previously, kennknowles (Kenn Knowles) wrote…</i></summary><blockquote>

Desination
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4266)*

**Comment by tgroh** [comment]
Ping?

**Comment by tgroh** [comment]
Ping?

**Comment by kennknowles** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4266#-:-L3CH0VNFFYLWKnXS5-u:bnfp4nl)*

**Comment by kennknowles** [comment]
Sorry for the delay - you'll need to rebase and resolve conflicts. It will give the tests a chance to retry.

**Pull request merged**
