### PR TITLE
[BEAM-10969] Upgrade Spark to version 2.4.7

### PR DESCRIPTION
**Pull request by iemejia**
R: @aromanenko-dev 
CC: @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by iemejia** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by iemejia** [comment]
Run Python Spark ValidatesRunner

**Comment by iemejia** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by aromanenko-dev** [comment]
Run Java Spark PortableValidatesRunner Streaming

**Comment by iemejia** [comment]
@ibzib The issues on the portable streaming tests are part of the flakes you mentioned at some point?
Apart of this I am really surprised of the issues with the Structured Streaming runner seems they could have broken something due to some backport, that error does not make sense at all. Probably needs more investigation.

**Comment by ibzib** [comment]
> @ibzib The issues on the portable streaming tests are part of the flakes you mentioned at some point?

Yeah, windowing is handled incorrectly: BEAM-10784

**Comment by iemejia** [comment]
@echauchot The exceptions with Structured Streaming runner seems too weird, it is like if Spark was generating invalid code. I doubt that this is an issue in the runner translation, but maybe we need to double check. maybe you have a different insight?

```
Caused by: java.lang.IllegalAccessError: org/apache/beam/sdk/transforms/GroupByKeyTest$BadEqualityKey
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.ObjectOperator$$anonfun$serializeObjectToRow$1.apply(objects.scala:155)
```

**Comment by echauchot** [comment]
@iemejia I'll take a look within a few days, thanks for raising this.

**Comment by iemejia** [comment]
Just for info it seems the errors on Spark Structured Streaming runner are not related to this PR, it seems the runner has its Validates Runner tests broken since https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/2098/
Filled BEAM-11023 for further tracking.

**Comment by iemejia** [comment]
I wonder if we should get this one merged then given that the failing tests are unrelated to the version upgrade. Opinions?
@aromanenko-dev @ibzib

**Comment by ibzib** [comment]
> I wonder if we should get this one merged then given that the failing tests are unrelated to the version upgrade. Opinions?

Fine with me.

**Comment by aromanenko-dev** [comment]
> Fine with me.

+1

**Review by aromanenko-dev — APPROVED** [review]
LGTM

**Comment by echauchot** [comment]
Sorry guys I was on a sick leave so I could not take a look at this PR. Tell me if you need any followup comments.

**Pull request merged**
