### PR TITLE
[BEAM-3029] Sets user agent in BigTableIO.Read.getBigTableService().

### PR DESCRIPTION
**Pull request by chamikaramj**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
R: @reuvenlax

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
R: @lukecwik

**Comment by lukecwik** [comment]
The user agent is meant to be set automatically from PipelineOptions here:
https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.java#L594

**Comment by lukecwik** [comment]
It seems as though the other method getBigtableService doesn't have the userAgent set on it.

**Comment by kennknowles** [comment]
The method `pipelineOptions.getUserAgent()` is not marked `@Nullable` and the default looks to always be non-null. Wouldn't the pipeline options code for `setUserAgent` fail if it were set to null?

**Comment by lukecwik** [comment]
It would fail but it is up to each runner to set the user agent beyond the default.

**Comment by reuvenlax** [comment]
looks good for self-merge.

**Comment by chamikaramj** [comment]
Updated BigTableIO.Read.getBigTableService() instead of IT. Luke, PTAL.

**Comment by lukecwik** [comment]
LGTM

**Comment by lukecwik** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Thanks. Will merge after tests pass.

**Comment by reuvenlax** [comment]
Once you merge please propose a cherry pick against the release branch.

**Comment by chamikaramj** [comment]
Will do.

**Comment by lukecwik** [comment]
Run Java PostCommit

**Pull request closed without merging**
