### PR TITLE
[Spark Dataset runner] Implement producer-consumer fusion for ParDos

### LINKED ISSUE #25761: [Feature Request]: Fuse ParDos in linear linage for Spark Dataset runner (producer-consumer fusion)
### What would you like to happen?

Beam runners may choose to apply optimizations to a pipeline before it is executed. A key optimization, fusion, relates to ParDo operations. If one ParDo operation produces a PCollection that is then consumed as the main input of another ParDo operation, the two ParDo operations will be fused together into a single ParDo operation and run in a single pass; this is "producer-consumer fusion".

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by mosche**
Beam runners may choose to apply optimizations to a pipeline before it is executed. A key optimization, fusion, relates to ParDo operations. If one ParDo operation produces a PCollection that is then consumed as the main input of another ParDo operation, the two ParDo operations will be fused together into a single ParDo operation and run in a single pass; this is "producer-consumer fusion".

This PR implements producer-consumer fusion for sequential ParDos in the Spark Dataset runner.

Closes #25761
This is also a follow up (optimization) regarding https://github.com/apache/beam/pull/25732.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Load Tests Java ParDo SparkStructuredStreaming Batch

**Comment by mosche** [comment]
Run Spark StructuredStreaming ValidatesRunner

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Load Tests Java ParDo SparkStructuredStreaming Batch

**Comment by mosche** [comment]
R: @aromanenko-dev 
R: @echauchot

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by mosche** [comment]
Run Spark Runner Tpcds Tests

**Comment by echauchot** [comment]
@aromanenko-dev can you take a look at this one ?

**Comment by aromanenko-dev** [comment]
@echauchot Sure, I'll take a look

**Review by aromanenko-dev — APPROVED** [review]
LGTM, it should be a nice perf improvement for some use cases.

**Pull request merged**
