### PR TITLE
Fix a typo in gradle task group

### PR DESCRIPTION
**Pull request by swegner**

### CODE REVIEW

**Comment by swegner** [comment]
r: @kennknowles

**Comment by kennknowles** [comment]
run java precommit

**Comment by kennknowles** [comment]
It seems that successes tend to be around 30 minutes. Yet it seems exceedingly unlikely this caused the timeout at 90 minutes.

**Comment by swegner** [comment]
retest this please

ping @kennknowles

**Comment by kennknowles** [comment]
Same comment about Python precommit. But let's move along.

**Pull request merged**
