### PR TITLE
[Go SDK] Refactor integration tests to use internal containers package for test containers

### LINKED ISSUE #24821: [Task][Go SDK]: Refactor Debezium and JDBC IO integration tests to use test container helpers
### What needs to happen?

[#24663](https://github.com/apache/beam/pull/24663) introduced an internal containers package with test helper functions for working with test containers. To reduce repetition, the code in the Debezium and JDBC IO Xlang integration tests can be refactored to also use these functions.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by johannaojeling**
Refactors the Debezium and JDBC IO Xlang integration tests to use the test helpers from the internal containers package when setting up test containers. Fixes #24821.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johannaojeling** [comment]
R: @lostluck

**Review by lostluck — APPROVED** [review]
I very much appreciate how you made the test containers automatically terminate with `t.Cleanup`. Great pattern!

Thank you!

**Comment by lostluck** [comment]
Run Go Flink ValidatesRunner

**Comment by johannaojeling** [comment]
> I very much appreciate how you made the test containers automatically terminate with `t.Cleanup`. Great pattern! And the retries. I'm very happy with that, since it avoids a great number of flakes.
> 
> Thank you!

Agreed, I like it too. Thanks!

**Pull request merged**
