### PR TITLE
[release-2.14.0] [BEAM-7606] Fix JDBC time conversion tests

### PR DESCRIPTION
**Pull request by iemejia**
Cherry pick of 4416b564f48de27d8525fdcb5d7a81e6b98a7d8b into the 2.14.0 release branch

R: @jbonofre @akedin 
CC: @charithe

### CODE REVIEW

**Comment by jbonofre** [comment]
Waiting Jenkins before merging.

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by iemejia** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by jbonofre** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by jbonofre** [comment]
The dataflow Jenkins tests failure doesn't seem to be related to this change.

**Comment by iemejia** [comment]
Thanks @jbonofre !

**Pull request merged**
