### PR TITLE
Delete beam-artifact temp file on exit

### LINKED ISSUE #29215: [Bug]: JavaUsingPython pipline create large tmp files quickly causing CI drain disk space
### What happened?

It is found that Jenkins often run of of disk space even inventory job run twice per day. Checking the filesystem it is found there are many tmp file named after `/tmp/beam-artifact....` hundreds MB per file. see https://ci-beam.apache.org/view/Inventory/job/beam_Inventory_apache-beam-jenkins-7/

This is from 

https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/External.java#L393

Done at pipeline expansion time for external transform.

This suggests real issue for users as tmp file left are large. We should be able to clean up these files after pipeline run.

Interestingly it seems only Jenkins 7 (or a few other workers) are affected. It is known that Jenkins scheduler tend to run same postcommit job on same machine. Likely due to this job:

https://ci-beam.apache.org/job/beam_PostCommit_XVR_JavaUsingPython_Dataflow/

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #29215

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Run XVR_JavaUsingPython_Dataflow PostCommit

**Comment by Abacn** [comment]
Run XVR_Direct PostCommit

**Comment by Abacn** [comment]
Run XVR_Flink PostCommit

**Comment by Abacn** [comment]
Run XVR_Samza PostCommit

**Comment by Abacn** [comment]
Run XVR_Spark3 PostCommit

**Comment by Abacn** [comment]
Flink XVR failed due to https://github.com/apache/beam/issues/29220 try again

**Review by bvolpato — APPROVED** [review]

**Comment by Abacn** [comment]
Run XVR_Flink PostCommit

**Comment by Abacn** [comment]
Run XVR_Samza PostCommit

**Comment by Abacn** [comment]
both XVR test able to pass on Python38, wait until Python311 to complete then we will merge

**Comment by Abacn** [comment]
tests passed

**Pull request merged**
