### PR TITLE
Fix grafana url for alerts and GA Post-Commits Status dashboard

### PR DESCRIPTION
**Pull request by andreydevyatkin**
Fixed metrics url to retrieve grafana alerts and GA Post-Commits Status dashboard

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by andreydevyatkin** [comment]
Run Beam Metrics Deployment

**Comment by damccorm** [comment]
@andreydevyatkin any reason to move this to draft? I think it is correct

**Comment by andreydevyatkin** [comment]
> @andreydevyatkin any reason to move this to draft? I think it is correct

@damccorm I found that the [GA Post-Commits Status dashboard](http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1) displays runs in the wrong order (for instance `Beam Metrics Report` workflow), so decided to fix it as part of this PR - that's why I moved PR to draft for a while

image

**Review by damccorm — APPROVED** [review]
Thanks

**Pull request merged**
