### PR TITLE
Pin protobuf version for TF dependency tests

### PR DESCRIPTION
**Pull request by jrmccluskey**
The Tensorflow dependency test running against TensorFlow 2.12 was failing as the test environment was separately installing protobuf 5.x. This ensures that an appropriate protobuf version is installed before installing beam deps. 

Fresh run of the workflow against this branch is running at https://github.com/apache/beam/actions/runs/11258372012 - there are some pandas/numpy failures that are unrelated.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
hmm, this is working locally but the protobuf version is getting clobbered when the action runs. weird.

**Review by tvalentyn — APPROVED** [review]

**Review by tvalentyn — APPROVED** [review]

**Comment by jrmccluskey** [comment]
for the record this is still not working, the protobuf version keeps being upgraded. current idea is to just disable these tests so we get signal from the rest of the suite while I figure out how to fix them

**Comment by jrmccluskey** [comment]
Okay, got a clean run on https://github.com/apache/beam/actions/runs/11298052670/job/31426200604 (the numpy failures have been fixed on master)

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
PTAL at lint errors

**Comment by jrmccluskey** [comment]
I don't understand how there's a linting failure when the only file changed isn't python and doesn't get linted...

**Comment by jrmccluskey** [comment]
Everything green, merging

**Pull request merged**
