### PR TITLE
[BEAM-2224] Cherry-pick #2965, #2971, #2975 onto release-2.0.0 

### PR DESCRIPTION
**Pull request by robertwb**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by robertwb** [comment]
R: @charlesccychen @davorbonaci

**Comment by charlesccychen** [comment]
Thanks, LGTM.

**Comment by robertwb** [comment]
Merged into release branch.

**Comment by dhalperi** [comment]
Please close PR at your leisure.

**Pull request closed without merging**
