### PR TITLE
[BEAM-2561] add integration test for date functions

### PR DESCRIPTION
**Pull request by xumingming**
R: @XuMingmin @takidau 

there are some duplications with PR #3532 , will do some refactor after #3532 is merged.

### CODE REVIEW

**Comment by xumingming** [comment]
Rebase done.

**Comment by xumingming** [comment]
Retest this please.

**Comment by JingsongLi** [comment]
+ R @JingsongLi, I'll take a quick look.

**Comment by JingsongLi** [comment]
Merged. Feel free to close.

**Comment by xumingming** [comment]
Thanks @XuMingmin @JingsongLi !

**Pull request closed without merging**
