### PR TITLE
[BEAM-6408] Fix load test job

### PR DESCRIPTION
**Pull request by lgajowy**
This jenkins job timeouted because we used only 10 workers and set a default 2 hours timeout on jenkins. I increased both the timeout (to 4 hrs) and workers (to --maxNumWorkers=32). I'm unsure if those are the right values - they certainly do the job (no timeout) but is it ok to use 32 workers? 

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Run GroupByKey Small Java Load Test Dataflow

**Comment by lgajowy** [comment]
Run GroupByKey Small Java Load Test Dataflow

**Comment by lgajowy** [comment]
@alanmyrvold, @swegner, @pabloem, @lukecwik could some of you take a look? 

I also started a devlist thread around this topic here (in case you have any thoughts): [link to the thread](https://lists.apache.org/thread.html/bcef2c05bd3ca9d545e51843112f1275e7e35f51f4b17d2c8191b139@%3Cdev.beam.apache.org%3E)

Thanks!

**Comment by swegner** [comment]
This generally seems ok. The only concern-- as you mention in the dev@ thread-- is whether we need to worry about exhausting our Dataflow resources.

@alanmyrvold can you help evaluate whether this change is OK with respect to Dataflow resources?

**Comment by lgajowy** [comment]
@alanmyrvold pinging this kindly :)

**Comment by lgajowy** [comment]
Run seed job

**Comment by lgajowy** [comment]
Resolved conflicts, tested if it builds the job.

@alanmyrvold it is not scheduled - it can be only phrase triggered (run on demand from GH) for now. It is not decided yet how often such tests should run. Once we run such tests periodically I agree that they should not overlap. I will keep an eye on this aspect as well.

**Pull request merged**
