### PR TITLE
[BEAM-8217] Cherry-pick PR #9551: Encode str to bytes py3 in sdk harness status server

### PR DESCRIPTION
**Pull request by angoenka**
[BEAM-8217] Encode str to bytes py3 in sdk harness status server

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by angoenka** [comment]
The error seems to be the same for Python Precommit as well

```
E 2019-09-12T18:47:30.173982702Z Handler for POST /v1.27/images/create returned error: manifest for gcr.io/cloud-dataflow/v1beta3/python37-fnapi:2.16.0 not found 
I 2019-09-12T18:47:30.175284933Z Container image gcr.io/cloud-dataflow/v1beta3/python37-fnapi:2.16.0 not found in VM cache. Will download. 

```

**Comment by angoenka** [comment]
Let me know if you think its ok to merge this PR as the failure error for Precommit tests seems to be unrelated.

**Comment by Hannah-Jiang** [comment]
> @Hannah-Jiang is working on a fix that address the Portable_python failure. Not sure if Precommit has same root cause.

My PR (#9560)is ready to merge once it passes the failing tests, it is waiting for creating new dataflow workers.

**Comment by Hannah-Jiang** [comment]
> The error seems to be the same for Python Precommit as well
> 
> ```
> E 2019-09-12T18:47:30.173982702Z Handler for POST /v1.27/images/create returned error: manifest for gcr.io/cloud-dataflow/v1beta3/python37-fnapi:2.16.0 not found 
> I 2019-09-12T18:47:30.175284933Z Container image gcr.io/cloud-dataflow/v1beta3/python37-fnapi:2.16.0 not found in VM cache. Will download. 
> ```

Where did you see this error? If I check the log from the `Details` link, timestamp is different and cannot find the log you pasted.
It's weird only py2 and py37 failed if it is caused by docker images.

**Comment by markflyhigh** [comment]
That's the log from worker in pantheon. You can find it from dataflow console.

**Comment by angoenka** [comment]
Do you also need to cherrypick #9560 to realease-2. 16 branch?

**Comment by markflyhigh** [comment]
yes. It's not merged since current precommit failed due to old dataflow container. I'd like to make test pass first.

**Comment by Hannah-Jiang** [comment]
My investigation is re-create dataflow worker would solve Precommit problem.
From [here](https://github.com/apache/beam/blob/release-2.16.0/sdks/python/apache_beam/runners/dataflow/internal/apiclient.py#L947), it used to use an image with `beam-master-20190802` tag, but after we change version from `2.16.0.dev` to `2.16.0` at `version.py`, it uses the one with `2.16.0` tag and now cannot find this image.

**Comment by markflyhigh** [comment]
We chatted offline with Hannah and it's part of the issue on Dataflow side.

**Pull request merged**
