### PR TITLE
[BEAM-4106] Add FileStagingOptions and merge staging file options between runners

### PR DESCRIPTION
**Pull request by iemejia**
R: @chamikaramj @ibzib

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java PreCommit

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run Flink ValidatesRunner

**Comment by chamikaramj** [comment]
LGTM. Thanks.

**Pull request merged**
