### PR TITLE
Restrict google-api-core

### LINKED ISSUE #22454: [Bug]: Spanner ITs are failing in Py37 PostCommits
### What happened?

Lots of SpannerIO tests started to fail once we upgraded google-cloud-recommendations-ai to 0.7.0.

Example:

https://ci-beam.apache.org/job/beam_PostCommit_Python37/5516/testReport/junit/apache_beam.io.gcp.experimental.spannerio_read_it_test/SpannerReadIntegrationTest/test_table_metrics_error_call/

```
Error Message
test setup failure
Stacktrace
cls = <class 'apache_beam.io.gcp.experimental.spannerio_read_it_test.SpannerReadIntegrationTest'>

    @classmethod
    def setUpClass(cls):
      _LOGGER.info(".... PyVersion ---> %s" % str(sys.version))
      _LOGGER.info(".... Setting up!")
      cls.test_pipeline = TestPipeline(is_integration_test=True)
      cls.args = cls.test_pipeline.get_full_options_as_args()
      cls.runner_name = type(cls.test_pipeline.runner).__name__
      cls.project = cls.test_pipeline.get_option('project')
      cls.instance = (
          cls.test_pipeline.get_option('instance') or _TEST_INSTANCE_ID)
      _ = cls._generate_table_name()
      spanner_client = cls._SPANNER_CLIENT = spanner.Client()
      _LOGGER.info(".... Spanner Client created!")
      cls._SPANNER_INSTANCE = spanner_client.instance(cls.instance)
      cls._create_database()
>     cls._add_dummy_entries()

apache_beam/io/gcp/experimental/spannerio_read_it_test.py:105: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
apache_beam/io/gcp/experimental/spannerio_read_it_test.py:87: in _add_dummy_entries
    with database.batch() as batch:
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/database.py:611: in __enter__
    session = self._session = self._database._pool.get()
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/pool.py:273: in get
    session.create()
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/session.py:113: in create
    api = self._database.spanner_api
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/database.py:235: in spanner_api
    client_options=client_options,
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/gapic/spanner_client.py:194: in __init__
    address=api_endpoint, channel=channel, credentials=credentials
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py:77: in __init__
    "grpc.keepalive_time_ms": _GRPC_KEEPALIVE_MS,
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py:114: in create_channel
    address, credentials=credentials, scopes=cls._OAUTH_SCOPES, **kwargs
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/google/api_core/grpc_helpers.py:297: in create_channel
    return grpc.secure_channel(target, composite_credentials, **kwargs)
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/grpc/__init__.py:2005: in secure_channel
    credentials._credentials, compression)
../../build/gradleenv/-1734967052/lib/python3.7/site-packages/grpc/_channel.py:1480: in __init__
    credentials)
src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi:454: in grpc._cython.cygrpc.Channel.__cinit__
    ???
src/python/grpcio/grpc/_cython/_cygrpc/arguments.pyx.pxi:76: in grpc._cython.cygrpc._ChannelArgs.__cinit__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: Expected int, bytes, or behavior, got <class 'grpc_gcp_pb2.ApiConfig'>
```

Likely this is due to some changes to the transitive dependency chain.

### Issue Priority

Priority: 1

### Issue Component

Component: dependencies

### PR DESCRIPTION
**Pull request by tvalentyn**
Fixes #22454.

`google-cloud-spanner==1.x` implicitly require `google-api-core <2.8.2`. Most likely, this is because since google-api-core==2.8.2 drops support for grpcio-gcp: https://github.com/googleapis/python-api-core/pull/401, which is used by google-cloud-spanner.

Also, regenerated container dependencies.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
R: @BjornPrime cc: @parthea

**Comment by tvalentyn** [comment]
Noting that postcommit passed: https://ci-beam.apache.org/job/beam_PostCommit_Python37_PR/384/

**Comment by tvalentyn** [comment]
also R: @kileys (next release manager) - I think you would need this change and the change updating container requirements on the release branch.

**Review by kileys — APPROVED** [review]

**Comment by tvalentyn** [comment]
Docker precommit also passed, https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Commit/12107. all other test suites passed on previous commit and are not affected by requirements change (second commit). merging.

**Pull request merged**
