### PR TITLE
[BEAM-13250] Factorise gcsio.GcsIO() from gcsfilesystem to allow overriding

### PR DESCRIPTION
**Pull request by BigJerBD**
Improvement to resolve :  https://issues.apache.org/jira/browse/BEAM-13250
first commit is identical to https://github.com/apache/beam/pull/15977, but since I believe this is relevant , I am open to put some effort to integrate a proper solution 

This change is relevant for testing purpose. Being able to change `storage_client` allows use gcs emulator or other gcs configurations.  (for example: https://github.com/fsouza/fake-gcs-server/issues/623#issuecomment-1107093547 )

This way it is possible at the very least to do : 

```
class TestGCSFileSystem(GCSFileSystem):
  GCS_PREFIX = 'gs-test://'

  @classmethod
  def scheme(cls):
    return 'gs-test'

  @staticmethod
  def get_gcsio():
    return gcsio.GcsIO(
      storage_client=storage.StorageV1(
          url="http://my_custom_url...",
          # Other custom configurations ...
      )
    )

```
Please note that this is not only usefull for testing purpose, it allows more flexibility  to configure the storage_client for the price of adding another user defined filesystem scheme 

Another alternative could to instead add an beam options  to be able to replace the url or other options. This might be better since it does not a new function to the GcsFileSystem that could be used by sdk users

Thanks :)

R:  @aaltay  @ihji

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
I don't see anything wrong with this change per se, but I think it would make more sense alongside a test change that leverages the new factorization. Do you have a specific test scenario that would be helped by this?

**Comment by BigJerBD** [comment]
This could be done to simplify some tests that patches on the module level
```python
  # in sdks/python/apache_beam/io/gcp/gcsfilesystem_test.py
  @mock.patch('apache_beam.io.gcp.gcsfilesystem.gcsio')   # this could be removed
  def test_create(self, mock_gcsio):
    # Prepare mocks.
    gcsio_mock = mock.MagicMock()
    gcsfilesystem.gcsio.GcsIO = lambda: gcsio_mock   # this would become:  self.fs.get_gcsio =  lambda: gcsio_mock
    ...
```
Would it be enough?

it might looks irrelevant but at the very least sdk users using those classes  directly do not have to  patch modules to override some gcsio.GcsIO properties if considered necessary

**Comment by aaltay** [comment]
@johnjcasey - would you be able to respond to the last question?

**Comment by johnjcasey** [comment]
Yep, that would work for me.

**Comment by BigJerBD** [comment]
Perfect I'll apply the change in the coming week

**Comment by BigJerBD** [comment]
Closing this PR since a similar change seems to have been merged to master : 

currently on master:
```python
# sdks/python/apache_beam/io/gcp/gcsfilesystem.py ...
 def _gcsIO(self):
    return gcsio.GcsIO(pipeline_options=self._pipeline_options)
```

**Pull request closed without merging**
