### PR TITLE
Enable remote gradle cache and build scan for GitHub Actions workflows

### LINKED ISSUE #28378: [Task]: enable remote gradle cache and build scan for newly added github action workflow
### What needs to happen?

The remote gradle cache and build scan was added in #28212. However, some workflows added after this PR did not include those envs (e.g. Java PreCommit). When the workflow are in stable state, we should check all and see if there is any workflow missing these settings. Also, it would be convenient to attach the build scan link to workflow summary (like what we did for the Website Staging link)

In general, it would be nice to have these configured in a single place instead every workflow yaml needs to add these line
```
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}
```
(as in #28212)

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by andreydevyatkin**
fixes #28378

The following changes have been made:
- Updated the `setup-environment-action/action.yml` action to publish build scan for all GitHub Actions workflows by adding the mandatory step `gradle/gradle-build-action@v2`
- Added missing Gradle configs for each workflow

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by andreydevyatkin** [comment]
Run RAT PreCommit

**Comment by andreydevyatkin** [comment]
Run RAT PreCommit

**Comment by andreydevyatkin** [comment]
Run RAT PreCommit

**Review by damccorm — APPROVED** [review]
Thanks!

**Comment by tvalentyn** [comment]
seeing many errors in post step of /.github/actions/setup-action : Index out of range .

sample run: https://github.com/apache/beam/actions/runs/6250219560/job/16969848231?pr=28557

https://github.com/actions/runner/issues/2816 looks similar . Is it caused by this change?

**Comment by volatilemolotov** [comment]
@tvalentyn I just checked and i see failures in workflows with v3 and v4 so i dont think that could be the cause. 
The index issue happens in setup repository post step which does not use checkout action but instead uses bash and git command. 

The issue im looking at is that checkout pulls in the current master. Then the setup action pulls in the merge comment and that causes a difference in number of steps. I have checked the PR and no changes to actions were made so im not sure from where the issue comes from

**Pull request merged**
