### PR TITLE
Updating Dataflow API protos and client

### PR DESCRIPTION
**Pull request by pabloem**
r:@aaltay 
Ran job 2017-05-02_14_25_41-229271276661569030 with these changes.
I believe it's not necessary to update `dataflow_v1b3_client.py`. Is this correct?

### CODE REVIEW

**Comment by aaltay** [comment]
Run Python PostCommit

**Comment by aaltay** [comment]
It is not necessary to change `dataflow_v1b3_client.py`.

**Comment by aaltay** [comment]
LGTM, I can merge it after tests.

**Comment by pabloem** [comment]
Could you merge please? : )

**Pull request closed without merging**
