### PR TITLE
Download codecov uploader since codecov has been removed from pypi

### PR DESCRIPTION
**Pull request by AnandInguva**
Fixes: https://github.com/apache/beam/issues/26251

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
I'd like to give https://github.com/apache/beam/pull/26283 a try before merging this one (not sure if it will work)

**Comment by AnandInguva** [comment]
I was aiming for the same thing. I just made a commit for that. I was testing it locally. seems like this could work

**Comment by AnandInguva** [comment]
I would wait and merge this https://github.com/apache/beam/pull/26082 first. Then solve this.

**Comment by damccorm** [comment]
> I would wait and merge this https://github.com/apache/beam/pull/26082 first. Then solve this.

Is there a reason to wait? I'd actually rather prioritize this one to get CI green

**Comment by AnandInguva** [comment]
> > I would wait and merge this #26082 first. Then solve this.
> 
> Is there a reason to wait? I'd actually rather prioritize this one to get CI green

Actually we don't need to wait. we can merge.

**Comment by damccorm** [comment]
SGTM - I'll wait for https://ci-beam.apache.org/job/beam_PreCommit_Python_Coverage_Commit/1689/console to complete then merge

**Review by damccorm — APPROVED** [review]
LGTM

**Pull request merged**
