### PR TITLE
[BEAM-646] Get Apex Runner out of the #apply()

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Move Apex Overrides to be applied via graph surgery.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @tweise @kennknowles 

This is built on #2061 and #2055

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tweise** [comment]
@tgroh the ViewAsXXX translation override was originally copied from FlinkRunner as there was no better way to reuse it (see https://github.com/apache/beam/blob/release-0.5.0/runners/apex/src/main/java/org/apache/beam/runners/apex/ApexRunner.java#L167 and everything below). Is this perhaps an opportunity to correct the default translation to make these extensive overrides unnecessary?

https://issues.apache.org/jira/browse/BEAM-783

**Comment by tgroh** [comment]
I would claim that there isn't really a "default translation" for `CreatePCollectionView`, but there may be some common ones, and it may be worth refactoring the common style of "Concatenate-and-write-view" overrides into `runners-core-construction`  (either here or elsewhere; I'd prefer the latter).

Most of this is also going to go away once more of the runner API is implemented, more precisely `ViewFns` as the way we specify a view. That may be ultimately implemented very similarly, and may have an approximately identical solution, but hopefully we'll have fewer `CreateView` transforms and just one way to materialize a collection.

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tgroh** [comment]
@tweise Any other thoughts?

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tweise** [comment]
@tgroh LGTM

I would recommend for future PRs to avoid formatting of code that is not otherwise modified. It unnecessary bloats the diff.

**Comment by tgroh** [comment]
My bad. I've reverted most of the formatting changes that I could see, and I'll merge once Apex ROS turns green again, or ping you if it turns out I've missed something.

Thanks!

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by tgroh** [comment]
retest this please

**Pull request closed without merging**
