### PR TITLE
[BEAM-3573] Move TestCountingSource to appropriate location

### PR DESCRIPTION
**Pull request by kennknowles**
This is a utility for testing, akin to `PAssert` or `TestStream`, yet was in a very strange location.

----

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tgroh** [comment]
Can this be removed in its entirety (and replaced with just `CountingSource`?)

**Comment by kennknowles** [comment]
Good point. I hope so. Incidentally I hit this problem because of dependencies not working - test deps aren't transitive. They aren't identical so it will take me a minute.

**Comment by kennknowles** [comment]
OK, after spending a minute on this and not wanting to waste a ton of time, it can be inlined to the one place it is used in the Beam codebase. Anyone outside the Beam codebase using this needs to switch to CountingSource.

**Comment by kennknowles** [comment]
Squashed and forced pushed because now it is a different change (both code noops). WDYT?

**Comment by kennknowles** [comment]
run java gradle precommit

**Pull request merged**
