### PR TITLE
Gearpump pom: runnable-on-service-tests is now validates-runner-tests

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

Adjust the gearpump pom to match the master configuration. This will also require the Jenkins job to be fixed up before it will work right, but that has to be done on the master branch.

R: @manuzhang

### CODE REVIEW

**Comment by kennknowles** [comment]
Actually, I just made it active by default, since it is the main thing was always want to check on this feature branch. We will turn it into a postcommit once it is on master. Otherwise it is too annoying to adjust Jenkins config on master but the pom.xml on the branch.

**Comment by manuzhang** [comment]
Filed https://github.com/apache/beam/pull/3181 to fix `WindowingTest#testNonPartitioningWindowing`. Strangely, I cannot reproduce the other two locally.

**Comment by kennknowles** [comment]
For now, I've excluded those tests just so the build can succeed.

**Comment by manuzhang** [comment]
I've cherry-picked the activation commit to https://github.com/apache/beam/pull/3181 and try to fix the tests failure there. Could you allow me to work it out ?

**Comment by kennknowles** [comment]
Yes, I seem to keep failing to exclude enough test classes. It seems likely that the failure is not directly related to just the things in those tests, but something used in basically all tests is nondeterministic.

**Comment by kennknowles** [comment]
I'll close this one.

**Pull request closed without merging**
