### PR TITLE
Re revert go sdk

### PR DESCRIPTION
**Pull request by kennknowles**
Into the Go SDK branch, merges `master` up to revert of accidental Go SDK, plus re-revert to put the Go SDK back.

### CODE REVIEW

**Comment by lukecwik** [comment]
CC: @wcn3 @herohde @lostluck

**Comment by lukecwik** [comment]
Note that #4808 is the change to fix up the master branch.

**Comment by kennknowles** [comment]
I'll wait for #4808 to go green and get merged to `master` before doing anything on this one, to be sure they keep compatible histories.

**Comment by wcn3** [comment]
I've validated the Go build still works, so LGTM from that perspective.

**Comment by kennknowles** [comment]
Were the RAT failures pre-existing?

**Comment by lukecwik** [comment]
It turns out that the Go/Java precommits don't depend on running RAT so it is being skipped:
https://github.com/apache/beam/blob/9eca13c0386a6b2c9b83a9e3fef081d377857765/build.gradle#L294

**Comment by kennknowles** [comment]
Why is the precommit looped out and using those targets? Shouldn't it just be straight line hardcoded list of targets like `:sdks:java:core:check` and `:globalRAT` or some such?

**Comment by lukecwik** [comment]
Ken, please direct your comments on #4830

**Pull request closed without merging**
