### PR TITLE
[Task] Update document for spark runner on a kubernetes cluster

### PR DESCRIPTION
**Pull request by HaoXuAI**
The PR updated the Spark runner document, including the way to run the beam job on a spark kubernetes cluster.
The work at Affirm has verified this.
address #27985

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damccorm** [comment]
@mosche or @aromanenko-dev would you mind taking a look?

**Comment by damccorm** [comment]
@aromanenko-dev or @mosche could you please take a look?

**Comment by mosche** [comment]
Thanks, this is looking great @HaoXuAI. Unfortunately I don't have much time to give this a closer look at the moment. @aromanenko-dev Can you give this a closer look?

**Review by mosche — APPROVED** [review]
Thanks @HaoXuAI, LGTM 👍 
Sorry for the delay on this.

**Comment by aromanenko-dev** [comment]
Sorry, I was on vacation in the last weeks. 

Thanks @HaoXuAI for contribution and @mosche for taking care of this!

**Pull request merged**
