### PR TITLE
Add Publish JUnit Test Results Action

### PR DESCRIPTION
**Pull request by magicgoody**
This PR was created to add an action that visualize the results of JUnit tests and adds them to the workflow summary page and the PR page (if the PR exists).

The action requires additional permissions:
pull-requests: write (allow adding the test result to the PR page)
checks: write (allow to add test result to workflow summary page)
issues: write (allow to add the test result in order if the issue was created or it was a comment/push)

Example runs:
Push: https://github.com/magicgoody/beam/actions/runs/5926105477
Pull_request_target: https://github.com/magicgoody/beam/actions/runs/5926531661

image

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by chamikaramj** [comment]
@Abacn could you check or suggest a reviewer ?

**Comment by Abacn** [comment]
third party action needs apache infra's approval to be able to run. Shall I make a request?

Also, if there is a test failure, is it possible to see which test and what is the reason for failure? This is the useful part. A summary of how many test run is already available in the log page, but currently the inconvenience for existing github action workflow is that when there is a  test failure, there is no way to see the stack trace.

**Review by Abacn — APPROVED** [review]
awesome! That really helps!

**Comment by Abacn** [comment]
Let's get this in and see if the workflow also runs on beam repo. Possible need request permission to infra

**Comment by magicgoody** [comment]
Third party action is blocked, the workflow is not running
image

**Comment by Abacn** [comment]
As expected. created https://issues.apache.org/jira/browse/INFRA-24950 requesting enabling this action

**Comment by Abacn** [comment]
Update: the third party workflow is whitelisted. I see a green run: https://github.com/apache/beam/actions/runs/6150041760/job/16687179322

But also there is failing run "Invalid workflow file
The workflow is not valid. Maximum object size exceeded"

https://github.com/apache/beam/actions/runs/6151946870/workflow

Will keep monitoring

**Comment by Abacn** [comment]
Also, when we apply this plugin to all other java tests, can we also change the uploaded archive for "JUnit Test Results" from `**/build/test-results/**/*.xml` to `**/build/reports/tests/` here, and change the condition to
```
if: failure()
```
so it would upload human readable detailed test results on failure.

https://github.com/apache/beam/blob/3304e1258b3268fbdd29de14d35a0da3644493e7/.github/workflows/beam_PreCommit_SQL_Java17.yml#L111

The current xml is not human readable, and `**/build/reports/tests/` contains html that include both stack trace and stdout / stderr

**Comment by magicgoody** [comment]
Hello @Abacn 
Sure, thanks

**Pull request merged**
