### PR TITLE
[BEAM-5270] Finish Python 3 porting for coders subpackage

### PR DESCRIPTION
**Pull request by RobbeSneyders**
This PR finishes the porting of the coders subpackage to Python 3 as outlined [here](https://s.apache.org/beam-python-3).

Python 3 tests can be activated per module by extending the module list under the py3 test environment in tox.ini.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by RobbeSneyders** [comment]
R: @tvalentyn @Fematich

**Comment by tvalentyn** [comment]
retest this please

**Comment by RobbeSneyders** [comment]
The py3 test suite does not run yet on Jenkins, and the docs test fails because of the futurize command not being found during the proto generation.

I'm working on these issues in #6266.

**Comment by tvalentyn** [comment]
I see, thanks. Let me know when the other change is ready for review.

**Comment by tvalentyn** [comment]
LGTM, thank you!

**Comment by tvalentyn** [comment]
cc: @aaltay

**Comment by tvalentyn** [comment]
Could you rebase this please?

**Comment by RobbeSneyders** [comment]
Rebased @tvalentyn

**Comment by tvalentyn** [comment]
Thank you, @RobbeSneyders 
I also checked coders microbenchmark to verify performance was not affected, although changes seem safe.

**Comment by tvalentyn** [comment]
@aaltay this is ready to merge.

**Pull request merged**
