### PR TITLE
[BEAM-12164]: Add retry protection to DetectNewPartitions

### PR DESCRIPTION
**Pull request by thiagotnunes**
The original algorithm of the DetectNewPartitions is susceptible to failures, because it produces side effects on every try which is not  idempotent. Specifically, it marks the partitions as SCHEDULED in the Spanner database and outputs them. If there is a bundle commit failure, during retry, the already SCHEDULED partitions will not be picked up again.

We change the algorithm in this PR to always schedule partitions that have a created at timestamp greater than the one saved in the DetectNewPartitions restriction. When scheduling the partitions, this SDF will also claim the created at of such partitions, advancing the timestamp saved. If there is a bundle commit failure, the restriction timestamp won't be saved, thus the partitions in the bundle will be picked up again regardless of their state.

More information can be seen at: https://docs.google.com/document/d/1IQAOqLmGuIaOJc55NmfUckM4rDCXHAmxKNuRg6Ae07U/edit#heading=h.q3e0xrkg85ay

### CODE REVIEW

**Comment by thiagotnunes** [comment]
Needs #16581 to be merged first

**Comment by thiagotnunes** [comment]
R: @pabloem

**Comment by pabloem** [comment]
sorry about the delay - do you think you could rebase this so I can look at the diff more easily?

**Comment by thiagotnunes** [comment]
Rebased, this is ready to be reviewed / merged now.

**Comment by thiagotnunes** [comment]
retest this please

**Comment by pabloem** [comment]
thanks for detailing the algorithm in the doc. This makes sense to me. Let me take a look at the code now...

**Comment by pabloem** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by pabloem** [comment]
this algorithm actually makes a lot of sense. LGTM.

**Comment by pabloem** [comment]
I'll merge after Examples Java 17 runs

**Pull request merged**
