### PR TITLE
Update python base image dependencies

### PR DESCRIPTION
**Pull request by AnandInguva**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by damccorm — APPROVED** [review]
Thanks

**Comment by AnandInguva** [comment]
```

372.7 sqlalchemy 1.4.50 requires greenlet, which is not installed.
372.8 Container does not include required Beam dependencies or has conflicting dependencies. If Beam dependencies have changed, you need to regenerate 
```

The docker precommit is failing due to the above error. I will investigate what that is.

**Comment by tvalentyn** [comment]
maybe another macos issue?

**Comment by AnandInguva** [comment]
sqlalchemy installing from MacOS M1 doesn't require greenlet as its dependency but when running on linux it does require greenlet as a dependency. 

I will generate these dependencies in linux for now. FYI, I was able to install greenlet on MacOS so I will ask sqlalchemy if this restriction is still valid on their end.

**Comment by AnandInguva** [comment]
Failing tests are not related to this PR. CC @damccorm( python oncall)  FYI

**Comment by damccorm** [comment]
Looks like it was broken by https://github.com/apache/beam/pull/29777 - checking for a quick fix, if not I'll rollback

**Comment by damccorm** [comment]
Should be fixed by https://github.com/apache/beam/pull/29801

**Comment by AnandInguva** [comment]
Python Coverage is failing and could be a flake. the scheduled run is green - https://github.com/apache/beam/actions/runs/7249689864/job/19748209860

Anyway I will keep on eye on the scheduled runs. Merging this PR.

**Pull request merged**
