### PR TITLE
[prism] Skip python tests that require an expansion service at this time.

### PR DESCRIPTION
**Pull request by lostluck**
Related to #28187.

Skip the copied kafka, SQL, and external transform tests that require an expansion Service stood up.

We should eventually have a post commit for these, but in the short term, filter them out to enable a pre-commit suite to execute.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @jrmccluskey 

I'm pretty confident the tests I'm skipping are not what's causing the checks to fail, though I am re-running them.

**Comment by jrmccluskey** [comment]
The line failing is here: 

https://github.com/apache/beam/blob/7af43ee4a4a6fb348e57ea066ed6261c453dcc35/sdks/java/container/common.gradle#L118

I'm inclined to say that is not an associated issue

**Review by jrmccluskey — APPROVED** [review]
LGTM, only nit is that it may be better to comment out the test content to restore later unless you intend to write new tests later

**Comment by lostluck** [comment]
> LGTM, only nit is that it may be better to comment out the test content to restore later unless you intend to write new tests later

Oh i originally copied those from the Flink runner tests, so nothing of value has been lost.

Thanks!

**Pull request merged**
