### PR TITLE
Revert "Cherrypick #15418 and #15515"

### PR DESCRIPTION
**Pull request by udim**
Reverts apache/beam#15608

Java postcommit failure: 
`java.lang.NoSuchMethodError: com.google.cloud.pubsublite.v1.stub.AdminServiceStubSettings$Builder.setMtlsEndpoint(Ljava/lang/String;)Lcom/google/api/gax/rpc/StubSettings$Builder`
https://ci-beam.apache.org/job/beam_PostCommit_Java_PR/790/testReport/

This PR is missing a gax dependency update provided in BOM v22: #15411

### CODE REVIEW

**Comment by udim** [comment]
R: @kennknowles 
CC: @dpcollins-google

**Comment by dpcollins-google** [comment]
I would prefer an explicit cherrypick to bump the gax version from 1.63.0 to 1.65.0 which should also solve the identified issue.

**Comment by kennknowles** [comment]
We should really be focused on getting this release stabilized, not rolling forward fixes. Especially when they bump dependencies. The next release is around the corner.

**Review by kennknowles — APPROVED** [review]
Approve. I expect for most users basically either a version of Beam bumps deps or doesn't. Let's not add dep bumps at the last minute. They can be risky changes.

**Comment by udim** [comment]
Run Java PreCommit

**Comment by udim** [comment]
run java postcommit

**Comment by udim** [comment]
Run Java PreCommit

**Pull request merged**
