### PR TITLE
[BEAM-7190] Enable file based token auth for samza portable runner

### PR DESCRIPTION
**Pull request by lhaiesp**
For Samza and potentially other portable runners who do not use docker and need to run on multi-tenant environment, there is a need to secure the communication between sdk worker and runner. Currently the SSL/TLS in portability is half done.

However, after investigation we found that it's sufficient to just
1. Use loopback address. So that the traffic is not exposed to external network
2. Enforce authentication. So that only the valid users can connect to the ports. 

With the two steps above, it won't be necessary to enable TLS. Because the data channel is only local and one needs root privilege to eavesdrop the local traffic.

A trivial way to do authentication is to share a secret token through file system (e.g. set the file permission to be 600, i.e. -rw-------) . Next we introduce a customized interpreter for both the gRPC client and server to provide and verify this token (see GrpcFileTokenAuthProvider.java and token_auth_interceptor.py). The server can then deny any connection attempts that do not have the right token.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by angoenka** [comment]
- Can we make the token creation and authentication modular and pluggable so that it can be added to other runners as well by setting a pipeline option. 
- We will also need secure channel to encrypt the content to call it truely secure.

**Comment by lhaiesp** [comment]
@angoenka can you be a little bit more specific about making it modular? Right now runners instantiate and start gRPC servers on their own. What I could do now is to put more logic into a util function but ultimately each runner needs to integrate with it themselves.

On your second point, the channel is effectively "secure" because 1) traffic is loopback only so there is no real network packet 2) the loopback traffic can not be eavesdropped unless by a root user, who can basically do anything including reading the private keys on file on in memory

**Comment by angoenka** [comment]
We are essentially creating a new header interceptor to validate the information in the header. We can make it modular by letting users specify the interceptor when starting job server.
The jobserver can convey the interceptor class name to the Samza/Flink/Spark ExecutableStage function which will add the interceptor when creating the Channels. A similar option can be passed to SDK Harness to add an arbitrary grpc interceptor.

To implement the use case of token based validation, Samza jobserver can simply instrument these options correctly.

**Comment by lhaiesp** [comment]
Sorry for being inactive here. We were busy with many internal issues when onboarding users to production. I'm back to work on it this week. Will consume the feedback and make the change. Thanks!

**Pull request closed without merging**
