### PR TITLE
[BEAM-4229] Revert BigQuery SQL support so Spanner works

### PR DESCRIPTION
**Pull request by apilloud**
So I can't downgrade BigQuery because of google-api-client, I can't upgrade Spanner because of grpc, and I can't have both because of google-cloud-core.

Time to revert my feature.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [X] Write a pull request description that is detailed enough to understand:
   - [X] What the pull request does
   - [X] Why it does it
   - [X] How it does it
   - [X] Why this approach
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Run `./gradlew build` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by apilloud** [comment]
R: @chamikaramj 
cc: @kennknowles

**Comment by chamikaramj** [comment]
Thanks. LGTM.

**Comment by kennknowles** [comment]
Reading the description of this PR makes me sad. Is there a JIRA filed for the followup? We need at least a workaround.

**Comment by chamikaramj** [comment]
Probably best path forward is to update gRPC and protobuf dependencies which was requested by a number off users.

**Comment by kennknowles** [comment]
Do we have to update them globally? Is there a JIRA with any notes on which modules have which problems?

**Comment by apilloud** [comment]
https://issues.apache.org/jira/browse/BEAM-3098

**Pull request merged**
