### PR TITLE
[BEAM-3172] Fix flakiness in sideinputs_test

### PR DESCRIPTION
**Pull request by charlesccychen**
This change also does a slight clean-up of the exception handling logic.

R: @chamikaramj

### CODE REVIEW

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by asfgit** [comment]
SUCCESS 
 
--none--

**Comment by chamikaramj** [comment]
LGTM

**Pull request merged**
