### PR TITLE
[runners-flink] #28258 Wait infinitely if the duration value is less …

### PR DESCRIPTION
**Pull request by ddebowczyk92**
…than 1ms in FlinkDetachedRunnerResult

This PR addresses issue #28258. If the provided `duration` value will be less than 1ms, the `while` loop condition will be always `True`  

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by ddebowczyk92** [comment]
assign set of reviewers

**Comment by damccorm** [comment]
@je-ik would you mind taking a look at this one?

**Comment by je-ik** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by je-ik** [comment]
The change LGTM, failing check seems not related, but I'd like to see the precommit pass. @damccorm do you see why the dataflow check fails?

**Comment by damccorm** [comment]
I am not sure, looks like there are some intermittent flakes with the suite though. This change is almost definitely not the culprit, so I'd lean towards us just filing an issue for testMaxThreadMetric and not blocking the PR. I also kicked it again to see if we can get a green run

**Comment by je-ik** [comment]
OK. LGTM, @ddebowczyk92 thanks for the fix!

**Pull request merged**
