### PR TITLE
Fix flaky Python local filesystem test

### PR DESCRIPTION
**Pull request by bsidhom**
Filesystem list order is not well-defined. This switches a python test to use [`assertItemsEqual`](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual) instead of `assertEqual`.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand:
   - [ ] What the pull request does
   - [ ] Why it does it
   - [ ] How it does it
   - [ ] Why this approach
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by bsidhom** [comment]
R: @aaltay

**Comment by bsidhom** [comment]
Note that :beam-sdks-python:setupVirtualenv has been failing for a while on Jenkins (possibly because `virutalenv` is not installed on the instance). I expect it to fail here as well. However, I've tested this on my local machine and it fixes the problem.

**Comment by bsidhom** [comment]
CC: @robertwb

**Comment by aaltay** [comment]
Test failures look unrelated.

**Pull request merged**
