### PR TITLE
Fix a bug that maxConnections is Short in config but read  back as Integer

### PR DESCRIPTION
**Pull request by olalamichelle**
Also added Unit Tests.

### CODE REVIEW

**Comment by bvolpato** [comment]
@Abacn Can you please take a look? You have more context here.

I can see that `maxConnections` is `FieldType.INT16`, but in the `JdbcIO` it's an Integer. Maybe we should make it `INT32` instead?

**Comment by bvolpato** [comment]
By the way, thanks for contributing @olalamichelle! I'm pinging Yi as he has a lot of context around this provider

**Comment by bvolpato** [comment]
There's a check failing for Spotless, please make sure you run `./gradlew spotlessApply` to fix formatting

**Comment by olalamichelle** [comment]
Done.

**Review by Abacn — APPROVED** [review]
Thanks. a previous fix done in #26480 still missing this particular code path (it fixed Python xlang jdbc schemaio but misses java schemaio itself)

**Comment by Abacn** [comment]
> @Abacn Can you please take a look? You have more context here.
> 
> I can see that `maxConnections` is `FieldType.INT16`, but in the `JdbcIO` it's an Integer. Maybe we should make it `INT32` instead?

Yeah, the bug indicates the usage of `INT32` is error prone -- however, change it to INT32 is equivalently error prone either. Many places need to be in sync

**Pull request merged**
