### PR TITLE
[BEAM-3785][SQL] Add support for arrays

### PR DESCRIPTION
**Pull request by akedin**
Add support for arrays, implement ARRAY creation and operations

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [ ] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by akedin** [comment]
R: @kennknowles @apilloud

**Comment by akedin** [comment]
retest this please

**Comment by akedin** [comment]
retest this please

**Comment by kennknowles** [comment]
:lgtm: good to have this support in place. I expect that we will want to look at the performance of basically running a syntax-tree interpreter on every expression. Not new in this PR, but seeing the functionality added made me think of it. That's a slow approach in a tight loop.

---

Reviewed 3 of 11 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4802#-:-L7GYokZVVYlXVewqo3g:b-oakol6)*

**Pull request merged**
