### PR TITLE
[Beam-3208] Add Distinct PTransform to mirror Java SDK 

### PR DESCRIPTION
**Pull request by ttanay**
The Java SDK introduced a `Distinct` PTransform to replace the `RemoveDuplicates` PTransform.
But, the Python SDK still had the `RemoveDuplicates` PTransform.
**A new `Distinct` PTransform was added which does the same thing as `RemoveDuplicates`. `RemoveDuplicates` is now an alias to the `Distinct` PTransform and is deprecated.**

JIRA Issue: https://issues.apache.org/jira/browse/BEAM-3208

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [X] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf). (N/A)

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](../.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by ttanay** [comment]
Run Portable_Python PreCommit

**Comment by ttanay** [comment]
Run RAT PreCommit

**Comment by ttanay** [comment]
Run Portable_Python PreCommit

**Comment by ttanay** [comment]
R: @pabloem @aaltay

**Comment by aaltay** [comment]
@ttanay is this ready for review? (There is still WIP in the title.)

**Comment by ttanay** [comment]
Thanks for checking this out @aaltay. 
I realized there is a better way to do the same. 
Hence, switched to WIP.
Need to make that change. Will let you know post that. :)

**Comment by ttanay** [comment]
Run Python_pytest PreCommit

**Comment by ttanay** [comment]
Python_pytest is failing with message:
>Task 'pytest' not found in root project 'beam'. Some candidates are: 'goTest', 'test'.

Did something change?

**Comment by pabloem** [comment]
Hi Tanay. The pytest thing showed up only today. I don't know where it came from, but it should be safe to ignore for now.

**Comment by aaltay** [comment]
@udim might have an idea about the pytest.

**Comment by udim** [comment]
Sorry, that is a test job of mine. It shouldn't be running automatically. :man_shrugging:

**Comment by ttanay** [comment]
> Hi Tanay. The pytest thing showed up only today. I don't know where it came from, but it should be safe to ignore for now.

Cool. :rocket: 

@aaltay @pabloem This is ready for review now.

**Comment by pabloem** [comment]
Hello Tanay. Happy to work on this PR together.

I like how you used the appropriate Beam deprecation marker for the old transform. That's great.

I believe that this new utility that you're adding is complex, and will be easy to misuse. Furthermore, the transform is quite simple. Would you consider using a different method to do this? (e.g. subclassing distinct, or having removeduplicates expand into distinct?) - we'd love to add the least complexity possible.

If you're in the ASF slack, feel free to ping me directly to chat.

**Comment by ttanay** [comment]
Hey @pabloem 
I made the changes. 
Thank you for helping out!

**Comment by pabloem** [comment]
Hi @ttanay - this is great. Would you please squash the commits so we can merge? - This LGTM

**Comment by ttanay** [comment]
> Hi @ttanay - this is great. Would you please squash the commits so we can merge? - This LGTM

@pabloem Should I change the deprecation version? It is currently "2.11" here:
https://github.com/apache/beam/pull/7918/files#diff-50f2e48308c52f12d0c907b571032195R206

**Comment by pabloem** [comment]
Since 2.11 is released already, yeah, I'd think you want to set it to 2.12

**Comment by ttanay** [comment]
> Since 2.11 is released already, yeah, I'd think you want to set it to 2.12

Cool. I'll make the change.

**Comment by ttanay** [comment]
@pabloem Squashed commits, changed deprecation version to "2.12":
https://github.com/apache/beam/pull/7918/files#diff-50f2e48308c52f12d0c907b571032195R206
PTAL

**Comment by pabloem** [comment]
Thanks Tanay!

**Pull request merged**
