### PR TITLE
[BEAM-5062] Add ability to provide custom S3ClientOptions

### PR DESCRIPTION
**Pull request by yuppie-flu**
This PR adds an ability to provide custom S3ClientOptions for creating required amazon s3 client.

------------------------

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by yuppie-flu** [comment]
retest this please

**Comment by iemejia** [comment]
Hi @yuppie-flu my total excuses for taking so long on the review of your PR. 
Thanks for the contribution, the code is ok for what it does, and it is definitely a nice contribution.

I am puzzled on how to solve the issue for the global case. I mean, if we expose all the options of S3 in S3Options we will have an unmanageable (and error-prone) API, I was wondering if we could better add a method like `withS3ClientFactory` where can parametrize the building of `AmazonS3Client`. That way we could cover not only the pathstyle case but any new change in the API because the user could always override and build the client differently if needed.

Would you be up to work on this solution better?, the general idea is to replace the `S3FileSystem` instantation by something that invokes this from `S3Options`:

```
  class S3ClientFactory implements DefaultValueFactory<AmazonS3ClientBuilder> {
    @Override
    public AmazonS3ClientBuilder create(PipelineOptions pipelineOptions) {
      S3Options options = pipelineOptions.as(S3Options.class);
      AmazonS3ClientBuilder builder =
              AmazonS3ClientBuilder.standard().withCredentials(options.getAwsCredentialsProvider());

      if (options.getClientConfiguration() != null) {
        builder = builder.withClientConfiguration(options.getClientConfiguration());
      }

      if (Strings.isNullOrEmpty(options.getAwsServiceEndpoint())) {
        builder = builder.withRegion(options.getAwsRegion());
      } else {
        builder =
                builder.withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration(options.getAwsServiceEndpoint(), options.getAwsRegion()));
      }

      return builder;
    }
  }
```

Of course end user could just reuse this class by using their own like this:
```
  options.withS3ClientFactory(new MyClientFactory());
```
and
```
  class MyClientFactory implements DefaultValueFactory<AmazonS3> {
    @Override
    public AmazonS3 create(PipelineOptions options) {
      AmazonS3ClientBuilder builder = new S3ClientFactory().create(options);
      builder.enablePathStyleAccess();
      return builder.build();
    }
  }
```

WDYT ?

**Comment by lukecwik** [comment]
@iemejia I like your suggestion, the most common options can be explicitly configurable and the remainder can fall under a single argument.

**Comment by yuppie-flu** [comment]
@iemejia Thank you for the detailed explanation. I totally agree with your idea, this way it will be a much cleaner solution.
I'll rework the PR.

**Comment by iemejia** [comment]
Excellent, thanks for understanding, feel free to improve my design if you find a cleaner way (I feel a bit uneasy with letting the Builder as the return type but given the 'particularities' of the S3 API seems like the most complete option.

**Comment by yuppie-flu** [comment]
Hey @iemejia 
I thought that a cleaner way would be to expose `S3ClientOptions` to client, not the whole `AmazonS3ClientBuilder`. You can check in this updated PR. However, it's impossible to pass `S3ClientOptions` to the builder as a whole object, so the PR includes "hack" method to pass them one-by-one.
I created an improvement issues for `aws-skd-java` library: https://github.com/aws/aws-sdk-java/issues/1736
When it's done, the hack can be removed.
What do you think?

**Comment by iemejia** [comment]
Hi, I see why `S3ClientOptions` seems cleaner, after looking at the comment in the linked ticket it seems the future of the S3 API is builder-oriented so maybe worth going back to the suggested track. WDYT ? (again not that I am super fan of letting the builder open but don't see a better trade-off).

**Comment by yuppie-flu** [comment]
@iemejia I don't have a strong opinion on that point. However I agree, that at least in current version of aws java library their API for such settings is builder-oriented. I just don't like that the builder is so huge and contains a lot of other stuff. Nevertheless it's irrelevant to apache-beam.
I reworked the PR to expose the whole builder. Could you please take a look?

**Comment by iemejia** [comment]
retest this please

**Comment by yuppie-flu** [comment]
retest this please

**Comment by yuppie-flu** [comment]
@iemejia Any updates? I rebased the PR to the latest master 4 days ago, tests passed.

**Comment by iemejia** [comment]
Hi sorry for the ridiculously long response time, I am checking this, mostly good to me, but want to do some extra things, but I will probably tackle those, will confirm you soon.

**Pull request merged**
