### PR TITLE
[BEAM-1257] Compressed text source emit an extra element when reading records

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

When reading from a text file with N rows. The textIO reader was reading an extra element if the file was compressed so the pCollection would have N+1 elements instead of N. This omits the last EOF that was being read and also adds unittests to prevent this in the future.

### CODE REVIEW

**Comment by sb2nov** [comment]
R: @chamikaramj PTAL

**Comment by chamikaramj** [comment]
LGTM

**Comment by chamikaramj** [comment]
Please create a JIRA and update the PR description.

**Comment by sb2nov** [comment]
Hmm i thought I had done that

**Comment by sb2nov** [comment]
R: @robertwb please merge

**Pull request closed without merging**
