### PR TITLE
[BEAM-8676] Upgrade gax-java 1.60.0 and grpc 1.32.2

### PR DESCRIPTION
**Pull request by veblush**
gRPC 1.32.2 has two important changes;
- Conscrypt-related optimization in the ALTS protocol
- BDP-estimator fix

R: @suztomo @lukecwik

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
#13075 is working on using the GCP libraries BOM within Beam to manage deps. It would be preferable if that change made it in first and we updated the libraries BOM version to one containing grpc 1.32.2 instead of doing these one off changes.

**Comment by veblush** [comment]
@lukecwik Oh having the bom would be nicer. As long as I can get this upgrade in Beam 2.26, I'm fine with both approaches. Do you think it will happen in Nov 4?

**Comment by lukecwik** [comment]
> @lukecwik Oh having the bom would be nicer. As long as I can get this upgrade in Beam 2.26, I'm fine with both approaches. Do you think it will happen in Nov 4?

@kileys

**Comment by kileys** [comment]
I should be able to get in the BOM changes before Nov 4th. Do you know when the libraries bom update will be released?

**Comment by lukecwik** [comment]
> I should be able to get in the BOM changes before Nov 4th. Do you know when the libraries bom update will be released?

12.1.0 has already been released containing the updated gRPC instance.

**Comment by kennknowles** [comment]
We can merge this while we are getting ready for the change to the BOM.

**Comment by kennknowles** [comment]
Run Java PreCommit

**Comment by kennknowles** [comment]
Run Python_PVR_Flink PreCommit

**Comment by kennknowles** [comment]
Run Portable_Python PreCommit

**Comment by kennknowles** [comment]
Some of the failures looked potentially real, in tests that have not flaked previously.

**Comment by veblush** [comment]
I guess `Java` test has real failures. (I don't think `Python_PVR_Flink` is relevant to this PR)

There are two tests failing. I guess this is coming from protobuf upgrading to  3.12 (from 3.11.1)
- [ProtoDynamicMessageSchemaTest.testNestedRowToProto](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/2812/testReport/junit/org.apache.beam.sdk.extensions.protobuf/ProtoDynamicMessageSchemaTest/testNestedRowToProto/)
- [ProtoDynamicMessageSchemaTest.testMapRowToProto](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/2812/testReport/junit/org.apache.beam.sdk.extensions.protobuf/ProtoDynamicMessageSchemaTest/testMapRowToProto/)

Because I don't think protobuf introduced actual breaking changes so I took a look at these test [code](https://github.com/apache/beam/blame/master/sdks/java/extensions/protobuf/src/test/java/org/apache/beam/sdk/extensions/protobuf/ProtoDynamicMessageSchemaTest.java#L202),

```
  @Test
  public void testNestedRowToProto() throws InvalidProtocolBufferException {
    ProtoDynamicMessageSchema schemaProvider = schemaFromDescriptor(Nested.getDescriptor());
    SerializableFunction<Row, DynamicMessage> fromRow = schemaProvider.getFromRowFunction();
    // equality doesn't work between dynamic messages and other,
    // so we compare string representation
    assertEquals(NESTED_PROTO.toString(), fromRow.apply(NESTED_ROW).toString());
  }
```

The error message is like below.
```
org.junit.ComparisonFailure: expected:<...sted_map {
  key: "k[1"
  value {
    primitive_double: 1.1
    primitive_float: 2.2
    primitive_int32: 32
    primitive_int64: 64
    primitive_uint32: 33
    primitive_uint64: 65
    primitive_sint32: 123
    primitive_sint64: 124
    primitive_fixed32: 30
    primitive_fixed64: 62
    primitive_sfixed32: 31
    primitive_sfixed64: 63
    primitive_bool: true
    primitive_string: "horsey"
    primitive_bytes: "\001\002\003\004"
  }
}
nested_map {
  key: "k2]"
  value {
    prim...> but was:<...sted_map {
  key: "k[2"
  value {
    primitive_double: 1.1
    primitive_float: 2.2
    primitive_int32: 32
    primitive_int64: 64
    primitive_uint32: 33
    primitive_uint64: 65
    primitive_sint32: 123
    primitive_sint64: 124
    primitive_fixed32: 30
    primitive_fixed64: 62
    primitive_sfixed32: 31
    primitive_sfixed64: 63
    primitive_bool: true
    primitive_string: "horsey"
    primitive_bytes: "\001\002\003\004"
  }
}
nested_map {
  key: "k1]"
  value {
    prim...>
```

From the code & output reading, it might be caused by using string comparison to compare two objects but chances are that two strings are not normalized, which could cause them to fail. (it's my wild guess)

@alexvanboxel, @reuvenlax
I want help from original author and review on https://github.com/apache/beam/pull/10502.

**Comment by kennknowles** [comment]
Note that the Python tests are Python-on-Flink so they do touch a number of Beam libraries. I think you are probably right that they are not actually affected, but do not let the name fool you.

**Comment by kennknowles** [comment]
Agree with your assessment. These tests are written in a fragile way.

**Comment by veblush** [comment]
@kennknowles I addressed the issue of the test. PTAL.

**Review by kennknowles — APPROVED** [review]
Thanks for hardening the test! The results are green and look good. The commit history is clean. Thanks a bunch!

**Pull request merged**
