### PR TITLE
[BEAM-2992] Removes codepaths for reading unsplit BigQuery sources

### PR DESCRIPTION
**Pull request by jkff**
R: @reuvenlax

### CODE REVIEW

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Alternatively R: @steveniemitz as author of #3894

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
Goddamit, flaky tests.

**Comment by jkff** [comment]
retest this please

**Comment by steveniemitz** [comment]
I rebased my PR off this ( #3894 ) and everything seems good!

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
@reuvenlax Did you mean to also approve this?

**Comment by reuvenlax** [comment]
lgtm

**Comment by jkff** [comment]
Thanks, merged; I found 1000+ more lines of code to remove and removed them.

**Pull request closed without merging**
