### PR TITLE
Add retry option to start_upload_ function

### PR DESCRIPTION
**Pull request by andreigurau**
Addresses #21065

This will allow retries when start_upload fails, which otherwise will prevent potential data loss.

Two things I'm a little uncertain about is the TODO comment previously mentioned to refactor this function to allow retries, and that the underlying library allows retries, but 1. Am I understanding it correctly that I can just refactor it by simply adding the `@retry.with_exponential_backoff` or is there something more? 2. I don't see the retry logic in the `Insert` functions, but maybe it's deeper than that? 

I'm a Python newbie so these things are not clear to me :/

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
Run PythonDocs PreCommit

**Comment by jrmccluskey** [comment]
I'm unfortunately not super familiar with the annotation system but it looks like this approach is pretty buttoned up from the GitHub Issue and the original Jira ticket. Pablo may have more insight

**Comment by Abacn** [comment]
I tend to think there was some reason retry did not apply there otherwise it is just a trivial annotation so why add a TODO there. 

This is a pretty low level code, the implementation of writing gcs file with same interface of a python file handle (open(s, 'w') as f; f.write(...)) The reason why there wasn't get retried is that the current implementation is not idempotent. A retry can cause a corrupted file. So currently it fails the bundle and make the whole file rewritten to gcs.

**Comment by andreigurau** [comment]
Closing this PR, since this doesn't seem to be the root cause of the bug I was trying to fix

**Pull request closed without merging**
