### PR TITLE
[BEAM-3109] Add an element batching transform.

### PR DESCRIPTION
**Pull request by aaltay**
Cherry picking: d226c7679b9d94a40553609f31ecbfba72559e8a from https://github.com/apache/beam/pull/3971 

R: @reuvenlax 
cc: @robertwb

### CODE REVIEW

**Comment by robertwb** [comment]
LGTM

The failures are unrelated: java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer

Jenkins: retest this please

**Comment by aaltay** [comment]
I see the same error in https://github.com/apache/beam/pull/3993. There is something wrong with python jenkins tests. Retesting does not seem to help.

**Comment by reuvenlax** [comment]
retest this please.

**Comment by reuvenlax** [comment]
retest this please.

**Comment by kennknowles** [comment]
Since this PR seems to have a good number of people hitting it, on Friday this started and I filed https://issues.apache.org/jira/browse/INFRA-15393. I have now modified most jobs to avoid node `beam8`. On Monday I will jump into infra hipchat (or anyone could) and get some action on the issue, which is presumably pretty easy to resolve.

**Comment by reuvenlax** [comment]
Failure in TikaIO is unrelated. This is ok to self-merge.

**Pull request merged**
