### PR TITLE
[BEAM-1737] Interpreting a Single-output ParDo as a Multi-output ParDo with a single output causes serialization failuresremove use of EvaluationContext in DStream lambda, it is not serializ…

### PR DESCRIPTION
**Pull request by amitsela**
…able and also redundant in this

case.

Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by amitsela** [comment]
R: @tgroh

**Comment by amitsela** [comment]
Run Spark ValidatesRunner

**Comment by amitsela** [comment]
E2E test that failed is Dataflow, so unrelated.

**Comment by amitsela** [comment]
What do you mean by "split translation" ?

**Comment by tgroh** [comment]
In `StreamingTransformTranslator#multiDo()` there's a branch for `ParDos` with/without side outputs, i.e.
`if (transform.getSideOutputTags().size() == 0)...`

I left it in there due to this serialization issue. Can that branch be removed and go through a single translation? is it worth doing?

I believe there's an identical branch in the batch translator.

**Comment by amitsela** [comment]
I'll take a look in the next couple of days, np.

**Comment by amitsela** [comment]
R: @aviemzur or @staslev 
CC: @tgroh

**Comment by amitsela** [comment]
Run Spark ValidatesRunner

**Comment by amitsela** [comment]
Run Spark ValidatesRunner

**Comment by staslev** [comment]
I think it looks good, but since I'm not really familiar with the scope, a few questions that may help me understand the change better:
1. Why were the two cases separated into an `if-else` in the first place? A comment from the pre-change era indicates it was a performance consideration, is this the case here?
2. This section is identically changed in both streaming and batch translators, right? (while it would be nice to remove the duplication here, I'm not hinting it should be done as part of this commit, just making sure I don't miss anything since they look very similar)
3. Did you have a chance to test this on an actual cluster?

**Comment by amitsela** [comment]
> Why were the two cases separated into an if-else in the first place? A comment from the pre-change era indicates it was a performance consideration, is this the case here?

The SDK used to have two different `PTransform`s, `ParDo.Bound` and `ParDo.BoundMulti` and so the runner had two separate translations.
> This section is identically changed in both streaming and batch translators, right? (while it would be nice to remove the duplication here, I'm not hinting it should be done as part of this commit, just making sure I don't miss anything since they look very similar)

Yes, this is something we unfortunately can escape because Spark uses different APIs for batch and streaming - the `RDD` API and the `DStream` API.
> Did you have a chance to test this on an actual cluster?

No, there's nothing new here in terms of the Spark graph.. no new/different usage.

**Comment by staslev** [comment]
ok, then LGTM.

**Pull request closed without merging**
