### PR TITLE
Add an example for `Distinct` PTransform

### PR DESCRIPTION
**Pull request by shhivam**
I noticed that there was no example for `Distinct` Java PTransform in the docs.

This PR changes that -- We add an example for `Distinct` Java PTransform in the docs.

Addresses some part of [BEAM-7703](https://issues.apache.org/jira/browse/BEAM-7703).

About choosing **Reviewers:** Not sure who to assign as a reviewer because I don't know who works on beam

------------------------

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by shhivam** [comment]
R: @pabloem @jrmccluskey

**Comment by pabloem** [comment]
hi thanks for the contribution! I'll rerun the tests so I can see the staged outcome

**Comment by pabloem** [comment]
LGTM thanks!

**Comment by shhivam** [comment]
Thanks @pabloem !

**Pull request merged**
