### PR TITLE
[BEAM-11693]  Update formatting. Fix email template

### PR DESCRIPTION
**Pull request by lostluck**
Adjust the formatting of the markdown in the release guide to be 1 sentence per line, rather than mix of that, 1 paragraph per line, and 80 char formatted. This makes reviewing later changes simpler, as new sentences appear as new lines, changes and removals as one would expect.

Also fixes the email template, which was broken by the explict more summary tag.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @pabloem @chamikaramj 

At time of review request, the precommits are still pending. I'll fix those (like whitespace) afterwards.

**Comment by ibzib** [comment]
> Adjust the formatting of the markdown in the release guide to be 1 sentence per line, rather than mix of that, 1 paragraph per line, and 80 char formatted. This makes reviewing later changes simpler, as new sentences appear as new lines, changes and removals as one would expect.

The present inconsistency is annoying, but IMO putting each sentence on a new line decreases the readability of the source in many cases. I'd favor an 80 or 100 character limit since it keeps the paragraph structure visibly intact in the source, and most importantly a computer can enforce it.

In any case, there should be a website-wide consensus on this, and it should be checked automatically. Otherwise, it will take a Sisyphean effort to maintain without much benefit.

**Comment by lostluck** [comment]
While i agree in principle, I'm of the mind that since I'm going to be making the next half dozen changes to this one markdown file, that at the very least it should be more consistent than it is with itself.

A sentence per line is far less manual work than maintaining specific character counts per line. Otherwise each change means reflowing the rest of the paragraph.
Unless we can agree on a markdown formatter that we can *just run* from gradle. Given we have a whitepace lint that doesn't actually fix the problem, I'm inclined to believe we don't have one such thing at present.

Further, when i run the whitepace linter it operates even on the git submodules which we likely don't want to get in the habit of formatting.

Besides: the common case is not reading the source, it's reading the rendered site which handles the flows properly anyway. Qhen editing, one would commonly be in an editor which can handle the user's wrapping preference. Finally, if one is searching for a specific line to change, as long as your don't search on sentence breaks, you're easily able to Ctrl-F for the specific line. With arbitrarily broken up text (like max 80 char lines) to character counts, you don't know if you can't find a snippet due to a typo, or due to a line break in the text your looking for.

Your preference is noted but I strongly disagree with the sysyphean effort proposed by manually maintaining 80 char flows without automation.
That we don't currently impose a standard still means that imposing one consistently for this single file is a dramatic improvement over it's current state of 3-4 different approaches.

**Comment by ibzib** [comment]
> Given we have a whitepace lint that doesn't actually fix the problem, I'm inclined to believe we don't have one such thing at present.

As far as I know, you're correct that there's no formatter right now. I agree that having a whitespace linter without an autoformatter is less than helpful since it adds to the manual maintenance burden without providing much benefit.

> Your preference is noted but I strongly disagree with the sysyphean effort proposed by manually maintaining 80 char flows without automation.

To be clear, I'm proposing we don't set any standard until we can both enforce it with a precommit check and fix violations with an automatic formatter. This PR is fine, but I think we can agree that manual maintenance is unsustainable.

**Comment by lostluck** [comment]
> To be clear, I'm proposing we don't set any standard until we can both enforce it with a precommit check and fix violations with an automatic formatter. This PR is fine, but I think we can agree that manual maintenance is unsustainable.

100% agree. Hence my preference to a sentence per line while there is no defined standard, or auto-formatter. Very minimal effort to maintain, among the other benefits I ranted about above.

**Comment by pabloem** [comment]
Content LGTM. I'll let y'all resolve the discussion with regards to formatting.

**Review by ibzib — APPROVED** [review]
LGTM

**Comment by lostluck** [comment]
Thanks! I'll get the next stage of this ready.

**Pull request merged**
