### PR TITLE
[BEAM-9573][release-2.20] Correct computing of watermark hold for timer output timestamp

### PR DESCRIPTION
**Pull request by mxm**
#### [BEAM-9573] Correct computing of watermark hold for timer output timestamp

With the introduction of timer output timestamps, a new watermark hold had been
added to the Flink Runner. The watermark computation works on the keyed state
backend which computes a key-scoped watermark hold and not the desired
operator-wide watermark hold.

Computation: https://github.com/apache/beam/blob/b564239081e9351c56fb0e7d263495b95dd3f8f3/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1140

Key-scoped state: https://github.com/apache/beam/blob/b564239081e9351c56fb0e7d263495b95dd3f8f3/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1130

The solution is to iterate over all available state backend keys.

#### [BEAM-9566] Mitigate performance issue for output timestamp watermark holds

Benchmarks have shown that the minimum output timestamp computation over all
timers is very expensive because we have to iterate over all keys in the state
backend. This is especially costly for RocksDB.

This change introduces a cache which stores and updates the timer output
timestamps such that the minimum can be retrieved efficiently.

Only at startup the cache is populated from the state backend. This should
give us roughly the same performance as before introducing output timestamps for
timers.

The following have been run with RocksDB:

Nexmark Query 12 before:
```
  Conf  Runtime(sec)    (Baseline)  Events(/sec)    (Baseline)       Results    (Baseline)
  0000         105.3                       950.0                        9039
  0001           2.2                      4466.3                         196
```

Nexmark query 12 with this change:
```
Performance:
  Conf  Runtime(sec)    (Baseline)  Events(/sec)    (Baseline)       Results    (Baseline)
  0000           6.0                     16730.8                        1919
  0001           0.8                     12391.6                         196
```

For more details please see BEAM-9566.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by amaliujia** [comment]
LGTM after necessary tests pass

**Comment by amaliujia** [comment]
@mxm any additional tests should run?

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
I've already tested those, but running them again to make sure.

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by mxm** [comment]
I have backported both fixes now: BEAM-9573 and BEAM-9566 as they really only make sense together. One fixes a bug, the other one a performance regression.

**Comment by amaliujia** [comment]
Sounds good to me. Thanks!

**Comment by mxm** [comment]
Error prone errors in the build:

```
20:42:09 * What went wrong:
20:42:09 Execution failed for task ':model:pipeline:compileJava'.
20:42:09 > Could not resolve all files for configuration ':model:pipeline:errorprone'.
20:42:09    > Could not resolve com.google.errorprone:error_prone_core:latest.release.
20:42:09      Required by:
20:42:09          project :model:pipeline
20:42:09       > Could not resolve com.google.errorprone:error_prone_core:2.3.4-SNAPSHOT.
20:42:09          > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/staging/com/google/errorprone/error_prone_core/2.3.4-SNAPSHOT/maven-metadata.xml.
20:42:09             > Could not HEAD 'https://oss.sonatype.org/content/repositories/staging/com/google/errorprone/error_prone_core/2.3.4-SNAPSHOT/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
20:42:09 
```

**Comment by mxm** [comment]
Run Portable_Python PreCommit

**Comment by mxm** [comment]
Run Java PreCommit

**Comment by mxm** [comment]
Run Flink Runner Nexmark Tests

**Comment by mxm** [comment]
Run Flink ValidatesRunner

**Comment by amaliujia** [comment]
Great! all tests have pass!

**Comment by mxm** [comment]
Awesome. Thanks for the patience!

**Pull request merged**
