### PR TITLE
(AWS S3 FS) Fix performance issue of S3 filesystem when reading large files

### LINKED ISSUE #25991: [Bug]: Performance degradation of S3 Filesystem when working with large splittable files when closed before all data is consumed.
### What happened?

Beam java pipeline encounter severe performance issues on all beam versions later than 2.30.0. After troubleshooting, we identified that enhancement done under BEAM-12329 seems root cause for the performance degradation.
Note that pipeline runs fine for small datasets of few MBs but are significant slower for lager datasets ~10GBs+.
It appears that on version 2.30 and lower, amazon-web-service module was not draining the input stream and program complained about "Not all bytes were read from .... " but as we know in this case system is overreacting and making  invalid assumption about remaining data and cost of read vs abort and reconnect.
In later version post 2.30.0, when input stream is drained when close function is called and subsequent requests to read remaining data needs to reconnect and seek to the position which is significantly slower in our case and pipeline keeps running for hours as against to a few minutes on version 2.30 and lower. 
Do you have any suggestion on how to achieve the same performance ? I have tried both amazon-web-services and amazon-web-services2 on all versions after 2.30 and all results same poor performance.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by mosche**
Fix performance issue of S3 filesystem when reading large files (fixes #25991)

Draining the S3 input stream is a bad idea as we might not read the entire file. Particularly for large files that get split (and [processed in parallel) this quickly explodes the amount of data that needs to be transferred.

As long as the remaining unread data fits into the TCP buffer this will continue draining the stream.
This is beneficial as the HTTP connection can be reused.

Otherwise the stream / connection is aborted, which involves some significant overhead.

This must be done when closing, but also when moving the channel to a new position.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @aromanenko-dev 
cc @vatanrathi

**Review by aromanenko-dev — APPROVED** [review]
LGTM
Any chances to have a regression (integration) test for this case?

**Comment by mosche** [comment]
There is a integration test for S3 FS. But this issue is really only noticeable with very large files which isn't feasible for testing.

**Comment by aromanenko-dev** [comment]
Well, I'd say that this is a good case for exactly IT since they are not running all the time. 

Anyway, it's not a blocker for now but I hope it fixes the underneath problem. @vatanrathi would you have a chance to test this fix on your side?

**Comment by mosche** [comment]
But what do you want to assert on @aromanenko-dev? This would be notoriously unreliable....
You could only record metrics and detect regressions that way.

**Comment by mosche** [comment]
It was fairly easy to reproduce the issue of @vatanrathi locally and verify this patch.

**Comment by vatanrathi** [comment]
I will be able to run more extensive tests if a test package can be made available to me.

**Comment by aromanenko-dev** [comment]
@mosche 
> But what do you want to assert on @aromanenko-dev? This would be notoriously unreliable....
> You could only record metrics and detect regressions that way.

Well, at least to make sure that it reads a quite large file from S3 with affordable amount of time by running a Beam pipeline  (since it was a cause of initial problem).

@vatanrathi Thanks for testing!

**Pull request merged**
