### PR TITLE
Deprecate runner support for Spark 2.4 (closes #22094)

### LINKED ISSUE #22094: [Task]: Deprecate runner for Spark v2
### What needs to happen?

It is time to deprecate the Spark 2 runner in Beam, see this [discussion](https://lists.apache.org/thread/opfhg3xjb9nptv878sygwj9gjx38rmco). Databricks is also dropping support for runtimes using Spark 2 by the end of June 2022.

With that the Spark 3 runner will become the default and only Spark runner.

### Issue Priority

Priority: 2

### Issue Component

Component: runner-spark

### PR DESCRIPTION
**Pull request by mosche**
It is time to deprecate the Spark 2 runner in Beam, see this [discussion](https://lists.apache.org/thread/opfhg3xjb9nptv878sygwj9gjx38rmco). Databricks is also dropping support for runtimes using Spark 2 by the end of June 2022.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
R: @echauchot 
R: @aromanenko-dev 
R: @jbonofre

**Comment by aromanenko-dev** [comment]
CC: @iemejia

**Review by echauchot — APPROVED** [review]
Thanks Moritz !

**Comment by mosche** [comment]
Hmm, having seen the maven download stats, I'm a bit skeptical if Spark 2.4 should be deprecated in fact.
The numbers of the last month:

beam-runners-spark-3
2.30.0 22
2.31.0 22
2.32.0 16
2.33.0 18
2.34.0 17
2.35.0 47
2.36.0 160
2.37.0 17
2.38.0 114
2.39.0 23
All 472
 
beam-runners-spark
2.30.0 26
2.31.0 24
2.32.0 69
2.33.0 403
2.34.0 352
2.35.0 1543
2.36.0 50
2.37.0 19
2.38.0 420
2.39.0 86
All 5224

**Pull request merged**
