### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by tvalentyn**
Also allowlist google calendar.

follow up for #30394

### CODE REVIEW

**Comment by tvalentyn** [comment]
R: @svetakvsundhar

**Comment by svetakvsundhar** [comment]
Ah, I think its addressing the below; sounds good. 
Screenshot 2024-02-23 at 12 37 55 PM

**Review by svetakvsundhar — CHANGES_REQUESTED** [review]
We should do Twitter as well based on the rendered image above.

**Comment by tvalentyn** [comment]
actually removing these frames may be a more appropriate course of action.

**Pull request closed without merging**
