### PR TITLE
[BEAM-12164]: Parses change streams fields as json / strings

### PR DESCRIPTION
**Pull request by thiagotnunes**
The backend is migrating from returning strings for certain fields to json. We need to change the parsing logic to accommodate for both until the migration is completed.

### CODE REVIEW

**Comment by thiagotnunes** [comment]
retest this please

**Comment by thiagotnunes** [comment]
Presubmit failures are unrelated to this PR

**Comment by thiagotnunes** [comment]
R: @pabloem

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by pabloem** [comment]
this LGTM. Thanks @thiagotnunes

**Comment by pabloem** [comment]
Run Java PreCommit

**Comment by thiagotnunes** [comment]
Run Java PostCommit

**Pull request merged**
