### PR TITLE
Enable managed service in Python tests

### PR DESCRIPTION
**Pull request by ahmedabu98**

### CODE REVIEW

**Comment by damccorm** [comment]
Looks like the test failure is still there/the file is not getting auto-created

**Comment by ahmedabu98** [comment]
Yep the test relies on the connector to create the table dynamically. This feature is present in 2.61.0 (and HEAD), but Managed Iceberg version is pinned at 2.60.0.

We can wait and rerun the tests when 2.61.0 is released and Managed Iceberg version is bumped accordingly.

**Review by damccorm — APPROVED** [review]
Got it - that makes sense. Approving conditional on us getting that green signal

**Comment by ahmedabu98** [comment]
The service config version was bumped and tests are green now! will merge

**Comment by damccorm** [comment]
Awesome - thanks!

**Pull request merged**
