### PR TITLE
[BEAM-9013] TestStream fix for DataflowRunner

### PR DESCRIPTION
**Pull request by rohdesamuel**
The DataflowRunner relies on the old implementation of the TestStream with only a single output and different watermark controlling mechanices. This adds the _DeprecatedSingleOutputTestStream which allows for any more development of the TestStream to occur in the _TestStream class without breaking backwards compatibility with Dataflow.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
Is there a test that verifies TestStream on DataflowRunner? It seems like this should've been caught in a PreCommit or PostCommit

**Comment by rohdesamuel** [comment]
> Is there a test that verifies TestStream on DataflowRunner? It seems like this should've been caught in a PreCommit or PostCommit

I guess not. As you said, it should have been caught in a Pre/PostCommit.

**Comment by TheNeuralBit** [comment]
Would it be possible to make some or all of the tests pipelines in https://github.com/apache/beam/blob/master/sdks/python/apache_beam/testing/test_stream_test.py, run on Dataflow? 

I guess this is tricky since we don't want it to run on all runners, just Dataflow and DirectRunner, but maybe you can do something like this: https://github.com/kamilwu/beam/blob/82db02dc68ffac074435bd0142dda900d7bfbec5/sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py#L141
https://github.com/kamilwu/beam/blob/82db02dc68ffac074435bd0142dda900d7bfbec5/sdks/python/apache_beam/io/gcp/bigquery_read_it_test.py#L53-L66

**Comment by robertwb** [comment]
Also, I thought the intent was to make all the `_WatermarkControllerEvaluator`, etc. an implementation detail (e.g. in the Direct runner) and let TestStream remain a primitive. It seems the right thing to do is keep TestStream a primitive and add Overrides for the Direct runner rather than add overrides to "undo" the DirectRunner implementation for the DataflowRunner. (I suspect this would also break Flink and any other runners that implemented TestStream the old way.)

**Comment by rohdesamuel** [comment]
Run Python PreCommit

**Comment by rohdesamuel** [comment]
> Also, I thought the intent was to make all the `_WatermarkControllerEvaluator`, etc. an implementation detail (e.g. in the Direct runner) and let TestStream remain a primitive. It seems the right thing to do is keep TestStream a primitive and add Overrides for the Direct runner rather than add overrides to "undo" the DirectRunner implementation for the DataflowRunner. (I suspect this would also break Flink and any other runners that implemented TestStream the old way.)

I moved the the multi-output TestStream implementation to the DirectRunner

**Comment by aaltay** [comment]
LGTM. We can merge it once test pass on the last commit.

**Comment by iemejia** [comment]
Should this one be cherry-picked into 2.18 branch or can we just move the ticket to 2.19?

**Comment by aaltay** [comment]
My suggestion: Mark this as a known issue and move the ticket to 2.19.

Because, this only impacts TestStream on DataflowRunner and TestStream on DataflowRunner does not work/not supported currently anyway. So it should not impact end users.

@rohdesamuel @robertwb is that accurate?

**Pull request merged**
