### PR TITLE
[BEAM-10114] Pub/Sub Lite getSplitBacklog implementation

### PR DESCRIPTION
**Pull request by palmere-google**
Add an implementation of getSplitBacklog to the Pub/Sub Lite Unbounded Reader. This
implementation depends on the pub/sub lite TopicStats api.

R: @dpcollins-google 

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by aaltay** [comment]
Is this still work in progress? Do you need help?

**Comment by aaltay** [comment]
Hey @palmere-google - Let us know if you need help here. (/cc @chamikaramj )

**Comment by palmere-google** [comment]
> Hey @palmere-google - Let us know if you need help here. (/cc @chamikaramj )
Sorry, I was out for a bit. This should be ready for review now :) Thanks for checking!

**Comment by aaltay** [comment]
@chamikaramj adding you as a reviewer. If it makes sense, please delegate to someone more familiar with dataflow streaming.

**Comment by dpcollins-google** [comment]
LGTM from the Pub/Sub lite perspective

**Comment by chamikaramj** [comment]
Thanks. Can you update the title of the PR with a JIRA ?

**Comment by chamikaramj** [comment]
Retest this please

**Comment by chamikaramj** [comment]
Please fix the failure which seems to be related.




sdks:java:io:google-cloud-platform:compileJava FAILED |  
  | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderSettings.java:67: error: [argument.type.incompatible] incompatible argument for parameter t of toCanonical. |  
  | throw ExtractStatus.toCanonical(e.getCause()); |  
  | ^ |  
  | found   : @Initialized @Nullable Throwable |  
  | required: @Initialized @NonNull Throwable |  
  | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderSettings.java:82: error: [dereference.of.nullable] dereference of possibly-null reference stub() |  
  | builder.setStub(stub().get()); |  
  | ^ |  
  | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderImpl.java:69: error: [dereference.of.nullable] dereference of possibly-null reference response |  
  | messageBytes += response.getMessageBytes(); |  
  | ^ |  
  | Note: Some input files use or override a deprecated API. |  
  | Note: Recompile with -Xlint:deprecation for details. |  
  | Note: Some input files use unchecked or unsafe operations. |  
  | Note: Recompile with -Xlint:unchecked for details. |  
  | 3 errors

**Comment by palmere-google** [comment]
> Please fix the failure which seems to be related.
I'm having difficulty reproducing these on my machine. They all seem to be related to nullness checks by the checker framework, but for some reason they don't happen for me

I'm running

./gradlew -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home :sdks:java:io:google-cloud-platform:compileJava

> 
> sdks:java:io:google-cloud-platform:compileJava FAILED |  
>   | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderSettings.java:67: error: [argument.type.incompatible] incompatible argument for parameter t of toCanonical. |  
>   | throw ExtractStatus.toCanonical(e.getCause()); |  
>   | ^ |  
>   | found : @initialized @nullable Throwable |  
>   | required: @initialized @nonnull Throwable |  
ExtractsStatus.toCanonical accepts a null throwable here, but I'm not sure how to convince the checker framework of this, so I suppressed the warning.

>   | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderSettings.java:82: error: [dereference.of.nullable] dereference of possibly-null reference stub() |  
>   | builder.setStub(stub().get()); |  
>   | ^ |  
Here I think assigning the result of stub() to a temporary should help the checker understand that we are making a null check.

>   | /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsublite/TopicBacklogReaderImpl.java:69: error: [dereference.of.nullable] dereference of possibly-null reference response |  
>   | messageBytes += response.getMessageBytes(); |  
>   | ^ |  
>   | Note: Some input files use or override a deprecated API. |  
>   | Note: Recompile with -Xlint:deprecation for details. |  
>   | Note: Some input files use unchecked or unsafe operations. |  
>   | Note: Recompile with -Xlint:unchecked for details. |  
>   | 3 errors
I'm pretty confident that our rpc stubs can never return a null response, so I suppressed this rather than performing a null check.

**Comment by palmere-google** [comment]
BEAM-10114

> Thanks. Can you update the title of the PR with a JIRA ?

Added an issue to the title

**Pull request merged**
