### PR TITLE
[BEAM-6326] Relax test assumption for PAssertTest#testWindowedIsEqualTo

### PR DESCRIPTION
**Pull request by mxm**
The Flink Runner returns a Pane which is early because it just assigns the
Windows to the test values. At this point without further transformations,
e.g. GroupByKey, it does not know that this is the only Pane.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
This doesn't seem to be the right way, at least the DirectRunner behaves differently. Will have to materialize this correctly for the side input then.

**Comment by mxm** [comment]
Actually this does not depend on side inputs, but I'm even seeing this with `PAssert.that` which does not use side inputs. The following works, note the comment for the changes:

```
    PCollection<Integer> pcollection =
        p
            .apply(
                Create.timestamped(
                    TimestampedValue.of(43, new Instant(250L)),
                    TimestampedValue.of(22, new Instant(-250L))))
            .apply(Window.into(FixedWindows.of(Duration.millis(500L))))
            // CHANGES: Add GroupByKey and re-output the results
            .apply(WithKeys.of(0)).apply(GroupByKey.create())
            .apply(ParDo.of(new DoFn<KV<Integer, Iterable<Integer>>, Integer>() {
              @ProcessElement
              public void processElement(ProcessContext ctxt) {
                for (Integer integer : ctxt.element().getValue()) {
                  ctxt.output(integer);
                }
              }
            }));

    PAssert.thatSingleton(pcollection)
        .inOnTimePane(new IntervalWindow(new Instant(0L), new Instant(500L)))
        .isEqualTo(43);
    PAssert.thatSingleton(pcollection)
        .inOnTimePane(new IntervalWindow(new Instant(-500L), new Instant(0L)))
        .isEqualTo(22);
```

The existing code on the other hand, always returns `EARLY` panes. The problem seems to be inside the windowing logic of the Fn Harness.

@robertwb Any opinions on how we should resolve this?

**Comment by robertwb** [comment]
It's unclear what the semantics of panes should be right after windowing, but it seems like a good idea to preserve it, and a Create.timestamped() would give things in the on time pane.

**Comment by mxm** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by mxm** [comment]
Test failure gone, with one more unrelated test to fix: https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming_PR/3/testReport/

**Comment by mxm** [comment]
Unrelated Elasticsearch PreCommit failures: https://builds.apache.org/job/beam_PreCommit_Java_Commit/3451/

**Pull request merged**
