### PR TITLE
Add a StatefulDoFn test that sets event time timer within allowed lat…

### PR DESCRIPTION
**Pull request by y1chi**
…eness

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by y1chi** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
Are there any suites expected to fail?

**Review by kennknowles — APPROVED** [review]

**Comment by aaltay** [comment]
Could this be merged?

**Comment by kennknowles** [comment]
I believe this is reproducing a bug, so that some (maybe all) runners ValidatesRunner suites would go red in postcommit. So I think please choose some suites to run and/or sickbay this case from those runners where it doesn't work yet.

**Comment by y1chi** [comment]
Run Java Dataflow V2 ValidatesRunner

**Comment by y1chi** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by y1chi** [comment]
Run Dataflow Streaming ValidatesRunner

**Comment by y1chi** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Pull request merged**
