### PR TITLE
[BEAM-14452] Beam compression format extension with Hadoop 4MC file format. 

### PR DESCRIPTION
**Pull request by meetdestiny**
The 4MC (4 More Compression) is a library for hadoop providing a new splittable compressed file format (4mc) which lets you leverage the power of LZ4 and ZSTD algorithms.
It differs from other compressed file formats in a way that the output files can be read using HIVE partitioning. This PR allows Dataflow to write files in 4MC compression format. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by chamikaramj** [comment]
Thanks. Could you follow instructions in Beam contribution guide (for example, attach a Jira): https://beam.apache.org/contribute/get-started-contributing/

Also, could you add unit and integration tests to make sure that this works ?

**Comment by chamikaramj** [comment]
BTW IIUC correctly, 4mc is a file format not just a compression format. Are you able to use this PR with existing Beam I/O connectors for various file formats (for example, FileIO and AvroIO). It's possible there's a misunderstanding about how Beam file-based I/O works.

**Comment by meetdestiny** [comment]
Agree. 4mc is a file format but the codec worked for us using TextIO. 

This is a sample pipeline which works with 4mc file format. 

PCollection<String> collection =  p
                    .apply("Read " + topic + " Messages", PubsubIO.readStrings().fromTopic(topicName))
                    .apply(Window.into(FixedWindows.of(Duration.standardMinutes(1))));
            collection.apply(FileIO.<String, String>writeDynamic().withNumShards(1)
                    .by((SerializableFunction<String, String>) input -> input)
                    .via(TextIO.sink()).withCompression(Compression.MC4).to(options.getBucket()+"/output/")
                    .withDestinationCoder(StringUtf8Coder.of())
                    .withNaming( new SerializableFunction<String, FileNaming> () {

                        @Override
                        public FileNaming apply(String input) {
                            return (window, pane, numShards, shardIndex, compression) -> {
                                return input.toString() +".4mc";
                            };
                        }

                    }));

**Comment by meetdestiny** [comment]
Also, 

> Thanks. Could you follow instructions in Beam contribution guide (for example, attach a Jira): https://beam.apache.org/contribute/get-started-contributing/
> 

https://issues.apache.org/jira/browse/BEAM-14452

**Comment by chamikaramj** [comment]
Still unclear to me how this work. Do 4mc encoded text files written by TextIO somehow end up being same as 4mc files ? If so, that sounds like by accident for me and probably we should develop a 4mc source/sink instead.

**Comment by chamikaramj** [comment]
It might be good to write a short design doc on this and share with Beam dev@.

**Comment by aromanenko-dev** [comment]
Agree with @chamikaramj , a brief design doc would be very appreciated.

**Comment by chamikaramj** [comment]
To clarify, next steps are.

(1) A brief design doc on why this approach works for reading/writing 4mc files (or propose an alternative approach)
(2) Make sure that the PR passes current tests
(3) Add new unit tests related to reading and writing with 4mc compression. See [1] and [2] for example tests.
(4) Add an integration test (optional)

[1] https://github.com/apache/beam/blob/master/sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java
[2] https://github.com/apache/beam/blob/master/sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java

**Comment by aaltay** [comment]
@meetdestiny - Could you please follow up on the mentioned next steps?

**Pull request closed without merging**
