### PR TITLE
[BEAM-10247] Pin google-api-core to 1.17.0

### PR DESCRIPTION
**Pull request by davidyan74**
Pin google-api-core to 1.17.0, because otherwise the pulled version 1.20.0 is incompatible with the pinned grpc.

R: @aaltay 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Samza | Spark
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by aaltay** [comment]
This looks good to me.

@tvalentyn - do we need to pin anything else related to this? (setup.py?)

**Comment by davidyan74** [comment]
FYI, this fixes the same issue described here: https://github.com/googleapis/python-api-core/issues/40

If we have grpcio < 1.29.0 with google-api-core > 1.17.0, I'd imagine a lot of GCP IOs would break.

**Comment by davidyan74** [comment]
To be safe, I think we should also pin google-api-core to 1.17.0 in setup.py, unless we are sure we are ready to require grpcio >= 1.29.0.

**Comment by aaltay** [comment]
I think we can consider updating grpcio as well. We will need to to do it eventually anyway.

Casting a wide net about grpcio. Any concerns about upgrading grpcio to 1.29.0 or later in python? (@chamikaramj @lukecwik @robertwb)

**Comment by tvalentyn** [comment]
I thinks setup.py should be as flexible as possible and as reasonable, it already does not include an upper bound on grpc. So we can either upgrade grpc in containers or downgrade the google-api-core.

Given the broad requirement in setup.py, I would prefer if we upgrade grpc instead, see: https://github.com/apache/beam/blob/63cc13ae0d135c9966fca3b87f34e06d142e412d/sdks/python/setup.py#L154

**Comment by tvalentyn** [comment]
cc: @ihji FYI in case Dataflow containers also need an update.

**Comment by aaltay** [comment]
> I thinks setup.py should be as flexible as possible and as reasonable, it already does not include an upper bound on grpc until next major version. So in containers we can either upgrade grpc or downgrade the google-api-core.
> 
> Given the broad requirement in setup.py, I would prefer if we upgrade grpc instead, see:
> 
> https://github.com/apache/beam/blob/63cc13ae0d135c9966fca3b87f34e06d142e412d/sdks/python/setup.py#L154

SGTM. Let's update and see if there will be any test issues.

**Comment by davidyan74** [comment]
I'll add the grpc version requirement to both setup.py and base_image_requirements.txt.
BTW, the tests failed because of this:

18:13:16 ERROR: Failure: SyntaxError (Non-ASCII character '\xc3' in file /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/build/gradleenv/-194514014/local/lib/python2.7/site-packages/rsa/key.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (key.py, line 1))

**Comment by tvalentyn** [comment]
Run  Python 2 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
I don't know why Jenkins lags. Tests are not triggered: https://builds.apache.org/job/beam_PostCommit_Python37_PR/.
PR LGTM but we need to test before merge.

**Comment by aaltay** [comment]
retest this please

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
Run Python 2 PostCommit

**Comment by davidyan74** [comment]
Looks like dependency check broke for python 2. Since python 2 is deprecated, I'm going to restrict the changes for just python 3.
```
10:09:10 google-auth 1.17.2 has requirement rsa<4.1; python_version < "3", but you have rsa 4.5.
10:09:10 ERROR: InvocationError for command /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/test-suites/tox/py2/build/srcs/sdks/python/target/.tox-py27-cloud/py27-cloud/bin/pip check (exited with code 1)
```

**Comment by tvalentyn** [comment]
David, can you add rsa<4.1; python_version < "3" to test dependencies to unblock this?

**Comment by davidyan74** [comment]
Sure, will do so shortly.

**Comment by tvalentyn** [comment]
Thank you. Test deps are declared here: https://github.com/apache/beam/blob/c328d2ac0f805cdfd9de8ffa513c611051549f65/sdks/python/setup.py#L181.
Sample syntax: https://github.com/apache/beam/blob/c328d2ac0f805cdfd9de8ffa513c611051549f65/sdks/python/setup.py#L151

**Comment by tvalentyn** [comment]
retest this please

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Can't get Jenkins to run.. Also https://github.com/googleapis/google-auth-library-python/pull/535 is another attempt to fix this in google-auth.

**Comment by pabloem** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
I think tests passed, but Jenkins hook is lagging to propagate the green signal. https://builds.apache.org/job/beam_PreCommit_Python_Commit/13221/consoleText
PostCommits also passed on previous commit, merging.

**Pull request merged**
