### PR TITLE
[BEAM-547] [BEAM-1730] Cleanup versions.py and root init has version access

### PR DESCRIPTION
**Pull request by sb2nov**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

R: @aaltay PTAL

### CODE REVIEW

**Comment by aaltay** [comment]
Do we need `version.py` after this change?
And can we remove https://github.com/apache/beam/blob/master/sdks/python/MANIFEST.in#L18

**Comment by sb2nov** [comment]
We still need versions.py as setup.py calls that script. I'll remove the manifest line

**Comment by sb2nov** [comment]
R: @aaltay PTAL

**Comment by aaltay** [comment]
LGTM. Thank you.

**Pull request closed without merging**
