### PR TITLE
[Cherry Pick #26243] Disable debezium xlang against samza

### LINKED ISSUE #26241: [Failing Test]: Samza XVR Test Failure on release-2.47.0 branch
### What happened?

The Samza cross-language validates runner test suite is failing on the release branch with the following error in the TestDebeziumIO_BasicRead test:

```
2023/04/12 17:19:07  (): java.lang.UnsupportedOperationException: The ActiveBundle does not have a registered bundle checkpoint handler.
2023/04/12 17:19:07 Job state: FAILED
    ptest.go:108: Failed to execute job: job go0testdebeziumio0basicread0521-jenkins-0412171850-7f7d8f6d_49001b62-7368-42c6-8be8-92ce416f7f7c failed
--- FAIL: TestDebeziumIO_BasicRead (44.53s)
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 0 (outage / failing precommit test impacting development)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [X] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by lostluck**
Fixes #26241

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
R: @jrmccluskey 

Same as the other PR, but cherry pick against release.

**Comment by jrmccluskey** [comment]
Looks like you picked up some other changes along the way there

**Comment by lostluck** [comment]
I'm having the worst luck with my branches lately.

**Comment by lostluck** [comment]
I had the merge target wrong. Fixed!

**Review by jrmccluskey — APPROVED** [review]

**Comment by lostluck** [comment]
Retest this please

**Comment by jrmccluskey** [comment]
retest this please

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Run Python_Integration PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow PreCommit

**Pull request merged**
