### PR TITLE
[BEAM-1752, BEAM-1582] Move checkpoint recovery tests to postcommit.

### PR DESCRIPTION
**Pull request by amitsela**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by amitsela** [comment]
retest this please

**Comment by amitsela** [comment]
Looks like a Maven central issue... try later.

**Comment by amitsela** [comment]
retest this please

**Comment by amitsela** [comment]
Run Spark RunnableOnService

**Comment by amitsela** [comment]
`Maven clean install` does not execute `UsesCheckpointRecovery` tests anymore, and they only run in `Spark Runner RunnableOnService` now.

**Comment by amitsela** [comment]
R: @aviemzur 
CC: @jkff

**Comment by aviemzur** [comment]
LGTM

**Pull request closed without merging**
