### PR TITLE
[Go SDK]: Infer field names from struct tags

### LINKED ISSUE #24465: [Task][Go SDK]: Utility function for inferring field names based on struct tags
### What needs to happen?

There is a [TODO](https://github.com/apache/beam/blob/v2.43.0/sdks/go/pkg/beam/io/bigqueryio/bigquery.go#L91) in the `bigqueryio.Read` transform to infer column names from type `t` instead of using `SELECT *` in the query.

I would like a function, e.g. in the util package, which infers field names from a given struct type and tag key, and returns them as a `[]string`.

It can be used in `bigqueryio.Read` to construct the select statement and for similar use cases, such as in `spannerio.Read` which currently uses its own unexported `columnsFromStruct` function.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by johannaojeling**
Implements a function `structx.InferFieldNames` which takes a struct type and a tag key, and returns a slice of field names based on this. Fixes #24465.

Updates `bigqueryio.Read` and `spannerio.Read` to make use of `structx.InferFieldNames` when constructing select statements.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johannaojeling** [comment]
R: @lostluck

**Review by lostluck — APPROVED** [review]
LGTM. Thank you for clearing out that TODO! 

Please note that neither of those two IOs are currently incredibly performant. They work, but they are unable to scale to multiple machines presently. I go into why a bit in a recent reply: https://github.com/apache/beam/pull/24364#issuecomment-1331378193

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by johannaojeling** [comment]
> LGTM. Thank you for clearing out that TODO!
> 
> Please note that neither of those two IOs are currently incredibly performant. They work, but they are unable to scale to multiple machines presently. I go into why a bit in a recent reply: [#24364 (comment)](https://github.com/apache/beam/pull/24364#issuecomment-1331378193)

Thanks for the reference! I was thinking of developing a new IO connector and will bear it in mind

**Pull request merged**
