### PR TITLE
Bump timeout for default transient expansion service

### LINKED ISSUE #25110: [Failing Test]: beam_PostCommit_XVR_Direct very flaky: PythonExternalTransformTest.pythonTransformWithDependencies fails
### What happened?

Test has always been very flaky due to 
```
java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout waiting for Python service startup after 16602 milliseconds.
	at org.apache.beam.sdk.extensions.python.PythonExternalTransform.expand(PythonExternalTransform.java:476)
```
This is because each call of `PythonExternalTransform.from()` will try to setup a transient expansion service. When lots of test running concurrently, timeout in one test is observed.

We may want to setup a service owned by the test class to decrease the load.

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #25110 

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run XVR_Direct PostCommit

**Comment by Abacn** [comment]
Run XVR_Direct PostCommit

**Comment by Abacn** [comment]
Run XVR_Direct PostCommit

**Comment by Abacn** [comment]
3 runs of previously flaky test all succeeded: https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct_PR/ (run 138,139,140), ready for review

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
