### PR TITLE
[BEAM-1938] Remove the requirement to visit PCollectionViews in Dataflow

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`.
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles

**Comment by kennknowles** [comment]
run dataflow validatesrunner

**Comment by kennknowles** [comment]
It was worth a try :-)

**Comment by kennknowles** [comment]
Have you run the `ValidatesRunner` suite manually? Please do, at least `ParDoTest`, if you haven't.

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
It looks like the dataflow tests succeeded before the build timed out, but let's do this again.

**Comment by tgroh** [comment]
retest this please

**Pull request closed without merging**
