### PR TITLE
[BEAM-1886] Remove TextIO override in Flink runner

### PR DESCRIPTION
**Pull request by JingsongLi**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by kennknowles** [comment]
Looks like ValidatesRunner passed, but you'll need to resolve conflicts.

**Comment by JingsongLi** [comment]
Resolved conflicts and rebased.

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by JingsongLi** [comment]
@aljoscha Can you run Flink test again? It passed after `mvn clean install` on my computer.

**Comment by aljoscha** [comment]
Run Flink ValidatesRunner

**Comment by JingsongLi** [comment]
Still can not update, @aljoscha can you help me check it?

**Comment by aljoscha** [comment]
I'll have a look.

**Comment by aljoscha** [comment]
@JingsongLi It seems we removed an exclude, by accident. I have the fix here: #2611

**Comment by aljoscha** [comment]
Thanks for fixing this, @JingsongLi 😃 

Now, on to the other PRs ...

**Pull request closed without merging**
