### PR TITLE
[release-2.41.0]Change _build import from setuptools to distutils

### PR DESCRIPTION
**Pull request by AnandInguva**
cherrypicks:  https://github.com/apache/beam/pull/22503
Fixes: https://github.com/apache/beam/issues/22516

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
R:  @kileys

**Comment by AnandInguva** [comment]
Run Python 3.9 PostCommit

**Review by tvalentyn — APPROVED** [review]

**Comment by tvalentyn** [comment]
Relevant tests passed on master, https://github.com/apache/beam/pull/22503#issuecomment-1199789078 . Current errors are not related, we should be able to merge this.

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python 3.9 PostCommit

**Comment by kileys** [comment]
Run Python PreCommit

**Comment by kileys** [comment]
Run Python 3.9 PostCommit

**Comment by kileys** [comment]
> Relevant tests passed on master, [#22503 (comment)](https://github.com/apache/beam/pull/22503#issuecomment-1199789078) . Current errors are not related, we should be able to merge this.

Merging

**Pull request merged**
