### PR TITLE
[BEAM-6539] Revert "Merge pull request #7316 [BEAM-6269] Cross-SDK transform expa…

### PR DESCRIPTION
**Pull request by youngoli**
…nsion protocol."

This reverts commit 26bd104f122986429ba5a8abd583b04a44a8edee, reversing
changes made to dcda09a8725d30467c4eb549985e3fe979208759.

This is causing issues in some portable Java PostCommits: https://issues.apache.org/jira/browse/BEAM-6539

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by youngoli** [comment]
Run Java PortabilityApi PostCommit

**Comment by youngoli** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by youngoli** [comment]
Run Java PreCommit

**Comment by youngoli** [comment]
Run Dataflow PortabilityApi ValidatesRunner

**Comment by youngoli** [comment]
R: @kennknowles @chamikaramj 

Since both of you reviewed the original PR. One PostCommit (Portable Dataflow ValidatesRunner) is still running as I'm writing this, but the other one (Portable Java PostCommit) seems to be fixed by this revert, so I'm expecting the unfinished one to also be fixed since it was exhibiting the same error.

**Comment by kennknowles** [comment]
LGTM. All the postcommits are green.

**Comment by chamikaramj** [comment]
Looks like all post-submits passed with this reverted. So I'll go ahead and submit this revert

cc: @robertwb

**Pull request merged**
