### PR TITLE
[BEAM-1265] Migrate DirectRunner evaluators to use Beam state API

### PR DESCRIPTION
**Pull request by charlesccychen**
This change depends on #3318.

### CODE REVIEW

**Comment by charlesccychen** [comment]
R: @aaltay

**Comment by charlesccychen** [comment]
Rebased to head, as #3318 has been merged.  Please take another look.

**Comment by aaltay** [comment]
LGTM. Thank you!

**Comment by aaltay** [comment]
retest this please

**Comment by charlesccychen** [comment]
Note that tests pass, though Jenkins is showing failures:

```
___________________________________ summary ____________________________________
  docs: commands succeeded
  lint: commands succeeded
  py27: commands succeeded
  py27cython: commands succeeded
  py27gcp: commands succeeded
  congratulations :)
```
(https://builds.apache.org/job/beam_PreCommit_Java_MavenInstall/12368/org.apache.beam$beam-sdks-python/consoleFull)

**Comment by aaltay** [comment]
Thank you, I will merge.

@jasonkuster any idea why jenkins is red, while tests actually passed?

**Pull request merged**
