### PR TITLE
Fix correct netty version

### LINKED ISSUE #27584: [Bug]: Netty dependency version diverged
### What happened?

In the latest Beam SDK release (2.49.0), Netty dependency version has diverged:

```
[INFO] |  +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.49.0:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.77.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.77.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.77.Final:compile
[INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.77.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.77.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.77.Final:compile
[INFO] |  |  +- io.grpc:grpc-netty:jar:1.55.1:compile
[INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.87.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-http:jar:4.1.87.Final:compile
[INFO] |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.87.Final:runtime
[INFO] |  |  |  |  \- io.netty:netty-codec-socks:jar:4.1.87.Final:runtime
```

This is due to we pinned netty_version for direct dependencies of Beam here:

https://github.com/apache/beam/blob/2c59a748b91a0988e0b8e332f18bd9db072c3e95/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L551

while google_cloud_platform_libraries_bom sets netty version

https://github.com/apache/beam/blob/2c59a748b91a0988e0b8e332f18bd9db072c3e95/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L705

Routine bump of google_cloud_platform_libraries_bom should also update netty_version

Manual update of google_cloud_platform_libraries_bom is error prone. In the long turn, we might consider use some tool to update (like dependabot)

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #27584

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @mutianf

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
Run Python_Runners PreCommit

**Comment by Abacn** [comment]
FlinkRequiresStableInputTest known flake, not relevant

**Review by mutianf — APPROVED** [review]

**Pull request merged**
