### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by chamikaramj**
You can run many tests automatically using release/src/main/scripts/mass_comment.py.

### CODE REVIEW

**Comment by chamikaramj** [comment]
Run Release Gradle Build

**Comment by chamikaramj** [comment]
Run Go PostCommit

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by chamikaramj** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by chamikaramj** [comment]
Run Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run Flink ValidatesRunner

**Comment by chamikaramj** [comment]
Run Samza ValidatesRunner

**Comment by chamikaramj** [comment]
Run Spark ValidatesRunner

**Comment by chamikaramj** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by chamikaramj** [comment]
Run Python Spark ValidatesRunner

**Comment by chamikaramj** [comment]
Run Python Dataflow ValidatesContainer

**Comment by chamikaramj** [comment]
Run Python Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run Python Flink ValidatesRunner

**Comment by chamikaramj** [comment]
Run Twister2 ValidatesRunner

**Comment by chamikaramj** [comment]
Run Python 3.6 PostCommit

**Comment by chamikaramj** [comment]
Run Python 3.7 PostCommit

**Comment by chamikaramj** [comment]
Run Python 3.8 PostCommit

**Comment by chamikaramj** [comment]
Run SQL PostCommit

**Comment by chamikaramj** [comment]
Run Go PreCommit

**Comment by chamikaramj** [comment]
Run Java PreCommit

**Comment by chamikaramj** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by chamikaramj** [comment]
Run JavaPortabilityApi PreCommit

**Comment by chamikaramj** [comment]
Run Portable_Python PreCommit

**Comment by chamikaramj** [comment]
Run PythonLint PreCommit

**Comment by chamikaramj** [comment]
Run Python PreCommit

**Comment by chamikaramj** [comment]
Run Python DockerBuild PreCommit

**Comment by chamikaramj** [comment]
Run XVR_Direct PostCommit

**Comment by chamikaramj** [comment]
Run XVR_Flink PostCommit

**Comment by chamikaramj** [comment]
Run XVR_Spark PostCommit

**Comment by chamikaramj** [comment]
Run PythonDocker PreCommit

**Comment by chamikaramj** [comment]
Run Flink ValidatesRunner

**Comment by chamikaramj** [comment]
Run Python 3.7 PostCommit

**Comment by chamikaramj** [comment]
Run Release Gradle Build

**Comment by chamikaramj** [comment]
Run XVR_Dataflow PostCommit

**Comment by chamikaramj** [comment]
Run Python Dataflow ValidatesRunner

**Comment by chamikaramj** [comment]
Run Python Dataflow ValidatesContainer

**Comment by chamikaramj** [comment]
Direct CrossLanguageValidatesRunner Tests failure is a known issue and not a blocker for Beam: https://issues.apache.org/jira/browse/BEAM-11699
Dataflow CrossLanguageValidatesRunner Tests failure is a known issue and not a blocker for Beam: https://issues.apache.org/jira/browse/BEAM-11779

**Comment by chamikaramj** [comment]
Run Python 3.7 PostCommit

**Comment by chamikaramj** [comment]
Run Release Gradle Build

**Comment by chamikaramj** [comment]
Run Java PostCommit

**Comment by chamikaramj** [comment]
Run Release Gradle Build

**Comment by lostluck** [comment]
The GoSDK failures are unrelated to the release. There's a Dataflow service issue WRT the post commit tests, and the pre-commit failures are xlang which are still under work (though I'm unable to replicate the failure locally with `go test`, so there's likely an issue WRT the jenkins'gradle set up...)

**Comment by chamikaramj** [comment]
Thanks for checking Rebo.

**Comment by tvalentyn** [comment]
Run Dataflow Python ValidatesRunner

**Comment by tvalentyn** [comment]
Run Pytohn Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Do you know what is the TFIDF failure in Java postcommits?

**Comment by chamikaramj** [comment]
It's a ongoing Dataflow service failure related to Runner v2 and shuffle
"Run Python Dataflow ValidatesRunner" passed for https://github.com/apache/beam/pull/13976

That's a temporary fix that will be rolled back in the mainline when the service issue is fixed.

**Comment by chamikaramj** [comment]
Run RAT PreCommit

**Pull request closed without merging**
