### PR TITLE
[BEAM-3602] Add gradle source set for generated gRPC code

### PR DESCRIPTION
**Pull request by bsidhom**
Add a source set for generated code.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand:
   - [x] What the pull request does
   - [x] Why it does it
   - [x] How it does it
   - [x] Why this approach
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lukecwik** [comment]
This isn't the best way to do this since your trying to add generated srcs to the non generated source set.
See: https://github.com/google/protobuf-gradle-plugin#intellij-idea

**Comment by bsidhom** [comment]
Hmm... It looks like I already had that enabled on import. This doesn't seem to fix it for me without adding the idea plugin. Is it preferable to add an IDE-specific plugin to get around this?

**Comment by bsidhom** [comment]
I also just tried to use the idea plugin. No dice. Not sure if I'm missing something.

**Comment by kennknowles** [comment]
BTW I'm working on the same thing to get a proper import to IntelliJ. I had success adding the directory both as a `sourceDir` and a `generatedSourceDir`: https://github.com/kennknowles/beam/commits/intellij

It seems to work OK but it is clear that one of our plugins is thrashing intellij by constantly dropping a lot of files somewhere that is causing reindex

**Comment by kennknowles** [comment]
... when I say "work OK" I mean that is solved that problem but by no means actually allows a clean import. I'm going to put slightly more effort into reproducing a "works the first time" import.

**Comment by bsidhom** [comment]
Is there a reason you're adding the generated sources to both `srcDirs` and `generatedSrcDirs`?

**Comment by bsidhom** [comment]
This has been superseded by #4583.

**Pull request closed without merging**
