### PR TITLE
[BEAM-2877] Add presubmit for Go code

### PR DESCRIPTION
**Pull request by herohde**
* Minor Go fixes for typos, proto changes and beamctl structure
  * Ran the presubmit command manually and it passed

### CODE REVIEW

**Comment by herohde** [comment]
R: @kennknowles

**Comment by herohde** [comment]
CC: @tgroh

**Comment by kennknowles** [comment]
What are all the non-groovy changes about?

**Comment by kennknowles** [comment]
Well, I guess your initial description said it, but can you split them into different commits (`git reset HEAD~ && git add .test_infra && git commit -m 'jenkins msg' && git add -u sdks/go && git commit -m 'go msg'`)

**Comment by kennknowles** [comment]
run seed job

**Comment by herohde** [comment]
Thanks @kennknowles. PTAL

**Comment by kennknowles** [comment]
retest this please

**Comment by kennknowles** [comment]
Run Python PreCommit

**Pull request merged**
