### PR TITLE
[BEAM-2544] Fix flaky AvroIOTest

### PR DESCRIPTION
**Pull request by alex-filatov**
Source of the flakiness is a race in a "write then read" subset of tests. Test pipeline was constructed in a way that write and read operations were performed concurrently instead of sequentially.

### CODE REVIEW

**Comment by alex-filatov** [comment]
R: @reuvenlax @kennknowles

**Comment by jkff** [comment]
R: @jkff 

(will take a look tomorrow)

**Comment by kennknowles** [comment]
It seems you have acquired a conflict - can you rebase and resolve?

**Comment by kennknowles** [comment]
The change you've made seems mandatory, so LGTM. @jkff and @reuvenlax please comment if there is a reason not to go ahead here. (or maybe the conflict is someone else doing the same fix...)

**Comment by alex-filatov** [comment]
Rebased and resolved

**Comment by jkff** [comment]
retest this please

**Comment by jkff** [comment]
LGTM. Not sure how this ever worked :-| Will merge on green.

**Pull request closed without merging**
