### PR TITLE
[BEAM-2959] Fix proto enums to use "YYY_UNSPECIFIED" as the first declared enum.

### PR DESCRIPTION
**Pull request by lukecwik**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by lukecwik** [comment]
Pending Dataflow worker dance.

**Comment by lukecwik** [comment]
R: @kennknowles or @tgroh

**Comment by lukecwik** [comment]
It used to be that the generated code for proto2 in c++ didn't allow for the same enum name to exist within the same proto definition because all enums were siblings and not children of the declared enum types. Will need to double check this before accepting your suggestion.

**Comment by kennknowles** [comment]
If proto3 has the same issue, we need to rewrite all of our enums to prefix them. So it is harmless to follow the current pattern here.

**Comment by kennknowles** [comment]
It does look like protoc for C++ dumps enums into the parent namespace: https://developers.google.com/protocol-buffers/docs/cpptutorial#enums-and-nested-classes

The same is true for Python:https://developers.google.com/protocol-buffers/docs/pythontutorial#enums

For clarity, the overall you have here and the one that prefixes all our enums should be in separate commits.

**Comment by lukecwik** [comment]
Need to keep the prefix for unspecified so we don't have a name clash.

Will prefix the remaining in a separate PR.

**Pull request closed without merging**
