### PR TITLE
Pin debezium test container version

### LINKED ISSUE #32936: [Failing Test]: Python Post-Commits are Perma-Red with Debezium IO failure
### What happened?

The Python PostCommit suites for all Python versions is perma-red with the same failure: 

```
FAILED apache_beam/io/external/xlang_debeziumio_it_test.py::CrossLanguageDebeziumIOTest::test_xlang_debezium_read - docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=debezium%2Fexample-postgres: Not Found ("manifest for debezium/example-postgres:latest not found: manifest unknown: manifest unknown")
```

Looking further, the [Dockerhub page](https://hub.docker.com/r/debezium/example-postgres/tags) for the container shows that there isn't currently a container tagged with `latest`, which is the root cause of the issue.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by jrmccluskey**
Pins the `debezium/example-postgres` container to version `3.0.0.Final` as there currently isn't a `latest` tagged container and this is causing workflows to fail.

Fixes #32936

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
Run Python PostCommit

**Comment by jrmccluskey** [comment]
Run Python PostCommit

**Review by tvalentyn — APPROVED** [review]

**Comment by Abacn** [comment]
for TODO note, latest tag might not be back , see #3292

**Comment by jrmccluskey** [comment]
Going to use the better fix in #32926

**Pull request closed without merging**
