### PR TITLE
Fix sklearn requirement file in Py311

### LINKED ISSUE #27151: [Failing Test]:  Python3.11 PostCommit failing apache_beam.ml.inference.sklearn_inference_it_test.SklearnInference
### What happened?

Both test stucks at least since June 7th (probably since June 5):

 apache_beam.ml.inference.sklearn_inference_it_test.SklearnInference.test_sklearn_mnist_classification	1 hr 5 min	10
 apache_beam.ml.inference.sklearn_inference_it_test.SklearnInference.test_sklearn_regression	1 hr 17 min	10

Taking a look at the Dataflow log (jobId: `2023-06-16_05_05_25-7286307859109106446`), 

```
INFO 2023-06-16T12:09:19.730887275Z Processing /var/opt/google/staged/scikit-learn-1.0.2.tar.gz
INFO 2023-06-16T12:09:22.166825380Z Installing build dependencies: started
INFO 2023-06-16T12:09:23.035339729Z Installing build dependencies: finished with status 'error'
INFO 2023-06-16T12:09:23.042156426Z error: subprocess-exited-with-error
INFO 2023-06-16T12:09:23.042223673Z
INFO 2023-06-16T12:09:23.042229948Z × pip subprocess to install build dependencies did not run successfully.
INFO 2023-06-16T12:09:23.042236330Z │ exit code: 1
INFO 2023-06-16T12:09:23.042241542Z ╰─> [4 lines of output]
INFO 2023-06-16T12:09:23.042247838Z Looking in links: /var/opt/google/staged
INFO 2023-06-16T12:09:23.042253600Z Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_system != "AIX" and platform_python_implementation != "PyPy"' don't match your environment
INFO 2023-06-16T12:09:23.042275525Z ERROR: Could not find a version that satisfies the requirement setuptools<60.0 (from versions: none)
INFO 2023-06-16T12:09:23.042282185Z ERROR: No matching distribution found for setuptools<60.0
INFO 2023-06-16T12:09:23.042287557Z [end of output]
```

sklearn install fails due to cannot install `setuptools<60.0`

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #27151

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
PythonLint failure on master, not related to this PR

**Comment by Abacn** [comment]
```
13:19:23 [gw4] PASSED apache_beam/ml/inference/sklearn_inference_it_test.py::SklearnInference::test_sklearn_mnist_classification 
13:32:20 [gw4] FAILED apache_beam/ml/inference/sklearn_inference_it_test.py::SklearnInference::test_sklearn_regression 
```

now one test passes and one fails, possibly due to compatibility issue

**Comment by Abacn** [comment]
Run Python 3.11 PostCommit

**Comment by Abacn** [comment]
R: @AnandInguva

**Review by AnandInguva — APPROVED** [review]

**Comment by Abacn** [comment]
Involved test passed: https://ci-beam.apache.org/job/beam_PostCommit_Python311_PR/lastCompletedBuild/testReport/apache_beam.ml.inference.sklearn_inference_it_test/

`apache_beam.examples.complete.game.leader_board_it_test.LeaderBoardIT.test_leader_board_it` fail unrelated. Flaky test

**Pull request merged**
