### PR TITLE
Remove unnecessary try/catch

### PR DESCRIPTION
**Pull request by damondouglas**
This PR addresses #28080 by removing an unnecessary try/block. The code in question updates a watermark via a callback wherein a SpannerException is caught and logged via a warning. Nothing in the tried code throws a SpannerException. Alternatively, a IllegalStateException could have been caught or thrown. However, analyzing the code further didn't suggest any thrown Runtime related exceptions.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damondouglas** [comment]
assign set of reviewers

**Comment by nielm** [comment]
> Nothing in the tried code throws a SpannerException

I disagree with this - this updates a change stream watermark using a Spanner database transaction --this could throw a SpannerException (which is a RuntimeException as it is extended from [BaseServiceException](https://github.com/googleapis/sdk-platform-java/blob/main/java-core/google-cloud-core/src/main/java/com/google/cloud/BaseServiceException.java) ) for a variety of reasons - including network, GRPC, service or database instance failures

@thiagotnunes who wrote this code to confirm.

**Comment by damondouglas** [comment]
@nielm (cc: @thiagotnunes ) Thank you so much for your insight. This makes a lot of sense now. Could we throw the SpannerException instead of log warning it then?

**Comment by thiagotnunes** [comment]
The issue here is what happens if an exception is thrown from the bundle finalizer?

If there is an error we would like to continue the operation without retrying indefinitely or halting the pipeline. If we bubble up the exception, what will happen?

**Comment by thiagotnunes** [comment]
cc @nancyxu123 who is the owner of this code now

**Comment by nancyxu123** [comment]
> cc @nancyxu123 who is the owner of this code now

I agree with Thiago. This function could definitely throw an exception, i.e. DEADLINE_EXCEEDED exception, so we should not remove the try/catch block. It's also ok to log the errors instead of throwing them, since we are only updating the watermark on a best-effort basis, hence why we are doing it in the bundlefinalizer

**Comment by damondouglas** [comment]
Thank you everyone @thiagotnunes and @nancyxu123 for responding so quickly and your helpful insights. I'm going to go ahead and close this PR.

**Pull request closed without merging**
