### PR TITLE
Upgrade Dataflow worker

### PR DESCRIPTION
**Pull request by dhalperi**
R: @tgroh

### CODE REVIEW

**Comment by dhalperi** [comment]
Run Dataflow RunnableOnService

**Comment by tgroh** [comment]
LGTM pending green

**Comment by dhalperi** [comment]
retest this please

**Comment by dhalperi** [comment]
retest this please

**Comment by dhalperi** [comment]
Dataflow runnable on service passed, and the Maven clean install failed only after everything succeeded but uploading to coveralls failed (s3 outage?).

**Pull request merged**
