### PR TITLE
Deflaking tests for BQ row insertions. These tests were flaky due to …

### PR DESCRIPTION
**Pull request by pabloem**
…race conditions against expected results

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
r: @kennknowles - I've run this test over 100 times and observed no failures. I believe this is good to go.

**Comment by Abacn** [comment]
This Fixes #22743

**Comment by pabloem** [comment]
failed test is unrelated

**Review by kennknowles — APPROVED** [review]
Makes sense to deflake, but we probably also want to re-introduce with a few other executors that reflect real-world usage.

That said, testing how the IO interacts with a mock is not terrifically interesting. If there's a concurrency problem, we want to know it is real with respect to something like real BigQuery.

**Comment by pabloem** [comment]
I wouldn't say there's a concurrency problem. the only issue here is the way teh test works imo. we have plenty of integration and unit tests for this, so I don't feel very conflicted...

**Pull request merged**
