### PR TITLE
Fix pydoc rendering for annotated classes

### LINKED ISSUE #21555: Incomplete documentation rendering for classes decorated by deprecated or experimental
For example in [https://beam.apache.org/releases/pydoc/current/apache_beam.io.fileio.html](https://beam.apache.org/releases/pydoc/current/apache_beam.io.fileio.html) , there is a statement about "WriteToFiles", but there is not documentation of this class. Taking a glance at the source code, there are class docstring and constructor docstring as well.

Also in this module, the class docstring of MatchContinuously is rendered, but not its __init__.__doc__ . For classes not decorated by deprecated or experimental, the documentation generation looks fine.

 

The issue seems existing from very early versions (at least v2.14.0 where WriteToFiles is introduced)

Imported from Jira [BEAM-14401](https://issues.apache.org/jira/browse/BEAM-14401). Original Jira may contain additional context.
Reported by: yihu.

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #21555

* Do not assemble target class into a func which messes up doc generating

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Refactored in a way similar to pypi's [deprecated package](https://github.com/tantale/deprecated/blob/3cf4d16f3c252ae0186a0eaf67b6f531fca8108a/deprecated/classic.py#L159). This resolves missing constructor documentation in pydoc, for example, [in mangodbio](https://beam.apache.org/releases/pydoc/current/apache_beam.io.mongodbio.html#apache_beam.io.mongodbio.ReadFromMongoDB), [in GroupIntoBatches](https://beam.apache.org/releases/pydoc/current/apache_beam.transforms.util.html#apache_beam.transforms.util.GroupIntoBatches).

(Precommit fails on known flake `Gradle build daemon disappeared unexpectedly`. will rerun in revision.)

R: @johnjcasey

**Comment by Abacn** [comment]
Run Python PreCommit

**Review by johnjcasey — APPROVED** [review]
LGTM

**Comment by Abacn** [comment]
R: @tvalentyn

**Comment by Abacn** [comment]
> Thanks!
> 
> Out of scope, but it may be possible to also alter docstring (`__doc__`) when decorators are used, so that it is reflected in autogenerated sphinx docs, I think TF is doing this here: https://github.com/tensorflow/tensorflow/blob/e4dbcc5732be1914b5dad205c2b1eabc040aafc4/tensorflow/python/util/deprecation.py#L372

Thanks. Sounds good. Filed #22265

**Pull request merged**
