### PR TITLE
(No need to review) Testing google_cloud_bigtable 2.25.3 with Beam 2.49.0

### PR DESCRIPTION
**Pull request by burkedavison**
Do not merge.

Updating google_cloud_bigtable to 2.25.3 to test against Beam 2.49.0.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
retest this please

**Comment by burkedavison** [comment]
Error during `beam_PreCommit_Java`: "Setup Repository"
https://github.com/apache/beam/actions/runs/6813097594/job/18526908727
```
Prepare all required actions
Run ./.github/actions/rerun-job-action
Run URL=https://api.github.com/repos/apache/beam/pulls/29359/commits
Run URL="https://api.github.com/repos/apache/beam/commits/b1d35c6[44](https://github.com/apache/beam/actions/runs/6813097594/job/18526908727#step:5:46)5f797c4031437066c62a2fb702f8a4b/check-runs"
Run URL="https://api.github.com/repos/apache/beam/actions/runs?check_suite_id="
Run URL="https://api.github.com/repos/apache/beam/actions/runs/null/jobs"
jq: error (at <stdin>:4): Cannot iterate over null (null)
Error: Process completed with exit code 5.
```

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Hey @byronellis , could you trigger the Java PreCommits? I must not have permissions, as they're being skipped for me at the moment: https://github.com/apache/beam/actions?query=actor%3Aburkedavison

**Comment by byronellis** [comment]
I did, stuff is still pending I think

**Comment by byronellis** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
Second invocation: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/6341/

Two failures:
* [Replicated] [o.a.b.s.u.UnboundedScheduledExecutorServiceTest.testThreadsAreAddedOnlyAsNeededWithContention](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/6341/testReport/junit/org.apache.beam.sdk.util/UnboundedScheduledExecutorServiceTest/testThreadsAreAddedOnlyAsNeededWithContention/)
* [New] [org.apache.beam.sdk.io.FileIOTest.testMatchWatchForNewFiles](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/6341/testReport/junit/org.apache.beam.sdk.io/FileIOTest/testMatchWatchForNewFiles/)

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Extract file timestamp failed: got file timestamp == 0.
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:374)
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:342)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:321)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:398)
	at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:335)
	at org.apache.beam.sdk.io.FileIOTest.testMatchWatchForNewFiles(FileIOTest.java:363)
...
Caused by: java.lang.RuntimeException: Extract file timestamp failed: got file timestamp == 0.
	at org.apache.beam.sdk.io.FileIO$MatchAll$ExtractFilenameAndLastUpdateFn.apply(FileIO.java:752)
	at org.apache.beam.sdk.io.FileIO$MatchAll$ExtractFilenameAndLastUpdateFn.apply(FileIO.java:746)
	at org.apache.beam.sdk.transforms.Watch$WatchGrowthFn.lambda$new$b100bdc2$1(Watch.java:861)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.hash.AbstractHasher.putObject(AbstractHasher.java:118)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.hash.AbstractHashFunction.hashObject(AbstractHashFunction.java:33)
	at org.apache.beam.sdk.transforms.Watch$WatchGrowthFn.hash128(Watch.java:975)
	at org.apache.beam.sdk.transforms.Watch$WatchGrowthFn.computeNeverSeenBeforeResults(Watch.java:986)
	at org.apache.beam.sdk.transforms.Watch$WatchGrowthFn.process(Watch.java:913)
```
See [Standard Error section](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/6341/testReport/junit/org.apache.beam.sdk.io/FileIOTest/testMatchWatchForNewFiles/) for additional output

**Comment by burkedavison** [comment]
Run Java PreCommit

**Comment by burkedavison** [comment]
All tests passed on 3rd invocation w/o source change.

**Comment by burkedavison** [comment]
Run Java Postcommit

**Comment by burkedavison** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by burkedavison** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by burkedavison** [comment]
Run PostCommit_Java_DataflowV2

**Comment by burkedavison** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming

**Comment by burkedavison** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by burkedavison** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Pull request closed without merging**
