### PR TITLE
improvements to fanout

### PR DESCRIPTION
**Pull request by aaltay**
R: @katsiapis or @robertwb 

Fixes and re-reverts: https://github.com/apache/beam/pull/5781

### CODE REVIEW

**Comment by aaltay** [comment]
Run Python PostCommit

**Comment by katsiapis** [comment]
Thank you Ahmet, LGTM!

**Comment by aaltay** [comment]
@alanmyrvold @swegner Alan, Scott do you know why pre-commit tests are not running on this PR? I had a similar issues with the original PR (https://github.com/apache/beam/pull/5768) did not notice tests did not run and we ended up reverting it.

**Comment by aaltay** [comment]
Run Python PostCommit

**Comment by swegner** [comment]
@aaltay I see pre-commits running now. Note that we've seen some lag in Jenkins PR triggering lately. This came up on dev@ and @jbonofre [mentioned he would ping INFRA](https://lists.apache.org/thread.html/4359dff63e9c5821b7e24c4a5c21bf3be17ca4327066750b09a7791c@%3Cdev.beam.apache.org%3E). I'll see if there was any follow-up.

**Comment by aaltay** [comment]
Thank you @swegner.

**Pull request merged**
