### PR TITLE
update GCP cloud libraries BOM to 26.5.0

### PR DESCRIPTION
**Pull request by reuvenlax**

### CODE REVIEW

**Review by damccorm — APPROVED** [review]
LGTM - sorry about the open and close, hit close on accident 😅

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Comment by reuvenlax** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by reuvenlax** [comment]
Run Java PreCommit

**Pull request merged**
