### PR TITLE
[BEAM-10856] Support for NestedValueProvider for Python SDK

### PR DESCRIPTION
**Pull request by epicfaace**
Support for NestedValueProvider for Python SDK. I've also added more comments to the pydoc for value_provider classes. R: @pabloem 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
Thanks @epicfaace for implementing these! I will not be able to review them for a couple of weeks. I can review once I'm back, or I can help find a new reviewer. What do you prefer?
(tvalentyn, udim) would be good choices for reviewers if you'd like a review soon.

**Comment by epicfaace** [comment]
Thanks for the heads up @pabloem . @tvalentyn , would you be able to review?

**Comment by epicfaace** [comment]
By the way, how do you normally lint your code according to the Beam guidelines / PR checks? I couldn't find any guidance / a quick reference in the Beam development guide on how to do that.

**Comment by tvalentyn** [comment]
https://cwiki.apache.org/confluence/display/BEAM/Python+Tips has some autoformatter tips that can help.

**Comment by tvalentyn** [comment]
@epicfaace Curious, what use-case do you have in mind for this change?

**Comment by epicfaace** [comment]
> @epicfaace Curious, what use-case do you have in mind for this change?

I'm creating a Dataflow template in which I need to write to multiple different output tables, "[prefix]_a", "[prefix]_b", "[prefix]_c", etc. I'd like to be able to specify a single runtime parameter, "prefix", and derive the output table names from this parameter, rather than having to redundantly specify each table name as an input runtime parameter.

I noticed that [this page](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#using-nestedvalueprovider) said that the Apache Beam SDK for Python does not support NestedValueProvider, so I just implemented it in Python in a similar way to how the Java SDK does it.

**Comment by tvalentyn** [comment]
Ok. We actually consider ValueProvider's an anti-pattern now, prefer not to extend their scope, and recommend to use FlexTemplates instead, see: https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates. Could you give that a try? I do appreciate your effort to improve the SDK and documentation though!

CC: azurezyq@ who is an expert on Flex Templates.

**Comment by epicfaace** [comment]
Hmm, I did try using Flex Templates initially, but it took way too long -- maybe 7-8 minutes -- for the job to initialize, as I think it was installing apache-beam and other dependencies. I switched to using ValueProviders because I needed a quick turnaround time for the job (the job itself takes around 10 minutes, so a 7-8 minute additional startup time is not worth it for me).

**Comment by tvalentyn** [comment]
I see, I'd like @arvindram03 and @azurezyq chime in here on their recommendation. I think there are undergoing efforts to reduce the startup time, or perhaps there are some tips to reduce it?

**Comment by arvindram03** [comment]
Hi @epicfaace ,

We agree the startup time with flex template python jobs is an issue. We are are working towards reducing the overall startup time to 3-4 mins by end of this year.  We recommend using flex templates instead of classic ones purely for flexibility and also you can leverage more feature expansions in the near future.

One of the major objective of flex templates is to avoid using ValueProviders. So, further overloading them with new features is not aligned with the roadmap.

**Comment by epicfaace** [comment]
@arvindram03 , thanks for the update. To clarify, this PR only aims for feature parity with the Java SDK, which already supports NestedValueProvider -- I'm not "overloading them with new features".

Additionally, Flex Templates is still a Pre-GA Offering, and as you mentioned, requires some work for it to be as efficient as regular templates. For these reasons, I don't think they're really a viable alternative to traditional templates at the moment (of course, with additional improvements by the end of the year, it could be!)

**Comment by pabloem** [comment]
A user has written a feature that they would find useful, and that will not change the experience for other users (if anything, it should improve it). The feature looks correct, and similar to what we do in Java. If we reject the PR, we may push the user to run on a fork. Can we let this in? @tvalentyn 
Flex templates have numerous benefits that are not being undone or discounted by adding this improvement to traditional templates, so I don't see a great disadvantage to merge this.

**Comment by tvalentyn** [comment]
> A user has written a feature that they would find useful, and that will not change the experience for other users (if anything, it should improve it). The feature looks correct, and similar to what we do in Java. If we reject the PR, we may push the user to run on a fork. Can we let this in? @tvalentyn

I agree with this assessment, feel free to merge once tests pass.

**Comment by pabloem** [comment]
@epicfaace can you ensure PythonDocs and PythonLint checks pass?

**Comment by pabloem** [comment]
@epicfaace LMK if you can take a look at the lint issues

**Comment by aaltay** [comment]
What is the next step on this PR?

**Comment by pabloem** [comment]
@epicfaace there's a number of failing tests. (Python Docs and Lint) - can you fix those?

**Comment by nikie** [comment]
@epicfaace @pabloem 
I have open PR into @epicfaace 's branch to fix pylint errors.

**Comment by nikie** [comment]
@tvalentyn 
Another possible use case for `NestedValueProvider` is to fetch external secrets based on provided values from, for example, Vault.

**Comment by nikie** [comment]
@epicfaace  
I am not sure why the tests are still failing. 
Rebasing against current `master` might help.

Pylint runs fine locally after my docstrings fix. I have also tried building docs with `sdks/python/scripts/generate_pydoc.sh`.

**Comment by nikie** [comment]
@pabloem, Python Docs and Lint tests now succeed.

**Comment by epicfaace** [comment]
@pabloem I'm not quite sure why CI is still failing, it gives this error:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\beam\\beam\\sdks\\python\\target\\.tox\\py36-win\\tmp\\it-4m1c1oje2145793178144\\full\\fb91a47796-2145832985040-2145832986608-2145793178144'
```

Any ideas? Or is the CI just flaky?

**Comment by aaltay** [comment]
> BeamAssertException

This one looks like a test on the asserts.

The actual error (which is likely a flake) is:

logs: https://github.com/apache/beam/pull/12779/checks?check_run_id=1433935136

apache_beam\runners\interactive\recording_manager_test.py:75: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
apache_beam\runners\interactive\interactive_environment.py:118: in new_env
    _interactive_beam_env.cleanup()
apache_beam\runners\interactive\interactive_environment.py:272: in cleanup
    cache_manager.cleanup()
apache_beam\runners\interactive\caching\streaming_cache.py:391: in cleanup
    shutil.rmtree(self._cache_dir)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:500: in rmtree
    return _rmtree_unsafe(path, onerror)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:390: in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:395: in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

...

>                   os.unlink(fullname)
E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\beam\\beam\\sdks\\python\\target\\.tox\\py36-win\\tmp\\it-4m1c1oje2145793178144\\full\\fb91a47796-2145832985040-2145832986608-2145793178144'

Maybe clean should catch the error and not fail? Or try again?

@KevinGG - Could you check this error?

@pabloem @epicfaace - I believe you can ignore this error for the purposes of this PR.

**Comment by KevinGG** [comment]
> > BeamAssertException
> 
> This one looks like a test on the asserts.
> 
> The actual error (which is likely a flake) is:
> 
> logs: https://github.com/apache/beam/pull/12779/checks?check_run_id=1433935136
> 
> ```
> apache_beam\runners\interactive\recording_manager_test.py:75: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> apache_beam\runners\interactive\interactive_environment.py:118: in new_env
>     _interactive_beam_env.cleanup()
> apache_beam\runners\interactive\interactive_environment.py:272: in cleanup
>     cache_manager.cleanup()
> apache_beam\runners\interactive\caching\streaming_cache.py:391: in cleanup
>     shutil.rmtree(self._cache_dir)
> c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:500: in rmtree
>     return _rmtree_unsafe(path, onerror)
> c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:390: in _rmtree_unsafe
>     _rmtree_unsafe(fullname, onerror)
> c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:395: in _rmtree_unsafe
>     onerror(os.unlink, fullname, sys.exc_info())
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> ...
> 
> >                   os.unlink(fullname)
> E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\beam\\beam\\sdks\\python\\target\\.tox\\py36-win\\tmp\\it-4m1c1oje2145793178144\\full\\fb91a47796-2145832985040-2145832986608-2145793178144'
> ```
> 
> Maybe clean should catch the error and not fail? Or try again?
> 
> @KevinGG - Could you check this error?


The problem is windows specific. I tried on Mac OS, the `shutil.rmtree` works even if the file handler is still open:
Screen Shot 2020-11-23 at 5 11 51 PM
It's said that on windows, if a file is opened, even if in the same process deleting it (or its parent directory), you will see this error: https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is.

Potential breaking point is in the streaming cache where the `open` and `close` are explicitly invoked (where `with` is inappropriate to use):
Screen Shot 2020-11-23 at 5 44 53 PM
Is it possible that a `finish_bundle` would fail silently or not executed at all?

This probably does not happen that often, we can revisit this if it happens frequently and ignore this by specifying `shutil.rmtree(path, ignore_errors=True, onerror=...)` since it's just failing to clean up useless temp files.

**Comment by aaltay** [comment]
> > > BeamAssertException
> > 
> > 
> > This one looks like a test on the asserts.
> > The actual error (which is likely a flake) is:
> > logs: [#12779 (checks)](https://github.com/apache/beam/pull/12779/checks?check_run_id=1433935136)
> > ```
> > apache_beam\runners\interactive\recording_manager_test.py:75: 
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > apache_beam\runners\interactive\interactive_environment.py:118: in new_env
> >     _interactive_beam_env.cleanup()
> > apache_beam\runners\interactive\interactive_environment.py:272: in cleanup
> >     cache_manager.cleanup()
> > apache_beam\runners\interactive\caching\streaming_cache.py:391: in cleanup
> >     shutil.rmtree(self._cache_dir)
> > c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:500: in rmtree
> >     return _rmtree_unsafe(path, onerror)
> > c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:390: in _rmtree_unsafe
> >     _rmtree_unsafe(fullname, onerror)
> > c:\hostedtoolcache\windows\python\3.6.8\x64\lib\shutil.py:395: in _rmtree_unsafe
> >     onerror(os.unlink, fullname, sys.exc_info())
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > 
> > ...
> > 
> > >                   os.unlink(fullname)
> > E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\beam\\beam\\sdks\\python\\target\\.tox\\py36-win\\tmp\\it-4m1c1oje2145793178144\\full\\fb91a47796-2145832985040-2145832986608-2145793178144'
> > ```
> > 
> > 
> > Maybe clean should catch the error and not fail? Or try again?
> > @KevinGG - Could you check this error?
> 
> The problem is windows specific. I tried on Mac OS, the `shutil.rmtree` works even if the file handler is still open:
> Screen Shot 2020-11-23 at 5 11 51 PM
> It's said that on windows, if a file is opened, even if in the same process deleting it (or its parent directory), you will see this error: [stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is](https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is).
> 
> Potential breaking point is in the streaming cache where the `open` and `close` are explicitly invoked (where `with` is inappropriate to use):
> Screen Shot 2020-11-23 at 5 44 53 PM
> Is it possible that a `finish_bundle` would fail silently or not executed at all?
> 
> This probably does not happen that often, we can revisit this if it happens frequently and ignore this by specifying `shutil.rmtree(path, ignore_errors=True, onerror=...)` since it's just failing to clean up useless temp files.

Maybe file a JIRA and we can track how often this happens? I do not think people triage all failures so it is hard to tell how frequently this happens in pre commit tests.

**Comment by KevinGG** [comment]
> Maybe file a JIRA and we can track how often this happens? I do not think people triage all failures so it is hard to tell how frequently this happens in pre commit tests.

Filed BEAM-11339 for this.

**Comment by pabloem** [comment]
thank you @epicfaace !

**Pull request merged**
