### PR TITLE
[BEAM-1310] Jdbc IO module now can run ITs against spark & dataflow runners

### PR DESCRIPTION
**Pull request by ssisk**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [X] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [X] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [X] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [X] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

I have added some changes that will allow us to start running the JdbcIO ITs with spark & dataflow.

These 2 commits are deliberately separate since they're doing different things. I don't think it's worth separating out into different commits since both are moving towards the same goal of enabling JdbcIOIT to actually run in jenkins, and can be logically reviewed together.

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Just curious: what about the other runners (Apex and Flink) ?

**Comment by iemejia** [comment]
Isn't this quite similar to what the example integration tests do ?
https://github.com/apache/beam/blob/4a29131d3c0f490d01820e92e028ec07eaffe927/examples/java/pom.xml#L173-L173
In that case we shouldn't reinvent the wheel and use the existing profiles, no ?

**Comment by jbonofre** [comment]
Agree, and for me it's not really integration tests ;) It's just unit tests on different runners ;)

**Comment by iemejia** [comment]
Yes, anyway this is a valuable idea, would be to have this rule at the top level of the IOs, no ? So they execute the integration tests with all the runners, does this make sense ?

**Comment by jbonofre** [comment]
Oh yes, definitely. My point is just a question of naming ;)
A real integration test (as discussed on the mailing list) is running on an integrated/actual platform.

**Comment by iemejia** [comment]
:+1: JB
Other thing been discussed at this moment and co-related, the 'mis-use' of @Category annotations in IOs. I thought that we put this annotations, e.g. RunnableOnService to execute the tests in all the runners, but it does not seem to be the case.
https://github.com/apache/beam/pull/2077

**Comment by iemejia** [comment]
And I mention this in case we want to filter the tests that are executed in all the runners (for speed reason for example).

**Comment by ssisk** [comment]
Thanks for your comments.

You are quite right that this is very similar to what the example integration tests do. I spent a bunch of time trying to get it working the same way as the example ITs, but it's quite tricky. The problems are:
1.  the runners have a dependency on the IOs - kafka/pubsub in particular. This means you can't have the IO module depend on the runners (and especially not the parent IO)
2. Simultaneously, you have to have all the proper jars included in the classpath for dataflow & spark to be able to pick them up. 
3. You have to pass parameters to the integration test, but can't use beamTestPiplineOptions since if you run verify, it'll also run the unit tests, and those don't understand the pipelineoptions for the IOs.

Between all those issues, I couldn't immediately get an examples-like version of this to work. I really tried :)

As I mention in the commit message (but I'm realizing now, that isn't easily visible here), this is a temporary measure. The long term plan I'm thinking about is to have an aggregator module that depends on both the runner and the IOs, and run the tests there, but I'd like to get the Jdbc IT running so that jason can start having perfkit running and calling this IT. 

I'll update the comments in the file to reflect this.

**Comment by ssisk** [comment]
re: naming - we have to pick some sort of boundary for what's an IT and what's a unit test. These tests meet the criteria of IT as discussed in the draft testing IO doc - I haven't heard any objections there. If we'd like to discuss that, happy to discuss it on dev@, but I'd like to not block this check-in on that.  https://docs.google.com/document/d/153J9jPQhMCNi_eBzJfhAg-NprQ7vbf1jNVRgdqeEE8I/edit?usp=sharing

I see the discussion of @NeedsRunner - my understanding is that only applies to unit tests, not ITs. (I think I was earlier told to remove it from this test.)

also, cc @dhalperi on this conversation as a whole.

**Comment by jbonofre** [comment]
For the naming, when I read the doc, I see:
```
* Verify that the IO transform can connect to a real instance of the data store running on a different machine, including passing credentials
* Verify that the IO Transform can read/write a small amount of data to a real instance of the data store
```
In this sense, it's not really integration tests, but more unit tests (as we use the JDBC instance embedded and created by the tests).

Honestly, it's not a big deal at all. It's just that what we named IT here sounds UT to me ;)

**Comment by ssisk** [comment]
Hey JB! 

These tests actually do connect to a real postgres instance. You'll note in the comments at the top of the file that you have to pass in connection parameters to talk to a real postgres instance. 

I've got the k8 script checked in for setting up that instance, and I'm waiting to stand up the k8 cluster for the apache gcp project until I get this CR in.

**Comment by jbonofre** [comment]
OHHHH my bad. I missed that part. Fair enough. It looks good to me !

**Comment by ssisk** [comment]
retest this please (current build break caused by maven repo connection issue)

We ran into an issue where my previous changes were causing the IO ITs to *always* be run. So now, I've set up a profile so they will only be run when that profile is specified.

I've tested this locally with the same maven command that jenkins runs, so it should no longer run the IO ITs inappropriately.

**Comment by ssisk** [comment]
retest this please

**Comment by ssisk** [comment]
retest this please

jenkins failed again, but retrieving the travis log (https://s3.amazonaws.com/archive.travis-ci.org/jobs/205968196/log.txt) is timing out when I try to access it, so not sure on cause.

**Comment by ssisk** [comment]
retest this please

**Comment by ssisk** [comment]
retest this please

**Comment by ssisk** [comment]
R @davorbonaci

**Comment by ssisk** [comment]
hey @davorbonaci do you mind taking a look at this PR?

**Comment by jbonofre** [comment]
I'm on it @ssisk ! ;)

**Comment by ssisk** [comment]
Thanks JB! 

Does your previous LGTM still apply, or are you taking another look before merging?

**Comment by jbonofre** [comment]
Just take a new look and LGTM. I gonna merge. Thanks !

**Comment by jbonofre** [comment]
@ssisk by the way, I started to prepare IT on others IO (already started JMS, MQTT, ...).

**Comment by jbonofre** [comment]
Just for the record, don't forget to add the Jira id in the commit message.

I do it for you with `git commit --amend`.

Thanks !

**Pull request closed without merging**
