### PR TITLE
Update README examples to use the new io APIs

### PR DESCRIPTION
**Pull request by mariapython**
beam.Read(beam.io.TextFileSource(...))   -->   beam.io.ReadFromText(...)
beam.Write(beam.io.TextFileSink(...))        -->   beam.io.WriteToText(...)

### CODE REVIEW

**Comment by mariapython** [comment]
R: @chamikaramj

**Comment by chamikaramj** [comment]
LGTM

**Comment by chamikaramj** [comment]
Please create a JIRA and update the title of the PR.

**Comment by mariapython** [comment]
Done: BEAM-1238

@robertwb: Can you please merge this?

**Comment by robertwb** [comment]
Please close.

**Pull request closed without merging**
