### PR TITLE
[BEAM-1512] Optimize leaf transforms materialization

### PR DESCRIPTION
**Pull request by aviemzur**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by aviemzur** [comment]
R: @amitsela 
Cc: @staslev

**Comment by staslev** [comment]
That's quite elegant.

I guess the proof that it really works lies in the fact the tests have managed to pass but just out of curiosity, did you have a chance to give it a try in cluster mode?

**Comment by aviemzur** [comment]
@staslev Yeah, ran it on cluster as well, looks good!

**Comment by amitsela** [comment]
LGTM, merging.

**Pull request closed without merging**
