### PR TITLE
Code completion plugin: Add Java SDK Transform Completions (Hard Coded)

### PR DESCRIPTION
**Pull request by sultanalieva-s**
Can be merged only after #27093.
The following PR contains the following features:
1. Completion window pops up with Beam Transforms from Java SDK. The Transforms are stored as an array of strings.
2. Minor Modifications in tests.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by sultanalieva-s** [comment]
Could you please take a look, @pabloem ?

**Comment by sultanalieva-s** [comment]
https://github.com/apache/beam/assets/66662058/6345b344-41f9-4684-a476-70e3bc8cdfc9

**Comment by pabloem** [comment]
reopening hoping for a rebase that will run with the new tests that @sultanalieva-s developed...

**Comment by sultanalieva-s** [comment]
> reopening hoping for a rebase that will run with the new tests that @sultanalieva-s developed...

yeah, I was planning to do the same after the CI is in the main branch. thanks.

**Comment by pabloem** [comment]
LGTM!

**Pull request merged**
