### PR TITLE
[BEAM-7011] Update Beam SDKs to use the StandardSideInputType enums.

### PR DESCRIPTION
**Pull request by lukecwik**
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @lostluck 
CC: @CraigChambersG

**Comment by lostluck** [comment]
@lukecwik You'll need to clean up the go imports for this change to compile, as Go has strict include what you use semantics.

18:02:25 .gogradle/project_gopath/src/github.com/apache/beam/sdks/go/pkg/beam/runners/dataflow/dataflowlib/fixup.go:19:2: imported and not used: "github.com/apache/beam/sdks/go/pkg/beam/core/runtime/graphx"
18:02:25 .gogradle/project_gopath/src/github.com/apache/beam/sdks/go/pkg/beam/runners/dataflow/dataflowlib/fixup.go:20:2: imported and not used: "github.com/apache/beam/sdks/go/pkg/beam/core/runtime/pipelinex"
18:02:25 .gogradle/project_gopath/src/github.com/apache/beam/sdks/go/pkg/beam/runners/dataflow/dataflowlib/fixup.go:21:2: imported and not used: "github.com/apache/beam/sdks/go/pkg/beam/core/util/protox"
18:02:25 .gogradle/project_gopath/src/github.com/apache/beam/sdks/go/pkg/beam/runners/dataflow/dataflowlib/fixup.go:23:2: imported and not used: "github.com/apache/beam/sdks/go/vendor/github.com/golang/protobuf/proto"

**Comment by lukecwik** [comment]
Thanks Robert

Is there tooling that does this automatically?

**Comment by lostluck** [comment]
There are, but most IDEs configured for Go should be automatically downloading and using them onsave.
The one that handles imports specifically, is [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)

**Comment by lukecwik** [comment]
R: @lostluck

**Comment by lostluck** [comment]
LGTM

**Comment by lostluck** [comment]
Note: I think the formatting changes in the go code are from go version differences for whomever is running `go fmt`. I think many of these changed (and I updated in a PR) after I updated my local go to 1.12.
Either way, they're benign if a bit noisy, and not worth nit-ing over.

**Comment by lukecwik** [comment]
Yes, I use go 1.12 locally, didn't know that the fmt had changed.

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Comment by lukecwik** [comment]
Run Python PreCommit

**Comment by lukecwik** [comment]
Run Java PreCommit

**Pull request merged**
