### PR TITLE
Replace website Beam Summit banners with Beam College banners

### PR DESCRIPTION
**Pull request by jrmccluskey**
Adds the new Beam College website banners to the repo and changes the banners from the Beam Summit promotions to these. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by jrmccluskey** [comment]
Run Website_Stage_GCS PreCommit

**Comment by jrmccluskey** [comment]
Run Website_Stage_GCS PreCommit

**Comment by jrmccluskey** [comment]
CC: @damccorm still not getting jenkins to stage the website

**Comment by jrmccluskey** [comment]
Oh it's shutdown according to #28426 but not triggering here

**Comment by damccorm** [comment]
Ah, the github action isn't happy - https://github.com/apache/beam/actions/runs/6190081183 - put up https://github.com/apache/beam/pull/28458 to fix

**Review by damccorm — APPROVED** [review]
This LGTM, but I'd like to be able to visualize it and make sure its working as intended. Lets get https://github.com/apache/beam/pull/28458 merged, and then update this PR with the latest from master to trigger the precommit before merging.

**Comment by jrmccluskey** [comment]
Agreed

**Comment by damccorm** [comment]
That one is merged, so feel free to pull in the latest contents (should automatically trigger the PR at that point). If it looks good to you rendered feel free to merge

**Comment by jrmccluskey** [comment]
huh rebase didn't do what I wanted to there

**Comment by jrmccluskey** [comment]
I'm just gonna remake this one...

**Comment by damccorm** [comment]
Nothing to see here

**Pull request closed without merging**
