### PR TITLE
DoFn lifecycle JavaDoc update.

### PR DESCRIPTION
**Pull request by svetakvsundhar**
Fixes issue #24184 by stating the the DoFn lifecycle both (1) has teardown on a best effort and (2) can vary by number of DoFn instances based on runner. 

A comment-- I don't think it makes sense to link this page to the JavaDocs given that the JavaDocs all contain links to other JavaDocs, eg: https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/transforms/DoFn.html. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by svetakvsundhar** [comment]
R: @Abacn

**Review by Abacn — APPROVED** [review]
Thanks! LGTM

Just a note: some context about the number of DoFn in Dataflow runner: https://cloud.google.com/dataflow/docs/guides/troubleshoot-oom#dofn

**Comment by Abacn** [comment]
Test status not updated to GitHub UI. There is an error:
```
./website/www/site/content/en/documentation/programming-guide.md:1198:71: W201 Trailing whitespace
```

**Comment by svetakvsundhar** [comment]
ah sorry about that, didn't see it locally.

**Pull request merged**
