### PR TITLE
Change to commons-lang dependency to commons-lang3 to be consistent with Spark

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @aviemzur

**Comment by aviemzur** [comment]
LGTM. Need to make sure that if we change `commons-lang3` version in Beam parent in the future it will be done with care so that this doesn't break Spark in cluster mode.

**Comment by iemejia** [comment]
https://builds.apache.org/view/Beam/job/beam_PreCommit_Java_MavenInstall/10091/

**Comment by iemejia** [comment]
Build passed ok so self-merging it.

**Pull request closed without merging**
