### PR TITLE
[BEAM-5379] Add go modules

### PR DESCRIPTION
**Pull request by zachbadgett**
**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by zachbadgett** [comment]
My take on Go modules: keep GoGradle, disable all dependency tasks; go.mod and go.sum live in the base directory so all Go related jobs can function properly.

I'll add the license to go.mod but go.sum does not support comments: https://github.com/golang/go/blob/master/src/cmd/go/internal/modfetch/fetch.go#L326

Still a few things to do related to documentation, wanted to get buy in on the implementation first.

**Comment by zachbadgett** [comment]
Ran into some issues on CI with permissions and the fact a new gopath is created for each directory, I'll have a fix pushed up for it today.

**Comment by lostluck** [comment]
Thank you! It's very exciting someones jumping on this! It's perpetually been on my todo list, but I've always lacked the time to get the Gradle expertise.

If it's possible to disable the dependency resolution tasks, then I have no problem with this approach. I hadn't even considered that as an option.

As for the RAT check, we can add exclusions for go.mod & go.sum files in the root build.gradle file. Given they're generated, this shouldn't be problematic.
https://github.com/apache/beam/blob/master/build.gradle#L77

One thing I'd like to ensure is that the SDK is *not* marked at the same version as mainline beam at this time. We need to tag it sdks/go/pkg/beam+v0.<current beam minor> or similar at this time. And ideally we have two modules, one for the actual user package in sdks/go/pkg/beam and one for sdks/go
If only to make the sdks/go depending on the user package very explicit. It also makes it clear that sdks/go/test etc depend on a version of the user package (which we can then force set to a specific commit or similar for the jenkins runs)

Largely:
* The SDK is still experimental and being v0 is a good signal for that.
* v2 has additional implications around quality that the SDK isn't prepared for (just yet). It's not a v2+ project at this time.
* (minor) We wouldn't need to update all the imports to refer to v2 to be in proper module compatibility.

**Comment by lostluck** [comment]
Run Go PostCommit

**Comment by lostluck** [comment]
Running the Post Commit makes it look like there's a bit more baking to be done WRT the integration tests, but this approach is still promising! 
https://builds.apache.org/job/beam_PostCommit_Go_PR/58/console
It looks like the integration tests are doing something weird, causing some recursion...

**Comment by zachbadgett** [comment]
@lostluck I have fixes and optimizations I need to push up, however I'm waiting for https://github.com/apache/beam/pull/9200 so we can prevent the readonly files from causing Jenkins issues.

**Pull request closed without merging**
