### PR TITLE
[BEAM-3098] Upgrades gRPC and protobuf dependencies

### PR DESCRIPTION
**Pull request by chamikaramj**
WIP. Not ready for review.

**Please** add a meaningful description for your change here

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Spark
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by chamikaramj** [comment]
This is currently failing Spanner tests. I'll try to work with Spanner guys to see what the issue is. Otherwise we'll have to vendor gRPC and protobuf for google-cloud-platform after pom files are deleted.

**Comment by garrettjonesgoogle** [comment]
Failure:

```
/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Java_Commit/src/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java:155: error: cannot find symbol
    builder.setUserAgentPrefix(USER_AGENT_PREFIX + "/" + releaseInfo.getVersion());
           ^
  symbol:   method setUserAgentPrefix(String)
  location: variable builder of type Builder
```

This is caused by the following change in google-cloud-java:

https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2690

**Comment by nithinsujir** [comment]
@chamikaramj Can you point me to the spanner test failure logs?

**Comment by nithinsujir** [comment]
@chamikaramj Can you point me to the spanner test failure logs please?

**Comment by garrettjonesgoogle** [comment]
This PR is obsolete - the upgrades were completed in https://github.com/apache/beam/pull/5988 .

**Comment by chamikaramj** [comment]
Closing.

**Pull request closed without merging**
