### PR TITLE
Retrieve Environments from PTransforms

### PR DESCRIPTION
**Pull request by tgroh**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
PTransforms associated with an environment (perhaps because they contain
a UDF) must be able to vend that environment in order to run the
environment-specific code.

### CODE REVIEW

**Comment by tgroh** [comment]
+ @axelmagn

**Comment by kennknowles** [comment]
:lgtm: with some commentary

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java, line 105 at r1](https://reviewable.io:443/reviews/apache/beam/4469#-L3iNibk7znNUBdYir0o:-L3iNibk7znNUBdYir0p:b-viscwt) ([raw file](https://github.com/apache/beam/blob/346e872a319849d522bae5a1908666f6d5b288e2/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java#L105)):*
> ```Java
>   }
> 
>   private static String flattenExtractor(PTransform transform) {
> ```

Probably just return Optional and none here

---

*[runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/WindowingStrategyTranslation.java, line 213 at r1](https://reviewable.io:443/reviews/apache/beam/4469#-L3iOernRWaT9lra6iPt:-L3iOernRWaT9lra6iPu:bh8dr3s) ([raw file](https://github.com/apache/beam/blob/346e872a319849d522bae5a1908666f6d5b288e2/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/WindowingStrategyTranslation.java#L213)):*
> ```Java
>    */
>   public static SdkFunctionSpec toProto(WindowFn<?, ?> windowFn, SdkComponents components) {
>     // TODO: The environment may not be required for known WindowFns, but can always just be ignored
> ```

A runner is not _required_ to implement the known WindowFns, so you still need an environment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apache/beam/4469#-:-L3iOvOdS7zQJJMqaBr2:bt1e9ka)*

**Comment by tgroh** [comment]
retest this please

**Comment by tgroh** [comment]
retest this please

**Pull request merged**
