### PR TITLE
Adds a bound on pydantic to exclude incompatible versions in the compat test.

### PR DESCRIPTION
**Pull request by tvalentyn**
fixes: #30852 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by damccorm — COMMENTED** [review]
It looks like other suites are failing, do we need the same change for those? https://github.com/apache/beam/actions/runs/8562842465/job/23466866257?pr=30863

**Comment by tvalentyn** [comment]
Yes, we need to help dependency resolver to set correct constraints, taking a look. New error: 

```
4361 2024-04-05T00:36:50.9531130Z pip 24.0 from /runner/_work/beam/beam/sdks/python/test-suites/tox/py38/build/srcs/sdks/python/target/.tox-py38-TFHubEmbeddings-015/py38-TFHubEmbeddings-015/lib/python3.8/site-packages/pip (python 3.8)
4362 2024-04-05T00:36:51.0529237Z py38-TFHubEmbeddings-015: commands_pre[2]> pip check
4363 2024-04-05T00:36:52.5529107Z tensorflow 2.13.1 has requirement typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.11.0rc1.
4364 2024-04-05T00:36:52.5531012Z py38-TFHubEmbeddings-015: exit 1 (1.55 seconds) /runner/_work/beam/beam/sdks/python/test-suites/tox/py38/build/srcs/sdks/python> pip check pid=62176
```

**Review by damccorm — APPROVED** [review]
Thanks!

**Comment by Abacn** [comment]
Python Coverage PreCommit is fixed however https://github.com/apache/beam/actions/workflows/beam_PostCommit_Python_Dependency.yml?query=event%3Aschedule is still failing. Does the same fix applicable to there?

**Comment by tvalentyn** [comment]
sent https://github.com/apache/beam/pull/30907 , which might help.

**Pull request merged**
