### PR TITLE
[BEAM-8715] update avro - extract avro to it's own module [WIP] 

### PR DESCRIPTION
**Pull request by zeidoo**
As per https://github.com/apache/beam/pull/9779#issuecomment-684965186, I'm submitting this PR so that other contributors have an idea of the changes that need to be done and get some feedback from the community.

Updates to CHANGES.md will be done when we get a clearer picture of what these changes are.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace
--- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
Build python source distribution and wheels
Python tests
Java tests

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by TheNeuralBit — COMMENTED** [review]
Thanks a lot for doing this! This all looks reasonable to me. This is a big change we'll need to discuss on the dev list though, I'll start a thread over there with a link to this PR.

**Comment by zeidoo** [comment]
Per module breakdown of the high level changes.
!!! = someone should probably confirm this is alright.

!!! beam.sdks.java.extensions.avro: (New module)
- moved from core.coders: AvroCoder, AvroGenericCoder
- moved from core.io: AvroIO, AvroSchemaIOProvider, AvroSink, AvroSource, ConstantAvroDestination, DynamicAvroDestinations, GenericRecordWriteConverter, SerializableAvroCodecFactory
- moved from core.schemas: AvroByteBuddyUtils, AvroUtils, AvroRecordSchema
- moved from core.test: user.avsc, test.avsc, AvroCoderTest, AvroCoderTestPojo, AvroIOTest, AvroSourceTest, SerializableAvroCodecFactoryTest, AvroGenerators, AvroUtilsTest, AvroSchemaCoderTest, AvroSchemaTest

beam:
- settings.gradle -> include ref to avro module 

beam.examples.java:
- gradle dep on Avro module, needs Avro coder
- only imports changed

beam.examples.kotlin:
- only imports (1 instance) changed

beam.runners.core-construction-java:
- gradle dep on Avro module, needs AvroGenericCoder and AvroCoder (for tests only)
- !!! AvroGenericCoderRegistrar uses the ClassLoader to check if the AvroGenericCoder class can be loaded, otherwise DOES NOT try to load that class

beam.runners.google-cloud-dataflow-java:
- gradle dep on Avro module, needs AvroCoder and AvroReader
- only imports changed

beam.runners.spark:
- NO gradle dep on Avro module, depends on beam.runners.google-cloud-dataflow-java which depends on Avro
- only imports changed (in 1 test file, uses AvroIO)

beam.sdks.java.core:
- !!! DefaultCoderProvider is now public (previously private)
- !!! BlockBasedReader is now public (previously was protected)
- !!! BlockBasedReader.isAtSplitPoint() is now public (previously was protected)
- !!! CounterMarkCoder introduced, previously was serialized with AvroCoder
- !!! DefaultFilenamePolicy.constructName() is now public (previously private)
- !!! FileIO.getEmptyMatchTreatment() and FileIO.getWatchInterval are now public (previously private)
- !!! new MyValueACoder for CoderRegistryTest.MyValueA, previously using AvroCoder
- !!! DefaultCoderTest Avro parts of these tests moved into the new Avro module
- !!! TextIOWriteTest added a UserWriteTypeCoder for UserWriteType, previously using AvroCoder
- !!! TextIOWriteTest.testDynamicDefaultFilenamePolicy, UserWriteTypeCoder now registered on the pipeline, previously this wasn't needed 
- !!! SchemasTest Avro parts of these tests moved into the new Avro module
- !!! LatestTest, replaced AvroCoder usages with StringUtf8Coder

beam.sdks.java.extensions.sketching:
- gradle dep on Avro module, needs AvroCoder for tests

beam.sdk.extensions.sql:
- gradle dep on Avro module, needs AvroIO and AvroSchemaIOProvider

beam.sdks.java.io.file-based-io:
- NO gradle dep on Avro module, indirect dep needed for AvroCoder and AvroIO

beam.sdks.java.io.google-cloud-platform:
- gradle dep on Avro module, needs AvroSource, AvroCoder and AvroUtils
- copy from core.test: user.avsc

beam.sdks.java.io.hadoop-format:
- gradle dep on Avro module, needs AvroCoder for tests only

beam.sdks.java.io.kafka:
- gradle dep on Avro module, and added applyAvroNature(), needs AvroCoder
- moved from core.test: user.avsc

beam.sdks.java.io.parquet:
- gradle dep on Avro module, needs AvroUtils and AvroCoder

beam.sdks.java.io.snowflake:
- gradle dep on Avro module, and added applyAvroNature(), needs AvroCoder for tests only
- copy from core.test: user.avsc

beam.sdks.java.testing.expansion-service:
- gradle dep on Avro module, needs AvroCoder for tests only

beam.sdks.java.testing.nexmark:
- gradle dep on Avro module, needs AvroIO and AvroCoder

**Comment by piotr-szuberski** [comment]
@zeidoo @TheNeuralBit Any progress here? A lot has already been done in this PR.

 As I remember there was a discussion on the devlist. Has it been decided to drop the idea of moving Avro out of the Beam core to the extensions?

**Comment by zeidoo** [comment]
Hi,

There were a couple of ideas floating around but I don't think there was consensus.

You can find the last few messages [here](https://mail-archives.apache.org/mod_mbox/beam-dev/202010.mbox/%3cCA+ACpyKYpR3mG9PSP8SSrSaKMPZz1E1gJxBY2jC_UcXCP6dtuw@mail.gmail.com%3e) .

If there's a consensus, I'll be happy to implement it once I get my development machine back (I'm currently in the middle of a intercontinental move, kinda, sort of, thanks to the fine folks at Hong Kong immigration and their newfound mainland Chinese induced love for purging the city of westners -- my very old laptop can't handle dev tools).

**Comment by piotr-szuberski** [comment]
> There were a couple of ideas floating around but I don't think there was consensus.

It would be great if you could proceed with it - it seems to me that you've done a terrific job here!

> If there's a consensus, I'll be happy to implement it once I get my development machine back (I'm currently in the middle of a intercontinental move, kinda, sort of, thanks to the fine folks at Hong Kong immigration and their newfound mainland Chinese induced love for purging the city of westners -- my very old laptop can't handle dev tools).

Really sorry to hear that. Wish you good luck!

**Comment by TheNeuralBit** [comment]
> There were a couple of ideas floating around but I don't think there was consensus.

Based on that thread, I think the action should be to establish some continuous testing against avro 1.9. It looks like with the fix for BEAM-9144 users _can_ use Avro 1.9 but we don't have anything in place to prevent us from breaking it in the future.

**Comment by piotr-szuberski** [comment]
> Based on that thread, I think the action should be to establish some continuous testing against avro 1.9. It looks like with the fix for [BEAM-9144](https://issues.apache.org/jira/browse/BEAM-9144) users _can_ use Avro 1.9 but we don't have anything in place to prevent us from breaking it in the future.

So would it be sufficient for now to add version compatibility tests like was done to Hadoop recently?

**Comment by TheNeuralBit** [comment]
> So would it be sufficient for now to add version compatibility tests like was done to Hadoop recently?

Yep!

**Comment by zeidoo** [comment]
Hi everyone,

I finally got a machine I can develop on.

@TheNeuralBit could you point me to the direction of the Hadoop tests in question? I can try to write some for Avro.

Some other guidelines to get this merged in as soon as possible would be appreciated too.

> > Based on that thread, I think the action should be to establish some continuous testing against avro 1.9. It looks like with the fix for [BEAM-9144](https://issues.apache.org/jira/browse/BEAM-9144) users _can_ use Avro 1.9 but we don't have anything in place to prevent us from breaking it in the future.
> 
> So would it be sufficient for now to add version compatibility tests like was done to Hadoop recently?

**Comment by TheNeuralBit** [comment]
I think the consensus was that we won't actually need to move avro to it's own Beam module. Instead we'll just test Beam core with multiple version of Avro. So we may be better off abandoning this PR.

Piotr started [this thread](https://lists.apache.org/thread.html/r2739eb540ea2b8d8c50db71850361b8b1347df66e4357001b334987b%40%3Cdev.beam.apache.org%3E) about his efforts to add 1.9 tests and @iemejia reported a few hangups they ran into. 

I think the Hadoop tests Piotr mentioned were added in https://github.com/apache/beam/pull/13352

**Comment by iemejia** [comment]
Agree with @TheNeuralBit  the best (and simpler) procedure is to run tests (like the ones Piotr did for Hadoop) with more recent 'provided' versions of Avro to ensure that Beam's use of Avro is compatible.

**Comment by TheNeuralBit** [comment]
I'm going to go ahead and close this, but feel free to re-open if you think we should pursue something like this.

**Pull request closed without merging**
