### PR TITLE
[BEAM-5887] Rollforward "Fix classifier for unshaded tests"

### PR DESCRIPTION
**Pull request by kennknowles**
Rolling forward this fix, which we can test against postcommit without re-enabling parallel
builds.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
Seed job has re-disabled parallel builds for postcommits, so going to run them against just this fix. This fix also speeds things up for local dev, so has value on its own.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by kennknowles** [comment]
Also, notably #6864 only re-enable parallel builds for postcommit. That was an oversight on my part. If it had also re-enabled for precommit, it would likely have been caught there.

**Comment by kennknowles** [comment]
R: @adude3141 @swegner

**Comment by kennknowles** [comment]
OK, slightly more thinking and there's this: The failure was a unit test, not an integration test. It is run in both precommit and postcommit, but only postcommit failed. And only postcommit had enabled parallel builds. So I would guess that the classifier fix is OK.

**Comment by kennknowles** [comment]
The test that failed was using Mockito argument capture across threads, and explicitly unsupported practice. It seems extremely likely that it was the parallel build that caused that test to start failing. Just another data point in moving forwards with parallel build efforts.

**Comment by kennknowles** [comment]
Green including postcommit. Please take a look.

**Comment by adude3141** [comment]
LGTM

**Pull request merged**
