### PR TITLE
Revert "Replace more uses of `ClassLoadingStrategy.Default.INJECTION` (#23210)"

### PR DESCRIPTION
**Pull request by Abacn**
Investigate Java11/17 postcommit test failures

This reverts commit 2b6291250f9b57bc3ce5f8e9407d234a6c89cd61.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run SQL_Java17 PreCommit

**Comment by Abacn** [comment]
Run SQL_Java11 PreCommit

**Comment by Abacn** [comment]
I am going to open this for now to get tests back green (and unblocks some other outstanding merging) CC: @cushon @lukecwik

**Comment by Abacn** [comment]
R: @aromanenko-dev

**Comment by Abacn** [comment]
Kafka_IO_Direct PreCommit known flake related to #25261

**Comment by lukecwik** [comment]
LGTM

**Review by lukecwik — APPROVED** [review]

**Comment by pabloem** [comment]
thanks @Abacn - indeed this looks like it's causing trouble : )

**Comment by pabloem** [comment]
Run Java_Kafka_IO_Direct PreCommit

**Comment by cushon** [comment]
I can reproduce with

```
JAVA_HOME=$JAVA8_HOME ./gradlew -PdisableSpotlessCheck=true -PdisableCheckStyle=true -PcompileAndRunTestsWithJava17 -PskipCheckerFramework -Pjava17Home=$JAVA17_HOME --max-workers=8 -Dorg.gradle.jvmargs=-Xms2g -Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.vfs.watch=false -Pdocker-pull-licenses clean  :sdks:java:extensions:sql:test
```

```
java.lang.IllegalArgumentException: org.apache.beam.sdk.coders.Coder$ByteBuddy$3j3EZPM9 must be defined in the same package as org.apache.beam.sdk.schemas.Schema
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1635)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6317)
	at org.apache.beam.sdk.coders.RowCoderGenerator.generate(RowCoderGenerator.java:176)
	at org.apache.beam.sdk.schemas.SchemaCoder.getDelegateCoder(SchemaCoder.java:117)
```

I think most of the failures are related to this change from the original PR: https://github.com/apache/beam/pull/23210#discussion_r1102152818

**Comment by Abacn** [comment]
Kafka_IO_Direct passed, merging for now

**Pull request merged**
