### PR TITLE
[BEAM=6857] Fix timermap test to not use TestStream

### PR DESCRIPTION
**Pull request by reuvenlax**
Since various runners exclude TestStream, this provides better test coverage.

### CODE REVIEW

**Comment by reuvenlax** [comment]
Run Dataflow ValidatesRunner

**Comment by reuvenlax** [comment]
run Flink ValidatesRunner

**Comment by reuvenlax** [comment]
Run Spark ValidatesRunner

**Comment by reuvenlax** [comment]
Run Samza ValidatesRunner

**Comment by reuvenlax** [comment]
Run Apex ValidatesRunner

**Comment by reuvenlax** [comment]
R: @dpmills

**Comment by dpmills** [comment]
LGTM

**Comment by reuvenlax** [comment]
Run JavaPortabilityApi PreCommit

**Pull request merged**
