### PR TITLE
[BEAM-1447] Remove need for Streaming Flag in Dataflow

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Autodetect if streaming is required, and if so run in Streaming.

I would love to have tests for this, but given the location it occurs,
I'm not sure how to do so effectively.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @kennknowles 
CC: @reuvenlax @davorbonaci

**Comment by kennknowles** [comment]
To be clear, it can still be forced if needed. Our own use case for that is getting test coverage for streaming even when all data is bounded. For users, I'm not sure what they'll use it for.

**Comment by tgroh** [comment]
retest this please

**Comment by kennknowles** [comment]
LGTM

**Pull request closed without merging**
