### PR TITLE
Revert "Merge master into go-sdk" (it actually merged the other way)

### PR DESCRIPTION
**Pull request by kennknowles**
Reverts apache/beam#4805

### CODE REVIEW

**Comment by kennknowles** [comment]
Actually this might cause some choas on the next merge from upstream.

**Comment by robertwb** [comment]
Is this one of those rare cases when it might make sense to do a force push/reset the head of our github repo?

**Comment by kennknowles** [comment]
Possibly. Things have happened since this merge and the synchronization might be a pain. Let's take it to the dev list.

**Comment by kennknowles** [comment]
Upon consideration I think rollback is the best plan.

**Comment by kennknowles** [comment]
Noting that this is green, and I will rebase since the quick pom fix has a conflict. Then I will build the re-revert PR to the `go-sdk` branch.

**Comment by lukecwik** [comment]
Thanks Ken

**Comment by lukecwik** [comment]
Note that #4818 contains the fix ups to the Go SDK branch.

**Comment by kennknowles** [comment]
I'll wait for green just as best practice. In the rebase to resolve conflicts, I simply had to re-delete `sdks/go/container/pom.xml` that had been modified to unblock development against `master`.

**Comment by kennknowles** [comment]
Please do not merge this - the dev list conversation is ongoing.

**Comment by lukecwik** [comment]
I had no intention to merge, just gave my stamp of approval so once the dev community discussion is resolved your unblocked to perform the merge.

**Pull request closed without merging**
