### PR TITLE
Add timeout to unit tests causing SickBay PostCommit timeout

### PR DESCRIPTION
**Pull request by Abacn**
**Please** add a meaningful description for your change here

Though being a sickbayed test suite, we still want to each test be exercised instead of stuck at some intermediate test and do not report anything.

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_Sickbay/

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Java Sickbay Tests

**Comment by Abacn** [comment]
Run Java Sickbay

**Comment by Abacn** [comment]
The timing out test is `org.apache.beam.sdk.io.AvroIOTest$NeedsRunnerTests.testContinuouslyWriteAndReadMultipleFilepatterns` for samza runner. Now the test suite no longer failing.

Ironically a couple of sickbayed tests actually succeeded.

**Comment by Abacn** [comment]
Run Java Sickbay

**Comment by Abacn** [comment]
R: @robertwb @damccorm

**Review by damccorm — APPROVED** [review]
This seems fine to me. I'm curious - how did you find this problem/do you pay attention to the sickbay? Its not really clear to me what the value of this suite is and I haven't seen anyone using it to this point

**Comment by Abacn** [comment]
> This seems fine to me. I'm curious - how did you find this problem/do you pay attention to the sickbay? Its not really clear to me what the value of this suite is and I haven't seen anyone using it to this point

Yeah this is not high priority. Just a small finding when inspect all permared postcommits. I am trying to do this like once a week or so.

My understanding is that this test suites have failing validate runner tests indicating certain runner does not support certain functionality. I am trying to work on a long standing issue (#20979 feature gaps between dataflow and portable runner) in the background and this sickbay test suite will be useful.

**Pull request merged**
