### PR TITLE
Update maven surefire and failsafe plugins to version 2.20

### PR DESCRIPTION
**Pull request by iemejia**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by iemejia** [comment]
R: @dhalperi

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
What's the rationale for this upgrade ?

**Comment by iemejia** [comment]
The rational is that for maven plugins we can benefit of the latest fixes with really low risk. Version 2.20 fixes many issues:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317927&version=12331679
And additionally supports colored output for users of the latest version of Maven.

**Comment by dhalperi** [comment]
LGTM, thanks!

**Pull request closed without merging**
