### PR TITLE
Updating generated files.

### PR DESCRIPTION
**Pull request by wcn3**
Fixing gen.go for latest proto revisions and regenerating all files.

### CODE REVIEW

**Comment by wcn3** [comment]
@herohde

**Comment by herohde** [comment]
Please run goimports/gofmt on these files.

**Comment by wcn3** [comment]
Done. Additionally, I fixed gen.go for the specializers to run gofmt so this doesn't happen again.

**Comment by herohde** [comment]
Thanks! There are other packages still in need of gofmt: stats, reflectx.

**Comment by wcn3** [comment]
Oh! I was only fixing directives in gen.go files, and the go::generate directives for those packages were elsewhere. All fixed up now! 👍

**Comment by wcn3** [comment]
@tgroh please merge

**Pull request merged**
