### PR TITLE
Beam 21465 add requires stable input to KafkaIO commit in finalize

### LINKED ISSUE #21465: Kafka commit offset drop data on failure for runners that have non-checkpointing shuffle
A user noticed that we commit Kafka offsets without any obvious checkpointing. We use a `Reshuffle.byRandomKey()` to cause Dataflow and the SparkRunner to checkpoint. But on runners with non-checkpointing shuffle, this risks data loss.

 

The modern solution is to use `{}@RequiresStableInput{`}. This is not perfectly/fully implemented across many runners, so we still need the explicit shuffle for now.

 

https://stackoverflow.com/questions/70785672/apache-beam-kafkaio-commit-offset-behaviour

Imported from Jira [BEAM-13715](https://issues.apache.org/jira/browse/BEAM-13715). Original Jira may contain additional context.
Reported by: kenn.

### PR DESCRIPTION
**Pull request by johnjcasey**
closes #21465

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
Run Python_PVR_Flink PreCommit

**Comment by kennknowles** [comment]
Just want to CC @xinyuiscool as I was checking the status of various runners and the Samza runner rejects pipelines with `@RequiresStableInput`. Other runners too, but I think DF and Flink are OK, and others it is no surprise.

**Comment by Abacn** [comment]
Apologize that missed this. @johnjcasey and @kennknowles If I understood correctly `Samza runner rejects pipelines with @RequiresStableInput. Other runners too, ...` means pipeline that involves KafkaCommitOffset can no longer runs on Samza (and some others) runner. Is this considered a regression or not?

**Comment by johnjcasey** [comment]
It would be, but this feature wouldn't work without a stable input to begin with

**Comment by Abacn** [comment]
> It would be, but this feature wouldn't work without a stable input to begin with

Said differently, the pipeline is not supposed to run on the runners that does not support `@RequiresStableInput` as it may cause data loss. If that is correct, could we add a note in CHANGES.md, either in bug fix or known issue section?

**Comment by johnjcasey** [comment]
It certainly seems like one. @kennknowles what is the general pattern here?

**Comment by chamikaramj** [comment]
Hmm, I think we use Reshuffle for checkpointing in other places as well so we might need to survey other I/Os for similar issues. For example,
https://github.com/apache/beam/blob/0ddaf041bd9a5bf0bad382557d0c165e55e96373/sdks/java/core/src/main/java/org/apache/beam/sdk/io/WriteFiles.java#L1045

Also, sometimes the downstream consumer might not be in the same transform or may be in a user transform, so this might end up not being enforceable.

**Comment by kennknowles** [comment]
Well, whether a runner can implement it correctly today or not, it does seem that this annotation accurately describes the requirements for correctness, so this change LGTM.

**Review by kennknowles — APPROVED** [review]

**Pull request merged**
