### PR TITLE
Refactor PR template to separate test types and label test variants

### PR DESCRIPTION
**Pull request by kennknowles**
Using some tricks I learned from https://plugins.jenkins.io/embeddable-build-status/

I'm manually editing this PR to use the new template, so you can enjoy it!

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @tysonjh

**Comment by kennknowles** [comment]
This refactor revealed quite a number of gaps and/or Jenkins jobs where the same job is expected to give status for a number of these cells. CC @lostluck and @tvalentyn who I think may have ideas there. Easy enough to copy/paste the same icon, but potentially useful to have separate health signals. (and of course we want all these signals to be actually tracked by other automation not just an HTML template)

**Comment by kennknowles** [comment]
My hope is for the "SDK/Transform PostCommit" tests that we can get separate icons for the various IO connectors or at least modules of connectors. All dependent on how easily we can automatically produce the Jenkins jobs we want, and also automatically summarize multiple Jenkins jobs so they don't get unwieldy.

**Comment by lostluck** [comment]
A nit on the PostCommit.
Go's PostCommit is the "Dataflow PostCommit" largely for historical
reasons.
It should be shifted to the Dataflow column as a result, with the ULR
column left blank.
 Go doesn't have a ULR PostCommit, it has one as a PreCommit, since the
surface is currently small & fast enough to run it as a precommit. That's
the "PreCommit_GoPortable" entry.
Go Precommits are currently correct in your sheet.

I assume the example targets are new? I love this idea! The Go examples are
not exercised regularly. I've made a note in the Big Go SDK Audit
spreadsheet I'm working on to add Go targets for the Examples (likely
leaning on the ULR more than anything).

**Comment by kennknowles** [comment]
Based on that description, I actually just removed it from the "ValidatesRunner" table. The same icon was already present in the "SDK PostCommits" table so there isn't lost signal there. And the "SDK PostCommits" table is sort of known to be a hodgepodge of "whatever someone wanted to run in PostCommit" so whenever there is an undifferentiated job that is the place for it.

Many examples already had jobs but they were just other icons in the PostCommit table. I'm gradually working on getting differentiated signals. (there are many ways to do this, like by gathering test status at a sub-Jenkins-job granularity, but this seems to be the best supported level of granularity)

**Comment by kennknowles** [comment]
Worth highlighting that while it used to be the case that `ValidatesRunner` purely tested the validity of the runner, now it is the best thing we have for testing SDK Harness implementations as well. So that is why having it per-language is still relevant, despite a single extensive suite written in a single language could suffice for establishing correctness of a portable runner.

**Comment by tvalentyn** [comment]
Seems like in this PR template dataflow python postcommits are attributed to Flink and there is one extra empty column at the end

**Comment by tvalentyn** [comment]
> Jenkins jobs where the same job is expected to give status for a number of these cells.

Could you give an example to understand what you mean?

**Comment by kennknowles** [comment]
> Seems like in this PR template dataflow python postcommits are attributed to Flink and there is one extra empty column at the end

Fixed. May as well browse the authoritative one at https://github.com/apache/beam/blob/9cf2451f5831831268297e50fa24234c09f2a6f3/.github/PULL_REQUEST_TEMPLATE.md

> > Jenkins jobs where the same job is expected to give status for a number of these cells.
> Could you give an example to understand what you mean?

The "Go PostCommit" I believe has "ValidatesRunner tests" as well as "Examples on Dataflow" tests, etc. Java postcommit used to have "Examples on Dataflow" and "IO integration tests on DirectRunner", etc. 

Thinking about the hierarchy of testing job > suite > class > method, the job is actually usually an implementation detail,  though the ability to configure them makes them able to give contradictory results for the same suite. The suite is probably the signal we want. They aren't perfectly aligned. I am just fixing up the PR template to reflect what we already have.

**Comment by lostluck** [comment]
Kenn, adding the Go PostCommit Badge to the Dataflow column where it belongs would be adding clarity to that badge being run against dataflow.

Arguably at this point, we should rename it to Dataflow anyway to match the Spark and Flink validations, and do away with the "generic" PostCommit for Go. Go being Portable Only means the speedy ULR variant we're using as a Portable Precommit means we're getting most signal from that anyway, and don't need a "generic" precommit target.  (renaming would not need to happen in this PR, but I do insist the badge be put in the right place now, since that's what's being discussed).

Per my ongoing auditting, the Go SDK needs to bolster what is covered for testing and examples, especially for various transforms, so if you insist on a badge being only in one place, the Dataflow column is more correct than the "post commit" column.

**Comment by kennknowles** [comment]
> Kenn, adding the Go PostCommit Badge to the Dataflow column where it belongs would be adding clarity to that badge being run against dataflow.

I don't currently have a cell that would match, do I? You mean the ValidatesRunner table?

> 
> Arguably at this point, we should rename it to Dataflow anyway to match the Spark and Flink validations, and do away with the "generic" PostCommit for Go. Go being Portable Only means the speedy ULR variant we're using as a Portable Precommit means we're getting most signal from that anyway, and don't need a "generic" precommit target. (renaming would not need to happen in this PR, but I do insist the badge be put in the right place now, since that's what's being discussed).

I'm very happy to do so, I'm just not entirely sure where you want it.

> 
> Per my ongoing auditting, the Go SDK needs to bolster what is covered for testing and examples, especially for various transforms, so if you insist on a badge being only in one place, the Dataflow column is more correct than the "post commit" column.

My take on "precommit" and "postcommit" is that they describe when a test should run and not a suite name. This has already caused actual confusion in the cases of PreCommit_*_Cron which is postcommit, and PostCommit_*_Phrase which is precommit.

So, yes, this change is just setting up a framework for getting signal that indicates _what_ is healthy or not.

**Comment by kennknowles** [comment]
One thing I'd like to get from the `ValidatesRunner` table is that it primarily validates the runner properly implements the basic primitives. Mostly, the different languages are redundant, except when it comes to specialized optimizations. The ULR "ValidatesRunner" column would ideally validate that the SDK harness properly implements the Fn API primitives. I don't think we can quite avoid having the full matrix, but it might be able to be more sparse without losing coverage, or at least be easy to quickly read off what the trouble is.

**Comment by lostluck** [comment]
I agree with all that! (getting better signal on Validates Runner Tests; make the PreCommit and PostCommit suites mean when they actually run rather than "A fast suite of tests, and a slow and heavy suite of tests", and avoiding the combinatorial complexity of running all the SDK tests against all the runners, etc).

At this point, the Go SDK is superseded in validating portability by the portable Python experience, and Java. The Go suites should be renamed away from being ValidatesRunners (VR), and largely validate that a smoke test of Go SDK functionality runs on each Runner properly. The Go SDK (and future SDKs) should not aim to replicate the full coverage of Runner behaviors, and instead focus on tests that test 1. User side PTransform code, such as for IOs and other Transform libraries, and 2. Pipelines that exercise behaviors on the SDK harness side of the worker (data & state management,  panes, splitting, checkpointing etc).

Some small set of these tests must end up being tested on properly distributed runners however, single loopback process runs, or 1 bundle at a time runs, are prone to cheating through local state. Such cheating invalidates the test's results. While we can always manually verify this kind of thing, I'd rather that part be validated as a closedbox for durability.

This is *not* how the Go SDK testing is currently set up however.

Right now, the basic precommit suite builds all the go code in the beam project (need to verify boot.go afterall),  has all the unit tests for the SDK, and which at most have small pipelines that run against the anemic Go Direct runner for light internal verification.

The post commit suite is a small set of integration tests, covering primitives, and some basic pipelines with a small set of the IOs (mostly Textio) and "built in" transforms. They run against each portable runner as post commits (Dataflow, Spark, Flink). The same suite is run against the Python ULR as a PreCommit, which catches most issues.

Ideally we'll expand that to cover more of the transforms and IOs, and examples (as separate suites, as you've got displayed in the table).

------

As to where the "Go PostCommit" target should go (this one I mean https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/ ), as I've insisted, it only runs against Dataflow. It should currently go into the Dataflow cell of the Validates Runner table, as that's the only table that refers to specific runners. I would like there to be an indication that the SDK is tested against dataflow, and that target is what currently does it.

The Go SDK only has one integration test suite that's used against the FnAPI compatible runners, so it's currently acceptable to have that same Dataflow target as the PostCommit badge too. Not ideal, but correct for now.

**Comment by kennknowles** [comment]
Works for me! Definitely its a problem of categorization. We don't have a "smoke tests on various runners" table so it is hard to find a home. I agree that cell is the best place for now, and we can always improve things more later. Done.

**Review by lostluck — APPROVED** [review]

**Comment by kennknowles** [comment]
Thanks for taking such a close look! Definitely made this better. It also made me feel very silly about it being the PR template instead of some more prominent dashboard...

**Pull request merged**
