### PR TITLE
[#24515] Ensure that portable Java pipelines on Dataflow are not able to opt out of runner v2.

### LINKED ISSUE #24515: [Task]: Remove the Dataflow JRH requiring all JRH users to use Runner V2 for 2.45.0+
### What needs to happen?

The Java Runner Harness (aka JRH) was an earlier implementation of the portability effort for Dataflow users powering Python, Go and Java portable pipelines.

Since then it has been superseded by the Runner V2 effort for Dataflow.

There are very few portable pipelines using the JRH on Dataflow and the purpose of this task is to require portable pipelines to use Runner V2.

Note that there will be no change to existing non-portable pipelines.

### Issue Priority

Priority: 2

### Issue Component

Component: runner-dataflow

### PR DESCRIPTION
**Pull request by lukecwik**
Towards #24515

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lukecwik** [comment]
Run PostCommit_Java_Dataflow

**Comment by lukecwik** [comment]
Run PostCommit_Java_DataflowV2

**Comment by lukecwik** [comment]
R: @Abacn

**Comment by lukecwik** [comment]
R: @bvolpato

**Review by Abacn — APPROVED** [review]
Thanks, this LGTM

**Review by bvolpato — COMMENTED** [review]
LGTM

**Pull request merged**
