### PR TITLE
[BEAM-4312] Enforce ErrorProne analysis in gearpump runner

### PR DESCRIPTION
**Pull request by iemejia**
R: @kennknowles 
CC: @manuzhang

### CODE REVIEW

**Comment by iemejia** [comment]
Run Gearpump ValidatesRunner

**Comment by kennknowles** [comment]
LGTM

**Comment by manuzhang** [comment]
Thanks. It seems there is a new primitive transform that Gearpump hasn't supported yet

```
java.lang.IllegalStateException: no translator registered for Impulse
	at org.apache.beam.runners.gearpump.translators.GearpumpPipelineTranslator.visitPrimitiveTransform(GearpumpPipelineTranslator.java:106)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:668)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:660)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:311)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:245)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:458)
```

**Comment by iemejia** [comment]
Run Gearpump ValidatesRunner

**Comment by iemejia** [comment]
Added the exclusion, thanks for the heads up @manuzhang and @kennknowles for the review.

**Pull request merged**
