### PR TITLE
[BEAM-27] Allow absolute timers

### PR DESCRIPTION
**Pull request by kennknowles**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [x] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [x] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [x] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

To set a timer at the very end of a window, which makes sense in event time, we need to have absolute timers in addition to relative timers.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @aljoscha care to take a look, since you are back from vacation?

The design choice would be whether to separate a `RelativeTimer` from an `AbsoluteTimer` and only allow relative timers for processing time since absolute timers are only very sensible with event time. I wonder what you think. My thought was that this might be too much abstraction overhead and who knows what someone might choose later.

**Comment by aljoscha** [comment]
Sure!

We could also have `EventTimeTimer`/`ProcessingTimeTimer` instead of `RelativeTimer`/`AbsoluteTimer` and get rid of the time domain in user space. I think your solution is good, though.

I think another question is whether to silently ignore absolute processing-time timers or throw an exception. I would be in favour of throwing an exception to make it clear to users what is happening.

**Comment by kennknowles** [comment]
I do kind of like the idea of getting rid of the `TimeDomain` in user space, especially since `SYNCHRONIZED_PROCESSING_TIME` is weird. For now I have not made that large a change. I am slightly worried their APIs and capabilities would diverge randomly, though that might also be OK.

**Comment by aljoscha** [comment]
Perfect! This looks good to merge. 👍

**Pull request merged**
