### PR TITLE
[BEAM-14231] Roll-forward #17190 with fixes for flake

### PR DESCRIPTION
**Pull request by TheNeuralBit**
GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by apilloud** [comment]
Failed test is test_dynamic_timer_clear_then_set_timer (BEAM-14367)

**Comment by apilloud** [comment]
Run Python PreCommit

**Review by apilloud — APPROVED** [review]
nit: could you add as assert to make sure we aren't caching on the key `None`?

**Comment by apilloud** [comment]
You should address my nit in a followup so this goes in the release.

**Comment by TheNeuralBit** [comment]
Thanks! It's a good nit, I'll make sure to follow-up on it but it may not make the release cut.

**Pull request merged**
