### PR TITLE
Add FlatMap(<builtin>) known issue to 2.40.0 blog

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Part of #22091

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
image

**Comment by pabloem** [comment]
lgtm!

**Comment by pabloem** [comment]
ugghhhhh sorry about that!

**Comment by TheNeuralBit** [comment]
retest this please

**Pull request merged**
