### PR TITLE
[BEAM-3457] Drop Go Maven PreCommit

### PR DESCRIPTION
**Pull request by herohde**
From #4814: For Go, the Gradle build passed 100% of the time while the Maven build passed 95% of the time in the past week. Both take ~4 mins to build.

### CODE REVIEW

**Comment by kennknowles** [comment]
I don't want to mess with the seed job right now just because of the large reverts going on (shouldn't affect them but just a little hesitant to touch anything that could delay them)

**Comment by kennknowles** [comment]
Actually on #4818 the RAT check in Maven caught something that the Gradle build did not. So we should have confirmation that RAT is catching everything in gradle. TBH I think that could be a separate Jenkins job since it is language agnostic and with no upstream or downstream steps.

This is a demonstration that the goal of precommit is not to succeed but to fail at the right times :-)

**Comment by herohde** [comment]
@kennknowles -- is there a blocker to merging? The Go PreCommit shouldn't do the RAT check, I assume.

**Comment by lukecwik** [comment]
The RAT run is fixed in #4830

**Comment by kennknowles** [comment]
There was no blocker from me - just wanted to confirm that we didn't have an important coverage gap, which Luke checked.

**Pull request merged**
