### PR TITLE
BEAM-2764: Set right range for min_doc_size and max_doc_size

### PR DESCRIPTION
**Pull request by CaoManhDat**
Change SolrIOTestUtils.MIN_DOC_SIZE and SolrIOTestUtils.MAX_DOC_SIZE to appropriate value, beasted the test ~2000 times.

### CODE REVIEW

**Comment by iemejia** [comment]
Retest this please

**Comment by CaoManhDat** [comment]
Retest this please

**Comment by tedyu** [comment]
lgtm

**Comment by iemejia** [comment]
Oh thanks for remembering me @tedyu I have forgotten to validate/merge this one.
R: @iemejia

**Comment by iemejia** [comment]
Thanks a lot for the fix @CaoManhDat and please forgive me for forgetting to merge this one before.

**Pull request closed without merging**
