### PR TITLE
[BEAM-440] add Create#empty

### PR DESCRIPTION
**Pull request by JasonMWhite**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:
- [x] Make sure the PR title is formatted like:
  `[BEAM-<Jira issue #>] Description of pull request`
- [x] Make sure tests pass via `mvn clean verify`. (Even better, enable
     Travis-CI on your fork and ensure the whole test matrix passes).
- [x] Replace `<Jira issue #>` in the title with the actual Jira issue
     number, if there is one.
- [x] If this contribution is large, please file an Apache
     [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---

### CODE REVIEW

**Comment by JasonMWhite** [comment]
This PR adds a new method, `Create#empty` to address [BEAM-440](https://issues.apache.org/jira/browse/BEAM-440). As I explained in the JIRA ticket, I don't think adding a `TypeDescriptor` would be very clean, since the coder is available from the pipeline coder registry, but the transform is created before the pipeline is made available.

This is my first PR to this repo, so feedback is definitely appreciated. @dhalperi you created the issue, mind taking a look?

**Comment by tgroh** [comment]
R: @tgroh (initially)

The TypeDescriptor could be an alternative field/in addition to the Coder, where you add an `Optional<TypeDescriptor<T>>` field to the `Values` PTransform. The Coder need not be available at transform creation time but at transform apply time, at which point you have access to the Pipeline.

Adding this method should also remove the ability to call `Create.of()` - as such, `Create.of(T...)` should be changed to `Create.of(T, T...)` to ensure that there is always at least one element or a Coder has been provided, and `Create.of(Iterable<T>)` should add a `checkArgument(!Iterables.isEmpty(elems))`

**Comment by tgroh** [comment]
Actually, on that last sentence, it's actually `getDefaultCreateCoder` should have that `checkArgument` - we can accept an empty elems Iterable if the user then specifies their coder; but we must have a coder by apply time.

**Comment by kennknowles** [comment]
R: @kennknowles

Is this still on your radar @JasonMWhite? Even though the issue is a bit deeper - as per my comment on the JIRA issue - we'd love to accept your contribution as a starting point. I think the main thing that would complete this PR would be to disable `Create.of()` (with no value) since that circumvents your new `Create.empty(Coder)`

**Pull request closed without merging**
