### PR TITLE
[DO NOT MERGE] Run all PostCommit and PreCommit Tests against Release Branch

### PR DESCRIPTION
**Pull request by tvalentyn**
You can run many tests automatically using release/src/main/scripts/mass_comment.py.

### CODE REVIEW

**Comment by tvalentyn** [comment]
Run Release Gradle Build

**Comment by tvalentyn** [comment]
Run Go PostCommit

**Comment by tvalentyn** [comment]
Run Java PostCommit

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by tvalentyn** [comment]
Run Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Samza ValidatesRunner

**Comment by tvalentyn** [comment]
Run Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Python Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Twister2 ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.8 PostCommit

**Comment by tvalentyn** [comment]
Run SQL PostCommit

**Comment by tvalentyn** [comment]
Run Go PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by tvalentyn** [comment]
Run JavaPortabilityApi PreCommit

**Comment by tvalentyn** [comment]
Run Portable_Python PreCommit

**Comment by tvalentyn** [comment]
Run PythonLint PreCommit

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python DockerBuild PreCommit

**Comment by tvalentyn** [comment]
Run XVR_Direct PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Flink PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark3 PostCommit

**Comment by tvalentyn** [comment]
Run Release Gradle Build

**Comment by tvalentyn** [comment]
Run Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Spark ValidatesRunner

**Comment by ibzib** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Run Release Gradle Build

**Comment by tvalentyn** [comment]
Run Go PostCommit

**Comment by tvalentyn** [comment]
Run Java PostCommit

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by tvalentyn** [comment]
Run Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Samza ValidatesRunner

**Comment by tvalentyn** [comment]
Run Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Python Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Twister2 ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.8 PostCommit

**Comment by tvalentyn** [comment]
Run SQL PostCommit

**Comment by tvalentyn** [comment]
Run Go PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by tvalentyn** [comment]
Run JavaPortabilityApi PreCommit

**Comment by tvalentyn** [comment]
Run Portable_Python PreCommit

**Comment by tvalentyn** [comment]
Run PythonLint PreCommit

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python DockerBuild PreCommit

**Comment by tvalentyn** [comment]
Run XVR_Direct PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Flink PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark3 PostCommit

**Comment by tvalentyn** [comment]
Run Release Gradle Build

**Comment by tvalentyn** [comment]
Run Go PostCommit

**Comment by tvalentyn** [comment]
Run Java PostCommit

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by tvalentyn** [comment]
Run Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Samza ValidatesRunner

**Comment by tvalentyn** [comment]
Run Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by tvalentyn** [comment]
Run Python Spark ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesContainer

**Comment by tvalentyn** [comment]
Run Python Dataflow ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python Flink ValidatesRunner

**Comment by tvalentyn** [comment]
Run Twister2 ValidatesRunner

**Comment by tvalentyn** [comment]
Run Python 3.6 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.7 PostCommit

**Comment by tvalentyn** [comment]
Run Python 3.8 PostCommit

**Comment by tvalentyn** [comment]
Run SQL PostCommit

**Comment by tvalentyn** [comment]
Run Go PreCommit

**Comment by tvalentyn** [comment]
Run Java PreCommit

**Comment by tvalentyn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by tvalentyn** [comment]
Run JavaPortabilityApi PreCommit

**Comment by tvalentyn** [comment]
Run Portable_Python PreCommit

**Comment by tvalentyn** [comment]
Run PythonLint PreCommit

**Comment by tvalentyn** [comment]
Run Python PreCommit

**Comment by tvalentyn** [comment]
Run Python DockerBuild PreCommit

**Comment by tvalentyn** [comment]
Run XVR_Direct PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Flink PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark PostCommit

**Comment by tvalentyn** [comment]
Run XVR_Spark3 PostCommit

**Comment by tvalentyn** [comment]
Run Python ReleaseCandidate

**Pull request closed without merging**
