### PR TITLE
[BEAM-6867] Fixing data race in DataflowSideInputReadCounter

### PR DESCRIPTION
**Pull request by pabloem**
r: @Ardagan

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by aaltay** [comment]
Could this be merged?

**Comment by pabloem** [comment]
I am holding this back a bit to try and repro the issue / test the fix. I will merge this by Wednesday.

**Comment by apilloud** [comment]
Ping. Its Wednesday.

**Comment by pabloem** [comment]
My apologies. I've bumped the Fix Version to 2.13.0. I wasnt able to repro the issue.

**Pull request merged**
