### PR TITLE
BEAM-13612: This will fix the NPE because of absence of the projectId

### PR DESCRIPTION
**Pull request by vishwajeetfr**
This addresses #21405 NullPointerException because of the projectId's absence picking up the default (or the one provided via BigQueryOptions) project id rather than failing with NPE
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by vishwajeetfr** [comment]
fixes #29409

**Comment by vishwajeetfr** [comment]
R: @slilichenko @damccorm

**Comment by johnjcasey** [comment]
Looks like a good change to me. But I agree, it looks like this change breaks a number of checks

**Comment by johnjcasey** [comment]
I now disagree with this change. It appears that all places where we query this value, we check if it's null first. if it is, we default to the .getProject value.

**Comment by johnjcasey** [comment]
I think the key is to update in the .getTable instead

**Comment by johnjcasey** [comment]
This has been resolved with #29471

**Pull request closed without merging**
