### PR TITLE
rebasing DSL_SQL branch from master

### PR DESCRIPTION
**Pull request by xumingming**
first time do this(rebase feature branch from master), not sure whether it is the right way. @jbonofre can you take a look at it?

### CODE REVIEW

**Comment by xumingming** [comment]
It build failed because previously referenced BEAM version `0.7.0-SNAPSHOT` could not be found. If I make the necessary code change, the code will conflict the `DSL_SQL` branch, because I already rebased from `master`, I cann't rebase from `DSL_SQL` again to resolve the conflict.. Need help here @jbonofre .

**Comment by XuMingmin** [comment]
@xumingming , currently DSL/SQL modules use parent version `0.7.0-SNAPSHOT`, while in `pom.xml` of SQL we declare as `0.6.0` explicitly.

As I know, no other modules use code of SQL part,(_correct me here if anything I miss_). You may follow the two steps to sync-up with latest main branch:
1. upgrade DSL/SQL module with parent version `2.1.0-SNAOSHOT`, and specify Beam libraries `2.0.0` in SQL   `pom.xml`; --There may be some code change to do the upgrade
2. then rebase from beam/master branch;

**Comment by xumingming** [comment]
then because of the rebase, the PR cann't be merge automatically, need to merge manually with `--force` option, right? @XuMingmin

**Comment by xumingming** [comment]
After 1) upgrade & make code change 2) rebase. The result branch will conflict with the DSL_SQL branch due to the rebase: https://github.com/apache/beam/pull/3253/conflicts

**Comment by XuMingmin** [comment]
I don't think so, you may need do it with two PRs.

**Comment by xumingming** [comment]
haha, that explains...thanks @XuMingmin

**Pull request closed without merging**
