### PR TITLE
Remove obsolete and deprecated bigquery native read.

### PR DESCRIPTION
**Pull request by robertwb**
Defers to builtin read with a warning rather than raising an exception.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by robertwb** [comment]
R: @abacn
CC: @pabloem

**Comment by Abacn** [comment]
Thanks! Is there an GitHub Issue for the deprecation? If not could we create one and refer to it in CHANGES?

**Comment by robertwb** [comment]
> Thanks! Is there an GitHub Issue for the deprecation? If not could we create one and refer to it in CHANGES?

Done.

**Comment by Abacn** [comment]
One thing I notice is that the removed `bigquery_tools.BigQueryReader` class is a documented one ([documentation](https://beam.apache.org/releases/pydoc/current/apache_beam.io.gcp.bigquery_tools.html#apache_beam.io.gcp.bigquery_tools.BigQueryReader)) and never marked as deprecated, although classes using it were marked as deprecated (`bigquery._BigQuerySource` and `bigquery.BigQueryReader`). `bigquery_tools.py` also had no doctoring warning the module was for internal usage only.

I would recommend we mark `bigquery_tools.BigQueryReader` class as deprecated for now, and remove it and its tests in a future version (after upcoming 2.43.0).

The changes in `bigquery.py` and its tests look good to me.

**Comment by robertwb** [comment]
OK, I've left BigQueryReader for now, though technically it's really an internal-only class. We'll remove it later. Its only public entrypoint is already marked as deprecated since 2.11.0. (It didn't have any self-contained unit tests, and it didn't seem worth refactoring the other tests at this point.)

**Comment by Abacn** [comment]
Thanks for clarifying that this is an internal-only class. In this case I agree it is good time to remove it now. And I think better remove both than removing tests and leave the class alone. The commit `bbf3b81` looks good to me.

**Comment by robertwb** [comment]
The failure at apache_beam.runners.portability.flink_runner_test.FlinkRunnerTestOptimized.test_assert_that looks irrelevent.

**Comment by robertwb** [comment]
Run Python_PVR_Flink PreCommit

**Comment by Abacn** [comment]
Hi robertwb@, I meant I understand now the original approach (also remove bigquery_tools.BigQueryReader) makes sense to me than my first comment. Sorry for confusion

**Review by Abacn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
