### PR TITLE
Update Guava version to match the libraries-bom 26.38.0

### PR DESCRIPTION
**Pull request by zhumin8**
Update Guava version to the one that matches 26.38.0. Other part of the Libraries BOM upgrade was done in https://github.com/apache/beam/pull/31158 already.

https://github.com/googleapis/java-cloud-bom/releases/tag/v26.38.0 has:

> These client libraries are built with the following Java libraries:
> - Guava: 33.1.0-jre

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by zhumin8** [comment]
error message from "PreCommit Java Pulsar IO Direct"
```
> Task :sdks:java:io:pulsar:test

org.apache.beam.sdk.io.pulsar.PulsarIOTest > testReadFromSimpleTopic FAILED
    org.apache.beam.sdk.Pipeline$PipelineExecutionException at PulsarIOTest.java:178
        Caused by: java.lang.IllegalArgumentException at Preconditions.java:445

10 tests completed, 1 failed
```

log for PreCommit Java:
```
* What went wrong:
Execution failed for task ':runners:java-fn-execution:test'.
> There were failing tests. See the report at: file:///runner/_work/beam/beam/runners/java-fn-execution/build/reports/tests/test/index.html
```

**Comment by suztomo** [comment]
Taking over

**Comment by suztomo** [comment]
Run Java Postcommit

**Comment by suztomo** [comment]
Run Java_PVR_Flink_Batch PreCommit

**Comment by suztomo** [comment]
Run Java Spark PortableValidatesRunner Batch

**Comment by suztomo** [comment]
Run PostCommit_Java_DataflowV2

**Comment by suztomo** [comment]
All checks have passed

**Pull request merged**
