### PR TITLE
[BEAM-2837] Updated grpc-google-pubsub-v1 dependency

### PR DESCRIPTION
**Pull request by mairbek**
Updated grpc-google-pubsub-v1 dependency.

R: @jkff

### CODE REVIEW

**Comment by robertwb** [comment]
Motivation?

**Comment by mairbek** [comment]
@robertwb to fix BEAM-2837. Cloud Spanner expects grpc-google-common-protos of version 0.1.8, otherwise fails on runtime.

**Comment by jkff** [comment]
Mairbek confirmed that a Dataflow pipeline reading and writing to pubsub works with this PR, but for extra safety I'm gonna run ValidatesRunner tests before merging.

**Comment by jkff** [comment]
Run Dataflow ValidatesRunner

**Pull request closed without merging**
