### PR TITLE
[BEAM-3608] Port shaded Guava to vendored Guava

### PR DESCRIPTION
**Pull request by kennknowles**
This PR replaces shaded private uses of Guava with vendored Guava. Instead of relocating and bundling in each jar we produce, Guava is relocated once and published, and everything depends on this artifact.

The process by which I produced this PR, since hand-review is not easy via GitHub (maybe OK via Reviewable.io):

 - global search and replace of `compile library.java.guava` with `shadow library.java.vendored_guava_20_0`
 - global search and replace of `com.google.common` imports to add the `org.apache.vendor.guava.v20_0.` prefix
 - look for compile errors and revert them manually
 - huge surprise that this was sufficient; yay!

Not all uses of Guava in our codebase are shaded private uses. Cassandra, Kinesis, Bigtable, and Calcite all use Guava on their essential public API surface.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @iemejia 

I didn't actually remove the shadow plugin to really speed up the build, but I confirmed that there's no Guava in the direct runner jar.

**Comment by kennknowles** [comment]
I stopped work after I saw most of the `needsRunnerTests` were on their way to passing. There's going to be some more to do. I didn't compile or test anything that wasn't part of that dependency chain.

**Comment by kennknowles** [comment]
OK, I went through and fixed up `compileJava`, then automatically sorted imports which fixes `checkstyleMain`, and `checkstyleTest` so this should be good. List of things with exceptions:

 - Kinesis (futures)
 - Cassandra (futures)
 - Bigtable (futures)
 - SQL (immutable list on Calcite's API surface)

**Comment by kennknowles** [comment]
And had to add some suppressions for errorprone issues that are not really issues.

**Comment by kennknowles** [comment]
The only failure was SQL's JDBC driver which checked how many jars were on the classpath, since it is supposed to be self-contained. I have switched it back to bundling Guava, since that is required.

**Comment by kennknowles** [comment]
Also R: @swegner or @aaltay who have messed with vendoring & shading. Anyone who feels up for it.

**Comment by kennknowles** [comment]
run java postcommit

**Comment by iemejia** [comment]
Ok, so we things we should probably do next:

- notify dev@ about the use of vendored guava imports
- update the contribution guide with info about this, and add how to deploy the vendored dependency source locally to improve ease of use from the IDE.

Two questions:

1. can we automatize the detection of guava imports and even break the build if
   so?  of course with the possibility to except some modules e.g. sql, cassandra
2. what is needed to remove the shadow plugin now? or at least exclude it for the
   modules that don't need anymore this kind of magic e.g. most IOs?

An interesting question for the future is what to do to detect security issues
with the vendored dependencies? Automatic dependency checkers probably won't
detect issues on our vendored dependencies. So something to think about.

**Comment by iemejia** [comment]
What I mean in (2) is that probably we should make exclude the default and make the packages who need still to shadow deps opt-in because they are less. WDYT @kennknowles @swegner ? (or something like that).

```Java
applyJavaNature(shadowClosure: {
  dependencies {
    exclude { true }
  }
})
```

**Comment by iemejia** [comment]
Ok, filled [BEAM-6437](https://issues.apache.org/jira/browse/BEAM-6437) and [BEAM-6438](https://issues.apache.org/jira/browse/BEAM-6438) to track the documentation part.

**Pull request merged**
