### PR TITLE
[BEAM-2441] move dsls/sql to sdks/java/extensions/sql

### PR DESCRIPTION
**Pull request by xumingming**
R: @XuMingmin @takidau

### CODE REVIEW

**Comment by takidau** [comment]
I'm seeing a lot of test failures when I run mvn verify on this PR:

[ERROR] Errors: 
[ERROR]   BeamSqlDslAggregationTest.testAggregationFunctionsWithBounded:75->runAggregationFunctions:145 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testAggregationFunctionsWithUnbounded:83->runAggregationFunctions:145 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testAggregationWithoutWindowWithBounded:41->runAggregationWithoutWindow:67 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testAggregationWithoutWindowWithUnbounded:49->runAggregationWithoutWindow:67 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testDistinctWithBounded:153->runDistinct:191 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testDistinctWithUnbounded:161->runDistinct:191 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testHopWindowWithBounded:247->runHopWindow:300 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testHopWindowWithUnbounded:255->runHopWindow:300 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testSessionWindowWithBounded:308->runSessionWindow:348 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testSessionWindowWithUnbounded:316->runSessionWindow:348 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testTumbleWindowWithBounded:199->runTumbleWindow:239 » UncheckedExecution
[ERROR]   BeamSqlDslAggregationTest.testTumbleWindowWithUnbounded:207->runTumbleWindow:239 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testCompositeFilterWithBounded:63->runCompositeFilter:84 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testCompositeFilterWithUnbounded:71->runCompositeFilter:84 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testNoReturnFilterWithBounded:92->runNoReturnFilter:112 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testNoReturnFilterWithUnbounded:100->runNoReturnFilter:112 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testSingleFilterWithBounded:36->runSingleFilter:55 » UncheckedExecution
[ERROR]   BeamSqlDslFilterTest.testSingleFilterWithUnbounded:44->runSingleFilter:55 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testLiteralFieldWithBounded:195->runLiteralField:221 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testLiteralFieldWithUnbounded:203->runLiteralField:221 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsInMultipleRowWithBounded:101->runPartialFieldsInMultipleRow:140 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsInMultipleRowWithUnbounded:109->runPartialFieldsInMultipleRow:140 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsInRowsWithBounded:148->runPartialFieldsInRows:187 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsInRowsWithUnbounded:156->runPartialFieldsInRows:187 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsWithBounded:66->runPartialFields:93 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testPartialFieldsWithUnbounded:74->runPartialFields:93 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testSelectAllWithBounded:39->runSelectAll:58 » UncheckedExecution
[ERROR]   BeamSqlDslProjectTest.testSelectAllWithUnbounded:47->runSelectAll:58 » UncheckedExecution
[ERROR]   BeamSqlDslUdfUdafTest.testUdaf:64 » UncheckedExecution java.lang.IllegalArgume...
[ERROR]   BeamSqlDslUdfUdafTest.testUdf:92 » UncheckedExecution java.lang.IllegalArgumen...
[ERROR]   BeamJoinRelUnboundedVsBoundedTest.testInnerJoin_boundedTableOnTheLeftSide:139 » UncheckedExecution
[ERROR]   BeamJoinRelUnboundedVsBoundedTest.testInnerJoin_unboundedTableOnTheLeftSide:113 » UncheckedExecution
[ERROR]   BeamJoinRelUnboundedVsBoundedTest.testLeftOuterJoin:167 » UncheckedExecution j...
[ERROR]   BeamJoinRelUnboundedVsBoundedTest.testRightOuterJoin:208 » UncheckedExecution ...
[ERROR]   BeamJoinRelUnboundedVsUnboundedTest.testFullOuterJoin:201 » UncheckedExecution
[ERROR]   BeamJoinRelUnboundedVsUnboundedTest.testInnerJoin:103 » UncheckedExecution jav...
[ERROR]   BeamJoinRelUnboundedVsUnboundedTest.testLeftOuterJoin:139 » UncheckedExecution
[ERROR]   BeamJoinRelUnboundedVsUnboundedTest.testRightOuterJoin:169 » UncheckedExecution
[INFO] 
[ERROR] Tests run: 229, Failures: 0, Errors: 38, Skipped: 0

Looks like I'm also seeing them on a clean apache/DSL_SQL branch, so probably not related to this PR, but I'd like to clear them up before merging anything further, particularly something as far reaching as this. Are you seeing these errors too?

**Comment by xumingming** [comment]
@takidau I think you need to do a full `mvn clean` in the ROOT directory of beam source code.

**Comment by takidau** [comment]
Didn't help. Talked w/ tgroh, looks like this is probably due to PR 3334. Filed BEAM-2707.

**Comment by xumingming** [comment]
Interesting. I did encountered the same issue, after a `mvn clean` in the root directory of beam source code(not `dsls/sql` folder or `sdks/java/extensions/sql`), the issue did go away. And also the jenkins build successfully.

**Comment by XuMingmin** [comment]
I build the PR locally as describe in BEAM-2707. 

LGTM as well.

**Comment by takidau** [comment]
Oddly enough, your instructions in BEAM-2707 (which I followed to the letter) did not work (I just checked my bash history to confirm). But a later (or additional?) mvn clean install seemed to do the trick. I don't know. Maven and I are not particularly good friends at this point. :-)

At any rate, merged. Thanks for the maven help!

**Pull request merged**
