### PR TITLE
[BEAM-5534] Revert "Merge pull request #6411 from huygaa11/revert-6311-twsit"

### PR DESCRIPTION
**Pull request by pabloem**
Bring WikipediaTopSessionsIT back

### CODE REVIEW

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
Run Java PostCommit

**Comment by pabloem** [comment]
r: @jasonkuster

**Comment by jasonkuster** [comment]
LGTM.

**Pull request merged**
