### PR TITLE
[BEAM-7629] Go SDK additional Validation for DoFns

### PR DESCRIPTION
**Pull request by youngoli**
This is the first draft of this CL for additional DoFn validation. It adds validation for Emits and SideInputs in StartBundle and FinishBundle.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python3_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) <br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by youngoli** [comment]
R: @lostluck 

Hoping I could get your feedback on what I have so far and help answering some questions.

1. Some of my tests currently fail because the following is expected in signatures for all DoFn methods: `side input parameters must follow main input parameter`. My understanding however is that when including side inputs in the StartBundle and FinishBundle methods (if ProcessElement has some) only the side inputs should be included, with no main inputs. So theoretically it should work, but right now all methods are treated as if they're ProcessElement. Is this correct?

2. I had trouble finding info for the expected inputs and outputs of the DoFn methods, and had to resort to checking other SDKs. Is there a place where that's documented for the Go SDK? If not, could you clarify for StartBundle, FinishBundle, Setup, and Teardown what parameters and return values they cab have (in addition to the side inputs and emits that I already account for)? Right now I make an assumption that Setup/Teardown shouldn't have any parameters based on the Java SDK, but couldn't find any concrete info for return values for any of the methods.

3. Should I worry about the Go SDK "generics" when it comes to the side input and emit validation? Is it even valid for a user to use generics to replace emits or side inputs there, and if so should I be checking that they're consistent? For this first draft I just ignored the possibility of generics.

**Comment by lostluck** [comment]
> R: @lostluck
> 
> Hoping I could get your feedback on what I have so far and help answering some questions.
> 
> 1. Some of my tests currently fail because the following is expected in signatures for all DoFn methods: `side input parameters must follow main input parameter`. My understanding however is that when including side inputs in the StartBundle and FinishBundle methods (if ProcessElement has some) only the side inputs should be included, with no main inputs. So theoretically it should work, but right now all methods are treated as if they're ProcessElement. Is this correct?
They shouldn't be treated exactly like ProcessElement, since the main inputs can never be populated in StartBundle and FinishBundle. The two should be treated the same as each other though.

https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/graph/fn.go#L134 is probably the root call where the error is being triggered.

The state machine is probably being a bit overzealous, and needs to be relaxed. It should be validating the order only not requiring the presence of anything. This PR is adding the necessary presence checking in a more aware place. This is my fault, sorry for the inconvenience.
  https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/funcx/fn.go#L311

> 2. I had trouble finding info for the expected inputs and outputs of the DoFn methods, and had to resort to checking other SDKs. Is there a place where that's documented for the Go SDK? If not, could you clarify for StartBundle, FinishBundle, Setup, and Teardown what parameters and return values they cab have (in addition to the side inputs and emits that I already account for)? Right now I make an assumption that Setup/Teardown shouldn't have any parameters based on the Java SDK, but couldn't find any concrete info for return values for any of the methods.

Re: Setup & Teardown: That's right they should only accept context.Context, and that's it.
Re: StartBundle & FinishBundle, should only be returning error I think? They almost certainly should *not* have main returns other than error.

> 3. Should I worry about the Go SDK "generics" when it comes to the side input and emit validation? Is it even valid for a user to use generics to replace emits or side inputs there, and if so should I be checking that they're consistent? For this first draft I just ignored the possibility of generics.

That's totally reasonable for this pass. I'm going to assume you mean the Universal Types ( beam.T, beam.X, beam.Y ... ). Universal types may only be used to replace a single type at present, not composite types (like, KVs, CoGBKs, or Iterators in any of their flavours.) When validating, all that matters is that they're used consistently (eg. a Beam.T emit maps to a Beam.T emit). They may not be substituted within a given DoFn between methods (eg. ProcessElement has a func(beam.T), then so too must Start and Finish).

**Comment by youngoli** [comment]
I made made the adjustments and rebased the branch just in case. It passed all unit tests locally, so I'm hoping it works now. I'm leaving the changes in a separate commit because they're somewhat large changes, so it might help to be able to review them separately.

**Comment by lostluck** [comment]
Run Go Postcommit

**Pull request merged**
