### PR TITLE
Run change point analysis on GHA

### PR DESCRIPTION
**Pull request by AnandInguva**
Service account needs to have permission to read/write from `apache-beam-testing` project's BigQuery.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by AnandInguva** [comment]
R: @damccorm We need to verify on if the service account has necessary permissions.

**Comment by damccorm** [comment]
> R: @damccorm We need to verify on if the service account has necessary permissions.

Right now, this won't work on GitHub Actions since we're using GitHub's pool of runners (ubuntu-latest), not our own self-hosted runners. We're planning to move to self-hosted this month, which should include adding service account access to those runners.

**Comment by damccorm** [comment]
Otherwise, this mostly looks good to me, though @tvalentyn may have thoughts since he reviewed the initial change.

**Comment by AnandInguva** [comment]
Yes, Valentyn is OOO as of now. I need to discuss one change with him. But wrt infra, I think once the service account is set, then this should be good for merging.

**Review by tvalentyn — APPROVED** [review]

**Pull request closed without merging**
