### PR TITLE
Downgrade container cryptography version to avoid yanked version

### PR DESCRIPTION
**Pull request by Abacn**
gradle task  `:sdks:python:container:xx:docker` now show warnings:

```
WARNING: The candidate selected for download or install is a yanked version: 'cryptography' candidate (version 38.0.2 at https://files.pythonhosted.org/packages/56/1e/2ffbbdddfe17308511cb2e06ac8c5aced9391dd5eea339e330a204edac34/cryptography-38.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (from https://pypi.org/simple/cryptography/) (requires-python:>=3.6))
16:10:52 Reason for being yanked: Regression in OpenSSL.
``` 
after #23587 in. Since we are close to another release cut. Better to get this in so we do not include. yanked version on released container.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @tvalentyn 
R: @AnandInguva

**Review by AnandInguva — APPROVED** [review]
I was getting this warning. Thanks for the quick fix.

**Comment by tvalentyn** [comment]
LGTM

**Comment by tvalentyn** [comment]
error is unrelated: 

```
 1654 > Task :sdks:java:fn-execution:compileJava                                      
 1655 warning: Memory constraints are impeding performance; please increase max heap size.
 1656 warning: Memory constraints are impeding performance; please increase max heap size.
 1657 error: warnings found and -Werror specified      
```

**Comment by tvalentyn** [comment]
Run PythonDocker PreCommit passed.

**Review by tvalentyn — APPROVED** [review]

**Pull request merged**
