### PR TITLE
[#24789] Spot fix fullvalue wrapping for SDF.

### PR DESCRIPTION
**Pull request by lostluck**
Discovered there's an inconsistency with how FullValue wrappings occur between SDF phases and DataSource decoding. Undiscovered due to fusion hiding the inconsistency.

Discovered while adding SDF handling to the replacement runner tracked in #24789.

Ideally, there would be no such distinction, but would entail a major consistency cleanup in the execution layer. For now, we wrap if needed, but cleaning up the inconsistency would improve SDK throughput.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by lostluck** [comment]
R:@damccorm  since he's around this week.

**Review by damccorm — APPROVED** [review]
LGTM

**Comment by damccorm** [comment]
@lostluck FYI, somehow this got merged back into your own branch, not master 😕

**Comment by damccorm** [comment]
image

**Comment by lostluck** [comment]
Dang it. I think I have a bad rebase in there. Thanks!

**Pull request merged**
