### PR TITLE
[BEAM-11227] Preparing vendored gRPC 1.36.0

### PR DESCRIPTION
**Pull request by suztomo**
This PR prepared the vendored gRPC 1.36.0 release. This PR does not use the artifact yet.

PR where I tested the vendored gRPC: https://github.com/apache/beam/pull/14028 

Command to confirm this branch generates the JAR file:
```
suztomo-macbookpro44% ./gradlew :vendor:grpc-1_36_0:shadowJar                                            
Configuration on demand is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
1 actionable task: 1 from cache
suztomo-macbookpro44% jar tvf vendor/grpc-1_36_0/build/libs/beam-vendor-grpc-1_36_0-0.1.jar  | grep '\.so$'
2628280 Fri Aug 21 11:19:38 EDT 2020 META-INF/native/liborg_apache_beam_vendor_grpc_v1p36p0_netty_tcnative_linux_x86_64.so
1933284 Fri Aug 21 11:19:38 EDT 2020 META-INF/native/liborg_apache_beam_vendor_grpc_v1p36p0_netty_tcnative_linux_aarch64.so

suztomo-macbookpro44% jar tf vendor/grpc-1_36_0/build/libs/beam-vendor-grpc-1_36_0-0.1.jar  |grep io/grpc/Context.class
org/apache/beam/vendor/grpc/v1p36p0/io/grpc/Context.class
suztomo-macbookpro44% jar tf vendor/grpc-1_36_0/build/libs/beam-vendor-grpc-1_36_0-0.1.jar  |grep netty/NettyClientHandler.class
org/apache/beam/vendor/grpc/v1p36p0/io/grpc/netty/NettyClientHandler.class
suztomo-macbookpro44% 
```

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/)<br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/) <br>[Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/) | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/)
Portable | --- | [Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | --- | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by kennknowles — APPROVED** [review]

**Comment by suztomo** [comment]
R: @kennknowles 

The checks passed! Would you merge this?

**Comment by kennknowles** [comment]
I tried:

```
./gradlew -p vendor/grpc-1_36_0/ -PisRelease -PvendoredDependenciesOnly publish
```

It failed with the following (I reformated for readability and removed irrelevant filesystem prefixes)

```
* What went wrong:
Execution failed for task ':vendor:grpc-1_36_0:validateVendoring'.
> ./vendor/grpc-1_36_0/build/libs/beam-vendor-grpc-1_36_0-0.1.jar exposed classes outside of org.apache.beam namespace: 
[
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/com/google/geo/type/Viewport$1.class,
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/com/google/geo/type/Viewport$Builder.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/com/google/geo/type/Viewport.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/com/google/geo/type/ViewportOrBuilder.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/com/google/geo/type/ViewportProto.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/Impl.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/Link.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/PerfMark.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/StringFunction.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/Tag.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/TaskCloseable.class, 
  ./vendor/grpc-1_36_0/build/tmp/expandedArchives/beam-vendor-grpc-1_36_0-0.1.jar_81fba4ad8fe8465e64883bca4a90d799/io/perfmark/package-info.class
]
```

**Comment by kennknowles** [comment]
(this was on current `github/master`)

**Comment by suztomo** [comment]
I didn't know the task. Let me check that later today.

**Comment by suztomo** [comment]
Created https://github.com/apache/beam/pull/14257 that includes documentation update to run the `check` task.

**Pull request merged**
