### PR TITLE
Fix sourceJar task dependencies

### LINKED ISSUE #28898: [Bug]: Nightly snapshot release is failing due to Gradle 8 upgrade
### What happened?

Around the same time that Gradle 8 got upgraded (#28756), the nightly snapshot has been failing on both Jenkins and GHA. For both, I'm seeing errors with many Gradle task configurations that go like:

```
Some problems were found with the configuration of task ':sdks:java:core:testSourcesJar' (type 'Jar').
- Gradle detected a problem with the following location: '/home/jenkins/jenkins-agent/26ff11f4/workspace/beam_Release_NightlySnapshot/src/sdks/java/core/build/generated-test-avro-java'.
 
Reason: Task ':sdks:java:core:testSourcesJar' uses this output of task ':sdks:java:core:generateTestAvroJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Possible solutions:
  1. Declare task ':sdks:java:core:generateTestAvroJava' as an input of ':sdks:java:core:testSourcesJar'.
  2. Declare an explicit dependency on ':sdks:java:core:generateTestAvroJava' from ':sdks:java:core:testSourcesJar' using Task#dependsOn.
  3. Declare an explicit dependency on ':sdks:java:core:generateTestAvroJava' from ':sdks:java:core:testSourcesJar' using Task#mustRunAfter.

For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```
Example: https://ci-beam.apache.org/job/beam_Release_NightlySnapshot/2041/console

Looks like Gradle 8 is more strict on declaring dependencies.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #28898

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Run Gradle Publish

**Comment by Abacn** [comment]
Run Gradle Publish

**Comment by Abacn** [comment]
R: @ahmedabu98

**Review by ahmedabu98 — APPROVED** [review]
Thanks for the quick turnaround! LGTM when tests pass

**Comment by Abacn** [comment]
Run Gradle Publish

**Comment by ahmedabu98** [comment]
Run Java_Pulsar_IO_Direct PreCommit

**Comment by ahmedabu98** [comment]
Run Portable_Python PreCommit

**Comment by ahmedabu98** [comment]
Run Python_PVR_Flink PreCommit

**Comment by Abacn** [comment]
Run Java PreCommit

**Pull request merged**
