### PR TITLE
[BEAM-1796] Make testShiftTimestampInvalid NeedsRunner instead of ROS

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.txt).

---
Currently broken in Apex. I'm investigating.

@jkff @tweise

### CODE REVIEW

**Comment by tgroh** [comment]
Example Break: https://builds.apache.org/job/beam_PostCommit_Java_RunnableOnService_Apex/842/changes

**Comment by tgroh** [comment]
Run Apex RunnableOnService

**Comment by jkff** [comment]
Can you clarify what effect you're intending to achieve by changing it from ROS to NR?

**Comment by tgroh** [comment]
Changing to RunnableOnService will cause it to not be picked up by the Apex RunnableOnService execution. That will stop it from breaking in Apex until the actual fix goes in.

**Comment by tgroh** [comment]
Specifically, the Apex RunnableOnService category will not execute any NeedsRunner tests, as it's not configured to pick them up; the test needs to be marked as NeedsRunner or ignored as the SDK doesn't have the proper classes to execute the test in the right context (with a Pipeline Runner)

**Comment by jkff** [comment]
LGTM modulo Apex ROS tests passing. Please also file a JIRA about this breakage and tag the PR with it.

**Comment by tgroh** [comment]
Filed https://issues.apache.org/jira/browse/BEAM-1796

**Pull request closed without merging**
