### PR TITLE
[BEAM-13289] Revert "Allow wildcards for java class lookup transform providers."

### PR DESCRIPTION
**Pull request by lukecwik**
Reverts apache/beam#15857

Causes infinite logging loop due to shading change.

### CODE REVIEW

**Comment by lukecwik** [comment]
R: @dpcollins-google @kileys 
CC: @robertwb @chamikaramj

**Review by dpcollins-google — APPROVED** [review]
As best I can tell, this is a pure rollback. Approved.

**Comment by lukecwik** [comment]
Java Precommit that was failing passed, merging.

**Comment by TheNeuralBit** [comment]
Thank you @lukecwik

**Pull request merged**
