### PR TITLE
Update build plugins

### PR DESCRIPTION
**Pull request by iemejia**
Update some of the gradle plugins. Noteworthy fixes:
- CVE in some of the plugins dependencies
- Spotless fixes for groovy/gradle formatting

R: @kennknowles @pabloem

### CODE REVIEW

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Java PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
Run Python PreCommit

**Comment by iemejia** [comment]
All green now, PTAL @kennknowles

**Comment by pabloem** [comment]
Thank you!

**Pull request merged**
