### PR TITLE
[BEAM-6080] Rollback PR/7049 for failing java post-commits

### PR DESCRIPTION
**Pull request by swegner**
PR/7049 is breaking java post-commit tests. Rolling back while we
investigate.

Revert "Merge pull request #7049 from angoenka/fix_artifact_hashing"

This reverts commit 9d356acc5e0b7cf4ec310992ea625d905ed21717, reversing
changes made to 67783b847593aa498a7030e229a1f6fa98740d57.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by swegner** [comment]
Run Java PostCommit

**Comment by swegner** [comment]
R: @angoenka @lostluck

**Comment by kennknowles** [comment]
LGTM

**Comment by angoenka** [comment]
The rollback breaks the Flink runner as the artifact staging stops working.
As artifact hash is an optional field we should validate it only when its present in metadata. Will put a PR for it in a bit.

**Comment by swegner** [comment]
@angoenka I see the [beam_PostCommit_Java_PVR_Flink](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/) suite is broken since this rollback. Do you know the quickest way to get back to a green state? Is an additional rollback needed?

Let me know if you need any help from me.

**Comment by angoenka** [comment]
https://github.com/apache/beam/pull/7071 should make it green

**Comment by angoenka** [comment]
The RC was 
1. We did a breaking change to the artifact proto some time back.
2. In enforced artifact hash field in code which was marked as optional in proto.
https://github.com/apache/beam/pull/7071 changes code to optionally check the hash if provided.

**Pull request merged**
