### PR TITLE
[BEAM-828] Set the Project of a Table Reference at Runtime

### PR DESCRIPTION
**Pull request by tgroh**
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

 - [ ] Make sure the PR title is formatted like:
   `[BEAM-<Jira issue #>] Description of pull request`
 - [ ] Make sure tests pass via `mvn clean verify`. (Even better, enable
       Travis-CI on your fork and ensure the whole test matrix passes).
 - [ ] Replace `<Jira issue #>` in the title with the actual Jira issue
       number, if there is one.
 - [ ] If this contribution is large, please file an Apache
       [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---
Instead of using the project at job submission time, use the project at
job execution time.

### CODE REVIEW

**Comment by tgroh** [comment]
R: @dhalperi @reuvenlax

**Comment by dhalperi** [comment]
Quick sanity check: new logs will not be run at an increased frequency, even if using per-window or data-dependent tables?

LGTM, self-merge at will

**Comment by tgroh** [comment]
No. This method is called exactly once in `splitIntoBundles`

**Comment by reuvenlax** [comment]
I'll copy this change into my PR, since it likely won't merge (the code has
been refactored into several different files)

**Pull request closed without merging**
