### PR TITLE
[BEAM-8442] Remove duplicate code for bundle register in Python SDK harness

### PR DESCRIPTION
**Pull request by sunjincheng121**
There are two methods for bundle register in Python SDK harness:
`SdkHarness._request_register` and `SdkWorker.register.` It should be unfied.

------------------------
Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/)
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python2/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python2_PVR_Flink_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Python35_VR_Flink/lastCompletedBuild/) | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/)
XLang | --- | --- | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | --- | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website
--- | --- | --- | --- | ---
Non-portable | [Build Status](https://builds.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/) 
Portable | --- | [Build Status](https://builds.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/) | --- | ---

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

### CODE REVIEW

**Comment by sunjincheng121** [comment]
Run Python PreCommit

**Comment by sunjincheng121** [comment]
R: @mxm

**Comment by sunjincheng121** [comment]
R: @aaltay

**Comment by sunjincheng121** [comment]
Thanks for the review @mxm :)

**Comment by ibzib** [comment]
I think this PR is causing [beam_PostCommit_XVR_Flink](https://builds.apache.org/job/beam_PostCommit_XVR_Flink/) to fail ([BEAM-8521](https://issues.apache.org/jira/browse/BEAM-8521)). (There are two test failures; this PR seems related to the failure in `test_java_expansion_portable_runner`.) Example stack trace:

```
11:13:37 File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 311, in get
11:13:37 self.fns[bundle_descriptor_id],11:13:37 KeyError: u'1-37'
```

I suspect the reason is that this PR changed the `register` instruction call from synchronous to asynchronous.

**Comment by mxm** [comment]
Thanks! This analysis is correct. The ProcessBundleDescriptor is assumed to be already in the cache before another task is executed. Thus, registration must be synchronous or we have a race condition after the initial registration.

**Comment by lukecwik** [comment]
Yes, there was a similar issue with Java in the past. It is best if registration is synchronous since then any ProcessBundleRequest can error out if the descriptor isn't available.

**Comment by aaltay** [comment]
For reference, this was reverted in https://github.com/apache/beam/pull/9956

**Comment by sunjincheng121** [comment]
@mxm @ibzib @lukecwik @aaltay Thanks a lot for your analysis. Really sorry that my commit breaks the post commit tests. I have investigated this issue and submitted a new PR #10004 which addressed this issue. It includes the following changes:

1) Update the client side implementation of Fn API to make sure registration is executed successfully before executing process_bundle. Personally I think that the client side implementation of Fn API should not assume that the implementation of registration in SDK harness is synchronous. The registration API itself is asynchronous and the client side implementation should check if the registration succeed. This will decouple the implementation dependency between the runner and the SDK harness.

2) Remove duplicate registration logic in the Python SDK harness. As you know, it changed the registration implementation of Python SDK harness to asynchronous.

Looking forward to your feedback. :)

Best,
Jincheng

**Pull request merged**
