### PR TITLE
[BEAM-4599] [SQL] add testArithmeticOperator

### PR DESCRIPTION
**Pull request by amaliujia**
Test arithmetic operator in SQL.

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go_GradleBuild/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza_Gradle/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_Gradle/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | --- | --- | --- | ---

### CODE REVIEW

**Comment by amaliujia** [comment]
to: @akedin @apilloud @vectorijk

**Comment by apilloud** [comment]
LGTM.

I remember we had a bunch of tests in the old style that checked the same thing. Are there any that are now redundant and can be deleted?

**Comment by amaliujia** [comment]
There are redundant tests in the old style. 

I'd like to keep the old tests now. As we become confident in the new tests' converge at operator level, we can remove the old tests in a batch.

**Comment by vectorijk** [comment]
Missing test for `Mod`? Otherwise, LGTM

**Comment by amaliujia** [comment]
Another thought is we can start to deprecate old style tests by merging those with this operator test.

I can work on that in a separate PR:  https://issues.apache.org/jira/browse/BEAM-4573

**Comment by amaliujia** [comment]
@vectorijk 

Yep, I forgot about mod. Thanks!

**Comment by amaliujia** [comment]
Updated this PR to merge old arithmetic operator integration test with new style test.

**Comment by amaliujia** [comment]
run java precommit

**Comment by amaliujia** [comment]
@XuMingmin could you review and/or merge this PR?

**Pull request merged**
