### PR TITLE
[BEAM-13647] Remove legacy Go Worker artifact name check

### LINKED ISSUE #21459: Go SDK FnApi environment version 9 should be compatible with Runner v2 artifact service
Go SDK FnApi environment version 9 should be compatible with Runner v2 artifact service. We need to test and verify whether Go SDK works well with Runner v2 artifact service before increasing the version number.

For 2.37 and 2.38 we'll keep both current and old versions as transitional code, but we should be able to comfortably pull out the old stuff in 2.39.

Imported from Jira [BEAM-13647](https://issues.apache.org/jira/browse/BEAM-13647). Original Jira may contain additional context.
Reported by: heejong.

### PR DESCRIPTION
**Pull request by damccorm**
In #16729, we moved to using the RoleUrn for the Go Worker Binary, with the intent of removing the legacy check after a few sprints. That should be safe now.

Fixes #21459 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Add a link to the appropriate issue in your description, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by damccorm** [comment]
R: @lostluck since you have the most context - anything I'm missing here that makes this unsafe?

**Comment by damccorm** [comment]
Run Go Flink ValidatesRunner

**Comment by damccorm** [comment]
Run Go Spark ValidatesRunner

**Comment by damccorm** [comment]
Run Go Samza ValidatesRunner

**Comment by lostluck** [comment]
Run Go Postcommit

**Comment by damccorm** [comment]
Run Go Postcommit

**Comment by damccorm** [comment]
Welp, looks like we can't just do this for free. Any idea what's going on here/why this isn't safe to remove? I'll close for now

**Pull request closed without merging**
