### PR TITLE
upgrade to gogradle plugin 0.11.2

### PR DESCRIPTION
**Pull request by adude3141**
update Gogradle plugin

This PR removes last blocking issue for upgrade to Gradle 5

------------------------

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

It will help us expedite review of your Pull Request if you tag someone (e.g. `@username`) to look at it.

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Apex | Dataflow | Flink | Gearpump | Samza | Spark
--- | --- | --- | --- | --- | --- | --- | ---
Go | [Build Status](https://builds.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | --- | --- | --- | --- | ---
Java | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Apex/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[Build Status](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Gearpump/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)
Python | [Build Status](https://builds.apache.org/job/beam_PostCommit_Python_Verify/lastCompletedBuild/) | --- | [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/) </br> [Build Status](https://builds.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [Build Status](https://builds.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/) | --- | --- | ---

### CODE REVIEW

**Comment by adude3141** [comment]
R: @swegner PTAL

**Comment by swegner** [comment]
CC: @lostluck

**Comment by lostluck** [comment]
LGTM. Thanks for doing this!
I'm more sad that gogradle hasn't updated to support Go Modules or go.mod files at least. 
A separate task would be to update to go version 1.11 on the jenkins machine.

**Comment by adude3141** [comment]
Thanks for looking into this.

@lostluck is that mod thingy this https://github.com/gogradle/gogradle/issues/267 issue?

Unfortunately I m more from java side, so I need to dig into that to get an idea how this could be tackled.

I think, there is still lots of work to be done to get gradle properly handling the go/python parts. Python is causing me more headaches, though.

@swegner Glad to help here. Will prepare PR for upgrade to gradle 5.2 after merge. Is this something which needs discussion on dev first?

**Comment by swegner** [comment]
> Is this something which needs discussion on dev first?

It wouldn't hurt to mention it, particularly if the upgrade will bring new features that could be useful in our build (Java 11 support perhaps?). Or if there are other implications developers will need to be aware of post-migration.

**Comment by lostluck** [comment]
> Thanks for looking into this.
> 
> @lostluck is that mod thingy this [gogradle/gogradle#267](https://github.com/gogradle/gogradle/issues/267) issue?
> 
> Unfortunately I m more from java side, so I need to dig into that to get an idea how this could be tackled.
> 
Please don't worry about the go tool version, and I (or another gopher) will handle it when the time comes. It's not a blocker. I was merely venting my concerns around gogradle in general.
That's the correct gogradle issue.  I've got that work to use go.mod for Beam tracked by https://issues.apache.org/jira/browse/BEAM-5379 
It's a non-urgent issue given the experimental status of the Go SDK, and versioning Go packages is tricky since it's relatively new but has go tool support.

**Comment by adude3141** [comment]
@lostluck Yes. of course. But I am a bit scared of trying to implement the build by shelling out. Although it seemingly works, it is really difficult - at least - to get it properly working with incremental build and build cache. With python we are doing that, and I do not have the feeling it is working very well... If Gogradle is here of better shape I do not know - I never looked into that.

**Comment by lostluck** [comment]
@adude3141 Agreed entirely. For Go, go tool handles build caching and incrementalism etc, and most recently, versioning. The trick is ensuring it plays well with Gradle & Jenkins, for infrastructures that require that route. That's a problem for a different PR though.

**Comment by adude3141** [comment]
@lostluck Sure. Sounds very interesting though, I definitely need to look into that.

Thanks for your input here. Really helpful.

**Pull request merged**
