### PR TITLE
[BEAM-3131] Updates Python datastore wordcount example to take a dataset parameter.

### PR DESCRIPTION
**Pull request by chamikaramj**
Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/BEAM/issues/) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by chamikaramj** [comment]
R: @aaltay

**Comment by aaltay** [comment]
Do we need to update the parameters in https://github.com/apache/beam/blob/239319b2a093cdb5c63375eddb5a91ac70172641/sdks/python/apache_beam/io/gcp/datastore/v1/datastoreio.py#L335 ?

**Comment by chamikaramj** [comment]
I don't think we need to update datastoreio module. project==dataset currently and we are consistent across Java and Python. This change simply allows this example to be used for cases where project where the job is executed is different from the project where the dataset is stored.

**Comment by aaltay** [comment]
The change LGTM.

Do we at least want to document that project argument can take a dataset? Or is it obvious for Datastore users that these two things are interchangeable?

**Comment by chamikaramj** [comment]
Thanks. Updated the datastoreio documentation to clarify that the project is the project to read from/write to.

**Pull request closed without merging**
